### ISSUE TITLE
Deploy OKD cluster using rhel base images

### ISSUE THREAD

**Issue by ahmad-hamade** [openshift/openshift-ansible#10007]
I'm not sure if this is the right place to answer this question but I have setup and deployed an OKD 3.9 cluster on a Subscribed and Licensed RHEL7.5 as below:

[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
oreg_url=registry.access.redhat.com/openshift3/ose-${component}:v3.9
openshift_deployment_type=origin
openshift_release=3.9
openshift_pkg_version=-3.9.0
openshift_image_tag=v3.9.41

All is working just fine. Can I continue using this environment or am I breaching licence conditions?

**Comment by michaelgugino** [comment]
This question is better answered by our support staff: https://www.redhat.com/en/services/support

OKD is Open Source Software and you're free to use it as you see fit, however, I don't know what conditions may affect your support agreement for the underlying RHEL operating system.
