### ISSUE TITLE
Inventory examples mostly without openshift_node_group_name definitions

### ISSUE THREAD

**Issue by lwindolf** [openshift/openshift-ansible#10005]
#### Description

The inventory examples in inventory/

hosts.example
hosts.glusterfs.external.example
hosts.glusterfs.mixed.example
hosts.glusterfs.native.example
hosts.glusterfs.registry-only.example
hosts.glusterfs.storage-and-registry.example
hosts.grafana.example
hosts.localhost
hosts.openstack

do not consistently have openshift_node_group_name definitions. As I understood the Ansible playbooks those are now mandatory since 3.10.

##### Version
```
Ansible 2.4.3.0
Openshift 3.10
git clone from github, using branch release-3.10

```

##### Steps To Reproduce

Check examples

##### Expected Results

Examples have working openshift_node_group_name definitions

**Comment by michaelgugino** [comment]
Yes, those example inventory files probably need some updating, but in any case should be used in tandem with the official documentation.

**Comment by kalexand-rh** [comment]
The [3.10 docs](https://docs.openshift.com/container-platform/3.10/install/example_inventories.html) include the `openshift_node_group_name` definitions.
