### ISSUE TITLE
Tag not found when pulling pod image

### ISSUE THREAD

**Issue by loshkovskyi** [openshift/openshift-ansible#1001]
Hello,

I deploy my testing OpenShift installations from [openshift-ansible-3.0.15-1](https://github.com/openshift/openshift-ansible/releases/tag/openshift-ansible-3.0.15-1). Today, I'm not able to create registry and router because of the following issue:

>
Nov 30 16:06:23 vm-node-01 origin-node[13893]: I1130 16:06:23.830351   13893 docker.go:159] Pulling image openshift/origin-pod:v1.1.0 without without credentials
Nov 30 16:06:26 vm-node-01 origin-node[13893]: E1130 16:06:26.266352   13893 manager.go:1867] Failed to create pod infra container: ErrImagePull; Skipping pod "router-west-1-deploy_default"

```
docker pull openshift/origin-pod:v1.1.0
Trying to pull repository docker.io/openshift/origin-pod ... not found
Tag v1.1.0 not found in repository docker.io/openshift/origin-pod
```

I follow official guides to create registries and routers, such as https://docs.openshift.org/latest/install_config/install/docker_registry.html

It looks to be a tag issue. Could you please advise why an outdated image is pulled?

**Comment by detiber** [comment]
@sdodson are you familiar with this at all? It looks like it's trying to pull version v1.1.0 and the tag for origin-pod is v1.1, is it a mismatch between the way the binary reports the version and the tagged images?

**Comment by sdodson** [comment]
Yeah, I built v1.1.0 but it should've been v1.1. I've had the v1.1.0 build deleted from copr.

@loshkovskyi on your hosts can you run the following

```
yum clean all
yum downgrade origin-\*1.1-0.git.0.a6bb7cd.el7
systemctl restart atomic-openshift-master
systemctl restart atomic-openshift-node
```

**Comment by loshkovskyi** [comment]
Sure, but it's not working:
```
[root@vm-node-01 ~]# rpm -qa|grep origin
tuned-profiles-origin-node-1.1.0-0.git.0.2a95a1a.el7.centos.x86_64
origin-1.1.0-0.git.0.2a95a1a.el7.centos.x86_64
origin-sdn-ovs-1.1.0-0.git.0.2a95a1a.el7.centos.x86_64
origin-clients-1.1.0-0.git.0.2a95a1a.el7.centos.x86_64
origin-node-1.1.0-0.git.0.2a95a1a.el7.centos.x86_64

[root@vm-node-01 ~]# yum downgrade origin-1.1.0-0.git.0.2a95a1a.el7.centos.x86_64
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.centos.webair.com
 * extras: mirror.dattobackup.com
 * updates: mirror.thelinuxfix.com
Nothing to do

[root@vm-node-01 ~]# yum install origin-pod.x86_64
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.centos.webair.com
 * extras: mirror.dattobackup.com
 * updates: mirror.thelinuxfix.com
Resolving Dependencies
--> Running transaction check
---> Package origin-pod.x86_64 0:1.1-0.git.0.a6bb7cd.el7.centos will be installed
--> Processing Dependency: origin = 1.1-0.git.0.a6bb7cd.el7.centos for package: origin-pod-1.1-0.git.0.a6bb7cd.el7.centos.x86_64
--> Finished Dependency Resolution
Error: Package: origin-pod-1.1-0.git.0.a6bb7cd.el7.centos.x86_64 (maxamillion-origin-next)
           Requires: origin = 1.1-0.git.0.a6bb7cd.el7.centos
           Installed: origin-1.1.0-0.git.0.2a95a1a.el7.centos.x86_64 (@maxamillion-origin-next)
               origin = 1.1.0-0.git.0.2a95a1a.el7.centos
           Available: origin-0.2-2.el7.centos.x86_64 (maxamillion-origin-next)
               origin = 0.2-2.el7.centos
           Available: origin-1.0.6-0.git.5812.e2a02a8.el7.centos.x86_64 (maxamillion-origin-next)
               origin = 1.0.6-0.git.5812.e2a02a8.el7.centos
           Available: origin-1.0.7-0.git.6899.032e1ef.el7.centos.x86_64 (maxamillion-origin-next)
               origin = 1.0.7-0.git.6899.032e1ef.el7.centos
           Available: origin-1.0.7-1.git.6900.d775557.el7.centos.x86_64 (maxamillion-origin-next)
               origin = 1.0.7-1.git.6900.d775557.el7.centos
           Available: origin-1.0.8-0.git.7227.8f1868d.el7.centos.x86_64 (maxamillion-origin-next)
               origin = 1.0.8-0.git.7227.8f1868d.el7.centos
           Available: origin-1.1-0.git.0.a6bb7cd.el7.centos.x86_64 (maxamillion-origin-next)
               origin = 1.1-0.git.0.a6bb7cd.el7.centos
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

[root@vm-node-01 ~]# cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core)
```

I need OpenShift based on Kubernetes 1.1 to test the new persistent storage feature.

**Comment by sdodson** [comment]
@loshkovskyi 

Two things, first origin-pod isn't a package that you should be installing, its purpose is only to be installed into the origin-pod Docker image.

Second, the root of the problem is that yesterday I built a package with version 1.1.0 which was incorrect and the appropriate images for that version don't exist on dockerhub. I've removed that build from the COPR and built the proper version 1.1 However yum won't consider this to be an upgrade so you must downgrade to that package. I've just run through installing the old bad package on my system and how to properly install the fixed packages.

This should get you to a working state

```
yum downgrade \*origin-\*1.1-0\*
systemctl restart origin-master origin-node
```

**Comment by loshkovskyi** [comment]
Thank you, it works now.
