### ISSUE TITLE
Making Examples Optional

### ISSUE THREAD

**Issue by jtslear** [openshift/openshift-ansible#1002]
Good Morning,  would it be worthwhile to provide the capability to optionally disable the loading of the openshift_examples?  In our environment, we aren't using them and are rather useless.  I'm merely trying to remove a bit of cruft from our overall installation.

**Comment by sdodson** [comment]
@jtslear For now, you can stop them from being installed into the namespace by setting the following, however I agree we should add a variable that disables the entire role.

```
openshift_examples_load_db_templates: false
openshift_examples_load_xpaas: false
openshift_examples_load_quickstarts: false
```

If you also want to disable the image streams
```
openshift_examples_load_rhel: false
openshift_examples_load_centos: false
```

**Comment by abutcher** [comment]
@brenton This one can be closed. ( Or @jtslear can close it if he gets here first :smiley_cat: )
