### ISSUE TITLE
RFE: configure additionalTrustedCA when using openshift_additional_ca

### ISSUE THREAD

**Issue by tremble** [openshift/openshift-ansible#10074]
#### Description

Now that the Masters are running as containers they don't pick up the host CA trusts by default.  Since we already offer openshift_additional_ca it would make sense to trust /etc/origin/master/ca-bundle.crt by default by adding the following to master-config.yaml:

```
imagePolicyConfig:
  additionalTrustedCA: /etc/origin/master/ca-bundle.crt
```

See also https://bugzilla.redhat.com/show_bug.cgi?id=1592936 and https://access.redhat.com/solutions/3587281

##### Version

3.11 / 4.0

##### Additional Information

I'd be happy to put together a PR and I've had a quick look.  I think the best bet would be to update openshift.master.image_policy_config via roles/openshift_facts/library/openshift_facts.py but since I'm unfamiliar with that chunk of code I'd appreciate a +1/-1  from you guys on the approach before I try digging too deep into it.  The quick and dirty option would be to update roles/openshift_control_plane/templates/master.yaml.v1.j2 but I think the option can only have one value, so folks *might* want to be able to override it.

@sdodson / @vrutkovs any comments?

**Comment by vrutkovs** [comment]
The solution looks good to me, lets see what @openshift/sig-master thinks about it - I'm mostly concerned about correct paths and upgrade flow

**Comment by Klaas-** [comment]
Hi,
So I'm coming from#8375 and #8142 . Would it also make sense to inject these additional CAs into all other pods? For example the docker-registry, the builder (for git/...). To me it seems important to be able to add a company CA and/or a CA that is being used for ssl interception on a proxy level at one central point during setup.

Greetings
Klaas

**Comment by Klaas-** [comment]
Also going a step further maybe automatically integrate all certs that are in /etc/pki/ca-trust/source/anchors/ on the ansible controller :)

**Comment by tremble** [comment]
@Klaas-

Doing that in general can cause other problems, especially if a container deliberately comes with an unusual CA baked in.  Personally I like the idea of all the 'core' pods using the CAs from somewhere central, but messing with other pods is liable to cause confusion.  (It's also something you'll need to convince upstream about, before the OpenShift Ansible team)

**Comment by Klaas-** [comment]
@tremble  I did not mean 'every' pod that is deployed into an openshift cluster. I meant the infrastructure/openshift internal pods. Those would include like registry/the s2i builder/glusterfs/....
Although it would also be nice to have a generic way of putting certs into every pod :)

**Comment by Klaas-** [comment]
So I've tested openshift 3.11 with the company proxy (ssl intercepting). The additionalTrustedCA in imagePolicyConfig works, so including that in openshift-ansible seems reasonable. The only other thing that really messed with the core functionality is the registry. I had to inject /etc/pki/ca-trust/extracted/pem/ and /etc/pki/ca-trust/extracted/openssl/ via a configmap.

**Comment by sdodson** [comment]
We've actually added /etc/pki to the host mounts for the apiserver pods. This would restore behavior found in 3.9 and earlier where the api server trusted the CAs that the host trusts. Which I think addresses the original concern for this RFE.

See #10486 #10485

This does not mean that the registry pod which is required for pull through would similarly trust all the CAs unless a mount is also specified for that pod.

**Comment by bortek** [comment]
This latest with moving things into pods affects this particular setting 

openshift_master_identity_providers=[{'name': 'corporate', 'challenge': 'true', 'login': 'true', 'mappingMethod': 'claim','kind': 'LDAPPasswordIdentityProvider','attributes': {'id': ['sAMAccountName'], 'email':['mail'],'name': ['displayName'],'preferredUsername': ['sAMAccountName']}, 'bindDN': 'CN=XXXXXXX,OU=Some OU,OU=User Accounts,DC=somedc,DC=somead,DC=corp,DC=net', **'bindPassword': {'file': '/etc/ansible/somepass.txt'},** 'ca': '/etc/openldap/cacerts/cacert.pem','insecure': 'false','url': 'ldaps://someURL here'}]

when using bindPassword from the file. The fie is not found since obviously is not in the pod but on the node. 

Are you going to address it in some way ?
