### ISSUE TITLE
[OCP 3.10] Scale Up - glusterfs nodes are only added to a glusterfs cluster

### ISSUE THREAD

**Issue by balpert89** [openshift/openshift-ansible#10097]
#### Description

Scaling up an existing Openshift Enterprise 3.10 cluster with glusterfs nodes will fail because the scaleup.yml playbook will only call `- import_playbook: ../openshift-glusterfs/private/add_hosts.yml`.

##### Version

* Your ansible version per `ansible --version`
```
ansible 2.4.3.0
  config file = /usr/share/ansible/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

* The output of `rpm -q openshift-ansible`
```
openshift-ansible-3.10.41-1.git.0.fd15dd7.el7.noarch
```

##### Steps To Reproduce
1. Deploy a cluster without glusterfs nodes
2. scale up the cluster from step 1 with new_nodes that also act as glusterfs storage nodes

##### Expected Results
The scaleup  checked if a glusterfs cluster was previously deployed. Based on the outcome of the check it 
a) deploys a new glusterfs cluster (if no previous cluster was found) or
b) adds new glusterfs hosts to the glusterfs cluster (if a previous cluster was found)

##### Observed Results
The scaleup.yml playbook just calls the `openshift-glusterfs/private/add_hosts.yml` regardless of an existing glusterfs cluster is in place or not
```
TASK [openshift_storage_glusterfs : Wait for GlusterFS pods] *************************************************************************************************************************************************
FAILED - RETRYING: Wait for GlusterFS pods (30 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (29 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (28 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (27 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (26 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (25 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (24 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (23 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (22 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (21 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (20 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (19 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (18 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (17 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (16 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (15 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (14 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (13 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (12 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (11 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (10 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (9 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (8 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (7 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (6 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (5 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (4 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (3 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (2 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (1 retries left).
fatal: [aott006-mst-01]: FAILED! => {"attempts": 30, "changed": false, "results": {"cmd": "/bin/oc get pod --selector=glusterfs=cns-storage-pod -o json -n cns-storage", "results": [{"apiVersion": "v1", "items": [], "kind": "List", "metadata": {"resourceVersion": "", "selfLink": ""}}], "returncode": 0}, "state": "list"}
```

##### Additional Information

related code: `playbooks/openshift-node/scaleup.yml` line 41.

**Comment by michaelgugino** [comment]
This is not a support set of events.

If a gluster cluster is not already deployed you should

1) Scale up your new nodes as if they're NOT gluster nodes (remove all gluster settings)
2) Add gluster settings to proper hosts/groups in inventory
3) Run specific gluster deployment playbooks.

**Comment by balpert89** [comment]
Sorry but that does not make any sense. From your description of the use case I would understand it if we completely get rid of the addition of gluster nodes, otherwise it breaks an automated end to end approach (creating inventory, preparing hosts, add nodes, doing post configuration stuff).

As you said, if its not an intended use case, lets decide what to do with the nodes after the actual scale up, regardless of the [glusterfs] group in the inventory -> removing the `add_hosts,yml` import_playbook directive from both master and node scaleup.

**Comment by michaelgugino** [comment]
@balpert89 You can't deploy gluster while scale up new nodes.  You have two options:

1)  Deploy gluster on existing nodes, then scale up new nodes that are part of gluster if you choose.
or
2)  Scale up the new nodes, then deploy gluster.

Scenario:  "I have 6 regular nodes, I want to add 3 new nodes as gluster nodes, I don't want to install gluster on the 6 regular nodes."

Solution: "Scale up 3 new nodes as if they're normal nodes.  Next, update inventory and run gluster playbooks"

**Comment by balpert89** [comment]
That I am not able to do both the scale up and the gluster installation in one step yet is clear to me. But forcing the addition of glusterfs nodes is not, the assumption that an already installed glusterfs cluster is available seems error prone and unintuitive to me - as shown above.

Why should it not be possible to utilize a check of the groups and decide upon the outcome what to do, either scaling the gluster cluster or creating a new one? I have done some tests:

Playbook:
```
- name: intersect tests
  gather_facts: no
  hosts: localhost
  tasks:
    - set_fact:
        is_glusterfs_completely_new: "{{ groups['glusterfs'] | intersect(groups['new_nodes']) | length == groups['glusterfs']|length }}"

    - debug: var=is_glusterfs_completely_new
```

Input 1:
```
[new_nodes]
node1
node2
node3

[glusterfs]
node1
node2
node3
```
Result 2: 
```
PLAY [intersect tests] *********************************************************************************************************************************************************************************

TASK [set_fact] ****************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *******************************************************************************************************************************************************************************************
ok: [localhost] => {
    "is_glusterfs_completely_new": true
}
```
----
Input 2
```
[new_nodes]
node1
node2
node3
node4

[glusterfs]
node1
node2
node3
```
Result 2
```
PLAY [intersect tests] *********************************************************************************************************************************************************************************

TASK [set_fact] ****************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *******************************************************************************************************************************************************************************************
ok: [localhost] => {
    "is_glusterfs_completely_new": true
}

PLAY RECAP *********************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
----
Input 3
```
node1
node2
node3

[glusterfs]
node1
node2
node3
node4
```
Result 3
```
PLAY [intersect tests] *********************************************************************************************************************************************************************************

TASK [set_fact] ****************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *******************************************************************************************************************************************************************************************
ok: [localhost] => {
    "is_glusterfs_completely_new": false
}
```

The result can be used to decide if we do a `add_hosts.yml` play or a `openshift-glusterfs/config.yml` (new installation) play.

I am eager on your input :-)

**Comment by michaelgugino** [comment]
While it's technically possible to implement something like this, I don't think it delivers a lot of value vs complexity.  There's a large matrix of gluster support:

glusterfs and/or glusterfs_registry (which may or may not consist of the same hosts), which hosts may or may not be 'native' eg, not nodes at all.

Previously, there was no ability to add gluster nodes during scaleup, even if gluster was already installed.  I think we're in a good place for now.

**Comment by balpert89** [comment]
Hm okay, the possibility to add is a good thing in itself, but forcing it upon me is not that cool ;-)

I have to work around that, I will create some intermediate group that holds all gluster hosts but with a different name, and in my post installation I will rebuild the correct glusterfs group in memory.

Thanks for the discussion!
