### ISSUE TITLE
openshift 3.10 install

### ISSUE THREAD

**Issue by moscarson** [openshift/openshift-ansible#10110]
#### Description

I am trying to install openshift on 4 RHEL7 systems.  1 master, 2 nodes, and 1 etcd system.  I have tried this a number of times with no success.  typical errors are that the nodes will never respond.  i have experimented with different settings in the ansible hosts file with no luck.

I have docker Docker version 1.13.1, build 6e3bb8e/1.13.1 installed and configured on the two nodes.  docker info shows about 30 GB of Data Space Available

I think first, I would like to know if these are 
a) correct RPMs
b) correct settings in ansible/hosts file.  

if so, I can rerun and provide specific output logs with failure messages

##### Version
ansible 2.6.3

openshift-ansible-3.10.41-1.git.0.fd15dd7.el7.noarch
openshift-ansible-docs-3.10.41-1.git.0.fd15dd7.el7.noarch
openshift-ansible-playbooks-3.10.41-1.git.0.fd15dd7.el7.noarch
openshift-ansible-roles-3.10.41-1.git.0.fd15dd7.el7.noarch

##### Steps To Reproduce
1. ansible-playbook  -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
2. ansible-playbook  -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

##### Expected Results
expect the installation to complete

##### Observed Results
the nodes never respond

##### Additional Information
/etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)

##### /etc/ansible/hosts
[all]
forge-mas-oshift.localdomain
forge-nod1-oshift.localdomain
forge-nod2-oshift.localdomain
forge-etc-oshift.localdomain

[masters]
forge-mas-oshift.localdomain

[etcd]
forge-etc-oshift.localdomain

[nodes]
forge-nod1-oshift.localdomain
forge-nod2-oshift.localdomain

[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_user=root
ansible_ssh_user=root
product_type=openshift
deployment_type=enterprise
openshift_release="3.10"
openshift_deployment_type=openshift-enterprise
debug_level=3
openshift_node_group_name=node-config-master
ansible_python_interpreter=/usr/bin/python
openshift_web_console_install=false
openshift_master_cluster_hostname=forge-mas-oshift.localdomain
log_path=/tmp/ansible.log
ansible_debug=true

**Comment by michaelgugino** [comment]
masters must also be nodes.

the following are deprecated/not used:
product_type=openshift
deployment_type=enterprise

openshift_node_group_name=node-config-master
is not sufficient for all nodes. I would use 'node-config-master-infra' for your master and 'node-config-compute' for your compute nodes.
