### ISSUE TITLE
Use --generate-ssh-keys when building an Azure image

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-ansible#10120]
```
ERROR: An RSA key file or key value must be supplied to SSH Key Value. You can use --generate-ssh-keys to let CLI generate one for you", "stderr_lines": ["ERROR: An RSA key file or key value must be supplied to SSH Key Value. You can use --generate-ssh-keys to let CLI generate one for you"
```
Based on the error above and on the fact that the VM that is created for building the node image is temporary, I think we can stop passing an SSH key in the VM and let `az vm` generate it on the fly with `--generate-ssh-keys`.

@openshift/sig-azure

**Comment by kwoodson** [comment]
@kargakis,  This sounds like a path forward.  The only downside I could see is if we want to ssh to the instance during a build for debug purposes.  Since I haven't done that in months I'm not sure its an issue.

**Comment by kargakis** [comment]
When working on the ci-operator job that runs the node build. I fixed it on my side, but the extra ssh key isn't really needed.
