### ISSUE TITLE
release-3.9 branch defaults openshift_version to 3.10, openshift/origin PR can't merge

### ISSUE THREAD

**Issue by wongma7** [openshift/openshift-ansible#10134]
#### Description
This is preventing patches to openshift/origin release-3.9 (https://github.com/openshift/origin/pull/20768) from merging
see also: https://github.com/openshift/origin/issues/20812

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/20768/test_pull_request_origin_extended_conformance_gce_39/620/build-log.txt

+ ../../bin/ansible.sh ansible-playbook -e openshift_test_repo=https://storage.googleapis.com/origin-ci-test/pr-logs/pull/20768/test_pull_request_origin_extended_conformance_gce_39/620/artifacts/rpms -e debug_level=4 -e 'oreg_url=registry.svc.ci.openshift.org/ci-pr-images/prtest-20891fe-620-origin-${component}:v3.9' playbooks/gcp/openshift-cluster/launch.yml '-e @sjb/inventory/base.cfg'
Activated service account credentials for: [jenkins-ci-provisioner@openshift-gce-devel.iam.gserviceaccount.com]
...
TASK [openshift_version : debug] ***********************************************
Tuesday 18 September 2018  16:21:39 +0000 (0:00:00.078)       0:03:48.719 ***** 
ok: [35.231.19.84] => {
    "msg": "openshift_pkg_version was not defined. Falling back to -3.10.0"
}

TASK [openshift_version : set_fact] ********************************************
Tuesday 18 September 2018  16:21:40 +0000 (0:00:00.079)       0:03:48.799 ***** 
ok: [35.231.19.84]

TASK [openshift_version : debug] ***********************************************
Tuesday 18 September 2018  16:21:40 +0000 (0:00:00.079)       0:03:48.878 ***** 
ok: [35.231.19.84] => {
    "msg": "openshift_image_tag was not defined. Falling back to v3.10.0"
}
...
fatal: [prtest-20891fe-348-ig-m-344k -> localhost]: FAILED! => {"changed": true, "cmd": ["tar", "-C", "/usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/", "-cvf", "/tmp/openshift-ansible-npRMvte/openshift-examples.tar", "."], "delta": "0:00:00.614246", "end": "2018-08-31 05:53:34.587461", "msg": "non-zero return code", "rc": 2, "start": "2018-08-31 05:53:33.973215", "stderr": "tar: /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now", "stderr_lines": ["tar: /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/: Cannot open: No such file or directory", "tar: Error is not recoverable: exiting now"], "stdout": "", "stdout_lines": []}

Should the CI be setting openshift.common.version or openshift_version? Not sure of the difference. What is openshift_protect_installed_version?

**Comment by vrutkovs** [comment]
CI is setting `openshift_release`, which is used correctly when image is being built, but its ignored when the nodes are being spawned.

**Comment by vrutkovs** [comment]
This is a matter of setting correct repos.

In Prow CI we're passing `openshift_release=3.9` and setting CentOS repos to be `http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin39/` instead of `../openshift-origin/` which has 3.10 packages.

This is not an issue we should fix in `release-3.9`, its a jenkins misconfiguration
