### ISSUE TITLE
The --confirm-def-push flag should be turned off for docker instance

### ISSUE THREAD

**Issue by chunyunchen** [openshift/openshift-ansible#1014]
We need set --confirm-def-push=false for docker instance due to bug: https://bugzilla.redhat.com/show_bug.cgi?id=1245472

**Comment by detiber** [comment]
@chunyunchen If I'm reading the bug correctly, this flag is needed to be able to push images to dockerhub from the OpenShift hosts.

If that is the case, is that something that we want to set by default? It seems like this is something that we would want to document, provide a flag for at install time, and possibly provide a utility for updating a running cluster with this setting.

@bparees what are your thoughts on how we should manage this setting?

**Comment by bparees** [comment]
personally i'd say we should set it, you don't accidentally push to dockerhub, you'd have to provide credentials and choose that push spec.

but since rhel felt it was important not to allow it by default, i guess we should abide that and not override it, so I guess i'd agree w/ document+provide option at install time.

**Comment by chunyunchen** [comment]
@detiber @bparees  I agree with document+provide option at install time.

**Comment by GrahamDumpleton** [comment]
If this is going to be optionally enabled, would it likely be enabled for OpenShift Online?

I was trying to use ability to push to Docker Hub as a way of replacing Docker Hub's automated build system and use OpenShift to manage that. It would be nice to be able to do that on OpenShift Online.

**Comment by bparees** [comment]
I would assume so, but @abhgupta would be the one to know for sure.
