### ISSUE TITLE
origin-master systemd files missing in 3.10

### ISSUE THREAD

**Issue by thinking-aloud** [openshift/openshift-ansible#10164]
#### Description
The Systemd scrips for the **master-api** and the **master-controller** point to a non existing location.
```
/etc/systemd/system/multi-user.target.wants/origin-master-api.service -> /usr/lib/systemd/system/origin-master-api.service
/etc/systemd/system/multi-user.target.wants/origin-master-controllers.service -> /usr/lib/systemd/system/origin-master-controllers.service
```

##### Version
```
ansible 2.5.1
openshift-ansible-3.10.47-1-41-g43d7e1269
```

##### Steps To Reproduce
1. Deploy a fresh cluster

##### Expected Results
systemctl lets me restart the master.

```
# systemctl restart origin-master-api.service origin-master-api.service
# <no output>
```

##### Observed Results
Describe what is actually happening.

```
# systemctl restart origin-master-api.service origin-master-api.service
Failed to restart master-api.service: Unit not found.
Failed to restart master-controller.service: Unit not found.

# systemctl status origin-master-api.service origin-master-api.service
Unit origin-master-api.service could not be found.
Unit origin-master-api.service could not be found.
```

##### Additional Information

```
CentOS Linux release 7.5.1804 (Core)
```

My current workaround is to just restart docker. Is there a better way?

**Comment by vrutkovs** [comment]
system services were removed in 3.10 as API and controllers are now running in static pods - see https://docs.openshift.com/container-platform/3.10/release_notes/ocp_3_10_release_notes.html#ocp-310-important-installation-changes

`/usr/local/bin/master-restart api api` should be used instead
