### ISSUE TITLE
Install release 3.9 but ansible-playbook request v3.10 example

### ISSUE THREAD

**Issue by kyauaa** [openshift/openshift-ansible#10208]
#### Description

Provide a brief description of your issue here. For example:

I am deploying a release 3.9, but failed when runinng the playbook. It shows
`
TASK [openshift_hosted_templates : Create tar of OpenShift examples] *************************************************************
fatal: [master.openshift -> localhost]: FAILED! => {"changed": true, "cmd": ["tar", "-C", "/root/openshift-ansible/roles/openshift_hosted_templates/files/v3.10/origin", "-cvf", "/tmp/openshift-ansible-3AXttTb/openshift-hosted-templates.tar", "."], "delta": "0:00:00.004351", "end": "2018-09-23 10:58:57.891950", "msg": "non-zero return code", "rc": 2, "start": "2018-09-23 10:58:57.887599", "stderr": "tar: /root/openshift-ansible/roles/openshift_hosted_templates/files/v3.10/origin: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now", "stderr_lines": ["tar: /root/openshift-ansible/roles/openshift_hosted_templates/files/v3.10/origin: Cannot open: No such file or directory", "tar: Error is not recoverable: exiting now"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/root/openshift-ansible/playbooks/deploy_cluster.retry`

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

OKD 3.9

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

`ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
`

If you're operating from a **git clone**:

* The output of `git describe`

openshift-ansible-3.9.45-1-4-g47526b2

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
package openshift-ansible is not installed
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
ansible-playbook ~/openshift-ansible/playbooks/prerequisites.yml

ansible-playbook ~/openshift-ansible/playbooks/deploy_cluster.yml

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages

TASK [openshift_hosted_templates : Create tar of OpenShift examples] *************************************************************
fatal: [master.openshift -> localhost]: FAILED! => {"changed": true, "cmd": ["tar", "-C", "/root/openshift-ansible/roles/openshift_hosted_templates/files/v3.10/origin", "-cvf", "/tmp/openshift-ansible-3AXttTb/openshift-hosted-templates.tar", "."], "delta": "0:00:00.004351", "end": "2018-09-23 10:58:57.891950", "msg": "non-zero return code", "rc": 2, "start": "2018-09-23 10:58:57.887599", "stderr": "tar: /root/openshift-ansible/roles/openshift_hosted_templates/files/v3.10/origin: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now", "stderr_lines": ["tar: /root/openshift-ansible/roles/openshift_hosted_templates/files/v3.10/origin: Cannot open: No such file or directory", "tar: Error is not recoverable: exiting now"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/root/openshift-ansible/playbooks/deploy_cluster.retry

PLAY RECAP ***********************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0
master.openshift           : ok=306  changed=101  unreachable=0    failed=1
node1.openshift            : ok=26   changed=1    unreachable=0    failed=0


INSTALLER STATUS *****************************************************************************************************************
Initialization             : Complete (0:00:39)
Health Check               : Complete (0:03:26)
etcd Install               : Complete (0:03:18)
Master Install             : Complete (0:05:52)
Master Additional Install  : In Progress (0:00:19)
        This phase can be restarted by running: playbooks/openshift-master/additional_config.yml



Failure summary:


  1. Hosts:    master.openshift
     Play:     Additional master configuration
     Task:     Create tar of OpenShift examples
     Message:  non-zero return code


```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by michaelgugino** [comment]
Most likely, you have set openshift_image_tag or openshift_release to 3.10 in error.

**Comment by kyauaa** [comment]
Thanks Michael. I added the version tag in my inventory file, and it works. Thank you!!!
