### ISSUE TITLE
Cannot Install WebConsole on AWS

### ISSUE THREAD

**Issue by jdunneirl** [openshift/openshift-ansible#10223]
#### Description

When trying to install the web console it fails to connect 

##### Version

3.10

ansible 2.6.4
  config file = None
  configured module search path = [u'/Users/john/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Sep 18 2018, 20:16:18) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

openshift-ansible-3.10.50-1-23-g87569f9a8

##### Steps To Reproduce
1. ansible-playbook -i inventory/hosts.ec2 playbooks/openshift-web-console/config.yml --key-file ~/.ssh/mykey.pem
2. [step 2]

inventory file 

[OSEv3:children]
masters
etcd
nodes
[OSEv3:vars]
ansible_ssh_user=centos
ansible_sudo=true
ansible_become=true
deployment_type=origin
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_install_examples=true
#openshift_release="3.10"
#openshift_version=3.10
#openshift_image_tag=v3.10
#openshift_pkg_version=3.10.0
openshift_web_console_nodeselector={'region':'infra'}
openshift_docker_options='--selinux-enabled --insecure-registry 172.30.0.0/16'
openshift_disable_check=disk_availability,docker_storage,memory_availability
[masters]
ec2-107-21-73-166.compute-1.amazonaws.com
[etcd]
ec2-107-21-73-166.compute-1.amazonaws.com
[nodes]
ec2-107-21-73-166.compute-1.amazonaws.com openshift_schedulable=true openshift_node_group_name="node-config-master-infra"
ec2-35-173-252-96.compute-1.amazonaws.com openshift_node_group_name="node-config-compute"
ec2-54-208-249-204.compute-1.amazonaws.com openshift_node_group_name="node-config-compute"

##### Expected Results
Console to install

```
changed: [ec2-107-21-73-166.compute-1.amazonaws.com]
TASK [openshift_web_console : debug] **************************************************************************************************************************************************************************
ok: [ec2-107-21-73-166.compute-1.amazonaws.com] => {
    "msg": []
}
TASK [openshift_web_console : Report console errors] **********************************************************************************************************************************************************
fatal: [ec2-107-21-73-166.compute-1.amazonaws.com]: FAILED! => {"changed": false, "msg": "Console install failed."}
to retry, use: --limit @/Users/john/openshift-ansible/playbooks/deploy_cluster.retry
PLAY RECAP ****************************************************************************************************************************************************************************************************
ec2-107-21-73-166.compute-1.amazonaws.com : ok=489  changed=94   unreachable=0    failed=1   
ec2-35-173-252-96.compute-1.amazonaws.com : ok=35   changed=2    unreachable=0    failed=0   
ec2-54-208-249-204.compute-1.amazonaws.com : ok=35   changed=2    unreachable=0    failed=0   
localhost                  : ok=13   changed=0    unreachable=0    failed=0   
INSTALLER STATUS **********************************************************************************************************************************************************************************************
Initialization              : Complete (0:01:23)
Health Check                : Complete (0:00:39)
Node Bootstrap Preparation  : Complete (0:00:01)
etcd Install                : Complete (0:03:19)
Master Install              : Complete (0:15:46)
Master Additional Install   : Complete (0:03:02)
Node Join                   : Complete (0:00:41)
Hosted Install              : Complete (0:03:13)
Web Console Install         : In Progress (0:15:06)
This phase can be restarted by running: playbooks/openshift-web-console/config.yml
Failure summary:
  1. Hosts:    ec2-107-21-73-166.compute-1.amazonaws.com
     Play:     Web Console
     Task:     Report console errors
     Message:  Console install failed.

FAILED - RETRYING: Verify that the console is running (1 retries left).
fatal: [ec2-107-21-73-166.compute-1.amazonaws.com]: FAILED! => {"attempts": 60, "changed": false, "results": {"cmd": "/bin/oc get deployment webconsole -o json -n openshift-web-console", "results": [{"apiVersion": "extensions/v1beta1", "kind": "Deployment", "metadata": {"annotations": {"deployment.kubernetes.io/revision": "2", "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"apps/v1beta1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"openshift-web-console\",\"webconsole\":\"true\"},\"name\":\"webconsole\",\"namespace\":\"openshift-web-console\"},\"spec\":{\"replicas\":1,\"strategy\":{\"rollingUpdate\":{\"maxUnavailable\":\"100%\"},\"type\":\"RollingUpdate\"},\"template\":{\"metadata\":{\"labels\":{\"app\":\"openshift-web-console\",\"webconsole\":\"true\"},\"name\":\"webconsole\"},\"spec\":{\"containers\":[{\"command\":[\"/usr/bin/origin-web-console\",\"--audit-log-path=-\",\"-v=0\",\"--config=/var/webconsole-config/webconsole-config.yaml\"],\"image\":\"docker.io/openshift/origin-web-console:v3.10.0\",\"imagePullPolicy\":\"IfNotPresent\",\"livenessProbe\":{\"exec\":{\"command\":[\"/bin/sh\",\"-c\",\"if [[ ! -f /tmp/webconsole-config.hash ]]; then \\\\\\n  md5sum /var/webconsole-config/webconsole-config.yaml \\u003e /tmp/webconsole-config.hash; \\\\\\nelif [[ $(md5sum /var/webconsole-config/webconsole-config.yaml) != $(cat /tmp/webconsole-config.hash) ]]; then \\\\\\n  echo 'webconsole-config.yaml has changed.'; \\\\\\n  exit 1; \\\\\\nfi \\u0026\\u0026 curl -k -f https://0.0.0.0:8443/console/\"]}},\"name\":\"webconsole\",\"ports\":[{\"containerPort\":8443}],\"readinessProbe\":{\"httpGet\":{\"path\":\"/healthz\",\"port\":8443,\"scheme\":\"HTTPS\"}},\"resources\":{\"requests\":{\"cpu\":\"100m\",\"memory\":\"100Mi\"}},\"volumeMounts\":[{\"mountPath\":\"/var/serving-cert\",\"name\":\"serving-cert\"},{\"mountPath\":\"/var/webconsole-config\",\"name\":\"webconsole-config\"}]}],\"nodeSelector\":{\"region\":\"infra\"},\"serviceAccountName\":\"webconsole\",\"volumes\":[{\"name\":\"serving-cert\",\"secret\":{\"defaultMode\":288,\"secretName\":\"webconsole-serving-cert\"}},{\"configMap\":{\"defaultMode\":288,\"name\":\"webconsole-config\"},\"name\":\"webconsole-config\"}]}}}}\n"}, "creationTimestamp": "2018-09-24T10:43:14Z", "generation": 2, "labels": {"app": "openshift-web-console", "webconsole": "true"}, "name": "webconsole", "namespace": "openshift-web-console", "resourceVersion": "19895", "selfLink": "/apis/extensions/v1beta1/namespaces/openshift-web-console/deployments/webconsole", "uid": "a402e7d4-bfe6-11e8-9b15-0e3bfb791860"}, "spec": {"progressDeadlineSeconds": 600, "replicas": 1, "revisionHistoryLimit": 2, "selector": {"matchLabels": {"app": "openshift-web-console", "webconsole": "true"}}, "strategy": {"rollingUpdate": {"maxSurge": "25%", "maxUnavailable": "100%"}, "type": "RollingUpdate"}, "template": {"metadata": {"creationTimestamp": null, "labels": {"app": "openshift-web-console", "webconsole": "true"}, "name": "webconsole"}, "spec": {"containers": [{"command": ["/usr/bin/origin-web-console", "--audit-log-path=-", "-v=0", "--config=/var/webconsole-config/webconsole-config.yaml"], "image": "docker.io/openshift/origin-web-console:v3.10.0", "imagePullPolicy": "IfNotPresent", "livenessProbe": {"exec": {"command": ["/bin/sh", "-c", "if [[ ! -f /tmp/webconsole-config.hash ]]; then \\\n  md5sum /var/webconsole-config/webconsole-config.yaml > /tmp/webconsole-config.hash; \\\nelif [[ $(md5sum /var/webconsole-config/webconsole-config.yaml) != $(cat /tmp/webconsole-config.hash) ]]; then \\\n  echo 'webconsole-config.yaml has changed.'; \\\n  exit 1; \\\nfi && curl -k -f https://0.0.0.0:8443/console/"]}, "failureThreshold": 3, "periodSeconds": 10, "successThreshold": 1, "timeoutSeconds": 1}, "name": "webconsole", "ports": [{"containerPort": 8443, "protocol": "TCP"}], "readinessProbe": {"failureThreshold": 3, "httpGet": {"path": "/healthz", "port": 8443, "scheme": "HTTPS"}, "periodSeconds": 10, "successThreshold": 1, "timeoutSeconds": 1}, "resources": {"requests": {"cpu": "100m", "memory": "100Mi"}}, "terminationMessagePath": "/dev/termination-log", "terminationMessagePolicy": "File", "volumeMounts": [{"mountPath": "/var/serving-cert", "name": "serving-cert"}, {"mountPath": "/var/webconsole-config", "name": "webconsole-config"}]}], "dnsPolicy": "ClusterFirst", "nodeSelector": {"region": "infra"}, "restartPolicy": "Always", "schedulerName": "default-scheduler", "securityContext": {}, "serviceAccount": "webconsole", "serviceAccountName": "webconsole", "terminationGracePeriodSeconds": 30, "volumes": [{"name": "serving-cert", "secret": {"defaultMode": 288, "secretName": "webconsole-serving-cert"}}, {"configMap": {"defaultMode": 288, "name": "webconsole-config"}, "name": "webconsole-config"}]}}}, "status": {"conditions": [{"lastTransitionTime": "2018-09-24T10:43:15Z", "lastUpdateTime": "2018-09-24T10:43:15Z", "message": "Deployment has minimum availability.", "reason": "MinimumReplicasAvailable", "status": "True", "type": "Available"}, {"lastTransitionTime": "2018-09-24T13:36:49Z", "lastUpdateTime": "2018-09-24T13:36:49Z", "message": "ReplicaSet \"webconsole-899695d59\" has timed out progressing.", "reason": "ProgressDeadlineExceeded", "status": "False", "type": "Progressing"}], "observedGeneration": 2, "replicas": 1, "unavailableReplicas": 1, "updatedReplicas": 1}}], "returncode": 0}, "state": "list"}
...ignoring

**Comment by nagonzalez** [comment]
I'm guessing this line in your config may be mucking this up:
```
openshift_web_console_nodeselector={'region':'infra'}
```

You're overwriting the default value here:
https://github.com/openshift/openshift-ansible/blob/a7bacc1ebf3da623cadee79faba5ee6e0ed71eb6/roles/openshift_web_console/defaults/main.yml#L2

what's the output of?
```
oc get all -n openshift-web-console
oc get events -n openshift-web-console
```

I'm guessing the webconsole isn't scheduled due to nodeselector of `{'region':'infra'}` not matching any of your nodes

Removing your `openshift_web_console_nodeselector` so you use the default should get you going

**Comment by vrutkovs** [comment]
`openshift_node_group_name="node-config-master-infra"` would set `node-role.kubernetes.io/master=true` and `node-role.kubernetes.io/infra=true`. `region=infra` labels are deprecated and no longer set

**Comment by adesurya** [comment]
@vrutkovs 

Hi, 

I'm got same problem. I already set  with your info in my inventory. but also got problem failed install webconsole on Azure

Here my inventory

`#bare minimum hostfile

[OSEv3:children]
masters
nodes
etcd

[masters]
xxxx.eastus.cloudapp.azure.com openshift_schedulable=true containerized=true

[etcd]
xxxx.eastus.cloudapp.azure.com

[nodes]
# openshift_node_group_name should refer to a dictionary with matching key of name in list openshift_node_groups.
xxxx.eastus.cloudapp.azure.com openshift_node_group_name="node-config-all-in-one"

[OSEv3:vars]
openshift_additional_repos=[{'id': 'centos-paas', 'name': 'centos-paas', 'baseurl' :'https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin311', 'gpgcheck':'0', 'enabled' :'1'}]

ansible_ssh_user=root
enable_excluders=False
enable_docker_excluder=False
ansible_service_broker_install=False

containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

openshift_node_groups=[{'name': 'node-config-all-in-one', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]

deployment_type=origin
openshift_deployment_type=origin

#openshift_metrics_image_version="v3.11"
openshift_logging_image_version="v3.11"
openshift_logging_elasticsearch_proxy_image="v1.0.0"
openshift_logging_es_nodeselector={"node-role.kubernetes.io/infra":"true"}
logging_elasticsearch_rollout_override=false
osm_use_cockpit=true

openshift_metrics_install_metrics=True
openshift_logging_install_logging=True
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
openshift_master_htpasswd_file='/etc/origin/master/htpasswd'

openshift_public_hostname=xxxx.eastus.cloudapp.azure.com
openshift_console_hostname=xxxx.eastus.cloudapp.azure.com

openshift_master_api_port=8443
openshift_master_console_port=8443
`
I'm using ansible 2.4.6.0
My Docker version 1.13.1
Openshift Version 3.10
Hosted VM on Azure
with Computing vCPU 8 and RAM 16GB.


output from 
oc get all -n openshift-web-console
`NAME                             READY     STATUS    RESTARTS   AGE
pod/webconsole-55c4d867f-jf6g4   0/1       Pending   0          27m

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/webconsole   ClusterIP   172.30.124.189   <none>        443/TCP   27m

NAME                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/webconsole   1         1         1            0           27m

NAME                                   DESIRED   CURRENT   READY     AGE
replicaset.apps/webconsole-55c4d867f   1         1         0         27m
`
oc get events -n openshift-web-console
`LAST SEEN   FIRST SEEN   COUNT     NAME                                          KIND         SUBOBJECT   TYPE      REASON              SOURCE                  MESSAGE
3m          28m          91        webconsole-55c4d867f-jf6g4.15eb435785a11daf   Pod                      Warning   FailedScheduling    default-scheduler       0/1 nodes are available: 1 node(s) were not ready.
28m         28m          1         webconsole-55c4d867f.15eb4357854a057c         ReplicaSet               Normal    SuccessfulCreate    replicaset-controller   Created pod: webconsole-55c4d867f-jf6g4
28m         28m          1         webconsole.15eb4357410723e8                   Deployment               Normal    ScalingReplicaSet   deployment-controller   Scaled up replica set webconsole-55c4d867f to 1
`
