### ISSUE TITLE
Installation Failed on Simple Cluster Mode. Error in RUNNING HANDLER [openshift_master : Verify API Server]

### ISSUE THREAD

**Issue by ajoykumarsinha** [openshift/openshift-ansible#10232]
#### Description

Provide a brief description of your issue here. For example:

> It is failed to install in a cluster mode with one master / one node / one etcd
> Following is the error getting during installation failure
>
> fatal: [os-master1.local]: FAILED! => {
    "attempts": 120, 
    "changed": false, 
    "cmd": [
        "curl", 
        "--silent", 
        "--tlsv1.2", 
        "--max-time", 
        "2", 
        "--cacert", 
        "/etc/origin/master/ca-bundle.crt", 
        "https://os-master1.local/healthz/ready"
    ], 
    "delta": "0:00:08.028596", 
    "end": "2018-09-26 09:24:22.328299", 
    "invocation": {
        "module_args": {
            "_raw_params": "curl --silent --tlsv1.2 --max-time 2 --cacert /etc/origin/master/ca-bundle.crt https://os-master1.local/healthz/ready", 
            "_uses_shell": false, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": false
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 28, 
    "start": "2018-09-26 09:24:14.299703", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "", 
    "stdout_lines": []
}
  

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

>[root@controller master]# ansible --version
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

If you're operating from a **git clone**:

* The output of `git describe`
> [root@controller openshift-ansible]# git describe
openshift-ansible-3.9.45-1-4-g47526b2
[root@controller openshift-ansible]# 

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
> All the machines are provisioned as VM under VMware 
> I have one ansible controller machine
> one master
> one node
> one etcd
> DNS has been setup in controller machine and it is able to resolve all the machines

##### Expected Results
 Openshift cluster will be installed

##### Observed Results
 
> Error got in this task 
> RUNNING HANDLER [openshift_master : Verify API Server]

> Following is the error
><os-master1.local> (0, '', '')
fatal: [os-master1.local]: FAILED! => {
    "attempts": 120, 
    "changed": false, 
    "cmd": [
        "curl", 
        "--silent", 
        "--tlsv1.2", 
        "--max-time", 
        "2", 
        "--cacert", 
        "/etc/origin/master/ca-bundle.crt", 
        "https://os-master1.local/healthz/ready"
    ], 
    "delta": "0:00:08.028596", 
    "end": "2018-09-26 09:24:22.328299", 
    "invocation": {
        "module_args": {
            "_raw_params": "curl --silent --tlsv1.2 --max-time 2 --cacert /etc/origin/master/ca-bundle.crt https://os-master1.local/healthz/ready", 
            "_uses_shell": false, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": false
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 28, 
    "start": "2018-09-26 09:24:14.299703", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "", 
    "stdout_lines": []
}

##### Additional Information

> Here is my inventory file 
>[OSEv3:children]
masters
etcd
nodes

[OSEv3:vars]
## Ansible user who can login to all nodes through SSH (e.g. ssh root@os-master1)
ansible_user=root

## Deployment type: "openshift-enterprise" or "origin"
openshift_deployment_type=origin
deployment_type=origin

## Specifies the major version
openshift_release=v3.9
openshift_pkg_version=-3.9.0
openshift_image_tag=v3.9.0
openshift_service_catalog_image_version=v3.9.0
template_service_broker_image_version=v3.9.0
openshift_metrics_image_version="v3.9"
openshift_logging_image_version="v3.9"
openshift_logging_elasticsearch_proxy_image_version="v1.0.0"
osm_use_cockpit=true
openshift_metrics_install_metrics=True
openshift_logging_install_logging=True

ansible_service_broker_install=false
ansible_service_broker_remove=true
openshift_use_dnsmasq=true

## Service address space,  /16 = 65,534 IPs
openshift_portal_net=172.30.0.0/16

## Pod address space
osm_cluster_network_cidr=10.128.0.0/14

## Subnet Length of each node, 9 = 510 IPs
osm_host_subnet_length=9

## Master API  port
openshift_master_api_port=443

## Master console port  (e.g. https://console.openshift.local:443)
openshift_master_console_port=443

## Clustering method
openshift_master_cluster_method=native

## Hostname used by nodes and other cluster internals
openshift_master_cluster_hostname=os-master1.local

## Hostname used by platform users
openshift_master_cluster_public_hostname=os-master1.public.local

## Application wildcard subdomain
openshift_master_default_subdomain=apps.os-master1.local

openshift_no_proxy='.local,127.0.0.1,localhost,*.example.com,xxx.xxx.0.0/16,xxx.xxx.0.0/16,.cluster.local,.svc'

## identity provider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

## Users being created in the cluster
openshift_master_htpasswd_users={'root': '$apr1$S7Yjf3DW$v1Nm3rWxCLnq0ziSzqxKw/'}

## Persistent storage, NFS
openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_host=zion.local
openshift_hosted_registry_storage_nfs_directory=/volume1/SHARED
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=50Gi

## Other vars
containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

#NFS check bug
openshift_enable_unsupported_configurations=True
#Another Bug 1569476 
skip_sanity_checks=true

openshift_node_kubelet_args="{'eviction-hard': ['memory.available<100Mi'], 'minimum-container-ttl-duration': ['10s'], 'maximum-dead-containers-per-container': ['2'], 'maximum-dead-containers': ['5'], 'pods-per-core': ['10'], 'max-pods': ['25'], 'image-gc-high-threshold': ['80'], 'image-gc-low-threshold': ['60']}"

[OSEv3:vars]

[masters]
os-master1.local

[etcd]
os-master1.local

#[lb]
#os-master1.local

[nodes]
os-master1.local openshift_node_labels="{'region': 'master'}"
os-infra1.local openshift_node_labels="{'region': 'infra'}"
os-node1.local openshift_node_labels="{'region': 'primary'}"
#os-node2.local openshift_node_labels="{'region': 'primary'}"

**Comment by tinu73** [comment]
Did you solve the problem in the meatime? I get the same error
