### ISSUE TITLE
FAILED - RETRYING: Wait for all control plane pods to become ready

### ISSUE THREAD

**Issue by AGr-IMS** [openshift/openshift-ansible#10247]
#### Description
On a multi master install, ansible stops with
FAILED - RETRYING: Wait for all control plane pods to become ready

The commands that are failing:
oc get pod master-controllers-master1.openshift.domain.tld -o json -n kube-system
oc get pod master-controllers-master2.openshift.domain.tld -o json -n kube-system
...

##### Version
ansible-playbook --version
ansible-playbook 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

git describe:
openshift-ansible-3.10.51-1-14-g9feb4b4

##### Steps To Reproduce
1. ansible-playbook openshift-ansible/playbooks/prerequisites.yml
2. ansible-playbook openshift-ansible/playbooks/deploy_cluster.yml

##### Expected Results
openshift-ansible should query pods wihtout fqdn, like:
oc get pod master-controllers-master1 -o json -n kube-system

##### Observed Results
FAILED - RETRYING: Wait for all control plane pods to become ready
failed: [master2.openshift.domain.tld] (item=controllers) => {"attempts": 60, "changed": false, "item": "controllers", "results": {"cmd": "/usr/bin/oc get pod master-controllers-master2.openshift.domain.tld -o json -n kube-system", "results": [{}], "returncode": 0, "stderr": "Error from server (NotFound): pods \"master-controllers-master2.openshift.domain.tld\" not found\n", "stdout": ""}, "state": "list"}

**Comment by AGr-IMS** [comment]
i fixed this task with
openshift.node.nodename.split('.')[0]
but i get the same error again with TASK - name: Wait for Node Registration
i think something other is wrong, here is my inventory:

# Create an OSEv3 group that contains the master, nodes, etcd, and lb groups.
# The lb group lets Ansible configure HAProxy as the load balancing solution.
# Comment lb out if your load balancer is pre-configured.
[OSEv3:children]
masters
nodes
etcd
glusterfs
#lb

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
openshift_release="3.10"
openshift_deployment_type=origin

openshift_disable_check=memory_availability

ansible_ssh_user=root

os_firewall_use_firewalld=true
openshift_use_dnsmasq=true

openshift_docker_insecure_registries=172.30.0.0/16

# Specify that we want to use an external GlusterFS cluster and a native heketi service
openshift_storage_glusterfs_is_native=False
openshift_storage_glusterfs_heketi_is_native=True
# Specify that heketi will use SSH to communicate to the GlusterFS nodes and
# the private key file it will use for authentication
openshift_storage_glusterfs_heketi_executor=ssh
openshift_storage_glusterfs_heketi_ssh_keyfile=/root/.ssh/id_rsa


# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'ldap_auth', 'challenge': 'true', 'login': 'true', 'kind': 'LDAPPasswordIdentityProvider', 'attributes': {'id': ['dn'], 'email': ['mail'], 'name': ['cn'], 'preferredUsername': ['uid']}, 'bindDN': 'openshift@domain.tld', 'bindPassword': 'PASSWORD','insecure': 'false', 'url': 'ldaps://dcro.domain.tld:636/OU=SDV,OU=Abteilung,OU=domain,DC=domain,DC=tld?sAMAccountName?sub?(&(objectClass=user)(memberOf=CN=OpenShift_Admin,OU=Domain_Apps,OU=Group,OU=domain,DC=domain,DC=tld))'}]
openshift_master_ldap_ca_file=/etc/pki/ca-trust/source/anchors/domain-CA.crt

# Native high availbility cluster method with optional load balancer.
# If no lb group is defined installer assumes that a load balancer has
# been preconfigured. For installation the value of
# openshift_master_cluster_hostname must resolve to the load balancer
# or to one or all of the masters defined in the inventory if no load
# balancer is present.
openshift_master_cluster_method=native
openshift_master_cluster_hostname=cluster.openshift.domain.tld
#openshift_master_cluster_public_hostname=lb.openshift.domain.tld
openshift_master_default_subdomain=apps.openshift.domain.tld

# enable ntp on masters to ensure proper failover
openshift_clock_enabled=true


#registry-router selector
openshift_node_groups=[	{ 'name': 'node-router', 'labels': [ 'node-router=true', 'node-role.kubernetes.io/infra=true' ] }, { 'name': 'node-registry', 'labels': [ 'node-registry=true', 'node-role.kubernetes.io/infra=true' ] }, { 'name': 'node-app', 'labels': [ 'node-app=true', 'node-role.kubernetes.io/compute=true' ] }, { 'name': 'node-config-master-infra', 'labels': [ 'node-role.kubernetes.io/master=true','node-role.kubernetes.io/infra=true' ] } ]
openshift_registry_selector='node-registry=true'
openshift_router_selector='node-router=true'
openshift_hosted_router_selector='node-router=true'

[masters]
master1.openshift.domain.tld
master2.openshift.domain.tld
master3.openshift.domain.tld

[etcd]
master1.openshift.domain.tld
master2.openshift.domain.tld
master3.openshift.domain.tld

[nodes]
master1.openshift.domain.tld openshift_node_group_name='node-config-master-infra'
master2.openshift.domain.tld openshift_node_group_name='node-config-master-infra'
master3.openshift.domain.tld openshift_node_group_name='node-config-master-infra'
node1.openshift.domain.tld openshift_node_group_name='node-app' openshift_schedulable=True
node2.openshift.domain.tld openshift_node_group_name='node-app' openshift_schedulable=True
node3.openshift.domain.tld openshift_node_group_name='node-app' openshift_schedulable=True
router-node1.openshift.domain.tld openshift_node_group_name='node-router' openshift_schedulable=false
router-node2.openshift.domain.tld openshift_node_group_name='node-router' openshift_schedulable=false
router-node3.openshift.domain.tld openshift_node_group_name='node-router' openshift_schedulable=false

[glusterfs]
glusterfs1.openshift.domain.tld glusterfs_devices='[ "/dev/sdb" ]'
glusterfs2.openshift.domain.tld glusterfs_devices='[ "/dev/sdb" ]'
glusterfs3.openshift.domain.tld glusterfs_devices='[ "/dev/sdb" ]'

**Comment by moortimis** [comment]
Having the same issue here, let me know if you find a solution. 
Thanks

**Comment by AGr-IMS** [comment]
i added .split('.')[0] to the variable openshift.node.nodename like
openshift.node.nodename.split('.')[0]

In the follwoing TASKs:

openshift-ansible/roles/openshift_control_plane/tasks/main.yml
Wait for all control plane pods to become ready

openshift-ansible/roles/openshift_manage_node/tasks/main.yml
Wait for Node Registration

openshift-ansible/roles/openshift_manage_node/tasks/config.yml
Set node schedulability

**Comment by garvsd** [comment]
Same issue here, tried with all available approaches. Is it Openshift 3.10 or 3.9 a recommended one?

**Comment by MikeWrightDev** [comment]
I tried the workaround 2 posts back and it worked.

BTW, there appears to be activity related to this on the master branch
https://github.com/openshift/openshift-ansible/commit/0411517980204c921fa908cefeacc49b0571e524#diff-54774cd1a74c81a803bc9a139d03f9d6

**Comment by aishenghuomeidaoli** [comment]
@MikeWrightDev what's the solution?

**Comment by mrafieee** [comment]
I had the same problem in Azure, Master nodes were not able to connect to Azure LB, track down the  issue to the VM NIC ,by recreating a new NIC the problem resolved.

in my case effected master node was not able to connect to Masters LB on 8443 port and was timing out on curl.

**Comment by vrutkovs** [comment]
Please collect master logs: https://docs.okd.io/3.11/install_config/master_node_configuration.html#master-node-view-logs

**Comment by maneeshmurali** [comment]
I am also facing the same issue with AWS. 
Openshift Orjin 3.11
FAILED - RETRYING: Wait for control plane pods to appear (53 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (52 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (51 retries left).

Please help.

**Comment by moortimis** [comment]
As far as I've been able to determine this issue is caused by Ansible being unable to contact the PublicMasterUrl. 

Things to check are DNS, your MasterPublucUrl, http_proxy as mentioned above even your route table.

**Comment by maneeshmurali** [comment]
Thanks for the response.

I am getting the below error.
----------------------------------------
failed: [prod.domain.com] (item=etcd) => {"attempts": 60, "changed": false, "item": "etcd", "module_results": {"cmd": "/usr/bin/oc get pod master-etcd-prod.domain.com -o json -n kube-system", "results": [{}], "returncode": 0, "stderr": "Error from server (NotFound): pods \"master-etcd-prod.domain.com\" not found\n", "stdout": ""}, "state": "list"}
----------------------------------------

The pods are created with the name " master-api-ip-172-31-32-96.ec2.internal". I am using AWS single node cluster setup for my lab. It seems the openshift is using AWS local hostname for the pod naming. I have already changed the EC2 hostname to the FQDN but still, the issue persists.

Please help

**Comment by tmalkowski** [comment]
One thing I found was that the ansible playbook actually created iptables rules at the end of the INPUT chain, which in my configuration meant it added the OS_FIREWALL_ALLOW chain *after* my RH-Firewall-1-INPUT chain (which ends in  -j REJECT). Switching the order in iptables manually seems to have resolved it.
