### ISSUE TITLE
Style guide does not cover playbook temporary variables

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#1024]
The style guide doesn't cover temporary variables used in playbooks, which I would suggest should be tmp_<playbook_id>_<var_name> with playbook_id being a short playbook descriptor based on where the playbook is located...  something like c_oc_config could be used for playbooks/common/openshift-cluster/config.yml.

**Comment by detiber** [comment]
@twiest

**Comment by twiest** [comment]
In Ansible 2.0, variables can be scoped using blocks. We might want to use that instead of prefixes for these temporary variables. It's much more intuitive IMO. I'll think about this further.

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit
