### ISSUE TITLE
Style guide - role variable names

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#1026]
Browsing galaxy.ansible.com, I came across the following: https://galaxy.ansible.com/intro#variables

The suggestion is that all role variables (including vars/main.yml) should be prefixed with the role name. This contradicts our style guide suggestion to use shortened prefixes.

As much as the long descriptive naming is a pain to work with, I think sticking with the galaxy best practices and more descriptive names for end users is worth the hassle.

**Comment by detiber** [comment]
@twiest

**Comment by twiest** [comment]
@detiber hmm, yeah, this is something we should definitely consider. I always prefer to use the conventions of the community. I'll think about this further.

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit
