### ISSUE TITLE
Ansible failing assertion openshift.common.deployment_type for Origin

### ISSUE THREAD

**Issue by suryaveerc** [openshift/openshift-ansible#1027]
I am trying to install OpenShift Origin V3 on OpenStack IceHouse  using the ansible installer.

Ansible version is 1.9.4 and I cloned the openshift-ansible yesterday.

**Below is the error log:**
TASK: [openshift_facts | Ensure PyYaml is installed] ************************** 
ok: [192.168.144.132] => (item=PyYAML)

TASK: [openshift_facts | Gather Cluster facts] ******************************** 
ok: [192.168.144.132]

TASK: [openshift_repos | assert ] ********************************************* 
**failed: [192.168.144.132] => {"assertion": "openshift.common.deployment_type in known_openshift_deployment_types", "evaluated_to": false, "failed": true}**

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/suryaveer/config.retry

192.168.144.132            : ok=20   changed=2    unreachable=0    failed=1   
localhost                  : ok=8    changed=0    unreachable=0    failed=0   

**Below is the hosts file:**

[OSEv3:children"]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=centos
ansible_sudo=true
#ansible_ssh_user=root

product_type=openshift
**deployment_type=origin**

[masters]
192.168.144.132 openshift_public_hostname=master.novalocal openshift_ip=10.0.1.163 openshift_public_ip=192.168.144.132

[nodes]
192.168.144.128 openshift_public_hostname=node1.novalocal openshift_ip=10.0.1.164 openshift_public_ip=192.168.144.128 openshift_node_labels="{'region': 'primary', 'zone': 'east'}" 
192.168.144.129 openshift_public_hostname=node2.novalocal openshift_ip=10.0.1.165 openshift_public_ip=192.168.144.129 openshift_node_labels="{'region': 'primary', 'zone': 'west'}"

I searched a lot but could not find any solution for this and as last resort I had open this issue.

Thanks

**Comment by detiber** [comment]
>[OSEv3:children"]

Is this a typo? it should be [OSEv3:children] and that could explain why the variable is reported as being unset...

**Comment by suryaveerc** [comment]
OMG!! Where to hide.. :(

Copy pasted from tutorial and never noticed. Why did it not failed for other things like it did read master, node details and created fact file..

Can you please confirm if I can install OSO V3 using this on OpenStack IceHouse.

Anyways, sorry to open this issue. Closing.

**Comment by detiber** [comment]
@suryaveerc no problem on opening the issue at all.

You should not have an issue installing on OpenStack, you will probably have an issue using the *.novalocal names for openshift_hostname and openshift_public_hostname though, since with nova networking those names will not be resolvable between cluster hosts if they are provisioned on different hypervisor hosts.

If possible, you may want to assign the instances properly resolvable DNS names or use the values of openshift_ip and openshift_public_ip for the respective hostname values.

The main reason the other tasks proceeded is because we use the child group names for configuration, the OSEv3 group is only really used for setting the cluster wide variables.

**Comment by suryaveerc** [comment]
Thanks for the comments. It installed. 
**[centos@master ~]$ oc get nodes**
NAME              LABELS                                                            STATUS    AGE
node1.novalocal   kubernetes.io/hostname=node1.novalocal,region=primary,zone=east   Ready     1h
node2.novalocal   kubernetes.io/hostname=node2.novalocal,region=primary,zone=west   Ready     1h
Let's see if it works further.

Thanks

**Comment by suryaveerc** [comment]
@detiber 
As mentioned by you I am facing the DNS problem. I hope it's fine to state my problem here.

This is the error I get:
F1208 20:49:33.402074       1 deployer.go:65] couldn't get deployment default/docker-registry-1: Get https://master.novalocal:8443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1: **dial tcp: lookup master.novalocal: no such host**

my inventory file has entries like above but I also added new field as suggested by you (hope I did it right)
192.168.144.132 **openshift_public_hostname=192.168.144.132** openshift_ip=10.0.1.170 openshift_public_ip=192.168.144.132 openshift_node_labels="{'region': 'infra', 'zone': 'default'}" 
192.168.144.129 **openshift_public_hostname=192.168.144.129** openshift_ip=10.0.1.171 openshift_public_ip=192.168.144.129 openshift_node_labels="{'region': 'primary', 'zone': 'east'}" 
192.168.144.133 **openshift_public_hostname=192.168.144.133** openshift_ip=10.0.1.172 openshift_public_ip=192.168.144.133 openshift_node_labels="{'region': 'primary', 'zone': 'west'}"

I do not have any local DNS setup and I have added entires in the /etc/hosts as
192.168.144.132 master.novalocal
192.168.144.133 node2.novalocal 
192.168.144.129 node1.novalocal

Please guide me what to do to make it work.
Thanks,

**Comment by detiber** [comment]
@abutcher we should create a bug/issue to track detecting common DNS and IP issues.

**Comment by suryaveerc** [comment]
@detiber I thought it may be problem in my setup, so, didn't opened an issue. Anyways, I'll open it as a issue.

Thanks
