### ISSUE TITLE
`yum-utils` install breaks on F29

### ISSUE THREAD

**Issue by vrutkovs** [openshift/openshift-ansible#10296]
Openshift-ansible should avoid installing `yum-utils` on Fedora 29 - this package seems broken. In any case, its not necessary on Fedora installs

cc @michaelgugino

**Comment by michaelgugino** [comment]
Seems sensible to me.

**Comment by Conan-Kudo** [comment]
`yum-utils` should trigger the installation of `dnf-utils` on Fedora 29, which is probably what is confusing Ansible. Maybe it doesn't handle virtual Provides well?
