### ISSUE TITLE
make http_proxy, no_proxy etc configurable via ansible 

### ISSUE THREAD

**Issue by ivanthelad** [openshift/openshift-ansible#1033]
Files outlined 
docker
node
api,
controller
https://docs.openshift.com/enterprise/3.1/install_config/http_proxies.html

**Comment by edseymour** [comment]
This feature is important as it currently requires manual configuration, subsequent re-runs of ansible installer will back-out the manual changes.

**Comment by abutcher** [comment]
In progress here https://github.com/openshift/openshift-ansible/pull/1385

**Comment by tbielawa** [comment]
The referenced branch has been merged and should take care of these issues.

This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
