### ISSUE TITLE
Docs could include more ami info

### ISSUE THREAD

**Issue by kastork** [openshift/openshift-ansible#1034]
For AWS cluster creation... (With Origin)

Is there a list of recommended ami ids by region and cluster role maintained somewhere?  I've been digging around and only find ids for us-east-1

Alternatively, is there a set of playbooks  that build a Centos or Fedora host for each role (which could then be saved privately as an ami)

**Comment by detiber** [comment]
You should be able to use the official Fedora 23, CentOS 7, and RHEL 7 AMIs for each region.

**Comment by kastork** [comment]
Perhaps I'm reading too much into the pre-reqs and so forth.  (I haven't taken the plunge and tried a deployment yet.)

It seems like a stock Centos image has quite a bit that needs to be done to it before it can be used as a master or node.  I figured there might be AMIs in each region that are already configured to be masters or nodes, or else there might be an ansible playbooks to do that work.

**Comment by detiber** [comment]
@kastork I'm not sure which pre-reqs you are referring to. We test against the stock images for Origin, if using the bin/cluster script it will even pre-configure the Docker storage on a separate EBS volume.

**Comment by detiber** [comment]
There are times we've used custom AMIs, but that is generally to pre-install packages in order to shorten provisioning time.

**Comment by kastork** [comment]
Ok got it.  Thanks.  I'll give it a go with Centos AMIs.

I think the confusion for me came from thus early paragraph in the "advanced installation" area of the docs.
(https://docs.openshift.org/latest/install_config/install/advanced_install.html)

"Prerequisites
Before installing OpenShift, you must first see the general Prerequisites topic to prepare your hosts, which includes verifying system and environment requirements per component type and properly installing and configuring Docker. It also includes installing Ansible version 1.8.4 or later, as the advanced installation method is based on Ansible playbooks and as such requires directly invoking Ansible.

After following the instructions in the Prerequisites topic, you can continue in this topic to Configuring Ansible."
