### ISSUE TITLE
Enabling Authentication Logs

### ISSUE THREAD

**Issue by xyker** [openshift/openshift-ansible#10347]
Not really a bug but more like a lack of documentation.  I am unable to find a way to debug my LDAP authentication by enabling logs in v3.10.

http://v1.uncontained.io/playbooks/troubleshooting/troubleshooting_guide.html
https://www.arctiq.ca/our-blog/2017/8/16/troubleshooting-openshift-ldap-authentication/

The two links above point me to editing /etc/sysconfig/atomic-openshift-master-api with a log level of 4 but that file does not seem to exist in 3.10  I only see this file: /etc/sysconfig/atomic-openshift-node
in a single master, multi-node setup.

The following is my LDAP inventory configuration:

> openshift_master_identity_providers=[{'name': 'ad_auth', 'challenge': 'true', 'login': 'true', 'kind': 'LDAPPasswordIdentityProvider', 'attributes': {'id': ['dn'], 'email': ['mail'], 'name': ['displayName'], 'preferredUsername': ['mail']}, 'bindDN': 'CN=Openshift User,OU=Service Accounts,DC=test,DC=com', 'bindPassword': 'Password',  'insecure': 'true', 'url': 'ldap://ad01.test.com/CN=Admins,OU=Special Access,DC=test,DC=com?mail'}]

git describe
openshift-ansible-3.10.53-1

**Comment by vrutkovs** [comment]
Setting `openshift_master_debug_level: 4` should increase the log level on masters
