### ISSUE TITLE
Add new master on current cluster 

### ISSUE THREAD

**Issue by infrasystemelille** [openshift/openshift-ansible#10351]
#### Description
Description
I would want to add an other master on my openshift cluster. With ansible, the deployment crashes at step "deployment master api and controllers" 

Version
ansible version: 2.7.0
openshift-ansible: last version of origin/release-3.10
ansible-playbook -vvv -i host.dll ../openshift-ansible/playbooks/openshift-master/scaleup.yml

Observed Results
failed: [osm.dll.in.ac-lille.fr] (item=api) => {
    "attempts": 60, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "all_namespaces": null, 
            "content": null, 
            "debug": false, 
            "delete_after": false, 
            "field_selector": null, 
            "files": null, 
            "force": false, 
            "kind": "pod", 
            "kubeconfig": "/etc/origin/master/admin.kubeconfig", 
            "name": "master-api-osm.dll.in.ac-lille.fr", 
            "namespace": "kube-system", 
            "selector": null, 
            "state": "list"
        }
    }, 
    "item": "api", 
    "results": {
        "cmd": "/usr/bin/oc get pod master-api-osm.dll.in.ac-lille.fr -o json -n kube-system", 
        "results": [
            {
                "apiVersion": "v1", 
                "kind": "Pod", 
                "metadata": {
                    "annotations": {
                        "kubernetes.io/config.hash": "26e621142d04fbfc2b664c96aa805c8a", 
                        "kubernetes.io/config.mirror": "26e621142d04fbfc2b664c96aa805c8a", 
                        "kubernetes.io/config.seen": "2018-10-08T12:00:44.207109954+02:00", 
                        "kubernetes.io/config.source": "file", 
                        "scheduler.alpha.kubernetes.io/critical-pod": ""
                    }, 
                    "creationTimestamp": "2018-10-08T10:00:47Z", 
                    "labels": {
                        "openshift.io/component": "api", 
                        "openshift.io/control-plane": "true"
                    }, 
                    "name": "master-api-osm.dll.in.ac-lille.fr", 
                    "namespace": "kube-system", 
                    "resourceVersion": "50223375", 
                    "selfLink": "/api/v1/namespaces/kube-system/pods/master-api-osm.dll.in.ac-lille.fr", 
                    "uid": "0765988d-cae1-11e8-ac48-00505692de01"
                }, 
                "spec": {
                    "containers": [
                        {
                            "args": [
                                "#!/bin/bash\nset -euo pipefail\nif [[ -f /etc/origin/master/master.env ]]; then\n  set -o allexport\n  source /etc/origin/master/master.env\nfi\nexec openshift start master api --config=/etc/origin/master/master-config.yaml --loglevel=${DEBUG_LOGLEVEL:-2}\n"
                            ], 
                            "command": [
                                "/bin/bash", 
                                "-c"
                            ], 
                            "image": "docker.io/openshift/origin-control-plane:v3.10.0", 
                            "imagePullPolicy": "IfNotPresent", 
                            "livenessProbe": {
                                "failureThreshold": 3, 
                                "httpGet": {
                                    "path": "healthz", 
                                    "port": 443, 
                                    "scheme": "HTTPS"
                                }, 
                                "initialDelaySeconds": 45, 
                                "periodSeconds": 10, 
                                "successThreshold": 1, 
                                "timeoutSeconds": 10
                            }, 
                            "name": "api", 
                            "readinessProbe": {
                                "failureThreshold": 3, 
                                "httpGet": {
                                    "path": "healthz/ready", 
                                    "port": 443, 
                                    "scheme": "HTTPS"
                                }, 
                                "initialDelaySeconds": 10, 
                                "periodSeconds": 10, 
                                "successThreshold": 1, 
                                "timeoutSeconds": 10
                            }, 
                            "resources": {}, 
                            "securityContext": {
                                "privileged": true
                            }, 
                            "terminationMessagePath": "/dev/termination-log", 
                            "terminationMessagePolicy": "File", 
                            "volumeMounts": [
                                {
                                    "mountPath": "/etc/origin/master/", 
                                    "name": "master-config"
                                }, 
                                {
                                    "mountPath": "/etc/origin/cloudprovider/", 
                                    "name": "master-cloud-provider"
                                }, 
                                {
                                    "mountPath": "/var/lib/origin/", 
                                    "name": "master-data"
                                }
                            ]
                        }
                    ], 
                    "dnsPolicy": "ClusterFirst", 
                    "hostNetwork": true, 
                    "nodeName": "osm.dll.in.ac-lille.fr", 
                    "restartPolicy": "Always", 
                    "schedulerName": "default-scheduler", 
                    "securityContext": {}, 
                    "terminationGracePeriodSeconds": 30, 
                    "tolerations": [
                        {
                            "effect": "NoExecute", 
                            "operator": "Exists"
                        }
                    ], 
                    "volumes": [
                        {
                            "hostPath": {
                                "path": "/etc/origin/master/", 
                                "type": ""
                            }, 
                            "name": "master-config"
                        }, 
                        {
                            "hostPath": {
                                "path": "/etc/origin/cloudprovider", 
                                "type": ""
                            }, 
                            "name": "master-cloud-provider"
                        }, 
                        {
                            "hostPath": {
                                "path": "/var/lib/origin", 
                                "type": ""
                            }, 
                            "name": "master-data"
                        }
                    ]
                }, 
                "status": {
                    "conditions": [
                        {
                            "lastProbeTime": null, 
                            "lastTransitionTime": "2018-10-08T10:00:47Z", 
                            "status": "True", 
                            "type": "Initialized"
                        }, 
                        {
                            "lastProbeTime": null, 
                            "lastTransitionTime": "2018-10-08T10:00:47Z", 
                            "message": "containers with unready status: [api]", 
                            "reason": "ContainersNotReady", 
                            "status": "False", 
                            "type": "Ready"
                        }, 
                        {
                            "lastProbeTime": null, 
                            "lastTransitionTime": "2018-10-08T10:00:47Z", 
                            "status": "True", 
                            "type": "PodScheduled"
                        }
                    ], 
                    "containerStatuses": [
                        {
                            "containerID": "docker://fb21e920219e7e2ebe9e4d2a6d607d7e97205fdb6cefcf01ba8fde7cbd813776", 
                            "image": "docker.io/openshift/origin-control-plane:v3.10.0", 
                            "imageID": "docker-pullable://docker.io/openshift/origin-control-plane@sha256:7b50902e49af679c5d81ad0f8d556ed83abbce41abe8ac9a458ff3d2bbea29e1", 
                            "lastState": {
                                "terminated": {
                                    "containerID": "docker://fb21e920219e7e2ebe9e4d2a6d607d7e97205fdb6cefcf01ba8fde7cbd813776", 
                                    "exitCode": 255, 
                                    "finishedAt": "2018-10-08T10:06:10Z", 
                                    "reason": "Error", 
                                    "startedAt": "2018-10-08T10:05:28Z"
                                }
                            }, 
                            "name": "api", 
                            "ready": false, 
                            "restartCount": 3, 
                            "state": {
                                "waiting": {
                                    "message": "Back-off 40s restarting failed container=api pod=master-api-osm.dll.in.ac-lille.fr_kube-system(26e621142d04fbfc2b664c96aa805c8a)", 
                                    "reason": "CrashLoopBackOff"
                                }
                            }
                        }
                    ], 
                    "hostIP": "10.202.226.210", 
                    "phase": "Running", 
                    "podIP": "10.202.226.210", 
                    "qosClass": "BestEffort", 
                    "startTime": "2018-10-08T10:00:47Z"
                }
            }
        ], 
        "returncode": 0
    }, 
    "state": "list"
}

Failure summary:

PLAY RECAP *****************************************************************************************************************************************************************************************************
localhost                  : ok=25   changed=0    unreachable=0    failed=0   
osm.dll.in.ac-lille.fr     : ok=299  changed=140  unreachable=0    failed=1   
osm2.dll.in.ac-lille.fr    : ok=60   changed=1    unreachable=0    failed=0   
osm3.dll.in.ac-lille.fr    : ok=28   changed=1    unreachable=0    failed=0   

INSTALLER STATUS ***********************************************************************************************************************************************************************************************
Initialization              : Complete (0:04:19)
Node Bootstrap Preparation  : Complete (0:18:55)
Master Install              : In Progress (0:07:45)
	This phase can be restarted by running: playbooks/openshift-master/config.yml

Additional Information
2 masters(etcd)/3infranodes/3nodes in rhel 7.5 on vmware

Inventory file:
[OSEv3:children]
masters
nodes
etcd
new_masters
new_nodes
new_etcd

[OSEv3:vars]
openshift_template_service_broker_namespaces=['openshift']
openshift_master_default_subdomain=apps.dll.in.ac-lille.fr
ansible_ssh_user=root
debug_level=2
openshift_master_cluster_hostname=openshift.dll.in.ac-lille.fr
openshift_master_cluster_public_hostname=openshift.dll.in.ac-lille.fr
#deployment_type=origin
openshift_deployment_type=origin
openshift_release="3.10"
openshift_clock_enabled=true
ansible_enable_service_broker=true
ansible_service_broker_install=true
openshift_service_catalog_install=true
openshift_enable_service_catalog=true
template_service_broker_install=true
template_enable_service_broker=true
openshift_hosted_etcd_storage_kind=dynamic
openshift_hosted_etcd_storage_volume_size=10G
openshift_hosted_etcd_storage_access_modes=["ReadWriteOnce"]
openshift_hosted_etcd_storage_volume_name=etcd-vol
dynamic_volumes_check=False
openshift_use_openshift_sdn=true

openshift_master_etcd_urls=['https://osm2.dll.in.ac-lille.fr:2379 https://osm3.dll.in.ac-lille.fr:2379']

#openshift_web_console_nodeselector='node-role.kubernetes.io/infra=true'

openshift_master_identity_providers=[{'name': 'ldap_ac-lille', 'challenge': 'true', 'login': 'true', 'kind': 'LDAPPasswordIdentityProvider', 'attributes': {'id': ['dn'], 'email': ['mail'], 'name': ['cn'], 'preferredUsername': ['uid']}, 'bindDN': 'uid=appli_openshift,ou=applications,ou=ac-lille,ou=education,o=gouv,c=fr', 'bindPassword': '', 'ca': '', 'insecure': 'true', 'url': "ldap://:389/ou=ac-lille,ou=education,o=gouv,c=fr?uid?sub?(&(|(fredulilsfmembre=5236;*)(fredulilsfmembre=*;5236;*)(uid=adminoc))(dateff=X))"}]

openshift_master_named_certificates=[{"certfile": "/home//git/openshift/configuration/before_openshift/https/dll.in.ac-lille.fr.crt", "keyfile": "/home//git/openshift/configuration/before_openshift/https/dll.in.ac-lille.fr.key", "cafile": "/home//git/openshift/configuration/before_openshift/https/dll.in.ac-lille.fr.ca"}]
openshift_master_overwrite_named_certificates=true

openshift_hosted_router_certificate={"certfile": "/home//git/openshift/configuration/before_openshift/https/apps.dll.in.ac-lille.fr.crt", "keyfile": "/home//git/openshift/configuration/before_openshift/https/apps.dll.in.ac-lille.fr.key", "cafile": "/home//git/openshift/configuration/before_openshift/https/apps.dll.in.ac-lille.fr.ca"}

openshift_hosted_registry_routehost=registry.apps.dll.in.ac-lille.fr
openshift_hosted_registry_routecertificates={"certfile": "/home//git/openshift/configuration/before_openshift/https/apps.dll.in.ac-lille.fr.crt", "keyfile": "/home//git/openshift/configuration/before_openshift/https/apps.dll.in.ac-lille.fr.key", "cafile": "/home//git/openshift/configuration/before_openshift/https/apps.dll.in.ac-lille.fr.ca"}

osm_cluster_network_cidr=172.18.0.0/16
openshift_portal_net=172.19.0.0/16
openshift_docker_options='--insecure-registry 172.18.0.0/15'
openshift_router_selector='node-role.kubernetes.io/infra=true'
openshift_registry_selector='node-role.kubernetes.io/infra=true'
osm_default_node_selector='node-role.kubernetes.io/compute=true'
openshift_master_api_port=443
openshift_disable_check=docker_image_availability,memory_availability,disk_availability,package_availability,docker_storage
openshift_http_proxy=http://10.202.226.219:3128
openshift_https_proxy=https://10.202.226.219:3128
openshift_no_proxy='172.18.0.0/15'

openshift_hosted_registry_storage_kind=object
openshift_hosted_registry_storage_provider=s3
openshift_hosted_registry_storage_s3_accesskey=
openshift_hosted_registry_storage_s3_secretkey=
openshift_hosted_registry_storage_s3_regionendpoint=
openshift_hosted_registry_storage_s3_bucket=docker-registry-dll
openshift_hosted_registry_storage_s3_region=default
openshift_hosted_registry_storage_s3_chunksize=26214400
openshift_hosted_registry_storage_s3_rootdirectory=/registry
openshift_hosted_registry_pullthrough=true
openshift_hosted_registry_acceptschema2=true
openshift_hosted_registry_enforcequota=false

[masters]
osm2.dll.in.ac-lille.fr
osm3.dll.in.ac-lille.fr

[etcd]
osm2.dll.in.ac-lille.fr
osm3.dll.in.ac-lille.fr

[nodes]
osm2.dll.in.ac-lille.fr openshift_node_group_name='node-config-master'
osm3.dll.in.ac-lille.fr openshift_node_group_name='node-config-master'
osi1.dll.in.ac-lille.fr openshift_node_group_name='node-config-infra'
osi2.dll.in.ac-lille.fr openshift_node_group_name='node-config-infra'
osi3.dll.in.ac-lille.fr openshift_node_group_name='node-config-infra'
osn1.dll.in.ac-lille.fr openshift_node_group_name='node-config-compute'
osn2.dll.in.ac-lille.fr openshift_node_group_name='node-config-compute'
osn3.dll.in.ac-lille.fr openshift_node_group_name='node-config-compute'

[proxy]
osp.dll.in.ac-lille.fr

[appnodes]
osn1.dll.in.ac-lille.fr
osn2.dll.in.ac-lille.fr
osn3.dll.in.ac-lille.fr

[new_masters]
osm.dll.in.ac-lille.fr

[new_nodes]
osm.dll.in.ac-lille.fr openshift_node_group_name='node-config-master'

[new_etcd]
osm.dll.in.ac-lille.fr

**Comment by michaelgugino** [comment]
Could be any number of reasons for this to fail.  You'll need to investigate why the static pod failed to come up.

**Comment by DanyC97** [comment]
@infrasystemelille right off bat i'd suggest you always format the code and the logs output. If the log output is too big then please use gist or any other alternative and provide the link.

if you just look through the open github issues, you can easily find 5/6 where other people provided output from  `journald`/ pod logs output etc

**Comment by michaelgugino** [comment]
> What do you need to investigate on this problem ? Do you need more logs or configuration files ?

@infrasystemelille this is not a support forum, it's for reporting bugs of openshift-ansible.  We do try to help users with simple problems here sometimes but we can't solve everything in this manner.  You can try the user mailing lists for additional support, or please consider openshift-enterprise.

**Comment by michaelgugino** [comment]
@nagonzalez if installing outside of rpm, best to use the requirements.txt for each release.  We test each release of openshift-ansible against a specific version of ansible as ansible changes behavior somewhat frequently; eg, for 3.10: https://github.com/openshift/openshift-ansible/blob/release-3.10/requirements.txt

**Comment by nagonzalez** [comment]
ahh, very cool. Didn't realize that was there.  I'll use that from now on
