### ISSUE TITLE
Configmap for node-config-master-crio must be present

### ISSUE THREAD

**Issue by felsys** [openshift/openshift-ansible#10360]
#### Description

3.9 > 3.10 upgrade fails with "Configmap for node-config-master-crio must be present". Cluster is running on atomic, not even using crio. Configmap is otherwise defined in inventory for master: openshift_node_group_name=node-config-master and worker nodes: openshift_node_group_name=node-config-compute

##### Version

ansible-playbook 2.6.3

git: openshift-ansible-3.10.53-1-2-gb839d82

##### Steps To Reproduce
1. Run .../v3_10/upgrade.yml playbook on a 3.9 cluster

##### Expected Results
Upgrade from 3.9 > 3.10

##### Observed Results

```
FAILED! => {"changed": false, "msg": "Configmap for node-config-master-crio must be present"}
```

**Comment by michaelgugino** [comment]
@feld-ims We don't create the actual configmaps for node-configs during upgrades.  You need to do that manually as there's no way for us to know how to build them from your existing node configs.
