### ISSUE TITLE
unable to run pre-req playbook on RHEL 7.5 single master / 3 etc /10 worker nodes setup.  fails with python-docker is not installed

### ISSUE THREAD

**Issue by trek-e** [openshift/openshift-ansible#10365]
#### Description

Provide a brief description of your issue here. For example:

ansible playbook for prerequisites fails at the task:  TASK [Ensure openshift-ansible installer package deps are installed]

with the error "No package matching 'python-docker' found available, installed or updated"

##### Version

Please put the following version information in the code block
indicated below.

ansible --version
ansible 2.6.5
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

If you're operating from a **git clone**:

openshift-ansible-3.11.21-1-2-g8d40299

If you're running from playbooks installed via RPM

not installed

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. populate a hosts file with server detail

[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=openshift-enterprise

[masters]
master.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.41

[etcd]
etcd1.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.97
etcd2.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.98
etcd3.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.99

[nodes]
node1.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.194
node2.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.195
node3.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.196
node4.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.198
node5.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.199
node6.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.200
node7.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.25
node8.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.91
node9.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.27
node10.thinkagilecp.asg.lenovo.lab ansible_ssh_host=10.8.52.28

2. [step 2]

execute (as root) :  ansible-playbook -i /etc/ansible/hosts playbooks/prerequisites.yml -u root --ask-pass

##### Expected Results
Describe what you expected to happen.

script to run successfully

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

script runs for ~ 5m and then pauses for retries

```
Example command and output or error messages
```
output from task:

FAILED - RETRYING: Ensure openshift-ansible installer package deps are installed (1 retries left).
fatal: [node6.thinkagilecp.asg.lenovo.lab]: FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'python-docker' found available, installed or updated", "rc": 126, "results": ["python-ipaddress-1.0.16-2.el7.noarch providing python-ipaddress is already installed", "iproute-4.11.0-14.el7.x86_64 providing iproute is already installed", "dbus-python-1.1.1-9.el7.x86_64 providing dbus-python is already installed", "libsemanage-python-2.5-11.el7.x86_64 providing libsemanage-python is already installed", "No package matching 'python-docker' found available, installed or updated"]}
FAIL

(for each node) 

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

Red Hat Enterprise Linux Server release 7.5 (Maipo)

```
EXTRA INFORMATION GOES HERE
```

**Comment by vrutkovs** [comment]
Seems `extras` repo was not added. Are you using `rhsub_user / rhsub_pass` or `rhsub_ak \ rhsub_orgid` to subscribe nodes correctly?

**Comment by trek-e** [comment]
thank you.  that got me going in the right direction.  I seem to be missing the documentation for this, where would it be posted?  i seem to be finding issues that are described somewhere that I need to set up but not seeing where that is.

**Comment by vrutkovs** [comment]
Manual host subscription is described in https://docs.openshift.com/container-platform/3.10/install/host_preparation.html#host-registration. `rhsub_user` is prob

Filed https://github.com/openshift/openshift-docs/issues/12396 to describe these options in documentation
