### ISSUE TITLE
Error Enabling HTPasswdPasswordIdentityProvider / 3.10

### ISSUE THREAD

**Issue by xyker** [openshift/openshift-ansible#10389]
#### Description

Enabling HTpasswdPasswordIdentityProvider returns the following error message:

> Message:  The conditional check 'item.kind == 'HTPasswdPasswordIdentityProvider'' failed. The error was: error while evaluating conditional (item.kind == 'HTPasswdPasswordIdentityProvider'): 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'kind'
> 
>                The error appears to have been in '/openshift-ansible/roles/openshift_control_plane/tasks/htpass_provider.yml': line 2, column 3, but may
>                be elsewhere in the file depending on the exact syntax problem.
> 
>                The offending line appears to be:
> 
>                ---
>                - name: Install httpd-tools if needed
>                  ^ here

Here is my inventory configuration for the identity providers:

openshift_master_identity_providers=[{'name':'htpasswd', 'login':'true, 'challenge':'true', 'kind':'HTPasswdPasswordIdentityProvider'},{'name': 'ad_auth', 'challenge': 'true', 'login': 'true', 'kind': 'LDAPPasswordIdentityProvider', 'attributes': {'id': ['dn'], 'email': ['mail'], 'name': ['displayName'], 'preferredUsername': ['sAMAccountName']}, 'bindDN': 'CN=user,DC=test,DC=com', 'bindPassword': 'password',  'insecure': 'true', 'url': 'ldap://ad1.test.com/DC=test,DC=com?sAMAccountName?sub?(&(sAMAccountName=*)(memberOf=CN=openshift,OU=Users,DC=test,dc=com))'}]

I was able to successfully deploy a cluster with just the LDAP identity provider.
##### Version

```
ansible --version
ansible 2.6.5

git describe
openshift-ansible-3.10.53-1-8-g5bfd3d7

```

##### Steps To Reproduce
1. Run deploy_cluster playbook with an inventory file that has a similar configuration as above.

##### Expected Results
I am expecting that the deployment succeeds with two possible identity providers.

##### Observed Results

> Message:  The conditional check 'item.kind == 'HTPasswdPasswordIdentityProvider'' failed. The error was: error while evaluating conditional (item.kind == 'HTPasswdPasswordIdentityProvider'): 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'kind'
> 
>                The error appears to have been in '/openshift-ansible/roles/openshift_control_plane/tasks/htpass_provider.yml': line 2, column 3, but may
>                be elsewhere in the file depending on the exact syntax problem.
> 
>                The offending line appears to be:
> 
>                ---
>                - name: Install httpd-tools if needed
>                  ^ here

**Comment by nagonzalez** [comment]
You may be missing a`'` on the first "true"

See below:
{'name':'htpasswd', 'login':'true`'`, 'challenge':'true', 'kind':'HTPasswdPasswordIdentityProvider'}

**Comment by vrutkovs** [comment]
Incorrect INI syntax in inventory, please reopen if the issue is reproduced again.

Docs are recommending to use YAML inventory to store group vars to make sure the syntax can be validated
