### ISSUE TITLE
Scale up did not generate any cert for new node

### ISSUE THREAD

**Issue by mrafieee** [openshift/openshift-ansible#10405]
#### Description
I have the metrics enabled in my cluster.
I created new node and used scaleup.yaml to scale the existing cluster up but looks like the metrics did not work fine.

##### Version
```
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

Server https://****:443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce
`oc get nodes` returns the full node list
`oc add top nodes` does not return the nodes I added after.

##### Additional Information
tried `oc logs` and got `stats/summary/: x509: certificate is valid for`

I tried the redeploy the certificates for nodes and the issue resolved, the question why I need to redeploy the whole cluster cert while only new nodes need the certs, this solution does not looking like logical, yet I request a fix or new feat on scaleup module.

**Comment by michaelgugino** [comment]
@ewolinetz ptal

**Comment by ewolinetz** [comment]
@rubenvp8510
