### ISSUE TITLE
Approve node certificate when bootstrapping - V3.10

### ISSUE THREAD

**Issue by thiyagu06** [openshift/openshift-ansible#10403]
#### Description

I am trying to install 1 Master,etc and 1 node cluster in RHEL 7.5. This is the fresh time installation of openshift in newly created VM

##### Version

* ansible version - 2.4.6.0

git describe

openshift-ansible-3.10.53-1-19-g29d0a16

##### Steps To Reproduce

ansible-playbook openshift-ansible/playbooks/prerequisites.yml
ansible-playbook openshift-ansible/playbooks/deploy_cluster.yml

Inventory File Conetent:

[OSEv3:children]
masters
nodes
etcd

[masters]
master.myhost.com

[etcd]
master.myhost.com

[nodes]
master.myhost.com openshift_node_group_name='node-config-master-infra'
app-node.myhost.com openshift_node_group_name='node-config-compute'

[OSEv3:vars]

ansible_user=root

openshift_deployment_type=openshift-enterprise

openshift_master_default_subdomain=myhost.com

debug_level=2

docker_version="1.13.1"
 etcd_debug=true

openshift_master_api_port=8443
openshift_master_console_port=8443

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

openshift_disable_check=docker_image_availability

##### Expected Results

The cluster should be up and running

```
Example command and output or error messages
```

##### Observed Results

 {"all_subjects_found": ["subject=/O=system:nodes/CN=system:node:master-dev\n", "subject=/O=system:nodes/CN=system:node:master-dev\n", "subject=/O=system:nodes/CN=system:node:master-dev\n", "subject=/O=system:nodes/CN=system:node:master-dev\n"], "attempts": 30, "changed": false, "client_approve_results": [], "client_csrs": {}, "failed": true, "msg": "Could not find csr for nodes: app-node-dev", "oc_get_nodes": {"apiVersion": "v1", "items": [{"apiVersion": "v1", "kind": "Node", "metadata": {"annotations": {"volumes.kubernetes.io/controller-managed-attach-detach": "true"}, "creationTimestamp": "2018-10-15T12:19:17Z", "labels": {"beta.kubernetes.io/arch": "amd64", "beta.kubernetes.io/os": "linux", "kubernetes.io/hostname": "master-dev", "node-role.kubernetes.io/infra": "true", "node-role.kubernetes.io/master": "true"}, "name": "master-dev", "namespace": "", "resourceVersion": "2129", "selfLink": "/api/v1/nodes/master-dev", "uid": "89a7fc80-d074-11e8-a137-fa163e342ea4"}, "spec": {"externalID": "master-dev"}, "status": {"addresses": [{"address": "10.106.22.105", "type": "InternalIP"}, {"address": "master-dev", "type": "Hostname"}], "allocatable": {"cpu": "8", "hugepages-1Gi": "0", "hugepages-2Mi": "0", "memory": "16163964Ki", "pods": "250"}, "capacity": {"cpu": "8", "hugepages-1Gi": "0", "hugepages-2Mi": "0", "memory": "16266364Ki", "pods": "250"}, "conditions": [{"lastHeartbeatTime": "2018-10-15T12:26:47Z", "lastTransitionTime": "2018-10-15T12:19:09Z", "message": "kubelet has sufficient disk space available", "reason": "KubeletHasSufficientDisk", "status": "False", "type": "OutOfDisk"}, {"lastHeartbeatTime": "2018-10-15T12:26:47Z", "lastTransitionTime": "2018-10-15T12:19:09Z", "message": "kubelet has sufficient memory available", "reason": "KubeletHasSufficientMemory", "status": "False", "type": "MemoryPressure"}, {"lastHeartbeatTime": "2018-10-15T12:26:47Z", "lastTransitionTime": "2018-10-15T12:19:09Z", "message": "kubelet has no disk pressure", "reason": "KubeletHasNoDiskPressure", "status": "False", "type": "DiskPressure"}, {"lastHeartbeatTime": "2018-10-15T12:26:47Z", "lastTransitionTime": "2018-10-15T12:19:09Z", "message": "kubelet has sufficient PID available", "reason": "KubeletHasSufficientPID", "status": "False", "type": "PIDPressure"}, {"lastHeartbeatTime": "2018-10-15T12:26:47Z", "lastTransitionTime": "2018-10-15T12:24:07Z", "message": "kubelet is posting ready status", "reason": "KubeletReady", "status": "True", "type": "Ready"}], "daemonEndpoints": {"kubeletEndpoint": {"Port": 10250}}, "images": [{"names": ["registry.access.redhat.com/openshift3/ose-node@sha256:93f9cbad56316639acde0e967246d11502835e2f0997db1990043707a3ced110", "registry.access.redhat.com/openshift3/ose-node:v3.10"], "sizeBytes": 1302399885}, {"names": ["registry.access.redhat.com/openshift3/ose-control-plane@sha256:4f45512cf0ef429c62aed894fb296509634bd009f4d1773b5dfe0b171be96732", "registry.access.redhat.com/openshift3/ose-control-plane:v3.10"], "sizeBytes": 788989223}, {"names": ["registry.access.redhat.com/rhel7/etcd@sha256:c67c6b125e47a68ad12c361f137f4c314a81d64ba64486f99e690d5022dde9b3", "registry.access.redhat.com/rhel7/etcd:3.2.22"], "sizeBytes": 255998747}, {"names": ["registry.access.redhat.com/openshift3/ose-pod@sha256:edeebeb143fcc21c470158f997704e1fb3903fd1e010d8d8a3be50d2e4093295", "registry.access.redhat.com/openshift3/ose-pod:v3.10", "registry.access.redhat.com/openshift3/ose-pod:v3.10.45"], "sizeBytes": 214263974}], "nodeInfo": {"architecture": "amd64", "bootID": "62617a7f-7f0f-45bf-b7df-982e5c8c22e4", "containerRuntimeVersion": "docker://1.13.1", "kernelVersion": "3.10.0-862.14.4.el7.x86_64", "kubeProxyVersion": "v1.10.0+b81c8f8", "kubeletVersion": "v1.10.0+b81c8f8", "machineID": "9804f951eb674e1385035b69d50c2ee1", "operatingSystem": "linux", "osImage": "OpenShift Enterprise", "systemUUID": "9804F951-EB67-4E13-8503-5B69D50C2EE1"}}}], "kind": "List", "metadata": {"resourceVersion": "", "selfLink": ""}}, "rc": 0, "server_approve_results": [], "server_csrs": null, "state": "unknown", "unwanted_csrs": [{"apiVersion": "certificates.k8s.io/v1beta1", "kind": "CertificateSigningRequest", "metadata": {"creationTimestamp": "2018-10-15T12:19:17Z", "generateName": "csr-", "name": "csr-7w7wj", "namespace": "", "resourceVersion": "442", "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/csr-7w7wj", "uid": "896db8d3-d074-11e8-a137-fa163e342ea4"}, "spec": {"groups": ["system:masters", "system:cluster-admins", "system:authenticated"], "request": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlIME1JR2FBZ0VBTURneEZUQVRCZ05WQkFvVERITjVjM1JsYlRwdWIyUmxjekVmTUIwR0ExVUVBeE1XYzNsegpkR1Z0T201dlpHVTZiV0Z6ZEdWeUxXUmxkakJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQnh3CjU2V1JKR09FMmxTc0RJMDJXSllBVXd0QjBLUWtyY052QVdWY3NaTVhCMGQrYXFSODlOZzZWQjkrNng5NGtaWFMKKytlRTkwVlQ5VFZqcnU1Tm1jS2dBREFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBbTlJUmRjOWRVT25Wbmg2ZQpWV0p1SStxdFdoU3dzdlJrOW14N2Z6LzFISnNDSVFEalBPZEExUjdycEliRWx6Z0FvNEFVdURidTAySWd6aUpQCml2ZHlZeXliTHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K", "usages": ["digital signature", "key encipherment", "client auth"], "username": "system:admin"}, "status": {"certificate": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNkVENDQVYyZ0F3SUJBZ0lVRVZCNVREUHRhQzBpdFNwdHVBWElDMTViZnIwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pqRWtNQ0lHQTFVRUF3d2JiM0JsYm5Ob2FXWjBMWE5wWjI1bGNrQXhOVE01TmpBMU9EVTRNQjRYRFRFNApNVEF4TlRFeU1UUXdNRm9YRFRFNU1UQXhOVEV5TVRRd01Gb3dPREVWTUJNR0ExVUVDaE1NYzNsemRHVnRPbTV2ClpHVnpNUjh3SFFZRFZRUURFeFp6ZVhOMFpXMDZibTlrWlRwdFlYTjBaWEl0WkdWMk1Ga3dFd1lIS29aSXpqMEMKQVFZSUtvWkl6ajBEQVFjRFFnQUVISERucFpFa1k0VGFWS3dNalRaWWxnQlRDMEhRcENTdHcyOEJaVnl4a3hjSApSMzVxcEh6MDJEcFVIMzdySDNpUmxkTDc1NFQzUlZQMU5XT3U3azJad3FOVU1GSXdEZ1lEVlIwUEFRSC9CQVFECkFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRklzWUJiaHlXNjBFSXVsVHl4WWczRGhEYVhEL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVVDV1FjbmxvKwpZZGt3V3RwUy9TWXhoNzNFVncvY3pvdXB0M1VuM013ZEYxcjVFM2JGaEliTFNsR2VTeVoxblV4TWtjY3ZnVjlFCnBXV3g1V0U1bVRuUld4WEtMVHBVU1REei92dFJLTUxUNllueHJ1MysveEN0M0NCc1EwTnV5cnNYVzZTVjY0YWYKUHY0bWxSL3VrbmFnemYrNDM4N2JxZjhPb0I0M3Fmci9PeTV4ZEwvSnN3bENFQURPTEI0YlRNckIxbkk3dGNBSgpybEt2a1BuVEhMODFpS1dWanBNcGxpc29MdkNWU0R3M1FIcDVDUG1zQTErMGtXVzgyN2RCdlBaa05DRG9mcGlPCkJkWHR0VVMxNjBPSW9mampzdEFhYjBXUDQ2VGRuWHljcXdHdDdObEVKK2s3bk4xbFd1TFFRVG1VeTNWSUFVaTUKNUY4aEFEZU5Jb3QzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K", "conditions": [{"lastUpdateTime": "2018-10-15T12:19:27Z", "message": "Auto approving kubelet client certificate after SubjectAccessReview.", "reason": "AutoApproved", "type": "Approved"}]}}, {"apiVersion": "certificates.k8s.io/v1beta1", "kind": "CertificateSigningRequest", "metadata": {"creationTimestamp": "2018-10-15T12:23:56Z", "generateName": "csr-", "name": "csr-8p7sx", "namespace": "", "resourceVersion": "1884", "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/csr-8p7sx", "uid": "2ffca8c5-d075-11e8-a137-fa163e342ea4"}, "spec": {"groups": ["system:nodes", "system:authenticated"], "request": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQlpUQ0NBUXdDQVFBd09ERVZNQk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVI4d0hRWURWUVFERXhaegplWE4wWlcwNmJtOWtaVHB0WVhOMFpYSXRaR1YyTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFCjAwTjBNU1VVTDVhMGQ5VU5XcnRjazhPMGlVK0pRZms0bXRlM2tDNEs3bjN5TEVuTkI3KzF3TVNIUUNqaFQ4cXMKTHY3MEJFWTNYMC9ZZ3BYY3F0VU12S0J5TUhBR0NTcUdTSWIzRFFFSkRqRmpNR0V3WHdZRFZSMFJCRmd3Vm9JSwpiV0Z6ZEdWeUxXUmxkb0lBaHdRS2FoWnBoeEQrZ0FBQUFBQUFBUGdXUHYvK05DNmtod1NzRVFBQmh4RCtnQUFBCkFBQUFBR3dpenYvK1JlOFRod1FLZ0FBQmh4RCtnQUFBQUFBQUFNVGs5Zi8rU0hKVE1Bb0dDQ3FHU000OUJBTUMKQTBjQU1FUUNJRytRSkt4eUtBYUlTMDE5NWtyekRBbXhuV2pBUW9hK1dzc3BiZHJMbTZtYkFpQkFtV0NQRWRxdApFaXRnanJnZm82U1RKZlNkTUE2OXlLdFJFbGVJYk96djl3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==", "usages": ["digital signature", "key encipherment", "server auth"], "username": "system:node:master-dev"}, "status": {}}, {"apiVersion": "certificates.k8s.io/v1beta1", "kind": "CertificateSigningRequest", "metadata": {"creationTimestamp": "2018-10-15T12:21:53Z", "generateName": "csr-", "name": "csr-hz5q4", "namespace": "", "resourceVersion": "1121", "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/csr-hz5q4", "uid": "e67cf6a4-d074-11e8-a137-fa163e342ea4"}, "spec": {"groups": ["system:nodes", "system:authenticated"], "request": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQlV6Q0IrZ0lCQURBNE1SVXdFd1lEVlFRS0V3eHplWE4wWlcwNmJtOWtaWE14SHpBZEJnTlZCQU1URm5ONQpjM1JsYlRwdWIyUmxPbTFoYzNSbGNpMWtaWFl3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJ4Ck9tR1NLQ2taY0E2RkpzaVJHbHJPTkRwNEsxUk8ySzVuZUVoNmgzbTBraW82ejZYQWRZdlZzN0NDZk41aFl5UU0KcDZSSHIrU1poSWJrQ2FUcHc5RCtvR0F3WGdZSktvWklodmNOQVFrT01WRXdUekJOQmdOVkhSRUVSakJFZ2dwdApZWE4wWlhJdFpHVjJnZ0NIQkFwcUZtbUhFUDZBQUFBQUFBQUErQlkrLy80MExxU0hCS3dSQUFHSEJBcUFBQUdICkVQNkFBQUFBQUFBQXhQcm0vLzUzSVFRd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFLNWtOZDZUUWRHZmo4dFAKaGdKeXNGL054QmViME9KSWRkaytlMnZlVVdOQ0FpQjFiaVRmSEJLMUd0ODk3TFg3SFU1cFdpdGpxZlF1aVJLVQpINHNwQndpS0l3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==", "usages": ["digital signature", "key encipherment", "server auth"], "username": "system:node:master-dev"}, "status": {}}, {"apiVersion": "certificates.k8s.io/v1beta1", "kind": "CertificateSigningRequest", "metadata": {"creationTimestamp": "2018-10-15T12:19:17Z", "generateName": "csr-", "name": "csr-svv8r", "namespace": "", "resourceVersion": "5", "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/csr-svv8r", "uid": "896fe6a2-d074-11e8-a137-fa163e342ea4"}, "spec": {"groups": ["system:masters", "system:cluster-admins", "system:authenticated"], "request": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQlV6Q0IrZ0lCQURBNE1SVXdFd1lEVlFRS0V3eHplWE4wWlcwNmJtOWtaWE14SHpBZEJnTlZCQU1URm5ONQpjM1JsYlRwdWIyUmxPbTFoYzNSbGNpMWtaWFl3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNaCkkrWTlERWlRVy95cGRzRTdwNmNRMVlvT0J4a2dXUThsOE1ELzRVVEpKOEx0Y0JFcGRTbUE4dldGQ04yU2JEMWsKOW9jOXZ3KzhiZWhYck1sMG9GMkFvR0F3WGdZSktvWklodmNOQVFrT01WRXdUekJOQmdOVkhSRUVSakJFZ2dwdApZWE4wWlhJdFpHVjJnZ0NIQkFwcUZtbUhFUDZBQUFBQUFBQUErQlkrLy80MExxU0hCS3dSQUFHSEJBcUFBQUdICkVQNkFBQUFBQUFBQXhQcm0vLzUzSVFRd0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ1lKQUMzMjg3elpDNjdaVm4KVGpIam5CN3N0bFpTUzdsS3lmRnBSOVI2ZytrQ0lRQ2I5TzNNWWtPRFpMbSt1a21YZmtBaGg1cWo2bDZRY2RMdwpWRWl6a0J4QUxBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==", "usages": ["digital signature", "key encipherment", "server auth"], "username": "system:admin"}, "status": {}}]}

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.5

**Comment by michaelgugino** [comment]
@thiyagu06 it appears the node process did not start on your compute node and has not requested a CSR.  You'll need to investigate why that is.

**Comment by SteffenSeckler** [comment]
@michaelgugino thanks for the hint. had a similar error, appears that while renaming the nodes at some point some wrong configuration was taking place, s.t. the certificate could not be requested due to wrong certificate checks
