### ISSUE TITLE
ntp

### ISSUE THREAD

**Issue by timothysc** [openshift/openshift-ansible#1041]
I saw no references in the manual on setting up clock synchronization.  

Does the installer setup and configure some sane defaults?  If not, it really should.  

e.g. chrony on atomic ntpclient on EL7

/cc @scollier

**Comment by detiber** [comment]
Can we rely on the default config for both?

At a minimum, we'll want to provide a flag to disable ntp config.

**Comment by timothysc** [comment]
I believe there are sane defaults, but we'll likely need to document.

**Comment by sdodson** [comment]
In addition to enabling ntp should we add a task early on that ensures
they're no more than $x seconds off of each other? What's the maximum diff
we can handle?

**Comment by detiber** [comment]
@sdodson how do we ensure time diff though?

Remember that hosts may not run fully in parallel depending on the configured number of forks. Also, there are any number of SSH related issues that could cause the tasks to run at different times on each host.

The most accurate test I can think of is to ensure they are all using the same time server and use the ntp client to get the skew from the server.

**Comment by timothysc** [comment]
I believe the defaults are sane.  +1 for flag.

**Comment by timothysc** [comment]
/cc @ncdc

xref : https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/getting-started-with-containers/#preparing_to_deploy_containers_with_kubernetes 

"Configure Network Time Protocol: All systems in the cluster (master and nodes) need to have their time synced together. Refer to the RHEL 7 System Administrator’s Guide for instruction on setting up Network Time Protocol daemon (ntpd) or Chrony Daemon (chronyd) on those systems." - yadda yadda
