### ISSUE TITLE
rhel_repos.yml arbitrary check

### ISSUE THREAD

**Issue by e-minguez** [openshift/openshift-ansible#10421]
https://github.com/openshift/openshift-ansible/blob/52cfbfa2f13cc43205c1065d15f4131463f1551b/roles/openshift_repos/tasks/rhel_repos.yml#L15-L19

It only checks that there are 4 'Red Hat' repos enabled, but no the names of those repositories.

**Comment by sdodson** [comment]
https://docs.ansible.com/ansible/2.5/modules/rhsm_repository_module.html#rhsm-repository-module seems to provide a reasonably idempotent pattern, enable the repos we care about, disable all the repos that don't match that.

But even then, this code is problematic. What if I want some extra repo enabled? It all seems very single use.

What do you think?
