### ISSUE TITLE
Cannot login to web console in version 3.10

### ISSUE THREAD

**Issue by watsonb** [openshift/openshift-ansible#10426]
#### Description

After a fresh installation of Open Shift Enterprise 3.10, I cannot login to the Web (Management) Console.

##### Version

```bash
# ansible version
(venv_ansible_2.6.2) [watsonb@ben-dev1 openshift-ansible]$ ansible --version
ansible 2.6.2
  config file = /home/watsonb/workspace/github/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/watsonb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/watsonb/venv_ansible_2.6.2/lib/python2.7/site-packages/ansible
  executable location = /home/watsonb/venv_ansible_2.6.2/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

# git info
(venv_ansible_2.6.2) [watsonb@ben-dev1 openshift-ansible]$ git status
# On branch release-3.10
# Your branch is ahead of 'origin/release-3.10' by 8 commits.
#   (use "git push" to publish your local commits)
#
nothing to commit, working directory clean
(venv_ansible_2.6.2) [watsonb@ben-dev1 openshift-ansible]$ git describe
openshift-ansible-3.10.53-1-16-g1bdec09
```

##### Steps To Reproduce
1. spin up 8 fresh, patched, RHEL 7.5 instances (success)
2. run prerequisites.yml playbook (success)
3. run deploy_cluster.yml playbook (success)
4. login to cluster via `oc login -u system:admin -n default` (success)
5. login as any user/password via the web console (fails)

##### Expected Results
Expect to be able to login to web console to manage projects by visiting a master (https://ose3-master1.example.com:8443/console) or by visiting the load balancer (https://ose3-lb.example.com:8443/console).

##### Observed Results
Directed to a page with an ambiguous error message: "An error has occurred" with a link back to the login screen.  See attached screenshots with browser in developer mode.

##### Additional Information

System version information
```bash
# system running Ansible playbook
(venv_ansible_2.6.2) [watsonb@ben-dev1 openshift-ansible]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.4 (Maipo)

# systems receiving Open Shift installation
[jenkins@ose3-master1 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```

Ansible inventory configuration
```yaml

[masters]
ose3-master[1:3].example.com

[etcd]
ose3-master[1:3].example.com

[nodes]
ose3-master[1:3].example.com openshift_node_group_name=node-config-master
ose3-infra[1:2].example.com openshift_node_group_name=node-config-infra
ose3-node[1:2].example.com openshift_node_group_name=node-config-compute

[nfs]
ose3-master1.example.com

[lb]
ose3-lb.example.com

[OSEv3:children]
masters
nodes
etcd
lb
nfs

[OSEv3:vars]
debug_level=2
ansible_user=jenkins
ansible_become=true

openshift_deployment_type=openshift-enterprise
openshift_release="3.10"
openshift_image_tag=v3.10.45
                          
openshift_disable_check=disk_availability,memory_availability,docker_storage

openshift_enable_service_catalog=true
template_service_broker_install=true

openshift_hosted_infra_selector='region=infra'
openshift_hosted_router_selector='region=infra'
openshift_hosted_registry_selector='region=infra'

openshift_master_default_subdomain=apps.example.com
openshift_master_cluster_hostname=ose3-lb.example.com
                                  
oreg_url=nexus03.example.com:19082/openshift3/ose-${component}:${version}
openshift_examples_modify_imagestreams=true
openshift_docker_insecure_registries=nexus03.example.com:19082
openshift_docker_additional_registries=nexus03.example.com:19082
openshift_cockpit_deployer_prefix='nexus03.example.com/openshift3/'
openshift_web_console_prefix='nexus03.example.com/openshift3/ose-'
openshift_service_catalog_image_prefix='nexus03.example.com/openshift3/ose-'
ansible_service_broker_image_prefix='nexus03.example.com/openshift3/ose-'
template_service_broker_prefix='nexus03.example.com/openshift3/ose-'
                                      
openshift_master_identity_providers=[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]

osm_custom_cors_origins=['.*']
```

Login attempt via Google Chrome with developer tools directly against ose3-master1 node:
![image](https://user-images.githubusercontent.com/1863643/47080710-58ea0500-d1ce-11e8-85c4-399d0e523594.png)

Login attempt (new tab) via Google Chrome with developer tools directly against ose3-lb node:
![image](https://user-images.githubusercontent.com/1863643/47081239-ae72e180-d1cf-11e8-8369-f9c2079cfbd4.png)

Login attempt via Firefox with developer tools directly against ose3-master1 node:
![image](https://user-images.githubusercontent.com/1863643/47080932-e88fb380-d1ce-11e8-8016-63ee0a97d5eb.png)

Login attempt (new tab) via Firefox with developer tools directly against ose3-lb node:
![image](https://user-images.githubusercontent.com/1863643/47081017-24c31400-d1cf-11e8-9447-36b7970844cd.png)

**Comment by watsonb** [comment]
Nobody else experiencing this issue?  I've re-deployed OSE numerous times with the same result.  The first attached images leads me to believe that it is a CORS issue, however I'm accessing the console from the same domain (RHEL 7 workstation and RHEL 7 servers are all on same network domain).  As such, I explicitly added the line: `osm_custom_cors_origins=['.*']` to my inventory to open it up as much as possible.

I'm hopeful there is some trivial configuration setting or command I can run to resolve this as it wasn't an issue a couple of months ago and with v3.9.  I'll be attempting to move to 3.11 soon and, if I run into the same problem, are there any specific logs I can check (and how would I go about checking them) to root out the problem?

**Comment by CountPickering** [comment]
I successfully deployed a 3.9 instance earlier this AM in a test lab, using the same playbook on 3.10 I get the same error as you.  I suspect there may be an issue with "allow all" method of "openshift_master_identity_providers" and am in the process of switching to a different method.  I will update this issue if I find a resolution.

**Comment by CountPickering** [comment]
Turns out my issue was having multiple masters without defining a cluster_hostname.  When I pointed my browser to the lb dns entry it would route me to a random host in the address bar, but when I attempted to login it would switch the hostname to master1 or another master node.  I believe this was because if you do not define a cluster hostname it will use the 1st master node as the cluster hostname which caused some issues for me.  Another symptom was after shutting down the master1 node the login page would not load on the other two master nodes.  I'm not sure if this applies to your situation.  However I did notice in your 1st picture master1 is in your address bar but in your console it references master2.  

One thing I might try if I were you would be adding: the cluster_method as native and defining a custer_hostname that is not the dns entry of your load balancer but does resolve to the ip address of your load-balancer.  example below:

openshift_master_cluster_method=native
openshift_master_cluster_hostname=openshift-internal.ocp.local

**Comment by watsonb** [comment]
I'll add in the `openshift_master_cluster_method=native` bit, but I'm a little confused on the cluster_hostname portion.  I feel like I'm complying with the example here: https://github.com/openshift/openshift-ansible/blob/master/inventory/hosts.example in that I am setting cluster_hostname to point at my load balancer.  

If I don't use the DNS name, what other name resolves to the IP of the load balancer and from what context?  From the context of the load balancer itself, `localhost` would do.  But what other name would I use that all other machines within the cluster can resolve let alone machines/clients outside of the cluster?  Where/how did you come up with a name like `openshift-internal.ocp.local'?  The `/etc/hosts` file on all of my machines merely have `localhost` entries and `/etc/resolv.conf` points to the proper DNS servers for our network (as part of the machine provisioning process).  Is there some other name resolution voodoo internal to the cluster of OSE machines that resolves `openshift-internal.ocp.local` to the load balancer's IP address?

I'll experiment by re-running the deploy_cluster playbook on my existing cluster with the inventory changes you've recommended and try spinning it all out "fresh" again as well.
