### ISSUE TITLE
Help : How to inject custom certificates in containerized installer

### ISSUE THREAD

**Issue by supabibz** [openshift/openshift-ansible#10475]
#### Description
Hi,

I'd like to redeploy my OKD with custom certificates for the console. I followed documentation to do so but each time  I get :
```certificate and/or key does not exist```

I understand that the certificate/key must be local to the installer but how to make these cert local when using containerized installer (a way to mount volumes like in docker maybe?)

##### Version
Openshift-ansible installer 3.11

##### Steps To Reproduce
Launch installer :
```atomic install --system --storage=ostree --set INVENTORY_FILE=/home/fedora/inventory --set PLAYBOOK_FILE=/usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml --set OPTS="-vvv -e 'ansible_python_interpreter=/usr/bin/python3'" docker.io/openshift/origin-ansible:v3.11```

##### Expected Results
Certificates deployed and installation successed..

##### Observed Results
Installer fails with :
```certificate and/or key does not exist```

##### Additional Information

Containerized Installer is launched on a dedicated Fedora Atomic Host 28 (when I realized what was the aim of the containerized installer (i.e. launch installer on a future OSE node...) I tried to use the standard docker installer but never got to make ansible to connect trough SSH to my nodes, so I stuck to containrized installer)
All Openshift hosts are Fedora Atomic Host 28 also.
Installation was already performed with success with the default certificates

Inventory :

```# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=fedora
ansible_python_interpreter=/usr/bin/python3
openshift_version="3.11"
openshift_master_cluster_method=native
openshift_master_cluster_hostname=xxxxxxxxxx
openshift_master_cluster_public_hostname=yyyyyy
openshift_master_overwrite_named_certificates=true
openshift_master_named_certificates=[{"certfile": "/home/fedora/OKD_console_external.crt", "keyfile": "/home/fedora/OKD_console_external.key", "cafile": "/home/fedora/chain.crt"}]
openshift_metrics_install_metrics=true


# If ansible_ssh_user is not root, ansible_become must be set to true
ansible_become=true

openshift_deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to AllowAllPasswordIdentityProvider
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

# host group for masters
[masters]
xxxxxxxxx

# host group for etcd
[etcd]
xxxxxxxxxx

# host group for nodes, includes region info
[nodes]
xxxxxxxxxx openshift_node_group_name='node-config-master'
zzzzzzzzzzz openshift_node_group_name='node-config-compute'
aaaaaaaaa openshift_node_group_name='node-config-compute'
bbbbbbbb openshift_node_group_name='node-config-infra'
cccccccccc openshift_node_group_name='node-config-infra'
```

**Comment by krejkrejkrej** [comment]
We've also seen this issue when installing origin 3.11 using system containers. Did you find out more why it happens and/or a remedy?

**Comment by supabibz** [comment]
> We've also seen this issue when installing origin 3.11 using system containers. Did you find out more why it happens and/or a remedy?

Unfortunately, I never solved this issue. I had to deploy the certificates manually and modify the master config after the installation.

**Comment by krejkrejkrej** [comment]
I found the problem. The containerized installer does not have access to /home/xxx and can't read the certificates specified in the inventory file. The only directory it mounts is /root, which means that if you place your certificate files in /root/xxx/certificate.crt, the installer is able to pick them up.

So, I see two issues here, one is that the containerized installer does not complain on paths outside /root, the other is the lacking documentation on this behaviour. 

The same issue would arise when trying to re-deploy certificates using the containerized installer.
