### ISSUE TITLE
Customizing registry route with playbooks

### ISSUE THREAD

**Issue by gregswift** [openshift/openshift-ansible#10510]
#### Description

Is anyone running a custom route for their registry?  It seems like the playbooks misuse a variable.  I mean, its documented for its use but its name, imo, means something else.  I would assume that if i want a custom route url for the registry that i should do this
```openshift_hosted_registry_registryurl=registry.iad.rsi.rackspace.net```
*however* their doc says that variable is used for the image not the url, and the code seems to match

https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_hosted/tasks/registry.yml#L99

##### Version

I'm running 3.6 right now, but the 3.11 playbooks have the same thing

**Comment by vrutkovs** [comment]
`openshift_hosted_registry_registryurl` would update the registry URL for the image used a registry. It won't affect the route used to expose the registry or registry console.

There is no `expose registry` option yet, so lets use this issue as a tracker
