### ISSUE TITLE
wrong images name mentioned in openshift-ansible/roles/openshift_logging_defaults/defaults/main.yml

### ISSUE THREAD

**Issue by shubhamgupta514** [openshift/openshift-ansible#10537]
Please change below images name in main.yml for logging containers

kibana5 to kibana
elasticsearch5 to elasticsearch
curator5 to curator

**Comment by calston** [comment]
This is bigger than that actually, the playbooks reference non-existent image tags in metrics, monitoring and logging. Not sure if someone has inadvertently deleted a pile of 3.10 tags from the docker hub repos.
