### ISSUE TITLE
Run prerequisites.yml on Fedora 28 playbook fails saying "requires Python 3"

### ISSUE THREAD

**Issue by iamzhout** [openshift/openshift-ansible#10549]
#### Description

Run `ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml` fail on clean Fedora 28 host

##### Version

* ansible version

```
ansible 2.6.5
  config file = /home/osboxes/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:24:06) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

* The output of `git describe`
openshift-ansible-3.11.34-1-4-g039b10a92

* The output of `rpm -q openshift-ansible`
package openshift-ansible is not installed

##### Steps To Reproduce
1.  install required packages following the [instructions](https://github.com/openshift/openshift-ansible/#setup) from openshift-ansible
2. Run `ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml`

##### Expected Results
The playbook should finish and deploy the prerequisites for setting up a basic all in one Openshift cluster in localhost.

##### Observed Results
Describe what is actually happening.

```
TASK [Run variable sanity checks] ********************************************************************************************************************************************************************
Tuesday 30 October 2018  00:59:42 -0400 (0:00:00.166)       0:01:35.449 *******
fatal: [localhost]: FAILED! => {"msg": "last_checked_host: localhost, last_checked_var: ansible_python;openshift-ansible requires Python 3 for Fedora; For information on enabling Python 3 with Ansible, see https://docs.ansible.com/ansible/python_3_support.html"}

PLAY RECAP *******************************************************************************************************************************************************************************************
localhost                  : ok=47   changed=4    unreachable=0    failed=1
```

##### Additional Information
* OS
Fedora release 28 (Twenty Eight)

* inventory file
Just the default one, w/ or w/o `ansible_python_interpreter=/usr/bin/python3` is the same

* other
I have searched google without success, like this one: https://github.com/openshift/openshift-ansible/issues/7952.

**Comment by vrutkovs** [comment]
In Fedora you need to install `ansible-python3` and run `ansible-playbook-3` instead
