### ISSUE TITLE
Could not find csr for nodes

### ISSUE THREAD

**Issue by go-faustino** [openshift/openshift-ansible#10559]
#### Description

When upgrading control plane from v3.9 to v3.10, "openshift_node : Approve the node" fails on the first master with the error:
Could not find csr for nodes: master1.domain.env.local

Running oc get csr, I can see the csr exists and has been approved.

On the master, running systemctl status origin-node shows activating, but can't see any error or what's stopping it from becoming active. No error shown with systemctl status or journalctl. I believe the error to be the origin-node not coming online, and not with the csr.

I searched the other issues, and none of the solutions seems to solve the problem, the master can resolve the hostnames of all cluster nodes and so on.

##### Version

```
ansible 2.4.3.0
openshift-ansible-3.10.66-1-3-g5aa2928
```

NOTE: I had to do some adjustments to the ansible playbook, which I don't see have any impact in this error:
- changed package python-docker name to python-docker-py
- removed docker version validation because it checks Docker is available on a repo to install but I don't need to install Docker and I don't want to setup a repo for the Docker version I'm currently running (1.13.1)

##### Steps To Reproduce

1. Run openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml with an inventory file

##### Expected Results

```
Successfully upgrade cluster
```

##### Observed Results

```
Got error:
Message:  Could not find csr for nodes: master1.domain.env.local
However, the problem is that the origin-node process is stuck activating and never becomes active but doesn't fail or output any errors
```

NOTE: I ran Ansible in verbose mode, but the output is huge, and I don't see any problems there, only the oc_csr_approve.py script output. It shows that there are no longer CSRs to approve, but the node isn't ready yet

##### Additional Information

```
OS: RHEL 7.2

Inventory file:
# Create an OSEv3 group that contains the master, nodes, etcd, and lb groups.
# The lb group lets Ansible configure HAProxy as the load balancing solution.
# Comment lb out if your load balancer is pre-configured.
 
[OSEv3:children]
masters
etcd
nodes

# host group for masters
[masters]
master1.domain.env.local
master2.domain.env.local
master3.domain.env.local

# host group for etcd
[etcd]
master1.domain.env.local
master2.domain.env.local
master3.domain.env.local
 
# host group for nodes, includes region info
[nodes]
master1.domain.env.local openshift_node_group_name='node-config-all-in-one'
master2.domain.env.local openshift_node_group_name='node-config-all-in-one'
master3.domain.env.local openshift_node_group_name='node-config-all-in-one'
node1.domain.env.local openshift_node_group_name='node-config-kitchen'
node2.domain.env.local openshift_node_group_name='node-config-elastic'
node3.domain.env.local openshift_node_group_name='node-config-table'
node4.domain.env.local openshift_node_group_name='node-config-table'
node5.domain.env.local openshift_node_group_name='node-config-elastic'
node6.domain.env.local openshift_node_group_name='node-config-elastic'
node7.domain.env.local openshift_node_group_name='node-config-table'
```

NOTE: All the nodes [1:7] have their own group name but they're all compute nodes, only with different additional labels

**Comment by nagonzalez** [comment]
looking at the play:
https://github.com/openshift/openshift-ansible/blob/release-3.10/roles/openshift_node/tasks/upgrade/restart.yml#L54

I'd venture to say that your node names don't match the values in your inventory. 

What's the output of:
```
oc get nodes
```

**Comment by go-faustino** [comment]
The problem was with the etcd image which is on a registry that's blocked by the proxy I'm behind. As it all failed silently, no image pull back off written to the logs, it took a lot of trial and error.

Thanks!

**Comment by bartvanandel** [comment]
How did you find this out?
