### ISSUE TITLE
In non SDN setups, ensure NodePort iptables rules are open on all nodes

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#1056]
The SDN bug needs to be fixed first for SDN - I don't think the rules will be identical.  But if SDN isn't in play it needs to be open by default for non-SDN setups for the port range

http://stackoverflow.com/questions/34125954/openshift-external-access-using-nodeport/34254192#34254192

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
