### ISSUE TITLE
No package matching 'origin-docker-excluder-3.11**' found available, installed or updated

### ISSUE THREAD

**Issue by wongkafai** [openshift/openshift-ansible#10564]
I would like to ask where I can install this package.

on RHEL 7.5, ansible-playbook -i /etc/ansible/hosts playbooks/prerequisites.yml fails with
 
RETRYING: Install docker excluder - yum (1 retries left).

fatal: [master.example.com]: FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'origin-docker-excluder-3.11**' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-docke    r-excluder-3.11**' found available, installed or updated"]}

fatal: [node.example.com]: FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'origin-docker-excluder-3.11**' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-docke    r-excluder-3.11**' found available, installed or updated"]}

**Comment by nagonzalez** [comment]
Final 3.11 packages are not available. This thread is tracking status:
http://lists.openshift.redhat.com/openshift-archives/users/2018-October/msg00064.html

If you really want to upgrade right now, you could add the CI/testing 3.11 yum repo as detailed in the thread.

**Comment by DanyC97** [comment]
@nagonzalez i'm still waiting for folks to confirm that 3.11 testing is okay and no issue seen.
Once that is done i'll promote the packages ...

**Comment by Reamer** [comment]
Hi @DanyC97,
I've updated my Platform to 3.11 with this Repo-BaseUrl (https://cbs.centos.org/repos/paas7-openshift-origin311-testing/x86_64/os/). It's works really good. My colleague created a new Cluster with this BaseUrl (https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin311/)

**Comment by DanyC97** [comment]
@Reamer thank you for the info.

As you might have seen the rpms been released as announced [here](http://lists.openshift.redhat.com/openshift-archives/users/2018-November/msg00007.html)

**Comment by DanyC97** [comment]
@vrutkovs if you have time i think we can close this issue as being fixed.

**Comment by Reamer** [comment]
@DanyC97 
Can you estimate when rpm are available in common?(http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/)

**Comment by Reamer** [comment]
Just read the mail (http://lists.openshift.redhat.com/openshift-archives/dev/2018-November/msg00005.html)
