### ISSUE TITLE
CRI-O is required d_type=true/ftype=1 on its XFS

### ISSUE THREAD

**Issue by bysnupy** [openshift/openshift-ansible#10588]
#### Description

`CRI-O` is required `overlay filesystem`, the `overlay filesystem` can be enable when `d_type` is turn on in `XFS` on its `RHEL7`.

As of `RHEL7.4`, the default value of `d_type` is `true` on its `XFS`, but older than the `RHEL7.4` is not. And Upgraded from old version is not changed the default value, `d_type=false`.

For instance,
If you install `CRI-O` to `RHEL7.4/7.5/7.6` that was updated from its old version `RHEL(7.0~7.3)`, then `OCP` install is failed due to fault of `d_type=false` on its `XFS`.

##### Version

- My verification is `v3.11`, but this issues is depends on `RHEL` state which is updated from `>=7.3` version.

##### Steps To Reproduce

you can check the `d_type` feature condition using `xfs_info` on RHEL updated from `<=v7.3`.
It's enabled `d_type` due to `ftype=1`.
~~~
$ xfs_info /var/lib/containers
...
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
...
~~~

##### Expected Results

- Personally, I think we would check the `d_type` to base path of `CRI-O` during prerequisites checks.

##### Observed Results

- `CRI-O` is not started during install due to `d_type=false`.

##### Additional Information

- Related `BZ`: https://bugzilla.redhat.com/show_bug.cgi?id=1490910#c4

- If you just installed a fresh `RHEL7.4+`version, you should have no problem.

**Comment by vrutkovs** [comment]
I don't think openshift-ansible can help with anything here. RHBZ was closed as NOTABUG, Atomic 7.5+ is required in latest version anyway
