### ISSUE TITLE
Openshift 3.11 Enterprise Installation fails

### ISSUE THREAD

**Issue by SubhakarKotta** [openshift/openshift-ansible#10603]
#### Description
Openshift 3.11 installation fails with error.

##### Version
Openshift-Enterprise : 3.11
RHEL : 7.5

[OSEv3:children]
masters
nodes
etcd

[masters]
10.225.68.119  openshift_public_ip=10.225.68.119 openshift_ip=10.225.68.119

[etcd]
10.225.68.119  openshift_public_ip=10.225.68.119 openshift_ip=10.225.68.119

[nodes]
10.225.68.119  openshift_node_group_name='node-config-master' openshift_public_ip=10.225.68.119 openshift_ip=10.225.68.119
10.225.68.125  openshift_node_group_name='node-config-infra' openshift_public_ip=10.225.68.125 openshift_ip=10.225.68.125
10.225.68.127  openshift_node_group_name='node-config-compute' openshift_public_ip=10.225.68.127 openshift_ip=10.225.68.127

[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=openshift-enterprise
openshift_master_cluster_public_hostname=10.225.68.119
openshift_master_cluster_hostname=10.225.68.119
openshift_examples_modify_imagestreams=false
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability
oreg_auth_user=<redhat login username>
oreg_auth_password=<redhat login password>
oreg_url=registry.access.redhat.com/openshift3/ose-${component}:${version}

Error:

Create credentials for oreg_url] fails with retry count.

Questions?
1) What should be oreg_url? I dont have any customized images
2) what should oreg_password ? I am using redhat login password
3) what should oreg_username ? I am using redhat login username
4) Is there any way to bypass oreg_* parameter ?

**Comment by MohanNagendraKumar** [comment]
Will it working
