### ISSUE TITLE
Parameter docker_storage_driver is ignored

### ISSUE THREAD

**Issue by franckgr** [openshift/openshift-ansible#10654]
#### Description

Parameter docker_storage_driver is ignored
https://docs.openshift.com/container-platform/3.9/install_config/install/advanced_install.html#configuring-cluster-pre-install-checks

In inventory docker_storage_driver=what_ever_you_want has no effect

In role container_runtime docker storage configuration task is executed only if container_runtime_docker_storage_type == 'overlay2'
this parameter container_runtime_docker_storage_type has no default and is not define so docker_storage_setup_overlay.yml is not execute.

##### Version

```
rpm -q openshift-ansible
openshift-ansible-3.9.43-1.git.0.d0bc600.el7.noarch

rpm -q ansible
ansible-2.4.6.0-1.el7ae.noarch

ansible --version
ansible 2.4.6.0
  config file = /home/quicklab/ansible.cfg
  configured module search path = [u'/home/quicklab/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### Steps To Reproduce

1. Add in inventory docker_storage_driver=overlay2
2. Execute prerequisites playbook

##### Expected Results

/etc/sysconfig/docker-storage-setup should contains STORAGE_DRIVER parameter if differents from default

```
$ cat /etc/sysconfig/docker-storage-setup 
# Edit this file to override any configuration options specified in
# /usr/lib/docker-storage-setup/docker-storage-setup.
#
# For more details refer to "man docker-storage-setup"
STORAGE_DRIVER="overlay2"
EXTRA_STORAGE_OPTIONS="--storage-opt overlay2.override_kernel_check=true  --graph=/var/lib/docker"```
```

##### Observed Results
/etc/sysconfig/docker-storage-setup doesn't contains STORAGE_DRIVER parameter

```
$ cat /etc/sysconfig/docker-storage-setup 
# Edit this file to override any configuration options specified in
# /usr/lib/docker-storage-setup/docker-storage-setup.
#
# For more details refer to "man docker-storage-setup"
EXTRA_STORAGE_OPTIONS="--storage-opt overlay2.override_kernel_check=true  --graph=/var/lib/docker"

```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

* Red Hat Enterprise Linux Server release 7.6 (Maipo)
* Your inventory file (especially any non-standard configuration parameters)
* The following bugzilla has been opened [1648398](https://bugzilla.redhat.com/show_bug.cgi?id=1648398)

##### Workaround:

As a workaround I use the following to enable task and override default value from docker_storage_setup_options.storage_driver

```
docker_storage_setup_options={'storage_driver':'overlay2'}
container_runtime_docker_storage_type=overlay2
```

**Comment by michaelgugino** [comment]
This is entirely by design.  We don't support setting up docker storage automatically for any other storage type.  If overlay2 does not meet your needs, please consult documentation around setting up docker storage for your environment as a prerequisite to running the install.

**Comment by franckgr** [comment]
Thank you for your answer. I assumed any other storage means other than the default for docker version installed within Openshift. What does docker_storage_driver mean since it doesn't appear anywhere in installer ?

I just deploy a fresh openshift 3.9 device driver uses is devicemapper. If I plan to use cri-o and cri-o gc overlay2 must be use.

> When CRI-O use is enabled, it is installed alongside docker, which currently is required to perform build and push operations to the registry. Over time, temporary docker builds can accumulate on nodes. You can optionally set the following parameter to enable garbage collection. **You must configure the node selector so that the garbage collector runs only on nodes where docker is configured for overlay2 storage.**

If there is no way to enable overlay2 instead of devicemapper in inventory and out of the box have a supported installation.

```
$ docker info
...
Images: 11
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker--vol-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
```

```
$ oc version
oc v3.9.43
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

**Comment by sdodson** [comment]
Docker storage driver configuration is something that's handled during docker package installation. In modern versions of RHEL 7 (7.5+) the storage driver defaults to overlay2 requiring no further configuration to deploy openshift in a production ready config. In the past one had to setup devicemapper thin pools but that's no longer necessary.
