### ISSUE TITLE
Transient Installer Error: the provided resource version does not match

### ISSUE THREAD

**Issue by dgoodwin** [openshift/openshift-ansible#1066]
Hit while installing from released OSE 3.1 repos:

-- Logs begin at Tue 2015-12-15 06:22:19 EST, end at Tue 2015-12-15 07:18:39 EST. --
Dec 15 06:47:07 ip-172-18-7-81.ec2.internal systemd[1]: Starting Atomic OpenShift Master API...
Dec 15 06:47:07 ip-172-18-7-81.ec2.internal atomic-openshift-master-api[15596]: I1215 06:47:07.665675   15596 start_api.go:96] Using a masterIP override "172.18.7.81"
Dec 15 06:47:07 ip-172-18-7-81.ec2.internal atomic-openshift-master-api[15596]: I1215 06:47:07.665776   15596 start_api.go:102] Using a listen address override "0.0.0.0:8443"
Dec 15 06:47:08 ip-172-18-7-81.ec2.internal atomic-openshift-master-api[15596]: I1215 06:47:08.530491   15596 plugins.go:71] No cloud provider specified.
Dec 15 06:47:08 ip-172-18-7-81.ec2.internal atomic-openshift-master-api[15596]: I1215 06:47:08.710902   15596 start_master.go:388] Starting master on 0.0.0.0:8443 (v3.1.0.4-16-g112fcc4)
Dec 15 06:47:08 ip-172-18-7-81.ec2.internal atomic-openshift-master-api[15596]: I1215 06:47:08.710936   15596 start_master.go:389] Public master address is https://ec2-52-90-216-26.compute-1.amazonaws.com:8443
Dec 15 06:47:08 ip-172-18-7-81.ec2.internal atomic-openshift-master-api[15596]: I1215 06:47:08.710953   15596 start_master.go:393] Using images from "openshift3/ose-<component>:v3.1.0.4"
Dec 15 06:47:08 ip-172-18-7-81.ec2.internal atomic-openshift-master-api[15596]: I1215 06:47:08.744571   15596 run_components.go:183] Using default project node label selector:
Dec 15 06:47:11 ip-172-18-7-81.ec2.internal atomic-openshift-master-api[15596]: F1215 06:47:11.856238   15596 controller.go:83] Unable to perform initial IP allocation check: unable to persist the updated service IP allocations: serviceipallocation "" cannot be updated: the provided resource version does not match
Dec 15 06:47:11 ip-172-18-7-81.ec2.internal systemd[1]: atomic-openshift-master-api.service: main process exited, code=exited, status=255/n/a
Dec 15 06:47:11 ip-172-18-7-81.ec2.internal systemd[1]: Failed to start Atomic OpenShift Master API.
Dec 15 06:47:11 ip-172-18-7-81.ec2.internal systemd[1]: Unit atomic-openshift-master-api.service entered failed state.
Dec 15 06:47:11 ip-172-18-7-81.ec2.internal systemd[1]: atomic-openshift-master-api.service failed.

Logging into the system and starting the service manually after this occurred, it came up fine.

Running uninstall playbook and re-trying the install on the exact same systems worked a second time around.

As such I probably cannot reproduce this, we may have to close if it doesn't show itself again soon but there's definitely a possible problem there somewhere.

**Comment by ncdc** [comment]
Upstream bug: https://github.com/kubernetes/kubernetes/issues/19848. Once https://github.com/kubernetes/kubernetes/pull/16067 is merged upstream, we can apply a proper fix there.

For now, we have an Origin-only fix: https://github.com/openshift/origin/pull/6737.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
