### ISSUE TITLE
[3.9] fact_caching_timeout default value is 86400 or 600 ?

### ISSUE THREAD

**Issue by bysnupy** [openshift/openshift-ansible#10669]
#### Description

This issue is for checking the specification of openshift-ansible cache timeout default value.

After checking here, I'll request to modify the documentation related with this issue, if the documentation is not correct.

* The description of documentation: [Running the RPM-based Installer
](https://docs.openshift.com/container-platform/3.9/install_config/install/advanced_install.html#running-the-advanced-installation-rpm)
~~~
The installer caches playbook configuration values for 10 minutes, by default. 
~~~

As of `v3.10` is configured `fact_caching_timeout = 600` in `/usr/share/ansible/openshift-ansible/ansible.cfg`, but not `v3.9`. As far as I know, in `v3.9` ansible refer the `/etc/ansible/ansible.cfg` as default, the cache timeout is not specified in `ansible.cfg`, so it used as `86400` default timeout value.

https://github.com/ansible/ansible/blob/stable-2.4/lib/ansible/config/base.yml#L272-L280
~~~
CACHE_PLUGIN_TIMEOUT:
  name: Cache Plugin expiration timeout
  default: 86400
  description: Expiration timeout for the cache plugin data
  env: [{name: ANSIBLE_CACHE_PLUGIN_TIMEOUT}]
  ini:
  - {key: fact_caching_timeout, section: defaults}
  type: integer
  yaml: {key: facts.cache.timeout}
~~~

##### Version

* Your ansible version per `ansible --version`

ansible 2.4.6.0

**Comment by vrutkovs** [comment]
Ansible would pick up `ansible.cfg` from the repo root automatically, which does get set there.

Is it an Origin RPM or OCP? 
Which version are you using?
Is `fact_caching_timeout` set in /usr/share/ansible/openshift-ansible/ansible.cfg ?

**Comment by bysnupy** [comment]
It's `OCP v3.9` and there is not `/usr/share/ansible/openshift-ansible/ansible.cfg` and I check what `ansible.cfg` is used by using `ansible-playbook --version`. The result was `/etc/ansible/ansible.cfg`.

**Comment by vrutkovs** [comment]
Right, it seems to be an issue with the RPM setup then

**Comment by bysnupy** [comment]
Does It mean the documentation is correct (timeout is 10 minutes) ? The issues is missing the `/usr/share/ansible/openshift-ansible/ansible.cfg` in the `RPM`, isn't it ?

**Comment by vrutkovs** [comment]
Yes, the docs are correct and RPMs should use 10min timeout, but RPM seems to be copying this file to a different location

**Comment by bysnupy** [comment]
I could know the background and cause about this issue, so I'll close it.
