### ISSUE TITLE
Use private IP instead of public ones when building primed images

### ISSUE THREAD

**Issue by razvan-miron** [openshift/openshift-ansible#10677]
#### Description

Trying to use AWS autoscaler with primed images on a private VPC. When building the AMI it tries to connect to the public IP of the instance.
Not sure how to make it use the private IP instead. 

##### Version
```
ansible --version : ansible 2.6.5
openshift version : 3.11

```

##### Steps To Reproduce
1. Fallow the septs from [Creating a primed image](https://docs.openshift.com/container-platform/3.11/admin_guide/cluster-autoscaler.html#creating-primed-image-cluster-auto-scaler-cluster-auto-scaler)
2. Run the build_ami.yml playbook to generate a primed image

##### Expected Results
Actual build the image

##### Observed Results
Builds the image with a public IP and tries to connect to it using that.
```
TASK [openshift_aws : wait for ssh to become available] **************************************************************
task path: /Work/git_repos/openshift-ansible-alg/roles/openshift_aws/tasks/provision_instance.yml:32
Monday 12 November 2018  17:06:47 +0200 (0:00:01.496)       0:00:27.747 *******
```
```
ansible-playbook -i hosts_primed playbooks/aws/openshift-cluster/build_ami.yml -e @build-ami-provisioning-vars.yaml
```

##### Additional Information

Is it possible to override the public ip setting and force it to use private IP's?
I saw in the code the the public IP check is hardcoded.

- name: wait for ssh to become available
  wait_for:
    port: 22
    host: "{{ instancesout.instances[0].public_ip_address }}"
    timeout: 300
    search_regex: OpenSSH

**Comment by spacedan** [comment]
Hello, I'm not sure if you are still pursuing this issue, but I found it while looking for a similar solution. I was also trying to create a primed AMI in our private VPC for the current release-3.11 version of the playbooks. 
I modified the openshift-ansible playbook - specifically the provision_instance playbook located at roles/openshift_aws/tasks/provision_instance.yml.
[Line 35](https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_aws/tasks/provision_instance.yml#L35) 
Change to:
`host: "{{ instancesout.instances[0].private_ip_address }}"` 
and [Line 42](https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_aws/tasks/provision_instance.yml#L42)
Change to:
`name: "{{ instancesout.instances[0].private_dns_name }}"`

ansible 2.6.19
openshift-ansible-3.11.153-2.git.0.ee699b5.el7.noarch
