### ISSUE TITLE
Can you teach me how to install it?

### ISSUE THREAD

**Issue by wongkafai** [openshift/openshift-ansible#10679]
i want to ask how to use ansible-playbook to install Red Hat OpenShift Container Platform 3.10 , inventory file.

The followings are the requirements for inventory file. Could you please provide examples for me as reference?
1.  node-config-all-in-one
2. openshift_master_console_port=443
3.  can it use storage?(have example for create PV and PVC step for storage?)
4. can it use docker login?

Below are problems when i try to install:
 2*. openshift_master_console_port=443 which is crashed with router port in default project (router in default project cannot run)

 4*. docker login 
      -- docker login docker-registry-default.router.default.svc:5000 (successful)
      -- docker login docker-registry-default.192.168.1.134.xip.io:443 (unsuccessful {Error response from daemon: Login: Account is not active.})

**Comment by gigo1980** [comment]
I am also interested in writing an guide how to setup step by step openshift for different cluster types
