### ISSUE TITLE
install Red Hat OpenShift Container Platform 3.10 fails

### ISSUE THREAD

**Issue by wongkafai** [openshift/openshift-ansible#10694]
How to fix the problem below:

use ansible-playbook -i /etc/ansible/hosts playbooks/deploy_cluster.yml for node-config-all-in-one

TASK [openshift_control_plane : Wait for control plane pods to appear]
FAILED - RETRYING: Wait for control plane pods to appear (60 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (59 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (58 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (57 retries left).
.............
FAILED - RETRYING: Wait for control plane pods to appear (1 retries left).
{
   "attempts": 60,
   "changed": false,
   "failed": true,
   "item": "etcd",
   "msg": {
      "cmd": "/usr/bin/oc get pod master-etcd-umtlhkosc.example.com -o json -n kube-system",
      "results": [
         {}
      ],
      "returncode": 1,
      "stderr": "The connection to the server umtlhkosc.example.com:8443 was refused - did you specify the right host or port?\n",
      "stdout": ""
   }
}

[root@umtlhkosc ~]# kubectl cluster-info
Kubernetes master is running at https://umtlhkosc.example.com:443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server umtlhkosc.example.com:443 was refused - did you spec                                ify the right host or port?

**Comment by JuozasA** [comment]
"The connection to the server umtlhkosc.example.com:8443 was refused - did you specify the right host or port?" 
For me sounds like the issue with firewall rules on the node. It cannot talk to itself

**Comment by Pectojin** [comment]
`kubectl cluster-info` is saying the cluster is running on 443, but the logs are complaining that 8443 isn't responding.

Did you change the `openshift_master_api_port` variable or otherwise try to change between 8443 and 443? It must be consistent.

**Comment by wongkafai** [comment]
Openshift certificate DNS problem

**Comment by vrutkovs** [comment]
Please collect master logs: https://docs.okd.io/3.11/install_config/master_node_configuration.html#master-node-view-logs
