### ISSUE TITLE
TASK [openshift_logging : include_tasks]

### ISSUE THREAD

**Issue by swepps1** [openshift/openshift-ansible#10691]
#### Description

I want to install Origin 3.9 and logging run error.

TASK [openshift_logging : include_tasks] ****************************************************************************************************************************************************************************************************
fatal: [kak-tst-openshift-master1.kak-tst.internal]: FAILED! => {"reason": "Invalid options for include_tasks: component\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/roles/openshift_logging/tasks/generate_certs.yaml': line 135, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Generate PEM certs\n  ^ here\n"}
        to retry, use: --limit @/usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
kak-tst-nfs.kak-tst.internal : ok=29   changed=1    unreachable=0    failed=0
kak-tst-openshift-infra1.kak-tst.internal : ok=140  changed=60   unreachable=0    failed=0
kak-tst-openshift-infra2.kak-tst.internal : ok=140  changed=60   unreachable=0    failed=0
kak-tst-openshift-infra3.kak-tst.internal : ok=140  changed=60   unreachable=0    failed=0
kak-tst-openshift-lb.kak-tst.internal : ok=32   changed=3    unreachable=0    failed=0
kak-tst-openshift-master1.kak-tst.internal : ok=711  changed=225  unreachable=0    failed=1
kak-tst-openshift-master2.kak-tst.internal : ok=325  changed=116  unreachable=0    failed=0
kak-tst-openshift-master3.kak-tst.internal : ok=325  changed=116  unreachable=0    failed=0
kak-tst-openshift-node1.kak-tst.internal : ok=140  changed=60   unreachable=0    failed=0
kak-tst-openshift-node2.kak-tst.internal : ok=140  changed=60   unreachable=0    failed=0
kak-tst-openshift-node3.kak-tst.internal : ok=140  changed=60   unreachable=0    failed=0
kak-tst-openshift-node4.kak-tst.internal : ok=140  changed=60   unreachable=0    failed=0
localhost                  : ok=15   changed=0    unreachable=0    failed=0

INSTALLER STATUS ****************************************************************************************************************************************************************************************************************************
Initialization             : Complete (0:00:43)
Health Check               : Complete (0:00:03)
etcd Install               : Complete (0:00:45)
NFS Install                : Complete (0:00:08)
Load balancer Install      : Complete (0:00:12)
Master Install             : Complete (0:03:52)
Master Additional Install  : Complete (0:00:29)
Node Install               : Complete (0:09:55)
Hosted Install             : Complete (0:01:08)
Web Console Install        : Complete (0:00:20)
Metrics Install            : Complete (0:01:34)
Logging Install            : In Progress (0:00:13)
        This phase can be restarted by running: playbooks/openshift-logging/config.yml

Failure summary:

  1. Hosts:    kak-tst-openshift-master1.kak-tst.internal
     Play:     OpenShift Aggregated Logging
     Task:     openshift_logging : include_tasks
     Message:  Failed without returning a message.
 

##### Version

* Your ansible version per `ansible --version`
[root@kak-tst-openshift-admin openshift-ansible]# ansible --version
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
[root@kak-tst-openshift-admin openshift-ansible]#

* The output of `rpm -q openshift-ansible`
[root@kak-tst-openshift-admin openshift-ansible]# rpm -q openshift-ansible
openshift-ansible-3.9.49-1.git.0.046ac59.el7.noarch

**Comment by vrutkovs** [comment]
ansible 2.7 is not yet supported, please downgrade to 2.6.5.

See #10685
