### ISSUE TITLE
iptables setup aborts if firewalld isn't installed

### ISSUE THREAD

**Issue by brenton** [openshift/openshift-ansible#107]
I saw this when running the byo playbook:

~~~
TASK: [openshift_common | Ensure alternative firewall service(s) are not enabled] ***
failed: [ose3-master.example.com] => (item=firewalld) => {"failed": true, "item": "firewalld", "parsed": false}
{"msg": "[Errno 2] No such file or directory", "failed": true, "cmd": "initctl version", "rc": 2}
{"msg": "cannot detect command to enable service firewalld, typo or init system potentially unknown", "failed": true}


FATAL: all hosts have already failed -- aborting
~~~

It seems like if firewalld isn't even installed we should just keep going.

**Comment by brenton** [comment]
@detiber, just fyi.  Not urgent.

**Comment by detiber** [comment]
@brenton this was fixed in master with https://github.com/openshift/openshift-ansible/pull/108
The fix is also in the enterprise2 branch.  Still working on getting the rebased changes into the v3beta2 branch.

**Comment by brenton** [comment]
awesome.  Thx!

**Comment by detiber** [comment]
The v3-beta2 branch has now been rebased to pick up this fix as well.  I'm going to go ahead and close out this ticket.

**Comment by detiber** [comment]
@twiest this issue can be closed now.

**Comment by twiest** [comment]
Closing per @detiber.
