### ISSUE TITLE
Bug discovered in ansible role openshift_storage_glusterfs while	adding host

### ISSUE THREAD

**Issue by marc-ledent** [openshift/openshift-ansible#10708]
#### Description
While adding a node having to host a glusterfs pod, installation fails : 

TASK [openshift_storage_glusterfs : Verify heketi service]
fatal: [avivm990.gait.dhl.com]: FAILED! => {"changed": false, "cmd": ["/usr/local/bin/oc", "--config=/tmp/openshift-glusterfs-ansible-16m4XL/admin.kubeconfig", "rsh", "--namespace=glusterfs", "heketi-storage-1-dqlq8", "heketi-cli", "-s", "http://localhost:8080", "--user", "admin", "cluster", "list"], "delta": "0:00:00.325466", "end": "2018-11-15 16:36:08.256372", "msg": "non-zero return code", "rc": 255, "start": "2018-11-15 16:36:07.930906", "stderr": "Error: Invalid JWT token: signature is invalid (client and server secrets may not match)\ncommand terminated with exit code 255", "stderr_lines": ["Error: Invalid JWT token: signature is invalid (client and server secrets may not match)", "command terminated with exit code 255"], "stdout": "", "stdout_lines": []}            

##### Version

$ ansible --version                                                    
ansible 2.6.7                                                                                                   
  config file = /opt/ansible/openshift-ansible-3.10/ansible.cfg                                                 
  configured module search path = [u'/home/mledent/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modul
es']                                                                                                            
  ansible python module location = /usr/lib/python2.7/site-packages/ansible                                     
  executable location = /usr/bin/ansible                                                                        
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]               

OpenShift: v3.10

##### Steps To Reproduce
Adding  new node that will host a glusterfs pod

##### Expected Results
Should work
##### Observed Results
Crashes (see description)

##### Additional Information

In fact, the problem is located in roles/openshift_storage_glusterfs/tasks/update_topology.yml:

The two lines 
<pre>
  - import_tasks: heketi_pod_check.yml
  - import_tasks: heketi_get_key.yml`
</pre>
should be swappes as heketi_pod_check needs the admin key to work. Therefore, we should have:

<pre>
---
# This taskfile is called when adding new nodes doing node and master
# scaleup play.
- import_tasks: mktemp.yml

# l_gluster_reload_topo passed in via add_hosts.yml
- when: l_gluster_reload_topo | default(True)
  block:
  - import_tasks: glusterfs_config_facts.yml
  - import_tasks: label_nodes.yml
  - import_tasks: heketi_get_key.yml
  - import_tasks: heketi_pod_check.yml
  - import_tasks: wait_for_pods.yml
  - import_tasks: heketi_load.yml
    when:
    - glusterfs_nodes | default([]) | count > 0

# l_gluster_registry_reload_topo passed in via add_hosts.yml
- when: l_gluster_registry_reload_topo | default(True)
  block:
  - import_tasks: glusterfs_registry_facts.yml
  - import_tasks: label_nodes.yml
  - import_tasks: heketi_get_key.yml
  - import_tasks: heketi_pod_check.yml
  - import_tasks: wait_for_pods.yml
  - import_tasks: heketi_load.yml
    when:
    - glusterfs_nodes | default([]) | count > 0
    - "'glusterfs' not in groups or glusterfs_nodes != groups.glusterfs"

- import_tasks: rmtemp.yml

</pre>

**Comment by giamma** [comment]
Thanks a lot this worked for me on 3.11.
