### ISSUE TITLE
3.11 web console fail to expand PVC if resourcequota defined in project

### ISSUE THREAD

**Issue by gripenk** [openshift/openshift-ansible#10729]
#### Description

Provide a brief description of your issue here. For example:
OKD 3.11 (enabled ExpandPersistentVolumes), with Netapp Trident NAS storageclass (v18.10) (enabled allowVolumeExpansion)   

I can enlarge PVC via both web console or oc if the project does not have resourcequota.
If project has "hard" resourcequota on "requests.storage", I can only enlarge the PVC via oc cli. Web console fails and show "Can't be greater than ."

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
ansible 2.6.5

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`
openshift-ansible-3.11.37-1.git.0.3b8b341.el7.noarch
Place the output between the code block below:

```
ansible 2.6.5
openshift-ansible-3.11.37-1.git.0.3b8b341.el7.noarch
```

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Expected Results
Describe what you expected to happen.

the pvc can be enlarged via web console
```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
CentOS Linux release 7.5.1804 (Core)
```

**Comment by vrutkovs** [comment]
I don't think this is related to installer, please file a new issue in https://github.com/openshift/origin
