### ISSUE TITLE
Registry and router image version mangled during upgrade

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#1072]
Seems like two different folks have run into this.

First case
Error: image openshift3/ose-docker-registry:vmanager 3.1.0.4 not found
Error: image openshift3/ose-haproxy-router:vmanager 3.1.0.4 not found

Second case from @cooktheryan yielded 
Error: image openshift3/ose-docker-registry:vsystem 3.1.0.4 not found

**Comment by sdodson** [comment]
@cooktheryan The upgrade scripts do some version checking of packages that are currently installed and those that are available. `grep openshift /var/log/yum.log` would be helpful in debugging what those values were at the time of upgrade. Also can you confirm which playbook you ran?

**Comment by cooktheryan** [comment]
The update was ran on the system pre-openshift-ansible

Jun 29 19:09:27 Installed: openshift-3.0.0.0-0.git.25.235b0e7.el7ose.x86_64
Jun 29 19:09:27 Installed: openshift-master-3.0.0.0-0.git.25.235b0e7.el7ose.x86_64
Jun 29 19:12:54 Installed: tuned-profiles-openshift-node-3.0.0.0-0.git.25.235b0e7.el7ose.x86_64
Jun 29 19:12:54 Installed: openshift-node-3.0.0.0-0.git.25.235b0e7.el7ose.x86_64
Jun 29 19:13:12 Installed: openshift-sdn-ovs-3.0.0.0-0.git.25.235b0e7.el7ose.x86_64
Aug 09 11:31:38 Updated: openshift-3.0.1.0-1.git.525.eddc479.el7ose.x86_64
Aug 09 11:31:39 Updated: tuned-profiles-openshift-node-3.0.1.0-1.git.525.eddc479.el7ose.x86_64
Aug 09 11:31:41 Updated: openshift-node-3.0.1.0-1.git.525.eddc479.el7ose.x86_64
Aug 09 11:31:41 Updated: openshift-sdn-ovs-3.0.1.0-1.git.525.eddc479.el7ose.x86_64
Aug 09 11:31:41 Updated: openshift-master-3.0.1.0-1.git.525.eddc479.el7ose.x86_64
Oct 14 12:12:47 Updated: openshift-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Oct 14 12:12:48 Updated: tuned-profiles-openshift-node-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Oct 14 12:12:48 Updated: openshift-node-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Oct 14 12:12:48 Updated: openshift-sdn-ovs-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Oct 14 12:12:48 Updated: openshift-master-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Nov 24 15:56:25 Installed: tuned-profiles-atomic-openshift-node-3.1.0.4-1.git.4.b6c7cd2.el7aos.x86_64
Nov 24 15:56:27 Installed: atomic-openshift-clients-3.1.0.4-1.git.4.b6c7cd2.el7aos.x86_64
Nov 24 15:56:29 Installed: atomic-openshift-3.1.0.4-1.git.4.b6c7cd2.el7aos.x86_64
Nov 24 15:56:46 Installed: atomic-openshift-node-3.1.0.4-1.git.4.b6c7cd2.el7aos.x86_64
Nov 24 15:56:46 Installed: atomic-openshift-sdn-ovs-3.1.0.4-1.git.4.b6c7cd2.el7aos.x86_64
Nov 24 15:56:46 Installed: atomic-openshift-master-3.1.0.4-1.git.4.b6c7cd2.el7aos.x86_64
Nov 24 15:56:46 Erased: openshift-sdn-ovs-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Nov 24 15:56:46 Erased: openshift-node-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Nov 24 15:56:46 Erased: openshift-master-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Nov 24 15:56:48 Erased: tuned-profiles-openshift-node-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Nov 24 15:56:49 Erased: openshift-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Dec 16 12:26:53 Updated: atomic-openshift-clients-3.1.0.4-1.git.15.5e061c3.el7aos.x86_64
Dec 16 12:27:00 Updated: atomic-openshift-3.1.0.4-1.git.15.5e061c3.el7aos.x86_64
Dec 16 12:27:34 Updated: tuned-profiles-atomic-openshift-node-3.1.0.4-1.git.15.5e061c3.el7aos.x86_64
Dec 16 12:27:39 Updated: atomic-openshift-node-3.1.0.4-1.git.15.5e061c3.el7aos.x86_64
Dec 16 12:27:56 Updated: atomic-openshift-sdn-ovs-3.1.0.4-1.git.15.5e061c3.el7aos.x86_64
Dec 16 12:27:59 Updated: atomic-openshift-master-3.1.0.4-1.git.15.5e061c3.el7aos.x86_64


Script ran was /home/rcook/git/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_0_to_v3_1/upgrade.yml

Running on a clean cluster without yum update being ran first. Will post output once completed

**Comment by cooktheryan** [comment]
Registry started correctly this time. Registry version openshift3/ose-docker-registry:v3.0.2.0


yum output
Sep 07 16:31:03 Installed: openshift-3.0.1.0-1.git.529.dcab62c.el7ose.x86_64
Sep 07 17:03:04 Installed: openshift-master-3.0.1.0-1.git.529.dcab62c.el7ose.x86_64
Sep 07 18:31:56 Installed: tuned-profiles-openshift-node-3.0.1.0-1.git.529.dcab62c.el7ose.x86_64
Sep 07 18:31:58 Installed: openshift-node-3.0.1.0-1.git.529.dcab62c.el7ose.x86_64
Sep 07 18:32:29 Installed: openshift-sdn-ovs-3.0.1.0-1.git.529.dcab62c.el7ose.x86_64
Oct 14 15:13:40 Updated: openshift-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Oct 14 15:13:41 Updated: tuned-profiles-openshift-node-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Oct 14 15:13:41 Updated: openshift-node-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Oct 14 15:13:41 Updated: openshift-sdn-ovs-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Oct 14 15:13:41 Updated: openshift-master-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Dec 16 13:25:57 Installed: tuned-profiles-atomic-openshift-node-3.1.0.4-1.git.15.5e061c3.el7aos.x86_64
Dec 16 13:26:00 Installed: atomic-openshift-clients-3.1.0.4-1.git.15.5e061c3.el7aos.x86_64
Dec 16 13:26:02 Installed: atomic-openshift-3.1.0.4-1.git.15.5e061c3.el7aos.x86_64
Dec 16 13:26:02 Installed: atomic-openshift-node-3.1.0.4-1.git.15.5e061c3.el7aos.x86_64
Dec 16 13:26:02 Installed: atomic-openshift-sdn-ovs-3.1.0.4-1.git.15.5e061c3.el7aos.x86_64
Dec 16 13:26:03 Installed: atomic-openshift-master-3.1.0.4-1.git.15.5e061c3.el7aos.x86_64
Dec 16 13:26:03 Erased: openshift-sdn-ovs-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Dec 16 13:26:03 Erased: openshift-node-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Dec 16 13:26:03 Erased: openshift-master-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Dec 16 13:26:04 Erased: tuned-profiles-openshift-node-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
Dec 16 13:26:05 Erased: openshift-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64

**Comment by abutcher** [comment]
```
TASK: [debug var=g_new_version] ***********************************************
ok: [osemaster0.prod.a4.vary.redhat.com] => {
    "var": {
        "g_new_version": "system 3.1.0.4"
    }
}
ok: [oseintnode0.prod.a4.vary.redhat.com] => {
    "var": {
        "g_new_version": "system 3.1.0.4"
    }
}
ok: [oseintnode1.prod.a4.vary.redhat.com] => {
    "var": {
        "g_new_version": "system 3.1.0.4"
    }
}
```

```
[root@osemaster0 ~]# yum list installed "atomic-openshift" 2>&1 | tail -n +2 | grep -v 'Installed Packages' | grep -v 'Red Hat Subscription Management'
This system is receiving updates from RHN Classic or Red Hat Satellite.
atomic-openshift.x86_64 3.1.0.4-1.git.15.5e061c3.el7aos @rhel-7-server-ose-3.1-rpms
```

@sdodson @cooktheryan

**Comment by abutcher** [comment]
Simplest fix might be to just add a `| grep -v 'RHN Classic' | grep -v 'manager' |` to the versions script or we can rework the logic.

**Comment by detiber** [comment]
@abutcher agreed, we should probably use the yum/dnf api for gathering the info rather than attempting to parse the output of yum list.

That said, a quick workaround for `| grep -v 'system' | grep -v 'manager' |` is probably a good idea.

**Comment by sdodson** [comment]
`-e 0` seems to clean things up quite a bit PR incoming

**Comment by abutcher** [comment]
@sdodson I'll close #1075 in favor of yours if you have some extra sauce.

**Comment by tbielawa** [comment]
We've made many advances in version detection recently so I am going to close this issue.

Please update and reopen this issue if this is still a priority you would like to see action on.
