### ISSUE TITLE
Grafana persistant storage

### ISSUE THREAD

**Issue by swepps1** [openshift/openshift-ansible#10749]
I want to install OpenShift 3.11 system and I want to use cluster monitoring. Default install is grafana but don't use persistant storage. Do I have to use persistant storage for grafana? If I use persistant storage How can I configuration?

**Comment by vguaglione** [comment]
I ran into a similar issue with Grafana when I noticed that the accounts I created and dashboards I saved did not survive a pod redeploy.  I created a persistent volume claim for the deployment but that did not fix the problem, which was quite surprising.
