### ISSUE TITLE
Credentials exposed on console when logging into registry

### ISSUE THREAD

**Issue by leifmadsen** [openshift/openshift-ansible#10753]
#### Description

When logging into a registry using `oreg_auth_user` and `oreg_auth_password` the Ansible console exposes the values.

##### Version

openshift-ansible-3.11.44-1

##### Steps To Reproduce

Deploy with openshift-ansible with installation method openshift-enterprise and set the `oreg_auth_user` and `oreg_auth_password` variables.

##### Expected Results

Don't show credentials.

##### Observed Results

Credentials are shown at the console.

**Comment by michaelgugino** [comment]
This should not be happening.  no_log is set on the module level.
