### ISSUE TITLE
Install error: `l_docker_creds_image_dict`  will check useless image `openshift/ose` is exist or not

### ISSUE THREAD

**Issue by pichuang** [openshift/openshift-ansible#10756]
#### Description

At TASK [container_runtime : Create credentials for oreg_url], the task always pull the image openshift3/ose, not openshift3/ose-control-plane at OCP 3.11.16

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
```
$ ansible --version
ansible 2.6.3
  config file = /home/pichuang/code/mirror-images/ansible.cfg
  configured module search path = [u'/home/pichuang/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`
```
$ rpm -q openshift-ansible
openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch
```

##### Steps To Reproduce
1. Prepare fresh system
2. ```ansible-playbook -i hosts /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml```
3.
```
skopeo inspect docker://external.registry.local/openshift3/ose
skopeo inspect docker://external.registry.local/openshift3/ose:v3.11.16
```

##### Expected Results
Describe what you expected to happen.

```
Interrupt the installation process
```

##### Observed Results
Describe what is actually happening.

```
fatal: [master1.ocp.local]: FAILED! => {"attempts": 3, "changed": false, "msg": "time=\"2018-11-20T13:53:45+08:00\" level=fatal msg=\"Error reading manifest latest in external.registry.local/open
shift3/ose: manifest unknown: manifest unknown\" \n", "state": "unknown"}```
```

**Comment by pichuang** [comment]
I already had created the PR for openshift-docs https://github.com/openshift/openshift-docs/pull/12914 , and got the answer: https://github.com/openshift/openshift-docs/pull/12914#issuecomment-440599385

**Comment by pichuang** [comment]
Here is the PR https://github.com/openshift/openshift-ansible/pull/10757

**Comment by michaelgugino** [comment]
Seems openshift3/ose is missing from your registry.  Image version is not necessary to be included in the skopeo command.

**Comment by mtnbikenc** [comment]
PR merged.
