### ISSUE TITLE
[release-3.9]: node scale-up playbook not working

### ISSUE THREAD

**Issue by fefl** [openshift/openshift-ansible#10766]
#### Description

When trying to run the [Openshift 3.9 Node Scale-up playbook](https://github.com/openshift/openshift-ansible/blob/release-3.9/playbooks/openshift-node/scaleup.yml) it fails because a role could not be found

##### Version

```
ansible --version
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

git describe
openshift-ansible-3.9.51-1-2-g7cac1555a
```

##### Steps To Reproduce
1. Have an existing Openshift 3.9 Cluster
2. Try to add a worker node via running `ansible-playbook playbooks/openshift-node/scaleup.yml`

##### Expected Results
 
A worker node is added to my existing cluster

##### Observed Results
Describe what is actually happening.

```
ERROR! the role 'openshift_master_facts' was not found in /openshift-ansible/playbooks/openshift-node/roles:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/openshift-ansible/playbooks/openshift-node

The error appears to have been in '/openshift-ansible/playbooks/openshift-node/scaleup.yml': line 42, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
  - openshift_master_facts
    ^ here

```

##### Additional Information

We already found a fix for that and would like to provide a pull request for this.

**Comment by smossber** [comment]
For those that are hitting this and just want a workaround.. you can set the ENV before running the playbook:
ANSIBLE_ROLES_PATH=${DEFAULT_ROLES_PATH}:/usr/share/ansible/openshift-ansible/roles ansible-playbook -i inventory/hosts /usr/share/ansible/openshift-ansible/playbooks/openshift-node/scaleup.yml
