### ISSUE TITLE
Cloud provider: can't set Openstack LB endpoints to be Octavia using playbook

### ISSUE THREAD

**Issue by yboaron** [openshift/openshift-ansible#10762]
#### Description

Provide a brief description of your issue here. For example:

> The Openstack cloud provider Loadbalancer support both 
> Neutron LBaaSv2 and Octavia.
> Currently, it is impossible to set Loadbalaber endpoint as 
> Octavia using Openshift-ansible playbooks.

##### Version

```
ansible --version
ansible 2.5.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cloud-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

rpm -q openshift-ansible
openshift-ansible-3.11.44-1.git.0.11d174e.el7.noarch
(shiftstack) [cloud-user@bastion ~]$ 

```

##### Expected Results
Enables control of the following parameters (in addittion to openshift_cloudprovider_openstack_lb_subnet_id) in Openstack
 cloud provider  Loadbalancer via ansible playbook:

Use Octavia:  which OpenStack LBaaS endpoint (Octavia or Neutron LBaaS)
 should be used.

Floating IP network: the network ID in which floating IPs will be allocated from. If not specified, the first network that marked as external will be used.

**Comment by yboaron** [comment]
@codificat  - 10x for the update, I missed your PR.
Ooops..,  I also sent a patch to address this issue, https://github.com/openshift/openshift-ansible/pull/10763 

I guess I can abandon my PR, and assign you to https://bugzilla.redhat.com/show_bug.cgi?id=1648972
Is it OK with you?

**Comment by codificat** [comment]
Thanks @yboaron - I'm fine dropping my PR and going for yours instead, whatever works best. Your PR seems to have some reviewers already so that's probably the best option.

I don't think I should take the bug though, I believe someone from the installer team should take it over instead.

Probably @sdodson can help us decide.

**Comment by sdodson** [comment]
/cc @tzumainn @luis5tb
PTAL

**Comment by luis5tb** [comment]
Both PRs are pretty much the same. Based on @codificat suggestion, let's go for @yboaron's PR, ensuring it includes the var definition at  roles/openshift_cloud_provider/defaults/main.yml.

Thanks @codificat! And please review @yboaron PR too!

**Comment by luis5tb** [comment]
This was fixed in https://github.com/openshift/openshift-ansible/pull/10763
