### ISSUE TITLE
Loopback interface in /etc/hosts (127.0.1.1) can cause OpenShift Enterprise v3.10 installation failure

### ISSUE THREAD

**Issue by watsonb** [openshift/openshift-ansible#10775]
#### Description

If /etc/hosts contains an entry as follows:

```text
127.0.1.1  <hostname> <fqdn>
```

Then it appears that etcd binds to this loopback interface and prevents the master-api service from connecting to etcd, hence the task that waits for the control plane to appear will fail with the error message:

```bash
Control plane pods didn't come up
```

##### Version

```
Ansible 2.6.2
openshift-ansible-3.10.70-1-10-ge4e0d04
```

##### Steps To Reproduce
1. Spin up fresh RHEL7 VMs
2. Run prerequisites.yml playbook (success)
3. Run deploy_cluster.yml playbook (fails)

##### Expected Results

Expect Open Shift Enterprise v3.10 to deploy and be useable.

##### Observed Results
deploy_cluster.yml fails similar to the following:

```bash
FAILED - RETRYING: Wait for control plane pods to appear (57 retries left).Result was: {
    "attempts": 4,
    "changed": false,
    "invocation": {
        "module_args": {
            "all_namespaces": null,
            "content": null,
            "debug": false,
            "delete_after": false,
            "field_selector": null,
            "files": null,
            "force": false,
            "kind": "pod",
            "kubeconfig": "/etc/origin/master/admin.kubeconfig",
            "name": "master-etcd-master01.example.com",
            "namespace": "kube-system",
            "selector": null,
            "state": "list"
        }
    },
    "msg": {
        "cmd": "/usr/bin/oc get pod master-etcd-master01.example.com -o json -n kube-system",
        "results": [
            {}
        ],
        "returncode": 1,
        **"stderr": "The connection to the server master01.example.com:8443 was refused - did you specify the right host or port?\n",**
        "stdout": ""
    },
    "retries": 61
```

##### Additional Information

* Your operating system and version: Red Hat Enterprise Linux Server release 7.6 (Maipo)

Ansible Inventory:

This has happened to me using two "flavors" of inventories given by this project:

 - https://github.com/openshift/openshift-ansible/blob/master/inventory/hosts.example
 - https://github.com/openshift/openshift-ansible/blob/master/inventory/hosts.localhost

I was able to resolve this via an ad-hoc Ansible task before running the prerequisites.yml and deploy_cluster.yml playbooks as follows:

```bash
ansible all -i <path/to/inventory.ini> --private-key <path/to/key> -b -m lineinfile -a "path=/etc/hosts regexp='^127\.0\.1\.1' state=absent"
```

Performing the above on /etc/hosts allowed my OpenShift Enterprise v3.10 install to succeed on both a simple "all-in-one" inventory configuration and a "production-like" multi-host inventory configuration.

I'm merely leaving this here for posterity if anyone else runs into similar issues.

**Comment by vrutkovs** [comment]
API server runs in a dedicated container, so `/etc/hosts/` doesn't get mounted there and it can't resolve this address.

Please avoid using `/etc/hosts` for DNS, you need a proper external DNS solution to run OKD
