### ISSUE TITLE
"Could not find csr for nodes" after failed install

### ISSUE THREAD

**Issue by kanadaj** [openshift/openshift-ansible#10777]
#### Description

After a failed initial deploy_cluster install, it turned out that the problem was that the master node so I've set up a new master node to use on another server. Now the deploy_cluster task fails with the error `Could not find csr for nodes` for all worker nodes. uninstall does not fix this issue - there seems to be some permanent change done to the firewall, routing, certificate store or something else that's not covered by either uninstall.yml, prerequisites.yml or deploy_cluster.yml.

Beyond fixing this issue, is there a quick way to fix this without having to reinstall every worker node from scratch? That certainly works, but it's not a good way to retry a failed install...

##### Reproduction Steps

> Start installing a cluster
> Interrupt the process during the console kublet check or later
> Run uninstall.yml
> Retry the installation from a different master which wasn't part of the original inventory

##### Version

okd 3.10 and 3.11 both seem impacted

```
ansible 2.7.2
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

openshift-ansible-3.10.79-1-16-g5621b67
```

##### Additional Information

```
CentOS 7.5
Standard, simple inventory file for 1 master+infra node and a handful of worker nodes
```

**Comment by pennpeng** [comment]
@kanadaj can't support ansible 2.7
