### ISSUE TITLE
Contiv plugin status in release 3.11

### ISSUE THREAD

**Issue by amon-ra** [openshift/openshift-ansible#10788]
#### Description
I have tryed to install openshift cluster with contiv network with no luck, contiv plugin is not installed.

inventory

##### Version

```
- ansible: 2.6.5
- openshift-ansible-3.11.39-1-4-g09e30c824
```

##### Steps To Reproduce
1. deploy 

##### Expected Results
Contiv installed or tryed to install.

##### Observed Results

Contiv not installed, no network.

##### Additional Information

```

```

Inventory
```
[OSEv3:children]
masters
nodes
etcd


[OSEv3:vars]
ansible_user=root

openshift_enable_excluders=true
openshift_use_crio=False
openshift_use_crio_only=False
containerized=False
deployment_type=origin
openshift_deployment_type=origin
openshift_portal_net=172.28.0.0/15
osm_cluster_network_cidr=10.128.0.0/14
osm_host_subnet_length=9
os_firewall_use_firewalld=false

openshift_use_openshift_sdn=false
openshift_use_contiv=true
os_sdn_network_plugin_name='cni'

# Use the following contiv settings for now. 
# In upcoming versions of the installer, these settings will be automatically defaulted and hence not needed to be configured explicitly here
netplugin_interface=eth1
netmaster_interface=eth0
netplugin_fwd_mode=routing
contiv_encap_mode=vxlan
contiv_default_network_tag=1000


```

**Comment by amon-ra** [comment]
I have made some changes to try to install it. There are here: [](https://github.com/amon-ra/openshift-ansible/tree/oondeo-3.11) 
You could try it

**Comment by MikeySmet** [comment]
Does that mean Contiv isn't maintained anymore?
I see them working on https://github.com/contiv/vpp is it the same thing?

**Comment by MikeySmet** [comment]
I see that you commited a working change to your branch. Have you also tried the L2 Bridge mode?

**Comment by amon-ra** [comment]
No. I have tryed to work only in l3

**Comment by MikeySm** [comment]
Is your setup high available? Because we have some problems with using 3 masters.
The etcd proxy uses the certificate file of the first master to authenticate. This will throw access denied if the proxy connects to the other 2 masters.
