### ISSUE TITLE
Nodes don't reboot during 3.9 to 3.10 upgrade in spite of setting openshift_rolling_restart_mode=system

### ISSUE THREAD

**Issue by dharmit** [openshift/openshift-ansible#10797]
#### Description

I upgraded my OKD 3.9 cluster to OKD 3.10 but the nodes didn't reboot in spite of setting `openshift_rolling_restart_mode=system` in the inventory file. There's only one master and it did reboot. 

Based on point 3 in [**"Upgrading to the Latest OKD 3.10 Release"** section of documentation](https://docs.okd.io/3.10/upgrading/automated_upgrades.html#upgrading-to-ocp-3-10), I'm expecting all the systems in the cluster to reboot.

Cluster is installed on CentOS 7.5.1804.

##### Version

* Your ansible version per `ansible --version`
    ```bash
    $ ansible --version
    ansible 2.7.2
      config file = /etc/ansible/ansible.cfg
      configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/lib/python2.7/site-packages/ansible
      executable location = /usr/bin/ansible
      python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
    ```

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`
    ```bash
    $ rpm -q openshift-ansible 
    openshift-ansible-3.10.68-1.git.0.f908cf5.el7.noarch
    ```

##### Steps To Reproduce
1. Upgrade the OKD 3.9 cluster to OKD 3.10 using [this hosts file](https://gist.github.com/dharmit/669b19bdb4d5309e89379d532d56b9d5#file-3-10).
2. Commands used for upgrade:
    ```bash
    $ ansible-playbook -i hosts.310 /usr/share/ansible/openshift-ansible/playbooks/openshift-master/openshift_node_group.yml
    $ ansible-playbook -i hosts.310 /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_10/upgrade.yml
    ```

##### Expected Results
All the systems (masters and nodes) to reboot during the upgrade process.

##### Observed Results
Only master gets rebooted during the upgrade process. Nodes don't.
```bash
$ ansible -i hosts.310 -m shell all --args "uptime"
os-node-3.example.com | CHANGED | rc=0 >>
 09:30:28 up 7 days,  1:21,  1 user,  load average: 0.95, 0.89, 0.80

os-node-2.example.com | CHANGED | rc=0 >>
 09:30:28 up 7 days,  1:21,  1 user,  load average: 0.29, 0.47, 0.76

os-node-1.example.com | CHANGED | rc=0 >>
 09:30:29 up 7 days,  1:21,  1 user,  load average: 2.06, 1.77, 1.29

os-node-4.example.com | CHANGED | rc=0 >>
 09:30:28 up 7 days,  1:21,  1 user,  load average: 0.88, 0.68, 0.73

os-master-1.example.com | CHANGED | rc=0 >>
 09:30:58 up  1:10,  2 users,  load average: 2.45, 2.42, 2.47

os-node-6.example.com | CHANGED | rc=0 >>
 09:30:29 up 7 days,  1:21,  1 user,  load average: 0.54, 0.38, 0.49

os-node-8.example.com | CHANGED | rc=0 >>
 09:30:29 up 7 days,  1:21,  1 user,  load average: 1.03, 0.83, 0.81

os-node-9.example.com | CHANGED | rc=0 >>
 09:30:28 up 7 days,  1:21,  1 user,  load average: 0.91, 0.51, 0.56

os-node-5.example.com | CHANGED | rc=0 >>
 09:30:29 up 7 days,  1:21,  1 user,  load average: 1.03, 0.80, 0.78

os-node-7.example.com | CHANGED | rc=0 >>
 09:30:28 up 7 days,  1:21,  1 user,  load average: 1.51, 1.36, 1.05

os-node-10.example.com | CHANGED | rc=0 >>
 09:30:30 up 7 days,  1:21,  1 user,  load average: 0.87, 0.93, 1.00
```

**Comment by dharmit** [comment]
@vrutkovs can you help with this? Is this a bug or is something missing in the inventory file?

**Comment by vrutkovs** [comment]
Please attach the playbooks output with `ansible-playbook -vvv`

**Comment by dharmit** [comment]
We can't provide the output as things blew up in our environment and we ended up doing fresh 3.11 install.

Closing this issue as it's not relevant anymore.
