### ISSUE TITLE
Control plane pods didn't come up

### ISSUE THREAD

**Issue by K-DOT** [openshift/openshift-ansible#10798]
#### Description

Hi. I'm trying to install 2-node cluster with origin version 3.10 (one master, one node). Playbook fails on task `openshift_control_plane : Wait for control plane pods to appear`

*This situation also happens with version 3.11*

##### Version

Version information
* My ansible version per `ansible --version`
`ansible 2.6.5`

* The output of `git describe`
`openshift-ansible-3.10.82-1`

My inventory file:

```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
openshift_disable_check=disk_availability,memory_availability,docker_storage
openshift_release="3.10.0"
openshift_image_tag="v3.10.0"
openshift_pkg_version="-3.10.0"

openshift_deployment_type=origin
[masters]
openshift-master.itandwisdom.com openshift_public_ip=185.136.232.200 openshift_public_hostname=openshift-master.itandwisdom.com

[etcd]
openshift-node.itandwisdom.com openshift_node_group_name='node-config-compute' openshift_public_ip=185.136.233.130 openshift_public_hostname=openshift-node.itandwisdom.com

[nodes]
openshift-master.itandwisdom.com openshift_public_ip=185.136.232.200 openshift_public_hostname=openshift-master.itandwisdom.com openshift_schedulable=true openshift_node_group_name='node-config-master-infra'
openshift-node.itandwisdom.com openshift_public_ip=185.136.233.130 openshift_public_hostname=openshift-node.itandwisdom.com openshift_node_group_name='node-config-compute'
```

##### Steps To Reproduce
1. Use specified inventory file
2. ansible-playbook playbooks/playbooks/prerequisites.yml (runing ok)
3. ansible-playbook playbooks/deploy_cluster.yml (fails)

##### Expected Results
Successful playbook execution

##### Observed Results

```
Initialization              : Complete (0:00:35)
Health Check                : Complete (0:00:41)
Node Bootstrap Preparation  : Complete (0:01:39)
etcd Install                : Complete (0:00:31)
Master Install              : In Progress (0:18:40)
	This phase can be restarted by running: playbooks/openshift-master/config.yml


Failure summary:


  1. Hosts:    openshift-master.itandwisdom.com
     Play:     Configure masters
     Task:     Report control plane errors
     Message:  Control plane pods didn't come up

```

I'm attaching ansible-playbook execution output [gist](https://gist.github.com/K-DOT/2deb5590e781735ac3083693f0449e31)

##### Additional Information

My systems meet minimum requirements according documentation. I can't see any useful error messages in logs, but I'm still thinking that I'm missing something simple and obvious. 

My hosts:
`$ cat /etc/redhat-release` `CentOS Linux release 7.5.1804 (Core) `

**Comment by K-DOT** [comment]
I'm able to install version 3.6

**Comment by K-DOT** [comment]
@btito  I think it's enough to resolve all hosts with hostnames and FQDN to proceed the installation. If I understand correctly it's very wide issue and there are many reasons for it.

**Comment by K-DOT** [comment]
I discovered that etcd is restarting before api-server, so it can be the issue. I will check logs to find any useful information.

**Comment by nagonzalez** [comment]
Fix (downgrading docker to version 1.13.1-75 ) worked for me.

**Comment by K-DOT** [comment]
I found out that I had two different issues.
1. Hostname should contain FQDN
hostname == hostname -f https://github.com/openshift/origin/issues/21285
2. Docker exec command bug  https://bugzilla.redhat.com/show_bug.cgi?id=1655214

**Comment by ashutosh1701204** [comment]
How do we resolve this issue

**Comment by ashutosh1701204** [comment]
I facing similar issue

**Comment by kumardineshwar** [comment]
remove the dnsmasq rpm and restore /etc/resolv.conf which pointing to actual nameserver.
tested and working on 3.7 and 3.11
