### ISSUE TITLE
Issue with named certificates

### ISSUE THREAD

**Issue by sureddy** [openshift/openshift-ansible#1082]
we are trying to install third party signed certificates into OpenShift installation. used openshift_master_named_certificate variable to include the certfile and keyfile. Installation is failing with unknown certificate authority and bad certificate errors. Here are the some relevant sections of the ansible host file:

<pre>
[OSEv3:children]
masters
nodes

openshift_pkg_version=-1.1.0.1

openshift_master_overwrite_named_certificates = true
# Configure custom master certificates

# Detected names may be overridden by specifying the names key
openshift_master_named_certificates=[{"certfile": "certs/qtzio.crt", "keyfile": "certs/qtzio.key", "names": ["master-host.com"]}]
</pre>
Here are the errors that is preventing the installation.
<pre>
Dec 16 22:44:40 master origin-master: E1216 22:44:40.969816   28087 ensure.go:164] Unable to create default security context constraint privileged.  Got error: Post https://master.sap.qtz.io/api/v1/securitycontextconstraints: x509: certificate signed by unknown authority
Dec 16 22:44:40 master origin-master: E1216 22:44:40.971105   28087 ensure.go:164] Unable to create default security context constraint nonroot.  Got error: Post https://master.sap.qtz.io/api/v1/securitycontextconstraints: x509: certificate signed by unknown authority
Dec 16 22:44:40 master origin-master: E1216 22:44:40.972333   28087 ensure.go:164] Unable to create default security context constraint hostmount-anyuid.  Got error: Post https://master.sap.qtz.io/api/v1/securitycontextconstraints: x509: certificate signed by unknown authority
Dec 16 22:44:40 master origin-master: E1216 22:44:40.973509   28087 ensure.go:164] Unable to create default security context constraint hostaccess.  Got error: Post https://master.sap.qtz.io/api/v1/securitycontextconstraints: x509: certificate signed by unknown authority
Dec 16 22:44:40 master origin-master: E1216 22:44:40.975215   28087 ensure.go:164] Unable to create default security context constraint restricted.  Got error: Post https://master.sap.qtz.io/api/v1/securitycontextconstraints: x509: certificate signed by unknown authority
Dec 16 22:44:40 master origin-master: E1216 22:44:40.977004   28087 ensure.go:164] Unable to create default security context constraint anyuid.  Got error: Post https://master.sap.qtz.io/api/v1/securitycontextconstraints: x509: certificate signed by unknown authority
Dec 16 22:44:40 master origin-master: E1216 22:44:40.980189   28087 ensure.go:106] Error adding service account roles to "default" namespace: Get https://master.sap.qtz.io/api/v1/namespaces/default: x509: certificate signed by unknown authority
Dec 16 22:44:40 master origin-master: E1216 22:44:40.981527   28087 ensure.go:50] Error creating namespace openshift-infra: Post https://*******/api/v1/namespaces: x509: certificate signed by unknown authority
Dec 16 22:44:40 master journal: http: TLS handshake error from x.x.x.x:37219: remote error: bad certificate
</pre>
Found similar case [#861](https://github.com/openshift/openshift-ansible/issues/861) and uninstalled, re-installed couple of times. Same error.

Since there is no parameter to set the CA cert in the named_certificates variables, we concatenated server-cert and ca-cert into one file and used that as the certfile. One error says unknown certificate authority and other error says handshake failure: bad certificate.

Are we doing anything wrong in the definition of named_certificates? Does openshift ansible playbook support adding third party certificates?

**Comment by abutcher** [comment]
Hey @sureddy, it looks like the custom certificate is being provided for the internal master hostname.

Have you set `openshift_master_cluster_hostname` and `openshift_master_cluster_public_hostname` in the ansible inventory? The named certificate should only be used for the `openshift_master_cluster_public_hostname`.

**Comment by sureddy** [comment]
yes. here is the relevant parts of the hosts:
<pre>
openshift_master_cluster_hostname=master-host.com
openshift_master_cluster_public_hostname=master-host.com
</pre>

I uninstalled and reinstalled again. same problem.
<pre>
Dec 17 00:38:17 master journal: http: TLS handshake error from *.*.*.* :35920: remote error: bad certificate

Dec 17 00:38:17 master journal: http: TLS handshake error from *.*.*.* :35922: remote error: bad certificate

Dec 17 00:38:17 master origin-master: F1217 00:38:17.680071   14144 run_components.go:390] Unable to initialize namespaces: unable to refresh the security allocation UID blocks: Get https://master/api/v1/namespaces: x509: certificate signed by unknown authority
</pre>

**Comment by abutcher** [comment]
Changing `openshift_master_cluster_hostname` to a different name will solve the problem. OpenShift is expecting installer generated certificates for inter-cluster requests and since the public name is the same as the internal name, the API is serving the custom certificate for both.

I think we could do more validation here and provide an error during install when named certificates are supplied and cluster_hostname matches cluster_public_hostname.

**Comment by sureddy** [comment]
@abutcher thank you so much. it did the magic. it worked now.

**Comment by abutcher** [comment]
Great!

**Comment by vishal-biyani** [comment]
@abutcher Would this also work with self-generated certificates?

**Comment by abutcher** [comment]
@vishal-biyani Yes, but named certificates are only for serving custom (+self signed) certificates for api/console traffic. https://docs.openshift.com/container-platform/3.4/install_config/certificate_customization.html#configuring-custom-certificates

**Comment by vishal-biyani** [comment]
Thanks @abutcher That helped with the issue I had.
