### ISSUE TITLE
Add XPaaS v1.2 templates and image streams

### ISSUE THREAD

**Issue by zroubalik** [openshift/openshift-ansible#1083]
Templates and image streams for XPaaS v1.2 release should be added. 
https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples

**Comment by sdodson** [comment]
@zroubalik can you please review #1086

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
