### ISSUE TITLE
OKD 3.11: Route to httpd example application not working

### ISSUE THREAD

**Issue by DizzyThermal** [openshift/openshift-ansible#10830]
#### Description

After installing OKD 3.11, I deploy an application from the service catalog to test out a route. When visiting the route created in the Web Console, Chrome returns: "This site can't be reached : httpd-ex-default.apps.example.com refused to connect.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

```
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

If you're operating from a **git clone**:

* The output of `git describe`
```
openshift-ansible-3.11.52-1
```

##### Steps To Reproduce
1. Node setup: 2 masters, 2 external etcd, 1 load-balancer, 2 nodes, 2 infra-nodes -- inventory file being used:

```
[OSEv3:children]
masters
etcd
lb
nodes

[masters]
master[1:2].example.com

[etcd]
etcd[1:2].example.com

[lb]
lb1.example.com

[nodes]
master[1:2].example.com openshift_node_group_name='node-config-master'
node[1:2].example.com openshift_node_group_name='node-config-compute'
infra-node[1:2].example.com openshift_node_group_name='node-config-infra'


[OSEv3:vars]
ansible_ssh_user=root

openshift_master_api_port=8443
openshift_master_console_port=8443

os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

openshift_deployment_type=origin
openshift_release=v3.11

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

openshift_master_cluster_method=native
openshift_master_cluster_hostname=console.example.com
openshift_master_default_subdomain=apps.example.com

## Needed for OKD 3.11
openshift_additional_repos=[{'id': 'centos-paas', 'name': 'centos-paas','baseurl' :'https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin311','gpgcheck' :'0', 'enabled' :'1'}]
```

2. DNS Server running DNSMasq with:

**/etc/hosts**:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.4.1.100  ns1.example.com ns1
10.4.1.101  lb1.example.com lb1 console.example.com console
10.4.1.102  master1.example.com master1
10.4.1.103  master2.example.com master2
10.4.1.104  etcd1.example.com etcd1
10.4.1.105  etcd2.example.com etcd2
10.4.1.106  node1.example.com node1
10.4.1.107  node2.example.com node2
10.4.1.108  infra-node1.example.com infra-node1
10.4.1.109  infra-node2.example.com infra-node2
```

**/etc/dnsmasq.conf**:
```
conf-dir=/etc/dnsmasq.d,.rpmnew,.rpmsave,.rpmorig

strict-order
domain-needed
local=/example.com/
bind-dynamic
log-queries

address=/.apps.example.com/10.4.1.101 # load-balancer
```

**/etc/resolv.conf** on each Node (DNS nameserver [ns1] additionally has an upstream DNS):
```
# Generated by NetworkManager
search example.com
nameserver 10.4.1.100
```

**dig output to test DNS resolution -- run from Load Balancer**:
```
[root@lb1 ~]# dig ns1.example.com @10.4.1.100 +short                                                                                                            
10.4.1.100
[root@lb1 ~]# dig lb1.example.com @10.4.1.100 +short                                                                                                            
10.4.1.101
[root@lb1 ~]# dig master1.example.com @10.4.1.100 +short
10.4.1.102
[root@lb1 ~]# dig master2.example.com @10.4.1.100 +short
10.4.1.103
[root@lb1 ~]# dig etcd1.example.com @10.4.1.100 +short
10.4.1.104
[root@lb1 ~]# dig etcd2.example.com @10.4.1.100 +short
10.4.1.105
[root@lb1 ~]# dig node1.example.com @10.4.1.100 +short                                                                                                          
10.4.1.106
[root@lb1 ~]# dig node2.example.com @10.4.1.100 +short
10.4.1.107
[root@lb1 ~]# dig infra-node1.example.com @10.4.1.100 +short
10.4.1.108
[root@lb1 ~]# dig infra-node2.example.com @10.4.1.100 +short
10.4.1.109
```

3. Installing from the DNS Nameserver (IP: 10.4.1.100), keys copied to all nodes (including self) via: ssh-copy-id:
```
for host in \
  lb1.example.com \
  master1.example.com \
  master2.example.com \
  etcd1.example.com \
  etcd2.example.com \
  node1.example.com \
  node2.example.com \
  infra-node1.example.com \
  infra-node2.example.com; \
  do
    ssh-copy-id ${host}; \
  done
```

4. Ran Prerequisite Playbook:
```
# ansible-playbook -i inventory.ini openshift-ansible/playbooks/prerequisites.yml
```

5. Ran Deploy Cluster Playbook:
```
# ansible-playbook -i inventory.ini openshift-ansible/playbooks/deploy_cluster.yml
```

##### Expected Results

I expect to be able to visit the deployed application from the Openshift Service Catalog (Apache (httpd)) via the created route: httpd-ex-default.apps.example.com

##### Observed Results

This site can’t be reached httpd-ex-default.apps.example.com refused to connect.

I am unable to visit the route.

#### Additional Notes

I have been trying to deploy this cluster for a couple weeks now. The only instance that I've ever had working was the single-node, all-in-one configuration after following gshipley's installcentos video/repo.

I am unable to locate the root cause for Routes not working.. I've tried to deploy the application in the "default" project and a newly create project, same result.

All 10 nodes are running CentOS 7.5 (DNS, Load balancer, master1, master2, etcd1, etcd2, node1, node2, infra-node1, and infra-node2).

Any insight into what may be going wrong is greatly appreciated. Thanks!

**Comment by koksj** [comment]
@DizzyThermal 

Does your install perhaps end with something like the below ?

Failure summary:
  1. Hosts:    192.168.100.21
     Play:     Deploy the central bootstrap configuration
     Task:     create node-config.yaml configmap
     Message:  {u'cmd': u'/usr/bin/oc create configmap node-config-master --from-file=node-config.yaml=/tmp/openshift_node_config-rIrNMz/node-config.yaml -n openshift-node', u'returncode': 1, u'results': {}, u'stderr': u'The connection to the server master.okd.cluster:8443 was refused - did you specify the right host or port?\n', u'stdout': u''}

**Comment by koksj** [comment]
@DizzyThermal 

Agreed, looks like a separate issue. Thank you for the prompt response.

**Comment by DizzyThermal** [comment]
Turns out this was an issue with the way I provisioned one of my master nodes. Double/triple check that your nodes are **clean** if you're running into install issues! One of my nodes had docker installed pre-installation, with an incorrect subnet mask that I had erroneously snapshotted and considered "clean".

Sorry for the noise, closing this issue.
