### ISSUE TITLE
"openshift_web_console_inactivity_timeout_minutes" variable skipped during deployment

### ISSUE THREAD

**Issue by Goblins-Trainins-Center** [openshift/openshift-ansible#10840]
#### Description
OpenShift Web Console  custom variables  are not pickedup from inventory.  During cluster deployment play or  dedicated playbook  _playbooks/openshift-web-console/config.yml_ .

##### Version
Playbooks: openshift-ansible-3.9.45-1
Cluster: v3.9.0

##### Steps To Reproduce
According to  docs  following variable was introduce as one that can be use in inventory  to change default settings of inactivity time in WebUI console during cluster deployment:
`openshift_web_console_inactivity_timeout_minutes: 15`

During ansible play all task regarding config change are skipped:

`TASK [openshift_web_console : Set web console config properties from inventory variables] ***10:00:16
Friday 07 December 2018  10:00:16 +0100 (0:00:00.120)       0:01:04.389 ******* 
skipping: [master2]
`

`TASK [openshift_web_console : Migrate assetConfig from master-config.yaml] *****10:00:16
Friday 07 December 2018  10:00:16 +0100 (0:00:00.115)       0:01:04.505 ******* 
skipping: [master2]`

and config map of Web Console has got default value seto to 0

##### Expected Results
After cluster deployment Openshif Web Console should have inactivity time set to 15 min.
Changes based on variable stored in inventory should be used during playbook.

**Comment by vrutkovs** [comment]
These tasks are being skipped since web console configmap already exists

**Comment by Goblins-Trainins-Center** [comment]
Ok, thus , what is the best approach to setup this thing during initial deployment of cluster ?

**Comment by angelbarrera92** [comment]
I have encountered the same problem in an openshift 3.9 installation. 
**Is there any way to change this behaviour?** 
This value seems to be able to be setup during initial cluster deployment. But i know some cases when this value has to be changed during cluster's live.

The workaround i followed to update this value is to remove the configmap and rerun the webconsole config ansible playbook.

```bash
$ oc project openshift-web-console
$ echo "Backup the actual configuration"
$ oc get cm webconsole-config -o yaml > webconsole-config.backup.yaml
$ echo "Once edited your ansible variables adding openshift_web_console_inactivity_timeout_minutes variable, rerun the ansible playbook"
$ ansible-playbook -i inventory/  /usr/share/ansible/openshift-ansible/playbooks/openshift-web-console/config.yml"
$ echo "Checking the change" 
$ oc get cm webconsole-config -o yaml | grep inactivityTimeoutMinutes -m 1
      inactivityTimeoutMinutes: 60
```
Once configmap is updated, is important to make a webconsole deployment rollout.

```bash
$ oc patch deployment webconsole -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
```

Thanks!
