### ISSUE TITLE
origin-ansible:v3.11 as a system container fails on fedora and redhat atomic during prerequisites.yml with libselinux-python

### ISSUE THREAD

**Issue by crissonpl** [openshift/openshift-ansible#10849]
#### Description

I'm trying to install okd from openshift-ansible v3.11 on a clean install of fedora and redhat atomic as a system container and on both it fails complaining about libselinux-python.

##### Version

Fedora - Generic release 29 (Generic)
Atomic - 7.6.1
openshift-ansible-3.11.53-1

##### Steps To Reproduce
1. install clean Fedora or Atomic 
2. install prerequisites
3. clone git repo
4. atomic install --system     --storage=ostree     --set INVENTORY_FILE=/root/development/okd/openshift-ansible/inventory/hosts.localhost --set PLAYBOOK_FILE=/usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml     --set OPTS="-v"     docker.io/openshift/origin-ansible:v3.11

##### Observed Results
```TASK [openshift_repos : Ensure libselinux-python is installed] *****************
Sunday 09 December 2018  10:07:17 +0000 (0:00:00.048)       0:00:05.244 *******
FAILED - RETRYING: Ensure libselinux-python is installed (3 retries left).
FAILED - RETRYING: Ensure libselinux-python is installed (2 retries left).
FAILED - RETRYING: Ensure libselinux-python is installed (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "Failure talking to yum: failure: repodata/repomd.xml from azure-cli: [Errno 256] No more mirrors to try.\nhttps://packages.microsoft.com/yumrepos/azure-cli/repodata/repomd.xml: [Errno 16] error opening local file from https://packages.microsoft.com/yumrepos/azure-cli/repodata/repomd.xml, IOError: [Errno 30] Read-only file system: '/var/cache/yum/x86_64/7/azure-cli/repomdXmwN_ftmp.xml'"}```

**Comment by TecHunter** [comment]
Had the same problem. the package for python3 is 'python3-libselinux' 
Renaming in `roles/openshift_repos/tasks/main.yaml` fixes this problem. Then I have the same problem later with more deps
