### ISSUE TITLE
Snap package support(Feature Request)

### ISSUE THREAD

**Issue by mikeroyal** [openshift/openshift-ansible#10847]
I was thinking the install and setup could be improved for Ubuntu and other Linux distros by having a [snap package](https://snapcraft.io/) version. If it's not a priority would you mind if I made the snap?

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by vrutkovs** [comment]
Could the snap be updated via travis-ci? 
Making a snap is okay, but once its submitted we should be updating it

**Comment by mikeroyal** [comment]
@vrutkovs,

Yes, you could use TravisCI or build.snapcraft.io, you'll get per-commit or daily updates in the edge channel in the store with no additional work from you. When you do stable releases, you can "snapcraft release openshift-ansible stable" and that will point the stable channel at that revision. It's possible to push beta releases to the beta channel so more technical users and committed community people can test it. But that's up to you. Essentially there's not a huge amount of maintenance in keeping the snap up to date. 

Security wise each snap is confined using a range of kernel isolation and security mechanisms, tailored to the snap, ensuring that vulnerabilities in the application are contained to the greatest degree currently possible. A careful review process ensures that snaps only receive the permissions they require to operate. Users do not have to make complex security decisions when installing the snap. You can read more about the security and configurations here [a guide to snap permissions and interfaces](https://blog.ubuntu.com/2018/11/01/a-guide-to-snap-permissions-and-interfaces).
