### ISSUE TITLE
HA labels on individual nodes 

### ISSUE THREAD

**Issue by aramalipoor** [openshift/openshift-ansible#10853]
#### Description

After 3.10 release we can't add labels with HA purpose, e.g. zone, region, rack, baremetal for individual nodes, via openshift-ansible.

From: https://docs.okd.io/3.10/install/configuring_inventory_file.html#configuring-inventory-defining-node-group-and-host-mappings

> While previously node labels could be set using the openshift_node_labels variable, starting in OKD 3.10 you must instead create your own custom node groups if you want to modify the default labels that are assigned to node hosts.

I think this removes a large use case for labelling nodes in the inventory. Servers to node groups is a many-to-one mapping, whereas servers to labels is many-to-many, so for every distinct set of labels you wish to use you need to create a separate node group.

One example is I want to label my nodes with the physical rack they are located in so I can configure the scheduler to distribute pods across racks. Using openshift_node_labels I can do this easily in the inventory. With openshift_node_group_name I'd have to create new node groups for each rack which only differs by the label value, so I'd end up with node groups like:

infra-rack-1
build-rack-1
compute-rack-1
infra-rack-2
build-rack-2
compute-rack-2
...
If I want to add another label dimension then adding node groups for each permutation of labels becomes unmaintainable.

To me it makes more sense to define these static labels in the inventory instead of dynamically running oc label node....

Is there a recommended way of doing that except having to write custom ansible roles (e.g. to read VM's metadata and add corresponding labels to each node.)?

#### Version
3.10

**Comment by vrutkovs** [comment]
Custom labels should be specified in custom node groups, see https://github.com/openshift/release/blob/master/cluster/test-deploy/gcp-dev/vars.yaml#L27-L39 for example

**Comment by vrutkovs** [comment]
There is no per-host labels indeed, but you can label those manually after the install or assign host-specific group
