### ISSUE TITLE
How to change openshift_node_group_name for a node in existing cluster?

### ISSUE THREAD

**Issue by dharmit** [openshift/openshift-ansible#10867]
#### Description
I would like to change the `openshift_node_group_name` for a few nodes in my cluster. I added a node group in the `openshift_node_groups` variable in the inventory file and changed the value for a couple of nodes under the `[nodes]` section and executed the `/usr/share/ansible/openshift-ansible/playbooks/openshift-master/openshift_node_group.yml` playbook but that didn't cause any changes.

What's the right way to change the node group for a node in the existing cluster?

##### Version
OKD 3.10 and OKD 3.11

##### Steps To Reproduce
1. Add a new node group in the `openshift_node_groups` variable in the inventory file
2. Change the value for a couple of nodes under the `[nodes]` section
3. Execute the `/usr/share/ansible/openshift-ansible/playbooks/openshift-master/openshift_node_group.yml` playbook

##### Expected Results
Node group for the hosts should have changed

##### Observed Results
Node group for the hosts stays as-is.

**Comment by suifengpiao14** [comment]
I met the same needs.
I change the node label
for example change the  role from infra to compute for  node A
process
1.  add compute label
 oc label node  A node-role.kubernetes.io/compute=true
2. delete infra label
oc label node  A node-role.kubernetes.io/compute-

now list all labels
oc label node A --list

it work for me

**Comment by vrutkovs** [comment]
`openshift_node_group.yml` would create necessary groups, not reconfigure masters. You'd need to redeploy the cluster to change node groups

**Comment by Drakkai** [comment]
@vrutkovs Are you sure that there is no option to change `openshift_node_group_name` for existing nodes? Is the only option to reassign node to other group by redeploying whole cluster? 

@suifengpiao14 node-role is not the same as `openshift_node_group_name`, it is not possible to change it via `oc label node`.

**Comment by vrutkovs** [comment]
@Drakkai yes, `oc label node` would work only for node labels, not other items in node config like kubelet args

**Comment by ServerNinja** [comment]
@vrutkovs , `oc label node` doesn't seem to persist when a node is rebooted. On the other hand, if I needed to add a new "node group" and re-assign an existing node to it that is not possible? It seems like this greatly reduces the flexibility for growth.

I have developers who are pushing new microservices that will require their own group of nodes to run on and it seems like there is no good way take 5 of our nodes and re-assign them to a new node group so we can do this. Is there any way this can be done?

**Comment by vrutkovs** [comment]
>oc label node doesn't seem to persist when a node is rebooted

If the node got a new address or dns name then OpenShift can't match its labels. Otherwise it should be persisted.

>re-assign an existing node to it that is not possible?

It should be possible to re-assign node labels via inventory update and rerunning `playbooks/openshift-master/openshift_node_group.yml`

**Comment by ServerNinja** [comment]
@vrutkovs , thanks for the quick response. If we run the scaleup playbook to add new nodes and we wish to add a new node with a new openshift_node_group... does scaleup run this playbook?
