### ISSUE TITLE
Openstack playbook fails using Rocky (via Packstack)

### ISSUE THREAD

**Issue by frippe75** [openshift/openshift-ansible#10888]
#### Description

Running the openstack playbook fails on the step where the stack gets deployed. The instances gets added (building), connected to the network then goes back to being unconnected. And after a while it looks like the stack is deployed a second time. I get double the nodes and finally ends with exceeding the core quota of my Openstack env.

##### Version

```
[centos@deploy openshift-ansible]$ git describe
openshift-ansible-4.0.0-0.95.0-26-g09ac753
[centos@deploy openshift-ansible]$ ansible --version
ansible 2.7.4
  config file = /home/centos/openshift-on-openstack/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### Steps To Reproduce
source keystonerc_openshift

ansible-playbook --user openshift \
  -i openshift-ansible/playbooks/openstack/inventory.py \
  -i inventory \
  openshift-ansible/playbooks/openstack/openshift-cluster/provision_install.yml

##### Expected Results
Have a running openshift-cluster stack
This is the only thing runing in my project/quota limit. I'm running the default number of nodes and the suggested flavor with 2core/instance. 
```
    "stack_create_failures": {
        "changed": true,
        "cmd": [
            "openstack",
            "stack",
            "failures",
            "list",
            "openshift-cluster"
        ],
        "delta": "0:00:23.520152",
        "end": "2018-12-14 13:24:30.409452",
        "failed": false,
        "rc": 0,
        "start": "2018-12-14 13:24:06.889300",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "openshift-cluster.infra_nodes.0.server:\n  resource_type: OS::Nova::Server\n  physical_resource_id: \n  status: CREATE_FAILED\n  status_reason: |\n    Forbidden: resources.server: Quota exceeded for cores: Requested 2, but already used 29 of 30 cores (HTTP 403) (Request-ID: req-0a50afdf-9992-495d-bea2-dfe804c28e65)",
        "stdout_lines": [
            "openshift-cluster.infra_nodes.0.server:",
            "  resource_type: OS::Nova::Server",
            "  physical_resource_id: ",
            "  status: CREATE_FAILED",
            "  status_reason: |",
            "    Forbidden: resources.server: Quota exceeded for cores: Requested 2, but already used 29 of 30 cores (HTTP 403) (Request-ID: req-0a50afdf-9992-495d-bea2-dfe804c28e65)"
        ]
    }



  1. Hosts:    localhost
     Play:     Create the OpenStack resources for cluster installation or scaleup
     Task:     openshift_openstack : fail
     Message:  Stack creation failed

```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```
Openshift-Ansible generated Openstack Heat templates
https://gist.github.com/frippe75/125d967d798eefa840b37857c9b51af0

##### Additional Information

```
CentOS 7.6 / Openstack Rocky Release
```

**Comment by tzumainn** [comment]
That's odd; at worst the stack should be updated, and not created twice. There's that issue, but also the question of why the stack fails to create in the first place.

Would it be possible to edit the following line for now?

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_openstack/tasks/provision.yml#L92

Set that to 0, and then re-run. If/when that fails, can you paste the output of heat stack-show for the openshift-cluster stack?

**Comment by frippe75** [comment]
Hi, thanks for responding!

Just running with retries set to 1.
Looked through the heat templates and notived an Octavia resource. I don't have Octavia deployed and it's not available via Packstack to my knowlegde.

Looking at the deploy options (inventory/group_vars/all.yml)
#openshift_openstack_use_lbaas_load_balancer: false
#openshift_openstack_use_vm_load_balancer: false

Not sure what this defaults to or if it's even related. 
Do I have to deploy Octavia. Was planning on doing that manually but remember it being quite time consuming having done it for Newton release ...

**Comment by tzumainn** [comment]
Interesting! As far as I can tell, that means that Octavia resources shouldn't be being deployed in the Heat stack. Would it be possible to update the all.yml that you're using, as well as the output of 'openstack stack template show'? That should give some information that can help me figure out what's going on.

**Comment by tzumainn** [comment]
Hm, I think this is probably not representative of your initial issue; the heat template shows no resources being created, which is probably incorrect. I know Heat can be a bit flaky in PackStack; could you make sure no openstack servers exist, and then re-deploy setting the stack name to something different, using these instructions?

https://github.com/openshift/openshift-ansible/blob/master/playbooks/openstack/configuration.md#stack-name-configuration

Then copy and paste the 'openstack stack template show' output.

**Comment by frippe75** [comment]
ok will try that. I do the deploy from an instance in this openstack env. But I guess I could run it from the laptop.

**Comment by tzumainn** [comment]
Ah, that instance can stay! Just want to make sure no leftover masters/app nodes/infra nodes for the aborted openshift cluster exist. Sorry for not being clearer!

**Comment by frippe75** [comment]
I think I solved my issue. Was not related to this repo. I added more storage to nova/libvirt and forgot to restore selinux context on that dir. So cinder could not provision storage for the vm's. Strange that I got multiple instances. But maybe that's an issue with the "retires". It retires for the wrong reason. Maybe the playbook should simply fail at this stage. But you can close this issue. Thanks for the support!

**Comment by frippe75** [comment]
Not sure you want to discuss this here, if not just close the issue.

My deploy fails probably because i'm behind a http proxy instead of having internet access.

[openshift@master-0 ~]$ sudo cat /var/lib/cloud/instance/scripts/runcmd
#!/bin/sh
'ansible-playbook' '/root/openshift_bootstrap/bootstrap.yml'

[openshift@master-0 ~]$ sudo cat /root/openshift_bootstrap/bootstrap.yml
cat: /root/openshift_bootstrap/bootstrap.yml: No such file or directory

ansible does not get installed and files expected under /root are not there. 
I have added http_proxy/https_proxy and yum proxy conf to the image via /etc/profile.d/proxy.sh

Ususally my cloud-init stuff works using this method but maybe sitting behind a proxy is not support either way...
