### ISSUE TITLE
OKD 3.11: etcd node scaleup.yml error (external etcd)

### ISSUE THREAD

**Issue by DizzyThermal** [openshift/openshift-ansible#10889]
#### Description

When attempting to run playbooks/openshift-etcd/scaleup.yml to add an additional external etcd node, the playbook fails with:

```
TASK [etcd : Add new etcd members to cluster] ******************************************************************************************************************************************
fatal: [etcd3.example.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'etcdctlv2'\n\nThe error appears to have been in '/root/openshift-ansible/roles/etcd/tasks/add_new_member.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add new etcd members to cluster\n  ^ here\n"}
```

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

```
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

If you're operating from a **git clone**:

* The output of `git describe`
```
openshift-ansible-3.11.57-1-8-gd969826
```

##### Steps To Reproduce
1. Create new CentOS 7 node, give a static IP address, and setup it's DNS to similar to the preinstalled nodes.
2. Run ansible playbook:

```
ansible-playbook -i inventory.ini openshift-ansible/playbooks/openshift-etcd/scaleup.yml
```

##### Expected Results
Node to be added as an additional etcd to the pre-existing cluster

##### Observed Results
Playbook fails with error:

```
TASK [etcd : Add new etcd members to cluster] ******************************************************************************************************************************************
fatal: [etcd3.example.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'etcdctlv2'\n\nThe error appears to have been in '/root/openshift-ansible/roles/etcd/tasks/add_new_member.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add new etcd members to cluster\n  ^ here\n"}
```

##### Additional Information

Inventory File:

```
[OSEv3:vars]
ansible_ssh_user=root

openshift_deployment_type=origin
openshift_release=v3.11

openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'

openshift_master_cluster_method=native
openshift_master_cluster_hostname=lb1.example.com
openshift_master_cluster_public_hostname=console.example.com
openshift_master_default_subdomain=apps.example.com

openshift_master_api_port=8443
openshift_master_console_port=8443

## Needed for OKD 3.11
openshift_additional_repos=[{'id': 'centos-paas', 'name': 'centos-paas','baseurl' :'https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin311','gpgcheck' :'0', 'enabled' :'1'}]

[OSEv3:children]
masters
etcd
lb
nodes
new_etcd

[masters]
master[1:3].example.com

[etcd]
etcd[1:2].example.com

[lb]
lb1.example.com

[nodes]
master[1:3].example.com openshift_node_group_name='node-config-master'
node[1:3].example.com openshift_node_group_name='node-config-compute'
infra-node[1:3].example.com openshift_node_group_name='node-config-infra'

[new_etcd]
etcd3.example.com
```

I was successful in scaling up an additional **master**, **node** (compute), and **infra-node** (infrastructure) today.. This was the type that happened to fail.

The output looks a bit odd, not sure if it's a bug or an issue on my end. Any suggestions?

Thanks all in advance!

**Comment by chuenlye** [comment]
The same issue with you. 

One temporary solution:
```
ansible-playbook -i inventory.ini openshift-ansible/playbooks/openshift-master/config.yml openshift-ansible/playbooks/openshift-etcd/scaleup.yml
```

That works well for me.

**Comment by sdodson** [comment]
Yes, in order to scale up etcd on 3.10 and 3.11 you first need to make the host a master, then run the etcd scaleup.

 # Add host to [new_masters] [new_nodes] run playbooks/openshift-master/scaleup.yml
 # Move host from [new_masters] [new_nodes] to [masters] [nodes]
 # Add host to [new_etcd] run playbooks/openshift-etcd/scaleup.yml
 # move host from [new_etcd] to [etcd]

**Comment by SmoothGlide** [comment]
> Yes, in order to scale up etcd on 3.10 and 3.11 you first need to make the host a master, then run the etcd scaleup.
> 
> 1. Add host to [new_masters] [new_nodes] run playbooks/openshift-master/scaleup.yml
> 2. Move host from [new_masters] [new_nodes] to [masters] [nodes]
> 3. Add host to [new_etcd] run playbooks/openshift-etcd/scaleup.yml
> 4. move host from [new_etcd] to [etcd]

I just wanna clarify the process here.
Step 1 - makes sense
Step 2 - Move the node - do I run any playbook at this point?
Step 3 - makes sense
Step 4 - do I run a playbook here?  Does the new etcd node remain under nodes, masters and etcd?

**Comment by SmoothGlide** [comment]
Anyone?

**Comment by slaterx** [comment]
@SmoothGlide after you successfully run the scaleup playbook there's no need to keep the host on the [new_<NAME>] section, therefore you can safely move those hosts to [<NAME>] section. 

Run the scaleup playbook for your master/nodes, then do the etcd scaleup if previous scaleup was successful.
