### ISSUE TITLE
No package matching 'origin-docker-excluder-4.0**' found available

### ISSUE THREAD

**Issue by frippe75** [openshift/openshift-ansible#10897]
**Failure summary:**

  1. Hosts:    app-node-0.openshift.lab.net, app-node-1.openshift.lab.net, app-node-2.openshift.lab.net, infra-node-0.openshift.lab.net, master-0.openshift.lab.net
     Play:     oo_nodes_to_config
     Task:     Install docker excluder - yum
     Message:  **No package matching 'origin-docker-excluder-4.0**' found available, installed or updated**
[centos@deploy openshift-on-openstack]$

Info in older issue was to log this for each new "missing version".

**Comment by khrm** [comment]
Use the repo at https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo.

```
 cd /etc/yum.repos.d && curl -O https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo```

**Comment by frippe75** [comment]
Will try that! Thanks @khrm

**Comment by vrutkovs** [comment]
Correct repos need to be specified, not an openshift-ansible issue

**Comment by rafi494** [comment]
@khrm Thanks . Worked for me .

**Comment by 4F2E4A2E** [comment]
This is not working anymore.
