### ISSUE TITLE
Can't view any routes (cluster console, registry console, ...): always redirected to catalog page

### ISSUE THREAD

**Issue by jomeier** [openshift/openshift-ansible#10900]
Hi, 

since a few days with new installations of OKD v3.11 I'm in the situation of not getting any route working.

Neither the cluster console, the registry console are working. I'm always redirected to the catalog page after I logged in to any of this pages.

I'm not using custom certificates.

Does anybody have an idea?

Best regards,

Josef

**Comment by maverick85** [comment]
I am having the exact same issue.
Have you advanced in any manner? thanks!

Ricardo

**Comment by fjakop** [comment]
Having the same problem. *.apps is pointing to master node (IP of node01e.my.domain).

My inventory looks like this
```
[masters]
node01e.my.domain

[etcd]
node01e.my.domain
node02e.my.domain
node03e.my.domain

[nodes]
node01e.my.domain openshift_node_group_name='node-config-master'
node02e.my.domain openshift_node_group_name='node-config-compute'
node03e.my.domain openshift_node_group_name='node-config-infra'

[OSEv3:vars]
openshift_master_default_subdomain=apps.another.domain
openshift_master_api_port=443
openshift_master_console_port=443
```
