### ISSUE TITLE
Docker-storage-setup issue on GCE

### ISSUE THREAD

**Issue by ezlee** [openshift/openshift-ansible#1093]
I built a cluster on GCE successfully, but the problem is that the nodes created are not configured with LVM, so when a new disk is attached and docker daemon is restarted, don't know why docker-storage-setup service will by default look for /dev/sda instaed of /dev/sdb which I designated for the docker storage. 

  Volume group "sda1" not found
  Cannot process volume group sda1

my /etc/sysconfig/docker-storage-setup file:
DEVS=/dev/sdb
VG=docker-vg

So docker-storage-setup.service is not able to start, docker.service is not able to start, and all origin-node.service are not able to start, and all master, node and infra are in a "NotReady" status.

Anyone has any solution?

**Comment by lypht** [comment]
GCE will always throw the "sda1" error for the boot disk, but should configure your persistent disk regardless if attached and unformatted.  The disk should not be mounted.  However, if you do not see output similar to 

**Checking that no-one is using this disk right now ...
OK
...
/dev/sdb...
...
Converted docker-vg/docker-pool to thin pool.
  Logical volume "docker-pool" changed.**

after running docker-storage-setup from the node itself, the GCE persistent disk has not successfully formatted.  

Thread #842 may help.  To validate, in the GCE developer console, the disk should show as in use by the node where you intend to run docker-storage-setup.  /dev/sdb should also appear as a block device with 660 permissions from the command line (again, on the node itself).

**Comment by detiber** [comment]
It should be noted that the docker-storage-setup service "fails" for subsequent runs after the initial run as well.

More importantly, how did you stand up the GCE cluster and then add the additional volume? If you are adding the volume after the initial install and if the original docker install used a driver other than the lvm-direct driver, then you will most likely also need to delete the contents of /var/lib/docker/ to change the storage driver.

**Comment by ezlee** [comment]
I think by default, gce cluster will use root disk (the boot one) as the docker storage. If the docker-storage-setup service is no longer a dependency for docker service, docker service can start without any issue. It seems that it can never use a new block device and create any vg and use as new docker storage with this gce ansible build. Byo on gce, maybe, or create customize boot image with root in a vg. 
Thanks you all!

**Comment by detiber** [comment]
@ezlee ah, I think I'm following a bit more now. The block device being attached should be unpartitioned, if the disk that GCE is presenting is pre-partitioned the docker-storage-setup script will fail to create the docker volume.

That said, the gce playbooks would need to be updated for the proper volume config (adding the additional volume) and any bootstrapping that would be needed for ensuring the volume is unpartitioned and unmounted (I've not done this on GCE, but we do it with the aws playbooks by specifying the additional volumes on launch and using cloud_init for ensuring the additional volumes are not mounted and unpartitioned).

**Comment by detiber** [comment]
@ezlee are you still having issues with this?

**Comment by moander** [comment]
I'm having the same issue on Centos 7.

/dev/sda has one single partition (non-lvm) like in GCE

/dev/sdb is  unpartitioned

Same docker-storage-setup file as @ezlee

**Comment by lypht** [comment]
What does `sudo lsblk -f` show? (*It must be run from within the /dev directory*)  

If /dev/sdb is present, docker-storage-setup ought to work with @ezlee 's values.  If any additional sdb partitions appear (sdb1,sdb2,sdb*n*) setup will fail.  

Here's an output of the list-block query from a node that has /var/lib/docker mounted to sdb and EXT4-formatted in a GCE_PD, and the docker storage volumes written to sdc (attached, but not formatted or mounted prior to docker-storage-setup).

**NAME                                                                                         FSTYPE      LABEL UUID                                   MOUNTPOINT
sda                                                                                                                                                   
└─sda1                                                                                       xfs               1cce92dd-3a98-4755-b095-939a2dddb74a   /
sdb                                                                                          ext4              7f3797bb-aafa-4bce-8ff3-0b1a27f7e5e3   /var/lib/docker
sdc                                                                                                                                                   
└─sdc1                                                                                       LVM2_member       FeFdWV-xDfa-Pda9-uH2w-qYtd-Dfux-Kq0ak0 
  ├─docker--vg-docker--pool_tmeta                                                                                                                     
  │ └─docker--vg-docker--pool                                                                                                                         
  │   ├─docker-8:16-1441793-b103e8512671d653d71f515597e1d3c63f98b67ce8b6ff6808b1a7a56625ced6 xfs               66bd5384-2e88-47ea-af5e-84e0d7efd10b   
  │   ├─docker-8:16-1441793-f81ae35496e82540c0430ef8b7bb68f871f9054ab865c5f699ab89e52c3048e8 xfs               66bd5384-2e88-47ea-af5e-84e0d7efd10b   
...**

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
