### ISSUE TITLE
Deploy V4.0

### ISSUE THREAD

**Issue by kempy007** [openshift/openshift-ansible#10938]
When can we deploy V4.0 using containerized method from docker.io/openshift/origin-ansible ? 

I see v4.0 tags are showing in related containers but not openshift/origin (is this a release control decision as to why that card is being held back?)

**Comment by vrutkovs** [comment]
Please don't use bugtracker as a support forum.

Documentation about v4.0 deployment is in progress, README would be updated once its ready
