### ISSUE TITLE
[OKD 3.11] LDAP: No option to not specify CA certificate

### ISSUE THREAD

**Issue by Kardi5** [openshift/openshift-ansible#10933]
#### Description
> The installation of OpenShift 3.11 with Ansible Playbooks fails with the error: "Control plane pods didn't come up". Most likely because the LDAP CA file is missing.

##### Version
* Ansible version per `ansible --version`
* Output of `git describe`

```
# ansible --version
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

# git describe
openshift-ansible-3.11.58-1-4-gc24ee0134
```

##### Steps To Reproduce
1. Use any working Ansible Inventory for OpenShift (single master)
2. Add 
```
openshift_master_identity_providers=[{'name': 'somecorp_ldap_provider', 'challenge': 'true', 'login': 'true', 'kind': 'LDAPPasswordIdentityProvider', 'attributes': {'id': ['uid'], 'email': ['mail'], 'name': ['cn'], 'preferredUsername': ['uid']}, 'bindDN': '', 'bindPassword': '', 'insecure': 'false', 'url': 'ldap://ldap.example.de:389/ou=users,dc=somecorp,dc=de?uid'}]
openshift_master_ldap_ca=''
```
as the only identity provider in the [OSEv3:vars] section.
3. Install OpenShift using the playbooks

##### Expected Results
Successfull installation of OpenShift.

##### Observed Results
Installation exits after multiple retries to connect to the pod and error "Control plane pods didn't come up" appears.

There is an exited container on the master. Check the logs of the exited docker container.
```
# docker ps -a
> find exited container 
# docker logs exited_container_id
```
Last message will be something like:
```
error:  master-config.yml > /etc/origin/master/somecorp_ldap_ca.crt: File not found
```
(Sorry don't have access to the specific logfile anymore...)

##### Possible explanation
The LDAP server uses a certificate from DigiCert (so it is trusted by system roots). So I shouldn't have to specify an CA to be able to verify the certificate from the LDAP server.

I found the following information in [the docs](https://docs.okd.io/3.11/install_config/configuring_authentication.html#LDAPPasswordIdentityProvider) (scroll down to the example).
At point 11 it says:
> Certificate bundle to use to validate server certificates for the configured URL. If empty, system trusted roots are used. Only applies if insecure: false.

Exactly what I needed. So I hoped this was also possible for the Ansible installation. Looking into the [example inventory](https://github.com/openshift/openshift-ansible/blob/release-3.11/inventory/hosts.example#L212) there was an option (openshift_master_ldap_ca or openshift_master_ldap_ca_file, tried both) for setting the certificate to an empty value. Both options did not work as I hoped. Also omitting the values (openshift_master_ldap_ca and openshift_master_ldap_ca_file) did not work. 

Digging deeper I found the reason for the behaviour. It seems to be the [custom Ansible filter here](https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/lib_utils/filter_plugins/openshift_master.py#L161):
```
 if not self._idp['insecure']:
    self._idp['ca'] = '/etc/origin/master/{}_ldap_ca.crt'.format(self.name)
```
This also indicates that the certifcate name depends on the identity provider name and not on the "ca" field (as indicated in the example inventory). 

**Workaround**

For now I simply specify an example certificate as workaround for the "File not found" error and manually remove the certificate (i.e. set the "ca" field to '' in the identity provider section) in the master-config.yml (in /etc/origin/master) after the installation. Everything works fine after a restart.

It would be nice if there was a option to not specify a CA certificate for LDAP and rely on the system trusted roots.

##### Additional Information
```
All hosts are on CentOS 7.5
Ansible host is on Ubuntu 18.04.1 LTS
```

**Comment by vrutkovs** [comment]
>>Certificate bundle to use to validate server certificates for the configured URL. If empty, system trusted roots are used. Only applies if insecure: false.

>Exactly what I needed.

This would be correct only when `insecure: true` is set in identity provider setup. In this case though the LDAP server certificate would not be validated at all.

>This also indicates that the certifcate name depends on the identity provider name and not on the "ca" field (as indicated in the example inventory).

Correct, several identity providers can be specified, each of those can have various CA fields, controlled by _file variables and not `ca` field. This is implemented to protect the user from specifying CA paths, which don't get mounted in the API container.

>It would be nice if there was a option to not specify a CA certificate for LDAP and rely on the system trusted roots.

API server runs in the RHEL (in OCP) or Centos (for Origin) container, it doesn't share the trusted root with the host. Relying on potentially outdated system root in container is dangerous and may lead to a lot of errors.

The simplest solution would be symlinking CA store to `/etc/origin/master/somecorp_ldap_provider_ldap_ca.crt` on the host and re-running playbooks

**Comment by Kardi5** [comment]
Thank you for your reply.

> Relying on potentially outdated system root in container is dangerous and may lead to a lot of errors.

So that's what's happening when I edit the master-config.yml by hand and set the CA field to an empty string? And if that's the case maybe the documentation should be changed to reflect that.

Also
> it doesn't share the trusted root with the host

in this case 
> symlinking CA store to /etc/origin/master/somecorp_ldap_provider_ldap_ca.crt on the host and re-running playbooks

seems to be a good solution to this problem. Maybe this could be also added to the docs.

**Comment by maverick85** [comment]
Hi there,

I came across this issue as well.

> > > Certificate bundle to use to validate server certificates for the configured URL. If empty, system trusted roots are used. Only applies if insecure: false.
> 
> > Exactly what I needed.
> 
> This would be correct only when `insecure: true` is set in identity provider setup. In this case though the LDAP server certificate would not be validated at all.
Right here.

> > This also indicates that the certifcate name depends on the identity provider name and not on the "ca" field (as indicated in the example inventory).
> 
> Correct, several identity providers can be specified, each of those can have various CA fields, controlled by _file variables and not `ca` field. This is implemented to protect the user from specifying CA paths, which don't get mounted in the API container.
> 
As I get it, the certificates are located inside `/etc/origin/master/`

> > It would be nice if there was a option to not specify a CA certificate for LDAP and rely on the system trusted roots.
> 
> API server runs in the RHEL (in OCP) or Centos (for Origin) container, it doesn't share the trusted root with the host. Relying on potentially outdated system root in container is dangerous and may lead to a lot of errors.
> 
> The simplest solution would be symlinking CA store to `/etc/origin/master/somecorp_ldap_provider_ldap_ca.crt` on the host and re-running playbooks

I feel like you're missing the point here:

I am using a valid certificate I am not expecting to even be required to fill this variable. It is a valid, public trusted certificate.
By leaving it empty if should use the trusted root (wherever from).... or fail, unless `insecure=true`.

As mentioned earlier, editing master-config.yaml and setting `ca: ` (to empty) then restarting is a "quick fix" and I can't imagine how many people are simply going with `insecure: true` just because otherwise the install would fail. It's a quick fix right there in the inventory you know the certificate is valid... just because there's a workaround doesn't mean its ok.

Right now what I'm doing is manually creating a symbolic link at `/etc/origin/master` with the name `providername_ldap_ca.crt` and pointing to `ca-bundle.crt`. I connect to the server via ssh and once `master-config.yaml` is created I do the symlink, so it runs smoothly.
