### ISSUE TITLE
openshift_facts : Ensure PyYaml is installed

### ISSUE THREAD

**Issue by ddwla4** [openshift/openshift-ansible#10957]
TASK [openshift_facts : Ensure PyYaml is installed] ***************************************************************************************************************************************
fatal: [node01.hh.com]: FAILED! => {"changed": false, "msg": "No package matching 'PyYAML' is available"}
fatal: [master.hh.com]: FAILED! => {"changed": false, "msg": "No package matching 'PyYAML' is available"}
fatal: [node02.hh.com]: FAILED! => {"changed": false, "msg": "No package matching 'PyYAML' is available"}

I install openshift-ansible3.3.26 failed.
OS:ubuntu

please help me,thanks

**Comment by fenggolang** [comment]
only centos?
