### ISSUE TITLE
Installation fails: TASK [openshift_cluster_monitoring_operator : Wait for the ServiceMonitor CRD to be created] 

### ISSUE THREAD

**Issue by ChristianGubo** [openshift/openshift-ansible#10969]
#### Description

We try to install OpenShift for the first time and now stuck on the problem that we cant resolve the issue here

TASK [openshift_cluster_monitoring_operator : Wait for the ServiceMonitor CRD to be created] 

In the attached File is the error with the log of the pod.

Thanks for your help!

[Fehler SND.txt](https://github.com/openshift/openshift-ansible/files/2737275/Fehler.SND.txt)

**Comment by liuyatao** [comment]
I also meet this problem.

**Comment by vrutkovs** [comment]
prometheus operator may hang due to a lot of reasons, please check pod status in `openshift-monitoring-operator` namespace

If its still running, #11395 would allow the admin to customize the timeout
