### ISSUE TITLE
Cannot specify openshift version to deploy

### ISSUE THREAD

**Issue by entirosadmin** [openshift/openshift-ansible#10966]
#### Description

> When I run the command: ansible-playbook -i inventory/hosts playbooks/deploy_cluster.yml and has specified V3.11 as the openshift version to install I get errors saying that 3.11 does not exists

##### Version

```
ansible 2.7.2
openshift-ansible-4.0.0-0.128.0
```

##### Steps To Reproduce
1. ansible-playbook -i inventory/hosts playbooks/deploy_cluster.yml

##### Expected Results
This should install 3 masters, 4 nodes and 2 infra instances

```
CHECK [memory_availability : 000int-prd-osmaster2.private.entiros.io] *******************************************************************************************************************************************************************************
fatal: [000int-prd-osmaster2.private.entiros.io]: FAILED! => {"changed": false, "checks": {"disk_availability": {}, "docker_image_availability": {"skipped": true, "skipped_reason": "Not active for this host"}, "docker_storage": {"skipped": true, "skipped_reason": "Not active for this host"}, "memory_availability": {"skipped": true, "skipped_reason": "Disabled by user request"}, "package_availability": {"changed": false, "invocation": {"module_args": {"packages": ["bash-completion", "httpd-tools", "origin", "origin-clients", "origin-hyperkube"]}}}, "package_version": {"failed": true, "failures": [["OpenShiftCheckException", "Not all of the required packages are available at their requested version\norigin:3.11.0 \norigin-node:3.11.0 \norigin-master:3.11.0 \nPlease check your subscriptions and enabled repositories."]], "invocation": {"module_args": {"package_list": [{"check_multi": false, "name": "origin", "version": "3.11.0"}, {"check_multi": false, "name": "origin-master", "version": "3.11.0"}, {"check_multi": false, "name": "origin-node", "version": "3.11.0"}], "package_mgr": "yum"}}, "last_failed": {"failed": true, "invocation": {"module_args": {"package_list": [{"check_multi": false, "name": "origin", "version": "3.11.0"}, {"check_multi": false, "name": "origin-master", "version": "3.11.0"}, {"check_multi": false, "name": "origin-node", "version": "3.11.0"}], "package_mgr": "yum"}}, "msg": "Not all of the required packages are available at their requested version\norigin:3.11.0 \norigin-node:3.11.0 \norigin-master:3.11.0 \nPlease check your subscriptions and enabled repositories."}, "msg": "Not all of the required packages are available at their requested version\norigin:3.11.0 \norigin-node:3.11.0 \norigin-master:3.11.0 \nPlease check your subscriptions and enabled repositories."}}, "msg": "One or more checks failed", "playbook_context": "install"}

```

##### Observed Results
The deploy fails as version 3.11 is not found.
If I do not specify any specific version it also fails when trying to install origin-node-4.0

```
Failure summary:

  1. Hosts:    000int-prd-osmaster1.xxx, 000int-prd-osmaster2.xxx, 000int-prd-osmaster3.xxx, 000int-prd-osnode1.xxx, 000int-prd-osnode2.xxx, 000int-prd-osnode3.xxx, 000int-prd-osnode4.xxx
     Play:     OpenShift Health Checks
     Task:     Run health checks (install) - EL
     Message:  One or more checks failed
     Details:  check "package_version":
               Not all of the required packages are available at their requested version
               origin:3.11.0 
               origin-node:3.11.0 
               origin-master:3.11.0 
               Please check your subscriptions and enabled repositories.
```

##### Additional Information

If i do not specify any specific version the masters passes the tests but not the nodes which fails on the error: "No package matching 'origin-node-4.0*' found available, installed or updated"

* Master, nodes and infra: Red Hat Enterprise Linux Server release 7.6 (Maipo)
* Deploying server is running: CentOS Linux release 7.5.1804 (Core)

**Comment by frippe75** [comment]
@entirosadmin I think I ran into something similar. 
I had to add this to inventory/group_vars/OSEv3.yml

openshift_additional_repos=[{'id':` 'centos-okd-ci', 'name': 'centos-okd-ci', 'baseurl' :'http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin311/', 'gpgcheck' :'0', 'enabled' :'1'}]

But you need to change from centos to redhat repo's maybe... Not sure

**Comment by Havilland** [comment]
@entirosadmin could you post your inventory file? This would help to troubleshoot the issue.

If you want to install 3.11 I would recommend that you check out the 3.11 branch.

**Comment by entirosadmin** [comment]
`[OSEv3:children]
masters
nodes
etcd

[masters]
000int-prd-osmaster1.private.xxx.io openshift_schedulable=true ec2_subnet_id=subnet-8d2a4ed6 openshift_node_group_name="node-config-master"
000int-prd-osmaster2.private.xxx.io openshift_schedulable=true ec2_subnet_id=subnet-1c294d47 openshift_node_group_name="node-config-master"

[etcd]
000int-prd-osinf1.private.xxx.io ec2_subnet_id=subnet-8d2a4ed6 openshift_node_group_name="node-config-infra"
000int-prd-osinf2.private.xxx.io ec2_subnet_id=subnet-1c294d47 openshift_node_group_name="node-config-infra"

[nodes]
000int-prd-osmaster1.private.xxx.io openshift_schedulable=true ec2_subnet_id=subnet-8d2a4ed6 openshift_node_group_name="node-config-master"
000int-prd-osmaster2.private.xxx.io openshift_schedulable=true ec2_subnet_id=subnet-1c294d47 openshift_node_group_name="node-config-master"
000int-prd-osinf1.private.xxx.io ec2_subnet_id=subnet-8d2a4ed6 openshift_node_group_name="node-config-infra"
000int-prd-osinf2.private.xxx.io ec2_subnet_id=subnet-1c294d47 openshift_node_group_name="node-config-infra"
000int-prd-osnode1.private.xxx.io openshift_schedulable=true ec2_subnet_id=subnet-1c294d47 openshift_node_group_name="node-config-compute"
000int-prd-osnode2.private.xxx.io openshift_schedulable=true ec2_subnet_id=subnet-1c294d47 openshift_node_group_name="node-config-compute"
000int-prd-osnode3.private.xxx.io openshift_schedulable=true ec2_subnet_id=subnet-1681d971 openshift_node_group_name="node-config-compute"

[OSEv3:vars]
debug_level=4
ansible_ssh_user=ec2-user
ansible_become=yes
enable_excluders=False
enable_docker_excluder=False
openshift_enable_service_catalog=False
ansible_service_broker_install=False
ec2_tag_customer=000INT
ec2_tag_service=OpenShift

containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

openshift_node_kubelet_args={'pods-per-core': ['10']}

deployment_type=origin
openshift_deployment_type=origin

openshift_release=v3.11

osm_use_cockpit=true

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

openshift_master_default_subdomain=apps.xxx.io
openshift_master_cluster_hostname=openshift.xxx.io
openshift_public_hostname=openshift.xxx.io
`
