### ISSUE TITLE
Install OKD 3.11 (origin-node-run.sh no such file)

### ISSUE THREAD

**Issue by Asgoret** [openshift/openshift-ansible#10998]
I catch strange error. I've tried to install OKD 3.11 and openshift origin-node failed to start with error
`container_linux.go:336: starting container process caused "exec: \"/usr/local/bin/origin-node-run.sh\": stat /usr/local/bin/origin-node-run.sh: no such file or directory"
: internal libpod error`

If i enter to this images i can't find this script in `/ust/local/bin/`.

Image with error and investigation:
![image](https://user-images.githubusercontent.com/30697011/51106292-65e1b900-17fc-11e9-9ca4-55db3afd4387.png)

**Comment by Asgoret** [comment]
@sdodson hi! Do you know somebody who can help me?)

**Comment by Asgoret** [comment]
And find command
![image](https://user-images.githubusercontent.com/30697011/51106774-d1785600-17fd-11e9-96cc-e431371677b8.png)

**Comment by vrutkovs** [comment]
This belongs to https://github.com/openshift/origin, as openshift-ansible doesn't control entrypoint of openshift/origin-node. A custom script is used to run SDN and OVS - see https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_sdn/files/sdn.yaml#L41
