### ISSUE TITLE
Sync pod should not restart Kubelet without configuration change if the sync pod crashes or is restarted

### ISSUE THREAD

**Issue by daskanu** [openshift/openshift-ansible#11007]
#### Description
If a sync pod crashes and restarts, it will trigger a Kubelet restart even without any changes to the configuration.

Sync pod fails (crashes) if it can't annotate node with oc since there is no error handling.

##### Version
ansible 2.6.5
openshift-ansible-3.11.44-1-18-g8ff9ff7

##### Steps To Reproduce
Just restart one of the sync pods in namespace openshift-node either by deleting the pod or killing the process.

##### Expected Results
Sync pod starts up and doesn't restart Kubelet since there were no changes done to the configuration.

##### Observed Results
Sync pod starts up and restarts Kubelet, because of configuration changes even if there aren't any.
oc -n openshift-node logs <sync-pod>
info: Configuration changed, restarting kubelet

Sync pod crashes if the annotation with oc fails. For example if there is a connection problem to the API server (DNS server fails resolving, etc.).

**Comment by vrutkovs** [comment]
>Sync pod crashes if the annotation with oc fails. For example if there is a connection problem to the API server (DNS server fails resolving, etc.).

That seems like expected action to do - if the node is faulty it should be restarted. If API connection problem doesn't get resolved by that it needs to be fixed for cluster to function

**Comment by daskanu** [comment]
Then tell me please, why all the other oc calls do have an error handling and just this one is lacking it?

Doesn't make sense to me.

**Comment by mtnbikenc** [comment]
Fixed in #11878
