### ISSUE TITLE
Failed install logging service

### ISSUE THREAD

**Issue by Asgoret** [openshift/openshift-ansible#11006]
Hi, i've tried to install OKD 3.11 with properties:
```
openshift_logging_install_logging=true
openshift_logging_es_ops_nodeselector={"node-role.kubernetes.io/infra":"true"}
openshift_logging_es_nodeselector={"node-role.kubernetes.io/infra":"true"}
```
And get:
```
RUNNING HANDLER [openshift_logging_elasticsearch : Rolling out new pod(s) for {{ _es_node }}] ***
fatal: [okd-master1]: FAILED! => {"changed": true, "cmd": ["oc", "--config=/etc/origin/master/admin.kubeconfig", "rollout", "latest", "logging-es-data-master-ci2yridn", "-n", "openshift-logging"], "delta": "0:00:00.187204", "end": "2019-01-15 12:06:56.759982", "msg": "non-zero return code", "rc": 1, "start": "2019-01-15 12:06:56.572778", "stderr": "error: #1 is already in progress (Running).", "stderr_lines": ["error: #1 is already in progress (Running)."], "stdout": "", "stdout_lines": []}
```

So installation is failed:
```
Failure summary:


  1. Hosts:    okd-master1
     Play:     OpenShift Aggregated Logging
     Task:     Rolling out new pod(s) for logging-es-data-master-ci2yridn
     Message:  non-zero return code
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Can somebody help me? @gnufied @brenton @rphillips @jfchevrette

**Comment by odbawler** [comment]
Just recently started getting the same issue after updating my version openshift-ansible, it also seems to try deploying an ops version of logging-kibana even with `openshift_logging_use_ops=false`

**Comment by vrutkovs** [comment]
openshift-ansible waits for logging pod to rollout. It seems to be failing healthchecks.

Please file a new ticket in https://github.com/openshift/origin-aggregated-logging and attach the logs from logging-es-data-master-ci2yridn there

**Comment by odbawler** [comment]
I don't think that should be closed, in my case openshift-ansible does the 
`Rolling out new pod(s) for {{ _es_node }}]` 
task twice. The 1st time it rolls out successfully, but then when it tries the 2nd time I get the 
`error: #1 is already in progress (Running).`
I would assume because the pod is already up and running. When I access OpenShift even after the failure, the elasticsearch pod is running. The 2nd rollout (that fails) is not needed.

I think this is new behaviour...

**Comment by Asgoret** [comment]
@vrutkovs why re-open this?

**Comment by odbawler** [comment]
@Asgoret I've got this working by rolling ansible version back to 2.6.10 from 2.7.5. If you are blocked i'd suggest trying that for now.
