### ISSUE TITLE
Don't remove temporary files at exit

### ISSUE THREAD

**Issue by metallica127** [openshift/openshift-ansible#11011]
#### Description

I'd like to save temporary files created during playbook run (this can be useful in terms of debugging and troubleshooting). Is there a possibility to do that?

##### Version
ansible 2.7.1
openshift-ansible-3.10.101-1

##### Additional Information
For example, I am running a `deploy_cluster.yml` playbook. And the following task failed:
```
TASK [openshift_hosted : Configure a passthrough route for docker-registry] ********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": {"cmd": "/usr/bin/oc replace -f /tmp/docker-registry-dULVEl --force -n default", "results": {}, "returncode": 1, "stderr": "error: timed out waiting for the condition\n", "stdout": "route.route.openshift.io \"docker-registry\" deleted\n"}, "state": "present"}
```

The temporary file `/tmp/docker-registry-dULVEl` is removed using `atexit` hook, probably [here](https://github.com/openshift/openshift-ansible/blob/6d7f8662d3fe8be6731986e85f3659fb34c8819e/roles/lib_openshift/library/oc_route.py#L1001)

**Comment by vrutkovs** [comment]
The install should succeed and temp files should be removed. Its okay to temporarily disable this hook (or whatever is needed) to keep temp files if these help to debug - and fix the issue.

The real issue here is why the route cannot be replaced - this would require fetching events, route object etc. manually anyway
