### ISSUE TITLE
OKD 3.11 fail install Istio (service mesh)

### ISSUE THREAD

**Issue by Asgoret** [openshift/openshift-ansible#11028]
#### Description

Provide a brief description of your issue here. For example:

On node all-in-one

##### Version

`ansible 2.7.5`

`git describe` -> `openshift-ansible-3.11.70-1`

##### Steps To Reproduce
1. Follow official [instruction](https://docs.openshift.com/container-platform/3.11/servicemesh-install/servicemesh-install.html#service-mesh-install_prerequisites)
2. On step `oc new-app -f ....` you catch error

##### Expected Results
Istio is installed

```
[root@okd-master1 istio-install]# oc new-app -f istio.yaml --param=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL=okd-master1.10.0.0.111.nip.io:8443
error: unable to load template file "istio.yaml": unable to decode "istio.yaml": no kind "Installation" is registered for version "istio.openshift.com/v1alpha1" in scheme "github.com/openshift/origin/pkg/oc/util/ocscheme/read_internal.go:14"
error: unable to locate any template files with name "istio.yaml"
```

##### Observed Results
Istio didn't install

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* OS: `Linux okd-master1 3.10.0-957.1.3.el7.x86_64 #1 SMP {DATE}  x86_64 x86_64 x86_64 GNU/Linux`

**Comment by vrutkovs** [comment]
Red Hat Service Mesh is not supported on OKD. Also, this is not an openshift-ansible issue.

See https://docs.openshift.com/container-platform/3.11/servicemesh-install/servicemesh-install.html#installing-operator
