### ISSUE TITLE
setting version on containerized installs

### ISSUE THREAD

**Issue by ibotty** [openshift/openshift-ansible#1102]
Right now, all docker-using units use `:latest` images.

A short-term fix is to use e.g. `{{ openshift.node.node_image }}{{ openshift_version | replace('-',':v', 1) }}` as image to run. That will work when setting, e.g. `openshift_pkg_version=-1.1`.

That leaves two problems I am aware of.

First, afaict, these are not always the images one wants. Atm the latest released openshift/node image is v1.1.0.1 (as is openshift/openvswitch), but openshift/origin is still at v1.1. One cannot control individual versions.

Second, the image running will depend on when people pull the image.

I see two ways in descending order of preference.
 * Determine latest tags (by querying the registry, kind of hairy) then set-fact the version to use in the systemd units,
 * Record the shasum of the pulled image and use in the systemd units.

**Comment by detiber** [comment]
@brenton didn't you have a PR recently that addressed part of this?

**Comment by sdodson** [comment]
> Atm the latest released openshift/node image is v1.1.0.1 (as is openshift/openvswitch), but openshift/origin is still at v1.1. One cannot control individual versions.

This shouldn't be the case or maybe I'm misunderstanding your point here. These all show v1.1, v1.1.0.1, v1.1.1, v1.1.2.
https://hub.docker.com/r/openshift/openvswitch/tags/
https://hub.docker.com/r/openshift/origin/tags/
https://hub.docker.com/r/openshift/node/tags/

I agree that we need to come up with a strategy for figuring out version availability and pinning for containerized installs.

**Comment by brenton** [comment]
@detiber, my PR is only to allow `openshift_pkg_version` to work with upgrades.

**Comment by ibotty** [comment]
That's fixed.
