### ISSUE TITLE
Cant access my apss when master is down

### ISSUE THREAD

**Issue by ZrytyADHD** [openshift/openshift-ansible#11035]
#### Description

Hi,
I have a question/issue about HA and failover of openshift
i got enviroment with:
3 Masters
3 etcd
2 nodes
1 lb
installed on centos 7.6
and I have a problem with app access. 
I need/want my enviroment available 24/7 but cant archvieve this.
When i power off my first master  for example, my app is not accessbile. I place example application PHP from catalog to test it and i failed.
i have created route for this app and also cant access console when one master is down too.
Can anyone explain me how to do that i read about some config such as keepalived and ipfailover. 

##### Version

Openshift origin 3.11

ansible 2.6.5

Cloned from official openshift repo

##### Steps To Reproduce
1.Install HA Cluster
2. Deploy example app and create route for it
3. Power off master 1
4. check if app is stil available

##### Expected Results
App can be still accesible by user

##### Observed Results
Can access my aplication

**Comment by nagonzalez** [comment]
OpenShift blog is a good place to read up on HA setups. Here's one such article:
https://blog.openshift.com/haproxy-highly-available-keepalived/

Your apps and routes to them are typically hosted on the `node` machines. Shutting down a master shouldn't impact app availability.

**Comment by ZrytyADHD** [comment]
> 
> 
> OpenShift blog is a good place to read up on HA setups. Here's one such article:
> https://blog.openshift.com/haproxy-highly-available-keepalived/
> 
> Your apps and routes to them are typically hosted on the `node` machines. Shutting down a master shouldn't impact app availability.

Thanks for help i point to guide. I resolve it at last i make 6 pods for one app php is example. Then i create route for my app  and expose it adding external ip adress 👍 in my case 10.0.0.111 and down master and what my app is still accesible and wqorking great.
