### ISSUE TITLE
nsx node config play should only run against OC nodes

### ISSUE THREAD

**Issue by Ashok2988** [openshift/openshift-ansible#11038]
nsx node config play should only run against oc node hostgroup. Currently it attempts to run against hosts in all hostgroups

**Comment by Ashok2988** [comment]
Pls assign this to yasensim

**Comment by Ashok2988** [comment]
@yasensim  FYI, opened an issue to track

**Comment by yasensim** [comment]
Thanks @Ashok2988 , I will send a pr fixing this later today.

**Comment by yasensim** [comment]
@sdodson , I thought #11039 will close this issue automatically but looks like I did something wrong :)
May I ask you to close it as I dont have such privileges?
Thanks,
Yasen

**Comment by vrutkovs** [comment]
Fixed in #11039
