### ISSUE TITLE
error: a port needed by OpenShift is not available

### ISSUE THREAD

**Issue by ZrytyADHD** [openshift/openshift-ansible#11036]
#### Description

After server restart cluster cant go up displaying error afster use:

sudo oc cluster up

error: a port needed by OpenShift is not available

##### Version

Openshift origin v 3.11
ansible 3.6.5
docker 1.13

* The output of `git describe`
log from cluster up lvl 3

`sudo oc cluster up --loglevel=3
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Checking type of volume mount ...
Determining server IP ...
I0120 15:52:08.060265   34451 up.go:1009] Cannot use the Docker host IP(): <nil>
I0120 15:52:08.709757   34451 up.go:415] Using "127.0.0.1" as primary server IP and "10.0.0.167,172.17.0.1" as additional IPs
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
I0120 15:52:09.016681   34451 helper.go:275] Used ports in container: map[int]struct {}{111:struct {}{}, 22:struct {}{}, 25:struct {}{}, 42332:struct {}{}, 10250:struct {}{}, 2379:struct {}{}, 2380:struct {}{}}
F0120 15:52:09.016738   34451 helpers.go:119] error: a port needed by OpenShift is not available`

VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. Restart server
2. use oc cluster up


##### Expected Results
cluster up success


##### Observed Results

error: a port needed by OpenShift is not available`

**Comment by vrutkovs** [comment]
`oc cluster up` issues should be filed in https://github.com/openshift/origin/
