### ISSUE TITLE
Added option for resource-quota-sync-period 

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#1106]
Hi,

if you want to use quotas, you have to set resource-quota-sync-period on kubernetesMasterConfig/controllerArguments (Documentation: https://docs.openshift.com/enterprise/3.1/dev_guide/quota.html#configuring_quota_sync_period).

It should be configurable via ansible.

**Comment by abutcher** [comment]
Hey @jkroepke this will be configurable via `osm_controller_args` once #1110 merges. I added some examples to the byo inventory files in the PR as well.
