### ISSUE TITLE
one of the openshift infra node's pod cannot reach the other pods on different infra nodes

### ISSUE THREAD

**Issue by mslovy** [openshift/openshift-ansible#11082]
#### Description

I deploy the cluster with the inventory below:

[OSEv3:children]
masters
nodes
etcd
lb

[OSEv3:vars]
################################################################################
# Ensure these variables are set for bootstrap
####################################################################
# openshift required configuration variables follow 
ansible_user=root
ansible_become=yes
openshift_deployment_type=origin
openshift_release="3.11"
openshift_version="3.11"
openshift_master_default_subdomain=apps.xxx.com
openshift_master_cluster_hostname=openshift.xxx.com
openshift_master_cluster_public_hostname=openshift.xxx.com
openshift_master_public_console_url=https://openshift.xxx.com:8443/console
openshift_master_public_api_url=https://openshift.xxx.com:8443
#openshift_master_metrics_public_url=
#openshift_master_logging_public_url=https://kibana.apps.xxx.com
openshift_master_api_port=8443
openshift_master_console_port=8443
openshift_clusterid=xxx
debug_level=2
openshift_disable_check=memory_availability,disk_availability,docker_image_availability
containerized=true

template_service_broker_install=True
ansible_service_broker_install=True
ansible_service_broker_remove=False
openshift_console_install=True

# openshift_deployment_type is required for installation
openshift_cloudprovider_kind=openstack
openshift_use_calico=True
openshift_use_openshift_sdn=False
os_sdn_network_plugin_name="cni"
osm_cluster_network_cidr=10.1.0.0/16

openshift_storageclass_default="true"
openshift_storageclass_name="standard"
openshift_storageclass_provisioner="cinder"
openshift_storageclass_parameters={"fstype": "xfs", "type": "sata"}

openshift_cloudprovider_openstack_auth_url="https://console.xxx.com:13000/v2.0"
openshift_cloudprovider_openstack_username="xxx"
openshift_cloudprovider_openstack_password="xxx"
openshift_cloudprovider_openstack_tenant_name="xxx"

# hosted registry swift
openshift_hosted_registry_storage_kind=object
openshift_hosted_registry_storage_provider=swift
openshift_hosted_registry_storage_swift_container="xxx"
openshift_hosted_registry_storage_swift_authurl="https://console.xxx.com:13000/v2.0"
openshift_hosted_registry_storage_swift_username="xxx"
openshift_hosted_registry_storage_swift_password="xxx"
openshift_hosted_registry_storage_swift_tenant="xxx"

# promethues
openshift_cluster_monitoring_operator_install=True
openshift_cluster_monitoring_operator_prometheus_storage_enabled=True
openshift_cluster_monitoring_operator_prometheus_storage_capacity=100Gi
openshift_cluster_monitoring_operator_alertmanager_storage_enabled=True
openshift_cluster_monitoring_operator_alertmanager_storage_capacity=10Gi

# openshift metrics
openshift_metrics_install_metrics=True
openshift_metrics_cassandra_storage_type=dynamic
openshift_metrics_storage_volume_size=50Gi
#
## ELK logging
openshift_logging_install_logging=True
openshift_logging_es_pvc_dynamic=true
openshift_logging_es_ops_memory_limit=4Gi
openshift_logging_es_pvc_size=200Gi
openshift_logging_es_nodeselector={"node-role.kubernetes.io/compute":"true","staging":"true"}
#
#openshift_management_install_management=true

################################################################################
# cluster specific settings maybe be placed here

[masters]
openshift-master-1

[etcd]
openshift-master-1

[lb]
#openshift-lb-1

[nodes]
openshift-compute-1 openshift_node_group_name='node-config-compute' openshift_schedulable=True
openshift-compute-2 openshift_node_group_name='node-config-compute' openshift_schedulable=True
openshift-master-1 openshift_node_group_name='node-config-master' openshift_schedulable=True
#openshift-master-2 openshift_node_group_name='node-config-master' openshift_schedulable=True
#openshift-master-3 openshift_node_group_name='node-config-master' openshift_schedulable=True
openshift-infra-1 openshift_node_group_name='node-config-infra' openshift_schedulable=True
openshift-infra-2 openshift_node_group_name='node-config-infra' openshift_schedulable=True

And the pod "prometheus-k8s" on openshift-infra-1 cannot reach the pod "alertmanager-main" on openshift-infra-2. Therefore, we always get the error from pod "prometheus-k8s". The error msg is ""

##### Version
the openshift version is v3.11

#### Troubleshooting
I try to do some basic troubleshooting on the nodes and find those:

On openshift-infra-1:
[root@openshift-infra-1 ~]# ip r | grep blackhole
blackhole 10.1.89.0/26 proto bird 
[root@openshift-infra-1 ~]# ip a | grep tun
7: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 10.1.89.0/32 brd 10.1.89.0 scope global tunl0

In openshift-infra-1 calico node container:
/ # cat /etc/calico/confd/config/bird_aggr.cfg 
# Generated by confd
# ------------- Static black hole addresses -------------

protocol static {

   route 10.1.89.0/26 blackhole;

}

# Aggregation of routes on this host; export the block, nothing beneath it.
function calico_aggr ()
{

  
      # Block 10.1.89.0/26 is confirmed
    
      if ( net = 10.1.89.0/26 ) then { accept; }
      if ( net ~ 10.1.89.0/26 ) then { reject; }
    
  

}

In etcd,
[root@openshift-master-1 ~]# etcdctl --cert=/etc/etcd/peer.crt --key=/etc/etcd/peer.key --cacert=/etc/etcd/ca.crt --endpoints=[https://192.168.1.12:2379] get /calico/resources/v3/projectcalico.org/nodes/o
penshift-infra-1
/calico/resources/v3/projectcalico.org/nodes/openshift-infra-1
{"kind":"Node","apiVersion":"projectcalico.org/v3","metadata":{"name":"openshift-infra-1","uid":"7cdfa494-fef5-11e8-95c0-fa163e056d1f","creationTimestamp":"2018-12-13T16:38:15Z"},"spec":{"bgp":{"ipv4Addre
ss":"192.168.1.17/24","ipv4IPIPTunnelAddr":"10.1.89.0"},"orchRefs":[{"nodeName":"openshift-infra-1","orchestrator":"k8s"}]}}

I suspend that ipv4IPIPTunnelAddr cannot set to "10.1.89.0" ? and it should be 10.1.89.[1-254]? Anyone can help to diagnose this problem. I do not find where to set ipv4IPIPTunnelAddr into etcd.

**Comment by kprabhak** [comment]
@mslovy 10.1.89.0 is a valid IP address for tunnel endpoint (keep in mind this is a cidr, so this is not a broadcast).

If you're pods are unable to reach pods on other nodes, it's possible that something else is causing the issue.
Can you provide the output of 'ip route show' on your source and destination nodes? Also, can you confirm that IP Protocol 4 (IPIP) is being allowed through intermediate firewalls or security groups/NACL's?
