### ISSUE TITLE
last_checked_var: openshift_master_manage_htpasswd;Found removed variables: openshift_hostname is replaced by Removed: See documentation;

### ISSUE THREAD

**Issue by ezeev** [openshift/openshift-ansible#11097]
#### Description

Provide a brief description of your issue here. For example:

I'm doing a clean install on AWS following the steps in the README. `make infrastructure` succeeds. `make openshift` fails with the following error:

```
Failure summary:


  1. Hosts:    ip-REDACTED.us-west-2.compute.internal
     Play:     Verify Requirements
     Task:     Run variable sanity checks
     Message:  last_checked_host: ip-REDACTEDus-west-2.compute.internal, last_checked_var: openshift_master_manage_htpasswd;Found removed variables: openshift_hostname is replaced by Removed: See documentation; 
make: *** [openshift] Error 2
```

##### Version

Please put the following version information in the code block
indicated below.

```
make infrastructure
make openshift
```

* Your ansible version per `ansible --version`

> ansible 2.7.6

If you're operating from a **git clone**:

* The output of `git describe`

> v3.10-6-g4f3dd43

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

**Comment by vrutkovs** [comment]
There is no Makefile in the repo - and README doesn't mention adding `openshift_hostname` to the hosts. Which repo are you using?

**Comment by ezeev** [comment]
I just realized that I created in this in the wrong repo - my apologies. I had multiple git windows going at once and pulled the trigger in the wrong one without noticing.
