### ISSUE TITLE
Redeploying certs fatal error with expired certs when it shouldn't

### ISSUE THREAD

**Issue by oybed** [openshift/openshift-ansible#11098]
#### Description
With OpenShift v3.11, the `openshift_certificate_expiry_fail_on_warn` is now defaulted to `True` and `openshift_certificate_expiry_warning_days` to 365. The docs state 30 to be the default and from reading the docs, it doesn't appear that it should be a fatal error.

The docs either needs to updated, or the default values should reverted back to 30 & false. The latter is preferred from my perspective.
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_certificate_expiry/defaults/main.yml

##### Version
OpenShift v3.11

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
> ansible --version
ansible 2.7.4
> git describe
openshift-ansible-3.11.51-1
```

##### Steps To Reproduce
1. Make sure to use certificates with less than 365 days expiration (e.g.: using Let's encrypt certs is a good example).
2. Follow the instructions in the docs for how to re-deploy *all* certificates
https://docs.openshift.com/container-platform/3.11/install_config/redeploying_certificates.html#redeploying-all-certificates-current-ca
3. Observe the playbook does a fatal failure due to a warning made to be fatal by default values

##### Expected Results

Playbook should not error out with certs that are valid for 90 days (my Let's Encrypt certs)

##### Observed Results

Playbook error out with fatal error due to low expiration time

##### Additional Information

You can make the playbook work by setting the `openshift_certificate_expiry_fail_on_warn` to False in your inventory.

**Comment by vrutkovs** [comment]
`openshift_certificate_expiry_warning_days` can be redefined when calling the playbook.

Please file an issue in https://github.com/openshift/openshift-docs to update defaults

**Comment by oybed** [comment]
@vrutkovs yes, as I mentioned in my `Additional Information` this can be worked around by defining the content in the inventory (or at runtime). However, was this an intended change to go from 30 to 365, and to make the warning a fatal error? I cannot really make that call to have the docs updated v.s. the defaults changed. I don't see any mention of this in the sample inventory hosts.example either, so this leads me to believe that maybe the defaults are wrong(?) 

@sdodson FYI

**Comment by vrutkovs** [comment]
>was this an intended change to go from 30 to 365, and to make the warning a fatal error?

yes. This playbook can be run in a CronJob so a warning won't be sufficient. Defaults are overly cautious specifically to have this warning issued early
