### ISSUE TITLE
I believe AMI ID needs changed

### ISSUE THREAD

**Issue by cooktheryan** [openshift/openshift-ansible#1111]
< TASK: fail msg="Could not find requested ami" >
 -----------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

failed: [localhost] => {"failed": true}
msg: Could not find requested ami

FATAL: all hosts have already failed -- aborting

***** I believe it should be 
     # centos-7, requires marketplace
"-    image: ami-96a818fe"
"+    image: ami-61bbf104"

**Comment by cooktheryan** [comment]
Created PR  Incorrect AMI id #1112

**Comment by detiber** [comment]
@twiest @brenton this can be closed now that https://github.com/openshift/openshift-ansible/issues/1112
