### ISSUE TITLE
oc_atomic_container.py ansible module is empty

### ISSUE THREAD

**Issue by jclaret** [openshift/openshift-ansible#11120]
#### Description

oc_atomic_container.py ansible module file in /usr/share/ansible/openshift-ansible/roles/lib_openshift/library is empty (file size is 0)

```
$ ls -l /usr/share/ansible/openshift-ansible/roles/lib_openshift/library/oc_atomic_container.py 
-rw-rwxr--. 1 root root 0 Jan 17 22:52 /usr/share/ansible/openshift-ansible/roles/lib_openshift/library/oc_atomic_container.py
```

##### Steps To Reproduce

```
$ git clone  https://github.com/openshift/openshift-ansible.git
$ cd openshift-ansible/
$ find . -name oc_atomic_container.py -exec ls -l {} \;
-rw-rw-r--. 1 jcl jcl 0 Feb  3 19:58 ./roles/lib_openshift/library/oc_atomic_container.py
```

or 

```
$ git clone https://github.com/redhat-cop/casl-ansible.git
$ cd casl-ansible
$ docker run -u `id -u` \
      -v $HOME/.ssh/id_rsa:/opt/app-root/src/.ssh/id_rsa:Z \
      -v $HOME/Documents/Customers/MINDCURV/aws:/tmp/src:Z \
      -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
      -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
      -e INVENTORY_DIR=/tmp/src/casl-ansible/inventory/sample.aws.killproc.net.d/inventory \
      -e PLAYBOOK_FILE=/tmp/src/casl-ansible/playbooks/openshift/end-to-end.yml \
      -e OPTS="--private-key=example.pem -u cloud-user -e aws_key_name=example" -t \
      quay.io/redhat-cop/casl-ansible
```

quay.io/redhat-cop/casl-ansible image is built from openshift/origin-ansible and this one includes the /usr/share/ansible/openshift-ansible/roles/lib_openshift/library directory with oc_atomic_container ansible module. Once the docker run, it runs the ansible-playbook to install Openshift and it shows the following error:

> TASK [openshift_node : Install or Update node system container] ***************************************************************************************************************************************************
> task path: /tmp/src/casl-ansible/galaxy/openshift-ansible/roles/openshift_node/tasks/node_system_container_install.yml:2
> Sunday 03 February 2019  17:15:02 +0000 (0:00:01.843)       0:10:10.234 ******* 
> Using module file /usr/share/ansible/openshift-ansible/roles/lib_openshift/library/oc_atomic_container.py
> fatal: [34.253.232.204]: FAILED! => {
>     **"msg": "module (oc_atomic_container) is missing interpreter line"**
> }
> Using module file /usr/share/ansible/openshift-ansible/roles/lib_openshift/library/oc_atomic_container.py

It expects to run the playbook node_system_container_install.yml, but the ansible module does not include shebang because the file is empty. Looking at other branches, it is there. but not in the master one.

```
---
- name: Install or Update node system container
  oc_atomic_container:
    name: "{{ openshift_service_type }}-node"
    image: "{{ system_osn_image }}"
    values:
    - "DNS_DOMAIN={{ openshift.common.dns_domain }}"
    - "DOCKER_SERVICE={{ openshift_docker_service_name }}.service"
    - 'ADDTL_MOUNTS={{ l_node_syscon_add_mounts2 }}'
    state: latest
```

**Comment by vrutkovs** [comment]
This is expected - atomic containers are not used in 4.0, see https://github.com/openshift/openshift-ansible/pull/10277

Please use `release-3.11` branch to install Openshift instead of master branch
