### ISSUE TITLE
Thought - Openshift Releases

### ISSUE THREAD

**Issue by DarkBlaez** [openshift/openshift-ansible#11124]
I have a thought having encountered issues with openshift-ansible installs since release 3.7 over time. All of my installs have been on fresh VMs across Vultr, Digital Ocean, as well as bare metal using Fedora Server, Fedora Atomic, Centos 7.x

In reviewing the ever list of issues which are very similar and bouncing that against my own experience, can someone help me understand what the process is to insure a release works across these core platforms. Here is why I ask, spinning up VMs are fairly cheap, performing a from-scratch run of the ansible script using hosts.localhost as the inventory file. Surely doing so will flush out the issues that most will encounter especially since many are all-in-one.

Keep in mind I have encountered issues with all-in-one along with multiple nodes and various configurations. All have had their share of issues and most were in the ansible scripts or some dependency change.

As a developer myself I know we tend to kick a release and move on to the next enhancement or bug. If there is not a dedicated group of individuals performing these test installs from scratch then let me know and I will formulate a team and the resources to test. Again, my expectation has always been spin up a fresh VM, run the scripts and result should be some level of success. I can easily do this with a core kubernetes install but when it comes to openshift it's nothing short of a pain in the potato

thanks
DB

**Comment by vrutkovs** [comment]
>In reviewing the ever list of issues which are very similar and bouncing that against my own experience, can someone help me understand what the process is to insure a release works across these core platforms

Every pull request for 3.10+ branches is being tested by installing the cluster on AWS (w/ no cloudprovider option, similar to baremetal install), GCP (w/ cloudprovider) and major upgrade option. Each install then runs e2e test suite to verify the installed cluster is working correctly.

>Keep in mind I have encountered issues with all-in-one along with multiple nodes and various configurations

Please report each issue separately, include the inventory you've used and playbook log
