### ISSUE TITLE
Control plane pods didn't come up - Centos7 running on Openstack

### ISSUE THREAD

**Issue by spsingh1982** [openshift/openshift-ansible#11123]
#### Description

Trying to setup Openshift All In One on Centos7 running on Openstack. 

FAILED - RETRYING: Wait for control plane pods to appear (5 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (4 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (3 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (2 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (1 retries left).
failed: [localhost] (item=api) => {"attempts": 60, "changed": false, "item": "api", "msg": {"cmd": "/usr/bin/oc get pod master-api-openshift-ver3.11-allinone -o json -n kube-system", "results": [{}], "returncode": 1, "stderr": "The connection to the server openshift-ver3.11-allinone:8443 was refused - did you specify the right host or port?\n", "stdout": ""}}
FAILED - RETRYING: Wait for control plane pods to appear (60 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (59 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (58 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (57 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (56 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (55 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (54 retries left).

##### Version

3.11

* Your ansible version per `ansible --version`
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

If you're operating from a **git clone**:
git clone https://github.com/openshift/openshift-ansible
git check release-3.11

* The output of `git describe`
openshift-ansible-3.11.78-1
If you're running from playbooks installed via RPM
ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml
ansible-playbook -i inventory/hosts.localhost playbooks/deploy_cluster.yml

* The output of `rpm -q openshift-ansible`
[root@openshift-ver3 playbooks]# rpm -q openshift-ansible
package openshift-ansible is not installed
Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml
ansible-playbook -i inventory/hosts.localhost playbooks/deploy_cluster.yml

##### Expected Results
Openshift should be deployed

```
Example command and output or error messages
```

##### Observed Results

INSTALLER STATUS *****************************************************************************************************************************************
Initialization              : Complete (0:00:13)
Health Check                : Complete (0:00:30)
Node Bootstrap Preparation  : Complete (0:01:16)
etcd Install                : Complete (0:00:19)
Master Install              : In Progress (0:18:59)
        This phase can be restarted by running: playbooks/openshift-master/config.yml
Tuesday 05 February 2019  00:54:00 +0000 (0:00:00.043)       0:21:18.096 ****** 
=============================================================================== 
openshift_control_plane : Wait for control plane pods to appear -------------------------------------------------------------------------------- 1059.37s
openshift_node : Check status of node image pre-pull --------------------------------------------------------------------------------------------- 30.56s
openshift_control_plane : Check status of control plane image pre-pull --------------------------------------------------------------------------- 30.31s
Run health checks (install) - EL ----------------------------------------------------------------------------------------------------------------- 30.08s
openshift_node : Install node, clients, and conntrack packages ------------------------------------------------------------------------------------ 4.31s
openshift_excluder : Install docker excluder - yum ------------------------------------------------------------------------------------------------ 4.09s
openshift_cli : Install clients ------------------------------------------------------------------------------------------------------------------- 3.50s
Run variable sanity checks ------------------------------------------------------------------------------------------------------------------------ 2.19s
openshift_node : Add iptables allow rules --------------------------------------------------------------------------------------------------------- 1.84s
openshift_node : Update journald setup ------------------------------------------------------------------------------------------------------------ 1.73s
tuned : Ensure files are populated from templates ------------------------------------------------------------------------------------------------- 1.31s
openshift_master_certificates : Check status of master certificates ------------------------------------------------------------------------------- 1.26s
openshift_control_plane : Pre-pull Origin image (docker) ------------------------------------------------------------------------------------------ 1.20s
etcd : Pre-pull etcd image ------------------------------------------------------------------------------------------------------------------------ 1.18s
Gather Cluster facts ------------------------------------------------------------------------------------------------------------------------------ 1.18s
openshift_node : Pre-pull node image -------------------------------------------------------------------------------------------------------------- 1.17s
openshift_control_plane : Create temp directory for static pods ----------------------------------------------------------------------------------- 1.16s
openshift_node : pre-pull pod image --------------------------------------------------------------------------------------------------------------- 1.15s
openshift_ca : Generate the aggregator api-client config ------------------------------------------------------------------------------------------ 1.15s
openshift_control_plane : Add iptables allow rules ------------------------------------------------------------------------------------------------ 1.05s

Failure summary:

  1. Hosts:    localhost
     Play:     Configure masters
     Task:     Report control plane errors
     Message:  Control plane pods didn't come up
[root@openshift-ver3 openshift-ansible]# 

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by sfarosu** [comment]
Hello, please make sure that in /etc/hosts your hostname (ex. master.example.com) is not set to 127.0.0.1.

**Comment by spsingh1982** [comment]
I removed the 127.0.0.1 from /etc/hosts and ran the deploy script again but no difference. 
Also added no_proxy in bashrc 
no_proxy=.internal.example.com,10.0.0.1,10.0.0.2,10.0.0.3,.cluster.local,.svc,localhost,127.0.0.1,172.30.0.1

Still not difference. Control pods not coming up. What logs or config can I share with you guys to help me troubleshoot this situation ?

**Comment by spsingh1982** [comment]
Using default **inventory/hosts.localhost** which is part of 3.11 and yes I did git checkout release-3.11

I will try to add proxy variables in /etc/sysconfig/docker and test again.

**Comment by spsingh1982** [comment]
Using docker runtime.

**Comment by sfarosu** [comment]
If you are running proxies just adding them in /etc/sysconfig/docker is not sufficient. You need a bunch of proxy variables in your inventory: https://docs.okd.io/3.11/install/configuring_inventory_file.html#advanced-install-configuring-global-proxy

**Comment by spsingh1982** [comment]
Adding in /etc/sysconfig/docker is definitely doing some tricks...Playbook moved ahead and running right  now...will keep u posted

**Comment by spsingh1982** [comment]
Seems like it is hung up on task 
openshift_service_catalog:wait for API Server rollout success

Is that normal? No failure no retries nothing, task is just hungup. Anyway to know progress?

**Comment by spsingh1982** [comment]
Still hung up, only 3 pods running right now --> docker registry, registry-console & router.

**Comment by sfarosu** [comment]
You don't really need openshift service catalog for a first install. The pods you see running are in the default namespace but the openshift control-plane is in kube-system namespace. So do a "oc get pods -o wide -n kube-system". If etcd/api/controllers pods are all running your cluster is up. Try to go minimal at first installation and add more stuff like metrics, monitoring, etc afterwards running specific playbooks.

**Comment by spsingh1982** [comment]
[root@openshift-ver3 ~]# oc get pods -o wide -n kube-system
NAME                                            READY     STATUS    RESTARTS   AGE       IP             NODE                         NOMINATED NODE
master-api-openshift-ver3.11-allinone           1/1       Running   3          21h       10.75.34.216   openshift-ver3.11-allinone   <none>
master-controllers-openshift-ver3.11-allinone   1/1       Running   3          21h       10.75.34.216   openshift-ver3.11-allinone   <none>
master-etcd-openshift-ver3.11-allinone          1/1       Running   3          21h       10.75.34.216   openshift-ver3.11-allinone   <none>
[root@openshift-ver3 ~]# 
[root@openshift-ver3 ~]# 
[root@openshift-ver3 ~]# oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-52qtn    1/1       Running   2          21h
registry-console-1-zqn8w   1/1       Running   2          21h
router-1-xlw8m             1/1       Running   3          21h
[root@openshift-ver3 ~]# 
[root@openshift-ver3 ~]# 
[root@openshift-ver3 ~]# oc get nodes
NAME                         STATUS    ROLES                  AGE       VERSION
openshift-ver3.11-allinone   Ready     compute,infra,master   21h       v1.11.0+d4cacc0
[root@openshift-ver3 ~]# 

When I attempt to open Openshift Web Console. I get the following error
Application is not available
The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

Also some comments from my side. 

1. When I ran the deploy again by adding proxy in /etc/sysconfig/docker, it was hung up on "openshift_service_catalog:wait for API Server rollout success"

2.  Then I took your suggestion, and also added proxy variables in inventory file and ran the prereq and deploy again, now it's failing on task
 Task:     Wait for /apis/servicecatalog.k8s.io/v1beta1 when registered

Trying to setup simply single all in one before I even attempt to HA version. I want to understand how to deploy all pieces. Is there any step by step which covers all this. If not, please provide some pointers how to resolve this.

**Comment by sfarosu** [comment]
So you have 2 choices installing the cluster after running prerequisites:
- run the deploy-cluster playbook (i think this is what you've used)
- run individual playbooks found in the docs:  https://docs.okd.io/3.11/install/running_install.html#running-the-installation-playbooks (Individual Component Playbook Run Order)

What you really need from all those playbooks to have a minimal cluster is : 
Health Check | ~/openshift-ansible/playbooks/openshift-checks/pre-install.yml
Node Bootstrap | ~/openshift-ansible/playbooks/openshift-node/bootstrap.yml
etcd Install | ~/openshift-ansible/playbooks/openshift-etcd/config.yml
Master Install | ~/openshift-ansible/playbooks/openshift-master/config.yml
Master Additional Install | ~/openshift-ansible/playbooks/openshift-master/additional_config.yml
Node Join | ~/openshift-ansible/playbooks/openshift-node/join.yml
Hosted Install | ~/openshift-ansible/playbooks/openshift-hosted/config.yml
Web Console Install | ~/openshift-ansible/playbooks/openshift-web-console/config.yml

After all these run with success you can then move to installing logging/metrics etc.

Now if you feel you need to reinstall from scratch run the uninstall playbook : ~/openshift-ansible/playbooks/adhoc/uninstall.yml
Just remember after running uninstall playbook you need to: 
- restore /etc/resolv.conf back to whatever you had before installing openshift.
- yum remove docker-* crio -y && yum clean all &&  rm -Rf /var/lib/dockershim/ /var/lib/docker /var/lib/containers /etc/sysconfig/docker* /etc/sysconfig/cri-o* /etc/docker /etc/crio /etc/origin /etc/cni
- reboot the machine
- try again reinstalling openshift

**Comment by spsingh1982** [comment]
Thanks for instructions. Let me try my hand on these, will post updates. Thanks mate.

**Comment by spsingh1982** [comment]
@sfarosu 

Now, I am trying to install on system where there is no proxy involved, to make my life simpler. My centos7 machine is directly connected to internet. Now prereq goes successfull like always. But after I run deploy script or indivisual bootstrap.yaml, network manager updates my /etc/resolv.conf to eth0 IP of the machine. This makes subsequent steps fails as setup is no longer able to get packages from internet. Before deploy or bootstrap, I had correct nameservers in resolv.conf and was able to get all packages from internet.

**Comment by spsingh1982** [comment]
nvm, it was resolved by adding DNS entries in interface configuration.

**Comment by spsingh1982** [comment]
@sfarosu 

Followed your individual playbooks method and all playbooks worked fine. But there is some issue with DNS resolution. 

```
[root@atlas-tools openshift-ansible]# oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-q9w4j    1/1       Running   0          5m
registry-console-1-m52v7   1/1       Running   0          5m
router-1-4bjzj             1/1       Running   0          5m
[root@atlas-tools openshift-ansible]# oc get pods -o wide -n kube-system
NAME                             READY     STATUS    RESTARTS   AGE       IP               NODE          NOMINATED NODE
master-api-atlas-tools           1/1       Running   0          8m        98.132.140.191   atlas-tools   <none>
master-controllers-atlas-tools   1/1       Running   0          8m        98.132.140.191   atlas-tools   <none>
master-etcd-atlas-tools          1/1       Running   0          8m        98.132.140.191   atlas-tools   <none>
[root@atlas-tools openshift-ansible]#
```
When I try to open web console on public https://ETH0IP:8443/ It gets redirected to https://atlas-tools:8443/console/

Why can't I reach via public IP and why this redirection happening ?

Note:, After install, /etc/resolv.conf is now pointing to ETH0IP.
