### ISSUE TITLE
Missing /etc/ansible/facts.d folder on OpenShift hosts

### ISSUE THREAD

**Issue by ekultails** [openshift/openshift-ansible#11147]
#### Description

OpenShift fails to install on virtual machine instances due to a missing folder on those instances.

##### Version

```
$ rpm -qa | grep openshift-ansible
openshift-ansible-playbooks-3.11.69-1.git.0.2ff281f.el7.noarch
openshift-ansible-3.11.69-1.git.0.2ff281f.el7.noarch
openshift-ansible-docs-3.11.69-1.git.0.2ff281f.el7.noarch
openshift-ansible-roles-3.11.69-1.git.0.2ff281f.el7.noarch
```
```
$ ansible --version
ansible 2.5.14
  config file = /home/stack/openshift/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/stack/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### Steps To Reproduce
1. Follow the official [Configuring for OpenStack](https://docs.openshift.com/container-platform/3.11/install_config/configuring_openstack.html) guide for OpenShift 3.11.
2. Provision the OpenShift hosts.
    a. `$ ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/openstack/openshift-cluster/provision.yml`

##### Expected Results

The OpenShift master, infrastructure, and app nodes should all be deployed.

##### Observed Results

OpenShift host facts cannot be saved to `/etc/ansible/facts.d/openshift` because those systems do not have the `/etc/ansible/` directory. This leads to the playbook failing.

Short error:

```
Could not create fact file: /etc/ansible/facts.d/openshift.fact, error: [Errno 13] Permission denied: '/etc/ansible'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

Full error: https://gist.github.com/ekultails/26debc2049e0443d26de10cb48f6443b

##### Additional Information

Operating system: RHEL 7.6
OpenStack: RHOSP 14 (Rocky)

I was able to fix the issue by first having Ansible create the directory and then set all of the `openshift_facts` tasks to have `become: true`. This worked for my deployment but there may be other places where the playbook files need to be updated.

```
$ sudo vim /usr/share/ansible/openshift-ansible/playbooks/init/cluster_facts.yml
---
- name: Initialize cluster facts
  # l_init_fact_hosts is passed in via play during control-plane-only
  # upgrades and scale-up plays; otherwise oo_all_hosts is used.
  hosts: "{{ l_init_fact_hosts | default('oo_all_hosts') }}"
  roles:
  - role: openshift_facts
  - role: lib_utils
  tasks:
  - name: get openshift_current_version
    # get_current_openshift_version is a custom module in lib_utils
    # this will set_fact openshift_current_version
    get_current_openshift_version:
      deployment_type: "{{ openshift_deployment_type }}"

  - name: Create facts directory
    file:
      path: /etc/ansible/facts.d
      state: directory
      owner: root
      group: root
      mode: 0755
    become: true
```

**Comment by lbrigman124** [comment]
I experienced the same problem when I was trying to install as a non-root user with OKD 3.11 on CentOS 7.5
I haven't found the commit but it is an upstream playbook that removed become.  Adding -b to the deploy_cluster playbook is a workaround but it wasn't required before.
I'm using openshift-ansible 3.11.37-1.git.0.3b8b341 on CentOS.

**Comment by vrutkovs** [comment]
Ansible would create that folder automatically, the user you're using need to have permissions to do that - use root, passwordless sudo with `ansible_become` or pass sudo password with `-K`
