### ISSUE TITLE
Task set_loopback_context.yml sets user to the wrong name.

### ISSUE THREAD

**Issue by rjhowe** [openshift/openshift-ansible#11158]
#### Description
openshift-master.kubeconfig  gets created with a user that has a name of "system:openshift-master/MASTER_HOSTNAME:API_PORT"

<https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_ca/tasks/main.yml#L196>

If ever the context gets changes we will recreate the context, but for usename we use the cluster_hostname (api_hostname). 

<https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_control_plane/tasks/set_loopback_context.yml#L22>

<https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_facts/library/openshift_facts.py#L397>

This results in a openshift-master.kubeconfig   that has a context referencing user  "system:openshift-master/CLUSTER_HOSTNAME:API_PORT" but the user in this kubeconfig is still  "system:openshift-master/MASTER_HOSTNAME:API_PORT", so we end up with a current context set to a user that is not present. 

Ill summit a PR later around this.

**Comment by mtnbikenc** [comment]
Fixed by #11169
