### ISSUE TITLE
Atomic master scaleup fails on firewalld

### ISSUE THREAD

**Issue by Hakulaku** [openshift/openshift-ansible#11174]
#### Description

When the playbooks/openshift-master/scaleup.yml is run with `os_firewall_use_firewalld=True` the upscaling fails with the error: `Firewalld is not supported on Atomic Host`. However, since RHEL atomic 7.5 Red Hat ships firewalld with Atomic. (https://bugzilla.redhat.com/show_bug.cgi?id=1403331). From this Atomic version i don't think the playbook should fail anymore.

##### Version
```
Ansible 2.6.5
```

##### Steps To Reproduce
1. Build cluster on Atomic with Firewalld as os-firewall
2. Change inventory file to add new master to the cluster by adding the inventory groups `[new_masters]` and `[new_nodes]`
3. Run the playbooks/openshift-master/scaleup.yml playbook

##### Expected Results
Scaleup should succeed with the combination of Atomic 7.5> and firewalld.

##### Observed Results
Scaleup fails with the error `Firewalld is not supported on Atomic Host`

##### Additional Information

* Red Hat Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1403331
* Github discussion regarding enabling Firewalld for AH: https://github.com/openshift/openshift-ansible/pull/6763

**Comment by vrutkovs** [comment]
Which version of the OKD are you using? What's the version of openshift-ansible?
