### ISSUE TITLE
3.11 installation fails -> {"msg": "Invalid settings supplied for environment: 'shell'"}

### ISSUE THREAD

**Issue by dusansusic** [openshift/openshift-ansible#11183]
#### Description

Provide a brief description of your issue here. For example:

>TASK [openshift_node : update the sysconfig to have necessary variables] *******
fatal: [master.dusan.internal]: FAILED! => {"msg": "Invalid settings supplied for environment: 'shell'"}
fatal: [node-0.dusan.internal]: FAILED! => {"msg": "Invalid settings supplied for environment: 'shell'"}
fatal: [node-1.dusan.internal]: FAILED! => {"msg": "Invalid settings supplied for environment: 'shell'"}
	to retry, use: --limit @/home/dusan/openshift-ansible/playbooks/deploy_cluster.retry

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0   
master.dusan.internal      : ok=113  changed=48   unreachable=0    failed=1   
node-0.dusan.internal      : ok=92   changed=48   unreachable=0    failed=1   
node-1.dusan.internal      : ok=92   changed=48   unreachable=0    failed=1   

INSTALLER STATUS ***************************************************************
Initialization              : Complete (0:00:22)
Health Check                : Complete (0:00:04)
Node Bootstrap Preparation  : In Progress (0:02:23)
	This phase can be restarted by running: playbooks/openshift-node/bootstrap.yml

Failure summary:

  1. Hosts:    master.dusan.internal, node-0.dusan.internal, node-1.dusan.internal
     Play:     node bootstrap config
     Task:     update the sysconfig to have necessary variables
     Message:  Invalid settings supplied for environment: 'shell'

##### Version
OKD 3.11
ansible 2.6.13
OS: RHEL 7.6

inventory file:
```

[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_user=dusan
ansible_become=yes
ansible_ssh_private_key_file=/home/dusan/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
openshift_deployment_type=origin
containerized=true
openshift_master_default_subdomain=openshift.dusan.io
openshift_disable_check=docker_storage,memory_availability,disk_availability,docker_image_availability
openshift_master_overwrite_named_certificates=true
openshift_hosted_router_selector='node-role.kubernetes.io/master=true'
openshift_registry_selector='node-role.kubernetes.io/master=true'
debug_level=2
openshift_release="3.11"
openshift_image_tag=v3.11.0
openshift_pkg_version=-3.11.0


openshift_master_cluster_hostname=ec2-xxxxxxxxxxxxxxxxx.us-west-1.compute.amazonaws.com
openshift_public_hostname=ec2-xxxxxxxxxxxxxxxxxxxxxx.us-west-1.compute.amazonaws.com

[masters]
master.dusan.internal

[etcd]
master.dusan.internal

[nodes]
master.dusan.internal	openshift_schedulable=True	openshift_node_group_name="node-config-master"
node-0.dusan.internal	openshift_schedulable=True	openshift_node_group_name="node-config-compute"
node-1.dusan.internal	openshift_schedulable=True	openshift_node_group_name="node-config-compute"
```

**Comment by vrutkovs** [comment]
Please attach a full output of the `ansible-playbook -vvv` run

**Comment by pczhangyu** [comment]
fatal: [master.example.com]: FAILED! => {"msg": "Invalid settings supplied for environment: 'shell'"}

**Comment by pczhangyu** [comment]
i have the save problom

**Comment by dusansusic** [comment]
@pczhangyu check ansible version, my problem was related to ansible installation. i installed it with pip but somehow it has different version after running prerequisites.yml file.

**Comment by pczhangyu** [comment]
> @pczhangyu check ansible version, my problem was related to ansible installation. i installed it with pip but somehow it has different version after running prerequisites.yml file.

ansible version >= 2.6.6 ?

**Comment by dusansusic** [comment]
I used `pyenv` to build/install python, then used pip and all packages for the user i am using to install openshift. it worked.

**Comment by pczhangyu** [comment]
> I used `pyenv` to build/install python, then used pip and all packages for the user i am using to install openshift. it worked.

thanks

**Comment by fctee** [comment]
centos6.8 default python version2.6.6  I also encountered this problem, and finally upgraded to python2.7 solve it
