### ISSUE TITLE
DNS Customization

### ISSUE THREAD

**Issue by feitnomore** [openshift/openshift-ansible#11189]
#### Description

I'm looking for a way to customize the DNS Domain Name on Openshift installation, to change it from cluster.local. I've seen there is a way to change it on Node Configuration file through dnsDomain parameter, but wanted to provision the environment already with the custom DNS .

##### Version

Openshift v3.9

##### Steps To Reproduce
Install Openshift.

##### Expected Results
Expected to find a paramenter on hosts file to set the custom domain.

**Comment by vrutkovs** [comment]
Origin doesn't support using other DNS names inside yet, see https://github.com/openshift/openshift-ansible/pull/8590#issuecomment-398125461
