### ISSUE TITLE
"No RBAC policy matched" during installation

### ISSUE THREAD

**Issue by ajax-sandell-peterman** [openshift/openshift-ansible#11181]
#### Description

Installation fails on step "Wait for control plane pods to appear" with the error 

```
failed: [master1.internal.domain.com] (item=etcd) => {"attempts": 60, "changed": false, "item": "etcd", "msg": {"cmd": "/usr/bin/oc get pod master-etcd-master1.internal.domain.com -o json -n kube-system", "results": [{}], "returncode": 1, "stderr": "Error from server (Forbidden): pods \"master-etcd-master1.internal.domain.com\" is forbidden: User \"system:anonymous\" cannot get pods in the namespace \"kube-system\": no RBAC policy matched\n", "stdout": ""}}
```

This error also appears for the other two master nodes as well at the same time. It would seem that the masters are failing to register due to not being authenticated when they attempt to do so.

##### Version

```
ansible 2.7.5
openshift-ansible-3.11.75-1-2-gca6f586
package openshift-ansible is not installed # N/A
```

##### Steps To Reproduce
1. Prep each host according to OKD latest documentation (NetworkManager, ssh key exchange, etc)
2. From Ansible machine:
```
yum install -y epel-release
yum install -y ansible
git clone https://github.com/openshift/openshift-ansible.git
cd openshift-ansible
vi inventory/hosts # Paste in the below inventory
git checkout release-3.11
ansible-playbook --flush-cache -i ./inventory/hosts ./playbooks/prerequisites.yml
ansible-playbook --flush-cache -i ./inventory/hosts ./playbooks/deploy_cluster.yml
```

##### Expected Results

The installation to complete successfully.

##### Observed Results

```
failed: [master1.internal.domain.com] (item=etcd) => {"attempts": 60, "changed": false, "item": "etcd", "msg": {"cmd": "/usr/bin/oc get pod master-etcd-master1.internal.domain.com -o json -n kube-system", "results": [{}], "returncode": 1, "stderr": "Error from server (Forbidden): pods \"master-etcd-master1.internal.domain.com\" is forbidden: User \"system:anonymous\" cannot get pods in the namespace \"kube-system\": no RBAC policy matched\n", "stdout": ""}}
```

A similar error is also reflected in the journald logs for origin-node on the masters:

``` Failed to list *v1.Node: nodes "master1.internal.domain.com" is forbidden: User "system:anonymous" cannot list nodes at the cluster scope: no RBAC policy matched```

##### Additional Information

Using CentOS Linux release 7.5.1804 (Core). Our custom certificate is issued to the master_cluster_hostname and has that hostname as its subject... we were previously using a multi-SAN certificate where this wasn't the case and got a host of x509 errors which have since disappeared. I've also tried using AllowAll instead of htpasswd as an authentication provider to no avail. I also double checked that [this PR](https://github.com/openshift/openshift-ansible/pull/9528) was merged into the openshift-ansible branch I was using since [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1614876) describes behavior similar to what I'm seeing. It is, so I don't think that's the issue.

If it matters we're using a cloud-native load balancer for the masters. I can use curl to hit it on 8443 and it returns a list of API endpoints.

We've also successfully deployed a single-node cluster from this same machine configuration using [Grant Shipley's script](https://github.com/gshipley/installcentos). I tried to see if there was anything in his inventory file that might hold the key to making this work but nothing jumped out at me.

Sanitized inventory file:
```
[OSEv3:children]
masters
nodes
etcd
#lb

[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=origin

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
openshift_master_htpasswd_users={'nunya': 'business'}

openshift_master_cluster_method=native
openshift_master_cluster_hostname=okd.internal.domain.com
openshift_master_cluster_public_hostname=okd.internal.domain.com
openshift_master_default_subdomain=apps.domain.com

openshift_master_overwrite_named_certificates=true
openshift_master_named_certificates=[{"certfile": "/root/okd.internal.domain.com.crt", "keyfile": "/root/okd.internal.domain.com.key", "names": ["okd.internal.domain.com"], "cafile": "/root/okd.internal.domain.com.ca-bundle.crt"}]

# host group for masters
[masters]
master1.internal.domain.com
master2.internal.domain.com
master3.internal.domain.com

# host group for etcd
[etcd]
master1.internal.domain.com
master2.internal.domain.com
master3.internal.domain.com

[nodes]
master1.internal.domain.com openshift_node_group_name='node-config-master'
master2.internal.domain.com openshift_node_group_name='node-config-master'
master3.internal.domain.com openshift_node_group_name='node-config-master'
node1.internal.domain.com openshift_node_group_name='node-config-compute'
infra-node1.internal.domain.com openshift_node_group_name='node-config-infra'
```

**Comment by vrutkovs** [comment]
Does it work without `_named_certificates` set?

**Comment by ajax-sandell-peterman** [comment]
@vrutkovs I will try and report back. Question though: our master load balancer is HTTP-aware and presenting our certificate to clients. Should we switch to an IP-based one so that it presents the self-signed certs issued during the installation process when we try this?

I'll also try using an older version of Ansible (2.6.9) and see if that helps. Thanks for the pointer!

**Comment by ajax-sandell-peterman** [comment]
@vrutkovs It got past that step when I commented out ```_named_certificates``` and switched to using an IP load balancer (so the certs presented by the nodes are used). What about our certificate was preventing the installation from proceeding? Do certain fields need to be present on it for the clients to auth successfully? Relevant cert details from OpenSSL are as follows:

```
Certificate:
    Data:
        Version: 3 (0x2)
    Signature Algorithm: sha256WithRSAEncryption
        Validity
            Not Before: Feb  5 00:00:00 2019 GMT
            Not After : Feb  5 23:59:59 2020 GMT
        Subject: OU=Domain Control Validated, OU=PositiveSSL, CN=okd.internal.domain.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
            X509v3 Subject Alternative Name:
                DNS:okd.internal.domain.com, DNS:www.okd.internal.domain.com
```

I'm now receiving an error on a later step but I'll run that to ground before I post an issue... it's likely a misconfiguration with our environment.

**Comment by vrutkovs** [comment]
See https://docs.okd.io/latest/install_config/certificate_customization.html#configuring-custom-certificates-master

**Comment by KEITA-Diego-Y** [comment]
I'm using AWS EC2 and ELB/ALB for setting up OKD3.11.
I hit the same issue, so if possible I'd try that solution above.
But, if commenting out "openshift_master_named_certificates", how can I specify the custom cert for masters when installation?
Without specifying the cert, I think I will again hit x509 issue.

---
#### Cluster nodes
I would like to setup 3 x master-infra, 2 x worker cluster on AWS.
Create 5 EC2s for nodes, 1 EC2 for Ansible host, two ALB (one is internal, one is internet-facing), and Route53 public and private hosted zone.

#### What I did
Previously I hit the x509 cert issue during "Wait for control plane pods to appear"  step, without creating custom certs (but ALB needs cert).   
 - First, `"Undable to connect to the server tcp [unknown pub ip, other then pub ip of nodes...]:443".`  
 - Then, I created ELB and create the public cert on AWS/ACM, so the error was turned out to be `stderr": "Unable to connect to the server: x509: certificate signed by unknown authority` 
 - Also, I tried http listener on ELB to master nodes, but it also failed
 - Then, I decided to try to create custom certs.


So I did
- Created custom CA cert and the cert signed by the CA using OpenSSL
- Uploaded the cert, prv key, and the ca to AWS/ALB

Then, x509 issue disappeared. But then hit the issue.



#### The part of my inventory.yml
Each certs and key is in the Ansible host.

```
openshift_master_ca_certificate={'certfile': '/path/to/the/cacrt', 'keyfile': '/path/to/the/prvkey'}

openshift_master_overwrite_named_certificates=true
openshift_master_named_certificates=[{"certfile": "/path/to/the/crt", "keyfile": "/path/to/the/prvkey", "cafile": "path/to/the/cacrt"}]
#openshift_master_named_certificates=[{"certfile": "/path/to/the/crt", "keyfile": "/path/to/the/prvkey", "names": ["master.mydomin.com"], "cafile": "/path/to/the/cacrt"}]

openshift_master_cluster_method=native
openshift_master_default_subdomain=apps.mydomin.com
openshift_master_cluster_public_hostname=master.mydomin.com
openshift_master_cluster_hostname=master.mydomin.com
```

Also, I set DNS records  
in public hosted zone of Route53.
 - CNAME master.mydomin.com ALB-pub
 - CNAME *.apps.mydomain.com ALB-pub

in private zone
 - CNAME master.mydomin.com ALB-prv
 - CNAME *.apps.mydomain.com ALB-prv

Any advice is appreciate.
Thanks.
