### ISSUE TITLE
[Networking] OpenVirtualSwitch don't work correctly 

### ISSUE THREAD

**Issue by 22RC** [openshift/openshift-ansible#11223]
#### Description

Hi,
I have two cluster nodes, one master and one slave, with respectively hostsubnet:
```
# oc get hostsubnet
NAME               HOST               HOST IP          SUBNET
docker-01.tainet   docker-01.tainet   172.16.130.101   10.128.0.0/23
docker-02.tainet   docker-02.tainet   172.16.130.102   10.129.0.0/23
```
When i want to access from one of the nodes, for example via telnet, on pods that are on other node i get following error:
```
[root@docker-02 ~]# telnet docker-registry.default.svc 5000
Trying 172.30.181.233...
telnet: connect to address 172.30.181.233: No route to host
```
The Internal IP address (10.128.0.51) of this pod live on docker-01 hostsubnet and result accessible only from this node. The routing table are the same on both node, that is,
```
# ip r
default via 172.16.128.10 dev eth0 proto static metric 100 
10.128.0.0/14 dev tun0 proto kernel scope link 
172.16.0.0/20 via 172.16.128.1 dev eth0 proto static metric 100 
172.16.32.0/20 via 172.16.128.1 dev eth0 proto static metric 100 
172.16.48.0/20 via 172.16.128.1 dev eth0 proto static metric 100 
172.16.80.0/20 via 172.16.128.1 dev eth0 proto static metric 100 
172.16.128.0/20 dev eth0 proto kernel scope link src 172.16.130.101 metric 100 
172.16.200.0/24 via 172.16.128.1 dev eth0 proto static metric 100 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.30.0.0/16 dev tun0 scope link 
```
I noticed that, if watching the arp table on both nodes, i saw that nodes have, respectively, configure entries for their hostsubnet, in particular for the entry of docker-registry i have the following entry:
```
[root@docker-01 ~]# arp -a |grep 10.128.0.51
? (10.128.0.51) at 0a:58:0a:80:00:33 [ether] on tun0

[root@docker-02 ~]# arp -a |grep 10.128.0.51
? (10.128.0.51) at <incomplete> on tun0
```
If i monitoring TCP traffic flow on tun0 (or vxlan_sys_4789) interface on docker-02 node and run telnet on dockeer-registry, i see the following output
```
[root@docker-02 ~]# tcpdump -vvv -i tun0 host 10.128.0.51
tcpdump: listening on tun0, link-type EN10MB (Ethernet), capture size 262144 bytes
09:49:11.021756 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 10.128.0.51 tell docker-02.tainet, length 28
09:49:12.023029 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 10.128.0.51 tell docker-02.tainet, length 28
```

##### Version
*Os: `CentOS Linux release 7.4.1708 (Core)`

* Ansible Version: `ansible 2.3.2.0`

* The output of git describe: `openshift-ansible-3.7.0-0.123.0-8-gd57f27b`

* Oc Version: 
```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://docker-01.tainet:8443
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce

I can't replicate this problem!!!

##### Expected Results

All pods are accessible on both nodes

##### Observed Results

Nodes can access only on their sub-networks respectively.

##### Additional Information
I had the same problem on new OKD installation v.3.11, and i haven't solved this problem with the official Troubleshooting Networking.

**Comment by vrutkovs** [comment]
See https://docs.openshift.com/container-platform/3.11/admin_guide/sdn_troubleshooting.html#debugging-node-to-node-networking

Not an installer/upgrade issue though

**Comment by 22RC** [comment]
Hi @vrutkovs, 
I've already tried to debug with official sdn_troubleshooting.
I did not notice anything strange unfortunately.
