### ISSUE TITLE
Install Openshift 3.11 Couldn't find csr for nodes

### ISSUE THREAD

**Issue by arenasmunera** [openshift/openshift-ansible#11248]
Hi,

I am trying to install Openshift 3.11 version over Openstack with 1 master, 1 infra and 2 nodes and I have found a problem with csr. Anyone know what could be the problem?

Failure summary:

  1. Hosts:    master-0.openshift.magnet.com
     Play:     Approve any pending CSR requests from inventory nodes
     Task:     Approve node certificates when bootstrapping
     Message:  Could not find csr for nodes: app-node-1.openshift.magnet.com, infra-node-0.openshift.magnet.com, app-node-0.openshift.magnet.com

Some aditional info:

[openshift@master-0 ~]$ systemctl status origin-node.service
● origin-node.service - OpenShift Node
   Loaded: loaded (/etc/systemd/system/origin-node.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-02-26 15:02:36 UTC; 1h 2min ago
     Docs: https://github.com/openshift/origin
 Main PID: 31198 (hyperkube)
   CGroup: /system.slice/origin-node.service
           └─31198 /usr/bin/hyperkube kubelet --v=2 --address=0.0.0.0 --allow-privileged=true --anonymous-auth=true --authentication-token-webhook=true --...

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

[openshift@master-0 ~]$ oc get csr
NAME                                                   AGE       REQUESTOR                                                 CONDITION
csr-58xlf                                              1h        system:node:master-0.openshift.magnet.com                 Approved,Issued
csr-724dg                                              1h        system:node:infra-node-0.openshift.magnet.com             Approved,Issued
csr-8nkvd                                              1h        system:admin                                              Approved,Issued
csr-fjnlf                                              1h        system:node:app-node-1.openshift.magnet.com               Approved,Issued
csr-kj827                                              1h        system:admin                                              Approved,Issued
csr-n4ptr                                              1h        system:node:master-0.openshift.magnet.com                 Approved,Issued
csr-qdxfn                                              1h        system:node:app-node-0.openshift.magnet.com               Approved,Issued
node-csr-U7J2EKaJMAVHbZ2ht1Rst2jubc-tSPKbshMGoyNt-40   1h        system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
node-csr-YUkLryni9XqlcEKmwov-_jTI2F_EtAl-stXZaIoT0pA   1h        system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
node-csr-m-pdOYbsyuKWe4s1vIWhR7ctu9LluPqrKJcQQlCwjwE   1h        system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued

[openshift@master-0 ~]$ oc get nodes
NAME                                STATUS    ROLES     AGE       VERSION
app-node-0.openshift.magnet.com     Ready     compute   1h        v1.11.0+d4cacc0
app-node-1.openshift.magnet.com     Ready     compute   1h        v1.11.0+d4cacc0
infra-node-0.openshift.magnet.com   Ready     infra     1h        v1.11.0+d4cacc0
master-0.openshift.magnet.com       Ready     master    1h        v1.11.0+d4cacc0

[openshift@master-0 ~]$ oc get pods
No resources found.

Thanks you very much for your help,

Carlos

**Comment by Voronenko** [comment]
Got the same issue during install with `containerized=no` mode.  Did you resolve issue since Feb?

**Comment by arenasmunera** [comment]
No, sorry! But I am really interesting yet
