### ISSUE TITLE
Adding GlusterFS on existing openshift 3.11 platform fails 

### ISSUE THREAD

**Issue by Ashishyh** [openshift/openshift-ansible#11255]
oc v3.11.82
kubernetes v1.11.0+d4cacc0
openshift-ansible-3.11.82-3.git.0.9718d0a.el7.noarch

##################################
Error
TASK [openshift_storage_glusterfs : Check for specified container versions] *******************************************************************************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_storage_glusterfs/tasks/version_check.yml:2
Wednesday 27 February 2019  12:15:38 +0530 (0:00:00.496)       0:04:59.907 **** 
fatal: [testlocal.cf.com]: FAILED! => {
    "changed": false, 
    "msg": "A valid version tag must be specified for all GlusterFS container images.\nValid image tags take the form of \"v3.x\" where \"x\" can be a one or two release\nversions (e.g. \"v3.0\" or \"v3.0.1\"). The following image versions were detected:\n\nGlusterFS: latest\nHeketi: latest\nglusterblock-provisioner: latest\n"
}

########################################################

Inventory file

openshift_hosted_registry_storage_kind=glusterfs 
openshift_hosted_registry_storage_volume_size=5Gi
openshift_hosted_registry_selector='node-role.kubernetes.io/infra=true'

     

openshift_storage_glusterfs_namespace=app-storage
openshift_storage_glusterfs_storageclass=true
openshift_storage_glusterfs_storageclass_default=false
openshift_storage_glusterfs_block_deploy=true
openshift_storage_glusterfs_block_host_vol_size=100
openshift_storage_glusterfs_block_storageclass=true
openshift_storage_glusterfs_block_storageclass_default=false

openshift_storage_glusterfs_registry_namespace=infra-storage
openshift_storage_glusterfs_registry_block_deploy=true
openshift_storage_glusterfs_registry_block_host_vol_size=100
openshift_storage_glusterfs_registry_block_storageclass=true
openshift_storage_glusterfs_registry_block_storageclass_default=false

**Comment by rbo** [comment]
Just-for-informations, I ran into the same problem today. This is a know-Issue at Red Hat work-a-round: https://access.redhat.com/solutions/3949971

Add the following variables to the inventory, and run the installation playbook again:
```
openshift_storage_glusterfs_image=registry.redhat.io/rhgs3/rhgs-server-rhel7:v3.11
openshift_storage_glusterfs_block_image=registry.redhat.io/rhgs3/rhgs-gluster-block-prov-rhel7:v3.11
openshift_storage_glusterfs_heketi_image=registry.redhat.io/rhgs3/rhgs-volmanager-rhel7:v3.11
```
