### ISSUE TITLE
variable get overwritten

### ISSUE THREAD

**Issue by mgm3232** [openshift/openshift-ansible#11252]
Hi,

Please check roles/openshift_logging/tasks/install_logging.yaml (?)

In inventory:

openshift_logging_use_ops: False
openshift_logging_es_pvc_storage_class_name: "glusterfs-storage-block"

What happens:

openshift-logging/logging-es-0,1,2 get deployed on glusterfs-storage

[root@bastion ~]# rpm -qa | grep openshift
openshift-ansible-3.11.69-1.git.0.2ff281f.el7.noarch
openshift-ansible-roles-3.11.69-1.git.0.2ff281f.el7.noarch
atomic-openshift-clients-3.11.69-1.git.0.7478b86.el7.x86_64
openshift-ansible-playbooks-3.11.69-1.git.0.2ff281f.el7.noarch
openshift-ansible-docs-3.11.69-1.git.0.2ff281f.el7.noarch
[root@bastion ~]#

**Comment by mgm3232** [comment]
[root@master ~]# oc get sc
NAME                          PROVISIONER                AGE
glusterfs-storage (default)   kubernetes.io/glusterfs    1h
glusterfs-storage-block       gluster.org/glusterblock   1h
[root@master ~]#

**Comment by faust64** [comment]
Hi,

Which version are you deploying?
Looking at 3.11.69, it sounds like you're using the wrong variable:

```
roles/openshift_logging_elasticsearch/tasks/main.yaml:      storage_class_name: "{{ openshift_logging_elasticsearch_pvc_storage_class_name | default('', true) }}"
roles/openshift_logging_elasticsearch/templates/pvc.j2:{% if storage_class_name is defined %}
roles/openshift_logging_elasticsearch/templates/pvc.j2:  storageClassName: {{ storage_class_name }}
```

In your case, I would go with: `openshift_logging_elasticsearch_pvc_storage_class_name: glusterfs-storage-block`

Let us know how that went.

Regards.
