### ISSUE TITLE
Dangerous Filter "lib_utils_oo_oreg_image"  in /roles/lib_utils/filter_plugins/oo_filters.py

### ISSUE THREAD

**Issue by disposab1e** [openshift/openshift-ansible#11259]
#### Description

Dangerous Filter "lib_utils_oo_oreg_image"  in /roles/lib_utils/filter_plugins/oo_filters.py results in image_default even if oreg_url is set in inventory. 

##### Version
```
ansible 2.6.13

Name       : openshift-ansible
Architektur : noarch
Version    : 3.11.82
Ausgabe    : 3.git.0.9718d0a.el7
```

##### Steps To Reproduce
1. Set oreg_url in inventory
oreg_url='satellite.example.com:5000/my-registry-openshift3_ose-${component}:${version}'
2. Run deploy_cluster.yaml Playbook

##### Expected Results

Etcs is downloaded from registry and installed.

##### Observed Results

Run 'docker image' on master
No etcd image downloaded from registry, instead tries to download etcd from registry.redhat.io.

##### Additional Information

```
Red Hat Enterprise Linux Server release 7.6 (Maipo)

Inventory:
oreg_url='satellite.example.com:5000/my-registry-openshift3_ose-${component}:${version}'
```

def lib_utils_oo_oreg_image(image_default, oreg_url) in file /roles/lib_utils/filter_plugins/oo_filters.py results in default_image what is a sub optimal behaviour.

When you explicitly set in your inventory:
osm_etcd_image=satellite.example.com:5000/my-registry-registry-rhel7_etcd:3.2.22

all is fine.

**Comment by vrutkovs** [comment]
Could you check the logs of the playbook and ansible facts? AFAIK at least `l_default_osm_etcd_image` in the latest 3.11 should contain oreg_url'ized version of etcd image, and unless `osm_etcd_image` or `etcd_image` is set it would be used

**Comment by disposab1e** [comment]
So sorry for that but I don't have the logs any more for this behaviour. But as along as osm_etcd_image was not set the etcd pods can't be installed because the installer tries to download the etcd image from registry.redhat.io.

The installer than stops when polling the console plane pods for exsitence.

**Comment by disposab1e** [comment]
I have no glue from python but I did some test...

```python

image_default = "registry.redhat.io/rhel7/etcd:3.2.22"

oreg_url = "satellite.example.com:5000/my-registry-openshift3_ose-${component}:${version}"

output = ""

if oreg_url == 'None':
    output = image_default
oreg_parts = oreg_url.rsplit('/', 2)

print(oreg_parts)

if len(oreg_parts) < 2:
    raise errors.AnsibleFilterError("oreg_url malformed: {}".format(oreg_url))
if not (len(oreg_parts) >= 3 and '.' in oreg_parts[0]):
    # oreg_url does not include host information; we'll just return etcd default

    output = image_default
    print(oreg_parts[0])
    print(output)
    exit()
image_parts = image_default.split('/')

print(image_parts)

if len(image_parts) < 3:
   output =  '/'.join([oreg_parts[0], image_parts[1], image_parts[2]])

print(oreg_parts[0])
print(output)

```

This outputs:

['satellite.example.com:5000', 'my-registry-openshift3_ose-${component}:${version}']
satellite.example.com:5000
registry.redhat.io/rhel7/etcd:3.2.22

For me the line with the bug for this kind of oreg_url is:

```python

if not (len(oreg_parts) >= 3 and '.' in oreg_parts[0]):

```

**Comment by vrutkovs** [comment]
It appears to be designed to work with `oreg_url=satellite.example.com:5000/openshift/ose3-${component}:${version}`, but won't work with `example.com/openshift-${component}:${version}`

@sdodson do we know if this is intended or a bug?

**Comment by disposab1e** [comment]
Yes absolutely as you can see I install with satellite and when you don't use ContentViews like me you have an oreg_url like me :-)

**Comment by sdodson** [comment]
So it fails if there's no namespace, that seems like a bug.

**Comment by disposab1e** [comment]
👍 +1 :-)
