### ISSUE TITLE
Issue while while modifying nodes in openshift cluster

### ISSUE THREAD

**Issue by mohit5577** [openshift/openshift-ansible#11264]
#### Description
On the existing openshift cluster we are trying to add the node. But when we run openshift update we are getting the error 
 "msg": "Could not find csr for nodes: oshnodeinfra-10-10-4-16"

##### Version
[centos@buildserver-10-10-0-132 ~]$ ansible --version
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

Place the output between the code block below:
<oshmaster-10-10-4-8.us-east1-b.c.saas-rnd-itc02.internal> Failed to connect to the host via ssh:
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_oc_csr_approve_payload_tsTp5a/__main__.py", line 24, in <module>
    from json.decoder import JSONDecodeError
fatal: [oshmaster-10-10-4-8.us-east1-b.c.saas-rnd-itc02.internal]: FAILED! => {
    "all_subjects_found": [
        "subject=/O=system:nodes/CN=system:node:oshnodeinfra-10-10-6-12\n",
        "subject=/O=system:nodes/CN=system:node:oshnodeinfra-10-10-6-12\n",
        "subject=/O=system:nodes/CN=system:node:oshnodeinfra-10-10-4-16\n",
        "subject=/O=system:nodes/CN=system:node:oshnodeinfra-10-10-4-16\n",
        "subject=/O=system:nodes/CN=system:node:oshnodeinfra-10-10-6-12\n",
        "subject=/O=system:nodes/CN=system:node:oshnodeinfra-10-10-6-12\n",
        "subject=/O=system:nodes/CN=system:node:oshnodeinfra-10-10-6-12\n",
        "subject=/O=system:nodes/CN=system:node:oshnodeinfra-10-10-4-16\n",
        "subject=/O=system:nodes/CN=system:node:oshnodeinfra-10-10-4-16\n",
        "subject=/O=system:nodes/CN=system:node:oshnodeinfra-10-10-6-12\n"
    ],
    "attempts": 30,
    "changed": false,
    "client_approve_results": [],
    "client_csrs": {},
    "invocation": {
        "module_args": {
            "node_list": [
                "oshnodeinfra-10-10-6-12",
                "oshnodeinfra-10-10-4-16"
            ],
            "oc_bin": "oc",
            "oc_conf": "/etc/origin/master/admin.kubeconfig"
        }
    },
    "msg": "Could not find csr for nodes: oshnodeinfra-10-10-4-16",
    "oc_get_nodes": {
        "apiVersion": "v1",
        "items": [
            {
                "apiVersion": "v1",
                "kind": "Node",
                "metadata": {
                    "annotations": {
                        "node.openshift.io/md5sum": "a37f634a0f8656d20a5f168a222d3d0d",
                        "volumes.kubernetes.io/controller-managed-attach-detach": "true"
                    },

Openshift Version 3.11

##### Steps To Reproduce
1. make openshift_update
The nodes are to be added in the cluster.

##### Observed Results
It is getting the csr error  "msg": "Could not find csr for nodes: oshnodeinfra-10-10-4-16",

##### OS version
Linux buildserver-10-10-0-132 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by faust64** [comment]
Sadly, this issue seems to pop up again and again ( openshift-ansible#11347, openshift-ansible#11365 ), lately.

Nevertheless, it looks like your Ansible version is 2.7, while 2.6 is recommended deploying 3.11. Could be unrelated. May not be a problem in your setup.
