### ISSUE TITLE
Error trying deploy GlusterFS to existing OKD 3.11

### ISSUE THREAD

**Issue by ZrytyADHD** [openshift/openshift-ansible#11279]
#### Description
When i try to install GlusterFS i got error when script try go to step  "copy heketi-storage list"

When i use ansible 2.7.8
`*
fatal: [svlnopsh01t]: FAILED! => {"changed": true, "cmd": "oc --config=/tmp/openshift-glusterfs-ansible-9qSRD8/admin.kubeconfig rsh --namespace=glusternowy deploy-heketi-storage-1-j25j9 cat /tmp/heketi-storage.json > /tmp/openshift-glusterfs-ansible-9qSRD8/heketi-storage.json", "delta": "0:00:00.221758", "end": "2019-03-02 19:37:43.567457", "msg": "non-zero return code", "rc": 1, "start": "2019-03-02 19:37:43.345699", "stderr": "command terminated with exit code 1", "stderr_lines": ["command terminated with exit code 1"], "stdout": "", "stdout_lines": []}
`

When i use ansible 2.6.5
`
fatal: [svlnopsh01t]: FAILED! => {"changed": true, "cmd": "oc --config=/tmp/openshift-glusterfs-ansible-4rdq9I/admin.kubeconfig rsh --namespace=glusternowy deploy-heketi-storage-1-c2p9g cat /tmp/heketi-storage.json > /tmp/openshift-glusterfs-ansible-4rdq9I/heketi-storage.json", "delta": "0:00:00.232928", "end": "2019-03-02 20:06:50.018285", "msg": "non-zero return code", "rc": 1, "start": "2019-03-02 20:06:49.785357", "stderr": "cat: /tmp/heketi-storage.json: No such file or directory\ncommand terminated with exit code 1", "stderr_lines": ["cat: /tmp/heketi-storage.json: No such file or directory", "command terminated with exit code 1"], "stdout": "", "stdout_lines": []}
`
I also check file which cant be find . File is in the folder /tmp on master but is empty.
##### Version
Centos 7.6
Docker 1.13.1
OKD 3.11
Ansible 2.6.5 try also on 2.7.8 without success

###### Inventory file
`openshift_storage_glusterfs_namespace=glusternowy
openshift_storage_glusterfs_name=storage
openshift_storage_glusterfs_storageclass=true
openshift_storage_glusterfs_storageclass_default=false
openshift_storage_glusterfs_block_deploy=true
openshift_storage_glusterfs_block_host_vol_size=100
openshift_storage_glusterfs_block_storageclass=true
openshift_storage_glusterfs_block_storageclass_default=false
`
\\
##### Steps To Reproduce
1. Install OKD 3.11
2. Configure inventory file
3. Run playbook `openshift-ansible/playbooks/openshift-glusterfs/config.yml`

##### Expected Results
GlusterFS storage succesfull instaled

##### Observed Results
Error on step "copy heketi-storage list"

**Comment by vrutkovs** [comment]
These gluster playbooks are part of openshift, so in order to install it you need to run prequisites and deploy_cluster playbooks
