### ISSUE TITLE
openshift_project_request_template role not being assigned

### ISSUE THREAD

**Issue by rtorti** [openshift/openshift-ansible#11275]
#### Description

Provide a brief description of your issue here. For example:

> adding osm_project_request_template='default/project-request' to [OSEv3:vars] in my inventory file and running the playbooks/openshift-master/config.yml results in the my master-config.yaml updating projectConfig projectRequestTemplate option correctly

> I have tried adding role variables for openshift_project_request_template in the same spot, but the role never gets applied to any of the nodes and the edits I'm trying inject with openshift_project_request_template_edits never happen.

>As a troubleshooting step: If I assigne this role to "hosts: oo_first_master" in playbooks/openshift-master/private/config.yml assignes the role and runs that tasks and injects the data I have in my role variable "openshift_project_request_template_edits=[]" in my inventory file

>is there another playbook to run which will apply this role?

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
ansible 2.6.5

If you're operating from a **git clone**:
Yes this is a git clone from
* The output of `git describe`
openshift-ansible-3.11.90-1-4-g73430e6

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. add following variables to your inventory file
osm_project_request_template='default/project-request'
openshift_project_request_template_manage=true
openshift_project_request_template_namespace=default
openshift_project_request_template_name=project-request
openshift_project_request_template_edits=[<data><data>]

2. ansible-playbook -vvv -i inventory/my-inventory.yaml playbooks/openshift-master/config.yml

##### Expected Results
Describe what you expected to happen.

Was expecting the role "openshift_project_request_template" to be applied and run on a master node.

##### Observed Results
Describe what is actually happening.

The role never gets assigned and the task to create the default project request template never happens.

**Comment by vrutkovs** [comment]
This role gets applied when `playbooks/openshift-master/additional_config.yml` is run - or during control plane setup in `deploy_cluster.yml`

**Comment by rtorti** [comment]
That was it.  Thank you.
