### ISSUE TITLE
Cannot access to cluster console

### ISSUE THREAD

**Issue by jota2016** [openshift/openshift-ansible#11306]
#### Description

After a new installation of 3.11, the Service Catalog and the Application console are accesible, but when try to access to Cluster console, it redirects to https://console.router.default.svc.cluster.local and it's not accesible.
From terminal I can see that cluster is not running, and when try to start it, gives a port in use error.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
ansible 2.6.14

* The output of `rpm -q openshift-ansible`
openshift-ansible-3.11.37-1.git.0.3b8b341.el7.noarch

##### Steps To Reproduce
1. oc cluster status
   Error: OpenShift cluster is not running
2. oc cluster up
   Getting a Docker client ...
   Checking if image openshift/origin-control-plane:v3.11 is available ...
   Checking type of volume mount ...
   Determining server IP ...
   Checking if OpenShift is already running ...
   Checking for supported Docker version (=>1.22) ...
   Checking if insecured registry is configured properly in Docker ...
   Checking if required ports are available ...
   error: a port needed by OpenShift is not available

##### Expected Results
Cluster console accesible

Provide any additional information which may help us diagnose the
issue.

OS: Red Hat 7.6
Docker version 1.13.1, build 07f3374/1.13.1

Inventory file:
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=origin
openshift_set_node_ip=true

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
openshift_master_htpasswd_users={'admin': 'encryptedpassword'}

[masters]
master.mydomain.com openshift_schedulable=true containerized=false

[etcd]
master.mydomain.com

[nodes]
master.mydomain.com openshift_ip=192.168.1.94 openshift_schedulable=true openshift_node_group_name='node-config-master-infra'
node1.mydomain.com openshift_ip=192.168.1.95 openshift_schedulable=true openshift_node_group_name='node-config-compute'
node2.mydomain.com openshift_ip=192.168.1.96 openshift_schedulable=true openshift_node_group_name='node-config-compute'

**Comment by jota2016** [comment]
I have performed a new installation from scratch, this time from git instead of CentOS OpenShift repos, and added this parameters to the inventory:
openshift_console_install=true
openshift_console_hostname=cluster-console.mydomain.com

Still the same.
The cluster fails to start.

oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
error: a port needed by OpenShift is not available


oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.mydomain.com:8443
openshift v3.11.0+d0c29df-98
kubernetes v1.11.0+d4cacc0


oc get cm console-config -n openshift-console -o yaml    
apiVersion: v1
data:
  console-config.yaml: |
    apiVersion: console.openshift.io/v1beta1
    auth:
      clientID: openshift-console
      clientSecretFile: /var/oauth-config/clientSecret
      logoutRedirect: ''
      oauthEndpointCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    clusterInfo:
      consoleBaseAddress: https://cluster-console.mydomain.com
      consoleBasePath: ''
      developerConsolePublicURL: https://master.mydomain.com:8443/console/
      masterPublicURL: https://master.mydomain.com:8443
    customization:
      branding: okd
      documentationBaseURL: https://docs.okd.io/3.11/
    kind: ConsoleConfig
    servingInfo:
      bindAddress: https://0.0.0.0:8443
      certFile: /var/serving-cert/tls.crt
      keyFile: /var/serving-cert/tls.key
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"console-config.yaml":"apiVersion: console.openshift.io/v1beta1\nauth:\n  clientID: openshift-console\n  clientSecretFile: /var/oauth-config/clientSecret\n  logoutRedirect: ''\n  oauthEndpointCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\nclusterInfo:\n  consoleBaseAddress: https://cluster-console.mydomain.com\n  consoleBasePath: ''\n  developerConsolePublicURL: https://master.mydomain.com:8443/console/\n  masterPublicURL: https://master.mydomain.com:8443\ncustomization:\n  branding: okd\n  documentationBaseURL: https://docs.okd.io/3.11/\nkind: ConsoleConfig\nservingInfo:\n  bindAddress: https://0.0.0.0:8443\n  certFile: /var/serving-cert/tls.crt\n  keyFile: /var/serving-cert/tls.key\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"openshift-console"},"name":"console-config","namespace":"openshift-console"}}
  creationTimestamp: 2019-03-06T10:15:57Z
  labels:
    app: openshift-console
  name: console-config
  namespace: openshift-console
  resourceVersion: "2525"
  selfLink: /api/v1/namespaces/openshift-console/configmaps/console-config
  uid: d50f0ce7-3ff8-11e9-acbd-00505685f0a6

**Comment by vrutkovs** [comment]
`oc cluster up` issues should be filed in https://github.com/openshift/origin

**Comment by damora** [comment]
I am running OpenShift 3.11 on ppc64le. I can't get the Cluster console to come up. I have tried all the fixes and nothing works. I have attached outupt of configmaps, oauthclient, and secrets. Any help is appreciated.

oc get -o yaml configmap console-config -n openshift-console >configmap
[configmap.txt](https://github.com/openshift/openshift-ansible/files/3816091/configmap.txt)

oc get -o yaml oauthclient openshift-console >oauthclient
[oauthclient.txt](https://github.com/openshift/openshift-ansible/files/3816097/oauthclient.txt)

oc get -o yaml secret console-oauth-config -n openshift-console >secret
[secret.txt](https://github.com/openshift/openshift-ansible/files/3816098/secret.txt)

**Comment by cvignola** [comment]
For what it's worth, we're experiencing this problem anew on amd64.  OKD 3.11 clusters we setup a few months ago worked fine.  However, until OKD 4.x is out, we still have some test scenarios that require OKD 3.11 and are now stuck.  So far we have not found any issue in https://github.com/openshift/origin that looks like it can help us. Advice appreciated if anyone has any!
