### ISSUE TITLE
Update 3.11 to 4.0

### ISSUE THREAD

**Issue by flipkill1985** [openshift/openshift-ansible#11328]
#### Description

TASK [openshift_version : assert openshift_release in openshift_image_tag] ************************************************************************************************************************
fatal: [192.168.178.43]: FAILED! => {
    "assertion": "openshift_release in openshift_image_tag", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "openshift_image_tag must match same major version as openshift_release. You provided: 4.0 and v3.11.0\n"
}
	to retry, use: --limit @/home/mohs/openshift-ansible/playbooks/prerequisites.retry

PLAY RECAP ****************************************************************************************************************************************************************************************
192.168.178.43             : ok=48   changed=4    unreachable=0    failed=1   
localhost                  : ok=11   changed=0    unreachable=0    failed=0 

3.11 update tp 4.0

**Comment by vrutkovs** [comment]
Updates from 3.11 to 4.0 are not (yet) supported
