### ISSUE TITLE
Require to validate if node name is same with hostname

### ISSUE THREAD

**Issue by bysnupy** [openshift/openshift-ansible#11331]
#### Description

We should add prerequisite rule to check OS hostname is same the node hostname of inventory for clarification.

Some time users misunderstand about node hostname is not related with OS hostname, they think the ansible's hostname is virtual logical name used into only OCP cluster. It can cause not matching OS hostname and node hostname.

If `OS` `hostname` is not same with `hostname` of inventory `host group`, it would be potential troubles, such as certificates created with unexpected `hostname`, `hostname` lookup trouble from `DNS`. 

So we would check if the `OS` `hostname` and `node hostname` (`Ansible hostname`) is same before install.

**Comment by vrutkovs** [comment]
>We should add prerequisite rule to check OS hostname is same the node hostname of inventory for clarification.

I don't think it can be done for installs with cloudprovider. OS hostname can deviate from inventory hostname on AWS, for instance, as kubelet uses cloudprovider metadata instead of hostname in this name

**Comment by bysnupy** [comment]
Thank you for your response @vrutkovs , 

It's a good point !
Yeah I forgot the cloud provider is configured the hostname through  a little different process ...
I just considered on-premise or other virtualization platforms ...

My issue is resolved, because I can understand the situation it should be consider multiple cloud platform either for validation of hostname. I'll close this issue.
