### ISSUE TITLE
Wait for control plane pods to appear fails

### ISSUE THREAD

**Issue by mbw290** [openshift/openshift-ansible#11333]
#### Description

Provide a brief description of your issue here. For example:

I am unable to complete my deployment with the deploy_cluster.yaml playbook.

```
TASK [openshift_control_plane : Wait for control plane pods to appear] **********************************************
Sunday 10 March 2019  07:51:12 -0400 (0:00:00.044)       0:01:37.098 ********** 
FAILED - RETRYING: Wait for control plane pods to appear (60 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (59 retries left).



```

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

[root@oc-master-node-1 ~]# ansible --version
```
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

If you're operating from a **git clone**:

* The output of `git describe`

```
[root@oc-master-node-1 openshift-ansible]# git describe
openshift-ansible-3.11.93-1-2-gcac5fb1
```

##### Steps To Reproduce
1. ansible-playbook -i /etc/ansible/inventory.download playbooks/deploy_cluster.yml 

##### Expected Results
I expect the cluster to deployed without any issues.

```
Example command and output or error messages
```

##### Observed Results

```
FAILED - RETRYING: Wait for control plane pods to appear (1 retries left).
failed: [192.168.1.180] (item=etcd) => {"attempts": 60, "changed": false, "item": "etcd", "msg": {"cmd": "/usr/bin/oc get pod master-etcd-oc-master-node-1.cluster.local -o json -n kube-system", "results": [{}], "returncode": 1, "stderr": "The connection to the server oc-master-node-1:8443 was refused - did you specify the right host or port?\n", "stdout": ""}}
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.
```

[root@oc-master-node-1 openshift-ansible]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@oc-master-node-1 openshift-ansible]# cat /etc/ansible/inventory.download 
[OSEv3:children]
masters
nodes
etcd


[masters]
192.168.1.180 openshift_ip=192.168.1.180 openshift_schedulable=true 

[etcd]
192.168.1.180 openshift_ip=192.168.1.180

[nodes]
192.168.1.180 openshift_ip=192.168.1.180 openshift_node_group_name='node-config-master'
192.168.1.182 openshift_ip=192.168.1.182 openshift_node_group_name='node-config-compute'
192.168.1.183 openshift_ip=192.168.1.183 openshift_node_group_name='node-config-compute'
192.168.1.182 openshift_ip=192.168.1.182 openshift_node_group_name='node-config-infra'

[OSEv3:vars]
openshift_additional_repos=[{'id': 'centos-paas', 'name': 'centos-paas', 'baseurl' :'https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin311', 'gpgcheck' :'0', 'enabled' :'1'}]

openshift_set_node_ip=true
ansible_ssh_user=root
enable_excluders=False
enable_docker_excluder=False
ansible_service_broker_install=False

containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

deployment_type=origin
openshift_deployment_type=origin

template_service_broker_selector={"region":"infra"}
openshift_metrics_image_version="v3.11"
openshift_logging_image_version="v3.11"
openshift_logging_elasticsearch_proxy_image_version="v1.0.0"
openshift_logging_es_nodeselector={"node-role.kubernetes.io/infra":"true"}
logging_elasticsearch_rollout_override=false
osm_use_cockpit=true

openshift_metrics_install_metrics=True 
openshift_logging_install_logging=True

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
openshift_master_htpasswd_file='/etc/origin/master/htpasswd'

openshift_public_hostname=console.mwimp.local
openshift_master_default_subdomain=apps.mwimp.local

openshift_master_api_port=8443
openshift_master_console_port=8443
```

**Comment by chaochuandea** [comment]
same problem.

**Comment by vrutkovs** [comment]
>"The connection to the server oc-master-node-1:8443 was refused - did you specify the right host or port?\n"

1. Can 192.168.1.180 can resolve 'oc-master-node-1' address?
2. Can 192.168.1.180 connect to 'oc-master-node-1' address?
3. Is there an apiserver container running on 'oc-master-node-1' machine?

**Comment by mbw290** [comment]
[root@oc-master-node-1 ~]# nslookup 192.168.1.180 
Server:		192.168.1.180
Address:	192.168.1.180#53

180.1.168.192.in-addr.arpa	name = oc-master-node-1.

[root@oc-master-node-1 ~]# 

[root@oc-master-node-1 ~]# ssh oc-master-node-1
Last login: Mon Mar 11 19:10:28 2019 from 192.168.1.6
[root@oc-master-node-1 ~]# 


[root@oc-master-node-1 ~]# netstat -tulpn | grep 8443
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      17545/openshift

**Comment by mbw290** [comment]
[root@oc-master-node-1 ~]# docker ps -a
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                      PORTS               NAMES
3d4815e81f5e        edf09f393863                             "/bin/bash -c '#!/..."   10 hours ago        Up 10 hours                                     k8s_controllers_master-controllers-oc-master-node-1.cluster.local_kube-system_3210f8756194a0d2e374db4a71b81896_8
9c614e2c6893        ff5dd2137a4f                             "/bin/sh -c '#!/bi..."   10 hours ago        Up 10 hours                                     k8s_etcd_master-etcd-oc-master-node-1.cluster.local_kube-system_6786c0d8132be22d946f7c4a10308155_9
6970b615f784        edf09f393863                             "/bin/bash -c '#!/..."   10 hours ago        Up 10 hours                                     k8s_api_master-api-oc-master-node-1.cluster.local_kube-system_b24b15710309f0062b93e07af49cb464_26
bd517499033c        docker.io/openshift/origin-pod:v3.11.0   "/usr/bin/pod"           10 hours ago        Up 10 hours                                     k8s_POD_master-etcd-oc-master-node-1.cluster.local_kube-system_6786c0d8132be22d946f7c4a10308155_10
44a2c2c0911c        docker.io/openshift/origin-pod:v3.11.0   "/usr/bin/pod"           10 hours ago        Up 10 hours                                     k8s_POD_master-api-oc-master-node-1.cluster.local_kube-system_b24b15710309f0062b93e07af49cb464_9
d13ef55a8135        docker.io/openshift/origin-pod:v3.11.0   "/usr/bin/pod"           10 hours ago        Up 10 hours                                     k8s_POD_master-controllers-oc-master-node-1.cluster.local_kube-system_3210f8756194a0d2e374db4a71b81896_9
be028fd5c414        ff5dd2137a4f                             "/bin/sh -c '#!/bi..."   10 hours ago        Exited (255) 10 hours ago                       k8s_etcd_master-etcd-oc-master-node-1.cluster.local_kube-system_6786c0d8132be22d946f7c4a10308155_8
98d1831f110d        docker.io/openshift/origin-pod:v3.11.0   "/usr/bin/pod"           10 hours ago        Exited (255) 10 hours ago                       k8s_POD_master-etcd-oc-master-node-1.cluster.local_kube-system_6786c0d8132be22d946f7c4a10308155_9
72e3e8161493        edf09f393863                             "/bin/bash -c '#!/..."   10 hours ago        Exited (2) 10 hours ago                         k8s_controllers_master-controllers-oc-master-node-1.cluster.local_kube-system_3210f8756194a0d2e374db4a71b81896_7
2b8dfc3ba193        edf09f393863                             "/bin/bash -c '#!/..."   10 hours ago        Exited (2) 10 hours ago                         k8s_api_master-api-oc-master-node-1.cluster.local_kube-system_b24b15710309f0062b93e07af49cb464_25
d71c96fbfeb2        docker.io/openshift/origin-pod:v3.11.0   "/usr/bin/pod"           10 hours ago        Exited (0) 10 hours ago                         k8s_POD_master-controllers-oc-master-node-1.cluster.local_kube-system_3210f8756194a0d2e374db4a71b81896_8
fa836326ee6f        docker.io/openshift/origin-pod:v3.11.0   "/usr/bin/pod"           10 hours ago        Exited (0) 10 hours ago                         k8s_POD_master-api-oc-master-node-1.cluster.local_kube-system_b24b15710309f0062b93e07af49cb464_8
[root@oc-master-node-1 ~]# 


I attached my updated inventory file and logs.
[inventory.log](https://github.com/openshift/openshift-ansible/files/2956310/inventory.log)
[openshift-ansible.log](https://github.com/openshift/openshift-ansible/files/2956312/openshift-ansible.log)

**Comment by vrutkovs** [comment]
Log says
>"Error from server (NotFound): pods \"master-etcd-oc-master-node-1.cluster.local\" not found\n

and etcd container is stopped:

>be028fd5c414 ff5dd2137a4f "/bin/sh -c '#!/bi..." 10 hours ago Exited (255) 10 hours ago k8s_etcd_master-etcd-oc-master-node-1.cluster.local_kube-system_6786c0d8132be22d946f7c4a10308155_8

What's in the logs for this container?

**Comment by mbw290** [comment]
I killed all running containers, rebooted the box and reran the playbook.

```
[root@oc-master-node-1 openshift-ansible]# docker ps -a
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS               NAMES
270b4c8c354e        ff5dd2137a4f                             "/bin/sh -c '#!/bi..."   11 hours ago        Up 11 hours                             k8s_etcd_master-etcd-oc-master-node-1.cluster.local_kube-system_6786c0d8132be22d946f7c4a10308155_10
4e5f7c627ce8        edf09f393863                             "/bin/bash -c '#!/..."   11 hours ago        Up 11 hours                             k8s_api_master-api-oc-master-node-1.cluster.local_kube-system_b24b15710309f0062b93e07af49cb464_27
7524c09d9842        edf09f393863                             "/bin/bash -c '#!/..."   11 hours ago        Up 11 hours                             k8s_controllers_master-controllers-oc-master-node-1.cluster.local_kube-system_3210f8756194a0d2e374db4a71b81896_9
bf3b7937f151        docker.io/openshift/origin-pod:v3.11.0   "/usr/bin/pod"           11 hours ago        Up 11 hours                             k8s_POD_master-controllers-oc-master-node-1.cluster.local_kube-system_3210f8756194a0d2e374db4a71b81896_10
710d804acb23        docker.io/openshift/origin-pod:v3.11.0   "/usr/bin/pod"           11 hours ago        Up 11 hours                             k8s_POD_master-api-oc-master-node-1.cluster.local_kube-system_b24b15710309f0062b93e07af49cb464_10
e5e771f0af85        docker.io/openshift/origin-pod:v3.11.0   "/usr/bin/pod"           11 hours ago        Up 11 hours                             k8s_POD_master-etcd-oc-master-node-1.cluster.local_kube-system_6786c0d8132be22d946f7c4a10308155_11
[secondrun.txt](https://github.com/openshift/openshift-ansible/files/2961015/secondrun.txt)

```

**Comment by rockocoop** [comment]
i have had a similar issue that i have reproduced consistently where i run the deploy_cluster.yml and it fails with wait for control plane pods.  After then i rerun the deploy_cluster.yml and the deployment is successful.  This is on a fresh installation of 3.11.82.

**Comment by rockocoop** [comment]
I resolved what i mentioned above by setting the servers hostnames to the name and not the FQDN and updating my inventory file with FQDN as inventory_hostname.

**Comment by mbw290** [comment]
Can you show me the hostname outputs, your /etc/hosts file and your inventory file please?

**Comment by rockocoop** [comment]
Basically the working setup is as follows:
- Each node has a parameter "hostname" which i use in a pre-install.yml for vairous things, including setting the server hostname.  Originally i used the FQDN for this but now just the name
- In the inventory file i set the internal name (ansible entry on far left of each node line) to the FQDN.  Previously it was just the name.

This resolved the issue as the POD uses the name but the status check uses the hostname as part of the naming convention for generating the POD name to check.  This caused the POD to have just the name of the host in it but the check to use the FQDN as part of the POD name.

**Comment by mbw290** [comment]
I was able to resolve this by downgrading Ansible.  I attached my hosts and inventory file plus my ansible version.

[inventory.txt](https://github.com/openshift/openshift-ansible/files/2977557/inventory.txt)
[hosts.txt](https://github.com/openshift/openshift-ansible/files/2977560/hosts.txt)
```
[root@oc-master-node-1 openshift-ansible]# ansible --version
ansible 2.6.9
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

**Comment by preetusha** [comment]
hello , I'm still facing the above issue, where my playbook is stuck at following task
![task_failed](https://user-images.githubusercontent.com/14831381/55104744-5fe04200-50a1-11e9-9c71-573982481f2d.jpg)

and it keeps repeating after 60 tries. 
ansible --version =2.6.9
openshift release 3.11.0

Thank you in advance

**Comment by rockocoop** [comment]
please share your inventory file

בתאריך יום ד׳, 27 במרץ 2019, 21:05, מאת preetusha ‏<notifications@github.com

**Comment by preetusha** [comment]
[OSEv3:Children]
masters
etcd
nodes
![invent](https://user-images.githubusercontent.com/14831381/55116970-8ad98e80-50bf-11e9-9a34-f1917f304fd7.PNG)

**Comment by rockocoop** [comment]
1. i would remove openshift_master_cluster_hostname parameter.
2. I believe that you have set openshift_master_cluster_public_hostname to
the domain of your servers and not a VIP FQDN that load balances between
the masters.  You need to setup a VIP with a resolvable FQDN for this that
sits in front of your masters (like via haproxy).  You could at a [lb]
section with one server and then set this value to that server's FQDN as
well.

3. I would also recommend using the FQDN of each server as its inventory
name on the left side and also setting the hostname on the servers to the
name of the server without the domain (not the fqdn)

Hope this helps.

Guy

**Comment by preetusha** [comment]
Sure will try  and let you know, thanks :)

**Comment by preetusha** [comment]
for 2. do you mean create another centos 7 server and use that as [lb]? can you give an example
and for 3. u mean instead of using cp-master1 use cp-master.ra-int.com( my FQDN)? 

thank you.

**Comment by xunchen002** [comment]
I resolved this issue by checking `/var/log/messages`.
And found the error message 
```
Nov  6 02:51:43 localhost dockerd-current: time="2019-11-06T02:51:43.968687455-05:00" level=error msg="Not continuing with pull after error: Error: image openshift3/ose-pod:v3.11.153 not found"
```
After pulling this image to my private registry, I can finally deploy the cluster.

btw, is anyone knows where to set this image version? I set the version in `/etc/ansible/hosts` but it seems not work for `ose-pod` image.

**Comment by adesurya** [comment]
> I was able to resolve this by downgrading Ansible. I attached my hosts and inventory file plus my ansible version.
> 
> [inventory.txt](https://github.com/openshift/openshift-ansible/files/2977557/inventory.txt)
> [hosts.txt](https://github.com/openshift/openshift-ansible/files/2977560/hosts.txt)
> 
> ```
> [root@oc-master-node-1 openshift-ansible]# ansible --version
> ansible 2.6.9
>   config file = /root/openshift-ansible/ansible.cfg
>   configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/lib/python2.7/site-packages/ansible
>   executable location = /usr/bin/ansible
>   python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
> ```

I found new error using your hosts and inventory file. Here the output 

`TASK [openshift_control_plane : Create the htpasswd file if needed] ************
 [WARNING]: Unable to find '/etc/origin/master/htpasswd' in expected paths (use
-vvvvv to see paths)

failed: [openshiftMaster] (item={'challenge': u'true', 'login': u'true', 'kind': u'HTPasswdPasswordIdentityProvider', 'name': u'htpasswd_auth'}) => {"changed": false, "item": {"challenge": "true", "kind": "HTPasswdPasswordIdentityProvider", "login": "true", "name": "htpasswd_auth"}, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ lookup('file', openshift_master_htpasswd_file) | oo_htpasswd_users_from_file if openshift_master_htpasswd_file is defined else l_osm_htpasswd_users_none }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /etc/origin/master/htpasswd"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/root/openshift-ansible/playbooks/openshift-master/config.retry

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0
openshhiftCompute          : ok=15   changed=0    unreachable=0    failed=0
openshiftInfra             : ok=15   changed=0    unreachable=0    failed=0
openshiftMaster            : ok=114  changed=10   unreachable=0    failed=1


INSTALLER STATUS ***************************************************************
Initialization  : Complete (0:00:28)
Master Install  : In Progress (0:00:52)
        This phase can be restarted by running: playbooks/openshift-master/config.yml
`

Can you help me to solved this issue?
