### ISSUE TITLE
all in one node

### ISSUE THREAD

**Issue by ppchu99** [openshift/openshift-ansible#11379]
all in one-node openshift 3.11,  using ansible 2.7.8 -- aka ansible-playbook

Kept getting all kind of network un-reachable error  for repo pointing to ..

http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/

This is an old problem in the past , I am not sure if using ansible 2.7.x is any good or has to go back to ansible 2.6.x

**Comment by nagonzalez** [comment]
you should definitely be on 2.6.x as 2.7 is unsupported atm
