### ISSUE TITLE
SELinux preventing HAProxy service to start on OpenShift LB with changed API port

### ISSUE THREAD

**Issue by amotech-cha** [openshift/openshift-ansible#11388]
#### Description

After changing OpenShift's API port to a non-common HTTP port (openshift_master_api_port: 8449) the HAProxy service run on the OpenShift Load Balancer does not start anymore.

##### Version

Ansible version: ansible 2.6.3
openshift-ansible: openshift-ansible-3.11.95-1

##### Steps To Reproduce
1. Clean system
2. Change the API port in the inventory, e.g. openshift_master_api_port: 8449
3. Run the deployment playbooks

##### Expected Results
Everything gets deployed

##### Observed Results
The deployment stops when trying to determine the rollout status of the control plane pods as the API service (via the load balancer) does not become available. 

##### Additional Information
LB: CentOS Linux release 7.6.1810 (Core)

On the load balancer the haproxy service reports:
xxx haproxy-systemd-wrapper[64800]: [ALERT] 080/084000 (64801) : Starting frontend atomic-openshift-api: cannot bind socket [0.0.0.0:8449]

Digging through the system's audit logs: 
type=AVC msg=audit(xxx: avc:  denied  { name_bind } for  pid=64801 comm="haproxy" src=8449 scontext=system_u:system_r:haproxy_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket permissive=0
type=SYSCALL msg=audit(xxx): arch=c000003e syscall=49 success=no exit=-13 a0=7 a1=55f6f2273cc0 a2=10 a3=55f6f0b0d52c items=0 ppid=64800 pid=64801 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="haproxy" exe="/usr/sbin/haproxy" subj=system_u:system_r:haproxy_t:s0 key=(null)

Quick fix, after which the deployment continues: 
semanage port --add --type http_port_t --proto tcp 8449

**Comment by vrutkovs** [comment]
>On the load balancer the haproxy service reports:
xxx haproxy-systemd-wrapper[64800]: [ALERT] 080/084000 (64801) : Starting frontend atomic-openshift-api: cannot bind socket [0.0.0.0:8449]

So the playbooks do change the port, these just won't set the selinux rules?
