### ISSUE TITLE
openshift v3.11 - deploy_cluster.yml Pre-pull node image fail

### ISSUE THREAD

**Issue by Mshv** [openshift/openshift-ansible#11397]
#### Description

I am trying to install opnehsift v3.11 from the scratch using:
https://github.com/openshift/openshift-ansible/tree/release-3.11

sudo ansible-playbook -i /root/inventory.ini playbooks/prerequisites.yml
sudo ansible-playbook -i /root/inventory.ini playbooks/deploy_cluster.yml

the first yml file which is prerequisites works fine but second one gives me the following error:
![Capture](https://user-images.githubusercontent.com/9473835/54898656-1dcfc880-4f08-11e9-8164-434732d6fadd.GIF)

**[root@workstation playbooks]# ansible-playbook -i /root/inventory.ini deploy_cluster.yml
ERROR! unexpected parameter type in action: <type 'int'>

The error appears to have been in '/root/openshift-ansible/roles/openshift_node/tasks/prepull.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Pre-pull node image
  ^ here**
---------------------------------------------------
[root@workstation playbooks]# ansible --version
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

----------------------------------------------------
And my inventory.ini file 

[OSEv3:children]
masters
nodes
etcd
[masters]
10.11.120.121 openshift_ip=10.11.120.121 openshift_schedulable=true openshift_node_group_name='node-config-master'
[etcd]
10.11.120.121 openshift_ip=192.168.189.176 openshift_node_group_name='node-config-master'
[nodes]
10.11.120.121 openshift_ip=10.11.120.121 openshift_schedulable=true openshift_node_group_name='node-config-master'
10.11.120.122 openshift_ip=10.11.120.122 openshift_schedulable=true openshift_node_group_name='node-config-infra'
10.11.120.123 openshift_ip=10.11.120.123 openshift_schedulable=true openshift_node_group_name='node-config-compute'
10.11.120.125 openshift_ip=10.11.120.125 openshift_schedulable=true openshift_node_group_name='node-config-compute'

[OSEv3:vars]
debug_level=4
ansible_ssh_user=root
enable_excluders=False
enable_docker_excluder=False
openshift_enable_service_catalog=False
ansible_service_broker_install=False

containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

deployment_type=origin
openshift_deployment_type=origin

openshift_release=v3.11.0
openshift_pkg_version=-3.11.0
openshift_image_tag=v3.11.0
openshift_service_catalog_image_version=v3.11.0
template_service_broker_image_version=v3.11.0

osm_use_cockpit=true

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
openshift_master_htpasswd_file='/etc/origin/master/htpasswd'

openshift_public_hostname=console.XXX.io
openshift_master_default_subdomain=apps.XXX.io

**Comment by BaruchDavid** [comment]
hello,
i have same issue with ansible 2.8.4.
Did you solved it?

**Comment by hafei** [comment]
i have same issue.
