### ISSUE TITLE
Install OpenShift-3.11 fails because of "The conditional check 'openshift_docker_ent_reg in oreg_url' failed"

### ISSUE THREAD

**Issue by pdellaert** [openshift/openshift-ansible#11419]
#### Description

When i'm installing OCP 3.11 using OpenShift Ansible, with the following hosts/nodes file, i run into an error that a conditional check fails. 

My nodes file does not contain `oreg_url`, only `oreg_auth_user` and `oreg_auth_password`. The only settings that contain `registry` or `registries` in them are:
```
openshift_docker_insecure_registries=172.254.0.0/16
openshift_docker_additional_registries=registry.access.redhat.com,docker.io
```

##### Analysis
This worked fine until this commit was made:
https://github.com/openshift/openshift-ansible/commit/6ce0ecc9f44170626a7ed44b06db18f47058db57#diff-90877efe325ca457cac9ff7838e909c8

##### Version

**ansible --version**
```
# ansible --version
ansible 2.7.9
  config file = /root/Nuage/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

**git describe**
```
# git describe
openshift-ansible-3.11.101-1-4-g4406c98
```

##### Steps To Reproduce
1. `git clone https://github.com/openshift/openshift-ansible`
2. `cd openshift-ansible`
3. `git checkout release-3.11`
4.  Provide nodes file, no `oreg_url`
5. `ansible-playbook -i nodes -vvvv playbooks/prerequisites.yml`
6. `ansible-playbook -i nodes -vvvv playbooks/deploy_cluster.yml`

##### Expected Results
Succesful install

##### Observed Results
Failed install with error
```
2019-03-28 16:20:09,836 p=2637 u=root |  fatal: [ocp-master01.lab.local]: FAILED! => {
    "msg": "The conditional check 'openshift_docker_ent_reg in oreg_url' failed. The error was: error while evaluating conditional (openshift_docker_ent_reg in oreg_url): Unable to look up a name or access an attribute in template string ({% if openshift_docker_ent_reg in oreg_url %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable\n\nThe error appears to have been in '/root/Nuage/openshift-ansible/roles/container_runtime/tasks/common/pre.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add enterprise registry, if necessary\n  ^ here\n"
}
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

OS for openshift-ansible node:
```
# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core)
```

OS for OCP nodes:
```
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```

**Comment by vrutkovs** [comment]
@jcpowermac PTAL, seems default oreg_url is not set in container_runtime role

@pdellaert, does anything else break if `oreg_url` is specified, set to `registry.access.redhat.com`?

**Comment by pdellaert** [comment]
@vrutkovs, if i configure `oreg_url` in my hosts file, it all works fine
