### ISSUE TITLE
openshift mirror method?

### ISSUE THREAD

**Issue by hetzbh** [openshift/openshift-ansible#11438]
Hi,
I need to install OKD 3.11 on a closed environment (no internet connection), which means I need to  create a local mirror of everything.

My question: which file(s) do I need to change to download the RPMS so they'll download from my local mirror?

**Comment by llomgui** [comment]
Hey,

First, you need to add "openshift_enable_origin_repo=false" in your inventory file.
Then in your local mirror (you can find rpm-gpg-key [here](https://github.com/CentOS-PaaS-SIG/centos-release-paas-common/blob/master/RPM-GPG-KEY-CentOS-SIG-PaaS)):

Prepare your repo file (/etc/yum.repos.d/CentOS-OpenShift-Origin.repo):
```
[openshift-origin]
name=CentOS OpenShift Origin
baseurl=https://linuxsoft.cern.ch/centos/7/paas/x86_64/openshift-origin/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-PaaS
```
Create your directory to save all rpms:
```
mkdir -p /var/www/html/repos/openshift-origin
reposync -g -l -d -m --repoid=openshift-origin --newest-only --download-metadata --download_path=/var/www/html/repos/
touch /var/www/html/repos/openshift-origin/comps.xml
createrepo -g comps.xml /var/www/html/repos/openshift-origin
```

Do not forget your daily cron.
