### ISSUE TITLE
Atomic Host install fails - pyyaml import error

### ISSUE THREAD

**Issue by keithjeb** [openshift/openshift-ansible#11451]
#### Description
Installation using containerized method fails on atomic host 4.2 as PyYAML is not available for default python2.7 interpreter.

Fix by using:
```
ansible_python_interpreter=python3
```
in inventory file. 
This seems like an omission from docs rather than a bug, happy to submit a PR if someone can point me at the right repo.

##### Version
3.11 docker image

##### Steps To Reproduce
Execute an install:
```
atomic install --system --storage=ostree --set INVENTORY_FILE=/home/fedora/hosts --set PLAYBOOK_FILE=/usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml --set OPTS="-v" docker.io/openshift/origin-ansible:v3.11
```
with hosts running Fedora atomic host.

##### Expected Results
Describe what you expected to happen.
Successful completion, or useful error in the event of missing prerequisite

##### Observed Results
Describe what is actually happening.

Fails due to lack of python 2.7 pyyaml on host, relevant extract below, [full here: ](https://gist.github.com/keithjeb/5798defe5fe4d6da65fb097dd078deee)
```
<atomic02.local> (1, '', 'Traceback (most recent call last):\n  File "<stdin>", line 113, in <module>\n  File "<stdin>", line 105, in _ansiballz_main\n  File "<stdin>", line 48, in invoke_module\n  File "/tmp/ansible_openshift_facts_payload_q39YTH/__main__.py", line 15, in <module>\nImportError: No module named yaml\n')
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 113, in <module>
  File "<stdin>", line 105, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/tmp/ansible_openshift_facts_payload_q39YTH/__main__.py", line 15, in <module>
ImportError: No module named yaml

fatal: [atomic02.local]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/tmp/ansible_openshift_facts_payload_q39YTH/__main__.py\", line 15, in <module>\nImportError: No module named yaml\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

```
##### Additional Information

This can be fixed by setting 
```
ansible_python_interpreter=python3
```
in the inventory.

**Comment by vrutkovs** [comment]
Ansible can't detect which python version suits better, the admin hast to set the correct interpreter in the inventory

/close

**Comment by keithjeb** [comment]
@vrutkovs fully agreed, which is why I also posted a solution. However this isn't mentioned in the docs, probably a note in the atomic section of 'preparing the host' might save others the same headaches debugging I had.

**Comment by vrutkovs** [comment]
Please file an issue in https://github.com/openshift/openshift-docs/ for that
