### ISSUE TITLE
auto scaler doesnt work

### ISSUE THREAD

**Issue by yeganx** [openshift/openshift-ansible#11462]
I have installed  the OKD metrics server:
$ ansible-playbook \
/usr/share/ansible/openshift-ansible/playbooks/metrics-server/config.yml  -i host.txt
-e openshift_metrics_server_install=true
I didnt change host.txt file , do i need add something ?

my versions :
#oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.toodevops.com:8443
openshift v3.11.0+d0c29df-98
kubernetes v1.11.0+d4cacc0

#oc adm top node
NAME                   CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%   
master.toodevops.com   2106m        70%       5753Mi          36%       
node1.toodevops.com    472m         15%       3619Mi          21%       
node2.toodevops.com    1279m        42%       9197Mi          58%

in my project which i add auto scaler :
#oc adm top pod
NAME               CPU(cores)   MEMORY(bytes)   
httpd-ex-3-59pnr   75m          28Mi

#oc get hpa
NAME       REFERENCE                   TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
httpd-ex   DeploymentConfig/httpd-ex   <unknown>/20%   1         2         1          1h

#oc describe hpa
Name:                                                  httpd-ex
Namespace:                                             test-autosaler
Labels:                                                app=httpd-ex
Annotations:                                           <none>
CreationTimestamp:                                     Thu, 04 Apr 2019 16:47:27 +0430
Reference:                                             DeploymentConfig/httpd-ex
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 20%
Min replicas:                                          1
Max replicas:                                          2
DeploymentConfig pods:                                 1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
Events:
  Type     Reason                        Age                 From                       Message
  ----     ------                        ----                ----                       -------
  Warning  FailedComputeMetricsReplicas  1h (x13 over 1h)    horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
  Warning  FailedGetResourceMetric       55s (x191 over 1h)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)

**Comment by yeganx** [comment]
# oc get hpa 
target ==>  <unknown>/20% 
 #oc describe hpa 
Warning FailedComputeMetricsReplicas 1h (x13 over 1h) horizontal-pod-autoscaler failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)

**Comment by vrutkovs** [comment]
HPA issues should be filed in https://github.com/openshift/origin
