### ISSUE TITLE
my pod can not access internet with domain name

### ISSUE THREAD

**Issue by yeganx** [openshift/openshift-ansible#11461]
I install okd 3.11 version
my problem is : can not ping google.com in none of my pod , also i dont have access to change resolve.conf file in my pods . and my internal dns is set in  resolve.conf file 
#vi /etc/resolv.conf
nameserver 192.168.96.229 # my intelnal dns
search test-autosaler.svc.cluster.local svc.cluster.local cluster.local toodevops.com
options ndots:5

**Comment by vrutkovs** [comment]
Your resolv.conf should be managed by NetworkManager - see https://docs.okd.io/3.11/install/prerequisites.html#dns-config-prereq
