### ISSUE TITLE
Cluster Console ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by tiempososcuros** [openshift/openshift-ansible#11494]
#### Description
I cant access the Cluster Console from web site
I go in Menu-> Service Catalog->Cluster Console
and get "ERR_CONNECTION_REFUSED".
Choosing this menu option redirect me to https://console.okd.tiempososcuros.tk
Website: https://okd-master.tiempososcuros.tk:8443

Records DNS:
*.okd.tiempososcuros.tk A 192.168.2.29
okd-master.tiempososcuros.tk A 192.168.2.29

##### Version
```
ansible --version
ansible 2.7.10

git describe
openshift-ansible-3.11.105-1-4-g7b3e790
```

##### Steps To Reproduce
Login as root
```
git clone https://github.com/openshift/openshift-ansible
cd openshift-ansible
ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml
ansible-playbook -i inventory/hosts.localhost playbooks/deploy_cluster.ym
```

##### Expected Results
Access to Cluster console thru website.

##### Observed Results
Connection refused after trying to access Cluster Console thru web console.

```
curl https://console.okd.tiempososcuros.tk
curl: (7) Failed connect to console.okd.tiempososcuros.tk:443; Connection refused
```

##### Additional Information
* CentOS Linux release 7.5.1804 (Core) with minimum install and completed all dependiecies for install OKD Openshift. Reinstalling whole enviroment from scratch 2 times and get the same effect.

* Inventory File
```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
openshift_master_identity_providers=[{'name': 'AllowAll_auth', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]
os_firewall_use_firewalld=True
openshift_deployment_type=origin
openshift_master_default_subdomain=okd.tiempososcuros.tk
openshift_router_selector='node-role.kubernetes.io/compute=true'
openshift_registry_selector='node-role.kubernetes.io/compute=true'
openshift_cluster_monitoring_operator_install=false
openshift_enable_service_catalog=false

[masters]
okd-master.tiempososcuros.tk

[etcd]
okd-master.tiempososcuros.tk

[nodes]
okd-master.tiempososcuros.tk openshift_node_group_name='node-config-master'
okd-node1.tiempososcuros.tk openshift_node_group_name='node-config-compute'
okd-node2.tiempososcuros.tk openshift_node_group_name='node-config-compute'
```

**Comment by nagonzalez** [comment]
Your wildcard DNS should point to the machines running the `router` which in your inventory you set as:
`openshift_router_selector='node-role.kubernetes.io/compute=true'`

You'll need something like this:

DNS:
```
*.okd.tiempososcuros.tk A ip_of_okd-node1.tiempososcuros.tk
*.okd.tiempososcuros.tk A ip_of_okd-node2.tiempososcuros.tk
okd-master.tiempososcuros.tk A 192.168.2.29
```

**Comment by tiempososcuros** [comment]
I added the DNS entries and now it works. However, I can only see the default project. How could you see other projects, such as those that start with openshift-?
Thanks

**Comment by niiku** [comment]
You mean in the cluster console? Can you maybe provide screenshots as your description is unclear.

**Comment by ZrytyADHD** [comment]
First login to your master server and do this comand:
oc login -u system:admin
after login do this comand:
oc adm policy add-cluster-role-to-user  cluster-admin admin

the second one give your user admin cluster-admin role and voila you will have access to all your projects

**Comment by tiempososcuros** [comment]
Now everything works correctly.
Thank you.

**Comment by kevingentile** [comment]
The instructions provide by @ZrytyADHD made the projects created through the ansible installation available to my admin user. I would expect the admin user have the cluster-admin role by default.
