### ISSUE TITLE
OSE 3.11 installer: Elasticsearch PV name is hardcoded

### ISSUE THREAD

**Issue by Fodoj** [openshift/openshift-ansible#11492]
#### Description

Installer allows to  configure name of the volume and NFS share, but in the end it always expects PV to be named `logging-volume`: https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_logging_elasticsearch/tasks/main.yaml#L428.

As a result, NFS share has to be also named "/nfs-dir/logging-volume".

##### Version

3.11

**Comment by jonasdemoor** [comment]
I can confirm this, I worked around this by changing `logging-volume` to `openshift-dev-logging-volume` (in my case) in the playbook. This isn't  ideal, and will probably break in the long term.

**Comment by ewolinetz** [comment]
A PR would be most welcome
