### ISSUE TITLE
openshift_hostname fixes

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#115]
- openshift_common
  - if openshift_hostname is set and doesn't match system hostname, set hostname to openshift_hostname
- openshift_node
  - set --hostname flag in /etc/sysconfig/openshift-node using openshift_hostname.

**Comment by sosiouxme** [comment]
I should mention that when I ran an install earlier, I managed to wind up with the nodes being named e.g. "node1" instead of their FQDN. This works fine as long as the --hostname params on both services match the node records. Since there was no --hostname on openshift-node, that was not the case; master and sdn-node thought the node was called node1, openshift-node used the FQDN.

This *could* be related to the fact that I deployed them after deploying the master with its own node, or to the fact that I initially failed to deploy them because they had a bogus hostname (breaking `hostname -f`).

**Comment by chmouel** [comment]
It seems that ansible is using ansible_host which use socket.getfqdn() instead of hostname -f which would be wrong when running from a public cloud vm
There is a bug in ansible for that here https://github.com/ansible/ansible/issues/9972

**Comment by detiber** [comment]
@chmouel Was just getting ready to dig into this, thanks.

I got a little excited when I saw the reference to ansible_nodename, but it looks like it just takes the output of uname, which might return just the hostname. Then I saw there was ansible_hostname and ansible_domain and thought we could possibly just join those, but ansible_domain is derived from the fqdn.

It looks like I'll have to work around it by querying the output of `hostname -f`

**Comment by detiber** [comment]
@chmouel @sosiouxme Mind giving this a try against the latest builds and the v3-beta3 branch? 

I've written up some cloud deployment related notes here as well: https://gist.github.com/detiber/533780527af710241298

On well behaved clouds, there should be no additional config needed, but for example if using os1, the metadata publishes a non-resolvable hostname for the public hostname, so openshift_public_hostname needs to be overridden for the hosts.

**Comment by sosiouxme** [comment]
I ignored the gist and ran my usual shtick on openstack. This includes setting up hostnames and DNS before starting the install. I use the same names in the BYO inventory I copy from the ansible repo. For some reason, ansible setting the hostname seems to have borked:

```
TASK: [openshift_common | Set hostname] *************************************** 
<master.osv3-0331.example.com> 
<master.osv3-0331.example.com> name=lmeyer-0331-rhel7osv3-ose-399775d4-8f1a-4b9f-8f4c-b5510c963a43.os1.phx2.redhat.com
<master.osv3-0331.example.com> ConnectTimeout=10 PasswordAuthentication=no KbdInteractiveAuthentication=no ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey ControlMaster=auto ControlPersist=60s
<master.osv3-0331.example.com> 
<master.osv3-0331.example.com> ConnectTimeout=10 PasswordAuthentication=no 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1427831988.43-22142418093986/hostname; rm -rf /root/.ansible/tmp/ansible-tmp-1427831988.43-22142418093986/ >/dev/null 2>&1' KbdInteractiveAuthentication=no ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey ControlMaster=auto ControlPersist=60s
failed: [master.osv3-0331.example.com] => {"failed": true}
msg: Command failed rc=1, out=, err=Failed to issue method call: Invalid argument
```

Not sure where it even got the original OS1 name from? Anyway, perhaps that's not how you meant it to be used yet.

Still true that "non-root user is currently broken when attempting to synchronize certs from the master to the nodes"?

Is test_inventory in the gist supposed to come from the text in the gist? Don't see the file anywhere else.

**Comment by detiber** [comment]
@sosiouxme not sure how many of these are still affecting, you...
>Not sure where it even got the original OS1 name from? Anyway, perhaps that's not how you meant it to be used yet.

It's coming from the openshift_facts module now (in the openshift_facts role). Overriding the hostname can be done by using the openshift_hostname and openshift_public_hostname variables.

>Still true that "non-root user is currently broken when attempting to synchronize certs from the master to the nodes"?

Yes, since the cert dirs are owned by root, the synchronize ansible module bumps into issues rsync'ing the content (sudo requiring tty). It can be worked around by modifying the sudoers file to add !requiretty, but I'm not fully convinced that we should be modifying the sudoers file on people's systems or requiring it to be a default. My current idea is to create a tarball of the content that is then put in the remote_user's path, can then be sync'd locally, and then use the [unarchive module](http://docs.ansible.com/unarchive_module.html) to handle sync'ing to the node. I want to get the master/node config changes out of the way before tackling that though.

>Is test_inventory in the gist supposed to come from the text in the gist? Don't see the file anywhere else.
It was just meant as an example that was self contained in the gist.  I avoided the byo playbook because it makes use of an inventory group_vars directory that is not as clear as the explicit variables in the test_inventory playbook.

**Comment by sosiouxme** [comment]
@detiber I feel like we had the same "sudo needs tty" problem in oo-install and got around it eventually (without forcing edits to sudoers).

**Comment by newgoliath** [comment]
I'm pretty confused by this.  If I'm using something like:

```
export OS_DEPLOYMENT_TYPE="enterprise"
bin/cluster -vv create -n 2 \
-o dns=192.168.190.81 \
-o image_name=rhel7.1 \
-o node_flavor_id=f8e3f887-7779-4a31-955d-9b958227c7f7 \
-o master_flavor_id=f8e3f887-7779-4a31-955d-9b958227c7f7 \
-o master_flavor_ram='' \
-o node_flavor_ram='' \
-o floating_ip_pools='external_net' \
-o external_net='external_net' \
-o deployment_type=enterprise \
openstack dellcloud
```

Where can I set the domain name to create the FQDNs necessary?

**Comment by detiber** [comment]
@newgoliath you *might* be able to specify it using `-o openshift_hostname` and `-o openshift_public_hostname`, but I haven't tested to see if the -o flag supports arbitrary variable setting or if it is limited to certain variables.

For enterprise deployments, we are not officially supporting bin/cluster as a deployment mechanism, and have been pointing people to the byo playbooks using a pre-defined inventory.

**Comment by newgoliath** [comment]
@detiber - thanks for the clarification.  I do like the total automation and integration of bin/cluster.  It would dovetail nicely with our OSP automation.  I might try hacking on it a bit to get the right values to be passed through.

**Comment by detiber** [comment]
@newgoliath totally understand. Long term goal is to get the enterprise installer wrapper (https://github.com/openshift/openshift-extras/tree/enterprise-3.0/oo-install) able to do all types of installs, support provisioning hosts ala bin/cluster, and support the majority of configurations using a yaml config file.

Once things settle down a bit on the openshift-ansible feature requests, we'll start making some progress towards that goal.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
