### ISSUE TITLE
Infinite wait when try to drain a node that has POD with PDB.

### ISSUE THREAD

**Issue by phlbrz** [openshift/openshift-ansible#11503]
Hello all,

I don't know how to open an issue about it.
I took a look at this task https://github.com/openshift/openshift-ansible/blob/9a0120f7502d753fcc8230597c50142017127742/playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml#L41
When I run the playbook upgrade_nodes openshift 3.11, some nodes that have pods with PDB get drain stuck and never ends the playbook with error or success.

What I had to do:
`oc adm manage-node nodexxx --schedulable=false` 
Look for pods that has PDB:
`oc get pdb --all-namespaces`
`oc delete po podxx1 -n xx` 
`oc delete po podxx2 -n xy`
`oc adm drain nodexx --grace-period=20 --ignore-daemonsets --force --delete-local-data --timeout=20s`
`oc label --overwrite node nodexx maintenance=true`
`sudo ansible-playbook -i inventory.ini /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_11/upgrade_nodes.yml -e openshift_upgrade_nodes_serial="1" -e openshift_upgrade_nodes_label="maintenance=true" -vvvv`

Playbook Sucess.
You can now remove maintenance label from the node.

Sources to understand the problem: 
https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#how-disruption-budgets-work
https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pdb-example

**Comment by vrutkovs** [comment]
Please report this issue at https://github.com/openshift/origin

**Comment by phlbrz** [comment]
@vrutkovs 

But when I started to open an issue at https://github.com/openshift/origin/issues/new has this note:



And what I reported is an Openshift Installer/Upgrade issue.
