### ISSUE TITLE
Deploy Image x509 error

### ISSUE THREAD

**Issue by marlon617** [openshift/openshift-ansible#11519]
![image](https://user-images.githubusercontent.com/5423846/56349497-40998800-61fb-11e9-8444-01a2df2481f4.png)

 Could not load image metadata.
Internal error occurred: Get https://registry.server.gingkoo/v2/: x509: certificate signed by unknown authority

版本 3.11

通过webconsole deploy images 出现证书错误。如上图 
命令行可以操作。
使用的外部仓库harbor 证书是自己制作的。

**Comment by niiku** [comment]
Hi @marlon617,
your cluster resp. docker daemon doesn't trust the TLS certificate from `registry.server.gingkoo`. So either you configure there a TLS certificate from a trusted CA (public or imported self signed CA), or you add the registry as `openshift_docker_insecure_registries` and allow http traffic, which is probably easier but not recommended. 
See more here 
https://docs.okd.io/3.11/install/configuring_inventory_file.html#configuring-cluster-variables

**Comment by marlon617** [comment]
如何导入自签名CA
