### ISSUE TITLE
add loadblancer to master HA

### ISSUE THREAD

**Issue by yeganx** [openshift/openshift-ansible#11528]
I have installed openshift 3.11 with 3 node , after installation I add HA master through this link 
https://docs.okd.io/latest/install_config/adding_hosts_to_existing_cluster.html
but now I dont know how set loadblancer and run which playbook for that ?
also in  https://docs.okd.io/latest/install/example_inventories.html#multi-masters-single-etcd-using-native-ha , I have read : 

> Moving from a single master cluster to multiple masters after installation is not supported.

so If It is correct why we have instruction to add master node ?
I confused :(

**Comment by yeganx** [comment]
Hello no answer?!

**Comment by faust64** [comment]
As far as I understand from your post, to the question "why do we have instructions to add master nodes", the answer would be: to recover from a master failure.

To the question "how to set loadbalancers", the advanced installation docs [1] would tell about adding some `lb` hostgroup to your Ansible inventory, listing instances to be deployed as HAproxy balancers.

Which playbook: you'll find a `playbooks/openshift-loadbalancer/config.yml` playbook that may be used deploying these.

[1] https://docs.openshift.com/enterprise/3.1/install_config/install/advanced_install.html#multiple-masters
