### ISSUE TITLE
Load heketi topology:  Unable to add device (already initialized or contains data?)

### ISSUE THREAD

**Issue by jjman4** [openshift/openshift-ansible#11547]
Hi,
Need a help to troubleshoot my issue when installing glusterfs via ansible

ansible-playbook playbooks/openshift-glusterfs/config.yml
.....
TASK [openshift_storage_glusterfs : Load heketi topology] ***********************************************************************************************************************************************************************************
Wednesday 24 April 2019  15:22:12 +0300 (0:00:00.882)       0:01:31.050 *******
fatal: [master.telma.net]: FAILED! => {"changed": true, "cmd": ["oc", "--config=/tmp/openshift-glusterfs-ansible-7dQNRe/admin.kubeconfig", "rsh", "--namespace=app-storage", "deploy-heketi-storage-1-zpflc", "heketi-cli", "-s", "http://localhost:8080", "--user", "admin", "--secret", "kCvUSnJiQvOoEBvgWYoFISKd4TL7n3IEstUYzc9LGQc=", "topology", "load", "--json=/tmp/openshift-glusterfs-ansible-7dQNRe/topology.json", "2>&1"], "delta": "0:00:03.518289", "end": "2019-04-24 15:22:16.030151", "failed_when_result": true, "rc": 0, "start": "2019-04-24 15:22:12.511862", "stderr": "", "stderr_lines": [], "stdout": "Creating cluster ... ID: 87168c9efc3f507ed3908234786a12f9\n\tAllowing file volumes on cluster.\n\tAllowing block volumes on cluster.\n\tCreating node master... ID: 4bac38895af0ab2c4eb66bf5f89eda89\n\t\tAdding device /dev/mapper/vg02-datavol ... Unable to add device: Setup of device /dev/mapper/vg02-datavol failed (already initialized or contains data?): setterm: $TERM is not defined.\n  Can't initialize physical volume \"/dev/mapper/vg02-datavol\" of volume group \"vg_701e9c06670ec3d7fe020095e665ab8e\" without -ff\n  /dev/mapper/vg02-datavol: physical volume not initialized.\n\tCreating node node1 ... ID: fddce4bc0e6cbf1ae1d8f54291303e9b\n\t\tAdding device /dev/mapper/vg02-datavol ... Unable to add device: Setup of device /dev/mapper/vg02-datavol failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain", "stdout_lines": ["Creating cluster ... ID: 87168c9efc3f507ed3908234786a12f9", "\tAllowing file volumes on cluster.", "\tAllowing block volumes on cluster.", "\tCreating node tapt364lv.corp.telma.mg ... ID: 4bac38895af0ab2c4eb66bf5f89eda89", "\t\tAdding device /dev/mapper/vg02-datavol ... Unable to add device: Setup of device /dev/mapper/vg02-datavol failed (already initialized or contains data?): setterm: $TERM is not defined.", "  Can't initialize physical volume \"/dev/mapper/vg02-datavol\" of volume group \"vg_701e9c06670ec3d7fe020095e665ab8e\" without -ff", "  /dev/mapper/vg02-datavol: physical volume not initialized.", "\tCreating node tapt365lv.corp.telma.mg ... ID: fddce4bc0e6cbf1ae1d8f54291303e9b", "\t\tAdding device /dev/mapper/vg02-datavol ... Unable to add device: Setup of device /dev/mapper/vg02-datavol failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain"]}

$ oc get no -o wide
NAME                      STATUS    ROLES          AGE       VERSION           INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                                      KERNEL-VERSION          CONTAINER-RUNTIME
master   Ready     infra,master   13d       v1.11.0+d4cacc0   192.168.8.83   <none>        Red Hat Enterprise Linux Server 7.4 (Maipo)   3.10.0-693.el7.x86_64   docker://1.13.1
node1   Ready     compute        13d       v1.11.0+d4cacc0   192.168.8.84   <none>        Red Hat Enterprise Linux Server 7.4 (Maipo)   3.10.0-693.el7.x86_64   docker://1.13.1

$ oc get pods --namespace app-storage
NAME                            READY     STATUS    RESTARTS   AGE
deploy-heketi-storage-1-zpflc   1/1       Running   0          26m

$ cat /etc/ansible/hosts
.....
#GlusterFS
openshift_storage_glusterfs_namespace=app-storage
openshift_storage_glusterfs_storageclass=true
openshift_storage_glusterfs_storageclass_default=false
openshift_storage_glusterfs_block_deploy=true
openshift_storage_glusterfs_block_host_vol_size=100
openshift_storage_glusterfs_block_storageclass=true
openshift_storage_glusterfs_block_storageclass_default=false
openshift_storage_glusterfs_is_native=false
openshift_storage_glusterfs_storageclass=true
openshift_storage_glusterfs_heketi_is_native=true
openshift_storage_glusterfs_heketi_executor=ssh
openshift_storage_glusterfs_heketi_ssh_port=22
openshift_storage_glusterfs_heketi_ssh_user=root
openshift_storage_glusterfs_heketi_ssh_sudo=false
openshift_storage_glusterfs_heketi_ssh_keyfile="/root/.ssh/id_rsa"

[glusterfs]
master glusterfs_devices='["/dev/mapper/vg02-datavol"]'
node1 glusterfs_devices='["/dev/mapper/vg02-datavol"]'
.....

$ ansible --version
ansible 2.7.9
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

**Comment by jjman4** [comment]
Installing heketi-client.x86_64 heketi.x86_64 and got the error below:

fatal: [master]: FAILED! => {"changed": true, "cmd": ["oc", "--config=/tmp/openshift-glusterfs-ansible-Y1LjC0/admin.kubeconfig", "rsh", "--namespace=app-storage", "dep                                                            loy-heketi-storage-1-sgh2t", "heketi-cli", "-s", "http://localhost:8080", "--user", "admin", "--secret", "Y6+oF2SSyrAF5DpAyCZvPZSD6ESci6EubkvbIxZ6q6g=", "topology", "load", "--j                                                            son=/tmp/openshift-glusterfs-ansible-Y1LjC0/topology.json", "2>&1"], "delta": "0:00:00.471942", "end": "2019-04-24 17:09:22.842348", "failed_when_result": true, "rc": 0, "start"                                                            : "2019-04-24 17:09:22.370406", "stderr": "", "stderr_lines": [], "stdout": "Creating cluster ... ID: 27ff88019cb3b3468fb047455dc07c2f\n\tAllowing file volumes on cluster.\n\tAl                                                            lowing block volumes on cluster.\n\tCreating node master ... Unable to create node: New Node doesn't have glusterd running\n\tCreating node node1 ... Unable to create node: New Node doesn't have glusterd running", "stdout_lines": ["Creating cluster ... ID: 27ff88019cb3b3468fb047455dc07c2f", "\tAllowing file volumes on                                                             cluster.", "\tAllowing block volumes on cluster.", "\tCreating node master ... Unable to create node: New Node doesn't have glusterd running", "\tCreating node                                                            node1 ... Unable to create node: New Node doesn't have glusterd running"]}

**Comment by ZrytyADHD** [comment]
First check the disk which you use trying to deploy cluster. I belive you want to use disk which is already used before.
To avoid any complication during deployment glusterr i use this script on all glusterfs nodes and master and gluster always deploy with success:

`setsebool -P virt_use_fusefs on
setsebool -P virt_sandbox_use_fusefs on

 firewall-cmd --zone=public --add-port=24007-24008/tcp --permanent; \
        firewall-cmd --zone=public --add-port=24009/tcp --permanent; \
        firewall-cmd --zone=public --add-service=nfs --add-service=samba --add-service=samba-client --permanent;\
        firewall-cmd --zone=public --add-port=111/tcp --add-port=139/tcp --add-port=445/tcp --add-port=965/tcp --add-port=2049/tcp \
         --add-port=38465-38469/tcp --add-port=631/tcp --add-port=111/udp --add-port=963/udp --add-port=49152-49251/tcp --permanent; \
        firewall-cmd --reload;
	   
yum install -y glusterfs glusterfs-fuse centos-release-gluster5.noarch glusterfs-api glusterfs-cli glusterfs-server heketi heketi-client epel-release
yum install -y glusterfs glusterfs-fuse centos-release-gluster5.noarch glusterfs-api glusterfs-cli glusterfs-server heketi heketi-client epel-release
systemctl start glusterd
systemctl enable glusterd

firewall-cmd --add-service=glusterfs --permanent &&\
		firewall-cmd --reload

touch /etc/firewalld/services/heketi.xml

cat <<EOF > /etc/firewalld/services/heketi.xml
<?xml version="1.0" encoding="utf-8"?> 
<service>
 <short>Heketi</short>
 <description>Heketi glusterfs REST API</description>
 <port protocol="tcp" port="8080"/>
</service>
EOF

restorecon /etc/firewalld/services/heketi.xml
chmod 640 /etc/firewalld/services/heketi.xml


firewall-cmd --zone=internal --add-service=heketi --permanent


`

**Comment by jjman4** [comment]
Hi,
after applying all the tips above, issue still happen.

fatal: [master.telma.net]: FAILED! => {"changed": true, "cmd": ["oc", "--config=/tmp/openshift-glusterfs-ansible-K3mpVR/admin.kubeconfig", "rsh", "--namespace=app-storage", "deploy-heketi-storage-1-g29tn", "heketi-cli", "-s", "http://localhost:8080", "--user", "admin", "--secret", "v4p7TWIv3NiUSknltU4ATuspybzfbdnyRvkWe7RgVUI=", "topology", "load", "--json=/tmp/openshift-glusterfs-ansible-K3mpVR/topology.json", "2>&1"], "delta": "0:00:00.531467", "end": "2019-05-03 15:44:02.990181", "failed_when_result": true, "rc": 0, "start": "2019-05-03 15:44:02.458714", "stderr": "", "stderr_lines": [], "stdout": "Creating cluster ... ID: b87e755fbfef89e8e6976b0d86aebdd6\n\tAllowing file volumes on cluster.\n\tAllowing block volumes on cluster.\n\tCreating node master ... Unable to create node: New Node doesn't have glusterd running\n\tCreating node node1 ... Unable to create node: New Node doesn't have glusterd running", "stdout_lines": ["Creating cluster ... ID: b87e755fbfef89e8e6976b0d86aebdd6", "\tAllowing file volumes on cluster.", "\tAllowing block volumes on cluster.", "\tCreating node master ... Unable to create node: New Node doesn't have glusterd running", "\tCreating node node1 ... Unable to create node: New Node doesn't have glusterd running"]}

All necessary packages installed:
Package glusterfs-6.1-1.el7.x86_64 already installed and latest version
Package glusterfs-fuse-6.1-1.el7.x86_64 already installed and latest version
Package glusterfs-api-6.1-1.el7.x86_64 already installed and latest version
Package glusterfs-cli-6.1-1.el7.x86_64 already installed and latest version
Package glusterfs-server-6.1-1.el7.x86_64 already installed and latest version
Package heketi-8.0.0-1.el7.x86_64 already installed and latest version
Package heketi-client-8.0.0-1.el7.x86_64 already installed and latest version
Package epel-release-7-11.noarch already installed and latest version

**Comment by ZrytyADHD** [comment]
First make sure you have on all nodes run **glusterd**
"Unable to create node: New Node doesn't have glusterd running"

In my inventory file i also add this lines:

`# app storage gluster
openshift_storage_glusterfs_namespace=app-storage
openshift_storage_glusterfs_storageclass=true
openshift_storage_glusterfs_storageclass_default=false
openshift_storage_glusterfs_block_deploy=true
openshift_storage_glusterfs_block_host_vol_create=true
openshift_storage_glusterfs_block_host_vol_size=100
openshift_storage_glusterfs_block_storageclass=true
openshift_storage_glusterfs_block_storageclass_default=false
openshift_storage_glusterfs_is_native=false
openshift_storage_glusterfs_heketi_is_native=true
openshift_storage_glusterfs_heketi_executor=ssh
openshift_storage_glusterfs_heketi_ssh_port=22
openshift_storage_glusterfs_heketi_ssh_user=root
openshift_storage_glusterfs_heketi_ssh_sudo=false
openshift_storage_glusterfs_heketi_ssh_keyfile="/root/.ssh/id_rsa"
`
This give ability to heketi to comunicate with nodes etc.

second section is where you define nodes on which glusterfs will be placed:

`[glusterfs]
server1 glusterfs_ip=10.0.3.86  glusterfs_devices='["/dev/sdc"]'
server2 glusterfs_ip=10.0.3.87  glusterfs_devices='["/dev/sdc"]'
server3 glusterfs_ip=10.0.3.88  glusterfs_devices='["/dev/sdc"]'
`

After some research i discover something. In second section when i dont add  glusterfs_ip section with server IP's on install you will get erors. And rememeber to dont forget in this section about marks ' " ]  
Several days ago i miis one ' and always get error during install.

**Comment by jjman4** [comment]
Hi,

When putting glusterfs_ip, seems error still remain.
Any advice?

fatal: [master]: FAILED! => {"changed": true, "cmd": ["oc", "--config=/tmp/openshift-glusterfs-ansible-2umlhH/admin.kubeconfig", "rsh", "--namespace=app-storage", "deploy-heketi-storage-1-nz4p6", "heketi-cli", "-s", "http://localhost:8080", "--user", "admin", "--secret", "sfpUFnlSP8pELVLOd01BXPmBIciskWYcHSUhQBxcLcc=", "topology", "load", "--json=/tmp/openshift-glusterfs-ansible-2umlhH/topology.json", "2>&1"], "delta": "0:00:03.808803", "end": "2019-05-14 13:53:43.842171", "failed_when_result": true, "rc": 0, "start": "2019-05-14 13:53:40.033368", "stderr": "", "stderr_lines": [], "stdout": "Creating cluster ... ID: 991e07e13ddcedc18637057398217130\n\tAllowing file volumes on cluster.\n\tAllowing block volumes on cluster.\n\tCreating node master ... ID: 60a0a377258e8782643b2e2a5d6784c6\n\t\tAdding device /dev/mapper/vg02-datavol ... Unable to add device: Setup of device /dev/mapper/vg02-datavol failed (already initialized or contains data?): setterm: $TERM is not defined.\n  Can't initialize physical volume \"/dev/mapper/vg02-datavol\" of volume group \"vg_701e9c06670ec3d7fe020095e665ab8e\" without -ff\n  /dev/mapper/vg02-datavol: physical volume not initialized.\n\tCreating node node1... ID: bf08f5c86d79720d616fa53441cd57bd\n\t\tAdding device /dev/mapper/vg02-datavol ... Unable to add device: Setup of device /dev/mapper/vg02-datavol failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain", "stdout_lines": ["Creating cluster ... ID: 991e07e13ddcedc18637057398217130", "\tAllowing file volumes on cluster.", "\tAllowing block volumes on cluster.", "\tCreating node master ... ID: 60a0a377258e8782643b2e2a5d6784c6", "\t\tAdding device /dev/mapper/vg02-datavol ... Unable to add device: Setup of device /dev/mapper/vg02-datavol failed (already initialized or contains data?): setterm: $TERM is not defined.", "  Can't initialize physical volume \"/dev/mapper/vg02-datavol\" of volume group \"vg_701e9c06670ec3d7fe020095e665ab8e\" without -ff", "  /dev/mapper/vg02-datavol: physical volume not initialized.", "\tCreating node node1 ... ID: bf08f5c86d79720d616fa53441cd57bd", "\t\tAdding device /dev/mapper/vg02-datavol ... Unable to add device: Setup of device /dev/mapper/vg02-datavol failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain"]}


$ systemctl status glusterd
● glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-05-03 15:37:18 EAT; 1 weeks 3 days ago
     Docs: man:glusterd(8)
  Process: 26308 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 26309 (glusterd)
   Memory: 13.5M
   CGroup: /system.slice/glusterd.service
           └─26309 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO

May 03 15:37:18 master systemd[1]: Starting GlusterFS, a clustered file-system server...
May 03 15:37:18 master systemd[1]: Started GlusterFS, a clustered file-system server.

**Comment by ZrytyADHD** [comment]
First give me inventory file please because this error appears to syntax error.
I also give you advaice. When i create glusterfs cluster i always use raw block device .

**Comment by jjman4** [comment]
Hi @ZrytyADHD 

see below my inventory file.

$ cat /etc/ansible/hosts
# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd
glusterfs

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become=true

openshift_deployment_type=origin
openshift_disable_check="docker_image_availability"
os_firewall_use_firewalld=True

#GlusterFS
openshift_storage_glusterfs_namespace=app-storage
openshift_storage_glusterfs_storageclass=true
openshift_storage_glusterfs_storageclass_default=false
openshift_storage_glusterfs_block_deploy=true
openshift_storage_glusterfs_block_host_vol_size=100
openshift_storage_glusterfs_block_storageclass=true
openshift_storage_glusterfs_block_storageclass_default=false
openshift_storage_glusterfs_is_native=false
#openshift_storage_glusterfs_heketi_executor=ssh
#openshift_storage_glusterfs_heketi_ssh_port=22
#openshift_storage_glusterfs_heketi_ssh_user=root
#openshift_storage_glusterfs_heketi_ssh_sudo=false
#openshift_storage_glusterfs_heketi_ssh_keyfile="/root/.ssh/id_rsa"
openshift_storage_glusterfs_storageclass=true
openshift_storage_glusterfs_storageclass_default=false
openshift_storage_glusterfs_block_deploy=true
openshift_storage_glusterfs_block_host_vol_create=true
openshift_storage_glusterfs_block_host_vol_size=100
openshift_storage_glusterfs_block_storageclass=true
openshift_storage_glusterfs_block_storageclass_default=false
openshift_storage_glusterfs_is_native=false
openshift_storage_glusterfs_heketi_is_native=true
openshift_storage_glusterfs_heketi_executor=ssh
openshift_storage_glusterfs_heketi_ssh_port=22
openshift_storage_glusterfs_heketi_ssh_user=root
openshift_storage_glusterfs_heketi_ssh_sudo=false
openshift_storage_glusterfs_heketi_ssh_keyfile="/root/.ssh/id_rsa"


[glusterfs]
master glusterfs_ip=192.168.8.83 glusterfs_devices='["/dev/mapper/vg02-datavol"]'
node1  glusterfs_ip=192.168.8.84 glusterfs_devices='["/dev/mapper/vg02-datavol"]'

# host group for masters
[masters]
master

# host group for etcd
[etcd]
master

# host group for nodes, includes region info
[nodes]
master openshift_node_group_name='node-config-master-infra'
node1 openshift_node_group_name='node-config-compute'

**Comment by ZrytyADHD** [comment]
Hmm everything looks fine in inventory. 
I have a nother idea this is my config for gluster if you can try to use raw block device such as I do :

server1 glusterfs_ip=10.0.3.71  glusterfs_devices='["/dev/sdc"]'
server2 glusterfs_ip=10.0.3.72  glusterfs_devices='["/dev/sdc"]'
server3 glusterfs_ip=10.0.3.73  glusterfs_devices='["/dev/sdc"]'
