### ISSUE TITLE
OKD 3.11: Redeploy cluster or master certificates cause prometheus/grafana TLS broken

### ISSUE THREAD

**Issue by jerryhan77** [openshift/openshift-ansible#11555]
#### Description

In order to redeploy LE issued named certificates, I have try to use playbooks/redeploy-certificates.yml or playbooks/openshift-master/redeploy-certificates.yml to redeploy cluster or master certificates.

After certificates successful redeployed. I found the prometheus and grafana web ui can not been access anymore.

The redeploy playbook changed the openshift-service-serving-signer has been changed.
That cause prometheus and grafana certificates invalid。

Reinstall openshift-monitoring can fix the issue.

How to fix the problem.

##### Version

```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

openshift-ansible:  openshift-ansible-3.11.103-1-30-g8a57696

**Comment by vrutkovs** [comment]
Fixed by https://github.com/openshift/openshift-ansible/pull/11472, available in openshift-ansible-3.11.104-1
