### ISSUE TITLE
Pod-to-service networking not working on fresh OKD 3.11 install

### ISSUE THREAD

**Issue by woopla** [openshift/openshift-ansible#11561]
#### Description

I've installed on a set of CentOS 7 VMs using the Ansible playbooks, and the network setup appears to be incomplete. `oc adm diagnostics NetworkCheck` reports that the pod-to-service connection fails with a `no route to host`.

##### Version

```
> ansible --version
ansible 2.6.2

> git describe
openshift-ansible-3.11.110-1-12-g67cc5965f

```

##### Steps To Reproduce
1. Run the Ansible-based install
2. Run `oc adm diagnostics NetworkCheck`

##### Expected Results
No error should be displayed

##### Observed Results

```
       ERROR: [DSvcNet1010 from diagnostic CheckServiceNetwork@openshift/origin/pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/service.go:193]
              Connectivity from pod "network-diag-global-ns-tmlsj/network-diag-test-pod-dtg9x" to service "app-storage/heketi-db-storage-endpoints" failed. Error: exit status 1, Out: bash: connect: No route to host
              bash: /dev/tcp/172.40.206.171/1: No route to host

```

##### Additional Information

Operating system and version, `CentOS Linux release 7.5.1804 (Core) `

I've had to modify the service network IP range, as the default conflicts with our VPN tunnels. I;m also using the multitenant OVS plugin, since we expect different groups to use this. Finally, I tried setting the proxy to userspace mode and reinstall, no dice. Here are the relevant parts of the inventory:
```
openshift_portal_net=172.40.0.0/16
os_sdn_network_plugin_name=redhat/openshift-ovs-multitenant
openshift_node_proxy_mode=userspace
```

Thanks,

Clément

**Comment by woopla** [comment]
I'm spending more time than I'd like debugging this by the way :) There are many moving parts to Openshift, so figuring out what is going on is complicated. I tried a local `minishift` install to compare, but it doesn't use the SDN so there are no comparison points that I can look at.

I'm open to suggestion as to how debugging where the problem is coming from. I looked at the [OKD doc on troubleshooting](https://docs.okd.io/3.11/admin_guide/sdn_troubleshooting.html#debugging-local-networking). While it provides tools to better isolate the problem, there are no pointers as to what could cause it.

**Comment by ZrytyADHD** [comment]
Try to delete ipfailover pod and change the version of image if you use it

**Comment by woopla** [comment]
@ZrytyADHD I do not have ipfailover pods in any namespace. The `openshift-sdn` namespace has `ovs` and `sync` pods, one per node.

**Comment by cutty853** [comment]
exact same problem here

**Comment by jnach** [comment]
Following
