### ISSUE TITLE
Openshift install fails at "FAILED - RETRYING: Wait for the sync daemonset to become ready and available"

### ISSUE THREAD

**Issue by patrickhargett** [openshift/openshift-ansible#11569]
#### Description

Provide a brief description of your issue here. For example:

When installing openshift 3.11, the "deploy_cluster" playbook fails with the following error:

FAILED - RETRYING: Wait for the sync daemonset to become ready and available

Retries continue until the deployment eventually fails

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
* The output of `git describe`

If you're running from playbooks installed via RPM

Place the output between the code block below:

```
Ansible: 2.6.0
Openshift: release-3.11
```

##### Steps To Reproduce
1. Download ansible version 2.6. Clone openshift-ansible, and checkout release 3.11
2. Complete the "prerequisites" and "deploy_cluster" playbooks
3. Run the deploy_cluster playbook.

##### Expected Results
Playbook completes, and cluster is deployed.

##### Observed Results
Describe what is actually happening.

Playbook times out on:
FAILED - RETRYING: Wait for the sync daemonset to become ready and available

Worker nodes are not in a ready state:
NAME                           STATUS     ROLES                  AGE       VERSION
ip-10-0-103-4.ec2.internal     NotReady   <none>                 2h        v1.11.0+d4cacc0
ip-10-0-166-240.ec2.internal   Ready      compute,infra,master   2h        v1.11.0+d4cacc0
ip-10-0-231-15.ec2.internal    NotReady   <none>                 2h        v1.11.0+d4cacc0

Some pods stuck in containercreating:
[centos@ip-10-0-166-240 ~]$ oc get pods --all-namespaces
NAMESPACE        NAME                                              READY     STATUS              RESTARTS   AGE
kube-system      master-api-ip-10-0-166-240.ec2.internal           1/1       Running             0          2h
kube-system      master-controllers-ip-10-0-166-240.ec2.internal   1/1       Running             0          2h
kube-system      master-etcd-ip-10-0-166-240.ec2.internal          1/1       Running             0          2h
openshift-node   sync-7298r                                        0/1       ContainerCreating   0          40m
openshift-node   sync-crzfl                                        0/1       ContainerCreating   0          40m
openshift-node   sync-mdrbq                                        1/1       Running             0          2h
openshift-sdn    ovs-4fqfh                                         1/1       Running             0          2h
openshift-sdn    ovs-6qpgc                                         0/1       ContainerCreating   0          2h
openshift-sdn    ovs-hf8r2                                         0/1       ContainerCreating   0          2h
openshift-sdn    sdn-kglhf                                         1/1       Running             0          2h
openshift-sdn    sdn-nl8ps                                         0/1       ContainerCreating   0          2h
openshift-sdn    sdn-s89qq                                         0/1       ContainerCreating   0          2h

##### Additional Information

I originally suspected bug https://bugzilla.redhat.com/show_bug.cgi?id=1633892, but not able to confirm.

I am deploying openshift on a 3 node cluster, on AWS. Master and worker nodes are on t2.2xlarge instances.

**Comment by vrutkovs** [comment]
Run `oc describe pod/sync-7298r -n openshift-node` (and others pods stuck in `ContainerCreating`). This would show the reason why these pods can't run

**Comment by patrickhargett** [comment]
I see the following for each pod that is in ContainerCreating state:

Events:
  Type     Reason                  Age                    From                                  Message
  ----     ------                  ----                   ----                                  -------
  Warning  FailedCreatePodSandBox  32m (x43053 over 15h)  kubelet, ip-10-0-231-15.ec2.internal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "sdn-s89qq": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"Cannot set property TasksAccounting, or unknown property.\""
  Normal   SandboxChanged          2m (x44851 over 15h)   kubelet, ip-10-0-231-15.ec2.internal  Pod sandbox changed, it will be killed and re-created.

**Comment by vrutkovs** [comment]
That seems to be a race condition in runc - see https://bugzilla.redhat.com/show_bug.cgi?id=1508040
