### ISSUE TITLE
OCP 3.11 with cri-o failed

### ISSUE THREAD

**Issue by niso120b** [openshift/openshift-ansible#11587]
We tried to install openshift with crio by the openshift ansible with crio guide https://docs.openshift.com/container-platform/3.11/crio/crio_runtime.html

We using 
![MicrosoftTeams-image(2)](https://user-images.githubusercontent.com/12515467/57288596-71663200-70c2-11e9-9a95-219b68e84745.png)
![MicrosoftTeams-image(1)](https://user-images.githubusercontent.com/12515467/57288597-71663200-70c2-11e9-9dcd-789e75e213cb.png)

and the installation sucess but the container runtime its still docker:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/12515467/57288640-88a51f80-70c2-11e9-8757-5d3d90f2ce7c.png)

**Comment by vrutkovs** [comment]
Please attach playbook logs (with `-vvv`) and origin-node service logs

**Comment by niso120b** [comment]
@vrutkovs 

Logs:
[prerequisites.log](https://github.com/openshift/openshift-ansible/files/3152461/prerequisites.log)

[deploy_cluster.log](https://github.com/openshift/openshift-ansible/files/3152460/deploy_cluster.log)

**Comment by vrutkovs** [comment]
openshift-ansible logs looks correct to me, what's in `origin-node` service logs on nodes?

**Comment by rodrigc** [comment]
@niso120b I ran into similar problems trying to get CRI-O working: https://github.com/openshift/openshift-ansible/issues/11693

With those same steps I got a working Openshift 3.11 cluster with CRI-O working at the beginning of May, but looks like something has changed recently so now those steps don't work for me.

**Comment by rodrigc** [comment]
@nisio120b Things now work for me with a newer version of openshift-ansible: https://github.com/openshift/openshift-ansible/issues/11693#issuecomment-516003920
