### ISSUE TITLE
oc get pod fails to reach server, but replicating curl command works on master and inside all docker images

### ISSUE THREAD

**Issue by blamoman** [openshift/openshift-ansible#11619]
On a minimal (1 master, 2 nodes) setup on EC2 behind a proxy, when installing via ansible scripts, during deploy_cluster, I get to 'Wait for control plane pods to appear', which fails (repeatedly). 

After exiting the script, the docker images are running and the api is up (hitting port 8443 with curl gets a number of sensible looking results). Doing 'oc get pod' tells me it failed to connect to the server, doing 'oc get pod --loglevel 10' shows me various curl requests it is making, if I make these curl requests on the host or inside any of the running docker instances the curl goes through. 

An strace showed that 'oc get pod' reads the hostname, so after changing the hostname to be just the ip address of the machine, strace shows that the hostname (ip) is read, but the curls still get addressed towards the full *.compute.internal.

Ansible version - 2.6.9
Openshift version -3.11
Docker version - 1.13.1

**Comment by vrutkovs** [comment]
Please collect master logs: https://docs.okd.io/3.11/install_config/master_node_configuration.html#master-node-view-logs
