### ISSUE TITLE
Error during installation 3.9 version.

### ISSUE THREAD

**Issue by gvv90** [openshift/openshift-ansible#11628]
#### Description

Provide a brief description of your issue here. For example:

During installation, on "openshift_ca" task, I'm having the following error:

TASK [openshift_ca : command] *****************************************************************************************************************************************************************************************************************
Thursday 23 May 2019  00:22:54 -0500 (0:00:00.044)       0:00:39.043 ********** 
changed: [master1.oshi39]
ERROR! template error while templating string: no filter named 'lib_utils_oo_collect'. String: {{ g_master_legacy_ca_result.files | default([]) | lib_utils_oo_collect('path') }}

##### Version

* Your ansible version per `ansible --version`
ansible 2.8.0
  config file = /home/gvillavicencio/Ansible_OpenshifOrigin/openshift-ansible/ansible.cfg
  configured module search path = ['/home/gvillavicencio/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 13:36:35) [GCC 9.0.1 20190227 (Red Hat 9.0.1-0.8)]

If you're operating from a **git clone**:

* The output of `git describe`
openshift-ansible-3.9.81-1-4-g2979210ee

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. ansible-playbook -i openshift_inventory playbooks/deploy_cluster.yml

##### Expected Results
Installation succesfull.

```
Example command and output or error messages
```

##### Observed Results
It couldn't install succesfully Openshift Origin 3.9

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
[root@infra1 ~]# cat /etc/*release*
CentOS Linux release 7.6.1810 (Core) 
Derived from Red Hat Enterprise Linux 7.6 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.6.1810 (Core) 
CentOS Linux release 7.6.1810 (Core) 
cpe:/o:centos:centos:7

* Your inventory file (especially any non-standard configuration parameters)
[OSEv3:children]
masters
etcd
nodes

[OSEv3:vars]
## Ansible user who can login to all nodes through SSH (e.g. ssh root@master1)
ansible_user=root

## Deployment type: "openshift-enterprise" or "origin"
openshift_deployment_type=origin
deployment_type=origin

## Specifies the major version
openshift_release=v3.9
openshift_pkg_version=-3.9.0
openshift_image_tag=v3.9.0
openshift_service_catalog_image_version=v3.9.0
template_service_broker_image_version=v3.9.0
openshift_metrics_image_version="v3.9"
openshift_logging_image_version="v3.9"
openshift_logging_elasticsearch_proxy_image_version="v1.0.0"
osm_use_cockpit=true
openshift_metrics_install_metrics=True
openshift_logging_install_logging=True

## Service address space,  /16 = 65,534 IPs
openshift_portal_net=172.30.0.0/16

## Pod address space
osm_cluster_network_cidr=10.128.0.0/14

## Subnet Length of each node, 9 = 510 IPs
osm_host_subnet_length=9

## Master API  port
openshift_master_api_port=443

## Master console port  (e.g. https://console.openshift.local:443)
openshift_master_console_port=443

## Clustering method
openshift_master_cluster_method=native

## Hostname used by nodes and other cluster internals
openshift_master_cluster_hostname=console-int.openshift.local

## Hostname used by platform users
openshift_master_cluster_public_hostname=console.openshift.local

## Application wildcard subdomain
openshift_master_default_subdomain=apps.openshift.local

## identity provider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

## Users being created in the cluster
openshift_master_htpasswd_users={'admin': '$apr1$Y7xqqalc$Mhtfi2EH5cwY6bLaFJWfm0', 'user1': '$apr1$HYdB7Vye$J9GFboUG/TIG3IYl0c4LV0'}

## Persistent storage, NFS
openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_host=zion.local
openshift_hosted_registry_storage_nfs_directory=/volume1/SHARED
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=50Gi

## Other vars
containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

#NFS check bug
openshift_enable_unsupported_configurations=True
#Another Bug 1569476 
skip_sanity_checks=true

openshift_node_kubelet_args="{'eviction-hard': ['memory.available<100Mi'], 'minimum-container-ttl-duration': ['10s'], 'maximum-dead-containers-per-container': ['2'], 'maximum-dead-containers': ['5'], 'pods-per-core': ['10'], 'max-pods': ['25'], 'image-gc-high-threshold': ['80'], 'image-gc-low-threshold': ['60']}"

[OSEv3:vars]

[masters]
master1.oshi39:2204

[etcd]
master1.oshi39:2204

[nodes]
master1.oshi39:2204 openshift_node_labels="{'region': 'master'}"
infra1.oshi39:2205 openshift_node_labels="{'region': 'infra'}"
node1.oshi39:2206 openshift_node_labels="{'region': 'primary'}"
node2.oshi39:2207 openshift_node_labels="{'region': 'primary'}"

* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by cmoulliard** [comment]
I'm also getting the same error using tag `v3.11.0`

```
TASK [openshift_ca : Create the master certificates if they do not already exist] ************************************************************************************************************************************************************
skipping: [10.0.76.177]

TASK [openshift_ca : command] ****************************************************************************************************************************************************************************************************************
changed: [10.0.76.177]
ERROR! template error while templating string: no filter named 'lib_utils_oo_collect'. String: {{ g_master_legacy_ca_result.files | default([]) | lib_utils_oo_collect('path') }}
```

**Comment by ghyde** [comment]
@gvv90 Your version of Ansible (2.8) is too new. OpenShift 3.9 requires Ansible 2.4 ([ref](https://docs.openshift.com/container-platform/3.9/install_config/install/host_preparation.html#host-registration)).

@cmoulliard OpenShift 3.11 requires Ansible 2.6 ([ref](https://docs.openshift.com/container-platform/3.11/install/host_preparation.html#host-registration)).

**Comment by nccurry** [comment]
I encountered this problem and it was caused by using an ansible version incompatible with the release version of openshift-ansible.

In the case of release-3.11 I was using ansible 2.8 instead of 2.6.

Try using the ansible version corresponding to your openshift-ansible release version.

**Comment by mtnbikenc** [comment]
Ansible 2.8+ will not be supported on versions of openshift-ansible below 3.11.
PR to support Ansible 2.8.1 on openshift-ansible release-3.11: https://github.com/openshift/openshift-ansible/pull/11325
