### ISSUE TITLE
Need openshift_ip "deprecated" variable

### ISSUE THREAD

**Issue by hector-vido** [openshift/openshift-ansible#11637]
#### Description

openshift_ip variable was removed from 3.11 documentation but is the only way to set **etcd** default interface.

##### Version

```
ansible 2.5.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

```
openshift-ansible-3.11.115-1-26-gb669651
```

##### Steps To Reproduce
1. Follow the default install instructions but install **ansible** 2.5.7.

##### Expected Results

etcd will be bounded to the first available interface.

##### Extra Information

The variable was removed from playbooks/init/cluster_facts.yml on the commit 9da0db77b8c250f47c4f877096d967caaa3acfe6.

This is useful to install on tests environments like Vagrant and Virtualbox, with a default NAT interface.

**Comment by vrutkovs** [comment]
`etcd_ip` is used to set etcd default interface, it is still in effect afaik

**Comment by hector-vido** [comment]
Thanks! O never found this on docs. I'll test.
