### ISSUE TITLE
Allow to not specify ca file for openid

### ISSUE THREAD

**Issue by alonikomax** [openshift/openshift-ansible#11643]
#### Description

Apparently commit no ceac075 changed the openid options to always include the ca option.
I'm in an environment where I can't add a correct file for this CA but the hosts themselves trust the provider. After deleting this option, the OpenID configuration works perfectly.

##### Version

```
openshift-ansible-3.11.98-1.git.0.3cfa7c3.el7.noarch
```

##### Steps To Reproduce
1. Add configuration for OpenID provider
2. CA file does not exist
3. Manually delete the ca option from the master configuration file
4. Profit

##### Expected Results
Have an option to decide if to have a ca file
```
openshift_master_openid_ca: false
```

##### Observed Results
No option

**Comment by vrutkovs** [comment]
>I'm in an environment where I can't add a correct file for this CA but the hosts themselves trust the provider

API servers run in a container, they need to either mount host's CA - which conflict with apiserver's CA bundle

**Comment by alonikomax** [comment]
But it's working fine when I delete this option. The host itself trusts the provider and it all works

**Comment by vrutkovs** [comment]
That happens since openID CA is already included in a standard CA bundle, included in base container of the apiserver. I don't think it has something to do with host CAs.

Removing this option would break installs which use custom CAs

**Comment by alonikomax** [comment]
Ok, it is in the bundle. But why can't I have a parameter like suggested to
remove the ca option? It should be a boolean and not something forced.

**Comment by maverick85** [comment]
Hi @alonikomax actually I just saw this post when browsing issues.

I know what you're talking about, happens with LDAP as well. I have a public trusted certificate so I don't need to manually add certificates. I have thought of a possible solution but don't know if it will work, adding
```
openshift_master_ldap_ca_file=''
```
in my case for ldap, must be a similar option , and just put ' ' so it will be empty.
In LDAP's case it add's ca: providername_ldap_ca.crt as some expected default value.

**Comment by duritong** [comment]
This completely breaks installation of openid with AzureAD where there is no CA file to include

**Comment by TimAplin** [comment]
For OpenID providers that use a public trusted certificate you can add this to your inventory to mitigate this issue (I've used this successfully with AzureAD):
`openshift_master_openid_ca_file='/etc/ssl/certs/ca-bundle.crt'`

Ensure ca-bundle.crt exists at this location on your ansible deployment host.  This will create an extra unnecessary item in master-config.yml but it wont have any impact.
