### ISSUE TITLE
openshift origin 3.11 offline installation fails

### ISSUE THREAD

**Issue by normanschlatter** [openshift/openshift-ansible#11645]
#### Description

Im trying to install openshift 3.11 on a 5 node cluster without access to the internet.
I created a local docker registry and a local centos-openshift-origin311 repo and made it available to all nodes, works fine.

The Problem:

Ansible Playbook adds on every node: /etc/yum.repos.d/CentOS-OpenShift-Origin311.repo
which is a big Problem since I wanna use my local repo.

Is there some special flag to bypass the creation of the online repo?

**Comment by kngharv** [comment]
Why you closed the issue?  how do you managed to install openshift offline?
