### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by fidelina** [openshift/openshift-ansible#11640]
I trying to install OpenShift v3.11 after uninstall falled cluster OpenShift

1)  runned ansible playbook /openshift-ansible/playbooks/adhoc/uninstall.yml 
2) pruned all containers and reinstall docker :
```
docker rmi -f $(docker images -aq)
docker rm -vf $(docker ps -aq)
docker volume prune -f
```
Version:
```
cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

```
```
git branch
  master
* release-3.11
```
```
ansible --version
ansible 2.7.1
  config file = /home/op/install-openshift/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
```
[root@gasu-development lib]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Wed May  1 14:55:20 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Wed May  1 14:55:20 2019
 OS/Arch:         linux/amd64
 Experimental:    false
[root@gasu-development lib]#
```
openshift-ansible/inventory/hosts
```
#bare minimum hostfile

[OSEv3:children]
masters
nodes
etcd
#glusterfs

[OSEv3:vars]
openshift_release="v3.11"
openshift_version="3.11"
#openshift_kubelet_name_override="{{ ansible_default_ipv4.address }}"
# if your target hosts are Fedora uncomment this
#ansible_python_interpreter=/usr/bin/python3
openshift_deployment_type=origin
openshift_portal_net=172.30.0.0/16
openshift_master_default_subdomain=gasu-development.ibs.ru
# localhost likely doesn't meet the minimum requirements
#openshift_disable_check=disk_availability,memory_availability

openshift_node_groups=[{'name': 'node-config-all-in-one', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]

openshift_hosted_router_replicas=1
openshift_hosted_registry_replicas=1

openshift_router_selector='region=infra'
openshift_registry_selector='region=infra'
#openshift_router_selector='region=primary'
#openshift_registry_selector='region=primary'

#######

[masters]
localhost ansible_connection=local openshift_public_hostname="gasu-development.ibs.ru" # openshift_hostname="{{ ansible_default_ipv4.address }}"

[etcd]
localhost ansible_connection=local

[nodes]
# openshift_node_group_name should refer to a dictionary with matching key of name in list openshift_node_groups.
localhost ansible_connection=local openshift_node_group_name="node-config-all-in-one"
#openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
#openshift_node_labels="{'region': 'primary', 'zone': 'default'}" openshift_schedulable=true

```

Now I have trable with playbooks/openshift-master/config.yml
```
Using module file /home/op/install-openshift/openshift-ansible/roles/lib_openshift/library/oc_obj.py
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
FAILED - RETRYING: Wait for control plane pods to appear (53 retries left).Result was: {
    "attempts": 8,
    "changed": false,
    "invocation": {
        "module_args": {
            "all_namespaces": null,
            "content": null,
            "debug": false,
            "delete_after": false,
            "field_selector": null,
            "files": null,
            "force": false,
            "kind": "pod",
            "kubeconfig": "/etc/origin/master/admin.kubeconfig",
            "name": "master-etcd-gasu-development.ibs.ru",
            "namespace": "kube-system",
            "selector": null,
            "state": "list"
        }
    },
    "msg": {
        "cmd": "/bin/oc get pod master-etcd-gasu-development.ibs.ru -o json -n kube-system",
        "results": [
            {}
        ],
        "returncode": 1,
        "stderr": "Unable to connect to the server: x509: certificate signed by unknown authority\n",
        "stdout": ""
    },
    "retries": 61
}
```

 journalctl -flu docker.service

```
May 26 10:05:02 gasu-development.ibs.ru oci-umount[14577]: umounthook <debug>: prestart container_id:7e34ab0dc6d8 rootfs:/var/lib/docker/overlay2/22d7032c6e1030d3850c6f7a0a2433b4d6b195678063739b0459101135e128d2/merged
May 26 10:05:02 gasu-development.ibs.ru oci-systemd-hook[14584]: systemdhook <debug>: 25b06f0c1c1a: Skipping as container command is /bin/bash, not init or systemd
May 26 10:05:02 gasu-development.ibs.ru oci-umount[14586]: umounthook <debug>: prestart container_id:25b06f0c1c1a rootfs:/var/lib/docker/overlay2/d23762d311c30c9d998b052b60edc9f4b16aadfae2a99cffb02ecf2c15b8b346/merged
May 26 10:05:02 gasu-development.ibs.ru oci-systemd-hook[14708]: systemdhook <debug>: 25b06f0c1c1a: Skipping as container command is /bin/bash, not init or systemd
May 26 10:05:02 gasu-development.ibs.ru oci-systemd-hook[14721]: systemdhook <debug>: 7e34ab0dc6d8: Skipping as container command is /bin/bash, not init or systemd
May 26 10:05:02 gasu-development.ibs.ru dockerd-current[6335]: time="2019-05-26T10:05:02.595553333+03:00" level=warning msg="25b06f0c1c1ae53142cc52ff7d9fc9557206118fece3866dc648ff4e41afdd17 cleanup: failed to unmount secrets: invalid argument"
May 26 10:05:02 gasu-development.ibs.ru dockerd-current[6335]: time="2019-05-26T10:05:02.603383483+03:00" level=warning msg="7e34ab0dc6d817477489bf2fa8e269299d5f816e65481524235935988b628a7b cleanup: failed to unmount secrets: invalid argument"

```
```
[root@gasu-development lib]# docker images | grep 25b06f0c1c1a
[root@gasu-development lib]# docker ps | grep 25b06f0c1c1a
[root@gasu-development lib]# ll /var/lib/docker/overlay2/22d7032c6e1030d3850c6f7a0a2433b4d6b195678063739b0459101135e128d2/merged
ls: cannot access /var/lib/docker/overlay2/22d7032c6e1030d3850c6f7a0a2433b4d6b195678063739b0459101135e128d2/merged: No such file or directory

[root@gasu-development lib]# openssl verify -CAfile /etc/origin/master/ca.crt /etc/origin/master/master.server.crt
/etc/origin/master/master.server.crt: OK
[root@gasu-development lib]# openssl verify -CAfile /etc/origin/master/ca-bundle.crt /etc/origin/master/master.server.crt
/etc/origin/master/master.server.crt: OK
[root@gasu-development lib]# oc status
Unable to connect to the server: x509: certificate signed by unknown authority

[root@gasu-development lib]# grep certificate-authority-data /etc/origin/master/admin.kubeconfig | awk '{ print $2 }' | base64 -d | md5sum
fb130cd574c9f507636e09fac6f79b57  -
[root@gasu-development lib]# grep certificate-authority-data /root/.kube/config | awk '{ print $2 }' | base64 -d | md5sum
fb130cd574c9f507636e09fac6f79b57  -
[root@gasu-development lib]# md5sum /etc/origin/master/ca-bundle.crt
fb130cd574c9f507636e09fac6f79b57  /etc/origin/master/ca-bundle.crt
```
[root@gasu-development lib]# grep certificate-authority-data /etc/origin/master/admin.kubeconfig | awk '{ print $2 }' | base64 -d | openssl x509 -noout -text
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=openshift-signer@1558850775
        Validity
            Not Before: May 26 06:06:15 2019 GMT
            Not After : May 24 06:06:16 2024 GMT
        Subject: CN=openshift-signer@1558850775
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
             .....
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Certificate Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
   
[root@gasu-development lib]#
```

diff /root/.kube/config /etc/origin/master/admin.kubeconfig  - It files is simmular

openssl s_client -CAfile /etc/origin/master/ca-bundle.crt -connect oc-master.gasu-development.ibs.ru:8443 -I have connect

```
CONNECTED(00000003)
depth=1 CN = openshift-signer@1558813491
verify error:num=19:self signed certificate in certificate chain
---
Certificate chain
 0 s:/CN=172.29.227.50
   i:/CN=openshift-signer@1558813491
 1 s:/CN=openshift-signer@1558813491
   i:/CN=openshift-signer@1558813491
---
Server certificate
-----BEGIN CERTIFICATE-----
MIID+TCCAuGgAwIBAgIBBDANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
....
-----END CERTIFICATE-----
subject=/CN=172.29.227.50
issuer=/CN=openshift-signer@1558813491
---
Acceptable client certificate CA names
/CN=openshift-signer@1558813491
/CN=openshift-signer@1558813490
Client Certificate Types: RSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA512:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA512:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2496 bytes and written 427 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 6B01BE43137D49AB5FFA0FEFAC2D023263ABF48020FE0B4715FE1B7534673637
    Session-ID-ctx:
    Master-Key: 58151DEA754960682C9AFD865886986F9037F8385D63699552C69CB156DDFB2F386B86E0188F359B24D56B12AB23B4EA
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket:
    0000 - f1 98 d9 93 f2 f0 9f f3-22 b1 96 62 eb 60 49 40   ........"..b.`I@
 ....

    Start Time: 1558855188
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)

```
 oc status --config=/etc/origin/master/admin.kubeconfig
Unable to connect to the server: x509: certificate signed by unknown authority

openssl x509 -noout -issuer -in /etc/origin/master/ca.crt
issuer= /CN=openshift-signer@1558850775

oc get pv
Unable to connect to the server: x509: certificate signed by unknown authority

```
 docker ps
CONTAINER ID        IMAGE                                                                                         COMMAND                  CREATED             STATUS              PORTS               NAMES
1ce5d80e836a        quay.io/coreos/etcd@sha256:43fbc8a457aa0cb887da63d74a48659e13947cb74b96a53ba8f47abb6172a948   "/bin/sh -c '#!/bi..."   27 minutes ago      Up 27 minutes                           k8s_etcd_master-etcd-gasu-development.ibs.ru_kube-system_365913b03d626d43833aa80048591d33_0
380ed350bafd        docker.io/openshift/origin-pod:v3.11.0                                                        "/usr/bin/pod"           27 minutes ago      Up 27 minutes                           k8s_POD_master-etcd-gasu-development.ibs.ru_kube-system_365913b03d626d43833aa80048591d33_0
95c0f352aede        docker.io/openshift/origin-pod:v3.11.0                                                        "/usr/bin/pod"           27 minutes ago      Up 27 minutes                           k8s_POD_master-api-gasu-development.ibs.ru_kube-system_d400ab198a15ccbe597efa10e38d0719_0
1e106df65f12        docker.io/openshift/origin-pod:v3.11.0                                                        "/usr/bin/pod"           27 minutes ago      Up 27 minutes                           k8s_POD_master-controllers-gasu-development.ibs.ru_kube-system_04335d3709e8228377883a762ef7f830_0

```

**Comment by fidelina** [comment]
> I trying to install OpenShift v3.11 after uninstall falled cluster OpenShift
> 
> 1. runned ansible playbook /openshift-ansible/playbooks/adhoc/uninstall.yml
> 2. pruned all containers and reinstall docker :
> 
> ```
> docker rmi -f $(docker images -aq)
> docker rm -vf $(docker ps -aq)
> docker volume prune -f
> ```
> 
> Version:
> 
> cat /etc/redhat-release
> CentOS Linux release 7.6.1810 (Core)
> 
> git branch
> master
> 
> * release-3.11
> 
> ansible --version
> ansible 2.7.1
> config file = /home/op/install-openshift/openshift-ansible/ansible.cfg
> configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
> ansible python module location = /usr/lib/python2.7/site-packages/ansible
> executable location = /usr/bin/ansible
> python version = 2.7.5 (default, Apr 9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
> 
> [root@gasu-development lib]# docker version
> Client:
> Version: 1.13.1
> API version: 1.26
> Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
> Go version: go1.10.3
> Git commit: b2f74b2/1.13.1
> Built: Wed May 1 14:55:20 2019
> OS/Arch: linux/amd64
> 
> Server:
> Version: 1.13.1
> API version: 1.26 (minimum version 1.12)
> Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
> Go version: go1.10.3
> Git commit: b2f74b2/1.13.1
> Built: Wed May 1 14:55:20 2019
> OS/Arch: linux/amd64
> Experimental: false
> [root@gasu-development lib]#
> 
> openshift-ansible/inventory/hosts
> #bare minimum hostfile
> 
> [OSEv3:children]
> masters
> nodes
> etcd
> #glusterfs
> 
> [OSEv3:vars]
> openshift_release="v3.11"
> openshift_version="3.11"
> #openshift_kubelet_name_override="{{ ansible_default_ipv4.address }}"
> 
> # if your target hosts are Fedora uncomment this
> #ansible_python_interpreter=/usr/bin/python3
> openshift_deployment_type=origin
> openshift_portal_net=172.30.0.0/16
> openshift_master_default_subdomain=gasu-development.ibs.ru
> 
> # localhost likely doesn't meet the minimum requirements
> #openshift_disable_check=disk_availability,memory_availability
> 
> #openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
> #openshift_master_htpasswd_users={'op': '$2y$05$QDLxdPMDiDP2SSM8c8TkheAWwhuXkTgLPuwoz.vW3U151qfshxrKC', 'developer': '$2y$05$lBfXlp8NIJiQCI6f6xpTK.g2zYldt3vwHOQQFTCcRSVHh5n1veuee'}
> 
> openshift_node_groups=[{'name': 'node-config-all-in-one', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]
> 
> openshift_hosted_router_replicas=1
> openshift_hosted_registry_replicas=1
> 
> openshift_router_selector='region=infra'
> openshift_registry_selector='region=infra'
> #openshift_router_selector='region=primary'
> #openshift_registry_selector='region=primary'
> 
> #######
> 
> [masters]
> localhost ansible_connection=local openshift_public_hostname="gasu-development.ibs.ru" # openshift_hostname="{{ ansible_default_ipv4.address }}"
> 
> [etcd]
> localhost ansible_connection=local
> 
> [nodes]
> 
> # openshift_node_group_name should refer to a dictionary with matching key of name in list openshift_node_groups.
> localhost ansible_connection=local openshift_node_group_name="node-config-all-in-one"
> #openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
> #openshift_node_labels="{'region': 'primary', 'zone': 'default'}" openshift_schedulable=true
> 
> Now I have trable with playbooks/openshift-master/config.yml
> :
> Using module file /home/op/install-openshift/openshift-ansible/roles/lib_openshift/library/oc_obj.py
> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
> FAILED - RETRYING: Wait for control plane pods to appear (53 retries left).Result was: {
> "attempts": 8,
> "changed": false,
> "invocation": {
> "module_args": {
> "all_namespaces": null,
> "content": null,
> "debug": false,
> "delete_after": false,
> "field_selector": null,
> "files": null,
> "force": false,
> "kind": "pod",
> "kubeconfig": "/etc/origin/master/admin.kubeconfig",
> "name": "master-etcd-gasu-development.ibs.ru",
> "namespace": "kube-system",
> "selector": null,
> "state": "list"
> }
> },
> "msg": {
> "cmd": "/bin/oc get pod master-etcd-gasu-development.ibs.ru -o json -n kube-system",
> "results": [
> {}
> ],
> "returncode": 1,
> "stderr": "Unable to connect to the server: x509: certificate signed by unknown authority\n",
> "stdout": ""
> },
> "retries": 61
> }
> 
> journalctl -flu docker.service
> 
> May 26 10:05:02 gasu-development.ibs.ru oci-umount[14577]: umounthook : prestart container_id:7e34ab0dc6d8 rootfs:/var/lib/docker/overlay2/22d7032c6e1030d3850c6f7a0a2433b4d6b195678063739b0459101135e128d2/merged
> May 26 10:05:02 gasu-development.ibs.ru oci-systemd-hook[14584]: systemdhook : 25b06f0c1c1a: Skipping as container command is /bin/bash, not init or systemd
> May 26 10:05:02 gasu-development.ibs.ru oci-umount[14586]: umounthook : prestart container_id:25b06f0c1c1a rootfs:/var/lib/docker/overlay2/d23762d311c30c9d998b052b60edc9f4b16aadfae2a99cffb02ecf2c15b8b346/merged
> May 26 10:05:02 gasu-development.ibs.ru oci-systemd-hook[14708]: systemdhook : 25b06f0c1c1a: Skipping as container command is /bin/bash, not init or systemd
> May 26 10:05:02 gasu-development.ibs.ru oci-systemd-hook[14721]: systemdhook : 7e34ab0dc6d8: Skipping as container command is /bin/bash, not init or systemd
> May 26 10:05:02 gasu-development.ibs.ru dockerd-current[6335]: time="2019-05-26T10:05:02.595553333+03:00" level=warning msg="25b06f0c1c1ae53142cc52ff7d9fc9557206118fece3866dc648ff4e41afdd17 cleanup: failed to unmount secrets: invalid argument"
> May 26 10:05:02 gasu-development.ibs.ru dockerd-current[6335]: time="2019-05-26T10:05:02.603383483+03:00" level=warning msg="7e34ab0dc6d817477489bf2fa8e269299d5f816e65481524235935988b628a7b cleanup: failed to unmount secrets: invalid argument"
> 
> May 26 10:05:23 gasu-development.ibs.ru oci-umount[15142]: umounthook : prestart container_id:d241c12df8fa rootfs:/var/lib/docker/overlay2/bccc0471fa2e89f127102dc43482bdeff151586f3676e6e27d39500fa4b9f700/merged
> ^C
> [root@gasu-development lib]# docker images | grep 25b06f0c1c1a
> [root@gasu-development lib]# docker ps | grep 25b06f0c1c1a
> [root@gasu-development lib]# ll /var/lib/docker/overlay2/22d7032c6e1030d3850c6f7a0a2433b4d6b195678063739b0459101135e128d2/merged
> ls: cannot access /var/lib/docker/overlay2/22d7032c6e1030d3850c6f7a0a2433b4d6b195678063739b0459101135e128d2/merged: No such file or directory
> 
> [root@gasu-development lib]# openssl verify -CAfile /etc/origin/master/ca.crt /etc/origin/master/master.server.crt
> /etc/origin/master/master.server.crt: OK
> [root@gasu-development lib]# openssl verify -CAfile /etc/origin/master/ca-bundle.crt /etc/origin/master/master.server.crt
> /etc/origin/master/master.server.crt: OK
> [root@gasu-development lib]# oc status
> Unable to connect to the server: x509: certificate signed by unknown authority
> 
> [root@gasu-development lib]# grep certificate-authority-data /etc/origin/master/admin.kubeconfig | awk '{ print $2 }' | base64 -d | md5sum
> fb130cd574c9f507636e09fac6f79b57 -
> [root@gasu-development lib]# grep certificate-authority-data /root/.kube/config | awk '{ print $2 }' | base64 -d | md5sum
> fb130cd574c9f507636e09fac6f79b57 -
> [root@gasu-development lib]# md5sum /etc/origin/master/ca-bundle.crt
> fb130cd574c9f507636e09fac6f79b57 /etc/origin/master/ca-bundle.crt
> [root@gasu-development lib]# grep certificate-authority-data /etc/origin/master/admin.kubeconfig | awk '{ print $2 }' | base64 -d | openssl x509 -noout -text
> Certificate:
> Data:
> Version: 3 (0x2)
> Serial Number: 1 (0x1)
> Signature Algorithm: sha256WithRSAEncryption
> Issuer: CN=openshift-signer@1558850775
> Validity
> Not Before: May 26 06:06:15 2019 GMT
> Not After : May 24 06:06:16 2024 GMT
> Subject: CN=openshift-signer@1558850775
> Subject Public Key Info:
> Public Key Algorithm: rsaEncryption
> Public-Key: (2048 bit)
> Modulus:
> .....
> Exponent: 65537 (0x10001)
> X509v3 extensions:
> X509v3 Key Usage: critical
> Digital Signature, Key Encipherment, Certificate Sign
> X509v3 Basic Constraints: critical
> CA:TRUE
> 
> [root@gasu-development lib]#
> 
> diff /root/.kube/config /etc/origin/master/admin.kubeconfig - It files is simmular
> 
> openssl s_client -CAfile /etc/origin/master/ca-bundle.crt -connect oc-master.gasu-development.ibs.ru:8443 -I have connect
> 
> ## CONNECTED(00000003)
> depth=1 CN = openshift-signer@1558813491
> verify error:num=19:self signed certificate in certificate chain
> ## Certificate chain
> 0 s:/CN=172.29.227.50
> i:/CN=openshift-signer@1558813491
> 1 s:/CN=openshift-signer@1558813491
> i:/CN=openshift-signer@1558813491
> ## Server certificate
> -----BEGIN CERTIFICATE-----
> MIID+TCCAuGgAwIBAgIBBDANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
> ....
> -----END CERTIFICATE-----
> subject=/CN=172.29.227.50
> issuer=/CN=openshift-signer@1558813491
> ## Acceptable client certificate CA names
> /CN=openshift-signer@1558813491
> /CN=openshift-signer@1558813490
> Client Certificate Types: RSA sign, ECDSA sign
> Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA512:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
> Shared Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA512:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
> Peer signing digest: SHA512
> Server Temp Key: ECDH, P-256, 256 bits
> ## SSL handshake has read 2496 bytes and written 427 bytes
> New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
> Server public key is 2048 bit
> Secure Renegotiation IS supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> SSL-Session:
> Protocol : TLSv1.2
> Cipher : ECDHE-RSA-AES128-GCM-SHA256
> Session-ID: 6B01BE43137D49AB5FFA0FEFAC2D023263ABF48020FE0B4715FE1B7534673637
> Session-ID-ctx:
> Master-Key: 58151DEA754960682C9AFD865886986F9037F8385D63699552C69CB156DDFB2F386B86E0188F359B24D56B12AB23B4EA
> Key-Arg : None
> Krb5 Principal: None
> PSK identity: None
> PSK identity hint: None
> TLS session ticket:
> 0000 - f1 98 d9 93 f2 f0 9f f3-22 b1 96 62 eb 60 49 40 ........"..b.`I@
> ....
> 
> ```
> Start Time: 1558855188
> Timeout   : 300 (sec)
> Verify return code: 19 (self signed certificate in certificate chain)
> ```
> 
> oc status --config=/etc/origin/master/admin.kubeconfig
> Unable to connect to the server: x509: certificate signed by unknown authority
> 
> openssl x509 -noout -issuer -in /etc/origin/master/ca.crt
> issuer= /CN=openshift-signer@1558850775
> 
> oc get pv
> Unable to connect to the server: x509: certificate signed by unknown authority

**Comment by fidelina** [comment]
```
sudo docker ps -a
CONTAINER ID        IMAGE                                                                                         COMMAND                  CREATED              STATUS                            PORTS               NAMES
6cb64be6ef0f        42f38837c3d6                                                                                  "/bin/bash -c '#!/..."   About a minute ago   Exited (255) About a minute ago                       k8s_controllers_master-controllers-gasu-development.ibs.ru_kube-system_04335d3709e8228377883a762ef7f830_11
5fdecd7bea30        42f38837c3d6                                                                                  "/bin/bash -c '#!/..."   About a minute ago   Exited (255) About a minute ago                       k8s_api_master-api-gasu-development.ibs.ru_kube-system_d400ab198a15ccbe597efa10e38d0719_11
1ce5d80e836a        quay.io/coreos/etcd@sha256:43fbc8a457aa0cb887da63d74a48659e13947cb74b96a53ba8f47abb6172a948   "/bin/sh -c '#!/bi..."   35 minutes ago       Up 35 minutes                                         k8s_etcd_master-etcd-gasu-development.ibs.ru_kube-system_365913b03d626d43833aa80048591d33_0
380ed350bafd        docker.io/openshift/origin-pod:v3.11.0                                                        "/usr/bin/pod"           35 minutes ago       Up 35 minutes                                         k8s_POD_master-etcd-gasu-development.ibs.ru_kube-system_365913b03d626d43833aa80048591d33_0
95c0f352aede        docker.io/openshift/origin-pod:v3.11.0                                                        "/usr/bin/pod"           35 minutes ago       Up 35 minutes                                         k8s_POD_master-api-gasu-development.ibs.ru_kube-system_d400ab198a15ccbe597efa10e38d0719_0
1e106df65f12        docker.io/openshift/origin-pod:v3.11.0                                                        "/usr/bin/pod"           35 minutes ago       Up 35 minutes                                         k8s_POD_master-controllers-gasu-development.ibs.ru_kube-system_04335d3709e8228377883a762ef7f830_0

```

**Comment by vrutkovs** [comment]
Resolved by uninstall, cleaning up `/etc/origin/master` along with containers and a reboot.

Seems new CA was not applied without a reboot
