### ISSUE TITLE
When deploying Atomic Enterprise the atomic-openshift-master.service won't start correctly

### ISSUE THREAD

**Issue by cooktheryan** [openshift/openshift-ansible#1164]
Jan 11 15:17:48 ae-e364319a-9037-4ae6-8a3a-158593e1cc0d.os1.phx2.redhat.com systemd[1]: Starting Atomic OpenShift Master...
Jan 11 15:17:49 ae-e364319a-9037-4ae6-8a3a-158593e1cc0d.os1.phx2.redhat.com atomic-openshift-master[1336]: Invalid MasterConfig /etc/origin/master/master-config.yaml
Jan 11 15:17:49 ae-e364319a-9037-4ae6-8a3a-158593e1cc0d.os1.phx2.redhat.com atomic-openshift-master[1336]: disabledFeatures[1]: invalid value 'S2IBuilder', Details: not one of valid features: Builder, S2I Builder, Web Console
Jan 11 15:17:49 ae-e364319a-9037-4ae6-8a3a-158593e1cc0d.os1.phx2.redhat.com atomic-openshift-master[1336]: disabledFeatures[2]: invalid value 'WebConsole', Details: not one of valid features: Builder, S2I Builder, Web Console
Jan 11 15:17:49 ae-e364319a-9037-4ae6-8a3a-158593e1cc0d.os1.phx2.redhat.com systemd[1]: atomic-openshift-master.service: main process exited, code=exited, status=255/n/a
Jan 11 15:17:49 ae-e364319a-9037-4ae6-8a3a-158593e1cc0d.os1.phx2.redhat.com systemd[1]: Failed to start Atomic OpenShift Master.

The fix is to modify /etc/origin/master/master-config.yaml line disabledFeatures: ["Builder", "S2I Builder", "Web Console"] which is to just add a space to We Console, and S2I Builder. I did not create a PR because this variable is in a lot of places but I did not know the repercussions of making the change. If I get the time I will test it with the fix against OSE.

**Comment by detiber** [comment]
@cooktheryan What build version?

@liggitt Was there a change upstream that changed behavior for the strings accepted for disabledFeatures?

**Comment by cooktheryan** [comment]
@detiber 
atomic-openshift-3.0.1.100-0.git.105.6fa8487.el7aos.x86_64
atomic-openshift-master-3.0.1.100-0.git.105.6fa8487.el7aos.x86_64
atomic-openshift-clients-3.0.1.100-0.git.105.6fa8487.el7aos.x86_64

**Comment by detiber** [comment]
@cooktheryan oh, that is quite an old buiild...  The public preview bits should have been 3.1

**Comment by detiber** [comment]
@brenton please close. We never tested against the 3.0.1 builds of AEP.
