### ISSUE TITLE
OpenShift 3.11 - hang on "Wait for API Server rollout success" in long time 

### ISSUE THREAD

**Issue by xWesKerTx** [openshift/openshift-ansible#11654]
#### Description

Deploy cluster is hanging on "Wait for API Server rollout success" in long time.
API server cannot deploy
I don't know what happening or get more log/info on it.

```
[root@master inventory]# curl -vv https://apiserver.kube-service-catalog.svc/healthz
* About to connect() to apiserver.kube-service-catalog.svc port 443 (#0)
*   Trying 172.30.251.61...
* Connection refused
* Failed connect to apiserver.kube-service-catalog.svc:443; Connection refused
* Closing connection 0
curl: (7) Failed connect to apiserver.kube-service-catalog.svc:443; Connection refused
```

oc get pods --all-namespaces | grep Crash:
```
kube-service-catalog    apiserver-5nph7                                0/1       CrashLoopBackOff   17         1h
kube-service-catalog    controller-manager-fzwhz                       0/1       CrashLoopBackOff   18         1h
```

master-logs api api:
```
E0531 20:32:24.702380       1 controller.go:111] loading OpenAPI spec for "v1beta1.servicecatalog.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
, Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
I0531 20:32:24.702421       1 controller.go:119] OpenAPI AggregationController: action for item v1beta1.servicecatalog.k8s.io: Rate Limited Requeue.
E0531 20:32:34.044366       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
E0531 20:32:34.526105       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
I0531 20:32:37.094807       1 controller.go:597] quota admission added evaluator for: {monitoring.coreos.com alertmanagers}
I0531 20:32:37.095570       1 controller.go:597] quota admission added evaluator for: {monitoring.coreos.com alertmanagers}
E0531 20:32:37.635330       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
E0531 20:32:44.073082       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
E0531 20:32:54.118825       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
E0531 20:33:04.149407       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
I0531 20:33:06.444830       1 logs.go:49] http: TLS handshake error from 10.9.118.180:46630: tls: first record does not look like a TLS handshake
E0531 20:33:14.180344       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
I0531 20:33:19.208143       1 logs.go:49] http: TLS handshake error from 10.9.118.180:46670: remote error: tls: unknown certificate authority
E0531 20:33:24.212488       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
I0531 20:33:24.702614       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.servicecatalog.k8s.io
E0531 20:33:24.702768       1 controller.go:111] loading OpenAPI spec for "v1beta1.servicecatalog.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
, Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]

.
.
.
W0531 20:45:02.069045       1 reflector.go:272] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:129: watch of *core.PersistentVolumeClaim ended with: The resourceVersion for the provided watch is too old.
I0531 20:45:05.907705       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.servicecatalog.k8s.io
E0531 20:45:05.907834       1 controller.go:111] loading OpenAPI spec for "v1beta1.servicecatalog.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
, Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
I0531 20:45:05.907881       1 controller.go:119] OpenAPI AggregationController: action for item v1beta1.servicecatalog.k8s.io: Rate Limited Requeue.
E0531 20:45:06.239719       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
E0531 20:45:08.580073       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
E0531 20:45:13.088291       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
W0531 20:45:13.088656       1 reflector.go:272] k8s.io/apiextensions-apiserver/pkg/client/informers/internalversion/factory.go:117: watch of *apiextensions.CustomResourceDefinition ended with: The resourceVersion for the provided watch is too old.
E0531 20:45:13.590439       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
E0531 20:45:14.993051       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
W0531 20:45:14.993414       1 reflector.go:272] k8s.io/client-go/informers/factory.go:130: watch of *v1.Role ended with: The resourceVersion for the provided watch is too old.
E0531 20:45:16.268967       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
E0531 20:45:17.597385       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
.
.
```

##### Version

ansible version

```
[root@master ~]# ansible --version
ansible 2.6.16
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
[root@master ~]# rpm -q openshift-ansible
openshift-ansible-3.11.98-1.git.0.3cfa7c3.el7.noarch
```

##### Steps To Reproduce
1. Deploy cluster stopping at this stage.

##### Additional Information

Red Hat version:
```
[root@master ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

Inventory file:
```
[OSEv3:children]
masters
nodes
etcd
nfs

[OSEv3:vars]
ansible_ssh_user=root

# General Cluster Variables
openshift_deployment_type=openshift-enterprise
openshift_release=v3.11
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability


# Cluster Authentication Variables
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
openshift_master_htpasswd_file=/etc/origin/master/htpasswd

# Registery registry.access.redhat.com
oreg_auth_user=xxxxxxx
oreg_auth_password=xxxxxxxx


# OpenShift Networking Variables
os_firewall_use_firewalld=true
openshift_master_api_port=443
openshift_master_console_port=443
openshift_master_default_subdomain=apps.tb.local.com

# NFS
openshift_enable_unsupported_configuration=true

# OCR configuration variables
openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_nfs_directory=/exports
openshift_hosted_registry_storage_nfs_options='*(rw,root_squash)'
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=19Gi

# OAB's etcd configuration variables
openshift_hosted_etcd_storage_kind=nfs
openshift_hosted_etcd_storage_nfs_options="*(rw,root_squash,sync,no_wdelay)"
openshift_hosted_etcd_storage_nfs_directory=/exports
openshift_hosted_etcd_storage_volume_name=etcd-vol2
openshift_hosted_etcd_storage_access_modes=["ReadWriteOnce"]
openshift_hosted_etcd_storage_volume_size=1G
openshift_hosted_etcd_storage_labels={'storage': 'etcd'}


# Certificate
openshift_ca_cert_expire_days=3650
openshift_node_cert_expire_days=3650
openshift_master_cert_expire_days=3650
etcd_ca_default_days=3650


[masters]
master.tb.local.com

[etcd]
master.tb.local.com

[nodes]
master.tb.local.com openshift_node_group_name='node-config-master'
node1.tb.local.com openshift_node_group_name='node-config-compute-infra'
node2.tb.local.com openshift_node_group_name='node-config-compute-infra'

[nfs]
master.tb.local.com
```

**Comment by Nymria** [comment]
I am dealing with same problem on Centos 7.6.

kube-service-catalog pods keeps crashbackoff
hosts file: 
```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
# if your target hosts are Fedora uncomment this
#ansible_python_interpreter=/usr/bin/python3
openshift_deployment_type=origin
#openshift_portal_net=172.30.0.0/16
# localhost likely doesn't meet the minimum requirements
openshift_disable_check=disk_availability,memory_availability,docker_availability

openshift_node_groups=[{'name': 'node-config-all-in-one', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]
openshift_metrics_install_metrics=true
#openshift_metrics_cassandra_image= "docker.io/openshift/origin-metrics-cassandra:v3.11.0"
#openshift_metrics_hawkular_metrics_image= "docker.io/openshift/origin-metrics-hawkular-metrics:v3.11.0"
#openshift_metrics_heapster_image= "docker.io/openshift/origin-metrics-heapster:v3.11.0"
#openshift_metrics_schema_installer_image= "docker.io/alv91/origin-metrics-schema-installer:v3.10.0"
[masters]
okd.terrainserver.com ansible_connection=local

[etcd]
okd.terrainserver.com ansible_connection=local

[nodes]
# openshift_node_group_name should refer to a dictionary with matching key of name in list openshift_node_groups.
okd.terrainserver.com ansible_connection=local openshift_node_group_name="node-config-all-in-one" openshift_schedulable=true 
```


api server logs here:

```
[root@okd muhammed]# oc logs apiserver-mblgm
I0618 19:37:49.554432       1 feature_gate.go:194] feature gates: map[OriginatingIdentity:true]
I0618 19:37:49.554616       1 feature_gate.go:194] feature gates: map[OriginatingIdentity:true NamespacedServiceBroker:true]
I0618 19:37:49.554660       1 hyperkube.go:192] Service Catalog version v3.11.0-0.1.35+8d4f895-2;Upstream:v0.1.35 (built 2019-01-08T23:12:26Z)
W0618 19:37:50.144287       1 util.go:112] OpenAPI spec will not be served
I0618 19:37:50.145230       1 util.go:182] Admission control plugin names: [NamespaceLifecycle MutatingAdmissionWebhook ValidatingAdmissionWebhook DefaultServicePlan ServiceBindingsLifecycle ServicePlanChangeValidator BrokerAuthSarCheck]
I0618 19:37:50.145541       1 plugins.go:158] Loaded 6 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,MutatingAdmissionWebhook,DefaultServicePlan,ServiceBindingsLifecycle,ServicePlanChangeValidator,BrokerAuthSarCheck.
I0618 19:37:50.145552       1 plugins.go:161] Loaded 1 validating admission controller(s) successfully in the following order: ValidatingAdmissionWebhook.
I0618 19:37:50.147820       1 storage_factory.go:285] storing {servicecatalog.k8s.io clusterservicebrokers} in servicecatalog.k8s.io/v1beta1, reading as servicecatalog.k8s.io/__internal from storagebackend.Config{Type:"", Prefix:"/registry", ServerList:[]string{"https://okd.terrainserver.com:2379"}, KeyFile:"/etc/origin/master/master.etcd-client.key", CertFile:"/etc/origin/master/master.etcd-client.crt", CAFile:"/etc/origin/master/master.etcd-ca.crt", Quorum:true, Paging:true, DeserializationCacheSize:0, Codec:runtime.Codec(nil), Transformer:value.Transformer(nil), CompactionInterval:300000000000, CountMetricPollPeriod:60000000000}
I0618 19:37:50.147895       1 storage_factory.go:285] storing {servicecatalog.k8s.io clusterserviceclasses} in servicecatalog.k8s.io/v1beta1, reading as servicecatalog.k8s.io/__internal from storagebackend.Config{Type:"", Prefix:"/registry", ServerList:[]string{"https://okd.terrainserver.com:2379"}, KeyFile:"/etc/origin/master/master.etcd-client.key", CertFile:"/etc/origin/master/master.etcd-client.crt", CAFile:"/etc/origin/master/master.etcd-ca.crt", Quorum:true, Paging:true, DeserializationCacheSize:0, Codec:runtime.Codec(nil), Transformer:value.Transformer(nil), CompactionInterval:300000000000, CountMetricPollPeriod:60000000000}
I0618 19:37:50.147946       1 storage_factory.go:285] storing {servicecatalog.k8s.io clusterserviceplans} in servicecatalog.k8s.io/v1beta1, reading as servicecatalog.k8s.io/__internal from storagebackend.Config{Type:"", Prefix:"/registry", ServerList:[]string{"https://okd.terrainserver.com:2379"}, KeyFile:"/etc/origin/master/master.etcd-client.key", CertFile:"/etc/origin/master/master.etcd-client.crt", CAFile:"/etc/origin/master/master.etcd-ca.crt", Quorum:true, Paging:true, DeserializationCacheSize:0, Codec:runtime.Codec(nil), Transformer:value.Transformer(nil), CompactionInterval:300000000000, CountMetricPollPeriod:60000000000}
I0618 19:37:50.148001       1 storage_factory.go:285] storing {servicecatalog.k8s.io serviceinstances} in servicecatalog.k8s.io/v1beta1, reading as servicecatalog.k8s.io/__internal from storagebackend.Config{Type:"", Prefix:"/registry", ServerList:[]string{"https://okd.terrainserver.com:2379"}, KeyFile:"/etc/origin/master/master.etcd-client.key", CertFile:"/etc/origin/master/master.etcd-client.crt", CAFile:"/etc/origin/master/master.etcd-ca.crt", Quorum:true, Paging:true, DeserializationCacheSize:0, Codec:runtime.Codec(nil), Transformer:value.Transformer(nil), CompactionInterval:300000000000, CountMetricPollPeriod:60000000000}
I0618 19:37:50.148090       1 storage_factory.go:285] storing {servicecatalog.k8s.io servicebindings} in servicecatalog.k8s.io/v1beta1, reading as servicecatalog.k8s.io/__internal from storagebackend.Config{Type:"", Prefix:"/registry", ServerList:[]string{"https://okd.terrainserver.com:2379"}, KeyFile:"/etc/origin/master/master.etcd-client.key", CertFile:"/etc/origin/master/master.etcd-client.crt", CAFile:"/etc/origin/master/master.etcd-ca.crt", Quorum:true, Paging:true, DeserializationCacheSize:0, Codec:runtime.Codec(nil), Transformer:value.Transformer(nil), CompactionInterval:300000000000, CountMetricPollPeriod:60000000000}
F0618 19:38:10.149377       1 storage_decorator.go:57] Unable to create storage backend: config (&{ /registry [https://okd.terrainserver.com:2379] /etc/origin/master/master.etcd-client.key /etc/origin/master/master.etcd-client.crt /etc/origin/master/master.etcd-ca.crt true true 0 {0xc420578280 0xc420578380} <nil> 5m0s 1m0s}), err (context deadline exceeded)
```

more info 
```
[root@okd muhammed]# curl -vvv -k https://okd.terrainserver.com:2379
* About to connect() to okd.terrainserver.com port 2379 (#0)
*   Trying 192.168.1.110...
* Connected to okd.terrainserver.com (192.168.1.110) port 2379 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* NSS error -12271 (SSL_ERROR_BAD_CERT_ALERT)
* SSL peer cannot verify your certificate.
* Closing connection 0
curl: (58) NSS: client certificate not found (nickname not specified)
```

**Comment by Nymria** [comment]
Well i am not much into openshift internals but to me it seems very much likely related to invalid ETCD certificate. 

Can anyone help with this ?

**Comment by Yossarian151** [comment]
Same exact issue. RHEL 7.6, Ansible 2.6.17. 

kube-service-catalog and openshift-monitoring (prometheus-k8s-1) are stuck in CrashLoopBackOff.

**Comment by vrutkovs** [comment]
Could you check that MTU on interfaces is valid? It seems https://github.com/openshift/openshift-ansible/pull/11707 is related

**Comment by Nymria** [comment]
These are my devices

```
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:d3:52:56:16  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp4s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 44:8a:5b:ec:77:93  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 19  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 6199  bytes 378248 (369.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6199  bytes 378248 (369.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:29:d1:e0  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.110  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::7894:5781:6bcb:3be6  prefixlen 64  scopeid 0x20<link>
        ether 30:3a:64:5d:9d:5f  txqueuelen 1000  (Ethernet)
        RX packets 8513  bytes 11047063 (10.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4648  bytes 673697 (657.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by Yossarian151** [comment]
Looks like it!

`docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:19:f7:69:dc  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens192: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.86.15  netmask 255.255.255.0  broadcast 192.168.86.255
        inet6 fe80::f60d:1ee:8543:5c40  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:55:d2:bb  txqueuelen 1000  (Ethernet)
        RX packets 4604813  bytes 2255795260 (2.1 GiB)
        RX errors 0  dropped 81185  overruns 0  frame 0
        TX packets 3799008  bytes 6387673359 (5.9 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 42698870  bytes 22419501072 (20.8 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 42698870  bytes 22419501072 (20.8 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.128.0.1  netmask 255.255.254.0  broadcast 10.128.1.255
        inet6 fe80::b0e8:5bff:fed6:3d9a  prefixlen 64  scopeid 0x20<link>
        ether b2:e8:5b:d6:3d:9a  txqueuelen 1000  (Ethernet)
        RX packets 61835  bytes 21465155 (20.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 66246  bytes 61539633 (58.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth00f6876f: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet6 fe80::70c1:b8ff:fef1:1e92  prefixlen 64  scopeid 0x20<link>
        ether 72:c1:b8:f1:1e:92  txqueuelen 0  (Ethernet)
        RX packets 5939  bytes 1803332 (1.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6731  bytes 717644 (700.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth19d81c07: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet6 fe80::58a7:b1ff:fe52:c2da  prefixlen 64  scopeid 0x20<link>
        ether 5a:a7:b1:52:c2:da  txqueuelen 0  (Ethernet)
        RX packets 15451  bytes 4351999 (4.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16782  bytes 23669043 (22.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

**Comment by Yossarian151** [comment]
Is there an interim workaround for the MTU issue? The services are in a bad state - fixing the node-config.yml probably isn't enough....

**Comment by xWesKerTx** [comment]
> #### Description
> Deploy cluster is hanging on "Wait for API Server rollout success" in long time.
> API server cannot deploy
> I don't know what happening or get more log/info on it.
> 
> ```
> [root@master inventory]# curl -vv https://apiserver.kube-service-catalog.svc/healthz
> * About to connect() to apiserver.kube-service-catalog.svc port 443 (#0)
> *   Trying 172.30.251.61...
> * Connection refused
> * Failed connect to apiserver.kube-service-catalog.svc:443; Connection refused
> * Closing connection 0
> curl: (7) Failed connect to apiserver.kube-service-catalog.svc:443; Connection refused
> ```
> 
> oc get pods --all-namespaces | grep Crash:
> 
> ```
> kube-service-catalog    apiserver-5nph7                                0/1       CrashLoopBackOff   17         1h
> kube-service-catalog    controller-manager-fzwhz                       0/1       CrashLoopBackOff   18         1h
> ```
> 
> master-logs api api:
> 
> ```
> E0531 20:32:24.702380       1 controller.go:111] loading OpenAPI spec for "v1beta1.servicecatalog.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
> , Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
> I0531 20:32:24.702421       1 controller.go:119] OpenAPI AggregationController: action for item v1beta1.servicecatalog.k8s.io: Rate Limited Requeue.
> E0531 20:32:34.044366       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
> E0531 20:32:34.526105       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
> I0531 20:32:37.094807       1 controller.go:597] quota admission added evaluator for: {monitoring.coreos.com alertmanagers}
> I0531 20:32:37.095570       1 controller.go:597] quota admission added evaluator for: {monitoring.coreos.com alertmanagers}
> E0531 20:32:37.635330       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
> E0531 20:32:44.073082       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
> E0531 20:32:54.118825       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
> E0531 20:33:04.149407       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
> I0531 20:33:06.444830       1 logs.go:49] http: TLS handshake error from 10.9.118.180:46630: tls: first record does not look like a TLS handshake
> E0531 20:33:14.180344       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
> I0531 20:33:19.208143       1 logs.go:49] http: TLS handshake error from 10.9.118.180:46670: remote error: tls: unknown certificate authority
> E0531 20:33:24.212488       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
> I0531 20:33:24.702614       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.servicecatalog.k8s.io
> E0531 20:33:24.702768       1 controller.go:111] loading OpenAPI spec for "v1beta1.servicecatalog.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
> , Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
> 
> .
> .
> .
> W0531 20:45:02.069045       1 reflector.go:272] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:129: watch of *core.PersistentVolumeClaim ended with: The resourceVersion for the provided watch is too old.
> I0531 20:45:05.907705       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.servicecatalog.k8s.io
> E0531 20:45:05.907834       1 controller.go:111] loading OpenAPI spec for "v1beta1.servicecatalog.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
> , Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
> I0531 20:45:05.907881       1 controller.go:119] OpenAPI AggregationController: action for item v1beta1.servicecatalog.k8s.io: Rate Limited Requeue.
> E0531 20:45:06.239719       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
> E0531 20:45:08.580073       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
> E0531 20:45:13.088291       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
> W0531 20:45:13.088656       1 reflector.go:272] k8s.io/apiextensions-apiserver/pkg/client/informers/internalversion/factory.go:117: watch of *apiextensions.CustomResourceDefinition ended with: The resourceVersion for the provided watch is too old.
> E0531 20:45:13.590439       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
> E0531 20:45:14.993051       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
> W0531 20:45:14.993414       1 reflector.go:272] k8s.io/client-go/informers/factory.go:130: watch of *v1.Role ended with: The resourceVersion for the provided watch is too old.
> E0531 20:45:16.268967       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
> E0531 20:45:17.597385       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
> .
> .
> ```
> 
> ##### Version
> ansible version
> 
> ```
> [root@master ~]# ansible --version
> ansible 2.6.16
>   config file = /etc/ansible/ansible.cfg
>   configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/lib/python2.7/site-packages/ansible
>   executable location = /usr/bin/ansible
>   python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
> [root@master ~]# rpm -q openshift-ansible
> openshift-ansible-3.11.98-1.git.0.3cfa7c3.el7.noarch
> ```
> 
> ##### Steps To Reproduce
> 1. Deploy cluster stopping at this stage.
> 
> ##### Additional Information
> Red Hat version:
> 
> ```
> [root@master ~]# cat /etc/redhat-release
> Red Hat Enterprise Linux Server release 7.6 (Maipo)
> ```
> 
> Inventory file:
> 
> ```
> [OSEv3:children]
> masters
> nodes
> etcd
> nfs
> 
> [OSEv3:vars]
> ansible_ssh_user=root
> 
> # General Cluster Variables
> openshift_deployment_type=openshift-enterprise
> openshift_release=v3.11
> openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability
> 
> 
> # Cluster Authentication Variables
> openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
> openshift_master_htpasswd_file=/etc/origin/master/htpasswd
> 
> # Registery registry.access.redhat.com
> oreg_auth_user=xxxxxxx
> oreg_auth_password=xxxxxxxx
> 
> 
> # OpenShift Networking Variables
> os_firewall_use_firewalld=true
> openshift_master_api_port=443
> openshift_master_console_port=443
> openshift_master_default_subdomain=apps.tb.local.com
> 
> # NFS
> openshift_enable_unsupported_configuration=true
> 
> # OCR configuration variables
> openshift_hosted_registry_storage_kind=nfs
> openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
> openshift_hosted_registry_storage_nfs_directory=/exports
> openshift_hosted_registry_storage_nfs_options='*(rw,root_squash)'
> openshift_hosted_registry_storage_volume_name=registry
> openshift_hosted_registry_storage_volume_size=19Gi
> 
> # OAB's etcd configuration variables
> openshift_hosted_etcd_storage_kind=nfs
> openshift_hosted_etcd_storage_nfs_options="*(rw,root_squash,sync,no_wdelay)"
> openshift_hosted_etcd_storage_nfs_directory=/exports
> openshift_hosted_etcd_storage_volume_name=etcd-vol2
> openshift_hosted_etcd_storage_access_modes=["ReadWriteOnce"]
> openshift_hosted_etcd_storage_volume_size=1G
> openshift_hosted_etcd_storage_labels={'storage': 'etcd'}
> 
> 
> # Certificate
> openshift_ca_cert_expire_days=3650
> openshift_node_cert_expire_days=3650
> openshift_master_cert_expire_days=3650
> etcd_ca_default_days=3650
> 
> 
> [masters]
> master.tb.local.com
> 
> [etcd]
> master.tb.local.com
> 
> [nodes]
> master.tb.local.com openshift_node_group_name='node-config-master'
> node1.tb.local.com openshift_node_group_name='node-config-compute-infra'
> node2.tb.local.com openshift_node_group_name='node-config-compute-infra'
> 
> [nfs]
> master.tb.local.com
> ```

I have created a wrong DNS record:
*.tb.local.com master
*.apps.tb.local.com (infra node)

Then, I removed the *.tb.local.com, the problem is solved.
Seems you are not the same issue with me viewing from the log.

**Comment by Nymria** [comment]
@xWesKerTx 

I have exact same logs as you.

I have only master node, my etc is as follows

```
127.0.0.1 localhost
192.168.1.110 okd.terrainserver.com
```

How do you suggest to solve it ? Did you remove the record after the installation is done ?

**Comment by vrutkovs** [comment]
>Is there an interim workaround for the MTU issue?

I don't think there is a way to fix on existing cluster. @squeed, do you any way of fixing this?

In the worst case you'd have to redeploy once https://github.com/openshift/openshift-ansible/pull/11707 is merged

**Comment by xWesKerTx** [comment]
@Nymria 

The DNS record should not have "*.domain.com" wildcard host record,
it only needs "*.apps.domain.com" wildcard apps record to point to all infra node.

If you are using All-in-one master option, then you need to have
"master.domain.com -> master"
"*apps.master.domain.com -> master"
records.

**Comment by squeed** [comment]
It should be possible to roll out a configuration change that reduces the sdn mtu to 1410. I don't know the details of the config syncer well enough to come up with the steps, though. Easiest is to redeploy, hard-coding `openshift_node_sdn_mtu = 1410`

**Comment by Nymria** [comment]
@vrutkovs 
I have made a fresh install of Centos and everything. Error remains exactly same.

I will migrate to Kubernetes i guess. This is not working :/
Thanks for the effort tho

**Comment by Yossarian151** [comment]
I redeployed and was successful even with the MTU = 1450. The problem (for me at least) was my ansible hosts file. I had to separate the node names explicitly like this:
<img width="636" alt="Screen Shot 2019-06-25 at 11 50 41 AM" src="https://user-images.githubusercontent.com/10459309/60117323-7bf68c80-973f-11e9-84ba-441510aa4c5f.png">
