### ISSUE TITLE
openshift 3.11 cat not deploy new app var image stream

### ISSUE THREAD

**Issue by alex8158** [openshift/openshift-ansible#11667]
Description

I deploy a okd cluster recently with release-3.11. but when I deploy an application. the  error shows:

Cloning "https://github.com/OpenShiftInAction/image-uploader.git " ...
 Commit: 549c356f1694661587b52fe8233a4439fdc9965c (Update index.php)
 Author: johnfosborneiii <johnfosborneiii@gmail.com>
 Date: Sun Jun 25 12:08:00 2017 -0400
pulling image error : unknown: unable to pull manifest from docker.io/centos/php-71-centos7:latest: Get https://registry-1.docker.io/v2/:  x509: certificate is valid for *.router.default.svc.cluster.local, router.default.svc.cluster.local, not registry-1.docker.io
error: build error: unable to get docker-registry.default.svc:5000/openshift/php@sha256:ed72ebcd21241c31fcc9041c802c337e7d41301fea90e76ff83e28bbd5ca271d

the same error appears when I deploy any application using image stream：

# oc new-project  image-uploader --display-name='Image Uploader Project'
# oc new-app  --image-stream=php --code=https://github.com/OpenShiftInAction/image-uploader.git --name=app-cli
# oc logs bc/app-cli
Cloning "https://github.com/OpenShiftInAction/image-uploader.git" ...
        Commit: 549c356f1694661587b52fe8233a4439fdc9965c (Update index.php)
        Author: johnfosborneiii <johnfosborneiii@gmail.com>
        Date:   Sun Jun 25 12:08:00 2017 -0400
pulling image error : unknown: unable to pull manifest from docker.io/centos/php-71-centos7:latest: Get https://registry-1.docker.io/v2/: x509: certificate is valid for *.router.default.svc.cluster.local, router.default.svc.cluster.local, not registry-1.docker.io
error: build error: unable to get docker-registry.default.svc:5000/openshift/php@sha256:ed72ebcd21241c31fcc9041c802c337e7d41301fea90e76ff83e28bbd5ca271d

my okd cluster info:

# ansible --version
ansible 2.7.9

# git describe
openshift-ansible-3.11.118-1-18-gd1b30a8

[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=origin
os_sdn_network_plugin_name=redhat/openshift-ovs-multitenant
openshift_disable_check=memory_availability,disk_availability,docker_image_availability,docker_storage
os_firewall_use_firewalld=True

the same config I ever deployed can succeeded deploy new apps with the formar openshift-ansible version.

**Comment by alex8158** [comment]
no one knowns?

**Comment by remkohdev** [comment]
Same here, seems a simple timeout in the installation process during pulling of images. Rerunning a Deploy of the same service, solved the issue. I assume cause previous images being cached already.
