### ISSUE TITLE
MTU incorrectly set for nodes on v3.11

### ISSUE THREAD

**Issue by oybed** [openshift/openshift-ansible#11664]
#### Description

Provide a brief description of your issue here. For example:

After a fresh install using `release-3.11` from `openshift-ansible`, the MTU settings for the nodes come up wrong. It used to be that it would subtract 50 from the main interface's MTU, but this no longer happens. It now needs to be manually adjusted after install completes. 

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
> ansible --version
ansible 2.7.4
> git describe
v3.11.3-2-g4901018

```

##### Steps To Reproduce
1. Install OCP v3.11 from `release-3.11` branch in an environment where MTU is lower than the "normal" 1500
2. Observe that the nodes uses MTU v1450 for the various veth* interfaces instead of <MTU_of_main_interface>-50. 

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
In the output from 'ip link' below, the mtu for the various veth* interfaces should be 1400:
 
> ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether fa:16:3e:42:9d:95 brd ff:ff:ff:ff:ff:ff
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:28:87:ce:12 brd ff:ff:ff:ff:ff:ff
4: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 12:9e:78:27:35:73 brd ff:ff:ff:ff:ff:ff
5: br0: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 3a:b2:81:6e:86:49 brd ff:ff:ff:ff:ff:ff
6: vxlan_sys_4789: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65000 qdisc noqueue master ovs-system state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 7e:5f:e0:b4:c5:13 brd ff:ff:ff:ff:ff:ff
7: tun0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 56:d0:43:79:cd:69 brd ff:ff:ff:ff:ff:ff
9: veth8bc3183b@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP mode DEFAULT group default 
    link/ether da:43:64:9d:a5:d9 brd ff:ff:ff:ff:ff:ff link-netnsid 1
10: veth91c41ffa@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP mode DEFAULT group default 
    link/ether a6:cd:20:68:96:46 brd ff:ff:ff:ff:ff:ff link-netnsid 0
11: veth75bd549b@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP mode DEFAULT group default 
    link/ether a2:2f:62:36:11:e6 brd ff:ff:ff:ff:ff:ff link-netnsid 2
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
This used to work in earlier versions of `release-3.11`, hence something changed in the last month or 2 (or 3). 
```

**Comment by oybed** [comment]
Some of the 'side-effects' experienced can be seen in this issue: https://github.com/openshift/origin/issues/22599#issuecomment-491438427

**Comment by vrutkovs** [comment]
MTU is being set via `openshift_node_sdn_mtu`, default value is 1410. There is no easy way to autodetect the MTU

**Comment by oybed** [comment]
@vrutkovs yes, it can be set through configuration, but this used to be automatically detected and set in  earlier versions of v3.11 (and pre v3.11 versions as well), hence it is experienced as "breakage" in newer versions of v3.11.

**Comment by vrutkovs** [comment]
Which "earlier version of 3.11" is that?
Could it be caused by https://github.com/openshift/openshift-ansible/pull/11525?

**Comment by oybed** [comment]
I will have to go back to find out which earlier versions worked, but we have multiple v3.11 clusters running and the ones that have been running for awhile (2-3 months or older) are correctly configured. Including having the mtu value in `/etc/sysconfig/docker-network` set correctly (should be set to 1400 in our environment). 

"old" v3.11 cluster:
```
> cat /etc/sysconfig/docker-network 
# /etc/sysconfig/docker-network
DOCKER_NETWORK_OPTIONS=' --mtu=1400'
> ip link | grep tun0
7: tun0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
```

"new" v3.11 cluster (any cluster installed in the last ~30 days):
```
> cat /etc/sysconfig/docker-network 
# /etc/sysconfig/docker-network
DOCKER_NETWORK_OPTIONS=' --mtu=1450'
> ip link | grep tun0
7: tun0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
```
