### ISSUE TITLE
Use delegate_to in roles instead of the playbook orchestration tasks

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#1167]
I've just tested with all of the rhel7 openssh client versions and the current version on my f22 box (openssh-6.9) and cannot replicate the previous issues with delegate_to that appeared to be a race condition on accessing the control persist socket.

Since we technically only support RHEL-7.1+ as the installer platform, I think we should go ahead and update the areas we worked around the issue, and push the playbook orchestration pieces down properly into the roles.

I fully expect that we'll see a stray issue or two for other OSs that people are running, and I propose that we treat those on a case by case basis (possibly telling them to set the paramiko connection plugin in their inventory as opposed to the openssh connection plugin).

@abutcher @twiest

**Comment by twiest** [comment]
I totally agree, thanks!

:+1:

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
