### ISSUE TITLE
Control plane pods didn't come up in Openshift 3.11

### ISSUE THREAD

**Issue by piyushkv1** [openshift/openshift-ansible#11687]
#### Description

Control plan failed to come up. This is happening with Openshift 3.11 version, same I tried with Openshift 3.11. I did not see issue there.

##### Version

Please put the following version information in the code block
indicated below.

[root@wdc-vsphere-cf-fvt-138-dhcp215 ~]# ansible --version
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 20 2019, 12:21:26) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
You have new mail in /var/spool/mail/root

If you're operating from a **git clone**:

[root@wdc-vsphere-cf-fvt-138-dhcp215 openshift-ansible]# git describe
openshift-ansible-3.11.109-1-2-g476aab3

Place the output between the code block below:

```
[root@wdc-vsphere-cf-fvt-138-dhcp215 openshift-ansible]# git branch
* release-3.11
```

##### Steps To Reproduce
1. Run openshift-ansible/playbooks/deploy_cluster.yml playbook

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
[root@wdc-vsphere-cf-fvt-138-dhcp215 openshift-ansible]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
* Your inventory file (especially any non-standard configuration parameters)
Attached

* Attaching ansible log file and inventory file.
[ansible.log](https://github.com/openshift/openshift-ansible/files/3282076/ansible.log)

[hosts.txt](https://github.com/openshift/openshift-ansible/files/3282079/hosts.txt)

**Comment by vrutkovs** [comment]
>ansible 2.8.0

This version is not yet supported, make sure the version of openshift-ansible you're using has #11325 included
