### ISSUE TITLE
openshift-logging: _cluster_component is undefined

### ISSUE THREAD

**Issue by tmartensson** [openshift/openshift-ansible#11715]
#### Description
Installing openshift-logging fails

##### Version
```
ansible 2.8.1

$ git describe
openshift-ansible-3.11.123-1-4-gea24f1ddd
```

##### Steps To Reproduce
Install openshift-logging with `ansible 2.8.1` using `playbooks/openshift-logging/config.yml`

##### Expected Results
openshift-logging to be installed and configured

##### Observed Results
The ansible-installer fails with error:
```
TASK [openshift_logging_elasticsearch : Set ES dc] *****
ERROR! '_cluster_component' is undefined
```

##### Additional Information
Downgrading to `ansible 2.7.11` solves the problem and the openshift-logging installer completes without problems.

**Comment by mtnbikenc** [comment]
Reproduced and opened a PR to fix.  Thanks for reporting it!

**Comment by mtnbikenc** [comment]
Fix merged.
