### ISSUE TITLE
No APIServer or Controller arguments lead to invalid YAML

### ISSUE THREAD

**Issue by Tebro** [openshift/openshift-ansible#1171]
So I am using the byo/config.yaml playbook to install a Openshift cluster and it failed when starting the Openshift Master.

Turns out, after some time reading various source files, that the settings for apiServerArguments and controllerArguments got extra line with "...". This cause it all to fail, I fixed it by modifying the templates (removed the whole variable insertion and just used "null" as that was what I needed).

**Comment by Tebro** [comment]
Same goes for kubeletArguments in the node's configuration.

**Comment by abutcher** [comment]
This should be fixed by #1168

**Comment by Tebro** [comment]
Oh wow, my clone is older. Well setting the values to null worked for me.
