### ISSUE TITLE
Openshift 3.11 Node Scaleup NotReady state due to cni config uninitialized

### ISSUE THREAD

**Issue by Srimrao02** [openshift/openshift-ansible#11743]
#### Description

We have 1 master and 2 worker nodes running in OCP on Azure, i'm trying to add new worker node.
The scaleup script runs successfully without any issue or failures but node is in Not Ready state.

 oc get nodes
NAME                    STATUS     ROLES     AGE       VERSION
devopenshift-infra-0    Ready      infra     203d      v1.11.0+d4cacc0
devopenshift-master-0   Ready      master    203d      v1.11.0+d4cacc0
devopenshift-node-0     Ready      compute   203d      v1.11.0+d4cacc0
devopenshift-node-1     Ready      compute   203d      v1.11.0+d4cacc0
devopenshift-node-2     NotReady   compute   4m        v1.11.0+d4cacc0

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

ansible --version
ansible 2.6.10

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
Bastion host:
$ rpm -q openshift-ansible
openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch

New node:
$ rpm -q openshift-ansible
openshift-ansible-3.11.123-1.git.0.db681ba.el7.noarch
```

##### Steps To Reproduce
1. Always after including new node in new_nodes section
2. Run scaleup.yml

##### Expected Results
Node should be in ready state

```
Example command and output or error messages
```

##### Observed Results
1. I see below error on the new nodes /var/log/messages
2. I don't see OVS and SDN pod being created for new node

```
Jul  3 12:06:55 devopenshift-node-2 atomic-openshift-node: E0703 12:06:55.754129   14600 summary.go:102] Failed to get system container stats for "/system.slice/atomic-openshift-node.service": failed to get cgroup stats for "/system.slice/atomic-openshift-node.service": failed to get container info for "/system.slice/atomic-openshift-node.service": unknown container "/system.slice/atomic-openshift-node.service"
Jul  3 12:06:59 devopenshift-node-2 atomic-openshift-node: W0703 12:06:59.333148   14600 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Jul  3 12:06:59 devopenshift-node-2 atomic-openshift-node: E0703 12:06:59.333325   14600 kubelet.go:2101] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

1. operating system and version, ie: RHEL 7.6
2. inventory file, i have skipped subscriptions and other cloud information.

* Sample code, etc

```
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
etcd
master0
glusterfs
new_nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=infyadmin
ansible_become=yes
openshift_install_examples=true
deployment_type=openshift-enterprise
openshift_release=v3.11
openshift_image_tag=v3.11.43
openshift_pkg_version=-3.11.43
docker_udev_workaround=True
openshift_use_dnsmasq=true
openshift_override_hostname_check=true
osm_use_cockpit=true
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_master_api_port=443
openshift_master_console_port=443
osm_default_node_selector='node-role.kubernetes.io/compute=true'
openshift_disable_check=memory_availability,docker_image_availability
openshift_cloudprovider_kind=azure

# host group for masters
[masters]
devopenshift-master-[0:0]

# host group for etcd
[etcd]
devopenshift-master-[0:0]

[master0]
devopenshift-master-0

# Only populated when CNS is enabled
[glusterfs]


# host group for nodes
[nodes]

devopenshift-master-0  openshift_node_group_name='node-config-master'

devopenshift-infra-0 openshift_hostname=devopenshift-infra-0 openshift_node_group_name='node-config-infra'

devopenshift-node-0 openshift_hostname=devopenshift-node-0 openshift_node_group_name='node-config-compute' logging='true'
devopenshift-node-1 openshift_hostname=devopenshift-node-1 openshift_node_group_name='node-config-compute' logging='true'

# host group for adding new nodes
[new_nodes]
devopenshift-node-2 openshift_node_group_name='node-config-compute'

```

**Comment by Srimrao02** [comment]
[ansible-run-log.txt](https://github.com/openshift/openshift-ansible/files/3354888/ansible-run-log.txt)

Ansible run log, i missed to capture initial output but covered rest of it.

Any suggestions or help appreciated.

**Comment by Srimrao02** [comment]
OC version command output:

# oc version
oc v3.11.43
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://masking-url:443
openshift v3.11.43
kubernetes v1.11.0+d4cacc0

**Comment by magick93** [comment]
Hi @Srimrao02 - did you mange to solve this issue?

**Comment by Srimrao02** [comment]
Hi @magick93 , Yes I had to follow up with Redhat team and identified that in our cluster users list in security context constraint(scc) was screwed up like this.

 `oc get scc -o yaml` see below user section output:
![image](https://user-images.githubusercontent.com/49248571/64340624-39d1ad00-d004-11e9-9166-9bca16531cda.png)

Due to this openshift-sdn namespace was throwing below events.

> Error creating: pods "ovs-" is forbidden: unable to validate against any security context constraint
> Error creating: pods "sdn-" is forbidden: unable to validate against any security context constraint

Later scc was edited to add service account for openshift-sdn to scc user list command `oc -n openshift-sdn adm policy add-scc-to-user privileged -z sdn`

Post this change, immediatley node came to ready state and CNI networks was initialized for the new node.

![image](https://user-images.githubusercontent.com/49248571/64340678-5a9a0280-d004-11e9-9182-a3e05d374dca.png)
