### ISSUE TITLE
No route to service with nsx-t

### ISSUE THREAD

**Issue by hniedlich** [openshift/openshift-ansible#11770]
Hello,

I need help with integrating openshift with NSX-T. I'm trying versions:
openshift 3.11
nsx-t 2.4
ansible 2.8.1

I'm doing exacly as it is said in in https://docs.vmware.com/en/VMware-NSX-T-Data-Center/2.4/nsxt_24_ncp_openshift.pdf
-create bare metal transport nodes
-create every resource needed by installer
-run playbook deploy_cluster.yml

I'm facing issue with "no route to host" when pods want to access for example kubernetes service on ip 172.30.0.1:443, and installation hangs with deploy error on router, registry etc.

Anyone know how to perform proper install with nsx-t? Can't find similar errors via google.

**Comment by piyushkv1** [comment]
Could you provide failure logs? Check if kube-proxy-and-dns DS is running on your setup.
