### ISSUE TITLE
heketi how reload topology ?

### ISSUE THREAD

**Issue by yeganx** [openshift/openshift-ansible#11776]
I have install containrized glusterfs storage on my openshift cluster.
```
oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://lb.example.com:8443
openshift v3.11.0+d0c29df-98
kubernetes v1.11.0+d4cacc0
```

```
oc get pods
NAME                                          READY     STATUS    RESTARTS   AGE
glusterblock-storage-provisioner-dc-1-mjc8k   1/1       Running   0          4d
glusterfs-storage-46269                       1/1       Running   5          45d
glusterfs-storage-bj6jj                       1/1       Running   3          5d
glusterfs-storage-snsmx                       1/1       Running   0          5d
glusterfs-storage-tn5jd                       1/1       Running   4          45d
heketi-storage-1-75dzf                        1/1       Running   14         42d

```
openshift cluster restart and heketi can not connect to cluster

```
 oc rsh heketi-storage-1-75dzf
 heketi-cli cluster list
Clusters:
[]
```
all gluster pod conncted :
```

gluster peer status
Number of Peers: 3

Hostname: Y.Y.Y.Y
Uuid: e473fd2e-5e21-492b-91df-0cfc1bee4844
State: Peer in Cluster (Connected)

Hostname: X.X.X.X
Uuid: 92bf0767-a753-40eb-b81f-dc924fd9850b
State: Peer in Cluster (Connected)
Other names:
compute1.example.com

Hostname: Z.Z.Z.Z
Uuid: 3d5d844a-5c65-4a0f-9fa7-e334b50e2a29
State: Peer in Cluster (Connected)

```
then I try to load topology.json
but this are errors 
```
heketi-cli topology load --json=/tmp/openshift-glusterfs-ansible-8QTnud/topology.json
Creating cluster ... ID: b37a83689c3be3040507890a7ac2fc8a
	Allowing file volumes on cluster.
	Allowing block volumes on cluster.
	Creating node X.example.com ... ID: 699fced3b15eead9b3a59a47ee62dd8c
		Adding device /dev/sdc ... 

Unable to add device: server did not provide a message (status 500: Internal Server Error)
		Adding device /dev/sdb ... 

Unable to add device: server did not provide a message (status 500: Internal Server Error)
	Creating node infra.toodevops.com ... ID: f1eae45849a8c0a2c096ae8e915c087d
		Adding device /dev/sdc ... 
Unable to add device: server did not provide a message (status 500: Internal Server Error)
		Adding device /dev/sdb ... Unable to add device: server did not provide a message (status 500: Internal Server Error)
	Creating node Y.example.com ... ID: f37b3c2b96662fd713e65d6a0639eda1
		Adding device /dev/sdc ... 
Unable to add device: server did not provide a message (status 500: Internal Server Error)
		Adding device /dev/sdb ... Unable to add device: server did not provide a message (status 500: Internal Server Error)
	Creating node Z.example.com... ID: bde39e721cc4ff291348432b88306f34
		Adding device /dev/sdc ... Unable to add device: server did not provide a message (status 500: Internal Server Error)
		Adding device /dev/sdb ... Unable to add device: server did not provide a message (status 500: Internal Server Error)
```
after that the result is :
```
heketi-cli cluster list
Clusters:
Id:b37a83689c3be3040507890a7ac2fc8a [file][block]
sh-4.4# heketi-cli cluster info b37a83689c3be3040507890a7ac2fc8a
Cluster id: b37a83689c3be3040507890a7ac2fc8a
Nodes:
699fced3b15eead9b3a59a47ee62dd8c
bde39e721cc4ff291348432b88306f34
f1eae45849a8c0a2c096ae8e915c087d
f37b3c2b96662fd713e65d6a0639eda1
Volumes:

Block: true

File: true

```
now i dont know how add volumes and devices
is there any ansible file for that ?

**Comment by ZrytyADHD** [comment]
Hi,
first try to do this:
Login to you cluster using 
`oc login` 
and enter you admin login and password
next switch to your project where you have heketi installed in my example this is `app-storage`
`oc project app-storage`
List the pods:
`oc get pods`
after displaying the pods use this :
`oc describe pod <heketi pod name>
for example:
`oc describe pod heketi-storage-1-zpm42`

Thanks to this you will get you admin key which is required.
Search for quota :

```
HEKETI_USER_KEY:                 <heketi user key>
HEKETI_ADMIN_KEY:                <heketi admin key> --> this is what you need
```

Copy the ` HEKETI_ADMIN_KEY`, we will use it to manage glusterfs with heketi.
Now use command:
oc rsh <nheketi pod name> heketi-cli -s http://localhost:8080 --user admin --secret <heketi admin key from prevvious lines> <command>

Example
oc rsh heketi-storage-1-l9wxm heketi-cli -s http://localhost:8080 --user admin --secret <heketi admin key>= topology info

This command should show you whole glusterfs topology.

If not write what you get.

**Comment by yeganx** [comment]
thank you for your response
but my problem is exactly that heketi can not connct to the gluster 
```
heketi-cli cluster list
Clusters:
```
`
oc rsh heketi-storage-1-pt6cr heketi-cli -s http://localhost:8080 --user admin --secret 1j+/BuAgHxrxNYGmovojRfgf9A3qP1YCsOg9Xr+fspw=  topology info`
this request has nothing in  reponse

**Comment by yeganx** [comment]
for more describtion about my problem:
I have gluster pods ready and runnig 
but heketi cluster-list return null
I dont know why it happned after rebooting openshift nodes.and now my question is :
how match heketi-cli to my existing gluster pod ?

**Comment by ZrytyADHD** [comment]
Hmm
this is very strange. I have an idea sometimes ago i configuring glusterfs on existing openshift using this tutorial: [https://medium.com/@wilson.wilson/install-heketi-and-glusterfs-with-openshift-to-allow-dynamic-persistent-volume-management-89156340b2bd](url)
Try to use this if you can but first you need to remove whole of your glusterfs config if you can do this.
Maybe this will help you resolve this.

**Comment by yeganx** [comment]
thank you 
I've read the link before ,
but I cant remove and format my devices , because my data is important . 
and if I remove them , if again this problem happen , what should I do ?
 what is the right solution for that ?

**Comment by yeganx** [comment]
no help :(

**Comment by ZrytyADHD** [comment]
I try to reporoduce you issue on my test enviroment but without success. Can you try to evacuate your data from this glusterfs cluster and recereate it. 
I mean copy all data from brick. It's normaly mounted folder which can be accesed thru terminal. Delete all glusterfs cluster and recreate it and after that copy whole backlup data to new cluster and breaks.

**Comment by yeganx** [comment]
now i have create copy of my gluster data ,
but how the pvc on openshift can determine where is their  data?

**Comment by yeganx** [comment]
I am thinking about way that add new devices to my gluster ,
I have some /dev/sdb joined to gluster before , the for joining /dev/sdc
I have edited my glsuterfs invetory file section to : 
```
[glusterfs]
master.XXX.com glusterfs_devices='[ "/dev/sdc" ]'
infra.XXX.com glusterfs_devices='[ "/dev/sdc" ]'
compute1.XXX.com glusterfs_devices='[ "/dev/sdc" ]'
compute2.XXX.com glusterfs_devices='[ "/dev/sdc" ]'
```
and run this playbook :  playbooks/openshift-glusterfs/config.yml
 Is that right ?

**Comment by yeganx** [comment]
Im sure what i Done , is not correct 
this topology is created after adding /dev/sdc
vi /tmp/openshift-glusterfs-ansible-j2oeFf/topology.json
```
{
  "clusters": [{
      "nodes": [{
          "node": {
            "hostnames": {
              "manage": ["master.XXX.com"],
              "storage": ["192.168.96.227"]
            },
            "zone": 1
          },
          "devices": ["/dev/sdc"]
        },{
          "node": {
            "hostnames": {
              "manage": ["infra.XXX.com"],
              "storage": ["192.168.96.228"]
            },
            "zone": 1
          },
          "devices": ["/dev/sdc"]
        },{
          "node": {
            "hostnames": {
              "manage": ["compute1.XXX.com"],
              "storage": ["192.168.96.229"]
            },
            "zone": 1
          },
          "devices": ["/dev/sdc"]
        },{
          "node": {
            "hostnames": {
              "manage": ["compute2.XXX.com"],
              "storage": ["192.168.96.217"]
            },
            "zone": 1
          },
          "devices": ["/dev/sdc"]
        }]
    }]
}

```
now /dev/sdb device arent in topology 
what is right way ?

**Comment by yeganx** [comment]
Is there any help ?
