### ISSUE TITLE
Node exporter - Ciphers

### ISSUE THREAD

**Issue by ZrytyADHD** [openshift/openshift-ansible#11781]
#### Description

Hello,
I need to add some Ciphers to my existing Cluster.
After scan of vulnerability, scaner detect me something like this:

```

`NVT: SSL/TLS: Report Vulnerable Cipher Suites for HTTPSSummary
This routine reports all SSL/TLS cipher suites accepted by a service where attack vectors existsonly on HTTPS services.

Vulnerability Detection Result’Vulnerable’ cipher suites accepted by this service via the TLSv1.0 protocol:TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)TLS_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)

’Vulnerable’ cipher suites accepted by this service via the TLSv1.1 protocol:TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)TLS_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)

’Vulnerable’ cipher suites accepted by this service via the TLSv1.2 protocol:TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)TLS_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)`
```

The problem is with something working on port 9100.
I check what use this port 9100 and discover its a node-exporter and try to add Ciphers to daemon set config editing yaml but without success because after few minutes config is wipe out and back to default.
How to setr it correctly to secure this or maybe the image will be replaced to disable this weak protocols.

##### Version
3.11

Ansible - 2.6.5

##### Steps To Reproduce
1. Add Ciphers and secure this vulnerabilities

**Comment by alxzndr** [comment]
I have the same report from a vulnerability scan.
Have you found a way to mitigate this?

**Comment by ZrytyADHD** [comment]
Sorry but still i can't resolve it

**Comment by alxzndr** [comment]
I fixed this by adding "etcd_cipher_suites" in the inventory under [OSEv3:vars]  [`etcd_cipher_suites="TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
`
