### ISSUE TITLE
Fails to "Apply the web console template file" in OpenShift 3.11 OKD install

### ISSUE THREAD

**Issue by ServerNinja** [openshift/openshift-ansible#11797]
#### Description

The OpenShift 3.11 install fails at "TASK [openshift_web_console : Apply the web console template file]". It is unable to apply the template file for the web console.

```
TASK [openshift_web_console : Apply the web console template file] *************************************************************************************************************************************************************************
task path: /home/deploy/src/openshift-ansible/roles/openshift_web_console/tasks/install.yml:138
Friday 02 August 2019  02:48:06 +0000 (0:00:00.055)       0:10:54.465 *********
fatal: [192.168.37.83]: FAILED! => {"changed": true, "cmd": "oc process -f \"/tmp/console-ansible-YH8kYo/console-template.yaml\" --param API_SERVER_CONFIG=\"apiVersion: webconsole.config.openshift.io/v1\nclusterInfo:\n  adminConsolePublicURL: https://console.stg.redacted.com/\n  consolePublicURL: https://osemaster01.stg.redacted.com:8443/console/\n  loggingPublicURL: ''\n  logoutPublicURL: ''\n  masterPublicURL: https://osemaster01.stg.redacted.com:8443\n  metricsPublicURL: ''\nextensions:\n  properties: {}\n  scriptURLs: []\n  stylesheetURLs: []\nfeatures:\n  clusterResourceOverridesEnabled: false\n  inactivityTimeoutMinutes: 0\nkind: WebConsoleConfiguration\nservingInfo:\n  bindAddress: 0.0.0.0:8443\n  bindNetwork: tcp4\n  certFile: /var/serving-cert/tls.crt\n  clientCA: ''\n  keyFile: /var/serving-cert/tls.key\n  maxRequestsInFlight: 0\n  namedCertificates: null\n  requestTimeoutSeconds: 0\n\" --param IMAGE=\"docker.io/openshift/origin-web-console:v3.11\" --param NODE_SELECTOR='\"node-role.kubernetes.io/master=true\"' --param REPLICA_COUNT=\"1\" --config=/tmp/console-ansible-YH8kYo/admin.kubeconfig | oc apply --config=/tmp/console-ansible-YH8kYo/admin.kubeconfig -f -", "delta": "0:00:00.386141", "end": "2019-08-02 02:48:07.224292", "msg": "non-zero return code", "rc": 1, "start": "2019-08-02 02:48:06.838151", "stderr": "Error from server (BadRequest): Deployment in version \"v1beta1\" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.NodeSelector: ReadMapCB: expect { or n, but found \", error found in #10 byte of ...|elector\":\"node-role.|..., bigger context ...|g\",\"name\":\"webconsole-config\"}]}],\"nodeSelector\":\"node-role.kubernetes.io/master=true\",\"serviceAccou|...", "stderr_lines": ["Error from server (BadRequest): Deployment in version \"v1beta1\" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.NodeSelector: ReadMapCB: expect { or n, but found \", error found in #10 byte of ...|elector\":\"node-role.|..., bigger context ...|g\",\"name\":\"webconsole-config\"}]}],\"nodeSelector\":\"node-role.kubernetes.io/master=true\",\"serviceAccou|..."], "stdout": "configmap/webconsole-config created\nserviceaccount/webconsole created\nservice/webconsole created", "stdout_lines": ["configmap/webconsole-config created", "serviceaccount/webconsole created", "service/webconsole created"]}
```

If you ssh to the master host and run the command from the task manually, you can see that there is some issue with the formatting of the template its trying to process:

```
$ oc process -f "/tmp/console-ansible-YH8kYo/console-template.yaml" --param API_SERVER_CONFIG="apiVersion: webconsole.config.openshift.io/v1\nclusterInfo:\n  adminConsolePublicURL: https://console.stg.redacted.com/\n  consolePublicURL: https://osemaster01.stg.redacted.com:8443/console/\n  loggingPublicURL: ''\n  logoutPublicURL: ''\n  masterPublicURL: https://osemaster01.stg.redacted.com:8443\n  metricsPublicURL: ''\nextensions:\n  properties: {}\n  scriptURLs: []\n  stylesheetURLs: []\nfeatures:\n  clusterResourceOverridesEnabled: false\n  inactivityTimeoutMinutes: 0\nkind: WebConsoleConfiguration\nservingInfo:\n  bindAddress: 0.0.0.0:8443\n  bindNetwork: tcp4\n  certFile: /var/serving-cert/tls.crt\n  clientCA: ''\n  keyFile: /var/serving-cert/tls.key\n  maxRequestsInFlight: 0\n  namedCertificates: null\n  requestTimeoutSeconds: 0\n" --param IMAGE="docker.io/openshift/origin-web-console:v3.11" --param NODE_SELECTOR='"node-role.kubernetes.io/master=true"' --param REPLICA_COUNT="1" --config=/tmp/console-ansible-YH8kYo/admin.kubeconfig | oc apply --config=/tmp/console-ansible-YH8kYo/admin.kubeconfig -f -
configmap/webconsole-config configured
serviceaccount/webconsole unchanged
service/webconsole unchanged
Error from server (BadRequest): Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.NodeSelector: ReadMapCB: expect { or n, but found ", error found in #10 byte of ...|elector":"node-role.|..., bigger context ...|g","name":"webconsole-config"}]}],"nodeSelector":"node-role.kubernetes.io/master=true","serviceAccou|...
```

##### Version

Please put the following version information in the code block
indicated below.

Ansible version:
```
$ ansible --version
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/deploy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

If you're operating from a **git clone**:

```
$ git describe
openshift-ansible-3.11.126-1
```

##### Steps To Reproduce
hosts file:
```
[masters]
192.168.37.83 openshift_public_hostname=osemaster01.stg.redacted.com

[etcd]
192.168.37.83

[nodes]
192.168.37.83 openshift_node_group_name='ose-master' openshift_schedulable=true openshift_public_hostname=osemaster01.stg.redacted.com
192.168.37.77 openshift_node_group_name='ose-node' openshift_schedulable=true
192.168.37.123 openshift_node_group_name='ose-node' openshift_schedulable=true
192.168.37.89 openshift_node_group_name='ose-node' openshift_schedulable=true
192.168.37.85 openshift_node_group_name='ose-router' openshift_schedulable=true
192.168.37.72 openshift_node_group_name='ose-router' openshift_schedulable=true

[new_nodes]

[OSEv3:children]
masters
nodes
new_nodes

[OSEv3:vars]
# Ansible settings
ansible_user=deploy
ansible_become=yes
debug_level=2

# OpenShift Installation Settings
openshift_node_groups=[{ 'name': 'ose-master', 'labels': [ 'node-role.kubernetes.io/master=true','region=master','zone=default']},{ 'name': 'ose-node', 'labels': [ 'node-role.kubernetes.io/compute=true','region=primary','role=app','zone=us-east-1']},{ 'name': 'ose-router', 'labels': [ 'region=router','node-role.kubernetes.io/infra=true','node-role.kubernetes.io/router=true','zone=us-east-1']}]

osm_default_node_selector='region=primary'

openshift_deployment_type=origin
openshift_release="3.11"

openshift_master_default_subdomain=stg.redacted.com
openshift_master_cluster_hostname=osemaster-int.stg.redacted.com

# Misc OpenShift Settings
openshift_disable_check=package_version,docker_image_availability,disk_availability,docker_image_availability
openshift_enable_service_catalog=true
template_service_broker_install=false
openshift_hosted_manage_registry=false
openshift_metrics_install_metrics=false
openshift_install_examples=false
openshift_web_console_nodeselector='node-role.kubernetes.io/master=true'

# Docker
openshift_docker_options=" --log-opt max-size=50m"
docker_upgrade=True

# Registry settings for disconnected install

# Router Settings
openshift_hosted_router_selector='node-role.kubernetes.io/router=true'
openshift_hosted_router_replicas=2

# Network
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
osm_cluster_network_cidr=10.16.0.0/17
openshift_portal_net=172.16.0.0/16
openshift_node_sdn_mtu=1450

# Auth
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
openshift_master_htpasswd_file=/etc/ansible/.htpasswd

# Certificates
openshift_master_overwrite_named_certificates=true
openshift_hosted_router_certificate={"certfile": "/etc/ansible/certificates/router.crt", "keyfile": "/etc/ansible/certificates/router.key", "cafile": "/etc/ansible/certificates/router-ca.crt"}
openshift_master_named_certificates=[{"certfile": "/etc/ansible/certificates/router.crt", "keyfile": "/etc/ansible/certificates/router.key", "cafile": "/etc/ansible/certificates/router-ca.crt"}]
```

##### Expected Results
I would expect that this step passes and it successfully applies the web console template so the install could continue.

##### Observed Results
Template fails to apply (see output above)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

```
$ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
```

**Comment by vrutkovs** [comment]
Invalid `openshift_web_console_nodeselector`, should be `'{"node-role.kubernetes.io/master":"true"}'.

Default are already set to master anyway, so its safe to omit it

**Comment by ServerNinja** [comment]
@vrutkovs , that fixed my problem. Thanks for the quick answer!

**Comment by aselvaveltcs** [comment]
Hi 
I have given web_console node selector, still facing the issues.

Tuesday 17 March 2020  22:25:19 +0300 (0:00:00.080)       0:14:12.129 *********
fatal: [mwdp3dev3m01.moh.gov.sa]: FAILED! => {"changed": true, "cmd": "oc process -f \"/tmp/console-ansible-TjbF1W/console-template.yaml\" --param API_SERVER_CONFIG=\"apiVersion: webconsole.config.openshift.io/v1\nclusterInfo:\n  adminConsolePublicURL: https://console.apps.mwdp3dev3m01.moh.gov.sa/\n  consolePublicURL: https://mwdp3dev3m01.moh.gov.sa:8443/console/\n  loggingPublicURL: ''\n  logoutPublicURL: ''\n  masterPublicURL: https://mwdp3dev3m01.moh.gov.sa:8443\n  metricsPublicURL: ''\nextensions:\n  properties: {}\n  scriptURLs: []\n  stylesheetURLs: []\nfeatures:\n  clusterResourceOverridesEnabled: false\n  inactivityTimeoutMinutes: 0\nkind: WebConsoleConfiguration\nservingInfo:\n  bindAddress: 0.0.0.0:8443\n  bindNetwork: tcp4\n  certFile: /var/serving-cert/tls.crt\n  clientCA: ''\n  keyFile: /var/serving-cert/tls.key\n  maxRequestsInFlight: 0\n  namedCertificates: null\n  requestTimeoutSeconds: 0\n\" --param IMAGE=\"registry.redhat.io/openshift3/ose-web-console:v3.11.170\" --param NODE_SELECTOR='\"{'\"'\"'node-role.kubernetes.io/master\\\": \\\"true\\\"}\"' --param REPLICA_COUNT=\"1\" --config=/tmp/console-ansible-TjbF1W/admin.kubeconfig | oc apply --config=/tmp/console-ansible-TjbF1W/admin.kubeconfig -f -", "delta": "0:00:00.425661", "end": "2020-03-17 22:25:19.996077", "msg": "non-zero return code", "rc": 1, "start": "2020-03-17 22:25:19.570416", "stderr": "Error from server (BadRequest): Deployment in version \"v1beta1\" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.NodeSelector: ReadMapCB: expect { or n, but found \", error found in #10 byte of ...|elector\":\"{'node-rol|..., bigger context ...|g\",\"name\":\"webconsole-config\"}]}],\"nodeSelector\":\"{'node-role.kubernetes.io/master\\\": \\\"true\\\"}\",\"se|...", "stderr_lines": ["Error from server (BadRequest): Deployment in version \"v1beta1\" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.NodeSelector: ReadMapCB: expect { or n, but found \", error found in #10 byte of ...|elector\":\"{'node-rol|..., bigger context ...|g\",\"name\":\"webconsole-config\"}]}],\"nodeSelector\":\"{'node-role.kubernetes.io/master\\\": \\\"true\\\"}\",\"se|..."], "stdout": "configmap/webconsole-config created\nserviceaccount/webconsole created\nservice/webconsole created", "stdout_lines": ["configmap/webconsole-config created", "serviceaccount/webconsole created", "service/webconsole created"]}

PLAY RECAP **********************************************************************************************************************************************************
localhost                  : ok=12   changed=0    unreachable=0    failed=0
mwdp3dev3b01.moh.gov.sa    : ok=109  changed=22   unreachable=0    failed=0
mwdp3dev3m01.moh.gov.sa    : ok=430  changed=97   unreachable=0    failed=1
mwdp3dev3nfs.moh.gov.sa    : ok=21   changed=1    unreachable=0    failed=0
mwdp3dev3w02.moh.gov.sa    : ok=109  changed=22   unreachable=0    failed=0


INSTALLER STATUS ****************************************************************************************************************************************************
Initialization              : Complete (0:00:17)
Health Check                : Complete (0:00:56)
Node Bootstrap Preparation  : Complete (0:06:51)
etcd Install                : Complete (0:00:55)
NFS Install                 : Complete (0:00:20)
Master Install              : Complete (0:02:55)
Master Additional Install   : Complete (0:00:35)
Node Join                   : Complete (0:00:26)
Hosted Install              : Complete (0:00:33)
        The use of NFS for the core OpenShift Container Platform components is not recommended, as NFS (and the NFS Protocol) does not provide the proper consistency needed for the applications that make up the OpenShift Container Platform infrastructure.
Web Console Install         : In Progress (0:00:07)
        This phase can be restarted by running: playbooks/openshift-web-console/config.yml
Tuesday 17 March 2020  22:25:20 +0300 (0:00:00.704)       0:14:12.833 *********
