### ISSUE TITLE
OpenStack playbooks require NetworkManager on nodes but don't install it

### ISSUE THREAD

**Issue by tliron** [openshift/openshift-ansible#11818]
#### Description

We're running the `provision_install.yml` playbook and using `CentOS-7-x86_64-GenericCloud-1905.qcow2` as the `openshift_openstack_default_image_name`. Using the origin release.

Indeed, CentOS-7 GenericCloud does not come with NetworkManager installed. But CentOS-8 GenericCloud is explicitly mentioned in the documentation. So why doesn't the installer install NetworkManager for us?

##### Version

Ansible 2.5.15
Playbooks are cloned from this repository with the `release-3.11` branch.

##### Observed Results

Get these errors:

`NetworkManager must be installed and enabled prior to installation`

##### Additional Information

We managed to find a workaround, adding this to `all.yml`:
```
openshift_openstack_provision_user_commands:
- systemctl stop sshd # will force Ansible playbook to stop
- yum install --assumeyes NetworkManager
- reboot # will allow Ansible playbook to continue
```
Also note that the following attribute is mentioned in the configuration, but seems to be ignored by the playbooks, e.g.:
```
openshift_openstack_required_packages: NetworkManager
```

**Comment by vrutkovs** [comment]
See https://docs.openshift.com/container-platform/3.11/install_config/configuring_openstack.html#installation-openstack-playbook - use `install.yml` playbook, which explicitly installs NM after nodes are prepared

**Comment by tliron** [comment]
I am using the `provision_install.yml` playbook per the README instructions. This playbook already includes `prerequisites.yml`, `provision.yml`, and `install.yml`. The error appears unless I implement my workaround.

Please re-open this bug.

**Comment by tliron** [comment]
Also please address the `openshift_openstack_required_packages` mentioned in the documentation. If this feature is not supported then the documentation should be fixed.

**Comment by X-dark** [comment]
I can reproduce the same behavior. I run `provision.yml` and then `install.yml`. `install.yml` fails with the NetworkManager error. I need to manually install, enable and reboot to make things work.
