### ISSUE TITLE
POD Deployment Error on Openshift Version 3.11

### ISSUE THREAD

**Issue by shneha** [openshift/openshift-ansible#11831]
#### Description

1 Master machine  with Openshift 3..11 installed
Trying to deploy pod on same machine.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

ansible 2.6.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch
```

##### Steps To Reproduce
1. Create Hello World Java program jar file
2. Create image of jar using docker file
3. Try to create POD from Image on openshift

##### Expected Results
Successful deployment of POD and service to be exposed on given port.

```
Output:
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  2m (x59933 over 4d)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match node selector.

```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  2m (x59933 over 4d)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match node selector.

```

Seems like some issue with NodeSelector.
Kindly assist

**Comment by ravitri** [comment]
@shneha - Can you share more details here please? 

1. Let's look at the yaml definition of the pod
$ oc get -oyaml pod <your-podname>

2. Also, the node labels
$ oc get nodes --show-labels

You would need to check the nodeSelector of the pod yaml file does not match the labels that the master node already has so you would have to match it accordingly.

**Comment by vrutkovs** [comment]
Not an openshift-ansible issue

**Comment by shneha** [comment]
THanks @ravitri for the inputs!
