### ISSUE TITLE
adding rhel7.6  compute to OCP 4.1 using scaleup.yml not adding node

### ISSUE THREAD

**Issue by davis-jacob** [openshift/openshift-ansible#11845]
#### Description

I have a running OCP 4.1 and I'm trying to add a RHEL7.6 node to this existing OCP cluster using scaleup.yml play. The play completes successfully , however if I run oc get nodes , I don't see the nodes listed
```
NAME              STATUS   ROLES    AGE     VERSION             INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                                   KERNEL-VERSION               CONTAINER-RUNTIME
compute-1         Ready    worker   5d17h   v1.13.4+ab8449285   20.0.9.39     20.0.9.39     Red Hat Enterprise Linux CoreOS 410.8.20190724.0 (Ootpa)   4.18.0-80.4.2.el8_0.x86_64   cri-o://1.13.10-0.1.dev.rhaos4.1.git9e2e1de.el8-dev
compute-2         Ready    worker   5d17h   v1.13.4+ab8449285   20.0.9.40     20.0.9.40     Red Hat Enterprise Linux CoreOS 410.8.20190724.0 (Ootpa)   4.18.0-80.4.2.el8_0.x86_64   cri-o://1.13.10-0.1.dev.rhaos4.1.git9e2e1de.el8-dev
control-plane-0   Ready    master   5d17h   v1.13.4+ab8449285   20.0.9.35     20.0.9.35     Red Hat Enterprise Linux CoreOS 410.8.20190724.0 (Ootpa)   4.18.0-80.4.2.el8_0.x86_64   cri-o://1.13.10-0.1.dev.rhaos4.1.git9e2e1de.el8-dev
control-plane-1   Ready    master   5d17h   v1.13.4+ab8449285   20.0.9.36     20.0.9.36     Red Hat Enterprise Linux CoreOS 410.8.20190724.0 (Ootpa)   4.18.0-80.4.2.el8_0.x86_64   cri-o://1.13.10-0.1.dev.rhaos4.1.git9e2e1de.el8-dev
control-plane-2   Ready    master   5d17h   v1.13.4+ab8449285   20.0.9.37     20.0.9.37     Red Hat Enterprise Linux CoreOS 410.8.20190724.0 (Ootpa)   4.18.0-80.4.2.el8_0.x86_64   cri-o://1.13.10-0.1.dev.rhaos4.1.git9e2e1de.el8-dev
```

##### Version
```
[root@ocp41-local ansible]# oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.8-201907241243+785687c-dirty", GitCommit:"785687c", GitTreeState:"dirty", BuildDate:"2019-07-24T19:44:04Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+4b86cc5", GitCommit:"4b86cc5", GitTreeState:"clean", BuildDate:"2019-07-24T19:42:25Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}

[root@ocp41-local ansible]# ansible --version
ansible 2.7.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### Steps To Reproduce
1. Set the host file as below

[all:vars]
ansible_user=core 
ansible_become=True 

openshift_kubeconfig_path="~/.kube/config" 
openshift_pull_secret_path="~/pull-secret.txt" 

[new_workers] 
npworker01

2. Run the below command from the machine used to install the OCP 4.1 cluster , where the ansible host is setup
```
ansible-playbook -i hosts /usr/share/ansible/openshift-ansible/playbooks/scaleup.yml


TASK [openshift_node : Install openshift packages] ******************************************************************************************************************************************
ok: [npworker01]

TASK [openshift_node : Enable the CRI-O service] ********************************************************************************************************************************************
ok: [npworker01]

TASK [openshift_node : include_tasks] *******************************************************************************************************************************************************
included: /usr/share/ansible/openshift-ansible/roles/openshift_node/tasks/config.yml for npworker01

TASK [openshift_node : Disable swap] ********************************************************************************************************************************************************
ok: [npworker01]

TASK [openshift_node : sysctl] **************************************************************************************************************************************************************
ok: [npworker01]

TASK [openshift_node : Setting sebool container_manage_cgroup] ******************************************************************************************************************************
ok: [npworker01]

TASK [openshift_node : create temp directory] ***********************************************************************************************************************************************
changed: [npworker01]

TASK [openshift_node : Wait for bootstrap endpoint to show up] ******************************************************************************************************************************
ok: [npworker01]

TASK [openshift_node : Fetch bootstrap ignition file locally] *******************************************************************************************************************************
changed: [npworker01]

TASK [openshift_node : Copy pull secret in the directory] ***********************************************************************************************************************************
changed: [npworker01]

TASK [openshift_node : Get release image] ***************************************************************************************************************************************************
changed: [npworker01 -> localhost]

TASK [openshift_node : Set openshift_release_image fact] ************************************************************************************************************************************
ok: [npworker01]

TASK [openshift_node : Pull release image] **************************************************************************************************************************************************
changed: [npworker01]

TASK [openshift_node : Get machine controller daemon image from release image] **************************************************************************************************************
changed: [npworker01]

TASK [openshift_node : Pull MCD image] ******************************************************************************************************************************************************
changed: [npworker01]

TASK [openshift_node : Apply ignition manifest] *********************************************************************************************************************************************
changed: [npworker01]

TASK [openshift_node : Reboot the host and wait for it to come back] ************************************************************************************************************************
changed: [npworker01]

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0
npworker01                 : ok=20   changed=9    unreachable=0    failed=0
```

##### Expected Results
new RHEL compute node to be added to the list of available nodes

##### Observed Results
No error running the ansible play

**Comment by vrutkovs** [comment]
Please attach the output of the playbook run with `-vvv`

**Comment by davis-jacob** [comment]
[scaleup-verbo.txt](https://github.com/openshift/openshift-ansible/files/3577984/scaleup-verbo.txt)

Attached is the -vvv logs

**Comment by vrutkovs** [comment]
The playbook logs look fine, although
`/etc/systemd/system/multi-user.target.wants/kubelet.service already exists. Not making a new symlink` is a bit worrisome - there is already a kubelet service there?

Please check `kubelet.service` logs on the node, it appears the kubelet has been setup correctly but can't reach API server.
Also, check that CSR for the machine have been approved (see https://docs.openshift.com/container-platform/4.1/machine_management/more-rhel-compute.html#installation-approve-csrs_more-rhel-compute)

**Comment by davis-jacob** [comment]
This is the status of kubelet.services.

[root@rhel-compute-3 ~]# systemctl status kubelet.service
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-09-06 02:56:27 EDT; 5s ago
  Process: 34501 ExecStart=/usr/bin/hyperkube kubelet --config=/etc/kubernetes/kubelet.conf --bootstrap-kubeconfig=/etc/kubernetes/kubeconfig --kubeconfig=/var/lib/kubelet/kubeconfig --container-runtime=remote --container-runtime-endpoint=/var/run/crio/crio.sock --allow-privileged --node-labels=node-role.kubernetes.io/worker,node.openshift.io/os_version=${VERSION_ID},node.openshift.io/os_id=${ID} --minimum-container-ttl-duration=6m0s --volume-plugin-dir=/etc/kubernetes/kubelet-plugins/volume/exec --client-ca-file=/etc/kubernetes/kubelet-ca.crt --cloud-provider=vsphere --anonymous-auth=false --v=3 (code=exited, status=255)
  Process: 34498 ExecStartPre=/bin/rm -f /var/lib/kubelet/cpu_manager_state (code=exited, status=0/SUCCESS)
  Process: 34495 ExecStartPre=/bin/mkdir --parents /etc/kubernetes/manifests (code=exited, status=0/SUCCESS)
 Main PID: 34501 (code=exited, status=255)

Sep 06 02:56:27 rhel-compute-3 hyperkube[34501]: I0906 02:56:27.420846   34501 feature_gate.go:206] feature gates: &{map[RotateKubeletServerCertificate:true SupportPodPidsLimi...ion:false]}
Sep 06 02:56:27 rhel-compute-3 hyperkube[34501]: I0906 02:56:27.431836   34501 mount_linux.go:180] Detected OS with systemd
Sep 06 02:56:27 rhel-compute-3 hyperkube[34501]: I0906 02:56:27.431890   34501 server.go:417] Version: v1.13.4+509f0153f
Sep 06 02:56:27 rhel-compute-3 hyperkube[34501]: I0906 02:56:27.431917   34501 feature_gate.go:206] feature gates: &{map[LocalStorageCapacityIsolation:false RotateKubeletServe...tion:true]}
Sep 06 02:56:27 rhel-compute-3 hyperkube[34501]: I0906 02:56:27.431954   34501 feature_gate.go:206] feature gates: &{map[RotateKubeletServerCertificate:true SupportPodPidsLimi...ion:false]}
Sep 06 02:56:27 rhel-compute-3 hyperkube[34501]: W0906 02:56:27.431964   34501 options.go:265] unknown 'kubernetes.io' or 'k8s.io' labels specified with --node-labels: [node-r....io/worker]
Sep 06 02:56:27 rhel-compute-3 hyperkube[34501]: W0906 02:56:27.431971   34501 options.go:266] in 1.15, --node-labels in the 'kubernetes.io' namespace must begin with an allow....kubernetes
Sep 06 02:56:27 rhel-compute-3 hyperkube[34501]: W0906 02:56:27.432010   34501 plugins.go:118] WARNING: vsphere built-in cloud provider is now deprecated. The vSphere provider...ure release
Sep 06 02:56:27 rhel-compute-3 hyperkube[34501]: E0906 02:56:27.432085   34501 vsphere.go:286] Failed to get uuid. err: Failed to match Prefix, UUID read from the file is VCG8BX3006
Sep 06 02:56:27 rhel-compute-3 hyperkube[34501]: F0906 02:56:27.432094   34501 server.go:264] failed to run Kubelet: could not init cloud provider "vsphere": Failed to match P... VCG8BX3006
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by davis-jacob** [comment]
Also all CSR's are approved and nothing pending

**Comment by sdodson** [comment]
` Sep 06 02:56:27 rhel-compute-3 hyperkube[34501]: F0906 02:56:27.432094 34501 server.go:264] failed to run Kubelet: could not init cloud provider "vsphere": Failed to match P... VCG8BX3006`
Can you grab that log untruncated with `journalctl -l`? Either way it's the vsphere provider not initializing.

**Comment by ravitri** [comment]
@vrutkovs @sdodson - Actually, when I talked to Davis we found that the existing cluster was on vSphere and the new node getting added was on baremetal. So the new node was expected to be part of same vSphere cloud. Since it was not, the controller didn't allow it to be added. I suggested having the new node as part of the same cloud. Let me know your thoughts on it too.

**Comment by vrutkovs** [comment]
Seems that's an MCD bug then - it should have updated worker machineconfig with vSphere data.

@runcom you might know what's up here

**Comment by vrutkovs** [comment]
>the existing cluster was on vSphere and the new node getting added was on baremetal

That's not supported. MachineConfigSet is being set for all nodes and they share the same config. If one of the nodes is actually on a different cloudprovider you should have used a different MachineConfigSet for it.

@sdodson sounds like a WONTFIX, WDYT?

**Comment by sdodson** [comment]
Yeah, that's not supported.
/close
