### ISSUE TITLE
/etc/cni/ directory is not created using: yum install openshift-ansible

### ISSUE THREAD

**Issue by oawties0412** [openshift/openshift-ansible#11850]
#### Description

Provide a brief description of your issue here. For example:

So, I have fresh RHEL system and I'm trying to install Openshift-enterprise 3.11, but I'm currently facing some issues with the first step of installation. 

I have a different problem which is in #11825 , so I tried to re-format my previous machine and now I'm currently facing this issue.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
ansible 2.6.19
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch
```

##### Steps To Reproduce
1. yum install openshift-ansible

##### Expected Results
/etc/cni directory will be created

```
The directory /etc/cni missing, does it have something to do with the SDN? 
```

##### Observed Results
Describe what is actually happening.

```
Missing /etc/cni
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
Rhel Version:
Red Hat Enterprise Linux Server release 7.7 (Maipo)

My inventory file: 
[OSEv3:children]
nodes
masters
nfs
etcd
new_nodes

[OSEv3:vars]
template_service_broker_install=false
openshift_master_cluster_public_hostname=None
openshift_master_default_subdomain=cloudapps.10.110.25.147.nip.io
ansible_ssh_user=root
openshift_master_cluster_hostname=None
deployment_type=openshift-enterprise
os_firewall_use_firewalld=True
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

openshift_disable_check=memory_availability,disk_availability,package_version,docker_image_availability,package_availability,package_update,docker_storage

oreg_url=10.110.25.141:8082/openshift3/ose-${component}:${version}
openshift_examples_modify_imagestreams=true
openshift_image_tag=v3.11.43
openshift_pkg_version=-3.11.43

openshift_additional_registry_credentials=[{'host':'10.110.25.141:8082','user':'admin','password':'admin123','test_login':'False', 'tls_verify':'False'}]
[nodes]
cssms004d.openshift.smart.ph openshift_public_ip=10.110.25.147 openshift_ip=10.110.25.147 openshift_public_hostname=cssms004d.openshift.smart.ph openshift_hostname=cssms004d.openshift.smart.ph openshift_node_labels="{'region': 'infra'}" openshift_node_group_name='node-config-master-infra' openshift_schedulable=True ansible_connection=local

[masters]
cssms004d.openshift.smart.ph  openshift_public_ip=10.110.25.147 openshift_ip=10.110.25.147 openshift_public_hostname=cssms004d.openshift.smart.ph openshift_hostname=cssms004d.openshift.smart.ph ansible_connection=local

[nfs]
cssms004d.openshift.smart.ph  openshift_public_ip=10.110.25.147 openshift_ip=10.110.25.147 openshift_public_hostname=cssms004d.openshift.smart.ph openshift_hostname=cssms004d.openshift.smart.ph ansible_connection=local

[etcd]
cssms004d.openshift.smart.ph  openshift_public_ip=10.110.25.147 openshift_ip=10.110.25.147 openshift_public_hostname=cssms004d.openshift.smart.ph openshift_hostname=cssms004d.openshift.smart.ph ansible_connection=local

[new_nodes]


```

Thank you so much. I'm really hoping someone can point me where to look :/. I'm really new into openshift, so I'm still figuring things out.

**Comment by vrutkovs** [comment]
`/etc/cni` should be created by OVS and SDN containers - check pod status and logs in `openshift-sdn` namespace

Similar issue: #7967

**Comment by magick93** [comment]
I'm facing a similar problem. You can find what I've tried on https://stackoverflow.com/questions/57719177/openshift-3-11-install-fails-unable-to-update-cni-config-no-networks-found-in.
