### ISSUE TITLE
No DNS used to resolve hostnames

### ISSUE THREAD

**Issue by ytcisme** [openshift/openshift-ansible#11875]
#### Description

I have no DNS server used to resolve hostnames. Can I just use IP to install  OpenShift Container Platform? I don't hope the nodes use hostname to connect to each other, so how can I do with that?

##### Version

OpenShift 3.11

**Comment by magick93** [comment]
Hi @ytcisme  

Previously I had installed OpenShift without using dns, and just used host file.

However, I'm unable to install OpenShift 3.11 even if I use dns or hostfiles. You can see the issues I'm facing on https://github.com/openshift/openshift-ansible/issues/11874

And as there is no OKD 4 yet, it maybe better to find an alternative to OpenShift.

**Comment by ytcisme** [comment]
> Hi @ytcisme
> 
> Previously I had installed OpenShift without using dns, and just used host file.
> 
> However, I'm unable to install OpenShift 3.11 even if I use dns or hostfiles. You can see the issues I'm facing on #11874
> 
> And as there is no OKD 4 yet, it maybe better to find an alternative to OpenShift.

Hi @magick93

Thanks for your reply. 

I have read your issue, it looked like that the CNI pod(openshift-sdn) was not running. 

I installed OpenShift 3.11 successfully by host file, but I think it's difficult to add a new node, maybe I need to update all of the nodes' host file and restart the dnsmasq. So I hope the nodes use IP directly to connect to each other, not hostname.

**Comment by dszortyka** [comment]
Hello @ytcisme ,
By chance, do you know how to manage/start the openshift-sdn? Hopefully to get rid of error **"Unable to update cni config: No networks found in /etc/cni/net.d"**

**Comment by magick93** [comment]
Hi Daniel

I'm not sure why the issue comes up. But I was able to move passed this
issue by first running the following, custom, playbook:

```

---- name: Prereqs  hosts: all  tasks:          - name: create
/etc/cni/net.d      file:        path: /etc/cni/net.d        state:
directory      - name: create /etc/cni/net.d      file:        path:
/etc/cni/net.d        state: directory     - name: Create
80-openshift-network.conf      copy:        dest:
"/etc/cni/net.d/80-openshift-network.conf"        content: |
{ "cniVersion": "0.2.0", "name": "openshift-sdn", "type":
"openshift-sdn" }
```
