### ISSUE TITLE
Openshift installation failed waiting on control pane pod 

### ISSUE THREAD

**Issue by olawale241** [openshift/openshift-ansible#11885]
#### Description

Provide a brief description of your issue here. For example:
I tried to install openshift 3.9 following  documentation , the installation didn't complete and was stuck on waiting for controller node 

TASK [openshift_control_plane : Wait for control plane pods to appear] *************************************
FAILED - RETRYING: Wait for control plane pods to appear (60 retries

##### Version
Openshift 3.9

Please put the following version information in the code block
indicated below.

##### Observed Results

TASK [openshift_control_plane : Wait for control plane pods to appear] *************************************
FAILED - RETRYING: Wait for control plane pods to appear (60 retries

```

##### Additional Information

**Comment by vrutkovs** [comment]
Please attach the inventory and ansible-playbook -vvv logs

**Comment by olawale241** [comment]
**INVENTORY FILE** 
## Ansible user who can login to all nodes through SSH (e.g. ssh root@os-master1)
ansible_user=root

## Deployment type: "openshift-enterprise" or "origin"
openshift_deployment_type=origin
deployment_type=origin

## Specifies the major version
openshift_release=v3.9
openshift_pkg_version=-3.9.0
openshift_image_tag=v3.9.0
openshift_service_catalog_image_version=v3.9.0
template_service_broker_image_version=v3.9.0
openshift_metrics_image_version="v3.9"
openshift_logging_image_version="v3.9"
openshift_logging_elasticsearch_proxy_image_version="v1.0.0"
osm_use_cockpit=true
openshift_metrics_install_metrics=True
openshift_logging_install_logging=True


## Service address space,  /16 = 65,534 IPs
openshift_portal_net=172.30.0.0/16

## Pod address space
osm_cluster_network_cidr=10.128.0.0/14

## Subnet Length of each node, 9 = 510 IPs
osm_host_subnet_length=9

## Master API  port
openshift_master_api_port=443

## Master console port  (e.g. https://console.openshift.identity.lsloyalty.com:443)
openshift_master_console_port=443

## Clustering method
openshift_master_cluster_method=native

## Hostname used by nodes and other cluster internals
openshift_master_cluster_hostname=opmaster.identity.lsloyalty.com

## Hostname used by platform users
openshift_master_cluster_public_hostname=opmaster.identity.lsloyalty.com

## Application wildcard subdomain
openshift_master_default_subdomain=apps.identity.lsloyalty.com

## identity provider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

## Users being created in the cluster
#openshift_master_htpasswd_users={'admin': '$apr1$Y7xqqalc$Mhtfi2EH5cwY6bLaFJWfm0', 'user1': '$apr1$HYdB7Vye$J9GFboUG/TIG3IYl0c4LV0'}
openshift_master_htpasswd_users={'admin': '$apr1$L1hX64LA$bPx2oUDzuGxnbPzfxv7Ni.', 'user1': '$apr1$M/ueXnE8$QhYHaSu.GkpvM.GC8Ws440'}

## Persistent storage, NFS
openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_host=nfsshared.identity.lsloyalty.com.
openshift_hosted_registry_storage_nfs_directory=/volume1/SHARED
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=10Gi


## Other vars
containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

#NFS check bug
openshift_enable_unsupported_configurations=True
#Another Bug 1569476
skip_sanity_checks=true

openshift_node_kubelet_args="{'eviction-hard': ['memory.available<100Mi'], 'minimum-container-ttl-duration': ['10s'], 'maximum-dead-containers-per-container': ['2'], 'maximum-dead-containers': ['5'], 'pods-per-core': ['10'], 'max-pods': ['25'], 'image-gc-high-threshold': ['80'], 'image-gc-low-threshold': ['60']}"

[OSEv3:vars]

[masters]
opmaster.identity.lsloyalty.com

[etcd]
opmaster.identity.lsloyalty.com

[nodes]
opmaster.identity.lsloyalty.com openshift_node_labels="{'region': 'master'}"
opnode1.identity.lsloyalty.com openshift_node_labels="{'region': 'infra'}"
opnode2.identity.lsloyalty.com openshift_node_labels="{'region': 'compute'}"
opnode3.identity.lsloyalty.com openshift_node_labels="{'region': 'compute'}"

**NOTICED ERROR WHILE INSTALLING
[inventory filepdf.pdf](https://github.com/openshift/openshift-ansible/files/3590204/inventory.filepdf.pdf)

** 

09 September 2019  07:12:23 -0400 (0:00:00.047)       0:04:25.228 ******
fatal: [opmaster.identity.lsloyalty.com]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service origin-master: host"}

**ERROR AFTER COMPLETION**

**Comment by olawale241** [comment]
[error.pdf](https://github.com/openshift/openshift-ansible/files/3590260/error.pdf)

**Comment by olawale241** [comment]
Attached is the inventory file , error file and eventually this output 


openshift_master : Start and enable master api ---------------------------------------------------------------------------------------------------------------------------------------------- 10.65s
openshift_master : Start and enable master controller service ------------------------------------------------------------------------------------------------------------------------------- 10.64s


Failure summary:


  1. Hosts:    opmaster.identity.lsloyalty.com
     Play:     Poll for hosted pod deployments
     Task:     Poll for OpenShift pod deployment success
     Message:  All items completed
[error.pdf](https://github.com/openshift/openshift-ansible/files/3590325/error.pdf)
[inventory filepdf.pdf](https://github.com/openshift/openshift-ansible/files/3590326/inventory.filepdf.pdf)

**Comment by olawale241** [comment]
[root@opmaster ~]# oc get nodes
NAME                              STATUS    ROLES     AGE       VERSION
opmaster.identity.lsloyalty.com   Ready     master    42m       v1.9.1+a0ce1bc657
opnode1.identity.lsloyalty.com    Ready     <none>    37m       v1.9.1+a0ce1bc657
opnode2.identity.lsloyalty.com    Ready     compute   37m       v1.9.1+a0ce1bc657
opnode3.identity.lsloyalty.com    Ready     compute   37m       v1.9.1+a0ce1bc657

[root@opmaster ~]# oc get pods -o wide
NAME                       READY     STATUS    RESTARTS   AGE       IP              NODE
docker-registry-1-deploy   0/1       Error     0          34m       10.131.0.3      opnode1.identity.lsloyalty.com
router-1-llw8f             1/1       Running   0          34m       192.168.1.211   opnode1.identity.lsloyalty.com

[root@opmaster ~]# oc get events
LAST SEEN   FIRST SEEN   COUNT     NAME                                               KIND                    SUBOBJECT                     TYPE      REASON                        SOURCE                                           MESSAGE
35m         35m          1         docker-registry-1-deploy.15c2c0ec3eb31ae2          Pod                                                   Normal    Scheduled                     default-scheduler                                Successfully assigned docker-registry-1-deploy to opnode1.identity.lsloyalty.com
35m         35m          1         docker-registry-1-deploy.15c2c0ec4a916949          Pod                                                   Normal    SuccessfulMountVolume         kubelet, opnode1.identity.lsloyalty.com          MountVolume.SetUp succeeded for volume "deployer-token-jnkj5"
35m         35m          1         docker-registry-1-deploy.15c2c0ecf48b08ad          Pod                     spec.containers{deployment}   Normal    Pulled                        kubelet, opnode1.identity.lsloyalty.com          Container image "openshift/origin-deployer:v3.9.0" already present on machine
35m         35m          1         docker-registry-1-deploy.15c2c0ed1ed7a697          Pod                     spec.containers{deployment}   Normal    Created                       kubelet, opnode1.identity.lsloyalty.com          Created container
35m         35m          1         docker-registry-1-deploy.15c2c0ed3487d891          Pod                     spec.containers{deployment}   Normal    Started                       kubelet, opnode1.identity.lsloyalty.com          Started container
35m         35m          1         docker-registry-1-xjscz.15c2c0edaebd1cd3           Pod                                                   Normal    Scheduled                     default-scheduler                                Successfully assigned docker-registry-1-xjscz to opnode1.identity.lsloyalty.com
35m         35m          1         docker-registry-1-xjscz.15c2c0edc1c7034a           Pod                                                   Normal    SuccessfulMountVolume         kubelet, opnode1.identity.lsloyalty.com          MountVolume.SetUp succeeded for volume "registry-certificates"
35m         35m          1         docker-registry-1-xjscz.15c2c0edc26c513a           Pod                                                   Normal    SuccessfulMountVolume         kubelet, opnode1.identity.lsloyalty.com          MountVolume.SetUp succeeded for volume "registry-token-f8nzb"
26m         35m          12        docker-registry-1-xjscz.15c2c0edc892936d           Pod                                                   Warning   FailedMount                   kubelet, opnode1.identity.lsloyalty.com          MountVolume.SetUp failed for volume "registry-volume" : exit status 32
26m         33m          4         docker-registry-1-xjscz.15c2c10a542759cf           Pod                                                   Warning   FailedMount                   kubelet, opnode1.identity.lsloyalty.com          Unable to mount volumes for pod "docker-registry-1-xjscz_default(2c48b40e-d2f3-11e9-a71f-000c299537e0)": timeout expired waiting for volumes to attach/mount for pod "default"/"docker-registry-1-xjscz". list of unattached/unmounted volumes=[registry-storage]
23m         23m          1         docker-registry-1-xjscz.15c2c18979b33fcb           Pod                                                   Warning   FailedMount                   kubelet, opnode1.identity.lsloyalty.com          Unable to mount volumes for pod "docker-registry-1-xjscz_default(2c48b40e-d2f3-11e9-a71f-000c299537e0)": timeout expired waiting for volumes to attach/mount for pod "default"/"docker-registry-1-xjscz". list of unattached/unmounted volumes=[registry-storage registry-certificates registry-token-f8nzb]
35m         35m          1         docker-registry-1.15c2c0edae394aa4                 ReplicationController                                 Normal    SuccessfulCreate              replication-controller                           Created pod: docker-registry-1-xjscz
25m         25m          1         docker-registry-1.15c2c179a74389f9                 ReplicationController                                 Normal    SuccessfulDelete              replication-controller                           Deleted pod: docker-registry-1-xjscz
35m         35m          1         docker-registry.15c2c0ec3c7010b7                   DeploymentConfig                                      Normal    DeploymentCreated             deploymentconfig-controller                      Created new replication controller "docker-registry-1" for version 1
25m         25m          1         docker-registry.15c2c179a5f9cdd0                   DeploymentConfig                                      Normal    ReplicationControllerScaled   deploymentconfig-controller                      Scaled replication controller "docker-registry-1" from 1 to 0
43m         43m          1         opmaster.identity.lsloyalty.com.15c2c07285204664   Node                                                  Normal    Starting                      kubelet, opmaster.identity.lsloyalty.com         Starting kubelet.
43m         43m          2         opmaster.identity.lsloyalty.com.15c2c072869e968e   Node                                                  Normal    NodeHasSufficientDisk         kubelet, opmaster.identity.lsloyalty.com         Node opmaster.identity.lsloyalty.com status is now: NodeHasSufficientDisk
43m         43m          2         opmaster.identity.lsloyalty.com.15c2c072869fa57f   Node                                                  Normal    NodeHasSufficientMemory       kubelet, opmaster.identity.lsloyalty.com         Node opmaster.identity.lsloyalty.com status is now: NodeHasSufficientMemory
43m         43m          2         opmaster.identity.lsloyalty.com.15c2c07286a0232e   Node                                                  Normal    NodeHasNoDiskPressure         kubelet, opmaster.identity.lsloyalty.com         Node opmaster.identity.lsloyalty.com status is now: NodeHasNoDiskPressure
43m         43m          1         opmaster.identity.lsloyalty.com.15c2c0728f362f78   Node                                                  Normal    NodeAllocatableEnforced       kubelet, opmaster.identity.lsloyalty.com         Updated Node Allocatable limit across pods
43m         43m          1         opmaster.identity.lsloyalty.com.15c2c072a17ad544   Node                                                  Normal    RegisteredNode                node-controller                                  Node opmaster.identity.lsloyalty.com event: Registered Node opmaster.identity.lsloyalty.com in Controller
43m         43m          1         opmaster.identity.lsloyalty.com.15c2c072d75143c4   Node                                                  Normal    Starting                      openshift-sdn, opmaster.identity.lsloyalty.com   Starting openshift-sdn.
43m         43m          1         opmaster.identity.lsloyalty.com.15c2c074eee7fb0c   Node                                                  Normal    NodeReady                     kubelet, opmaster.identity.lsloyalty.com         Node opmaster.identity.lsloyalty.com status is now: NodeReady
38m         38m          1         opnode1.identity.lsloyalty.com.15c2c0bcc54ed156    Node                                                  Normal    Starting                      kubelet, opnode1.identity.lsloyalty.com          Starting kubelet.
38m         38m          2         opnode1.identity.lsloyalty.com.15c2c0bcc7799cc5    Node                                                  Normal    NodeHasSufficientDisk         kubelet, opnode1.identity.lsloyalty.com          Node opnode1.identity.lsloyalty.com status is now: NodeHasSufficientDisk
38m         38m          2         opnode1.identity.lsloyalty.com.15c2c0bcc77a75ec    Node                                                  Normal    NodeHasSufficientMemory       kubelet, opnode1.identity.lsloyalty.com          Node opnode1.identity.lsloyalty.com status is now: NodeHasSufficientMemory
38m         38m          2         opnode1.identity.lsloyalty.com.15c2c0bcc77b00c6    Node                                                  Normal    NodeHasNoDiskPressure         kubelet, opnode1.identity.lsloyalty.com          Node opnode1.identity.lsloyalty.com status is now: NodeHasNoDiskPressure
38m         38m          1         opnode1.identity.lsloyalty.com.15c2c0bcd11cb1a4    Node                                                  Normal    NodeAllocatableEnforced       kubelet, opnode1.identity.lsloyalty.com          Updated Node Allocatable limit across pods
38m         38m          1         opnode1.identity.lsloyalty.com.15c2c0bd242449c4    Node                                                  Normal    RegisteredNode                node-controller                                  Node opnode1.identity.lsloyalty.com event: Registered Node opnode1.identity.lsloyalty.com in Controller
38m         38m          1         opnode1.identity.lsloyalty.com.15c2c0bd6af2d11e    Node                                                  Normal    Starting                      openshift-sdn, opnode1.identity.lsloyalty.com    Starting openshift-sdn.
38m         38m          1         opnode1.identity.lsloyalty.com.15c2c0bf2dc14141    Node                                                  Normal    NodeReady                     kubelet, opnode1.identity.lsloyalty.com          Node opnode1.identity.lsloyalty.com status is now: NodeReady
38m         38m          1         opnode2.identity.lsloyalty.com.15c2c0bd2421dce8    Node                                                  Normal    RegisteredNode                node-controller                                  Node opnode2.identity.lsloyalty.com event: Registered Node opnode2.identity.lsloyalty.com in Controller
36m         36m          1         opnode2.identity.lsloyalty.com.15c2c0df0a1af128    Node                                                  Normal    Starting                      kubelet, opnode2.identity.lsloyalty.com          Starting kubelet.
36m         36m          2         opnode2.identity.lsloyalty.com.15c2c0df0cd452cb    Node                                                  Normal    NodeHasSufficientDisk         kubelet, opnode2.identity.lsloyalty.com          Node opnode2.identity.lsloyalty.com status is now: NodeHasSufficientDisk
36m         36m          2         opnode2.identity.lsloyalty.com.15c2c0df0cd4c574    Node                                                  Normal    NodeHasSufficientMemory       kubelet, opnode2.identity.lsloyalty.com          Node opnode2.identity.lsloyalty.com status is now: NodeHasSufficientMemory
36m         36m          2         opnode2.identity.lsloyalty.com.15c2c0df0cd5088d    Node                                                  Normal    NodeHasNoDiskPressure         kubelet, opnode2.identity.lsloyalty.com          Node opnode2.identity.lsloyalty.com status is now: NodeHasNoDiskPressure
36m         36m          1         opnode2.identity.lsloyalty.com.15c2c0df14920f3b    Node                                                  Normal    NodeAllocatableEnforced       kubelet, opnode2.identity.lsloyalty.com          Updated Node Allocatable limit across pods
36m         36m          1         opnode2.identity.lsloyalty.com.15c2c0df99fbec73    Node                                                  Normal    Starting                      openshift-sdn, opnode2.identity.lsloyalty.com    Starting openshift-sdn.
35m         35m          1         opnode2.identity.lsloyalty.com.15c2c0e170c41a57    Node                                                  Normal    NodeReady                     kubelet, opnode2.identity.lsloyalty.com          Node opnode2.identity.lsloyalty.com status is now: NodeReady
38m         38m          1         opnode3.identity.lsloyalty.com.15c2c0bcc3600186    Node                                                  Normal    Starting                      kubelet, opnode3.identity.lsloyalty.com          Starting kubelet.
38m         38m          2         opnode3.identity.lsloyalty.com.15c2c0bcc5950852    Node                                                  Normal    NodeHasSufficientDisk         kubelet, opnode3.identity.lsloyalty.com          Node opnode3.identity.lsloyalty.com status is now: NodeHasSufficientDisk
38m         38m          2         opnode3.identity.lsloyalty.com.15c2c0bcc5960015    Node                                                  Normal    NodeHasSufficientMemory       kubelet, opnode3.identity.lsloyalty.com          Node opnode3.identity.lsloyalty.com status is now: NodeHasSufficientMemory
38m         38m          2         opnode3.identity.lsloyalty.com.15c2c0bcc596ab93    Node                                                  Normal    NodeHasNoDiskPressure         kubelet, opnode3.identity.lsloyalty.com          Node opnode3.identity.lsloyalty.com status is now: NodeHasNoDiskPressure
38m         38m          1         opnode3.identity.lsloyalty.com.15c2c0bccf14323e    Node                                                  Normal    NodeAllocatableEnforced       kubelet, opnode3.identity.lsloyalty.com          Updated Node Allocatable limit across pods
38m         38m          1         opnode3.identity.lsloyalty.com.15c2c0bd2422d5c8    Node                                                  Normal    RegisteredNode                node-controller                                  Node opnode3.identity.lsloyalty.com event: Registered Node opnode3.identity.lsloyalty.com in Controller
38m         38m          1         opnode3.identity.lsloyalty.com.15c2c0bd6815433b    Node                                                  Normal    Starting                      openshift-sdn, opnode3.identity.lsloyalty.com    Starting openshift-sdn.
38m         38m          1         opnode3.identity.lsloyalty.com.15c2c0bf2c067129    Node                                                  Normal    NodeReady                     kubelet, opnode3.identity.lsloyalty.com          Node opnode3.identity.lsloyalty.com status is now: NodeReady
35m         35m          1         router-1-deploy.15c2c0e53e83a417                   Pod                                                   Normal    Scheduled                     default-scheduler                                Successfully assigned router-1-deploy to opnode1.identity.lsloyalty.com
35m         35m          1         router-1-deploy.15c2c0e5575164aa                   Pod                                                   Normal    SuccessfulMountVolume         kubelet, opnode1.identity.lsloyalty.com          MountVolume.SetUp succeeded for volume "deployer-token-jnkj5"
35m         35m          1         router-1-deploy.15c2c0e6edf5bdb2                   Pod                     spec.containers{deployment}   Normal    Pulling                       kubelet, opnode1.identity.lsloyalty.com          pulling image "openshift/origin-deployer:v3.9.0"
35m         35m          1         router-1-deploy.15c2c0e72355704f                   Pod                     spec.containers{deployment}   Normal    Pulled                        kubelet, opnode1.identity.lsloyalty.com          Successfully pulled image "openshift/origin-deployer:v3.9.0"
35m         35m          1         router-1-deploy.15c2c0e74ff41ece                   Pod                     spec.containers{deployment}   Normal    Created                       kubelet, opnode1.identity.lsloyalty.com          Created container
35m         35m          1         router-1-deploy.15c2c0e76dfae765                   Pod                     spec.containers{deployment}   Normal    Started                       kubelet, opnode1.identity.lsloyalty.com          Started container
35m         35m          1         router-1-deploy.15c2c0ec990e8df8                   Pod                     spec.containers{deployment}   Normal    Killing                       kubelet, opnode1.identity.lsloyalty.com          Killing container with id docker://deployment:Need to kill Pod
35m         35m          1         router-1-llw8f.15c2c0e7e5db8464                    Pod                                                   Normal    Scheduled                     default-scheduler                                Successfully assigned router-1-llw8f to opnode1.identity.lsloyalty.com
35m         35m          1         router-1-llw8f.15c2c0e7f70b113c                    Pod                                                   Normal    SuccessfulMountVolume         kubelet, opnode1.identity.lsloyalty.com          MountVolume.SetUp succeeded for volume "server-certificate"
35m         35m          1         router-1-llw8f.15c2c0e7fad11236                    Pod                                                   Normal    SuccessfulMountVolume         kubelet, opnode1.identity.lsloyalty.com          MountVolume.SetUp succeeded for volume "router-token-gwq7t"
35m         35m          1         router-1-llw8f.15c2c0e8369ecb88                    Pod                     spec.containers{router}       Normal    Pulling                       kubelet, opnode1.identity.lsloyalty.com          pulling image "openshift/origin-haproxy-router:v3.9.0"
35m         35m          1         router-1-llw8f.15c2c0e912807695                    Pod                     spec.containers{router}       Normal    Pulled                        kubelet, opnode1.identity.lsloyalty.com          Successfully pulled image "openshift/origin-haproxy-router:v3.9.0"
35m         35m          1         router-1-llw8f.15c2c0e92f858b96                    Pod                     spec.containers{router}       Normal    Created                       kubelet, opnode1.identity.lsloyalty.com          Created container
35m         35m          1         router-1-llw8f.15c2c0e946bf1d99                    Pod                     spec.containers{router}       Normal    Started                       kubelet, opnode1.identity.lsloyalty.com          Started container
35m         35m          1         router-1.15c2c0e7e56b0084                          ReplicationController                                 Normal    SuccessfulCreate              replication-controller                           Created pod: router-1-llw8f
35m         35m          1         router.15c2c0e53c21bab5                            DeploymentConfig                                      Normal    DeploymentCreated             deploymentconfig-controller                      Created new replication controller "router-1" for version 1

**Comment by olawale241** [comment]
attched the files , i noticed that the controller is deployed but the console is not .
    On Monday, September 9, 2019, 04:40:15 a.m. CDT, Vadim Rutkovsky <notifications@github.com> wrote:  
 
 
Please attach the inventory and ansible-playbook -vvv logs
