### ISSUE TITLE
Enabling multiple etcds for sharding different resource objects.

### ISSUE THREAD

**Issue by timothysc** [openshift/openshift-ansible#1188]
https://trello.com/c/CM3C5Wak/8-sharding-to-an-auxillary-etcd-users-projects-events

The upstream enablement already exists for events, but it will require the following several changes:
- creation of potentially multiple etcds for different resource objects
- add the configuration to the api-server options
- ensure proper shared keys are populated
  ...? @rrati 

/cc @abhgupta

**Comment by timothysc** [comment]
xref: https://github.com/openshift/origin/pull/6838

**Comment by detiber** [comment]
I've created the following trello card for this: https://trello.com/c/oHzBQDjU

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
