### ISSUE TITLE
Improve error checking of openshift_pkg_version

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#1189]
openshift_pkg_version should provide better error checking, instead of just faililng at the yum install tasks...

For example, specifying '-3.0' results in:
[0;31mfailed: [ose30-node02.ose.local] => {"changed": false, "failed": true, "rc": 0, "results": []}[0m
[0;31mmsg: No Package matching 'openshift-3.0' found available, installed or updated[0m

**Comment by anweiss** [comment]
Running in to this as well. What is the correct way to specify a package version? I've tried `openshift_pkg_version=-1.1` with `deployment_type=origin` and am seeing the error.

**Comment by detiber** [comment]
@anweiss This PR should have addressed the issue you were seeing with openshift_pkg_version: https://github.com/openshift/openshift-ansible/pull/1276

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
