### ISSUE TITLE
Supported environments should be moved to config

### ISSUE THREAD

**Issue by danmcp** [openshift/openshift-ansible#119]
Ex:

      dmcphers@mcpherson:~/gocode/src/github.com/openshift/openshift-ansible (master)$ ./cluster.sh --help
      ./cluster.sh : [create|terminate|update|list] { GCE environment tag}

      Supported environment tags:
            SUPPORTED_ENVS = %w(prod stg int twiest gshipley kint test jhonce amint tdint lint jdetiber)

shows ids of developers today.  Which is a bit off-putting to someone external looking at the project.  It makes it seem like it's a pet project where you have to get your name on to a list before you can use it.  I would suggest you move this to optional config.  Maybe ~/.openshift-ansible with properties like:

SUGGESTED_ENVS=prod,stg,int
ONLY_ALLOW_SUGGESTED_ENVS=false

**Comment by danmcp** [comment]
@twiest FYI

**Comment by twiest** [comment]
@danmcp thanks

**Comment by detiber** [comment]
@twiest @danmcp The cluster changes that @jwhonce has lined up does away with this.

**Comment by danmcp** [comment]
@detiber Is there still the ability to restrict to specific environments if so desired?  I believe @twiest still has that use case.

**Comment by detiber** [comment]
@danmcp it currently does not (It's also missing aws support and some of the gce support is still missing as well). As a stop gap, I see no issues with someone running with making the changes in cloud.rb. 

@jwhonce @twiest thoughts?

**Comment by twiest** [comment]
@detiber python cluster replaces cluster.sh, it does not replace cloud.rb. Leave cloud.rb alone, we use it for other stuff.

I do still have the use case for having the environments listed, but I like Dan's suggestion of specifying the valid environments in a config file. I'm fine with how the python cluster is for now, but I'll be looking to change it in the future to have that config file feature (optional, of course).
