### ISSUE TITLE
getting Fail openshift_kubelet_name_override for new hosts in ansible logs

### ISSUE THREAD

**Issue by aliartiza75** [openshift/openshift-ansible#11929]
#### Description

I am getting this error

```
PLAY [Fail openshift_kubelet_name_override for new hosts]
```

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
ansible 2.6.19

If you're operating from a **git clone**:

* The output of `git describe`
NIL
If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`
openshift-ansible-3.11.146-1.git.0.fcedb45.el7.noarch

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```
##### Steps To Reproduce
NIL

##### Expected Results
Openshift cluster is provisioned successfully.

##### Observed Results
Describe what is actually happening.
I am getting the error given below;

```
PLAY [Fail openshift_kubelet_name_override for new hosts]
```
The issue is that I have tried multiple versions of openshift ansible but still getting the same error. Although this [issue](https://bugzilla.redhat.com/show_bug.cgi?id=1641085) has been solved. But after reading resolution details I didn't understand anything. Can you guys kindly explain how to resolve this issue? 

```
PLAY [Fail openshift_kubelet_name_override for new hosts]
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)

Red Hat Enterprise Linux Server release 7.6 (Maipo)

* Your inventory file (especially any non-standard configuration parameters)
```
OSEv3:
  children:
    masters:
      hosts:
        master.openshift.local: ""
    etcd:
      hosts:
        master1.openshift.local: ""
    nodes:
      hosts:
        master1.openshift.local:
          openshift_node_group_name: node-config-master
        infra1.openshift.local:
          openshift_node_group_name: node-config-infra
        node-databas1.openshift.local:
          openshift_node_group_name: node-config-compute-databas
  vars:
    ansible_become: true
    ansible_ssh_user: XX
    ansible_user: XX
    containerized: true
    timeout: 60
    openshift_deployment_type: openshift-enterprise
    openshift_release: "v3.11"
    os_sdn_network_plugin_name: 'redhat/openshift-ovs-networkpolicy'
    openshift_disable_check: X
    openshift_node_groups: XXXX
    openshift_master_identity_providers: XXXX
    openshift_master_cluster_hostname: master.X.com
    openshift_master_cluster_public_hostname: X.com
    openshift_master_default_subdomain: X.com
    openshift_repos_enable_testing: false        
    openshift_master_bootstrap_auto_approve: "true"
    openshift_cloudprovider_kind: "azure"
    openshift_cloudprovider_azure_location: "X"
    openshift_clusterid: X
    template_service_broker_install: "false"
    openshift_cluster_monitoring_operator_install: "false"
    openshift_logging_install_logging: "false"
    openshift_logging_es_memory_limit: "1024M"
    openshift_logging_es_nodeselector:
      node-role.kubernetes.io/compute: "true"
    openshift_cluster_admin_users:
    XXXXXX

**Comment by aliartiza75** [comment]
the variable `openshift_kubelet_name_override` is defined in this file given below, can some kindly explain what is the purpose of this variable?

https://github.com/openshift/openshift-ansible/blob/5218f3c57ea9b5b5570bf0bc61b9bfea6df0632d/images/installer/root/usr/local/bin/generate#L189

**Comment by aliartiza75** [comment]
@vrutkovs @mtnbikenc need help for this issue.  thank you

**Comment by aliartiza75** [comment]
how to undefine the `openshift_kubelet_name_override` variable?

**Comment by vrutkovs** [comment]
Please include necessary information:
* full inventory
* which playbook are you running and its output with `-vvv` switch

>openshift-ansible/images/installer/root/usr/local/bin/generate

This is a binary to generate openshift inventory, however its no longer being used

**Comment by aliartiza75** [comment]
@vrutkovs the issue is being generated in this [file](https://github.com/openshift/openshift-ansible/blob/5218f3c57ea9b5b5570bf0bc61b9bfea6df0632d/playbooks/prerequisites.yml#L3). By looking at this file I came to conclusion that the error is being generated due to this condition:

```
- openshift_kubelet_name_override is defined
- openshift_cloudprovider_kind | default('', true) != 'azure'
``` 

on line 10  and 11.

The question that I wanna ask is that how can I undefine `openshift_kubelet_name_override` and assign `azure` to `openshift_cloudprovider_kind` variable.

**Comment by aliartiza75** [comment]
not stale

**Comment by aliartiza75** [comment]
not close
