### ISSUE TITLE
Running redeploy-certificates.yml fails in Update metrics-server certificates

### ISSUE THREAD

**Issue by patrick-oneill** [openshift/openshift-ansible#11946]
#### Description
When redploying the certificates to OCP 3.11 it failed on the "Update metrics-server certificates" section as follows:

TASK [Create temp directory for all our templates] 
fatal: [working-shepherd-icp-mst.fyre.ibm.com]: FAILED! => {"msg": "The conditional check 'openshift_metrics_server_install | bool' failed. The error was: error while evaluating conditional (openshift_metrics_server_install | bool): 'openshift_metrics_server_install' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/playbooks/metrics-server/private/redeploy-certificates.yml': line 13, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Create temp directory for all our templates\n    ^ here\n"}

##### Version
```
ansible 2.6.19

```

##### Steps To Reproduce
1. Clean Install OCP v3.11.146
2. Run a redeploy of the certificates as follows
ansible-playbook -v -i /root/openshift-ansible/inventory/hosts /usr/share/ansible/openshift-ansible/playbooks/redeploy-certificates.yml

##### Expected Results
New certs to be deployed with no errors

##### Observed Results
Playbook fails on metrics-server updates

The file it references has this content
```---
- name: Update metrics-server certificates
  hosts: oo_first_master
  roles:
  - lib_openshift
  - openshift_facts
  tasks:
  - name: Create temp directory for doing work in on target
    command: mktemp -td openshift-metrics-server-ansible-XXXXXX
    register: mktemp
    changed_when: False

  - name: Create temp directory for all our templates
    file:
      path: "{{ mktemp.stdout }}/templates"
      state: directory
      mode: 0755
    changed_when: False
    when: openshift_metrics_server_install | bool

```
The error given is
```
PLAY [Update metrics-server certificates] 

TASK [Gathering Facts] 
ok: [working-shepherd]

TASK [Create temp directory for doing work in on target] 
ok: [working-shepherd] => {"changed": false, "cmd": ["mktemp", "-td", "openshift-metrics-server-ansible-XXXXXX"], "delta": "0:00:00.991337", "end": "2019-10-10 10:36:53.334036", "rc": 0, "start": "2019-10-10 10:36:52.342699", "stderr": "", "stderr_lines": [], "stdout": "/tmp/openshift-metrics-server-ansible-4VUlYR", "stdout_lines": ["/tmp/openshift-metrics-server-ansible-4VUlYR"]}

TASK [Create temp directory for all our templates] 
fatal: [working-shepherd]: FAILED! => {"msg": "The conditional check 'openshift_metrics_server_install | bool' failed. The error was: error while evaluating conditional (openshift_metrics_server_install | bool): 'openshift_metrics_server_install' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/playbooks/metrics-server/private/redeploy-certificates.yml': line 13, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Create temp directory for all our templates\n    ^ here\n"}
	to retry, use: --limit @/usr/share/ansible/openshift-ansible/playbooks/redeploy-certificates.retry
```

##### Additional Information
I'm using RHEL 7.6
And I added these lines to my hosts file before running the reploy playbook
```
openshift_master_overwrite_named_certificates=true
openshift_master_named_certificates=[{"certfile": "/root/installers/cert/shepherd_cert.pem", "keyfile": "/root/installers/cert/server.key", "names": ["working-shepherd-icp-mst"], "cafile": "/root/installers/cert/cacert.pem"}]

openshift_hosted_router_certificate={"certfile": "/root/installers/cert/shepherd_cert.pem", "keyfile": "/root/installers/cert/server.key", "cafile": "/root/installers/cert/cacert.pem"}
```

**Comment by bostrt** [comment]
Same issue has been reported here and has some traction: https://bugzilla.redhat.com/show_bug.cgi?id=1759835

**Comment by Shivkumar13** [comment]
@patrick-oneill 

Can you try to set the below in the inventory, and rerun the redeploy-certificates.yaml playbook?

openshift_metrics_server_install=false

**Comment by Shivkumar13** [comment]
@patrick-oneill 
I could see that this was a bug, which is fixed in the below openshift-ansible version.
openshift-ansible-3.11.154-1.git.0.7a11cbe.el7.noarch.rpm

Try to update the same package and try to redeploy.

**Comment by patrick-oneill** [comment]
Setting `openshift_metrics_server_install=false` is the workaround and I did that last year to get passed the issue.

We are no longer using OCP3.11 so I no longer have an environment to test with. The issue can be closed if you feel it is fixed.
