### ISSUE TITLE
How to override masterIP value in master-config.yaml in ansible hosts file

### ISSUE THREAD

**Issue by eliu** [openshift/openshift-ansible#11950]
#### Description

I need a method or existing ansible vars that can help me override `masterIP` value in `master-config.yaml` in ansible hosts file.

I have 2 network interfaces in my machine and I need configurable way to use IP from specified network interface as the masterIP.

##### Version

ansible `2.6.6`
openshift-ansible branch `release-3.11`

**Comment by nmr** [comment]
I think that my pull request should solve this problem:
https://github.com/openshift/openshift-ansible/pull/11951

**Comment by eliu** [comment]
@nmr their approval workflow moves slowly like sloth ...  -.-'
