### ISSUE TITLE
Cannot use image_name with space character in name on OpenStack

### ISSUE THREAD

**Issue by akram** [openshift/openshift-ansible#1195]
Hi,

I am trying the a cluster on OpenStack with an image which contains space ' ' caracter in image name name:

```
./bin/cluster create  -o image_name='RHEL 7.2 x86_64' -o external_net=public -o floating_ip_pool=public openstack akram
```

The creation fails with the OpenStack heat message:

```
| stack_status          | UPDATE_FAILED                                                                                                                                   |
| stack_status_reason   | resources.infra_nodes: resources[0]: Property error:                                                                                            |
|                       | resources.server.properties.image: Error validating                                                                                             |
|                       | value u'RHEL': The Image (RHEL) could not be found.                                                                                             |
```

The image_name and probably other options needs to be escaped. moreover the .split function used in bin/cluster python script is called with a second parameter split("=", 1) , which should cut the number of parameters to pass.

**Comment by detiber** [comment]
@akram do you have a suggested fix for this? I'm not sure when the internal team would be able to address it.

**Comment by michaelgugino** [comment]
The affected code path has been removed.

Closing as this bug is no longer valid.
