### ISSUE TITLE
README_AWS refers to PrivateKey, which seems to not exist

### ISSUE THREAD

**Issue by donovanmuller** [openshift/openshift-ansible#1196]
The paragraph on "[(Optional) Setup your $HOME/.ssh/config file](https://github.com/openshift/openshift-ansible/blob/master/README_AWS.md#optional-setup-your-homesshconfig-file)" refers to adding the `PrivateKey` entry in your `.ssh/config`.

However, the `PrivateKey` option does not seem to [exist](http://linux.die.net/man/5/ssh_config) and fails with the following error when running the "Wait for user steup" task:

```
stderr: /Users/xxx/.ssh/config: line 3: Bad configuration option: privatekey
/Users/xxx/.ssh/config: terminating, 1 bad configuration options
```

I believe this should be `IdentityFile` instead.
I.e.

```
Host *.compute-1.amazonaws.com
  IdentityFile $HOME/.ssh/my_private_key.pem
```

Happy to make the change to the docs, just wanted to get confirmation?

**Comment by abutcher** [comment]
@donovanmuller Yes, that should definitely be `IdentityFile` :+1:
