### ISSUE TITLE
AWS bin/cluster created cluster does not deploy router, no matching node label

### ISSUE THREAD

**Issue by donovanmuller** [openshift/openshift-ansible#1198]
If you create an AWS cluster with `bin/cluster create aws <cluster_id>`, the region label is set to `region=us-east-1`, if using the default value. 

However, the default `nodeSelector` for the router deployment is [`region=infra`](https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example#L130).
This means that the router does not get deployed:

```
$ oc get events
...
4h          20m        399       router-1-deploy            Pod                                                         FailedScheduling   {scheduler }                Failed for reason Region and possibly others
4h          20m        380       router-1-deploy            Pod                                                         FailedScheduling   {scheduler }                Failed for reason MatchNodeSelector and possibly others
...
```

because there are no matching nodes with label `region=infra`.
If you add (thanks to [this](https://blog.openshift.com/setting-openshift-3-openstack) post for the idea) the `infra` label to the infra node (replacing `region=us-east-1` with `region=infra`), the router then gets scheduled successfully.

Not sure what the best solution would be (document or change label/selector for bin/cluster?) but this should ideally "just work" and not require the manual intervention.

**Comment by detiber** [comment]
https://github.com/openshift/openshift-ansible/pull/1146 should address your issue. We weren't properly handling bin/cluster created hosts.
