### ISSUE TITLE
Install Specific version of Openshift v.3.11

### ISSUE THREAD

**Issue by ZrytyADHD** [openshift/openshift-ansible#11996]
Hi i need to install on my enviroment specific version of Openshift 

```
Kubernetes
v1.11.0+d4cacc0
OKD
v3.11.0+7618f0a-307
```

How to do this ?
I need this version because all of my cluster curently runing this and i need to have the same version everywhere.

**Comment by vrutkovs** [comment]
See https://docs.openshift.com/container-platform/3.11/install/configuring_inventory_file.html#configuring-cluster-variables, `openshift_image_tag` and `openshift_pkg_version`

**Comment by ZrytyADHD** [comment]
Hey,
i try to use information that you provide but without success.
When i try to use `openshift_image_tag ` and `openshift_pkg_version` everything going ok to step:
'Wait for control plane pods to appear'. When i dlete this line setup complete sucessfully.
Can you explain me a little more how to use it maybe i do something wrong.
My goal is to install `v3.11.0+7618f0a-307` version of OKD Openshift to have all enviroments in one version.
