### ISSUE TITLE
okd 4

### ISSUE THREAD

**Issue by swepps1** [openshift/openshift-ansible#12019]
Hello

Can I install okd 4 version on "centos 7 or 8" ? I don't want to upgrade (I read that I can upgrade openshift 3.11 version to okd 4) I want to new install.

Thank you!
Laci

**Comment by rajputvishwas** [comment]
Yes you can https://linoxide.com/linux-how-to/setup-openshift-origin-centos-7/

You can also refer installation guide available https://github.com/openshift/okd for OKD 4.

**Comment by swepps1** [comment]
Thank you your answer!
You don't understand me! I can new install okd 4 version (not origin 3.11)on centos 7 or 8 or coreos.
I found article that How can I upgrade my sytem!
https://github.com/openshift/openshift-ansible

But I want to new install!
