### ISSUE TITLE
Can't reach apps in openshift using haproxy.

### ISSUE THREAD

**Issue by ZrytyADHD** [openshift/openshift-ansible#12026]
Hi, 
I'm using OKD Openshit v 3.11 and have an issue.
I build simple cluster with
1x master 10.0.7.1
1xinfra node 10.0.7.2
2xapp nodes 10.0.7.3, 10.0.7.4

I deploy sample app php add route `cake.openshit.kbs.eu`.
Everything work fine but i need to reach this app using haproxy with different address for example cake.company.kbs.eu. I configure haproxy front end backend and getting error 503 or the app is unavailable.
I also trying to expose my app add external IP but without success.
Can anyone help me with that.
Also in future i will try to expose app with path. I mean 
I create some apps avalable with adress `mysupportapps.openshit.kbs.eu` and path to them 
`/calc `and` /play ` and also reach them thru haproxy.

**Comment by aholen** [comment]
I had a similar problem, and had to change the termination types on the route for the project: https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#secured-routes

**Comment by ZrytyADHD** [comment]
Ok,
I partly resolve this.
I create app and route `cake.openshit.kbs.eu` and sucesfully redirect it to `mysupportapps.openshit.kbs.eu`.
The problem is when I add path in route config to calc.  I cant redirect adres `cake.openshit.kbs.eu/calc`
to `mysupportapps.openshit.kbs.eu/calc'. 
i got error that app is not working.
