### ISSUE TITLE
redeploy-openshift-ca playbook fails copying ca-bundle.crt

### ISSUE THREAD

**Issue by benscottub** [openshift/openshift-ansible#12041]
[redeploy-openshift-ca.log](https://github.com/openshift/openshift-ansible/files/3923497/redeploy-openshift-ca.log)
#### Description

I am trying to run redeploy-openshift-ca.yml on my 3.11.0 openshift cluster. I am using the openshift-ansible-3.11.154-2 RPM. I am not specifying a custom CA in my inventory file. I am running the playbook from the first control plane server which is osmdev1. I get the following error referencing the first node server, osndev1:
```
TASK [copy] *********************************************************************************************************************************************************************************************************************************
task path: /usr/share/ansible/openshift-ansible/playbooks/openshift-master/private/redeploy-openshift-ca.yml:238
fatal: [osndev1.acsu.buffalo.edu]: FAILED! => {
    "changed": false, 
    "msg": "Could not find or access '/tmp/openshift-ansible-LANNhBK/ca-bundle.crt' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
}
```
I have attached the full playbook output to this issue. 
##### Version

```
[root@osmdev1 private]# ansible --version
ansible 2.6.20
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
[root@osmdev1 private]# rpm -qa | grep openshift-ansible
openshift-ansible-roles-3.11.154-2.git.0.1640c49.el7.noarch
openshift-ansible-docs-3.11.154-2.git.0.1640c49.el7.noarch
openshift-ansible-3.11.154-2.git.0.1640c49.el7.noarch
openshift-ansible-playbooks-3.11.154-2.git.0.1640c49.el7.noarch

```

##### Steps To Reproduce
1. Be me
2. Run the redeploy openshift ca playbook at /usr/share/ansible/openshift-ansible/playbooks/openshift-master/redeploy-openshift-ca.yml

##### Expected Results
Describe what you expected to happen.

```
The openshift CA is regenerated and bundles are deployed to the masters and nodes and stuff is rebooted.
```

##### Observed Results
Describe what is actually happening.

```
The playbook fails.
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

**Comment by ThomVivet** [comment]
Same issue here for us. @benscottub do you remember how did you solved it ?

**Comment by benscottub** [comment]
> Same issue here for us. @benscottub do you remember how did you solved it ?

Sorry, I never resolved this issue. I redeployed all the certificates from scratch.
