### ISSUE TITLE
Compatibility issues between heketi:latest and yum glusterfs-fuse

### ISSUE THREAD

**Issue by kanadaj** [openshift/openshift-ansible#12087]
#### Description

In the latest version of docker.io/heketi/heketi:latest, it uses glusterfs 7.1 which is incompatible with the glusterfs-fuse installed on CentOS based on the documentation. Mounting the file system results in the following error:

```
Mount failed. Please check the log file for more details.

 the following error information was pulled from the glusterfs log to help diagnose this issue:
[2020-01-25 01:10:33.908242] E [MSGID: 101019] [graph.y:321:volume_end] 0-parser: "type" not specified for volume heketidbstorage-utime
[2020-01-25 01:10:33.908308] E [MSGID: 100026] [glusterfsd.c:2473:glusterfs_process_volfp] 0-: failed to construct the graph
```

##### Version

```
# ansible --version
ansible 2.9.2
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

# git describe
openshift-ansible-3.11.165-1-6-g099908d
```

##### Steps To Reproduce
1. Start installing GlusterFS as the file provider with the ansible playbooks
2. Installation fails when GlusterFS fails to mount

##### Additional Information

Linux version in case it matters, probably really doesn't:
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core
```

**Comment by kanadaj** [comment]
I've managed to solve this for now by manually updating the GlusterFS servers via mirror.centos.org. using GlusterFS RPM files from http://mirror.centos.org/centos/7/storage/x86_64/gluster-6/ (http://mirror.centos.org/centos/7/storage/x86_64/gluster-7/ should work as well but I haven't confirmed).

I suggest to update the documentation to either include manually installing a newer version of GlusterFS FUSE, or to change the ansible files to use earlier versions of the gluster and heketi images to avoid compatibility issues with the yum packages.

**Comment by obliviousmippling** [comment]
I have had the same compatibility issues,
I am fairly sure gluster-7 will not work, because it seems to be the cause of the issue.

(From within the container)
`gluster --version`
replied with 7.1

I managed to fix it by adding
`openshift_storage_glusterfs_image='gluster/gluster-centos:gluster4u0_centos7'`
openshift_storage_glusterfs_registry_image='gluster/gluster-centos:gluster4u0_centos7'´
to the [OSEv3:vars] section



however this caused a whole bunch of other issues...

**Comment by obliviousmippling** [comment]
I have had the same compatibility issues,
I am fairly sure gluster-7 will not work, because it seems to be the cause of the issue.

(From within the container)
`gluster --version`
replied with 7.1

I managed to fix it by adding
`openshift_storage_glusterfs_image='gluster/gluster-centos:gluster4u0_centos7'`
`openshift_storage_glusterfs_registry_image='gluster/gluster-centos:gluster4u0_centos7'`
to the [OSEv3:vars] section

The Default is:
`openshift_storage_glusterfs_image='gluster/gluster-centos:latest'`
 `openshift_storage_glusterfs_registry_image='gluster/gluster-centos:latest'`

sadly there is no docker image for gluster-6
https://hub.docker.com/r/gluster/gluster-centos/tags

**Comment by am-titan** [comment]
> I've managed to solve this for now by manually updating the GlusterFS servers via mirror.centos.org. using GlusterFS RPM files from http://mirror.centos.org/centos/7/storage/x86_64/gluster-6/ (http://mirror.centos.org/centos/7/storage/x86_64/gluster-7/ should work as well but I haven't confirmed).
> 
> I suggest to update the documentation to either include manually installing a newer version of GlusterFS FUSE, or to change the ansible files to use earlier versions of the gluster and heketi images to avoid compatibility issues with the yum packages.

Hi kanadaj,

If you could please describe the process of updating Glusterfs I would be thankful.
I am having issues with the version:
`glusterfs --version
glusterfs 3.12.2`

I also believe that the Origin OKD 3.11 guide is out of date.

Thanks

**Comment by kanadaj** [comment]
@am-titan sure!
1) Check if there is a current version installed:
```
glusterfs --version
glusterfs 3.12.2
```
If yes, remove it with yum:
```
yum remove glusterfs-fuse glusterfs-libs
```

Then install the 6.7 version from the CentOS mirror:
```
wget https://www.mirrorservice.org/sites/mirror.centos.org/centos/7/storage/x86_64/gluster-6/glusterfs-6.7-1.el7.x86_64.rpm
wget https://www.mirrorservice.org/sites/mirror.centos.org/centos/7/storage/x86_64/gluster-6/glusterfs-libs-6.7-1.el7.x86_64.rpm
wget https://www.mirrorservice.org/sites/mirror.centos.org/centos/7/storage/x86_64/gluster-6/glusterfs-client-xlators-6.7-1.el7.x86_64.rpm
wget https://www.mirrorservice.org/sites/mirror.centos.org/centos/7/storage/x86_64/gluster-6/glusterfs-fuse-6.7-1.el7.x86_64.rpm
rpm -i glusterfs-6.7-1.el7.x86_64.rpm
rpm -i glusterfs-libs-6.7-1.el7.x86_64.rpm
rpm -i glusterfs-client-xlators-6.7-1.el7.x86_64.rpm
rpm -i glusterfs-fuse-6.7-1.el7.x86_64.rpm
```

For the last batch you can probably substitute with links from the gluster-7 folder if you want a more up-to-date version:
https://www.mirrorservice.org/sites/mirror.centos.org/7/storage/x86_64/gluster-7/

mirror.centos.org could work as well, but since the website _**DOES NOT HAVE SSL/TLS ENABLED**_ for whatever madness, I've replaced the links with mirrorservice.org and you should probably use one of the mirrors that supports HTTPS: https://www.centos.org/download/mirrors/

Should probably also verify the checksums before running the RPM commands.

**Comment by ibishop100** [comment]
I used the gluster-7 repo from centos, worked fine!

Thanks

**Comment by am-titan** [comment]
> @am-titan sure!
> 
> 1. Check if there is a current version installed:
> 
> ```
> glusterfs --version
> glusterfs 3.12.2
> ```
> 
> If yes, remove it with yum:
> 
> ```
> yum remove glusterfs-fuse glusterfs-libs
> ```
> 
> Then install the 6.7 version from the CentOS mirror:
> 
> ```
> wget https://www.mirrorservice.org/sites/mirror.centos.org/centos/7/storage/x86_64/gluster-6/glusterfs-6.7-1.el7.x86_64.rpm
> wget https://www.mirrorservice.org/sites/mirror.centos.org/centos/7/storage/x86_64/gluster-6/glusterfs-libs-6.7-1.el7.x86_64.rpm
> wget https://www.mirrorservice.org/sites/mirror.centos.org/centos/7/storage/x86_64/gluster-6/glusterfs-client-xlators-6.7-1.el7.x86_64.rpm
> wget https://www.mirrorservice.org/sites/mirror.centos.org/centos/7/storage/x86_64/gluster-6/glusterfs-fuse-6.7-1.el7.x86_64.rpm
> rpm -i glusterfs-6.7-1.el7.x86_64.rpm
> rpm -i glusterfs-libs-6.7-1.el7.x86_64.rpm
> rpm -i glusterfs-client-xlators-6.7-1.el7.x86_64.rpm
> rpm -i glusterfs-fuse-6.7-1.el7.x86_64.rpm
> ```
> 
> For the last batch you can probably substitute with links from the gluster-7 folder if you want a more up-to-date version:
> https://www.mirrorservice.org/sites/mirror.centos.org/7/storage/x86_64/gluster-7/
> 
> mirror.centos.org could work as well, but since the website does not have SSL enabled, going with an SSL enabled mirror is probably a safer bet.
 Thanks much appreciated, will try that tomorrow.😁

**Comment by am-titan** [comment]
Thanks for your help, but it seems that I didn't work for me :(
So I'm not trying to hijack a thread, I already have an own one open for this case, please feel free to visit it any help is appreciated.

#12083 


Thx

**Comment by vladimir-spintech** [comment]
For me it was old version of glusterfs on the client nodes. This installs version 7.3.

On Gluster Storage nodes:
```bash
yum install centos-release-gluster
yum install glusterfs-server
```

On Compute nodes:
```bash
yum install centos-release-gluster
yum install glusterfs glusterfs-fuse
```

**Comment by am-titan** [comment]
Yep, as @kanadaj suggested to update the cluster version was the solution for the problem.
I just moved it all from here to another post in order not to hijack.
