### ISSUE TITLE
Replacing master host

### ISSUE THREAD

**Issue by ZrytyADHD** [openshift/openshift-ansible#12088]
Hi,
I'm using OKD with this config
1 master colocated with ETCD
1 infra node
 2 app nodes

I need to replace my master node. Can any one provide me some steps how to do this.
First I try to add new master host and replace old without success. 
After add new one I copy ca.serial.txt, certs and move everything to new one. Remove old one from ETCD cluster etc.
Some things still have calls to old master.

**Comment by imranrazakhan** [comment]
You can find details here

https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/cluster_administration/assembly_replace-master-host

**Comment by ZrytyADHD** [comment]
Ok,I read this article before.
My problem is I have only one master not 3 such is this scenario. When i replace and reconfigure everything to new after disable of old master cluster is stop working because kubernetes master is still working on old server and I don't know how to move it to new one.

**Comment by uselessidbr** [comment]
Did you drain the master?

**Comment by ZrytyADHD** [comment]
Yes of course i do this  with many option --ignore daemon sets and delete-local-data too.
The problem is when i do command:
`oc describe svc kubernetes -n default`
the old master is still visible but it shoudnt.
I think the problem is beacause i use only one master config and
when i do command:
`kubectl cluster info`
the answer is:
`Kubernetes master working on server master1` which is old master.
