### ISSUE TITLE
error: update acceptor rejected registry-console-2: pods for rc 'default/registry-console-2' took longer than 600 seconds to become available

### ISSUE THREAD

**Issue by tianguohui** [openshift/openshift-ansible#12125]
Okd3.11 shows that the installation is successful. When I execute > **oc get pods -n default** <, **registry-console-2-deploy** displays error

NAME                        READY     STATUS    RESTARTS   AGE
docker-registry-3-k75jc     1/1       Running   0          5h
**registry-console-2-deploy   0/1       Error     0          3d**
registry-console-3-deploy   0/1       Error     0          2d
registry-console-4-deploy   0/1       Error     0          6h
router-6-bkt4h              1/1       Running   0          5h

![image](https://user-images.githubusercontent.com/59588791/76738374-76e1dd80-67a5-11ea-8bf7-aef23aee75f3.png)

**Comment by bessalahAmar** [comment]
have same issue , did you find any solution ? and the source of the problem

**Comment by tianguohui** [comment]
> 有同样的问题，您找到任何解决办法了吗？和问题的根源

I haven't found a solution yet. How about you?

**Comment by tianguohui** [comment]
> have same issue , did you find any solution ? and the source of the problem

I haven't found a solution yet. How about you?

**Comment by gongsh** [comment]
I also have the same problem!help

**Comment by bessalahAmar** [comment]
#12115 
add this into the inventory file: 
`openshift_cockpit_deployer_image='docker.io/timbordemann/cockpit-kubernetes:latest'`

or edit the deployment to use this image "docker.io/timbordemann/cockpit-kubernetes:latest"

**Comment by gongsh** [comment]
> #12115
> 
> **source** : ansible-openshift playbook use the "docker.io/kubernetes/cockpit-kubernetes" which is no more available on docker hub
> 
> **solution** :
> 
> 1. if you want to make it work on a running cluster , edit the deployment to use this image "docker.io/timbordemann/cockpit-kubernetes:latest"
> 2. or add this into the inventory file:
>    `openshift_cockpit_deployer_image='docker.io/timbordemann/cockpit-kubernetes:latest'`

Good! My problems are solved,thank you!
