### ISSUE TITLE
metrics-cassandra PVC not able to clam from StorageClass with glusterblock storage

### ISSUE THREAD

**Issue by SimonLau413** [openshift/openshift-ansible#12130]
#### Description

Provide a brief description of your issue here. For example:

The event of metrics-cassandra PVC showing the following message:

"waiting for a volume to be created, either by external provisioner "gluster.org/glusterblock-app-storage or manually created by system administrator"

##### Version

ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)

git describe:
openshift-ansible-3.11.193-1

##### Steps To Reproduce

1. Run fresh installation with ansible playbook
2. oc describe pvc metrics-cassandra-1 showing state in pending, the hawkular-cassandra pods also in pending state and never up.

##### Expected Results

The whole cluster should be running normally.

##### Observed Results

[root@master ~]# oc describe pvc metrics-cassandra-1

Type    Reason                Age                  From                         Message
  ----    ------                ----                 ----                         -------
  Normal  ExternalProvisioning  1m (x4839 over 19h)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "gluster.org/glusterblock-app-storage" or manually created by system administrator

[root@master ~]# oc describe pod hawkular-cassandra-1-2gqxn

Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  26s (x31080 over 19h)  default-scheduler  pod has unbound PersistentVolumeClaims

[root@master ~]# oc get storageclass
NAME                      PROVISIONER                            AGE
glusterfs-storage         kubernetes.io/glusterfs                19h
glusterfs-storage-block   gluster.org/glusterblock-app-storage   19h

##### Additional Information

Operating system: CentOS Linux release 7.7.1908 (Core)

Inventory file:

[OSEv3:children]
masters
nodes
etcd
glusterfs
glusterfs_registry

[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=origin
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability,package_version
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
openshift_release=v3.11
openshift_master_default_subdomain=apps.example.local
openshift_master_cluster_public_hostname=webconsole.example.local

os_firewall_use_firewalld=true

openshift_hosted_registry_cert_expire_days=1825
openshift_ca_cert_expire_days=3650
openshift_node_cert_expire_days=1825
openshift_master_cert_expire_days=1825
etcd_ca_default_days=1825

openshift_use_crio=true
openshift_use_crio_only=false
openshift_crio_enable_docker_gc=true
openshift_crio_docker_gc_node_selector={'runtime': 'cri-o'}

openshift_storage_glusterfs_timeout=900

openshift_storage_glusterfs_namespace=app-storage
openshift_storage_glusterfs_storageclass=true
openshift_storage_glusterfs_storageclass_default=false
openshift_storage_glusterfs_block_deploy=true
openshift_storage_glusterfs_block_host_vol_size=100
openshift_storage_glusterfs_block_storageclass=true
openshift_storage_glusterfs_block_storageclass_default=false
openshift_storage_glusterfs_is_native=false
openshift_storage_glusterfs_heketi_is_native=true
openshift_storage_glusterfs_heketi_executor=ssh
openshift_storage_glusterfs_heketi_ssh_port=22
openshift_storage_glusterfs_heketi_ssh_user=root
openshift_storage_glusterfs_heketi_ssh_sudo=false
openshift_storage_glusterfs_heketi_ssh_keyfile="/root/.ssh/id_rsa"

openshift_hosted_registry_storage_kind=glusterfs
openshift_hosted_registry_storage_volume_size=20Gi
openshift_hosted_registry_selector='node-role.kubernetes.io/infra=true'
openshift_hosted_registry_routehost=registry.apps.example.local

openshift_storage_glusterfs_registry_namespace=infra-storage
openshift_storage_glusterfs_registry_block_deploy=true
openshift_storage_glusterfs_registry_block_host_vol_size=50
openshift_storage_glusterfs_registry_block_storageclass=true
openshift_storage_glusterfs_registry_block_storageclass_default=false
openshift_storage_glusterfs_registry_is_native=false
openshift_storage_glusterfs_registry_heketi_is_native=true
openshift_storage_glusterfs_registry_heketi_executor=ssh
openshift_storage_glusterfs_registry_heketi_ssh_port=22
openshift_storage_glusterfs_registry_heketi_ssh_user=root
openshift_storage_glusterfs_registry_heketi_ssh_sudo=false
openshift_storage_glusterfs_registry_heketi_ssh_keyfile="/root/.ssh/id_rsa"

openshift_metrics_install_metrics=true
openshift_metrics_cassandra_storage_type=pv
openshift_metrics_hawkular_nodeselector={"node-role.kubernetes.io/infra": "true"}
openshift_metrics_cassandra_nodeselector={"node-role.kubernetes.io/infra": "true"}
openshift_metrics_heapster_nodeselector={"node-role.kubernetes.io/infra": "true"}
openshift_metrics_storage_volume_size=10Gi
openshift_metrics_cassandra_pvc_storage_class_name="glusterfs-storage-block"

[masters]
master.example.local

[etcd]
master.example.local

[nodes]
master.example.local openshift_schedulable=true openshift_node_group_name='node-config-master-crio'
node1.example.local openshift_schedulable=true openshift_node_group_name='node-config-compute-crio'
node2.example.local openshift_schedulable=true openshift_node_group_name='node-config-compute-crio'
infra1.example.local openshift_node_group_name='node-config-infra-crio'

[glusterfs]
node1.example.local glusterfs_ip=172.16.0.12 glusterfs_devices='[ "/dev/sdb" ]'
node2.example.local glusterfs_ip=172.16.0.13 glusterfs_devices='[ "/dev/sdb" ]'
infra1.example.local glusterfs_ip=172.16.0.14 glusterfs_devices='[ "/dev/sdb" ]'

[glusterfs_registry]
node1.example.local glusterfs_ip=172.16.0.12 glusterfs_devices='[ "/dev/sdb" ]'
node2.example.local glusterfs_ip=172.16.0.13 glusterfs_devices='[ "/dev/sdb" ]'
infra1.example.local glusterfs_ip=172.16.0.14 glusterfs_devices='[ "/dev/sdb" ]'

**Comment by p-cunning** [comment]
I feel like we've seen the same issue as well. We had to recreate the storageclass and remove the storage namespace from the provisioner type (i.e. gluster.org/glusterblock instead of gluster.org/glusterblock-infra-storage). We traced back through various versions of the openshift-ansible RPMs where the change was made to add the namespace to the provisioner. We deployed a 3.11.135 cluster with no problem, but then deployed a later version cluster and realized the namespace change was added.

However

Deploying an app as recently as this week that required a PV, the PV failed to create because the gluster namespace was missing from the storageclass provisioner. So it seemed some bundled components (logging, metrics, prometheus) wanted just "gluster.org/glusterblock", and other components wanted "gluster.org/glusterblock-infra-storage"
