### ISSUE TITLE
sdn/ovs pods not restarted during upgrade v3.11

### ISSUE THREAD

**Issue by sterburg** [openshift/openshift-ansible#12170]
#### Description

When running deploy_cluster.yaml with a newer openshift_image_tag version the sdn and ovs daemonsets in the openshift-sdn namespace gets updated with the new image version, but that doesn't trigger a redeploy of all its pods because the updateStreategy is set to only OnDelete (instead of RollingUpdate).

It is IMHO pointless to create an ImageStream "node:v3.11" and define a metadata.annotations."image.openshift.io/triggers" to update the daemonset spec when that imagestream changes when the updateStrategy is set to OnDelete.

See
https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.11.219-1/roles/openshift_sdn/files/sdn-ovs.yaml#L16

##### Version

```
ansible 2.9.0
python version 2.7.5
openshift 3.11.146-1.git.0.4aab273.el7.x86_64
```
(but i still see it in latest 3.11.217 playbooks/template too.)

##### Steps To Reproduce

1. install ocp using deploy_cluster.yml with inventory parameters `openshift_image_tag=3.11.51`
2. update inventory parameter to `openshift_image_tag=3.11.146` and run deploy_cluster.yml again.

##### Expected Results

ImageStream "node", DaemonSet "sdn" & "ovs" updated with new image reference and pods redeployed with new image.

```
oc -n openshift-sdn get po -o yaml |grep image:
image: registry/openshift3/ose-node:v3.11.146

oc -n openshift-sdn get ds -o yaml |grep image:
image: registry/openshift3/ose-node:v3.11.146

oc -n openshift-sdn describe is/node
v3.11
  reference to registry reigstry/openshift3/ose-node:v3.11.146
    27 minutes ago
```

##### Observed Results
The ImageStream and DaemonSet are updates but Pods not.

```
oc -n openshift-sdn get po -o yaml |grep image:
image: registry/openshift3/ose-node:v3.11.51

oc -n openshift-sdn get ds -o yaml |grep image:
image: registry/openshift3/ose-node:v3.11.146

oc -n openshift-sdn describe is/node
v3.11
  reference to registry reigstry/openshift3/ose-node:v3.11.146
    27 minutes ago
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* see https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.11.219-1/roles/openshift_sdn/files/sdn-ovs.yaml#L16
* The proposal is to update the updateStrategy to "RollingUpdate" (tested, it works), otherwise i see no added value of specifying an imageTrigger annotation.
* The effort here is to create a Pipeline that always runs deploy_cluster.yaml to do 1) Configuration Changes, 2) Upgrades, 3) Scaleup instead of running ad-hoc "upgrade" and "scaleup" playbooks.

**Comment by mtnbikenc** [comment]
Upgrading the installed cluster version should not be performed with `playbooks/deploy_cluster.yml`.  Upgrades are performed with `playbooks/byo/openshift-cluster/upgrades/v3_11/upgrade.yml`.  See docs at, https://docs.openshift.com/container-platform/3.11/upgrading/automated_upgrades.html.

SDN and OVS pods are deleted during the upgrade while nodes are cordoned and drained.  The pods are then redeployed with the updated image versions.

For more information see, https://github.com/openshift/openshift-ansible/pull/11075
