### ISSUE TITLE
sanity checks failed

### ISSUE THREAD

**Issue by runseason** [openshift/openshift-ansible#12189]
#### Description
openshift3.11
TASK [Run variable sanity checks] *******************************************************************************************************************
task path: /usr/share/ansible/openshift-ansible/playbooks/init/sanity_checks.yml:14
fatal: [jqdev-l-00860.jqdev.sm.com]: FAILED! => {
    "msg": "last_checked_host: devbld00609.jqdev.sm.com, last_checked_var: ansible_python;'NoneType' object has no attribute '__getitem__'"
}
        to retry, use: --limit @/usr/share/ansible/openshift-ansible/playbooks/openshift-checks/pre-install.retry

##### Version
ansible 2.6.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

**Comment by runseason** [comment]
Is there anybody knows what's problem of this ?

**Comment by mtnbikenc** [comment]
It means the `ansible_python` var was not defined in the host vars for `devbld00609.jqdev.sm.com`.  Ansible was unable to determine the python version installed on that host for some reason.  If Ansible is unable to determine the python version installed, it may be a bug in your version of Ansible.

You can run the Ansible `setup` module and grep the output for `ansible_python` to see what Ansible is finding for that host.

For example:
```
$ ansible localhost -m setup | grep \"ansible_python\" -A 18
        "ansible_python": {
            "executable": "/usr/bin/python3",
            "has_sslcontext": true,
            "type": "cpython",
            "version": {
                "major": 3,
                "micro": 3,
                "minor": 8,
                "releaselevel": "final",
                "serial": 0
            },
            "version_info": [
                3,
                8,
                3,
                "final",
                0
            ]
        },
```
