### ISSUE TITLE
As a user, i want to configure kubernetesMasterConfig.podEvictionTimeout

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#1224]
Hi,

Openshift require 5 minutes to rescheulde a pod, if the node is dead. I want to configure via value via ansible..

https://github.com/openshift/openshift-ansible/blob/ec643bee6b4de6d26f5aea346d73e8158f10939e/roles/openshift_master/templates/master.yaml.v1.j2#L94

**Comment by detiber** [comment]
@brenton this can be closed now that https://github.com/openshift/openshift-ansible/issues/1243 has been merged.
