### ISSUE TITLE
ROUTER_CIPHERS reverts after every certificate redeployment

### ISSUE THREAD

**Issue by djdevin** [openshift/openshift-ansible#12246]
#### Description

When running redeploy-certificates.yml to deploy a new console cert the router settings are reverted which includes ROUTER_CIPHERS. This causes a compliance issue as some organizations require disablement of < TLS 1.2

I couldn't find anything in the inventory file that would allow this to be preserved.

##### Version

OpenShift Master:
    v3.11.0+bd0bee4-337 
Kubernetes Master:
    v1.11.0+d4cacc0 
OpenShift Web Console:
    v3.11.0+ea42280 

openshift-ansible-playbooks-3.11.146-1.git.0.fcedb45.el7.noarch

##### Steps To Reproduce
1. Set ROUTER_CIPHERS on the default router DC to "modern" (TLS 1.2)
2. Redeploy certificates
3. ROUTER_CIPHERS is now ""

##### Expected Results

ROUTER_CIPHERS remains at "modern"

##### Observed Results

ROUTER_CIPHERS is reset to default (TLS 1.0, 1.1, 1,2)

**Comment by 01James** [comment]
Hello are you using nginx? If so nginx restart will resolve this issue.

**Comment by djdevin** [comment]
No - default haproxy.

**Comment by 01James** [comment]
I want to note that I have no prior knowledge of this but decided to give it a shot. I found many documents online but not mentioning why modern is not maintaining the TLS version.
https://www.haproxy.com/documentation/aloha/latest/traffic-management/lb-layer7/tls/ I found here that you can use 

force-tlsv10 | Enforces the use of TLS protocol version 1.0
-- | --
force-tlsv11 | Enforces the use of TLS protocol version 1.1
force-tlsv12 | Enforces the use of TLS protocol version 1.2
----------

no-tlsv10 | Disables support of TLS 1.0 protocol
-- | --
no-tlsv11 | Disables support of TLS 1.1 protocol
no-tlsv12 | Disables support of TLS 1.2 protocol

I also found that modern is supposed to eliminate TLS 1.0, TLS 1.1, and some of the insecure ciphers. The following command sets the ciphers to "modern". I don't think this is happening but I would ask the security team if any downgrade attack has been performed? https://www.ibm.com/support/knowledgecenter/SSYHZ8_20.0.x/com.ibm.dba.managing/op_topics/tsk_cluster_security.html

**Comment by djdevin** [comment]
@01James sorry, that's not the issue - the "modern" cipher set works fine.

The issue is that upon running the redeploy-certificates playbook, the ROUTER_CIPHERS environment variable on the router deployment configuration is reset and has to be manually reset to "modern".

**Comment by mtnbikenc** [comment]
Using openshift_hosted_routers is a possible workaround.  See https://bugzilla.redhat.com/show_bug.cgi?id=1935809
/close
