### ISSUE TITLE
OKD-3.11 logging install blocked: missing image on quay.io for quay.io/openshift/oauth-proxy:v1.1.0. 

### ISSUE THREAD

**Issue by bravosierrasierra** [openshift/openshift-ansible#12290]
#### Description

After commit e26d5cf612fd44d0bdcbb3db037f3d235e456e0d we have blocked installation for openshift logging in OKD 3.11 branch. Source of problem: missing image on quay.io for quay.io/openshift/oauth-proxy:v1.1.0. Original docker image docker.io/openshift/oauth-proxy:v1.1.0 still exist, but not used in install

##### Version

git branch "release 3.11"

**Comment by iamruhua** [comment]
same situation here
