### ISSUE TITLE
Please rename directory v1.1 and v1.0 for OpenShfit Enterprise

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-ansible#1241]
There are `imagestream` and `template` files under `openshift-ansible/roles/openshift_examples/files/examples/v1.{0,1}/`. There are some confusion and issues due to this versioning.

Issue1. The confusion of documentation

ref: https://github.com/openshift/openshift-docs/issues/1454

Issue2. v1.1's quick-start template(cakephp-mysql) doesn't work for OSE v3.1.

ref: http://post-office.corp.redhat.com/archives/openshift-sme/2016-January/msg00573.html (internal)

**Comment by detiber** [comment]
@sdodson

**Comment by sdodson** [comment]
We could symlink them.

Which scheme makes the most sense?
Just add symlinks for the version numbers
v3.1 -> v1.1
v3.0 -> v1.0

Or, make the paths depend on `deployment_type` ? We'd need to add atomic-enterprise and online too I guess.
openshift-enterprise-v3.1 -> origin-v1.1
openshift-enterprise-v3.0 -> origin-v1.0
atomic-enterprise-v3.1 -> origin-v1.1
online-v3.1 -> origin-v1.1

**Comment by detiber** [comment]
@sdodson thoughts on shipping the examples (at least the ones in the origin repo) as a subpackage?

Then we could track the package version installed and update the examples when the package version has changed.

In general, it probably wouldn't be a bad idea to track the package versions in openshift_facts in general.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
