### ISSUE TITLE
how to change the docker options from openshift-ansible

### ISSUE THREAD

**Issue by wenskys** [openshift/openshift-ansible#1242]
Hi，
   when i use openshift-ansible,the docker options is "OPTIONS='--selinux-enabled --insecure-registry 172.30.0.0/16'[1] ". selinux-enabled and storage-driver=overlay conflict when i change this.
    if i want to change the docker device-mapper to overlay such as "storage-driver=overlay",what can i do at "/etc/origin/hosts"?
    thank!
    by the way,what the openshift-orign:v1.1.1 and docker:1.9 can be use by  openshift-ansible?

[1].https://docs.openshift.org/latest/install_config/install/prerequisites.html

**Comment by detiber** [comment]
Right now, we don't support setting any other options in docker, but it seems like it could be added by adding a new variable and setting it in the 'Secure Registry and Logs Options' task in roles/openshift_docker/tasks/main.yml

I'm not sure I fully understand the second question though:
```
by the way,what the openshift-orign:v1.1.1 and docker:1.9 can be use by openshift-ansible?
```

**Comment by wenskys** [comment]
At the releases of openshift-ansible-3.0.35-1,we use openshift-orign-v1.1.0.1 and docker-1.8.2，at openshift-orign-v1.1.1 and docker-1.9.1 that have more Changes,so i want to know something about the new releases for openshift-ansible which use origin-v1.1.1 and docker-1.9.1.
thank!

**Comment by detiber** [comment]
openshift-ansible by default will install the latest version of origin available. You can change the version installed by setting `openshift_pkg_version` in your inventory file.
