### ISSUE TITLE
ERROR: become is not a legal parameter at this level in an Ansible Playbook

### ISSUE THREAD

**Issue by barkerd427** [openshift/openshift-ansible#1249]
Discovered this error during my investigation on #1203. I get this error when I use tags from `openshift-ansible-3.0.21-1` to `openshift-ansible-3.0.35-1` and on master:
```
➜  openshift-ansible git:(master) bin/cluster -vvvvv create aws dst-test
RUN [time ansible-playbook -vvvvv -i inventory/aws/hosts -e 'num_masters=1 num_nodes=2 cluster_id=dst-test cluster_env=dev num_etcd=0 num_infra=1 deployment_type=origin' playbooks/aws/openshift-cluster/launch.yml]
ERROR: become is not a legal parameter at this level in an Ansible Playbook

real    0m30.430s
user    0m0.996s
sys 0m0.785s
Traceback (most recent call last):
  File "bin/cluster", line 379, in <module>
    args.func(args)
  File "bin/cluster", line 69, in create
    self.action(args, inventory, cluster, playbook)
  File "bin/cluster", line 246, in action
    .format(args.action, exc))
ActionFailed: ACTION [create] failed: Command 'time ansible-playbook -vvvvv -i inventory/aws/hosts -e 'num_masters=1 num_nodes=2 cluster_id=dst-test cluster_env=dev num_etcd=0 num_infra=1 deployment_type=origin' playbooks/aws/openshift-cluster/launch.yml' returned non-zero exit status 1
```

Everything works fine with tag `openshift-ansible-3.0.20-1`. I haven't looked into the issue at all at this point. I will try to if I can get some bandwidth in the next couple weeks.

**Comment by detiber** [comment]
@barkerd427 what version of Ansible are you running? We've started testing against 1.9.4 only to start work on Ansible 2.0 compatibility.

It seems I need to update our version check and docs to take that into account though.

**Comment by detiber** [comment]
Created https://github.com/openshift/openshift-ansible/pull/1253 to address the requirement for ansible 1.9.4

**Comment by barkerd427** [comment]
```
➜  openshift-ansible git:(3703f1b) ✗ ansible --version
ansible 1.8.4
  configured module search path = None
```

**Comment by detiber** [comment]
@barkerd427 that would explain it then. Unfortunately, there really isn't a good way to maintain backward compatibility with 1.8 as we are working towards supporting 2.0

**Comment by barkerd427** [comment]
Upgrading to 1.9.4 fixed this issue.
