### ISSUE TITLE
Regenerating etcd certificates?

### ISSUE THREAD

**Issue by brettneese** [openshift/openshift-ansible#1260]
Our openshift master node crashed, and I'm having problems recovering it. We're running on AWS with elastic IPs, so I figured I could just deploy an image we created onto a new instance, but that didn't work because the internal IP is different. 

When trying to reconfigure using the original hosts file, however, I get ```msg: Job for origin-master.service failed. See 'systemctl status origin-master.service' and 'journalctl -xn' for details.``` 

Doing some digging, I realized that this is because the hostnames in the certificate for etcd didn't include the new internal IP (we're running our etcd on the master for now.) Is there an easy way to regenerate them? I thought the playbook would do this automatically, but that does not appear to be happening. (Though the associated steps succeed.)

![image](https://cloud.githubusercontent.com/assets/504279/12496028/ba890034-c058-11e5-99ae-4ac776207623.png)

**Comment by abutcher** [comment]
Hey @brettneese - If the master has a new IP you're going to need new server certificates for the master and etcd.

I think this will do the trick in w/ the least amount of steps:
```
mkdir /tmp/backup-certs
mv /etc/origin/master/master.server.{crt,key} /tmp/backup-certs/
mv /etc/origin/master/etcd.server.{crt,key} /tmp/backup-certs/
```

Then re-run the ansible playbook and this will re-create the missing certificates without overwriting anything in place.

I'm on freenode irc as abutcher if you have any questions.

**Comment by abutcher** [comment]
The manual steps are also covered [here](https://docs.openshift.org/latest/install_config/upgrades.html#updating-master-certificates)

**Comment by brettneese** [comment]
That worked, but I'm having other problems. That was very useful information, though! :)

Closing and following up on IRC.
