### ISSUE TITLE
Docker is being installed where it shouldn't 

### ISSUE THREAD

**Issue by spinolacastro** [openshift/openshift-ansible#1262]
I've discovered that the docker has being installed on etcd even though we run a non-atomic install

<pre>
- name: Configure docker hosts
  hosts: oo_masters_to_config:oo_nodes_to_config:oo_etcd_to_config
</pre>

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
