### ISSUE TITLE
etcd certs use first interface's ip by default

### ISSUE THREAD

**Issue by goern** [openshift/openshift-ansible#1267]
On a host with two network interfaces, https://github.com/openshift/openshift-ansible/blob/master/roles/etcd_certificates/tasks/server.yml#L21 seem to use only the first IP. This may lead to problems if all traffic should go thru the second interface.

**Comment by detiber** [comment]
@goern indeed, we also do not make it easy to override the names used for the etcd certs. Ideally, we should be using the same openshift_ip and openshift_hostname variables as the other roles.

I created https://trello.com/c/2tygIgBm/163-fix-etcd-hostname-ip-address-handling to address the issue.

**Comment by abutcher** [comment]
Fixed in https://github.com/openshift/openshift-ansible/pull/1754
