### ISSUE TITLE
Etcd failing to install 

### ISSUE THREAD

**Issue by brettneese** [openshift/openshift-ansible#1271]
When running the Ansible installer pointing at a master, a node, and a etcd node on AWS, I get: 

```
PLAY [Set etcd facts needed for generating certs] ***************************** 

GATHERING FACTS *************************************************************** 
FATAL: no hosts matched or all hosts have already failed -- aborting
TASK: [openshift_facts | Verify Ansible version is greater than 1.8.0 and not 1.9.0 and not 1.9.0.1] *** 
FATAL: no hosts matched or all hosts have already failed -- aborting
```

Not sure how to debug this more fully; journalctl shows nothing of interest.

**Comment by abutcher** [comment]
This error is saying that the ansible version doesn't match what openshift-ansible requires.

We're updating this check to ensure the version is greater than or equal to `1.9.4` and less than `2.0` in https://github.com/openshift/openshift-ansible/pull/1253

**Comment by brettneese** [comment]
Hmm. How do I fix it?

On Monday, January 25, 2016, Andrew Butcher <notifications@github.com>
wrote:

> This error is saying that the ansible version doesn't match what
> openshift-ansible requires.
>
> We're updating this check to ensure the version is greater than or equal
> to 1.9.4 and less than 2.0 in #1253
> <https://github.com/openshift/openshift-ansible/pull/1253>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/openshift-ansible/issues/1271#issuecomment-174736870>
> .
>


-- 
Brett Neese
563-210-3459

**Comment by abutcher** [comment]
What is your ansible version? It should be `1.9.4` to pass the upcoming check.

```
$ ansible --version
ansible 1.9.4
  configured module search path = None
```

**Comment by brettneese** [comment]
Yep, it is, and all other tasks work as wll. Do I need to check on the etcd
server as well?
[image: Inline image 1]


Brett Neese
563-210-3459

**Comment by abutcher** [comment]
Can you post your inventory?

**Comment by brettneese** [comment]
Yep, here you go. 

[hosts.txt](https://github.com/openshift/openshift-ansible/files/104322/hosts.txt)

**Comment by detiber** [comment]
Ansible version would only matter on the host you are running it from.  That said, when reworking the version checking @abutcher did discover that using ansible_version as is being done in the existing master does not work as expected. 

@abutcher I wonder if there is a platform related bug in how the test works.

@brettneese What OS and python version are you using?

**Comment by brettneese** [comment]
OSX 10.11.2, python 2.7.11. 

Everything else works. It's just adding in the etcd server that is causing things to fail. Deploying on https://aws.amazon.com/marketplace/pp/B00O7WM7QW.

**Comment by abutcher** [comment]
@detiber Yep, definitely weird.

```
>>> from ansible.runner.filter_plugins.core import version_compare
>>> ansible_version = {'major': 1, 'full': '1.9.4', 'string': '1.9.4\n  configured module search path = None', 'minor': 9, 'revision': 4}
>>> version_compare(ansible_version, '1.8.0', '<')
False
>>> version_compare(ansible_version, '1.8.0', '>')
True
```

**Comment by brettneese** [comment]
Is there an easy way to skip the version check? Not totally convinced that's what's causing it, I think it actually has to do with the etcd certs.

**Comment by abutcher** [comment]
Yeah, the `FATAL: no hosts matched or all hosts have already failed -- aborting` makes me think there's another issue. Were there any errors prior to what you first posted in the issue? The version check could be commented out but I suspect it will fail on the next task.

**Comment by detiber** [comment]
One thing that would definitely bomb out the check is if the fact gathering
failed to run successfully (or gather_facts is set to 'no' like some of our
localhost runs).

On Mon, Jan 25, 2016 at 9:46 PM, Andrew Butcher <notifications@github.com>
wrote:

> Yeah, the FATAL: no hosts matched or all hosts have already failed --
> aborting makes me think there's another issue. Were there any errors
> prior to what you first posted in the issue? The version check could be
> commented out but I suspect it will fail on the next task.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/openshift-ansible/issues/1271#issuecomment-174788040>
> .
>



-- 
Jason DeTiberus

**Comment by brettneese** [comment]
Reconfiguring right now. The only thing I noticed -- and this may actually
be getting somewhere -- is that Docker is taking an absurdly long time to
install.

Brett Neese
563-210-3459

**Comment by brettneese** [comment]
Docker install is still hanging. Hmmm....

Brett Neese
563-210-3459

**Comment by brettneese** [comment]
Hanging tight on this until I can figure out #1272. Not sure what's going up there, but could be related: I was having problems earlier today with that step as well.

**Comment by brettneese** [comment]
Yeah, this was actually because of #1272. Closing.
