### ISSUE TITLE
Docker failing to enable itself

### ISSUE THREAD

**Issue by brettneese** [openshift/openshift-ansible#1272]
I was having a problem with #1271, but now, on a fresh install, I'm running into 

```
TASK: [docker | enable and start the docker service] ************************** 
failed: [ec2-52-71-193-182.compute-1.amazonaws.com] => {"failed": true}
msg: Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.

failed: [ec2-52-72-119-63.compute-1.amazonaws.com] => {"failed": true}
msg: Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.


FATAL: all hosts have already failed -- aborting
```

`systemctl` and `journalctl` don't yield anything interesting. 

Host for ansible is OSX 10.11.2, python 2.7, ansible 1.9.4. Servers are https://aws.amazon.com/marketplace/pp/B00O7WM7QW. I've attached my inventory file.
[hosts.txt](https://github.com/openshift/openshift-ansible/files/104428/hosts.txt)

Not sure how to begin to debug this or I'd post more information. :(

**Comment by detiber** [comment]
Do you only hit this on the first time through, or does this continue to fail for subsequent runs as well?

**Comment by brettneese** [comment]
Running a second time causes the etcd node to timeout and become
inaccessible, somehow (can't even get to it via SSH manually). Deleting
just that etcd instance and creating a new instance in its place works, but
I get stuck on #1271.

**Comment by brettneese** [comment]
Commenting out the etcd server, configuring, and reconfiguring I get stuck on:

```
TASK: [docker | enable and start the docker service] ************************** 
ok: [ec2-52-72-119-63.compute-1.amazonaws.com]
failed: [ec2-52-71-193-182.compute-1.amazonaws.com] => {"failed": true}
msg: Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
```

There's specifically something funky going on with etcd.

**Comment by brettneese** [comment]
Any more thoughts on this? cc: @abutcher

**Comment by abutcher** [comment]
@brettneese Are you able to start docker manually after this or does it start on its own given some time?

**Comment by brettneese** [comment]
No, actually, the weirdest thing happens: the etcd node becomes completely inaccessible, which may actually be why? Except that I don't see any ssh errors.

**Comment by brettneese** [comment]
grr, just tried reconfiguring using the old master and a new etcd a minute ago. got past this, and its accessible, but ran into the cert issue in #1271. 

seems inconsistent which problem I run into, wondering if there's a race condition going on somewhere or something.

these have to be related, right?

**Comment by abutcher** [comment]
@brettneese Yeah, what I think is happening is that the etcd node becomes unavailable at some point after starting docker and when we attempt to gather facts on the etcd node (for certificate generation) it's inaccessible.

What version of docker is being installed? Kernel version? What is the AMI ID?

**Comment by brettneese** [comment]
https://aws.amazon.com/marketplace/pp/B00O7WM7QW

`Docker version 1.8.2-el7.centos, build a01dc02/1.8.2`

Interestingly when the cert generation fails, the machine is still accessible for a hot second (it somehow became inaccessible while I was logged into it trying to get docker version and kernel version!)

Not sure if there's a window after docker fails when it's still accessible.

**Comment by brettneese** [comment]
Nope, I was wrong, it's back online somehow 

Kernel version: 3.10.0-229.14.1.el7.x86_64

**Comment by abutcher** [comment]
Could you try with `docker_udev_workaround=True` in your inventory under `[OSEv3:vars]`. This will override (and shorten) the default udev timeout for the system if you're hitting an issue where docker starts the first time and times out creating the lvm loop storage backend.

**Comment by brettneese** [comment]
Nope. :-\ 

I did scroll through the logs, and it looks like Docker is definitely failing before #1271. Not sure why it's working fine on the master - they're the same AMI.

**Comment by abutcher** [comment]
What do you have in the logs? Please gist/pastebin and that should give us a better idea what is happening.

`journalctl -u docker --since=<time last install as started in HH:MM:SS> -l`

**Comment by brettneese** [comment]
Well, for one, it would help if I did `sudo journalctl` ;-P

Thought they were just empty, or I'd have posted them earlier. 

Here we go: http://pastebin.com/1Xstq3pS

**Comment by abutcher** [comment]
Alright, seems related to loopback storage initialization.

If you start the docker daemon manually, let that complete and then stop the daemon are you then able to restart the docker service via systemd.

```
sudo /usr/bin/docker daemon -D -l debug --storage-opt dm.no_warn_on_loop_devices=true
```

**Comment by brettneese** [comment]
```
-- Logs begin at Thu 2016-01-28 18:19:24 UTC, end at Thu 2016-01-28 18:30:17 UTC. --
Jan 28 18:30:12 ip-172-31-44-180 sudo[11979]: centos : TTY=pts/0 ; PWD=/usr/lib/systemd/system ; USER=root ; COMMAND=/bin/systemctl restart docker.service
Jan 28 18:30:12 ip-172-31-44-180 systemd[1]: Stopping Docker Application Container Engine...
Jan 28 18:30:12 ip-172-31-44-180 docker[11782]: time="2016-01-28T18:30:12.149976678Z" level=info msg="Processing signal 'terminated'"
Jan 28 18:30:12 ip-172-31-44-180 docker[11782]: time="2016-01-28T18:30:12.155127731Z" level=error msg="remove /var/run/docker.pid: no such file or directory"
Jan 28 18:30:12 ip-172-31-44-180 systemd[1]: Starting Docker Storage Setup...
Jan 28 18:30:12 ip-172-31-44-180 docker-storage-setup[11983]: Volume group "xvda1" not found
Jan 28 18:30:12 ip-172-31-44-180 docker-storage-setup[11983]: Cannot process volume group xvda1
Jan 28 18:30:12 ip-172-31-44-180 docker-storage-setup[11983]: No volume group has been specified and root device volume group could not be determined. Exiting.
Jan 28 18:30:12 ip-172-31-44-180 systemd[1]: docker-storage-setup.service: main process exited, code=exited, status=1/FAILURE
Jan 28 18:30:12 ip-172-31-44-180 systemd[1]: Failed to start Docker Storage Setup.
Jan 28 18:30:12 ip-172-31-44-180 systemd[1]: Unit docker-storage-setup.service entered failed state.
Jan 28 18:30:12 ip-172-31-44-180 systemd[1]: Starting Docker Application Container Engine...
Jan 28 18:30:12 ip-172-31-44-180 docker[11991]: time="2016-01-28T18:30:12.224590805Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
Jan 28 18:30:12 ip-172-31-44-180 docker[11991]: time="2016-01-28T18:30:12.247402693Z" level=error msg="WARNING: No --storage-opt dm.thinpooldev specified, using loopback; th
Jan 28 18:30:12 ip-172-31-44-180 docker[11991]: time="2016-01-28T18:30:12.266766371Z" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
Jan 28 18:30:12 ip-172-31-44-180 docker[11991]: time="2016-01-28T18:30:12.267519699Z" level=info msg="Option DefaultDriver: bridge"
Jan 28 18:30:12 ip-172-31-44-180 docker[11991]: time="2016-01-28T18:30:12.267538959Z" level=info msg="Option DefaultNetwork: bridge"
Jan 28 18:30:12 ip-172-31-44-180 docker[11991]: time="2016-01-28T18:30:12.274283072Z" level=warning msg="Running modprobe bridge nf_nat br_netfilter failed with message: mod
Jan 28 18:30:12 ip-172-31-44-180 docker[11991]: time="2016-01-28T18:30:12.278028111Z" level=info msg="Firewalld running: false"
Jan 28 18:30:12 ip-172-31-44-180 docker[11991]: time="2016-01-28T18:30:12.320673816Z" level=info msg="Loading containers: start."
Jan 28 18:30:12 ip-172-31-44-180 docker[11991]: time="2016-01-28T18:30:12.320824527Z" level=info msg="Loading containers: done."
Jan 28 18:30:12 ip-172-31-44-180 docker[11991]: time="2016-01-28T18:30:12.320841787Z" level=info msg="Daemon has completed initialization"
Jan 28 18:30:12 ip-172-31-44-180 docker[11991]: time="2016-01-28T18:30:12.320858359Z" level=info msg="Docker daemon" commit="a01dc02/1.8.2" execdriver=native-0.2 graphdriver
Jan 28 18:30:12 ip-172-31-44-180 systemd[1]: Started Docker Application Container Engine.
Jan 28 18:30:17 ip-172-31-44-180 sudo[12043]: centos : TTY=pts/0 ; PWD=/usr/lib/systemd/system ; USER=root ; COMMAND=/bin/journalctl --since 18:30:00
```

**Comment by abutcher** [comment]
@brettneese Ok docker started. Have you retried the ansible playbooks?

**Comment by brettneese** [comment]
Sorry, got pulled away to a meeting.

Yep, that does work. Is this something that needs to be fixed in the script itself?

**Comment by abutcher** [comment]
There a couple things going on here:
* We shouldn't be installing docker on etcd for non-containerized installs.
* [loopback storage is not recommended for production environments](http://www.projectatomic.io/blog/2015/06/notes-on-fedora-centos-and-docker-storage-drivers/). We've seen this issue before (https://github.com/openshift/openshift-ansible/issues/916) and have worked around it in the current aws provisioning scripting by using a separate volume for docker storage. Unfortunately I think this is something that would need to be worked around prior to install. @detiber may have some ideas if this is not the stance we want to take.

**Comment by detiber** [comment]
I wouldn't be opposed to setting the udev workaround by default until we
release a newer Docker version.

**Comment by abutcher** [comment]
Issue for fixing docker install on non-containerized etcd https://github.com/openshift/openshift-ansible/issues/1262

**Comment by brettneese** [comment]
So doing #1202 works on the master, but is #1262 why it's failing on the etcd? 

Is there a quick and dirty way to force Docker to only install on the master?

**Comment by abutcher** [comment]
The quick and dirty way would be to edit `playbooks/common/openshift-docker/config.yml` and remove `:oo_etcd_to_config` from the end of the hosts line, so that it looked like:

```
- name: Configure docker hosts
  hosts: oo_masters_to_config:oo_nodes_to_config
...
```

I think we'll need to setup a new group like `oo_docker_to_config` and conditionally include containerized hosts in that group to fix it.

**Comment by jae2** [comment]
For me even running from that fork gives the same problem mentioned in this issue:

Feb 05 14:46:50 ip-172-31-10-33 docker-storage-setup[23162]: Volume group "xvda1" not found
Feb 05 14:46:50 ip-172-31-10-33 docker-storage-setup[23162]: Cannot process volume group xvda1
Feb 05 14:46:50 ip-172-31-10-33 docker-storage-setup[23162]: No volume group has been specified and root device volume group could not be determined. Exiting.
Feb 05 14:46:50 ip-172-31-10-33 systemd[1]: docker-storage-setup.service: main process exited, code=exited, status=1/FAILURE
Feb 05 14:46:50 ip-172-31-10-33 systemd[1]: Failed to start Docker Storage Setup.
-- Subject: Unit docker-storage-setup.service has failed

**Comment by tbielawa** [comment]
@brettneese @abutcher please review PR and decide if it should stay open. xoxoxo

**Comment by vrutkovs** [comment]
Stale issue, please open a new issue if docker still fails to start
