### ISSUE TITLE
etcd isn't installed with Vagrant + Ansible + OpenShift Origin

### ISSUE THREAD

**Issue by harobed** [openshift/openshift-ansible#1289]
Hi,

what I did : 

```
$ git clone git@github.com:openshift/openshift-ansible.git
$ cd openshift-ansible
$ vagrant up --no-provision
$ vagrant provision
$ vagrant ssh master
[root@ose3-master vagrant]# systemctl status etcd.service
● etcd.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

I look in ```/etc/``` I found nothing about etcd, etcd package isn't installed

```
[root@ose3-master vagrant]# yum list installed | grep "etcd"
[root@ose3-master vagrant]#
```

this is my Ansible log output : https://gist.github.com/harobed/a9bfa7ae0bcdbd8d34e3

Are there a bug ?

Best regards,
Stéphane

**Comment by detiber** [comment]
We only install an external etcd for HA installations, for single master
installs we use the embedded etcd service provided by the openshift binary.
