### ISSUE TITLE
Add docs on how to retain the registry's service IP if you delete and recreate the docker-registry service

### ISSUE THREAD

**Issue by ncdc** [openshift/openshift-ansible#1297]
Until we've switched to referencing the integrated registry via DNS, we should add docs on how to retain the IP address the docker-registry service uses in the event users delete and recreate the service. I believe @smarterclayton suggested doing this:

1. make note of the ClusterIP for the service
1. `oc delete svc/docker-registry`
1. `oadm registry ... -o json > registry.json`
1. edit `registry.json`, find the Service in there, and set its `ClusterIP` to the address noted in step 1
1. `oc create -f registry.json`

**Comment by detiber** [comment]
@ncdc did you intend to file this under openshift-docs instead?

**Comment by ncdc** [comment]
grrr, sorry
