### ISSUE TITLE
examples fail to load

### ISSUE THREAD

**Issue by rrati** [openshift/openshift-ansible#1302]
The installer fails to load the examples:

failed: [192.1.0.3] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-centos7.json"], "delta": "0:00:00.606947", "end": "2016-01-28 16:05:39.297060", "failed": true, "failed_when_result": true, "rc": 1, "start": "2016-01-28 16:05:38.690113", "stdout_lines": [], "warnings": []}
stderr: Error from server: ImageStream "ruby" is invalid: [spec.tags[2.0].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[2.2].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[2.0].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[2.2].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "nodejs" is invalid: [spec.tags[0.10].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[0.10].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "perl" is invalid: [spec.tags[5.16].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[5.20].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[5.16].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[5.20].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "php" is invalid: [spec.tags[5.5].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[5.6].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[5.5].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[5.6].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "python" is invalid: [spec.tags[2.7].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[3.3].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[3.4].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[2.7].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[3.3].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[3.4].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "wildfly" is invalid: [spec.tags[8.1].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[8.1].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "mysql" is invalid: [spec.tags[5.6].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[5.5].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[5.5].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[5.6].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "postgresql" is invalid: [spec.tags[9.2].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[9.4].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[9.2].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[9.4].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "mongodb" is invalid: [spec.tags[2.4].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[2.6].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[2.4].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[2.6].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "jenkins" is invalid: [spec.tags[1].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[1].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']

**Comment by sdodson** [comment]
Which version of openshift is this?
`oc version`

**Comment by detiber** [comment]
Scott,

This was a build from origin master.

The bigger issue is that the variables for disabling a subset of the
examples do not use the bool filter and fail to take effect.

Other than that, a heads up that the next Enterprise update will have this
issue.

**Comment by sdodson** [comment]
Also happening with containerized installs on origin because origin:latest is a daily build.

**Comment by sdodson** [comment]
@rrati if you have a second can you try this PR?

`git pull https://github.com/sdodson/openshift-ansible is-sync` in your checkout

**Comment by timothysc** [comment]
We'll give it another try once we scale up the node count.

**Comment by sdodson** [comment]
It's merged already btw.
