### ISSUE TITLE
Functional testing for roles

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#131]
Potentially using https://github.com/nickjj/rolespec
Blog discussing using rolespec: http://devops.works/2015/03/15/testing-ansible-roles-part-2/

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit
