### ISSUE TITLE
CI tests

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#133]
1. Run unit tests
2. Functional Testing
   a. Run role tests
   a. Full functional tests
       i. master/node on one host
       i. master with multiple nodes, no sdn
       i. master with multiple nodes, with sdn

Considerations:
1. test using multiple versions of ansible that we consider "supported"
1. Will need separate CI tests for origin, online and enterprise
    a. Enterprise should install packages/images from latest puddle (we'll need to ensure puddles are sync'd)
    a. Online should install packages/images from latest candidate repo
    a. Origin should install packages/images built from latest checkout
1. Online/Enterprise should use RHEL, Origin should use CentOS

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit
