### ISSUE TITLE
Cockpit does not work with 2-step auth

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/openshift-ansible#1331]
So this is just a "heads up", but it seems Cockpit does not like machines that have 2-step auth https://github.com/cockpit-project/cockpit/issues/3678 I will be working on a specific PAM file today but gonna guess that it might be good to have that as an option in the playbooks. Will update with working PAM file

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
