### ISSUE TITLE
cockpit-bridge needs to be installed on nodes

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#1336]
In order for full cockpit functionality we need to install cockpit-bridge on all nodes.

@ebalsumgo

**Comment by sdodson** [comment]
That said, cockpit is limited to adding 5 remote hosts so the value here may not be that great. The real reason that cockpit is installed is for cockpit-kubernetes and that only need to be installed wherever you're running cockpit-ws and the user you're logged into cockpit as needs to have a ~/.kube/config that grants cluster-admin access.

**Comment by detiber** [comment]
Maybe make it optional, with a default of not installing it?

**Comment by ebalsumgo** [comment]
Cockpit is limited to only being able to monitor 5 servers total? yeah thats sub optimal in a prod environment

**Comment by gravis** [comment]
Is this a licence limitation?

**Comment by sdodson** [comment]
It's not a license limitation but a limitation of what Red Hat will support as part of your RHEL subscriptions if you're a subscriber. If you go beyond 5 hosts you'll just get a warning message.

**Comment by gravis** [comment]
So the problem won't occur on Atomic host, right?

**Comment by sdodson** [comment]
My understanding is that the warning will be displayed regardless of whether it's RHEL, Centos, or Fedora. I don't know for sure which cockpit components are installed on the different versions of Atomic Host. Happy to accept PRs adding cockpit-bridge and necessary components everywhere for origin but I think we have a duty to ensure subscribers aren't inadvertently getting an unsupported config so we'd disable that by default on OSE/OCP.

**Comment by ebalsumgo** [comment]
Just to update this a bit. My original concern was about the visibility of the management parts of cockpit, which may/may not be of interest to people at all :)
