### ISSUE TITLE
Error running bin/cluster create on openstack "vars_files" is not a valid attribute

### ISSUE THREAD

**Issue by kunallimaye** [openshift/openshift-ansible#1339]
## Command used to create OSE cluster

``` bash
    bin/cluster create \
        --masters 1 \
        --nodes 2 \
        --deployment-type openshift-enterprise \
        --option public_key=~/.ssh/klimaye-macb-air.pem \
        --option master_flavor=m1.large \
        --option node_flavor=m1.large \
        --option image_name=ose3-pre-req-rhel-7-2 \
        --option dns=8.8.8.8,8.8.4.4 \
        --option cluster_env=dev \
        openstack \
        klimaye-xpaas
```
## Returns an error

``` bash
ERROR! 'vars_files' is not a valid attribute for a PlaybookInclude

The error appears to have been in '/Users/klimaye/Projects/finiteloop.me/ose3/openshift-ansible/playbooks/openstack/openshift-cluster/config.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---  
- include: ../../common/openshift-cluster/config.yml
  ^ here
```

**Comment by kunallimaye** [comment]
## Environment information

+ OS X El Capitan version <kbd>10.11.3</kbd>
+ bin/cluster version <kbd>0.3</kbd>
+ Ansible version <kbd>2.0.0.2</kbd>
+ Python version <kbd>2.7.9</kbd>

```bash
klimaye-mac:openshift-ansible klimaye$ bin/cluster --version
cluster 0.3
klimaye-mac:openshift-ansible klimaye$ ansible --version
ansible 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
klimaye-mac:openshift-ansible klimaye$ ansible-playbook --version
ansible-playbook 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
klimaye-mac:openshift-ansible klimaye$ python --version
Python 2.7.9
```

**Comment by detiber** [comment]
@kunallimaye We haven't yet updated the playbooks/roles to support Ansible 2.0 yet, currently we support running using Ansible 1.9.4.

We are tracking the Ansible 2.0 support here: https://github.com/openshift/openshift-ansible/issues/686

**Comment by akostadinov** [comment]
Also hitting this issue. Any ETA on the work?

**Comment by detiber** [comment]
@akostadinov we are targeting the work for the 1.3/3.3 release. That said, I don't think there is much work left for the existing PR to be in a state ready to merge. The productization team is mainly focused on 1.2/3.2 items currently though.

**Comment by JohnKelty** [comment]
Following advice from above, I tried against Ansible 1.9.4 and receive this error:
```
[root@mtl-vm374 ansible]# ansible-playbook openshift-ansible/playbooks/byo/config.yml
ERROR: fail is not a legal parameter in an Ansible task or handler
```
I tried this on a wide variety of 1.9.x releases all with the same "fail is not a legal parameter" error.  Can you please advise if this is a bug or if there is a combination of openshift-ansible playbook & ansible version that works?

Thanks,
John

**Comment by detiber** [comment]
@JohnKelty there shouldn't be an issue with ansible 1.9.4, can you provide a copy of the inventory you are using?

**Comment by JohnKelty** [comment]
Hi @detiber it is:
```
[OSv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_sudo must be set to true
#ansible_sudo=true

deployment_type=origin

# host group for masters
[masters]
mtl-vm374

# host group for nodes
[nodes]
mtl-vm374

```

Thanks,
John

**Comment by metmajer** [comment]
Experienced the same error using Ansible versions 2.0.2.0 and 2.0.0.2. I then downgraded to 1.9.4 via `pip install ansible==1.9.4` which allows me to execute the playbook.

```
metmajer$ ansible --version
ansible 1.9.4
  configured module search path = None
```

**Comment by detiber** [comment]
We've gotten a lot further along with testing of the v2 compatibility changes here: https://github.com/openshift/openshift-ansible/pull/991

We will be splitting the changes out into smaller PRs and working to get them merged within the next few weeks.

**Comment by JohnKelty** [comment]
I tried several 1.9.4 Ansibles and received that error.  For the record, this one does seem to work fine:
[http://dl.fedoraproject.org/pub/epel/7/x86_64/a/ansible1.9-1.9.4-2.el7.noarch.rpm](url)

**Comment by michaelgugino** [comment]
The affected code path has been removed.

Closing this bug as it is no longer valid.
