### ISSUE TITLE
installer doesn't remove labels that are not present

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-ansible#1343]
For example, given the following node status:

```
master1-9b5f.oslab.opentlc.com      kubernetes.io/hostname=192.168.0.101,region=master                              Ready,SchedulingDisabled   1h
```

And the following line from `/etc/ansible/hosts`:

```
master[1:3].example.com
```

If the installer is run the region label will not be removed from the master node.

This is generally contra to what the user expects, given that the installer will, for other aspects, remove/alter what's already there.

**Comment by detiber** [comment]
This one is a bit tricky...  generally we persist facts to make sure that if a person runs Ansible without setting the variables to ensure that we don't clobber something the user expects.

**Comment by abutcher** [comment]
@detiber We could make these an additive fact with overwrite behavior?

**Comment by abutcher** [comment]
But even then it comes back to having some modules to maintain openshift resource state

**Comment by detiber** [comment]
@abutcher yeah, whatever it would be would be much more involved than a quick fix.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
