### ISSUE TITLE
oauthConfig.templates.error - custom error page template

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#1346]
See docs changes at https://github.com/openshift/openshift-docs/pull/1552 and code changes at https://github.com/openshift/origin/pull/7057

Admin can set a custom error page template for rendering errors during the authentication flow in 

```
oauthConfig:
  templates:
    error: templates/error-template.html
```

**Comment by tbielawa** [comment]
@liggitt are you requesting a specific change here?

This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.

**Comment by liggitt** [comment]
because ansible templates the server config, it is unclear to me which parts of the config can be driven through ansible via custom properties. if this can already be set in the config by ansible via custom properties provided by the user, then no change is needed
