### ISSUE TITLE
oadm prune images command fails with malformed HTTP response

### ISSUE THREAD

**Issue by lypht** [openshift/openshift-ansible#1348]
Hello,

I am able to successfully prune *deployments* and *builds* with `oadm prune <object_type> <options>`.  However, although I receive detail of the *images* to prune using `oadm prune images --keep-tag-revisions=3 --keep-younger-than=60m`, any attempt to actually perform the operation with the `--confirm` argument results in **error: error communicating with registry: Get http://{{ registry-ip }}:5000/healthz: malformed HTTP response "\x15\x03\x01\x00\x02\x02"**

Without the confirm argument:
`oadm prune images --keep-tag-revisions=3 --keep-younger-than=60m`
**Dry run enabled - no modifications will be made. Add --confirm to remove images
Deleting registry layer blobs ...
BLOB
sha256:3da3b622accadc9129b2ac8a8501afd5d7d969533140e5ddb1a8956cd1137fee
sha256:8ea9875808eb04226c24d8e9f8c0498da9a448c621eea01d84960432679e07ed
sha256:9215c8520e6dd3613b255cb61f713f8a20f0eace61bc4ab7b6a08aeadb875048
sha256:c4ad332c650dbfd9ee91dc80aca7eb3293ec80ea91398c7a57391bc55839e136...
Deleting images from server ...
IMAGE
sha256:41b7cde7ab06b5870f5bcfb75a5738708dae6e346fdde92d023d5263a4c0a8b8
sha256:576a7cc9956b4ca42da77d7c6ed03f01f7b540674daed24ce107c393f3752877
sha256:52cd6e2cefc648658d6473da7999f85ce7cb088efd0529ebd58a9a0cd5675ee5
sha256:fc559b24c7da6b2692083ece8793e4740c0fec7be6fc53852e191f62124faba2**

With the confirm argument:
`oadm prune images --keep-tag-revisions=3 --keep-younger-than=60m --confirm`
**error: error communicating with registry: Get http://{{ registry-ip }}:5000/healthz: malformed HTTP response "\x15\x03\x01\x00\x02\x02"**

I have a feeling this is due to the fact that the registry is secure, but  `prune --confirm` uses http.  Thanks in advance for reading.

**Comment by sdodson** [comment]
@miminar does `oadm prune images` need special instructions to work against
a secured registry?

**Comment by miminar** [comment]
No, `https` schema is tried first. `http` is used as a fallback. Just confirmed on current master that prune with confirm flag works on secured registry out of the box.

@lypht is your registry's certificate signed by the same certificate authority the openshift is using? If not, you'll need to pass also `--certificate-authority=` option.

What does `curl --cacert {{ master-config-dir }}/ca.crt -f -i https://{{ registry-ip }}:5000/healthz` produce for you?

**Comment by lypht** [comment]
It was in fact a faulty certificate reference.  Thank you both for the input.

**Comment by lorenzvth7** [comment]
@lypht What did you mean with certificate reference? Have the same issue on a secure registry.

**Comment by lorenzvth7** [comment]
@lypht Can you specifiy the command you did? I tried:
 `oadm prune images --keep-tag-revisions=10 --certificate-authority=/etc/docker/certs.d/172.30.xx.xx:5000/ca.crt` but this wasn't working. Still same issue

**Comment by lorenzvth7** [comment]
Okay sorry. It works when I perform it on my master. Not on a node.
