### ISSUE TITLE
Origin Support

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#136]
- deployment_type=origin should not fail and should be the default (current default is online)
- repo configs for origin:
  - publicly accessible repo containing openshift and openshift-sdn packages
  - publicly accessible repo containing dependencies for any packages not available in epel or centos repos
- should work on centos, bootstrapping dependency repos as needed
- docker images should pull from docker hub

**Comment by ejemba** [comment]
openshift-ansible try to install openshift-sdn-master even if 
`openshift_use_openshift_sdn=False` is is `[os:vars]` section 

    [os:vars]
    ansible_ssh_user=root
    openshift_use_openshift_sdn=False

I got the following error  

    TASK: [openshift_sdn_master | Install openshift-sdn-master] *******************
    failed: [ns327****.ip-5-**-**.eu] => {"changed": false, "failed": true, "rc": 0, "results": []}
    msg: No Package matching 'openshift-sdn-master' found available, installed or updated

Can you please fix this ?

**Comment by detiber** [comment]
https://github.com/openshift/openshift-ansible/pull/139 Provides full support for origin using bin/cluster

**Comment by detiber** [comment]
@twiest this was resolved with https://github.com/openshift/openshift-ansible/pull/139

**Comment by twiest** [comment]
Closing.
