### ISSUE TITLE
Adding inventory pre-validation

### ISSUE THREAD

**Issue by simon3z** [openshift/openshift-ansible#1366]
It would be useful to add a playbook to validate that the hosts in the inventory can be used for the deployment in order to identify early the most trivial errors or conflicts.

Probably also having these checks right after the gathering of the facts would be good enough.

@detiber is there already something like that? Are there some trivial errors that can be caught early?
Thanks.

**Comment by detiber** [comment]
@simon3z We started adding some validation to openshift_facts to catch some errors, but we don't do nearly enough...  some things I can think of off the top of my head that we should be doing:
- check for networking conflicts with the service network and the sdn network
- validate that hostnames are resolvable

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit
