### ISSUE TITLE
[RFE] api-only hosts group for masters that aren't running the controllers service

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-ansible#1382]
Currently we only have a generic "masters" group that results in every system in the group being configured for both controller and api duties.

It would be nice if we added an [api] group for systems that only performed api duties, and left the [masters] for systems that would run the controllers service

**Comment by sdodson** [comment]
Why would one want to do that? What's the use case?

**Comment by detiber** [comment]
@thoraxe I'm finding a use case for this hard as well. I fully expect that over time the controllers will actually become pods running within OpenShift in a way that is similar to the upstream Kubernetes model.

**Comment by sdodson** [comment]
@timothysc Any scalability testing that indicates separation of API and Controller services is necessary?

**Comment by timothysc** [comment]
@sdodson Always a nice-to-have, it depends on what scale.  This is an ops-flexibility as well for piecemeal upgrades.

**Comment by detiber** [comment]
@timothysc Will we ever move towards the upstream model where the controllers are always containerized whether or not the api server is?

Basically, if there is anything on the roadmap for the cluster to manage the controllers independently, then there would be little value of splitting them out with the current method.

**Comment by timothysc** [comment]
@detiber The long-term trend will aim towards self-hosting the components.  api-sever + etcd + node will been needed for boot-strapping, then everything else will be self-hosted... hopefully/eventually.

**Comment by smarterclayton** [comment]
Even if we do that, we'll probably still schedule the controllers tightly with the api servers

**Comment by thoraxe** [comment]
Let's say that I am a service provider. There are thousands of API consumers constantly checking the status of their apps, etc etc. I would probably want to scale my API system out quite large and have several layers of proxies and caches in front of it.

But, that environment likely still only needs three controllers.

That environment may need etcd to be scaled out, though, as I would assume the API requests for information ultimately end up pulling data from etcd?

**Comment by sdodson** [comment]
Adding caching proxies in front of the API is something I don't think we'd
support without very careful testing, I imagine very few resources are
meaningfully cacheable. This sounds like a lot of pre-mature optimizationg,
I think until we see evidence that this is necessary it's not worth doing.

**Comment by timothysc** [comment]
> I would probably want to scale my API system out quite large and have several layers of proxies and caches in front of it.

The api-servers themselves serve as a cache to etcd "resource" requests.  But I agree that its relatively trivial to horizontally scale the api-servers independently.

**Comment by thoraxe** [comment]
Caching/proxies or not, scaling the API layer is something that people are going to want to do sooner rather than later...

**Comment by smarterclayton** [comment]
You don't need 3 controllers.  You need N+1 where N is the number of
failures you want to survive.  You can always just disable the controllers
on some masters, as long as you know you have N+1

**Comment by timothysc** [comment]
> Caching/proxies or not, scaling the API layer is something that people are going to want to do sooner rather than later...

+1, I think calling out the role explicitly makes a lot of sense to me.

**Comment by detiber** [comment]
What if we did one of the following:
- add a variable for listing the controller hosts by inventory name
- add a host level variable that allows for configuring/not configuring the controllers service on a master host.

My concern with breaking it out into a specific role is that it would require a major refactoring of the openshift_master role for something that the majority of users would not care about. It also makes sure that we are tightly coupling the controllers service to hosts that are running the api service.

**Comment by thoraxe** [comment]
If you had something like the following:

```ini
[masters]
foo.example.com api_only=true
bar.example.com api_only=true
baz.example.com
zab.example.com
rab.example.com
```

That would be totally fine with me.
