### ISSUE TITLE
deploy registry fails after advanced install

### ISSUE THREAD

**Issue by xelfe** [openshift/openshift-ansible#1402]
I'm running 2 Centos 7 fresh install and follow everything into [Advanced Installation](https://docs.openshift.org/latest/install_config/install/advanced_install.html) doc.

At start there's already a router deployment that is in standing mode but it's probably normal because I've never set them.

When I'm trying to deploy the registry [Docker registry](https://docs.openshift.org/latest/install_config/install/docker_registry.html)  everything looks good into the events but the pods fail with this error;

`couldn't get deployment default/docker-registry-1: Get https://master.mydomain:8443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1: dial tcp my-ip-node1:8443: connection refused`

It is not suppose to be the master-ip on 8443 instead of node1-ip ? Like I said, it's all on fresh install. Any idea ?

**Comment by abutcher** [comment]
@xelfe Hey, yes that should be master-ip. Does `master.mydomain` resolve to the correct ip?

**Comment by xelfe** [comment]
@abutcher . I dont know how to change that. I just did a normal install from ansible-host like so ;

```
[OSEv3:children]
masters
nodes
[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
[masters]
master.my-domain
[nodes]
master.my-domain openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
node1.my-domain openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
```

**Comment by xelfe** [comment]
> @xelfe Hey, yes that should be master-ip. Does master.mydomain resolve to the correct ip?

the lookup of both node1-my-domain and master-my-domain resolve to the right ip.

**Comment by abutcher** [comment]
@xelfe Are the lookups correct from the node on which the docker-registry deployment pod was scheduled? From that node can you `curl https://master.mydomain:8443/`?

**Comment by abutcher** [comment]
Added `-k` to the curl options but you could also pass `--cacert`

`curl --cacert /etc/origin/master/ca.crt https://master.mydomain:8443/`

**Comment by xelfe** [comment]
curl -k https://master.mydomain:8443;
```
{
  "paths": [
    "/api",
    "/api/v1",
    "/controllers",
    "/healthz",
    "/healthz/ping",
    "/healthz/ready",
    "/logs/",
    "/metrics",
    "/oapi",
    "/oapi/v1",
    "/swaggerapi/"
  ]
}
```
curl --cacert /etc/origin/master/ca.crt https://master.mydomain:8443/ ;

`curl: (7) Failed connect to master.mydomain:8443; Connection refused`

**Comment by abutcher** [comment]
Hmmmm might have a certificate issue. Based on the above this may fail with connection refused:

```
openssl s_client -CAfile /etc/origin/master/ca.crt -showcerts -connect master.mydomain:8443
```

Looking for

```
...
    Start Time: 1455574020
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)           <-- the good stuff
```

**Comment by xelfe** [comment]
both node and master return code:0 ok

**Comment by sdodson** [comment]
You don't have a wildcard dns entry for *.mydomain do you?

**Comment by xelfe** [comment]
Yes I do.. That was the problem. Shame on me. Thank you

**Comment by sdodson** [comment]
So it was routing all requests to your router?

**Comment by xelfe** [comment]
@sdodson: exactly ! Now there still a origin-haproxy-router deploy into pending state. But thanks I can deploy the registry.
