### ISSUE TITLE
scaleup playbook does not configure insecure-registry in sysconfig/docker 

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-ansible#1407]
I added a couple of nodes like this:

```bash
ansible-playbook -i hosts openshift-ansible/playbooks/byo/openshift-cluster/scaleup.yml
```

Afterwards builds on these nodes failed when they could not push to the registry. The following change to `/etc/sysconfig/docker` and restarted of docker fixes it.

```diff
4c4
< OPTIONS='--selinux-enabled'
---
> OPTIONS='--insecure-registry=172.30.0.0/16 --selinux-enabled   '
36a37,38
> BLOCK_REGISTRY=''
> INSECURE_REGISTRY=''
```

Shouldn't `scaleup.yml` apply the `openshift_docker` role which normally makes this change?

**Comment by abutcher** [comment]
@dlbewley Good catch we should definitely be applying that role to `oo_nodes_to_config` in scaleup.yml

**Comment by detiber** [comment]
@abutcher We should probably avoid setting insecure-registry by default now and default to deploying a secured registry.
