### ISSUE TITLE
etcd hostnames on AWS sourced from metadata fail install if AWS DNS not used

### ISSUE THREAD

**Issue by edseymour** [openshift/openshift-ansible#1408]
When installing on AWS the etcd hostname facts seem to honour the metadata pulled from AWS rather than "hostname" or reverse DNS. 

If the EC2 metadata hostname is not resolvable, this causes the installation to fail. 

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

The workaround tried was to comment out the facts retrieval in the normalize_aws_facts of roles/openshift_facts/library/openshift_facts.py. When this is done the etcd hostnames are configured using the hosts' IP addresses. 

```
    # facts['network']['hostname'] = metadata.get('local-hostname')
    # facts['network']['public_hostname'] = metadata.get('public-hostname')
```

**Comment by edseymour** [comment]
Recommendation is now to include openshift_hostname against all hosts in the ansible inventory file.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
