### ISSUE TITLE
Can't login remotely, X509 certificate expired or invalid

### ISSUE THREAD

**Issue by theone4ever** [openshift/openshift-ansible#1431]
I just used the latest revision on master branch to install a single master multiple node open shift cluster. The installation went well, but when i try to login with Openshift CLI remotely, like "oc login", always get error: Unable to connect to the server: x509: certificate has expired or is not yet valid.

Some people say certificate expiration issue usually caused by clock not synced, so shall i install ntp container on each host? 

Thank you in advance.

**Comment by abutcher** [comment]
Hey @theone4ever, configuring ntp/chrony is definitely recommended if your clocks are drifting.

Can you verify your certificate expiration dates with the following command:
```
for i in /etc/origin/master/*.crt; do echo $i; openssl x509 -in $i -noout -enddate; done
```

You will likely need to re-install if one of the certificates is busted. There is an uninstall playbook that makes it easy to start over:
```
ansible-playbook -i <inventory> playbooks/adhoc/uninstall.yml
```

**Comment by abutcher** [comment]
Actually, your cluster probably wouldn't have started if one of those certificates was busted. Before you start over I'd also try passing the generated CA (/etc/origin/master/ca.crt) to `oc login` like this if you haven't already.

```
oc login <master-hostname:port> --certificate-authority=/path/to/ca.crt
```

**Comment by theone4ever** [comment]
HI Abutcher,

I just verified all certificates, all of them will expire at 2018, so this should not be a pb. What interest is that i have no pb if do oc login in my mac. The problem only exists if i do it in a VM (centos based) which has the right time and date. Then i realize the option "--insecure-skip-tls-verify", when set it to true, i can also do it in that VM.

Thank you very much!

BR/Keven

**Comment by michaelgugino** [comment]
It looks like this matter has been solved by answering a question.

Closing this issue as it is resolved.

**Comment by mostafaelsayyad** [comment]
Solution worked for me when I realized that the machine(cent os) date time was not correct.
So, I corrected it and worked fine
