### ISSUE TITLE
Setting openshift_master_dns_port does not get applied to node.yaml.v1.j2

### ISSUE THREAD

**Issue by donovanmuller** [openshift/openshift-ansible#1433]
If you set the [`openshift_master_dns_port`](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_master/tasks/main.yml#L57) group var to something other than the default value of 53 (e.g. `openshift_master_dns_port: 8053`), that port setting will not be applied on [`node.yaml.v1.j2`](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_node/templates/node.yaml.v1.j2) and the default port of 53 will always be used. 

This results in pods on the node unable to resolve service DNS entries.

The [`node.yaml.v1.j2`](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_node/templates/node.yaml.v1.j2) template should include the `dnsPort` [here](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_node/templates/node.yaml.v1.j2#L6) similar to the way it is done for [`master.yaml.v1.j2`](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_master/templates/master.yaml.v1.j2#L50).

**Comment by abutcher** [comment]
When `openshift_master_dns_port` is set to something other than port 53 the kubernetes endpoints are updated with the new backend port and the kubernetes service, which is the default dns ip, still has port 53.

```
# oc get svc/kubernetes
NAME         CLUSTER_IP   EXTERNAL_IP   PORT(S)                 SELECTOR   AGE
kubernetes   172.30.0.1   <none>        443/TCP,53/UDP,53/TCP   <none>     10m
```

```
# oc get ep/kubernetes
NAME         ENDPOINTS                                                        AGE
kubernetes   192.168.122.224:8053,192.168.122.224:8443,192.168.122.224:8053   10m
```

Are you setting `openshift_dns_ip` and can you confirm that your kubernetes service and endpoints look like the above in terms of ports? Can you connect to your kubernetes service ip on port 53? It's likely iptables missing the new dns port?

**Comment by donovanmuller** [comment]
Yeah, was on a wild goose chase 😃 (Turned out to be iptable related). 
Works as advertised.
