### ISSUE TITLE
iSCSI installation fails

### ISSUE THREAD

**Issue by jdnieto** [openshift/openshift-ansible#1434]
In task "Install iSCSI storage plugin dependencies" fails when deployment type is enterprise an rhel_skip_subscription is true.
Should be possible to skip this task.

**Comment by detiber** [comment]
@jdnieto If the system is not registered or subscribed, then many of the other packages will fail to install as well.

As an aside, are you intending to install version 3.0? If you want to install the latest you will need to set deployment_type to openshift-enterprise instead of enterprise.

**Comment by jdnieto** [comment]
@detiber, thanks solved with openshift-enterprise. Misunderstood concept, sorry.
