### ISSUE TITLE
upgrade/v3_1_minor ignoring requested package version

### ISSUE THREAD

**Issue by SillyMoo** [openshift/openshift-ansible#1435]
Tried to upgrade from origin 1.1.0.1 to 1.1.2 using the byo/upgrade/v3_1_minor playbook. I had set in my inventory the lines:

[OSEv3:vars]
openshift_pkg_version=-1.1.2

which works fine for normal installation. But the openshift_pkg_version seems to have been ignored by the upgrade scripts, and lead to an upgrade to verison 1.1.3, not 1.1.2.

**Comment by abutcher** [comment]
@brenton

**Comment by brenton** [comment]
I suspect the same fix that was made to the 3.0 -> 3.1 playbook would be needed for the minor upgrade too: https://github.com/openshift/openshift-ansible/pull/1377/files.  @SillyMoo, Would you mind trying out https://github.com/openshift/openshift-ansible/pull/1438 ?

**Comment by SillyMoo** [comment]
I'm afraid this still updates to the latest version. I think it's because the update uses 'yum update' not 'yum update-to'. If you do 'yum update origin-master-1.1.2' then the docs state that if 'origin-master-1.1.2' is not present then it will behave just like 'yum update origin-master'. If you want to update to a specific version then you need to use 'yum update-to origin-master-1.1.2'.

**Comment by brenton** [comment]
From the yum manpage:

`Note  that "update" works on installed packages first, and only if there are no matches does it look for available packages. The difference is most noticeable when you do "update foo-1-2" which will act exactly as "update foo" if foo-1-2 is installed. You  can  use the "update-to" if you'd prefer that nothing happen in the above case.`

It does sounds like we have an edge case to deal with.  @SillyMoo, in your case was origin-master-1.1.2 already installed?

**Comment by SillyMoo** [comment]
So it was origin-1.1.0.1 was installed, and I was trying to upgrade to 1.1.2, and it went straight to 1.1.3 (even when using the branch from your pull request).

Logs attached.
[upgrade.txt](https://github.com/openshift/openshift-ansible/files/138011/upgrade.txt)

**Comment by SillyMoo** [comment]
Looking at the logs I think it's actually packaging issue at the maxamillion repo?. For some reason updating to origin-node-1.1.2 leads to origin-sdn-ovs-1.1.3 being selected as a dependency. And then origin-sdn-ovs-1.1.3 has origin-node-1.1.3 as a dependency. So by picking origin-node-1.1.2 that leads to origin-sdn-ovs-1.1.3 which leads to all the origin components updating to 1.1.3.

Which is odd.

**Comment by SillyMoo** [comment]
Ok, so quick play around, and:

```yum update-to origin-node-1.1.2```

leads to updating to version 1.1.3, but:

```yum update-to origin*-1.1.2```

Correctly updates to origin 1.1.2.

**Comment by detiber** [comment]
@tdawson @sdodson For any dependencies we have in other subpackages, we probably need to make sure that we are version locking them...  maybe that change just never made it up into the origin spec file?

**Comment by sdodson** [comment]
So you think this would work if everything were symmetric?

pkg a requires b = %{version}
pkg b requires a = %{version} ? I'll test some builds to see if this is the
case, it won't help us with anything that's out there now but it will in
the future.

**Comment by detiber** [comment]
@sdodson exactly. However it would limit us to having to release all sub-packages for any given errata instead of being able to just ship a fix for a single sub-package.

**Comment by sdodson** [comment]
> @sdodson exactly. However it would limit us to having to release all sub-packages for any given errata instead of being able to just ship a fix for a single sub-package.

That's fine, we always push all the packages anyway.

**Comment by cboggs** [comment]
+1

This is a pretty big issue for us, as we can't upgrade safely without a cluster rebuild due to our desire to avoid running release candidates in production.

Any ETA on when 1.2.0 will be released?

**Comment by sdodson** [comment]
I just read through our spec file and it looks like this should be fine now. I tried to do a quick test but ran into other un-related problems with my setup and I don't have time to invest in going further with this right now.

1.2.0 should be any day now.

**Comment by cboggs** [comment]
Ok, thanks for taking a quick look. For what it's worth, we found that trying to upgrade from origin 1.1.4 to origin 1.1.6 causes the cluster to upgrade inconsistently. The masters end up at 1.1.6, but nodes end up at 1.2.0-rc1 due to a SDN package that drags the node packages up past 1.1.6.

I'll see if I can get a cluster rebuilt to manually capture the behavior again. Will also crawl the specs and see if I can gain any insights.

**Comment by SillyMoo** [comment]
Yes I upgraded using 3_1 minor and the nodes all went forward to 1.2, despite 1.1.3 being specified.

**Comment by sdodson** [comment]
Ok, I'll see if I can look at this soon. Until we move to the Centos PaaS sig channels we're a bit hamstrung by the fact that COPR only keeps the latest version of packages with a 14 day grace period. So unless people mirror packages locally and maintain their own repos installing the latest version is all you can do right now.

**Comment by cboggs** [comment]
Yea, we've been mirroring the repo locally for that reason, but now that you mention it, it's possible that we missed something and that's what causing the pain points. Interesting.

**Comment by sdodson** [comment]
This only fixes the v3_1_minor playbook, but can you give the changes in #1897 a try?

**Comment by cboggs** [comment]
Running the new update command manually (just to see deps resolution, not actually letting it run through yet) does indeed seem to fix it. We stumbled upon a solution in the same vein yesterday, this is cleaner though!

Will try it out with a fresh 1.1.4 cluster and let you know.
