### ISSUE TITLE
Update the nodes before deployment

### ISSUE THREAD

**Issue by simon3z** [openshift/openshift-ansible#1436]
For automated deployment it would be useful to be able to update the nodes, for example to avoid issues such as:

```
/usr/bin/docker: relocation error: /usr/bin/docker: symbol dm_task_get_info_with_deferred_remove, version Base not defined in file libdevmapper.so.1.02 with link time reference
```

**Comment by simon3z** [comment]
cc @detiber @enoodle

**Comment by detiber** [comment]
@abutcher I'm torn on this one...

We aren't handling updating hosts prior to doing an installation, so in that sense, this seems more of a bootstrapping step.

However, I can also see benefits to doing it...

**Comment by abutcher** [comment]
@detiber I'm torn too... we have a yum update step in the pre-reqs for advanced. If we decide this would be a convenient thing to add then maybe it shouldn't happen by default?

**Comment by detiber** [comment]
@abutcher agreed...  That said, we could start assembling a bootstrapping playbook that would include these types of tasks. Then it would be something that could be available for use with the ManageIQ integration as well as other integrations as well.

**Comment by abutcher** [comment]
@detiber I like that idea

**Comment by simon3z** [comment]
@detiber @abutcher yeah we need this in ManageIQ regardless... so we may as well add it here and call it (optional) before the usual deployment.
