### ISSUE TITLE
Potential Regression bug regarding oo_first_etcd

### ISSUE THREAD

**Issue by jtslear** [openshift/openshift-ansible#1458]
While testing things, I kept running into an issue with an etcd node that was reused as an origin-node.
  
Since docker is configured first, the facts enforce him to utilize iptables; this is the default for the docker facts.  Now the etcd role also enforces this and works just fine.  But when the play continues and it's executed on `oo_first_etcd` we lose that fact (this is my hunch at least).  The os_firewall role defaults to firewalld, so later on, when firewalld is supposed to go enable itself, it can't.  Systemctl prevents it, due to the iptables play having disabled it in the past and the ansible run fails.

This is only a hunch as I cannot understand why would've lost that fact.  And this only appears to repeat itself when I use an etcd node as an origin-node as well.

I must ask though, if we enforce the use of iptables by default nearly everywhere, why does os_firewall default to using firewalld?

**Comment by detiber** [comment]
@jtslear sorry for the delay in responding here.

The goal with not forcing iptables is that eventually we want to fully migrate to using firewalld instead. The current iptables management is a big hack and there is no way to guarantee atomic operations using iptables, so even with careful planning we could end up with a broken config if we are making changes at the same time as kubernetes and/or docker. There are also some non-openshift roles that are using the os_firewall role and using firewalld directly as well.

That said, it definitely sounds like you are hitting a bug. Are you still able to reproduce this with the latest master? If so, I'd be happy to try and replicate if you can provide the inventory file you are using for deployment.

**Comment by jtslear** [comment]
I am not able to reproduce this at this time.  I'll close this.

It's good to know that you guys are thinking of firewalld into the future.  Thank you for the information.
