### ISSUE TITLE
Current issues with bin/cluster GCE installation

### ISSUE THREAD

**Issue by frankcarey** [openshift/openshift-ansible#1459]
I just spent a few hours banging my head against this and failed again (tried this a few months ago too and failed) :(   Here are the issues I ran into for the next person.  If the GCE installer doesn't work right now, I think it would be best to clarify that in the GCE instructions so people don't waste time with it.
## Installing the right versions of dependencies
- The GCE install instructions don't make any mention of a specific version of ansible or libcloud.. it also doesn't mention the ruby dependencies on the homepage.
- Homebrew (OSX) installs ansible 2.x now, and after having issues there is a ticket suggesting that only 1.9.4 is supported, so I spent time getting that to work. I uninstalled the 2.x version in homebrew and installed  homebrew/versions/ansible19 instead.
- libcloud - not using Centos, but OSX for this, so instructions should clarify that you can install this with `pip install apache-libcloud`, this installs version 0.20.1 (although 1.0.0-pre1 is the latest)
## p12 vs pem vs json files

I hit this issue the last time where auth was failing. It's working now after following instructions. The process is a pain though and it would be a lot better if it could just use the json format as google says the old version is deprecated.
- If you see an error about it being deprecated, it appears it's really just a warning and your error may be elsewhere
## Using an existing project ID

The first project I tried was what I'm using for my google container engine clusters. I was getting the following error

```
File "/usr/local/Cellar/ansible19/1.9.4/libexec/vendor/lib/python2.7/site-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.scanner.JSONDecodeError: ..
```

I spent some time debugging in python, There must be something wrong in the JSON in the stuff google is returning (I noticed there was quite a bit in there like the init scripts?) .. so I said screw it, I'll try a blank project.
## When starting from a blank (new) google project

If you create a brand new project for this using the google UI, but don't select the compute engine page, then the account is never setup with it and you get this error..
`Access Not Configured. The API (Compute Engine API) is not enabled for your project. Please use the Google Developers Console to update your configuration.`

Once you get around that (by just visiting the UI) then I got an error where it seems the SSH key isn't being added to the instances.

```
TASK: [Wait for user setup] ***************************************************
failed: [localhost] => (item={'status': 'RUNNING', 'network': 'default', ...
stderr: Warning: Permanently added '...' (RSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/HIDDEN/launch.retry

localhost                  : ok=9    changed=1    unreachable=0    failed=1
```

**Comment by michaelgugino** [comment]
The affected code path has been removed.

Closing this bug as it is no longer valid.
