### ISSUE TITLE
HTPasswd command not found

### ISSUE THREAD

**Issue by theone4ever** [openshift/openshift-ansible#1460]
Hello everyone,

I installed a open shift cluster (i used centos 7 atomic host as os for both master and nodes). Before setup, i chose HTPasswd as identityProviders. But after installation, when login to master to create some users with this command "htpasswd </path/to/users.htpasswd> <user_name>", it complains that htpasswd command not found. As you know it is cent atomic host, everything running in container, i am not supposed to install addition sw, how shall i create user now? 

Thank you in advance.

BR/Keven

**Comment by sdodson** [comment]
Yeah, this was one of the limitations I ran into when providing the containerized installation. The only thing I could come up with is to use the httpd image. This seemed like it was mostly a convenience item so I'm not sure I'll get to it anytime soon, we'd definitely accept a PR to implement it though.

**Comment by sdodson** [comment]
Actually this is a dupe of #1071 lets discuss there.

**Comment by theone4ever** [comment]
Sure, let's follow up on 1071, close it now.
