### ISSUE TITLE
Volume permission issue when create rc

### ISSUE THREAD

**Issue by theone4ever** [openshift/openshift-ansible#1464]
Hello everyone,

I installed a open shift cluster on centos atomic host. Also i have successfully installed docker image registry. When create pod, everything just works fine, but when create a replication controller which includes the same pod, it always fails. From the docker log, i can see that the container tries to change owner of one directly in mounted volume, but get permission issue.

The definition of the rc:

apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379

And the Dockerfile of the redis image is here: https://github.com/docker-library/redis/blob/b375650fb69b7db819e90c0033433c705b28656e/3.0/Dockerfile. So you can see the once this container started, it tries to change the owner of folder /data which is a mounted volume, is this a problem? Btw, I have disabled selinux, also change mod on folder /var/lib/docker/volumes on each node. 

Thank you in advance!

BR/Keven

**Comment by detiber** [comment]
@theone4ever I do suspect that the issue may be related to the chown, but I'm not familiar enough with the RC configuration to know if there is an easy way to work around it.

Can you create an issue for this against https://github.com/openshift/origin or send an email to the user list: https://lists.openshift.redhat.com/openshiftmm/listinfo ?

**Comment by theone4ever** [comment]
Thank you very much! I have sent an request to user mailing list.
