### ISSUE TITLE
Installation experience feedback

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#1500]
Please provide any feedback on ways that you think the installation experience can be improved for OpenShift here.

**Comment by timothysc** [comment]
A step-by-step guided wizard that drops a decorated inventory file to run at the end.  It would help guide the user through the options, and walk the choose-your-own-adventure-dag.

**Comment by tbielawa** [comment]
The feature described above is part of the atomic-openshift-installer now.

This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
