### ISSUE TITLE
DNS issue in Openstack deployment

### ISSUE THREAD

**Issue by theone4ever** [openshift/openshift-ansible#1512]
Hi all,

I tried to create a cluster on Openstack. I used command below, openstack heat stack has been created without pb. In the created Neurtron subnet, DNS is 8.8.8.8 and 8.8.4.4 which is correct. But the DNS host created in this cluster (hostname is e2e-dns) use itself as nameserver instead of both itself and the two i provided (8.8.8.8 and 8.8.4.4 ), thus it can't access Internet to download package. Is this correct?

bin/cluster create -t origin -n 3 -o image_name=CentOS-7-Generic-Cloud -o external_net=net04_ext -o floating_ip_pool=net04_ext -o master_flavor=m1.medium -o node_flavor=m1.medium -o infra_flavor=m1.medium -o dns=8.8.8.8,8.8.4.4 openstack e2e

**Comment by theone4ever** [comment]
I checked the source code, it seems there is dns forward support if the deployment type is enterprise, atomic-enterprise and so on, also it requires the host os as REHL. my deployment type is origin and using centos, anyway workaround?

**Comment by lhuard1A** [comment]
@theone4ever 
What looks wrong in that setup is:

> In the created Neurtron subnet, DNS is 8.8.8.8 and 8.8.4.4

I expect the DNS of the Neutron subnet to be the IP of the dns VM

> But the DNS host created in this cluster (hostname is e2e-dns) use itself as nameserver instead of both itself and the two i provided (8.8.8.8 and 8.8.4.4 ), thus it can't access Internet to download package.

I expect the dns VM (`e2e-dns`) to use only the DNS that you specified on the `bin/cluster` command line and to ignore what is advertised by DHCP.

Here is what should “force” the DNS setting of the `e2e-test` VM: https://github.com/openshift/openshift-ansible/blob/master/playbooks/openstack/openshift-cluster/files/heat_stack.yaml#L605

**Comment by theone4ever** [comment]
Hi Lenaic,

Thank you for your reply.
I double checked the deployment, actually i was wrong. The DNS server for DNS VM is actually itself, also in the neutron subnet, the DNS server is the DNS VM. 

But the problem comes later when ansible tries to install bind and bind-utils package on DNS VM. Because DNS VM uses itself as DNS server while bind and bind-utils (named service) are not installed, so it can't resolve any domain name on internet, so whole installation failed. 

Did i miss sth?

BR/Keven

**Comment by theone4ever** [comment]
@lhuard1A 
Ok, i see. I was wrong, the DNS server on neutron subnet is the IP of e2e-dns.

But the second part mentioned doesn't seems to work. Some how e2e-dns still uses itself to resolve any domino names, thus bind and bind-utils package can't be installed. Any suggestions?

BR/Keven

**Comment by theone4ever** [comment]
@lhuard1A ,

Btw, i just login to e2e-dns VM, check if anything goes wrong, here is the result of ifconfig:

[openshift@e2e-dns ~]$ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.42.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:a6:6b:c9:7d  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.246.2  netmask 255.255.255.0  broadcast 192.168.246.255
        inet6 fe80::f816:3eff:fee3:3e29  prefixlen 64  scopeid 0x20<link>
        ether fa:16:3e:e3:3e:29  txqueuelen 1000  (Ethernet)
        RX packets 4589  bytes 534404 (521.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3166  bytes 433970 (423.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 1790  bytes 154508 (150.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1790  bytes 154508 (150.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


And here is content in /etc/sysconfig/network-scripts/ifcfg-eth0:

DEVICE="eth0"
BOOTPROTO="dhcp"
DNS1="8.8.8.8"
DNS2="8.8.4.4"
PEERDNS="no"
ONBOOT="yes"

Any idea?

**Comment by lhuard1A** [comment]
The `ifcfg-eth0` of `e2e-dns` looks exactly to what is expected.
Could you check the content of its `/etc/resolv.conf`.
I expect to see `8.8.8.8` and `8.8.4.4` and to not see anything else and particularly not see the Neutron subnet DNS because of the `PEERDNS="no"`.

**Comment by theone4ever** [comment]
@lhuard1A ,

Here is content in /etc/resolv.conf

# Generated by NetworkManager
search novalocal
nameserver 8.8.8.8
nameserver 8.8.4.4


Surprisingly, now DNS VM can resolve domain names. But i have to confess that i was playing around this cluster, so might be side effect of that. So i will try to do a clean install again, see if works as expected.

Btw, does this installation works for centos atomic host? Since DNS VM will install bind package via yum, so i should use centos image, then for master, infra nodes and normal nodes, i should be able to use centos atomic host, right?

BR/Keven

**Comment by theone4ever** [comment]
@lhuard1A 
i just did a new installation, the problem occur again, while heat is bootstrap VMs, the e2e-dns's /etc/reslov.conf looks wrong again:

; generated by /usr/sbin/dhclient-script
search openstacklocal
nameserver 192.168.240.2


while /etc/sysconfig/network-scripts/ifcfg-eth0 looks right:
DEVICE="eth0"
BOOTPROTO="dhcp"
DNS1="147.214.9.30"
DNS2="147.214.252.30"
PEERDNS="no"
ONBOOT="yes"

Does it requires a reboot after heat bootstrap?

BR/Keven

**Comment by theone4ever** [comment]
@lhuard1A 
It seems PEERDNS needs to be set as yes to overwrite /etc/reslov.conf according to centos web site. And i verified it, now it is working. 


At https://www.centos.org/docs/5/html/Deployment_Guide-en-US/s1-networkscripts-interfaces.html, it says below:


PEERDNS=<answer>
where <answer> is one of the following:

yes — Modify /etc/resolv.conf if the DNS directive is set. If using DHCP, then yes is the default.

no — Do not modify /etc/resolv.conf.

**Comment by michaelgugino** [comment]
The affected code path has been removed.  Additionally, it looks like this issue was solved by external documentation.

Closing this issue as it is no longer valid and/or solved.
