### ISSUE TITLE
RFE: installer support for cloud-provider

### ISSUE THREAD

**Issue by dak1n1** [openshift/openshift-ansible#1522]
I recently tested out these settings in my BYO inventory config file during an install. They successfully create the necessary entries in master-config.yaml and node-config.yaml to set up AWS as the cloud-provider:

```
osm_controller_args={'cloud-provider': ['aws'], 'cloud-config': ['/etc/aws/aws.conf']}
osm_api_server_args={'cloud-provider': ['aws'], 'cloud-config': ['/etc/aws/aws.conf']}
openshift_node_kubelet_args={'cloud-provider': ['aws'], 'cloud-config': ['/etc/aws/aws.conf']}
```
This is great because I no longer have to edit configs across all my cluster nodes. However, the installer fails when attempting to start up the master and node services, due to two missing config settings:

-  /etc/aws/aws.conf must be present
- /etc/sysconfig/atomic-openshift-{master, master-controllers, master-api, node} must have AWS credentials (if not using instance-based IAM roles)

Without the two options above, the installer can't set up a cluster with cloud-provider configured for AWS.

Could we maybe create the option to add AWS creds to our BYO inventory, and also have the option to create aws.conf?

**Comment by detiber** [comment]
This is dependent on https://github.com/openshift/openshift-ansible/pull/883 (which provides the generic cloud provider support).
