### ISSUE TITLE
Tolerate structs in clientSecret and bindPassword inputs

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#1525]
https://github.com/openshift/origin/pull/7608 adds the ability to provide `clientSecret` and `bindPassword` values to the master via envvars, files, or encrypted files. 

The benefit is that it allows removing all secrets from the master config file.

To support this, `clientSecret` and `bindPassword` fields in identity provider config snippets could be string values (like they were previously), or be nested maps. In either case, they should just be passed through to the config.

**Comment by detiber** [comment]
@tbielawa this is probably a good one to tackle.
