### ISSUE TITLE
Path problem with mktemp  

### ISSUE THREAD

**Issue by ejemba** [openshift/openshift-ansible#154]
We have a problem with the ansible playbook when mktemp is not located there `/usr/bin/mktemp`, for instance debian based distro it is `/bin/mktemp`

    TASK: [Create local temp directory for syncing certs] *************************
    failed: [ns3271148.ip-5-39-83.eu -> 127.0.0.1] => {"cmd": "/usr/bin/mktemp -d /tmp/openshift-ansible-    XXXXXXX", "failed": true, "rc": 2}
    msg: [Errno 2] Aucun fichier ou dossier de ce type
    FATAL: all hosts have already failed -- aborting
    PLAY RECAP ********************************************************************

Can you fix this ?

**Comment by detiber** [comment]
@ejemba could you verify that this is no longer present when using the following PR: https://github.com/openshift/openshift-ansible/pull/139

**Comment by ejemba** [comment]
mktemp problem disappears .

**Comment by detiber** [comment]
@twiest this issue was resolved with the merging of https://github.com/openshift/openshift-ansible/pull/139

**Comment by twiest** [comment]
Closing.
