### ISSUE TITLE
RFE: put nodeSelector label in default namespace

### ISSUE THREAD

**Issue by goern** [openshift/openshift-ansible#1551]
When using labels for region and zones (as shown in https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example#L156 ) the default namespace will never run a registry or router. 

Fixing it using https://lists.openshift.redhat.com/openshift-archives/users/2016-February/msg00036.html is easy and could be part of a playbook.

**Comment by detiber** [comment]
@abutcher relevant to your current interests.
