### ISSUE TITLE
Name resolution issue with bin/cluster with libvirt

### ISSUE THREAD

**Issue by fredoche** [openshift/openshift-ansible#1552]
Hi,

I went through the instruction set to create a local openshift cluster via libvirt on Fedora 23.  However, cluster creation fails at some point:

```
 bin/cluster create libvirt lenaic
...
fatal: [lenaic-master-59bdd] => Failed to template {{ hostvars[openshift.common.hostname] | certificates_to_synchronize }}: host not found: lenaic-master-59bdd.example.com

```
To me , it seems that node name resolution by the master fails due to problems in name resolution, despite configuring dnsmasq on the host platform according to the instructions [here](https://github.com/openshift/openshift-ansible/blob/master/README_libvirt.md).

Any clue what could be done to get the command going through? Thanks

**Comment by fredoche** [comment]
I ran the same command on tag openshift-ansible-3.0.47-1 and it seems to create the cluster just fine .

**Comment by fredoche** [comment]
I made this fork from the mentionned tag, and added two commits, one for the centos image hash, and one to force docker 1.8.2.

https://github.com/fredoche/openshift-ansible/commits/centos-image-plus-docker-1-8-2

**Comment by detiber** [comment]
@fredoche I started to attempt to reproduce this and I am hitting an issue with the use of the 'equalto' test with the reject filter in playbooks/libvirt/openshift-cluster/tasks/launch_instances.yml.

I'm investigating a solution that would be compatible with jinja 2.7 to get past that problem and reproduce the issue.

**Comment by detiber** [comment]
@fredoche I started the following PR to address this as I work through reproducing: https://github.com/openshift/openshift-ansible/issues/1578 Currently it only consists of a fix for the reject/equalto error I was hitting.

**Comment by detiber** [comment]
@fredoche After working through the issues I hit (and addressed in https://github.com/openshift/openshift-ansible/pull/1578) I was not able to reproduce the issue that you saw. That said, I am running Fedora 22.

@abutcher are your running Fedora 23 to try to see if you can reproduce this?

**Comment by lhuard1A** [comment]
Hi there,

This issue has already been fixed by ae5377c9.

**Comment by fredoche** [comment]
@detiber  Unfortunately I do not have the precise commit number anymore, it was "master", whatever that was for me a few days  ago :whale:  . But yeah I am running fedora 23 and was able to reproduce the issue on 2 different laptops at the time. I'll try to reproduce the issue with the current master but according to @lhuard1A that should be fixed now :+1:

**Comment by fredoche** [comment]
Works fine now, thanks!
