### ISSUE TITLE
Updating 3.1 minor failes with 'with_items expects a list or a set'

### ISSUE THREAD

**Issue by triplonetienne** [openshift/openshift-ansible#1557]
This problem has probably something to do with the undefined ``g_new_master_hosts`` on line 38 of the ``evaluate_groups.yml`` file used in the upgrade. When checking the upgrade.yml file of the v3_1_minor upgrade, this variable is not set. After removing the ``| union(g_new_master_hosts)`` part on line 38, the upgrade succeeded.

**Comment by abutcher** [comment]
Looks like `g_new_master_hosts` needs to be set here as well as a few other places in the upgrade playbooks.

https://github.com/openshift/openshift-ansible/blob/master/playbooks/byo/openshift-cluster/upgrades/v3_1_minor/upgrade.yml#L4-L8
