### ISSUE TITLE
Consider closed auth by default

### ISSUE THREAD

**Issue by cgwalters** [openshift/openshift-ansible#1560]
The origin containers want to come open by default, which I think I understand.  It's good for quickly trying things, and it's also desired in Vagrant, etc.

However, I think users of Ansible should be considered more serious - they may be running it on real servers in their infrastructure, and it might be accessible to the Internet even.

I think we should have closed auth by default - the existing docs on configuring authentication are pretty good.

**Comment by detiber** [comment]
@cgwalters A while back we came to the decision to have Origin default to the product default (AllowAll) and override that for Enterprise and Online installations (DenyAll). 

That said, the ansible variable openshift_identity_providers is available to configure this and is documented in the example host files.

I wouldn't be against changing the default for Origin, but would like confirmation from @smarterclayton before changing the current default.

**Comment by smarterclayton** [comment]
Ansible origin being closed auth by default is fine.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
