### ISSUE TITLE
origin/node image is not being pulled

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-ansible#1561]
I've not been able to track this down but in one of the recent changes (past week~) new installs (CentOS Atomic 7.2) are failing on the first run as it seems the node image isn't being pulled before starting the origin-node service. 

Last week it worked without any issues, the prod branch a few days ago also worked without issues (haven't tried the latest one yet).

The origin-node service is marked as running and ansible continues to run, then when it gets around to adding the node to the cluster it fails. 

`docker ps` shows the container is not running. 

Re-running the playbook, the origin-node container will come up and the install will be successful.

**Comment by andrewklau** [comment]
I tried pre-pulling down the openshift/node image before running the ansible installer, this created a different issue related to openvswitch systemd not existing. This time failing at starting the origin-node service.

Re-running it would fail once the whole install, but each time enabling the origin-node service. So for my 3 master, 1 node case it took 5 runs to complete.

**Comment by detiber** [comment]
@andrewklau The prod, stage, and int branches are used by the OpenShift Ops team, and shouldn't be relied upon, since we don't do any type of generic testing against those branches.

That said, we did change up from "pre-pulling" the images explicitly to attempting to pull the images on demand...  @brenton related to your changes, I believe.

**Comment by brenton** [comment]
Yeah, it's probably related to removing that image pull.  @sdodson, do you think there would be ways to make the systemd units more resilient?  It seems odd to me that starting the unit would require us to prefetch the image.

**Comment by brenton** [comment]
If the safest thing is just to prefetch all the images I guess we can add it back.

**Comment by brenton** [comment]
@andrewklau, would you mind testing https://github.com/openshift/openshift-ansible/pull/1569?  We're still tracking down some edge cases where the master and node startup ordering doesn't seem to be correct.

**Comment by andrewklau** [comment]
@brenton running now, will let you know when it's done

**Comment by andrewklau** [comment]
@brenton yes this fixes the installation issue, however now the install completes with nodes being marked as "NotReady" 

Restarting the origin-node service fixes that. I'm guessing that may be related to the startup order?

**Comment by brenton** [comment]
@andrewklau, OK, the "NotReady" issue is the one we're investigating.

**Comment by sdodson** [comment]
> Yeah, it's probably related to removing that image pull. @sdodson, do you think there would be ways to make the systemd units more resilient? It seems odd to me that starting the unit would require us to prefetch the image.

We could add a unit that's specific to pulling the image, that unit could have a TimeoutStartSec=0, disabling the timeout. Then our unit would keep its timeout but depend on the image pull unit. That way it's clear whether it failed due to image availability or due to a problem in our service.

**Comment by andrewklau** [comment]
@brenton ok thanks, shall I close this issue and is there another one open to track the "NotReady" issue?

**Comment by brenton** [comment]
Yeah, let's close this for now.  I just opened https://github.com/openshift/openshift-ansible/issues/1570.  Feel free to add any info you want.  I'll try and get some of the people on our side to add their notes as well.
