### ISSUE TITLE
Nodes "NotReady" after initial install

### ISSUE THREAD

**Issue by brenton** [openshift/openshift-ansible#1570]

**Comment by brenton** [comment]
I know I've seen this for containerized installs.  I believe we heard report it was happening for RPM installations as well.

**Comment by abutcher** [comment]
Similar issue with rpm installation may be separate. @thoraxe will hopefully be able to confirm after another install.

**Comment by brenton** [comment]
Should we close this?

**Comment by sdodson** [comment]
#1564 would have improved the situation for this.

I believe @thoraxe's situation was traced back to a NetworkManager bug, a separate issue.
