### ISSUE TITLE
Docker not starting after upgrade to Docker 1.9

### ISSUE THREAD

**Issue by david-strejc** [openshift/openshift-ansible#1573]
Using master openshift-ansible repo my cluster won't install any more.

I've noticed that there have been update in Docker package from 1.8 to 1.9.

`Mar 09 09:03:45 1.devcloud.cz systemd[1]: docker.service: Got notification message from PID 7150, but reception only permitted for main PID 7149`

This is in systemctl status docker log. 

Installation fails.

UPDATE: this is not openshift-ansible issue - this is yum package docker 1.9.1 issue

**Comment by hieuhuynh3001** [comment]
How to fix can not enable and start docker server when install openshift-ansible:
> Open : `/roles/docker/tasks/main.yml`. 
> Find line 4 in file `main.yml`:
```
action: "{{ ansible_pkg_mgr }} name=docker state=present"
```
> Change to:
```
action: "{{ ansible_pkg_mgr }} name=docker-1.8.2 state=present"
```

**Comment by dotam** [comment]
Thanks @hieuhuynh3001

**Comment by msirovy** [comment]
maybe use default centos/rhel version should be optional via variable

**Comment by fredoche** [comment]
I added this to my docker host configuration via
```
$ sudo systemctl edit docker
```
```
[Service]
NotifyAccess=all
```

A change in docker certainly involves forking of some kind, and the code that used to notify systemd of its readiness moved from the main process to another. Just my 2 cts though.
At least this allows you to run the latest docker.

**Comment by sdodson** [comment]
Thanks, yesterday I pushed the docker-1.9.1 build into the copr repo that ansible installs from. I've deleted that build while I try to find a bugzilla that addresses the issue you guys ran into. You should be able to run `yum downgrade docker-1.8.2` on your hosts to downgrade to the old version of docker.

**Comment by fredoche** [comment]
@sdodson do you have a link to the bugzilla issue? I'd like to know more about why docker suddenly forks itself (does it even?). thanks

**Comment by jwhonce** [comment]
@fredoche https://bugzilla.redhat.com/show_bug.cgi?id=1300076

**Comment by sdodson** [comment]
FYI, I have pushed docker-1.9.1 back into our COPR repo after including the fixes from the BZ above. I'm including it in our COPR because we're getting ready for Origin 1.2 which will require docker-1.9 and it will be a bit before docker-1.9 is included in Centos extras.

Copr build details https://copr.fedorainfracloud.org/coprs/maxamillion/origin-next/build/167286/

**Comment by fredoche** [comment]
Thanks for the update!

**Comment by sdodson** [comment]
@david-strejc Have you had a chance to re-test this?

**Comment by michaelgugino** [comment]
Current docker version available is much newer than problem version.

Closing this issue as it is no longer valid.
