### ISSUE TITLE
installer doesn't update existing kube configs on nodes when re-run

### ISSUE THREAD

**Issue by edseymour** [openshift/openshift-ansible#1574]
If you re-run the installer with different cluster endpoints, for example `openshift_master_cluster_hostname` aspects of node and master configuration are not updated, and when atomic-openshift-\* services are started they still attempt connection using previously configured settings, and installation fails. The only option appears to be uninstall, then re-install, which is a little drastic.

**Comment by detiber** [comment]
@edseymour this is going to be introduced with the following PR: https://github.com/openshift/openshift-ansible/pull/1142
