### ISSUE TITLE
libvirt provider improvement ideas

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#1580]
Instead of relying on dhcp to assign ip addresses and parsing the ip addresses from the instances, it might make sense to instead use a custom network config that configures instance ip addresses based on a known mac address computed for the host prior to creation.

An example of a network config like this is here: https://github.com/detiber/ansible_v3_vms/blob/master/templates/libvirt_network.xml.j2

**Comment by detiber** [comment]
@lhuard1A @fredoche This crossed my mind as I was working on replicating https://github.com/openshift/openshift-ansible/issues/1552

**Comment by michaelgugino** [comment]
The affected code path has been removed.

Closing this issue as it is no longer valid.
