### ISSUE TITLE
docker fails to start - bad OPTIONS content

### ISSUE THREAD

**Issue by henderb** [openshift/openshift-ansible#1590]
I'm trying to follow https://github.com/openshift/openshift-ansible/blob/master/README_origin.md but it fails at `TASK: [docker | enable and start the docker service]`

docker fails to start and complains that `daemon` should not have options. There seems to be a template variable that didn't get evaluated by ansible?

```
# /etc/sysconfig/docker

# Modify these options if you want to change the way the docker daemon runs
OPTIONS='--insecure-registry=172.30.0.0/16 --selinux-enabled {# openshift_docker_options | default('',True) #}'

DOCKER_CERT_PATH=/etc/docker
```

**Comment by henderb** [comment]
```
# This is an example of a bring your own (byo) host inventory

# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
etcd
lb

# Set variables common for all OSEv3 hosts
[OSEv3:vars]

# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_sudo must be set to true
#ansible_sudo=true

deployment_type=origin

# host group for masters
[masters]
osv3-master.legitscript.com

# host group for nodes
[nodes]
osv3-master.legitscript.com
osv3-node[1:3].legitscript.com

# host group for etcd
[etcd]
osv3-etcd[1:3].legitscript.com

[lb]
osv3-lb.legitscript.com
```

**Comment by abutcher** [comment]
@henderb Not related to this issue but the example inventory in the README shouldn't have an `lb` host group in it. The `lb` group is a stand in haproxy instance for balancing the API when deploying an HA cluster (multiple masters) and won't be necessary in this case.

**Comment by detiber** [comment]
@henderb ah, I suspect the issue may be the use of CentOS 6.  The ansible version is fine (1.9.4), but I suspect that it might be an issue related to the python version or jinja2 version in use.

**Comment by henderb** [comment]
Thanks, I've run it from the master node (CentOS 7 of course) and that worked.
