### ISSUE TITLE
Problem with Validate permissions on the config dir etcd

### ISSUE THREAD

**Issue by hieuhhnl** [openshift/openshift-ansible#1591]
I have problem with etcd:
TASK: [etcd | Validate permissions on the config dir] ************************\* 
failed: [osv3-etcd.example.com] => {"failed": true, "gid": 0, "group": "root", "mode": "0700", "owner": "root", "path": "/etc/etcd", "size": 146, "state": "directory", "uid": 0}
msg: chown failed: failed to look up user etcd

FATAL: all hosts have already failed -- aborting

Please help me check. Thanks

**Comment by detiber** [comment]
@hieuhuynh3001 I think you are actually hitting his bug: https://github.com/openshift/openshift-ansible/issues/1138

**Comment by michaelgugino** [comment]
This issue appears to have been solved in the other bug #1138.
If this issue is still affecting you, please consider opening a new issue.

**Comment by sbadakhc** [comment]
Seeing this again here: https://github.com/openshift/openshift-ansible/issues/7490
