### ISSUE TITLE
Let's encrypt certificate

### ISSUE THREAD

**Issue by david-strejc** [openshift/openshift-ansible#1595]
I've tried to reconfigure Openshift and use let's encrypt certificate (I've used named certificate option when rebuilding Open Shift with ansible) - but Open Shift complains about certificate is not valid.

Is this my fault or should I change something else?

**Comment by abutcher** [comment]
Have you set `openshift_master_cluster_hostname` (internal) and `openshift_master_cluster_public_hostname` (external) in your inventory? In order to use named certificates, these variables must be set to different hostnames so that the named certificate is only served for the public hostname.

**Comment by michaelgugino** [comment]
This issue appears to have been resolved by answering a question.

If this issue is still affecting you, please consider reopening this issue.
