### ISSUE TITLE
Treat single master as an HA config if native HA is specified and cluster hostnames are defined

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#1605]
If the following are True: 
- openshift_master_cluster_method=native
- openshift_master_cluster_hostname is defined
- openshift_master_cluster_public_hostname is defined

Treat even a single master as an HA install.

Currently, if the native cluster variables are set, they are used, but the master service isn't configured to override the loopback kubeconfig, which causes bootstrapping issues when trying to connect to itself through the load balancer.

**Comment by detiber** [comment]
Workaround for now is to set openshift_master_ha = True in the inventory

**Comment by abutcher** [comment]
Sounds like the fix would be to assume `openshift_master_ha = True` when `openshift_master_cluster_method is in ['native', ...]` rather than relying on the count?

**Comment by detiber** [comment]
Well, we can't allow a single master host for pacemaker based clustering (or maybe we could).

I also don't think we want to change the default behavior between a release, so we'd want to change it on a release boundary...  say 1.2/3.2 :)
