### ISSUE TITLE
[Warn user about bad openshift_hostname values

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/openshift-ansible#1607]
I'm trying to use the aws script to install openshift in my vpc
```
TASK: [Warn user about bad openshift_hostname values] ************************* 
[test-openshift-node-compute-xxx, test-openshift-node-compute-bbbb, test-openshift-node-infra-eee]
The hostname "ip-172-32-xx-xx.xx-xx-1.compute.internal" for "ip-172-32-xx-xx" doesn't resolve to an ip address owned by this host. Please set openshift_hostname variable to a hostname that when resolved on the host in question resolves to an IP address matching an interface on this host. This host will fail liveness checks for pods utilizing hostPorts, press ENTER to continue or CTRL-C to abort.:
```

After that it fails:
```
Unable to resolve etcd URLs: lookup ip-172-32-xxx: no such host
```

Can someone explain me this error and tell me how I can avoid this? (I'm not even using etcd)

**Comment by detiber** [comment]
@sdodson thoughts?

**Comment by sdodson** [comment]
@lorenzvth7 Can you show us your nodes group? Is the message correct that 'ip-172-32-xx-xx.xx-xx-1.compute.internal' on host ip-172-32-xx-xx resolves to an IP address that's not local to that host?

**Comment by lorenzvth7** [comment]
@sdodson It's working in other VPC's. So it's not an issue with the ansible probably. Apologies.

**Comment by sdodson** [comment]
Sorry, not sure if you're still having problems or not based on your last comment. Which tasks failed on your compute and infra nodes?

**Comment by deanpeterson** [comment]
I am getting the same error.  I am running the openshift ansible installer.  I set my master and node to point directly to my amazon ec2 instance's public ip.  I create a dns record to point to that same public IP.  I do not reference the internal ip address Ansible is warning about.
