### ISSUE TITLE
Generate certificates on localhost

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#1633]
Hi,

we start the ansible-playbook on an external host. Our problem is all certificates will be generated on the first master instead on the ansible host. If we want to redeploy the master1 host, all certificates (/etc/origin/generated-configs/; /etc/etcd/generated_certs/) will be lost. After re-running the ansible, all certificates will be regenerated. 

Expected: generated all required certificates on the current workdir where is ansible-playbook start, if localhost != master1

Best Regards,
Jan-Otto Kröpke

**Comment by detiber** [comment]
We've discussed this a bit. At some point in the future, the initial certificates needed for bootstrapping the cluster will be generated and replicated from a "bootstrapping host" that may or may not be the host running ansible.  At that point that "bootstrapping host" would be the only one that needs to be backed up certificate wise.

As it stands now:
- The "first" etcd host will host the CA and generated certificates for the etcd server hosts and etcd client certs on the master hosts.
- The "first" master host will host the CA and generated certificates for all of the masters and node certs.

The CA files on the first etcd and first master should be considered important data to be backed up (just as much as the etcd data itself, and important persisted volumes used by pods deployed in the OpenShift cluster), all generated certificates that are not stored in etcd can be regenerated by either running the ansible playbooks against the hosts or by running manual commands to re-generate the certificates needed.

**Comment by jkroepke** [comment]
Hi,

thank you for your response. I have two questions:

Its possible (or planned) to specified:
* a custom ca? The custom ca can be deployed on all masters, before the ansible will be started.
* a custom location for all generated ca files. The ansible installer generate all files on a nfs. If I want to rebuild the first master, the ansible installer could be reuse the file from the nfs storage.
** An alternative: Do you all all locations where the generated ca stored? Maybe I can solved it with symlinks.

**Comment by detiber** [comment]
@abutcher mind giving some more info on the current state and planned state for custom CA files?

**Comment by abutcher** [comment]
We'll be implementing https://github.com/openshift/openshift-ansible/issues/1535 first, which allows for using a custom CA with named certificates for public facing API/console.

Use of a custom CA for generated certificates is planned with the ability to redeploy certificates. That work currently relies on completing https://github.com/openshift/openshift-ansible/pull/1501.

Here are the certificate locations we use today. I like the idea of customizing where these are stored... that's probably something that will come with Jason's original comments re: a bootstrapping host.

`/etc/origin/master` master certificates
`/etc/origin/generated-configs` generated master and node certificates (first master)
`/etc/origin/node` node certificates
`/etc/etcd/generated_certs` generated etcd certificates
`/etc/etcd` etcd certificates

**Comment by tbielawa** [comment]
Both of the linked PR's by @abutcher have been merged.

This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
