### ISSUE TITLE
Handle additional OpenShift configuration files

### ISSUE THREAD

**Issue by simon3z** [openshift/openshift-ansible#1661]
Sometimes (especially in the configuration of `openshift_master_identity_providers`) a manual intervention is necessary to copy files on the nodes.

E.g. the `htpasswd` file for `HTPasswdPasswordIdentityProvider` or a certificate file for `LDAPPasswordIdentityProvider`, etc.

It should be possible to specify local files that gets deployed automatically.

cc @abutcher @detiber

**Comment by detiber** [comment]
@simon3z for htpasswd in particular, do you think providing the file would be of more value, or specifying users and passwords (potentially pre-hashed) to be better?

I do agree on the ldap certs though, I hate asking someone to provide the cert as a variable. @abutcher can this be handled similarly to the named certificates?

**Comment by simon3z** [comment]
> @simon3z for htpasswd in particular, do you think providing the file would be of more value, or specifying users and passwords (potentially pre-hashed) to be better?

I thought that asking for that would have been too much :smile: , but indeed it would be definitely better for us.

**Comment by abutcher** [comment]
@detiber Yup, I'm not sure if the variable should be part of the provider dictionary or something adjacent but we can provide a mechanism to land a cert.

**Comment by detiber** [comment]
@abutcher I'm thinking adjacent variables.
