### ISSUE TITLE
Failing to Verify API Server

### ISSUE THREAD

**Issue by zmhassan** [openshift/openshift-ansible#1662]
When doing the installation of openshift 3.1 on openstack it is failing for me. My setup is 3 Rhel 7.2 servers running on openstack.
It keeps failing at this stage when using the ansible build script. 
```bash
NOTIFIED: [openshift_master | Verify API Server] ******************************
```

 
failed: [master.ose1.xxxx.com] => {"attempts": 120, "changed": false, "cmd": ["curl", "--silent", "--cacert", "/etc/origin/master/ca.crt", "https://master.ose1.xxxx.com:8443/healthz/ready"], "delta": "0:00:00.034010", "end": "2016-03-24 11:49:13.644663", "failed": true, "rc": 7, "start": "2016-03-24 11:49:13.610653", "stdout_lines": [], "warnings": ["Consider using get_url module rather than running curl"]}
msg: Task failed as maximum retries was encountered
 
Steps to reproduce:
* Create 3 vm's on openstack.
* Do all the steps in registering rhn subscription
* set hostname to custom domain `https://master.ose1.xxxx.com` on master
* set hostname to custom domain `https://node1.ose1.xxxx.com` on node1
* set hostname to custom domain `https://node1.ose1.xxxx.com` on node2

* run:  ansible-playbook -i inventory.yml  playbooks/byo/config.yml -vvvv

**Comment by abutcher** [comment]
@zmhassan Are you able to run that curl after the failure and what sort of output do we get?

**Comment by abutcher** [comment]
@zmhassan Also, trade out --silent for --verbose

**Comment by zmhassan** [comment]
@abutcher I'm on internal IRC. I could give you more detail of my setup their `#openshift`
my nick is zhassan

**Comment by zmhassan** [comment]
To answer the questions about running curl. I'm not running curl its the installer that is doing it. I suspect its a dns issue as I'm running internal.

**Comment by zmhassan** [comment]
Issue is resolved. I needed to specify ip address in openshift_hostname because of setup.

**Comment by poltorres7** [comment]
@zmhassan where did you specify the IP address for the openshift_hostname???

**Comment by zmhassan** [comment]
I was using the ansible script to install https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-host-variables
