### ISSUE TITLE
Unable to login to the web console after completion of installation of openshift ose3v1 on openstack

### ISSUE THREAD

**Issue by zmhassan** [openshift/openshift-ansible#1663]
Hi 

I get the following message when I try to login to the main web console for openstack 3v1. 
Cock pit seems to be working but not openshift 3v1

An error occurred during a connection to https://master.ose3v1.xxx.com:8443. security library: improperly formatted DER-encoded message. (Error code: sec_error_bad_der)

**Comment by abutcher** [comment]
Hey @zmhassan, did a re-install resolve this error?

**Comment by zmhassan** [comment]
I was able to install thanks. I'm going to close this
