### ISSUE TITLE
Unable to run rhel_subscribe playbook multiple times

### ISSUE THREAD

**Issue by ncdc** [openshift/openshift-ansible#1670]
It fails because once you run it the first time, the pool becomes part of the consumed pools for the system, so subsequent runs of `Retrieve the OpenShift Pool ID` fail because the pool doesn't show up in `subscription-manager list --available --matches="{{ rhel_subscription_pool }}" --pool-only`

**Comment by abutcher** [comment]
@ncdc Could you try out #1691 ?
