### ISSUE TITLE
Howto use chrony module

### ISSUE THREAD

**Issue by gr3x** [openshift/openshift-ansible#1675]
Hello, I want to use the chrony module available in openshift-ansible (https://github.com/openshift/openshift-ansible/tree/master/roles/chrony) but I don't know how to enable this one.
What I already tried is that:
add the line the "chrony_ntp_servers" in my ansible/host file like that:  
nod001.example.com openshift_hostname=nod001.example.com openshift_ip=1.1.1.1 chrony_ntp_servers='ntp1.example.com,ntp2.example.com,ntp3.example.com' openshift_node_labels="{'env': 'test', 'role': 'node'}"

but it seems not working; 
Best regards,

**Comment by detiber** [comment]
@gr3x the chrony role isn't being invoked as part of the normal playbook run. In order to apply the role, you would need to write a custom playbook for your hosts that would apply the role.

We are currently working on requiring ntpd/chrony as part of the installation as part of the following PR: https://github.com/openshift/openshift-ansible/pull/1672

**Comment by gr3x** [comment]
@detiber ok thank you for your answer, the PR you mentioned is exactly what I want :+1:

**Comment by detiber** [comment]
@gr3x the PR I mentioned above has changed a bit...  Are you looking to use chrony on an atomic host, or on a standard RHEL/CentOS/Fedora host?

**Comment by gr3x** [comment]
Thanks, Jason for your answer.
The chrony/ntpd usage will be only for standard RHEL in a first time.

**Comment by detiber** [comment]
@gr3x okay, so ntpd on RHEL would meet your needs then?

**Comment by gr3x** [comment]
Yes of course, for me ntpd would be even better because all the rest of our
infrastructure already use ntpd by default.

Le 05 Apr 2016 à 20:42, Jason DeTiberus <notifications@github.com> a écrit :

@gr3x <https://github.com/gr3x> okay, so ntpd on RHEL would meet your needs
then?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/openshift-ansible/issues/1675#issuecomment-205942454>
