### ISSUE TITLE
Add GC options 

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#1683]
Hi,

I want to configure the openshift GC via ansible.

Documentation: https://docs.openshift.com/enterprise/3.1/admin_guide/garbage_collection.html

**Comment by detiber** [comment]
@jkroepke there is an example of setting the image gc params here: https://github.com/openshift/openshift-ansible/blob/1565bc6e71bdda712d4cfdbf28754f00b38a4674/inventory/byo/hosts.ose.example#L261

The container gc params can be set using the same method as well.

**Comment by jkroepke** [comment]
Thanks!
