### ISSUE TITLE
ansible version 2.0.1

### ISSUE THREAD

**Issue by zhwenh** [openshift/openshift-ansible#1686]
ansible version 2.0.1 
show error:

ERROR! 'vars_files' is not a valid attribute for a PlaybookInclude

The error appears to have been in '/Users/wenhuazhang/Ansible/roles/openshift-ansible/playbooks/byo/openshift-cluster/config.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- include: ../../common/openshift-cluster/config.yml
  ^ here

**Comment by detiber** [comment]
We've been tracking ansible 2.0+ support here: https://github.com/openshift/openshift-ansible/issues/686

**Comment by moolitayer** [comment]
@detiber It would be helpful to have a clear warning saying ansible version not supported

**Comment by detiber** [comment]
I believe this is now resolved.
