### ISSUE TITLE
Can't run the networking debug script

### ISSUE THREAD

**Issue by bitwalker** [openshift/openshift-ansible#1706]
My cluster is using the AWS playbook. The way things are wired up, I don't have root user access to the instances created by the playbook, I only have the keypair for a sudoer user named centos. This is a problem because the debug script is written with the assumption that it is not only being run as root (when being run from the master), but that the nodes it SSHs to will also be with root user credentials. I tried to modify the script locally and run it with sudo added where possible, but I couldn't get it to work properly. This is doubly inconvenient because I'm having a real hell of a time figuring out some network issues, and the one script that seems designed to help me diagnose is completely unusable for me :(.

Let me know if you need any extra details, I'll be glad to provide any info you need.

**Comment by sdodson** [comment]
@knobunc How do you think we should approach this?

**Comment by michaelgugino** [comment]
The affected code path has been removed.

Closing this issue because it is no longer valid.
