### ISSUE TITLE
unreliable iptables-services installation

### ISSUE THREAD

**Issue by akostadinov** [openshift/openshift-ansible#1709]
It looks like `iptables` package not upgraded if exists but that can break `iptables-services` installation which is newer in repo. I think `iptables-services` should use same version as `iptables`  or have both packages forced to version `latest`.

```
TASK: [os_firewall | Install iptables packages] ******************************* 
ok: [ec2-52-23-215-161.compute-1.amazonaws.com] => (item=iptables) => {"changed": false, "item": "iptables", "msg": "", "rc": 0, "results": ["iptables-1.4.21-14.el7.x86_64 providing iptables is already installed"]}
failed: [ec2-52-23-215-161.compute-1.amazonaws.com] => (item=iptables-services) => {"changed": true, "item": "iptables-services", "rc": 1, "results": ["Loaded plugins: amazon-id, rhui-lb, search-disabled-repos\nResolving Dependencies\n--> Running transaction check\n---> Package iptables-services.x86_64 0:1.4.21-16.el7 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package                 Arch         Version               Repository     Size\n================================================================================\nInstalling:\n iptables-services       x86_64       1.4.21-16.el7         rhel-72        50 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package\n\nTotal download size: 50 k\nInstalled size: 24 k\nDownloading packages:\nRunning transaction check\nERROR with transaction check vs depsolve:\niptables = 1.4.21-16.el7 is needed by iptables-services-1.4.21-16.el7.x86_64\n You could try running: rpm -Va --nofiles --nodigest\nYour transaction was saved, rerun it with:\n yum load-transaction /tmp/yum_save_tx.2016-04-05.15-50.02Wuyy.yumtx\n"]}

FATAL: all hosts have already failed -- aborting
```

**Comment by sdodson** [comment]
This seems like repo error, what's the output of this?
```
repoquery --installed iptables iptables-services
repoquery iptables iptables-services
```

**Comment by akostadinov** [comment]
I have filed a pull #1710 . Issue is that ansible is not smart enough to upgrade `iptables` if it is already installed and then tries to install newer `iptables-services`.

**Comment by sdodson** [comment]
which version of iptables was installed? i suspect your pr will fix it regardless

**Comment by akostadinov** [comment]
iptables-0:1.4.21-14.el7.x86_64

**Comment by sdodson** [comment]
This was determined only to be a problem when a host was installed with a pre-release version of iptables and then that version of iptables was no longer available in the repo set. Not a problem for us to solve.

**Comment by jaryn** [comment]
I have this problem with `iptables 1.4.21-17.el7` on `rhel-guest-image-7.4-62.x86_64.qcow2` when using OA to deploy OSP 3.5. It wants to install `1.4.21-18.el7`.

**Comment by sdodson** [comment]
So your image has 7.4 version of iptables installed but do you have 7.4 repos enabled? I assume not, enable 7.4 repos and I imagine this will go away.

**Comment by jaryn** [comment]
### In short

I don't think this is any problem with the repos. I think ansible has some bug in the package module.

### In long

We have
```
[cloud-user@ose3-master ~]$ yum repolist -v | grep -e 'Repo-id' -e 'Repo-baseurl'
Repo-id      : RH7-RHAOS-3.4/x86_64
Repo-baseurl : http://download.lab.bos.redhat.com/rcm-guest/puddles/RHAOS/AtomicOpenShift-signed/3.4/2017-04-21.4/RH7-RHAOS-3.4/x86_64/os
Repo-id      : latest_rhel_z_stream/x86_64
Repo-baseurl : http://download.devel.redhat.com/rel-eng/repos/rhel-7.4-candidate/x86_64/
Repo-id      : ose
Repo-baseurl : http://download-node-02.eng.bos.redhat.com/rcm-guest/puddles/RHAOS/AtomicOpenShift-signed/3.4/latest/RH7-RHAOS-3.4/x86_64/os
Repo-id      : rhel-extras-candidate
Repo-baseurl : http://download-node-02.eng.bos.redhat.com/brewroot/repos/extras-rhel-7.4-container-build/latest/x86_64/
Repo-id      : rhel-latest/x86_64
Repo-baseurl : http://download-ipv4.eng.brq.redhat.com/rel-eng/latest-RHEL-7/compose/Server/x86_64/os/
```

This is with the new image:
```
[cloud-user@ose3-master ~]$ yum list installed iptables iptables-services
Loaded plugins: search-disabled-repos
Installed Packages
iptables.x86_64                                                                  1.4.21-18.el7                                                          installed            
iptables-services.x86_64                                                         1.4.21-18.el7                                                          @latest_rhel_z_stream
```
That says to me that we didn't had to upgrade the `iptables` as it is from "repo" `installed` which means it was on the image. The need to ugrade of the `iptables` was the problem. `yum install iptables iptables-services` suceeded, but ansible ensuring `state:present package: iptables iptables-services` has probably some bug in computing dependencies and failed to install. `state:upgrade` caused no issues.

**Comment by akostadinov** [comment]
@jaryn I also think that there is something fishy in the ansible behavior. Perhaps file an issue in the ansible project.

**Comment by sdodson** [comment]
The @ prefix to the repo name  here incidates that the repo which installed this package is no longer enabled. So, when verifying that iptables-services is installed I think it causes a problem.

What happens on this host if you run `yum install iptables-services` ?
