### ISSUE TITLE
osv3 enterprise auth should default to deny

### ISSUE THREAD

**Issue by sosiouxme** [openshift/openshift-ansible#171]
@detiber This is a small thing but wanted to make sure it's not forgotten...

The generated config for the master leaves the default "anypasswd" authentication in place. When we talked about this a while back, we said we wanted to default to "deny" (aka secure out of the box) and then allow the administrator to open that up the way they want. I assume configuring authentication is somewhere down the road for the installer, but we should still begin by defaulting to deny.

**Comment by detiber** [comment]
@sosiouxme Do you think we should default to deny for all deployment types, or just enterprise and online deployment types (leaving origin deployment types anypasswd to make for a better initial experience) ?

**Comment by sosiouxme** [comment]
Leave origin deployment types to anypasswd.

----- Original Message -----

**Comment by sdodson** [comment]
Related: 
* https://bugzilla.redhat.com/show_bug.cgi?id=1205969
* https://bugzilla.redhat.com/show_bug.cgi?id=1206414 (sorta)
* https://trello.com/c/XlDJ66hG

**Comment by detiber** [comment]
@twiest @sosiouxme This can be closed, not sure when it was merged, but this has been the default for --deployment-type=enterprise for a while now.
