### ISSUE TITLE
After merge #1708 Openshift is not installing on FC23

### ISSUE THREAD

**Issue by rikatz** [openshift/openshift-ansible#1711]
After merge #1708 the installation of Openshift on FC23 stops working.

FC23 uses docker 1.9.1 (instead of Docker 1.8.2) and this causes some problems with dnf downgrade.

Another solution would be to allow user to enable or disable, on Ansible Hosts file (/etc/ansible/hosts) the install of Docker or the usage of it's own Docker.

**Comment by detiber** [comment]
@rikatz are you using the docker-storage-setup role? or was it the merging of https://github.com/openshift/openshift-ansible/pull/1655 that caused the issue you are seeing?

**Comment by sdodson** [comment]
Ok, so Fedora 23 shipped with Docker-1.7 and has 1.9.1 in updates. So it won't have docker-1.8.2 available. Origin 1.1.4 and newer should actually be fine so i'll relax the downgrade to docker-1.8.2 logic which should hopefully address this.

**Comment by sdodson** [comment]
Should be fixed now by only downgrading when origin < 1.1.4, can you pull the latest and verify?

**Comment by rikatz** [comment]
@detiber No, I have other issues with docker-storage-setup (primarily with the --storage-opt dm.use_deferred_removal=true --storage-opt dm.use_deferred_deletion=true) when using Docker binary (1.10), but I do remove them, and Docker starts normally.

The problem was the ansible scripts trying to downgrade docker to 1.8.4 :) But I think this should work now, gonna try on my environment ;)

**Comment by sdodson** [comment]
The section option isn't supported in docker-1.8.2. `--storage-opt dm.use_deferred_deletion=true` so when downgrading to that you need to remove that.
