### ISSUE TITLE
Containerized install broken on missing docker executable

### ISSUE THREAD

**Issue by simon3z** [openshift/openshift-ansible#1712]
The deployment is broken when setting `containerized=true` for hosts that don't have docker installed yet:

```
TASK: [openshift_facts ] ****************************************************** 
failed: [vm-oshift01.vn1.bytenix.com] => {"cmd": "docker exec origin-master openshift version", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting
```

cc @detiber @alongoldboim @dkorn

**Comment by abutcher** [comment]
Ran into this one for node hosts /cc @sdodson

**Comment by abutcher** [comment]
Not sure if it makes sense to default the version information collected when docker isn't installed and `is_containerized == true` or refactor so that docker is installed where it needs to be before we collect facts

**Comment by detiber** [comment]
@abutcher we can always query the available version in openshift_facts if the package isn't installed, similar to how we are checking the container version available (or should be)...

**Comment by abutcher** [comment]
@detiber this is the check for available container version?

**Comment by detiber** [comment]
@abutcher I know that if docker is installed we attempt to pull the "client" container and get the version from the container. We could do something similar with non-containerized by checking the version of the available package (if available in a repo).

That said, we should be skipping those checks for is_containerized and docker is not available, they should then be properly gathered when openshift_facts is run after docker is installed.

**Comment by michaelgugino** [comment]
This issue appears to have been solved.  Docker is now installed on masters, nodes, and etcd hosts when containerized.

Closing this issue because it is solved.
