### ISSUE TITLE
How to remove the docker version of the check, I need to manually install the docker

### ISSUE THREAD

**Issue by zhwenh** [openshift/openshift-ansible#1714]
How to remove the docker version of the check, I need to manually install the docker，
Now playbook setup needs docker 1.8.2，But our server must to install docker 1.10.3
my hosts content:

[OSEv3:children]
masters
nodes

[OSEv3:vars]

ansible_ssh_user=root
osm_cluster_network_cidr=172.16.0.0/16
openshift_docker_options="--insecure-registry 172.16.0.0/16 --ipv6=false"

openshift_pkg_version=-1.1.6
deployment_type=origin

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

[masters]
10.1.130.14

[nodes]
10.1.130.14 openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
10.1.130.15 openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
10.1.130.16 openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
#10.1.130.16 openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

[testhost]
10.1.130.14
10.1.130.15
10.1.130.16

***my repo file content ***
[extras]
name=CentOS-$releasever - Extras
baseurl=http://mirror.centos.org/centos/$releasever/extras/$basearch/
gpgcheck=1
gpgkey=http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7

**After manual setup docker 1.9.1 ,now show this errors:**
TASK: [docker | Downgrade docker if necessary] ******************************** 
failed: [10.1.130.14] => {"changed": true, "cmd": ["yum", "downgrade", "-y", "docker-1.9.1"], "delta": "0:00:01.206202", "end": "2016-04-07 09:14:42.796258", "rc": 1, "start": "2016-04-07 09:14:41.590056", "warnings": ["Consider using yum module rather than running yum"]}
stderr: Error: Package: docker-1.9.1-25.el7.centos.x86_64 (extras)
Requires: docker-forward-journald = 1.9.1-25.el7.centos
Installed: docker-forward-journald-1.9.1-25.1.origin.el7.centos.x86_64 (@maxamillion-origin-next)
docker-forward-journald = 1.9.1-25.1.origin.el7.centos
Available: docker-forward-journald-1.9.1-25.el7.centos.x86_64 (extras)
docker-forward-journald = 1.9.1-25.el7.centos
stdout: Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile

elrepo: repos.lax-noc.com
epel: mirror01.idc.hinet.net
rpmforge: mirrors.neusoft.edu.cn Resolving Dependencies --> Running transaction check ---> Package docker.x86_64 0:1.9.1-25.el7.centos will be a downgrade --> Processing Dependency: docker-forward-journald = 1.9.1-25.el7.centos for package: docker-1.9.1-25.el7.centos.x86_64 ---> Package docker.x86_64 0:1.9.1-25.1.origin.el7.centos will be erased --> Finished Dependency Resolution You could try using --skip-broken to work around the problem You could try running: rpm -Va --nofiles --nodigest
FATAL: all hosts have already failed -- aborting

**I Modify the two files roles\docker_storage_setup\tasks\main.yml and 
roles\openshift_docker_facts\tasks\main.yml Change 1.8.2 into 1.9.1.
Or not, who can tell me how can I skip the docker inspection and installation**

**Comment by detiber** [comment]
@zhwenh can you explain your use case? There is currently a performance issue related to Kubernetes < 1.2 when using Docker 1.9 and some questions about compatibility with docker 1.10 as well.

**Comment by zhwenh** [comment]
openshift_pkg_version=-1.1.6
deployment_type=origin
