### ISSUE TITLE
Automatically detect packages version to install when adding new nodes

### ISSUE THREAD

**Issue by simon3z** [openshift/openshift-ansible#1727]
When adding new nodes the exact version of OpenShift to install should be automatically determined by looking at the already existing nodes.

cc @detiber

**Comment by abutcher** [comment]
@smunilla was looking into this recently

**Comment by abutcher** [comment]
Folks may also want to add nodes at a specific or latest version for blue/green node deploys.

**Comment by sdodson** [comment]
We do this with containerized installs and for RPMs you're limited to current channel. We should investigate adding this for rpm installs though.

**Comment by abutcher** [comment]
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1359703

**Comment by smunilla** [comment]
This is indeed something we're looking into. I'd prefer to keep a cluster as in sync as possible

**Comment by jhaohai** [comment]
any update? When I add new node to a v1.3 cluster, the ansible playbook install v1.5 origin into my node

**Comment by michaelgugino** [comment]
@sdodson this looks to be completed, or are we planning on backporting this?

**Comment by sdodson** [comment]
No, looks like this is in 3.2 and newer assuming you use the scaleup playbooks.
