### ISSUE TITLE
Typo for "Kind" and "Name" in xpass image stream template file

### ISSUE THREAD

**Issue by chunyunchen** [openshift/openshift-ansible#1729]
Met below errors when installing ose 3.2 with ansible:

"stderr: Error from server: ImageStream "jboss-eap70-openshift" is invalid: [spec.tags[1.3-Beta].from.name: Invalid value: "": must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[1.3-Beta].from.name: Required value: name is required, spec.tags[1.3-Beta].from.kind: Required value: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "redhat-sso70-openshift" is invalid: [spec.tags[1.3-TP].from.name: Invalid value: "": must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[1.3-TP].from.name: Required value: name is required, spec.tags[1.3-TP].from.kind: Required value: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']"

The keywords name should be "kind" and "name", but not "Kind" / "Name"

Typo locations:
[1] https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v1.2/xpaas-streams/jboss-image-streams.json#L155-L156

[2] https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v1.2/xpaas-streams/jboss-image-streams.json#L262-L263

**Comment by sdodson** [comment]
This should already be fixed in master, can you please make sure your branch is up to date and try again?

**Comment by chunyunchen** [comment]
@sdodson It's fixed, I am closing the issue. Thanks!
