### ISSUE TITLE
Add ability to pin version installed

### ISSUE THREAD

**Issue by elyscape** [openshift/openshift-ansible#1741]
Right now, there is no ability to set which version of OpenShift Origin is installed. This is something that would be useful for compliance/reproducibility purposes.

**Comment by abutcher** [comment]
Hey @elyscape you should be able to do something like this in your inventory to control which version of Origin is installed.

```
deployment_type=origin
openshift_pkg_version=-1.1.4
```

**Comment by elyscape** [comment]
Hey, you're right! I'm not sure how I missed that. Thanks for your help!
