### ISSUE TITLE
Installer should have the ability to configure image streams pointing to a private docker-registry

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-ansible#1747]
For running installs disconnected from the internet, we need to be able to point /etc/sysconfig/docker, as well as the image stream templates to a private registry for image content.

@detiber @oybed @timothyh @sabre1041

**Comment by sdodson** [comment]
Fixed in https://github.com/openshift/openshift-ansible/pull/1925

**Comment by sdodson** [comment]
A subsequent PR made that optional. you'll want to set `openshift_examples_modify_imagestreams=True`
