### ISSUE TITLE
bad parsing data in /etc/sysconfig/docker

### ISSUE THREAD

**Issue by bigsow** [openshift/openshift-ansible#1757]
ansible 1.9.5
During installation OSE via /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml, I got:
`NOTIFIED: [openshift_docker | restart openshift_docker] *********************** failed: 
[servername] => {"failed": true} msg: Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details. `

I found that is problem during parsing,
Ansible modified /etc/sysconfig/docker file at line 4 to:
`OPTIONS='--insecure-registry=172.30.0.0/16 --selinux-enabled {# openshift_docker_options | default('',True) #}'`
and Docker service start failed,

when I had changed above line to
`OPTIONS='--insecure-registry=172.30.0.0/16 --selinux-enabled`
Docker service starded perfectly.

So I had changed problematic line 4 and after I ran Ansible again by command:
`ansible-playbook -i hosts /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml,`
Ansible playbook modified /etc/sysconfig/docker again, to value:
`OPTIONS='--insecure-registry=172.30.0.0/16 --selinux-enabled {# openshift_docker_options | default('',True) #}'`
and the Docker service start failed again :(,

I know that my problem is from OSE, but mabye you have any solution, how to investigate problem with bad parsing,
I remember that when I tried to install OSE from opensift-ansible gir repo, I got problem with /etc/origin/node/node-config.yaml
at the end of line 4 (whole line below)
`dnsIP: {# openshift_dns_ip | default(openshift_master_cluster_vip | default(None if openshift.common.version_gte_3_1_or_1_1 | bool else openshift_node_first_master_ip | default(None, true), true), true) #} is "#}" ?`

**Comment by sdodson** [comment]
Can you tell us which version of the playbooks you have installed?
`rpm -q openshift-ansible`

**Comment by abutcher** [comment]
@bigsow also, what versions of python and python-jinja2 are you using?

**Comment by bigsow** [comment]
```
# rpm -qa|grep  openshift-ansible
openshift-ansible-3.0.47-6.git.0.7e39163.el7aos.noarch
openshift-ansible-playbooks-3.0.47-6.git.0.7e39163.el7aos.noarch
openshift-ansible-filter-plugins-3.0.47-6.git.0.7e39163.el7aos.noarch
openshift-ansible-roles-3.0.47-6.git.0.7e39163.el7aos.noarch
openshift-ansible-lookup-plugins-3.0.47-6.git.0.7e39163.el7aos.noarch
```
but I get only playbooks and roles from it, tar and copy to my Fedora labptop, to similar path, because I have got access to repository !rhel-7-server-ose-3.1-rpms/x86_64 only on servers, and opensift-ansible is available only there :(

On my laptop I have got:
- ansible-1.9.5.tar.gz,
- Python 2.7.3
- jinja2:
>>> import jinja2
>>> print jinja2.__version__
2.6

**Comment by bigsow** [comment]
Ok I think that my problem was due to bad Ansible versions or any python libraries, I finished another installation from rhel7 and everything was ok.
