### ISSUE TITLE
Various difficulties with AWS integration

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-ansible#1760]
I'm working on some improvements to the README and playbooks/roles for the aws integration. Currently, however i'm getting stuck here:

```
PLAY [Configure master certificates] ****************************************** 

GATHERING FACTS *************************************************************** 
FATAL: no hosts matched or all hosts have already failed -- aborting


TASK: [openshift_facts | Verify Ansible version is greater than or equal to 1.9.4 and less than 2.0] *** 
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/launch.retry

52.23.249.165              : ok=0    changed=0    unreachable=1    failed=0   
52.90.247.150              : ok=0    changed=0    unreachable=1    failed=0   
52.91.105.211              : ok=0    changed=0    unreachable=1    failed=0   
54.209.35.103              : ok=0    changed=0    unreachable=1    failed=0   
esauer-test-master-5f86a   : ok=44   changed=8    unreachable=0    failed=0   
esauer-test-node-compute-be05b : ok=32   changed=7    unreachable=0    failed=0   
esauer-test-node-compute-c63a1 : ok=32   changed=7    unreachable=0    failed=0   
esauer-test-node-infra-0dc66 : ok=32   changed=7    unreachable=0    failed=0   
localhost                  : ok=89   changed=9    unreachable=0    failed=0   

ACTION [create] failed: Command 'ansible-playbook  -i inventory/aws/hosts -e 'num_masters=1 num_nodes=2 cluster_id=esauer-test cluster_env=dev num_etcd=0 num_infra=1 deployment_type=openshift-enterprise' playbooks/aws/openshift-cluster/launch.yml' returned non-zero exit status 3
```

Hosts are being flagged twice in the inventory, as both a host and an IP. Any pointers?

cc: @detiber

**Comment by detiber** [comment]
@etsauer the issue here is that the playbooks are adding the hosts using the friendly names and the dynamic inventory is returning the hosts listed as IPs.

Are you getting this from directly running the bin/cluster script or by invoking the aws launch playbook in a different way?

**Comment by etsauer** [comment]
@detiber i am directly invoking bin/cluster

**Comment by detiber** [comment]
@etsauer is there by chance another 'cluster' deployed in your aws account named 'test-cluster' ?

**Comment by detiber** [comment]
@etsauer or did you previously destroy one and try to spin up another one with the same name? If so you will want to run inventory/aws/ec2.py --refresh-cache to clean up the stopped/removed instances.

**Comment by etsauer** [comment]
@detiber yes, that was it. I had an old cluster with the same name. That's gotten me further. Now I get this:
```
TASK: [openshift_facts ] ****************************************************** 
fatal: [esauer-test2-node-compute-f055c] => One or more undefined variables: 'ec2_region' is undefined
fatal: [esauer-test2-node-compute-a68a6] => One or more undefined variables: 'ec2_region' is undefined
fatal: [esauer-test2-node-infra-c488f] => One or more undefined variables: 'ec2_region' is undefined

FATAL: all hosts have already failed -- aborting
```

The master succeeds and seems to get through this, but once we get around to configuring nodes, they're not seeing my exported vars (or at least this specific one). All hosts are already created and running by this point, which should be proof that at one point this var was set.

**Comment by detiber** [comment]
@etsauer it looks like the value wasn't getting set on the config playbook which would affect subsequent runs.

**Comment by metmajer** [comment]
I am facing the very same issue. Any clues on how to resolve the issue?
