### ISSUE TITLE
Ship byo example inventories in openshift-ansible RPM?

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#1769]
As a stop gap to mitigate issues of ensuring that ansible options match those in our product documentation should we ship the example byo inventories in the base RPM or the docs RPM? Currently the docs rpm is pretty much oriented towards developers rather than users.

**Comment by sdodson** [comment]
@detiber @abutcher thoughts?

**Comment by abutcher** [comment]
+1 the example inventory is pretty rough so I almost want to say docs rpm.
