### ISSUE TITLE
Setup openshift from docker images

### ISSUE THREAD

**Issue by patjlm** [openshift/openshift-ansible#177]
Openshift can run from docker images:

  docker run -d --name "openshift-origin" --net=host --privileged \
      -v /var/run/docker.sock:/var/run/docker.sock \
      openshift/origin start

Would it be possible to make openshift-ansible use this method of installation instead of Yum ? that would remove some requirements.

**Comment by detiber** [comment]
@patjlm The short answer is: yes, eventually.

**The longer answer:**
Current development in the module is focused on Enterprise and Online deployments which will be using the yum install method for the near future. I don't foresee any work being done towards docker based deployments until after 3.0 GA, however I'd be more than happy to help review, test and troubleshoot any contributions towards adding that support.

**Comment by patjlm** [comment]
Thanks for the answer.
Not being a big ansible user (yet), I am not able to contribute that. I will do if I end up doing it on my side.
I guess this ticket can be closed then.

**Comment by detiber** [comment]
@patjlm If you don't mind, I'd like to keep it open since it is something that still needs to be addressed.

**Comment by rhcarvalho** [comment]
@detiber isn't this already supported?

**Comment by abutcher** [comment]
Yes, setting `containerized=true` per host or globally will perform containerized install.

**Comment by rhcarvalho** [comment]
Closing this since we already support containerized installations.
