### ISSUE TITLE
Additional features for metrics support

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#1780]
This is for work to build upon https://github.com/openshift/openshift-ansible/pull/1582

> we can tweak USE_PERSISTENT_STORAGE but not METRIC_DURATION which is critical for us.
Do you think it will be possible to be added?
> Also the (soon?) coming METRIC_RESOLUTION is also really important: openshift/origin-metrics#101

**Comment by enoodle** [comment]
@simon3z @detiber should I close #1767 ?

**Comment by detiber** [comment]
@enoodle no, I'll close this issue in favor of yours.
