### ISSUE TITLE
Deploying docker-registry; PersistentVolume's nfs server show incorrect host

### ISSUE THREAD

**Issue by jmashburn** [openshift/openshift-ansible#1794]
Deploying origin using Vagrant on mac, the nfs server entry (inventory_hostname) shows master1 instead of openshift-master1.example.com.  If I where to add master1 to the node's /etc/hosts file the registry deploys no problem.

`{
    "kind": "PersistentVolume",
    "apiVersion": "v1",
    "metadata": {
        "name": "registry-volume",
        "selfLink": "/api/v1/persistentvolumes/registry-volume",
        "uid": "12af2f9c-08b8-11e6-aba1-525400b263eb",
        "resourceVersion": "371",
        "creationTimestamp": "2016-04-22T18:28:56Z"
    },
    "spec": {
        "capacity": {
            "storage": "5Gi"
        },
        "nfs": {
            "server": "master1",
            "path": "/exports/registry"
        },
        "accessModes": [
            "ReadWriteMany"
        ],
        "claimRef": {
            "kind": "PersistentVolumeClaim",
            "namespace": "default",
            "name": "registry-claim",
            "uid": "1307630b-08b8-11e6-aba1-525400b263eb",
            "apiVersion": "v1",
            "resourceVersion": "367"
        },
        "persistentVolumeReclaimPolicy": "Retain"
    },
    "status": {
        "phase": "Bound"
    }
}`

**Comment by detiber** [comment]
@jmashburn is this when using the PR here: https://github.com/openshift/openshift-ansible/pull/1697 ?

**Comment by jmashburn** [comment]
@detiber Yes, just did a new pull/install and the PersistentVolume's nfs server is set at "master1".

**Comment by detiber** [comment]
@jmashburn ok, I'm going to go ahead and close this issue out, since the Vagrantfile in master does not even support this yet.

Could you add a comment to the open PR?
