### ISSUE TITLE
Centos 7 on AWS install failing on TASK: [openshift_node_dnsmasq | fail msg="Not implemented"]

### ISSUE THREAD

**Issue by donovanmuller** [openshift/openshift-ansible#1795]
Trying to install with [latest master](https://github.com/openshift/openshift-ansible/commit/04b52454275572f9d09e76c6ce46bdd60aa46c72) and getting the following:

```
TASK: [openshift_node_dnsmasq | fail msg="Not implemented"] *******************
failed: [ec2-54-174-6-95.compute-1.amazonaws.com] => {"failed": true}
msg: Not implemented
failed: [ec2-54-174-40-221.compute-1.amazonaws.com] => {"failed": true}
msg: Not implemented
failed: [ec2-54-172-100-198.compute-1.amazonaws.com] => {"failed": true}
msg: Not implemented
failed: [ec2-54-173-252-72.compute-1.amazonaws.com] => {"failed": true}
msg: Not implemented

FATAL: all hosts have already failed -- aborting
```

Centos 7.2 ([ami-0f764765](https://www.bashton.com/blog/2016/update-centos-7-2-ami/)) on AWS (US-east)

Host file looks like:

```
[OSEv3:children]
masters
nodes

[masters]
ec2-54-172-100-198.compute-1.amazonaws.com openshift_node_labels="{'zone': 'us-east-1d'}" openshift_public_ip=54.172.100.198 openshift_public_hostname=ec2-54-172-100-198.compute-1.amazonaws.com

[nodes]
ec2-54-172-100-198.compute-1.amazonaws.com openshift_node_labels="{'zone': 'us-east-1d'}" openshift_public_ip=54.172.100.198 openshift_public_hostname=ec2-54-172-100-198.compute-1.amazonaws.com
ec2-54-174-40-221.compute-1.amazonaws.com openshift_node_labels="{'region': 'infra', 'zone': 'us-east-1d'}" openshift_public_ip=54.174.40.221 openshift_public_hostname=ec2-54-174-40-221.compute-1.amazonaws.com
ec2-54-174-6-95.compute-1.amazonaws.com openshift_node_labels="{'region': 'primary', 'zone': 'us-east-1d'}" openshift_public_ip=54.174.6.95 openshift_public_hostname=ec2-54-174-6-95.compute-1.amazonaws.com
ec2-54-173-252-72.compute-1.amazonaws.com openshift_node_labels="{'region': 'primary', 'zone': 'us-east-1d'}" openshift_public_ip=54.173.252.72 openshift_public_hostname=ec2-54-173-252-72.compute-1.amazonaws.com

[OSEv3:vars]
num_masters=1
num_nodes=2
num_infra=1
```

with host variables:

```
ansible_ssh_private_key_file: ...

# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user: ec2-user

# If ansible_ssh_user is not root, ansible_sudo must be set to true
ansible_sudo: true

deployment_type: origin
cluster_id: test-osev3
osm_default_subdomain: test-osev3
openshift_router_selector: region=infra
openshift_node_dnsmasq: false
```

I added `openshift_node_dnsmasq: false` to see if it would fix it but no luck...

**Comment by donovanmuller** [comment]
Coming from https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_node_dnsmasq/tasks/main.yml#L25.

Will investigate what [`systemctl show NetworkManager`](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_node_dnsmasq/tasks/main.yml#L4) gives us...

**Comment by detiber** [comment]
It looks like the variable to disable the behavior is documented wrong in the example inventory files. It should be `openshift_use_dnsmasq` instead of `openshift_node_dnsmasq`.

**Comment by donovanmuller** [comment]
@detiber Using `openshift_use_dnsmasq ` worked. Have submitted PR with renaming if that's all that needs to be changed.

**Comment by sdodson** [comment]
Thanks for the PR. I'd still like to actually fix this so that it works on Centos cloud images. Can you point me to where you got the centos cloud image, is it just the default Centos image in AWS?

**Comment by donovanmuller** [comment]
See above: "Centos 7.2 ([ami-0f764765](https://www.bashton.com/blog/2016/update-centos-7-2-ami/)) on AWS (US-east)"

**Comment by donovanmuller** [comment]
@sdodson Seems the rename also fixed the original `NetworkManager` issue. Just ran it again and went through successfully...
