### ISSUE TITLE
Tag v1.2.0 not found in repository docker.io/openshift/origin

### ISSUE THREAD

**Issue by jprovaznik** [openshift/openshift-ansible#1800]
openshift-ansible fails on centos atomic host (containerized deployment) when installing openshift origin. It seems that openshift_version/image_tag is evaluated to v1.2.0 but only v1.2.0-rc1 tag exists on docker.io.

TASK: [openshift_cli | Install clients] *************************************** 
skipping: [dns1-origin-master-0.example.com]

TASK: [openshift_cli | Pull CLI Image] **************************************** 
<dns1-origin-master-0.example.com> ESTABLISH CONNECTION FOR USER: centos
<dns1-origin-master-0.example.com> REMOTE_MODULE command docker pull openshift/origin:v1.2.0
<dns1-origin-master-0.example.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 dns1-origin-master-0.example.com /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1461584253.73-95265263053286 && echo $HOME/.ansible/tmp/ansible-tmp-1461584253.73-95265263053286'
<dns1-origin-master-0.example.com> PUT /tmp/tmpG25r2K TO /home/centos/.ansible/tmp/ansible-tmp-1461584253.73-95265263053286/command
<dns1-origin-master-0.example.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 dns1-origin-master-0.example.com /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=bsaysusaqtmcirmxftjtdagoifwxolpp] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-bsaysusaqtmcirmxftjtdagoifwxolpp; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/centos/.ansible/tmp/ansible-tmp-1461584253.73-95265263053286/command; rm -rf /home/centos/.ansible/tmp/ansible-tmp-1461584253.73-95265263053286/ >/dev/null 2>&1'"'"''
failed: [dns1-origin-master-0.example.com] => {"changed": true, "cmd": ["docker", "pull", "openshift/origin:v1.2.0"], "delta": "0:00:02.840508", "end": "2016-04-25 11:37:36.921582", "rc": 1, "start": "2016-04-25 11:37:34.081074", "warnings": []}
stderr: Tag v1.2.0 not found in repository docker.io/openshift/origin
stdout: Trying to pull repository docker.io/openshift/origin ... not found

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/main.retry

dns1-infra.example.com     : ok=14   changed=10   unreachable=0    failed=0   
dns1-origin-master-0.example.com : ok=291  changed=54   unreachable=0    failed=1   
dns1-origin-node-hzr604rn.example.com : ok=15   changed=1    unreachable=0    failed=0   
localhost                  : ok=20   changed=0    unreachable=0    failed=0

**Comment by sdodson** [comment]
We need to fix our image version introspection to handle the following output
```
oc v1.2.0-rc1-17-g642f0af
kubernetes v1.2.0-36-g4a3f9c5
```

**Comment by jprovaznik** [comment]
A workaround is set explicitly openshift_image_tag: v1.2.0-rc1

**Comment by syhrz** [comment]
hello, I'm still new with ansible, how to set the value btw? thx!

**Comment by detiber** [comment]
@syhrz in your inventory file, under [OSEv3:vars] you would put the following:
```
openshift_image_tag='v1.2.0-rc1'
```
