### ISSUE TITLE
openshift_node_dnsmasq not implemented 

### ISSUE THREAD

**Issue by elkouhen** [openshift/openshift-ansible#1807]
Hello 

I'am trying to install ansible on a CentOS 7.2.1511

Ansible fails with the following message (see below).

Is there a way to go through ?

Is there a branch more stable than master ?  

Thank you
Mehdi

TASK: [openshift_node_dnsmasq | Install dnsmasq configuration] ***************\* 
ok: [openshift-master.dynu.com]
ok: [openshift-node.dynu.com]

TASK: [openshift_node_dnsmasq | Install network manager dispatch script] *****\* 
skipping: [openshift-master.dynu.com]
skipping: [openshift-node.dynu.com]

**TASK: [openshift_node_dnsmasq | fail msg="Not implemented"] ******************\* 
**failed: [openshift-master.dynu.com] => {"failed": true}
msg: Not implemented
failed: [openshift-node.dynu.com] => {"failed": true}
msg: Not implemented**

FATAL: all hosts have already failed -- aborting

**Comment by sdodson** [comment]
For now you can set `openshift_use_dnsmasq=False` in your hosts file. We'll work on fixing this soon.

**Comment by donovanmuller** [comment]
@sdodson this happens because `NetworkManager` is not installed on Centos 7.2 by default.
I installed it manually just to test and after that the check passes.

If there's not more to this, would it just be a simple addition of installing `NetworkManager` to the task?

**Comment by sdodson** [comment]
@donovanmuller Yeah that's one way to fix it. I was very apprehensive about installing NetworkManager on a host that wasn't already using it. Do you see that as risky?

**Comment by detiber** [comment]
@sdodson I don't think we want to install NetworkManager for a user unless one of the following conditions are met:
- We bootstrapped the host (which we don't do yet in the productized installer)
- The user 'opts in' (probably through an Ansible variable)

**Comment by detiber** [comment]
Well, we could also do something crazy like this as well:
- if NetworkManager not present/enabled:
  - query configured interfaces
  - ensure NetworkManager installed
  - configure existing interfaces as unmanaged interfaces
- Ensure NetworkManager is running/enabled
- Disable and Mask network.service

**Comment by donovanmuller** [comment]
I'm +1 for opting in as a simple workaround until a more robust solution is decided.

**Comment by andrewklau** [comment]
Slightly related, when I had dnsmasq enabled at some point it ended up exceeding the query limit which ended up breaking a few things (including ability to re-running the install):

"Maximum number of concurrent DNS queries reached (max: 150)"

**Comment by sdodson** [comment]
@andrewklau Is your master setup HA? any chance that one of your api servers was down?

**Comment by andrewklau** [comment]
@sdodson yep native master HA, api service was down. I was re-running the install because of a syntax error in one of my config files which caused the service not to startup and the installer to fail. The second run hung forever due to the maximum DNS queries.

**Comment by imasen** [comment]
Pain.

**Comment by saurabhtandon13** [comment]
Hello All, 

I am also getting the same error, i have disabled the Network Manager on both master and node and then started the installation it failed with error "TASK: [openshift_node_dnsmasq | fail msg="Not implemented"] *****************" " 

As suggested above i have added " openshift_use_dnsmasq=False" in the host file path : ~/.config/openshift/hosts under 

[OSEv3:vars]
ansible_ssh_user=root
openshift_master_default_subdomain=cloudapps.redhat.com
deployment_type=openshift-enterprise
openshift_use_dnsmasq=False

Then i restarted the installation

*** Installation Summary ***

Hosts:
- osmaster.redhat.com
  - OpenShift Master
  - OpenShift Node (Unscheduled)
  - Etcd (Embedded)
- osnode.redhat.com
  - OpenShift Node (Dedicated)
  - Storage

Total OpenShift Masters: 1
Total OpenShift Nodes: 2

NOTE: Add a total of 3 or more Masters to perform an HA installation.

Gathering information from hosts...
Installed environment detected.
By default the installer only adds new nodes to an installed environment.
Do you want to (1) only add additional nodes or (2) reinstall the existing hosts potentially erasing any custom changes?: 2
osmaster.redhat.com is already an OpenShift Master
osnode.redhat.com is already an OpenShift Node

Wrote atomic-openshift-installer config: /root/.config/openshift/installer.cfg.yml
Wrote ansible inventory: /root/.config/openshift/hosts

Ready to run installation process.

If changes are needed please edit the config file above and re-run.

Are you ready to continue? [y/N]: y

the moment i select y i have noticed that the value disapper from the hosts file and installation failed again on the same stage. I would request to share the complete step to fix this issue.

**Comment by sdodson** [comment]
@saurabhtandon13 the quick installer does not support the full set of options yet and will overwrite items you've added to its generated inventory, soon you'll be able to specify arbitrary configuration values but that work is in progress see https://github.com/openshift/openshift-ansible/pull/1778. Right now NetworkManager is required if you want to use the dnsmasq functionality, which is the default, if possible I'd just install NetworkManager and enable NetworkManager on all hosts.

**Comment by saurabhtandon13** [comment]
Hello, 

Thanks for your prompt response. I have now enabled the NetworkManager on both master and the node and started the installation again. I am using an external DNS server during installation the DNS IP address in /etc/resolve.conf is changed to the IP address of the Virtual machine and then master is not able to communicate with the node and the installation is failed again. 

Can you please let me know the workaround for the same.

**Comment by jkaurredhat** [comment]
Yes, I  am too facing the same issue. Can anyone help.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
