### ISSUE TITLE
invalid line added to /etc/sysconfig/docker

### ISSUE THREAD

**Issue by ReSearchITEng** [openshift/openshift-ansible#1817]
While installing on RHEL7 (with ansible 1.9.4), the line below has been added to /etc/sysconfig/docker ; Aparently the ansible vars were not replaced.
Of course, docker daemon could not start till I disabled this line.

`#OPTIONS=' --insecure-registry={# hostvars[groups.oo_first_master.0].openshift.common.portal_net #} -l warn --ipv6=false'`

PS: I have cloned from github earlier today.

**Comment by detiber** [comment]
@ReSearchITEng can you provide more info about what your inventory looks like?

**Comment by ReSearchITEng** [comment]
grep -v "^#" /etc/ansible/hosts.used | sed '/^$/d'
[OSEv3:children]
masters
nodes
etcd
[OSEv3:vars]
ansible_ssh_user=root
debug_level=5
deployment_type=origin
use_cluster_metrics=true
openshift_docker_additional_registries=registry.access.redhat.com
openshift_docker_insecure_registries=registry.access.redhat.com
openshift_docker_options="-l warn --ipv6=false"
#openshift_master_identity_providers=...
osm_use_cockpit=true
osm_cockpit_plugins=['cockpit-kubernetes']
[masters]
x1
[etcd]
x1
[nodes]
x[2:3]
x4 openshift_node_labels="{'region': 'infra'}"

**Comment by detiber** [comment]
@abutcher related to the portal_net change, I believe.

**Comment by abutcher** [comment]
I think the problem is related to the reruns. I'm unable to reproduce with a similar inventory / host layout.

**Comment by sdodson** [comment]
@ReSearchITEng Does this still happen with current code base and Ansible 2.x?

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
