### ISSUE TITLE
Remove or document prod, stg, next branches

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#1821]
Origin users keep using them and reporting bugs that've been fixed in master for quite some time. We should either document or remove what those branches are used for. I'd lean towards removing them as I'm not sure how discoverable the documentation would be.

@twiest @detiber @abutcher thoughts?

**Comment by detiber** [comment]
@joelddiaz We discussed this the other day. Is there any need to keep around the old Ops branches, or can we safely nuke them?

**Comment by joelddiaz** [comment]
@detiber we weren't using them, so it's safe to nuke them (which I believe @twiest just did a few minutes ago)

**Comment by detiber** [comment]
@joelddiaz great, thanks for the followup.
