### ISSUE TITLE
What do you think about open Gitter room for Openshift Ansible ?

### ISSUE THREAD

**Issue by harobed** [openshift/openshift-ansible#1822]
What do you think about open Gitter room for Openshift Ansible ? https://gitter.im/

I think it's useful to contact contributors. It's better that irc, because it is simply to do relation between Github contributors and room users.

Best regards,
Stéphane

**Comment by detiber** [comment]
Considering there is an irc bridge for gitter: https://irc.gitter.im/ I wouldn't object to it.

@abutcher @sdodson thoughts?

**Comment by abutcher** [comment]
:+1: from me. I made a channel for the repository `#openshift/openshift-ansible`

**Comment by harobed** [comment]
Thanks.

Can you add Gitter badge in readme ?

```
[![Join the chat at https://gitter.im/openshift/openshift-ansible](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/openshift/openshift-ansible)
```

**Comment by harobed** [comment]
I think it can be useful to append this badge to increase the users number in Gitter room.
