### ISSUE TITLE
sudo: sorry, you must have a tty to run sudo

### ISSUE THREAD

**Issue by jprovaznik** [openshift/openshift-ansible#1825]
When deploying on openstack it fails with:
$ ./bin/cluster create -t origin openstack test1
... snip ...
PLAY [Gather facts] *********************************************************** 

GATHERING FACTS *************************************************************** 
failed: [ans1-master-0] => {"failed": true, "parsed": false}
... snip ...
sudo: sorry, you must have a tty to run sudo

Workaround is to disable requiretty in /etc/sudoers:
sed -i "/^Defaults.*requiretty/s/^/#/" /etc/sudoers

In openshift-on-openstack we disable it during cloud-init:
https://github.com/redhat-openstack/openshift-on-openstack/blob/master/fragments/lb-boot.sh#L51

**Comment by detiber** [comment]
@jprovaznik this should have already been the case: https://github.com/openshift/openshift-ansible/blob/master/playbooks/openstack/openshift-cluster/files/user-data

**Comment by jprovaznik** [comment]
@detiber thanks for pointing this out, I missed it. I checked user-data.txt passed to the dns node and this sudo config file is not included there, it looks like this:
[root@ans1-dns instance]# cat user-data.txt
Content-Type: multipart/mixed; boundary="===============6993002742202057530=="
MIME-Version: 1.0

--===============6993002742202057530==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

#cloud-config
disable_root: true

system_info:
  default_user:
    name: openshift
    sudo: ["ALL=(ALL) NOPASSWD: ALL"]

--===============6993002742202057530==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

#cloud-config
write_files:
  - path: /etc/sysconfig/network-scripts/ifcfg-eth0
    content: |
      DEVICE="eth0"
      BOOTPROTO="dhcp"
      DNS1="8.8.8.8"
      DNS2="8.8.4.4"
      PEERDNS="no"
      ONBOOT="yes"
runcmd:
  - [ "/usr/bin/systemctl", "restart", "network" ]

--===============6993002742202057530==--

I *think* the problem is in multiple usage of write_files directive (it's used in another part here - https://github.com/openshift/openshift-ansible/blob/master/playbooks/openstack/openshift-cluster/files/heat_stack.yaml#L599), though I'm not a cloud-init expert. Anyway the issue seems to be that this config file is actually not passed to the instance.

**Comment by detiber** [comment]
@jprovaznik Can you try with the latest updates I pushed to this PR: https://github.com/openshift/openshift-ansible/pull/1773
