### ISSUE TITLE
'dict object' has no attribute 'oo_nodes_to_config'

### ISSUE THREAD

**Issue by jprovaznik** [openshift/openshift-ansible#1826]
When deploying on openstack it fails with:
$ ./bin/cluster create -t origin openstack test1
... snip ...
TASK: [openshift_facts | Gather hostnames for proxy configuration] ************ 
fatal: [172.24.4.231] => One or more undefined variables: 'dict object' has no attribute 'oo_nodes_to_config'
fatal: [ans1-master-0] => One or more undefined variables: 'dict object' has no attribute 'oo_nodes_to_config'
fatal: [172.24.4.228] => One or more undefined variables: 'dict object' has no attribute 'oo_nodes_to_config'
fatal: [172.24.4.229] => One or more undefined variables: 'dict object' has no attribute 'oo_nodes_to_config'
fatal: [172.24.4.230] => One or more undefined variables: 'dict object' has no attribute 'oo_nodes_to_config'
fatal: [ans1-node-compute-0] => One or more undefined variables: 'dict object' has no attribute 'oo_nodes_to_config'
fatal: [ans1-node-infra-0] => One or more undefined variables: 'dict object' has no attribute 'oo_nodes_to_config'
fatal: [ans1-node-compute-1] => One or more undefined variables: 'dict object' has no attribute 'oo_nodes_to_config'

FATAL: all hosts have already failed -- aborting

**Comment by jannispl** [comment]
I'm currently experiencing the same issue.

**Comment by detiber** [comment]
This should be fixed in the latest update here: https://github.com/openshift/openshift-ansible/pull/1773

I don't currently have an OpenStack environment handy to test this on, so there may still be some outstanding issues.

**Comment by cben** [comment]
I encountered the same error with `bin/cluster create libvirt foo` and it worked cleanly with #1773.
:clap:

**Comment by jfmatth** [comment]
I'm trying to vagrant provision on Fedora 23 with libvirt, having exact problem.

**Comment by detiber** [comment]
@jfmatth there are quite a few issues with the Vagrantfile. I've created the following PR to address some of the issues: https://github.com/openshift/openshift-ansible/pull/1697

There are still some outstanding known issues, but please take a look and see if it gets you past the error you are seeing.

**Comment by jfmatth** [comment]
@detiber  Jason, thanks for commenting and updating.

I finally got the Vagrantfile to work after a little bit of work, it's the ansible stuff that falls over with the oo_nodes_to_config problem from this Issue.

I'll try your fix and let you know how well it works for me.

J

**Comment by privettoli** [comment]
@jfmatth, any news how to fix this problem?

**Comment by detiber** [comment]
@abutcher I think this is related to the Vagrantfile being out of date with the current groups. Not sure if we should go ahead and merge the pending Vagrantfile changes and continue to iterate on the issues afterwards instead of leaving this in the current state. Thoughts?

**Comment by abutcher** [comment]
@detiber Agreed, +1 on merging the the vagrantfile changes.

**Comment by jfmatth** [comment]
@privettoli Anthony, I haven't had any time to take a look at your fix.  Work has been quite busy.

I don't know if it's the Vagrantfile, since I finally got the VM's to provision.

I'll try to take a look soon.

**Comment by gordillo-ramon** [comment]
Same for aws.

**Comment by privettoli** [comment]
Fixed for me by adding such groups: "oo_nodes_to_config" and "oo_masters_to_config" to the inventory (or Vagrantfile ansible.group).

**Comment by jfmatth** [comment]
Can you be more specific for those of non-ansible people😀

**Comment by privettoli** [comment]
@jfmath, I duplicated the content of the inventory groups into "oo_" specific ones.
Inventory file:
[masters]
master

[nodes]
master
node[0:10]

# let's add the oo_ specific:
[oo_masters_to_config]
master

[oo_nodes_to_config]
master
node[0:10]

**Comment by jfmatth** [comment]
Great news, thank you, i'll give it a try soon.
