### ISSUE TITLE
secure registry considerations

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-ansible#1832]
There seems to be a default no possible way to not have the --insecure-registry line added. It appears to be hardcoded.

Also, what are thoughts on adding the ca.crt into the the root bundle: eg.
cp /etc/origin/node/ca.crt /etc/pki/ca-trust/source/anchors; update-ca-trust 

This could avoid having to worry about having to make changes to all nodes should the docker-registry be re-deployed etc. (ie. not worrying about /etc/docker/certs.d/docker-registry-ip:5000 )

The above is all assuming that people are using the default ca.crt for securing their registry..

**Comment by abutcher** [comment]
Hey @andrewklau you should be able to avoid the --insecure-registry option with this inventory variable.

```
openshift_docker_hosted_registry_insecure=false
```

> Also, what are thoughts on adding the ca.crt into the the root bundle: eg.
cp /etc/origin/node/ca.crt /etc/pki/ca-trust/source/anchors; update-ca-trust

I think this is something we'll want to do when we have options to secure registry. Although, when registry communication uses DNS that may simplify `/etc/docker/certs.d/dns-entry:5000`

**Comment by andrewklau** [comment]
My ansible foo isn't that great yet, but I was under the assumption it wasn't pulling anything from the inventory file? https://github.com/openshift/openshift-ansible/blob/4e01bd4a87088f53af309b36ce4da431888fcaf4/playbooks/common/openshift-node/config.yml#L121

I tried the above `openshift_docker_hosted_registry_insecure=false` and it didn't seem to work.

**Comment by abutcher** [comment]
@andrewklau You're right, that is hard coded :(
