### ISSUE TITLE
iptables proxier not writing iptables rules

### ISSUE THREAD

**Issue by metmajer** [openshift/openshift-ansible#1837]
I have recently deployed an OpenShift Origin cluster on AWS, however, I simply can't get my services to communicate with each others:

- I keep getting `UnknownHost` exceptions from my Java backend application
- `ping` and `telnet` give me `bad address`

A conversation in #openshift-dev on IRC with @deads2k revealed that the `proxier` component is prevented from making entries to `iptables`. In fact, after deploying the applications, `journalctl | grep proxier` shows:

```
origin-node[22943]:... proxier.go:421] Adding new service "easytravel/easytravel-mongodb:27017-tcp" at 172.30.108.189:27017/TCP
origin-node[22943]:... proxier.go:421] Adding new service "easytravel/easytravel-mongodb:28017-tcp" at 172.30.108.189:28017/TCP
origin-node[22943]:... proxier.go:421] Adding new service "easytravel/easytravel-backend:8080-tcp" at 172.30.186.73:8080/TCP
origin-node[22943]:... proxier.go:484] Setting endpoints for "easytravel/easytravel-mongodb:28017-tcp" to [10.1.2.2:28017]
origin-node[22943]:... proxier.go:484] Setting endpoints for "easytravel/easytravel-mongodb:27017-tcp" to [10.1.2.2:27017]
origin-node[22943]:... proxier.go:484] Setting endpoints for "easytravel/easytravel-backend:8080-tcp" to [10.1.0.3:8080]
```

Issuing a `sudo iptables -L` on the node that runs the `easytravel-backend` Docker container shows the following entries:

```
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
```

However, `KUBE_SERVICES` is empty (where it is supposed to contain an entry to the `easytravel-mongodb` service):

```
Chain KUBE-SERVICES (1 references)
target     prot opt source               destination
```

Here's a link to a complete `journalctl` dump from the origin node: [origin-node-journalctl.log](https://dl.dropboxusercontent.com/u/14609545/origin-node-journalctl.log). Beware, it's huge.

**Comment by deads2k** [comment]
Any chance your pod is failing its readiness or liveness check?  `oc status`, `oc get pods`, and `oc describe pods/<your-pod>`

**Comment by metmajer** [comment]
@deads2k seems like that's the case:

```
metmajer$ oc status -v
In project easytravel on server https://52.90.204.189:8443

svc/easytravel-backend - 172.30.212.212:8080
  dc/easytravel-backend deploys istag/easytravel-backend:openshift
    deployment #1 deployed about a minute ago - 1 pod

svc/easytravel-mongodb - 172.30.170.237 ports 27017, 28017
  dc/easytravel-mongodb deploys istag/easytravel-mongodb:openshift
    deployment #1 deployed about a minute ago - 1 pod

Warnings:
  * dc/easytravel-backend has no readiness probe to verify pods are ready to accept traffic or ensure deployment is successful.
    try: oc set probe dc/easytravel-backend --readiness ...
  * dc/easytravel-mongodb has no readiness probe to verify pods are ready to accept traffic or ensure deployment is successful.
    try: oc set probe dc/easytravel-mongodb --readiness ...

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
```

Here is how I deployed the applications:

```
oc new-app --docker-image dynatrace/easytravel-mongodb:openshift --docker-image dynatrace/easytravel-backend:openshift  --env "ET_DATABASE_LOCATION=easytravel-mongodb:27017"
```

`oc describe svc/easytravel-mongodb` gives:

```
Name:			easytravel-mongodb
Namespace:		easytravel
Labels:			app=easytravel-mongodb
Selector:		app=easytravel-mongodb,deploymentconfig=easytravel-mongodb
Type:			ClusterIP
IP:			172.30.170.237
Port:			27017-tcp	27017/TCP
Endpoints:		10.1.1.3:27017
Port:			28017-tcp	28017/TCP
Endpoints:		10.1.1.3:28017
Session Affinity:	None
No events.
```

`oc describe pods` gives:

```
NAME                         READY     STATUS    RESTARTS   AGE
easytravel-backend-1-rhjsz   1/1       Running   0          4m
easytravel-mongodb-1-74tj7   1/1       Running   0          4m
```

`oc describe pod easytravel-mongodb-1-74tj7` gives:

```
Name:		easytravel-mongodb-1-74tj7
Namespace:	easytravel
Node:		ip-172-31-28-88.ec2.internal/172.31.28.88
Start Time:	Thu, 28 Apr 2016 21:42:18 +0200
Labels:		app=easytravel-mongodb,deployment=easytravel-mongodb-1,deploymentconfig=easytravel-mongodb
Status:		Running
IP:		10.1.1.3
Controllers:	ReplicationController/easytravel-mongodb-1
Containers:
  easytravel-mongodb:
    Container ID:	docker://3e67d1dcc1c9bb787d1ada9b0e40af48d35100bf21483120fc28f7748b179d43
    Image:		dynatrace/easytravel-mongodb@sha256:0ec3e282d11a8c11615fa7a9e554a9890548bd89c47a95ced36dc70488a9fec7
    Image ID:		docker://617d9a34d1fcf76db8ba1e185df43e9d8f930a8e5ce6906cd23e56f3071f29e0
    Ports:		27017/TCP, 28017/TCP
    QoS Tier:
      cpu:		BestEffort
      memory:		BestEffort
    State:		Running
      Started:		Thu, 28 Apr 2016 21:42:21 +0200
    Ready:		True
    Restart Count:	0
    Environment Variables:
      ET_DATABASE_LOCATION:	easytravel-mongodb:27017
Conditions:
  Type		Status
  Ready 	True
Volumes:
  easytravel-mongodb-volume-1:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  default-token-8prhf:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-8prhf
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath				Type		Reason		Message
  ---------	--------	-----	----					-------------				--------	------		-------
  5m		5m		1	{default-scheduler }								Normal		Scheduled	Successfully assigned easytravel-mongodb-1-74tj7 to ip-172-31-28-88.ec2.internal
  5m		5m		1	{kubelet ip-172-31-28-88.ec2.internal}	spec.containers{easytravel-mongodb}	Normal		Pulled		Container image "dynatrace/easytravel-mongodb@sha256:0ec3e282d11a8c11615fa7a9e554a9890548bd89c47a95ced36dc70488a9fec7" already present on machine
  5m		5m		1	{kubelet ip-172-31-28-88.ec2.internal}	spec.containers{easytravel-mongodb}	Normal		Created		Created container with docker id 3e67d1dcc1c9
  5m		5m		1	{kubelet ip-172-31-28-88.ec2.internal}	spec.containers{easytravel-mongodb}	Normal		Started		Started container with docker id 3e67d1dcc1c9
```

**Comment by rhcarvalho** [comment]
@metmajer the `oc status` output indicate that you don't have any probes set up. They're not a requirement though.
You're instantiating your images through `oc new-app`, and it doesn't add probes for you.


If you do `oc rsh easytravel-mongodb-1-74tj7` (may need to update the name of the pod), can you connect to mongo using the hostname you pass to your app?

```console
$ oc rsh easytravel-mongodb-1-74tj7
sh-4.2$ mongo -u "$USER" -p "$PASSWORD" --host 'easytravel-mongodb:27017' 
```

Then we need to make sure that from the backend pod you can access your mongo (seems that not right now). @deads2k might have better hints to debug the networking issue.

**Comment by metmajer** [comment]
@rhcarvalho that didn't work:

```
metmajer$ oc rsh easytravel-mongodb-1-g21hd
/ $ mongo -u labuser -p --authenticationDatabase admin --host 'easytravel-mongod
b:27017' easyTravel-Business
MongoDB shell version: 3.2.4
Enter password:
connecting to: easytravel-mongodb:27017/easyTravel-Business
2016-04-29T12:01:30.533+0000 I NETWORK  [thread1] getaddrinfo("easytravel-mongodb") failed: Name does not resolve
2016-04-29T12:01:30.548+0000 E QUERY    [thread1] Error: couldn't initialize connection to host easytravel-mongodb, address is invalid :
connect@src/mongo/shell/mongo.js:226:14
@(connect):1:6

exception: connect failed
```

**Comment by metmajer** [comment]
Could that be due to a permission issue inside the container? Taking `ping` as an example here:

```
/ $ which ping
/bin/ping
/ $ ping
BusyBox v1.24.2 (2016-03-29 19:24:15 GMT) multi-call binary.

Usage: ping [OPTIONS] HOST

Send ICMP ECHO_REQUEST packets to network hosts

	-4,-6		Force IP or IPv6 name resolution
	-c CNT		Send only CNT pings
	-s SIZE		Send SIZE data bytes in packets (default:56)
	-t TTL		Set TTL
	-I IFACE/IP	Use interface or IP address as source
	-W SEC		Seconds to wait for the first response (default:10)
			(after all -c CNT packets are sent)
	-w SEC		Seconds until ping exits (default:infinite)
			(can exit earlier with -c CNT)
	-q		Quiet, only display output at start
			and when finished
	-p		Pattern to use for payload

/ $ ping orf.at
PING github.com (192.30.252.121): 56 data bytes
ping: permission denied (are you root?)
```

**Comment by rhcarvalho** [comment]
@metmajer this seems to be a limitation of your base image:

```console
$ docker run --rm -it --entrypoint sh mvertes/alpine-mongo 
/ # ping github.com
PING github.com (192.30.252.121): 56 data bytes
64 bytes from 192.30.252.121: seq=0 ttl=61 time=33.195 ms
64 bytes from 192.30.252.121: seq=1 ttl=61 time=102.774 ms
64 bytes from 192.30.252.121: seq=2 ttl=61 time=85.289 ms
^C
--- github.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 33.195/73.752/102.774 ms
$ docker run --rm -it --entrypoint sh --user nobody mvertes/alpine-mongo 
~ $ ping github.com
PING github.com (192.30.252.121): 56 data bytes
ping: permission denied (are you root?)
```

I found the image looking at https://github.com/Dynatrace/Dynatrace-easyTravel-Docker/blob/master/mongodb/Dockerfile.

**Comment by rhcarvalho** [comment]
@metmajer OpenShift by default will not run your image as root, but as a non-privileged user.

**Comment by metmajer** [comment]
@rhcarvalho I know. The Dockerfile you've linked to before is not the one I have used for the OpenShift deployments. Here's what it looks like:

```
FROM alpine:edge

MAINTAINER ...

ENV MONGODB_DB /data/db/easyTravel/
ENV MONGODB_USER mongodb

RUN echo http://dl-4.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories && \
    apk add --no-cache mongodb && \
    chown ${MONGODB_USER}:${MONGODB_USER} /usr/bin/mongo*

# Deploy easyTravel database
ADD build/easyTravel-mongodb-db.tar.gz ${MONGODB_DB}
RUN chown -R ${MONGODB_USER}:${MONGODB_USER} ${MONGODB_DB}

VOLUME ${MONGODB_DB}

EXPOSE 27017 28017

USER ${MONGODB_USER}

CMD mongod --auth --rest --httpinterface --smallfiles --dbpath ${MONGODB_DB}
```

As you see, I directly derived from `alpine:edge`. Any limitations known?

What about the missing entries in `iptables`. If they are set up correctly, then the failure might not be located inside the container.

**Comment by rhcarvalho** [comment]
Even with `centos` I cannot use `ping` as a non-root user... don't know why:

```console
$ docker run --rm -it --entrypoint sh --user nobody centos
sh-4.2$ ping github.com
ping: icmp open socket: Operation not permitted
```

But I can use `dig` to make DNS queries...

```console
$ oc rsh mongodb-1-1-7qrwa
sh-4.2$ dig mongodb-2 A +search

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> mongodb-2 A +search
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53102
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;mongodb-2.demo.svc.cluster.local. IN   A

;; ANSWER SECTION:
mongodb-2.demo.svc.cluster.local. 30 IN A       172.17.0.4

;; Query time: 6 msec
;; SERVER: 10.0.2.15#53(10.0.2.15)
;; WHEN: Fri Apr 29 13:06:11 UTC 2016
;; MSG SIZE  rcvd: 66
```

That pod is a deployment of our MongoDB example https://github.com/openshift/mongodb/tree/master/2.4/examples/replica

**Comment by rhcarvalho** [comment]
Here's what I get from iptables in my host:

```console
$ sudo iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */

Chain DOCKER (1 references)
target     prot opt source               destination         

Chain KUBE-SERVICES (1 references)
target     prot opt source               destination       
```

**Comment by metmajer** [comment]
I wonder if it's ok that your `KUBE_SERVICES` chain is empty. Is that because you're running only 1 service or are you probably facing the same issue? ;)

**Comment by metmajer** [comment]
I have just created a derived mongodb Docker image `FROM centos/mongodb-26-centos7`, which is offered by the OpenShift project: https://github.com/openshift/mongodb. Sadly, the same problem occurs here:

```
metmajer$ oc rsh easytravel-mongodb-1-mrkmu
sh-4.2$ mongo -u labuser -p --host easytravel-mongodb easyTravel-Business
MongoDB shell version: 2.6.9
Enter password:
connecting to: easytravel-mongodb:27017/easyTravel-Business
2016-04-29T15:01:44.827+0000 getaddrinfo("easytravel-mongodb") failed: Name or service not known
2016-04-29T15:01:44.828+0000 Error: couldn't connect to server easytravel-mongodb:27017 (0.0.0.0), address resolved to 0.0.0.0 at src/mongo/shell/mongo.js:148
exception: connect failed
```

**Comment by sdodson** [comment]
@metmajer what's the contents of /etc/resolv.conf in `easytravel-mongodb-1-mrkmu` ?

**Comment by metmajer** [comment]
Great question @sdodson. The following commands have been executed inside a `oc rsh easytravel-mongodb-1-22o7w`:

```
sh-4.2$ cat /etc/resolv.conf
search easytravel.svc.cluster.local svc.cluster.local cluster.local ec2.internal
nameserver 172.31.26.2
nameserver 172.31.0.2
options ndots:5
```

There's also a possibly not too relevant entry for the pod in `/etc/hosts`:

```
sh-4.2$ cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.1.2.2	easytravel-mongodb-1-22o7w
```

Here is what `dig` gives me for `easytravel-mongodb`:

```
sh-4.2$ dig easytravel-mongodb

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> easytravel-mongodb
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 9027
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;easytravel-mongodb.		IN	A

;; AUTHORITY SECTION:
.			44	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2016042900 1800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 172.31.0.2#53(172.31.0.2)
;; WHEN: Fri Apr 29 15:44:52 UTC 2016
;; MSG SIZE  rcvd: 122
```

**Comment by metmajer** [comment]
Btw, I have deployed the cluster using detiber's awesome [aws_cleanup](https://github.com/openshift/openshift-ansible/pull/1773) PR. This clean up allowed me to finally get up and running with OpenShift Origin on AWS. Maybe @detiber's got some idea here?

**Comment by sdodson** [comment]
Thanks. So, first in order to view the service iptables rules you need to look in the nat table. `iptables -L -t nat | grep easytravel` I imagine you'll see the service rules there, hopefully they're fine.

But it looks like your dns resolution is screwed up. What's `172.31.26.2`? is that the ip of the node in which the pod is running? And `172.31.0.2` is the node's default nameserver?

By default dig won't follow the search path and it also seems to randomly select one of the nameservers from the /etc/resolv.conf. So lets look at each nameserver defined. In the pod, can you try these two commands, `dig +search @172.31.26.2 easytravel-mongodb` and `dig +search @172.31.0.2 easytravel-mongodb`

I'm assuming that 172.31.26.2 is the ip address of the node where this pod lives, which means that this is an Origin 1.2 install which uses dnsmasq. Can you verify on that node that dnsmasq is running successfully? On that node can you run `dig @172.31.0.2 kubernetes.default.svc.cluster.local` and also `dig @172.30.0.1 kubernetes.default.svc.cluster.local` ? If the first command fails then dnsmasq is busted, if the second fails then service ips are busted.

**Comment by detiber** [comment]
@sdodson currently the dnsmasq config is disabled for AWS installs using bin/cluster, since NetworkManager is not present on those hosts.

**Comment by metmajer** [comment]
@sdodson I logged into the cluster node that runs the `easytravel-backend` and ran `sudo iptables -L -t nat | grep easytravel`:

```
KUBE-MARK-MASQ  all  --  ip-10-1-0-3.ec2.internal  anywhere             /* easytravel/easytravel-backend:8080-tcp */
DNAT       tcp  --  anywhere             anywhere                       /* easytravel/easytravel-backend:8080-tcp */ tcp to:10.1.0.3:8080
KUBE-MARK-MASQ  all  --  ip-10-1-2-2.ec2.internal  anywhere             /* easytravel/easytravel-mongodb:27017-tcp */
DNAT       tcp  --  anywhere             anywhere                       /* easytravel/easytravel-mongodb:27017-tcp */ tcp to:10.1.2.2:27017
KUBE-SVC-5XVK3QHFXHEGZYVA  tcp  --  anywhere             ip-172-30-17-239.ec2.internal   /* easytravel/easytravel-mongodb:27017-tcp cluster IP */ tcp dpt:27017
KUBE-SVC-HIA4DBXQI47V4QZD  tcp  --  anywhere             ip-172-30-147-162.ec2.internal  /* easytravel/easytravel-backend:8080-tcp cluster IP */ tcp dpt:webcache
KUBE-SEP-S4RCZ7J44UTAKF7C  all  --  anywhere             anywhere             /* easytravel/easytravel-mongodb:27017-tcp */
KUBE-SEP-BZHRXSIDJFAVXDFE  all  --  anywhere             anywhere             /* easytravel/easytravel-backend:8080-tcp */
```

I found out that `172.31.26.2` is the private IP of the node that runs the `easytravel-mongodb` pod. However, with only the following containers running on that machine and without `dnsmasq` present, I don't understand how DNS resolution should be working:

```
[centos@ip-172-31-26-2 ~]$ sudo docker ps
CONTAINER ID        IMAGE                                                                                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
87fa6bf8dda4        dynatrace/easytravel-mongodb@sha256:9434dc40d15d3cfd5f927e7b9f4196fda94f8e54d78766448b29d91ad3bd02ea   "container-entrypoint"   16 hours ago        Up 16 hours                             k8s_easytravel-mongodb.81468cfb_easytravel-mongodb-1-22o7w_easytravel_7f04a891-0e20-11e6-9086-0e0d956d50c1_3bd861d4
1e98fdb66a84        openshift/origin-pod:v1.2.0-rc1                                                                        "/pod"                   16 hours ago        Up 16 hours                             k8s_POD.d7fff26_easytravel-mongodb-1-22o7w_easytravel_7f04a891-0e20-11e6-9086-0e0d956d50c1_3853b338
```

I connected into the pod via `oc rsh easytravel-mongodb-1-22o7w` and ran the requested commands:

```
sh-4.2$ oc rsh easytravel-mongodb-1-22o7w^C
sh-4.2$ dig +search @172.31.26.2 easytravel-mongodb

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> +search @172.31.26.2 easytravel-mongodb
; (1 server found)
;; global options: +cmd
;; connection timed out; trying next origin

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> +search @172.31.26.2 easytravel-mongodb
; (1 server found)
;; global options: +cmd
;; connection timed out; trying next origin
...
```

```
sh-4.2$ dig +search @172.31.0.2 easytravel-mongodb

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> +search @172.31.0.2 easytravel-mongodb
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 45109
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;easytravel-mongodb.		IN	A

;; AUTHORITY SECTION:
.			52	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2016042900 1800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 172.31.0.2#53(172.31.0.2)
;; WHEN: Sat Apr 30 08:23:59 UTC 2016
;; MSG SIZE  rcvd: 122
```

Then, running `dig @172.30.0.1 kubernetes.default.svc.cluster.local` on a cluster node gives the following results:

```
[centos@ip-172-31-26-2 ~]$ dig @172.30.0.1 kubernetes.default.svc.cluster.local

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> @172.30.0.1 kubernetes.default.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by sdodson** [comment]
@detiber hmm, how is it disabled other than NetworkManager simply not being installed on the hosts? I'd have expected the install to fail all together if so.

@metmajer Ok, first, the last dig command shows us that dns requests via the kube svc ip are failing. Can you check that you can connect to your master on port 8053? `oc describe svc kubernetes` should show you the endpoints which should include your master ip addresses. Then can you try dns lookup via those endpoints `dig @master-ip -p 8053 kubernetes.default.svc.cluster.local` if that fails can you debug why you can't reach your masters on port 8053?

Once that's fixed, lets look into dnsmasq -- dnsmasq won't be running as a container but it should've been setup via a dispatcher script in /etc/NetworkManager/dispatcher.d/99-origin-dns.sh. You should see that /etc/resolv.conf has been updated to point to the node's local ip and that /etc/dnsmasq.d/ has configuration files that route requests for cluster.local to kubernetes service ip of 172.30.0.1 and other requests to this node's normal dns servers.

**Comment by metmajer** [comment]
@sdodson: `oc describe svc kubernetes` gives me:

```
metmajer:~$ oc describe svc kubernetes
Error from server: services "kubernetes" not found
```

An `oc describe svc`:

```
metmajer:~$ oc describe svc
Name:			easytravel-backend
Namespace:		easytravel
Labels:			app=easytravel-mongodb
Selector:		app=easytravel-mongodb,deploymentconfig=easytravel-backend
Type:			ClusterIP
IP:			172.30.147.162
Port:			8080-tcp	8080/TCP
Endpoints:		10.1.0.3:8080
Session Affinity:	None
No events.

Name:			easytravel-mongodb
Namespace:		easytravel
Labels:			app=easytravel-mongodb
Selector:		app=easytravel-mongodb,deploymentconfig=easytravel-mongodb
Type:			ClusterIP
IP:			172.30.17.239
Port:			27017-tcp	27017/TCP
Endpoints:		10.1.2.2:27017
Session Affinity:	None
No events.
```

Do I need to provided access to the `kubernetes` service to my `admin` user first? Since that service is not available, the following command is not expected to work anyway:

```
[centos@ip-172-31-26-1 ~]$ dig 54.173.122.81 -p 8053 kubernetes.default.svc.cluster.local

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> 54.173.122.81 -p 8053 kubernetes.default.svc.cluster.local
;; global options: +cmd
;; connection timed out; no servers could be reached
```

@sdodson: let me know if you want to take a look around the cluster yourself.

**Comment by sdodson** [comment]
You need to be an admin and you need to do it in the default namespace.
`oc describe -n default svc kubernetes`

You did @your-master-ip, right? dig needs the @ Also, try port 53 too just to see if it's been miscofnigured. If neither work then we need to debug why you can't access port 8053 on your master from your nodes.

**Comment by metmajer** [comment]
I am slightly confused by the user permissions system in OpenShift:

```
metmajer:~$ oc describe -n default svc kubernetes
Error from server: User "admin" cannot get services in project "default"
```

Seems like I have to add this capability first?

**Comment by metmajer** [comment]
```
[centos@ip-172-31-26-1 ~]$ dig @$MasterIP -p 8053 kubernetes.default.svc.cluster.local

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> @54.173.122.81 -p 8053 kubernetes.default.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

and

```
[centos@ip-172-31-26-1 ~]$ dig @54.173.122.81 -p 53 kubernetes.default.svc.cluster.local

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> @54.173.122.81 -p 53 kubernetes.default.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by sdodson** [comment]
You should be `system:admin`. The root user on your first master should have his ~/.kube/config file setup to login as `system:admin` try that user. If that fails copy /etc/origin/master/admin.kubeconfig back into ~/.kube/config and try again.

Ok, so you need to check iptables on the master or amazon security lists to see why you can't connect to your master's port 8053. Can you look into that? Ansible should open access via iptables but the amazon acls aren't handled automatically.

**Comment by metmajer** [comment]
Ok, here's what I did: `~/.kube/config` contains a user `system:admin`. I copied the value under `user.client-certificate-data` into `~/.ssh/openshift.crt` on my local machine and ran `oc login https://$MasterIP:8443 --certificate-authority=/Users/metmajer/.ssh/openshift.crt --username=system:admin`. No matter what I enter as passphrase I get:

```
Password:
error: username system:admin is invalid for basic auth
```

I am doing this for the first time. Is there anything I do wrong?

Should there be any particular processes or docker containers running on the master? I don't see any useful ones except for: `/usr/bin/openshift`. No docker containers are running.

**Comment by deads2k** [comment]
@liggitt https://github.com/openshift/origin/pull/8410 ?

**Comment by metmajer** [comment]
After adding  port 53 to the cluster's security group on AWS, I can now telnet to `$MasterIP:53` from my compute nodes. Will provide a PR for an updated [README_AWS.md](https://github.com/openshift/openshift-ansible/blob/master/README_AWS.md) if it turns out to be useful.

**Comment by metmajer** [comment]
Alright. I have followed some advice in https://github.com/openshift/origin/issues/5259 and copied the config from the master's `.kube/config` to my local host. I then logged in via `oc login https://$MasterIP:8443 -u system:admin --config=./config`. This gives me:

```
metmajer$ oc login https://$MasterIP:8443 -u system:admin --config=./config
You have access to the following projects and can switch between them with 'oc project <projectname>':

  * default (current)
  * easytravel
  * management-infra
  * openshift
  * openshift-infra

Using project "default".
```

However, looking up service `kubernetes` gives:

```
metmajer$ oc describe svc kubernetes
Error from server: services "kubernetes" not found
```

**Comment by sdodson** [comment]
The master should create that service when it starts, restart it by running `systemctl restart origin-master` and check again, if it's still not there review master logs for problems. You can view the logs by running `journalctl -lu origin-master`.

**Comment by metmajer** [comment]
See some interesting logs here: https://gist.github.com/metmajer/f14a08fbfa65df1b5b468de560b6dba6#file-origin-master.

`controller.go:262] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[]} [{[{172.31.29.181 <nil>}] [] [{https 8443 TCP} {dns 53 UDP} {dns-tcp 53 TCP}]}]}` is probably worth an investigation.

**Comment by metmajer** [comment]
After a restart of the origin master, the kubernetes service is still not coming up. Here's the output of `journalctl` after the restart: https://gist.github.com/metmajer/f14a08fbfa65df1b5b468de560b6dba6#file-origin-master-restart-log.

**Comment by sdodson** [comment]
So, when you logged in you passed `--config=./config`. If you want to use the same kubeconfig in the future you'll need to also add `--config=./config` because the default would be ~/.kube/config And just to make sure you're in the right namespace I'd run `oc describe svc kubernetes --config=./config -n default`

**Comment by metmajer** [comment]
Got it. I had assumed `--config` would be a one-shot configuration when logging in.

```
metmajer$ oc describe svc kubernetes --config=./config -n default
Name:			kubernetes
Namespace:		default
Labels:			component=apiserver,provider=kubernetes
Selector:		<none>
Type:			ClusterIP
IP:			172.30.0.1
Port:			https	443/TCP
Endpoints:		172.31.29.181:8443
Port:			dns	53/UDP
Endpoints:		172.31.29.181:53
Port:			dns-tcp	53/TCP
Endpoints:		172.31.29.181:53
Session Affinity:	None
No events.
```

Yay! We are getting somewhere.

**Comment by metmajer** [comment]
Sadly,...

```
metmajer$ oc project
Using project "default" on server "https://$MasterIP:8443".
```

```
metmajer$ oc describe svc
Name:			easytravel-mongodb
Namespace:		default
Labels:			app=easytravel-mongodb
Selector:		app=easytravel-mongodb,deploymentconfig=easytravel-mongodb
Type:			ClusterIP
IP:			172.30.89.63
Port:			27017-tcp	27017/TCP
Endpoints:		10.1.2.2:27017
Port:			28017-tcp	28017/TCP
Endpoints:		10.1.2.2:28017
Session Affinity:	None
No events.
```

Name:			kubernetes
Namespace:		default
Labels:			component=apiserver,provider=kubernetes
Selector:		<none>
Type:			ClusterIP
IP:			172.30.0.1
Port:			https	443/TCP
Endpoints:		172.31.29.181:8443
Port:			dns	53/UDP
Endpoints:		172.31.29.181:53
Port:			dns-tcp	53/TCP
Endpoints:		172.31.29.181:53
Session Affinity:	None
No events.

Name:			router
Namespace:		default
Labels:			router=router
Selector:		router=router
Type:			ClusterIP
IP:			172.30.83.60
Port:			80-tcp	80/TCP
Endpoints:		172.31.19.59:80
Port:			443-tcp	443/TCP
Endpoints:		172.31.19.59:443
Port:			1936-tcp	1936/TCP
Endpoints:		172.31.19.59:1936
Session Affinity:	None
No events.
```

```
metmajer$ oc get pods
NAME                         READY     STATUS    RESTARTS   AGE
easytravel-mongodb-1-ahnix   1/1       Running   0          3m
router-1-b54p5               1/1       Running   0          3d
```

```
metmajer$ oc get pods
NAME                         READY     STATUS    RESTARTS   AGE
easytravel-mongodb-1-ahnix   1/1       Running   0          3m
router-1-b54p5               1/1       Running   0          3d
```

```
metmajer$ oc rsh easytravel-mongodb-1-ahnix
/ $ telnet easytravel-mongodb 27017
telnet: bad address 'easytravel-mongodb'
```

**Comment by metmajer** [comment]
I'll have to change my Docker image to add `dig`. Will provide additional insights soon.

In the meantime: how can I enable a user to use the `kubernetes` service in custom projects through the web ui? Thanks.

**Comment by sdodson** [comment]
Ok, I think what you're hitting now is that I've improperly set dnsIP address to the node's ip address even if you've requested that dnsmasq not be used. Your node's /etc/resolv.conf doesn't indicate that dnsmasq is in use. I've opened #1852 to address this configuration problem.

You can run this to clean it up then you'll need to delete your pods, they should be re-recreated with proper configuration.
`sed -i '/dnsIP.*$/d' /etc/origin/node/node-config.yaml && systemctl restart origin-node`

**Comment by metmajer** [comment]
@sdodson: did a quick verification of what you have proposed. I applied the expression to all nodes except the master. Then re-created the applications under a new user in the `default` project and made sure that the `kubernetes` and `router` services are available. I then logged into the pod via `oc rsh` and tried a `telnet` - to no avail:

```
/ $ telnet easytravel-mongodb 27017
telnet: bad address 'easytravel-mongodb'
```

**Comment by sdodson** [comment]
@metmajer The pod you've connected to is in the same namespace as your mongodb service? That's the only way I'd expect that to work.

**Comment by metmajer** [comment]
Sure. The pod I had connected to is the pod that runs mongodb.

**Comment by sdodson** [comment]
What's your new pod's /etc/resolv.conf look like now?

**Comment by metmajer** [comment]
```
/ $ cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local ec2.internal
nameserver 172.30.0.1
nameserver 172.31.0.2
options ndots:5
```

Wait a minute. Has anything changed at all?

**Comment by metmajer** [comment]
@sdodson and @detiber: have you tested this PR works before you closed? I have applied the patches from https://github.com/openshift/openshift-ansible/pull/1852 to detiber's `aws_cleanup` branch and re-created the cluster. I have pushed the application `easytravel-mongodb` into the `default` project via:

```
oc new-app --docker-image dynatrace/easytravel-mongodb:openshift
```

and still get:

```
/ $ telnet easytravel-mongodb 27017
telnet: bad address 'easytravel-mongodb'
```
