### ISSUE TITLE
Parameterize some defaults for Logging to prevent cluster collaps 

### ISSUE THREAD

**Issue by jayunit100** [openshift/openshift-ansible#1887]
Lets see if we can prevent https://github.com/openshift/origin/issues/8868 at the installer level, at least temporarily if not permanantly.

TL;DR :We don't want `docker logs` from noisy containers to fill up the disks and kill your cluster!

**Comment by jayunit100** [comment]
cc @timothysc @rrati

**Comment by sdodson** [comment]
What logging options are you suggesting to resolve this?

**Comment by timothysc** [comment]
We need to configure defaults for docker to log using journald + and set sane roll-over defaults.  

Right now the defaults OOTB will explode a reasonable sized cluster.

**Comment by timothysc** [comment]
I think setting docker to log to the journal and configure the journals defaults.  

We have yet to determine what are sane defaults on the journald for densely packed nodes.

**Comment by sdodson** [comment]
Can you drive coordinating with cluster infra and containers teams on what the best defaults should be? We're happy to implement whatever the decision is but I don't think that's something that our team should decide.

CC: @ncdc @jwhonce @mfojtik @cgwalters

**Comment by ncdc** [comment]
Isn't the default already the journald log driver?

**Comment by timothysc** [comment]
@ncdc no.

**Comment by ncdc** [comment]
@timothysc ??? isn't the RHEL/Docker default journald?

**Comment by ncdc** [comment]
Nevermind, I see that's just in Fedora.
