### ISSUE TITLE
Allow specify an IP address for DNSmasq

### ISSUE THREAD

**Issue by chmouel** [openshift/openshift-ansible#1889]
Currently  when configuring DNSmasq it would configure the resolv.conf to the public interface (and due of to the public IP)

https://github.com/openshift/openshift-ansible/blob/4620c60/roles/openshift_node_dnsmasq/files/networkmanager/99-origin-dns.sh#L33-L36

My public IP is closed for 53 and I assume for most people doing this in production they would want this to be close.

It would be nice if we can configure this IP so we could specify the internal interface instead

**Comment by sdodson** [comment]
It doesn't need to be accessible from outside of the host. What problems are you seeing?

**Comment by chmouel** [comment]
it gets the public IP on my server : 

![2016-05-13__17-01-24-11433](https://cloud.githubusercontent.com/assets/98980/15252016/5a9a496c-192c-11e6-8e56-fa12efc152e9.png)

(when I really want my local link 10.231.129.213 in there instead)

**Comment by sdodson** [comment]
Sorry, can you post `ip addr show` to help explain? Why do you want 10.231.129.213 in particular? What problems are created by using 46.231.129.213?

**Comment by chmouel** [comment]
cause my firewall block 53 on that public  IP, my full ip addr => http://sprunge.us/KOPd

**Comment by knobunc** [comment]
Can you get the tar from the debug.sh referenced at https://docs.openshift.com/enterprise/3.1/admin_guide/sdn_troubleshooting.html#further-help

That would help track down your problem...

**Comment by sdodson** [comment]
> cause my firewall block 53 on that public IP, my full ip addr => http://sprunge.us/KOPd

that should work unless you've added specific iptables rules prohibiting that, have you done that? the debug output will help us get a better view of the overall network configuration too.

**Comment by chmouel** [comment]
I think you right, well my issue was more had to do with : 

https://github.com/openshift/openshift-ansible/pull/1875

I was using the ansible from the shipped rpm, 

testing from master works for me, 

since I have some static IP on this server this probably came from this bug, I had the hint from a message you (scott) posted on one mailing list

I guess this can be closed,

sorry for the noise,

**Comment by sdodson** [comment]
No problem, thanks for letting us know the resolution.
