### ISSUE TITLE
We need to ensure that the "latest" dir in https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples is up to date

### ISSUE THREAD

**Issue by mwoodson** [openshift/openshift-ansible#1895]
We noticed that the "latest" symlink located here:

https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples

Is not up to date.  It points to 1.1.  1.2 is the newest version.  IS there a way we can ensure that the latest symlink is kept up to date when new versions are installed?

**Comment by detiber** [comment]
@sdodson is there a reason we can't drop the latest symlink and just use the version facts? Maybe break out for Origin/Enterprise versioning and symlink between the versioning there instead?

Having a latest symlink seems error prone considering latest for Origin could be different than Enterprise, etc.

**Comment by sdodson** [comment]
@mwoodson Where are you running into it, just in the RPM that installs it, right? I'm not finding anywhere in the playbooks that actually use it.

@detiber I think it was added as a way to let the docs reference one path and not have it change. I agree it's problematic.
