### ISSUE TITLE
etcd_image hardcoded to registry.access.redhat.com

### ISSUE THREAD

**Issue by maci0** [openshift/openshift-ansible#1915]
in

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_facts/library/openshift_facts.py

`etcd_image = 'registry.access.redhat.com/rhel7/etcd'`

many enterprise customers have a local copy of these images, the fact should be 
`etcd_image = 'rhel7/etcd'`
instead

**Comment by detiber** [comment]
@sdodson any issues you see with this?

**Comment by sdodson** [comment]
No, I think it's fine.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.

**Comment by maci0** [comment]
This issue is still present.

**Comment by codrinbucur** [comment]
I am running into this as well. Any reason to keep it hardcoded?
