### ISSUE TITLE
AWS create cluster fail: 'dict object' has no attribute 'ec2_tag_sub-host-type'

### ISSUE THREAD

**Issue by gordillo-ramon** [openshift/openshift-ansible#1933]
Hi.

When running a fresh installation with 

bin/cluster create aws dev

It stops at:

TASK: [openshift_facts ] ****************************************************** 
fatal: [dev-node-compute-e97ed] => One or more undefined variables: 'dict object' has no attribute 'ec2_tag_sub-host-type'
fatal: [dev-node-compute-38774] => One or more undefined variables: 'dict object' has no attribute 'ec2_tag_sub-host-type'
fatal: [dev-node-infra-d4f02] => One or more undefined variables: 'dict object' has no attribute 'ec2_tag_sub-host-type'

I have checked and instances has sub-host-type tag.

Any clue?

**Comment by abutcher** [comment]
Hey @gordillo-ramon, I think this PR adds the sub-host-type tag but it also has some other cloud playbook fixes. Could you give it a try? https://github.com/openshift/openshift-ansible/pull/1773

**Comment by gordillo-ramon** [comment]
Yes, it works.

Do you know when will it be merged to master?
