### ISSUE TITLE
identiy_provider in openshift ansible github master not working for me

### ISSUE THREAD

**Issue by LutzLange** [openshift/openshift-ansible#1944]
I do struggle with the latest master of openshift-ansible it fails for me and I have trouble identifying why.

ASK: [openshift_master | set_fact ] ******************************************  
fatal: [tmaster] => Failed to template {{ openshift.master.identity_providers | translate_idps('v1', openshift.common.version, openshift.common.deployment_type) }}: an unexpected type error occurred. Error was t
ranslate_idps() takes exactly 2 arguments (4 given) 

My inventory has :
[OSEv3:vars] 
ose_version=3.2 
ansible_ssh_user=llange 
deployment_type=openshift-enterprise
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/htpasswd'}]

**Comment by abutcher** [comment]
Hey @LutzLange, do you have the openshift-ansible rpms installed? If installed you'll need to modify your ansible config or set some environment variables so that plugins within /usr/share/ansible don't take precedence over your openshift-ansible checkout.

```
[defaults]
lookup_plugins     = ~/openshift-ansible/lookup_plugins
filter_plugins     = ~/openshift-ansible/filter_plugins
```

```
 ANSIBLE_LOOKUP_PLUGINS=~/openshift-ansible/lookup_plugins
 ANSIBLE_FILTER_PLUGINS=~/openshift-ansible/filter_plugins
```

**Comment by LutzLange** [comment]
Well spotted ;-).

I ended up removing the openshift-ansible rpm. That got rid of the error.

**Comment by abutcher** [comment]
Good deal, closing this out :)
