### ISSUE TITLE
How to prevent OpenShift to overwrite Docker options ?

### ISSUE THREAD

**Issue by Lunik** [openshift/openshift-ansible#1951]
I setup multiples otions into /etc/sysconfig. But after running openshift deployment playbooks, everithing is overwrited.
It append into "docker: Set various docker options"
I may have forget something ?

**Comment by detiber** [comment]
@Lunik This is intended behavior, we need to make changes to the docker sysconfig file for installing OpenShift.

If you set `openshift_docker_options` in your hosts file, it will append those items to the resulting config.

See https://github.com/openshift/openshift-ansible/blob/02a4d70c55ba89bde345d82e0731c70626209ee0/inventory/byo/hosts.origin.example#L76 for an example.

**Comment by Lunik** [comment]
Thanks ! That was helpfull 👍

**Comment by Lunik** [comment]
I just noticed that in the [Documentation](https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-host-variables) some variables are missing
