### ISSUE TITLE
master_cert_config_dir unset

### ISSUE THREAD

**Issue by ibotty** [openshift/openshift-ansible#1961]
Running the byo/config playbook on a previously provisioned cluster, I get the following error.

```
TASK: [Clear named certificates] ********************************************** 
fatal: [A_MASTER] => One or more undefined variables: 'master_cert_config_dir' is undefined
```

The change was introduced in 
```
commit c9cd222f8eab56a31c6ff237739653672c7010af
Author: Andrew Butcher <abutcher@redhat.com>
Date:   Tue May 17 10:24:41 2016 -0400

    Consolidate ca/master/node certificates roles into openshift_certificates.
```

Setting the variables somewhere on these hosts, fixes that error:

```
  - set_fact:
      master_cert_config_dir: "{{ openshift.common.config_base }}/master"
    when: master_cert_config_dir is not defined
```

I guess the correct fix is using `openshift.master.cert_config_dir` instead and setting the var in the `openshift_master_vars` role.

Should I send a pull request to do that?

**Comment by abutcher** [comment]
@ibotty I'm going to be backing the changes out -- there are a bunch of other issues.
