### ISSUE TITLE
DNS config into hosts file ? 

### ISSUE THREAD

**Issue by Lunik** [openshift/openshift-ansible#1967]
I want to configure the skyDNS directly with the [hosts file](https://github.com/openshift/openshift-ansible/blob/02a4d70c55ba89bde345d82e0731c70626209ee0/inventory/byo/hosts.origin.example). I can't see where I should do it.
Or should I set it directly from the `master-config.yml` ?

**Comment by sdodson** [comment]
@Lunik Can you elaborate on what sort of configuration you'd like to do?

**Comment by Lunik** [comment]
Change the binding port ?

**Comment by sdodson** [comment]
You can already do that by setting `openshift_master_dns_port`

**Comment by Lunik** [comment]
All right ! I haven't noticed that hosts variables where linked like that to templates variables !

Thanks !
