### ISSUE TITLE
Libvirt provider - harcoded or not defined values in playbooks

### ISSUE THREAD

**Issue by dumdan** [openshift/openshift-ansible#1970]
## Hardcoded values

I am trying to show the "diffs", as much as possible:

In `playbooks/libvirt/openshift-cluster/tasks/launch_instances.yml` - lines 86 & 94 - hardcoded **"openshift-ansible"**

```
index 7231f25..833586f 100644
--- a/playbooks/libvirt/openshift-cluster/tasks/launch_instances.yml
+++ b/playbooks/libvirt/openshift-cluster/tasks/launch_instances.yml
@@ -83,7 +83,7 @@
   with_items: instances

- name: Wait for the VMs to get an IP

-  shell: 'virsh -c {{ libvirt_uri }} net-dhcp-leases openshift-ansible | egrep -c ''{{ instances | join("|") }}'''
+  shell: 'virsh -c {{ libvirt_uri }} net-dhcp-leases {{ libvirt_network }} | egrep -c ''{{ instances | join("|") }}'''
   register: nb_allocated_ips
   until: nb_allocated_ips.stdout == '{{ instances | length }}'
   retries: 60
@@ -91,7 +91,7 @@
   when: instances | length != 0

 - name: Collect IP addresses of the VMs
-  shell: 'virsh -c {{ libvirt_uri }} net-dhcp-leases openshift-ansible | awk ''$6 == "{{ item }}" {gsub(/\/.*/, "", $5); print $5}'''
+  shell: 'virsh -c {{ libvirt_uri }} net-dhcp-leases {{ libvirt_network }} | awk ''$6 == "{{ item }}" {gsub(/\/.*/, "", $5); print $5}'''
   register: scratch_ip
   with_items: instances
```
## Undefined variables/facts

Since the the VMs provisioned for this provider (libvirt) have only one network interface (eth0), the "fact" "ansible_default_ipv4" is an empty dict(), so it has no "address" component. I **suggest** using the first element of **"ansible_all_ipv4_addresses"** in the module `"roles/openshift_facts/library/openshift_facts.py"`

```
--- a/roles/openshift_facts/library/openshift_facts.py
+++ b/roles/openshift_facts/library/openshift_facts.py
@@ -1654,7 +1654,7 @@ class OpenShiftFacts(object):
                 dict: The generated default facts
         """
         defaults = {}
-        ip_addr = self.system_facts['default_ipv4']['address']
+        ip_addr = self.system_facts['all_ipv4_addresses'][0]
         exit_code, output, _ = module.run_command(['hostname', '-f'])
         hostname_f = output.strip() if exit_code == 0 else ''
         hostname_values = [hostname_f, self.system_facts['nodename'],
```

**Comment by detiber** [comment]
@dumdan Thanks again for the feedback. The libvirt_network issue is definitely a bug in the installer, thanks for highlighting that. Would it be possible for you to submit a PR for this?

For the issue with default_ipv4, I would expect that to still be defined even if there is only a single interface. The only time I would expect the value to be undefined is if the host was lacking a default route entry. I'm wondering if this is impacted by the type of network when using a pre-existing network.

**Comment by dumdan** [comment]
Done - submitted pull request for "https://github.com/openshift/openshift-ansible.git"
For the "default_ipv4" I will check some more. I do run many network instances and my attempts were focused on non-default networks.

**Comment by michaelgugino** [comment]
The affected code path has been removed.

Closing this issue as it is no longer valid.
