### ISSUE TITLE
rhel_subsciption playbook is failing due to "error while evaluating conditional: deployment_type"

### ISSUE THREAD

**Issue by alongoldboim** [openshift/openshift-ansible#1972]
@sdodson @detiber @simon3z 

--------------------------------------------------------------------------------
**inventory:**
[OSEv3:children]
masters
nodes
 
[OSEv3:vars]
ansible_ssh_user=root
deployment_type=openshift-enterprise
rhsub_user=*****
rhsub_pass=*****
rhsub_pool=*****
 
[masters]
 
[nodes]
10.35.48.24
 
--------------------------------------------------------------------------------
 
**result:**
fatal: [localhost] => error while evaluating conditional: deployment_type in ['atomic-enterprise', 'enterprise', 'openshift-enterprise'] and ansible_distribution == "RedHat" and lookup('oo_option', 'rhel_skip_subscription') | default(rhsub_skip, True) | default('no', True) | lower in ['no', 'false']
 
 
PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/rhel_subscribe.retry
 
10.35.48.24                : ok=28   changed=2    unreachable=0    failed=0  
localhost                  : ok=5    changed=0    unreachable=1    failed=0  
 
 
--------------------------------------------------------------------------------
 
**command:**
ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/rhel_subscribe.yml -i /usr/share/ansible/openshift-ansible/rhel_subscribe_inventory.yaml
 
--------------------------------------------------------------------------------
 
**tested against:**
master.

I don't think it should run on localhost as well.

**Comment by detiber** [comment]
In playbooks/byo/rhel_subscribe.yml we are applying the rhel_subscribe role to the 'all' group, which will include 'localhost', instead we should be using the 'l_oo_all_hosts' group we are creating previously (or possibly even just getting rid of creating the 'l_oo_all_hosts' group and using the 'OSEv3' group, since it is a byo specific playbook).

**Comment by sdodson** [comment]
@alongoldboim I've built openshift-ansible-3.0.96-1 for you in the same internal repo you got 3.0.95 from, can you try this version?

**Comment by alongoldboim** [comment]
@sdodson I don't think ill get to it today, ill try getting to it tomorrow.
