### ISSUE TITLE
Containerized Flag Causes Breakage on Load Balancer System in HAProxy Deployments

### ISSUE THREAD

**Issue by dgoodwin** [openshift/openshift-ansible#1980]
If you set containerized=true in your inventory vars (for all systems, which is something I've seen QE doing), or directly on the load balancer, the installer fails with an error about missing an haproxy config file. The LB cannot be containerized as I understand it, so we should likely error out if the user has set this var for that system, or ignore it.

**Comment by detiber** [comment]
On Jun 3, 2016 7:57 AM, "Devan Goodwin" <notifications@github.com> wrote:
>
> If you set containerized=true in your inventory vars (for all systems,
which is something I've seen QE doing), or directly on the load balancer,
the installer fails with an error about missing an haproxy config file. The
LB cannot be containerized as I understand it, so we should likely error
out if the user has set this var for that system, or ignore it.

I want to say there was a contribution for containerized haproxy (iirc it
built the image that it deploys).

**Comment by abutcher** [comment]
> I want to say there was a contribution for containerized haproxy (iirc it
built the image that it deploys).

I remember something like this -- if there isn't we should at least provide a more helpful error if the loadbalancer has containerized=true.

**Comment by jhcook** [comment]
Hi there. Is there any progress on this; because, I've set containerised and run into this problem on release-1.3 and master branches.

**Comment by dgoodwin** [comment]
No change in current situation afaik, still not a supported option and you would need to work around by setting containerized=false on the load balancer host.

The topic of supporting containerized lb did some up recently in backlog grooming but I don't think it was anything on immediate horizon, let me know if I'm wrong on that guys.

**Comment by sdodson** [comment]
@dgoodwin You're correct, no immediate plans to support containerized lb hosts. The lb role is really a placeholder for more complete load balancer solution whether that's IaaS offerings like an ELB or on prem options like an F5 or other infrastructure managed outside of your OpenShift installation.

**Comment by detiber** [comment]
@sdodson @dgoodwin might be a good idea to have this fail gracefully/quickly.

**Comment by jhcook** [comment]
@dgoodwin thank you for the suggestion. It now works as expected. I've deployed an HA configuration with lb:vars containerized=false and everyone is smiling.

@detiber you are correct. It would be better to fail fast and loud in this situation. 

It would be great if the documentation were updated.

**Comment by dgoodwin** [comment]
I will modify this to error out if the lb sees containerized=true.

**Comment by dgoodwin** [comment]
This logically seems like it should happen in the openshift_loadbalancer role, but that would not be erroring out quickly. However you could just fix and re-run to correct the problem.

We don't have a good cross-playbook location for pre-flight checks right now do we?

We could alternatively ignore containerized for the load balancer, but then we'd need a similar check to make sure you didn't just try to install it on Atomic and we're back to needing a location for that.

I'm going to lean towards just erroring out in the role and the user can re-run if they hit this, it's not early but it's better than the situation now.

**Comment by jhcook** [comment]
@dgoodwin I think it's good enough in the docs to say lb ignores containerized since it's not available in a container.
