### ISSUE TITLE
option openshift_additional_repos doesn't work

### ISSUE THREAD

**Issue by tj13** [openshift/openshift-ansible#1987]
i pulled the latest code. 

changed option openshift_additional_repos as below:
openshift_additional_repos=[{'id': 'origin', 'name': 'origin', 'baseurl': 'http://172.0.0.214:8083/elrepo-kernel/maxamillion-origin-next/', 'enabled': 1, 'gpgcheck': 1, gpgkey: 'https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/pubkey.gpg'}]

ran command: 
$ ansible-playbook -i sit /home/tanjun/openshift-ansible/playbooks/byo/config.yml 

failed message as below:

TASK [openshift_repos : Create any additional repos that are defined] **********
fatal: [centosdev01.sit.caijj.net]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'unicode object' has no attribute 'id'"}

**Comment by abutcher** [comment]
Adding quotes to the `gpgkey` key should fix.

```
openshift_additional_repos=[{'id': 'origin', 'name': 'origin', 'baseurl': 'http://172.0.0.214:8083/elrepo-kernel/maxamillion-origin-next/', 'enabled': 1, 'gpgcheck': 1, 'gpgkey': 'https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/pubkey.gpg'}]
```
