### ISSUE TITLE
Define openshift_node_kubelet_args multiple times

### ISSUE THREAD

**Issue by gr3x** [openshift/openshift-ansible#1993]
Hello,
I don't know if it is possible but in our infrastructure we have multiple kind of nodes. Our nodes are not all the same and we want to define different kubelet arguments for each one. 
The problem is that when we define the openshift_node_kubelet_args inside our ansible config this parameter affects all our nodes and not only a part of the nodes.
We already try to override this parameter by specifying directly the parameter for each node but it's not working.
Is there a way to do something we want or definetely not ?
Best regards,

**Comment by detiber** [comment]
@gr3x you will want to modify your host inventory and create sub groups for the nodes, and specify the vars on those groups..  something like this:
```
[nodes:children]
node_group_a
node_group_b

[node_group_a:vars]
openshift_node_kubelet_args: <kubelet args for node_group_a>

[node_group_a]
node1
node2
node3

[node_group_b:vars]
openshift_node_kubelet_args: <kubelet args for node_group_b>

[node_group_b]
node4
node5
node6
```

**Comment by gr3x** [comment]
@detiber it works like a charm ! Thank you a lot, also now instead of a lot of duplicated lines we have now a more simply ansible file.
