### ISSUE TITLE
AWS Instances incorrectly determine IP addresses if configured with a PROXY

### ISSUE THREAD

**Issue by edseymour** [openshift/openshift-ansible#1998]
If the AWS instance is configured to connect via a proxy using HTTP_PROXY HTTPS_PROXY, then the private (and public) IP addresses can be incorrectly determined, particularly if the proxy server is also an AWS instance (they will be determined as the respective IPs of the proxy server). 

The AWS method uses the AWS API to determine the IPs (and other metadata). The workaround is to ensure that the APIs IP address is added to the NO_PROXY configuration,

NO_PROXY=169.254.169.254,...

If this is done, then the metadata is correctly calculated for the instance.

**Comment by sdodson** [comment]
> The workaround is to ensure that the APIs IP address is added to the NO_PROXY configuration,

When you say this you mean the cloud provider's API IP, right? Does that API have a hostname that's standardized or it varies on instance creation?

**Comment by edseymour** [comment]
@sdodson yes, in the example above that's the AWS IP that's hardcoded into the ansible playbook - if you add that to NO_PROXY it works around this issue. AWS doesn't use a hostname because it may not be resolvable by your DNS (I assume) - they use a fixed IP.

**Comment by sdodson** [comment]
@edseymour Thanks, and you fix this you're adding the API IP to NO_PROXY of which service? I assume the node because the kubelet needs to talk to the API? We're actually not specifying HTTP/HTTPS/NO_PROXY in the node service because we came to the conclusion that it would almost never require a proxy.

**Comment by edseymour** [comment]
@sdodson - the problem occurs during installation; as you're running Ansible. 

I configured the host systems with HTTP_PROXY, HTTPS_PROXY, and NO_PROXY configurations. I had to configure sudo on all hosts to preserve the proxy envs. 

I didn't investigate configuring Ansible proxy configuration, so it's possible there are ways to set the proxy through that route.

**Comment by detiber** [comment]
@sdodson @edseymour this seems to only cover a subset of AWS deployments (namely single master instances, since that is the only time the master IP would be contacted directly).

@edseymour Are you deploying in a VPC that does not have the ec2 provided dns enabled? We should probably discourage deployments like this, since they will not work with the native cloud provider integration.

**Comment by edseymour** [comment]
@detiber I disagree - I encountered this issue in a HA deployment, 3 masters, four nodes. The result is a failed etcd deployment as the etcd cert picks up this invalid IP for its alt address. Etcd then fails to start as it has an invalid cert. 

Yes, we are not using the AWS DNS, but that is how a lot of customers I've worked with seem to operate, using their own corporate DNS in place of the AWS DNS within their VPC.

**Comment by detiber** [comment]
@edseymour Are they implementing their own persistent storage then?

My concern is breaking the existing use-cases. If there is a way we can add support for this use case without breaking those, I have no issues.

**Comment by edseymour** [comment]
@detiber ignore DNS, this is an issue that affects an AWS installation using an Internet proxy to access Internet resources. The "bug" is that the Ansible playbook gathers Instance metadata from the AWS API, which is a hardcoded IP (169.254.169.254). If the target hosts don't have this IP address in the NO_PROXY list (i.e. bypass the proxy for this IP) the AWS API returns the metadata of the proxy server, rather than the Instance running (this assumes the proxy server is also an Instance on AWS). 

One effect of this is that the alt-address in the etcd certificates gets configured to the IP address of the proxy instance, rather than the IP of the ectd instance. This results in etcd failing to start due to a bad certificate. 

I'm not sure a fix is needed as such, but some docs around the use of proxy configuration during the install would probably suffice. 

The issue certainly affects AWS, it may also affect GCP and other cloud platforms. GCP metadata can be found at metadata.google.internal, for example.

**Comment by edseymour** [comment]
FYI - the AWS API is used in the normalize_aws_facts method of  roles/openshift_facts/library/openshift_facts.py 

See also http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

**Comment by detiber** [comment]
@edseymour ah, now I'm on the same page. I do agree that we should have the appropriate cloud metadata provider ips/urls added.
