### ISSUE TITLE
Provision elastic IP in AWS to avoid ip reconfiguring in cluster

### ISSUE THREAD

**Issue by gordillo-ramon** [openshift/openshift-ansible#1999]
It is needed prior to generate all the CAs, to set up elastic (static) ip, and assign them to the nodes.

**Comment by detiber** [comment]
@gordillo-ramon we don't currently have a "supported" method of provisioning cloud instances. The current bin/cluster scripts are community supported and I wouldn't consider them production ready by any means. The elastic IP in this case would be expected to be assigned to the host prior to running the playbooks.

One thing to keep in mind is that it is possible to configure the ec2 instances in a VPC with a pre-configured internal IP and ELBs can be used for the external access, which would prevent any issues arising from changes to external IPs for the host.

That said, there is work being done on reference architectures for cloud platforms that will include some level of infrastructure automation.

**Comment by gordillo-ramon** [comment]
@detiber, if we create the elastic IP, there is any way to assign them to the hosts in the playbooks? It is because the playbooks are provisioning the hosts too (including the storage), so IMHO, it should be easier to add the tasks for IP provisioning too in each cloud.

I understand this is a community supported feature, I am just trying to help to this community with my personal experience. I am trying to understand deeper the ansible configuration to contribute with code too.

Thx.

**Comment by detiber** [comment]
@gordillo-ramon It is definitely something that could be done in the provisioning playbooks. If you are interested in attempting to implement it, I would suggest taking a look at the Ansible ec2_eni module: http://docs.ansible.com/ansible/ec2_eni_module.html

**Comment by michaelgugino** [comment]
The affected code path has been removed.

Closing this issue as it is no longer valid.
