### ISSUE TITLE
How can we set up metric, cockpit, logging, etc, on AWS once cluster ir created?

### ISSUE THREAD

**Issue by gordillo-ramon** [openshift/openshift-ansible#2000]
I have seen the byo inventory setup, but nothing similar on AWS.

Thanks.

**Comment by abutcher** [comment]
Hey @gordillo-ramon, you could re-run ansible with a static inventory containing your AWS hosts/vars or create a setup similar to [demo-ansible](https://github.com/2015-Middleware-Keynote/demo-ansible), where a [dynamic inventory](http://docs.ansible.com/ansible/intro_dynamic_inventory.html) ([inventory](https://github.com/2015-Middleware-Keynote/demo-ansible/tree/master/inventory/aws/hosts), [group_setup](https://github.com/2015-Middleware-Keynote/demo-ansible/blob/master/playbooks/group_setup.yml)) is used and the [BYO playbook is called with relevant cluster variables set](https://github.com/2015-Middleware-Keynote/demo-ansible/blob/36ee909bf392ca5bd40e93c303e42afd8223f3bf/playbooks/openshift_setup.yml#L77-L120).

**Comment by mazzy89** [comment]
@abutcher I'd like to install only openshift logging. Could I run only openshift-logging playbook or should I run `byo/openshift-cluster/config.yaml`?

**Comment by abutcher** [comment]
`playbooks/byo/openshift-cluster/openshift-logging.yml` can be used to deploy logging on an existing cluster.

**Comment by michaelgugino** [comment]
The affected code path has been removed.  Additionally, information on how to deploy these services using existing plays has been provided.

Closing this issue as it is no longer valid.
