### ISSUE TITLE
Upgrade playbook should upgrade metrics as well

### ISSUE THREAD

**Issue by ibotty** [openshift/openshift-ansible#2006]
AFAICT, it only needs to add ",MODE=refresh" to the oc process call in the openshift_metrics role.

Should I prepare a pr that adds a mode to openshift_metrics that does that?

**Comment by detiber** [comment]
@ibotty I am currently in the process of reworking some of the post-config steps, including metrics/logging. That said, it is still going to be a bit before it's ready.

I generally don't like the idea of having a flag to a role that would trigger this type of behavior, it really seems like an anti-pattern. Instead I feel that we should detect when to run with each mode in some manner, even if that is specifying a version of metrics to run to the role.

@dgoodwin @abutcher thoughts?

**Comment by abutcher** [comment]
@detiber I'm not a fan of modes either but the method lends itself to how we've been doing upgrades so far; taking hand editing into account and only updating what we need to via the upgrade playbooks.

I'm not sure what the best route would be. Would it be crazy to update the role and do a `lineinfile` in the upgrade playbooks to match?

**Comment by detiber** [comment]
@abutcher long term, I want the roles to be valid for ongoing CM. Managing their components in a declarative and idempotent fashion.

While we don't really want the "installer" to upgrade things outside of the upgrade workflow, I think that logic all belongs in the playbooks.

For the standalone use case, I think having the role track what version of openshift is installed on the master would probably make the most sense (since we are matching tags/versions here) and if the desired version is not the running version then we would trigger a refresh (or the proper workflow for handling the upgrade).

**Comment by dgoodwin** [comment]
Personally I do not see a big problem with a role that by default just makes sure metrics is there and running, but has a flag that can be set to cause it to refresh and upgrade. We've talked about "orchestrators" in the form of the playbooks and an upgrade playbook doing that doesn't catch me as wrong just yet, but I'm still learning what we aim to avoid and why.

The role automatically realizing the tag mismatch on the metrics containers would be nice, provided we're sure it's safe to initiate that upgrade automatically for all users even just in a config playbook maintenance run. I'm not so sure that's the case but  I'll ping mwringe to get a peek at latest upgrade docs.

**Comment by dgoodwin** [comment]
Ping @mwringe re ^^

**Comment by detiber** [comment]
@dgoodwin If restricting the thought of the roles being something that are run in a controlled manner without being independently consumable, then I would agree.

I'm trying to put myself in the role of an end user that:
- Is idiomatic Ansible and follows upstream conventions (the declarative and idempotent part)
- Wants to consume our roles within their own Ansible-based configuration management tooling

Obviously we wouldn't fully support that use case, but having that level of sophistication in the role means that the external orchestrator is much more straightforward (just ensuring the proper version variables are set).

**Comment by ibotty** [comment]
Re using the roles as is: That's problematic in an upgrade playbook. We ran into the upgrade playbook restarting docker on all nodes at the exact same time. So all the careful serial upgrade logic did not get run because of a "restart docker" trigger.

In a way, that's a failure of ansible, that you can't notify and then do the notify action serially, but it makes that kind of painful.

**Comment by detiber** [comment]
@ibotty it definitely wouldn't be the method we recommend for most users, it would be a choose your own adventure with CM type of thing. 

We haven't dug in too deeply yet, but I think with ansible 2.0 or 2.1 they introduce the ability to run a task or a block serially.

**Comment by dgoodwin** [comment]
@detiber I'm still a bit confused about how flags like that violate those principles but I'll ping you about that someday. 

With the upcoming release/version variable changes being done for upgrade it might make it a little easier to assume a version is set in the roles and take action.

Also it looks like it is as simple as @ibotty mentioned: https://docs.openshift.org/latest/install_config/upgrading/manual_upgrades.html#manual-upgrading-cluster-metrics

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
