### ISSUE TITLE
Any primer on deploying/managing Origin over ManageIQ ?

### ISSUE THREAD

**Issue by andriyfomenko** [openshift/openshift-ansible#2014]
Hi,

We are using Origin over fixed set of CentOS 7 hosts: so far it has been working beautifully for application development environment when deployed with Ansible.

As I'm starting to experiment with Origin deployment into AWS EC2, it looks like ManageIQ is "just what a doctor prescribed" to manage cluster (especially on scale-in/out), but I can not really find a one concise walkthrough on how everything is supposed to fit together, or at least a primer on where to start research. 

README_AWS.md seems to describe how to perform a static cluster deployment into AWS, but I do not see how ManageIQ fits into the overall picture, although "manageiq" is mentioned here and there in this project configuration files.

Am I missing something obvious?
Can you please point me in the right direction?

Thank you in advance,

Andriy F.

**Comment by detiber** [comment]
@andriyfomenko apologies for this slipping through the cracks...  The current integration points for manageiq within openshift-ansible are related to configuring the service accounts needed for ManageIQ to interact with OpenShift. 

For managing OpenShift using ManageIQ, I would have to defer to the upstream ManageIQ community.
