### ISSUE TITLE
Upgrade doc about branch/tags to use

### ISSUE THREAD

**Issue by talset** [openshift/openshift-ansible#2015]
The documentation for the setup and upgrade should be updated in order to specify which tags or branch should be used.
in the upgrade doc [1] it is not specified.

  [1] https://docs.openshift.com/enterprise/3.2/install_config/upgrading/automated_upgrades.html#running-the-upgrade-playbook-directly

For example :
 My customer is in 3.1.1.6 and want to upgrade to 3.2.
 If we use the master branch the docker_upgrade.yml require docker 1.10. If we use branch enterprise-3.2 same issue.
 If we use tag openshift-ansible-3.2.0-1 we have docker 1.9. And we also have tag v3.0.2-1.

Same question for a setup.

Thanks

**Comment by talset** [comment]
Maybe I should open this issue in the openshift-docs repo but it could be nice to have your inputs

**Comment by sdodson** [comment]
@talset Thanks, we should document that here too, however I don't believe any of the enterprise docs for 3.1 or 3.2 instruct users to clone this repo as they should be using the installer that's shipped in the OSE channels instead. Those are the only QE'd and supported versions.

**Comment by talset** [comment]
Yes you right for the OSE part it is not supported
