### ISSUE TITLE
docker version 1.10 or greater not recognized during ansible installation

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/openshift-ansible#2016]
Installation of OpenShift origin: ansible stops:
```
TASK [docker : Fail if Docker upgrade is required] *****************************
fatal: [nsxx.ipxxx]: FAILED! => {"changed": false, "failed": true, "msg": "Docker  must be upgraded to Docker 1.10 or greater"}
```

## additional information:
```
docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

Also tried to change my `/etc/ansible/hosts` file and add
`docker_version=1.11.2`

**Comment by dgoodwin** [comment]
What OS was this on and where did the Docker version come from?

Your version should be ok but I suspect something is going wrong with checking what version of Docker is available and defaulting to 0.0.

The check is done with:

# Going forward we require Docker 1.10 or greater. If the user has a lesser version installed they must run a separate upgrade process.
- name: Get current installed Docker version                                                                                           
  command: "{{ repoquery_cmd }} --installed --qf '%{version}' docker"                                                                  
  when:  not openshift.common.is_atomic | bool                                                                                         
  register: curr_docker_version                                                                                                        
  changed_when: false    

I'm guessing your docker is not installed via rpm?

**Comment by dgoodwin** [comment]
Ok so I'm guessing you have docker-engine rpm installed, not "docker", and the command repoquery --installed -qf '%{version}' docker is returning nothing.

When you say Docker 1.9 is too low, did you mean for the openshift-ansible requirements? The Docker 1.10 requirement is very recent in master and has not been shipped anywhere yet, it is expected to go out when Docker 1.10 is available.

I suggest switching to the enterprise-3.2 branch in git and installing from there. This will only require Docker 1.9.x and you should be able to install fine on CentOS 7.2.

A standalone Docker 1.10 playbook will be available for any Origin 1.2 / OSE 3.2 environments to upgrade to Docker 1.10 as this will very soon be required even to use the Docker registry.

**Comment by lorenzvth7** [comment]
@dgoodwin  I'm not using enterprise but Origin. So I'm probably not able to use OSE3.2 stuff?

**Comment by dgoodwin** [comment]
Apologies I am mistaken, enterprise-3.2 branch also has the Docker 1.10 changes right now. 

you can instead use the last tagged release prior to this: "git checkout openshift-ansible-3.0.97-1".

We will discuss if there's anything we can do to loosen the requirements on Docker versions.

**Comment by dgoodwin** [comment]
@lorenzvth7 the enterprise-3.2 branch is valid for origin too, no changes to the code it's just the naming we're using.

**Comment by bigz94** [comment]
The documentation should also be updated then, it says exclusivly docker v1.9.x ;)

**Comment by dgoodwin** [comment]
Yeah it's all in the works, 1.10 has not been shipped to CentOS or RHEL yet, nor has the code in openshift-ansible you're attempting to run. However it does raise the question of where can an origin user get the installer from right now, I'm trying to find a better answer than the git tag option above but I'm not sure there is one.

We're also discussing if we should be less picky/brittle about the Docker version.

**Comment by lorenzvth7** [comment]
@dgoodwin 
Now I got:
```
TASK [docker : Set various docker options] *************************************
fatal: [ns390175.ip-188-165-242.eu]: FAILED! => {"failed": true, "msg": "The conditional check 'docker_check.stat.isreg' failed. The error was: error while evaluating conditional (docker_check.stat.isreg): 'dict object' has no attribute 'isreg'\n\nThe error appears to have been in '/root/openshift-ansible/roles/docker/tasks/main.yml': line 89, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set various docker options\n  ^ here\n"}
```
I checked out openshift-ansible-3.0.97-1 and I installed docker 1.9.1 (`yum install docker`). Than I executed my ansible playbook and it went further than before but stopped here. After the fail I checked my docker version which was changed in 1.11 (after running the playbook)

**Comment by bigz94** [comment]
Its just annoying that docker had to change there naming -> docker / docker-engine. Is there no simple workaround to install direktly from the docker page? Using docker-engine?

**Comment by lorenzvth7** [comment]
Workaround (git checkout openshift-ansible-3.0.97-1) worked + using `yum install docker` (1.9.1).

**Comment by bigz94** [comment]
Ps. Did an issue exactly like this one #2019 will close it, but you will find some tries to work around the problem.

**Comment by dgoodwin** [comment]
Just a couple notes from reading the other issue, the requirement for Docker 1.10 is out of our hands and was done by Docker themselves, they're about to or already have pushed changes to their registry which will break older clients pulling newer built images (IIRC). This is why the changes just went into master to require this, but we're discussing now if there's a smoother option in the interim.

@lorenzvth7 glad to hear the git tag worked!

**Comment by donnydavis** [comment]
Same issue here.

**Comment by donnydavis** [comment]
A better way to check for version would be something like this 
docker version |grep Version: | awk 'FNR == 2 {print $2}'
gives the output of docker version no matter how it is installed

**Comment by donnydavis** [comment]
Looks like docker 1.10 finally hit the repos 
Installing : docker-1.10.3-44.el7.centos.x86_64

I am running through install with enterprise-3.2 branch now, and will update if it works

**Comment by donnydavis** [comment]
This issue should be closed. Docker 1.10 is available in the centos repos, and the enterprise-3.2 playbook installs without issue now.

**Comment by lvthillo** [comment]
@donnydavis version is up to date. But still have this issue :( openshift/ansible#9396
