### ISSUE TITLE
[Upgrade] Make unschedulable fail on mixed platform (atomic/rhel)

### ISSUE THREAD

**Issue by talset** [openshift/openshift-ansible#2017]
Because of some issue on atomic in order to mount EBS we are using atomic on master and rhel on nodes. It work perfectly except a little issue during the upgrade :

```
failed: [proxy01.......com -> master01.......com] => {"cmd": "oadm manage-node ip-10-......eu-west-1.compute.internal --schedulable=false", "failed": true, "rc": 2
```

The issue is here :

```
- name: Prepare for Node evacuation                                                                                                                                                                   
  command: >
    {{ openshift.common.admin_binary }} manage-node {{ openshift.common.hostname | lower }} --schedulable=false
  delegate_to: "{{ groups.oo_first_master.0 }}"
```

openshift.common.admin_binary is evaluate from rhel node and try to execute remotely on master1 (atomic host).

On rhel

```
client_binary='oc', admin_binary='oadm'
```

On atomic

```
    if safe_get_bool(facts['common']['is_containerized']):
        facts['common']['admin_binary'] = '/usr/local/bin/oadm'                                                                                                                                       
        facts['common']['client_binary'] = '/usr/local/bin/oc'
```

Do you have an idea how to fix that in ansible ?

**Comment by sdodson** [comment]
What's your inventory look like? For your master have you set containerized=False ?

That aside, I feel like reviving this PR to address this https://github.com/openshift/openshift-ansible/pull/1099

**Comment by talset** [comment]
It is a classical inventory file with 3 masters and 3 nodes.
I don't set containerized, it use this fact :
```
    facts['common']['is_atomic'] = os.path.isfile('/run/ostree-booted')
    if 'is_containerized' not in facts['common']:
        facts['common']['is_containerized'] = facts['common']['is_atomic']
```

It work when the upgrade is perform on a master (2 & 3), the local fact is_atomic=True and it delegate to master01 (on atomic also)
But for my 3 nodes, the local fast is automatically set to is_containerized=False and it delegate the command to master01 on atomic.

Here is the issue, the command delegate is genereted on the rhel node and executed on atomic host.
