### ISSUE TITLE
The latest version installed origin - 1.2. Failure

### ISSUE THREAD

**Issue by lifei825** [openshift/openshift-ansible#2027]
The deployment of an error after update git:
failed: [10.1.130.31] => {"changed": false, "failed": true, "rc": 0, "results": []}
## msg: No Package matching 'origin-1.2.0' found available, installed or updated

Run manually add the old yum source, also delete the old，why？

**Comment by sdodson** [comment]
@tdawson Do we have time to get origin 1.2.0 built in Centos PaaS SIG repos?

**Comment by tdawson** [comment]
Already built, and tested, working on getting it into the released repo
https://bugs.centos.org/view.php?id=11017

In CentOS testing repo already:
http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin/

**Comment by lifei825** [comment]
yum -y install --enablerepo=centos-openshift-origin-testing origin-1.2.0, is ok
cat /etc/yum.repos.d/CentOS-OpenShift-Origin.repo
[centos-openshift-origin-testing]
name=CentOS OpenShift Origin Testing
baseurl=http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin/
enabled=0

**Comment by tdawson** [comment]
origin-1.2.0 is now in the CentOS PaaS SIG repo.
Please try again.

**Comment by lifei825** [comment]
yes,thanks !

**Comment by michaelgugino** [comment]
This issue appears to have been solved.

Closing this issue.
