### ISSUE TITLE
 origin on centos 7.1

### ISSUE THREAD

**Issue by priyanka5** [openshift/openshift-ansible#2029]
Hi , I am installing origin on centos 7.1, it already has docker-engine 11 version installed.

Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

error it gives is : {"changed": false, "failed": true, "msg": "Docker  must be upgraded to Docker 1.10 or greater"} 

I have already seen similar issues https://github.com/openshift/openshift-ansible/issues/2019 , which says it should be docker instead of doker-engine. Why is it so? can I remove docker-engine and install docker to make it work, if yes how?

Thanks!

**Comment by bigz94** [comment]
Its  aproblem with the naming, checkout issue #2016. I Think they are working on the issue.

To uninstall docker follow: https://docs.docker.com/engine/installation/linux/ubuntulinux/#uninstallation
then just use the workaround given in the issue:
```git checkout openshift-ansible-3.0.97-1``` and ```yum install docker``` (for 1.9.1).

Havent tried it yet, but seems to work.

**Comment by priyanka5** [comment]
@bigz94 : thanks for replying but "yum install docker" doesnt work . it takes yum install docker-engine

**Comment by bigz94** [comment]
@priyanka5 whats the output of following: ```yum list docker``` or ```repoquery -i docker``` 
There seems to be a problem with the repository.

**Comment by priyanka5** [comment]
I installed docker 1.9.1. the output is:

Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Installed Packages
docker.x86_64                                                                           1.9.1-25.1.origin.el7.centos                                                                           installed


but now i am getting error:

TASK [docker : Fail if Docker upgrade is required] *****************************
fatal: []: FAILED! => {"changed": false, "failed": true, "msg": "Docker 1.9.1 must be upgraded to Docker 1.10 or greater"}

**Comment by bigz94** [comment]
you have to checkout the right version of this repository:
```git checkout openshift-ansible-3.0.97-1```

**Comment by priyanka5** [comment]
have tried this, but new error:

[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{g_all_hosts}}').
This feature will be removed in a
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name bool
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

Ansible version: ansible 2.1.0.0

any help?

**Comment by bigz94** [comment]
it seems as if they changed it now back again:
https://github.com/openshift/openshift-ansible/pull/2021#issuecomment-225576066
maybe you can jump back again to the master branch.
I am not sure from where this error comes from. Maybe restart from a clean cenots installation? If that is possible.

**Comment by sdodson** [comment]
The packaging from dockerproject.org is not compatible with the Origin RPMs because it doesn't `Provides: docker`. So we'd need to refactor both the RPM and major parts of the ansible code here to accomodate using packages from dockerproject.org.

**Comment by priyanka5** [comment]
@sdodson : thanks so will it work with "docker-engine" rpm ? I guess no :(

**Comment by sdodson** [comment]
@priyanka5 No, it won't work with that package right now unless it's started adding a `Provides: docker` recently. I haven't looked in the past month.

**Comment by detiber** [comment]
@sdodson I'm not sure it would be such a major refactor...  We *could* check for the existence of the docker binary in the path and then query the binary for the version number. @dgoodwin, thoughts?

**Comment by abutcher** [comment]
Checking for and using the binary was also suggested in https://github.com/openshift/openshift-ansible/issues/2016

**Comment by sdodson** [comment]
We'd have to fix the RPM packaging of origin though and I don't know how to do that in a way that will continue to allow us to say docker >= 1.8.2.

**Comment by detiber** [comment]
@sdodson we could potentially remove the Requires in the origin packaging.

**Comment by sdodson** [comment]
I'm discussing that with Lokesh to find out what sort of problems may arise from that.

My opinion though is that we don't have the capacity to test that so I'd prefer being able to assume centos/fedora/rhel packaging. Will we then be on the hook to deal with Origin 1.2 and docker-1.12 as soon as dockerproject.org ships it?

**Comment by dgoodwin** [comment]
I'm not opposed to checking the docker binary version as that's a pretty simple way to work past this, however we absolutely should not commit to "supporting" this path given our conversations last week. We were at 90 supported install combos at least at the start of last week, we don't need to be taking on more paths to install this thing. 

If folks want to contribute small patches to make it work with docker-engine that seems fine to me, but just not something we should commit to keeping working, I would propose that it has to be community based.

**Comment by priyanka5** [comment]
@sdodson : now it has started giving strange error "No Package matching 'origin' found available, installed or updated", "rc": 0, "results": []" , have you ever seen this?

**Comment by priyanka5** [comment]
why ansible is not taking care of downloading package. I have installed origin last time too but seeing these issues recently only.

**Comment by yazGo** [comment]
This issue is also in the enterprise-3.2 installation on rhel7.2, I am using the branch enterprise-3.2 of openshift-ansible
git branch
* enterprise-3.2
  master

Having the same error
TASK: [docker | Fail if Docker upgrade is required] *************************** 
failed: [m1-32.xxxxxx.com] => {"failed": true}
msg: Docker 1.9.1 must be upgraded to Docker 1.10 or greater

FATAL: all hosts have already failed -- aborting

**Comment by dgoodwin** [comment]
The change to relax requirement on Docker 1.10 until more widely available was just merged to master branch this morning. enterprise-3.2 is not expected to pick this up as we expect that to ship with Docker 1.10. 

I'd try master right now.

**Comment by yazGo** [comment]
hello, what do you mean by " as we expect that to ship with Docker 1.10" ? We are using rhel7.2 and the available docker version in the repos are Docker version 1.9.1

**Comment by dgoodwin** [comment]
I believe Docker 1.10 is coming with next RHEL 7 release, and our enterprise-3.2 branch is expected to arrive after that is available.

**Comment by bigz94** [comment]
The current master branch worked now for centos 7.2 after remving docker 10.x+ test-task

**Comment by DanyC97** [comment]
cc @vrutkovs candidate for closing as being stale issue

**Comment by vrutkovs** [comment]
Recent versions of Origin require Docker 1.12 / 1.13
