### ISSUE TITLE
Won't take osm_image overwrite

### ISSUE THREAD

**Issue by benashton2** [openshift/openshift-ansible#2030]
I got containerised installation working with satellite last week using the below in the hosts file:

[OSEv3:vars]
osm_image= {{ satellite_url }}:5000/my_image_name

And this still works on the same box.

I am now trying to do this on a second box and it is just not picking up the osm_image overwrite, even if I pass -e osm_image=my_image_name, it will just ignore it. I was having similar issues when trying to use oreg_url on the working box. 

Can anybody help?

**Comment by abutcher** [comment]
@benashton2 Hey, can you check if your `osm_image` value is making it into the persisted facts for the new master? These can be found within `/etc/ansible/facts.d/openshift.fact` `openshift: { master: {master_image: VALUE}}`

**Comment by alangibson** [comment]
I'm having the same problem with openshift-ansible 3.4.63. I can't override osm_image in the inventory or on the command like with -e.

That master_image value does not make it into openshift.fact on the master.

```
[centos@openshift-1 ~]$ sudo grep 'master_image' /etc/ansible/facts.d/openshift.fact
[centos@openshift-1 ~]$

```
