### ISSUE TITLE
docker upgrade on atomic hosts: how to handle

### ISSUE THREAD

**Issue by ibotty** [openshift/openshift-ansible#2036]
RHEL and CentOS Atomic hosts use the docker-current/docker-latest split. To move to docker-latest (which is recommended, right?), afaict, one has to perform the following steps.

 * disable/stop docker systemd service unit,
 * enable/start docker-latest systemd service unit,
 * set `DOCKERBINARY=/usr/bin/docker-latest` in `/etc/sysconfig/docker`.

If that's desirable, I can change the docker-upgrade playbook as well as the docker role to do that.

**Comment by sdodson** [comment]
We intend to only support `docker` it's my understanding that `docker-latest` should actually conflict with our services however I don't know for sure how that's implemented, or even if it is implemented.

That said, I think https://github.com/openshift/origin/pull/9046 should make this work when you've elected to use docker-latest. We definitely won't be testing with anything other than docker-current.

**Comment by sdodson** [comment]
Essentially, docker aka docker-current exists to fulfill the requirements of kubernetes and openshift. Whereas docker-latest is there to meet the needs of users who require newer versions of docker than those that have been thoroughly vetted against kubernetes and openshift.
