### ISSUE TITLE
How to update OpenShift Origin from 1.2 to 1.3

### ISSUE THREAD

**Issue by Lunik** [openshift/openshift-ansible#2047]
I have seen that there are upgrades aviable into `playbooks/byo/openshift-cluster/upgrades/`
But I don't see how to update my OpenShift Origin cluster from 1.2 to 1.3

Or maybe it's just because the 1.3 is in alpha ?

**Comment by abutcher** [comment]
Hey @Lunik, we don't have a playbook for 1.2 to 1.3 yet.

**Comment by tj13** [comment]
@abutcher any update now?

**Comment by stevenmirabito** [comment]
@tj13 See here: https://github.com/openshift/openshift-ansible/tree/master/playbooks/byo/openshift-cluster/upgrades/v3_3

v3.3 refers to the version of OpenShift Enterprise, subtract 2 from the major version to get the version of OpenShift Origin.

**Comment by michaelgugino** [comment]
This issue appears to have been solved by answering the question.

Closing this issue.  If you are still affected by this issue, please consider opening a new issue.

**Comment by JoaoJoia** [comment]
There is someone that can help me with the upgrade  of OpenShift Origin cluster from 1.2 to 1.3. the v3_4 upgrade?
