### ISSUE TITLE
I can't create a cluster on AWS 

### ISSUE THREAD

**Issue by darkjeff99** [openshift/openshift-ansible#2057]
Hello 

I tried to create an openshift origin cluster on AWS. For that I use an instance directly on AWS and I launch the 
`bin/cluster -v create aws opshift`

I use those parameter
`export AWS_ACCESS_KEY_ID='XXX'
export AWS_SECRET_ACCESS_KEY='XXXX'
export ec2_image=ami-XXX (<- copy of centos7 ami)
export ec2_region=us-east-1
export ec2_keypair=sshkey
export ec2_assign_public_ip=false
export os_etcd_root_vol_size=20
export os_etcd_root_vol_type=standard
export os_etcd_vol_size=20
export os_etcd_vol_type=standard
export os_master_root_vol_size=20
export os_master_root_vol_type=standard
export os_node_root_vol_size=15
export os_docker_vol_size=50
export os_docker_vol_ephemeral=false
export ec2_instance_type=m3.medium`

And I have this result
`TASK [Launch instance(s)] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The following group names are not valid: public"}`

So ok the SG 'public' doesn't existe on my account.I changed for SG ec2_security_groups="['sec-infra']" (<-- this one exist) in the result is :

`TASK [Launch instance(s)] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Instance creation failed => InvalidParameterValue: Value () for parameter groupId is invalid. The value cannot be empty"}
	to retry, use: --limit @playbooks/aws/openshift-cluster/launch.retry
`

I tried with the SG-ID and I have 
`TASK [Launch instance(s)] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The following group names are not valid: sg-xxxxxx"}
	to retry, use: --limit @playbooks/aws/openshift-cluster/launch.retry
`

What I do wrong ?

**Comment by andriyfomenko** [comment]
propblem looks to the be related to the version on ansible

switching ansible from v.2 nto v.1.9 seems to resolve it

**Comment by darkjeff99** [comment]
l forgot the vpc varaible
