### ISSUE TITLE
Do not set networkPluginName in node config when openshift network plugin is used

### ISSUE THREAD

**Issue by pravisankar** [openshift/openshift-ansible#2066]
With this PR https://github.com/openshift/origin/pull/9147, node configuration networkConfig.networkPluginName is optional for openshift network plugin. We recommend users not to set this param in this case. OpenShift node will auto detect network plugin from OpenShift master and this will avoid any plugin mismatches (more details: https://trello.com/c/Lr0wa4hr/228-5-detect-master-and-node-sdn-plugin-mismatch-sdn)

I don't know if we need any ansible changes, please verify and do the needful.
@brenton @sdodson

**Comment by detiber** [comment]
@sdodson I think we'll want this prior to 3.3, since we are forking we should be able to not worry about backwards compat for versions prior to 1.3/3.3
