### ISSUE TITLE
can not pull image 

### ISSUE THREAD

**Issue by minikiller** [openshift/openshift-ansible#2079]
i used latest openshift-ansible vesion to build openshift cluster. when it finished, i create router,it show following error:
Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "Tag v1.2.0-rc1-13-g2e62fab not found in repository docker.io/openshift/origin-pod"

**Comment by lvthillo** [comment]
explained in #2045

**Comment by sdodson** [comment]
This was a packaging issue that's since been resolved. If you're still having the problems please `yum upgrade origin\*`
