### ISSUE TITLE
Fresh installation do install DNSMASQ by default  for 3.2 if openshift_use_dnsmasq not defined

### ISSUE THREAD

**Issue by ivanthelad** [openshift/openshift-ansible#2080]
The documentation states that DNSmasq will be installed by default.

https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.ose.example#L375

If this config is not present then i expect that the new resolution mechanism  of using a local dnsmaq to be installed. This is not the case. The installer reverts back to the previous 3.1 mechanism.

**Comment by abutcher** [comment]
This is the intended behavior if I'm understanding correctly. DNSmasq will be configured by default unless `openshift_use_dnsmasq=False` has been set in the inventory. Was DNSmasq not configured by default?

**Comment by ivanthelad** [comment]
Correct, the dnsmasq was not not configured

On Wed, Jun 29, 2016 at 2:16 PM, Andrew Butcher <notifications@github.com>
wrote:

> This is the intended behavior if I'm understanding correctly. DNSmasq will
> be configured by default unless openshift_use_dnsmasq=False has been set
> in the inventory. Was DNSmasq not configured by default?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/openshift-ansible/issues/2080#issuecomment-229491402>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACgmj_WLCwm8LZbJdFOcb7gxVfjkS6hKks5qQuCjgaJpZM4I9pJF>
> .
>



-- 

Red Hat GmbH, http://www.de.redhat.com/, Registered seat: Grasbrunn,
Commercial register: Amtsgericht Muenchen, HRB 153243,
Managing Directors: Charles Cachera, Michael Cunningham, Michael
O'Neill, Eric Shander

**Comment by abutcher** [comment]
Which version of the installer are you using? I'm unable to reproduce with the latest packaged installer / master branch.
