### ISSUE TITLE
The problem of openshift_node_dnsmasq when use openshift-ansible (lastest master branch) 

### ISSUE THREAD

**Issue by jeffchanjunwei** [openshift/openshift-ansible#2105]
Hi. I have just download the openshift-ansible master branch to install origin. But a problem of  openshift_node_dnsmasq always happen. There is no use after install NetworkManager. Info showed bellow

TASK [openshift_node_dnsmasq : fail] *******************************************
fatal: [10.134.29.16]: FAILED! => {"changed": false, "failed": true, "msg": "Currently, NetworkManager must be installed and enabled prior to installation."}
fatal: [10.134.29.158]: FAILED! => {"changed": false, "failed": true, "msg": "Currently, NetworkManager must be installed and enabled prior to installation."}
fatal: [10.134.29.159]: FAILED! => {"changed": false, "failed": true, "msg": "Currently, NetworkManager must be installed and enabled prior to installation."}
	to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP *********************************************************************
10.134.29.158              : ok=253  changed=14   unreachable=0    failed=1   
10.134.29.159              : ok=72   changed=3    unreachable=0    failed=1   
10.134.29.16               : ok=72   changed=3    unreachable=0    failed=1   
localhost                  : ok=14   changed=6    unreachable=0    failed=0   

**Versions**
openshift-ansible: lastest master 
centos7-1.6
openshift v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

**Additional Information**
archtecture of my openshfit
Host Name Infrastructure Component to Install
master.example.com Master and node
node1.example.com Node
node2.example.com Node

**Comment by sdodson** [comment]
Do you have network manager installed and started?

**Comment by jeffchanjunwei** [comment]
@sdodson  thx. It is fixed after starting the networkmanager.

**Comment by deromka** [comment]
Why is NetworkManager should be a prerequisite? Can't we add handling of missing NetworkManager package? So Ansible will install it? 
I can make a pull request with the fix.

**Comment by sdodson** [comment]
> Why is NetworkManager should be a prerequisite? Can't we add handling of missing NetworkManager package? So Ansible will install it?

It's required because we use a NM dispatcher script to configure the node to use skydns to lookup cluster.local addresses. It's not hard to install NM and enable it but from discussions with the NM team we didn't think it was a safe thing to do without alerting the admin. If you want to open a PR that installs NM and enables it but is off by default that'd be fine. something like `when: openshift_node_install_nm | default(False)` then you could set openshift_node_install_nm=True in your inventory to opt in.

**Comment by jonasheinisch** [comment]
@deromka Have you done that?

**Comment by deromka** [comment]
No, not yet. Still have not had time slot for this

**Comment by sbadakhc** [comment]
I'm seeing this also. Installing on Fedora 26 using the master branch at commit bf723d2dcd84e13ae3856538df04c767433df984.

**Comment by brennv** [comment]
@sbadakhc This looks like a step in the right direction https://github.com/openshift/openshift-ansible-contrib/pull/542

**Comment by sbadakhc** [comment]
@brennv Thanks I will take a look and feedback.
