### ISSUE TITLE
number of forks/threads a command line option

### ISSUE THREAD

**Issue by tdawson** [openshift/openshift-ansible#211]
Right now, the number of forks ansible will use is set with the ansible config file, and the default it 5.
I would like to have that be customizable for openshift-ansible via a command line option.

  ./bin/cluster create -f 50 -m 1 -n 20 -t online aws <cluster_id>
Would create 1 master, 20 nodes, and use up to 50 forks.

**Comment by detiber** [comment]
@tdawson, you should be able to accomplish this currently by exporting the ANSIBLE_FORKS env variable as a stopgap.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
