### ISSUE TITLE
etcd role uses the same variable for advertise and listen URLs

### ISSUE THREAD

**Issue by FilipVozar** [openshift/openshift-ansible#2114]
etcd config uses the same variable (etcd_ip, which is set using openshift.common.ip) for advertise_client_urls and listen_client_urls (same for peer urls), which means that it's not possible to use etcd with nodes behind NAT. 

If we want to specify NAT'd public IP address in advertise_client_urls then etcd fails to start, because it tries to bind to the same IP address (since the same IP is specified in listen_client_urls), but this IP address doesn't belong to any of the host's interfaces.

**Comment by albarki** [comment]
I had the same issue, and I solved it by passing an extra variable to overwrite the variable `etcd_ip` as follows:
`ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml -e "etcd_ip=192.168.205.10"`
