### ISSUE TITLE
There are many deprecation warnings in a playbook run

### ISSUE THREAD

**Issue by tbielawa** [openshift/openshift-ansible#2125]
I noticed many deprecation warnings like such

> [DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{g_all_hosts}}').

This is a simple fix. PR incoming presently.

**Comment by detiber** [comment]
One thing to note is that we can't address these until we completely cut off Ansible < 2.0

**Comment by tbielawa** [comment]
Do we have a label for that @detiber ?

**Comment by tbielawa** [comment]
@detiber also, check out the PR. It only fixes a subset of the deprecation warnings. Nothing specific to ansible >= 2.x

**Comment by detiber** [comment]
@tbielawa noted, I blame it on post-summit brain :)
