### ISSUE TITLE
AWS installer doesn't add master to the set of nodes

### ISSUE THREAD

**Issue by mdanter** [openshift/openshift-ansible#2150]
When provisioning an OSE cluster with 1 master and 3 nodes, the master instance is not part of the set of nodes. (tested with both origins and product bits)

**Comment by etsauer** [comment]
cc: @detiber

**Comment by detiber** [comment]
@mdanter what is the method of installation? If using atomic-openshift-installer, what does the generated config look like? If using the advanced installation method, what does the inventory file look like?

**Comment by abutcher** [comment]
Sounds like the master wasn't explicitly added to the node group? @detiber Can we just add masters to nodes when we're evaluating groups?

**Comment by detiber** [comment]
@abutcher I'm not sure we want to do that, since there could be legitimate reasons that someone may not want their masters to be a node (I'm thinking specifically about cases where they aren't using the features that require the master to be a node, or their SDN configuration allows for the masters to be a part of the pod network without explicitly being a node).

**Comment by abutcher** [comment]
@detiber Makes sense

**Comment by sdodson** [comment]
@mdanter what is the method of installation? If using atomic-openshift-installer, what does the generated config look like? If using the advanced installation method, what does the inventory file look like?

**Comment by mdanter** [comment]
This is for the AWS installer, so everything is form the dynamic inventory. Although I also read the info on RH slack channel that this is done on purpose, as it's considered good practice to not share the master on AWS. This is probably not an issue.

**Comment by detiber** [comment]
@mdanter the master should always be a node (otherwise there are features/functionality that will not work since the master is unable to access the pod SDN otherwise). It should however be tagged as unschedulable.

**Comment by mdanter** [comment]
https://github.com/openshift/openshift-ansible/pull/2313 addresses this issue

**Comment by DanyC97** [comment]
can we please close this issue as #2313 was merged ?
