### ISSUE TITLE
upgrade playbook fails on atomic hosts

### ISSUE THREAD

**Issue by ibotty** [openshift/openshift-ansible#2172]
There is no repoquery on atomic hosts, so `playbooks/common/openshift-cluster/upgrades/docker/upgrade_check.yml` will fail.

If the rpm_q module #963 is merged, at least checking the current version won't need repoquery anymore which will help a bit.

I can see two ways to check for docker upgrades on atomic hosts, both are pretty invasive.

1. Also do the atomic host upgrade:
 * Check whether there is a new upgrade available,
 * Check docker versions (current and in the next atomic release)
 * proceed as usual

2. Install the new docker rpm on top of the atomic release using rpm-ostree pkg-add.

Both will need very thorough documentation as well!

**Comment by detiber** [comment]
I suspect we'll want to just avoid querying rpm on atomic host, since we don't control the docker package on those hosts.

**Comment by dgoodwin** [comment]
Two paths to the new docker upgrade stuff, one is the standalone "upgrade docker" playbook, the other is the 3.2 upgrade playbook. The upgrade docker playbook was guarding if the host was atomic, I missed it when including this in 3.2 though. Fix incoming momentarily.
