### ISSUE TITLE
HaProxy blocks start of openshift-master process

### ISSUE THREAD

**Issue by david-strejc** [openshift/openshift-ansible#2180]
When I've installed clean deployment (BYO) installation failed with HAProxy being bind to 8443 port and openshift-master process won't start.

When I've stopped HAproxy installation continued.

**Comment by sdodson** [comment]
You have the lb role on the same host that you have the master role? That's
really not a great architecture but if you want to do that you have to
change the API port for the master so they don't conflict.

**Comment by michaelgugino** [comment]
This issue appears to have been solved by answering the question.

Closing this issue because it is solved.
