### ISSUE TITLE
Deploying on CentOS fails, kubeconfig file is created with incorrect name 

### ISSUE THREAD

**Issue by alongoldboim** [openshift/openshift-ansible#2186]
pastebin with needed info:
http://pastebin.com/VwjHtTAL

inventory file:
```yaml
[OSEv3:vars]
openshift_master_identity_providers=[{"name":"example_name","login":"true","challenge":"true","kind":"AllowAllPasswordIdentityProvider"}]
    
[OSEv3:children]
masters
nodes

[masters:vars]
ansible_ssh_user=root
ansible_sudo=yes
deployment_type=origin
#openshift_use_manageiq=True

[nodes:vars]
ansible_ssh_user=root
ansible_sudo=yes
deployment_type=origin
#openshift_use_manageiq=True


[masters]
192.168.122.2 ansible_connection=local ansible_sudo=no

[nodes]
192.168.122.2 ansible_connection=local openshift_scheduleable=True
192.168.122.4
192.168.122.6

```

**Comment by alongoldboim** [comment]
@sdodson @detiber @simon3z please have a look.

**Comment by abutcher** [comment]
Details from IRC.

Node kubeconfig was created as `/etc/origin/node/system:node:example1.com.kubeconfig` but node configuration references `/etc/origin/node/system:node:192.168.122.6.kubeconfig`.

```
host 192.168.122.6
6.122.168.192.in-addr.arpa domain name pointer example1.com

host example1.com
example1.com has address 192.168.122.6
```

**Comment by detiber** [comment]
@abutcher I suspect that the oadm command that creates the kubeconfig is determining the name in a different way than we are when naming the files.

**Comment by abutcher** [comment]
Both the config value and the filename (set via `--user` param to `create-api-client-config`) are based on `openshift.common.hostname`. It looks like these could only differ if `openshift.common.hostname` was set to a different value when creating the client config vs creating the node config.

**Comment by sdodson** [comment]
@alongoldboim Any chance you've re-run the installer after changing the inventory?

**Comment by alongoldboim** [comment]
@sdodson change it in what way?

**Comment by sdodson** [comment]
Altering the inventory name or openshift_hostname values between runs.

**Comment by sdodson** [comment]
@alongoldboim bump -- any chance your inventory changed between runs?

**Comment by alongoldboim** [comment]
Checked again and it worked out on its own :), closing.
