### ISSUE TITLE
Playbook should check hostsubnet doesn't clash with osm_cluster_network_cidr

### ISSUE THREAD

**Issue by andrewhatfield** [openshift/openshift-ansible#2203]
If a user is deploying the playbook and has their subnet set to 10.10.0/16 and hasn't changed osm_cluster_network_cidr from the default 10.1.0.0/16 the playbook works its way through quite a way until it fails with an unhelpful error highlighting that it was unable to get a subnet for the nodes.

Need to check if there is a conflict early on and fail early and meaningfully

**Comment by lpsantil** [comment]
+1
