### ISSUE TITLE
Router and Registry pods are not deployed when scheduling disabled for master

### ISSUE THREAD

**Issue by bkmagnetron** [openshift/openshift-ansible#2206]
By default scheduling is disabled for master.

```
[root@vlinux _files]# cat /etc/ansible/hosts 
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_sudo must be set to true
#ansible_sudo=true

deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# host group for masters
[masters]
vlinux.myhost.net

# host group for nodes, includes region info
[nodes]
vlinux.myhost.net openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
vlinux2.myhost.net openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
```

```
PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=6    unreachable=0    failed=0   
vlinux.myhost.net         : ok=392  changed=86   unreachable=0    failed=0   
vlinux2.myhost.net        : ok=154  changed=40   unreachable=0    failed=0   

[root@vlinux _files]# oc get nodes
NAME                  STATUS                     AGE
vlinux.myhost.net    Ready,SchedulingDisabled   55m
vlinux2.myhost.net   Ready                      55m
[root@vlinux _files]# oc project default
Now using project "default" on server "https://vlinux.myhost.net:8443".
[root@vlinux _files]# oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-deploy   0/1       Pending   0          48m
router-1-deploy            0/1       Pending   0          49m
```

When I append `openshift_schedulable=true` to master node in Ansible hosts and install, everything works good.

**Comment by anhnguyenbk** [comment]
@bkmagnetron I have the same problem too. I follow your instruction (append openshift_schedulable=true to master node) and it works. But I get in trouble, I can't login to private registry when the registry running on master node.  So I can't pushing image to the registry. Are your registry working normal?

**Comment by bkmagnetron** [comment]
@anhnguyenbk 
I think the registries are working fine (when `openshift_schedulable=true`) because the Django Example that I deployed will build an image and push it to the registry, pods are also successfully deployed to other node. And route also working.

**Comment by pat2man** [comment]
You need at least one node in the "infra" region or you need to update your default project node selector to run nodes in the "primary" region. The suggested setup is to have at least one "infra" node and at least one "primary" node.

**Comment by bkmagnetron** [comment]
@pat2man I just followed this example https://docs.openshift.org/latest/install_config/install/advanced_install.html#single-master and yes I do have one infra node and one primary node.

**Comment by anhnguyenbk** [comment]
I set the docker registry ip to `no_proxy` env variable of Docker. Then I can push image to the registry successful. Unfortunately, when I deployed the `nodejs-example`, my deployment process has failed with logs
```
F0727 09:43:15.317280 1 deployer.go:70] couldn't get deployment test/nodejs-example-4: Get https://172.30.0.1:443/api/v1/namespaces/test/replicationcontrollers/nodejs-example-4: dial tcp 172.30.0.1:443: getsockopt: connection refused
```
I'm cluster beginner, could you give me some advice?

**Comment by pat2man** [comment]
@bkmagnetron Yeah it seems the documentation should be updated to reflect this, or the default should be set to true. Documentation is a separate project...

**Comment by sdodson** [comment]
Sorry we missed this, we've updated the docs here https://github.com/openshift/openshift-docs/pull/4317/
