### ISSUE TITLE
Add support arbitrary variables per-host 

### ISSUE THREAD

**Issue by alongoldboim** [openshift/openshift-ansible#2207]
@smunilla @sdodson @detiber @simon3z 
Currently can only add arbitrary variables per role, but not on a single instance.
As example I would like to set `ansible_connection=local` just for the master we deploy on.

**Comment by sdodson** [comment]
This is a blocker for your use cases?

**Comment by alongoldboim** [comment]
I think so, @simon3z what do you think?

**Comment by detiber** [comment]
@sdodson I'd consider this a P0, it breaks many advanced install use cases.

**Comment by simon3z** [comment]
Thanks @detiber yeah this seems pretty serious. Thanks.

**Comment by smunilla** [comment]
#2228 Adds this functionality
