### ISSUE TITLE
Getting SIGHUP when deploying atomic-openshift-installer command from ssh

### ISSUE THREAD

**Issue by alongoldboim** [openshift/openshift-ansible#2209]
@smunilla @simon3z @detiber @sdodson 

```
ssh -t root@10.35.48.15 'SSH_AUTH_SOCK=/root/ssh_manageiq_121 sudo -bE atomic-openshift-installer -u -c /usr/share/ansible/openshift-ansible/inventory.yaml install 1> /tmp/openshift-ansible.log.1 2> /tmp/openshift-ansible.log.2 < /dev/null; sleep 2' 
```

This command works only with sleep, if ill remove it the command won't take effect and the playbooks will not run.
I think the command is getting SIGHUP before the atomic-openshift-installer can register SIGHUP handler, Any chance to make this sooner?

**Comment by smunilla** [comment]
Around the 3.4 timeframe, we'll be looking into this as well as anywhere the quick-installer is using subprocess to call out. For now, I guess just stick with the workaround.

**Comment by alongoldboim** [comment]
@simon3z thoughts?

**Comment by simon3z** [comment]
> Around the 3.4 timeframe, we'll be looking into this as well as anywhere the quick-installer is using subprocess to call out. For now, I guess just stick with the workaround.

@smunilla do you have any insight on how to fix this? @alongoldboim and @dkorn may be able to help on this.

**Comment by detiber** [comment]
@abutcher ptal
