### ISSUE TITLE
Update ALL certificates in an openshift cluster

### ISSUE THREAD

**Issue by cw-aleks** [openshift/openshift-ansible#2212]
# The Story

Let's say you have installed an openshift cluster last year ~15th July.
The certificates are valid for one year.

Now suddenly your cluster is going down with the following message.

```
<TIMESTAMP> <MASTER> atomic-openshift-master[92741]: F0721 21:59:11.925617 92741 \
start_master.go:100] could not reach etcd: 501: \
  All the given peers are not reachable (failed to propose on members \
    [https://<ETDC_URL>:4001] twice \
      [last error: Get https://<ETDC_URL>:4001/v2/keys/?quorum=false&recursive=false&sorted=false: \
  x509: certificate has expired or is not yet valid]) [0]
```

My dirty solution was to move on ALL hosts the /etc/origin and rerun the ansible installer.
I have done this because I haven't seen any better way.

What's your solution?
# The wish

How about to add a playbook to update the certificates in the same way as the install creates the certificates?

**opinions?**

**Comment by sdodson** [comment]
We're working on this, we have outstanding work to both review a cluster's certificate age and to update certificates.

**Comment by DanyC97** [comment]
can we close this issue as #1142 was merged ?

**Comment by sdodson** [comment]
Yes, I think so. There's ongoing efforts to improve those playbooks but I think they're working for the most part today.
