### ISSUE TITLE
'master_cert_config_dir' is undefined

### ISSUE THREAD

**Issue by m-wynn** [openshift/openshift-ansible#2215]
It looks like #1990 removed the `master_cert_config_dir` variable, and in most instances it has been replaced with `{{ openshift.common.config_base }}/master`.  This change didn't seem to make it to `playbooks/common/openshift-master/config.yml` on what is currently line [202](https://github.com/openshift/openshift-ansible/blob/cd46274c9d52dab3553f3f88fca37bf2a93c9068/playbooks/common/openshift-master/config.yml#L202), at the top of task "Deploy named certificates".

This makes the task  "Ensure named certificate directory exists" fail.  I don't mind PRing this, but I would like confirmation that replacing the line with `named_certs_dir: "{{ openshift.common.config_base }}/master/named_certificates/"` is the proper way to fix it.

**Comment by abutcher** [comment]
Thanks @m-wynn! You're correct but I went ahead and opened https://github.com/openshift/openshift-ansible/pull/2216 w/ another fix for the deprecation warnings in that play.
