### ISSUE TITLE
undefined variables: 'deployment_type' is undefined, using atomic-openshift-installer

### ISSUE THREAD

**Issue by alongoldboim** [openshift/openshift-ansible#2223]
@simon3z @detiber @smunilla @sdodson 
http://pastebin.com/eW8mN7Qx
* Getting this error when trying to deploy, tried with Ansible 1.9.4 and with 2.1.0, both failed.
* Not sure why i got an unreachable error, should be failed.
* Another unrelated issue if the installer should be deployed with ansible 2 then the dependency should be on it (currently  >=1.9.4)

**Comment by smunilla** [comment]
Fixed by #2226
