### ISSUE TITLE
origin-node.service fails to load on Centos 7 due to bad kubeconfig file name

### ISSUE THREAD

**Issue by alongoldboim** [openshift/openshift-ansible#2234]
@smunilla @detiber @sdodson @simon3z @dkorn 
inventory:
http://pastebin.com/UF75NiLw

ansbile log (192.168.122.7):
http://pastebin.com/zL9ZfYtP

`journalctl -lu origin-node` (192.168.122.7):
http://pastebin.com/qgSBUhZA

this file exists:
/etc/origin/node/system:node:example2.com.kubeconfig

it is being created using a bad name.

**Comment by sdodson** [comment]
Dupe of #2186
