### ISSUE TITLE
Advanced installed Failed on openshift_examples

### ISSUE THREAD

**Issue by metal3d** [openshift/openshift-ansible#2246]
Hi,
I'm testing installation on 3 centos 7 servers - using my Fedora 24 as deployer.
I'm trying a "one master - 2 nodes" using this inventory:

```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin

[masters]
master.192.168.124.56.xip.io

[nodes]
node1.192.168.124.97.xip.io
node2.192.168.124.185.xip.io
```

Running:
```
$ ansible --version
ansible 2.1.0.0
$ ansible-playbook  -i testinventory  playbooks/byo/config.yml
```

The error is:
```
fatal: [master.192.168.124.56.xip.io]: FAILED! => {"changed": false, "failed": true, "msg": "path /usr/share/openshift/examples/./image-streams does not exist", "path": "/usr/share/openshift/examples/./image-streams", "state": "absent"}
```

"oc" is installed but no nodes are detected:

```
# on master
$ oc get nodes
[nothin appears]
```

Can you please help me to understand ?

Openshift version 1.2.1 tested, then "master" git branch. Error is the same.

**Comment by abutcher** [comment]
Hey @metal3d, which task is that error message tied to? It looks like the `examples_base` variable from the `openshift_examples` role is being set incorrectly.

The playbooks will configure etcd+masters, install examples and then configure nodes. At this point in the run only masters will be up and running.

**Comment by metal3d** [comment]
@abutcher 

This is what the cow says:

```
/ TASK [openshift_examples : Unarchive the OpenShift examples \
\ on the remote]                                              /
 -------------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [master.192.168.124.56.xip.io]: FAILED! => {"changed": false, "failed": true, "msg": "path /usr/share/openshift/examples/./image-streams does not exist", "path": "/usr/share/openshift/examples/./image-streams", "state": "absent"}

```

I don't understand you last sentence. Do you mean that there is no way to have working nodes at this time or only because the playbook crashed ?

**Comment by metal3d** [comment]
@abutcher at this time I deactivate "openshift_install_examples" (set to false) and it seems that the install continues.
Also, I didn't see the https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example file that is a good starting point. I've only read the openshift documentation and not the given example.

Now... There are two more fails... 
```
 ___________________________________________________________
/ TASK [openshift_node_certificates : Unarchive the tarball \
\ on the node]                                              /
 -----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [node2.192.168.124.185.xip.io]: FAILED! => {"changed": false, "failed": true, "msg": "path /etc/origin/node/./system:node:192.168.124.185.crt does not exist", "path": "/etc/origin/node/./system:node:192.168.124.185.crt", "state": "absent"}
fatal: [node1.192.168.124.97.xip.io]: FAILED! => {"changed": false, "failed": true, "msg": "path /etc/origin/node/./system:node:192.168.124.97.crt does not exist", "path": "/etc/origin/node/./system:node:192.168.124.97.crt", "state": "absent"}
```

Maybe you can set this issue to a waiting state, I will study what happends and give you more precise information. 

Thanks for you help

**Comment by metal3d** [comment]
Ok... I've installed without error after a while.
There are 3 "problems":

- we cannot install examples so as I explained earlier, we can disable example installation
- etcd group: if I set one, there are an error with etcd directory
- if I set "lb" group with the master inside, 8443 is already in use by haproxy and so origin-master won't start

There are no documentation about restriction, or maybe I rally did something wrong.

To be precise, I already have installed Kubernetes with "traefik" LB on master, even if it's not a "nice to have", it should be possible, isn't it ?

**Comment by abutcher** [comment]
Examples and etcd certificates are both failing to unarchive which reminds me of https://github.com/openshift/origin/issues/9569. Could you try with ansible's `stable-2.1` branch?

To test using an ansible checkout:
```
$ git clone git@github.com:ansible/ansible.git
$ cd ansible
$ git checkout stable-2.1
$ git submodule update --init --recursive
$ . ./hacking/env-setup
```

Now we're running latest `stable-2.1`:
```
$ ansible --version
ansible 2.1.1.0 (stable-2.1 9eb32357de) last updated 2016/07/07 14:49:45 (GMT -400)
  lib/ansible/modules/core: (detached HEAD c8d6886007) last updated 2016/07/07 14:51:49 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 4d6afbcb62) last updated 2016/07/07 14:51:51 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

lb and master conflicting ports has been raised here https://github.com/openshift/openshift-ansible/issues/2069 however, the lb group configured by openshift-ansible is meant to be a stand in load balancer for the master API when multiple masters are in use. I say stand in because our lb group (which supports a single instance) introduces a single point of failure and should not be used in production environments. We call attention to this in openshift-docs but it could definitely be documented more clearly in our example inventories.

**Comment by metal3d** [comment]
Ok, for etcd it's ok since I'm using ansible 2.1.1.0 (fedora package, I was using another version installed from pip before). Anyway, "examples" are not ok but it's not so important ;)

For loadbalancers, I just don't understand what is wrong... but I guess I will create another issue (or maybe there is a way to speak with you to be sure that I should create an issue)

There are 2 others "problems" (that word is maybe not appropriated) from SSL certificates. I will check and create an issue for it. But at this time I'm able to have openshift origin working on my 3 VM :)

One more time, thanks for your help and spent time to help.

I can close issue
