### ISSUE TITLE
Nodejs-example deploy failed. Dial tcp 172.30.0.1:443: getsockopt: connection refused

### ISSUE THREAD

**Issue by anhnguyenbk** [openshift/openshift-ansible#2248]
I used `ansible-playbook playbooks/byo/config.yml` command to set up a cluster has 1 master (also be a infra node with `openshift_schedulable=true` ) and 1 primary node. All of them were created by Vagrant with VirtualBox Provider. When I deploy nodejs-example application, build phase sucessful, but deployment phase failed with below result
```
F0802 08:24:20.635837       1 deployer.go:70] couldn't get deployment test/nodejs-example-3: Get https://172.30.0.1:443/api/v1/namespaces/test/replicationcontrollers/nodejs-example-3: dial tcp 172.30.0.1:443: getsockopt: connection refused
```
I created `nodejs.yaml` file with image from previous build phase and use `kubectl create -f nodejs.yaml` command to deploy. The nodejs-ex pod was created successful.
I think here is a origin problem
Thank for your help.

**Comment by sdodson** [comment]
So the pod is failing to reach the kubernetes service IP. I'd first restart the `origin-node` service on the host and try again. If that fails go through the network debugging steps here https://docs.openshift.org/latest/admin_guide/sdn_troubleshooting.html

**Comment by anhnguyenbk** [comment]
It's VirtualBox networking problem. I removed NAT interface and used Host-only connect to Internet through a proxy. It worked.

**Comment by govindmundhra** [comment]
@anhnguyenbk  How did you resolve the Virtualbox networking problem? I tried it and it didn't work for me.
Please can you guide me through the resolution? I have two networks on Virtual machine 1. NAT and 2. Host-only Network. If I remove NAT, Then I am no longer able to connect to VM.

**Comment by anhnguyenbk** [comment]
Don't use NAT. You can choose between one of two options:
- Use **NAT Network** (you can create new NAT Network on File->Preferences->Network)  and Host-only Network. 
- Use only Host-only network (You will need a proxy server on your host. VMs can connect to the Internet through the proxy.).

**Comment by naveenkumartangallapally** [comment]
can u please explain briefly plzzzz,if we remove NAT how we can connect to internet?

**Comment by anhnguyenbk** [comment]
@naveenkumartangallapally u can use **NAT Network** (not NAT) and Host-only Network, or just only Host-only network. For the internet connection when using Host-only network, u can use install a proxy server on your host machine and setting proxy for your VMs. Sorry for late reply, because now I don't study Kubernet anymore.
