### ISSUE TITLE
Do hosted registry/router optional

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#2253]
HI,

We do not want to create our router/registry via openshift-ansible. 

We have multiple routers with custom options and a secured registry.

I would be awsome to create options like 

```
openshift_hosted_manage_router=false
openshift_hosted_manage_registry=false
```

**Comment by jkroepke** [comment]
@sdodson @abutcher Thanks. Its possible to backport this feature to 3.2 enterprise?

**Comment by sdodson** [comment]
@jkroepke https://github.com/openshift/openshift-ansible/pull/2256 backported it to 3.2 branch

**Comment by jkroepke** [comment]
Thanks a lot!
