### ISSUE TITLE
Static pod in openshift-origin

### ISSUE THREAD

**Issue by enlinxu** [openshift/openshift-ansible#2270]
Hi,
Is there a way to create a static pod using ansible, so that it is automatically started once the origin cluster is up and running.

Thanks in advance,

**Comment by detiber** [comment]
@enlinxu If you are looking for a native ansible module, the only current solution is the kubernetes module: http://docs.ansible.com/ansible/kubernetes_module.html, however I'm not sure if there are issues with authenticating against an OpenShift cluster using it.

If that module doesn't fit your needs/work, then the current best route would probably be to just wrap the oc tooling temporarily to create the pod from a json definition.

We are working on upstream openshift/kubernetes modules, but they are not yet in a consumable state. I spoke about our work in this area at AnsibleFest last month: https://www.ansible.com/videos-ansiblefest-sf-2016 and you can take a look at the (demo quality) work here: https://github.com/detiber/ansible_fest_2016, which also requires the openshift library we are working on here: https://github.com/ftl-toolbox/lib_openshift

**Comment by DanyC97** [comment]
cc @vrutkovs candidate for closing as being stale issue

**Comment by vrutkovs** [comment]
>Is there a way to create a static pod using ansible, so that it is automatically started once the origin cluster is up and running.

Running custom container via static pod is probably a wrong solution to an unclear problem. If its a core component - like custom SDN - you should use DaemonSets, but for user-level apps usual Deployments are recommended.

Not an openshift-ansible issue in any case.
