### ISSUE TITLE
Install NetworkManager automatically

### ISSUE THREAD

**Issue by dvohra** [openshift/openshift-ansible#2272]
While Docker, etcd and HAProxy get installed automatically shouldn't NetworkManager get installed automatically too?

The following commands are required to be run on Centos or RedHat.
```
sudo yum install NetworkManager
sudo systemctl start NetworkManager
sudo systemctl enable NetworkManager
sudo systemctl status NetworkManager
```

**Comment by dvohra** [comment]
Thanks for the correction.

**Comment by sdodson** [comment]
Dupe of #1807
