### ISSUE TITLE
RFE - Enable and start lvm2-lvmetad.service when appropriate

### ISSUE THREAD

**Issue by edseymour** [openshift/openshift-ansible#2289]
A common Docker configuration is to use a LVM thin pool for docker container storage. In some systems (for example Fedora) the lvm2-lvmetad service is disabled by default. 

Subsequently, when running OpenShift for a short while, and following a number of Pod creations, deletions. The system can become unresponsive and will actually no longer run containers. 

systemctl commands won't respond and timeout
docker commands won't respond and timeout

Docker logs show that the system is unable to umount container storage devices. 

Enabling the lvmetad service resolves the issue.

**Comment by detiber** [comment]
@sdodson I'm wondering if this is something that should fall under the responsibility of docker-storage-config (or even docker) rather than openshift-ansible itself. Thoughts?

@dgoodwin I wonder if this could be related to the issue QE was seeing

**Comment by sdodson** [comment]
@rhvgoyal thoughts on this one? We can enable it via the openshift installer but is that the right place?

**Comment by edseymour** [comment]
I agree with @detiber that it seems like the docker-storage-setup would be a better place, since that is configuring the volume groups. (At least report a warning if it isn't enabled). 

I think the issue, however, is peculiar to OpenShift/K8s as a vanilla docker build doesn't seem to be affected in this way. I'm running both and only noticed this on my Fedora + Origin environment, but not my Fedora + just Docker. It could be that the Docker env is more static; you tend to create and destroy a lot of containers in OpenShift.

**Comment by rhvgoyal** [comment]
I don't understand few things.

- What's the dependency on lvmetad and what will happen if it is not enabled.
- Why lvmetad is disabled by default on Fedora.
