### ISSUE TITLE
maxamillion-origin-next-epel-7.repo

### ISSUE THREAD

**Issue by menren** [openshift/openshift-ansible#231]
Hello,

it seems this repository is down because the hosting site copr-be.cloud.fedoraproject.org is down...

**Comment by menren** [comment]
Found this :
https://fedorahosted.org/fedora-infrastructure/ticket/3916

**Comment by sebiwi** [comment]
I'm having the same issue.

**Comment by menren** [comment]
Official status :

http://status.fedoraproject.org/
