### ISSUE TITLE
openshift-ansible takes hours to run after upgrade ansible to 2.1 / openshift 3.2

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#2312]
Hi,

after upgrade ansible to 2.1 and openshift 3.2 (used the official playbooks rpm), The config.yaml playbook takes hours to finish compared to ansible 1.9.4 and openshift 3.1 (used the official playbooks rpm, too)

I'm using the ansible.cfg from [scale up pdf](https://www.openshift.com/sites/default/files/file_downloads/ose-scale-master_0.pdf):

```
[defaults]
forks = 100
host_key_checking = False
remote_user = root
roles_path = roles/
gathering = smart
fact_caching = jsonfile
fact_caching_connection = .cache
fact_caching_timeout = 600
inventory = inventory

[privilege_escalation]
become = False

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=600s
control_path = .cache/%%h-%%r
pipelining = True
```

Our cluster have 3 masters and 18 pods. ansible itself runs on CentOS 7.

There are any known issues about the performance?

**Comment by sdodson** [comment]
Yes, there was a performance regression between ansible 2.0.0.2 and ansible 2.1.0.0. We're using a pre-2.2 build that addresses that issue. You can get it from https://copr.fedorainfracloud.org/coprs/abutcher/ansible/ or if you're running from the 3.1 branch you should be able to continue using ansible 1.9.4, to get that from epel `yum swap ansible ansible1.9`

**Comment by sdodson** [comment]
The regression was https://github.com/ansible/ansible/issues/16749

**Comment by detiber** [comment]
@sdodson @abutcher thoughts on leaving this issue open until ansible 2.2 ships upstream? I'm good either way.

**Comment by abutcher** [comment]
@detiber I think we should leave this open until then.

**Comment by jkroepke** [comment]
Thanks for the information.
Can I used a version greater then 2 from epel which is not affected?

@abutcher version does not work for me, because the playbook says, the nodes are UNREACHABLE. ssh is working fine.

**Comment by jkroepke** [comment]
Okay, looks like an bug in ansible 2.2.

If I removed the control_path setting, ansible works fine.

**Comment by jkroepke** [comment]
Does the enterprise-3.2 branch work with ansible 2.2?

**Comment by sdodson** [comment]
> Does the enterprise-3.2 branch work with ansible 2.2?

Yes, both master and enterprise-3.2 require ansible 2.x and should work with 2.2. All our current work is performed using the 2.2 builds.

**Comment by detiber** [comment]
@jkroepke can you elaborate on the issue you were hitting with control_path? We are working on tracking down an issue with intermittent connection hangs using ansible 2.2, and I want to see if you are hitting the same issue or a different issue.

**Comment by jkroepke** [comment]
If I define control_path (see first comment here). All nodes are UNREACHABLE on Task setup.

**Comment by detiber** [comment]
@jkroepke is it possible that the control_path is being evaluated in a way that is longer than the length allowed for unix domain sockets (108 on Linux, 104 on Mac)?

**Comment by jkroepke** [comment]
Before I upgrade to 2.2, I had no problems.

 Its not mission critical, since ansible provides defaults for control_path. (I have still control sockets without define control_path in the local ansible.cfg)

**Comment by detiber** [comment]
@jkroepke I'm wondering if the way that the path is evaluated may differ from 2.1. We've seen a similar error related to the control_path length, where there was a more appropriate error returned back in the ansible 1.9 days.

**Comment by jkroepke** [comment]
Its maybe a problem that i'm using a symlink for the playbook?

Here is my directory structure..

```
root/
- openshift/
-- openshift-ansible/
-- ansible.cfg
-- testing/
--- ansible.cfg -> /root/openshift/ansible.cfg
--- inventory
--- .cache/
--- openshift-ansible -> /root/openshift/openshift-ansible
-- prod/
--- ansible.cfg -> /root/openshift/ansible.cfg
--- inventory
--- .cache/
--- openshift-ansible -> /root/openshift/openshift-ansible
```

My work dir is testing or prod, if I executing the playbook.

**Comment by jkroepke** [comment]
> @sdodson @abutcher thoughts on leaving this issue open until ansible 2.2 ships upstream? I'm good either way.

Ansible 2.2 prerelease 5 is now available in RHEL OSE repos. FYI.

**Comment by tbielawa** [comment]
@jkroepke ansible 2.2.0.0.3 is now available in fedora updates-testing. Please try reproducing your error again with a newer version.

Please update and reopen this issue if this is still a priority you would like to see action on.
