### ISSUE TITLE
Invalid value: "/etc/origin/master/ca-bundle.crt" after rerun config.yaml playbook

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#2332]
Hi!

today, I tried a new ansible version:

```
$ git log -1
commit 6cd82e8ac5e1770df5a97ba2b7b559948efd47cc
Merge: 206b96f 7ca5a72
Author: Scott Dodson <sdodson@redhat.com>
Date:   Thu Aug 18 16:15:37 2016 -0400

    Merge pull request #2324 from sdodson/enterprise-3.2

    Mount /sys rw
```

After running ansible-playbook -i inventory ./openshift-ansible/playbooks/byo/config.yml, master2 and master3 can't start atomic-openshift-master-api.service anymore.

```
Aug 19 17:40:12 FQDN atomic-openshift-master-api[41165]: Invalid MasterConfig /etc/origin/master/master-config.yaml
Aug 19 17:40:12 FQDN atomic-openshift-master-api[41165]: oauthConfig.masterCA: Invalid value: "/etc/origin/master/ca-bundle.crt": could not read file
Aug 19 17:40:12 FQDN atomic-openshift-master-api[41165]: serviceAccountConfig.masterCA: Invalid value: "/etc/origin/master/ca-bundle.crt": could not read file
```

/etc/origin/master/ca-bundle.crt does exists only on master1.

Shoud the tasks https://github.com/openshift/openshift-ansible/commit/b3d04f1a54c0109ce38be103ddc7c83f1992c10e are included to the config.yaml?

**Comment by detiber** [comment]
@sdodson was the rename from ca.crt to ca-bundle.crt supposed to be backported to the 3.2 branch?

**Comment by sdodson** [comment]
@detiber I believe the cert re-deploy assumes that's the case. I think we should add this to config.yml too.

**Comment by jkroepke** [comment]
I have not defined openshift_certificates_redeploy_ca in my inventory.

**Comment by detiber** [comment]
@sdodson sounds good to me.

**Comment by sdodson** [comment]
> I have not defined openshift_certificates_redeploy_ca in my inventory.

Yeah, you shouldn't have to. The problem is that in the template the path was changed to ca-bundle.crt as part of that work but we fail to migrate when you're not running the upgrade playbooks. We can fix this real quick.

**Comment by jkroepke** [comment]
Should I run always the upgrade playbook before running config playbook? I rerun the config.yml to test cluster wide settings in our test environments.
