### ISSUE TITLE
Upgrade playbooks should copy a pristine admin.kubeconfig for their use (was: Error upgrade from v1.2.1)

### ISSUE THREAD

**Issue by Scisci75** [openshift/openshift-ansible#2342]
Hi, today I've done a git pull origin master  and I've tryed to upgrade from version 1.2.1 using openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_2 /upgrade.yml

the error  is:

TASK [Reconcile Security Context Constraints] **********************************
fatal: [origin-m-01.xxx.it]: FAILED! => {"changed": true, "cmd": ["oadm", "policy", "reconcile-sccs", "--confirm", "--additive-only=true"], "delta": "0:00:00.108750", "end": "2016-08-23 11:45:22.531059", "failed": true, "rc": 1, "start": "2016-08-23 11:45:22.422309", "stderr": "error: openshift-infra is not a valid namespace\nSee 'oadm policy reconcile-sccs -h' for help and examples.", "stdout": "", "stdout_lines": [], "warnings": []}

someone can help me please?
 Thanks 
Mirko

**Comment by sdodson** [comment]
@Scisci75 As the user that ansible uses, on the first master, can you run `oc whoami` ?

**Comment by Scisci75** [comment]
ok copying /etc/origin/master/admin.kubeconfig to ~/.kube/config now works
Thanks
Mirko

**Comment by sdodson** [comment]
Re-opening this. This means that we're not using a clean copy of the admin's kubeconfig during upgrade process and we should be.
