### ISSUE TITLE
Cannot push to local repo

### ISSUE THREAD

**Issue by psteyn** [openshift/openshift-ansible#2343]
I've created a local docker registry, and whenever I want to push to it I get:

sg="Denied creating ImageStreamMapping: User \"system:serviceaccount:lithium:registry\" cannot create imagestreammappings in project \"lithium\"" 

I've googled the error, and cannot find the right command to fix it.
I have a local user called docker_user, I can login to docker with my token just fine.

I've tried:
 oadm policy add-role-to-user system:image-builder registry
oadm policy add-role-to-user system:image-builder docker_user
, but I get the same issue.

Any assistance would be appreciated!

**Comment by sdodson** [comment]
@psteyn Thanks for closing this, I assume you've found the solution? What was it.

**Comment by psteyn** [comment]
@sdodson  I believe this command fixed it:  oadm policy add-role-to-user admin system:serviceaccount:lithium:registry -n lithium
