### ISSUE TITLE
Templated variables not being substituted in facts

### ISSUE THREAD

**Issue by jam13** [openshift/openshift-ansible#2349]
I have been trying to pass environment variables through to vars using the lookup env function like this:

```
openshift_cloudprovider_aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
openshift_cloudprovider_aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
```

which is mentioned in the example byo hosts file. I've tried it in group_vars/all, hosts and direct in vars passed to a playbook.

A simple debug playbook shows that these variables are being correctly set:

```- debug: var=openshift_cloudprovider_aws_access_key```

However when run with the openshift playbooks, the variables end up like this:

```{# lookup('env','AWS_ACCESS_KEY_ID') #}```

From what I've been able to work out, this is being caused by the openshift_facts module merging unparsed template values over the top of the hostvars (which do contain the correct values):

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_cloud_provider/tasks/main.yml#L6

Looking at the related function here:

https://github.com/openshift/openshift-ansible/blob/master/filter_plugins/oo_filters.py#L83

it seems to be merging the play vars with the host specific section of the hostvars, and the play vars take priority. I'm guessing that this was introduced as a way of supporting multiple versions of ansible, but it seems a bit odd and from what I can see is not fully working. My understanding is that ansible versions prior to 2.0 are not supported, so is this code obsolete?

I've reproduced the problem on latest master, and both ansible v2.1 and v2.2.

**Comment by jam13** [comment]
Note that reversing the merge priority, so that the host specific hostvars overwrite the ansible vars seems to work correctly:

```
diff --git a/filter_plugins/oo_filters.py b/filter_plugins/oo_filters.py
index b57bc0a..031cab4 100644
--- a/filter_plugins/oo_filters.py
+++ b/filter_plugins/oo_filters.py
@@ -108,8 +108,8 @@ class FilterModule(object):
         ansible_version = pkg_resources.get_distribution("ansible").version
         merged_hostvars = {}
         if LooseVersion(ansible_version) >= LooseVersion('2.0.0'):
-            merged_hostvars = FilterModule.oo_merge_dicts(hostvars[inventory_hostname],
-                                                          variables)
+            merged_hostvars = FilterModule.oo_merge_dicts(variables,
+                                                          hostvars[inventory_hostname])
         else:
             merged_hostvars = FilterModule.oo_merge_dicts(hostvars[inventory_hostname],
                                                           hostvars)
```

but I've no idea what the repercussions of this are as I don't know what the reason for the merge is in the first place.

**Comment by abutcher** [comment]
@jam13 Thanks for the spot on diagnosis here. I'm going to test your proposed fix but I think it will work out right. Long term I'd like to get rid of the merge entirely and just access the inventory variables / play variables directly for these facts.
