### ISSUE TITLE
No Package matching 'atomic-openshift-0.0' found available, installed or updated

### ISSUE THREAD

**Issue by abutcher** [openshift/openshift-ansible#2383]
Users will receive this message when atomic-openshift* packages are not available and `deployment_type=openshift-enterprise`. Thinking that the `0.0` default should probably be removed since it's a little confusing although we will likely check for package availability in the to-be-created pre-requisites playbook.

```
TASK [openshift_common : Install the base package for versioning]
**************
fatal: [master0.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "No Package matching 'atomic-openshift-0.0' found available, installed or updated", "rc": 0, "results": []}
fatal: [master1.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "No Package matching 'atomic-openshift-0.0' found available, installed or updated", "rc": 0, "results": []}
fatal: [master2.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "No Package matching 'atomic-openshift-0.0' found available, installed or updated", "rc": 0, "results": []}
```

**Comment by detiber** [comment]
@abutcher I think it's used in a comparison. @dgoodwin should be able to verify.

**Comment by dgoodwin** [comment]
@abutcher do you have #2348 in your running copy?

I tried to fix this via https://bugzilla.redhat.com/show_bug.cgi?id=1368548 by just reporting a better error when we see the 0.0, but leaving it in otherwise.

**Comment by abutcher** [comment]
@dgoodwin Nice! I picked this from an email but it looks like you've addressed it. I will close.
