### ISSUE TITLE
Support for Virtualenv

### ISSUE THREAD

**Issue by jhcook** [openshift/openshift-ansible#2399]
I use Virtualenv and store the ansible directory in a Git repo. I have made the following change, to make things work, and although I can't recall exactly why, it would be nice if this were built in.

```
$ git diff roles/openshift_facts/library/openshift_facts.py
diff --git a/roles/openshift_facts/library/openshift_facts.py b/roles/openshift_facts/library/openshift_facts.py
index ebd7994..f188380 100755
--- a/roles/openshift_facts/library/openshift_facts.py
+++ b/roles/openshift_facts/library/openshift_facts.py
@@ -2148,7 +2148,8 @@ def main():
     openshift_env_structures = module.params['openshift_env_structures']
     protected_facts_to_overwrite = module.params['protected_facts_to_overwrite']

-    fact_file = '/etc/ansible/facts.d/openshift.fact'
+    #fact_file = '/etc/ansible/facts.d/openshift.fact'
+    fact_file = os.getcwd() + '/openshift.fact'

     openshift_facts = OpenShiftFacts(role,
                                      fact_file,
```

**Comment by detiber** [comment]
@jhcook only place I can see this being a problem is if the user does not have permissions to create /etc/ansible/facts.d/openshift.fact.

The installation already requires root access (or sudo) and the existing directory is where 'local facts' are automatically picked up by ansible, so I'm not sure we'd want to change where the facts are stored.

**Comment by jhcook** [comment]
Ok perhaps I'm confused, but this is running on the client machine? You shouldn't require root. I run the entire playbook as my normal user. root privs are used on the node being configured.

**Comment by detiber** [comment]
openshift_facts shouldn't be run against the local (client) host, it should only be run against remote hosts (unless the local host is defined as one of the masters, nodes, etcd, etc).

**Comment by jhcook** [comment]
Right. What I'm getting at is /etc/ansible/facts.d should exist on the local host and be writable by a normal user? I'm using Ansible not in /etc/ansible -- it doesn't exist. I use Virtualenv inside a checked out Ansible directory in my home directory and change the inventory and roles_path in ansible.cfg. Perhaps there's a clever way to do this with environment variables are the Ansible constants?

**Comment by detiber** [comment]
@jhcook if openshift_ansible is getting run against localhost and localhost isn't one of the hosts being "installed".

Can you share your hosts file and how you are invoking the playbook to see if we can replicate the issue?

**Comment by detiber** [comment]
@jhcook I'm not seeing anything there that jumps out at me. I did notice that the hosts/lite-app_openshift inventory probably needs `ansible_become=yes` added to ensure compatibility with later ansible 2.x releases, but it shouldn't be running openshift_facts against the localhost.

@abutcher can you see if you can reproduce the issue?

**Comment by jhcook** [comment]
Hi there. This can be closed. I've removed the change and it works just fine. So, somewhere along the lines the "problem" evaporated. Thanks!
