### ISSUE TITLE
Cluster Nodes can't reach each other with Vagrant Deployment

### ISSUE THREAD

**Issue by wattsteve** [openshift/openshift-ansible#241]
I'm running Vagrant 1.7.2 (with VirtualBox) with Ansible 1.9.1. I've followed the vagrant instructions "vagrant up --no-provision; vagrant provision" and the deployment appears to go smoothly.  It produces 3 Vagrant servers - master, node1 and node2. When I vagrant ssh into master and run "osc get nodes" I see that node1 and node2 are reporting as NotReady, so I checked the networking setup and discovered that none of the nodes can reach each other via the network. This is the first time I've used openshift-ansible so I'm also not sure how its meant to work. Any guidance would be appreciated. 

I've provided the details of the network below:

master etc/hosts and ifconfig - http://pastebin.com/Mc5tEY30
node1 etc/hosts and ifconfig - http://pastebin.com/gXZGP5A4
node2  etc/hosts and ifconfig - http://pastebin.com/VaaM39Hr

**Comment by wattsteve** [comment]
This issue looks to be because enp0s8 is not picking up an IP. When I run "sudo systemctl restart network" on each machine it then enp0s8 picks up an IP and we have clustered networking working.

**Comment by detiber** [comment]
@wattsteve I must say, I've never used the VirtualBox provider for vagrant, I always use the libvirt provider. 

One thing I can tell you is that ansible wouldn't be changing the networking configuration, that would either be coming from Vagrant or VirtualBox itself.  Ansible is only run when when vagrant provision is called.

I'm going to dig into the Vagrant docs to see if something stands out in the virtualbox provider networking config that may be causing the issue though.

**Comment by detiber** [comment]
@wattsteve Can you try the changes I've made in this PR: https://github.com/openshift/openshift-ansible/pull/242 ? From looking at the docs and reading about some similar issues, it looks like the VirtualBox network config is a bit more convoluted than libvirt, and to specify an interface/network other than the default, you need to do some changes with modifyvm first.

**Comment by wattsteve** [comment]
It didn't work. I left comments under the PR

**Comment by dlbewley** [comment]
See #331

**Comment by dlbewley** [comment]
I think this issue can probably be closed. @wattsteve ?

**Comment by wattsteve** [comment]
I can't confirm, but feel free to close it.

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.
