### ISSUE TITLE
timdatectl access denied Solution

### ISSUE THREAD

**Issue by ejb1123** [openshift/openshift-ansible#2410]
I am running this on 4 CentOS 7.2.1551 (core) machines, 1 master and 3 nodes.

```
TASK [openshift_clock : Set clock facts] *************************************** changed: [master.example.com] 
TASK [openshift_clock : Install ntp package] *********************************** changed: [master.example.com] 
TASK [openshift_clock : Start and enable ntpd/chronyd] ************************* fatal: [master.example.com]: 
FAILED! => {"changed": true, "cmd": "timedatectl set-ntp true", "delta": "0:00:00.751361", "end": "2016-09-03 16:32:13.621602", "failed": true, "rc": 1, "start": "2016-09-03 16:32:12.870241", "stderr": "Failed to set ntp: Access denied", "stdout": "", "stdout_lines": [], "warnings": []}
```

When I ran the command manually as root on the server I still got the error above. I then went ahead and ran `systemctl start nptd.service`, `system start npdate.service`, `systemctl enable nptd.service`, `systemctl enable npdate.service`. I then checked the status of timedatectl and `NTP synchronized` was set to `yes` and `NTP enabled` was no. After that I installed chrony through yum, ran `timedatectl set-ntp true` and did not get the `access denied` error

**Comment by detiber** [comment]
@ejb1123 that is definitely not expected...  the ntpd service should be sufficient for timedatectl. 

@smunilla ptal

**Comment by hzgraham** [comment]
could this be due to an SELinux denial?

**Comment by smunilla** [comment]
I haven't been able to replicate this. @ejb1123 Does this fail on all hosts or just the master?

**Comment by bashburn** [comment]
We ran into this same issue, and the setup was that ntpd was started and running, but chronyd was masked. I don't know if that will help reproduce it, but by stopping ntpd and enabling chronyd, it fixed it.

**Comment by detiber** [comment]
@smunilla I suspect that the version of systemd in use on those CentOS instances is causing it to use chronyd rather than ntpd for some reason. Original testing on this role verified that it would use ntpd on RHEL and chronyd on Atomic Host, but could be something related to the CentOS config for systemd or a newer version of systemd that has since shipped...

**Comment by smunilla** [comment]
@detiber I'll see if I can come up with a solution

**Comment by nccurry** [comment]
Saw this same error in a recent install. Simply unmasking chronyd seemed to fix the problem. I left ntpd enabled and chronyd disabled, just unmasked.
