### ISSUE TITLE
Pruner support

### ISSUE THREAD

**Issue by gravis** [openshift/openshift-ansible#2434]
Is there something in the roadmap to ensure pruners are installed by ansible?
https://docs.openshift.com/enterprise/3.2/admin_guide/pruning_resources.html

I can't find anything related in this repo, and this is really needed for production clusters.
Thanks

**Comment by sdodson** [comment]
Not that I'm aware of, we'd definitely accept a PR for it. Cron jobs on the first master with all the options exposed or just a dictionary defining cron jobs generically with examples for the various pruning jobs would work well.

**Comment by andrewklau** [comment]
@gravis this might help https://github.com/openshift/openshift-tools/blob/stg/scripts/monitoring/cron-openshift-pruner.py ?

**Comment by detiber** [comment]
@sdodson I do worry about limiting this to just the "first master", but I can't think of a sufficient alternative. Scheduled jobs is alpha for 1.4, so that would be the preferred method once we feel that we can rely on it.

**Comment by harobed** [comment]
Up :)
