### ISSUE TITLE
flanneld service fails to start with ose3.3

### ISSUE THREAD

**Issue by jprovaznik** [openshift/openshift-ansible#2436]
When using flannel on ose3.3, openshift-ansible fails with error:

```
TASK [flannel : Enable flanneld] ***********************************************
task path: /usr/share/ansible/openshift-ansible/roles/flannel/tasks/main.yml:31
<flannel33-openshift-master-0.example.com> ESTABLISH SSH CONNECTION FOR USER: cloud-user
<flannel33-openshift-master-0.example.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/%h-%r flannel33-openshift-master-0.example.com '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dklhtbzhphpyitayqetzzxkwfpgsbrlx; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<flannel33-openshift-node-s6e22h8m.example.com> ESTABLISH SSH CONNECTION FOR USER: cloud-user
<flannel33-openshift-node-s6e22h8m.example.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/%h-%r flannel33-openshift-node-s6e22h8m.example.com '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-jzpdgisowludpowwmyieklkvmqfncysn; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [flannel33-openshift-master-0.example.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"arguments": "", "enabled": true, "name": "flanneld", "pattern": null, "runlevel": "default", "sleep": null, "state": "started"}, "module_name": "service"}, "msg": "Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}
fatal: [flannel33-openshift-node-s6e22h8m.example.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"arguments": "", "enabled": true, "name": "flanneld", "pattern": null, "runlevel": "default", "sleep": null, "state": "started"}, "module_name": "service"}, "msg": "Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/var/lib/ansible/playbooks/main.retry

PLAY RECAP *********************************************************************
flannel33-openshift-master-0.example.com : ok=510  changed=125  unreachable=0    failed=1   
flannel33-openshift-node-s6e22h8m.example.com : ok=145  changed=37   unreachable=0    failed=1   
localhost                  : ok=37   changed=14   unreachable=0    failed=0   
```

On the lannel33-openshift-master-0.example.com flanneld failed probably because of this error message:

```
Sep 12 08:58:40 flannel33-openshift-master-0.example.com flanneld[49454]: E0912 08:58:40.569847 49454 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
```

Used RPMs:
openshift-ansible-lookup-plugins-3.3.2-1.git.0.1223e95.el7.noarch
openshift-ansible-3.3.2-1.git.0.1223e95.el7.noarch
openshift-ansible-filter-plugins-3.3.2-1.git.0.1223e95.el7.noarch
openshift-ansible-roles-3.3.2-1.git.0.1223e95.el7.noarch
openshift-ansible-docs-3.3.2-1.git.0.1223e95.el7.noarch
openshift-ansible-playbooks-3.3.2-1.git.0.1223e95.el7.noarch

**Comment by sdodson** [comment]
I hate to ask, but the version you're using was tagged nearly two months ago, can you try a more recent version there were a few fixes to flannel support since then.

**Comment by jprovaznik** [comment]
Ouch, sorry, my fault. I "fixed" an old puddle build instead of "latest" in my repo url :(, I'll close this if not reproducible on the latest one.

**Comment by sdodson** [comment]
Ok, I think the other issue you opened recently on flannel is in the same boat.

**Comment by jprovaznik** [comment]
Hitting the same issue both with newest 3.2 and 3.3 versions:
ansible-2.2.0-0.5.prerelease.el7.noarch
openshift-ansible-filter-plugins-3.2.28-1.git.0.5a85fc5.el7.noarch
openshift-ansible-docs-3.2.28-1.git.0.5a85fc5.el7.noarch
openshift-ansible-lookup-plugins-3.2.28-1.git.0.5a85fc5.el7.noarch
openshift-ansible-roles-3.2.28-1.git.0.5a85fc5.el7.noarch
openshift-ansible-3.2.28-1.git.0.5a85fc5.el7.noarch
openshift-ansible-playbooks-3.2.28-1.git.0.5a85fc5.el7.noarch


and:

ansible-2.2.0-0.5.prerelease.el7.noarch
openshift-ansible-lookup-plugins-3.3.22-1.git.0.6c888c2.el7.noarch
openshift-ansible-3.3.22-1.git.0.6c888c2.el7.noarch
openshift-ansible-filter-plugins-3.3.22-1.git.0.6c888c2.el7.noarch
openshift-ansible-roles-3.3.22-1.git.0.6c888c2.el7.noarch
openshift-ansible-docs-3.3.22-1.git.0.6c888c2.el7.noarch
openshift-ansible-playbooks-3.3.22-1.git.0.6c888c2.el7.noarch

**Comment by jprovaznik** [comment]
inventory:
[OSv3:children]
infra
masters
nodes
etcd
[infra]
localhost

[masters]
flannel-puddle33-openshift-master-0.example.com

[etcd]
flannel-puddle33-openshift-master-0.example.com

[nodes]
flannel-puddle33-openshift-master-0.example.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
flannel-puddle33-openshift-node-6jbt26sb.example.com openshift_node_labels="{'region': 'primary', 'zone': 'default'}"

[dns]
localhost

[extradnsitems]
loadbalancer


vars:
[root@flannel-puddle33-infra ansible]# find group_vars/
group_vars/
group_vars/nodes.yml
group_vars/OSv3.yml
group_vars/masters.yml

[root@flannel-puddle33-infra ansible]# cat group_vars/masters.yml 
num_infra: 1
router_vip: 192.168.0.4
openshift_schedulable: true
openshift_master_api_port: 8443
openshift_hosted_router_replicas: 0
[root@flannel-puddle33-infra ansible]# cat group_vars/OSv3.yml 
ansible_first_run: true
infra_instance_id: c886cdb3-7405-4964-9e86-66a39e1d5b5f
ansible_ssh_user: cloud-user
ansible_sudo: true
ansible_become: true
deployment_type: openshift-enterprise # deployment type valid values are origin, online and openshif-enterprise
osm_default_subdomain: cloudapps.example.com # default subdomain to use for exposed routes
openshift_override_hostname_check: true
openshift_use_openshift_sdn: false
openshift_use_flannel: true
openshift_use_dnsmasq: false
flannel_interface: eth1
openshift_master_cluster_hostname: flannel-puddle33-lb.example.com
openshift_master_cluster_public_hostname: flannel-puddle33-lb.example.com
openshift_master_identity_providers:
  - name: htpasswd_auth
    login: true
    challenge: true
    kind: HTPasswdPasswordIdentityProvider
    filename: /etc/origin/openshift-passwd
openshift_cloudprovider_kind: openstack
openshift_cloudprovider_openstack_auth_url: http://10.16.184.104:5000/v2.0
openshift_cloudprovider_openstack_username: admin
openshift_cloudprovider_openstack_password: xxx
openshift_cloudprovider_openstack_tenant_name: xxx
openshift_cloudprovider_openstack_region: RegionOne
openshift_hosted_manage_registry: false
openshift_hosted_manage_router: false
