### ISSUE TITLE
changes to openshift_master_kube_admission_plugin_config in 1.3

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-ansible#2462]
Using an old 1.2 inventory file which had `openshift_master_kube_admission_plugin_config` fails to start the controller. 

It appears to be related to changes in the admission controller https://docs.openshift.org/latest/install_config/master_node_configuration.html

Merging the kube admission config with `openshift_master_admission_plugin_config` resolves this.

**Comment by detiber** [comment]
@andrewklau thanks for catching this! @sdodson, looks like we need to do a migration for kube_admission_plugin_config.

**Comment by sdodson** [comment]
This is https://bugzilla.redhat.com/show_bug.cgi?id=1393645
