### ISSUE TITLE
 nodeName parameter in node.config does not match instance name on openstack

### ISSUE THREAD

**Issue by pradeepnss** [openshift/openshift-ansible#2471]
When trying to implement persistent volume in openshift using dynamic provisioning that use the cluster’s configured cloud provider’s API to create new storage resources we observe that openshift nodes go into "Not Ready" state.

The reason for this is nodeName in the node.config has full hostname which includes the dns domain name. When openshift/kubernetes api contacts the openstack about this nodeName as it does not match the instance name it causes the openshift nodes to fail.

Below is the link that i used to configure openshift to openstack cloud provider:-
https://docs.openshift.com/enterprise/3.2/install_config/configuring_openstack.html#install-config-configuring-openstack

Openshift version: v3.2.1.4-1-g1864c8f
kubernetes : v1.2.0-36-g4a3f9c5
Openstack: red-hat-openstack-platform version 7

When investigated further on the error we observe on the openshift node, i found a bug report https://bugzilla.redhat.com/show_bug.cgi?id=1321964#c3 on the same issue. In the report, it is mentioned that currently the installer does not match the nodeName to the instance name on the openstack and work around is to manually edit the config file.

Discussed this issue with Andrew Butcher and Jason DeTiberus on gitter and based on their suggestion opening up this issue to investigate further on this problem.

**Comment by abutcher** [comment]
@pradeepnss This issue should be addressed by https://github.com/openshift/openshift-ansible/pull/2501. Can you confirm?

**Comment by pradeepnss** [comment]
@abutcher Yes, that pull request should address the issue.

**Comment by sdodson** [comment]
#2501 merged, closing this.
