### ISSUE TITLE
TASK openshift_node : Configure Proxy Settings - Fails

### ISSUE THREAD

**Issue by Pyrokinesis** [openshift/openshift-ansible#2479]
We got this when deploying 2 Master nodes cluster from Ansible into Atomic Hosts.
Even if we define or not proxy cluster vars, it fails. We don't use proxy in our env.

OUTPUT:

```
TASK [openshift_node : Configure Proxy Settings] *******************************
task path: /drake/openshift-ansible/roles/openshift_node/tasks/systemd_units.yml:51
fatal: [master2.demo.<mydomain>.com]: FAILED! => {
    "failed": true, 
    "msg": "'dict object' has no attribute 'http_proxy'"
}

RUNNING HANDLER [openshift_node : restart openvswitch] *************************

RUNNING HANDLER [openshift_node : restart node] ********************************
    to retry, use: --limit @/drake/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP *********************************************************************
localhost                  : ok=12   changed=7    unreachable=0    failed=0   
master1.demo.<mydomain>.com : ok=169  changed=20   unreachable=0    failed=1   
master2.demo.<mydomain>.com : ok=220  changed=41   unreachable=0    failed=1
```

**Comment by tbielawa** [comment]
@Pyrokinesis can you please provide some additional information for us:

* Which operating system are you running this on
* Are you running from RPM or git checkout
  * (if applicable) What `openshift-ansible-*` and `atomic-openshift-utils` package versions are installed (`rpm -qa | grep -E '(openshift-ansible|atomic-openshift)`)
  * (if applicable) What is the hash of your git checkout (`git log -1 | grep commit`)
* Were you using the quick installer (`/usr/bin/atomic-openshift-installer`) or running `ansible-playbook`?
* What command did you run exactly to start the install?
* Can you provide your inventory file for us?

Thanks a lot!

**Comment by jaryn** [comment]
This happens to me as well.

```Red Hat Enterprise Linux Server release 7.2 (Maipo)```
```
openshift-ansible-docs-3.2.35-1.git.0.aeda1a9.el7.noarch
openshift-ansible-roles-3.2.35-1.git.0.aeda1a9.el7.noarch
atomic-openshift-clients-3.2.2.0-1.git.0.4b97cb6.el7.x86_64
atomic-openshift-master-3.2.2.0-1.git.0.4b97cb6.el7.x86_64
tuned-profiles-atomic-openshift-node-3.2.2.0-1.git.0.4b97cb6.el7.x86_64
atomic-openshift-3.2.2.0-1.git.0.4b97cb6.el7.x86_64
openshift-ansible-3.2.35-1.git.0.aeda1a9.el7.noarch
openshift-ansible-filter-plugins-3.2.35-1.git.0.aeda1a9.el7.noarch
openshift-ansible-playbooks-3.2.35-1.git.0.aeda1a9.el7.noarch
atomic-openshift-sdn-ovs-3.2.2.0-1.git.0.4b97cb6.el7.x86_64

openshift-ansible-lookup-plugins-3.2.35-1.git.0.aeda1a9.el7.noarch
atomic-openshift-utils-3.2.35-1.git.0.aeda1a9.el7.noarch
atomic-openshift-node-3.2.2.0-1.git.0.4b97cb6.el7.x86_64
```

```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
deployment_type=openshift-enterprise
ansible_ssh_user=cloud-user
ansible_sudo=true
ansible_sudo_user=root
openshift_use_manageiq=True
#use_cluster_metrics=true

openshift_additional_repos=[{'id': 'ose-devel', 'name': 'ose-devel', 'baseurl': 'http://xxx.redhat.com/rcm-guest/puddles/RHAOS/AtomicOpenShift-errata/3.2/latest/RH7-RHAOS-3.2/x86_64/os/', 'enabled': 1, 'gpgcheck': 0, 'skip_if_unavailable': 1}, {'id':'rhel-extras-candidate','name':'rhel-extras-candidate','baseurl':'http://xxx.redhat.com/brewroot/repos/extras-rhel-7.2-candidate/latest/x86_64/', 'enabled': 1, 'gpgcheck': 0, 'skip_if_unavailable': 1}]
cli_docker_additional_registries=brew-pulp-docker01.xxx.redhat.com:8888
cli_docker_insecure_registries=brew-pulp-docker01.xxx.redhat.com:8888

[masters]
ose3-master-ddg5z openshift_scheduleable=True openshift_hostname=ose3-master-ddg5z openshift_public_hostname=ose3-master-ddg5z

[nodes]
ose3-master-ddg5z openshift_node_labels="{'region':'infra','zone':'default'}" openshift_hostname=ose3-master-ddg5z openshift_public_hostname=ose3-master-ddg5z

ose3-node0-ddg5z openshift_node_labels="{'region':'primary','zone':'east'}" openshift_hostname=ose3-node0-ddg5z openshift_public_hostname=ose3-node0-ddg5z
ose3-node1-ddg5z openshift_node_labels="{'region':'primary','zone':'west'}" openshift_hostname=ose3-node1-ddg5z openshift_public_hostname=ose3-node1-ddg5z
```
```ansible-playbook -b --become-user root -i inventory /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml```

**Comment by jaryn** [comment]
So I tried this playbook
```

---
- hosts: localhost
  vars:
    openshift:
        common:
           some: value
  tasks:
    - name: Configure Proxy Settings
      debug: msg="HTTP_PROXY={{ openshift.common.NOT_A_PROBLEM }}"
      with_items:
        - "{{ openshift.common.THE_PROBLEM }}"
      when: "{{ openshift.common.http_proxy is defined and openshift.common.http_proxy != '' }}"

It fails like so
```
TASK [Configure Proxy Settings] ************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'THE_PROBLEM'"}
```

So the issue is that the ```with_items``` clausule is rendered before the ```when``` clausule is checked

```

**Comment by detiber** [comment]
@jaryn you are correct that `with_items` is evaluated prior to `when`, the `when` is applied for each loop iteration. What version of the playbooks are you using? It looks like in master we are setting defaults for those values, which should prevent the issue.

**Comment by jaryn** [comment]
It was stated above. ```openshift-ansible-playbooks-3.2.35-1.git.0.aeda1a9.el7.noarch```

**Comment by bjpritch** [comment]
I've seen this issue as well running the following via ansible-playbook:

`$ ansible-playbook playbooks/byo/config.yml`

Ansible version below:
`$ ansible --version
ansible 2.2.0.0 (stable-2.2 257182e46a) last updated 2016/10/20 11:12:33 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 730f26d52f) last updated 2016/10/20 13:23:05 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD d51b3d5887) last updated 2016/10/20 13:23:05 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides`

This was also using a version of openshift-ansible from git:

`$ git status
HEAD detached at openshift-ansible-3.2.33-1
nothing to commit, working directory clean`

I can supply my inventory file directly if needed.

**Comment by detiber** [comment]
@sdodson ptal
