### ISSUE TITLE
Origin version 1.3 installation failure

### ISSUE THREAD

**Issue by VivekAwsathi** [openshift/openshift-ansible#2482]
The installation for openshift-origin 1.3 fails because of the unavailability of the 1.3.0 packages in the repository.
Seems like the packages are available in the testing repository, are these going to be made available in the release repository soon or are you planning to enable the testing repo?

**Comment by sdodson** [comment]
Yes, they'll be promoted from testing to the released repos shortly.

**Comment by sdodson** [comment]
Those packages should be pushed into the release repo within the next day. I've just done a quick test install setting this variable and all went well.

openshift_additional_repos=[{'id': 'origin-testing', 'name': 'origin-tesing', 'baseurl': 'http://cbs.centos.org/repos/paas7-openshift-origin-testing/x86_64/os/', 'enabled': 1, 'gpgcheck': 0}]

**Comment by VivekAwsathi** [comment]
Thank-you very much! 
Just out of curiosity, the process to promote from test to release repo is not automated?

**Comment by sdodson** [comment]
It's automated, it's just that centos paas sig is downstream from origin so there's some delay between when origin releases and when the rpms are available in centos paas sig while it's built and tested.

**Comment by minikiller** [comment]
@sdodson  I also want to upgrade, but i don't know where to add this line
```openshift_additional_repos=[{'id': 'origin-testing', 'name': 'origin-tesing', 'baseurl': 'http://cbs.centos.org/repos/paas7-openshift-origin-testing/x86_64/os/', 'enabled': 1, 'gpgcheck': 0}]```
thanks.

**Comment by VivekAwsathi** [comment]
I added this line in the inventory file and that worked for me. I hope that helps.

**Comment by minikiller** [comment]
@VivekAwsathi  it works,thanks

**Comment by VivekAwsathi** [comment]
@sdodson The packages for 1.3.0 have not been promote to the release repo yet... Has there been any problem with the packages? Any idea when are they going to be promoted?
many thanks,

**Comment by sdodson** [comment]
Please see https://lists.centos.org/pipermail/centos-devel/2016-September/015188.html

**Comment by detiber** [comment]
I'm wondering if we need to go ahead and have a flag that would enable the testing repo rather than the release repo.

**Comment by sdodson** [comment]
I think that'd be nice for when we start having v1.4 alpha/rc builds but I think that should be up to the PaaS SIG to decide if testing is the right place for those or if we should rely on a COPR.

**Comment by detiber** [comment]
@sdodson indeed. @tdawson what are your thoughts?

**Comment by tdawson** [comment]
I believe in the future we will be doing this.  It should be part of our testing workflow.  Will it be ready for 1.4, I'm not positive, but they are getting close.

**Comment by sdodson** [comment]
1.3 packages are now in the normal repos, so closing this.
