### ISSUE TITLE
Ansible advanced installation on Fedora 24

### ISSUE THREAD

**Issue by psteyn** [openshift/openshift-ansible#2491]
Please add the following to the readme.

Fedora 24:

dnf -y install python2-dnf PyYAML python-dbus libsemanage-python 

Thanks.  I had to restart the installation at every point of breakage, as the existing readme tells me that I only need to do:

dnf install -y ansible-2.1.0.0 pyOpenSSL python-cryptography

Perhaps even better is to not have ansible break, but rather just install these packages if they are missing?

Thank you

**Comment by kimattree** [comment]
I had the same issue, in addition to this occurring on two installs with a basic Fedora 24 install, with a full dnf -y update.

docker.service not starting on each node, resolved by running:

gem install bundler
sleep 5
systemctl restart docker.service

**Comment by detiber** [comment]
@maxamillion any chance you would have a chance to take a look at adding dependency installation (or know someone else who may) for Fedora installs? I'll volunteer @smunilla to assist if needed.

@kimattree I'm a bit confused why doing a `gem install bundler` would resolve the docker service not starting. I do wonder if you may be hitting a timeout related to docker-storage-setup and the underlying docker storage not being ready before the docker service start times out.  Is there any additional information from `journalctl -u docker -l` to provide more info around the service failure?

**Comment by maxamillion** [comment]
There used to be a note in the README to run the https://github.com/openshift/openshift-ansible/blob/master/playbooks/adhoc/bootstrap-fedora.yml playbook before doing anything else, it's possible we just need to update that and make sure running that is still noted as it used to be.

**Comment by psteyn** [comment]
Good plan. I did not know about the bootstrap playbook until 5 minutes ago.
