### ISSUE TITLE
query on openshift ansible installation 

### ISSUE THREAD

**Issue by priyanka5** [openshift/openshift-ansible#2492]
Hi, I have installed OSE 3.2 using ansible , now we are looking for some customisation. Could you please tell me how ansible works , from where it takes OpenShift source code and where in Ansible soure that location is defined ? so that I can have a look to source and modify it.

Downloaded ansible from here https://github.com/openshift/openshift-ansible

Thanks a lot!

**Comment by sdodson** [comment]
@priyanka5 Please see https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.ose.example#L52-L66 which links to console customization documentation.

**Comment by priyanka5** [comment]
@sdodson thanks , but apart from console we are also looking for customization of openshift-master logs, so that it displays custom fields, is there a way? or I am curious to know how ansible works , from where it takes source code.

**Comment by sdodson** [comment]
No, you cannot do that today as far as I know. If you're aware of documentation for how to customize master logs then let us know and we can consider adding it to ansible. If the customization you're looking for is not available in OSE then please open a support ticket requesting that RFE, if you're not an OSE customer then open an issue in https://github.com/openshift/origin
