### ISSUE TITLE
image push to docker-registry fails

### ISSUE THREAD

**Issue by davebotelho** [openshift/openshift-ansible#2494]
I am trying to do a simple app deployment of a python app using a Dockerfile and source locally.  It seems to run fine up until it needs to push the image up to the internal docker-registry.  I gives me this error below:

Removing intermediate container 51b6cd4beb76
Step 10 : ENV "OPENSHIFT_BUILD_NAME" "python-app-1" "OPENSHIFT_BUILD_NAMESPACE" "default"
 ---> Running in d7332a8557c1
 ---> cc9e693ac6ae
Removing intermediate container d7332a8557c1
Step 11 : LABEL "io.openshift.build.commit.author" " \u003c\u003e"
 ---> Running in b09c04c1921e
 ---> adeb647c7fbc
Removing intermediate container b09c04c1921e
Successfully built adeb647c7fbc
I0921 18:43:32.487774       1 docker.go:118] Pushing image 172.30.124.209:5000/default/python-app:latest ...
E0921 18:47:47.463319       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
E0921 18:52:07.468981       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
E0921 18:56:27.464916       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
E0921 19:00:47.460197       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
E0921 19:05:07.463946       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
E0921 19:09:27.456470       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
E0921 19:13:47.460951       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
F0921 19:13:52.461153       1 builder.go:204] Error: build error: Failed to push image: Put http://172.30.124.209:5000/v1/repositories/default/python-app/: read tcp 10.239.251.18:8000: connection reset by peer
##### Version

[cloud_user@openshift-lab1-master-0 python-app]$ oc version
oc v1.2.1
kubernetes v1.2.0-36-g4a3f9c5

[cloud_user@openshift-lab1-master-0 openshift-ansible]$ git describe
openshift-ansible-3.4.1-1-113-g72d6546

[cloud_user@openshift-lab1-master-0 python-app]$ ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### Steps To Reproduce

[cloud_user@daveos-master-0 python-app]$ oc new-app /home/cloud_user/dockerfiles/python-app --strategy=docker --name=python-app

--> Found Docker image 0416b29 (11 weeks old) from Docker Hub for "gliderlabs/alpine:3.1"

```
* An image stream will be created as "alpine:3.1" that will track the source image
* A Docker build using binary input will be created
  * The resulting image will be pushed to image stream "python-app:latest"
  * Use 'start-build --from-dir=DIR' to trigger a new build
* This image will be deployed in deployment config "python-app"
* Port 5000 will be load balanced by service "python-app"
  * Other containers can access this service through the hostname "python-app"
* WARNING: Image "python-app" runs as the 'root' user which may not be permitted by your cluster administrator
```

--> Creating resources with label app=python-app ...
    error: imagestreams "alpine" already exists
    imagestream "python-app" created
    buildconfig "python-app" created
    deploymentconfig "python-app" created
    service "python-app" created

[cloud_user@daveos-master-0 python-app]$ oc start-build bc/python-app --from-dir=.

Uploading "." at commit "HEAD" as binary input for the build ...
Uploading directory "." as binary input for the build ...
python-app-1
##### Current Result

Successfully installed flask itsdangerous Werkzeug Jinja2 click MarkupSafe
Cleaning up...
 ---> e9bf349c32fb
Removing intermediate container 51b6cd4beb76
Step 10 : ENV "OPENSHIFT_BUILD_NAME" "python-app-1" "OPENSHIFT_BUILD_NAMESPACE" "default"
 ---> Running in d7332a8557c1
 ---> cc9e693ac6ae
Removing intermediate container d7332a8557c1
Step 11 : LABEL "io.openshift.build.commit.author" " \u003c\u003e"
 ---> Running in b09c04c1921e
 ---> adeb647c7fbc
Removing intermediate container b09c04c1921e
Successfully built adeb647c7fbc
I0921 18:43:32.487774       1 docker.go:118] Pushing image 172.30.124.209:5000/default/python-app:latest ...
E0921 18:47:47.463319       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
E0921 18:52:07.468981       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
E0921 18:56:27.464916       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
E0921 19:00:47.460197       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
E0921 19:05:07.463946       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
E0921 19:09:27.456470       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
E0921 19:13:47.460951       1 dockerutil.go:86] push for image 172.30.124.209:5000/default/python-app:latest failed, will retry in 5s ...
F0921 19:13:52.461153       1 builder.go:204] Error: build error: Failed to push image: Put http://172.30.124.209:5000/v1/repositories/default/python-app/: read tcp 10.239.251.18:8000: connection reset by peer
##### Expected Result

SUCCESS :)
##### Additional Information

OS VERSION:
Linux openshift-lab1-master-0.localdomain 3.10.0-327.10.1.el7.x86_64 #1 SMP Sat Jan 23 04:54:55 EST 2016 x86_64 x86_64 x86_64 GNU/Linux

[cloud_user@openshift-lab1-master-0 ~]$ oc get nodes
NAME                            STATUS    AGE
10.236.2.195                    Ready     1d
10.236.2.196                    Ready     1d
master.openshift-lab1.XXXXXXXX   Ready     1d

[cloud_user@openshift-lab1-master-0 ~]$ oc projects default
Now using project "default" on server "https://master.openshift-lab1.XXXXXXX:8443".
[cloud_user@openshift-lab1-master-0 ~]$ oc get pods
NAME                      READY     STATUS    RESTARTS   AGE
docker-registry-2-vbo99   1/1       Running   0          21h
python-app-1-build        0/1       Error     0          21h
router-1-cxqy9            1/1       Running   1          1d

**Comment by sdodson** [comment]
@davebotelho unfortunately you need to add the service ip of your registry to `openshift_no_proxy` variable. It's a bit of a chicken and egg situation that will get resolved in the future when we can push to the registry via dns. For your specific environment, without making any more changes, you should be able to add `openshift_no_proxy=172.30.124.209` and re-run ansible assuming you've not made config file changes that ansible would overwrite. This will add 172.30.124.209 to /etc/sysconfig/docker NO_PROXY variable and restart docker. Things should work after that point.

**Comment by davebotelho** [comment]
I updated manually my /etc/sysconfig/docker files on master and nodes and restarted docker.  I am not able to login to the docker-registry using a token (which I couldn't do before) but I cannot manually push up an image after login. Its giving me an unauthorized error:

[cloud_user@openshift-lab1-master-0 python-app]$ sudo docker push 172.30.124.209:5000/dave/python-app:v1
The push refers to a repository [172.30.124.209:5000/dave/python-app] (len: 1)
1ae2e62621f0: Preparing
unauthorized: authentication required

When I retried my python-app build, it doesn't fail but it just hangs until it times out.

Removing intermediate container 900d536a15b7
Successfully built ec162382d2ba
I0922 18:36:00.190838       1 docker.go:118] Pushing image 172.30.124.209:5000/davetest/python-app:latest ...
F0922 18:51:28.025689       1 builder.go:204] Error: build error: Failed to push image: Post http://172.30.124.209:5000/v2/davetest/python-app/blobs/uploads/: read tcp 172.30.124.209:5000: connection timed out

Before I go and uninstall and reinstall using the openshift_no_proxy variable in my hosts file -- do you think there is anything else missing?

**Comment by sdodson** [comment]
Lets debug the docker service, `oc describe -n default svc/docker-registry`  verify that the IP is still 172.30.124.209 and that it also has at least one endpoint. Can you `curl -v 172.30.124.209:5000` ? if that fails what attempting to reach the endpoint directly from the host where the build happened?

> Before I go and uninstall and reinstall using the openshift_no_proxy variable in my hosts file -- do you think there is anything else missing?

Unfortunately the docker-registry will have a new service ip the next time you build the cluster so if you choose to re-build and use the same openshift_no_proxy value you'll need to make sure to maintain the ip address, this explains how to do that https://docs.openshift.org/latest/install_config/registry/extended_registry_configuration.html#maintaining-the-registry-ip-address

**Comment by davebotelho** [comment]
[cloud_user@openshift-lab1-master-0 python-app]$ oc describe -n default svc/docker-registry
Name:                   docker-registry
Namespace:              default
Labels:                 docker-registry=default
Selector:               docker-registry=default
Type:                   ClusterIP
IP:                     172.30.124.209
Port:                   5000-tcp        5000/TCP
Endpoints:              10.1.0.2:5000
Session Affinity:       ClientIP
No events.

[cloud_user@openshift-lab1-master-0 python-app]$ curl -v 172.30.124.209:5000
* About to connect() to proxy http.proxy.fmr.com port 8000 (#0)
*   Trying 10.239.251.18...
* Connected to http.proxy.fmr.com (10.239.251.18) port 8000 (#0)
> GET HTTP://172.30.124.209:5000/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.30.124.209:5000
> Accept: */*
> Proxy-Connection: Keep-Alive
>

**Comment by davebotelho** [comment]
without curl'ing through the proxy

[cloud_user@openshift-lab1-master-0 python-app]$ curl -v 172.30.124.209:5000
* About to connect() to 172.30.124.209 port 5000 (#0)
*   Trying 172.30.124.209...
* Connected to 172.30.124.209 (172.30.124.209) port 5000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.30.124.209:5000
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Date: Thu, 22 Sep 2016 19:20:58 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 172.30.124.209 left intact

**Comment by sdodson** [comment]
Ok, everything looks fine. Only thing I'd suggest is verifying that the curl command works on the node where the build happened if that wasn't 'openshift-lab1-master-0'. You can describe the build pod to determine which host ran it.

**Comment by davebotelho** [comment]
OK I can curl from each of the nodes and just to be sure that the no_proxy environment variable is set on each of the nodes as well - I updated the /etc/environment and restarted openshift.  When I again attempt to do the start-build, I did notice that the in STEP2 below NO_PROXY does NOT contain the docker-registry IP.  Where is it getting that from?  

I added it into /etc/environment, /etc/sysconfig/docker (and restarted on master and nodes).

Step 1 : FROM gliderlabs/alpine@sha256:1ea49ad7201297e882a64da9aabe10dac1a4665b29811d799d1cd7f1b6e7d450
 ---> e17afe2d7d7b
Step 2 : ENV "HTTP_PROXY" "http://http.proxy.fmr.com:8000" "HTTPS_PROXY" "http://http.proxy.fmr.com:8000" "NO_PROXY" ".cluster.local,10.236.2.195,10.236.2.196,master.openshift-lab1.fmr.com" "http_proxy" "http://http.proxy.fmr.com:8000" "https_proxy" "http://http.proxy.fmr.com:8000" "no_proxy" ".cluster.local,10.236.2.195,10.236.2.196,master.openshift-lab1.fmr.com"
 ---> Using cache
 ---> 0d271e787e81
Step 3 : ENV http_proxy http://http.proxy.fmr.com:8000
 ---> Using cache
 ---> c789536afcbd
Step 4 : ENV https_proxy http://http.proxy.fmr.com:8000
 ---> Using cache
 ---> 9f799b81ed60
Step 5 : EXPOSE 5000
 ---> Using cache
 ---> 11145b0c37e2
Step 6 : CMD python app.py
 ---> Using cache
 ---> b77a7150a9b1
Step 7 : ADD . /code
 ---> Using cache
 ---> 11a68a6d7849
Step 8 : WORKDIR /code
 ---> Using cache
 ---> 627c079aeda7
Step 9 : RUN apk-install python     python-dev     py-pip &&    pip install -r requirements.txt
 ---> Using cache
 ---> 4b504a695428
Step 10 : ENV "OPENSHIFT_BUILD_NAME" "python-app-2" "OPENSHIFT_BUILD_NAMESPACE" "davetest"
 ---> Using cache
 ---> 3a5d4b023287
Step 11 : LABEL "io.openshift.build.commit.author" " \u003c\u003e"
 ---> Using cache
 ---> cab3af0c97fd
Successfully built cab3af0c97fd
I0922 19:44:45.811078       1 docker.go:118] Pushing image 172.30.124.209:5000/davetest/python-app:latest ...

**Comment by davebotelho** [comment]
Is it pulling it from in here?

/etc/ansible/facts.d/openshift.fact:{"node": {"labels": {"region": "primary", "zone": "east"}, "dns_ip": "192.168.0.5", "debug_level": "5", "proxy_mode": "iptables"}, "docker": {"blocked_registries": [], "hosted_registry_network": "172.30.0.0/16", "insecure_registries": [], "hosted_registry_insecure": true, "additional_registries": []}, "common": {"hostname": "10.236.2.196", "https_proxy": "http://http.proxy.fmr.com:8000", "ip": "10.236.2.196", "http_proxy": "http://http.proxy.fmr.com:8000", "is_containerized": false, "public_ip": "10.236.2.196", "debug_level": "5", "generate_no_proxy_hosts": true, "cluster_id": "default", "install_examples": true, **"no_proxy_internal_hostnames": "master.openshift-lab1.fmr.com,10.236.2.196,10.236.2.195",** "public_hostname": "10.236.2.196", "deployment_type": "origin"}, "cloudprovider": {}, "clock": {}}

This is the line from Step2.... it sure reads backwards the same with an appended ".cluster.local"

"NO_PROXY" ".cluster.local,10.236.2.195,10.236.2.196,master.openshift-lab1.fmr.com"

**Comment by sdodson** [comment]
Proxy configuration is pretty complicated and happens at various levels. The values you're seeing in the build logs are from the environment variables injected by the BuildDefaults admission controller defined in /etc/origin/master/master-config.yaml kubernetesMasterConfig.admissionConfig.pluginConfig.BuildDefaults Those environment variables ensure things like maven can interact with external resources via the proxy but they shouldn't matter for the image push. However, just for completeness you can add the docker service ip to the config and restart the master, the next build will pick up those changes.

For the image push, it's the host's docker daemon performing the push so it's the settings in /etc/sysconfig/docker. Given that now that you've updated it no longer shows that it's connecting to your proxy I think that's fine. Can you set BUILD_LOGLEVEL=4 for your build and see if there's anything else showing up in the build logs? https://docs.openshift.com/enterprise/3.2/dev_guide/builds.html#accessing-build-logs

**Comment by davebotelho** [comment]
Ok I've made those changes and loglevel is at 4 for everything.  It stalled out again at push... details below.

[cloud_user@openshift-lab1-master-0 python-app]$ oc logs -f python-app-2-build
I0922 20:22:30.655446       1 builder.go:46] $BUILD env var is {"kind":"Build","apiVersion":"v1","metadata":{"name":"python-app-2","namespace":"davetest","selfLink":"/oapi/v1/namespaces/davetest/builds/python-app-2","uid":"47a371b8-8102-11e6-9054-fa163e9000db","resourceVersion":"54821","creationTimestamp":"2016-09-22T20:22:27Z","labels":{"app":"python-app","buildconfig":"python-app","openshift.io/build-config.name":"python-app"},"annotations":{"openshift.io/build.number":"2"}},"spec":{"serviceAccount":"builder","source":{"type":"Binary","binary":{},"secrets":[]},"strategy":{"type":"Docker","dockerStrategy":{"from":{"kind":"DockerImage","name":"gliderlabs/alpine@sha256:1ea49ad7201297e882a64da9aabe10dac1a4665b29811d799d1cd7f1b6e7d450"},"env":[{"name":"HTTP_PROXY","value":"http://http.proxy.fmr.com:8000"},{"name":"HTTPS_PROXY","value":"http://http.proxy.fmr.com:8000"},{"name":"NO_PROXY","value":".cluster.local,10.236.2.195,10.236.2.196,master.openshift-lab1.fmr.com,172.30.124.209"},{"name":"http_proxy","value":"http://http.proxy.fmr.com:8000"},{"name":"https_proxy","value":"http://http.proxy.fmr.com:8000"},{"name":"no_proxy","value":".cluster.local,10.236.2.195,10.236.2.196,master.openshift-lab1.fmr.com,172.30.124.209"}]}},"output":{"to":{"kind":"DockerImage","name":"172.30.124.209:5000/davetest/python-app:latest"},"pushSecret":{"name":"builder-dockercfg-ybg6k"}},"resources":{},"postCommit":{}},"status":{"phase":"New","outputDockerImageReference":"172.30.124.209:5000/davetest/python-app:latest","config":{"kind":"BuildConfig","namespace":"davetest","name":"python-app"}}}

I0922 20:22:30.661255       1 builder.go:57] Master version "v1.2.1", Builder version "v1.2.1"
I0922 20:22:30.661624       1 builder.go:145] Running build with cgroup limits: api.CGroupLimits{MemoryLimitBytes:92233720368547, CPUShares:2, CPUPeriod:100000, CPUQuota:-1, MemorySwap:92233720368547}
I0922 20:22:30.664406       1 source.go:180] Receiving source from STDIN as archive ...
I0922 20:22:31.085389       1 docker.go:78] Starting Docker build from build config python-app-2 ...
Step 1 : FROM gliderlabs/alpine@sha256:1ea49ad7201297e882a64da9aabe10dac1a4665b29811d799d1cd7f1b6e7d450
 ---> e17afe2d7d7b
Step 2 : ENV "HTTP_PROXY" "http://http.proxy.fmr.com:8000" "HTTPS_PROXY" "http://http.proxy.fmr.com:8000" "NO_PROXY" ".cluster.local,10.236.2.195,10.236.2.196,master.openshift-lab1.fmr.com,172.30.124.209" "http_proxy" "http://http.proxy.fmr.com:8000" "https_proxy" "http://http.proxy.fmr.com:8000" "no_proxy" ".cluster.local,10.236.2.195,10.236.2.196,master.openshift-lab1.fmr.com,172.30.124.209"
 ---> Running in 1d86b3a012f3
 ---> 9951c3ba1e2e
Removing intermediate container 1d86b3a012f3
Step 3 : ENV http_proxy http://http.proxy.fmr.com:8000
 ---> Running in 4c10a0c3ee8d
 ---> c74d29c04f84
Removing intermediate container 4c10a0c3ee8d
Step 4 : ENV https_proxy http://http.proxy.fmr.com:8000
 ---> Running in f05b34c16246
 ---> 48b0d30670e8
Removing intermediate container f05b34c16246
Step 5 : EXPOSE 5000
 ---> Running in 0cecb83e8930
 ---> d233cae5dd01
Removing intermediate container 0cecb83e8930
Step 6 : CMD python app.py
 ---> Running in a8fea2f56e96
 ---> 45803d75d7c9
Removing intermediate container a8fea2f56e96
Step 7 : ADD . /code
 ---> 493eeca4b6bb
Removing intermediate container a3b4061cab1c
Step 8 : WORKDIR /code
 ---> Running in aeae8a719553
 ---> 287d878a4081
Removing intermediate container aeae8a719553
Step 9 : RUN apk-install python     python-dev     py-pip &&    pip install -r requirements.txt
 ---> Running in 17a599860ce0
fetch http://alpine.gliderlabs.com/alpine/v3.1/main/x86_64/APKINDEX.tar.gz
(1/17) Installing libbz2 (1.0.6-r3)
(2/17) Installing expat (2.1.1-r1)
(3/17) Installing libffi (3.0.13-r0)
(4/17) Installing gdbm (1.11-r0)
(5/17) Installing ncurses-terminfo-base (5.9-r3)
(6/17) Installing ncurses-libs (5.9-r3)
(7/17) Installing readline (6.3-r3)
(8/17) Installing sqlite-libs (3.8.10.2-r1)
(9/17) Installing python (2.7.12-r0)
(10/17) Installing python-doc (2.7.12-r0)
(11/17) Installing python-tests (2.7.12-r0)
(12/17) Installing py-gdbm (2.7.12-r0)
(13/17) Installing pkgconf (0.9.7-r0)
(14/17) Installing pkgconfig (0.25-r1)
(15/17) Installing python-dev (2.7.12-r0)
(16/17) Installing py-setuptools (1.1.7-r0)
(17/17) Installing py-pip (1.5.6-r2)
Executing busybox-1.22.1-r15.trigger
OK: 91 MiB in 32 packages
Downloading/unpacking flask (from -r requirements.txt (line 1))
Downloading/unpacking itsdangerous>=0.21 (from flask->-r requirements.txt (line 1))
  Running setup.py (path:/tmp/pip-build-ExMSmm/itsdangerous/setup.py) egg_info for package itsdangerous

    warning: no previously-included files matching '*' found under directory 'docs/_build'
Downloading/unpacking Werkzeug>=0.7 (from flask->-r requirements.txt (line 1))
Downloading/unpacking Jinja2>=2.4 (from flask->-r requirements.txt (line 1))
Downloading/unpacking click>=2.0 (from flask->-r requirements.txt (line 1))
  Running setup.py (path:/tmp/pip-build-ExMSmm/click/setup.py) egg_info for package click

    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
Downloading/unpacking MarkupSafe (from Jinja2>=2.4->flask->-r requirements.txt (line 1))
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip-build-ExMSmm/MarkupSafe/setup.py) egg_info for package MarkupSafe

Installing collected packages: flask, itsdangerous, Werkzeug, Jinja2, click, MarkupSafe
  Running setup.py install for itsdangerous

    warning: no previously-included files matching '*' found under directory 'docs/_build'
  Running setup.py install for click

    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
  Running setup.py install for MarkupSafe

    building 'markupsafe._speedups' extension
    gcc -fno-strict-aliasing -Os -fomit-frame-pointer -DNDEBUG -Os -fomit-frame-pointer -fPIC -I/usr/include/python2.7 -c markupsafe/_speedups.c -o build/temp.linux-x86_64-2.7/markupsafe/_speedups.o
    unable to execute 'gcc': No such file or directory
    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Failure information, if any, is above.
    Retrying the build without the C extension now.


    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Plain-Python installation succeeded.
    ==========================================================================
Successfully installed flask itsdangerous Werkzeug Jinja2 click MarkupSafe
Cleaning up...
 ---> f4bd36acb115
Removing intermediate container 17a599860ce0
Step 10 : ENV "OPENSHIFT_BUILD_NAME" "python-app-2" "OPENSHIFT_BUILD_NAMESPACE" "davetest"
 ---> Running in 70ad1cc6c764
 ---> 6871c65f2273
Removing intermediate container 70ad1cc6c764
Step 11 : LABEL "io.openshift.build.commit.author" " \u003c\u003e"
 ---> Running in a980a9ec7ab9
 ---> 82b67998143f
Removing intermediate container a980a9ec7ab9
Successfully built 82b67998143f
I0922 20:23:41.227724       1 cfg.go:45] Locating docker auth for image 172.30.124.209:5000/davetest/python-app:latest and type PUSH_DOCKERCFG_PATH
I0922 20:23:41.227923       1 cfg.go:83] Using serviceaccount user for Docker authentication for image 172.30.124.209:5000/davetest/python-app:latest
I0922 20:23:41.227936       1 docker.go:116] Authenticating Docker push with user "serviceaccount"
I0922 20:23:41.227955       1 docker.go:118] Pushing image 172.30.124.209:5000/davetest/python-app:latest ...

**Comment by sdodson** [comment]
Sorry, I don't see anything that seems wrong. The only other suggestion I have is to check the logs for your registry pod for errors there or go through network debugging steps we've seen pushes fail when MTU values are wrong, curl works but pushing images fail. See https://docs.openshift.org/latest/admin_guide/sdn_troubleshooting.html

**Comment by davebotelho** [comment]
Ok thanks Scott for your help. I'll keep trying.

**Comment by davebotelho** [comment]
Scott, one more question... if I am logged in as a user "dave" and I am doing the start-build as that user into my project "davetest".... then why is this logfile showing its trying to push the docker image as user serviceaccount.

I0922 20:23:41.227936 1 docker.go:116] Authenticating Docker push with user "serviceaccount"

What does that mean?

**Comment by sdodson** [comment]
Each project has a set of service accounts, it should be using the `builder` service account in the `davetest` project to push the image.

**Comment by lucastheisen** [comment]
I ran into this as well, I think it is the same as this [RedHat issue|https://bugzilla.redhat.com/show_bug.cgi?id=1504464#c1].  Gonna try adding to `openshift_no_proxy`, but would be nice if this was documented in the advanced installation instructions...
