### ISSUE TITLE
no package etcd found advanced installation (seperate etcd host)

### ISSUE THREAD

**Issue by jagadeeshops** [openshift/openshift-ansible#2495]
i tried installing openshift origin in advanced installation mode with 3 masters, 3 etcds and 2 nodes

it failed with error saying "no package etcd found"

i tried to add repos for etcd but not found. it seems to have only tar.gz.

##### Version
rhel 7 - maipo

##### Steps To Reproduce
1. do the advanced installation with multiple masters

##### Additional Information
[The exact command you ran]

operating system  RHEL 7.2
Your inventory file

# Create an OSEv3 group that contains the master, nodes, etcd, and lb groups.
# The lb group lets Ansible configure HAProxy as the load balancing solution.
# Comment lb out if your load balancer is pre-configured.
[OSEv3:children]
masters
nodes
etcd
# lb

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=ec2-user

# If ansible_ssh_user is not root, ansible_sudo must be set to true
ansible_sudo=true

deployment_type=origin

# Uncomment the following to enable htpasswd authentication; defaults to
# DenyAllPasswordIdentityProvider.
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# Native high availbility cluster method with optional load balancer.
# If no lb group is defined installer assumes that a load balancer has
# been preconfigured. For installation the value of
# openshift_master_cluster_hostname must resolve to the load balancer
# or to one or all of the masters defined in the inventory if no load
# balancer is present.
openshift_master_cluster_method=native
openshift_master_cluster_hostname=aws-l9jhoklp.ca.com
openshift_master_cluster_public_hostname=aws-l9jhoklp.ca.com

# apply updated node defaults
openshift_node_kubelet_args={'pods-per-core': ['10'], 'max-pods': ['250'], 'image-gc-high-threshold': ['90'], 'image-gc-low-threshold': ['80']}

# override the default controller lease ttl
#osm_controller_lease_ttl=30

# enable ntp on masters to ensure proper failover
openshift_clock_enabled=true

# host group for masters
[masters]
aws-l9jhoklp.ca.com
aws-b5167037.ca.com
aws-22122a75.ca.com

# host group for etcd
[etcd]
aws-l9jhoklp.ca.com
aws-b5167037.ca.com
aws-22122a75.ca.com

# Specify load balancer host
# [lb]
# lb.example.com

# host group for nodes, includes region info
[nodes]
aws-l9jhoklp.ca.com openshift_node_labels="{'region': 'us-east-1', 'zone': 'us-east-1a', 'type': 'master'}" openshift_schedulable=false
aws-b5167037.ca.com openshift_node_labels="{'region': 'us-east-1', 'zone': 'us-east-1a', 'type': 'master'}" openshift_schedulable=false
aws-22122a75.ca.com openshift_node_labels="{'region': 'us-east-1', 'zone': 'us-east-1a', 'type': 'master'}" openshift_schedulable=false
aws-5226ab5a.ca.com openshift_node_labels="{'region': 'us-east-1', 'zone': 'us-east-1a', 'type': 'node'}"
aws-74524967.ca.com openshift_node_labels="{'region': 'us-east-1', 'zone': 'us-east-1a', 'type': 'node'}"

**Comment by sdodson** [comment]
@jagadeeshops you should be able to enable the extras repos and find the package there. Let us know if that fixes it.

**Comment by detiber** [comment]
@sdodson we probably need to have @tdawson add etcd to the CentOS PaaS SIG repos, similar to docker. We don't want to have a reliance on extras because of version compatibility issues.

**Comment by tdawson** [comment]
Added to my todo list.
We'll see how easy/hard it is to get it in.

**Comment by tdawson** [comment]
@detiber So, I just looked at this.  The version in extras is the same version as in rhel extras.  It was released within 7 days of it being available.  I don't see a version compatibility issue.
I'd like to use the base CentOS packages whenever possible.  If version becomes an issue, we can deal with it then.  Like we had to for docker once.

**Comment by sdodson** [comment]
Closing this then, only need to enable centos-extras channel. We don't currently, outside of rhel_subscribe, manage repos other than the Origin repo so until we change that I don't think there's anything for us to fix.

**Comment by jagadeeshops** [comment]
Thanks @sdodson . I added centos-extras repo. after that it installed propeerly.
I hard coded the release version in base url since its not resolving correctly.
Repo file below:
[extras]
name=CentOS-$releasever - Extras
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras
baseurl=http://mirror.centos.org/centos/7/extras/$basearch/
enabled=1
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5
priority=1

**Comment by sdodson** [comment]
Hmm, I don't think you should have to do that, but i'm glad you got it working.

**Comment by detiber** [comment]
@sdodson I think we should probably consider ensuring it is enabled on CentOS deployments within the openshift_repos role.
