### ISSUE TITLE
Scaleup playbook not updating no_proxy lists

### ISSUE THREAD

**Issue by tremble** [openshift/openshift-ansible#2496]
There are a number of places where no_proxy lists are being autogenerated to include all nodes/routers/masters during scale-up operations these aren't being updated.  As far as I can tell this caused:
https://github.com/openshift/origin/issues/10882

Possibly a duplicate of #1940 

So far I've found the following files which need updating:

Masters:
- /etc/origin/master/master-config.yaml
- /etc/sysconfig/atomic-openshift-master
- /etc/sysconfig/atomic-openshift-master-api
- /etc/sysconfig/atomic-openshift-master-controllers

All Nodes:
- /etc/sysconfig/docker

##### Version
openshift-ansible-3.3.0-1-646-g6bf9b60
ansible 2.2.0

##### Steps To Reproduce
1. stand up cluster including HTTP proxies, where the proxy won't allow port 10250 access
2. Expand the cluster using the scaleup playbook
3. Attempt to access log files for a pod on the new host

##### Current Result
Obscure permission denied errors

##### Expected Result
Logs

**Comment by sdodson** [comment]
Yeah, this is #1940 I think the only critical portion to update is /etc/sysconfig/atomic-openshift-master and /etc/sysconfig/atomic-openshift-master-api  all other components I believe should be fine. You can also work around this if all your hosts, which don't require a proxy, are in a common domain path by adding that like `openshift_no_proxy=.hosts.example.com`
