### ISSUE TITLE
Origin 1.3 container install failed

### ISSUE THREAD

**Issue by vanloswang** [openshift/openshift-ansible#2498]
The content of ~/.config/openshift/installer.cfg.yml is:

``` bash
ansible_callback_facts_yaml: /root/.config/openshift/.ansible/callback_facts.yaml
ansible_config: /usr/share/atomic-openshift-utils/ansible.cfg
ansible_inventory_path: /root/.config/openshift/hosts
ansible_log_path: /tmp/ansible.log
deployment:
  ansible_ssh_user: root
  hosts:
  - connect_to: 192.168.10.22
    containerized: true
    hostname: 192.168.10.22
    ip: 192.168.10.22
    node_labels: '{''region'': ''infra''}'
    public_hostname: 192.168.10.22
    public_ip: 192.168.10.22
    roles:
    - master
    - etcd
    - node
    - storage
  master_routingconfig_subdomain: ''
  roles:
    etcd: {}
    master: {}
    node: {}
    storage: {}
variant: origin
variant_version: '1.3'
version: v2
```

Error log is:

``` bash
TASK [openshift_version : set_fact] ********************************************
ok: [192.168.10.22]

TASK [openshift_version : fail] ************************************************
fatal: [192.168.10.22]: FAILED! => {"changed": false, "failed": true, "msg": "Must specify openshift_release or openshift_image_tag in inventory to install origin. (suggestion: add openshift_release=\"1.2\" to inventory)"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/config.retry

PLAY RECAP *********************************************************************
192.168.10.22              : ok=39   changed=2    unreachable=0    failed=1   
localhost                  : ok=10   changed=9    unreachable=0    failed=0   


An error was detected.  After resolving the problem please relaunch the
installation process.
```

**Comment by abaxo** [comment]
I ran into this issue a few days ago and realised I just hadn't understood the documentation.

I solved it by placing this snippet into the [OSEv3:vars] section of my /etc/ansible/hosts file. The installer is expecting to have a release which matches up to an openshift tag in the container repo, here: https://hub.docker.com/r/openshift/origin/tags/ 

`deployment_type=origin
containerized=true
openshift_release=v1.3.0`

I don't think this is a bug, but it may be worth clarifying in the docs.

**Comment by vanloswang** [comment]
@abaxo openshift-ansible need to generate these config properly, not just docs work. Origin 1.2 does not need additional config in /etc/ansible/hosts. 
@detiber what do yout think about abaxo's suggestion?

**Comment by abaxo** [comment]
@vanloswang - understood, my first experience with Openshift was only in 1.3.

**Comment by detiber** [comment]
@abaxo @vanloswang: I think the tricky part right now is that we use the CentOS PaaS SIG packages for non-containerized installations.

@smunilla what are your thoughts on enabling a different default version for containerized/non-containerized?  Fun part will be when we start consuming CentOS PaaS SIG-built containers by default, where we would then need a way to override to pull the containers generated by an Origin release.

**Comment by smunilla** [comment]
@detiber I'm fine with it for now. I think we need to make our default/displayed versions a little more configurable anyhow.
