### ISSUE TITLE
hosted logging on v1.2

### ISSUE THREAD

**Issue by enoodle** [openshift/openshift-ansible#2517]
When deploying the hosted logging role on Origin v1.2 I get 

```
TASK [openshift_hosted_logging : Process the deployer template] ****************
fatal: [mtayer-centos7-1.eng.lab.tlv.redhat.com]: FAILED! => {"changed": true, "cmd": "oc --config=/tmp/openshift-ansible-pkMqtb/admin.kubeconfig new-app logging-deployer-template -p IMAGE_PREFIX=docker.io/open$
hift/origin- ", "delta": "0:00:00.130579", "end": "2016-09-28 14:45:19.780989", "failed": true, "failed_when_result": true, "rc": 1, "start": "2016-09-28 14:45:19.650410", "stderr": "error: error processing tem$
late logging/logging-deployer-template: Template \"logging-deployer-template\" is invalid: template.parameters[3]: Required value: template.parameters[3]: parameter KIBANA_HOSTNAME is required and must be speci$
ied", "stdout": "", "stdout_lines": [], "warnings": []}
```

As far as I understand this is because the template from `roles/openshift_examples/files/examples/v1.2/infrastructure-templates/enterprise/logging-deployer.yaml` is not using the configmap. I noticed that when I switch the file on the target master with the 1.3 version this role succeeds. I was wondering if there is something we can do here about that to fix it? Is it possible to backport this file?

cc @richm

**Comment by richm** [comment]
@enoodle You have to use the v1.3 template with 1.3 and the v1.2 template with 1.2. I'm not sure what you want to backport.
