### ISSUE TITLE
Configure ntpdate service during etcd node installation 

### ISSUE THREAD

**Issue by ekuric** [openshift/openshift-ansible#2539]
[provide a description of the issue]

installing openshift using openshift-ansible will not configure ntp service on etcd nodes 
##### Version

ansible 2.2.0
##### Steps To Reproduce
1. Install OpenShift using openshift-ansible 
2. after installation ntpdate service will not be started
##### Current Result

ntpdate service not started on etcd nodes 
##### Expected Result

nptdate service to be configured and started during etcd node installation 
##### Additional Information

On etcd servers, below error message will be visible in logs which will disappear once `ntpdate` service is configured.It could help if there is option to add in playbook as for example 
`ntpserver` or similar which will then configure ntpdate and start it during etcd node installation using openshift-ansible 

```
Oct  3 10:04:49 dhcp5-215 etcd: the clock difference against peer 5a9c045751aa4dcf is too high [1.449674737s > 1s]
Oct  3 10:05:19 dhcp5-215 etcd: the clock difference against peer 5a9c045751aa4dcf is too high [1.449190648s > 1s]
Oct  3 10:05:49 dhcp5-215 etcd: the clock difference against peer 5a9c045751aa4dcf is too high [1.448797576s > 1s]
Oct  3 10:06:19 dhcp5-215 etcd: the clock difference against peer 5a9c045751aa4dcf is too high [1.448390938s > 1s]
Oct  3 10:06:49 dhcp5-215 etcd: the clock difference against peer 5a9c045751aa4dcf is too high [1.447876292s > 1s]
```

**Comment by sdodson** [comment]
Debugging this in https://bugzilla.redhat.com/show_bug.cgi?id=1370229

**Comment by sdodson** [comment]
Actually, your situation is different than that bug.

On your hosts chrony was installed already and as such ansible simply enables ntp using `timedatectl set-ntp true`. However, the host cannot reach its configured ntp servers.

```
# grep server /etc/chrony.conf 
# Use public servers from the pool.ntp.org project.
server 0.rhel.pool.ntp.org iburst
server 1.rhel.pool.ntp.org iburst
server 2.rhel.pool.ntp.org iburst
server 3.rhel.pool.ntp.org iburst

#nmap -p 123 0.rhel.pool.ntp.org
Starting Nmap 6.40 ( http://nmap.org ) at 2016-10-03 12:12 EDT
Nmap scan report for 0.rhel.pool.ntp.org (204.11.201.12)
Host is up (0.014s latency).
rDNS record for 204.11.201.12: mis.wci.com
PORT    STATE    SERVICE
123/tcp filtered ntp
Nmap done: 1 IP address (1 host up) scanned in 5.56 seconds
```

Now, when you installed ntp, for some reason it got a different set of ntp servers from dhclient-scripts and those work. So, I'm not sure what we should do here.

**Comment by jeremyeder** [comment]
Hmm, I think this is because Corp IT has a while ago disabled access from labs to external NTP servers.  DHCP probably handed out the correct hostname for the internal NTP servers.
