### ISSUE TITLE
master metrics url is set when metrics are disabled

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-ansible#2543]
Not sure if this is intended behaviour, when metrics deployment is not enabled, the metrics url is still set in the master config. 

This will end up with a bunch of errors in the javascript console, harmless but perhaps avoidable..

**Comment by detiber** [comment]
@smunilla I would only expect the metrics URL to be set if the user defines the variable or they are deploying metrics and get a default metrics URL, otherwise I would expect it to remain unset to avoid the console errors.
