### ISSUE TITLE
"openshift_use_dnsmasq: true" doesn't work as expected

### ISSUE THREAD

**Issue by jprovaznik** [openshift/openshift-ansible#2547]
[provide a description of the issue]
openshift_use_dnsmasq default value is "true", if this variable is left unset then openshift_node_dnsmasq role is executed as expected. If this variable is explicitly set to "true", then openshift_node_dnsmasq is skipped as it was set to false.

##### Version
either master branch (openshift-ansible-3.4.3-1) or current 3.2 stable branch 
ansible-2.2.0-0.5.prerelease.el7.noarch

##### Steps To Reproduce
deploy BYO with openshift_use_dnsmasq: true

##### Current Result
tasks in openshift_node_dnsmasq are skipped

##### Expected Result
tasks in openshift_node_dnsmasq are executed

**Comment by jhcook** [comment]
I'm a bit puzzled by this one. I do not use openshift_use_dnsmasq at all and my clusters are coming up san dnsmasq. This cost me a bit of time trying to figure out the delay in outbound connections from containers. I manually did this, but the issue sporadically showed up after a cluster deployment from last month update at the end of September. It was working fine, then a yum update hosed it.  

Clearly, that part has nothing to do with Ansible, but it's not enabling dnsmasq as one would think.
