### ISSUE TITLE
OpenShift ansible ignores openshift_ip variable

### ISSUE THREAD

**Issue by david-strejc** [openshift/openshift-ansible#2559]
I've configured hosts file as follows:

```
# host group for nodes, includes region info
[nodes]
192.168.50.11 openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_ip=192.168.50.11 openshift_public_ip=192.168.50.11
192.168.50.12 openshift_node_labels="{'region': 'primary', 'zone': 'east'}" openshift_ip=192.168.50.12 openshift_public_ip=192.168.50.12
192.168.50.13 openshift_node_labels="{'region': 'primary', 'zone': 'west'}" openshift_ip=192.168.50.13 openshift_public_ip=192.168.50.13
```

But Open Shift Origin is still trying to bind to eth0 routable interface (I am working with Vagrant and VirtualBox instances of VMs).

Any idea?

**Comment by abutcher** [comment]
Hey @david-strejc do you have similar `openshift_ip` `openshift_public_ip` set for master hosts in the inventory?

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.

**Comment by bradynathan** [comment]
I have a similar issue, because I am trying to set up a backnet for node communication.  It appears that that the ectd configuration is ignoring the openshift_ip.  My logs show that the origin-master-api is trying to connect on the public interface.
