### ISSUE TITLE
OpenShift Node : dnsIP invalid value on openstack

### ISSUE THREAD

**Issue by talset** [openshift/openshift-ansible#257]
A bug in openstack nova api break the node-config.yaml. (fixed in kilo https://bugs.launchpad.net/nova/+bug/1334857)

-  Bug : 
```bash
curl  http://169.254.169.254/latest/meta-data/local-ipv4/ -> 192.168.0.36,198.154.x.y
```
instead of 
```bash
curl  http://169.254.169.254/latest/meta-data/local-ipv4/ -> 192.168.0.36
```

- Problem :

In openshift-node beta-3 config it is expected to have only one address.
```bash
/etc/openshift/node/node-config.yaml
dnsIP: 192.168.0.36,198.154.x.y
```

```bash
openshift-node[21753]: dnsIP: invalid value '192.168.0.36,198.154.x.y': must be a valid IP
```

**Comment by detiber** [comment]
@twiest this can be closed now that https://github.com/openshift/openshift-ansible/issues/266 is merged.

**Comment by twiest** [comment]
Closing.
