### ISSUE TITLE
router-certs not created by Ansible for 1.3 deployment on centos.

### ISSUE THREAD

**Issue by jmlambert78** [openshift/openshift-ansible#2580]
I deploy origin 1.3 on centos. After the ansible is run, the registry runs, but not the router
The router deploy is in error, and that generates some error on secrets mount.
After invesstigation it lacks router-certs in the default secrets set.
To fix i created a new secret router-certs and added the crt & key of the openshift-router;kubeconfig file... then oc create -f router-certs.yaml, then redeploy
Seen with  @mangirdaz 
##### Version

[if you're operating from a git clone provide the output of `git describe`]

openshift-ansible-3.2.32-1

[if you're running from playbooks installed via RPM or atomic-openshift-utils `rpm -q atomic-openshift-utils openshift-ansible`]
[Your version of ansible, `ansible --version`]
##### Steps To Reproduce

Install the playbook of ansible
Login to the target machine, check the pods in the defualt namespace, then the deploy will be broken
if you have the chance to see the old 
##### Current Result

The deploy breaks 
##### Expected Result

Router should just be deployed correctly...
##### Additional Information

[The exact command you ran]
[Your operating system and version, ie: RHEL 7.2, Fedora 23]
Centos7.2
[Your inventory file]
# Create an OSEv3 group that contains the masters and nodes groups

[OSEv3:children]
masters
nodes
# new_nodes
# Set variables common for all OSEv3 hosts

[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password

ansible_ssh_user=root
# ansible_ssh_pass=

osm_default_subdomain=139.59.157.21.xip.io
containerized=true
# If ansible_ssh_user is not root, ansible_sudo must be set to true
# ansible_sudo=true

deployment_type=origin
openshift_release=v1.3.0
docker_upgrade=false
# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/htpasswd'}]
# host group for masters

[masters]
139.59.157.21
# host group for nodes, includes region info[nodes]

[nodes]
139.59.157.21 openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true

[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by detiber** [comment]
@jmlambert78 I suspect you need a newer version of the Ansible roles. You can try using the latest build from koji (https://cbs.centos.org/koji/buildinfo?buildID=12476) or if that does not work, I would suggest removing the packages and installing directly from the release-1.3 branch.

@tdawson This issue appears to be the installer packages being out of date in the released repo.
