### ISSUE TITLE
Ansible Playbook - ImportError: No module named parsing.yaml.dumper

### ISSUE THREAD

**Issue by Shyckymn** [openshift/openshift-ansible#2585]
Trying to run an Openshift advanced installation with ansible.

When I execute the command line, the system returns the following errors. Any suggestion?

```
# ansible-playbook /tmp/openshift-ansible/playbooks/byo/config.yml
Traceback (most recent call last):
  File "/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 194, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 681, in _load_tasks
    role_name=role_name
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 255, in __init__
    self.async_seconds = template.template_from_string(play.basedir, self.async_seconds, all_vars)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 346, in template_from_string
    environment.filters.update(_get_filters())
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 54, in _get_filters
    plugins = [ x for x in utils.plugins.filter_loader.all()]
  File "/usr/lib/python2.7/site-packages/ansible/utils/plugins.py", line 232, in all
    self._module_cache[path] = imp.load_source('.'.join([self.package, name]), path)
  File "/tmp/openshift-ansible/filter_plugins/oo_filters.py", line 20, in <module>
    from ansible.parsing.yaml.dumper import AnsibleDumper
ImportError: No module named parsing.yaml.dumper
```

##### Version
```
# git describe
openshift-ansible-3.4.6-1-9-g131bcdc
```
```
# ansible --version
ansible 1.9.4
  configured module search path = None
```

##### Additional Information
```
# uname -ar
Linux pxl0dockr009 3.10.0-327.28.3.el7.x86_64 #1 SMP Fri Aug 12 13:21:05 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
[root@pxl0dockr009 byo]# cat /etc/*rele*
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
```

**Comment by tbielawa** [comment]
> from ansible.parsing.yaml.dumper import AnsibleDumper
>ImportError: No module named parsing.yaml.dumper

It may be such that that module did not became available until one of the Ansible releases in the 2.x series. I'm going to try and double check that now.

**Comment by tbielawa** [comment]
@Shyckymn I just did some downgrades and upgrades and collected the file list results.

With **ansible-1.9.3-2.fc23.noarch** the specified module does not exist

With **ansible-2.1.2.0-1.fc23.noarch** the specified module does exist
* `/usr/lib/python2.7/site-packages/ansible/parsing/yaml/dumper.py`

And using the pre-release 2.2 version **ansible-2.2.0-0.50.prerelease.fc23.noarch** the same file also exists.

I suggest you upgrade your ansible version to at least 2.1.x @Shyckymn and try again.

**Comment by Shyckymn** [comment]
@tbielawa Thanks for your help. I updated the version of the ansible and now the scenario has changed.

Now I have a new error:

```
TASK [openshift_version : fail] ************************************************
fatal: [pxl0dockr009]: FAILED! => {"changed": false, "failed": true, "msg": "No OpenShift version available, please ensure your systems are fully registered and have access to appropriate yum repositories."}
```

Does the advanced installation needs any subscrption or something lihe that?

**Comment by Shyckymn** [comment]
@tbielawa If I create a router to meet the installation of one Private Registry and then I want to install the collection of Metrics/Heapster, do I have to create a new router or use that was already created for the Private Registry?
Perhaps this is the root cause of my problem ...

**Comment by tbielawa** [comment]
@Shyckymn Well if you're trying to install OpenShift Container Platform you'll need a subscription. IIRC, if you're installing OpenShift Origin (i.e., usually CentOS) then I don't believe you need a subscription.

**Comment by tbielawa** [comment]
@Shyckymn I'm not sure about the answer to your private registry question. Maybe @detiber or @abutcher will know.

**Comment by Shyckymn** [comment]
Sorry... I posted an reply to wrong forum topic...

**Comment by abutcher** [comment]
Hey @Shyckymn, one router is sufficient for the cluster.

**Comment by Shyckymn** [comment]
The error with ansible has been solved. But I'm having trouble with nodes. 
I'll open another issue. 
Thanks for your attention.
