### ISSUE TITLE
Unable to login to web console after Multi Master Cluster Installation

### ISSUE THREAD

**Issue by VRspace4** [openshift/openshift-ansible#2591]
I'm able to login using `oc login` with any username and password. However, when I attempt to log into the web console from two of the three masters, I get the following message:

> Error
> An error has occurred
> Return to the console.

This is what Chrome Developer Tools' Console reads:

> [vendor.js:5012]
 > GET https://192.168.41.140:8443/oapi/v1/users/~ 401 (Unauthorized)

`/etc/ansible/hosts` content

> [OSEv3:children]
> masters
> nodes
> etcd
> lb
> 
> [OSEv3:vars]
> ansible_ssh_user=root
> deployment_type=origin
> openshift_master_cluster_method=native
> 
> [masters]
> node1.dprm
> node2.dprm
> node3.dprm
> 
> [etcd]
> node1.dprm
> node2.dprm
> node3.dprm
> 
> [lb]
> loadbalancer.dprm
> 
> [nodes]
> node1.dprm openshift_node_labels="{'name': 'Node1'}"
> node2.dprm openshift_node_labels="{'name': 'Node2'}"
> node3.dprm openshift_node_labels="{'name': 'Node3'}"
> 

##### Version
[if you're operating from a git clone provide the output of `git describe`]
**openshift-ansible-3.4.6-1-12-ge30fdf9**

[Your version of ansible, `ansible --version`]
**ansible 2.1.1.0**

##### Steps To Reproduce
1. Installed Multiple Masters Cluster from [Advanced Installation](https://docs.openshift.org/latest/install_config/install/advanced_install.html)
2. Attempt to login to the web console

##### Current Result
> Error
> An error has occurred
> Return to the console.

##### Expected Result
Access to Openshift Origin web console

##### Additional Information
CentOS Linux release 7.2.1511 (Core) for all virtual machines

**Comment by VRspace4** [comment]
I restarted the two VMs and now I can login. Closing issue.

**Comment by khodayard** [comment]
Same situation with OKD 3.11 on 17 VMs (3 masters)
Fixed with reboot
