### ISSUE TITLE
Trying to map proper hostvars using openstack dynamic inventory.. need a little help.

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-ansible#2609]
Attempting to run the installer populated from a dynamic inventory. Trying to figure out what additional hostvars need mapped. At this point i'm having issues during the etcd cert copy, as directories are being created with IP addresses rather than hostnames.

##### Version

```
$ git describe
openshift-ansible-3.4.8-1-13-g9fa3c6c

# ansible --version
ansible 2.2.0
  config file = /root/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Current Result
```
TASK [etcd_server_certificates : Sign and create the server crt] ***************
fatal: [master-0.test-stack.casl.rht-labs.com -> None]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_yiEc70/ansible_module_delegated_serial_command.py\", line 275, in <module>\r\n    main()\r\n  File \"/tmp/ansible_yiEc70/ansible_module_delegated_serial_command.py\", line 206, in main\r\n    os.chdir(chdir)\r\nOSError: [Errno 2] No such file or directory: '/etc/etcd/generated_certs/etcd-192.168.99.6'\r\n", "msg": "MODULE FAILURE"}
        to retry, use: --limit @./repository/casl-ansible/playbooks/openshift/install.retry
```

##### Expected Result
Install finishes successfully

##### Additional Information
```
ansible-playbook -i ./repository/casl-ansible/inventory/provision-openstack-sample/ ./repository/casl-ansible/playbooks/openshift/install.yaml -e 'openshift_ansible_path=/root/repository/openshift-ansible'
```

Copy of playbook is here: https://github.com/etsauer/casl-ansible/tree/openstack-heat/playbooks/openshift

Using a dynamic/static hybrid inventory to pull host info from OpenStack. Inventory sample looks like:
https://github.com/etsauer/casl-ansible/tree/openstack-heat/inventory/provision-openstack-sample

@sdodson @abutcher

**Comment by detiber** [comment]
@etsauer you probably want to set openshift_hostname and openshift_public_hostname for each of the hosts.
