### ISSUE TITLE
Trying a Single Master with Two Nodes install - Only master appears at "oc nodes" execution...

### ISSUE THREAD

**Issue by Shyckymn** [openshift/openshift-ansible#2610]
I've ran the ansible playbook several times but the nodes are still not showing up.

I'm using the "Single Master Example" from the Advanced Installation method:
https://docs.openshift.org/latest/install_config/install/advanced_install.html

```
[root@pxl0dockr009 ~]# docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
docker.io/openshift/origin-metrics-deployer   latest              227793577d16        11 days ago         653.5 MB
docker.io/openshift/node                      v1.3.0              8a75a9a467e5        4 weeks ago         579.5 MB
docker.io/openshift/origin                    v1.3.0              7b24611e640f        4 weeks ago         487.1 MB
docker.io/openshift/openvswitch               v1.3.0              ae9b91b329c3        4 weeks ago         303.7 MB
docker.io/openshift/origin-pod                v1.3.0              35873f68181d        4 weeks ago         1.591 MB

[root@pxl0dockr010 ~]# docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
docker.io/openshift/origin-metrics-deployer   latest              227793577d16        11 days ago         653.5 MB
docker.io/openshift/node                      v1.3.0              8a75a9a467e5        4 weeks ago         579.5 MB
docker.io/openshift/openvswitch               v1.3.0              ae9b91b329c3        4 weeks ago         303.7 MB
docker.io/openshift/origin-pod                v1.3.0              35873f68181d        4 weeks ago         1.591 MB

[root@pxl0dockr011 ~]# docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
docker.io/openshift/origin-metrics-deployer   latest              227793577d16        11 days ago         653.5 MB
docker.io/openshift/node                      v1.3.0              8a75a9a467e5        4 weeks ago         579.5 MB
docker.io/openshift/openvswitch               v1.3.0              ae9b91b329c3        4 weeks ago         303.7 MB
docker.io/openshift/origin-pod                v1.3.0              35873f68181d        4 weeks ago         1.591 MB
```

```
# cat /etc/ansible/hosts
# This is the default ansible 'hosts' file.
#
# It should live in /etc/ansible/hosts
#
#   - Comments begin with the '#' character
#   - Blank lines are ignored
#   - Groups of hosts are delimited by [header] elements
#   - You can enter hostnames or ip addresses
#   - A hostname/ip can be a member of multiple groups

# Ex 1: Ungrouped hosts, specify before any group headers.

# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# Proxy Configuration
openshift_no_proxy=172.30.200.19,192.168.*.*,10.8.7.*,kubernetes.*,docker-registry.default.svc.cluster.local

# Configuring Cluster Metrics
openshift_hosted_metrics_deploy=true

# Metrics Storage - Dynamic Volume Provisioning
openshift_hosted_metrics_storage_kind=dynamic

# Openshift Release
openshift_release=1.3.0

# Installation Mode
containerized=true

# Openshift Hostname
openshift_hostname=pxl0dockr009

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become=true

deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# host group for masters
[masters]
pxl0dockr009

# host group for nodes, includes region info
[nodes]
pxl0dockr009 openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
pxl0dockr010 openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
pxl0dockr011 openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
```
##### Version

```
# docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.14.x86_64
 Go version:      go1.6.2
 Git commit:      5206701-unsupported
 Built:           Mon Aug 29 14:00:01 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.14.x86_64
 Go version:      go1.6.2
 Git commit:      5206701-unsupported
 Built:           Mon Aug 29 14:00:01 2016
 OS/Arch:         linux/amd64
```

```
# ansible --version
ansible 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```

**Comment by detiber** [comment]
@Shyckymn was there an error when running the playbook?

One thing that stands out is that you are setting `openshift_hostname` under `[OSEv3:vars]`, which will set it for all hosts. You will want to set it for each of the hosts defined, currently all nodes will be setting their nodeName to `pxl0dockr009`

**Comment by Shyckymn** [comment]
@detiber I'll try to install the Master and Node on the same server and, after that, if it works, I'll try to add another node.
What is the correct section in what I must set my openshift_hostname for the first scenario?

**Comment by detiber** [comment]
@Shyckymn if only one host is in use, then you can set it anywhere. If multiple hosts are in-use, I would suggest setting it inline with the host definition, similar to openshift_node_labels

**Comment by Shyckymn** [comment]
@detiber Thanks for you help! Now I got Hawkular/Metrics working. 

But when i try to implement the HPA mechanism, my events are showing the following error:

`failed to get CPU utilization: failed to get CPU consumption and request: failed to unmarshall heapster response: json: cannot unmarshal object into Go value of type []v1alpha1.PodMetrics `

`failed to get CPU consumption and request: failed to unmarshall heapster response: json: cannot unmarshal object into Go value of type []v1alpha1.PodMetrics`

Do you have any idea what might be happening?

**Comment by detiber** [comment]
@jcantrill anything you can offer?

**Comment by jcantrill** [comment]
I would suggest reading: https://github.com/openshift/origin-metrics#verifying-the-components-after-installation  Additionally, the oadm binary provides diagnostic checks which may be of use to you to check the cluster in general.  It also specifically has diagnostics for metrics.  @mwringe do you have any additional input?

**Comment by mwringe** [comment]
@Shyckymn I would suspect the issue with the HPA is because of security problems accessing the Heapster endpoint.

Assuming of course that the metrics deployer exited with something other than an error code. The checks are now built into the deployer directly. 

If the metrics components all deployed properly and you can see metric graphs in the console, then the metric components should be installed properly.

A couple of things to check with the HPA, please make sure the metric components are installed to the 'openshift-infra' project, if its installed anywhere else the HPA wont be able to find it. Can you access Heapster via the API proxy?

[eg curl -k -H "Authorization: Bearer `oc whoami -t`" -X GET https://localhost:8443/api/v1/proxy/namespaces/openshift-infra/services/https:heapster:/api/v1/model/metrics]

@DirectXMan12 any ideas?

**Comment by DirectXMan12** [comment]
> failed to get CPU utilization: failed to get CPU consumption and request: failed to unmarshall heapster response: json: cannot unmarshal object into Go value of type []v1alpha1.PodMetrics

That generally means you're running the wrong version of Heapster for your version of OpenShift/Kubernetes.  I see you're running the latest metric deployer.  Can you run the version that matches your OpenShift version?

**Comment by mwringe** [comment]
@DirectXMan12 what version of Heapster does the current HPA support then?

**Comment by DirectXMan12** [comment]
Origin 1.3 should work with the copy of Heapster tagged for 1.3, IIRC.  The newest versions of Heapster will only work with Kube 1.4+, IIRC.

**Comment by wookie41** [comment]
@Shyckymn Have you managed to fix the issue? If yes, what was causing it?
