### ISSUE TITLE
[RFE] Deploy Heketi/Gluster storage during installation

### ISSUE THREAD

**Issue by lpabon** [openshift/openshift-ansible#2614]
Deploy Heketi and Gluster containers during installation so that the administrator can use Gluster storage for their infrastructure.  This could include, but not limited to, storage for applications or storage for docker container images.

Reference: https://github.com/heketi/heketi/issues/451

**Comment by erinboyd** [comment]
@brenton Here is the CNS (Containerized Gluster) for the registry

**Comment by dustymabe** [comment]
I think this can be closed now? https://docs.openshift.org/latest/install_config/install/advanced_install.html#advanced-install-glusterfs-persistent-storage
