### ISSUE TITLE
Installation with user having his home directory on an NFS share with root_squash

### ISSUE THREAD

**Issue by fgiloux** [openshift/openshift-ansible#2619]
The installation fails when the directory of the user used by ansible is on an NFS share configured with root_squash. It is possible to work around the first issues by setting remote_tmp = /tmp/.ansible in ansible.cfg. Unfortunately it still fails a bit later down the play book, when ansible tries to create .kube in the user home directory using sudo.
##### Version

Ansible 2.2
OpenShift 3.3.28
atomic-openshift-utils-3.3.28-1.git-0.762256b.el7.noach
openshift-ansible-3.3.28-1.git.0.762256b.el7.noarch
##### Steps To Reproduce
1. Create a user for ansible installation with his home directory on an NFS share configured with root_squash
2. Run ansible installation: ansible-playbook -i ocp-hosts-sandpit /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
##### Current Result

Error creating .kube
##### Expected Result

Run further. Files created in home directory should not be created with sudo.
##### Additional Information

RHEL 7.2

**Comment by detiber** [comment]
@fgiloux this is tricky, since the other actions in that role require root privileges.  A simple resolution would be to just skip the creation of the default kubeconfig for the ssh user, and creating it for the root user only.

**Comment by fgiloux** [comment]
@detiber it makes sense. A warning and going on with the playbook should be fine. Lots of companies use a dedicated ansible user for running the playbook that won't be used for accessing OpenShift.
