### ISSUE TITLE
Pods are not being balanced between nodes within a cluster

### ISSUE THREAD

**Issue by Shyckymn** [openshift/openshift-ansible#2628]
I have one Openshift Cluster with one host acting as master/node and another host acting as node:

```
# oc get nodes
NAME                                  STATUS    AGE
pxl0dockr009   Ready     4h
pxl0dockr010   Ready     2h
```

When I scale up my app, the pods are not being balanced between the hosts.
How the Openshift environment works with the pods balancing?
What is the criteria?

```
# oc get pods -o wide
NAME            READY     STATUS    RESTARTS   AGE       IP          NODE
nginx-3-0r7re   0/1       Pending   0          32s       <none>
nginx-3-5drmx   1/1       Running   0          32s       10.1.0.12   pxl0dockr009
nginx-3-6a0nh   1/1       Running   0          32s       10.1.0.15   pxl0dockr009
nginx-3-9cloj   1/1       Running   0          32s       10.1.0.13   pxl0dockr009
nginx-3-ftfqs   1/1       Running   0          1h        10.1.0.8    pxl0dockr009
nginx-3-kz0nz   1/1       Running   0          32s       10.1.0.9    pxl0dockr009
nginx-3-mm5qa   1/1       Running   0          32s       10.1.0.7    pxl0dockr009
nginx-3-oqwlr   1/1       Running   0          32s       10.1.0.11   pxl0dockr009
nginx-3-sebct   1/1       Running   0          32s       10.1.0.10   pxl0dockr009
nginx-3-tal45   1/1       Running   0          32s       10.1.0.14   pxl0dockr009
```

##### Version
```
# oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://pxl0dockr009.dispositivos.bb.com.br:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
```

**Comment by detiber** [comment]
@Shyckymn what are the node labels? Is there a default project node selector, a node selector set on the project, or a selector set on the DeploymentController/ReplicationController?

`oc get nodes --show-labels` will show node labels

For default project node selector is defined in `/etc/origin/master/master-config.yaml` with the `projectConfig.defaultNodeSelector` key

For project node selector you can run:
```
oc get namespace -o yaml <namespace> | grep selector
```

For DC/RC selector you can scan the output of the following looking for nodeSelector:
```
oc get dc <dc_name> -o yaml
oc get rc <rc_name> -o yaml
```

**Comment by Shyckymn** [comment]
@detiber Thanks for your attention! I understood the mechanism.
I installed a new node in my environment to test the balancing of pods.
The first node has answered for its hostname, but the second got the IP address instead of the hostname:

```
# oc get nodes
NAME                                  STATUS    AGE
10.8.7.222                            Ready     1m
pxl0dockr009                        Ready     21h
pxl0dockr010                        Ready     17h
```

So, I edited the file `/etc/origin/node/node-config.yaml` in the second node (10.8.7.222) and changed the `nodeName:` parameter to have the hostname of the second node and after that I restarted the origin-node service.

After that, the second node has been registered at the master server successfully, but the master still got the first node registration with the incorrect name. So, I ran `oc delete node 10.8.7.222`.
The problem is that, after the node deletion, the second node doesn't reach the Registry from the master. Before the deletion of "10.8.7.222", the telnet in the IP:Port of the Registry works. After the deletion, the telnet doesn't work anymore and the node was not able to pull the images from the master.

I don't know what I have to do in the node installation to have the name of the node correctly configured.

I'm using the `ansible-playbook -i /etc/ansible/hosts.new_hosts /tmp/openshift-ansible/playbooks/byo/openshift-node/scaleup.yml` command line and my Ansible inventory file has the following contents:

```
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
new_nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root
# Openshift Release
openshift_release=1.3.0
# Debug level for all OpenShift components (Defaults to 2)
debug_level=4
# Installation Mode
containerized=true
# Deployment Type
deployment_type=origin

# host group for masters
[masters]
pxl0dockr009

# host group for nodes, includes region info
[nodes]
pxl0dockr009 openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
pxl0dockr010 openshift_node_labels="{'region': 'primary', 'zone': 'east'}"

[new_nodes]
pxl0dockr011 openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
```

**Comment by detiber** [comment]
You'll probably want something like this:

> [nodes]
> pxl0dockr009 openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_hostname=pxl0dockr009
> pxl0dockr010 openshift_node_labels="{'region': 'primary', 'zone': 'east'}"  openshift_hostname=pxl0dockr010

> [new_nodes]
> pxl0dockr011 openshift_node_labels="{'region': 'primary', 'zone': 'west'}" openshift_hostname=pxl0dockr011

**Comment by Shyckymn** [comment]
It doesn't work:

`ansible-playbook -i /etc/ansible/hosts.new_hosts /opt/openshift-ansible/playbooks/byo/openshift-node/scaleup.yml
`

`fatal: [pxl0dockr009]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'openshift'\n\nThe error appears to have been in '/opt/openshift-ansible/roles/openshift_manage_node/tasks/main.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Wait for Node Registration\n  ^ here\n"}`

```
# Create an OSEv3 group that contains the masters and nodes groups

[OSEv3:children]
masters
nodes
new_nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root
# Openshift Release
openshift_release=1.3.0
# Installation Mode
containerized=true
# Deployment Type
deployment_type=origin

# host group for masters
[masters]
pxl0dockr009

# host group for nodes, includes region info
[nodes]
pxl0dockr009

[new_nodes]
pxl0dockr010 openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
openshift_hostname=pxl0dockr010
```

**Comment by Shyckymn** [comment]
Solved after put the `openshift_hostname` parameter in the same line, after `openshift_node_labels`.
