### ISSUE TITLE
MODULE FAILURE in Masters

### ISSUE THREAD

**Issue by J0hnson** [openshift/openshift-ansible#2633]
[root@ansible byo]# ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/openshift-ansible/library']

[root@ansible byo]# cat ./hosts

```
# Create an OSEv3 group that contains the master, nodes, etcd, and lb groups.
# The lb group lets Ansible configure HAProxy as the load balancing solution.
# Comment lb out if your load balancer is pre-configured.
[OSEv3:children]
masters
nodes
etcd
lb

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
debug_level=2
openshift_release=v1.3
# Uncomment the following to enable htpasswd authentication; defaults to
# DenyAllPasswordIdentityProvider.
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# Native high availbility cluster method with optional load balancer.
# If no lb group is defined installer assumes that a load balancer has
# been preconfigured. For installation the value of
# openshift_master_cluster_hostname must resolve to the load balancer
# or to one or all of the masters defined in the inventory if no load
# balancer is present.
openshift_master_cluster_method=native
openshift_master_cluster_hostname=lb.paastest.cn
openshift_master_cluster_public_hostname=lb.paastest.cn

# apply updated node defaults
openshift_node_kubelet_args={'pods-per-core': ['10'], 'max-pods': ['250'], 'image-gc-high-threshold': ['90'], 'image-gc-low-threshold': ['80']}

# override the default controller lease ttl
#osm_controller_lease_ttl=30

# enable ntp on masters to ensure proper failover
openshift_clock_enabled=true

# host group for masters
[masters]
master1.paastest.cn
master2.paastest.cn

# host group for etcd
[etcd]
etcd1.paastest.cn
etcd2.paastest.cn
etcd3.paastest.cn

# Specify load balancer host
[lb]
lb.paastest.cn

# host group for nodes, includes region info
[nodes]
master[1:2].paastest.cn openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
node1.paastest.cn openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
node2.paastest.cn openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
```

Above is my configurations，i tried to install openshift in 3 masters,3 etcds ,1 lb,2 nodes.But i got errors while installing with ansible:

MSG:

MODULE FAILURE
**fatal: [master2.paastest.cn]: FAILED!** => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        **"module_name": "openshift_facts"**
    }, 
    "module_stderr": "", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_A2kYP2/**ansible_module_openshift_facts.py**\", line 2209, in <module>\r\n    main()\r\n  File \"/tmp/ansible_A2kYP2/ansible_module_openshift_facts.py\", line 2190, in main\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_A2kYP2/ansible_module_openshift_facts.py\", line 1647, in **init**\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_A2kYP2/ansible_module_openshift_facts.py\", line 1685, in generate_facts\r\n    defaults = self.get_defaults(roles, deployment_type, deployment_subtype)\r\n  File \"/tmp/ansible_A2kYP2/ansible_module_openshift_facts.py\", line 1795, in get_defaults\r\n    version_info = get_docker_version_info()\r\n  File \"/tmp/ansible_A2kYP2/ansible_module_openshift_facts.py\", line 1134, in get_docker_version_info\r\n    if 'Server' in version_info:\r\nTypeError: argument of type 'NoneType' is not iterable\r\n", 
    "parsed": false
PLAY RECAP *********************************************************************
etcd1.paastest.cn          : ok=102  changed=27   unreachable=0    failed=0  
etcd2.paastest.cn          : ok=94   changed=20   unreachable=0    failed=0  
etcd3.paastest.cn          : ok=93   changed=20   unreachable=0    failed=0  
lb.paastest.cn             : ok=70   changed=5    unreachable=0    failed=0  
localhost                  : ok=10   changed=9    unreachable=0    failed=0  
master1.paastest.cn        : ok=70   changed=2    unreachable=0    **failed=1**  
master2.paastest.cn        : ok=69   changed=2    unreachable=0    **failed=1**  
node1.paastest.cn          : ok=53   changed=2    unreachable=0    failed=0  
node2.paastest.cn          : ok=53   changed=2    unreachable=0    failed=0 

Any help is highly appreciated.

**edited by sdodson** to make hosts file contents a code block to avoid markdown formatting

**Comment by sdodson** [comment]
Do you by chance have two docker packages installed? What's the output of `docker version` look like?

**Comment by J0hnson** [comment]
Hi Scott,

Thanks for your advice.
I install docker on that two masters manually,and they work fine now.
But  i am still not confused why docker cannot be installed automatically via openshift-ansible.
