### ISSUE TITLE
Flannel vars renamed in flannel 0.5.5

### ISSUE THREAD

**Issue by jprovaznik** [openshift/openshift-ansible#2635]
It seems that the upcoming flannel-0.5.5 uses different variable names in /etc/sysconfig/flannel.
##### Version

rhel 7.3
flannel-0.5.5-1.el7.x86_64
openshift-ansible commit 553ce409a40305a984894a980fc3969c11f41aba
##### Steps To Reproduce

deploy with flannel on rhel 7.3
##### Current Result

flanneld service fails to start
##### Expected Result

flanneld service starts
##### Additional Information

This fix works for the new version:
roles/flannel/tasks/main.yml
   lineinfile:
￼      dest: /etc/sysconfig/flanneld
￼      backrefs: yes
￼ -    regexp: "^(FLANNEL_ETCD=)"
￼ +    regexp: "^(FLANNEL_ETCD_ENDPOINTS=)"
￼      line: '\1{{ etcd_hosts|join(",") }}'
￼  
￼  - name: Set flannel etcd key
￼    become: yes
￼    lineinfile:
￼      dest: /etc/sysconfig/flanneld
￼      backrefs: yes
￼ -    regexp: "^(FLANNEL_ETCD_KEY=)"
￼ +    regexp: "^(FLANNEL_ETCD_PREFIX=)"
￼      line: '\1{{ flannel_etcd_key }}'

**Comment by sdodson** [comment]
@ingvagabund Do you know if we could set both old and new values without breaking flannel?

**Comment by ingvagabund** [comment]
The problem is the `flannel.service` file that expects new names of envs. We could grep the service file and check if it expects the new names or the old names and regenerate the ``flanneld`` file accordingly.

**Comment by sdodson** [comment]
I'm suggesting we just add both and we avoid trying to do conditional logic in ansible based on whether it/s 0.5.5 or earlier. Does it ignore envars it doesn't know about?

**Comment by ingvagabund** [comment]
That is okay as long as the config file is touched by automatic scripts only. It can be confusing for the user and cause problems when only part of the vars is modified.

Yes, the service ignores all unused envs.

**Comment by jeremyeder** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1391515

**Comment by jprovaznik** [comment]
reopening this issue, the bellow fail is probably related:
TASK [flannel : Set flannel etcd options] **************************************
task path: /usr/share/ansible/openshift-ansible/roles/flannel/tasks/main.yml:7
fatal: [test-infra-1.example.com]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/roles/flannel/tasks/main.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set flannel etcd options\n  ^ here\n"
}
fatal: [test-ocp34-master-2.example.com]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/roles/flannel/tasks/main.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set flannel etcd options\n  ^ here\n"
}
fatal: [test-infra-0.example.com]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/roles/flannel/tasks/main.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set flannel etcd options\n  ^ here\n"
}
fatal: [test-ocp34-master-1.example.com]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/roles/flannel/tasks/main.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set flannel etcd options\n  ^ here\n"
}
fatal: [test-ocp34-master-0.example.com]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/roles/flannel/tasks/main.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set flannel etcd options\n  ^ here\n"
}
fatal: [test-ocp34-node-62rl4p3n.example.com]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/roles/flannel/tasks/main.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set flannel etcd options\n  ^ here\n"
}
fatal: [test-ocp34-node-z5w51z39.example.com]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/roles/flannel/tasks/main.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set flannel etcd options\n  ^ here\n"
}
	to retry, use: --limit @/var/lib/ansible/playbooks/main.retry

PLAY RECAP *********************************************************************
loadbalancer               : ok=64   changed=10   unreachable=0    failed=0   
localhost                  : ok=60   changed=22   unreachable=0    failed=0   
test-infra-0.example.com   : ok=159  changed=41   unreachable=0    failed=1   
test-infra-1.example.com   : ok=159  changed=41   unreachable=0    failed=1   
test-ocp34-etcd-0.example.com : ok=95   changed=29   unreachable=0    failed=0   
test-ocp34-etcd-1.example.com : ok=86   changed=22   unreachable=0    failed=0   
test-ocp34-etcd-2.example.com : ok=86   changed=22   unreachable=0    failed=0   
test-ocp34-master-0.example.com : ok=388  changed=110  unreachable=0    failed=1   
test-ocp34-master-1.example.com : ok=303  changed=91   unreachable=0    failed=1   
test-ocp34-master-2.example.com : ok=303  changed=91   unreachable=0    failed=1   
test-ocp34-node-62rl4p3n.example.com : ok=159  changed=41   unreachable=0    failed=1   
test-ocp34-node-z5w51z39.example.com : ok=159  changed=41   unreachable=0    failed=1

**Comment by sdodson** [comment]
@smunilla PTAL
