### ISSUE TITLE
Webinterface not reachable after Vagrant deployment

### ISSUE THREAD

**Issue by dtpest** [openshift/openshift-ansible#2644]
I'm using "openshift-ansible" repo to deploy Openshift on my Ubuntu Node with KVM.
After running "vagrant up --provider=libvirt --no-provision --debug" Port 8443 is in use - SSH is using this Port.
After "vagrant provision" Port 8443 is no longer in use.
So I am unable to open the webinterface.

##### Version
openshift-ansible-3.4.10-1-21-g556e8d2
ansible 2.1.2.0
Vagrant 1.8.6

##### Steps To Reproduce
git clone "openshift-ansible"
vagrant up --provider=libvirt --no-provision --debug
vagrant provision

##### Current Result
Can not connect to the webinterface on Port 8443
##### Expected Result
Could open webinterface on Port 8443 with the Host IP address
172.16.98.100:8443

##### Additional Information
Host IP: 172.16.98.100
Host OS: Ubuntu 16.04.01

**Comment by detiber** [comment]
Closing because we are removing this Vagrantfile in favor of the one in openshift-ansible-contrib.
