### ISSUE TITLE
Vagrant deployment leads to infinite loop

### ISSUE THREAD

**Issue by dtpest** [openshift/openshift-ansible#2645]
vagrant up leads to infinite loop.
DEBUG ssh: Sending SSH keep-alive ... 

##### Version
openshift-ansible-3.4.10-1-21-g556e8d2
Vagrant 1.8.6
ansible 2.1.2.0
Ubuntu 16.04.01

##### Steps To Reproduce
vagrant up --provider=libvirt --no-provision --debug

##### Current Result
......
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: uname -s | grep SunOS (sudo=false)
DEBUG ssh: Exit status: 1
DEBUG ssh: Downloading: /etc/hosts to /home/labuser/.vagrant.d/tmp/hosts.node1
DEBUG ssh: Exit status: 1
DEBUG ssh: Re-using SSH connection.
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: test -d $Env:SystemRoot (sudo=false)
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
.....
##### Expected Result
Deployment process should end with the created Nodes.

**Comment by detiber** [comment]
Closing, since we are removing this Vagrantfile in favor of the one in openshift-ansible-contrib.
