### ISSUE TITLE
Upgrade 1.3.0 to 1.3.1 fails (probably 3.3.0 to 3.3.1 also)

### ISSUE THREAD

**Issue by tobru** [openshift/openshift-ansible#2661]
I tried to upgrade Origin from 1.3.0 to 1.3.1 with the following steps:
1. Set `openshift_release` in `/etc/ansible/hosts` to v1.3.1 (was v1.3.0)
2. Run `playbooks/byo/openshift-cluster/upgrades/v3_3/upgrade.yml`

This stops at:

```
TASK [fail] ********************************************************************
fatal: [origin-master1.vagrant.dev]: FAILED! => {"changed": false, "failed": true, "msg": "openshift_release is 1.3.1 which is not a valid release for a 1.3 upgrade\n"}
```

What are the correct parameters to upgrade the cluster from 1.3.0 to 1.3.1?
##### Version

openshift-ansible-3.4.12-1-10-g1f28e81 (also tried with openshift-ansible-3.3.39-1)
ansible 2.2.0.0
##### Steps To Reproduce

See above
##### Current Result

See above
##### Expected Result

Cluster upgraded to 1.3.1
##### Additional Information

`ansible-playbook playbooks/byo/openshift-cluster/upgrades/v3_3/upgrade.yml`
CentOS Linux release 7.2.1511 (Core)

```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_become=True
ansible_ssh_user=ansible
containerized=True
deployment_type=origin
docker_version=1.10.3
openshift_hosted_manage_registry=True
openshift_hosted_registry_replicas=1
openshift_hosted_registry_selector=registry=allowed
openshift_hosted_router_replicas=1
openshift_hosted_router_selector=router=allowed
openshift_install_examples=True
openshift_master_default_subdomain=192.168.216.210.nip.io
openshift_release=v1.3.1
openshift_use_manageiq=False
openshift_use_nuage=False
os_sdn_network_plugin_name=redhat/openshift-ovs-multitenant

[masters]
origin-master1.vagrant.dev openshift_ip='192.168.216.201' openshift_node_labels='{"region":"infra","logging-infra-fluentd":"allowed"}' openshift_schedulable=False

[nodes]
origin-node1.vagrant.dev openshift_ip='192.168.216.210' openshift_node_labels='{"logging-infra-fluentd":"allowed","region":"vagrant","registry":"allowed","router":"local"}'
origin-node2.vagrant.dev openshift_ip='192.168.216.211' openshift_node_labels='{"logging-infra-fluentd":"allowed","region":"vagrant","registry":"allowed"}'
origin-master1.vagrant.dev openshift_ip='192.168.216.201' openshift_node_labels='{"region":"infra","logging-infra-fluentd":"allowed"}' openshift_schedulable=False
```

**Comment by tobru** [comment]
Now that 3.3.1.3 is released, I was hoping that the upgrade tasks has been revised. But it looks like there was no change and I'm still lost at `openshift_release is 1.3.0 which is not a valid release for a 1.3 upgrade`. What needs to be done to upgrade from 1.3.0 to 1.3.1?

**Comment by tobru** [comment]
I found the solution: openshift_release must be v1.3 and then one can choose the update version with openshift_image_tag or openshift_pkg_version, depending on the deployment type.

**Comment by sdodson** [comment]
@tobru Thanks for the followup with your resolution.
