### ISSUE TITLE
Ansible 2.2 bug in AWS cloud provider ini file

### ISSUE THREAD

**Issue by mwoodson** [openshift/openshift-ansible#2668]
We are testing a new version of Ansible (ansible-2.2.0.0-0.70.rc3.el7.noarch).

In the new version of Ansible, the ini module will die if the ini file is NOT there.  According to the ini module docs, it looks like there is a new option called "create:"  However, I'm not sure if create is backwards compatible.

I see 2 options. 1) "touch" the file before it's created.  2) use "create: true"

Here is where it's bombing in the ansible code:

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_cloud_provider/tasks/aws.yml

Here is the ini module doc.  Please see the "create" statement.

http://docs.ansible.com/ansible/ini_file_module.html

**Comment by sdodson** [comment]
Thanks for testing the new build, this is really helpful.
