### ISSUE TITLE
RFE: gather info playbook

### ISSUE THREAD

**Issue by timothysc** [openshift/openshift-ansible#2684]
Provide a basic gather info play book that could be used by both the field and customers.  
I could have a customizable list of hosts to gather info from and default to gathering master+etcd data: 
- configurations
- logs 
- Any other recommended data, e.g. SOS 

And place that data into a structured tarball.  This could also be useful for Q/E when filing issues.  

/cc @jeremyeder @mffiedler

**Comment by mffiedler** [comment]
The pbench oc tool script from pbench would be a good addition.  grabs info about the openshift config + the current events.

**Comment by brenton** [comment]
This definitely sounds like something that @rhcarvalho, @sosiouxme and I would be interested in helping with as part of the customer response and diagnostics team.

**Comment by rhcarvalho** [comment]
If someone wants something that collects data like that today, have a look at https://github.com/feedhenry/fh-system-dump-tool#fh-system-dump-tool

Despite the name, there's little specific to FeedHenry/RHMAP there, and should help collecting data of arbitrary OpenShift clusters.

**Comment by jeremyeder** [comment]
Is this meant to replace sosreport?

**Comment by timothysc** [comment]
I envision this would be a means to do field bug-reporting at the cluster level.
