### ISSUE TITLE
playbooks/adhoc/metrics_setup/playbooks/uninstall.yml didn't select openshift-infra project

### ISSUE THREAD

**Issue by harobed** [openshift/openshift-ansible#2717]
There is a bug in https://github.com/openshift/openshift-ansible/blob/master/playbooks/adhoc/metrics_setup/playbooks/uninstall.yml playbook.

It didn't select `openshift-infra` project.

This playbook is obsolete?

**Comment by harobed** [comment]
@vnugent

**Comment by harobed** [comment]
Example configuration with namespace: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_metrics/tasks/main.yaml#L49

**Comment by harobed** [comment]
It's possible to merge this `playbooks/adhoc/metrics_setup/` folder with https://github.com/openshift/openshift-ansible/commits/master/roles/openshift_metrics ?

or delete it ?

@sdodson

**Comment by sdodson** [comment]
@harobed Yes, we should get rid of the adhoc playbook it's no longer maintained.

**Comment by vnugent** [comment]
It's probably no longer needed.  I submitted the adhoc playbook before metrics setup role was created.

**Comment by rhcarvalho** [comment]
Is this still an open issue, or was it fixed by #2739?
