### ISSUE TITLE
openshift_loadbalancer role fails to DropIn limits.conf

### ISSUE THREAD

**Issue by jeremyeder** [openshift/openshift-ansible#2719]
https://bugzilla.redhat.com/show_bug.cgi?id=1391924

Manually adding the file allows for openshift-ansible runs to complete.
"DropInPaths": "/etc/systemd/system/haproxy.service.d/limits.conf"

TASK [openshift_loadbalancer : Configure the nofile limits for haproxy] ********
task path: /usr/share/ansible/openshift-ansible/roles/openshift_loadbalancer/tasks/main.yml:13
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/files/ini_file.py
<172.100.1.3> ESTABLISH SSH CONNECTION FOR USER: cloud-user
<172.100.1.3> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssap
i-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/%h-%r 172.100.1.3 '/bin/sh -c '"'"'sudo -H -S -n -u root /bi
n/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-xaenhusvtsynhjyohordqaxnbarjctyb; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [loadbalancer]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "backup": false, 
            "content": null, 
            "create": false, 
            "delimiter": null, 
            "dest": "/etc/systemd/system/haproxy.service.d/limits.conf", 
            "directory_mode": null, 
            "follow": false, 
            "force": null, 
            "group": null, 
            "mode": null, 
            "no_extra_spaces": false, 
            "option": "LimitNOFILE", 
            "owner": null, 
            "regexp": null, 
            "remote_src": null, 
            "section": "Service", 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "state": "present", 
            "unsafe_writes": null, 
            "value": "100000"
        }, 
        "module_name": "ini_file"
    }, 
    "msg": "Destination /etc/systemd/system/haproxy.service.d/limits.conf does not exist !", 
    "rc": 257
}
        to retry, use: --limit @/var/lib/ansible/playbooks/main.retry

**Comment by sdodson** [comment]
What version of the code are you running? We fixed this in https://github.com/openshift/openshift-ansible/pull/2686

**Comment by jeremyeder** [comment]
We stayed back a bit because #2635 wasn't merged and were carrying it.  I see that was resolved yesterday so I'll rebase what we're using and confirm back.
