### ISSUE TITLE
RPMs provided from dockerproject.org do not provide this requirement

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-ansible#2720]
Back in June 13 (#2021), there is a warning in the README saying:

> This repo and the origin RPMs that it installs currently require a package that provides docker. Currently the RPMs provided from dockerproject.org do not provide this requirement, though they may in the future.

The PR comments made me think this restriction was temporary.

This issue is for tracking our ability to remove that warning from the first paragraph in the README.

**Comment by rhcarvalho** [comment]
@sdodson @detiber does that warning in the README still make sense?

**Comment by sdodson** [comment]
Yes, current dockerproject.org packaging still only provides docker-engine. There may be packaging changes we can make on our side but I think those changes aren't compatible with RHEL7 versions of yum/rpm. So we're basically stuck right now.

**Comment by rhcarvalho** [comment]
@sdodson would it help to open an issue upstream?

**Comment by sdodson** [comment]
I think given the installer is already very RHEL/Fedora centric I'm fine with continuing to use docker from those distributions rather than upstream. Some portions of the installer actually rely on patches only in the distro versions. `--add-registry` mainly.

**Comment by DanyC97** [comment]
@rhcarvalho you mind closing the issue as answer been provided ? thx

**Comment by DanyC97** [comment]
cc @vrutkovs candidate for closing as being stale issue
