### ISSUE TITLE
[Openstack method] No timeout option causes heat create/update to fail on slower machines

### ISSUE THREAD

**Issue by dougbtv** [openshift/openshift-ansible#2733]
The `--timeout` passed to heat create or update is hardcoded at 3 minutes. This causes the playbooks to fail on slower machines.

##### Version
openshift-ansible-3.4.17-1

##### Steps To Reproduce

1. Run against slower machines (especially: VMs)

##### Current Result

Resources shown after create / update stack report that there was a timeout.

##### Expected Result

Enough time is given 

##### Proposed fix

Give a `heat_timeout` option for the openstack method. I will submit a PR.

**Comment by detiber** [comment]
Closing since #2734 merged
