### ISSUE TITLE
Need a variable to be able to append additional CA cert for OpenShift to trust.

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-ansible#2761]
Right now the installer does not provide a way for OpenShift to trust additional private CA certificates. This becomes an issue when I want to configure OpenShift to be load balanced by some external load balancer that requires to terminate a certificate. In this case I can allow OpenShift to just generate it's own certificates as per default, but as OpenShift will talk to itself through that external Load Balancer, it just needs to also trust that external private cert.

cc @abutcher

**Comment by abutcher** [comment]
@etsauer Do you think this is still needed given that we can't terminate SSL at the LB unless the client cert is being passed on?
