### ISSUE TITLE
PEERDNS=no in /etc/sysconfig/network-script/ifcfg-xxxx should be dealt with in dnsmasq configs

### ISSUE THREAD

**Issue by mwoodson** [openshift/openshift-ansible#2768]
@sdodson  and I talked earlier today.

On a node, I had PEERDNS=no in the ifcfg-eth0 file.  This prevented the dnsmasq from working.
Removing this option made things work as expected.

##### Version

 openshift-ansible-3.3.46/
ansible 2.2

##### Current Result

the /etc/resolv.conf doens't get configured correctly.

##### Expected Result

/etc/resolv.conf needs to be configured correctly.

**Comment by sdodson** [comment]
In my testing of #2822 I wasn't able to find any problems with PEERDNS=no (other than those I fixed in that PR). If you have access to an environment with this config still can you send me /etc/sysconfig/network-scripts/ifcfg-$INTERFACE /etc/resolv.conf and the output of `nmcli c s $INTERFACE` ?
