### ISSUE TITLE
openshift_host_metrics_public_url is not set correctly in master-config.yaml

### ISSUE THREAD

**Issue by ivanthelad** [openshift/openshift-ansible#2778]
[provide a description of the issue]
On a multi master, 3, installation it was observed on 2 of the masters have the setting metricsPublicURL correctly set.
The ansible setting in the ansible hosts file is
   - openshift_master_metrics_public_url=https://hawkular-metrics.{{ mysubdomain }}/hawkular/metrics

the resulted in one of the masters this resulted in the following config set
 - metricsPublicURL: https://hawkular-metrics.apps.{/hawkular/metrics

While the other two were correctly set with the place holder been used {{ mysubdomain }} 
##### Version
[if you're operating from a git clone provide the output of `git describe`]
HEAD detached at openshift-ansible-3.3.38-1
[if you're running from playbooks installed via RPM or atomic-openshift-utils `rpm -q atomic-openshift-utils openshift-ansible`]
[Your version of ansible, `ansible --version`]

##### Steps To Reproduce
1. [step 1]
Create a multi master environment 
2. [step 2]
Set the metricsPublicUrl to use a variable 

##### Current Result
1 or more of the masters will have a incorrect setting 

##### Expected Result
All the masters have the same config 

##### Additional Information
[The exact command you ran]
[Your operating system and version, ie: RHEL 7.2, Fedora 23]
2.1.2.0
[Your inventory file]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by sdodson** [comment]
@dgoodwin think you were looking into this already?

**Comment by dgoodwin** [comment]
Went an alternate path but I did stash the fixes we were talking about. Will try to take a look at this next week.

**Comment by detiber** [comment]
This seems to be related to https://github.com/openshift/openshift-ansible/issues/2588

**Comment by dgoodwin** [comment]
Demonstration of the problem:

```
$ ansible masters -i ./hosts -a "cat /etc/origin/master/master-config.yaml" | grep metricsPublic
  metricsPublicURL: https://hawkular-metrics./hawkular/metrics
  metricsPublicURL: https://hawkular-metrics.apps.example.com/hawkular/metrics
  metricsPublicURL: https://hawkular-metrics./hawkular/metrics
```

**Comment by dgoodwin** [comment]
I believe re-running the playbook solves the problem at least in the config file.
