### ISSUE TITLE
containerized + origin supported?

### ISSUE THREAD

**Issue by cgwalters** [openshift/openshift-ansible#2790]
Is it intended to be supported to do containerized installs of Origin right now?

AFAICS there's just one `openshift/origin` image, but the code assumes a setup like:

```
    - "{{ openshift.common.service_type }}-master"
    - "{{ openshift.common.service_type }}-master-api"
    - "{{ openshift.common.service_type }}-master-controllers"
    - "{{ openshift.common.service_type }}-node"
```

Am I missing anything?

**Comment by sdodson** [comment]
Should work, I haven't personally tried it in some time. The `openshift/origin` image is used for most of the containerized services but the node and etcd use separate images.

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_facts/library/openshift_facts.py#L1614-L1622
