### ISSUE TITLE
[RFE] openshift_hosted_{metrics, logging} roles should support `--host-mount` option for storage

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-ansible#2800]
Many customers do not have Persistent Storage options outside of NFS with which they can create PVs, which is not ideal for things like metrics and logging, where we tend to recommend block storage with high i/o for proper performance. While we support a fair number of block storage options, the majority of them are cloud-deployment oriented, which currently leaves non-cloud on-premise customers with two options: Fibre Channle or iSCSI. In the event that neither of those are available, we end up recommending attaching extra disks/LUNs to the nodes that will run these services, using the `--host-mount` option to attach them. We would like to see this option supported in future versions of the installer.

As I see it the needed additions would be the following:

1. Support for a `host-mount` type for var `openshift_hosted_X_storage_kind`.
This would need to result in giving the relevant ServiceAccount access to the `priveleged` SCC to be able to mount a directory on the host, and a patch to the dc to claim the SCC privileges. i.e.:
```
oadm policy add-scc-to-user privileged  \
       system:serviceaccount:logging:aggregated-logging-elasticsearch
oc patch $dc \
       -p '{"spec":{"template":{"spec":{"containers":[{"name":"elasticsearch","securityContext":{"privileged": true}}]}}}}'
```
2. instead of creating a new PV, we would feed the value of 
`openshift_hosted_X_storage_volume_name` to `--mount-host` during deployment, i.e.:
```
oc set volume $dc \
          --add --overwrite --name=elasticsearch-storage \
          --type=hostPath --path={{ openshift_hosted_X_storage_volume_name }}
    oc deploy --latest $dc
    oc scale $dc --replicas=1
```
3. Finally (if not already supported), we need to be able to pass in a node-selector for logging and metrics, as we can currently for the router/registry, i.e. `openshift_hosted_{metrics,logging}_selector`

##### Version
OCP 3.3+

##### Additional Information
Additional docs: https://docs.openshift.com/container-platform/3.3/install_config/aggregate_logging.html#aggregated-elasticsearch

@sdodson @jkupferer @sabre1041 @mwitzenm @themoosman

**Comment by etsauer** [comment]
bump. can someone take a look at this? getting more and more requests for it.

**Comment by bbeaudoin** [comment]
I would like to see `nodeselectorlabel` supported. Current option for `hostPath` for ElasticSearch has the node selector label as `logging-es-node` with a value corresponding to the DC node number, not a big deal but I'd like to see these land on the correct nodes to start without being specific about the value.

**Comment by jkupferer** [comment]
There is a node selector variable for elasticsearch: `openshift_hosted_logging_elasticsearch_nodeselector`.

**Comment by bbeaudoin** [comment]
Yes, there is a nodeselector, but when there are three instances the nodeselector needs to be different for each instance. That's why it would be useful to select by label and not label=value.

**Comment by gordillo-ramon-redhat** [comment]
+1 for this feature. That will enable also AIO installations for developers to provide persistent storage without the need to set up an NFS server.

**Comment by detiber** [comment]
@jcantrill @ewolinetz

**Comment by ewolinetz** [comment]
@etsauer I want to make sure I'm correctly understanding the host mount requirements correctly:
Be provided the ability to specify that instead of a PVC mount for the Elasticsearch DC(s) a host mount will be used and use the host `path` provided?
We would also ensure that the ES SA is added to the correct SCC (likely `hostmount-anyuid` or `hostaccess`).

Secondarily, the node selector would be a single label as opposed to a 'label=value' pair, correct?  i.e. `openshift_logging` and `openshift_metrics`. This would be separate from the current `logging-infra` label, or to replace the hard-coded value of `logging-infra`?

**Comment by bbeaudoin** [comment]
@ewolinetz since that was mine, I'll respond. Current practice is to set "logging-es-node" to an enumeration of the hosts instead of true/false. It's a wish list item and doesn't necessarily belong here.

**Comment by bbeaudoin** [comment]
Oh, two items :) on the host path yes, if we specify the storage type as hostPath and specify the path the error returned is hostPath isn't a supported PV type which is correct but is a supported backend.

The issue is the PV role is called for all storage backends and it only knows PVs. When hostPath is specified, the logging SA does need hostmount-anyuid for sure.

**Comment by jkupferer** [comment]
In case it is useful here, I have created ansible roles for implementing
these hostmounts after cluster installation:

https://github.com/jkupferer/ansible-role-openshift-logging-elasticsearch-hostmount
https://github.com/jkupferer/ansible-role-openshift-metrics-cassandra-hostmount

What these roles do is use the existing node selector to get the list of
available nodes and then iterates over that node list for the desired
number of pods setting the node selector on the deployment config (logging)
or replication controller (metrics) to specify the host by
kubernetes.io/hostname label.

- Johnathan
