### ISSUE TITLE
Update Metrics templates for v1.4

### ISSUE THREAD

**Issue by mwringe** [openshift/openshift-ansible#2801]
There are new metric templates available for v1.4 required for https://bugzilla.redhat.com/show_bug.cgi?id=1392343

The origin template can be found here: https://github.com/openshift/origin-metrics

and the enterprise one is available here: https://github.com/openshift/origin-metrics/blob/enterprise/metrics.yaml

**Comment by mwringe** [comment]
@sdodson can you please take a look? Is it easier for me to do a PR, or does the system automatically pull from these locations?

**Comment by sdodson** [comment]
@mwringe We run a script that syncs things from your repo, I can handle that, but I'm having to manually patch in IMAGE_VERSION 3.4.0. If you can fix that upstream that'd make things easier.

**Comment by sdodson** [comment]
@mwringe disregard, that problem is in logging not metrics.
