### ISSUE TITLE
If OpenShift Metrics fail, assetConfig.metricsPublicURL is never set

### ISSUE THREAD

**Issue by harobed** [openshift/openshift-ansible#2805]
If OpenShift Metrics installation fail here: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_metrics/tasks/install.yml#L90

`assetConfig.metricsPublicURL` isn't set.

Next, if I relaunch Metrics installation and `openshift-infra` pods are up, `greenfield` is set to `True` and this line https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_metrics/tasks/main.yaml#L80 isn't executed.

Then `assetConfig.metricsPublicURL` is never set in `master-config.yaml`

Suggest: move `Configure master for metrics` to https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_metrics/tasks/main.yaml ?

Best regards,
Stéphane

**Comment by harobed** [comment]
@sdodson @dgoodwin @abutcher

**Comment by sdodson** [comment]
Fixed in #2973

**Comment by sdodson** [comment]
Fixed in #2973
