### ISSUE TITLE
Set good version in openshift-ansible/inventory/byo/hosts.origin.example in release-1.3 branch

### ISSUE THREAD

**Issue by harobed** [openshift/openshift-ansible#2806]
Set good version in [openshift-ansible/inventory/byo/hosts.origin.example](https://github.com/openshift/openshift-ansible/blob/release-1.3/inventory/byo/hosts.origin.example) in release-1.3 branch

```
openshift_image_tag=v1.3.1
# openshift_pkg_version=v1.3.1
# openshift_hosted_metrics_deployer_prefix=openshift/origin-
# openshift_hosted_metrics_deployer_version=v1.3.1
```

**Comment by sdodson** [comment]
How about just updating the templates in roles/openshift_hosted_templates/.../v1.3/origin/ to be the correct version? Ultimately we should just match the tag to the version of Origin but that had previously presented a problem for OCP which wasn't tagged in the same way.
