### ISSUE TITLE
tuned configuration fails on fedora 25 atomic host 

### ISSUE THREAD

**Issue by dustymabe** [openshift/openshift-ansible#2809]
tuned configuration fails on fedora 25 atomic host because no tuned-adm exists

```
TASK [openshift_node : Set atomic-guest tuned profile] *************************
fatal: [ec2-54-173-118-171.compute-1.amazonaws.com]: FAILED! => {"changed": false, "cmd": "tuned-adm profile atomic-guest", "failed": true, "msg": "[Errno 2] No such file or directory: 'tuned-adm'", "rc": 2}
        to retry, use: --limit @/sharedfolder/code/github.com/openshift/openshift-ansible/playbooks/byo/config.retry
```

##### Version
The following version + a workaround for https://github.com/openshift/openshift-ansible/issues/2808
```
$ git describe
openshift-ansible-3.4.17-1-93-gb6fa0f8
```
```
$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[vagrant@f25vanilla openshift-ansible]$ rpm -q ansible
ansible-2.2.0.0-3.fc25.noarch
```

##### Steps To Reproduce
same as steps to rephttps://github.com/openshift/openshift-ansible/issues/2808

**Comment by detiber** [comment]
I suspect we previously included the tuned packages in the atomic base image and we no longer do with f25.

**Comment by dustymabe** [comment]
> I suspect we previously included the tuned packages in the atomic base image and we no longer do with f25.

as far as I can tell from looking at the history of the repo (https://pagure.io/forks/dustymabe/fedora-atomic.git) I don't think it has ever been there. @cgwalters can you confirm?

**Comment by dustymabe** [comment]
would you accept a patch that detects if tuned exists and only applies if so?

**Comment by detiber** [comment]
@dustymabe indeed.

**Comment by cgwalters** [comment]
In general there hasn't been much execution of openshift-ansible against Fedora, as far as I know.

**Comment by detiber** [comment]
@cgwalters not sure if I would agree with that. The Fedora team ( @maxamillion in particular) has done testing in the past.

**Comment by maxamillion** [comment]
I don't test against Fedora Atomic Host, but I do test it periodically on Fedora systems and it's being used to deploy our multi-node OpenShift environment backing OSBS.
