### ISSUE TITLE
add routingConfig.subdomain to master config template

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#282]
https://github.com/openshift/origin/pull/3173 adds a "routingConfig" stanza to master-config.yaml:

`subdomain` is the suffix appended to $service.$namespace. to form the default route hostname

```
routingConfig:
  subdomain: router.default.local
```

If omitted, a subdomain of "router.default.local" is used

**Comment by detiber** [comment]
@sdodson sounds like something we'd want for 3.0 GA

**Comment by sdodson** [comment]
FWIW, this is in the template as a static value, lets treat this issue as the follow up to make it easily configurable.

**Comment by liggitt** [comment]
I think Clayton just changed the default to include .svc.

**Comment by detiber** [comment]
@brenton @twiest this can be closed now
