### ISSUE TITLE
Unable to start SSO application

### ISSUE THREAD

**Issue by kunallimaye** [openshift/openshift-ansible#2823]
Unable to launch application using the sso image from the [xPass image stream](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v1.4/xpaas-streams/jboss-image-streams.json)

##### Version

+ openshift-ansible-3.3.4-1-804-g767fa52
+ ansible 2.1.0.0

##### Steps To Reproduce

1. ```oc cluster up```
2. ```oc login -u system:admin```
3. ```oc create -n openshift -f jboss-image-streams.json```
4. ```oc login -u developer```
5. ```oc new-app --docker-image registry.access.redhat.com/redhat-sso-7/sso70-openshift --name=ssoservice```

##### Current Result
Can not launch the application with following error:
```bash
18:08:00,877 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: java.lang.IllegalStateException: WFLYCTL0056: Could not rename /opt/eap/standalone/configuration/standalone_xml_history/current to /opt/eap/standalone/configuration/standalone_xml_history/20161117-180800876
	at org.jboss.as.controller.persistence.ConfigurationFile.createHistoryDirectory(ConfigurationFile.java:638)
	at org.jboss.as.controller.persistence.ConfigurationFile.successfulBoot(ConfigurationFile.java:470)
	at org.jboss.as.controller.persistence.BackupXmlConfigurationPersister.successfulBoot(BackupXmlConfigurationPersister.java:94)
	at org.jboss.as.controller.AbstractControllerService.finishBoot(AbstractControllerService.java:449)
	at org.jboss.as.server.ServerService.boot(ServerService.java:368)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
	at java.lang.Thread.run(Thread.java:745)

18:08:00,877 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
```

##### Expected Result

The application should start.

##### Additional Information

Work around is to actually delete <kbd>/opt/eap/standalone/configuration/standalone_xml_history/current</kbd> directory from the image/container.  
This can be done by updating the <kbd>/opt/eap/bin/openshift-launch.sh</kbd> file:
```bash
# Add following command at the start of the file:
rm -fr $JBOSS_HOME/standalone/configuration/standalone_xml_history/current
```

**Comment by kunallimaye** [comment]
May be this issue actually should be logged against @jboss-openshift??
https://github.com/jboss-openshift/application-templates

Please let us know. 
--kl

**Comment by sdodson** [comment]
@rcernich can you take a look at this? Unless we think this is something specific to what openshift-ansible has done I think this should be against jboss-openshift repo.

**Comment by rcernich** [comment]
This seems to be a problem with the image itself, possibly due to user perms.  I'm wondering if the password file isn't being updated appropriately per [1].  That said, I don't know what would have changed to cause this to not work now.

[1]1 https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines

**Comment by knrc** [comment]
@sdodson I've just ran up sso with new-app on our instance and found no issues, continuing to investigate

**Comment by knrc** [comment]
@kunallimaye what os etc. are you using?

**Comment by knrc** [comment]
@sdodson  There is definitely something strange going on here, who would be the best person to talk to on the OCP side?

**Comment by sdodson** [comment]
@kunallimaye Sorry, I failed to notice you're using `oc cluster up` which doesn't do anything with ansible. We should really take this issue to the origin repo.
@csrwng any ideas what would prevent the sso app from running correctly when running on an `oc cluster up` environment?

**Comment by csrwng** [comment]
@sdodson nothing comes to mind but I will take a look

**Comment by csrwng** [comment]
So using the latest 'oc' from origin master, the sso app starts ok for me. @kunallimaye just curious, why did you specify the image in new-app if you'd imported the image stream. (Just wondering if for some reason you're getting an older image). 

I did:

```
oc create -n openshift -f jboss-image-streams.json
oc new-app redhat-sso70-openshift --name=ssoservice
```

The pod started ok for me.

**Comment by knrc** [comment]
@csrwng I suspect this may not be an image issue but perhaps something related to the environment, I'll try to find you on IRC to discuss

**Comment by knrc** [comment]
This appears to be related to the following docker issue, I'm continuing to investigate possible workarounds

https://github.com/docker/docker/issues/24660

**Comment by kunallimaye** [comment]
No worries - as I mentioned earlier, happy to log it against
jboss-openshift if appropriate.
Please let us know.

And I will also try the latest openshift origin image.
—kl

-- 
Kunal Limaye

On 23 November 2016 at 01:18:20, Scott Dodson (notifications@github.com)
wrote:

@kunallimaye <https://github.com/kunallimaye> Sorry, I failed to notice
you're using oc cluster up which doesn't do anything with ansible. We
should really take this issue to the origin repo.
@csrwng <https://github.com/csrwng> any ideas what would prevent the sso
app from running correctly when running on an oc cluster up environment?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/openshift-ansible/issues/2823#issuecomment-262251410>,
or mute the thread

**Comment by knrc** [comment]
@kunallimaye What it your environment?

**Comment by kunallimaye** [comment]
```
klimaye-mac:~ klimaye$ oc version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth

klimaye-mac:~ klimaye$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Comment by knrc** [comment]
@kunallimaye Which OS?  I was talking to someone else today, they hit the same issue with another image on RHEL 7.2 with overlayfs, they updated to RHEL 7.3 and the issue appeared to be fixed.

**Comment by kunallimaye** [comment]
macOS Sierra
Version 10.12

**Comment by jkroepke** [comment]
It happends because rename isn't supported on overlayfs

```
Renaming directories: Calling rename(2) for a directory is allowed only when both the source and the destination path are on the top layer. Otherwise, it returns EXDEV error (“cross-device link not permitted”). Your application needs to be designed to handle EXDEV and fall back to a “copy and unlink” strategy.
```

Deleting is folder is a valid workaround for this issue. RedHat should maybe use move instead rename.

See: https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

**Comment by kunallimaye** [comment]
Another workaround is to create a persistent volume claim in the deployment
config like below

```bash
# Create a persistent volume claim in the deployment config using the
command below
$ oc volume dc/sso --add --claim-size 512M --mount-path
/opt/eap/standalone/configuration/standalone_xml_history --name
standalone-xml-history
```

-- 
Kunal Limaye

On 8 November 2017 at 03:54:53, Jan-Otto Kröpke (notifications@github.com)
wrote:

It happends because rename isn't supported on overlayfs

Renaming directories: Calling rename(2) for a directory is allowed
only when both the source and the destination path are on the top
layer. Otherwise, it returns EXDEV error (“cross-device link not
permitted”). Your application needs to be designed to handle EXDEV and
fall back to a “copy and unlink” strategy.

Deleting is folder is a valid workaround for this issue. RedHat should
maybe use move instead rename.

See:
https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/openshift-ansible/issues/2823#issuecomment-342547898>,
or mute the thread

**Comment by kunallimaye** [comment]
Another workaround is to create a persistent volume claim in the deployment
config like below:

```bash
# Create a persistent volume claim in the deployment config using the command below
$ oc volume dc/sso --add --claim-size 512M --mount-path /opt/eap/standalone/configuration/standalone_xml_history --name standalone-xml-history
```

**Comment by jkroepke** [comment]
It should be included into the standard xPASS Images

**Comment by glennswest** [comment]
I have added the workaround the the ocp azure ref arch. The problem duplicates everytime without the fix.

**Comment by knrc** [comment]
In the past this issue has often occurred because of permission changes in one layer being overridden in another layer, it may be that this is happening within the SSO image and falling foul of the bug mentioned earlier.

I'll take a look at the SSO image and see if there's anything we can do to mitigate this issue.

**Comment by knrc** [comment]
The rename mentioned by @jkroepke does appear to be the issue, when SSO is installed into the EAP server is runs up the server and creates the standalone_xml_history directory.  The file being renamed is a few layers below the top layer.

I'll get this directory removed as part of the build, this should mitigate the issue and stop the bug being triggered.

**Comment by knrc** [comment]
https://issues.jboss.org/browse/CLOUD-2195
