### ISSUE TITLE
Set scale of metrics (cassandra / hawkular)

### ISSUE THREAD

**Issue by garethahealy** [openshift/openshift-ansible#2824]
Currently, it doesn't look like you can set how many cassandra or hawkular pods you might want for HA purposes. Would be nice if this was possible.

https://docs.openshift.com/container-platform/3.3/install_config/cluster_metrics.html#cluster-metrics-scaling-openshift-metrics-pods

**Comment by sdodson** [comment]
@garethahealy are you using dynamic volume provisioning? we'd probably only add this for dynamic volume provisioning

**Comment by garethahealy** [comment]
I am not using dynamic volume provisioning at the current customer i am with, but if it can only be done that way, thats fine.
