### ISSUE TITLE
registry-console deployment fails once openshift_install_examples is set to false

### ISSUE THREAD

**Issue by iteeconsulting** [openshift/openshift-ansible#2847]
registry-console deployment fails once `openshift_install_examples` is set to `false`

##### Version
openshift-ansible-3.3.54-1
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o override

##### Steps To Reproduce
1. in your  inventory file:  `openshift_install_examples=false`

##### Current Result
```json
TASK [cockpit-ui : Deploy registry-console] ************************************
fatal: [master0.xxx]: FAILED! => {"changed": true, "cmd": ["oc", "new-app", "--template=registry-console", "-p", "OPENSHIFT_OAUTH_PROVIDER_URL=https://master0.xxx:8443", "-p", "REGISTRY_HOST=docker-registry-default.xxx", "-p", "COCKPIT_KUBE_URL=https://registry-console-default.xxx", "--config=/tmp/openshift-ansible-rVeJHi/admin.kubeconfig", "-n", "default"], "delta": "0:00:00.200412", "end": "2016-11-21 11:32:26.830878", "failed": true, "failed_when_result": true, "rc": 1, "start": "2016-11-21 11:32:26.630466", "stderr": "error: no match for \"registry-console\"\n\nThe 'oc new-app' command will match arguments to the following types:\n\n  1. Images tagged into image streams in the current project or the 'openshift' project\n     - if you don't specify a tag, we'll add ':latest'\n  2. Images in the Docker Hub, on remote registries, or on the local Docker engine\n  3. Templates in the current project or the 'openshift' project\n  4. Git repository URLs or local paths that point to Git repositories\n\n--allow-missing-images can be used to point to an image that does not exist yet.\n\nSee 'oc new-app -h' for examples.", "stdout": "", "stdout_lines": [], "warnings": []}
```
##### Expected Result
Two possibilities, I think:
1. cockpit-ui role should be _self contained_, i.e. that role by itself should provide the registry console template
or,
2. `openshift_install_examples` could be used in conditional check to decide whether console needs to be installed 

##### Additional Information
The workaround for the problem is to set `openshift_install_examples` to `True`

[The exact command you ran]
`ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook \
-i ../infra/openstack/hosts -b playbooks/byo/config.yml --private-key=$SSH_PRIVATE_KEY`

[Your operating system and version, ie: RHEL 7.2, Fedora 23]
CentOS 7.2

[Your inventory file]
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=centos
ansible_become=yes
deployment_type=origin
osm_default_node_selector='region=primary'
openshift_hosted_router_selector='region=infra'
#openshift_hosted_router_force_subdomain='XXX'
openshift_hosted_registry_selector='region=infra'
openshift_master_default_subdomain=xxx.xxx
openshift_release=v1.3
openshift_install_examples=false
#docker_version="1.11.2"

[masters]
master0.xxxx ...

[nodes]
master0.xxxx ...
node0.xxxx ...
node1.xxxx ...

**Comment by abutcher** [comment]
I believe this was fixed in https://github.com/openshift/openshift-ansible/pull/2573 but fix has not been backported to release-1.3 @sdodson.
