### ISSUE TITLE
The etcd backup step doesn't work in containerized deployment on CentOS 7.2

### ISSUE THREAD

**Issue by bachp** [openshift/openshift-ansible#2850]
The reason seems to ba that ansible is using the etcdctl utility of the host. On CentOS 7.2 this is version 2.3.7. The containerized deployment however uses an etcd3 container.

One possible solution is to use the `etcdctl` from the container.

##### Version
`git describe`: openshift-ansible-3.4.21-1-43-g1bba20b (current release-1.4 branch)
`ansible --version`:
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

##### Steps To Reproduce
1. Deploy a containerized deployment
2. Run the `playbooks/byo/openshift-cluster/upgrades/v3_4/upgrade.yml` playbook

##### Current Result

`etcdctl backup` fails with a panic as there seems to be a version missmatch.
The error occures here: https://github.com/openshift/openshift-ansible/blob/master/playbooks/common/openshift-cluster/upgrades/etcd/backup.yml#L5`

The error message is: 
```
fatal: [master01]: FAILED! => {"changed": true, "cmd": ["etcdctl", "backup", "--data-dir=/var/lib/etcd/", "--backup-dir=/var/lib/origin/etcd-backup-20161128163259"], "delta": "0:00:01.585915", "end": "2016-11-28 15:38:51.772632", "failed": true, "rc": 2, "start": "2016-11-28 15:38:50.186717", "stderr": "2016-11-28 15:38:50.318061 W | snap: skipped unexpected non snapshot file db\n2016-11-28 15:38:51.287513 W | wal: ignored file 0.tmp in wal\npanic: runtime error: makeslice: len out of range\n\ngoroutine 1 [running]:\npanic(0xc52260, 0xc82000f550)\n\t/usr/lib/golang/src/runtime/panic.go:481 +0x3e6\ngithub.com/coreos/etcd/wal.(*decoder).decode(0xc820141710, 0xc8201d52c0, 0x0, 0x0)\n\t/builddir/build/BUILD/etcd-2.3.7/src/github.com/coreos/etcd/wal/decoder.go:55 +0x142\ngithub.com/coreos/etcd/wal.(*WAL).ReadAll(0xc8200f40d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/builddir/build/BUILD/etcd-2.3.7/src/github.com/coreos/etcd/wal/wal.go:237 +0x442\ngithub.com/coreos/etcd/etcdctl/command.handleBackup(0xc820175680)\n\t/builddir/build/BUILD/etcd-2.3.7/src/github.com/coreos/etcd/etcdctl/command/backup_command.go:93 +0x90f\ngithub.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0xd94728, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe45c20, 0x18, 0x0, ...)\n\t/builddir/build/BUILD/etcd-2.3.7/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:137 +0x1081\ngithub.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0xc820175440, 0xc82000a1c0, 0x4, 0x4, 0x0, 0x0)\n\t/builddir/build/BUILD/etcd-2.3.7/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:175 +0xffa\nmain.main()\n\t/builddir/build/BUILD/etcd-2.3.7/src/github.com/coreos/etcd/etcdctl/main.go:69 +0x1aae", "stdout": "", "stdout_lines": [], "warnings": []}
```

##### Expected Result

The backup is successful. It is done by the correct version of `etcdctl`

##### Additional Information
[Centos 7.2 1511]

**Comment by dgoodwin** [comment]
Fairly certain we know what this is and your analysis is right but if you get a chance please include the actual error you hit. Adding @sdodson as he's been in this area lately. Doing the backup with a container is an interesting idea IMO.

**Comment by bachp** [comment]
@dgoodwin I updated the issue to include the error message from ansible

**Comment by sdodson** [comment]
I'm marking this P2 as this is not a regression and etcd 3.0.15 will soon be available for centos making the current method work. We do however need to re-factor how we perform the etcd backup in containerized environments to use the etcd container in the future.
