### ISSUE TITLE
using release_version with n.v.r.c can result in version check failure

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-ansible#2854]
It appears that setting release_version to a full n.v.r.c (eg: 3.3.1.3) can result in a failure in the version check.

```yaml
openshift_image_tag=v=3.3.1.3
openshift_release=3.3.1.3
docker_version="1.10.3"
deployment_type=openshift-enterprise
containerized=false
```

Can result in:

```
2016-11-23 11:23:48,664 p=11856 u=root |  fatal: [ip-192-199-0-230.ec2.internal]: FAILED! => {
    "changed": false,
    "failed": true
}

MSG:

Detected OpenShift version 3.3.1.5 does not match requested openshift_release 3.3.1.3. You may need to adjust your yum repositories, inventory, or run the appropriate OpenShift upgrade playbook.

2016-11-23 11:23:48,666 p=11856 u=root |        to retry, use: --limit @/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry
```

This is not a serious issue. It seems that openshift_pkg_version should be used in the case where you want n.v.r.c

**Comment by sdodson** [comment]
@dgoodwin Should we just document that we only care about X.Y?

**Comment by dgoodwin** [comment]
Yeah openshift_release should just be "X.Y" or "vX.Y", we do document it correctly I believe but we could easily validate the inputs to watch for incorrect formats.

**Comment by tbielawa** [comment]
@dgoodwin said:

>  I believe but we could easily validate the inputs to watch for incorrect formats.

:clap: Validation is amazing.
