### ISSUE TITLE
Advanced install fails on firewalld.yml

### ISSUE THREAD

**Issue by deanpeterson** [openshift/openshift-ansible#2860]
I pulled down the latest origin openshift-ansible playbooks and ran the Advanced install. I get the following error:

```
ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml
statically included: /root/openshift-ansible/roles/os_firewall/tasks/firewall/firewalld.yml
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/openshift-ansible/roles/os_firewall/tasks/firewall/firewalld.yml': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Ensure iptables services are not enabled
  ^ here
```

The error appears to have been in '/root/openshift-ansible/roles/os_firewall/tasks/firewall/firewalld.yml': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Ensure iptables services are not enabled
  ^ here

##### Master
[if you're operating from a git clone provide the output of `git describe`]
openshift-ansible-3.4.17-1-158-g90fb07f

[Your version of ansible, `ansible --version`]
ansible 2.1.2.0

##### Steps To Reproduce
1. # cd ~
    # git clone https://github.com/openshift/openshift-ansible
    # cd openshift-ansible
2. ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml

##### Current Result
```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/openshift-ansible/roles/os_firewall/tasks/firewall/firewalld.yml': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Ensure iptables services are not enabled
  ^ here


The error appears to have been in '/root/openshift-ansible/roles/os_firewall/tasks/firewall/firewalld.yml': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Ensure iptables services are not enabled
  ^ here

```
##### Expected Result
Successful installation
##### Additional Information
[The exact command you ran]
RHEL 7.2

**Comment by luizvasconceloss** [comment]
I have the same problem.

ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

Red Hat Enterprise Linux Server release 7.3 (Maipo)

git describe
openshift-ansible-3.4.17-1-158-g90fb07f

**Comment by deanpeterson** [comment]
Updating ansible fixed the problem for me. "yum update ansible"

**Comment by sdodson** [comment]
@mtnbikenc Lets document 2.2 as a requirement now that we're starting to leverage features from 2.2. Our RPMs require it but we don't document it at the top level and probably not in the roles that've recently been updated to use features in 2.2

**Comment by mtnbikenc** [comment]
This should be closed via:
#2865
#2942
