### ISSUE TITLE
RFE: Create documentation for BYO

### ISSUE THREAD

**Issue by esukram** [openshift/openshift-ansible#2862]
I want to deploy OpenShift via Ansible on bare metal. We have preinstall RHEL/Atomic hosts. So the containerized deployment should be used - IMHO.

The existing playbooks also take care of provisioning the VMs/EC2 instances/... I was not able to get any documentation how to create a custom playbook and inventory file to define the hosts.

To get that somehow would be very very helpful.

**Comment by sdodson** [comment]
@esukram Do the example inventory files in inventory/byo/ help?

**Comment by esukram** [comment]
Hi @sdodson for the fast reply.

I was actually able to get it running (at some sort) by using:
[Origin inventory](/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example)

However it did not work straight away, I am using Red Hat Atomic and the Ansible run got stuck several times and some weird host lookup things happened (only on the first 'nodes' node).
