### ISSUE TITLE
error because pyOpenSSL is not installed

### ISSUE THREAD

**Issue by dustymabe** [openshift/openshift-ansible#2869]
I get an error because pyOpenSSL is not installed when I run this from an f25 system (the host where ansible is installed). 

```
TASK [Verify Ansible version is greater than or equal to 2.1.0.0] **************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'not ansible_version.full | version_compare('2.1.0.0', 'ge')' failed. The error was: No module
 named OpenSSL.crypto\n\nThe error appears to have been in '/sharedfolder/code/github.com/openshift/openshift-ansible/playbooks/common/openshift-cluster/verify_ansible_vers
ion.yml': line 8, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - name: Verify Ansi
ble version is greater than or equal to 2.1.0.0\n    ^ here\n"}
```

After I install pyOpenSSL everything works fine. Maybe that is a dep that should get installed by the rpm. Maybe not. If not, we should give a better error message to the users of openshift-ansible. 

##### Version
Working from 90fb07f and using `ansible-2.2.0.0-3.fc25.noarch.rpm` on fedora 25. No pyOpenSSL is installed.

**Comment by dustymabe** [comment]
@mscherer @detiber - thoughts?

**Comment by mscherer** [comment]
I agree we need a better error message. Let me take a look.

**Comment by mscherer** [comment]
So the problem is on https://github.com/openshift/openshift-ansible/blob/master/filter_plugins/oo_filters.py#L13 

We do import the module without making sure it is here. 

We can either install it prior to using the filter, or importing openssl conditionally and if we can't, disable oo_parse_named_certificates . Or just fail that method if openssl is not present.

I am gonna try the last method.

**Comment by dustymabe** [comment]
@mscherer is this something that should actually be a dependency of the rpm? or is it working as desired?

**Comment by mscherer** [comment]
Indeed, i do not know what I add in mind, but adding the dependency would also help (as I use it out of git, I totally forgot of the rpm). After looking in more details, this is used on openshift master role, so that's hard to avoid using it anyway.

**Comment by malagant** [comment]
I get the same message on current master with openshift 3.6.0-alpha-1. I'm on Centos 7.3. However, it doesn't help if I run `yum install pyOpenSSL`. Any hints on this?
