### ISSUE TITLE
openshift_release is 1.3 which is not a valid release for a 1.4 upgrade

### ISSUE THREAD

**Issue by J0hnson** [openshift/openshift-ansible#2900]
[root@master2 ~]# oc version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://lb.paastest.cn:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4

I tried to use v3_4/upgrade.yml to upgrade openshift v1.3.1 to openshift v.14.
but it doesn't wok.
************************************
The error message is :
task path: /etc/ansible/openshift-ansible/playbooks/common/openshift-cluster/upgrades/pre/verify_inventory_vars.yml:33
fatal: [master1.paastest.cn]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "msg": "openshift_release is 1.3 which is not a valid release for a 1.4 upgrade\n"
        }, 
        "module_name": "fail"
    }, 
    "msg": "openshift_release is 1.3 which is not a valid release for a 1.4 upgrade\n"
}
*******************************
So is it possible to upgrade oc to v1.4 with v3_4 upgrade yaml file?

**Comment by dgoodwin** [comment]
@J0hnson do you still have openshift_release set in your inventory?

**Comment by J0hnson** [comment]
@dgoodwin I kept  with openshift_release=1.3 .If i commented openshift_release,the result is:

    "msg": "Detected OpenShift version 1.3.1 does not match requested openshift_release 1.4. You may need to adjust your yum repositories, inventory, or run the appropriate OpenShift upgrade playbook."
}

**Comment by dgoodwin** [comment]
Ok commenting it out or updating to 1.4 is correct, the message in your last comment would indicate that you do not have packages available for Origin 1.4. Are these published in yum repos yet and if so, do you have those repos enabled?

**Comment by J0hnson** [comment]
@dgoodwin Thanks very much for your suggestion. Yes, that's the problem of the repos i set.
Please close this ticket.

**Comment by FilipVozar** [comment]
@J0hnson could you please provide your solution? I'm having the same problem and I can't find repos for origin 1.4

**Comment by J0hnson** [comment]
@FilipVozar yes, i cannot find the repo too. So i just download origin 1.4 in the machine and install.
