### ISSUE TITLE
v3_2 upgrade playbook broken after 3.4 Upgrade Improvements

### ISSUE THREAD

**Issue by zeroem** [openshift/openshift-ansible#2924]
After the "3.4 Upgrade Improvements" pull request, #2441, the `v3_2` upgrade playbook fails as it references playbooks, eg `playbooks/common/openshift-cluster/upgrades/pre.yml` that have been removed.

##### Version
openshift-ansible-3.4.17-1-212-ga3ce4c1
ansible 1.9.6

##### Steps To Reproduce
```
ansible-playbook -i your-inventory playbooks/byo/openshift-cluster/upgrades/v3_2/upgrade.yml
```

##### Current Result
```
ERROR: the playbook: openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_2/upgrade.yml could not be found
```

##### Expected Result
The upgrade runs without erroring out at startup

**Comment by detiber** [comment]
@zeroem To run the 3.2 upgrade, you should run from the release-1.2 branch, only the latest version and the current development versions of OpenShift are currently tested against the master branch.

Also, the release-1.2 branch now requires Ansible 2.x (currently tested against Ansible 2.2).

**Comment by zeroem** [comment]
Ok, thank you for the information. I appreciate your time.
