### ISSUE TITLE
Playbooks do not fail gracefully when run with Ansible < 2.2

### ISSUE THREAD

**Issue by dtpest** [openshift/openshift-ansible#2925]
[provide a description of the issue]
Using libvirtd description

##### Version
git: openshift-ansible-3.4.17-1-212-ga3ce4c1
ansible 2.0.0.2

##### Steps To Reproduce
bin/cluster list libvirt '' <- does work
bin/cluster create libvirt lenaic <- fails

##### Current Result
ERROR! no action detected in task

The error appears to have been in '/home/labuser/openshift-ansible/roles/docker/tasks/main.yml': line 114, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Start the Docker service
  ^ here

##### Expected Result
Should start cluster

**Comment by abutcher** [comment]
Hey @dtpest, the playbooks should have [verified that your ansible version is 2.2](https://github.com/openshift/openshift-ansible/blob/master/playbooks/common/openshift-cluster/verify_ansible_version.yml). This task uses the systemd module which was introduced in ansible 2.2.

**Comment by detiber** [comment]
@abutcher I wonder if we are hitting the error prior to the task being run.

**Comment by abutcher** [comment]
@detiber You're right, makes sense that we'd get the syntax error rather than run.

**Comment by jberkus** [comment]
Looks like none of the playbooks are verifying ansible version.  I just hit this with the BYO playbook as well.

**Comment by detiber** [comment]
@jberkus I believe that is because the systemd module doesn't exist in 2.2. @mtnbikenc any ideas on how we could better test for ansible version?

**Comment by dtpest** [comment]
Hey,
i'm using ansible 2.0.0.2 and not 2.2

**Comment by dtpest** [comment]
Updated to 2.2 and ansible could start successfully

**Comment by mtnbikenc** [comment]
@detiber It looks like `bin/cluster create` uses the `launch.yml` playbooks.  In looking at those playbooks, they are not including the `verify_ansible_version.yml` playbook where the version verification is done.

**Comment by detiber** [comment]
@mtnbikenc @jberkus was hitting it with the byo playbooks as well.

@abutcher any thoughts?

Re-opening, since we should fail more gracefully for Ansible < 2.2

**Comment by dustymabe** [comment]
can we change the title of this issue to more accurately reflect the problem ?

**Comment by detiber** [comment]
@dustymabe done

**Comment by mtnbikenc** [comment]
https://github.com/openshift/openshift-ansible/pull/2942 should address this.
