### ISSUE TITLE
Installation of openshift-examples should be optional

### ISSUE THREAD

**Issue by jberkus** [openshift/openshift-ansible#2945]
Currently, the openshift-examples role is part of most of the playbooks. If it fails, cluster setup does not complete:

```
TASK [openshift_examples : Create tar of OpenShift examples] *******************
fatal: [35.163.205.174 -> localhost]: FAILED! => {"changed": false, "cmd": "tar -C /root/ansible/roles/openshift_examples/files/examples/v1.3/ -cvf /tmp/openshift-ansible-xodBcmC/openshift-examples.tar .", "failed": true, "msg": "[Errno 2] No such file or directory: 'tar'", "rc": 2}
```

This makes the assumption that the workstation running openshift-ansible is a permanent development workstation, and not (for example) a throwaway container running on another server.  While the role isn't complex or involved, it can fail for any of the following reasons:

* running ansible from read-only filesystem or share
* controlling client is very low on disk space
* tar not installed (as it is not in the Fedora Base Image)

Given this, the openshift-examples role should not be in the critical path for tasks which have to succeed in order for your openshift setup to succeed.  Here are my recommendations on ways to handle this, in desireability order:

1. remove openshift-examples from the playbooks and give it its own playbook so that users can choose to install the examples as a specific action if they want them.  Additionally, this could support installing the examples to a directory of the user's choosing instead of to the openshift-ansible tree.
2. add a parameter, install_openshift_examples, which turns on or off building the examples.
3. run openshift-examples but ignore any failures.

**Comment by detiber** [comment]
> running ansible from read-only filesystem or share

The files are created under /tmp, but we probably should respect the TMPDIR env var.

> controlling client is very low on disk space

I think the current variable `openshift_install_examples` covers this use case.

> tar not installed (as it is not in the Fedora Base Image)

We should most likely validate tar is available as a pre-req. We previously copied the files individually and it was horrendously slow, which is why we've resorted to using tar, which had been available on all platforms that we ran on (until now it seems).

**Comment by jberkus** [comment]
Ah, I searched the docs for that variable, and couldn't find it.  It's not in the page which covers the other install options.  Where is it?

**Comment by sdodson** [comment]
The example inventories in inventory/byo/ are generally the most up to date reference for config options. When you speak of docs do you mean docs.openshift.org or something internal to this repo?

**Comment by jberkus** [comment]
docs.openshift.org, yes.  Most of the options are detailed there.

**Comment by DanyC97** [comment]
@jberkus you mind closing the issue since answer been provided ? 

cc @vrutkovs candidate for closing as being stale issue

**Comment by vrutkovs** [comment]
Most options are described in `hosts.example`, docs.openshift.org issues should be filed against https://github.com/openshift/openshift-docs/
