### ISSUE TITLE
.../v3_2/upgrade.yml references files that do not exist

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-ansible#2949]
[playbooks/byo/openshift-cluster/upgrades/v3_2/upgrade.yml#L58-L65](https://github.com/openshift/openshift-ansible/blob/d4771b1a9a331393f5f4bf6c1cdf130637546c43/playbooks/byo/openshift-cluster/upgrades/v3_2/upgrade.yml#L58-L65) includes:

- include: ../../../../common/openshift-cluster/upgrades/pre.yml
- include: ../../../../common/openshift-cluster/upgrades/upgrade.yml
- include: ../../../../common/openshift-cluster/upgrades/post.yml

None of these 3 files exist.

@dgoodwin assigning it to you, as I think this was a missing part of the refactor in #2441.

I looked for an easy fix myself, but seems that the changes were more complex than I could follow in a reasonable amount of time.

**Comment by dgoodwin** [comment]
Unfortunately those were very complex changes, we decided awhile back to only support the latest in master though I tend to keep latest -1 active for my own purposes in testing more easily. These 3_2 playbooks were just forgotten and should be deleted.

If you have 3.1->3.2 upgrade needs just checkout the release-1.2 branch.

I will delete these and add a pr to close this issue.

**Comment by rhcarvalho** [comment]
Thanks @dgoodwin, deleting the whole thing from master would be delightful ;)
