### ISSUE TITLE
Playbook fails when only using private IP's

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/openshift-ansible#2960]
Playbook fails when we only use private ip's in our setup. 

##### Version
`v1.2.0` 
`ansible version: 2.1.0`

##### Steps To Reproduce
Installed + configured the prereqs on our environment. (docker, docker-storage-setup, ssh connection from master to nodes, install git, ansible, openssl, ...
After that we delete our networkinteface with the public ip's.  
We have 3 nic's left:
- docker0
- ens192
- lo

We edit the `/etc/ansible/hosts` which looks like this:
```
# host group for masters
[masters]
192.168.20.1

# host group for etcd
[etcd]
192.168.20.1

# host group for nodes, includes region info
[nodes]
192.168.20.1
192.168.20.2
```
Now I launch the playbook:
`ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml`

##### Current Result
```
...
TASK [openshift_facts : Ensure PyYaml is installed] ****************************
ok: [192.168.20.1]
ok: [192.168.20.2]

TASK [openshift_facts : Ensure yum-utils is installed] *************************
ok: [192.168.20.2]
ok: [192.168.20.1]

TASK [openshift_facts : Gather Cluster facts and set is_containerized if needed] ***
fatal: [192.168.20.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_7lfdJ7/ansible_module_openshift_facts.py\", line 2130, in <module>\r\n    main()\r\n  File \"/tmp/ansible_7lfdJ7/ansible_module_openshift_facts.py\", line 2111, in main\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_7lfdJ7/ansible_module_openshift_facts.py\", line 1589, in __init__\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_7lfdJ7/ansible_module_openshift_facts.py\", line 1622, in generate_facts\r\n    defaults = self.get_defaults(roles, deployment_type)\r\n  File \"/tmp/ansible_7lfdJ7/ansible_module_openshift_facts.py\", line 1665, in get_defaults\r\n    ip_addr = self.system_facts['default_ipv4']['address']\r\nKeyError: 'address'\r\n", "msg": "MODULE FAILURE", "parsed": false}
fatal: [192.168.20.2]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_A7Bz2D/ansible_module_openshift_facts.py\", line 2130, in <module>\r\n    main()\r\n  File \"/tmp/ansible_A7Bz2D/ansible_module_openshift_facts.py\", line 2111, in main\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_A7Bz2D/ansible_module_openshift_facts.py\", line 1589, in __init__\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_A7Bz2D/ansible_module_openshift_facts.py\", line 1622, in generate_facts\r\n    defaults = self.get_defaults(roles, deployment_type)\r\n  File \"/tmp/ansible_A7Bz2D/ansible_module_openshift_facts.py\", line 1665, in get_defaults\r\n    ip_addr = self.system_facts['default_ipv4']['address']\r\nKeyError: 'address'\r\n", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************

##### Expected Result
Playbook works.

##### Additional Information
Centos7 + we have our own registry (also in the 192 network) where we will pull from so normally we don't need internet acces.

```

**Comment by sdodson** [comment]
The key here is the lack of ansible.default_ipv4.address

**Comment by sdodson** [comment]
@lorenzvth7 I doubt it will improve the situation, but we require ansible-2.2 and we should make sure to test with the latest code from release-1.2 branch.

**Comment by lorenzvth7** [comment]
@sdodson I've now ansible-2.2 (the newest). Also newest git clone from the openshift repo.
I used the same hosts file to start the playbooK.

```
TASK [openshift_facts : Gather Cluster facts and set is_containerized if needed] ***
fatal: [192.168.20.2]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 192.168.20.2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_SPOBxJ/ansible_module_openshift_facts.py\", line 2374, in <module>\r\n    main()\r\n  File \"/tmp/ansible_SPOBxJ/ansible_module_openshift_facts.py\", line 2361, in main\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_SPOBxJ/ansible_module_openshift_facts.py\", line 1832, in __init__\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_SPOBxJ/ansible_module_openshift_facts.py\", line 1869, in generate_facts\r\n    defaults = self.get_defaults(roles, deployment_type, deployment_subtype)\r\n  File \"/tmp/ansible_SPOBxJ/ansible_module_openshift_facts.py\", line 1912, in get_defaults\r\n    ip_addr = self.system_facts['ansible_default_ipv4']['address']\r\nKeyError: 'address'\r\n", "msg": "MODULE FAILURE"}
fatal: [192.168.20.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 192.168.20.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_JHGeHd/ansible_module_openshift_facts.py\", line 2374, in <module>\r\n    main()\r\n  File \"/tmp/ansible_JHGeHd/ansible_module_openshift_facts.py\", line 2361, in main\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_JHGeHd/ansible_module_openshift_facts.py\", line 1832, in __init__\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_JHGeHd/ansible_module_openshift_facts.py\", line 1869, in generate_facts\r\n    defaults = self.get_defaults(roles, deployment_type, deployment_subtype)\r\n  File \"/tmp/ansible_JHGeHd/ansible_module_openshift_facts.py\", line 1912, in get_defaults\r\n    ip_addr = self.system_facts['ansible_default_ipv4']['address']\r\nKeyError: 'address'\r\n", "msg": "MODULE FAILURE"}
```

**Comment by detiber** [comment]
@lorenzvth7 what is the output of `ip route` on your host? `ansible.default_ipv4.address` is only populated if there is a interface that provides a default route.

**Comment by lorenzvth7** [comment]
This is the output of `ip route`
```
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
192.168.20.0/24 dev ens192  proto kernel  scope link  src 192.168.20.1  metric 100
```

**Comment by lorenzvth7** [comment]
@detiber What do I need to do/change to let the playbook work?

**Comment by sdodson** [comment]
@lorenzvth7 if ens192 owned the default route 0.0.0.0/0 things would work and I don't think it would break anything in your environment.

**Comment by lorenzvth7** [comment]
@sdodson @detiber Is default route = default gateway?

**Comment by sdodson** [comment]
No, default is where all traffic without a more specific route goes, it should say "default" in the destination field like this first one.

```
[root@ose3-master origin]# ip route show
default via 192.168.122.1 dev ens3  proto static  metric 100 
10.128.0.0/14 dev tun0  proto kernel  scope link 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
172.40.0.0/16 dev tun0  scope link 
192.168.122.0/24 dev ens3  proto kernel  scope link  src 192.168.122.80 
192.168.122.0/24 dev ens3  proto kernel  scope link  src 192.168.122.80  metric 100 
```

**Comment by lorenzvth7** [comment]
@sdodson Thanks. With that info we were able to go further.
Now the playbook fails:
```
TASK [openshift_common : Install the base package for versioning] **************
fatal: [192.168.20.1]: FAILED! => {"changed": false, "failed": true, "msg": "Failure talking to yum: Cannot find a valid baseurl for repo: base/7/x86_64"}
```
This seems to be a sign we do need internet access during the install?

**Comment by detiber** [comment]
@lorenzvth7 internet access is not required, but there are potentially files from the base and extras repos that will need to be mirrored in order to complete an installation.

**Comment by lorenzvth7** [comment]
@detiber Will do some testing. Its probably better to use atomic instead of centos. Everything is installed there already.

**Comment by lorenzvth7** [comment]
@detiber @sdodson 
I was able to perform the installation of openshift `1.3.0` from an installer-server with ansible (centos 7.1) on an atomic machine (master + node) WITH internet. I took away the internet access of that server and reran the playbook. Now it fails here:
```
TASK [etcd : Pull etcd container] **********************************************
fatal: [192.168.80.129]: FAILED! => {"changed": false, "cmd": ["docker", "pull", "registry.access.redhat.com/rhel7/etcd"], "delta": "0:00:00.048291", "end": "2016-12-13 14:05:59.706911", "failed": true, "rc": 1, "start": "2016-12-13 14:05:59.658620", "stderr": "unable to ping registry endpoint https://registry.access.redhat.com/v0/\nv2 ping attempt failed with error: Get https://registry.access.redhat.com/v2/: dial tcp: lookup registry.access.redhat.com on 192.168.80.1:53: read udp 192.168.80.129:34204->192.168.80.1:53: read: connection refused\n v1 ping attempt failed with error: Get https://registry.access.redhat.com/v1/_ping: dial tcp: lookup registry.access.redhat.com on 192.168.80.1:53: read udp 192.168.80.129:46329->192.168.80.1:53: read: connection refused", "stdout": "Using default tag: latest\nTrying to pull repository registry.access.redhat.com/rhel7/etcd ... ", "stdout_lines": ["Using default tag: latest", "Trying to pull repository registry.access.redhat.com/rhel7/etcd ... "], "warnings": []}
```

But when I check the available images it seems for me that the image is still on the server:

> # docker images
> REPOSITORY                              TAG                 IMAGE ID            CREATED             SIZE
> registry.access.redhat.com/rhel7/etcd   latest              90e4b9a0686b        11 days ago         236.8 MB

**Comment by lorenzvth7** [comment]
@detiber @sdodson 
I was able to perform a full installation from one install server (centos) on one openshift-server (master&node) atomic host. The atomic host had internet connection.
After disabeling the internet connection I got this error:

```
TASK [etcd : Pull etcd container] **********************************************
fatal: [192.168.80.132]: FAILED! => {"changed": false, "cmd": ["docker", "pull", "registry.access.redhat.com/rhel7/etcd"], "delta": "0:00:00.046348", "end": "2016-12-13 16:03:43.323267", "failed": true, "rc": 1, "start": "2016-12-13 16:03:43.276919", "stderr": "unable to ping registry endpoint https://registry.access.redhat.com/v0/\nv2 ping attempt failed with error: Get https://registry.access.redhat.com/v2/: dial tcp: lookup registry.access.redhat.com on 192.168.80.1:53: read udp 192.168.80.132:42290->192.168.80.1:53: read: connection refused\n v1 ping attempt failed with error: Get https://registry.access.redhat.com/v1/_ping: dial tcp: lookup registry.access.redhat.com on 192.168.80.1:53: read udp 192.168.80.132:46917->192.168.80.1:53: read: connection refused", "stdout": "Using default tag: latest\nTrying to pull repository registry.access.redhat.com/rhel7/etcd ... ", "stdout_lines": ["Using default tag: latest", "Trying to pull repository registry.access.redhat.com/rhel7/etcd ... "], "warnings": []}
```

Now I've setup my own registry on the centos-server. It's able to pull images and the registry is running on my private network. So my openshift-server (also on that private network) is able to pull images. 

I've the following in my playbook:
`oreg_url=192.168.80.133/cluster/origin-${component}:v1.3.0`

That's my private registry and the place where I can store the images. This will probably work for the registry, router, and that kind of stuff AFTER the installation.

Is there a way to tell openshift to use the images from this registry DURING the installation? (for example: `docker pull registry.access.redhat.com/rhel7/etcd:latest` is inside my registry as 192.168.80.133/cluster/origin-etcd:v1.3.0

**Comment by detiber** [comment]
@lorenzvth7 yes, you can tell it to use a different registry, it would be easier if the registry was mirroring the images with the same projects/names, though.

If the registry provides a mirror, then you could add the following to your invengory:
```
openshift_docker_additional_registries=192.168.30.133
# if insecure registry only
openshift_docker_insecure_registries=192.168.30.133
oreg_url=192.168.30.133/origin/${component}:${version}
openshift_examples_modify_imagestreams=true
```

It is possible to override images pulled for components if not using a direct mirror, but it would take some digging to find the variables needed.

**Comment by lorenzvth7** [comment]
@detiber 
Set the env var already in the playbook but it's still complaining about `registry.access.redheat`

```
TASK [etcd : Pull etcd container] **********************************************
fatal: [192.168.80.132]: FAILED! => {"changed": false, "cmd": ["docker", "pull", "registry.access.redhat.com/rhel7/etcd"], "delta": "0:00:00.044171", "end": "2016-12-13 16:29:20.458963", "failed": true, "rc": 1, "start": "2016-12-13 16:29:20.414792", "stderr": "unable to ping registry endpoint https://registry.access.redhat.com/v0/\nv2 ping attempt failed with error: Get https://registry.access.redhat.com/v2/: dial tcp: lookup registry.access.redhat.com on 192.168.80.1:53: read udp 192.168.80.132:43916->192.168.80.1:53: read: connection refused\n v1 ping attempt failed with error: Get https://registry.access.redhat.com/v1/_ping: dial tcp: lookup registry.access.redhat.com on 192.168.80.1:53: read udp 192.168.80.132:60686->192.168.80.1:53: read: connection refused", "stdout": "Using default tag: latest\nTrying to pull repository registry.access.redhat.com/rhel7/etcd ... ", "stdout_lines": ["Using default tag: latest", "Trying to pull repository registry.access.redhat.com/rhel7/etcd ... "], "warnings": []}
```

**Comment by detiber** [comment]
@lorenzvth7 Ah, looks like the etcd image is hardcoded, instead of just using the default registry config. You can override that by setting `osm_etcd_image=192.168.30.133/cluster/origin-etcd:v1.3.0` in your inventory.

**Comment by lorenzvth7** [comment]
@detiber Thanks, that seemed to work for the etcd. Now I'm trying to pull the CLI image which is in my repo as `192.168.80.133/openshift/origin:v1.3.0`

`"stdout": "Trying to pull repository 192.168.30.133/openshift/origin ... \nPulling repository 192.168.30.133/openshift/origin\nError while pulling image: Get http://192.168.30.133/v1/repositories/openshift/origin/images`

My registry is secured with a selfsigned certificate. So I've put the `openshift_docker_insecure_registries` line in comment but it's still complaining.

**Comment by detiber** [comment]
@lorenzvth7 you'll probably need to add the certificate to the host, copying it to `/etc/docker/certs.d/192.168.30.133` on each of the hosts should do the trick.

**Comment by lorenzvth7** [comment]
@detiber 
Yeap, I already did that. As I described in the example above I was able to pull `192.168.80.133/openshift/origin:v1.3.0` but not `openshift/origin:v1.3.0` (while it seems to look in 192.168.30.133 too)

**Comment by lorenzvth7** [comment]
@detiber Okay sorry, my bad. Copied your instructions but `192.168.30.133` instead of `192.168.80.133`. Thanks

**Comment by detiber** [comment]
@lorenzvth7 doh, my fingers where moving faster than my eyes.

**Comment by lorenzvth7** [comment]
@detiber Haha. I will close this issue because everything is solved. Thanks for the great support.

**Comment by lorenzvth7** [comment]
@detiber Just one last question. Is there also a way to define the image of cockpit in the playbook? Default it's `cockpit/kubernetes:latest `.
Didn't found an option [here](https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.ose.example)
