### ISSUE TITLE
Example inventory file includes undefined group

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-ansible#2974]
```console
$ ansible -i inventory/byo/hosts.origin.example -m ping all
ERROR! Attempted to read "inventory/byo/hosts.origin.example" as ini file: inventory/byo/hosts.origin.example:7: Section [OSEv3:children] includes undefined group: nfs 
```

```console
$ ansible -i inventory/byo/hosts.ose.example -m ping all
ERROR! Attempted to read "inventory/byo/hosts.ose.example" as ini file: inventory/byo/hosts.ose.example:7: Section [OSEv3:children] includes undefined group: nfs
```

Granted that the examples are not meant to work ootb, would it make sense to include a dummy `[nfs]` group like there is `[lb]` and `[etcd]`, etc.?

If we put a stub for every group, people starting off the example inventory should be able to update the host list and be good to go.

//cc @abutcher

**Comment by sdodson** [comment]
I think that's fine, we just need to make sure wherever we're using groups we're checking not for the group's existence but for length > 0. I ran into this a bit while trying to implement implicit etcd group members.
