### ISSUE TITLE
etcd container doesn't start

### ISSUE THREAD

**Issue by bdurrow** [openshift/openshift-ansible#2978]
Because of https://bugzilla.redhat.com/show_bug.cgi?id=1392611 etcd container doesn't start.  The master api doesn't start completely so the check for master api readiness fails and the playbook doesn't complete.

##### Version
bst:openshift-ansible brad$ git describe
openshift-ansible-3.3.57-1-12-g0553bdb

bst:openshift-ansible brad$ ansible --version
ansible 2.1.1.0
  config file = /Users/brad/.ansible.cfg
  configured module search path = Default w/o overrides

[brad@ose33-master-c1b-01 ~]$ rpm -qa | fgrep docker
docker-common-1.10.3-46.el7.centos.14.x86_64
docker-selinux-1.10.3-46.el7.centos.14.x86_64
docker-1.10.3-46.el7.centos.14.x86_64

##### Steps To Reproduce
Unless it is necessary I don't really want to take the time to redact my inventory file to post here.  I'm not sure if it is relevant but I made the following changes to the git sandbox 

bst:openshift-ansible brad$ git diff -u roles/openshift_hosted/tasks/registry/storage/object_storage.yml
diff --git a/roles/openshift_hosted/tasks/registry/storage/object_storage.yml b/roles/openshift_hosted/tasks/registry/storage/object_storage.yml
index 7b1b3f6..5667059 100644
--- a/roles/openshift_hosted/tasks/registry/storage/object_storage.yml
+++ b/roles/openshift_hosted/tasks/registry/storage/object_storage.yml
@@ -2,7 +2,7 @@
     msg: >
       Object Storage Provider: {{ openshift.hosted.registry.storage.provider }}
       is not currently supported
-  when: openshift.hosted.registry.storage.provider not in ['azure_blob', 's3', 'swift']
+  when: openshift.hosted.registry.storage.provider not in ['azure_blob', 's3', 'swift', 'gcs']

 - fail:
     msg: >
@@ -13,6 +13,9 @@
 - include: s3.yml
   when: openshift.hosted.registry.storage.provider == 's3'

+- include: gcs.yml
+  when: openshift.hosted.registry.storage.provider == 'gcs'
+
 - name: Test if docker registry config secret exists
   command: >
     {{ openshift.common.client_binary }}

bst:openshift-ansible brad$ cat roles/openshift_hosted/tasks/registry/storage/gcs.yml
---
- fail:
    msg: >
      openshift_hosted_registry_storage_gcs_bucket is required
  when: openshift.hosted.registry.storage.gcs.bucket | default(none) is none

After preparing the vms using gcloud instance create commands I run this command:
ansible-playbook -i inventory/hosts playbooks/byo/config.yml

All commands below are run from the "first" master.

##### Current Result
[brad@ose33-master-c1b-01 selinux]$ sudo service etcd_container start; sleep 1; sudo service etcd_container status -l
Redirecting to /bin/systemctl start  etcd_container.service
Redirecting to /bin/systemctl status  -l etcd_container.service
● etcd_container.service - The Etcd Server container
   Loaded: loaded (/etc/systemd/system/etcd_container.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2016-12-14 15:42:15 UTC; 172ms ago
  Process: 26128 ExecStop=/usr/bin/docker stop etcd_container (code=exited, status=1/FAILURE)
  Process: 26074 ExecStart=/usr/bin/docker run --name etcd_container --rm -v /var/lib/etcd:/var/lib/etcd:z -v /etc/etcd:/etc/etcd:z --env-file=/etc/etcd/etcd.conf --net=host --entrypoint=/usr/bin/etcd registry.access.redhat.com/rhel7/etcd (code=exited, status=126)
  Process: 26069 ExecStartPre=/usr/bin/docker rm -f etcd_container (code=exited, status=1/FAILURE)
 Main PID: 26074 (code=exited, status=126)

Dec 14 15:42:15 ose33-master-c1b-01 systemd[1]: etcd_container.service: control process exited, code=exited status=1
Dec 14 15:42:15 ose33-master-c1b-01 systemd[1]: Unit etcd_container.service entered failed state.
Dec 14 15:42:15 ose33-master-c1b-01 systemd[1]: etcd_container.service failed.

[brad@ose33-master-c1b-01 selinux]$ sudo /usr/bin/docker-current run --name etcd_container --rm -v /var/lib/etcd:/var/lib/etcd:z -v /etc/etcd:/etc/etcd:z --env-file=/etc/etcd/etcd.conf --net=host --entrypoint=/usr/bin/etcd registry.access.redhat.com/rhel7/etcd
permission denied
docker: Error response from daemon: Container command could not be invoked..

[brad@ose33-master-c1b-01 selinux]$ sudo tail -50 /var/log/audit/audit.log | fgrep denied
type=AVC msg=audit(1481730249.844:20131): avc:  denied  { transition } for  pid=27630 comm="exe" path="/usr/bin/etcd" dev="dm-7" ino=12742666 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:system_r:svirt_lxc_net_t:s0:c218,c223 tclass=process
type=AVC msg=audit(1481730255.881:20147): avc:  denied  { transition } for  pid=27698 comm="exe" path="/usr/bin/etcd" dev="dm-7" ino=12742666 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:system_r:svirt_lxc_net_t:s0:c923,c988 tclass=process
type=AVC msg=audit(1481730261.811:20158): avc:  denied  { transition } for  pid=27766 comm="exe" path="/usr/bin/etcd" dev="dm-7" ino=12742666 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:system_r:svirt_lxc_net_t:s0:c261,c614 tclass=process

##### Expected Result
[brad@ose33-master-c1b-01 selinux]$ sudo service etcd_container start; sleep 1; sudo service etcd_container status -l
Redirecting to /bin/systemctl start  etcd_container.service
Redirecting to /bin/systemctl status  -l etcd_container.service
● etcd_container.service - The Etcd Server container
   Loaded: loaded (/etc/systemd/system/etcd_container.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-12-14 15:46:27 UTC; 17s ago
  Process: 29259 ExecStop=/usr/bin/docker stop etcd_container (code=exited, status=1/FAILURE)
  Process: 29522 ExecStartPre=/usr/bin/docker rm -f etcd_container (code=exited, status=1/FAILURE)
 Main PID: 29527 (docker-current)
   Memory: 8.0M
   CGroup: /system.slice/etcd_container.service
           └─29527 /usr/bin/docker-current run --name etcd_container --rm -v /var/lib/etcd:/var/lib/etcd:z -v /etc/etcd:/etc/etcd:z --env-file=/etc/etcd/etcd.conf --net=host --entrypoint=/usr/bin/etcd registry.access.redhat.com/rhel7/etcd

Dec 14 15:46:30 ose33-master-c1b-01 etcd_container[29527]: 2016-12-14 15:46:30.344827 I | raft: newRaft ea91f92766c1e40c [peers: [766db541aea762cb,cb85ca3d71f67687,ea91f92766c1e40c], term: 5, commit: 113311, applied: 110011, lastindex: 113311, lastterm: 5]
Dec 14 15:46:30 ose33-master-c1b-01 etcd_container[29527]: 2016-12-14 15:46:30.345547 I | etcdserver: added member 766db541aea762cb [https://10.142.4.1:2380] to cluster dcf40809bb48cc6c from store
Dec 14 15:46:30 ose33-master-c1b-01 etcd_container[29527]: 2016-12-14 15:46:30.345559 I | etcdserver: added member cb85ca3d71f67687 [https://10.128.4.2:2380] to cluster dcf40809bb48cc6c from store
Dec 14 15:46:30 ose33-master-c1b-01 etcd_container[29527]: 2016-12-14 15:46:30.345565 I | etcdserver: added member ea91f92766c1e40c [https://10.128.4.1:2380] to cluster dcf40809bb48cc6c from store
Dec 14 15:46:30 ose33-master-c1b-01 etcd_container[29527]: 2016-12-14 15:46:30.345575 I | etcdserver: set the cluster version to 2.3 from store
Dec 14 15:46:30 ose33-master-c1b-01 etcd_container[29527]: 2016-12-14 15:46:30.349966 I | etcdserver: starting server... [version: 2.3.7, cluster version: 2.3]
Dec 14 15:46:30 ose33-master-c1b-01 etcd_container[29527]: 2016-12-14 15:46:30.569670 I | raft: raft.node: ea91f92766c1e40c elected leader cb85ca3d71f67687 at term 5
Dec 14 15:46:30 ose33-master-c1b-01 etcd_container[29527]: 2016-12-14 15:46:30.575404 I | rafthttp: the connection with cb85ca3d71f67687 became active
Dec 14 15:46:30 ose33-master-c1b-01 etcd_container[29527]: 2016-12-14 15:46:30.604109 I | rafthttp: the connection with 766db541aea762cb became active
Dec 14 15:46:30 ose33-master-c1b-01 etcd_container[29527]: 2016-12-14 15:46:30.734439 I | etcdserver: published {Name:ose33-master-c1b-01.c.openshift-dev-01.internal ClientURLs:[https://10.128.4.1:2379]} to cluster dcf40809bb48cc6c

##### Additional Information

Note, I downloaded the source rpm and looked at the selinux policy module for docker and found this:

[brad@ose33-master-c1b-01 docker-selinux-032bcda7b1eb6d9d75d3c0ce64d9d35cdb9c7b85]$ fgrep bin docker.fc
/usr/bin/docker.*		--	gen_context(system_u:object_r:docker_exec_t,s0)
/usr/bin/docker-latest			--	gen_context(system_u:object_r:docker_exec_t,s0)
/usr/bin/docker-novolume-plugin		--	gen_context(system_u:object_r:docker_auth_exec_t,s0)

If I read the man page correctly this should apply the correct label to /usr/bin/docker-current but it doesn't.

[brad@ose33-master-c1b-01 ~]$ matchpathcon /usr/bin/docker-current
/usr/bin/docker-current	system_u:object_r:bin_t:s0

This resolves the problem:
[brad@ose33-master-c1b-01 selinux]$ sudo chcon -t docker_exec_t /usr/bin/docker*
[brad@ose33-master-c1b-01 selinux]$ sudo service docker restart
Redirecting to /bin/systemctl restart  docker.service

**Comment by sdodson** [comment]
@bdurrow I think the fix for that simply to upgrade docker and docker-selinux (which will install container-selinux) when also upgrading to Centos 7.3. Can you try that?

**Comment by bdurrow** [comment]
Running yum upgrade to update to Centos 7.3 didn't appear to help:

[brad@ose33-master-c1b-01 selinux]$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[brad@ose33-master-c1b-01 selinux]$ sudo yum upgrade docker docker-selinux
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.steadfast.net
 * extras: repos.forethought.net
 * updates: mirror.tzulo.com
No packages marked for update
[brad@ose33-master-c1b-01 selinux]$ rpm -qa | fgrep docker
docker-common-1.10.3-46.el7.centos.14.x86_64
docker-selinux-1.10.3-46.el7.centos.14.x86_64
docker-1.10.3-46.el7.centos.14.x86_64
[brad@ose33-master-c1b-01 selinux]$ rpm -q container-selinux
package container-selinux is not installed
[brad@ose33-master-c1b-01 selinux]$ sudo yum search container-selinux
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.steadfast.net
 * extras: repos.forethought.net
 * updates: mirror.tzulo.com
Warning: No matches found for: container-selinux
No matches found
[brad@ose33-master-c1b-01 selinux]$ sudo yum info docker-selinux
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.steadfast.net
 * extras: repos.forethought.net
 * updates: mirror.tzulo.com
Installed Packages
Name        : docker-selinux
Arch        : x86_64
Version     : 1.10.3
Release     : 46.el7.centos.14
Size        : 27 k
Repo        : installed
From repo   : extras
Summary     : SELinux policies for Docker
URL         : https://github.com/docker/docker
License     : ASL 2.0
Description : SELinux policy modules for use with Docker.

When I look at the repo I don't see a newer version than the one that is installed.  I looked at these two locations:
http://mirror.centos.org/centos/7/extras/x86_64/Packages/
http://mirror.centos.org/centos/7.3.1611/extras/x86_64/Packages/

There is also no package for container-selinux at those locations.

After a reboot I still get:
[brad@ose33-master-c1b-01 ~]$ sudo yum upgrade
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.steadfast.net
 * extras: repos.forethought.net
 * updates: mirror.tzulo.com
No packages marked for update
[brad@ose33-master-c1b-01 ~]$ matchpathcon -V /usr/bin/docker-current
/usr/bin/docker-current has context system_u:object_r:docker_exec_t:s0, should be system_u:object_r:bin_t:s0

**Comment by vanloswang** [comment]
@bdurrow  maybe https://bugzilla.redhat.com/show_bug.cgi?id=1392611 will help. I meet the issue https://bugs.centos.org/view.php?id=12411, and fix by set the right selinux label.

**Comment by sdodson** [comment]
It looks like docker-1.10.3-59 and other packages were pushed into Centos extras repo yesterday, if you upgrade to those is the problem resolved?
