### ISSUE TITLE
dedicated build nodes feature should be surfaced in the installer

### ISSUE THREAD

**Issue by jeremyeder** [openshift/openshift-ansible#2984]
I heard that 3.4 has a dedicated build node capability, but that it is a manual procedure.  Please surface this capability in the installer.

**Comment by sdodson** [comment]
Link to docs describing that functionality?

**Comment by jeremyeder** [comment]
I heard this from Steve Speicher.  Will ping him.

**Comment by jeremyeder** [comment]
Got an out of office reply from Steve.

**Comment by jeremyeder** [comment]
@sdodson @detiber docs are here: https://docs.openshift.org/latest/install_config/build_defaults_overrides.html

/cc @bparees 

I believe at minimum, the installer needs to be taught to set a taint on nodes somehow.

**Comment by bparees** [comment]
for configuring the build defaulter/override behavior via ansible, we're going to do this:
https://trello.com/c/LsaA9CN2

but setting up appropriate taints on the nodes falls outside the scope of that card (hence @jeremyeder's ask)

**Comment by bparees** [comment]
@jeremyeder it looks like you should already be able to do this by setting the openshift_builddefaults_json:

https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example#L619
