### ISSUE TITLE
Cannot add a new node to an existing cluster

### ISSUE THREAD

**Issue by fesenko** [openshift/openshift-ansible#2991]
Hi there,

I created a cluster with the following configuration:

- one master;
- two compute nodes;
- one infra node.

I need to add a new compute node to the existing cluster. When I run the command 
`ansible-playbook -i inventory/aws/hosts  -e 'cluster_id=ocs-cluster cluster_env=dev deployment_type=origin' playbooks/aws/openshift-cluster/add_nodes.yml` I get the error:

> 
> ERROR! 'vars_files' is not a valid attribute for a PlaybookInclude
> 
> The error appears to have been in '/root/openshift-ansible/playbooks/aws/openshift-cluster/scaleup.yml': line 20, column 3, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
> - include: ../../common/openshift-cluster/scaleup.yml
>   ^ here

ansible 2.2.0.0;
the branch is  release-1.4.

Please help me.

**Comment by fesenko** [comment]
@sdodson 

Hi Scott, do you know who can help me with that? Thanks

**Comment by sdodson** [comment]
@lhuard1A can you take a look at this? needs conversion similar to #1862

**Comment by mazzystr** [comment]
I've been successful in scaling up OpenShift nodes in AWS numerous times.

Try this procedure....
Add an element called new_nodes to [OSEv3:children]
Then create a new key called [new_nodes:children]
Then add additional nodes as elements to [new_nodes:children]
I'm not kidding ... it literally called new_nodes

Then run play ./common/openshift-cluster/scaleup.yml
When scaleup is complete OpenShift should have the new nodes registered.  Confirm via oc get nodes.

Finally...
Move the elements of [new_nodes:children] to [nodes:children]
Delete [OSEv3:children].new_nodes and [new_nodes:children]

**Comment by fesenko** [comment]
@mazzystr 
Hi Chris,

Thank you for your reply. Which file I should work with? I don't have /etc/ansible/hosts on my ansible host.
