### ISSUE TITLE
Define nodeselector for openshift-infra project in playbook

### ISSUE THREAD

**Issue by MaxCCC** [openshift/openshift-ansible#2994]
Is there a way to define on which node you want to deploy your openshift-infra (metrics) project?

##### Version
Ansible 2.2
OpenShift Origin v1.3.0

##### Steps To Reproduce
Searching for a way how to deploy the openshift-infra project on node with label infra.
Tried but did not help:
`openshift-infra': {'default_node_selector': 'region=infra'}`
For the logging project I found a way:
```
openshift_hosted_logging_kibana_nodeselector="region=infra"
openshift_hosted_logging_curator_nodeselector="region=infra"
openshift_hosted_logging_elasticsearch_nodeselector="region=infra"
openshift_hosted_logging_fluentd_nodeselector="region=primary"
```
 
##### Current Result
hawkular, heapster etc are deployed on random nodes.

##### Expected Result
Deploy all the pods inside the openshift-infra project on my nodes with label:infra

##### Additional Information
I know it's possible to change the node selector of the namespace of my project and redeploy everything after that but I'm searching for a more generic way.

**Comment by lorenzvth7** [comment]
+1

**Comment by ljuaneda** [comment]
+1

**Comment by mazzystr** [comment]
+1

**Comment by andreas-kowasch** [comment]
+1

**Comment by davivcgarcia** [comment]
+1
