### ISSUE TITLE
Support for docker-latest (1.12)

### ISSUE THREAD

**Issue by jam13** [openshift/openshift-ansible#2997]
My understanding is that openshift _should_ run on 1.12 and that's going to become a requirement, if not in 3.4 then soon after. At the moment I can't see how this is possible, as whilst RHEL/Centos 7.3 now ships docker 1.12, it's called docker-latest and operates as a completely separate package to docker, only sharing a run folder.

https://access.redhat.com/articles/2317361

I've not found any workaround for this yet, and from what I can see it's going to require quite a few changes to systemd and other config files to support it.

##### Version
openshift-ansible master
ansible v2.2.0

##### Steps To Reproduce
Setup nodes with docker-latest rather than docker.

##### Current Result
Installer doesn't see docker v1.12

##### Expected Result
Installer recognises docker-latest package and makes appropriate changes to the config to support it.

##### Additional Information
Centos 7.3

**Comment by sdodson** [comment]
That's correct. OCP 3.4, as far as a Red Hat supported configuration is concerned, will require docker-1.12. Prior to OCP 3.4 launch docker will be updated in RHEL and Centos to be version 1.12 and once that's done we'll merge #2786

It'd be nice to update openshift-ansible to allow the use of docker-latest but I'm not sure we'll get time to implement that, we're happy to review a pull request for that though.

**Comment by andrewklau** [comment]
@sdodson hmm rhel atomic 7.3.1 only supports 1.10.3-59 https://access.redhat.com/articles/2317361 

So docker-latest is a dependency for upgrading to 1.4/3.4 (?)

**Comment by sdodson** [comment]
@andrewklau RHEL Atomic 7.3.2 has docker-1.12. Sorry for the delay in getting back.
