### ISSUE TITLE
var 'openshift_enable_origin_repo' not work

### ISSUE THREAD

**Issue by lirenjiede** [openshift/openshift-ansible#3002]
var 'openshift_enable_origin_repo' can not work well

I just use openshift-ansible 1.4 to install openshift. And I set the var 'openshift_enable_origin_repo' as false at inventory file. But I find that the yum repo file 'openshift-ansible-centos-paas-sig.repo' copy to target machine.
I expect that the openshift origin repo file don't transfer to target machine.

My operating system and version, Centos7.

**Comment by loa** [comment]
I can confirm and believe it's the same issue in #2972

**Comment by abutcher** [comment]
Closing this as a duplicate issue. I've opened #3033 to fix. Thanks!
