### ISSUE TITLE
dnsmasq does not serve PTR records, making nodes not compliant with Kube DNS

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#3017]
The default dnsmasq configuration on the node does not appear to support PTR records - I discovered this while debugging e2e failures against a GCE cluster.

```
# on the master, direct to skydns
$ dig @localhost -p 8053 +tcp +search 89.65.30.172.in-addr.arpa. PTR
...
;; ANSWER SECTION:
89.65.30.172.in-addr.arpa. 30	IN	PTR	test-service-2.e2e-tests-dns-h04r3.svc.cluster.local.

# on the master, direct to dnsmasq
$ dig @10.128.0.2 +tcp +search 89.65.30.172.in-addr.arpa. PTR
; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3 <<>> @10.128.0.2 +tcp +search 89.65.30.172.in-addr.arpa. PTR
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 48864
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;89.65.30.172.in-addr.arpa.	IN	PTR

;; AUTHORITY SECTION:
30.172.in-addr.arpa.	30	IN	SOA	ns.global.gcedns-prod.internal. cloud-dns-hostmaster.google.com. 2015030600 7200 3600 24796800 5
```

This means we are not spec compliant with upstream.  It looks like we need to specify a ptr-address record in dnsmasq, but not sure (I would have expected it to pass that question along to the master, though).

**Comment by smarterclayton** [comment]
@sdodson

**Comment by sdodson** [comment]
How do you deal with CIDRs?

**Comment by smarterclayton** [comment]
Not sure what you mean.  The master will answer certain PTR questions and not others - PTR for both services (services cidr) and pods (pod cidrs), but that is a consequence of the API results, not from the base config.  I.e. if you had a service or pod IP outside of the default CIDRs, the masters would answer it still.

**Comment by smarterclayton** [comment]
We can potentially punt this from 1.5 if we can fix it in 1.6.  It's not a regression per se (it regressed in 1.4).

**Comment by sdodson** [comment]
Leaving as P1, setting milestone as 1.6.

**Comment by apupier** [comment]
Do you have a workaround for this issue?

**Comment by sdodson** [comment]
@apupier you'd need to configure the node's dnsBindAddress and point dnsmasq at that rather than at the kube service ip. That's all manual at this point, that cannot be done via openshift-ansible today.

**Comment by travisrogers05** [comment]
@sdodson How would someone on 1.4 get around this?  Where do they set dnsBindAddress and does dnsmasq config have to be altered on each node?

**Comment by travisrogers05** [comment]
Is there a workaround for this issue?

**Comment by sdodson** [comment]
I have not tested this, so please verify this before rolling it out to your environment.

In /etc/origin/node/node-config.yaml set these two variables, the second list of nameservers to use for recursion is important because /etc/resolv.conf will be pointing at dnsmasq so you need to break the loop, otherwise the node's dns server will attempt to use dnsmasq too. see https://github.com/openshift/origin/pull/12805/files#diff-a44510486e42f2dc94701ffcf68584ceR536

```
dnsBindAddress: 0.0.0.0.8054
dnsNameservers:
 - 2.2.2.2
 - 4.4.4.4
```

Then set this in /etc/dnsmasq.d/origin-dns-ptr.conf to send PTR queries to the node's dns server
```
server=/in-addr.arpa/127.0.0.1#8054
```

You should not need to alter firewall rules or anything else. I'm interested to hear how/if this works for anyone.

**Comment by travisrogers05** [comment]
I've tried this workaround with no success.  See https://bugzilla.redhat.com/show_bug.cgi?id=1420121 for more details.
