### ISSUE TITLE
QUESTION: Only one load balancer can be installed for HA masters?

### ISSUE THREAD

**Issue by xiaoping378** [openshift/openshift-ansible#3019]
i didn't find the solution of installing multiple HAProxy load balancers, this project can install only one lb?

**Comment by mazzystr** [comment]
I have multiple HAProxy routers installed and things route correctly.

Set the following in the Ansible hosts file under [OSEv3:vars]...
openshift_master_default_subdomain=abc.example.com

Then deploy routers in the following manner...
[OSEv3:children]
routers

[routers:children]
<some static hostname or cloud_provider tag>

[routers:vars]
openshift_hosted_router_selector="$key=$value"
openshift_hosted_router_replicas=[0-9]+
openshift_hosted_router_force_subdomain='def.abc.example.com'


Just make sure that you've deployed nodes with label "$key=$value"
