### ISSUE TITLE
Install default CNI plugins when os_sdn_network_plugin_name=cni?

### ISSUE THREAD

**Issue by ozdanborne** [openshift/openshift-ansible#3022]
According to the [k8s docs](http://kubernetes.io/docs/admin/network-plugins/#cni):

>Kubernetes requires the standard CNI `lo` plugin, at minimum version 0.2.0

I'm thinking it would make sense for openshift-ansible to download and install the `loopback` plugin when `os_sdn_network_plugin_name=cni`. Or even better - download all the default plugins?

**Comment by sdodson** [comment]
@djosborne sorry for the delay in getting to this, but loopback plugin is a standard kubernetes CNI plugin?
@dcbw Is this something we should be shipping in our openshift packages?

**Comment by djosborne** [comment]
@sdodson Yes. For example, `registry-console-1-deploy` fails to deploy when networking mode is set to CNI:

`oc describe pod registry-console-1-deploy` shows the following:
```
Error syncing pod, skipping: failed to "SetupNetwork" for "registry-console-1-deploy_default" with SetupNetworkError: "Failed to setup network for pod \"registry-console-1-deploy_default(e89d0b14-0391-11e7-a4da-42010af0003e)\" using network plugins \"cni\": failed to find plugin \"loopback\" in path [/opt/loopback/bin /opt/cni/bin]; Skipping pod"
```
