### ISSUE TITLE
etcd host is binding to wrong IP / interface

### ISSUE THREAD

**Issue by ozdanborne** [openshift/openshift-ansible#3024]
I am using openshift-ansible with a host dedicated to etcd, as seen in the following inventory file:
```
[OSEv3:children]
masters
nodes
etcd

[masters]
node1

[nodes]
node1

[etcd]
node2
```

Each host is a VM configured with 2 interfaces:
- eth0 is a NAT interface (VMs are **not** able to access one another using this address)
- eth1 is a private interface  (VMs **are** able to access one another using this address)

Hosts resolve their hostname and each other's hostnames to the eth1 addresses.

Masters and nodes are correctly running openshift services on the eth1 private addresses.

##### Version
- openshift-ansible-3.4.17-1-277-g3e5f338
- ansible 2.2.0.0

##### Current Result
- Etcd is running on eth0.
- Master seems to be correctly trying to access etcd at it's expected address (eth1)

##### Expected Result
Etcd should be running on eth1, the accessible address returned when doing a hostname lookup of the node.

##### Additional Information
- Centos-7

I've gotten around this by manually specifiying `openshift_ip` in my inventory file for the etcd host. However, I am then running into SSL certificate issues where the certificates are authorized only for the IP address and do not work when accessing etcd via the domain name. My hunch is that without specifiying `openshift_ip` the certificates might work, but I'm still investigating.

**Comment by vegai** [comment]
This seems to still be an issue. It happens for me when trying to provision boxes created with Vagrant.
