### ISSUE TITLE
openshift_image_tag=latest broken again

### ISSUE THREAD

**Issue by sjenning** [openshift/openshift-ansible#3045]
https://github.com/openshift/openshift-ansible/pull/2882 allowed for `openshift_image_tag=latest`.
I think is was broken shortly thereafter with https://github.com/openshift/openshift-ansible/pull/2855 afaict

```
deployment_type=origin
openshift_image_tag=latest
```

```
TASK [openshift_master_facts : set_fact] ***************************************
fatal: [origin-master.local.variantweb.net]: FAILED! => {"failed": true, "msg": "Unknown short_version atest"}
```

Looks like a code path is assuming the first character of the image tag is 'v' and removing it.

**Comment by abutcher** [comment]
Hey @sjenning, did you hit this with the master branch @ a specific commit?

**Comment by sjenning** [comment]
I pulled just before trying.  I was at b5bc26c at the time.

**Comment by abutcher** [comment]
@sjenning Thanks, I opened up #3055 if you wouldn't mind kicking the tires on it.

**Comment by sjenning** [comment]
@abutcher thanks! trying now
