### ISSUE TITLE
Nodes are not getting labelled at install

### ISSUE THREAD

**Issue by chmouel** [openshift/openshift-ansible#305]
I have this in my /etc/ansible/hosts  :

    [nodes]
    master.enoshift.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_hostname=master.enoshift.com openshift_public_hostname=enoshift.com
    node1.enoshift.com openshift_node_labels="{'region': 'primary', 'zone': 'east'}" openshift_hostname=node1.enoshift.com openshift_public_hostname=node1.enoshift.com
    node2.enoshift.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}" openshift_hostname=node2.enoshift.com openshift_public_hostname=node2.enoshift.com

and after install when running a oc get nodes my nodes are not getting labelled

    PLAY RECAP ********************************************************************
    localhost                  : ok=5    changed=0    unreachable=0    failed=0
    master.enoshift.com    : ok=94   changed=38   unreachable=0    failed=0
    node1.enoshift.com     : ok=43   changed=19   unreachable=0    failed=0
    node2.enoshift.com     : ok=43   changed=19   unreachable=0    failed=0

    root@master:~/openshift-ansible$ oc get nodes                                                                                                                           [
    NAME                      LABELS                                           STATUS
    master.enoshift.com   kubernetes.io/hostname=master.enoshift.com   Ready
    node1.enoshift.com    kubernetes.io/hostname=node1.enoshift.com    Ready
    node2.enoshift.com    kubernetes.io/hostname=node2.enoshift.com    Ready

Thanks

**Comment by aveshagarwal** [comment]
I am also seeing the same issue.

**Comment by brenton** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1235953

**Comment by spinolacastro** [comment]
I've a fix for it: https://github.com/openshift/openshift-ansible/pull/416/files

**Comment by brenton** [comment]
This should be reolved thanks to @spinolacastro.  Let us know if that's not the case.
