### ISSUE TITLE
Add test to ensure that generated module code matches source

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#3078]
So that we never potentially have mismatched generated and source module code for things like yedit we need to have a CI task to verify that generated code matches the source.

**Comment by detiber** [comment]
@sdodson @kwoodson probably need to add this to the root tox config rather than `make ci`, otherwise :+1: from me.

**Comment by kwoodson** [comment]
@sdodson @detiber 
I have the functionality in a PR currently.  I'll figure out how to add it to tox so that it runs as a part of the tests.

**Comment by kwoodson** [comment]
This is resolved in https://github.com/openshift/openshift-ansible/pull/3107
