### ISSUE TITLE
hostname local_fact set multiple times

### ISSUE THREAD

**Issue by ingvagabund** [openshift/openshift-ansible#3080]
#### Description
``Initialize host facts`` task [1] sets ``hostname`` once the ``openshift_facts`` is run. As a part of the role the ``hostname`` local fact is set [2]. If my humble interpretation of the playbook is correct, the ``hostname`` fact setting at [1] can be removed. Additionally, there could be more places where the ``hostname`` is set after the ``openshift_facts`` role as well.

[1] https://github.com/openshift/openshift-ansible/blob/e7c4a9410e88e2c18ba05fea067e5988f3b8ffa0/playbooks/common/openshift-cluster/initialize_facts.yml#L15
[2] https://github.com/openshift/openshift-ansible/blob/e7c4a9410e88e2c18ba05fea067e5988f3b8ffa0/roles/openshift_facts/tasks/main.yml#L27

##### Version
```
https://github.com/openshift/openshift-ansible, e7c4a9410e88e2c18ba05fea067e5988f3b8ffa0
```

**Comment by detiber** [comment]
@ingvagabund I believe the value set by initialize_facts is used prior to the openshift_facts role being run. @dgoodwin could probably provide some more insight.

**Comment by dgoodwin** [comment]
Came from https://github.com/openshift/openshift-ansible/commit/a939f5c518bbcbb1be0713781e2fd1f405c36751 but unfortunately commit doesn't clarify why, do you recall @abutcher ?
