### ISSUE TITLE
OpenShift uninstall leaves some configurations behind

### ISSUE THREAD

**Issue by myllynen** [openshift/openshift-ansible#3082]
From https://bugzilla.redhat.com/show_bug.cgi?id=1412559:

Description of problem:
I'm using the following stanza to finish cleaning up after uninstallation, I think removal some/all of these (perhaps except for docker) should be part of the real uninstall procedure:

	find \
	/var/lib/docker/*
        /etc/sysconfig/atomic-* \
        /etc/pki/ca-trust/source/anchors/openshift* \
        /etc/openvswitch /var/log/openvswitch \
        -maxdepth 1 -print 2> /dev/null | xargs rm -rf

Thanks.

Version-Release number of selected component (if applicable):
openshift-ansible-playbooks-3.3.54-1.git.0.61a1dee.el7.noarch

**Comment by gregswift** [comment]
It also leaves behind network interfaces.

```
[root@ip-10-2-1-19 ~]# nmcli
docker0: connected to docker0
	bridge, 02:42:17:FC:52:A1, sw, mtu 1500
	inet4 172.17.0.1/16

eth0: connected to System eth0
	ethernet (vif), 02:EA:B8:1B:75:4D, hw, mtu 9001
	ip4 default
	inet4 10.2.1.19/25
	inet6 fe80::ea:b8ff:fe1b:754d/64

vxlan_sys_4789: disconnected
	vxlan, 5A:21:73:DA:DE:01, sw, mtu 65470

lo: unmanaged
	loopback (unknown), 00:00:00:00:00:00, sw, mtu 65536

br0: unmanaged
	openvswitch, 2A:6B:34:E5:B5:49, sw, mtu 8951

ovs-system: unmanaged
	openvswitch, AE:E7:97:AE:A5:57, sw, mtu 1500

tun0: unmanaged
	openvswitch, D6:4E:48:48:4B:F4, sw, mtu 8951
```

I cleaned them out with:
```
 for device in br0 vxlan_sys_4789 ovs-system tun0; do nmcli device delete ${device}
```

Version-Release number of selected component (if applicable):
openshift-ansible-3.4.57-1-10-gbb7b9cd

**Comment by myllynen** [comment]
Thanks for pointing out the leftover interfaces.

>  for device in br0 vxlan_sys_4789 ovs-system tun0; do nmcli device delete ${device}; done

This (nor ip device delete dev ovs-system, for example) did not get rid of all the devices on all nodes, perhaps those should be cleaned up properly at an earlier stage when removing the related components.

**Comment by myllynen** [comment]
FWIW, my latest find stanza now looks like:

       find \
       /etc/ansible/facts.d/* \
       /var/lib/etcd \
       /var/lib/docker/* \
       /etc/sysconfig/atomic-* \
       /etc/pki/ca-trust/source/anchors/openshift* \
       /etc/openvswitch /var/log/openvswitch \
       /tmp/ansible* /tmp/openshift* /tmp/tmp* \
        -maxdepth 1 -print 2> /dev/null | xargs rm -rf

**Comment by gregswift** [comment]
That find doesn't work well if you've done the whole device-mapper thing with your docker config.
```
node-020 | FAILED | rc=123 >>
rm: cannot remove ‘/var/lib/docker/containers/79fd7a00ad43356e5c3365e9c811b276aa8f20b389493909b20f10a928359658/shm’: Device or resource busy
rm: cannot remove ‘/var/lib/docker/containers/98a9f265abcfe32a46ad192867c21664d3b35415cc5f5349ba46585e68c05616/secrets/kubernetes.io/serviceaccount’: Device or resource busy
```

So i did the cleanup you had, then rebooted the boxes, and then
```
rm -rf /var/lib/docker
lvremove /dev/vg/lv  #using real path obviously
> /etc/sysconfig/docker-storage #empty the file, otherwise it will think its already done
docker-storage-setup
```

**Comment by bbeaudoin** [comment]
Ran into issues on cleanup after upgrade/downgrade. Similar issues, did not scrub as cleanly as myllynen. Noticed iptables had stale rules from previous installations as well. If /etc/sysconfig/iptables is missing the installation won't run but it appears to work fine if that file is empty or truncated.

**Comment by myllynen** [comment]
FWIW, I've created a repo with some automation playbooks and scripts for OpenShift installation, there are few playbooks to help to complete uninstallation well. Ideally, of course, those wouldn't be needed but the OpenShift uninstallation playbook would do everything needed.

https://github.com/myllynen/openshift-automation-tools
https://github.com/myllynen/openshift-automation-tools/blob/master/conf/uninst.yml
https://github.com/myllynen/openshift-automation-tools/blob/master/conf/wipe-docker.yml
https://github.com/myllynen/openshift-automation-tools/blob/master/conf/wipe-nfs.yml

Thanks.
