### ISSUE TITLE
Unable to register RHEL during installation on GCE

### ISSUE THREAD

**Issue by kunallimaye** [openshift/openshift-ansible#3102]
#### Description

Installing OSE 3.3 on GCE using Mac OSX result in the following error message: 

> **subscription-manager** not found

```bash
# Environment to run the installation script
ansible-openshift $ export rhel_subscription_user=RHN-USERNAME
ansible-openshift $ export rhel_subscription_pass=RHN-PASSWORD
ansible-openshift $ export rhel_subscription_pool=RHN-POOL-NAME
ansible-openshift $ bin/cluster create gce clustername -t openshift-enterprise 
```
> Please note we donot set <kbd>rhel_subscription_server</kbd> environment variable

##### Version

```
VERSION INFORMATION HERE PLEASE
# ansible version
ansible 2.2.0.0
# git describe
openshift-ansible-3.4.17-1-380-g44d53dc
```

##### Steps To Reproduce
1. Open a terminal
2. $ git clone https://github.com/openshift/openshift-ansible
3. $ cd openshift-ansible
4. $ export rhel_subscription_user=RHN-USERNAME
5. $ export rhel_subscription_pass=RHN-PASSWORD
6. $ export rhel_subscription_pool=RHN-POOL-NAME
7. $ bin/cluster create gce clustername -t openshift-enterprise 

##### Expected Results
OpenShift cluster is created

##### Observed Results
We get *subscription-manager* not found on each master and node.

##### Additional Information

Installing subscription-manager fixes this issue

**Comment by detiber** [comment]
Closing since #3103 resolves this issue.
