### ISSUE TITLE
Add hook to run tasks before upgrade script moves to next node/master

### ISSUE THREAD

**Issue by wester55** [openshift/openshift-ansible#3115]
Problem: Using stock upgrade script cause upgrade run forward too quick. If pods are running special software (like GlusterFS) they need more time to come in order. Additionally, we want make cluster-wide or specific checks to ensure some state is back to normal (example: GlusterFS healed itself and all volumes are online).

Why important: Currently, there is no option to make upgrade success without breaking parts of cluster when you run complicated/converged/large amount of various projects on Openshift cluster. Because there is no checks upgrade process does on applications running on top of cluster, there is high chance something will break. 

Current solution: We use Ansible playbooks to pre-modify standard upgrade scriptin places where masters/nodes come online after upgrade. We add include for custom tasks which retry until some condition is met.

Suggested solution: Ansible upgrade script will check for predefined file existence.  This should happen in all related places (not only where nodes go online after upgrade, but also where masters may get online after upgrade, because sometimes we use masters as nodes too). The person would then populate this file with needed tasks  before upgrade starts.

**Comment by detiber** [comment]
@dgoodwin relevant to your interests.

**Comment by dgoodwin** [comment]
Starting to evolve in #3101.
