### ISSUE TITLE
Origin repo pulls old version

### ISSUE THREAD

**Issue by johnjelinek** [openshift/openshift-ansible#313]
Using the ansible playbook, it deployed a pre-1.0 version of openshift and the cli tools. Any updates on how to get the latest or upgrade my cluster?

**Comment by sdodson** [comment]
@johnjelinek The repo was just updated with 1.0.0 build, sorry for the delay.

https://copr.fedoraproject.org/coprs/maxamillion/origin-next/build/101711/

**Comment by sdodson** [comment]
@twiest This can be closed now that we've pushed a 1.0.0 origin build.

**Comment by johnjelinek** [comment]
Do I need to `systemctl restart openshift-master.service
openshift-node.service` after updating?

**Comment by sdodson** [comment]
Yes, it looks like you need to restart the services. I thought that was
happening automatically but I'll have to fix that assuming we determine it
to be safe to do so.

**Comment by twiest** [comment]
closing.
