### ISSUE TITLE
Where is the master's log?

### ISSUE THREAD

**Issue by johnjelinek** [openshift/openshift-ansible#314]
I looked in `/tmp` and in `var/log` but I don't see anything.

**Comment by sdodson** [comment]
It's logged to journald, which by default will send things to /var/log/messages.

I wrote an appendix for the training materials which details how to send the logs elsewhere, I'll look at making sure this gets into the formal documentation.

https://github.com/openshift/training/blob/master/beta-4-setup.md#appendix---infrastructure-log-aggregation

**Comment by sdodson** [comment]
You find what you needed?

**Comment by johnjelinek** [comment]
I did, thank you!



—

**Comment by priyanka5** [comment]
@sdodson @johnjelinek : do you know how to enable debug logs for openshift master?

**Comment by detiber** [comment]
@priyanka5 setting `openshift_master_debug_level` and re-running the ansible playbook will do the trick. 

If you wanted to do it manually, you would change the value for `--log-level` in `/etc/sysconfig/openshift-master`, if you are running HA masters, you'll want to modify `/etc/sysconfig/openshift-master-api` or `/etc/sysconfig/openshift-master-controllers` depending on whether you want to change it for the api or the controllers service.
