### ISSUE TITLE
Document openshift_node_local_quota_per_fsgroup in BYO inventories

### ISSUE THREAD

**Issue by bjpritch** [openshift/openshift-ansible#3162]
#### Description
The "openshift_node_local_quota_per_fsgroup" parameter looks to be available for use for managing perFsGroup node configuration (emptyDir quota). However, this parameter is not documented in the BYO inventories.

I haven't tested this parameter yet, so I don't know if it was intentional to leave it out as a non-supported configuration.

##### Version
Current 

##### Expected Results
If it's a supported parameter for installation, document in example inventories.

EDIT: wording

**Comment by abutcher** [comment]
`volumeConfig.localQuota.perFSGroup` is pretty restricted per https://docs.openshift.com/container-platform/3.4/install_config/master_node_configuration.html#node-configuration-files.

> Preliminary support for local emptyDir volume quotas, set this value to a resource quantity representing the desired quota per FSGroup, per node. (i.e. 1Gi, 512Mi, etc) Currently requires that the volumeDirectory be on an XFS filesystem mounted with the 'gquota' option, and the matching security context contraint’s fsGroup type set to 'MustRunAs'.
