### ISSUE TITLE
Upgrading from OCP 3.3 to 3.4 is missing latest ImageStreams/Templates

### ISSUE THREAD

**Issue by kurktchiev** [openshift/openshift-ansible#3168]
#### Description
After upgrading from 3.3 to 3.4 I was expecting to see the latest IS/Templates released in origin/ocp for php(7), mysql(5.7), ruby/etc/etc

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
root@osmaster0p:~:
----> ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

root@osmaster0p:~:
----> rpm -q atomic-openshift-utils openshift-ansible
atomic-openshift-utils-3.4.44-1.git.0.efa61c6.el7.noarch
openshift-ansible-3.4.44-1.git.0.efa61c6.el7.noarch
```

##### Steps To Reproduce
1. upgrade from 3.3.* to 3.4.*
2. look for latest IS that should be available 

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
Rhel 7.3
```

**Comment by tbielawa** [comment]
@ebalsumgo do you still have the logs from your upgrade? Can you search for `openshift_examples` and `openshift_hosted_templates` in it?

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-ansible/pull/3104 pulled in the latest, it just hasn't shipped yet

**Comment by ebalsumgo** [comment]
@tbielawa i do not have them unfortunately

@sdodson is there any sort of eta/timing on their release for 3.4? or at least if it IS planned to get them released with 3.4?

**Comment by sdodson** [comment]
@ebalsumgo Yeah, January 31st currently. In the mean time you could run these two commands to pull them right now.

`oc create -n openshift -f https://raw.githubusercontent.com/openshift/openshift-ansible/release-1.4/roles/openshift_examples/files/examples/v1.4/image-streams/image-streams-rhel7.json`
`oc update -n openshift -f https://raw.githubusercontent.com/openshift/openshift-ansible/release-1.4/roles/openshift_examples/files/examples/v1.4/image-streams/image-streams-rhel7.json`

**Comment by ebalsumgo** [comment]
well alright then... i guess it is good enough to close this?

**Comment by ebalsumgo** [comment]
one question, php 7 is not tagged as latest but mysql 5.7 is tagged as latest, that intentional?

**Comment by sdodson** [comment]
If someone has time I'd appreciate someone testing that upgrade playbooks do infact add the new image streams but I'm relatively certain they do.

**Comment by ebalsumgo** [comment]
one thing that just came up, because some of the new versions are tagged as latest and some are not, specifically mysql is tagget with latest, it inadvertently upgraded things. Not sure how that problem can be solved to be honest though :/

**Comment by ebalsumgo** [comment]
My guess here is playing the Relase Notes game and NOT tagging any of the new versions as latest for at least a few releases to give cluster admins a chance to work with their customers to upgrade to the latest images. We managed to crash our Red Hat SSO as the OCP tempaltes pull from :latest and I upgraded the ISs yesterday and mysql redeployed itself with 5.7 which you cant do without doing some upgrade steps.

**Comment by sdodson** [comment]
@ebalsumgo I'm not terribly familiar with image stream semantics, but what you're saying is that your build leveraged the latest image stream tag from php image stream and that the latest image stream tag previously pointed at 5.6 but was moved to 7.0 and that broke your application? To me it seems like it's unwise to ever use the latest image stream tag and you should stick with using a tag that's known to work before migrating your application to a new tag.

@bparees mind lending your expertise?

**Comment by bparees** [comment]
what @sdodson said pretty much covers it.  The "latest" imagestream tags are always going to follow whatever the latest version is, so when a new version gets introduced (like 7.0), latest is going to be updated to point to that.  If you want a stable version, you use the version specific tag (5.6, 7.0) not latest.

the tag even says as much:
https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-rhel7.json#L236

```
"Build and run PHP applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-php-container/blob/master/5.6/README.md.\n\nWARNING: By selecting this tag, your application will automatically update to use the latest version of PHP available on OpenShift, including major versions updates."
```

**Comment by bparees** [comment]
As for templates referencing latest, for the most part we try not to, but in the cases where we do, we are routinely testing those templates to ensure they work with the latest imagestreamtags, so i'd be curious which template you were using and how it was broken by the upgrade.

**Comment by ebalsumgo** [comment]
@sdodson @bparees you are both correct however, note that i said that the tag for the image comes from the official template, which requests :latest not a specific version :/ so problem is two fold.
1. Fix the official templates to not point to :latest
2. Any pre 3.4.0.x application will most likely get broken when the new IS get pushed as they are deployed from said templates which pointed them to :latest

Specifically the mysql template does this, PHP is acting properly and is pointing to a specific version, I have not gone through all the IS/templates yet so those two I can speak to as of right now only.

**Comment by bparees** [comment]
@ebalsumgo i think your response overlapped my second comment.

> Fix the official templates to not point to :latest

mysql template does now specify a version:
https://github.com/openshift/origin/blob/master/examples/db-templates/mysql-persistent-template.json#L85

https://github.com/openshift/origin/blob/master/examples/db-templates/mysql-persistent-template.json#L252

Whether that change came after 3.4 was cut, or 3.4 didn't pick up the new template for some reason, i'm not sure, but the latest mysql template is correct.

> Any pre 3.4.0.x application will most likely get broken when the new IS get pushed as they are deployed from said templates which pointed them to :latest

and unfortunately there's really nothing we can do about that at this point.

**Comment by ebalsumgo** [comment]
> and unfortunately there's really nothing we can do about that at this point.
I think at least a Release Note is warranted here, as any application that was deployed pre 3.4 will truly be broken as far as mysql is concerned. We just experienced it by breaking authentication to our production cluster due to the SSO mysql DC getting 5.7 and mangling the data in it, said deployment is a 3.3.x deployment. again, mysql is the only one I can speak outright as it just bit me, but seeing as how there are quite a large number of templates, some sort of a note that changes are happening from :latest to specific version and how to upgrade a legacy DC seem like something to be included in the RN at least or Errata upgrade notes. simple oc edit dc/$somedc (search :latest and replace with current version) pre-upgrade of cluster would have solved the problem had we known it was coming.

**Comment by bparees** [comment]
sure, a release note makes sense to warn people that some of the "latest" tags will be updated to point to new images and they should audit their resources for references to "latest" imagestreamtags.

**Comment by ebalsumgo** [comment]
I think with that and what @sdodson said about the release of the new templates around end of january we can close this issue?

**Comment by michaelryanmcneill** [comment]
@bparees @sdodson I just wanted to mention this again because it seems like it wasn't clear that this is an issue. php:5.6 is still marked as latest in the updated imagestreams tag, even though php:7.0 is the latest image available. Based off what @bparees said above that is incorrect.

> what @sdodson said pretty much covers it. The "latest" imagestream tags are always going to follow whatever the latest version is, so when a new version gets introduced (like 7.0), latest is going to be updated to point to that. If you want a stable version, you use the version specific tag (5.6, 7.0) not latest.

**Comment by bparees** [comment]
@michaelryanmcneill php:7.0 was not part of 3.4, it's part of 3.5, so i wouldn't expect the 3.4 imagestreams to include 7.0.
