### ISSUE TITLE
Installing Openshift Origin 1.4 using byo ansible script

### ISSUE THREAD

**Issue by baluyot** [openshift/openshift-ansible#3170]
#### Description

Provide a brief description of your issue here. For example:
I can't seem to install Openshift Origin 1.4 release using the advance installation instructions.
When I follow the advance installation instructions, clone this git project, switch to release-1.4 branch and run the command:

ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml

It always installs version 1.3

[root@origin openshift-ansible]# oc version
oc v1.3.3
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://oso.example.com:8443
openshift v1.3.3
kubernetes v1.3.0+52492b4

Am I doing something wrong?

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
[root@origin openshift-ansible]# ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

[root@origin openshift-ansible]# git describe
openshift-ansible-3.4.56-1

root@origin openshift-ansible]# rpm -q atomic-openshift-utils openshift-ansible
package atomic-openshift-utils is not installed
package openshift-ansible is not installed
```

##### Steps To Reproduce
1. clone this git repo and switch to release-1.4 branch
2. run the "advance installation" instructions using any of the multiple masters example.

##### Expected Results
Describe what you expected to happen.

```
I expect to be running Openshift Origin v1.4
```

##### Observed Results
Describe what is actually happening.

```
[root@origin openshift-ansible]# oc version
oc v1.3.3
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://oso.example.com:8443
openshift v1.3.3
kubernetes v1.3.0+52492b4
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
[root@origin openshift-ansible]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)
```

**Comment by abutcher** [comment]
Hey @baluyot, I don't think the 1.4 packages have hit repos yet. Looks like they're available in testing repos per https://github.com/openshift/openshift-ansible/issues/3095#issuecomment-274279189, so the installer is just running with the highest version available.

**Comment by dindinw** [comment]
Hi @baluyot, it there a way to enable the pass testing repo in the `config.yml` file? I have to change the `roles/openshift_repos/files/origin/repos/openshift-ansible-centos-paas-sig.repo` file to set `enable=1` manually , otherwise, every time my local yum repo file will be replaced by the file with `enable=0`, and the installation will be failed when try to install v1.4.1

**Comment by ubwa** [comment]
Hi @abutcher any updates as to when the 1.4.1 RPM's will hit the live repos?
