### ISSUE TITLE
Import Centos Image streams fails with proxy configured

### ISSUE THREAD

**Issue by aerialls** [openshift/openshift-ansible#3189]
#### Description

I think I've found another problem with the proxy. Only with the proxy configured, the step "Import Centos Image streams" is failing. 

##### Version

```
ansible 2.2.0.0
openshift-ansible-3.5.2-1-2-gc5a1e1e with patch from PR #3128 
```

##### Steps To Reproduce
1. Use the following configuration https://gist.github.com/aerialls/f45abab663233d5f2a63eda37d6f8789
2. Launch with `ansible-playbook playbooks/byo/config.yml`

##### Expected Results

The task `Import Centos Image streams` does not failed.

##### Observed Results

The task `Import Centos Image stream` is failing with the following message

```
fatal: [os01.foobar.com]: FAILED! => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-centos7.json"], "delta": "0:00:00.104231", "end": "2017-01-26 11:12:33.221646", "failed": true, "failed_when_result": true, "rc": 1, "start": "2017-01-26 11:12:33.117415", "stderr": "unable to connect to a server to handle \"imagestreamlists\": the server has asked for the client to provide credentials", "stdout": "", "stdout_lines": [], "warnings": []}
```

If the setup is run without the proxy configuration, this task does not failed. It's only with the proxy activated.

##### Additional Information

I'm using `CentOS Linux release 7.3.1611 (Core)` in a clean server.

**Comment by sdodson** [comment]
@aerialls what was the problem and solution?

**Comment by aerialls** [comment]
Sorry for the delay!

We tried many deployments on the same server with/without proxies. In the end, the server was not clean enough to by really sure of the scope of the problem. We decided to start again on a clean slate and the error was gone :)
