### ISSUE TITLE
openshift_logging does not create ES deploymentconfigs on image change

### ISSUE THREAD

**Issue by jcantrill** [openshift/openshift-ansible#3199]
Trying to install logging using the role 'openshift_logging' does not update the image to the ES DC after installing the logging stack.  This is because of the when statement in 'tasks/install_elasticsearch.yaml' which conditionally runs when the cluster is resized but does not take into account some of the other vars may have changed.

**Comment by jcantrill** [comment]
@ewolinetz I will have to test to confirm if #3202 fixed this issue.  It can be confirmed by:

1.  deploying
2. Modifying the image_version
3. deploy again.

assert new deployment image equals the desired image version.

**Comment by ewolinetz** [comment]
i just verified that the image version will change, closing as resolved by #3202
