### ISSUE TITLE
RFE: Ability to configure trusted CA cert for `openshift_docker_additional_registries`

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-ansible#3244]
#### Description

When I configure additional docker registries via:

`openshift_docker_additional_registries=registry.example.com`

I would like to also be able to point to a `ca.crt` for that registry and have ansible distribute that cert to all of my nodes, either to `/etc/docker/certs.d/registry.example.com`, or by adding to rhel trust via `update-ca-trust`.

A sample hosts config might look like:

```
openshift_docker_additional_registries=registry1.example.com,registry2.example.com
openshift_docker_additional_registries_ca_files={'registry1.example.com': './registry1-ca.crt', 'registry2.exmple.com', './registry2-ca.crt'}
```

##### Version

all future versions

**Comment by michaelgugino** [comment]
Out of scope for installer.
