### ISSUE TITLE
Easier, Faster, and Better way for following README_libvirt.md file

### ISSUE THREAD

**Issue by incubus8** [openshift/openshift-ansible#3245]
Hi Guys,

Is there any automation script that setup the whole dependencies thing? 
As written in https://github.com/openshift/openshift-ansible/blob/master/README_libvirt.md it's very pain and difficult to follow and install dependencies one-by-one for new user like me, and also this Geniso dependency link http://cdrkit.org/ is not working. 

Any help would be greatly appreciate!

Thanks,

**Comment by michaelgugino** [comment]
The affected code path has been removed.

Closing this issue because it is no longer valid.
