### ISSUE TITLE
Issue on enabling Logging, ie, openshift_hosted_logging_deploy=true

### ISSUE THREAD

**Issue by glamperi** [openshift/openshift-ansible#3256]
When I run the playbook for byo/config.xml for OCP 3.4 with "openshift_hosted_logging_deploy=true", I get the following x509 certificate errors for the logging-deployer.  Is this a known issue?

+ oc delete secret logging-fluentd logging-elasticsearch logging-kibana logging-kibana-proxy logging-curator logging-curator-ops
Deleting secrets
Unable to connect to the server: x509: certificate is valid for router.default.svc, router.default.svc.cluster.local, not kubernetes.default.svc.cluster.local
Unable to connect to the server: x509: certificate is valid for router.default.svc, router.default.svc.cluster.local, not kubernetes.default.svc.cluster.local
Unable to connect to the server: x509: certificate is valid for router.default.svc, router.default.svc.cluster.local, not kubernetes.default.svc.cluster.local
Unable to connect to the server: x509: certificate is valid for router.default.svc, router.default.svc.cluster.local, not kubernetes.default.svc.cluster.local
Unable to connect to the server: x509: certificate is valid for router.default.svc, router.default.svc.cluster.local, not kubernetes.default.svc.cluster.local
Unable to connect to the server: x509: certificate is valid for router.default.svc, router.default.svc.cluster.local, not kubernetes.default.svc.cluster.local
+ :
+ echo 'Creating secrets'
+ oc secrets new logging-elasticsearch key=/etc/deploy/scratch/keystore.jks truststore=/etc/deploy/scratch/truststore.jks searchguard.key=/etc/deploy/scratch/searchguard_node_key searchguard.truststore=/etc/deploy/scratch/searchguard_node_truststore admin-key=/etc/deploy/scratch/system.admin.key admin-cert=/etc/deploy/scratch/system.admin.crt admin-ca=/etc/deploy/scratch/ca.crt admin.jks=/etc/deploy/scratch/system.admin.jks
Creating secrets
error: Get https://kubernetes.default.svc.cluster.local/api: x509: certificate is valid for router.default.svc, router.default.svc.cluster.local, not kubernetes.default.svc.cluster.local
See 'oc secrets new -h' for help and examples.

### <HTPASSWD_AUTH>

We are aware of the current issues related to htpasswd_auth failures
Please downgrade to ansible 2.2.0.0 until a fix is released.
You can track the status of the bug fix in this issue:
https://github.com/openshift/openshift-ansible/issues/3111
Please erase this <HTPASSWD_AUTH> section if it does not apply to you.

Thanks - 2017-01-31

#### Description

Provide a brief description of your issue here. For example:

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by ewolinetz** [comment]
@glamperi thanks for reporting this. This was a known issue for the logging deployer image that was thought to had been resolved, but it looks like it was missed.

**Comment by glamperi** [comment]
Hi Eric,

  I also tried to deploy logging by-hand (ie, OC CLI), but when I run "oadm
policy add-cluster-role-to-user oauth-editor
system:serviceaccount:logging:logging-deployer"
to add the needed oauth-editor role, the command line error says that
oauth-editor does not exist.  Perhaps, there is more setup needed before
this is run or logging is installed in the base installer?  You can see my
erb file here [1]

[1] https://github.com/glamperi/installrhel7.3

Gary Lamperillo
Principal Solutions Architect
glamperi@redhat.com
(M) 310-896-5282 <callto:310-896-5282>

**Comment by ewolinetz** [comment]
@glamperi sorry, I must have misread the initial error you were seeing. It seems that any of the requests for deleting/creating secrets was being rejected.. That is something new, the previously seen issue that I had referenced was regarding route generation and receiving certificate errors.
Could you open a Bugzilla regarding the issue you are facing with the deployer? Can you please attach the deployer logs with the BZ too?


Regarding running through the installation manually, it seems that you are missing the role that is created in step 5 in the Aggregated Logging install docs [1]. If you are not able to see that template, step 3 of that document describes how you can create it.

[1] https://access.redhat.com/documentation/en/openshift-container-platform/3.4/single/installation-and-configuration#pre-deployment-configuration

**Comment by glamperi** [comment]
> Could you open a Bugzilla regarding the issue you are facing with the
deployer? Can you please attach the deployer logs with the BZ too?

Where?  I thought this is were issues go?

Gary Lamperillo
Principal Solutions Architect
glamperi@redhat.com
(M) 310-896-5282 <callto:310-896-5282>

**Comment by glamperi** [comment]
Also, I did install the template.  The oauth-editor comes from somewhere
else, because I tried doing this several times.

Gary Lamperillo
Principal Solutions Architect
glamperi@redhat.com
(M) 310-896-5282 <callto:310-896-5282>

**Comment by ewolinetz** [comment]
what is the output from `oc get template/logging-deployer-account-template -o yaml`?

Can you also paste the contents of `/usr/share/ansible/openshift-ansible/roles/openshift_hosted_templates/files/v1.4/enterprise/logging-deployer.yaml` ?

**Comment by ewolinetz** [comment]
@glamperi can you try to rerun your installation using `openshift_hosted_logging_deploy=true` in your inventory. We have updated to no longer use the deployer image to do the logging installation so you should no longer encounter the error you saw above.

**Comment by glamperi** [comment]
Eric,

  I am using an older fork because of the python issue with metrics and
RHEL 7.3, so I would not be able to do this now.  If I want to try this, I
would do another git clone and then only use logging and set metrics to
false. Correct?

Thanks,
Gary

Gary Lamperillo
Principal Solutions Architect
glamperi@redhat.com
(M) 310-896-5282 <callto:310-896-5282>

**Comment by ewolinetz** [comment]
By default metrics shouldn't install, but correct -- you would use deploy logging true and deploying metrics false.

**Comment by glamperi** [comment]
I reran the installation with "openshift_hosted_logging_deploy=true" and
still getting this error:

fatal: [master.192.168.1.222.xip.io]: FAILED! => {"changed": false,
"failed": true, "msg": "No package matching 'python-ruamel-yaml' found
available, installed or updated", "rc": 126, "results": ["No package
matching 'python-ruamel-yaml' found available, installed or updated"]}


Sudheer Chekka
Middleware Solutions Architect
408-398-5848
