### ISSUE TITLE
Add metrics deployer options to the byo/example inventory file

### ISSUE THREAD

**Issue by myllynen** [openshift/openshift-ansible#3263]
The byo/example inventory file already contains:

> #Configure the prefix and version for the deployer image
> #openshift_hosted_logging_deployer_prefix=registry.example.com:8888/openshift3/
> #openshift_hosted_logging_deployer_version=3.3.0

It would seem that the corresponding options (s,logging,metrics,g) work as well. If that is the case, please consider adding them to the byo/example configuration file to make it easier to discover them.

Thanks.

**Comment by sdodson** [comment]
Seems like a super easy PR to file.

**Comment by myllynen** [comment]
Since it turned out that the deployer is going away (https://bugzilla.redhat.com/show_bug.cgi?id=1425020#c2) it might be best just to close this one.

Thanks.
