### ISSUE TITLE
Make DOCKER_NETWORK_OPTIONS configurable in installer

### ISSUE THREAD

**Issue by bdecoste** [openshift/openshift-ansible#327]
e.g. -b=lbr0 and --mtu=1450

**Comment by detiber** [comment]
As clarification, we'll probably want to leave the bridge device unset in the installer, since it is set through the sdn plugin.

We'll probably want to enable the ability to set the mtu (or enable the sdn plugin the gain the ability to configure the mtu as well).

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
