### ISSUE TITLE
Health checks may mutate host state 

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-ansible#3276]
Currently the checks in [playbooks/byo/openshift-preflight/check.yml](https://github.com/openshift/openshift-ansible/blob/master/playbooks/byo/openshift-preflight/check.yml) depend on the `openshift_facts` role to collect information about the cluster, and `openshift_facts` may modify hosts as observed in this task:

```
TASK [openshift_facts : Ensure various deps are installed] *********************
ok: [node2] => (item=[u'iproute', u'python-dbus', u'python-six', u'PyYAML', u'yum-utils'])
ok: [node1] => (item=[u'iproute', u'python-dbus', u'python-six', u'PyYAML', u'yum-utils'])
ok: [master1] => (item=[u'iproute', u'python-dbus', u'python-six', u'PyYAML', u'yum-utils'])
ok: [master2] => (item=[u'iproute', u'python-dbus', u'python-six', u'PyYAML', u'yum-utils'])
```

**Comment by detiber** [comment]
@rhcarvalho we've discussed moving the package installation outside of openshift_facts. I'm not sure if there is anyone actively working on that though... @sdodson?

**Comment by sdodson** [comment]
No not yet. @rhcarvalho are you suggesting that the checks be made not to include openshift_facts? I don't think we can reliably run openshift_facts without installing those packages.

**Comment by rhcarvalho** [comment]
I opened this as a reminder for investigation. The checks only need access
to some variables for now, and openshift_facts seen to do a lot more. The
easiest way to get the common vars is using the module. Maybe there could
be a way to trigger a "short path" that is free of host mutations.

**Comment by sosiouxme** [comment]
After much reflection I think as long as the health checks are mutating state in the same way as an install would (which they should as the same roles are invoked), it is acceptable. We have at least two scenarios for checks to run. 

- running the checks against hosts that they haven't installed yet as preparation for installing them; in which case, the hosts are not in production yet and making changes to them should not be a problem. 
- running the checks against already-installed hosts, but these should already have the state mutations from being installed, so won't need anything further to prepare the checks.

We should of course give the users adequate notice in our docs that changes will happen. And we have to be careful of corner cases like having installed with one version of openshift-ansible and running checks from another version. For this reason it's still a good idea to minimize the state mutations necessary for running the checks. But there is just a certain amount of bootstrapping that is necessary to even get enough information to proceed, and I think we'll have to be OK with that.

I move to close this issue...

**Comment by rhcarvalho** [comment]
Perhaps I originally focused on the wrong point.

We now know that some checks may require external deps, so we can't avoid having those installed.

In retrospect, probably my pain point was that `openshift_facts` takes a considerable time to run, while for most if not all checks all we use are some variables that either come from the inventory or are derived from other variables from the inventory.

Essentially, running the checks in quick succession during development was too slow for me. My hack was to locally comment out the dependency on `openshift_facts` and then manually hard code the values for the variables of interest.

`openshift_facts` is a large role. There is an opportunity to make the checks run faster if we'd be able to somehow use only the parts of `openshift_facts` we're interested in.

This requires investigation. We can consider it an RFE to split `openshift_facts`.

Closing this now because really there's nothing to do about mutating the host state.

----

And let me take the opportunity to ask...
@sdodson is there an existing Trello card or issue about breaking up `openshift_facts`? Is that even something that we could consider?
Or rather we could be investigating why `openshift_facts` is slow when compared to `setup`?!
