### ISSUE TITLE
Registry-console provide custom cert

### ISSUE THREAD

**Issue by garethahealy** [openshift/openshift-ansible#3279]
#### Description
Registry-console task doesn't support providing a custom cert via ansible, which means you have to do post-install steps:

- https://docs.openshift.com/container-platform/3.3/install_config/registry/deploy_registry_existing_clusters.html#securing-the-registry-console
- https://github.com/openshift/openshift-ansible/blob/master/roles/cockpit-ui/tasks/main.yml

##### Version
Please put the following version information in the code block
indicated below.

```
$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
 
$ rpm -q atomic-openshift-utils openshift-ansible
atomic-openshift-utils-3.3.54-1.git.0.61a1dee.el7.noarch
openshift-ansible-3.3.54-1.git.0.61a1dee.el7.noarch
```

##### Steps To Reproduce
Deploy with hosted registry, view the registry-console which uses a generated self signed cert.

##### Expected Results
Be able to provide the cert via ansible

**Comment by dmsimard** [comment]
:+1:
