### ISSUE TITLE
Target uses selinux but python bindings aren't installed

### ISSUE THREAD

**Issue by simon3z** [openshift/openshift-ansible#3303]
#### Description

It seems that the installation of `libselinux-python` is not enforced and then a failure occurs:

```
TASK [openshift_metrics : generate password for hawkular metrics and jgroups] **
failed: [ose-c06-node01.10.35.48.65.nip.io -> localhost] (item=hawkular-metrics) => {
    "checksum": "1d5c308a70682353cadaa33586805d8b76fddbd5", 
    "failed": true, 
    "item": "hawkular-metrics"
}

MSG:

Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!

failed: [ose-c06-node01.10.35.48.65.nip.io -> localhost] (item=hawkular-jgroups-keystore) => {
    "checksum": "9c7383915805b3deaa8d6ef8bbe6638801547ff6", 
    "failed": true, 
    "item": "hawkular-jgroups-keystore"
}

MSG:

Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!
```

##### Version

```
$ ansible --version
ansible 2.2.0.0
```

```
$ git describe
openshift-ansible-3.5.3-1-95-gfc96d8d
```

##### Steps To Reproduce
1. Run openshift-ansible against CentOS machines without `libselinux-python` installed

##### Expected Results
I suppose `libselinux-python` should be installed if required.

##### Observed Results
The packages `libselinux-python` is not installed and then a failure occurs (above).

cc @detiber @sdodson

**Comment by giuseppe** [comment]
@simon3z are you using `containerized=true`?

**Comment by simon3z** [comment]
> @simon3z are you using containerized=true?

@giuseppe no... that's why it's puzzling, I saw that part of the code (/check) as well.

**Comment by detiber** [comment]
That step is run as a local action, so it is complaining about libselinux-python missing from the host/container running the playbook

**Comment by detiber** [comment]
@sdodson, sounds like we need to add it to the dependencies in the spec

**Comment by giuseppe** [comment]
right, for me it gets installed as dependency from firewalld

**Comment by detiber** [comment]
@giuseppe right, but firewalld is not a dependency or a requirement for the host running Ansible.

**Comment by sdodson** [comment]
@simon3z are you running via rpms or a github checkout? My fix won't work for github checkouts but will for rpm based installs.

**Comment by simon3z** [comment]
@sdodson @detiber @giuseppe sorry I didn't comment fast enough... I wanted to suggest to add it to the `requirements.txt` file as well so you cover also who's not using rpms.

Thanks.
