### ISSUE TITLE
Vagrant install - NetworkManager fights over 2nd interface

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-ansible#331]
Instructions for deployment are 2 steps

```sh
# step 1
vagrant up --no-provision
# step 2
vagrant provision
```

Immediately after step 1, the `enp0s3` interface of each node has an IP obtained from the host via DHCP in 10.0.2, and `enp0s8` has a statically configured IP in 192.168.100 from vagrant:

```sh
[vagrant@ose3-master ~]$ cat /etc/sysconfig/network-scripts/ifcfg-enp0s3
# Generated by dracut initrd
NAME="enp0s3"
DEVICE="enp0s3"
ONBOOT=yes
NETBOOT=yes
IPV6INIT=yes
BOOTPROTO=dhcp
TYPE=Ethernet

[vagrant@ose3-master ~]$ cat /etc/sysconfig/network-scripts/ifcfg-enp0s8
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
NM_CONTROLLED=no
BOOTPROTO=none
ONBOOT=yes
IPADDR=192.168.100.100
NETMASK=255.255.255.0
DEVICE=enp0s8


PEERDNS=no
#VAGRANT-END
```

However, NetworkManager does not know that Vagrant has taken responsibility for `enp0s8`. 

```
[vagrant@ose3-master ~]$ systemctl -l status NetworkManager
NetworkManager.service - Network Manager
   Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; enabled)
   Active: active (running) since Wed 2015-07-08 23:53:49 UTC; 2min 16s ago
 Main PID: 567 (NetworkManager)
   CGroup: /system.slice/NetworkManager.service
           ├─  567 /usr/sbin/NetworkManager --no-daemon
           ├─  644 /sbin/dhclient -d -q -sf /usr/libexec/nm-dhcp-helper -pf /var/run/dhclient-enp0s3.pid -lf /var/lib/NetworkManager/dhclient-3c36b8c2-334b-57c7-91b6-4401f3489c69-enp0s3.lease -cf /var/lib/NetworkManager/dhclient-enp0s3.conf enp0s3
           └─12963 /sbin/dhclient -d -q -sf /usr/libexec/nm-dhcp-helper -pf /var/run/dhclient-enp0s8.pid -lf /var/lib/NetworkManager/dhclient-e431a5d1-34aa-4254-8b2c-72d7a70092c0-enp0s8.lease -cf /var/lib/NetworkManager/dhclient-enp0s8.conf enp0s8
```

Subsequently in a few moments, the IP will be stripped when DHCP fails for this interface. At that point step 2 ( `vagrant provision` ) will fail with no discovered nodes.

# Possible Workarounds #

These don't feel like the right fix, but can be workarounds to execute before proceeding to step 2 above. I'm not sure if Vagrant can do this automatically, or if the ansible playbook should implement the network restarts early in the play or do something more elegant.

**reboot**

```sh
for node in master node1 node2; do
  vagrant reload $node
done
```

**restart networking**

```sh
vagrant ssh $node
sudo systemctl restart NetworkManager
sudo systemctl restart network
```

**Comment by detiber** [comment]
@dlbewley thanks for taking a closer look at this. I was able to find this issue against Vagrant: https://github.com/mitchellh/vagrant/issues/5590

It looks like it's fixed in the latest master, but there hasn't been a release cut yet that contains the fix.

As suggested in the linked issue, we can add the following to our Vagrantfile as a workaround (before the ansible provisioner): `config.vm.provision "shell", inline: "nmcli connection reload; systemctl restart network.service"`

**Comment by detiber** [comment]
@dlbewley if you can verify that the above workaround is sufficient for VirtualBox, I can test that it doesn't break anything with the libvirt provider and I can submit a PR (or you can, if you prefer) to get the workaround in place.

**Comment by dlbewley** [comment]
Thanks, @detiber 
I don't fully grok Vagrant, so I'm not sure this is most proper, but it does fix the network problem during the `vagrant provision` step. The network is still broken shortly after the `vagrant up --no-provision` step FWIW.

```diff
diff --git a/Vagrantfile b/Vagrantfile
index 648bc51..0268677 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -39,13 +39,14 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
     config.vm.define "node#{node_index}" do |node|
       node.vm.hostname = "ose3-node#{node_index}.example.com"
       node.vm.network :private_network, ip: "192.168.100.#{200 + n}"
+      config.vm.provision "shell", inline: "nmcli connection reload; systemctl restart network.service"
     end
   end
-
   config.vm.define "master" do |master|
     master.vm.hostname = "ose3-master.example.com"
     master.vm.network :private_network, ip: "192.168.100.100"
     master.vm.network :forwarded_port, guest: 8443, host: 8443
+    config.vm.provision "shell", inline: "nmcli connection reload; systemctl restart network.service"
     master.vm.provision "ansible" do |ansible|
       ansible.limit = 'all'
       ansible.sudo = true
```

**Comment by detiber** [comment]
@dlbewley I would expect it to still be broken following a --no-provision since we are doing the nmcli reload and restarting the network as a provision step.  I would expect that it should "do the right thing" before running the ansible provisioning step though.
