### ISSUE TITLE
unable to push image to docker registry in openshift origin 1.3.3

### ISSUE THREAD

**Issue by msavlani** [openshift/openshift-ansible#3341]
Hi,
I am new to openshift/origin and followed installation instructions provided as part of Advanced installation.
I ran ansible playbook to setup clusters on 3 machines.
Setup was completed successfully but during example testing , i ran into below issue 

Below is the output if i run command from any pods or directly from node/master machine.

#  docker push 172.30.156.164:5000/testtemplates/dancer-mysql-example:latest
The push refers to a repository [172.30.156.164:5000/testtemplates/dancer-mysql-example] (len: 1)
Sending image list
Index response didn't contain any endpoints

I am using openshift/origin version 1.3.3
And below is my oc get pods output 

# oc get pods
NAME                        READY     STATUS             RESTARTS   AGE
docker-registry-9-z7fks     1/1       Running            0          4d
registry-console-1-deploy   0/1       DeadlineExceeded   0          6d
registry-console-2-2hvvh    1/1       Running            0          5d
router-2-0k0f0              1/1       Running            3          5d

# oc get dc
NAME               REVISION   DESIRED   CURRENT   TRIGGERED BY
docker-registry    9          1         1         config
registry-console   2          1         1         config
router             2          1         1         config

# oc get svc
NAME               CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
docker-registry    172.30.156.164   <none>        5000/TCP                  6d
kubernetes         172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     7d
registry-console   172.30.78.102    <none>        9000/TCP                  6d
router             172.30.86.226    <none>        80/TCP,443/TCP,1936/TCP   6d

**Comment by sdodson** [comment]
@miminar Does this error message mean anything specific?
```
Sending image list
Index response didn't contain any endpoints
```

**Comment by miminar** [comment]
> Index response didn't contain any endpoints

For some reason, docker daemon thinks that the registry is a v1 registry. So for some reason, docker failed to ping registry's v2 endpoint.

@msavlani is the registry secured? And if not, is docker daemon configured to with `--insecure-registry=172.30.0.0/16` (`systemctl status docker` should give you the info).

**Comment by msavlani** [comment]
My systems are sitting behind proxy and thus  it was unable to reach my registry if i set proxy variables.
I added above endpoint to no proxy and it worked like silk.

Thanks for looking into my issue.
