### ISSUE TITLE
Deploy Heaspter Standalone flavor of Openshift Hosted Metrics

### ISSUE THREAD

**Issue by jacksilv** [openshift/openshift-ansible#3353]
Openshift metrics provides a parameters to deploy only Heapster (see https://github.com/openshift/origin-metrics/blob/master/deployer/scripts/heapster.sh#L84).
This option (HEAPSTER_STANDALONE) is not exposed by any variable from the Openshift metrics role.
I would like to introduce this variable and I can provide the implementation.

**Comment by sdodson** [comment]
@jcantrill I think we just need to set an envvar when deploying standalone?
