### ISSUE TITLE
Rename `utils` to a more descriptive name

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-ansible#3354]
The current name is so misleading. What would be the impact of renaming `utils` to `atomic-openshift-installer` or anything else that reflect what the content of the directory is?

I know we'd need to update `openshift-ansible.spec` in this repo, and the description in `CONTRIBUTING.md`. Anything external?

Is that a good / bad / useless idea?

/cc @sdodson @detiber @abutcher @tbielawa @mtnbikenc

**Comment by sdodson** [comment]
Fine with me as long as it still builds and makes it into a functional rpm.

**Comment by mtnbikenc** [comment]
:+1: 

`utils` was misleading to me as well when first working on openshift-ansible.  I'm sure there is a legacy reason why it was called utils.

**Comment by detiber** [comment]
I would probably suggest that we rename the directory `installer_wrapper` to not be tied directly to product naming.

I'm not really invested in the name, I'd just prefer something descriptive that isn't tied to product naming (which can change).

**Comment by rhcarvalho** [comment]
In the effort of documenting what is in each top-level dir, this is what we got about utils:

```
└── utils               Contains the `atomic-openshift-installer` command, an
                        interactive CLI utility to install OpenShift across a
                        set of hosts.
```

@detiber, IMHO an indirect name would still cause confusion. One would need to map from `installer_wrapper` (or any other generic name) to `atomic-openshift-installer` or `oo-install` (executable names found in `openshift-ansible.spec`).

**Comment by detiber** [comment]
We could always just go with oo-install

**Comment by rhcarvalho** [comment]
`oo-install` is good. I've seen the "oo" prefix in several places, including Ansible variable names, what does it stand for? Hmm OpenShift Ops?
