### ISSUE TITLE
openshift_additional_repos is not reentrant on error

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#3361]
If you specify an invalid openshift_additional_repos, the following task in openshift_facts/tasks passes because the repo hasn't been specified yet:

```
- name: Ensure various deps are installed
  package: name={{ item }} state=present
  with_items: "{{ required_packages }}"
  when: not l_is_atomic | bool
``` 

But on subsequent runs (after we fail much later when additional_repos bails out) the broken additional_repo prevents the playbook from moving past this step.

**Comment by sdodson** [comment]
Can you provide the broken openshift_additional_repos? The situation you're describing should only happen when the additional repos override other working repos. Is that it?
