### ISSUE TITLE
Fail to upgrade Origin after updating openshift-ansible to the latest release

### ISSUE THREAD

**Issue by 201sandeep** [openshift/openshift-ansible#3366]
I am trying to upgrade openshift origin from v.1.4 to v1.5 but it is not letting me do so.. 

[root@openshift-vm1 ~]# oc version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift-vm1.example.com:8443
openshift v1.4.1
kubernetes v1.4.0+776c994
[root@openshift-vm1 ~]#

Below are the status of nodes and pods, I successfully upgraded it from v1.3 to v1.4 but now it is throwing below error when i am doing it from v1.4 to v1.5

[root@openshift-vm1 ~]# oc get nodes
NAME                        STATUS    AGE
openshift-vm1.example.com   Ready     40d
openshift-vm2.example.com   Ready     40d
[root@openshift-vm1 ~]#
[root@openshift-vm1 ~]#
[root@openshift-vm1 ~]# oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-5-dzsxp    1/1       Running   7          26d
help-1-hmzmz               1/1       Running   0          3h
registry-console-1-xidc7   1/1       Running   13         14d
router-2-48toe             1/1       Running   16         12d
[root@openshift-vm1 ~]#

Steps i have followed

1. cloned the latest git folder
2. executed the playbook as below...

`[root@openshift-vm1 openshift-ansible]# oc version ; ansible-playbook -i /etc/ansible/hosts playbooks/byo/openshift-cluster/upgrades/v3_5/upgrade.yml
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift-vm1.example.com:8443
openshift v1.4.1
kubernetes v1.4.0+776c994

PLAY [Create initial host groups for localhost] ********************************

TASK [include_vars] ************************************************************
ok: [localhost]

`

it initiated but exited with below error...

`TASK [openshift_version : fail] ************************************************
fatal: [openshift-vm1.example.com]: FAILED! => {
    "changed": false,
    "failed": true
}

MSG:

Detected OpenShift version 1.4.1 does not match requested openshift_release 1.5. You may need to adjust your yum repositories, inventory, or run the appropriate OpenShift upgrade playbook.

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0
openshift-vm1.example.com  : ok=61   changed=1    unreachable=0    failed=1
openshift-vm2.example.com  : ok=41   changed=1    unreachable=0    failed=0

`

Any HELP PLS !!!!

**Comment by 201sandeep** [comment]
I just scrolled the repository @ http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/ 

can see no package is available yet for this upgrade...  Please confirm if my observation is right...

**Comment by ngpestelos** [comment]
@201sandeep I ran into the same [problem](https://github.com/openshift/openshift-ansible/issues/3494) with the repo. Can you try again?

**Comment by sdodson** [comment]
We do not currently have 1.5 RPMs.

**Comment by tdawson** [comment]
The repo you are pointing to is for finaished, released packages.
Origin 1.5 has not been released yet, only an Alphas and Betas have been released, so you will not see rpm's for 1.5 in that repo.
Right now, we have a version of origin-1.5 in our testing area.
https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin/

**Comment by tdawson** [comment]
Finished many years ago.
Closing.
