### ISSUE TITLE
Fedora (AH): python (core) yaml

### ISSUE THREAD

**Issue by cgwalters** [openshift/openshift-ansible#3394]
I was looking at a run on current Fedora AH, which fails very quickly with:

```
TASK [openshift_facts : Gather Cluster facts and set is_containerized if needed] ***
task path: /srv/walters/src/github/openshift/openshift-ansible/roles/openshift_facts/tasks/main.yml:20
fatal: [node]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 192.168.121.166 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_SO8QZU/ansible_module_openshift_facts.py\", line 20, in <module>\r\n    import yaml\r\nImportError: No module named yaml\r\n", "msg": "MODULE FAILURE"}
```

Now...I think this is partly a Python 2 vs 3 thing, since on a current CentOS AH, we have:

```
# rpm -q --whatrequires PyYAML
atomic-1.14.1.12-8df71d7c6a33c2f7c95f4d4c72b623546fc82d55.2805e4f21d124fff45ffda5d817d81c80fa41afa.el7.centos.x86_64
cloud-init-0.7.5-10.el7.centos.1.x86_64
```

Yet on Fedora AH:

```
# rpm -q --whatrequires PyYAML
no package requires PyYAML
# rpm -q --whatrequires python3-PyYAML
cloud-init-0.7.8-3.fc25.noarch
atomic-1.14.1-1.fc25.x86_64
```

However, what confuses me is I know we at least had *some* runs since e.g. www.projectatomic.io/blog/2016/12/part1-install-origin-on-f25-atomic-host/  I even tried deploying the version of AH referenced there (`25.42`) thinking that perhaps we *did* previously pull in `PyYAML` but something got ported to Python 3, but AFAICS, nope.

So we'll have to decide a bit - do we carry PyYAML just for openshift-ansible?  How did Dusty's runs work?

**Comment by dustymabe** [comment]
just ran this with latest upstream `openshift-ansible` 6490024 repo and I did [hit an error](https://github.com/openshift/openshift-ansible/issues/3396) but it was way into the install and not this issue at all. Are you running with python3 like I did in the blog post?

```
ansible-playbook -i myinventory playbooks/byo/config.yml -e 'ansible_python_interpreter=/usr/bin/python3'
```

**Comment by cgwalters** [comment]
Ah, was requiring Python 3 for Fedora decided as The Plan or it just happens to work better today?

**Comment by dustymabe** [comment]
I just assumed it was the way forward since one of the critical libraries was missing in python2 form (`PyYaml`). I figured rather than trying to convince people to add python2 packages back we should just forge ahead. If you'd like to revisit this then we can certainly do that.

**Comment by cgwalters** [comment]
I submitted https://github.com/openshift/openshift-ansible/pull/3402 - let's move the discussion there.
