### ISSUE TITLE
Make it an official ansible module

### ISSUE THREAD

**Issue by Fale** [openshift/openshift-ansible#340]
Please, try to push OpenShift to become an official (extra) Ansible module. This will make easier for the users to use it and can work as OpenShift advertise in the Ansible comunity.

**Comment by detiber** [comment]
@Fale Our current priorities are as follows:
1. Resolve outstanding issues people are seeing with installs
2. Add installer/ansible support for additional installation types and supported configurations
3. Push as much as we can upstream (in no particular order)
  * Create PRs for our custom modules for inclusion into Ansible's extras modules
  * Push roles out to Ansible Galaxy for easier discovery

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit
