### ISSUE TITLE
OpenStack cloud-init resets hostname to default value

### ISSUE THREAD

**Issue by ingvagabund** [openshift/openshift-ansible#3455]
When deploying OpenShift on cluster provisioned inside OpenStack with `openshift_public_hostname`/`openshift_hostname` set to different name than VM's original hostname, `cloud-init` resets the hostname back to its original name after each reboot.

The reasoning for the behaviour is described here [1]. So when running deployment/upgrade of a cluster, hostnames of all cluster nodes are reset to their original name which should not happen.

The article mentions at least three solutions how to solve the problem. I like the one suggesting to put a special file under `/etc/cloud/cloud.cfg.d`. E.g.

```yaml
# cat /etc/cloud/cloud.cfg.d/99_hostname.cfg
preserve_hostname: true
```

Tested and it works. VM hostname is preserved after running ``hostnamectl set-hostname NEWHOSTNAME``.

Is this something we should deal with within openshift ansible? Or is that something every user should deal with before running the openshift ansible?

[1] https://adam.younglogic.com/2015/03/resetting-hostname/
[2] http://cloudinit.readthedocs.io/en/latest/topics/modules.html?highlight=hostname#set-hostname

**Comment by detiber** [comment]
@ingvagabund We shouldn't be overriding the system hostname by default as of 1.2/3.2. 

Is `openshift_set_hostname` being set in the inventory?

**Comment by ingvagabund** [comment]
> Is openshift_set_hostname being set in the inventory?

`openshift_public_hostname` and `openshift_hostname` are.

The issue comes from https://bugzilla.redhat.com/show_bug.cgi?id=1419465

You are saying changing of hostname is depricated? If not, in what situations is it allowed?

**Comment by detiber** [comment]
relevant tasks are here: https://github.com/openshift/openshift-ansible/blob/7374505de2a11b94d22672b8da7e405b919a15bc/roles/openshift_common/tasks/main.yml#L40-L48

I'm not sure that is related to the bug at hand, though.

**Comment by ingvagabund** [comment]
And yes, ``openshift_set_hostname `` is set as well.

**Comment by ingvagabund** [comment]
The bug is the OpenStack's VM metadata provides old hostname instead of the new one. Since the hostname is used to name a node, the node is registered with the new hostname but the metatada still returns the old hostname. So the node can not be found on master.
