### ISSUE TITLE
no test named 'equalto' - Can't update to Jinja 2.8

### ISSUE THREAD

**Issue by cameron-scrace** [openshift/openshift-ansible#3463]
#### Description
I'm using Centos 7 and when running the upgrade playbook I get the error message: no test named 'equalto'. The lines that cause this were only added to the playbook a few days ago. The equalto test is provided by Jinja 2.8 but even after running yum update the python2-jinja2 package remains at version 2.7. Is there a clean way to install Jinja 2.8 on Centos 7?

##### Version
```
CentOS Linux release 7.3.1611

ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

git describe
openshift-ansible-3.5.3-1-364-gf0a32af

```

##### Steps To Reproduce
1. Have Openshift Origins 1.3 on Centos 7
2. Run 1.4 upgrade playbook

##### Expected Results
Upgrade succeeds.

##### Observed Results
Upgrade fails with error no test named 'equalto'

**Comment by sdodson** [comment]
We need to ensure that we don't depend on anything newer than what's available in Jinja 2.7.

**Comment by detiber** [comment]
@sdodson @mtnbikenc If needed we can ship a custom test plugin to work around the issue: https://docs.ansible.com/ansible/dev_guide/developing_plugins.html#test-plugins

**Comment by vhosakot** [comment]
`pip install --upgrade Jinja2` resolved this error for me.
