### ISSUE TITLE
We should squash openshift-ansible into one package

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#3469]
We either need to make openshift-ansible depend on all the subpackages or simply get rid of them all. Users will more than likely install openshift-ansible rpm and expect things to work. In my opinion the subpackages individually provide almost no value so I'd prefer we squash them into one package unless there's some reason not to do so. The quick-installer aka `atomic-openshift-utils` can remain a subpackage.

It won't, no playbooks, no roles, no filter plugins, etc.

```
# yum install openshift-ansible

 Package           Arch       Version          Repository                              Size
 openshift-ansible          noarch  3.5.10-1.git.0.ba66b63.el7  rhel-7-server-ose-3.5-rpms  183 k
 openshift-ansible-docs noarch  3.5.10-1.git.0.ba66b63.el7  rhel-7-server-ose-3.5-rpms   181 k
 
Transaction Summary
=============================================================================================================================================================================================
Install  1 Package (+1 Dependent package)
 
Complete!
```

Thoughts?

**Comment by sdodson** [comment]
FYI @stevekuznetsov

**Comment by sdodson** [comment]
Looking for consensus/discussion from those assigned, not actual implementation.

**Comment by tbielawa** [comment]
I support this.

Note that `atomic-openshift-utils` will be funny though, because to actually operate I believe it would need to have a `Requires` for `openshift-ansible` to be able to use the roles/playbooks/etc.

**Comment by detiber** [comment]
+1 to squashing it down.

This was brought up recently in a separate PR around testing, but it might make sense to break utils out into it's own repo.

**Comment by stevekuznetsov** [comment]
Yeah, today `yum install openshift-ansible` gives you this...

```
# tree /usr/share/ansible/openshift-ansible
/usr/share/ansible/openshift-ansible
├── library
│   ├── kubeclient_ca.py
│   ├── kubeclient_ca.pyc
│   ├── kubeclient_ca.pyo
│   ├── modify_yaml.py
│   ├── modify_yaml.pyc
│   ├── modify_yaml.pyo
│   ├── rpm_q.py
│   ├── rpm_q.pyc
│   └── rpm_q.pyo
└── playbooks
    └── common
        └── openshift-master
```

Which is a useless collection of nothing

**Comment by detiber** [comment]
I like how there is a sub-directory of playbooks in there...

**Comment by tdawson** [comment]
issue is old and no longer applies.  Closing.
