### ISSUE TITLE
Common way of handling fail-fast validation checks that affect multiple roles needed

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#3479]
#3475 highlights an example where we need to apply common validation checks that apply to multiple roles. The scope of the PR is for providing a way to test that installations on atomic host fail early if the version of docker does not meet the requirements for install, but I believe it provides a complex enough example of some of the challenges that we face in moving from the existing openshift-ansible codebase (larger monolithic roles with complex and intertwined dependencies) towards smaller, more composable roles.

What we need:
- A way to run pre-install validation checks for multiple roles early enough to 'fail fast'
- A way for those pre-install validation checks to have access to common system 'facts' (is_atomic in this case)

I'd also argue that we should be able to only run the pre-install validation checks, that way we could simply provide a playbook that could let a user know that their system is ready to install or upgrade OpenShift. Here I'm specifically thinking of the following scenarios:
- User environments where there are separate teams responsible for different parts of the provisioning, configuration and installation process.
- Validation of 'golden images' for cloud installs.

Ideally, we'd also be able to use the same set of the pre-install validation checks for other uses as well. Using the example from #3475, verifying that the version of docker on atomic host is compatible is just as applicable to upgrade it is for install. They checks could also be used for diagnostics, especially if we do not limit them checking a minimum version of docker, but instead compare the version of OpenShift (installed or requested) against installed or available versions (installed only for atomic host) of docker. 

Since there is already consensus to build small composable roles vs large monolithic roles, I believe that brings us to the following requirements:
- Define and gather a set of host facts common to multiple roles
  - not like openshift_facts, but more like the ansible_* facts provided by the setup module
  - places where we test truthiness of openshift.common.is_atomic could become `openshift_host_type == 'atomic'`
- Define and run a set of pre-install validation checks common to multiple roles
- Must work in the scope of small composable roles

One approach:
Add `tasks/pre-validate.yml` to roles that require it.
  - Pro: Allows us to ensure the pre-validation steps are run as part of the role using `include`, this could be condionalized to allow for skipping the pre-validate steps if desired.
  - Pro: Allows us to call the pre-validation steps in playbook `pre_tasks` using `include_role` with `tasks_from: pre-validate.yml`
  - Con: Dependency roles would be run prior to `pre-validate.yml` for both the role dependency and `include_role` uses.
  - Con: Ordering and ensuring the presence of tests prior to running roles needs to be explicitly defined and managed for each playbook/play. 
  - Con: pre-validate steps would be executed multiple times if called in `pre_reqs` and listed as a role dependency.
  - Con: there is no way to transition a role to this model without a massive refactoring of the role to decouple it from existing role dependencies.
  - Con: this approach encourages monolithic modules

While I do not believe the above approach is feasible or desirable, I think we need to be cautious not to fully decouple the pre-validation from the roles they are pre-validating.

Instead I would like to see if we can define allowable dependency roles/modules that provide a limited scope of behavior.
  - 'fact' roles/modules would be limited to only providing fact data back from the system
    - A hierarchical set of 'fact' roles/modules would allow us to avoid lumping everything into a single role/module for all uses and would also allow us to avoid creating duplicated or even conflicting logic or interfaces between roles.
    - If implemented as modules, we could make them available in lib_openshift, or a separate lib_openshift_facts role. The modules could then be included/used wherever they are needed.
    - We could also provide roles that would call the required modules needed for a specific purpose. This would allow for us to set role dependencies to ensure facts are available rather than having to make explicit module calls everywhere the values are needed. It would also allow for ensuring that the fact collection tasks are only run a single time for each playbook, while it won't be desirable for all uses (those cases could explicitly call the modules again), it would prevent us from running potentially costly checks multiple times during a run.
  - 'pre-validation' roles/modules that are limited to tasks that do not modify system state
    - similar to the 'facts' modules/roles above, but these roles could also depend on the associated 'facts' roles, which would ensure that the needed facts are available in the role to be used. This would allow for us to build a hierarchical set of pre-validation roles that could be used in multiple playbooks.

This also gets into some of the challenges when comparing the existing codebases and trying to codify best practices. I think there is a fine line that we need to walk to when solving this problem. We don't want to continue down the openshift_facts/openshift_common type approach, but we need to be careful to avoid pushing all of the complexity for these types of checks to every entry-point playbook that would require them.

I think if we can define a clear set of restrictions and limitations for these different 'types' of roles, and if we enforce a naming standard then we should be able to leverage a tool like [ansible-review](https://github.com/willthames/ansible-review) to enforce those restrictions.

**Comment by ewolinetz** [comment]
+1 @detiber 

Since we want smaller, composable roles couldn't the first thing a role does is gather any required facts  and fail if certain facts aren't available or their values are incorrect. I would argue we want to make a role gather its own facts as much as possible -- this may not be possible in all cases where a fact is global enough i.e. is_atomic. It may increase verbosity of our roles, and for some facts we would see duplicates of fact gathering, but it would allow us to decouple our roles and make them independent of execution order. As part of that we may want to offer [a]? module[s]? to make it easy to gather specific system facts.

It makes sense to me that we could add a tag like `pre-validate` to all of these pre-tasks so that we could have an entry-point where we only do validation, as you suggest.

**Comment by detiber** [comment]
> Since we want smaller, composable roles couldn't the first thing a role does is gather any required facts and fail if certain facts aren't available or their values are incorrect. I would argue we want to make a role gather its own facts as much as possible -- this may not be possible in all cases where a fact is global enough i.e. is_atomic.

Yes, I think in the general case the role should gather it's own facts. I'm just thinking that as we continue to break out larger roles into smaller roles we are going to hit the issue of 'common' facts/variables even more than we do today.

> It may increase verbosity of our roles, and for some facts we would see duplicates of fact gathering, but it would allow us to decouple our roles and make them independent of execution order. As part of that we may want to offer [a]? module[s]? to make it easy to gather specific system facts.

So, the fun part is differentiating between facts and variable defaults as well. I don't want to get back into a situation where we have another `openshift_facts` module. Which complicates duplication even more as well. In some cases variable defaults will need to be computed by using the value of a gathered fact, to avoid causing issues where defaults may have changed. The best example I can think of for this is changing the cidr of the service network or the SDN. We've changed the system default of these in the past, and if we just update from the previous default to the new default we would cause service disruption.

> It makes sense to me that we could add a tag like pre-validate to all of these pre-tasks so that we could have an entry-point where we only do validation, as you suggest.

I think having support for tags is a good thing, but I hesitate to say that it should be the supported way of doing pre-validation. Especially since tags can only be specified at command invocation and cannot be configured during runtime.

**Comment by sosiouxme** [comment]
I think a number of recent proposals are making strides toward fixing this. I am hopeful with the role refactoring we'll soon be able to establish a pattern of pre-run validation per role. I think we can close this particular issue (but someone reopen if you want to keep it as a reminder).
