### ISSUE TITLE
how to change the kubernetes/default service IP 

### ISSUE THREAD

**Issue by xiaoping378** [openshift/openshift-ansible#3480]
#### Description
I  want to run 1024 pods per node.  so i changed the the ip range. 
```
osm_cluster_network_cidr=12.1.0.0/12
openshift_portal_net=170.30.0.0/12
openshift_node_kubelet_args={'pods-per-core': ['0'], 'max-pods': ['1024']}
```

but i got a error and origin-master can't start up.
```
the cluster IP 172.16.0.1 for service kubernetes/default is not within the service CIDR 170.16.0.0/12; please recreate

SDN initialization failed: Error: Existing service with IP: 172.16.0.1 is not part of service network: 170.16.0.0/12
```

so how do i change the kubernetes/default service IP ``172.16.0.1`` ?

using origin ``v1.4.1``,  openshift-ansible ``openshift-ansible-3.4.17-1``

**Comment by detiber** [comment]
@xiaoping378 Are you seeing this error on a fresh install with those provided variables, or are you updating the variables and running the playbook against an existing installation?

**Comment by xiaoping378** [comment]
@detiber Thank you for your reminder， i retry a fresh install, it is OK.
Thanks again.
