### ISSUE TITLE
playbook does not handle installation of docker versions properly

### ISSUE THREAD

**Issue by jaloren** [openshift/openshift-ansible#3482]
#### Description

by default, the playbook installs docker engine 1.10. The name of the rpm is docker. I want the playbook to install docker engine 1.12.6. So I attempted to set the docker version in my hosts OSEv3:vars like so

docker_version=1.12.6

This failed because the repo that the playbook is configured to pull docker engine from does not have version 1.12.6 of an rpm named docker. I then installed the [docker repo](https://yum.dockerproject.org/repo/main/centos/7/) and yum install docker-engine-1.12.6 on all my systems manually. 

However, the ansible playbook uses a repoquery command to verify the docker version that uses docker rpm name and not docker-engine. 

IMHO, the ansible playbook should be updated so that provisions the canonical yum repo for docker and properly installs docker-engine-X and not this legacy docker rpm. Alternatively, the repoquery code should have an if block to check either docker-X or docker-engine-X.

##### Version

Please put the following version information in the code block
indicated below.

```
VERSION INFORMATION HERE PLEASE
ansibile verison:
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

git clone:
openshift-ansible-3.4.9-1
```

##### Steps To Reproduce
1. install docker-engine-1.12.6 manually on all nodes.
2.  run playbook

OR:

1. add docker_version=1.12.6 to the ansibles hosts file
2. run playbook.

##### Expected Results
playbook should have installed docker-engine 1.12.6

##### Observed Results
Describe what is actually happening.

```
TASK [docker : Install Docker] *************************************************
fatal: [gluster4.dev.norvax.net]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'docker-1.12.6' found available, installed or updated", "rc": 126, "results": ["No package matching 'docker-1.12.6' found available, installed or updated"]}
```

**Comment by sdodson** [comment]
https://github.com/openshift/origin/issues/8508 needs to be fixed before we can address this. Are you ok with me closing this?

**Comment by jaloren** [comment]
I'd like to understand the issue a little better. Here's my understanding: if anyone wants to use docker engine 1.12 with openshift origin and they want to use the playbooks to deploy it, they are left with the following options: 1) hack the ansible playbook so it will repoquery properly or 2) hack the rpms 

The reason its like this is to due to a upstream packaging issue that is outside the ansible playbooks control.  I have personally dealt with rpm dependency hell with other software packages so I sympathize. That leaves me with a couple questions:

- is there a reason why the ansible playbooks couldn't be modified to work around this problem? For example, the repoquery command could simply be modified to look for either docker-engine or docker and some documentation could be provided to tell the user to install docker engine 1.12 out of band.
- if that's not acceptable, what about providing a  clearly documented section in the README that explains the issue and possible workarounds.
- or minimally document that ansible playbook is only supported with docker engine 1.10.

PS I can certainly provide a PR for the documentation.

**Comment by sdodson** [comment]
> I'd like to understand the issue a little better. Here's my understanding: if anyone wants to use docker engine 1.12 with openshift origin and they want to use the playbooks to deploy it, they are left with the following options: 1) hack the ansible playbook so it will repoquery properly or 2) hack the rpms

docker 1.12.5 is available in Centos 7 and RHEL 7. Fedora 25 has 1.12.6. Are you specifically looking for 1.12.6 or just 1.12? 1.12.6 is still being tested with openshift and bugs are being resolved before it's released to Centos/RHEL.

> The reason its like this is to due to a upstream packaging issue that is outside the ansible playbooks control. I have personally dealt with rpm dependency hell with other software packages so I sympathize. That leaves me with a couple questions:
> 
>     is there a reason why the ansible playbooks couldn't be modified to work around this problem? For example, the repoquery command could simply be modified to look for either docker-engine or docker and some documentation could be provided to tell the user to install docker engine 1.12 out of band.
>     if that's not acceptable, what about providing a clearly documented section in the README that explains the issue and possible workarounds.
>     or minimally document that ansible playbook is only supported with docker engine 1.10.
> 
> PS I can certainly provide a PR for the documentation.

We can amend the rpmquery commands but as soon as you try to install the origin or OCP RPMS those too have dependencies that Require 'docker' rather than 'docker-engine' as available from the upstream Docker Project repo. I guess one option we have is to remove all RPM dependencies from our RPMs and simply rely on the playbooks to ensure docker or docker-engine are installed, however we don't test with upstream releases so we'd have to figure out some way to ensure it's tested at some minimal level.

**Comment by jaloren** [comment]
docker 1.12.5 is perfectly acceptable. Its tracking down the RPM that was the challenge. Once I located it, here http://mirror.centos.org/centos/7/extras/x86_64/, it worked fine. 

So here's my two cents for whatever its worth. This might be simple minded but it seems like the canonical way to install docker via rpms is documented here:

https://docs.docker.com/engine/installation/linux/centos/
https://docs.docker.com/engine/installation/linux/centos/#install-using-the-repository

The canonical name is docker-engine -- not docker. And in fact the docker documentation explicitly calls this out and tells you to uninstall docker and install docker-engine. I would wager any sys admin of red hat or centos system will look at that way. I have been managing centos VMs for over 10 years (even got to deal with 5 back in the day). 

Given that, if openshift is going to go the RPM route and use rpm dependencies, then it should be based on docker-engine, which comes from the canonical docker repo. If its not going to do that, I strongly urge removing this rpm dependency completely -- its tremendously confusing for an issue that should be very simple. Furthermore, if redhat chooses to roll their own docker rpms and name them differently, then this highly counter-intuitive and confusing behavior should be explicitly called out in the ansible documentation and it made clear what repos a sys admin will need to go to and what version of docker is supported. 

For example something like:
ansible openshift and openshift origin support docker engine 1.12.5 only. You must obtain the rpms from http://mirror.centos.org/centos/7/extras/x86_64/. You cannot use the official docker rpms from https://docs.docker.com/engine/installation/linux/centos/.

That one paragraph would have saved me hours of work.

**Comment by sdodson** [comment]
Do you think it's acceptable for us to enable the centos extras repo by default when installing Origin? We could do that as well.

**Comment by jaloren** [comment]
Yes but :) Sorry for being difficult. My company goes to great length to curate and have a local mirror of all rpms we use. This ensures 1) that we know what's actually be deployed, 2) avoids service interruption if we loose access to an external mirror and 3) reduces network latency and speeds up installation.

If ansible playbook is going to add this "extra" repo (pun intended sorry couldn't resist), that should be clearly and explicitly documented. There should also be a way for a user to specify whether they want to pull it down locally and skip adding the repo in.
