### ISSUE TITLE
Failed task: Ensure various deps are installed

### ISSUE THREAD

**Issue by ngpestelos** [openshift/openshift-ansible#3494]
#### Description

It seems OpenShift's package repo is unavailable.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

```
2.2.0.0
```

If you're operating from a **git clone**:

* The output of `git describe`

```
openshift-ansible-3.5.3-1-389-gaec9cd88
```
##### Steps To Reproduce

1. run `ansible-playbook -i hosts playbooks/byo/config.yml -vvvv`

##### Expected Results

Playbook should be able to download dependencies.

##### Observed Results

<img width="782" alt="screen shot 2017-02-25 at 8 07 36 am" src="https://cloud.githubusercontent.com/assets/5047/23325693/4099793c-fb32-11e6-860d-e6172323f558.png">

##### Additional Information

n/a

**Comment by sdodson** [comment]
This should be fixed by https://github.com/openshift/openshift-ansible/pull/3487

**Comment by ngpestelos** [comment]
It works now; thank you 👍
