### ISSUE TITLE
Consider changing auto_expand_replicas to 0-2

### ISSUE THREAD

**Issue by portante** [openshift/openshift-ansible#3496]
Currently, in the [elasticsearch.yml.j2 template](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging/templates/elasticsearch.yml.j2#L11), we have `auto_expand_replicas: 0-3`, which means that when we have four data nodes, we'll have 1 primary index, and 3 replicas.

It is not clear that by default we need 4 copies of an index for stability.  At most, by default, three is sufficient.

Let's consider changing this to `0-2` to avoid over-replicating by default.

Another question would be to allow a configuration option so that users can affect this via an ansible variable.

**Comment by portante** [comment]
See PR #3468.

**Comment by jcantrill** [comment]
We are still defaulting to 0-2 but this #3647 would allow the user to modify.  Possibly we should be starting at 0 and advising the users how and when to modify this value.  cc @lukas-vlcek

**Comment by portante** [comment]
If we have a simple Small, Medium, Large model for ES configurations, we can just drop this entirely, since those models would contain the prescription for the replication count.

**Comment by jcantrill** [comment]
I am going to leave this open as the source for making the 'calculated' changes.  Based on email thread:

* Small / Experimental  (1 ES pod (master w/ data), 1 shard, 0 replicas)
* Medium (3 ES pods (3 masters w/ data, each in separate failure
domains), 3 shards, 2 replicas)
* Large (3 ES master pods (no data), 3+ client nodes, N data nodes
across three or more failure domains, M shards, 2 replicas)
* Large Performance Tuned (same as Large, but with designated hot /
warm nodes)

[1]http://post-office.corp.redhat.com/archives/eng-common-logging/2017-March/msg00086.html

**Comment by jcantrill** [comment]
#3672 sets value to default which is false.
