### ISSUE TITLE
The logic for handling USE_JOURNAL seems confusing

### ISSUE THREAD

**Issue by portante** [openshift/openshift-ansible#3497]
From PR #3293, it would seem the logic used to handling the `USE_JOURNAL` parameter settings is confusing.  Below is a `bash` script which attempts to emulate how that logic works:

```
#!/bin/bash

USE_JOURNAL=$1

if [ "${USE_JOURNAL:-}" != false ] ; then
   echo "USE_JOURNAL is true"
else
   echo "USE_JOURNAL is false"
fi
```

When one runs this, it yields the following behavior:
```
$ # No parameters ...
$ ./this.bash
USE_JOURNAL is true
$ # Any value that is not 'false' is considered true
$ ./this.bash bad
USE_JOURNAL is true
$ # 'false' is properly considered 'false'
$ ./this.bash false
USE_JOURNAL is false
$ # But 'true' is only considered 'true' because it is not 'false' 
$ ./this.bash true
USE_JOURNAL is true
```

If somebody makes a mistake, and does not specify '`false`' correctly, they'll get a value of '`true`'.

Wouldn't we want the opposite behavior?  For example:

```
#!/bin/bash

USE_JOURNAL=$1

if [ "${USE_JOURNAL:-}" = true ] ; then
   echo "USE_JOURNAL is true"
else
   echo "USE_JOURNAL is false"
fi
```

And then we can set the default value to '`true`' so that we can clearly see and understand how this behaves?

**Comment by ewolinetz** [comment]
This belongs under the `openshift/origin-aggregated-logging` repo as this logic is contained with the Fluentd image (https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/run.sh#L17-L32)
