### ISSUE TITLE
Install nfs-utils on all nodes

### ISSUE THREAD

**Issue by johnjelinek** [openshift/openshift-ansible#350]
nfs-utils and I didn't know why my persistent volumes weren't mounting. It would be good to add this to the playbooks.

**Comment by sdodson** [comment]
This was fixed in the RPM packaging of openshift rather than via ansible. If you're running origin-1.0.2 or later you should get nfs-utils installed everywhere that openshift-node is installed.

https://github.com/openshift/origin/commit/7a8966256430966a395cfb0437042fa72960e8c7
