### ISSUE TITLE
Some Python files being ignored by `setup.py lint`

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-ansible#3500]
While making changes to `roles/lib_openshift/src/test/unit/test_oadm_manage_node.py`, I noticed that it and other files are not being linted.

Seems that the logic in [`setup.py OpenShiftAnsiblePylint.find_all_modules`](https://github.com/openshift/openshift-ansible/blob/641b7c93b1d5ce5388fce66d737704d00a83ec68/setup.py#L128) excludes directories named "test", what might be an oversight.

I believe the test files should be linted as well (they even have `# pylint: disable` comments), @detiber @tbielawa @mtnbikenc @sdodson thoughts?

**Comment by detiber** [comment]
@rhcarvalho I'm good with enabling linting on test files, I'd like to get some agreement from others prior to flipping the switch, though.

**Comment by tbielawa** [comment]
```python
    def find_all_modules(self):
        ''' find all python files to test '''
        exclude_dirs = ['.tox', 'utils', 'test', 'tests', 'git']
```

**THATS** where we're defining exclusions‽ I have racked my brain attempting to figure out where that was being controlled.

* I propose that we also add "move excludes out of CODE and into DATA" as part of this (a future?) change.

**Comment by rhcarvalho** [comment]
FWIW I have a WIP to fix this.

**Comment by rhcarvalho** [comment]
Unfortunately `pylint` only handle exclude patterns on the basename, not on paths. Because of that we need to find files / filter out excludes when calling `pylint` (or write in down in some non-standard config?).
(same thing we were doing in utils/Makefile some weeks/months ago before tox).

**Comment by tbielawa** [comment]
> Unfortunately pylint only handle exclude patterns on the basename, not on paths. Because of that we need to find files / filter out excludes when calling pylint (or write in down in some non-standard config?).

I noticed that just now when I ran a test and looked at the coverage stuff. I'm sure we can do a simple `os.path.walk` or something and exclude those 'test'ish directories from further descent if we wanted to.

**Comment by rhcarvalho** [comment]
@tbielawa I'd doing for now:

```
git ls-files -co --exclude-standard '*.py' | grep -Ev '^(utils|roles/lib_(openshift|utils)/src)/' | xargs pylint
```

- `git ls-files` makes it easy to ignore files that are ignored by git
- `grep` to filter out `utils/` and the `src` dir of roles with code generation

**Comment by detiber** [comment]
> THATS where we're defining exclusions‽ I have racked my brain attempting to figure out where that was being controlled.

> I propose that we also add "move excludes out of CODE and into DATA" as part of this (a future?) change.

I've been meaning to move that into setup.cfg, but haven't gotten to it yet.
