### ISSUE TITLE
Unable to push images to registry (cannot validate certificate)

### ISSUE THREAD

**Issue by ngpestelos** [openshift/openshift-ansible#3516]
#### Description

I've setup a cluster using the BYO playbook. When I tried to build an image, I am unable to push the resulting image to the registry (please refer to screenshot below).

##### Version

* ansible 2.2.0.0
* openshift-ansible-3.5.3-1-410-g77c7b1c2

##### Steps To Reproduce
1. Create an app (e.g. ruby postgresql ephemeral)
2. Watch the build logs

##### Expected Results

<img width="1182" alt="screen shot 2017-02-28 at 5 29 50 am" src="https://cloud.githubusercontent.com/assets/5047/23381438/673fcad4-fd79-11e6-8ea1-511a0d919412.png">

##### Observed Results

I've tried https://github.com/openshift/openshift-ansible/issues/610 but it seems to be for an older version.

##### Additional Information

Inventory file: https://gist.github.com/ngpestelos/e61287b1444216ebead115232e562c8d

**Comment by sdodson** [comment]
Fixed in https://github.com/openshift/openshift-ansible/pull/3512
