### ISSUE TITLE
we need to pull xpaas secret files into /usr/share/openshift/examples/[somewhere]

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-ansible#353]
Each of the xpaas images requires a secret and a service account. The following link has the corresponding json definitions for each:

https://github.com/jboss-openshift/application-templates/tree/ose-v1.0.0/secrets

The installer should pull these in and put them somewhere (eg /usr/share/openshift/examples/[somewhere])

**Comment by detiber** [comment]
@twiest this issue can be closed.  Having the secrets available on the master doesn't help the end user use case of needing to specify the secrets when creating an app from template.

**Comment by sdodson** [comment]
Sorry I missed the IRC conversation, yeah, this is the reason we didn't include the secrets on the master. We assumed that 99% of the folks who needed access to the secrets examples wouldn't actually have access to the master to begin with. The xPaas folks are working on a distribution method to deliver their examples directly to developers.

**Comment by twiest** [comment]
Closing per comments.
