### ISSUE TITLE
servingInfo minTLSVersion and cipherSuites overrides

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#3530]
https://github.com/openshift/origin/pull/13167 allows overriding minimum tls version and cipher suites in any servingInfo config stanza.

It should be possible for a customer to override those values via ansible

**Comment by sdodson** [comment]
What's the likelihood of someone wanting to set these per servingInfo?

**Comment by sdodson** [comment]
Like if I give them two knobs and that sets the values for all is that good enough for 99%?

**Comment by liggitt** [comment]
splitting api and console (asset) doesn't seem useful, since a browser needs to access both

having different ones for the node could *maaaaybe* make sense, since basically only the apiserver talks to the node, so you could keep it at default levels and just relax the API if required for some legacy load balancer or something (the people who want to tighten our defaults would likely want to do it uniformly)
