### ISSUE TITLE
Need to enable origin in quick installer when either building or running on centos

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#3531]
Currently the quick installer SRPM needs to be patched in order to enable origin deployment types because the quick installer has traditionally targetted OCP installs. However this package also ships in Centos so we should make sure that the version shipped there has origin installs enabled and we should do so in a manner which doesn't require SRPM patching which is error prone and often forgotten.

**Comment by sdodson** [comment]
CC: @tdawson

**Comment by tdawson** [comment]
This was obsolete many years ago.
Closing.
