### ISSUE TITLE
Need to deliver roles/contiv/files/loopback via contiv packaging

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#3541]
Can we move roles/contiv/files/loopback somewhere else? We shouldn't be using openshift-ansible to deliver binary files if there's any other way that we could include that in the contiv distribution. This has broken our RPM build process because our ansible playbooks are noarch packages so I'm going to temporarily remove the contiv role from our RPMs.

**Comment by sdodson** [comment]
@srampal @jcpowermac @danyc97 thoughts?

**Comment by srampal** [comment]
@sdodson  We will look into options for this and get back to you.

**Comment by sdodson** [comment]
Also, is contiv only built and supported on x86_64? Origin will soon work on other arches such as ppc64 and aarm64

**Comment by DanyC97** [comment]
@sdodson what time window are you guys looking for others arches ? (just curious to see how far are you from it)

**Comment by srampal** [comment]
@sdodson contiv is only built and supported on x86_64 currently.

**Comment by sdodson** [comment]
> @sdodson contiv is only built and supported on x86_64 currently.

No specific timeline, I know the whole toolchain needs to be vetted and I believe golang bits are now ready. Next would be origin itself.
