### ISSUE TITLE
Requirement of Python 3 on Fedora isn't documented

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-ansible#3543]
Requirement of using Python 3 on Fedora isn't documented https://github.com/openshift/openshift-ansible#setup but without it installation fails:

```
$ ansible-playbook playbooks/byo/openshift_facts.yml -i aws.inventory 
...
TASK [openshift_facts : Validate python version] *******************************
fatal: [ec2-xx-xxx-xxx-xxx.compute-1.amazonaws.com]: FAILED! => {
	"changed": false, 
	"failed": true
}

MSG:

openshift-ansible requires Python 3 for Fedora;
For information on enabling Python 3 with Ansible, see https://docs.ansible.com/ansible/python_3_support.html
...
```
Also when there is two versions of Python installed, we have to tell ansible which one it should use by adding to inventory file the following:
```
[OSEv3:vars]
ansible_python_interpreter=/usr/bin/python3
```

**Comment by jfmatth** [comment]
Can i add that i have yet to get Fedora Atomic to work correctly on an openshift-ansible deployment with logging and metrics?  

Comparing Centos and Fedora atomic deployments seems to revolve around the fact that python3 is mandated in fedora not centos.

HTH
