### ISSUE TITLE
Install python3-dbus package instead of python-dbus when Python3 is used

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-ansible#3544]
I'm using Fedora on my host and Fedora on the managed hosts. I'm using Python3 (see #3543).

Installation fails with:
```
TASK [openshift_facts : Gather Cluster facts and set is_containerized if needed] ***
fatal: [ec2-xx-xxx-xx-xx.compute-1.amazonaws.com]: FAILED! => {
	"changed": false, 
	"failed": true
}

MSG:

This module requires dbus python bindings
```

It turns out (thank you @rhcarvalho!) that installer installs `python-dbus` package on the nodes while it should install `python3-dbus` package in case of using Python3.

**Comment by php-coder** [comment]
Workaround 1:
install `python3-dbus` package manually with command `ansible all -i my.inventory -m shell -a 'dnf install -y python3-dbus'`

Workaround 2:
```
--- roles/openshift_facts/vars/main.yml
+++ roles/openshift_facts/vars/main.yml
@@ -1,7 +1,7 @@
 ---
 required_packages:
   - iproute
-  - python-dbus
+  - python3-dbus
   - python-six
   - PyYAML
   - yum-utils
```

**Comment by sdodson** [comment]
Perhaps
`  - "{{ 'python3-dbus' if ansible_distribution == 'Fedora' else 'python-dbus' }}"`
Unfortunately RHEL7 doesn't have python3-dbus nor does it have python2-dbus

**Comment by php-coder** [comment]
I was thinking about using distribution-specific vars files (https://ansible-tips-and-tricks.readthedocs.io/en/latest/os-dependent-tasks/variables/). Or it is an overkill here?

**Comment by sdodson** [comment]
I think that'd work well.

**Comment by zonArt** [comment]
Looks like on oracle-linux and on centos, package name is inverted (dbus-python instead of python-dbus). Could be an idea to think about alternative distros as well. Thanks
