### ISSUE TITLE
Adding roles/lib_openshift/library to ansible_library breaks ansible-doc -l

### ISSUE THREAD

**Issue by alvaroaleman** [openshift/openshift-ansible#3559]
#### Description

Adding `roles/lib_openshift/library` to ansible_library breaks `ansible-doc -l`

##### Version

openshift-ansible 6ecb86b2fcc36e3383d86395d3be0a443e12981e
ansible 2.2.0.0

##### Steps To Reproduce
1. git clone git@github.com:openshift/openshift-ansible.git
2. export ANSIBLE_LIBRARY=$(pwd)/openshift-ansible/roles/lib_openshift/library
3. ansible-doc -l

##### Expected Results

A list of all available modules

##### Observed Results

```
 [ERROR]: unable to parse /tmp/openshift-ansible/roles/lib_openshift/library/oc_adm_router.py

 [ERROR]: unable to parse /tmp/openshift-ansible/roles/lib_openshift/library/oc_env.py

ERROR! module oc_env has a documentation error formatting or is missing documentation

```

**Comment by detiber** [comment]
@alvaroaleman thanks for reporting this issue, I've created #3560 to address it.
