### ISSUE TITLE
Add tags to prepare immutable image

### ISSUE THREAD

**Issue by mcapuccini** [openshift/openshift-ansible#3561]
#### Description

Hello! The installation through Ansible takes quite a bit of time, so I was trying to understand if it would be possible to create an immutable image in my cloud providers in order to speed up a bit the process. Does exist any tag in your roles to run only tasks that can be executed before the cluster deployment (e.g. packages installation, images pull)? Or if it doesn't exist is there any other way to figure out what can be run before the actual deployment, so one can prepare a preprovisioned image?

**Comment by sdodson** [comment]
Not currently, we'd like to break the installation into two parts enabling folks to bake gold images and then configure the host assuming that everything is pre-installed. We haven't yet looked into it so I'm not sure the approach we'd take.

**Comment by mcapuccini** [comment]
@sdodson what about using `containerized=true` and prepull:
- openshift/origin
- openshift/node 
- openshift/openvswitch
- registry.access.redhat.com/rhel7/etcd
reference: https://docs.openshift.org/latest/install_config/install/rpm_vs_containerized.html
