### ISSUE TITLE
Add option configure jenkinsPipelineConfig

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-ansible#3562]
The Jenkins pipeline config should be added to the master-config.yaml configurable so eg. jenkins-persistent could be used instead of jenkins-empheral

https://docs.openshift.org/latest/install_config/configuring_pipeline_execution.html

**Comment by sdodson** [comment]
@bparees Any reason not to automate this during installation? What points of configuration would we need to provide?

**Comment by bparees** [comment]
@sdodson no particular reason not to, no.

we'd probably want to allow configuration of all the fields shown in that example.
