### ISSUE TITLE
"ansible_facts" empty when used to output module result

### ISSUE THREAD

**Issue by juanvallejo** [openshift/openshift-ansible#3564]
#### Description

When using an ansible module, such as [docker_container](https://docs.ansible.com/ansible/docker_container_module.html), the module's output is placed under a key named [ansible_facts](https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker_container.py#L1672) in the dictionary that it returns. However, that key returns with an empty value by the time it has gone through [module.exit_json](https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker_container.py#L2010).

Note that is is only an issue when executing a module from a python file using the [module_executor](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_health_checker/openshift_checks/package_version.py#L20).

Also, placing the module's output under any key name that is not `ansible_facts` works, allowing the python file that executed the module to read its results successfully.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

##### Steps To Reproduce
1. Execute an ansible module, that places its results under `ansible_facts` in its returned dictionary (such as `docker_container`), from a python file using the [module_executor](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_health_checker/openshift_checks/package_version.py#L20)
and attempt to read results.

##### Expected Results
Module's output appears under documented key inside of `ansible_facts`.

```
Example command and output or error messages
```

##### Observed Results
`ansible_facts` is present in module's returned dictionary but has an empty object as its value.

```
results = self.module_executor("docker_container", {"name": "my_image", task_vars})
return {"msg": "%s" % results["ansible_facts"]}
```

cc @rhcarvalho @brenton

**Comment by rhcarvalho** [comment]
@juanvallejo perhaps this is a better fit for https://github.com/ansible/ansible/issues?
And then, replace the reference to our OpenShiftCheck class with a direct use of an action plugin:

```python
class Example(ActionPlugin):
    def run(self, ...):
        self._execute_module(...)
```

**Comment by detiber** [comment]
@rhcarvalho It looks like it is by design:
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/__init__.py#L776-L834

**Comment by detiber** [comment]
@juanvallejo @rhcarvalho: actually, I think it's getting sanitized because of the Encoding/Decoding issue in 2.2.1.0: https://github.com/ansible/ansible/blob/devel/lib/ansible/vars/unsafe_proxy.py
