### ISSUE TITLE
Issue with Console after install

### ISSUE THREAD

**Issue by Delmonte3161** [openshift/openshift-ansible#3591]
I have run the ansible installation (latest master) on a stack consisting of 3 masters, 3 etds, 1 lb, 3 nodes, and 1 installer node.  After much work, including running the older version of ansible and adding host prep steps to enable NetworkManager, the installation completed successfully.  However, I'm having issues verifying the install and need help figuring out what the issue is.

The nodes verification checked out fine.
[cloud-user@k8s-master-0 bin]$ oc get nodes
```
NAME            STATUS                     AGE
192.168.1.100   Ready,SchedulingDisabled   1h
192.168.1.101   Ready,SchedulingDisabled   1h
192.168.1.102   Ready,SchedulingDisabled   1h
192.168.1.20    Ready                      1h
192.168.1.21    Ready                      1h
192.168.1.22    Ready                      1h
```

However, when I attempt to reach the console via this URL (https://k8s-lb-0:8443/console/), the Openshift Origin console opens and displays a banner but the window just hangs on "Loading..." (after I accept certificates and such).  It behaves the same when using any of the master nodes as well.

Additionally, trying to follow the steps to verify the etcd cluster FROM the master nodes isn't working because etcdctl is not installed on the master nodes.
```
[cloud-user@k8s-master-0 bin]$ etcdctl -C \
>     https://192.168.1.30:2379,https://192.168.1.31:2379,https://192.168.1.32:2379 \
>     --ca-file=/etc/origin/master/master.etcd-ca.crt \
>     --cert-file=/etc/origin/master/master.etcd-client.crt \
>     --key-file=/etc/origin/master/master.etcd-client.key cluster-health
-bash: etcdctl: command not found
```

If an "Issue" isn't the correct forum to go about this let me know and I can take the questions to the appropriate venue.

**Comment by Delmonte3161** [comment]
I initially had my master nodes not schedulable.  I corrected that and now the pods look good.  

```
[cloud-user@k8s-master-0 ~]$ oc get nodes
NAME            STATUS    AGE
192.168.1.100   Ready     18h
192.168.1.101   Ready     18h
192.168.1.102   Ready     18h
192.168.1.20    Ready     18h
192.168.1.21    Ready     18h
192.168.1.22    Ready     18h
[cloud-user@k8s-master-0 ~]$ oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-ux7zy    1/1       Running   0          31m
registry-console-1-bjfkf   1/1       Running   3          17h
router-3-iubv6             1/1       Running   0          30m
```

But the console still doesn't work.  I get the OpenShift banner/logo and "Loading..." in the center of the window.

**Comment by sdodson** [comment]
Regarding etcdctl, you're probably running embedded etcd because a host wasn't defined in the etcd group, so you need to install etcd for the client tools.  `yum install etcd`

For the console, I bet it's redirecting you to an ouath page or something and that's failing. Can you post the contents of /etc/origin/master/master-config.yaml? Feel free to redact any sensitive info but there's usually not any.

**Comment by Delmonte3161** [comment]
I'll gather the config (and follow up with another comment).

Regarding the etcd, no I am not running embedded etcd.  They are running on dedicated hosts and the etcd service is running on them (and etcdctl is available on those nodes).  etcdctl is just not available on the master nodes and the verification step had you executing it FROM a master node.

**Comment by Delmonte3161** [comment]
Here's the master config (I just grabbed it from the first master node).  All the URLs in this config are referencing the private ips.  Since this is in OpenStack, I am accessing the console from my browser via the node's public IP.  I don't know if that is causing any issues or not.  I configured the cluster in the ansible hosts file all with the private IPs.

[master-config.yaml.txt](https://github.com/openshift/openshift-ansible/files/828640/master-config.yaml.txt)

**Comment by Delmonte3161** [comment]
I re-installed from scratch, this time using the stable 1.4 release and also configuring my public master url to match the public ip of one of my master nodes (I don't have a load balancer in front of these public ips yet).  This enabled me to launch the console and reach the login prompt.  However, I do not seem to be able to log in with anything.  The page just hangs presumably authenticating the user.  Where are the logs where I can see what is happening here?
