### ISSUE TITLE
TASK [openshift_excluder : Install docker excluder] failed

### ISSUE THREAD

**Issue by sjenning** [openshift/openshift-ansible#3603]
Trying to do RPM install against fresh CentOS7 cloud instance (having already run `yum update -y`)

```
TASK [openshift_excluder : Install docker excluder] ****************************
fatal: [origin-master.local.variantweb.net]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "rc": 126, 
    "results": [
        "No package matching 'origin-docker-excluder' found available, installed or updated"
    ]
}

MSG:

No package matching 'origin-docker-excluder' found available, installed or updated
```

My theory is that the origin repo isn't being added before the step is executed.  The package is here:
http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/

@sdodson

**Comment by Delmonte3161** [comment]
I am having this issue as we speak.  The ansible script worked yesterday but fails today (running against fresh infrastructure).  Did something change?

`No package matching 'origin-docker-excluder' found available, installed or updated`
