### ISSUE TITLE
configure OpenShift console/api on an another port 

### ISSUE THREAD

**Issue by kkurpanik** [openshift/openshift-ansible#3652]
Is there any way to change the default API port 8443 to another one?

I have tried so far the following two options but without success:
openshift_master_console_port=6443
openshift_master_api_port=6443

installation playbook is failing on Veritfy API Server step with error:

fatal: [master]: FAILED! => {
    "attempts": 120, 
    "changed": false, 
    "cmd": [
        "curl", 
        "--silent", 
        "--tlsv1.2", 
        "--cacert", 
        "/etc/origin/master/ca-bundle.crt", 
        "https://vw-lin-rhel7-10.cloud.lab:6443/healthz/ready"
    ], 
    "delta": "0:00:00.009678", 
    "end": "2017-03-14 16:31:06.016004", 
    "failed": true, 
    "rc": 7, 
    "start": "2017-03-14 16:31:06.006326", 
    "warnings": []
}

**Comment by sferich888** [comment]
https://curl.haxx.se/libcurl/c/libcurl-errors.html

CURLE_COULDNT_CONNECT (7)
Failed to connect() to host or proxy.

Have you opened up the fire wall to make sure that port is accessible?

**Comment by vrutkovs** [comment]
Right, `default_r_openshift_master_os_firewall_allow` should include `openshift_master_console_port`
