### ISSUE TITLE
openshift_examples failes

### ISSUE THREAD

**Issue by automatikdonn** [openshift/openshift-ansible#366]
failed: [*****REDACTED****] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-centos7.json"], "delta": "0:00:00.242828", "end": "2015-07-18 18:34:58.819948", "failed": true, "failed_when_result": true, "rc": 1, "start": "2015-07-18 18:34:58.577120", "stdout_lines": [], "warnings": []}
stderr: The connection to the server *****REDACTED****:8443 was refused - did you specify the right host or port?

Its trying to download examples before the server starts. This task needs to get pushed the the end

**Comment by detiber** [comment]
https://github.com/openshift/openshift-ansible/pull/374 <- we were testing the variable for the multi-master use case as a boolean without using the bool filter, so the master wasn't properly started.

**Comment by automatikdonn** [comment]
Please mark as resolved.

**Comment by detiber** [comment]
@twiest please close.

**Comment by twiest** [comment]
Closing per comment.
