### ISSUE TITLE
openshift_manage_node Install doesn't start Master for node to register to

### ISSUE THREAD

**Issue by automatikdonn** [openshift/openshift-ansible#367]
the only processes that starts is etcd, openshift master doesn't start for the node to register with.

WORKAROUND - Open new ssh session with master and exec

openshift start master --config=/etc/openshift/master/master-config.yaml

result
ansible script completes

**Comment by detiber** [comment]
https://github.com/openshift/openshift-ansible/pull/374 <- we were testing the variable for the multi-master use case as a boolean without using the bool filter, so the master wasn't properly started.

**Comment by automatikdonn** [comment]
Mark as resolved please.

**Comment by detiber** [comment]
@twiest please close.

**Comment by twiest** [comment]
Closing per comment.
