### ISSUE TITLE
openshift_master | Install OpenShift Master package

### ISSUE THREAD

**Issue by johnjelinek** [openshift/openshift-ansible#370]
On the first run of the ansible playbook for origin, there is some step that is removing `nameserver 8.8.8.8` from `/etc/resolv.conf`. This is causing the following step to fail. If I rerun the playbook after this fail, it continues on as normal (only if I re-add `nameserver 8.8.8.8` to `/etc/resolv.conf`).

```
TASK: [openshift_master | Install OpenShift Master package] *******************
failed: [osv3-master.johnjelinek.com] => {"changed": false, "failed": true, "rc": 0, "results": []}
msg: No Package matching 'openshift-master' found available, installed or updated

FATAL: all hosts have already failed -- aborting
```

**Comment by detiber** [comment]
@johnjelinek how are you invoking ansible again?  I'm not aware of anything that should be removing the nameserver within the playbooks.  The VagrantFile mucks with the hosts file and using bin/cluster with openstack appears to as well. Outside of that I'm not seeing any references.

**Comment by johnjelinek** [comment]
`ansible-playbook playbooks/byo/config.yml`

**Comment by smarterclayton** [comment]
I'm seeing this on ec2 as well.  Empty /etc/resolv.conf

**Comment by smarterclayton** [comment]
Nm, it was VPC with the default DHCP setting and the subnet not having any.

**Comment by detiber** [comment]
@johnjelinek The situation that @smarterclayton described I could easily see causing the behavior you are describing...  if to use a VPC/subnet that does not assign DNS, then you would want to configure NetworkManager to prepend a chosen dns server on the eth0 interface by creating /etc/hdcp/dhclient-eth0.conf containing: `prepend domain-name-servers 8.8.8.8`

There is also a way to tell NetworkManager to not manage resolv.conf, but I cannot remember the conf file/setting combination for that off the top of my head.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
