### ISSUE TITLE
No package matching 'origin-docker-excluder'

### ISSUE THREAD

**Issue by DarkBlaez** [openshift/openshift-ansible#3705]
OS: Centos 7
Ansible: 2.4.0

I set up 2 masters, 2 etcd, 1 lb, 4 nodes. Playbook stops with:
No package matching 'origin-docker-excluder' found available, installed or updated across all masters and all nodes.

I saw other issues similar and thought this fix was checked in. However, this persist on current git pull

What is the resolution?

Thanks
DB

**Comment by wicksy** [comment]
+1

**Comment by glenfordwilliams** [comment]
im also having this issue

**Comment by sdodson** [comment]
You should be able to work around this by setting enable_excluders=false in your inventory. This is happening due to a bug in the excluder packages themselves where origin-excluder excludes origin-docker-excluder so as soon as that package is installed the other is excluded from yum.

I guess the proper way forward is for us to disable this functionality unless they're running Origin 1.5 GA (yet to be released) which has the fix for this.

**Comment by DarkBlaez** [comment]
Using current 3.6 release and/or including current git pull, putting enable_excluders=false in the inventory yields another error

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_release=v1.4
osn_storage_plugin_deps=['glusterfs']
openshift_node_kubelet_args={'max-pods': ['40'], 'image-gc-high-threshold': ['90'], 'image-gc-low-threshold': ['80']}
enable_excluders=false

[...]

Error reported across the 2 masters and 4 nodes:

TASK [openshift_excluder : Enable docker excluder] ************************************************************
fatal: [osmaster01.dripple.io]: FAILED! => {
    "changed": false, 
    "cmd": "origin-docker-excluder exclude", 
    "failed": true, 
    "rc": 2
}

MSG:

[Errno 2] No such file or directory

Am I doing something wrong here? I assumed setting this in the VARS section would address this?

Thanks
DB

**Comment by DarkBlaez** [comment]
enable_docker_excluder=false instead of enable_excluders=false allowed the playbook to run and complete without errors. Not sure why the first method did not work and what the impact will be. I assume this will be all fixed per prior mention once Origin 1.5GA is release

**Comment by sdodson** [comment]
Master should be fixed now as far as only needing `enable_excluders=false` I'll work on disabling this by default in origin today until centos paas sig repo has fixed excluder packages.

**Comment by jfillman** [comment]
I'm running into the same issue while trying to build origin in AWS. Sorry for my ignorance as i'm just getting familiar with ansible but WRT to the inventory config in the openshift-ansible-contrib git repo, where exactly do i add the 'enable-excluders=false' directive?

I don't see a typical inventory file with an [OSEv3:vars] section.

**Comment by kevin-youtechgrp** [comment]
For openshift-ansible-contrib, can add `enable_excluders=false` to the ansible-playbook command extra-vars list to apply the workaround
