### ISSUE TITLE
Switching from openshift-ovs-multitenant to flannel

### ISSUE THREAD

**Issue by J0hnson** [openshift/openshift-ansible#3706]
oc v1.4.1
kubernetes v1.4.0+776c994

I am using openshift-ovs-multitenant in openshift, is it possible to change to flannel without reinstall?

Thanks

**Comment by sdodson** [comment]
No, I don't believe it is possible in general and I know we don't automate that in the installer.

**Comment by sdodson** [comment]
@vishpat may have some guidance on how to move an existing environment to sdn
