### ISSUE TITLE
openshift_node_certificates | Generate the node client config

### ISSUE THREAD

**Issue by johnjelinek** [openshift/openshift-ansible#371]
This step always fails if I run the retry command: `ansible-playbook playbooks/byo/config.yml --limit @/Users/jjelinek/config.retry`

**Comment by detiber** [comment]
https://github.com/openshift/openshift-ansible/pull/374 <- we were testing the variable for the multi-master use case as a boolean without using the bool filter, so the master wasn't properly started.

**Comment by johnjelinek** [comment]
This error is present before HA masters too.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
