### ISSUE TITLE
if openshift_hosted_metrics_public_url is defined should always be populated

### ISSUE THREAD

**Issue by juanluisvaladas** [openshift/openshift-ansible#3717]
When ```openshift_hosted_metrics_deploy``` is set to ```false```, ```assetConfig.metricsPublicURL``` is not populated in master-config.yaml even if ```openshift_hosted_metrics_public_url``` is defined explicitly.

I consider wanting to deploy the metrics manually but having the config playbook filling correctly the ```metricsPublicURL``` is a valid use case. Specially considering that if the ```metrics-deployer``` pod is deleted the playbook will attempt to redeploy metrics.

**Comment by sdodson** [comment]
This is fixed on master, in #2973
