### ISSUE TITLE
Ansible Origin Playbook with YAML Syntax Error

### ISSUE THREAD

**Issue by gbaufake** [openshift/openshift-ansible#3719]
YAML Syntax Error
```
ansible 2.2.1
openshift-ansible-3.6.4-1-11-g03ae7f7
```

##### Steps To Reproduce
1. Clone this Repository
2. Install Ansible
3. Run ``ansible-playbook openshift-ansible/inventory/byo/hosts.origin.example``

##### Expected Results
```
ERROR! Syntax Error while loading YAML.

The error appears to have been in '/openshift-ansible/inventory/byo/hosts.origin.example': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
      ^ here
```

##### Additional Information

* RHEL 7.2

**Comment by sdodson** [comment]
You need to pass the inventory with the -i flag, it's treating your inventory as the playbook. You should run it more like this.

`ansible-playbook -i openshift-ansible/inventory/byo/hosts.origin.example playbooks/byo/config.yml`

**Comment by Petrox** [comment]
FYI quick hint:

 One possible reason for this message is when you write a line without an equals sign in the vars(!) block like this.

    openshift_clock_enabled true

instead of

    openshift_clock_enabled=true

The error message is not clear, but after a few wtf minutes one might find the host-looking variable definition.
