### ISSUE TITLE
file name={{ sync_tmpdir }} state=absent

### ISSUE THREAD

**Issue by johnjelinek** [openshift/openshift-ansible#372]
Maybe this requires rsync to be preinstalled?
```
TASK: [file name={{ sync_tmpdir }} state=absent] ******************************
FATAL: no hosts matched or all hosts have already failed -- aborting
```

**Comment by detiber** [comment]
This looks to be related to the other failures that were stemming from the incorrect testing for master ha.
https://github.com/openshift/openshift-ansible/pull/374
