### ISSUE TITLE
Getting stuck at: TASK: [setup]

### ISSUE THREAD

**Issue by elasti-ronenc** [openshift/openshift-ansible#3732]
Trying to add nodes into openshift, add the relevant nodes as [new_nodes]
and run
ansible-playbook -K -i File.erb ../../ansible/playbooks/byo/openshift-node/scaleup.yml  

and it stuck at task :
TASK: [setup]
anyone can assist ?

**Comment by abutcher** [comment]
Hey @elasti-ronenc, which versions of ansible/openshift-ansible are you using and how many nodes are you adding? Also, is it hanging at the first `[setup]` task encountered?

**Comment by elasti-ronenc** [comment]
Hi @abutcher , it was SSH issues...
i reboot the master and it worked
thanks
i will update with results

**Comment by abutcher** [comment]
Cool, thanks @elasti-ronenc
