### ISSUE TITLE
Deployment type / openshift.common.service_type documentation

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-ansible#3751]
There is some documentation about the available deployment types in https://github.com/openshift/openshift-ansible/blob/master/DEPLOYMENT_TYPES.md, however this information has not been updated since it's introduction in Aug 26, 2015.

We're relying on the value of `openshift.common.service_type` in health checks, would be good to have up-to-date documentation to rely on.

**Comment by rhcarvalho** [comment]
@sdodson if you could provide some information to update that table, or point me to someone who would know, I can go ahead and create a PR to update the docs.

Thanks!

**Comment by sosiouxme** [comment]
https://github.com/openshift/openshift-ansible/blob/8e26f8cf9594693702fd1e545b47116cbbff34f0/roles/openshift_repos/vars/main.yml should be current for specifying `deployment_type` which feeds into `openshift.common.service_type`.
