### ISSUE TITLE
FAILED - RETRYING: TASK: openshift_master : Start and enable master (1 retries left)

### ISSUE THREAD

**Issue by m4ri01** [openshift/openshift-ansible#3774]
always get this error when i installing ansible playbook, heres my error

> TASK [openshift_master : Start and enable master] ******************************
FAILED - RETRYING: TASK: openshift_master : Start and enable master (1 retries left).
fatal: [10.70.70.123]: FAILED! => {"attempts": 1, "changed": false, "failed": true, "msg": "Unable to start service origin-master: Job for origin-master.service failed because the control process exited with error code. See \"systemctl status origin-master.service\" and \"journalctl -xe\" for details.\n"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP *********************************************************************
10.70.70.123               : ok=299  changed=11   unreachable=0    failed=1   
localhost                  : ok=9    changed=0    unreachable=0    failed=0   
and here is my systemctl status origin master

> ● origin-master.service - Origin Master Service
   Loaded: loaded (/usr/lib/systemd/system/origin-master.service; enabled; vendor preset: disabled)
   Active: activating (start) since Sab 2017-03-25 20:23:27 WIB; 4s ago
     Docs: https://github.com/openshift/origin
 Main PID: 1886 (openshift)
   CGroup: /system.slice/origin-master.service
           └─1886 /usr/bin/openshift start master --config=/etc/origin/master/master-config.yaml --loglevel=2

Mar 25 20:23:31 alpha.gulo.local origin-master[1886]: E0325 20:23:31.006383    1886 cacher.go:254] unexpected ListAndWatch error: pkg/....local
Mar 25 20:23:31 alpha.gulo.local origin-master[1886]: E0325 20:23:31.014990    1886 cacher.go:254] unexpected ListAndWatch error: pkg/....local
Mar 25 20:23:31 alpha.gulo.local origin-master[1886]: E0325 20:23:31.015343    1886 cacher.go:254] unexpected ListAndWatch error: pkg/....local
Mar 25 20:23:31 alpha.gulo.local origin-master[1886]: E0325 20:23:31.021858    1886 cacher.go:254] unexpected ListAndWatch error: pkg/....local
Mar 25 20:23:31 alpha.gulo.local origin-master[1886]: E0325 20:23:31.022150    1886 cacher.go:254] unexpected ListAndWatch error: pkg/....local
Mar 25 20:23:31 alpha.gulo.local origin-master[1886]: E0325 20:23:31.958640    1886 reflector.go:203] github.com/openshift/origin/vendor/k8s...
Mar 25 20:23:31 alpha.gulo.local origin-master[1886]: E0325 20:23:31.962466    1886 reflector.go:203] github.com/openshift/origin/vendor/k8s...
Mar 25 20:23:31 alpha.gulo.local origin-master[1886]: E0325 20:23:31.977332    1886 reflector.go:214] github.com/openshift/origin/vendor/k8s...
Mar 25 20:23:31 alpha.gulo.local origin-master[1886]: E0325 20:23:31.977408    1886 reflector.go:214] github.com/openshift/origin/vendor/k8s...
Mar 25 20:23:31 alpha.gulo.local origin-master[1886]: E0325 20:23:31.977559    1886 reflector.go:214] github.com/openshift/origin/vendor/k8s...
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by sdodson** [comment]
@m4ri01 Can you gather the master logs with `--no-pager` flag so that it gets the entire line, all of your log entries were truncated unfortunately.
