### ISSUE TITLE
failed installation - kernel: vxlan: Cannot bind port 4789, err=-97

### ISSUE THREAD

**Issue by carljmosca** [openshift/openshift-ansible#3775]
#### Description

After attempting a multi-master installation, nodes will not start.
##### Version

Please put the following version information in the code block
indicated below.

ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

openshift-ansible-3.6.9-1

master branch

installing via playbooks
##### Steps To Reproduce

ansible-playbook ~/openshift-ansible/playbooks/byo/openshift-cluster/config.yml 

##### Expected Results

Successful installation.

##### Observed Results
Describe what is actually happening.

FAILED - RETRYING: TASK: openshift_node : Start and enable node (1 retries left).
fatal: [REPLACED_HOST_NAME]: FAILED! => {"attempts": 1, "changed": false, "failed": true, "msg": "Unable to start service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information
Excerpt from journalctl -xe
```
Mar 25 11:29:52 MASTER-NODE-REPLACED-NAME origin-node[23418]: F0325 11:29:52.237522   23418 node.go:350] error: SDN node startup failed: Allocated ofport (-1) did not match request (1)
Mar 25 11:29:52 MASTER-NODE-REPLACED-NAME systemd[1]: origin-node.service: main process exited, code=exited, status=255/n/a
Mar 25 11:29:52 MASTER-NODE-REPLACED-NAME systemd[1]: Failed to start Origin Node.
Mar 25 11:29:52 MASTER-NODE-REPLACED-NAME systemd[1]: Unit origin-node.service entered failed state.
Mar 25 11:29:52 MASTER-NODE-REPLACED-NAME systemd[1]: origin-node.service failed.
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME systemd[1]: origin-node.service holdoff time over, scheduling restart.
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME systemd[1]: Cannot add dependency job for unit iptables.service, ignoring: Unit is masked.
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME systemd[1]: Starting Origin Node...
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME origin-node[23484]: I0325 11:29:57.762622   23484 node.go:61] Initializing SDN node of type "redhat/openshift-ovs-subnet" with configured hostname "MASTER-NODE-REPLACED-NAME" (IP ""), iptables sync period "30s"
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME origin-node[23484]: I0325 11:29:57.773608   23484 docker.go:418] Connecting to docker on unix:///var/run/docker.sock
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME origin-node[23484]: I0325 11:29:57.773638   23484 docker.go:438] Start docker client with request timeout=2m0s
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME origin-node[23484]: I0325 11:29:57.778087   23484 start_node.go:303] Starting node MASTER-NODE-REPLACED-NAME (v1.4.1)
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME origin-node[23484]: I0325 11:29:57.779433   23484 start_node.go:312] Connecting to API server https://MASTER-REPLACED-NAME:8443
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME origin-node[23484]: I0325 11:29:57.780783   23484 docker.go:418] Connecting to docker on unix:///var/run/docker.sock
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME origin-node[23484]: I0325 11:29:57.780855   23484 docker.go:438] Start docker client with request timeout=0s
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME dockerd-current[16015]: time="2017-03-25T11:29:57.781496605-04:00" level=info msg="{Action=_ping, LoginUID=4294967295, PID=23484}"
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME origin-node[23484]: I0325 11:29:57.782374   23484 node.go:141] Connecting to Docker at unix:///var/run/docker.sock
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME origin-node[23484]: I0325 11:29:57.880860   23484 manager.go:140] cAdvisor running in container: "/system.slice/origin-node.service"
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME origin-node[23484]: W0325 11:29:57.956063   23484 manager.go:148] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME ovs-vsctl[23532]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --if-exists del-br br0 -- add-br br0 -- set Bridge br0 fail-mode=secure protocols=OpenFlow13
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME ovs-vsctl[23533]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --if-exists del-port br0 vxlan0
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME ovs-vsctl[23534]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --may-exist add-port br0 vxlan0 -- set Interface vxlan0 ofport_request=1 type=vxlan "options:remote_ip=\"flow\"" "options:key=\"flow\""
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME kernel: vxlan: Cannot bind port 4789, err=-97
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME origin-node[23484]: F0325 11:29:57.996792   23484 node.go:350] error: SDN node startup failed: Allocated ofport (-1) did not match request (1)
Mar 25 11:29:57 MASTER-NODE-REPLACED-NAME systemd[1]: origin-node.service: main process exited, code=exited, status=255/n/a
Mar 25 11:29:58 MASTER-NODE-REPLACED-NAME systemd[1]: Failed to start Origin Node.
Mar 25 11:29:58 MASTER-NODE-REPLACED-NAME systemd[1]: Unit origin-node.service entered failed state.
Mar 25 11:29:58 MASTER-NODE-REPLACED-NAME systemd[1]: origin-node.service failed.
```
Red Hat Enterprise Linux Server release 7.3 (Maipo)

Inventory file:
```
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
etcd
lb

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
enable_excluders=false

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
# openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/openshift/openshift-passwd'}]

# master cluster ha variables using pacemaker or RHEL HA
openshift_master_cluster_hostname=cloud-master.REPLACED.DOMAIN
openshift_master_cluster_public_hostname=cloud-master.REPLACED.DOMAIN
openshift_master_cluster_method=native

# apply updated node defaults
openshift_node_kubelet_args={'pods-per-core': ['10'], 'max-pods': ['250'], 'image-gc-high-threshold': ['90'], 'image-gc-low-threshold': ['80']}

# override the default controller lease ttl
#osm_controller_lease_ttl=30

# enable ntp on masters to ensure proper failover
openshift_clock_enabled=true

# osm_default_subdomain=cloud.REPLACED.DOMAIN

# host group for masters
[masters]
cloud-m1e.REPLACED.DOMAIN
cloud-m2e.REPLACED.DOMAIN
cloud-m1w.REPLACED.DOMAIN

# host group for etcd
[etcd]
cloud-e1e.REPLACED.DOMAIN
cloud-e1w.REPLACED.DOMAIN
cloud-e2w.REPLACED.DOMAIN

# Specify load balancer host
[lb]
cloud-master.REPLACED.DOMAIN

# host group for nodes, includes region info
[nodes]
cloud-m1e.REPLACED.DOMAIN openshift_schedulable=False openshift_node_labels="{'region': 'infra', 'zone': 'default-east'}"
cloud-m2e.REPLACED.DOMAIN openshift_schedulable=False openshift_node_labels="{'region': 'infra', 'zone': 'default-east'}"
cloud-m1w.REPLACED.DOMAIN openshift_schedulable=False openshift_node_labels="{'region': 'infra', 'zone': 'default-west'}"
cloud-h1e.REPLACED.DOMAIN openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
cloud-h2e.REPLACED.DOMAIN openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
cloud-h1w.REPLACED.DOMAIN openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
cloud-h2w.REPLACED.DOMAIN openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
```

**Comment by knobunc** [comment]
@carljmosca What was the resolution here?

**Comment by rafaleon15** [comment]
Please @carljmosca, comment here. I am also blocked with this.

**Comment by knobunc** [comment]
It may be that you are hitting a kernel bug where it failed when IPv6 was disabled.  It was trying to bind to both IPv4 and v6 and failing if either failed.

**Comment by carljmosca** [comment]
I will try to piece together what was done to get past this.  I do recall upgrading and downgrading a combination of the kernel, docker, and ansible (running on RHEL 7).  I created this and at least one other issue and it seemed there was little to no interest/activity here.

**Comment by poltorres7** [comment]
@carljmosca @rafaleon15 Does someone get any solution. I am stuck in the same issue. please share your knowledge.

**Comment by carljmosca** [comment]
I will try to work back through the steps:

@poltorres7 What version of origin-sdn-ovs do you have?  I am running origin-sdn-ovs-1.4.1-1.el7.x86_64.

I believe a downgrade was required.

**Comment by poltorres7** [comment]
I have the same version

**Comment by carljmosca** [comment]
Assuming you're using the master branch, try moving back to release-1.2

**Comment by rafaleon15** [comment]
@poltorres7 did it work?

**Comment by poltorres7** [comment]
@rafaleon15  unfortunately it didn't work for me, I try my installation in a new host and I've progress with other issues. I've consult a redhat expert, and he told me that there was a problen with the SDN service in the master. I tried to restart the atomic-openshift-master.service but it didn't work :( . I'm new in this, I hope I've help you.

**Comment by rafaleon15** [comment]
Ok guys, I made it work, thanks to @carljmosca advices. I copied some versions from a working installation of a colleague. 
For me the keys were:
1. The kernel. I used CentOS Linux release 7.2.1511 (Core), had to downgrade to kernel 3.10.0-229.14.1.el7.x86_64
2. Ansible version. Had to downgrade to 2.2.0.0-1.el7 to by pass some 'htpasswd' error
3. My installation is dockerized, so containerized=true in the inventory. I was having exactly the same SDN problem if it was dockerized or not, so probably it will work also not dockerized with that kernel.
4. Nothing special with Docker version (2:1.12.6-16.el7.centos) or NetworkManager version (1:1.4.0-19.el7_3). Just got the latest I could.

**Comment by carljmosca** [comment]
Given that this seems to have some attention now and I don't think we can articulate a complete solution, I am reopening this issue.

**Comment by sdodson** [comment]
What version of openvswitch RPM is everyone using?

**Comment by carljmosca** [comment]
openvswitch-2.4.0-2.el7.x86_64

**Comment by sdodson** [comment]
That's the version we've shipped in OCP 3.0 through 3.4 and we've never seen problems with 7.2 or 7.3 kernels there.

3.10.0-229.14.1.el7.x86_64 is a 7.1.z kernel, I'm out of ideas and will have to let the networking team take this from here.

**Comment by carljmosca** [comment]
OK...in the meantime is there a particular release you can recommend?

**Comment by sdodson** [comment]
You can try the package from the Origin 1.5 repos, but I'm still not certain this is related to the OpenvSwitch version.

http://cbs.centos.org/repos/paas7-openshift-origin15-release/x86_64/os/Packages/openvswitch-2.6.1-3.git20161206.el7.x86_64.rpm

**Comment by carljmosca** [comment]
Thanks...will give it a try.

**Comment by sdodson** [comment]
You have checked to make sure that nothing else is bound to port 4789, correct?
`lsof -i UDP:4789`

**Comment by carljmosca** [comment]
Yes, but thank you for asking...always amazed how I miss the easy obvious stuff when knee deep in issues. :)

**Comment by carljmosca** [comment]
I am trying the openvswitch above but when I asked about releases, I was wondering if I should be using a branch besides master, such as release-x.y.  I have tried  more than one. :)

**Comment by sdodson** [comment]
For openshift-ansible master is tested against the current development release and the current latest GA, so 3.6 and 1.5. The release branches are updated less frequently and generally only with bugfixes so they should be more stable, the branch name corresponds to the origin release version they support.

**Comment by cjsrinivas** [comment]
Having the same issue as well (install fails, cannot bind to port 4789). Previously, I did get OpenShift 3.5 to work on a AWS RHEL 7.3 machine that was running the 3.10.0-514.10.2.el7.x86_64 kernel. However, now I am running a RHEL 7.3 VM with a 3.10.0-514.16.1.el7.x86_64 kernel, which is where the failed VMs landed after a 7.2 to a 7.3 upgrade.

**Comment by carljmosca** [comment]
I had to use kernel 3.10.0-229.14.1.el7.x86_64

**Comment by rafaleon15** [comment]
Hi, my last problem was that one of the routers could not start, it said it could not fit in any node.
Now it is working. I downgraded NetworkManager to version NetworkManager.x86_64 1:1.0.0-16.git20150121.b4ea599c.el7_1 just because my colleague installation was using that version, but I think that what made it work is that I set the master as schedulable.
I added the master to be also a node (a requirement for SDN to work), but I did not want it schedulable to keep it responsive. The router could not start on it, so I have made it schedulable and voila, not it works.

**Comment by sdodson** [comment]
@rafaleon15 Yes, if your masters are labeled such that the router would be deployed there you'll need to ensure that you add openshift_schedulable=true or mark them schedulable manually after the install. We've recently updated the documentation for this https://github.com/openshift/openshift-docs/pull/4317

**Comment by sdodson** [comment]
Disabling IPv6 breaking vxlan is being tracked as a kernel bug, unfortunately that bug is private right now, I've requested that it be made public as there's no sensitive data in the bug. If that happens I'll close this with a reference to that bug.

**Comment by sdodson** [comment]
Ok, bug is now public.

https://bugzilla.redhat.com/show_bug.cgi?id=1445054
There's also a KCS article for Red Hat Customers https://access.redhat.com/solutions/3039771
