### ISSUE TITLE
openshift-ansible upgrade playbooks uncertainties

### ISSUE THREAD

**Issue by samjaninf** [openshift/openshift-ansible#3794]
#### Description
I cannot for the life of me utilize the upgrade playbooks to upgrade openshift origin to 1.5. I am probably just doing it incorrectly but any help or advice would be appreciated.

##### Version
ansible 2.2.1.0
If you're operating from a **git clone**:
yes
* The output of `git describe`
openshift-ansible-3.6.10-1-18-g1579cfe

If you're running from playbooks installed via RPM or
RPM

* The output of `rpm -q atomic-openshift-utils openshift-ansible`
atomic-openshift-utils-3.4.59-2.git.2.76c5698.el7.noarch
openshift-ansible-3.4.59-2.git.2.76c5698.el7.noarch

##### Version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://[master host name here]:8443
openshift v1.4.1
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. ansible-playbook playbooks/byo/openshift-cluster/upgrades/v3_5/upgrade.yml

##### Expected Result
openshift origin cluster running at version 1.5

##### Current Result
TASK [fail] ********************************************************************
fatal: [[master host domain name]]: FAILED! => {
    "changed": false,
    "failed": true
}

MSG:

openshift_release is 1.5 which is not a valid release for a 1.4 upgrade

##### Additional Information
CentOS Linux release 7.3.1611 (Core)

**Comment by tbielawa** [comment]
@samjaninf I do not believe that Origin 3.5 has had a General Availability release yet.
