### ISSUE TITLE
calico network failed to "SetupNetwork"

### ISSUE THREAD

**Issue by zhwenh** [openshift/openshift-ansible#3805]
@djosborne 
calico network failed to "SetupNetwork"

origin v1.5.0-rc.0 Version + Calico + cni

this is my inventory

openshift_use_openshift_sdn=false
openshift_node_proxy_mode=iptables
openshift_use_calico=true
os_sdn_network_plugin_name=cni

kubectl get pods --namespace=kube-system
NAME READY STATUS RESTARTS AGE
calico-policy-controller-442588368-2k3hh 1/1 Running 0 1d

f8c226ee26b5 calico/node:v1.1.0 "start_runit" 2 days ago Up 2 days calico-node

./calicoctl get profile k8s_ns.default -o yaml

apiVersion: v1
kind: profile
metadata:
name: k8s_ns.default
tags:
k8s_ns.default
spec:
egress:
action: allow
destination: {}
source: {}
ingress:
action: allow
destination: {}
source: {}
"router-1-deploy_default “ pod is in ns default
Additional Information

Error syncing pod, skipping: failed to "SetupNetwork" for "router-3-deploy_default" with SetupNetworkError: "Failed to setup network for pod "router-3-deploy_default(799d976f-1502-11e7-b3c1-fa163e10ef43)" using network plugins "cni": failed to send CNI request: Post http://dummy/: dial unix /var/run/openshift-sdn/cni-server.sock: connect: no such file or directory; Skipping pod"	39 times in the last 0 seconds

**Comment by djosborne** [comment]
Hmm, seems suspect that it mentions `openshift-sdn/cni-server.sock`. Did you set `openshift_use_openshift_sdn=False`? What's your inventory.ini file look like?

**Comment by zhwenh** [comment]
this is my inventory

openshift_use_openshift_sdn=false
openshift_node_proxy_mode=iptables
openshift_use_calico=true
os_sdn_network_plugin_name=cni

**Comment by zhwenh** [comment]
@djosborne
this is my inventory

openshift_use_openshift_sdn=false
openshift_node_proxy_mode=iptables
openshift_use_calico=true
os_sdn_network_plugin_name=cni

kubectl get pods --namespace=kube-system
NAME READY STATUS RESTARTS AGE
calico-policy-controller-442588368-2k3hh 1/1 Running 0 1d

f8c226ee26b5 calico/node:v1.1.0 "start_runit" 2 days ago Up 2 days calico-node

"router-1-deploy_default “ pod is in ns default
Additional Information

Error syncing pod, skipping: failed to "SetupNetwork" for "router-3-deploy_default" with SetupNetworkError: "Failed to setup network for pod "router-3-deploy_default(799d976f-1502-11e7-b3c1-fa163e10ef43)" using network plugins "cni": failed to send CNI request: Post http://dummy/: dial unix /var/run/openshift-sdn/cni-server.sock: connect: no such file or directory; Skipping pod"	39 times in the last 0 seconds

**Comment by djosborne** [comment]
@zhwenh  It sounds like the kubelet is not using Calico as its CNI plugin. Can you answer some of the following questions for me?

- Can you check that `/opt/cni/bin/calico` and `/opt/cni/bin/calico-ipam` exist?
- Can you check that  `/etc/cni/net.d/10-calico.conf` exists?
- Are there any other configuration files in `/etc/cni/net.d`?
- Those directories are the default CNI directories. Is it possible the directory has been overriden? Is it possible the flags `--cni-conf-dir` or `--cni-bin-dir` were changed for the underlying kubelet process?
- Can you check that OpenShift is configured to use the above directories for its network plugins? I think this information can be found in the openshift-origin logs, or in the kubeconfig file? 
- Which version of OpenShift is running?
- Were there any errors when running the ansible install or did it install cleanly?

**Comment by zhwenh** [comment]
HI @djosborne , the Openshift origin v1.5.0-rc.0 Version + Calico 2.1+ cni 
I  add "-v /opt/cni/bin:/opt/cni/bin -v /etc/cni/net.d:/etc/cni/net.d"   to /etc/systemd/system/docker.service.wants/origin-node.service . and calico-node pod is Running !

**Comment by sdodson** [comment]
@zhwenh nice find, we can fix this.
