### ISSUE TITLE
Preflight check for  inventory file

### ISSUE THREAD

**Issue by bahho** [openshift/openshift-ansible#3815]
#### Description

Ther should be pre-flight check for the syntax of the inventory file. 

##### Steps To Reproduce
1. Produce a syntax error in the inventory file
2. Run one of the installation playbooks

##### Expected Results
A warning that there is a syntax error in the inventory file and the installation is halted.

##### Observed Results
Installation starts goes until the erroneous part comes up. In my case I had forgotten one quotation mark for one of the node parameters, which was to be given as a list. 
Installation aborted only when docker tried to spin up the atomic-openshift-node container. It would be great to have a pre-flight check so that you don't have to find out the error 30 minutes after the installation started. 

##### Additional Information

I had the kubelet arguments in the inventory like this
```
openshift_node_kubelet_args={'kube-reserved': ['cpu=500m,memory=1G'], 'system-reserved':['cpu=500m,memory=1G'], 'maximum-dead-containers':['30] }
```
with one ' missing.

**Comment by bahho** [comment]
Not only syntax but also other checks would be extremely useful. 
For instance, when you would like to install a HA cluster and forget to mention the cluster method, it takes a while until the user figures out that his/her config was not correct.

**Comment by sdodson** [comment]
Agreed, any suggestions for how best to validate everything?

**Comment by sosiouxme** [comment]
We created a [card for doing this on our private board](https://trello.com/c/jAW7IXcR/106-pre-flight-check-for-inventory-file). I think we could put something in the `openshift_sanitize_inventory` role to do more sanity checking on the inventory. For instance, check that fields which are supposed to be JSON actually parse, perhaps even their structure matches if known. Check that certain combinations of parameters make sense (e.g. if you have specified X=foo you need to also specify Y). The exact implementation needs refinement but the exact tests can probably be created incrementally.

**Comment by bostrt** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1592421
