### ISSUE TITLE
Install yum deps as part of the Ansible playbooks

### ISSUE THREAD

**Issue by mykaul** [openshift/openshift-ansible#3829]
Why is there a need (mentioned @ https://docs.openshift.com/container-platform/latest/install_config/install/host_preparation.html#installing-base-packages ) to install:
yum install wget git net-tools bind-utils iptables-services bridge-utils bash-completion

Can't it be done in a playbook? See https://github.com/machacekondra/ovirt-ansible-roles/blob/master/playbooks/openshift.yml for example

**Comment by rhcarvalho** [comment]
@sdodson I've also always wondered about this. Is there a technical limitation preventing us from doing it?

**Comment by sdodson** [comment]
@rhcarvalho no, we need to put together a pre-requisites playbook for many reasons, we've just never gotten to it.

**Comment by rhcarvalho** [comment]
@sosiouxme FYI

**Comment by sosiouxme** [comment]
For prerequisites on the host running Ansible, it seems like they could just be included in the requires for atomic-openshift-utils.

I wonder if this list comes from the use case where people are installing ansible separately and running from a git clone of openshift-ansible.
