### ISSUE TITLE
Need to add ROUTER_METRICS_TYPE during router upgrades

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#3845]
@jhadvig has discovered that after upgrading to latest origin e2e tests fail because the router does not export metrics when upgraded from 3.5 to current origin/master. This was a change that was introduced in https://github.com/openshift/origin/pull/13337 and we need to make sure to apply that change during upgrades.

e2e test failure post upgrade https://ci.openshift.redhat.com/jenkins/view/All/job/test_branch_origin_extended_conformance_install_update/154/consoleFull#-81124364856cbb9a5e4b02b88ae8c2f77

Router upgrade happens here but all we do is patch the image version.

https://github.com/openshift/openshift-ansible/blob/master/playbooks/common/openshift-cluster/upgrades/post_control_plane.yml#L12-L42

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-docs/pull/3779 potential source for other additional changes during upgrade

**Comment by stevekuznetsov** [comment]
Seems like @smarterclayton should have made this change as part of his patchset

**Comment by smarterclayton** [comment]
Um... why is router upgrade not rerunning oadm router and merging?

**Comment by smarterclayton** [comment]
So if the upgrader is just setting the latest image, there are quite a few things that are missing.  In which case we probably need to start doing more to actually upgrade users, but it's not inconsistent with our current behavior.  My understanding is that online was actually doing something much more, and I assumed that as part of the merge of the ops code we pulled that in.

**Comment by sdodson** [comment]
I don't believe they were doing anything beyond what we're doing now, @mwoodson can you verify?

@smarterclayton can you show us how you'd re-generate and merge?

**Comment by smarterclayton** [comment]
Thomas had described to me before, but that may have been manual.  Even
though we try really hard to be backwards compat, router and registry may
deserve to be periodically upgraded (but, we'd have to be sure users wanted
that, a la reconcile).
