### ISSUE TITLE
Several YAML files do not adhere to the style guide

### ISSUE THREAD

**Issue by codificat** [openshift/openshift-ansible#3847]
There are several Ansible YAML files in the repo that do not follow the guidance from the [style guide](../blob/master/docs/style_guide.adoc) and use a `.yaml` extension instead of `.yml`:

```
$ find . -name \*.yml | grep -vF ./. | wc -l
445
$ find . -name \*.yaml | grep -vF ./. | wc -l
157
```

Some YAML files in the repo could be non-Ansible and have a *legitimate* `.yaml` extension (e.g. OpenShift resource definitions typically use `.yaml`, like the ones in `roles/openshift_{examples,hosted_templates}/files`), but still there are various files that would have to be renamed to adhere to the style guide.

Edit: note that some of these files are already referenced by name externally. At least the example certificate expiration check playbooks are referenced in the [OpenShift documentation](https://docs.openshift.org/latest/install_config/redeploying_certificates.html#install-config-cert-expiry-running-playbooks) and [knowledge base](https://access.redhat.com/node/2868251).

**Comment by sdodson** [comment]
👍 I think we should take this on as a change to be completed for 3.6 and we should make sure all docs.openshift.com content is updated at the same time. We would not merge these changes back into 3.5.
