### ISSUE TITLE
Are there any examples of deploying Openshift-Ansible with Nuage Networks?

### ISSUE THREAD

**Issue by akamalov** [openshift/openshift-ansible#3854]
This is a question, not an issue or bug report.

Are there any examples of deploying Openshift-Ansible with Nuage Networks? 

We have an existing Nuage Networks ecosystem. I'd like to deploy using OpenShift-Ansible and integrate it with an existing Nuage ecosystem, so when pods/containers deploy, they'd deploy on Nuage SDN. Is it possible do it ?

Thanks,

Alex

**Comment by sdodson** [comment]
@vishpat can you help?

**Comment by vishpat** [comment]
@sdodson @akamalov I have forwarded your request to our support team. They should be able to answer this.

**Comment by akamalov** [comment]
@vishpat , no response from support team yet?
