### ISSUE TITLE
The Included Cert Expiry Playbooks should allow for ENV var overrides

### ISSUE THREAD

**Issue by tbielawa** [openshift/openshift-ansible#3856]
This idea was spawned from a discussion in https://github.com/openshift/openshift-ansible/pull/3822

[tbielawa](https://github.com/openshift/openshift-ansible/pull/3822#discussion_r109742183):

> This customization hook is great. I comment about it though because it diverges from the roles default warning window.
> The role parameters document openshift_certificate_expiry_warning_days as having a default value of 30. Would you
> consider changing the defaults from 45 to match the 30 for the role? I'm open to hearing why you might not want to as well.

[codificat](https://github.com/openshift/openshift-ansible/pull/3822#discussion_r109881318):

> Even in less extreme cases, I believe cluster admins prefer to have a
> fairly advanced warning in order to have time to plan cert redeployment.
> In fact I was wondering if the role's default should be increased, with
> this example's value set even higher :) What do you think?
> 
> Slightly related to this, I think we could improve the role by allowing
> env var overrides on all defaults - this would allow runtime
> customization without the need to touch playbooks, which would be very
> welcome in the container use case... but that's beyond scope of this PR,
> so if you're ok with that I'll create a separate issue/PR.

**Comment by DanyC97** [comment]
My 0.002$ : in a prod env, 30 days notice might be a short window, ideally will be nice if the warning had say 3 levels or something where will catch 3 data points: 90/60/30 days (light, medium, high warning type of style).

**Comment by tbielawa** [comment]
I like that idea, @DanyC97. I will work on including that too in a future update.
