### ISSUE TITLE
OpenShift Master+Node doesn't install etcd

### ISSUE THREAD

**Issue by automatikdonn** [openshift/openshift-ansible#386]
Not sure if I am doing something wrong, or this is intended. 
Running the install with a single host, master+node install runs without issue. 
Cannot access the OpenShift Console, and the etcd service in not installed or running.

**Comment by detiber** [comment]
@automatikdonn if there are no etcd hosts defined in the inventory, then openshift will use the embedded etcd (external etcd hosts are required for a multi-master ha service, but that is a different discussion).

There should be an error in the master logs to indicate why the console is not available: `journalctl -u openshift-master -l`

Any further information you can provide regarding what your inventory file looks like as well as the output of the master logs would help in further troubleshooting.

**Comment by automatikdonn** [comment]
Issue was resolved some time ago. Please mark as closed
