### ISSUE TITLE
install openshift v1.2.1

### ISSUE THREAD

**Issue by akdj** [openshift/openshift-ansible#3869]
Hi, 
I want to install the version 1.2.1 of openshift. 

I specified the version in the host file, and I used the openshift-ansible-3.2.54-1.tar.gz package to install.
But : 
fatal: [178.33.25.175]: FAILED! => {"changed": false, "failed": true, "msg": "Detected OpenShift version 1.4.1 does not match requested openshift_release 1.2.1. You may need to adjust your yum repositories, inventory, or run the appropriate OpenShift upgrade playbook."}

I don't know if I did the good steps...

**Comment by akdj** [comment]
my host file : 


# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
#Set variales commons for all OSEv3 hosts
[OSEv3:vars]
# containerized=true
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root
ansible_ssh_pass=xxxxxxx
osm_default_subdomain=xxxxx.xxxxxxx.xxxx
# If ansible_ssh_user is not root, ansible_sudo must be set to true
# ansible_sudo=true
debug_level=2
deployment_type=origin
openshift_release=v1.2.1
 oo_release=v1.2.0
 docker_version="1.10.3"
 docker_upgrade=False
# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
# host group for masters
[masters]
x.x.x.x
# host group for nodes, includes region info[nodes]
[nodes]
x.x.x.x openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true
x.x.x.x openshift_node_labels="{'region': 'primary', 'zone': 'default'}"

**Comment by sosiouxme** [comment]
Unfortunately the installer does not adjust the yum config at all according to the `openshift_release` you indicate. Since Origin puts all current versions of the RPMs in one repository, yum won't install anything but the latest unless specifically directed to, or if newer versions are excluded.

The easiest path is probably to configure the excludes in `/etc/yum.conf` yourself, like so:

    exclude= origin*1.3* origin*1.4*

**Comment by akdj** [comment]
I found out that i have in my machine the version 1.4.1 of origin : with yum info origin,   but I can't remove it with yum remove origin

**Comment by akdj** [comment]
done
