### ISSUE TITLE
re-run byo playbook fails on task: Create registry certificates

### ISSUE THREAD

**Issue by ObviusOwl** [openshift/openshift-ansible#3870]
#### Description
Since I busted the metrics deployment I decided to re-run the playbook, which fails on the task *Create registry certificates* (see below).

With grep I found the file: `openshift-ansible/roles/lib_openshift/library/oc_adm_ca_server_cert.py` Where I added a `.decode()` method call to x509output (line 1507), which fixed it for me.

The problem is probably a incorrect use of `subprocess.Popen`. By default the std streams are byte encoded, thus we need to decode them before matching the regexp. 

##### Version

```
ansible 2.2.0.0
Python 3.5.3
Fedora 25
openshift-ansible git-commit b930b55451b
```

##### Steps To Reproduce
run `ansible-playbook playbooks/byo/config.yml` twice

##### Observed Results
The playbook fails with the message

```
TASK [openshift_hosted : Create registry certificates] *************************
fatal: [paas.example.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to paas.example.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_952_ce4c/ansible_module_oc_adm_ca_server_cert.py\", line 1607, in <module>\r\n    main()\r\n  File \"/tmp/ansible_952_ce4c/ansible_module_oc_adm_ca_server_cert.py\", line 1599, in main\r\n    results = CAServerCert.run_ansible(module.params, module.check_mode)\r\n  File \"/tmp/ansible_952_ce4c/ansible_module_oc_adm_ca_server_cert.py\", line 1547, in run_ansible\r\n    if not server_cert.exists() or params['force']:\r\n  File \"/tmp/ansible_952_ce4c/ansible_module_oc_adm_ca_server_cert.py\", line 1507, in exists\r\n    match = regex.search(x509output)  # E501\r\nTypeError: cannot use a string pattern on a bytes-like object\r\n", "msg": "MODULE FAILURE"}
```

##### Additional Information

The Python manual says:
> communicate() returns a tuple (stdout_data, stderr_data). The data will be strings if streams were opened in text mode; otherwise, bytes.

and 

> If text mode is not used, stdin, stdout and stderr will be opened as binary streams.

Ref: https://docs.python.org/3.6/library/subprocess.html?highlight=subprocess#frequently-used-arguments

**Comment by kwoodson** [comment]
@ObviusOwl, Thanks for reporting this.  I'll test a few scenarios with the supported versions of python and hopefully have a PR soon.

**Comment by kwoodson** [comment]
https://github.com/openshift/openshift-ansible/pull/3894

**Comment by admiyo** [comment]
Seeing the same problem using python3 on Fedora 25.  Was able to edit the decode into the file as above, but it did not change the outcome:

fatal: [munchlax]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "backup": true, 
            "cert": "/etc/origin/master/registry.crt", 
            "debug": false, 
            "expire_days": 730, 
            "force": false, 
            "hostnames": [
                "172.30.76.243", 
                "docker-registry.default.svc", 
                "docker-registry.default.svc.cluster.local", 
                "docker-registry-default.router.default.svc.cluster.local"
            ], 
            "key": "/etc/origin/master/registry.key", 
            "kubeconfig": "/etc/origin/master/admin.kubeconfig", 
            "signer_cert": "/etc/origin/master/ca.crt", 
            "signer_key": "/etc/origin/master/ca.key", 
            "signer_serial": "/etc/origin/master/ca.serial.txt", 
            "state": "present"
        }
    }
}

MSG:

{u'cmd': u'/bin/oc adm ca create-server-cert --cert=/etc/origin/master/registry.crt --expire-days=730 --hostnames=172.30.76.243,docker-registry.default.svc,docker-registry.default.svc.cluster.local,docker-registry-default.router.default.svc.cluster.local --key=/etc/origin/master/registry.key --overwrite=True --signer-cert=/etc/origin/master/ca.crt --signer-key=/etc/origin/master/ca.key --signer-serial=/etc/origin/master/ca.serial.txt', u'returncode': 1, u'results': {}, u'stderr': u'Error: unknown flag: --expire-days\n\n\nUsage:\n  oc adm ca create-server-cert [options]\n\nOptions:\n      --cert=\'\': The certificate file. Choose a name that indicates what the service is.\n      --hostnames=[]: Every hostname or IP you want server certs to be valid for. Comma delimited list\n      --key=\'\': The key file. Choose a name that indicates what the service is.\n      --overwrite=true: Overwrite existing cert files if found.  If false, any existing file will be left as-is.\n      --signer-cert=\'openshift.local.config/master/ca.crt\': The certificate file.\n      --signer-key=\'openshift.local.config/master/ca.key\': The key file.\n      --signer-serial=\'openshift.local.config/master/ca.serial.txt\': The serial file that keeps track of how many certs have been signed.\n\nUse "oc adm options" for a list of global command-line options (applies to all commands).\n\n', u'stdout': u''}

**Comment by admiyo** [comment]
Had to remove the --expire-days flag.

**Comment by admiyo** [comment]
This was on Fedora25

**Comment by abutcher** [comment]
@admiyo that'd be a different issue that what was originally reported here but what version of origin are you targeting?

**Comment by djdevin** [comment]
I'm on 1.5 (origin and o-ansible) but I'm still getting this. I checked and that .decode() is already there.

Thoughts?

**Comment by ObviusOwl** [comment]
@djdevin are you sure you checked out the latest `release-1.5` branch? I just tried to run the playbook on the 1.5 branch and had to manually add the `decode()`s.
@kwoodson is this a regression or hasn't #3894 been back-ported to the 1.5 branch (yet)?

**Comment by abutcher** [comment]
Created backport for 1.5 #4241

**Comment by djdevin** [comment]
@ObviusOwl I thought I did, but it must be me. Thanks for looking. It works fine now.
