### ISSUE TITLE
RFE: Proxy settings specific to docker

### ISSUE THREAD

**Issue by fgiloux** [openshift/openshift-ansible#3874]
### Proxy settings specific to docker

It would be advantageous to have a set of parameters for proxy settings specific to docker.

#### Description

Today there is a single set of parameters to configure proxy settings during the installation:
#openshift_http_proxy=http://USER:PASSWORD@IPADDR:PORT
#openshift_https_proxy=https://USER:PASSWORD@IPADDR:PORT
#openshift_no_proxy='.hosts.example.com,some-host.com'

The docker daemons get also configured with these settings:
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_docker_facts/tasks/main.yml#L32-L34

I have been at 3 customers where they actually only need a proxy to have docker accessing the internet to pull images from registry.access.redhat.com

Having a proxy configured for other components make it cumbersome, especially as these settings are injected in builds, hence images, hence pods if they are not overwritten by other settings.

It would be good to be able to set proxy settings specific to docker during the installation. They could also default to the global settings if they are not set and if this behaviour is deemed as desirable.

##### Version
```
* ansible 2.2.1.0
* atomic-openshift-utils-3.4.67-1.git.0.14a0b4d.el7.noarch
```

##### Steps To Reproduce
1. Install OpenShift with the following settings in the inventory
openshift_http_proxy=http://USER:PASSWORD@IPADDR:PORT
openshift_https_proxy=https://USER:PASSWORD@IPADDR:PORT
openshift_no_proxy='.hosts.example.com,some-host.com'
 
2. Check the docker configuration: /etc/sysconfig/docker

##### Expected Results
I would like to have another set of proxy settings available in the inventory:
docker_http_proxy=http://USER:PASSWORD@IPADDR:PORT
docker_https_proxy=https://USER:PASSWORD@IPADDR:PORT
docker_no_proxy='.hosts.example.com,some-host.com'

**Comment by fgiloux** [comment]
A workaround for my customers may be to set:
openshift_builddefaults_http_proxy=""
openshift_builddefaults_https_proxy=""
openshift_builddefaults_no_proxy=""
openshift_builddefaults_git_http_proxy=""
openshift_builddefaults_git_https_proxy=""

but the proxy settings get also injected for the master and node services and the approach may not be intuitive either when the proxy is only required for docker.

**Comment by jeffcpullen** [comment]
This has been a nightmare to understand, and now work around. Would love to see a docker proxy configuration broken off.
