### ISSUE TITLE
Invalid Release 3.4.67-1

### ISSUE THREAD

**Issue by billyfoss** [openshift/openshift-ansible#3901]
#### Description

When pulling an older tag openshift-ansible03.4.67-1, we find code for 3.6.17. 

##### Version

https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.4.67-1/openshift-ansible.spec
contains change history for 3.6.17.

**Comment by rhcarvalho** [comment]
@sdodson FYI

**Comment by sdodson** [comment]
I'm having a hard time figuring out what's happened there. The more recent tags on that branch all look fine.

**Comment by sdodson** [comment]
We've found that for some reason a branch was created with the same name as the tag. I've just deleted that branch and now the reference above is correct again.
