### ISSUE TITLE
openshift_metrics fails when htpasswd is not found.

### ISSUE THREAD

**Issue by mwoodson** [openshift/openshift-ansible#3921]
### <HTPASSWD_AUTH>

We are aware of the current issues related to htpasswd_auth failures
Please downgrade to ansible 2.2.0.0 until a fix is released.
You can track the status of the bug fix in this issue:
https://github.com/openshift/openshift-ansible/issues/3111
Please erase this <HTPASSWD_AUTH> section if it does not apply to you.

Thanks - 2017-01-31

#### Description

openshift_metrics requires htpasswd and fails with a message.  I believe that openshift_metrics should install the dependency (httpd-tools) if it can't find it, not fail.

I just dug deeper, the httpd-tools needs to be installed from the host that is running the role/playbook.  I think it would be better to have htpasswd called from the node installing and configuring openshift_metrics.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
openshift-ansible-3.5

```

##### Steps To Reproduce
1. run the openshift_metrics roles without htpasswd on the host you are running from.

##### Expected Results
```
Install htpasswd if it's not there
```

##### Observed Results
Describe what is actually happening.

```
it fails hard now
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```

```

**Comment by ewolinetz** [comment]
per our IRC discussion, the issue seems to be that `openshift_metrics` is expecting `htpasswd` to be available on the control host. There does not appear to be a clear need to run `htpasswd` on the control, it should be possible to accomplish the same on the target.

**Comment by sdodson** [comment]
I think for now I'd press for the workaround of just intalling http-tools on the control host, if our RPM packages were installed rather than vendoring this would be the case.

**Comment by ewolinetz** [comment]
@sdodson but there isn't a need to generate the files locally as they are then immediately copied to the remote host. it seems like an extra, unnecessary step/hop
