### ISSUE TITLE
RepresenterError on deny_all with Ansible 2.2.1.0-2.el7.noarch,

### ISSUE THREAD

**Issue by dgoodwin** [openshift/openshift-ansible#3952]
#### Description

Similar to #3111 we encountered a RepresenterError in openshift-ansible code using Ansible 2.2.1.0-2.el7.noarch.

##### Version

```
ansible 2.2.1.0-2.el7.noarch
openshift-ansible vendored copy of 
openshift-ansible-3.5.52
```

##### Steps To Reproduce

Unfortunately not entirely sure, lost my reproducer as this was a shared system that had to be immediately downgraded.

##### Observed Results
The output I have saved:

```
TASK [openshift_master : Create session secrets file] **************************
ok: [52.55.135.148]
ok: [52.90.15.204]
ok: [52.207.231.248]

TASK [openshift_master : set_fact] *********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RepresenterError: cannot represent an object: deny_all
fatal: [52.90.15.204]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RepresenterError: cannot represent an object: deny_all
fatal: [52.55.135.148]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RepresenterError: cannot represent an object: deny_all
fatal: [52.207.231.248]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

NO MORE HOSTS LEFT *************************************************************
```

I was unable to find a stack trace in my logs unfortunately. 

I'm also not sure where the deny_all is coming from, the resulting master-config did not contain deny_all after downgrading and deploying the cluster.

**Comment by sdodson** [comment]
@abutcher PTAL

**Comment by dgoodwin** [comment]
Mistake in my report, at this point it would have been running vendored version of openshift-ansible-3.4.40, not 3.5.

**Comment by dgoodwin** [comment]
Confirmed with @abutcher this is caused because that version of 3.4 did not have the yaml fix. Re-vendoring newer 3.4 builds should fix if they upgrade ansible again. Thanks for looking into it guys.
