### ISSUE TITLE
Playbook fails because g_etcd_hosts is not set.

### ISSUE THREAD

**Issue by ericlake** [openshift/openshift-ansible#3956]
#### Description

Running the origin_metrics or openshift_logging playbooks fails with the error:

`fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "This playbook requires g_etcd_hosts to be set"}`

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE

ansible --version
ansible 2.3.0.0 (stable-2.3 27073dd9bd) last updated 2017/04/19 15:22:00 (GMT +000)
  config file = /home/eric6133/.ansible.cfg
  configured module search path = [u'/home/elake/ansible/modules/']
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

git describe
openshift-ansible-3.6.29-1
```

##### Steps To Reproduce
1. Ensure that ansible and git are installed
2. Clone the https://github.com/openshift/openshift-ansible repo
3. Have your ansible inventory file populated
4. Run the playbook as shown below.

##### Expected Results
The expectation is that the playbook will succeed and set up hawkular metrics.

```
ansible-playbook -i ansible-inventory/prod/ord1 openshift-ansible/playbooks/common/openshift-cluster/openshift_metrics.yml -e openshift_metrics_install_metrics=True -e openshift_metrics_hawkular_hostname=metrics.rsi.rackspace.net -e openshift_metrics_cassandra_storage_type=pv -e openshift_metrics_image_version=v1.4 -e openshift_metrics_hawkular_ca=thawte-bundle.crt -e openshift_metrics_hawkular_cert=rsi.rackspace.net.crt -e openshift_metrics_hawkular_key=rsi.rackspace.net.key -bkK
SSH password: 
SUDO password[defaults to SSH password]: 

PLAY [Populate config host groups] ***********************************************************************************************************************************************************

TASK [fail] **********************************************************************************************************************************************************************************
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ g_etcd_hosts is not defined }}

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "This playbook requires g_etcd_hosts to be set"}
	to retry, use: --limit @code/openshift-ansible/playbooks/common/openshift-cluster/openshift_metrics.retry

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1 
```

##### Observed Results
Describe what is actually happening.

```
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ g_etcd_hosts is not defined }}

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "This playbook requires g_etcd_hosts to be set"}
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* OS = CentOS Linux release 7.3.1611 (Core)

It seems that including the cluster_hosts.yml play in each of these will move past the issue described above.

```
diff --git a/playbooks/common/openshift-cluster/evaluate_groups.yml b/playbooks/common/openshift-cluster/evaluate_groups.yml
index 6aac70f..5f856cf 100644
--- a/playbooks/common/openshift-cluster/evaluate_groups.yml
+++ b/playbooks/common/openshift-cluster/evaluate_groups.yml
@@ -5,6 +5,7 @@
   become: no
   gather_facts: no
   tasks:
+  - include_vars: ../../byo/openshift-cluster/cluster_hosts.yml
   - fail:
       msg: This playbook requires g_etcd_hosts to be set
     when: "{{ g_etcd_hosts is not defined }}"
```

**Comment by abutcher** [comment]
Hey @ericlake,

The entry point for the metrics playbook is `playbooks/byo/openshift-cluster/openshift-metrics.yml` rather than the `../common/..` playbook. The playbook within `byo` sets up groups such as `g_etcd_hosts` which the `common` playbook does not.

```
ansible-playbook -i ansible-inventory/prod/ord1 playbooks/byo/openshift-cluster/openshift-metrics.yml ...
```

**Comment by ericlake** [comment]
@abutcher,

OK cool. I was going off of the https://docs.openshift.org/latest/install_config/cluster_metrics.html doc for that path. Now I am getting:

```
TASK [openshift_metrics : copy local generated passwords to target] **************************************************************************************************************************
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: not {{ openshift_metrics_heapster_standalone | bool }}

failed: [master-001.ord1.prod.rsi.rackspace.net] (item=hawkular-metrics.pwd) => {"failed": true, "item": "hawkular-metrics.pwd", "msg": "Unable to find '/tmp/tmp.4Unv7CNtdk/hawkular-metrics.pwd' in expected paths."}
failed: [master-001.ord1.prod.rsi.rackspace.net] (item=hawkular-metrics.htpasswd) => {"failed": true, "item": "hawkular-metrics.htpasswd", "msg": "Unable to find '/tmp/tmp.4Unv7CNtdk/hawkular-metrics.htpasswd' in expected paths."}
```

It seems that it is creating the files as root and so my local user can not read them for the copy operation.

```
[ eric@toolbox-001.ord1.prod code ]$ sudo ls -ld /tmp/tmp.4Unv7CNtdk
drwx------. 2 root root 67 Apr 19 17:38 /tmp/tmp.4Unv7CNtdk

[ eric@toolbox-001.ord1.prod code ]$ sudo ls -ls -l /tmp/tmp.4Unv7CNtdk
total 8
4 -rw-r--r--. 1 root root 47 Apr 19 17:38 hawkular-metrics.htpasswd
4 -rw-r--r--. 1 root root 15 Apr 19 17:38 hawkular-metrics.pwd
```

**Comment by abutcher** [comment]
@ericlake Thanks for pointing the doc out, I'll look into getting that updated. I'll need to investigate the ownership issue a bit.

**Comment by sdodson** [comment]
@abutcher BTW, playbooks/byo/openshift-cluster/openshift-metrics.yml is brand new on master and release-1.5 

https://github.com/openshift/openshift-ansible/pull/3953 and #3948

**Comment by ericlake** [comment]
Is there a different set of instructions for getting metrics set up for 1.4? Right now we are running into:
```
2017-04-19 18:01:30 Starting Hawkular Metrics
unable to write 'random state'
unable to write 'random state'
The --truststore_authorities value is not specified. Aborting
```

**Comment by abutcher** [comment]
@jcantrill ^

**Comment by abutcher** [comment]
I wouldn't expect running a playbook from `playbooks/common/` as an entry point to work but the problem may be that the common playbook does work on its own but not from the master branch of this repo -- maybe an earlier tag.

**Comment by ericlake** [comment]
Looking in both release-1.5 and release-1.4 the `openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.yml` does not exist.

**Comment by ewolinetz** [comment]
@ericlake the `byo/openshift-cluster/openshift-metrics.yml` playbook was just merged into release-1.5 with https://github.com/openshift/openshift-ansible/pull/3953

**Comment by ericlake** [comment]
Aah .. I see it now. Had to git pull in the branch.

**Comment by ericlake** [comment]
Running out of the updated release-1.5 branch I now get this error:

```
TASK [openshift_metrics : fetch] *************************************************************************************************************************************************************
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: not {{ openshift_metrics_heapster_standalone | bool }}

fatal: [master-001.ord1.prod.rsi.rackspace.net]: FAILED! => {"failed": true, "msg": "Failed to fetch the file: [Errno 13] Permission denied: '/tmp/tmp.53FteGPZWh/hawkular-metrics.pkcs12'"}
	to retry, use: --limit @/home/eric6133/code/openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.retry
```

**Comment by ewolinetz** [comment]
@ericlake can you rerun your playbook with `-vv` to see a line number?

**Comment by ericlake** [comment]
@ewolinetz,

```
TASK [openshift_metrics : fetch] *************************************************************************************************************************************************************
task path: /home/eric6133/code/openshift-ansible/roles/openshift_metrics/tasks/import_jks_certs.yaml:32
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: not {{ openshift_metrics_heapster_standalone | bool }}

fatal: [master-001.ord1.prod.rsi.rackspace.net]: FAILED! => {"failed": true, "msg": "Failed to fetch the file: [Errno 13] Permission denied: '/tmp/tmp.DhiJEpXjW7/hawkular-metrics.pkcs12'"}
	to retry, use: --limit @/home/eric6133/code/openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.retry
```

**Comment by ewolinetz** [comment]
Thanks @ericlake, I'm not sure why you don't have that pkcs12 file in your temp directory, it should be created at an earlier point in the playbook. Can you paste the full output of your play (with `-vv`) in a gist/pastebin and share it?

**Comment by ericlake** [comment]
https://gist.github.com/ericlake/7e46cd34e381a3f4467fb4eed8660a77

**Comment by ewolinetz** [comment]
@ericlake what does your inventory file look like? It looks like its just failing to fetch from the remote temp dir to the local temp dir..

**Comment by ericlake** [comment]
https://gist.github.com/ericlake/41e36d1eb2429e89fee7d06ecf778e01

This inventory file worked for the install originally so it seemed pretty good.

**Comment by ewolinetz** [comment]
I'm not sure if it'll work with your configuration, but can you try to add this to your `OSEv3:vars` section?
`ansible_ssh_user=root`

**Comment by ericlake** [comment]
Adding `ansible_ssh_user=root` did not help. I know that the instructions are deprecated but I am going to try installing per https://github.com/openshift/origin-metrics/blob/master/docs/deployer_installation.adoc.

**Comment by origliante** [comment]
I have the same problem on OSE 3.5, also with openshift_logging.yml

**Comment by jcantrill** [comment]
@origliante use the `openshift-ansible/playbooks/byo/openshift-cluster/openshift-logging.yaml' playbook

**Comment by origliante** [comment]
@jcantrill thanks!

(just for reference, now I'm getting this https://github.com/openshift/openshift-ansible/issues/3810)
