### ISSUE TITLE
Inconsistent metrics documentation

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-ansible#3977]
#### Description

Metrics installation in the docs seem to state the use of variables like:

```
openshift_metrics_install_metrics
```

However example host files are suggesting:

```
openshift_hosted_metrics_deploy
```

**Comment by ewolinetz** [comment]
Which docs are you referring to specifically?

There is a page for installing metrics as part of the advanced installation [1] and for installing it afterwards [2].
Those are two different playbook entry points and to maintain backwards compatibility with parameter names, the advanced install still uses the pre 3.5 variable names.


[1] https://docs.openshift.org/latest/install_config/install/advanced_install.html#advanced-install-cluster-metrics
[2] https://docs.openshift.org/latest/install_config/cluster_metrics.html

**Comment by andrewklau** [comment]
Oh, ok thanks! It wasn't obvious they were two different playbooks.
