### ISSUE TITLE
openshift-origin yum repo still with 1.4.1 packages ?

### ISSUE THREAD

**Issue by thechile** [openshift/openshift-ansible#3980]
Hi

Does anyone have news about when [http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/](http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/) will be updated with 1.5.0 rpms ?

thank you.

**Comment by thechile** [comment]
[https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin/](https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin/) has the 1.5.0 rpm files already. But main in [openshift-ansible-centos-paas-sig.repo](https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_repos/files/origin/repos/openshift-ansible-centos-paas-sig.repo) uses the mirror repo which still only has older packages. 

The mirror repository seems to take a long time to update/sync... anyone know how this promotion from testing to prod/main happens ? 

thanks

**Comment by thechile** [comment]
.. there is also [https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin15/](https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin15/) but i can't see how this ties in with openshift-ansible, so i can use its packages during rpm install.

**Comment by sdodson** [comment]
@thechile Centos PaaS SIG is moving towards providing a repo per release, they have their meeting tomorrow and I'll try to check on the status of that.

You could use openshift_additional_repos variable to add http://cbs.centos.org/repos/paas7-openshift-origin15-testing/x86_64/os/Packages/ as a repo for the time being. See inventory/byo/hosts.origin.example for more details on that variable.

**Comment by thechile** [comment]
ok thank you. It's confusing that when i switch to use the 1.5 branch that the yum repo file points to `http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/` which only has the 1.4.1 packages. 

If i understood you, `http://mirror.centos.org/centos/7/paas/x86_64/` should be updated to also have the `openshift-origin15` repository and  `openshift-ansible-centos-paas-sig.repo` should be updated to use this ?

Maybe the repo file should be changed to a template so the target repo automatically reflects the branch version number.

**Comment by sdodson** [comment]
I believe that's the intention but it's taking a while for all the pieces to fall into place. I'll check on the status in tomorrow's meeting.

**Comment by thechile** [comment]
I'm seeing 1.5 package appear in the `openshift-origin` repo now so i'll try redeploy and check.
