### ISSUE TITLE
OpenShift-Ansible - Custom IPtable Ruleset (Master and Worker)

### ISSUE THREAD

**Issue by akamalov** [openshift/openshift-ansible#4014]
**Environment:**

```
NAME="Red Hat Enterprise Linux Atomic Host"
VERSION="7.3"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Atomic Host"
VARIANT_ID=atomic.host
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Atomic Host 7.3"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:atomic-host"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION=7.3
```

**OpenShift-Ansible Version:**

```3.6.11-1```

**Question:**

I tried to ask this question in Stackoverflow, however unfortunately didn't get any answers, so I am trying out my luck here.

- Can someone provide examples of creating custom iptable ruleset in OpenShift-Ansible:

       - For controller nodes
       - For worker nodes
 
- Am I to modify:

        - Master nodes:  openshift-ansible/roles/openshift-master/defaults/main.yml
        - Worker nodes:  openshift-ansible/roles/openshift_node/defaults/main.yml

- How about with multiple ports (using range of ports and using non-sequential ports)

**Comment by akamalov** [comment]
wow..no one ? No one has any idea?

**Comment by sdodson** [comment]
We have no support for this today. I think we should add a variable to define custom allow and custom deny rules and then apply those within the master and node roles. We'd probably want it to be different based on master or node.

Feel free to submit a PR and we'll review.

**Comment by akamalov** [comment]
Thanks @sdodson.  Closing the ticket due to unsupported configuration.
