### ISSUE TITLE
Error on TASK [docker : Install Docker]

### ISSUE THREAD

**Issue by gbaufake** [openshift/openshift-ansible#4016]
#### Description

Error on Task Docker ->  FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'docker' found available, installed or updated", "rc": 126, "results": ["No package matching 'docker' found available, installed or updated"]}

Docker is installed and running: 

docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-04-26 11:31:19 EDT; 9min ago
     Docs: https://docs.docker.com
 Main PID: 22442 (dockerd)
   Memory: 22.0M

```
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
git describe: openshift-ansible-3.5.62-1
```

##### Steps To Reproduce
1. Clone the Openshift-Ansible
2. Run the ansible-playbook -i invetory_file openshift-ansible/playbooks/byo/config.yml

##### Expected Results

```
fatal: [IP]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'docker' found available, installed or updated", "rc": 126, "results": ["No package matching 'docker' found available, installed or updated"]}
```

##### Additional Information

* RHEL 7.4

**Comment by sdodson** [comment]
So docker is pre-installed? `rpm -qa \*docker\*` please

**Comment by gbaufake** [comment]
@sdodson 

`rpm -qa \*docker\*` results on 

`docker-engine-17.04.0.ce-1.el7.centos.x86_64
atomic-openshift-docker-excluder-3.6.65-1.git.0.1c96bcd.el7.noarch
docker-engine-selinux-17.04.0.ce-1.el7.centos.noarch`

**Comment by sdodson** [comment]
Oh, we're not compatible with upstream's RPM packaging. Unfortunately you need to stick to packages provided in Fedora, RHEL, or Centos.

**Comment by zhxqgithub** [comment]
why openshift-ansible was not support docker-ce  when using playbook to install openshift ???however ,I can not upgrade openshift cluster from 3.6 to 3.7 successfully by openshft-ansible playbook after  I upgrade docker from 1.12 to 17.03 manually in openshift cluster 3.6.  The origin-node-3.7 rpm need docker>1.12, but it was too too old.

**Comment by sdodson** [comment]
> why openshift-ansible was not support docker-ce when using playbook to install openshift ???however ,I can not upgrade openshift cluster from 3.6 to 3.7 successfully by openshft-ansible playbook after I upgrade docker from 1.12 to 17.03 manually in openshift cluster 3.6. The origin-node-3.7 rpm need docker>1.12, but it was too too old.

where do you see that origin-node-3.7 requires docker > 1.12? It should require only >= 1.12 and 1.12 is in the centos extras repo.

**Comment by zhxqgithub** [comment]
sorry,my mistake ,it require only >=1.12. in origin-node-3.7*.rpm , but i don't want to use docker 1.12,I want to use docker-ce .

**Comment by sdodson** [comment]
@zhxqgithub sorry, we don't support that.

**Comment by lostiniceland** [comment]
@sdodson any plans for the long term to change that. I was hoping for Openshift 3.9 to be able to run docker-ce but it is obviously not the case.

**Comment by sdodson** [comment]
@lostiniceland no, not at this time.

**Comment by malagant** [comment]
I like to understand the reasons behind the statement: "we don't support that".
Is it too much of incompatibility issues? Or is it because no one wants to write playbooks for this at the moment? I really have the need for current docker versions for using new features for docker image creation and I don't want to build externally and then pushing to the openshift registry.

I clearly like to contribute if you want to enable docker-ce.
