### ISSUE TITLE
openshift-ansible fails to run on Fedora Atomic 25 nodes

### ISSUE THREAD

**Issue by davivcgarcia** [openshift/openshift-ansible#4022]
#### Description

The installer fails with error message 'module failure' on cluster composed by a single master and two nodes (byo). Setup based on Fedora Atomic 25.

#### Versions

ansible version from installer node:
```
$ ansible --version
ansible 2.3.0.0
  config file = /home/davivcgarcia/Projects/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```
openshift-ansible code version:
```
$ git branch
  master
* release-1.5
```
fedora atomic nodes version:
```
[root@f25-master ~]# atomic host status
State: idle
Deployments:
● fedora-atomic:fedora-atomic/25/x86_64/docker-host
             Version: 25.113 (2017-04-25 01:47:29)
              Commit: 3492546bc1ef6bca1bc7801ed6bb0414f90cc96668e067996dba3dee0d83e6c3
              OSName: fedora-atomic
```

#### Problem

Running the ansible-playbook with:
```
$ ansible-playbook -i myinventory playbooks/byo/config.yml -e 'ansible_python_interpreter=/usr/bin/python3' -vvv
```
This error occurs for all nodes listed in the inventory:
```
<f25-master.dvercill.local> (1, '', 'Traceback (most recent call last):\n  File "/tmp/ansible_487jx9mk/ansible_module_openshift_facts.py", line 2491, in <module>\n    main()\n  File "/tmp/ansible_487jx9mk/ansible_module_openshift_facts.py", line 2478, in main\n    protected_facts_to_overwrite)\n  File "/tmp/ansible_487jx9mk/ansible_module_openshift_facts.py", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_487jx9mk/ansible_module_openshift_facts.py", line 2491, in <module>
    main()
  File "/tmp/ansible_487jx9mk/ansible_module_openshift_facts.py", line 2478, in main
    protected_facts_to_overwrite)
  File "/tmp/ansible_487jx9mk/ansible_module_openshift_facts.py", line 1899, in __init__
    for (k, v) in self.system_facts.items():
RuntimeError: dictionary changed size during iteration

fatal: [f25-master.dvercill.local]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_487jx9mk/ansible_module_openshift_facts.py\", line 2491, in <module>\n    main()\n  File \"/tmp/ansible_487jx9mk/ansible_module_openshift_facts.py\", line 2478, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_487jx9mk/ansible_module_openshift_facts.py\", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n", 
    "module_stdout": "", 
    "rc": 1
}

MSG:

MODULE FAILURE
```

The inventory used was based on [(Installing an OpenShift Origin Cluster on Fedora 25 Atomic Host: Part 1 ):](http://www.projectatomic.io/blog/2016/12/part1-install-origin-on-f25-atomic-host/)
```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_user=root
ansible_become=false
deployment_type=origin
containerized=true
openshift_release=v1.5
openshift_router_selector='router=true'
openshift_registry_selector='registry=true'
openshift_master_default_subdomain=origin.dvercill.local

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
openshift_master_htpasswd_users={'admin': '$apr1$yWirWX8r$tmeB6DmKLCIkQ5OY2IcBy1', 'user': '$apr1$oH.3dE8a$UHmiqkSCa7NUssLagsDTZ/'}

[masters]
f25-master.dvercill.local

[etcd]
f25-master.dvercill.local

[nodes]
f25-master.dvercill.local   openshift_schedulable=false
f25-node-01.dvercill.local  openshift_node_labels="{'router':'true','registry':'false'}"
f25-node-02.dvercill.local  openshift_node_labels="{'router':'false','registry':'true'}"
```

**Comment by jberkus** [comment]
I can verify this.  The problem seems to be an incompatibility with ansible 2.3.0.0, although installation doesn't complete with 2.2.1.0 either.

**Comment by jberkus** [comment]
@abutcher I'll be camped out on #openshift-dev all day if you want me to trace or test fixes.

**Comment by jberkus** [comment]
@abutcher: currently I'm testing commit 90f6a70 with ansible 2.2.2.0, which is the last known good combination for Fedora-Atomic.  It's already gotten past the spots where we hit earlier bugs, but isn't complete yet.  Will report back.

**Comment by jberkus** [comment]
Also, one contributing factor: it's common for the ansible node to be running ansible-python2, but we need to use python3 on each Atomic node.  I'm wondering if having two different python versions involved is contributing to the breakage?  If you think so @abutcher, I can test with ansible-python3 on the ansible node.

**Comment by sdodson** [comment]
Does setting the following variable improve the situation?
`ansible_python_interpreter=/usr/bin/python3`

**Comment by jberkus** [comment]
That's already set.  It has to be for Fedora-atomic, which doesn't ship with python2.

**Comment by jberkus** [comment]
Confirmed that this combination works:

* Ansible 2.2.2.0
* O-A commit 90f6a70
* Origin 1.5.0
* Fedora Atomic 25 4/26.  

There may be other things which don't work perfectly out of the box (I'll test registry, S2I, etc. today), but it looks like the breakage is due to changes after that commit and/or due to Ansible 2.3.

**Comment by abutcher** [comment]
@jberkus cool, glad you've got a working set up for now -- I'll continue putting together fixes for this issue wrt ansible-2.3.

**Comment by jberkus** [comment]
@abutcher let me know when you have something to test, since I rebuild FAO clusters all the time.

**Comment by davivcgarcia** [comment]
@jberkus which commit/version of Fedora Atomic is working for you? I didn't find the changelog to determine what is the version you mentioned.

**Comment by jberkus** [comment]
Looks like 3.6.24-1, per commit link above.

https://github.com/openshift/openshift-ansible/commit/90f6a70bc7cdc128e0fb5809bb8ddeb37a0f8b89

**Comment by abutcher** [comment]
Opened referenced PR with some fixes that get things going for me. I also ran into https://github.com/ansible/ansible/issues/23731 while testing.

**Comment by davivcgarcia** [comment]
This bug not only applies. Closing it.
