### ISSUE TITLE
Metrics installation fails when docker volume dir is immutable

### ISSUE THREAD

**Issue by mwoodson** [openshift/openshift-ansible#4046]
#### Description

When deploying metrics on an Online cluster, we are unable to create the htpasswd.  The cod that is being executed is here:

https://github.com/openshift/openshift-ansible/blob/release-1.5/roles/openshift_metrics/tasks/generate_hawkular_certificates.yaml#L43-L48

The problem comes from Online clusters having an immutable /var/lib/docker/volumes.  This is because we do NOT want Online customers creating ephemeral volumes on the host.

The error we are seeing is this:

    "stderr": "/usr/bin/docker-current: Error response from daemon: create 189984d7bea8c4687b3a8edb8871aa7faf268cf1ac54711dff9296a0c16abc06: mkdir /var/lib/docker/volumes/189984d7bea8c4687b3a8edb8871aa7faf268cf1ac54711dff9296a0c16abc06: permission denied.\nSee '/usr/bin/docker-current run --help'.", 

##### Version

openshift 3.5
openshift-ansible-3.5.62

* Your ansible version per `ansible --version`

```
ansible 2.2
```

##### Steps To Reproduce
1. Make /var/lib/docker/volume immutable (this is done in Online)
2. Run the metrics playbooks

##### Observed Results

docker run is failing because the volume is immutable

**Comment by ewolinetz** [comment]
@mwoodson this should now be resolved with #4054 being merged

**Comment by ewolinetz** [comment]
The issue still exists, it is stemming from the image having a `Volume` definition within it. We should be able to switch to using the `htpasswd` module provided by Ansible

**Comment by ewolinetz** [comment]
re addressing in https://github.com/openshift/openshift-ansible/pull/4063
