### ISSUE TITLE
RFE: Support for modifying rootLogger in logging-elasticsearch config map on 3.5

### ISSUE THREAD

**Issue by dgoodwin** [openshift/openshift-ansible#4048]
#### Description

On 3.5 the logging-elasticsearch config map contains the following relevant properties:

```
data:
  logging.yml: |
    [snip]
    rootLogger: ${es.logger.level}, console, file
    [snip]
```

However this logging.yml property is a multi-line string with a lot more content, making it difficult to programatically edit the yaml.

In 3.6 version of the role this property appears configurable via a variable.

Requesting a backport of just this small change for release-1.5 branch. This would not need to be rebuilt, we can carry the patch in ops repo until next 3.5 build, should there be one. Just need a way to control this setting that will still be compatible come 3.6+.

##### Version

openshift-ansible-3.5.62

**Comment by ewolinetz** [comment]
Backport of this commit: https://github.com/openshift/openshift-ansible/commit/a222702ed4316f99eac497ac755c5349804c66d2

**Comment by ewolinetz** [comment]
Closing due to #4055 being merged in
