### ISSUE TITLE
Should we update our default NFS mount options?

### ISSUE THREAD

**Issue by tbielawa** [openshift/openshift-ansible#4056]
Per the [upstream documentation](https://docs.openshift.com/container-platform/3.5/install_config/persistent_storage/persistent_storage_nfs.html#nfs-export-settings) NFS exports should use the `rw,root_squash,no_wdelay` mount options.

Our [current defaults](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_storage_nfs_lvm/defaults/main.yml#L3) do not set the `no_wdelay` parameter.

```
       no_wdelay
              This option has no effect if async is also set.  The NFS  server  will  normally
              delay  committing  a  write request to disc slightly if it suspects that another
              related write request may be in progress or may arrive soon.  This allows multi‐
              ple  write  requests  to  be  committed to disc with the one operation which can
              improve performance.  If an NFS server received mainly small unrelated requests,
              this  behaviour  could actually reduce performance, so no_wdelay is available to
              turn it off.  The default can be explicitly requested with the wdelay option.
```

Is this something we should change to match upstream? Their comment on the `no_wdelay` option is:

> The no_wdelay option prevents the server from delaying writes, which greatly improves read-after-write consistency.

**Comment by sdodson** [comment]
Yes, we should. Though I think all of our solutions (cassandra, elasticsearch) are poorly suited for NFS use unfortunately. So the ultimate endstate should be to use CNS, but that's something for another day.
