### ISSUE TITLE
Upgrade playbook outputting jinja2 warnings

### ISSUE THREAD

**Issue by laurafitzgerald** [openshift/openshift-ansible#4069]
#### Description

Provide a brief description of your issue here. For example:

On a multi node upgrade from v3.4.0.40 using the automatic ansible installer, seeing the following error (example)

```
[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{
'admission_plugin_config' in openshift.master }}
```
in multiple locations (listed below).

Play 3/59 (Populate config host groups)
Play 10/59 (Set openshift_no_proxy_internal_hostnames)
Play 22/59 (Populate config host groups)
Play 44/59 (Set OpenShift master facts)
Play 45/59 (Upgrade master config and systemd units)
Play 57/59 (Drain and upgrade nodes)
Play 60/59 (Drain and upgrade nodes)
Play 61/59 (Drain and upgrade nodes)

##### Versions

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

```
atomic-openshift-utils-3.4.79-1.git.0.6faa668.el7.noarch
openshift-ansible-3.4.79-1.git.0.6faa668.el7.noarch
```

##### Steps To Reproduce
1. Install multi-node OpenShift v3.4.0.40
2. Follow upgrade steps [here](https://docs.openshift.com/container-platform/3.4/install_config/upgrading/automated_upgrades.html#install-config-upgrading-automated-upgrades)

##### Expected Results
Installation to occur without errors/warnings

##### Observed Results
Seeing [WARNING] output

##### Additional Information

RHEL 7.2

**Comment by sdodson** [comment]
We need to backport https://github.com/openshift/openshift-ansible/pull/4061 to release-1.4 and release-1.3 but we're not yet ready to verify them on ansible 2.3.

release-1.5 and master should be fixed already
