### ISSUE TITLE
es_number_of_shards and es_number_of_replicas aren't used in roles/openshift_logging/templates/es.j2 template

### ISSUE THREAD

**Issue by harobed** [openshift/openshift-ansible#4083]
In `roles/openshift_logging/tasks/set_es_storage.yaml`:

* [es_number_of_shards](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging/tasks/set_es_storage.yaml#L79)
* and [es_number_of_replicas](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging/tasks/set_es_storage.yaml#L80)

aren't used in [roles/openshift_logging/templates/es.j2](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging/templates/es.j2) template.

Why? It's a mistake?

cc @ewolinetz 

Best regards,
Stéphane

**Comment by ewolinetz** [comment]
It is a mistake -- that should be set for the configmap template. 
That must have been overlooked on the change to introduce the ability to configure shard counts.
Thank you for pointing that out!

**Comment by harobed** [comment]
Do you prefer a pull request for `release-1.5` branch and `master` or you can do that today (I need to install it)?

**Comment by ewolinetz** [comment]
@harobed #4084 is the 1.5 fix, i will also cherry pick it for master afterwards. Which version is a higher priority for you?

**Comment by ewolinetz** [comment]
#4085 is the cherry pick pr

**Comment by ewolinetz** [comment]
Should now be resolved by #4084 and #4085
