### ISSUE TITLE
use  ansible  install cluster   have a  No OpenShift version available  Error!

### ISSUE THREAD

**Issue by myonlyzzy** [openshift/openshift-ansible#4092]
#### Description

use  ansible  install cluster   have a  No OpenShift version available  Error!
##### Version

ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

 git describe 
openshift-ansible-3.6.51-1-14-g0a195fb

os  centos7.3 
TASK [openshift_version : Abort if openshift_pkg_version was not set] ***********************************************************************
task path: /home/kevin/openshift-ansible/roles/openshift_version/tasks/main.yml:143
fatal: [master.2dfire.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "No OpenShift version available; please ensure your systems are fully registered and have access to appropriate yum repositories."
}
	to retry, use: --limit @/home/kevin/openshift-ansible/playbooks/byo/config.retry

**Comment by abutcher** [comment]
Hey @myonlyzzy, could you share your inventory and in particular the `deployment_type` set within the inventory? This error indicates that openshift-ansible cannot find the `origin` (`deployment_type=origin`) or `atomic-openshift` (`deployment_type=openshift-enterprise`) package.
