### ISSUE TITLE
Issue configuring MultiMasters

### ISSUE THREAD

**Issue by maiconbaumx** [openshift/openshift-ansible#4100]
#### Description

I'm having problem configuring MultiMasters on OpenShift. I'm following this guide to setup MultiMaster: https://docs.openshift.com/enterprise/3.1/install_config/install/advanced_install.html

Anyone have an idea? I don't know if my ansible/hosts is configured correctly. 

##### Version

Ansible: 2.2.0.0
Docker: 1.10.3
Kubernetes: 1.5.2
OpenShift: 1.5.0

##### Steps To Reproduce
ansible-playbook ./openshift-ansible/playbooks/byo/config.yml -vvv

##### Observed Results

> fatal: [paas-master-maicon.handson.aws.local]: FAILED! => {
>     "changed": false,
>     "failed": true,
>     "invocation": {
>         "module_args": {
>             "additive_facts_to_overwrite": [],
>             "backup": null,
>             "content": null,
>             "delimiter": null,
>             "directory_mode": null,
>             "filter": "*",
>             "follow": false,
>             "force": null,
>             "gather_subset": [
>                 "hardware",
>                 "network",
>                 "virtual",
>                 "facter"
>             ],
>             "gather_timeout": 10,
>             "group": null,
>             "local_facts": {
>                 "api_port": "",
>                 "api_url": "",
>                 "api_use_ssl": "",
>                 "cluster_hostname": "paas-cluster.ommiteddomain.com",
>                 "cluster_public_hostname": "paas-cluster.ommiteddomain.com",
>                 "console_path": "",
>                 "console_port": "",
>                 "console_url": "",
>                 "console_use_ssl": "",
>                 "controllers_port": "",
>                 "ha": true,
>                 "master_count": "2",
>                 "public_api_url": "",
>                 "public_console_url": ""
>             },
>             "mode": null,
>             "openshift_env": {},
>             "openshift_env_structures": [],
>             "owner": null,
>             "protected_facts_to_overwrite": [],
>             "regexp": null,
>             "remote_src": null,
>             "role": "master",
>             "selevel": null,
>             "serole": null,
>             "setype": null,
>             "seuser": null,
>             "src": null,
>             "unsafe_writes": null
>         },
>         "module_name": "openshift_facts"
>     },
>     "msg": "openshift_facts received a different value for openshift.master.ha"
> }
....

> TASK [openshift_master_facts : Set master facts] *******************************
> task path: /root/paas/setup/openshift-ansible/roles/openshift_master_facts/tasks/main.yml:31
> fatal: [paas-master02-maicon.handson.aws.local]: FAILED! => {
>     "failed": true,
>     "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: {{ hostvars[groups.oo_first_master.0].openshift.master.session_encryption_secrets }}: 'dict object' has no attribute 'session_encryption_secrets'\n\nThe error appears to have been in '/root/paas/setup/openshift-ansible/roles/openshift_master_facts/tasks/main.yml': line 31, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set master facts\n  ^ here\n"
> }

##### Additional Information

CentOS 7
8gb RAM
2vCPU

Here is my /etc/ansible/hosts:

> 
> [OSEv3:children]
> masters
> nodes
> lb
> etcd
> 
> [OSEv3:vars]
> 
> ansible_ssh_user=root
> 
> 
> 
> deployment_type=origin
> openshift_master_cluster_method=native
> openshift_clock_enabled=true
> 
> 
> openshift_master_cluster_hostname=paas-cluster.ommiteddomain.com
> 
> openshift_master_cluster_public_hostname=paas-cluster.ommiteddomain.com
> osm_default_subdomain=handson.aws.local
> 
> [masters]
> paas-master-maicon.handson.aws.local openshift_hostname=paas-master-maicon.handson.aws.local
> paas-master02-maicon.handson.aws.local openshift_hostname=paas-master02-maicon.handson.aws.local
> 

> 
> [etcd]
> paas-etcd01-maicon.handson.aws.local
> paas-etcd02-maicon.handson.aws.local
> paas-etcd03-maicon.handson.aws.local

> [lb]
> paas-lb-maicon.handson.aws.local
> 
> [nodes]
> paas-master-maicon.handson.aws.local openshift_hostname=paas-master-maicon.handson.aws.local openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
> paas-master02-maicon.handson.aws.local openshift_hostname=paas-master02-maicon.handson.aws.local openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
> paas-node01-maicon.handson.aws.local openshift_hostname=paas-node01-maicon.handson.aws.local openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
> paas-node02-maicon.handson.aws.local openshift_hostname=paas-node02-maicon.handson.aws.local openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
> paas-node03-maicon.handson.aws.local openshift_hostname=paas-node03-maicon.handson.aws.local openshift_node_labels="{'region': 'primary', 'zone': 'north'}"
> paas-node04-maicon.handson.aws.local openshift_hostname=paas-node04-maicon.handson.aws.local openshift_node_labels="{'region': 'primary', 'zone': 'west'}"

**Comment by maiconbaumx** [comment]
Actually, I added etcds in the ansible/hosts and got a new error:

> task path: /root/paas/setup/openshift-ansible/roles/etcd_common/tasks/etcdctl.yml:2
> fatal: [paas-etcd02-maicon.handson.aws.local]: FAILED! => {
>     "failed": true,
>     "msg": "The conditional check 'o' failed. The error was: error while evaluating conditional (o): 'o' is undefined\n\nThe error appears to have been in '/root/paas/setup/openshift-ansible/roles/etcd/tasks/main.yml': line 123, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include_role:\n  ^ here\n"
> }
> fatal: [paas-etcd01-maicon.handson.aws.local]: FAILED! => {
>     "failed": true,
>     "msg": "The conditional check 'o' failed. The error was: error while evaluating conditional (o): 'o' is undefined\n\nThe error appears to have been in '/root/paas/setup/openshift-ansible/roles/etcd/tasks/main.yml': line 123, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include_role:\n  ^ here\n"
> }
> fatal: [paas-etcd03-maicon.handson.aws.local]: FAILED! => {
>     "failed": true,
>     "msg": "The conditional check 'o' failed. The error was: error while evaluating conditional (o): 'o' is undefined\n\nThe error appears to have been in '/root/paas/setup/openshift-ansible/roles/etcd/tasks/main.yml': line 123, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include_role:\n  ^ here\n"
> }

**Comment by maiconbaumx** [comment]
I saw [this commit](https://github.com/openshift/openshift-ansible/commit/1dcf43f235cd6c5125e4f2b60a4301105b7344fe) changing exactly where I'm getting error. Is there a problem or my configuration is missing?

**Comment by sdodson** [comment]
Yeah, for multi-master you must specify an etcd host, ideally 3 of them as that's what's required for high availability etcd.

If you have the ability I'd start fresh or at least run playbooks/adhoc/uninstall.yml and then start your install again if you ran it once and then again after changing the hosts file.

**Comment by maiconbaumx** [comment]
Thank you for your reply @sdodson. As I said early, I have configured 3 etcd hosts for MultiMaster, but I got a new error: 

> 
> task path: /root/paas/setup/openshift-ansible/roles/etcd_common/tasks/etcdctl.yml:2
> fatal: [paas-etcd02-maicon.handson.aws.local]: FAILED! => {
> "failed": true,
> "msg": "The conditional check 'o' failed. The error was: error while evaluating conditional (o): 'o' is undefined\n\nThe error appears to have been in '/root/paas/setup/openshift-ansible/roles/etcd/tasks/main.yml': line 123, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include_role:\n ^ here\n"
> }
> fatal: [paas-etcd01-maicon.handson.aws.local]: FAILED! => {
> "failed": true,
> "msg": "The conditional check 'o' failed. The error was: error while evaluating conditional (o): 'o' is undefined\n\nThe error appears to have been in '/root/paas/setup/openshift-ansible/roles/etcd/tasks/main.yml': line 123, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include_role:\n ^ here\n"
> }
> fatal: [paas-etcd03-maicon.handson.aws.local]: FAILED! => {
> "failed": true,
> "msg": "The conditional check 'o' failed. The error was: error while evaluating conditional (o): 'o' is undefined\n\nThe error appears to have been in '/root/paas/setup/openshift-ansible/roles/etcd/tasks/main.yml': line 123, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include_role:\n ^ here\n"
> }

**Comment by maiconbaumx** [comment]
Guys, after I try everything.. 
I comment this line from the "/openshift-ansible/roles/etcd/tasks/main.yml" playbook (line 123 to 126):

>- include_role:
>    name: etcd_common
>   tasks_from: etcdctl.yml
>  when: openshift_etcd_etcdctl_profile | default(true) | bool

And this error gonna away.. But, when I try to setup MultiMaster again, I got this error on second Master:


>assetConfig.servingInfo.certFile: Invalid value: "/etc/origin/master/master.server.crt": could not read >file: stat /etc/origin/master/mast
>assetConfig.servingInfo.keyFile: Invalid value: "/etc/origin/master/master.server.key": could not read >file: stat /etc/origin/master/maste
>servingInfo.certFile: Invalid value: "/etc/origin/master/master.server.crt": could not read file: stat >/etc/origin/master/master.server.cr
>servingInfo.keyFile: Invalid value: "/etc/origin/master/master.server.key": could not read file: stat >/etc/origin/master/master.server.key


If I copy this certificates manually to second Master, everything works fine. Anyone knows what I'm doing wrong, please? Or something that I'm forgetting to do..

**Comment by ingvagabund** [comment]
@maiconbaumx can you update your ansible to 2.2.1.0 at least?

**Comment by abutcher** [comment]
The missing certificates issue is https://bugzilla.redhat.com/show_bug.cgi?id=1448824 which should be fixed by https://github.com/openshift/openshift-ansible/pull/4116.

**Comment by maiconbaumx** [comment]
@ingvagabund This is the first thing that I've tryed.. :( 
@abutcher ok, thank you for the reply! 

My workaround was copy certificate manually and re-run the config playbook

**Comment by maiconbaumx** [comment]
Please, close this issue. This new fix works fine for me.
Thanks!
