### ISSUE TITLE
Docker 1.12 restarts itself with docker.cleanup service and breaks upgrades

### ISSUE THREAD

**Issue by jupierce** [openshift/openshift-ansible#4102]
#### Description
roles/openshift_node_upgrade/tasks/docker/upgrade.yml can fail with 
```
fatal: [preview-node-compute-7a588]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "daemon_reload": false, 
            "enabled": null, 
            "masked": null, 
            "name": "docker", 
            "state": "stopped", 
            "user": false
        }
    }, 
    "msg": "Unable to stop service docker: Job for docker.service canceled.\n"
}
```
if the docker.cleanup timer runs at an inopportune time. 

This timer runs once every hour, on the hour, and starts the docker service. 

##### Version
3.5

**Comment by jupierce** [comment]
@sdodson @mwoodson

**Comment by sdodson** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1448457 filed but i think we can work around this in #4099
