### ISSUE TITLE
Limit memory for metrics

### ISSUE THREAD

**Issue by un1x86** [openshift/openshift-ansible#4112]
Hi

I was wondering how to limit memory for metrics pods. I tried with

```
openshift_metrics_cassandra_limits_memory=0.5G
openshift_metrics_hawkular_limits_memory=0.5G
openshift_metrics_heapster_limits_memory=0.5G
```

But that did not seem to work. Ansible runns through fine but the pots are still started with a 2G memory limit.

**Comment by ewolinetz** [comment]
@un1x86 which version of openshift-ansible did you use?

**Comment by un1x86** [comment]
I was using v.1.5.

I recreated the VM and used 

```
openshift_metrics_cassandra_limits_memory=0.5Gi
openshift_metrics_hawkular_limits_memory=0.5Gi
openshift_metrics_heapster_limits_memory=0.5Gi
```

That seems to have worked.

**Comment by ewolinetz** [comment]
@un1x86 good to hear, I'll update the documentation then. I saw that it specified using 'G' instead of 'Gi'.

**Comment by un1x86** [comment]
@ewolinetz thank you.
