### ISSUE TITLE
Install higher version of docker upon running the playbook?

### ISSUE THREAD

**Issue by aelmehra** [openshift/openshift-ansible#4132]
Is it possible to have ansible deploy a higher version of docker than 1.9 or would I need to run the playbook and then upgrade docker?

I am creating a cluster on 3 centos 7.3 VMs.

Thanks

**Comment by sdodson** [comment]
The playbooks should install the maxmimum version of docker supported by the branch you're installing from. Which branch and release of origin are you targetting?

**Comment by aelmehra** [comment]
Im targeting release-1.5. Here is my hosts file:

[OSEv3:children]
masters
nodes
etcd
lb

[OSEv3:vars]
ansible_ssh_user=root
debug_level=2
deployment_type=origin
openshift_release=v1.5
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

[masters]
docker1m

[etcd]
docker[1:2]n

[lb]
docker1m

[nodes]
docker1m
docker[1:2]n openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
