### ISSUE TITLE
Imagestream import fails when using advanced installation method

### ISSUE THREAD

**Issue by Killboy** [openshift/openshift-ansible#415]
The advanced installation method doesn't seem to be using the cluster name/vip to communicate with the active API host, my /etc/ansible/hosts content is listed below the error, is there something I'm missing? Also I'm not sure how to determine all the available parameters for /etc/ansible/hosts

thanks
## error:

TASK: [openshift_examples | Import RHEL streams] *****************************\* 
failed: [ose3m1.cloud.local] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-rhel7.json"], "delta": "0:00:00.184110", "end": "2015-08-04 09:48:38.480609", "failed": true, "failed_when_result": true, "rc": 1, "start": "2015-08-04 09:48:38.296499", "stdout_lines": [], "warnings": []}
stderr: The connection to the server ose3m1.cloud.local:8443 was refused - did you specify the right host or port?
The connection to the server ose3m1.cloud.local:8443 was refused - did you specify the right host or port?
The connection to the server ose3m1.cloud.local:8443 was refused - did you specify the right host or port?
The connection to the server ose3m1.cloud.local:8443 was refused - did you specify the right host or port?
The connection to the server ose3m1.cloud.local:8443 was refused - did you specify the right host or port?
The connection to the server ose3m1.cloud.local:8443 was refused - did you specify the right host or port?
The connection to the server ose3m1.cloud.local:8443 was refused - did you specify the right host or port?
The connection to the server ose3m1.cloud.local:8443 was refused - did you specify the right host or port?
## /etc/ansible/hosts:
# Create an OSEv3 group that contains the masters and nodes groups

[OSEv3:children]
masters
nodes
# Set variables common for all OSEv3 hosts

[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password

ansible_ssh_user=admin
# If ansible_ssh_user is not root, ansible_sudo must be set to true

ansible_sudo=true
# To deploy origin, change deployment_type to origin

deployment_type=enterprise
# enable htpasswd authentication

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/openshift/master/users.htpasswd'}]
# Cluster settings

openshift_master_cluster_password=blah
openshift_master_cluster_vip=192.168.122.110
openshift_master_cluster_public_vip=192.168.122.110
# Point at the vip

openshift_master_public_api_url=https://ose3.cloud.local:8443
openshift_master_public_console_url=https://ose3.cloud.local:8443/console
# host group for masters

[masters]
ose3m1.cloud.local
ose3m2.cloud.local
# host group for nodes, includes region info

[nodes]
ose3m1.cloud.local
ose3m2.cloud.local
ose3n1.cloud.local

**Comment by goern** [comment]
this seems to be the fact when the master is not a node and therefor has no docker installed... task `TASK: [openshift_examples | Import RHEL streams] ` should not be run on master?

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
