### ISSUE TITLE
How to create and define  categorize template ?

### ISSUE THREAD

**Issue by DockerAsura** [openshift/openshift-ansible#4186]
Hi there,
How to create the template in defined catalog on openshift name?

Currently , when i creating a template automatically it defending under Uncategorized. So, How make those tools categorized, category

Openshift Version 1.5

Thanks
Kumar

**Comment by sdodson** [comment]
@DockerAsura See the template creation documentation, you need to set a category.

https://docs.openshift.org/latest/dev_guide/templates.html#writing-templates
