### ISSUE TITLE
Module failure cause of the sudo password

### ISSUE THREAD

**Issue by zafinxueqian** [openshift/openshift-ansible#4202]
#### Description

Provide a brief description of your issue here. For example:

fatal: [10.1.8.6]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "OpenSSH_6.4, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 51: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 45914\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nsudo: a password is required\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n",
    "module_stdout": "",
    "rc": 1
}

##### Version
master branch version
Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
ansible version: 2.3.0.0
If you're operating from a **git clone**:

* The output of `git describe`
openshift-ansible-3.6.68-1-2-gf20bf53

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. [step 1]

ansible-playbook [ -i inventory ] playbooks/byo/config.yml
2. [step 2]

##### Expected Results
Describe what you expected to happen.
openshift installed
```
Example command and output or error messages
```
command::  ansible-playbook [ -i inventory ] playbooks/byo/config.yml

ERROR: 

fatal: [10.1.8.6]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "OpenSSH_6.4, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 51: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 45914\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nsudo: a password is required\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n",
    "module_stdout": "",
    "rc": 1
}

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by zafinxueqian** [comment]
Thank you for your reply, sdodson. I will try that and let you know the result.

**Comment by zafinxueqian** [comment]
Hey @sdodson , after changes, I got another error: 
MSG:

Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.


fatal: [10.1.4.5]: FAILED! => {
    "changed": false,
    "failed": true
}

**Comment by sdodson** [comment]
@zafinxueqian on 10.1.4.5 `journalctl -lu origin-node.service` to see what it's complaining about.

**Comment by zafinxueqian** [comment]
@sdodson , I'm using centos 7 and I got an weird error:

fatal: [TempMaster1]: FAILED! => {
    "changed": true,
    "failed": true,
    "rc": 1,
    "results": [
        "Loaded plugins: fastestmirror, langpacks\nLoading mirror speeds from cached hostfile\n * epel: mirror.steadfast.net\nResolving Dependencies\n--> Running transaction check\n---> Package origin-docker-excluder.noarch 0:1.5.0-1.el7 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package                 Arch    Version         Repository                Size\n================================================================================\nInstalling:\n origin-docker-excluder  noarch  1.5.0-1.el7     centos-openshift-origin  6.0 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package\n\nTotal download size: 6.0 k\nInstalled size: 2.4 k\nDownloading packages:\nPublic key for origin-docker-excluder-1.5.0-1.el7.noarch.rpm is not installed\nRetrieving key from file:///etc/pki/rpm-gpg/openshift-ansible-CentOS-SIG-PaaS\n"
    ]
}

MSG:

warning: /var/cache/yum/x86_64/7/centos-openshift-origin/packages/origin-docker-excluder-1.5.0-1.el7.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID 2f297ecc: NOKEY


GPG key retrieval failed: [Errno 14] curl#37 - "Couldn't open file /etc/pki/rpm-gpg/openshift-ansible-CentOS-SIG-PaaS".   


But actually I can find the key file  under that directory. What should I do?
