### ISSUE TITLE
Set Node Schedulability Failed

### ISSUE THREAD

**Issue by rppf** [openshift/openshift-ansible#4207]
Trying openshift-ansible in CentOS 7 on VMWare
Then I encountered this error

TASK [openshift_manage_node : Set node schedulability] **********************************************************************
FAILED - RETRYING: Set node schedulability (10 retries left).
FAILED - RETRYING: Set node schedulability (9 retries left).
FAILED - RETRYING: Set node schedulability (8 retries left).
FAILED - RETRYING: Set node schedulability (7 retries left).
FAILED - RETRYING: Set node schedulability (6 retries left).
FAILED - RETRYING: Set node schedulability (5 retries left).
FAILED - RETRYING: Set node schedulability (4 retries left).
FAILED - RETRYING: Set node schedulability (3 retries left).
FAILED - RETRYING: Set node schedulability (2 retries left).
FAILED - RETRYING: Set node schedulability (1 retries left).
fatal: [console.dampi.tk -> console.dampi.tk]: FAILED! => {"attempts": 10, "changed": false, "failed": true, "msg": {"results": [{"cmd": "/usr/local/bin/oc get node 192.168.230.130 -o json", "results": [{}], "returncode": 1, "stderr": "Unable to connect to the server: net/http: TLS handshake timeout\n", "stdout": ""}], "returncode": 1}}
        to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

This is my inventory file

[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswo$
containerized=true
openshift_release=v1.5
openshift_image_tag=v1.5.0
openshift_public_hostname=console.dampi.tk
openshift_master_default_subdomain=apps.console.dampi.tk
openshift_hosted_metrics_deploy=false

[masters]
console.dampi.tk openshift_schedulable=true

[nodes]
console.dampi.tk openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true

**Comment by sdodson** [comment]
Why is your master down? `journalctl -lu origin-master`

**Comment by Black-X** [comment]
I look over journals and I cant see any error on origin-master.

**Comment by abutcher** [comment]
@Black-X So `origin-master` service is up and healthy? What do we get from running the following from the master?

```
oc --loglevel=7 --config=/etc/origin/master/admin.kubeconfig get node/192.168.230.130
```

**Comment by Black-X** [comment]
This is what I've got from running the command above

I0517 00:29:12.617943    3224 loader.go:354] Config loaded from file /etc/origin                        /master/admin.kubeconfig
I0517 00:29:12.646719    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/api
I0517 00:29:12.646752    3224 round_trippers.go:303] Request Headers:
I0517 00:29:12.646762    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:12.646770    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:12.913269    3224 round_trippers.go:321] Response Status: 200 OK in                         266 milliseconds
I0517 00:29:12.914113    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/apis
I0517 00:29:12.914165    3224 round_trippers.go:303] Request Headers:
I0517 00:29:12.914190    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:12.914213    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:12.925257    3224 round_trippers.go:321] Response Status: 200 OK in                         11 milliseconds
I0517 00:29:12.989545    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/apis/apps/v1beta1
I0517 00:29:12.989594    3224 round_trippers.go:303] Request Headers:
I0517 00:29:12.989612    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:12.989628    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:12.993066    3224 round_trippers.go:321] Response Status: 200 OK in                         3 milliseconds
I0517 00:29:13.013791    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/apis/authentication.k8s.io/v1beta1
I0517 00:29:13.013842    3224 round_trippers.go:303] Request Headers:
I0517 00:29:13.013859    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:13.013876    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:13.017243    3224 round_trippers.go:321] Response Status: 200 OK in                         3 milliseconds
I0517 00:29:13.018020    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/apis/autoscaling/v1
I0517 00:29:13.018047    3224 round_trippers.go:303] Request Headers:
I0517 00:29:13.018063    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:13.018079    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:13.022114    3224 round_trippers.go:321] Response Status: 200 OK in                         4 milliseconds
I0517 00:29:13.022759    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/apis/batch/v1
I0517 00:29:13.022781    3224 round_trippers.go:303] Request Headers:
I0517 00:29:13.022792    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:13.022802    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:13.025946    3224 round_trippers.go:321] Response Status: 200 OK in                         3 milliseconds
I0517 00:29:13.026445    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/apis/batch/v2alpha1
I0517 00:29:13.026461    3224 round_trippers.go:303] Request Headers:
I0517 00:29:13.026468    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:13.026476    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:13.029294    3224 round_trippers.go:321] Response Status: 200 OK in                         2 milliseconds
I0517 00:29:13.055097    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/apis/certificates.k8s.io/v1alpha1
I0517 00:29:13.055115    3224 round_trippers.go:303] Request Headers:
I0517 00:29:13.055121    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:13.055126    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:13.057357    3224 round_trippers.go:321] Response Status: 200 OK in                         2 milliseconds
I0517 00:29:13.057688    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/apis/extensions/v1beta1
I0517 00:29:13.057698    3224 round_trippers.go:303] Request Headers:
I0517 00:29:13.057704    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:13.057709    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:13.059963    3224 round_trippers.go:321] Response Status: 200 OK in                         2 milliseconds
I0517 00:29:13.060402    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/apis/policy/v1beta1
I0517 00:29:13.060413    3224 round_trippers.go:303] Request Headers:
I0517 00:29:13.060418    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:13.060423    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:13.062538    3224 round_trippers.go:321] Response Status: 200 OK in                         2 milliseconds
I0517 00:29:13.087848    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/apis/storage.k8s.io/v1beta1
I0517 00:29:13.087870    3224 round_trippers.go:303] Request Headers:
I0517 00:29:13.087876    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:13.087881    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:13.089202    3224 round_trippers.go:321] Response Status: 200 OK in                         1 milliseconds
I0517 00:29:13.089545    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/api/v1
I0517 00:29:13.089557    3224 round_trippers.go:303] Request Headers:
I0517 00:29:13.089562    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:13.089567    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:13.091961    3224 round_trippers.go:321] Response Status: 200 OK in                         2 milliseconds
I0517 00:29:13.234991    3224 request.go:632] Throttling request took 142.746866                        ms, request: GET:https://192.168.230.130:8443/oapi/v1
I0517 00:29:13.235164    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/oapi/v1
I0517 00:29:13.235193    3224 round_trippers.go:303] Request Headers:
I0517 00:29:13.235329    3224 round_trippers.go:306]     Accept: application/jso                        n, */*
I0517 00:29:13.235372    3224 round_trippers.go:306]     User-Agent: oc/v1.5.0+0                        31cbe4 (linux/amd64) openshift/a4aae4a
I0517 00:29:13.244160    3224 round_trippers.go:321] Response Status: 200 OK in                         8 milliseconds
I0517 00:29:13.246669    3224 cached_discovery.go:112] returning cached discover                        y info from /root/.kube/192.168.230.130_8443/servergroups.json
I0517 00:29:13.246779    3224 cached_discovery.go:70] returning cached discovery                         info from /root/.kube/192.168.230.130_8443/apps/v1beta1/serverresources.json
I0517 00:29:13.246857    3224 cached_discovery.go:70] returning cached discovery                         info from /root/.kube/192.168.230.130_8443/authentication.k8s.io/v1beta1/server                        resources.json
I0517 00:29:13.247004    3224 cached_discovery.go:70] returning cached discovery                         info from /root/.kube/192.168.230.130_8443/autoscaling/v1/serverresources.json
I0517 00:29:13.247096    3224 cached_discovery.go:70] returning cached discovery                         info from /root/.kube/192.168.230.130_8443/batch/v1/serverresources.json
I0517 00:29:13.247196    3224 cached_discovery.go:70] returning cached discovery                         info from /root/.kube/192.168.230.130_8443/batch/v2alpha1/serverresources.json
I0517 00:29:13.247581    3224 cached_discovery.go:70] returning cached discovery                         info from /root/.kube/192.168.230.130_8443/certificates.k8s.io/v1alpha1/serverr                        esources.json
I0517 00:29:13.247757    3224 cached_discovery.go:70] returning cached discovery                         info from /root/.kube/192.168.230.130_8443/extensions/v1beta1/serverresources.j                        son
I0517 00:29:13.247830    3224 cached_discovery.go:70] returning cached discovery                         info from /root/.kube/192.168.230.130_8443/policy/v1beta1/serverresources.json
I0517 00:29:13.247915    3224 cached_discovery.go:70] returning cached discovery                         info from /root/.kube/192.168.230.130_8443/storage.k8s.io/v1beta1/serverresourc                        es.json
I0517 00:29:13.248572    3224 cached_discovery.go:70] returning cached discovery                         info from /root/.kube/192.168.230.130_8443/v1/serverresources.json
I0517 00:29:13.252307    3224 cached_discovery.go:112] returning cached discover                        y info from /root/.kube/192.168.230.130_8443/servergroups.json
I0517 00:29:13.252569    3224 round_trippers.go:296] GET https://192.168.230.130                        :8443/api/v1/nodes/192.168.230.130
I0517 00:29:13.252583    3224 round_trippers.go:303] Request Headers:
I0517 00:29:13.252591    3224 round_trippers.go:306]     Accept: application/jso                        n
I0517 00:29:13.252598    3224 round_trippers.go:306]     User-Agent: oc/v1.5.2+4                        3a9be4 (linux/amd64) kubernetes/43a9be4
I0517 00:29:13.315433    3224 round_trippers.go:321] Response Status: 200 OK in                         62 milliseconds
NAME              STATUS    AGE
192.168.230.130   Ready     12h

**Comment by abutcher** [comment]
@Black-X Alright, that output looks good and we were able to get the node. I'd expect the task that failed above to pass. Maybe this was an intermittent failure.

**Comment by Black-X** [comment]
Should I reinstall openshift-ansible? By the way. I'm following this tutorial
https://www.youtube.com/watch?v=-OOnGK-XeVY

**Comment by abutcher** [comment]
@Black-X Try re-running the playbook and see if we get past that step.

**Comment by rppf** [comment]
Sorry for the late response. I already solved it. Thanks. I just misconfigured my ip address in my VM.
