### ISSUE TITLE
openshift_hosted components should not default to registry.access.redhat.com

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-ansible#4210]
#### Description

When doing a disconnected install, I will point my cluster to a private registry like so:

```
openshift_docker_additional_registries=registry.example.com:5000
openshift_docker_insecure_registries=registry.example.com:5000
openshift_docker_blocked_registries=registry.access.redhat.com,docker.io
```

Currently these settings are ignored by multiple components because they are hard coded to `registry.access.redhat.com/openshift3`. If they were to default to `openshift3/` instead, then the above would be all i needed to do a disconnected install from a private registry. Instead i have to also remap all of the following:

```
oreg_url=/openshift3/ose-${component}:${version}
openshift_cockpit_deployer_prefix=/openshift3/
openshift_hosted_logging_deployer_prefix=/openshift3/
openshift_metrics_image_prefix=/openshift3/
```

I believe that all of these should simply default to the above, rather than having the registry hard-coded in them.

@ewolinetz @sdodson

**Comment by sdodson** [comment]
We should push people to set oreg_url and use that to define the registry
host. That's how the old template based install for logging and metrics
worked.

The additional registries stuff is red hat specific and can lead to
unexpected behavior (first registry dies, fails through to next registry,
etc). I guess it's safer if you block other registries but still seems non
deterministic.
