### ISSUE TITLE
Need to make sure we have etcd >= 2.0.11

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#422]
etcd-0.4.6 was shipped in rhel-7-extras channel so we should make sure that ansible ensures >= 2.0.11

**Comment by sdodson** [comment]
CC: @etsauer

**Comment by alangibson** [comment]
This also effects Oracle Linux 7. The quick and dirty hack is

    curl -O ftp://fr2.rpmfind.net/linux/fedora/linux/development/rawhide/x86_64/os/Packages/e/etcd-2.1.1-2.fc24.x86_64.rpm
    sudo rpm -hiv etcd-2.1.1-2.fc24.x86_64.rpm

**Comment by sdodson** [comment]
@alangibson etcd-2 has been in the rhel-7-extras channel for ~3 months, though regrettably it'll be some time before etcd-2.1 is available. Does OEL have an extras channel as well?

**Comment by alangibson** [comment]
Somewhat surprisingly Oracle has a public yum repo:

    http://public-yum.oracle.com/oracle-linux-7.html

There's no etcd in either the latest, addons or optional channels. For that, I'd normally look in to EPEL, CentOS, or (as a last resort) the equivalent Fedora.

**Comment by samsong8610** [comment]
Break installation on fedora 22.

    TASK: [etcd | Install etcd] ***************************************************
    failed: [master1.paas.local] => {"changed": true, "rc": 1, "results": ["Last metadata expiration check performed 0:21:06 ago on Fri Aug 28 09:44:54 2015.\nNo package etcd-2.* available.\n"]}
    msg: Yum command has been deprecated, redirecting to '/usr/bin/dnf -d 2 -y install etcd-2.*'.
    See 'man dnf' and 'man yum2dnf' for more information.
    To transfer transaction metadata from yum to DNF, run:
    'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'

    Error: Unable to find a match.

    # dnf --version
    1.1.0
      Installed: dnf-0:1.1.0-2.fc22.noarch at 2015-08-28 09:38
      Built    : Fedora Project at 2015-08-12 16:58
    
      Installed: rpm-0:4.12.0.1-12.fc22.x86_64 at 2015-08-28 09:37
      Built    : Fedora Project at 2015-06-29 10:36
    # uname -a
    Linux master1.paas.local 4.0.4-301.fc22.x86_64 #1 SMP Thu May 21 13:10:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I also installed yum etc.
    dnf list installed|grep yum
    dnf-yum.noarch                          1.1.0-2.fc22                     @System
    yum.noarch                              3.4.3-505.fc22                   @System
    yum-metadata-parser.x86_64              1.1.4-14.fc22                    @System
    yum-utils.noarch                        1.1.31-508.fc22                  @System

I think `dnf install` only compare the glob pattern against the package name part which may contains slash.
