### ISSUE TITLE
[RFE] improve template/imagestream installation

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-ansible#424]
With the 3.0.1 upgrade it appears that the installer doesn't "update" the image streams / templates it installs.

We should:

1) check for existing templates
2) if no templates found, use "oc create", otherwise "oc replace"

**Comment by brenton** [comment]
We'll probably have to have ansible prompt for confirmation if it detects `oc replace` is needed.  I'm a little worried we'll nuke someone's customizations.

**Comment by detiber** [comment]
@brenton fully agree, this should probably be part of an upgrade workflow and not the normal installation workflow.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
