### ISSUE TITLE
Installer should be idempotent 

### ISSUE THREAD

**Issue by timothysc** [openshift/openshift-ansible#425]
I know this is a tall order, but we should strive to make the installer idempotent, which currently it's not.  

If the installation fails for any reason it will leave the machine in 1/2 configured state.  Subsequent runs will often fail due to the previous installation state.  

cc @smarterclayton @mattf @eparis @scollier

**Comment by smarterclayton** [comment]
@brenton

On Wed, Aug 5, 2015 at 4:05 PM, Timothy St. Clair <notifications@github.com>
wrote:

> I know this is a tall order, but we should strive to make the installer
> idempotent, which currently it's not.
>
> If the installation fails for any reason it will leave the machine in 1/2
> configured state. Subsequent runs will often fail due to the previous
> installation state.
>
> cc @smarterclayton <https://github.com/smarterclayton> @mattf
> <https://github.com/mattf> @eparis <https://github.com/eparis> @scollier
> <https://github.com/scollier>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/openshift-ansible/issues/425>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by brenton** [comment]
If you can give us details of what actually failed in your case we can be sure to address it with priority.  We are aware that many of the pre checks to see if a job needs to run are not are pretty dumb today.

**Comment by timothysc** [comment]
There were several issues... before any subsequent run I needed to pdsh the nodes in my cluster and run:

rm -rf /etc/openshift /var/lib/openshift /etc/etcd /var/lib/etcd /etc/sysconfig/openshift* /etc/sysconfig/docker* /root/.kube/config /etc/ansible/facts.d /usr/share/openshift

One issue that stood out in my mind was the mundging of /etc/sysconfig/docker file, was not detected by subsequent installation runs, causing them to fail.

**Comment by brenton** [comment]
Thanks Tim!

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit

This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
