### ISSUE TITLE
Making Openshift Installer be a downstream of k8's installer.

### ISSUE THREAD

**Issue by timothysc** [openshift/openshift-ansible#426]
I know this is also a tall order, but some of the benefits of having a large community around k8's is with enough eyeballs, all bugs are shallow.  Many of the modifications I've been making around clustered etcd configuration I would like to make in a single location and simply tell someone to rebase and absorb those changes.  

For the time being I'll create multiple pulls, but we should strive to leverage the community where we can.  

cc @smarterclayton @mattf @eparis @scollier 

ref: https://github.com/GoogleCloudPlatform/kubernetes/tree/master/contrib/ansible

**Comment by detiber** [comment]
@timothysc I agree fully.

@twiest we should probably discuss how to do this further in a way that works for origin/online/enterprise.  I would really like to be able to checkout the upstream repo(s) as sibling repos to avoid duplication. That said, we'd probably want a "fork" of the k8s ansible that we "rebase" based on the upstream code to prevent upstream changes from breaking workflow.

Thinking something like:
kubernetes-ansible (fork of the ansible code subdirectory from upstream k8s)
openshift-ansible (sibling repo to kubernetes-ansible that somehow references the sibling repo to inherit roles, filters, modules, etc)

We could always just "rebase" the upstream roles into openshift-ansible periodically, but the clear separation may make re-use easier among the different products we are now supporting....

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit
