### ISSUE TITLE
hawkular metrics missing view permmisions

### ISSUE THREAD

**Issue by jcantrill** [openshift/openshift-ansible#4281]
Using metrics playbook with 'oc cluster up' for https://github.com/openshift/origin/pull/14338 I ran into this with the metrics image.  Shouldn't the role be adding this?
```
Error: the service account for Hawkular Metrics does not have permission to view resources in this namespace. View permissions are required for Hawkular Metrics to function properly.
Usually this can be resolved by running: oc adm policy add-role-to-user view system:serviceaccount:openshift-infra:hawkular -n openshift-infra
```

cc @ewolinetz @mwringe

**Comment by ewolinetz** [comment]
Is this a new requirement? Was this something that was missed when we ported the role over?

**Comment by mwringe** [comment]
The role should probably be automatically adding this.

What version is this for?

**Comment by jcantrill** [comment]
3.6 plus... probably need to also check 3.5 since we are using ansible there too

**Comment by ewolinetz** [comment]
On master: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_metrics/tasks/generate_rolebindings.yaml

On 1.5: https://github.com/openshift/openshift-ansible/blob/release-1.5/roles/openshift_metrics/tasks/generate_rolebindings.yaml

**Comment by WangHouLing** [comment]
Excuse me,is there any way that I could get metrics not be limited by tenant?

@mwringe @ewolinetz @jcantrill
