### ISSUE TITLE
Set first etcd url to be local (to the master)

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-ansible#4293]
If etcd is colocated in the master, docs recommend setting the URL in master-config to be the local etcd

https://docs.openshift.org/latest/scaling_performance/host_practices.html

Currently it seems to only rank by the order based on what is listed in the ansible inventory

**Comment by abutcher** [comment]
Removed this recommendation from the docs via https://github.com/openshift/openshift-docs/pull/4543 since endpoints are chosen randomly.
