### ISSUE TITLE
origin 1.4.1 to 1.5.1 logging upgrade

### ISSUE THREAD

**Issue by jantzen05** [openshift/openshift-ansible#4355]
Updating origin logging from version 1.4.1 to 1.5.1 ends with: 
`TASK [openshift_logging : Generate Elasticsearch DeploymentConfig] ***********************************************************
task path: /opt/openshift/openshift-ansible/roles/openshift_logging/tasks/set_es_storage.yaml:66
fatal: [serverX]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "AnsibleUndefinedVariable: 'unicode object' has no attribute 'iteritems'"
`
We have host mounted storage.
openshift-ansible-3.5.72-1

Running:
ansible-playbook ./playbooks/byo/openshift-cluster/openshift-logging.yml 

Logging settings in ansible hosts file:
`# Loggging settings
openshift_logging_install_logging=true
openshift_logging_image_prefix="openshift/origin-"
openshift_logging_image_version="v1.5.1"
openshift_logging_namespace=logging
openshift_logging_use_ops=true
openshift_logging_master_url="https://kubernetes.default.svc.cluster.local"
openshift_logging_public_master_url="https://paas:8443"
openshift_logging_curator_default_days=31
openshift_logging_curator_run_hour=0
openshift_logging_curator_run_minute=0
openshift_logging_curator_run_timezone="UTC"
openshift_logging_curator_script_log_level="INFO"
openshift_logging_curator_log_level="ERROR"
openshift_logging_curator_cpu_limit="100m"
openshift_logging_curator_memory_limit="512M"
openshift_logging_curator_nodeselector="role=infra"
openshift_logging_curator_ops_cpu_limit="100m"
openshift_logging_curator_ops_memory_limit="512M"
openshift_logging_curator_ops_nodeselector="role=infra"
openshift_logging_kibana_hostname="logging.com"
openshift_logging_kibana_replica_count=2
openshift_logging_kibana_cpu_limit="200m"
openshift_logging_kibana_memory_limit="2G"
openshift_logging_kibana_nodeselector="role=infra"
openshift_logging_kibana_ops_hostname="logging-ops.com"
openshift_logging_kibana_ops_replica_count=2
openshift_logging_kibana_ops_cpu_limit="200m"
openshift_logging_kibana_ops_memory_limit="2G"
openshift_logging_kibana_ops_nodeselector="role=infra"
openshift_logging_fluentd_nodeselector="logging-infra-fluentd=true"
openshift_logging_es_cluster_size=2
openshift_logging_es_cpu_limit="500m"
openshift_logging_es_memory_limit="2G"
openshift_logging_es_pvc_dynamic="false"
openshift_logging_es_recover_after_time="5m"
openshift_logging_es_nodeselector="role=infra"
openshift_logging_es_ops_allow_cluster_reader=true
openshift_logging_es_ops_cluster_size=2
openshift_logging_es_ops_cpu_limit="500m"
openshift_logging_es_ops_memory_limit="2G"
openshift_logging_es_ops_pvc_dynamic="false"
openshift_logging_es_ops_recover_after_time="5m"
openshift_logging_es_ops_nodeselector="role=infra"`

##### Steps To Reproduce
Having openshift 1.4.1 with host mounted storage and the above settings.
1. run ansible-playbook ./playbooks/byo/openshift-cluster/openshift-logging.yml 

OS: redhat:enterprise_linux:7.3:ga:server

**Comment by ewolinetz** [comment]
Can you update your node_selectors to be in the form of `openshift_logging_es_nodeselector={"role": "infra"}` ?

**Comment by jantzen05** [comment]
I updated all the nodeselectors and got pass this error.
