### ISSUE TITLE
openshift.hosted.registry: Object Storage Provider: "gcs" is not currently supported

### ISSUE THREAD

**Issue by pschiffe** [openshift/openshift-ansible#4366]
#### Description

OpenShift hosted registry role doesn't fully support GCS (google cloud storage) object storage provider. While the `registry_config.j2` template file supports it [1], the execution of the role won't pass the assertion [2].

[1] https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_hosted/templates/registry_config.j2#L56
[2] https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_hosted/tasks/registry/storage/object_storage.yml#L5

When fixing the assertion to:
```
- openshift.hosted.registry.storage.provider in ['azure_blob', 's3', 'swift', 'gcs']
```
the OpenShift hosted registry role works correctly for me.

##### Version

```
$ git describe 
openshift-ansible-3.5.78-1
```

##### Steps To Reproduce
Try to deploy OpenShift 3.5 with Ansible installer on the Google Cloud Platform with hosted registry. Config I'm trying to use:
```
openshift_hosted_registry_selector: 'role=infra'
openshift_hosted_registry_storage_kind: object
openshift_hosted_registry_storage_provider: gcs
openshift_hosted_registry_storage_gcs_bucket: '{{ some_valid_bucket }}'
openshift_hosted_registry_storage_gcs_rootdirectory: /registry
openshift_hosted_registry_pullthrough: true
openshift_hosted_registry_acceptschema2: true
openshift_hosted_registry_enforcequota: true
```

##### Expected Results
Successfully deployed OpenShift on GCP.

##### Observed Results
Failed assertion `Object Storage Provider: "gcs" is not currently supported`

**Comment by abutcher** [comment]
@pschiffe are you able to successfully configure gcs registry storage if you remove the assertion?

**Comment by pschiffe** [comment]
@abutcher yes, I've tried that and it worked.

**Comment by abutcher** [comment]
@pschiffe Great, let's knock down that barrier then.

**Comment by pschiffe** [comment]
@abutcher awesome, thanks! Would it be possible to merge this commit also to the `release-1.5` branch?

**Comment by ingvagabund** [comment]
1.5 backport here https://github.com/openshift/openshift-ansible/pull/4420
