### ISSUE TITLE
Uninstall playbook should not delete directories. 

### ISSUE THREAD

**Issue by SamLeonard93** [openshift/openshift-ansible#4385]
#### Description

The ansible playbook deletes directories by name. It should delete by dir/* 

This will avoid any mapped storage to an OCP directory (namely /var/lib/openshift) from causing an uninstall failure. 

##### Version

openshift-ansible-playbooks.noarch                 3.5.71-1.git.0.128c2db.el7                  rhel-7-server-ose-3.5-rpms

##### Steps To Reproduce

Run the uninstall playbook on an installation that has /var/lib/openshift on a separate mount. The uninstall will fail.

##### Expected Results

The uninstall runs to completion

##### Observed Results

The uninstall fails trying to remove a directory.

##### Additional Information

Workaround by adding the following to the bottom of the uninstaller stanza that is erroring out:

  - name: Remove remaining files
    file: path={{ item }} state=absent
    with_items:
    - "~{{ ansible_ssh_user }}/.kube"
    - /etc/ansible/facts.d/openshift.fact
    - /etc/atomic-enterprise
    - /etc/corosync
    - /etc/openshift
    - /etc/openshift-sdn
    - /etc/systemd/system/atomic-openshift-master.service
    - /etc/systemd/system/atomic-openshift-master-api.service
    - /etc/systemd/system/atomic-openshift-master-controllers.service
    - /etc/systemd/system/origin-master.service
    - /etc/systemd/system/origin-master-api.service
    - /etc/systemd/system/origin-master-controllers.service
    - /etc/systemd/system/openvswitch.service
    - /etc/sysconfig/atomic-enterprise-master
    - /etc/sysconfig/atomic-enterprise-master-api
    - /etc/sysconfig/atomic-enterprise-master-controllers
    - /etc/sysconfig/atomic-openshift-master-api
    - /etc/sysconfig/atomic-openshift-master-controllers
    - /etc/sysconfig/origin-master
    - /etc/sysconfig/origin-master-api
    - /etc/sysconfig/origin-master-controllers
    - /etc/sysconfig/openshift-master
    - /etc/sysconfig/origin-master
    - /etc/sysconfig/origin-master-api
    - /etc/sysconfig/origin-master-controllers
    - /root/.kube
    - /usr/share/openshift/examples
    - /var/lib/atomic-enterprise
    - /var/lib/openshift
    - /var/lib/pacemaker
    - /var/lib/pcsd
    - /usr/lib/systemd/system/atomic-openshift-master-api.service
    - /usr/lib/systemd/system/atomic-openshift-master-controllers.service
    - /usr/lib/systemd/system/origin-master-api.service
    - /usr/lib/systemd/system/origin-master-controllers.service
    - /usr/local/bin/openshift
    - /usr/local/bin/oadm
    - /usr/local/bin/oc
    - /usr/local/bin/kubectl
    - /etc/flannel
    **ignore_errors: yes**

**Comment by sal2fcVir** [comment]
@etsauer @j5r5myk

**Comment by etsauer** [comment]
@abutcher @sdodson 

Would it make sense for the `file` module to be enhanced to support something like `state=empty` for directories? I can open an RFE on the ansible side, just wanted to see what you thought about that.

**Comment by abutcher** [comment]
We'll also have access to the built-in `ansible_mounts` fact that we could check. Out directories we delete `/var/lib/openshift` is probably the only one likely to be a mount so we could special case it and determine if it is a mount prior to deleting OR we could check all directories.

```
ok: [master1.abutcher.com] => {
    "ansible_mounts": [
        {
            "device": "/dev/mapper/rhel-root", 
            "fstype": "xfs", 
            "mount": "/", 
            "options": "rw,seclabel,relatime,attr2,inode64,noquota", 
            "size_available": 11620257792, 
            "size_total": 18238930944, 
            "uuid": "b6e63afe-a4e2-4074-9ee1-46efa3ff9530"
        }, 
        {
            "device": "/dev/sda1",
            "fstype": "xfs",
            "mount": "/boot",
            "options": "rw,seclabel,relatime,attr2,inode64,noquota",
            "size_available": 822747136,
            "size_total": 1063256064,
            "uuid": "789cdfcb-635e-4ba8-9aca-78d8763216ed"
        }
    ]
    "changed": false
}
```

**Comment by etsauer** [comment]
Yeah that would make sense for now.

Just curious, why aren't `/var/lib/origin` or `/var/lib/etcd` on this list? Those are two others that are likely to be mounts.

**Comment by jblbn** [comment]
Hi, I'm also seeing this issue when Docker uses a mountpoint at /var/lib/docker
