### ISSUE TITLE
fedora atomic 25 - issue with default registry,  pushing docker image to regitry failed

### ISSUE THREAD

**Issue by anihak** [openshift/openshift-ansible#4389]
hi,
i have deployed openshift on 3 VMS (1 master and 2 nodes ), as described in this link (http://www.projectatomic.io/blog/2016/12/part2-install-origin-on-f25-atomic-host/),  I have removed the etcd from the docker file since i get error with it. so , now ! my openshift is working but when I try to deploy the sample Java application in the catalog I get this error   :    

```
Pushing image 172.30.133.100:5000/sample/sampleapp:latest ...
Registry server Address: 
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: Get https://172.30.133.100:5000/v1/_ping: Tunnel Connection Failed

```

 

Provide a brief description of your issue here. For example:

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by sdodson** [comment]
This looks to be a networking issue, can you please go through the networking debug steps to verify what connectivity issues you're encountering when trying to reach the docker registry? You'll want to verify connectivity to https://172.30.133.100:5000/v1/_ping from the host where your build ran.

https://docs.openshift.org/latest/admin_guide/sdn_troubleshooting.html

**Comment by anihak** [comment]
here is a part of the networking debug  result .  up to now  , i found a problem in the registry's endpoint 
is there a way to fix it  ?  
[root@openshift-demo ~]# oc get route --all-namespaces
NAMESPACE   NAME               HOST/PORT                                       PATH      SERVICES           PORT       TERMINATION   WILDCARD
default     docker-registry    docker-registry-default.XX.XX.131.17.xip.io              docker-registry    <all>      passthrough   None
default     registry-console   registry-console-default.XX.XX.131.17.xip.io             registry-console   <all>      passthrough   None
sample      sampleapp          sampleapp-sample.XX.XX.131.17.xip.io                     sampleapp          8080-tcp                 None


[root@openshift-demo ~]# oc get services --all-namespaces
NAMESPACE   NAME               CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
default     docker-registry    172.30.133.100   <none>        5000/TCP                  1d
default     kubernetes         172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     1d
default     registry-console   172.30.179.218   <none>        9000/TCP                  1d
default     router             172.30.168.129   <none>        80/TCP,443/TCP,1936/TCP   1d
sample      sampleapp          172.30.50.34     <none>        8080/TCP                  1d




[root@openshift-demo ~]# curl -kv http://172.30.133.100:5000/bar
*   Trying 172.30.133.100...
* TCP_NODELAY set
* Connected to 172.30.133.100 (172.30.133.100) port 5000 (#0)
> GET /bar HTTP/1.1
> Host: 172.30.133.100:5000
> User-Agent: curl/7.51.0
> Accept: */*
>

* Curl_http_done: called premature == 0
* Connection #0 to host 172.30.133.100 left intact


[root@openshift-demo ~]# oc get endpoints --selector=docker-registry
No resources found.


[root@openshift-2 cloud-user]# sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1


[root@openshift-2 cloud-user]#  ip route
default via XX.XX.130.254 dev eth0 proto static metric 100
10.128.0.0/14 dev tun0 proto kernel scope link
XX.XX.130.0/23 dev eth0 proto kernel scope link src XX.XX.131.17 metric 100
169.254.169.254 via 139.54.131.1 dev eth0 proto dhcp metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.30.0.0/16 dev tun0 scope link
192.168.134.0/24 dev eth1 proto kernel scope link src 192.168.134.160 metric 100
