### ISSUE TITLE
release-1.5 fails on fedora25 with "RuntimeError: dictionary changed size during iteration"

### ISSUE THREAD

**Issue by jfclere** [openshift/openshift-ansible#4406]
#### Description

While running:
ansible-playbook playbooks/byo/config.yml -e 'ansible_python_interpreter=/usr/bin/python3'
I have the following error (for all the nodes)
+++
fatal: [bela1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "dummy_init: Refcount now 1\nTraceback (most recent call last):\n  File \"/tmp/ansible_mf2iyrvc/ansible_module_openshift_facts.py\", line 2491, in <module>\n    main()\n  File \"/tmp/ansible_mf2iyrvc/ansible_module_openshift_facts.py\", line 2478, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_mf2iyrvc/ansible_module_openshift_facts.py\", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n", 
    "module_stdout": "", 
    "rc": 1
}

MSG:

MODULE FAILURE

+++

##### Version

[jfclere@jfcpc openshift-ansible]$ ansible --version
ansible 2.3.0.0
  config file = /home/jfclere/BELA/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

##### Steps To Reproduce
1. adjust [/etc/ansible/hosts (to openshift_release=v1.5.0) from a running v1.4.1)
2. ansible-playbook playbooks/byo/config.yml -e 'ansible_python_interpreter=/usr/bin/python3'

##### Expected Results
Installed master, etcd and nodes.

##### Observed Results
Error message.

**Comment by jfclere** [comment]
I have retried with penshift-ansible-3.5.82-1 the problem is still here.

**Comment by abutcher** [comment]
This was addressed in master by https://github.com/openshift/openshift-ansible/pull/4062/commits/fb16c946f7ec37c615e976faadf726151b75d386. We should backport commit to `release-1.5` if the fix is good.

**Comment by jfclere** [comment]
Yes that fixes the problem.

**Comment by abutcher** [comment]
@jfclere Thanks for the heads up! I'll throw a backport together and link to this issue.
