### ISSUE TITLE
RFE: disk space checks on root filesystem

### ISSUE THREAD

**Issue by dustymabe** [openshift/openshift-ansible#4413]
on commit dc12c4b

Was able to get my system in an interesting state because of limited disk space on the root filesystem. I didn't realize it but there was a very limited amount of space available on the root filesystem and when openshift-ansible tried to cp the `/usr/local/bin/openshift` binary out of the container and into the host, it failed.

```
TASK [openshift_cli : Copy client binaries/symlinks out of CLI image for use on the host] ************************************************************************************************************************
*************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 28] No space left on device
fatal: [45.55.51.130]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/usr/lib64/python3.6/shutil.py\", line 544, in move\n    os.rename(src, real_dst)\nOSError: [Errno 18] Invalid cross-device link: '/tmp/tmp_3v8
ij06/openshift' -> '/usr/local/bin/openshift'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/tmp/ansible_i84p32ax/ansible_module_openshif
t_container_binary_sync.py\", line 134, in <module>\n    main()\n  File \"/tmp/ansible_i84p32ax/ansible_module_openshift_container_binary_sync.py\", line 125, in main\n    binary_syncer.sync()\n  File \"/tmp/an
sible_i84p32ax/ansible_module_openshift_container_binary_sync.py\", line 67, in sync\n    self._sync_binary('openshift')\n  File \"/tmp/ansible_i84p32ax/ansible_module_openshift_container_binary_sync.py\", line
 105, in _sync_binary\n    shutil.move(src_path, dest_path)\n  File \"/usr/lib64/python3.6/shutil.py\", line 558, in move\n    copy_function(src, real_dst)\n  File \"/usr/lib64/python3.6/shutil.py\", line 257, 
in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n  File \"/usr/lib64/python3.6/shutil.py\", line 122, in copyfile\n    copyfileobj(fsrc, fdst)\n  File \"/usr/lib64/python3.6/shutil.py\", line 
82, in copyfileobj\n    fdst.write(buf)\nOSError: [Errno 28] No space left on device\n", 
    "module_stdout": "", 
    "rc": 1
}
```

Ok, so I extended the filesystem and then started openshift-ansible again, but because the binary didn't copy over successfully, subsequent runs would fail because it couldn't run the binary.

```
TASK [openshift_facts : Gather Cluster facts and set is_containerized if needed] *********************************************************************************************************************************
*************************************************************
ok: [159.203.166.219]
ok: [159.203.166.133]
fatal: [45.55.51.130]: FAILED! => {
    "changed": false, 
    "cmd": "/usr/local/bin/openshift version", 
    "failed": true, 
    "rc": 13
}

MSG:

[Errno 13] Permission denied
```

We should probably do some sort of minimum checking on the root filesystem and verify it has some amount of free space (1GiB maybe?).

**Comment by sdodson** [comment]
I think 1GiB is a good baseline for both containerized and rpm based for the root filesystem.

@rhcarvalho do you guys have anything for root fs free space yet?

**Comment by rhcarvalho** [comment]
We do have a check for available disk space that is already integrated with the install flow, but that's for `/var`, as per the documented requirements:

https://docs.openshift.org/latest/install_config/install/prerequisites.html#hardware

We look at the existing mount points, first check `/var` and fallback to `/` if need be:

[roles/openshift_health_checker/openshift_checks/disk_availability.py#L55](https://github.com/openshift/openshift-ansible/blob/897e62c2739fef22d967f184fc0fc694150f4e09/roles/openshift_health_checker/openshift_checks/disk_availability.py#L55)

Now, if the install requires disk space in other mount points, then we should document it and also expand the check to verify other paths.

Looking at [the play that failed](https://github.com/openshift/openshift-ansible/blob/dc12c4b28321e944b2fd3a35241510fd6513fcae/roles/openshift_cli/tasks/main.yml#L13), it seems that for `containerized` installs we copy binaries into `/usr/bin` (probably we could make `oc` a symlink to `openshift` to save space...), and for `non-containerized` we install an RPM (which will also require disk space in other mount points...).

@sdodson thoughts?

---

Apart from this RFE, looks like there's still a bug report in here, we can probably make [roles/openshift_cli/library/openshift_container_binary_sync.py](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_cli/library/openshift_container_binary_sync.py) handle errors and perhaps clean up partially copied files for example.

**Comment by sdodson** [comment]
I think we should document that / must have at least 1GiB free and add a check for it too.

I'll have to check, I don't think we're extracting `openshift` and `oc` both. If we're doing both then yes we should just symlink `oc` to `openshift` to save space.

**Comment by sdodson** [comment]
@rhcarvalho sure thing

**Comment by dustymabe** [comment]
> Make oc a symlink to openshift to save space (currently we docker cp each individually)

I think we already do this:

```
[root@f1 ~]# ls -l /usr/local/bin/
total 248484
lrwxrwxrwx. 1 root root         9 Jun 12 15:33 kubectl -> openshift
lrwxrwxrwx. 1 root root         9 Jun 12 15:33 oadm -> openshift
lrwxrwxrwx. 1 root root         9 Jun 12 15:33 oc -> openshift
-rwxr-xr-x. 1 root root 254445400 May 16 20:07 openshift

```

**Comment by rhcarvalho** [comment]
The disk verification was implemented and is part of the installation flow. The docs PR has been open. Closing this RFE as successfully implemented. Thanks.
