### ISSUE TITLE
Why "OpenIDIdentityProvider" challenge field must be "false" in Inventory file

### ISSUE THREAD

**Issue by lirenjiede** [openshift/openshift-ansible#4417]
#### Description

Hi all guys,
When I change the provider "OpenIDIdentityProvider" challenge field from false to true. I receive a error during install origin openshift by openshift-ansible.

##### Version
* openshift-ansible version: 1.4

##### Steps To Reproduce
change below OpenID auth config chanllenge from **false** to **true**
#OpenID auth
openshift_master_identity_providers=[{"name": "openid_auth", "login": "true", "challenge": "**true**", "kind": "OpenIDIdentityProvider", "client_id": "my_client_id", "client_secret": "my_client_secret", "claims": {"id": ["sub"], "preferredUsername": ["preferred_username"], "name": ["name"], "email": ["email"]}, "urls": {"authorize": "https://myidp.example.com/oauth2/authorize", "token": "https://myidp.example.com/oauth2/token"}, "ca": "my-openid-ca-bundle.crt"}]

and then I meet below issue:
**"failed": true, 
    "msg": "|failed provider OpenIDIdentityProvider does not allow challenge authentication"**

but
after I research openshift origin doc, it allow openid provider challenge field as true

**Comment by sdodson** [comment]
There's a bug for this too.

https://bugzilla.redhat.com/show_bug.cgi?id=1444367

**Comment by lirenjiede** [comment]
@sdodson, got it. thanks a lot.

**Comment by sdodson** [comment]
we'll try to get this fixed soon, if you'd like feel free to open a pr

**Comment by hemmop** [comment]
This bug bit us as well today. Do you have any progress here @sdodson?

**Comment by sdodson** [comment]
/assign michaelgugino
Can you take a look at updating this IDP it's in the translate_idps function

**Comment by michaelgugino** [comment]
This is fixed now.https://github.com/openshift/openshift-ansible/pull/6046
