### ISSUE TITLE
Origin metrics and logging update from 1.4.1 to 1.5.1 missing requirement check for keytool and python passlib

### ISSUE THREAD

**Issue by jantzen05** [openshift/openshift-ansible#4421]
#### Description
Upgrading from 1.4.1 to 1.5.1 for metrics and logging failed bacause java keytool isn't installed.

##### Version
ansible 2.3.1.0
openshift-ansible-3.5.72-1

openshift-ansible/playbooks/byo/openshift-cluster/openshift-logging.yml or 
openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.yml

##### Steps To Reproduce
1. run one of the above mentioned playbooks

##### Observed Results
Failed during certificate creation

Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by go-faustino** [comment]
I'm having the same problem. 

Keytool is available within the jre bin directory on my hosts, but I still haven't been able to get it to work changing the PATH.

**Comment by ewolinetz** [comment]
Keytool is required to be available on your control host [1]. We should update the role docs to specify this

[1] https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging/tasks/generate_jks.yaml#L62
