### ISSUE TITLE
Origin logging update from 1.4.1 to 1.5.1 not setting OAP_PUBLIC_MASTER_URL or OAP_LOGOUT_REDIRECT in kibana

### ISSUE THREAD

**Issue by jantzen05** [openshift/openshift-ansible#4423]
#### Description
Trying to access logging through kibana after upgrade failed and I was sent to host name of the server the upgrade script was run from.

##### Version

Please put the following version information in the code block
indicated below.

ansible 2.3.1.0
openshift-ansible-3.5.72-1

openshift-ansible/playbooks/byo/openshift-cluster/openshift-logging.yml

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. Start on first master in a cluster install.
2. run openshift-ansible/playbooks/byo/openshift-cluster/openshift-logging.yml
3. oc edit dc/logging-kibana or/and dc/logging-kibana-ops
4. validate that OAP_PUBLIC_MASTER_URL and OAP_LOGOUT_REDIRECT does not have machine hostname.

##### Expected Results
I expected that OAP_PUBLIC_MASTER_URL and OAP_LOGOUT_REDIRECT had the same url as openshift_logging_public_master_url define on the ansible hosts file.

##### Observed Results
I saw that the value in OAP_PUBLIC_MASTER_URL and OAP_LOGOUT_REDIRECT was local server name.
I was enabled to login and route from my paas url to a local servername url.

Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by xelfe** [comment]
Same issue here. Kibana expect my master url instead of my public one. Only thing I found is that OAP_PUBLIC_MASTER_URL is set to master.

**Comment by ewolinetz** [comment]
Can you please provide the logging specific variables you provided in your inventory file as part of the upgrade?

**Comment by jantzen05** [comment]
Just had the same issue during upgrade from 3.5 to 3.6.
`openshift_logging_install_logging="true"
openshift_logging_image_prefix="x.x.x.x/openshift/origin-"
openshift_logging_image_version="v3.6.0"
openshift_logging_namespace="logging"
openshift_logging_use_ops="true"
openshift_logging_master_url="https://kubernetes.default.svc.cluster.local"
openshift_logging_public_master_url="https://paas-api-test"
openshift_logging_curator_default_days=14
openshift_logging_curator_run_hour=0
openshift_logging_curator_run_minute=0
openshift_logging_curator_run_timezone="UTC"
openshift_logging_curator_script_log_level="INFO"
openshift_logging_curator_log_level="ERROR"
openshift_logging_curator_memory_limit="1G"
openshift_logging_curator_nodeselector={"role": "infrastructure"}
openshift_logging_curator_ops_memory_limit="1G"
openshift_logging_curator_ops_nodeselector={"role": "infrastructure"}
openshift_logging_kibana_hostname="logging-test"
openshift_logging_kibana_replica_count=2
openshift_logging_kibana_memory_limit="4G"
openshift_logging_kibana_proxy_memory_limit="1G"
openshift_logging_kibana_nodeselector={"role": "infrastructure"}
openshift_logging_kibana_ops_hostname="logging-ops-test"
openshift_logging_kibana_ops_replica_count=2
openshift_logging_kibana_ops_memory_limit="4G"
openshift_logging_kibana_ops_proxy_memory_limit="1G"
openshift_logging_kibana_ops_nodeselector={"role": "infrastructure"}
openshift_logging_fluentd_nodeselector={"logging-infra-fluentd": "true"}
openshift_logging_es_cluster_size=4
openshift_logging_es_memory_limit="12G"
openshift_logging_es_recover_after_time="5m"
openshift_logging_es_nodeselector={"role": "infrastructure"}
openshift_logging_es_ops_cluster_size=4
openshift_logging_es_ops_memory_limit="8G"
openshift_logging_es_ops_recover_after_time="5m"
openshift_logging_es_ops_nodeselector={"role": "infrastructure"}
openshift_logging_es_ops_allow_cluster_reader="true"
`

**Comment by patlachance** [comment]
Have a look at https://access.redhat.com/solutions/3605061
