### ISSUE TITLE
Named Certificate causes cert generation to fail.

### ISSUE THREAD

**Issue by cameron-scrace** [openshift/openshift-ansible#4442]
When installing openshift via ansible with a named certificate defined in the ansible hosts file the openshift certs are not created correctly. The cacert for the named cert is being added to /etc/origin/master/ca.crt instead of just /etc/origin/master/ca-bundle.crt. This is causing /etc/origin/master/ca.crt and /etc/origin/master/ca.key to mismatch which results in a failed install with the error: tls: private key does not match public key.

```
ansible --version
ansible 2.3.0.0

git describe
openshift-ansible-3.6.100-1-25-g1720a52
```

##### Steps To Reproduce
1. Create ansible hosts file that defines a named certificate with a cacert.
2. Run ansible playbook.

##### Expected Results
Openshift installs successfully.

##### Observed Results
Openshift fails to install due to ca.crt and ca.key not matching.

```
error: tls: private key does not match public key
```

**Comment by abutcher** [comment]
@cameron-scrace Could you share your inventory and in particular any certificate related variables?

**Comment by cameron-scrace** [comment]
openshift_master_named_certificates=[{"certfile": "/root/certs/named-server.crt", "keyfile": "/root/certs/named-server.key", "names": ["openshift.<company name>.com"], "cafile": "/root/certs/named-ca.crt"}]
openshift_master_overwrite_named_certificates=true

As a work around I waited for the install to fail, then manually edited the generated /etc/origin/master/ca.crt and ran it again.

**Comment by abessifi** [comment]
@cameron-scrace @abutcher  it seems that this issue still exists even in openshift 3.11.104.

>As a work around I waited for the install to fail, 
>then manually edited the generated /etc/origin/master/ca.crt and ran it again.
Unfortunately the ansible overwrite the ca.crt each time it's ran.

Please any other workaround ?

**Comment by npoyant** [comment]
Confirmed this is occurring in 3.11.117 as well

**Comment by edcrosbys** [comment]
Issue still occurs in 3.11.117. Worked around it by copying ca-bundle over ca. Had this running on masters:

**Comment by edcrosbys** [comment]
Ran this script this on the masters as a workaround while the installer ran:
`#!/bin/bash
bundle=/etc/origin/master/ca-bundle.crt
cert=/etc/origin/master/ca.crt
while true
do
    if [[ -f ${bundle} && -f ${cert} ]]
    then
    	bundle_cksum=`cksum ${bundle}|awk '{print $1}'`
    	cert_cksum=`cksum ${cert}|awk '{print $1}'`
        echo "cksums are ${bundle_cksum} ${cert_cksum} "
    	if  [[ ${bundle_cksum} -ne ${cert_cksum} ]]
    	then
      	 cp ${bundle} ${cert}
    	fi
    fi
    sleep 20
done
`

**Comment by edcrosbys** [comment]
You have to wait for the initial install to fail before copying the files over each other. Otherwise, you will get an error that only one certificate is expected in ca.crt.

**Comment by arocki7** [comment]
Use the official openshift-ansible RPM, it works fine there.

**Comment by arocki7** [comment]
If you have your 'cafile' name as 'ca.crt', please change to something like 'custom_ca.crt'. Because the playbook just copies your named_certificate CA into /etc/origin/master/. If you use the same name as openshift self-signer, it's going to overwrite it.

**Comment by spasche** [comment]
I can confirm that renaming the 'cafile' to something other than 'ca.crt' fixes the issue. Thanks @arocki7 !

**Comment by trelo-bifteki** [comment]
Thanks @arocki7 for the suggestion. I have been troubling myself with this issue for two weeks!
