### ISSUE TITLE
Why does logging have "openshift_logging_master_public_url" and "openshift_master_logging_public_url"?

### ISSUE THREAD

**Issue by portante** [openshift/openshift-ansible#4454]
Why does logging have `openshift_logging_master_public_url` and `openshift_master_logging_public_url`?  I cannot find `openshift_master_logging_public_url` documented anywhere, but yet I find it currently at https://github.com/openshift/openshift-ansible/blob/0ee812822a5fe5ba7cc00d00c58744104c2d9fee/roles/openshift_master_facts/tasks/main.yml#L48.

**Comment by patlachance** [comment]
This is the redirect URL used to authenticate the user accessing the Kibana UI.
