### ISSUE TITLE
Formatting or formatting option not supported for file format 'qcow2'

### ISSUE THREAD

**Issue by screeley44** [openshift/openshift-ansible#448]
since the vbox scenario didn't work, thought I would give libvirt a try...my host is a rhel 6.5 system and when vagrant uses the libvirt provider, I get this error on the qemu-img create.  Is there any way around this, I haven't found one that works yet?

[root@screeley openshift-ansible (master)]# vagrant up --provider=libvirt --no-provision
Bringing machine 'node1' up with 'libvirt' provider...
Bringing machine 'node2' up with 'libvirt' provider...
Bringing machine 'master' up with 'libvirt' provider...
==> node1: Creating image (snapshot of base box volume).
==> node1: An error occurred. The error will be shown after all tasks complete.
==> node2: Creating image (snapshot of base box volume).
==> master: Creating image (snapshot of base box volume).
==> node2: An error occurred. The error will be shown after all tasks complete.
==> master: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error occurred when executing the action on the
'node1' machine. Please report this as a bug:

Call to virNetworkCreateXML failed: internal error Child process (/usr/bin/qemu-img create -f qcow2 -b /VirtualMachines/centos-7.1_vagrant_box_image_0.img -o backing_fmt=qcow2 /VirtualMachines/openshift-ansible_node1.img 41943040K) unexpected exit status 1: '' uses a qcow2 feature which is not supported by this qemu version: QCOW version 3
Formatting or formatting option not supported for file format 'qcow2'

/root/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume_xml'
/root/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/create_volume.rb:6:in`create_volume'
/root/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/models/compute/volume.rb:40:in `save'
/root/.vagrant.d/gems/gems/fog-core-1.32.0/lib/fog/core/collection.rb:51:in`create'
/root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/create_domain_volume.rb:43:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in`call'
/root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:42:in `block in call'
/root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:40:in`synchronize'
/root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:40:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in`call'
/root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:24:in `block in call'
/root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:17:in`synchronize'
/root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:17:in `call

**Comment by detiber** [comment]
@screeley44 I believe we merged a change previously that required a newer version of libvirt than is provided by RHEL 6.  This should work under RHEL7 or Fedora.

We'd be open to PRs that would allow it to work under RHEL6 as well. I don't expect adding that support will be high on our priority list for a while (especially since bin/cluster is mainly provided as a convenience).

**Comment by screeley44** [comment]
@detiber - thanks for the response, and yeah, might be good to keep on the back burner, understand it won't be high priority but might be useful at some point for someone, was just giving it a shot to see what would happen.  wonder how hard it is to update libvirt with out completely hosing my system...I'll look into that :-)

**Comment by detiber** [comment]
@screeley44 I suspect updating libvirt on a RHEL 6 system would be difficult.

https://github.com/openshift/openshift-ansible/pull/234 was the PR that introduced the change that broke things for RHEL6, previously we were doing some ugly inspection of the arp cache to try to determine the guest vm IP addresses.

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.
