### ISSUE TITLE
Kubectl conflicts with file from other package

### ISSUE THREAD

**Issue by dtpest** [openshift/openshift-ansible#4487]
I'm trying to deploy Openshift Origin on Amazon AWS.
But getting the following error:
----------------------------------------------------------------
Transaction check error:
  file /usr/bin/kubectl from install of origin-clients-1.5.1-1.el7.x86_64 conflicts with file from package kubernetes-client-1.5.2-0.6.gitd33fd89.el7.x86_64
  file /usr/bin/kube-apiserver from install of origin-1.5.1-1.el7.x86_64 conflicts with file from package kubernetes-master-1.5.2-0.6.gitd33fd89.el7.x86_64
  file /usr/bin/kube-controller-manager from install of origin-1.5.1-1.el7.x86_64 conflicts with file from package kubernetes-master-1.5.2-0.6.gitd33fd89.el7.x86_64
  file /usr/bin/kube-scheduler from install of origin-1.5.1-1.el7.x86_64 conflicts with file from package kubernetes-master-1.5.2-0.6.gitd33fd89.el7.x86_64
  file /usr/bin/kube-proxy from install of origin-1.5.1-1.el7.x86_64 conflicts with file from package kubernetes-node-1.5.2-0.6.gitd33fd89.el7.x86_64
  file /usr/bin/kubelet from install of origin-1.5.1-1.el7.x86_64 conflicts with file from package kubernetes-node-1.5.2-0.6.gitd33fd89.el7.x86_64
----------------------------------------------------------------

Using the follwing settings:
----------------------------------------------------------------
export AWS_ACCESS_KEY_ID='XXXXXXXXX'
export AWS_SECRET_ACCESS_KEY='XXXXXXXXXXX'

export ec2_instance_type='m4.large'
export ec2_master_instance_type='m3.medium'
export ec2_security_groups="['openshift']"
export ec2_assign_public_ip='false'
export ec2_region='us-east-1'
export ec2_image='ami-d20d16ba'
export ec2_keypair='XXXXXXXXXXXXXXX'
export ec2_vpc_subnet='subnet-XXXXXXXXXX'

export os_etcd_root_vol_size='20'
export os_etcd_root_vol_type='standard'
export os_etcd_vol_size='20'
export os_etcd_vol_type='standard'
export os_master_root_vol_size='20'
export os_master_root_vol_type='standard'
export os_node_root_vol_size='15'
export os_docker_vol_size='50'
export os_docker_vol_ephemeral='false'

----------------------------------------------------------------

##### Version

Please put the following version information in the code block
indicated below.

Your ansible version per `ansible --version`
ansible 2.3.0.0 

If you're operating from a git clone:

The output of `git describe`
openshift-ansible-3.6.99-1-2-gdc12c4b

##### Steps To Reproduce
bin/cluster -v create -n=2 -t=origin aws cluster-test

##### Expected Results
Provisioned Openshift Cluster on Amazon AWS

**Comment by ingvagabund** [comment]
@dtpest are you deploying the OpenShift on vanilla new cluster? It says the kubernetes-client-1.5.2-0.6.gitd33fd89.el7.x86_64 is installed. It should not be. If it is intended, you should remove the `kubernetes-client` before proceeding.

**Comment by ingvagabund** [comment]
Can you share the full ansible log?

**Comment by dtpest** [comment]
@ingvagabund It is a plain vanilla new cluster!
As you can see above I'm using a different AMI, maybe there is already something installed.
Because with the default AMI it does work.

**Comment by ingvagabund** [comment]
@jhadvig you know the AMI stuff more than I do :P
