### ISSUE TITLE
etcd advertise should use hostname instead of IP when using proxy

### ISSUE THREAD

**Issue by adrianlzt** [openshift/openshift-ansible#4490]
#### Description

etcd ``ETCD_ADVERTISE_CLIENT_URLS`` is configured with the [ip of etcd the hosts](https://github.com/openshift/openshift-ansible/blob/4cd57c9d9f2ed4838f7dceed36cd48b418b5f2f3/roles/etcd/defaults/main.yaml#L7) instead of the hostnames.

If master-controllers are configured with ``HTTPS_PROXY`` and ``NO_PROXY``, it will make the first connection (using the hostname stored in the master config) correctly avoiding the proxy (as configured in NO_PROXY) but then fails when tries to connect to the IP (not defined in the ``NO_PROXY`` env).

The obvious workaround is to define the IPs of the etcd hosts in the ``openshift_no_proxy`` ansible var.

##### Version

```
ansible 2.2.1.0
atomic-openshift-utils-3.5.60-1.git.0.b6f77a6.el7.noarch
openshift-ansible-3.5.60-1.git.0.b6f77a6.el7.noarch
```

##### Steps To Reproduce
1. Configure OpenShift with ``HTTP_PROXY`` and ``NO_PROXY``
2. Check logs in atomic-openshift-master-controllers.service showing errors

##### Expected Results
etcd configured with hostnames to match NO_PROXY

##### Observed Results
Describe what is actually happening.

```
# journalctl -u atomic-openshift-master-controllers.service
Jun 17 15:45:50 xxx atomic-openshift-master-controllers[28739]: E0617 15:45:50.988458   28739 leaderlease.go:95] unable to check lease openshift.io/leases/controllers: Forbidden
Jun 17 15:45:51 xxx atomic-openshift-master-controllers[28739]: E0617 15:45:51.727956   28739 leaderlease.go:87] client: etcd cluster is unavailable or misconfigured; error #0: Forbidden
Jun 17 15:45:51 xxx atomic-openshift-master-controllers[28739]: ; error #1: Forbidden
Jun 17 15:45:51 xxx atomic-openshift-master-controllers[28739]: ; error #2: Forbidden
```

##### Additional Information

```
Red Hat Enterprise Linux Server release 7.3 (Maipo)

hosts:
openshift_http_proxy=proxy:6666
openshift_https_proxy=proxy:6666
openshift_no_proxy=.internal.domain
```

**Comment by sdodson** [comment]
Yeah, we to fix this, we should make sure that the certs are signed appropriately and for some reason I thought that etcd was moving to always use IPs.

https://bugzilla.redhat.com/show_bug.cgi?id=1458660 related
