### ISSUE TITLE
Running openshift install playbook does not specify the version

### ISSUE THREAD

**Issue by jhadvig** [openshift/openshift-ansible#4511]
Running openshift install playbook does not specify the atomic-openshift(since I am installing enterprise) version, for which [aos_version.py](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_health_checker/library/aos_version.py) is reponsible even though Im specifying the `openshift_pkg_version` env variable
```
        "package_version": {
            "failed": true, 
            "invocation": {
                "module_args": {
                    "package_list": [
                        {
                            "check_multi": false, 
                            "name": "openvswitch", 
                            "version": "2.6"
                        }, 
                        {
                            "check_multi": false, 
                            "name": "docker", 
                            "version": "1.12"
                        }, 
                        {
                            "check_multi": true, 
                            "name": "atomic-openshift", 
                            "version": ""
                        }, 
                        {
                            "check_multi": true, 
                            "name": "atomic-openshift-master", 
                            "version": ""
                        }, 
                        {
                            "check_multi": true, 
                            "name": "atomic-openshift-node", 
                            "version": ""
                        }
                    ]
                }
            }, 
            "msg": "Multiple minor versions of these packages are available\n  atomic-openshift\n  atomic-openshift-master\n  atomic-openshift-node\nThere should only be one OpenShift release repository enabled at a time."
        }
```

Here is the whole log of the [job](https://ci.openshift.redhat.com/jenkins/view/All/job/continuous-upgrade_provision-job/20/console) where Im installing openshift with `config.yml` playbook. I'm lauching the play with:

```
ansible-playbook  -vv          \
          --become           \
          --become-user root \
          --connection local \
          --inventory sjb/inventory/ \
          /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml \
          -e etcd_data_dir="/tmp/etcd"                                  \
          -e deployment_type="openshift-enterprise"                     \
          -e openshift_pkg_version="-3.6.116-1.git.0.07bb1f5.el7" \
          -e oreg_url='registry.ops.openshift.com/openshift3/ose-\${component}:\${version}' \
          -e openshift_docker_additional_registries="registry.ops.openshift.com"
```

@sosiouxme @rhcarvalho I saw that you have been working on the https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_health_checker/library/aos_version.py . Can you pls take a look cause it looks that the "version"  in the "package_list" is not getting the version of openshift that shall be installed ... or am I missing something ?

**Comment by sosiouxme** [comment]
@jhadvig when you are installing OCP, it is expecting repos to be set up as customers would see them, with one minor release (ose-3.x) per version. Instructions for an install or upgrade are to only enable the one that you're using, so the check considers it a problem if the same RPM is available with two different minor versions (e.g. 3.5 and 3.6). It may not actually be a problem, i.e. the install may proceed just fine, but it's a bit of a red flag that you need to clean up your config, and possibly an indication that you're getting something you didn't expect by having extra repos enabled.

Now, it's not obvious to me what your setup is here, but I'm guessing maybe you just have a single repo where you keep adding in updated versions of `atomic-openshift*`. If that's the environment you need to work in, I'd say it's acceptable to disable this check as the output advises (just as the check is inactive for Origin where we expect every version ever is in one repo).
