### ISSUE TITLE
docker installed before docker-excluder

### ISSUE THREAD

**Issue by ingvagabund** [openshift/openshift-ansible#4523]
In order to detect currently available OCP version during containerized deployment one needs to run `openshift_version` role. Given the version is available inside a docker image, one needs to run corresponding image, thus install `docker` rpms. Since the version detection is carried before the `docker-excluder` rpm is installed, one can install `docker` rpms of a version that is excluded by the `docker-excluder`. E.g. in 3.3 deployment one gets `docker-1.12*` installed instead of `docker-1.10*`.

At the same time in order to install the `docker-excluder` one needs to know OCP version (otherwise OpenShift rpms and OpenShift docker images version can differ).

Potential ways how to fix it?
* install docker, detect version, uninstall docker (if its version is not the expected one)
* install the latest docker-excluder available at the beginning, detect the OCP version, then reinstall (e.g. distro-sync) the docker-excluder to the proper version based on the detected OCP version.
* set the `docker_version` variable in the inventory file
* implement different mechanism to detect the containerized OCP version

**Comment by sdodson** [comment]
Sounds like we should just hardcode docker_version and openshift_release in the 3.2, 3.3, 3.4, and 3.5 playbooks to appropriate values for those releases. Only do this for openshift-enterprise.

**Comment by ingvagabund** [comment]
@jhadvig will this cause a trouble to the CI infra?
