### ISSUE TITLE
Support configuring the CFME application image name

### ISSUE THREAD

**Issue by simon3z** [openshift/openshift-ansible#4557]
#### Description

The support to configure the `openshift_cfme_container_image` is missing (see `playbooks/common/openshift-cfme/config.yml`):

```yaml
---
# TODO: Make this work. The 'name' variable below is undefined
# presently because it's part of the cfme role. This play can't run
# until that's re-worked.
```

cc @sdodson 

##### Version

```
ansible 2.2.2.0
  config file = /home/simon/src/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

```
openshift-ansible-3.6.123-1
```

##### Expected Results
It should be possible to configure the `openshift_cfme_container_image`.

##### Observed Results
The template is deployed always with the same image name (`docker.io/manageiq/manageiq-pods:app-latest-fine`).

**Comment by simon3z** [comment]
cc @gtanzillo @bazulay @fbladilo

**Comment by ilackarms** [comment]
@simon3z I was able to set `openshift_cfme_container_image` in my hosts file:
```
[OSEv3:vars]
#...
openshift_cfme_application_img_name=docker.io/ilackarms/manageiq-pods
openshift_cfme_application_img_tag=app-latest-fine
```

After running `openshift-cfme` playbook, I can see that manageiq pods are deployed using the configured image:

```
# ssh openshift-host-master -- oc describe pod manageiq-0 -n cfme
Name:                   manageiq-0
Namespace:              cfme
Security Policy:        privileged
Node:                   /
Labels:                 name=manageiq
Status:                 Pending
IP:
Controllers:            StatefulSet/manageiq
Containers:
  manageiq:
    Image:      docker.io/ilackarms/manageiq-pods:app-latest-fine
#...
```

Am I missing something that isn't using the user-configured value for `openshift_cfme_application_img_name` ?
