### ISSUE TITLE
Support Amazon PVs for CFME application

### ISSUE THREAD

**Issue by simon3z** [openshift/openshift-ansible#4567]
#### Description

It should be possible to use Amazon storage to deploy CFME.

cc @sdodson @tbielawa @fbladilo @gtanzillo @bazulay

##### Version

```
ansible 2.2.2.0
  config file = /home/simon/src/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

```
openshift-ansible-3.6.123-1
```

##### Expected Results
It should be possible to use Amazon storage (disabling nfs) to deploy CFME.

##### Observed Results
Currently the only storage supported is nfs.

**Comment by simon3z** [comment]
@joelddiaz if you have time you could start using the CFME role here in openshift-ansible.

I am not sure how hard would be this to workaround/fix. Maybe @sdodson and @tbielawa can help us to get this done.

cc @bazulay

**Comment by joelddiaz** [comment]
@simon3z i tried running through the CFME role from a current openshift-ansible checkout, and it eventually failed for me while setting up the NFS bits:

TASK [openshift_cfme : Ensure the CFME DB PV template is evaluated] ************
Monday 24 July 2017  19:47:32 +0000 (0:00:02.527)       0:44:50.727 *********** 
fatal: [13.59.190.128]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: {{ groups.nfs.0 }}: 'dict object' has no attribute 'nfs'"}

**Comment by simon3z** [comment]
> @simon3z i tried running through the CFME role from a current openshift-ansible checkout, and it eventually failed for me while setting up the NFS bits:

@ilackarms can you check what does it take to disable NFS? Can you work with @joelddiaz to see what other issues he'll encounter after that?

BTW @sdodson was looking into adding the support for an external db (RDS): https://trello.com/c/VzQZvtcg/469-add-external-database-support-to-cfme-role

We need that as well once we hashed out these other issues.

**Comment by ilackarms** [comment]
@simon3z what are we currently using NFS for? I see that it's required according to the installation docs for openshift-ansible

**Comment by ilackarms** [comment]
@simon3z i take Amazon storage to refer to EFS (the closest thing in their storage portfolio to NFS)?

**Comment by ilackarms** [comment]
disabling `openshift-nfs` should be as simple as removing the `openshift-nfs` section from [openshift-cluster/config.yml]

note that this dependency is used by 66 playbooks, although it's unclear how many actually require nfs to run successfully.

i'll try a local test and see what breaks

**Comment by ilackarms** [comment]
simpler way of 'disabling' nfs is to specify no `[nfs]` nodes in the hosts file.

running the cfme role without any nfs nodes causes it to quickly error looking for 
`openshift_cfme_nfs_server: "{{ groups.nfs.0 }}"`: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_cfme/defaults/main.yml#L30

**Comment by ilackarms** [comment]
there are two possible routes for supporting Amazon PVs (backed by AWS EBS Volumes):
1 - Static Provisioning
2 - Dynamic Provisioning

Using the static provisioning route, users will specify EBS volumes by id that are created prior to running the cfme playbook

The Dynamic Provisioning route is more complex. It will require a StorageClass to be created (see https://github.com/openshift/openshift-ansible/blob/master/playbooks/common/openshift-cluster/openshift_hosted.yml#L30), and the pods requiring PVs will need to request dynamically provisioned storage (basically just uncomment https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_cfme/files/miq-template.yaml#L195).

The goal in either case here is to stop hard-coding the use and creation of NFS-backed PVs. We will want to turn the (`miq-template.yml`](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_cfme/files/miq-template.yaml) into a `j2` template where we can switch between using `nfs` or `amazon` based on user-provided variables (in particular if openshift_cloudprovider_kind == 'aws'). In the case of NFS, keep things how they are. In the case of AWS, we will need some other variables from the user (either static volume ids for static provisioning, or storageconfig parameters for dynamic provisioning)

**Comment by j00p34** [comment]
default StorageClass is actually automatically created in the latest setup. I have just run the unmodified miq-template.yml from  https://github.com/ManageIQ/manageiq-pods/blob/master/templates/miq-template.yaml without nfs and without creating PV's and it works out of the box on Amazon with dynamic provisioning of ebs storage.

my setup:
OpenShift Master:
v3.6.0-rc.0+8ef052d-472
Kubernetes Master:
v1.7.0+695f48a16f

Just making nfs setup optional would probably be enough to make this work. The StorageClass is a default class and will be selected automatically. I don't think https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_cfme/files/miq-template.yaml#L195 is needed unless you would want to use a non default StorageClass instead.

**Comment by ilackarms** [comment]
@j00p34 so volumes matching persistent volume claims will automatically be provisioned? Can we remove all the manual NFS-provisioning code, and allow storage volumes to be provisioned dynamically from NFS storage class?

**Comment by j00p34** [comment]
@ilackarms sorry for the late response. I went on vacation right before your post. I did not test this with nfs but I guess it works if you have your storage class properly configured. You probably found that out yourself by now :)

**Comment by ilackarms** [comment]
@j00p34 i think there's no provisioner for nfs storage that is 
1 - available OOB with openshift
2 - configured by Openshift-Ansible

I saw that https://github.com/kubernetes-incubator/nfs-provisioner is (was) a thing; so I think you can add such a provisioner to Openshift, but it's not available OOB.
