### ISSUE TITLE
Logging-cluster enable fails in Elasticsearch's pod!

### ISSUE THREAD

**Issue by maiconbaumx** [openshift/openshift-ansible#4595]
Hello guys!
I'm getting this error when I try to enable logging-cluster with ansible, in the Elasticsearch's pod:

![screen shot 2017-06-26 at 20 33 55](https://user-images.githubusercontent.com/15946206/27564595-34561676-5aaf-11e7-9cde-de4251a4a454.png)

Consecutively, the rest of the stack fails. :/ 
Anyone have an idea?

**Comment by ewolinetz** [comment]
@maiconbaumx can you provide the output of  `oc get configmap/logging-elasticsearch -n logging -o yaml`?

**Comment by maiconbaumx** [comment]
@ewolinetz Sure!
Here:


apiVersion: v1
data:
  elasticsearch.yml: |
    cloud:
        kubernetes:
            namespace: ${NAMESPACE}
            service: ${SERVICE_DNS}
    cluster:
        name: ${CLUSTER_NAME}
    discovery:
        type: kubernetes
        zen.minimum_master_nodes: 1
        zen.ping.multicast.enabled: false
    gateway:
        expected_master_nodes: ${NODE_QUORUM}
        expected_nodes: ${RECOVER_EXPECTED_NODES}
        recover_after_nodes: ${RECOVER_AFTER_NODES}
        recover_after_time: ${RECOVER_AFTER_TIME}
    index:
        number_of_replicas: 0
        number_of_shards: 1
        translog:
            flush_threshold_period: 5m
            flush_threshold_size: 256mb
        unassigned.node_left.delayed_timeout: 2m
    io.fabric8.elasticsearch.authentication.users:
    - system.logging.kibana
    - system.logging.fluentd
    - system.logging.curator
    - system.admin
    io.fabric8.elasticsearch.kibana.mapping.app: /usr/share/elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
    io.fabric8.elasticsearch.kibana.mapping.ops: /usr/share/elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
    network:
        host: 0.0.0.0
    node:
        data: true
        master: true
    openshift.config:
        project_index_prefix: project
        time_field_name: '@timestamp'
        use_common_data_model: true
    openshift.operations.allow_cluster_reader: false
    openshift.searchguard:
        keystore.path: /etc/elasticsearch/secret/admin.jks
        truststore.path: /etc/elasticsearch/secret/searchguard.truststore
    path:
        data: /elasticsearch/persistent/${CLUSTER_NAME}/data
        logs: /elasticsearch/${CLUSTER_NAME}/logs
        scripts: /elasticsearch/${CLUSTER_NAME}/scripts
        work: /elasticsearch/${CLUSTER_NAME}/work
    script:
        indexed: true
        inline: true
    searchguard:
        authcz.admin_dn:
        - CN=system.admin,OU=OpenShift,O=Logging
        config_index_name: .searchguard.${HOSTNAME}
        ssl:
            http:
                clientauth_mode: OPTIONAL
                enabled: true
                keystore_filepath: /etc/elasticsearch/secret/key
                keystore_password: kspass
                keystore_type: JKS
                truststore_filepath: /etc/elasticsearch/secret/truststore
                truststore_password: tspass
                truststore_type: JKS
            transport:
                enabled: true
                enforce_hostname_verification: false
                keystore_filepath: /etc/elasticsearch/secret/searchguard.key
                keystore_password: kspass
                keystore_type: JKS
                truststore_filepath: /etc/elasticsearch/secret/searchguard.truststore
                truststore_password: tspass
                truststore_type: JKS
  logging.yml: |
    # you can override this using by setting a system property, for example -Des.logger.level=DEBUG
    es.logger.level: INFO
    rootLogger: ${es.logger.level}, file
    logger:
      # log action execution errors for easier debugging
      action: WARN

      # deprecation logging, turn to DEBUG to see them
      deprecation: WARN, deprecation_log_file

      # reduce the logging for aws, too much is logged under the default INFO
      com.amazonaws: WARN

      io.fabric8.elasticsearch: ${PLUGIN_LOGLEVEL}
      io.fabric8.kubernetes: ${PLUGIN_LOGLEVEL}

      # aws will try to do some sketchy JMX stuff, but its not needed.
      com.amazonaws.jmx.SdkMBeanRegistrySupport: ERROR
      com.amazonaws.metrics.AwsSdkMetrics: ERROR

      org.apache.http: INFO

      # gateway
      #gateway: DEBUG
      #index.gateway: DEBUG

      # peer shard recovery
      #indices.recovery: DEBUG

      # discovery
      #discovery: TRACE

      index.search.slowlog: TRACE, index_search_slow_log_file
      index.indexing.slowlog: TRACE, index_indexing_slow_log_file

      # search-guard
      com.floragunn.searchguard: WARN

    additivity:
      index.search.slowlog: false
      index.indexing.slowlog: false
      deprecation: false

    appender:
      console:
        type: console
        layout:
          type: consolePattern
          conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %.10000m%n"

      file:
        type: dailyRollingFile
        file: ${path.logs}/${cluster.name}.log
        datePattern: "'.'yyyy-MM-dd"
        layout:
          type: pattern
          conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
      deprecation_log_file:
        type: dailyRollingFile
        file: ${path.logs}/${cluster.name}_deprecation.log
        datePattern: "'.'yyyy-MM-dd"
        layout:
          type: pattern
          conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

      index_search_slow_log_file:
        type: dailyRollingFile
        file: ${path.logs}/${cluster.name}_index_search_slowlog.log
        datePattern: "'.'yyyy-MM-dd"
        layout:
          type: pattern
          conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

      index_indexing_slow_log_file:
        type: dailyRollingFile
        file: ${path.logs}/${cluster.name}_index_indexing_slowlog.log
        datePattern: "'.'yyyy-MM-dd"
        layout:
          type: pattern
          conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
          
kind: ConfigMap
metadata:
  creationTimestamp: 2017-06-27T21:05:41Z
  name: logging-elasticsearch
  namespace: logging
  resourceVersion: "37147"
  selfLink: /api/v1/namespaces/logging/configmaps/logging-elasticsearch
  uid: 60b93a1c-5b7c-11e7-b87d-061b5159fc30

**Comment by jcantrill** [comment]
@maiconbaumx  not sure what version of the openshift-ansible code base you are using but this was fixed quite awhile ago: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging_elasticsearch/templates/elasticsearch.yml.j2#L43  and can be resolved by adding the one line to your config file.

**Comment by maiconbaumx** [comment]
I'll try this @jcantrill!
Actually I'm using Origin 1.5

**Comment by maiconbaumx** [comment]
@jcantrill my previous problem was solved with your help, thanks! Now I have a problem with Kibana Proxy container.. The Kibana's POD crashes with this log in Kibana Proxy's container:








 BYTES_PER_MEG=1048576
+ BYTES_PER_GIG=1073741824
+ DEFAULT_MIN=67108864
+ export NODE_OPTIONS=
+ echo 2Gi
+ grep -qE ^([[:digit:]]+)([GgMm])?i?$
+ grep -oE ^[[:digit:]]+
+ echo 2Gi
+ num=2
+ + grep -oE [GgMm]
echo 2Gi
Using NODE_OPTIONS: '--max-old-space-size=2048' Memory setting is in MB
Running from directory: '/opt/openshift-auth-proxy'
+ unit=G
+ [ G = G ]
+ num=2147483648
+ [ 2147483648 -lt 67108864 ]
+ NODE_OPTIONS=--max-old-space-size=2048
+ export NODE_OPTIONS
+ cd /opt/openshift-auth-proxy
+ echo Using NODE_OPTIONS: '--max-old-space-size=2048' Memory setting is in MB
+ pwd
+ echo Running from directory: '/opt/openshift-auth-proxy'
+ exec node --max-old-space-size=2048 /usr/local/bin/npm start
> openshift-auth-proxy@0.0.24 start /opt/openshift-auth-proxy
> node openshift-auth-proxy.js
fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'secret/oauth-secret'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.<anonymous> (/opt/openshift-auth-proxy/lib/config.js:157:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/openshift-auth-proxy/openshift-auth-proxy.js:6:22)
npm ERR! Linux 3.10.0-514.16.1.el7.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.36
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE
npm ERR! openshift-auth-proxy@0.0.24 start: `node openshift-auth-proxy.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the openshift-auth-proxy@0.0.24 start script 'node openshift-auth-proxy.js'.
npm ERR! This is most likely a problem with the openshift-auth-proxy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node openshift-auth-proxy.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls openshift-auth-proxy
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.10.0-514.16.1.el7.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.36
npm ERR! npm  v2.7.0
npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>;
npm ERR! Please include the following file with any support request:
npm ERR! /opt/openshift-auth-proxy/npm-debug.log 





Any idea? :/

**Comment by jcantrill** [comment]
This is because the proxy now requires the secrets to be specified as env vars coming into the container on the DC.  Either:
1. There is a bug in the release-1.5 of ansible
2. You have an old origin-ansible

Your DC should have something like the following in it: https://github.com/openshift/openshift-ansible/blob/release-1.5/roles/openshift_logging/templates/kibana.j2#L109-L122

**Comment by maiconbaumx** [comment]
@jcantrill thank you so much!
Everything works fine now, after your help.
