### ISSUE TITLE
docker_image_availability check is broken for images based on prerelease deployments

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#4608]
The check is incorrect - it's 

1. using the wrong image (should be using v3.6.0-alpha.2, which comes from the binary)
2. should have reported those as found

It is completely valid to install from prerelease images.

```
Failure summary:

  1. Host:     ci-primg284-ig-m-wg27
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required Docker images are not available:
                   openshift/origin-deployer:v3.6.0,
                   openshift/origin-docker-registry:v3.6.0,
                   openshift/origin-haproxy-router:v3.6.0,
                   openshift/origin-pod:v3.6.0
               Configured registries: docker.io
               
               check "memory_availability":
               Available memory (7.1 GiB) is too far below recommended value (16.0 GiB)
               
               check "disk_availability":
               Available disk space (36.0 GB) for the volume containing "/var" is below minimum recommended space (40.0 GB)

  2. Host:     ci-primg284-ig-n-frxx
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required Docker images are not available:
                   openshift/origin-deployer:v3.6.0,
                   openshift/origin-docker-registry:v3.6.0,
                   openshift/origin-haproxy-router:v3.6.0,
                   openshift/origin-pod:v3.6.0
               Configured registries: docker.io

  3. Host:     ci-primg284-ig-n-nzps
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required Docker images are not available:
                   openshift/origin-deployer:v3.6.0,
                   openshift/origin-docker-registry:v3.6.0,
                   openshift/origin-haproxy-router:v3.6.0,
                   openshift/origin-pod:v3.6.0
               Configured registries: docker.io

  4. Host:     ci-primg284-ig-n-8z4m
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required Docker images are not available:
                   openshift/origin-deployer:v3.6.0,
                   openshift/origin-docker-registry:v3.6.0,
                   openshift/origin-haproxy-router:v3.6.0,
                   openshift/origin-pod:v3.6.0
               Configured registries: docker.io
```

**Comment by smarterclayton** [comment]
Broke the CI jobs https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/284/console - I disabled the check for now, but I want to re-enable it when this bug is fixed

**Comment by sosiouxme** [comment]
The [check uses the `openshift_image_tag`](https://github.com/openshift/openshift-ansible/blob/77d8b348f09fe078e425b76079cc716520198b21/roles/openshift_health_checker/openshift_checks/docker_image_availability.py#L97-L107) which is supplied by the `openshift_version` role and is (I thought) what's used for the run-on-OpenShift image template, unless overridden by `oreg_url`. So if the check is wrong then I would think the deploy would use the same wrong version for registry/router/etc, unless I'm misunderstanding something. @abutcher @ashcrow @ingvagabund do I speak wrongly about any of this?

Tangentially related to https://github.com/openshift/openshift-ansible/issues/4415 - it's "hard" to determine a priori what images it's supposed to look for.

**Comment by ashcrow** [comment]
When doing containerized installs ``openshift_version`` checks to verify ``openshift_image_tag`` is set. It will abort if it's not been set previously.

If it's an rpm install and ``openshift_image_tag`` has not been set it will fall back to ``v{{ openshift_version }}``

Looking at the output of the failed run it looks like ``openshift_image_tag`` wasn't defined and the fall back was used:

```
TASK [openshift_version : debug] ***********************************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_version/tasks/main.yml:141
Tuesday 27 June 2017  00:18:09 +0000 (0:00:00.033)       0:05:30.480 ********** 
ok: [xxxxx] => {
    "msg": "openshift_image_tag was not defined. Falling back to v3.6.0"
}
```

**Comment by sosiouxme** [comment]
And now that I think about it I recall that for Origin we specifically didn't want `openshift_version` to default to alpha releases, instead requiring them to be specifically requested.

@smarterclayton wouldn't the correct path here be to specify `openshift_image_tag` for CI to test alpha releases?

**Comment by sosiouxme** [comment]
Just doing some issue cleanup here. I think this is... working as designed? Feel free to re-open if this issue is still relevant.
