### ISSUE TITLE
[RFE] allow hostpath volume mount from openshift-logging role

### ISSUE THREAD

**Issue by ljuaneda** [openshift/openshift-ansible#4625]
Currently, there is no way to mount hostpath volume to ES instances with the ansible role openshift-logging.
We'd like the ability to set something like :
openshift_logging_elasticsearch_storage_type == "hostpath"

We'd need a nodeselector on each ES dc and ES-OPS dc to fit the ES pods on a given node, this selector could be based on es instance count, like "logging-es-node=1" "logging-es-node=2" and so on...
Then we'd need a variable to set the mount path on the node host, like openshift_logging_elasticsearch_hostpath_mountpath == "/mnt/logging-es"
openshift_logging_elasticsearch_ops_hostpath_mountpath == "/mnt/logging-es-ops"

**Comment by pweil-** [comment]
tracking upstream: https://trello.com/c/g2FOzhDl
