### ISSUE TITLE
[RFE] allow hostpath volume mount from openshift-metrics role

### ISSUE THREAD

**Issue by ljuaneda** [openshift/openshift-ansible#4627]
Currently, there is no way to mount hostpath volume to cassandra instances with the ansible role openshift-metrics.
We'd like the ability to set something like :
`openshift_metrics_cassandra_storage_type == "hostpath"`

We'd need a nodeselector on each cassandra rc to fit the pods on a given node, this selector could be based on the cassandra replica count, like "metrics-cassandra-node=1" "metrics-cassandra-node=2" and so on...
Then we'd need a variable to set the mount path on the node host, like `openshift_metrics_cassandra_hostpath_mountpath == "/mnt/metrics-cassandra"`

**Comment by pweil-** [comment]
tracking upstream: https://trello.com/c/g2FOzhDl
