### ISSUE TITLE
OpenStack installation failed with "host not found"

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/openshift-ansible#465]
I install OpenShift on OpenStack with

    ./bin/cluster create -n 1 -m 1 -e 1 -t origin -o image_name=centos-7-amd64 -o keypair=main \
     -o master_flavor=t1.small -o node_flavor=t1.small -o dns=10.0.0.53 \
     -o infra_flavor=t1.small openstack openshift

but failed with

    TASK: [openshift_manage_node | Label nodes] *********************************** 
    fatal: [10.99.0.121] => Failed to template {% if 'openshift_node_labels' in hostvars[item] %} True {% else %} False {% endif %}: host not found: 192.168.83.5
    
    FATAL: all hosts have already failed -- aborting

I put some debug statement and found `hostvars` use VM's floating IP address as key, but `openshift_nodes` values are VM's private IP addresses.

`openshift-ansible` is master branch (1399425c70052445cc8659fd12cd19535fb95e5a).

**Comment by detiber** [comment]
@xionglingfeng working on a fix for this here: https://github.com/openshift/openshift-ansible/pull/467

**Comment by xionglingfeng** [comment]
Perfect. Thank you.
