### ISSUE TITLE
OpenShift Ansible should leverage node bootstrap

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#4685]
OpenShift (since 1.5) has supported limited client bootstrapping.  As soon as master opens for 3.7 I'm going to land changes that make it more in line with upstream in https://github.com/openshift/origin/pull/15037.  I would like to get a head start on those changes in openshift-ansible for 3.7 as well, and use this as an opportunity to look at how we organize a roll out in order to get faster and simpler deployments.

Bootstrapping moves config and security responsibilities to the master, as well as cert rotation responsibilities.  The node is in a "near zero configuration state" (possibly some overrides), and has only a kubeconfig to talk to the master.  It requests a client cert and then a server cert from the master, and tries to fetch a node-config.yaml file from the master in a known namespace (or generates a default).  It would periodically refresh or reload those certs and its config.  A small number of overrides per machine is reasonable, but needs more discussion.

The goal for bootstrapping is to allow faster node bring up by reducing the differences between nodes, as well as centralizing more config and letting the cluster converge on the desired state vs having to automate back and forth.

In a perfect world, the *ONLY* piece of coordination between masters and nodes is the injection of the bootstrap kubeconfig.  We want the nodes to be completely configured and waiting only for the presence of the kubeconfig as quickly as possible, and that setup would likely be the setup for a golden image (on cloud providers), where the bootstrap kubeconfig is put into place via cloud-init.  There's no reason to wait to configure nodes except for potential conflicts during the installer (and for perf reasons I'd really like to parallelize that if possible).

In addition, we've talked about tying in node-group provisioning in to this flow, where we want to define a node group (based on some image) and have that be provisioned independently.  We do not yet have individual node configuration possible during bootstrapping, nor do we support merging a large set of node config with the server, so there may be additional work that we need to investigate around how to have different node groups that each share a single config setup.

How to configure, copied from #15037:

1. start a master with `cluster-signing-cert-file` and `cluster-signing-key-file` set in the master config to point to the cluster CA key and cert.
2. create a bootstrap config file with `oc serviceaccounts create-kubeconfig -n openshift-infra node-bootstrapper > KUBECONFIG_WITH_CSR_RIGHTS`
3. start a node with `sudo openshift start node --bootstrap --kubeconfig=KUBECONFIG_WITH_CSR_RIGHTS`
4. as an admin, use `oc get csr` to see the pending CSR and `oc adm certificate approve NAME` for both CSRs

I'd like to put in a new experimental flag / behavior to ansible `openshift_node_configuration_mode=bootstrap` or similar so that we can start testing in this fashion as soon as code lands.

**Comment by smarterclayton** [comment]
@sdodson partial dump of thoughts around bootstrapping

**Comment by sdodson** [comment]
@kwoodson This is relevant to your golden images discussion.

**Comment by kwoodson** [comment]
@smarterclayton @sdodson @twiest 

I love this idea.  +💯

**Comment by sdodson** [comment]
I believe this has been fully realized, if not to the exact spec defined above. Are there any outstanding items we'd like to see implemented?

**Comment by DanyC97** [comment]
will be nice to turn this into a proposal and have it in docs section ? what do you think @sdodson  ?

**Comment by sdodson** [comment]
Yes, we need to write up clear documentation of the implementation. docs.openshift.org has some mention of the changes in release notes but it doesn't go into detail.
