### ISSUE TITLE
Implement standard retry for all repo tasks

### ISSUE THREAD

**Issue by sosiouxme** [openshift/openshift-ansible#4686]
There are a number of places in openshift-ansible where we do something requiring access to a repo to work. These interactions are prone to failing due to temporary blips in service. We see it in CI flakes frequently and can reasonably expect it's a problem occasionally for users too (they can retry the whole playbook run, but this is not a great experience). The situation could probably be improved if we made a pattern of retrying the task, perhaps with a timeout and/or cache clear between.

Possibly this could even be an enhancement for the ansible packaging modules. Note that where we're using the `package` module... it doesn't have a lot of options now; and for straight repoquery commands we'd have to do something else entirely. If we can do something generically to implement this pattern that would be ideal, and might also help us in supporting disconnected installs.

**Comment by sdodson** [comment]
The approach I'd thought about taking here is to force all of our actions to work strictly from cache and then make the handler that clears repo cache responsible for retrying repo cache creation. I'm not certain if this is entirely possible or not, I don't think it is if we stick to using the package module as it doesn't expose all the options that the yum or dnf modules do.

Even with that I *think* these sort of failures often persist for multiple minutes. So does it really make sense to retry over and over indefinitely waiting for repo sanity?

**Comment by sosiouxme** [comment]
> The approach I'd thought about taking here is to force all of our actions
> to work strictly from cache and then make the handler that clears repo
> cache responsible for retrying repo cache creation.
>

Seems like it would help with metadata, but I don't think you want to cache
all of the packages too :) unless you're disconnected and sync the whole
repo first. I'm not sure how often it's just metadata versus actual package
transmission that errors out. Doesn't yum already work mostly from cache
unless the cache gets cleared?


> I'm not certain if this is entirely possible or not, I don't think it is
> if we stick to using the package module as it doesn't expose all the
> options that the yum or dnf modules do.
>

The `package` action plugin isn't actually that complicated so it wouldn't
be hard to copy it to `rhpackage` or something and hack in some more
parameters. We could even put the retry logic there (yum nor dnf have any).
Not sure what we'd do about repoqueries... I guess that could be a parallel
action plugin.


> Even with that I *think* these sort of failures often persist for
> multiple minutes. So does it really make sense to retry over and over
> indefinitely waiting for repo sanity?
>

Not indefinitely, but if we're expecting an install to take an hour or more
then I think at least a few minutes would be reasonable to avoid aborting
the whole thing on brief outages. Of course it's not super easy to
determine when it's an outage versus failure to resolve packages, and in
the latter case we'd want to fail sooner than later.
