### ISSUE TITLE
how can i change the health check parameters when i install the openshift use ansible+vagrant

### ISSUE THREAD

**Issue by AgainstWind** [openshift/openshift-ansible#4706]
#### Description

 1. Host:     master1
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "memory_availability":
               Available memory (7.6 GiB) is too far below recommended value (16.0 GiB)
               
               check "docker_storage":
               Use of loopback devices with the Docker devicemapper storage driver
               (the default storage configuration) is unsupported in production.
               Please use docker-storage-setup to configure a backing storage volume.
               See http://red.ht/2rNperO for further information.
               
               check "disk_availability":
               Available disk space in "/var" (38.9 GB) is below minimum recommended (40.0 GB)

  2. Host:     node1
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_storage":
               Use of loopback devices with the Docker devicemapper storage driver
               (the default storage configuration) is unsupported in production.
               Please use docker-storage-setup to configure a backing storage volume.
               See http://red.ht/2rNperO for further information.

  3. Host:     node2
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_storage":
               Use of loopback devices with the Docker devicemapper storage driver
               (the default storage configuration) is unsupported in production.
               Please use docker-storage-setup to configure a backing storage volume.
               See http://red.ht/2rNperO for further information.
The execution of "/home/vagrant/openshift-ansible/playbooks/byo/config.yml"
includes checks designed to fail early if the requirements
of the playbook are not met. One or more of these checks
failed. To disregard these results, you may choose to
disable failing checks by setting an Ansible variable:

   openshift_disable_check=disk_availability,docker_storage,memory_availability

Failing check names are shown in the failure details above.
Some checks may be configurable by variables if your requirements
are different from the defaults; consult check documentation.
Variables can be set in the inventory or passed on the
command line using the -e flag to ansible-playbook.
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by nasica88** [comment]
I believe this is too late a response.   I had the same trouble of being poor in disk storage.


  1. Hosts:    10.10.14.98
     Play:     OpenShift Health Checks
     Task:     Run health checks (install) - EL
     Message:  One or more checks failed
     Details:  check "disk_availability":
               Available disk space in "/var" (34.1 GB) is below minimum recommended (40.0 GB)

I got away from that error by editing the following file.

    $ sudo vi /usr/share/ansible/openshift-ansible/roles/openshift_health_checker/openshift_checks/disk_availability.py
    ...
            '/var': {
                'oo_masters_to_config': 10 * 10**9,    #40 * 10**9,
                'oo_nodes_to_config': 5 * 10**9,       #15 * 10**9,
                'oo_etcd_to_config': 5 * 10**9,        #20 * 10**9,
