### ISSUE TITLE
External network is stucked at default value

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/openshift-ansible#471]
Current version (2cbba20205318b3c16b7aa8cd2693e2838c547c1) of master branch seems ignored `-o external_net` and `-o floating_ip_pools` parameters and always use `External` as external network name. This make the creation failed when external network is named other than 'external'.

**Comment by detiber** [comment]
@xionglingfeng I assume this is with the OpenStack provider?

**Comment by xionglingfeng** [comment]
@detiber The `heat` stack failed to create because the external network `External` is undefined. I read the heat template and find the `external_net` is always `external` no matter what I specified in  the command line. The expected result is the `external_net` parameter is the value I set in command line.

**Comment by detiber** [comment]
@lhuard1A @akram can either of you provide more detail on this issue?

**Comment by lhuard1A** [comment]
I confirm the issue.
The options to set the external network and the floating IP pool exist, but the corresponding values are not passed to the heat template which is using the default values.

I’ll submit a PR to fix that and to do some cleanup asap.

**Comment by xionglingfeng** [comment]
With my test, the `floating_ip_pools` is not set correctly yet.

    Resource Failed - Unknown Status Failed Due To "Resource Create Failed: Stackvalidationfailed:
    Property Error : Floating-Ip: Floating Network Error Validating Value U'External': Unable To Find Network With Name 'External'"

**Comment by xionglingfeng** [comment]
@lhuard1A I made a mistake in my command line. `floating_ip_pools` should be replaced with `floating_ip_pool`. After that, the creation is succeeded. Thank you!
