### ISSUE TITLE
etcd node is not created with OpenStack

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/openshift-ansible#472]
I run

    ./bin/cluster -v create -t origin -m 1 -n 1 -i 1 -e 1 -o dns=10.0.0.53 \
     -o master_flavor=t1.small \
     -o node_flavor=t1.small -o infra_flavor=t1.small -o image_name=centos-7-amd64 \
     openstack openshift

to deploy OpenShift on OpenStack. This command is expected to create four nodes:

* master node
* compute node
* infra node
* etcd node

But there are only three nodes are created. It seems there are not `etcd` nodes.

**Comment by detiber** [comment]
@lhuard1A could you take a look at this? I don't have an environment that I can use for testing the current OpenStack provider (no Heat or Neutron)

**Comment by lhuard1A** [comment]
@detiber #492 adds what was missing for the support of clustered etcd on OpenStack.

**Comment by detiber** [comment]
@lhuard1A outstanding, thanks!
