### ISSUE TITLE
Running failed playbook from the point it failed

### ISSUE THREAD

**Issue by jarekg83** [openshift/openshift-ansible#4741]
Is there any way to run byo/config.yml from the place it failed?

--start-at-task doesn't seem to work at all :/.

Any hints?

**Comment by aizuddin85** [comment]
Hello @jarekg83 ,

Do you have any details logs on the matter?

Regards

**Comment by tbielawa** [comment]
My understanding is that because we use a mix of dynamic and static includes that resuming a playbook run is not possible at this time.

**Comment by jarekg83** [comment]
Hi guys,

@aizuddin85 no I don't but when it generally fails let's say at the task 'Deploying metrics' I would like to fix what caused that error and run it from --start-at-task "Deploying metrics' but that doesn't work at all.

If it's because of the dynamic and static includes - fair enough but it would be nice to have such an option - somehow.

Thanks!
