### ISSUE TITLE
Error during ansible playbook: 'glusterfs_name' is undefined

### ISSUE THREAD

**Issue by ozdanborne** [openshift/openshift-ansible#4745]
#### Description

Trying to install a Calico cluster. Runs of openshift-ansible on byo is failing due to an undefined `glusterfs_name`. 

This commit seems pretty suspect: #4245 

I'm very surprised that I seem to be the only one hitting this. Would have thought it's not calico-specific but it could very well be...

##### Version

```
ansible 2.2.0.0
openshift-ansible-3.6.141-1-20-gb8c5241
```

(Current master)

##### Steps To Reproduce

`ansible-playbook openshift-ansible/playbooks/byo/config.yml`

##### Expected Results

Successful playbook runthrough.

##### Observed Results

```
TASK [openshift_storage_glusterfs : Create temp directory for doing work in] ***
skipping: [master]

TASK [openshift_storage_glusterfs : set_fact] **********************************
skipping: [master]

TASK [openshift_storage_glusterfs : Verify target namespace exists] ************
skipping: [master]

TASK [openshift_storage_glusterfs : Delete pre-existing heketi resources] ******
fatal: [master]: FAILED! => {"failed": true, "msg": "'glusterfs_name' is undefined"}
        to retry, use: --limit @/home/turk/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP *********************************************************************
etcd1                      : ok=128  changed=13   unreachable=0    failed=0   
localhost                  : ok=12   changed=0    unreachable=0    failed=0   
master                     : ok=518  changed=131  unreachable=0    failed=1   
node                       : ok=261  changed=69   unreachable=0    failed=0   


Failure summary:

  1. Host:     master
     Play:     Configure GlusterFS
     Task:     openshift_storage_glusterfs : Delete pre-existing heketi resources
     Message:  'glusterfs_name' is undefined
```

##### Additional Information

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)

CentOS Linux release 7.3.1611 (Core) 

* Your inventory file (especially any non-standard configuration parameters)

```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
os_sdn_network_plugin_name=cni
openshift_use_openshift_sdn=false
openshift_use_calico=true
openshift_disable_check=memory_availability,docker_storage


[masters]
master

[nodes]
master openshift_node_labels="{'region': 'infra'}"
node

[etcd]
etcd1
```

**Comment by ozdanborne** [comment]
cc: @jarpa @rajatchopra

**Comment by jcpowermac** [comment]
Looks like this the task with the issue.

From the docs `openshift_storage_glusterfs_heketi_wipe` is supposed to be false by default but not seeing where that is defined.

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml#L20

**Comment by sdodson** [comment]
Looks like the defaulting happens in https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_storage_glusterfs/tasks/glusterfs_config.yml#L11 which pulls its default from https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_storage_glusterfs/defaults/main.yml#L10 not sure why that's falling down.

**Comment by jcpowermac** [comment]
Thanks @sdodson missed that.  
Also weird that the `glusterfs_name` is defaulted so shouldn't have ran into this.

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_storage_glusterfs/tasks/glusterfs_config.yml#L6

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_storage_glusterfs/defaults/main.yml#L5

**Comment by jarrpa** [comment]
Looks like (this task)[https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_storage_glusterfs/tasks/glusterfs_config.yml#L2] is getting skipped, thus the variable is never being defined... but since ansible needs to compute every loop of a task before skipping them, it's trying to expand glusterfs_name in the loop parameters. A default statement should fix this. On it.

**Comment by jarrpa** [comment]
@jcpowermac Can you see if the above helps fix your issue?

**Comment by jcpowermac** [comment]
@ozdanborne can you fetch this [PR](https://github.com/openshift/openshift-ansible/pull/4909) and test?

**Comment by ozdanborne** [comment]
I know @kprabhak successfully installed Calico using this PR. I'll run it myself today.

**Comment by ozdanborne** [comment]
Still hitting an error. Commented on the PR. Retrying with the fix.

**Comment by ozdanborne** [comment]
@jcpowermac #4909 works. Can we merge?
