### ISSUE TITLE
Switch scheduler template from ServiceSpreadingPriority to SelectorSpreadPriority?

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#476]
https://github.com/openshift/origin/pull/4175 re-adds `ServiceSpreadingPriority` priority, so our current scheduler template is valid.

However, we may want to switch our default scheduler template to use `SelectorSpreadPriority`, added in https://github.com/kubernetes/kubernetes/pull/10667, that spreads on service or replication controller.

@abhgupta, do you have an opinin on which we should make the default?

**Comment by detiber** [comment]
@liggitt awesome news on ServiceSpreadingPriority coming back.

@liggitt @abhgupta I've been wanting to make the scheduler config more flexible for a while.  If we want to change the default, I may take that as an opportunity to refactor it a bit.
