### ISSUE TITLE
Cassandra pod cannot work due to log "CassandraDaemon.java:709 - Has no permission to create directory /cassandra_data/data"

### ISSUE THREAD

**Issue by lirenjiede** [openshift/openshift-ansible#4760]
Hi all, 
I just use openshift-ansible1.5 to install origin 1.5 with metrics, but the cassandra pod can not work.
use oc logs commands. find below error log:
**WARN  09:34:13 Directory /cassandra_data/data doesn't exist
ERROR 09:34:13 Has no permission to create directory /cassandra_data/data**

I just use nfs as persistent storage

##### Version
openshift-ansible 1.5
openshift origin 1.5
```

**Comment by sdodson** [comment]
Can you please provide your inventory/variables?

**Comment by lirenjiede** [comment]
### openshift metrics
openshift_hosted_metrics_deploy=true
openshift_master_default_subdomain=abc.test
openshift_hosted_metrics_deployer_prefix=openshift/origin-
openshift_hosted_metrics_deployer_version=v1.5.1

openshift_hosted_metrics_storage_kind=nfs
openshift_hosted_metrics_storage_access_modes=['ReadWriteOnce']
openshift_hosted_metrics_storage_host=nfs.test.com
openshift_hosted_metrics_storage_nfs_directory=/data
openshift_hosted_metrics_storage_volume_name=metrics
openshift_hosted_metrics_storage_volume_size=60Gi

**Comment by lirenjiede** [comment]
just close issue, due to resolve it. Thanks @sdodson

**Comment by mrmootu** [comment]
How did you resolve the problem?
