### ISSUE TITLE
Missing Docker registry

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/openshift-ansible#478]
Deploying Openshift to Openstack is successes with the current master branch (30d653aa5b776afbf35c98b1b5e7436f8cb7123c) with patch (#474). However, added new example app cannot be built because

```
Time    Name    Kind    Reason  Message
2:25:47 AM  cakephp-mysql-example-1     Build   invalidOutput   Error starting build: the ImageStream test/cakephp-mysql-example:latest cannot be used as the output for Build test/cakephp-mysql-example-1 because the integrated Docker registry is not configured, or the user forgot to set a valid external registry (451 times in the last 7 minutes, 19 seconds)
2:24:32 AM  cakephp-mysql-example   DeploymentConfig    failedCreate    Couldn't create initial deployment: DeploymentConfig "cakephp-mysql-example" is invalid: triggers[0].imageChange.tag: invalid value 'latest': no image recorded for test/cakephp-mysql-example:latest (4 times in the last 6 minutes, 3 seconds)
```

I think the Docker registry should run at `infra node` according to #470 

> infra nodes (short for infrastructure nodes) are nodes which are set aside for deploying the internal router/registry and other internal components.

**Comment by detiber** [comment]
@xionglingfeng I believe the issue at play here is that the openstack playbooks are not adding the openshift_registry role to any hosts.  You would need to follow the steps here: https://docs.openshift.org/latest/admin_guide/install/docker_registry.html to install the registry.

You will also want to deploy a router as well: https://docs.openshift.org/latest/admin_guide/install/deploy_router.html

**Comment by xionglingfeng** [comment]
@detiber Why not add these roles to Openstack playbook? Is there any special consideration?

**Comment by detiber** [comment]
@xionglingfeng I wouldn't be against adding the roles to the openstack playbook, however I think the roles need quite a bit of improvement before I would consider them production ready.

Some of the deficiencies I think need to be addressed before the roles are fully ready:
- The registry role doesn't support configuring persistent storage
- The registry and router roles are not able to deploy HA services
- The router role does not support configuring SSL for the application wildcard domain

Since these are things most deployments will want, we defer to the documentation until the role deficiencies are addressed.

**Comment by xionglingfeng** [comment]
@detiber In the previous comments, you mentioned that the `registry` and `routers` can be installed on any hosts. But which one is most appropriate to do, e.g. `infra` nodes?

For the latest comment, can you show me some documents about 
> configuring persistent storage
since I didn't see anything about this?

For the HA and SSL part, I think maybe we can ignore them to make a complete build first?

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
