### ISSUE TITLE
installing cfme requires changes to master configuration

### ISSUE THREAD

**Issue by joelddiaz** [openshift/openshift-ansible#4782]
Was working to get cfme installed with the cloudforms team, and we noticed when going through the playbooks/common/openshift-cfme/config.yml playbook, it runs the tune_masters tasklist from roles/openshift_cfme/tasks/. This results in changing the maxImagesBulkImportedPerRepository setting being raised to '100' (from what I believe is a default of '5').

It doesn't sound right that desiring to install cfme requires such core cluster configuration changes. I understand that the template that installs cfme is using an imagestream whose target has 30+ tags, and importing only 5 means we may not end up with the tag we really want to pull. But then maybe we simply don't need to be using an ImageStream...

**Comment by tbielawa** [comment]
The tuning of the `maxImagesBulkImportedPerRepository` setting comes from this specific recommendation on the upstream docs

* https://github.com/ManageIQ/manageiq-pods#increase-maximum-number-of-imported-images-on-imagestream

Per the [upstream docs](https://github.com/ManageIQ/manageiq-pods#cluster-sizing) and the openshift-cfme role README in this repo it is noted that `Recommendations assume MIQ will be the only application running on this cluster.`

You're not alone in this, however, I have heard other voices comment about the core system tuning as well. I'd much rather find a better alternative but I am not sure that can come from the openshift-ansible side of things.

What are alternative to image streams?

**Comment by joelddiaz** [comment]
@tbielawa i'm certainly no expert on image streams and their uses, but would simply avoiding image streams and just pointing directly to the docker image/tag combo we want to pull/run be something workable?

I don't think we had plans to run a cluster that ran nothing but manageiq. I'm hoping we can accommodate running manageiq alongside the other workloads we have in our ops cluster. We have a pretty strict policy of no oversubscription of resources (ie pod requests == pod limits values), so as long as we have appropriate requests/limits for the pods, we should be able to guarantee resources.

**Comment by joelddiaz** [comment]
@tbielawa i was able to remove the imagestreams and just point to the docker hub container images directly.

I deleted the imagestream objects, and also had to update the deploymentconfig to remove the imagestream pieces out of the triggers section:

[root@jdiaztest-master-d13dd ~]# oc get dc postgresql -o yaml | grep -A2 trigger
  triggers:
  - type: ConfigChange

The dc now just pulls directly from docker hub.

[root@jdiaztest-master-d13dd ~]# oc get pods | grep postgres
postgresql-1-b2c80   1/1       Running   0          15m
