### ISSUE TITLE
Change app domain suffix

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/openshift-ansible#479]
Installation on Openstack with the current master branch (30d653a) and patch (#474) will set the domain suffix for apps as `openshiftapps.com`. I searched the source code of whole `openshift-ansible` but found nowhere defined this string...
How to change the domain suffix?

**Comment by detiber** [comment]
osm_default_subdomain needs to be set on the master host.

**Comment by abutcher** [comment]
@brenton This issue can be closed
