### ISSUE TITLE
Changing API and console port isn't possible

### ISSUE THREAD

**Issue by arthfl** [openshift/openshift-ansible#4804]
#### Description

We had openshift_master_api_port and openshift_master_console_port both set to 443 on our initial deployment.
Later on we decided to change the port to 8443, so changed the variables in the inventory and rerun the playbooks.
This failed at

```TASK [openshift_examples : Import RHEL streams] ```

Because none of the *.kubeconfig files got updated with the new port settings and ```oc``` was obviously not able to connect.

After fixing the port settings manually everywhere, something was still odd with the user accounts, as they wheren't able to see their projects...etc. So we had to redeploy the whole cluster from zero.

##### Version
```
ansible 2.3.1.0
openshift-ansible-3.6.133-1
```

##### Steps To Reproduce
1. Deploy a nice OpenShift cluster, in our case: 2 masters, 2 worker nodes, 3 etcd nodes. With following setting in the inventory file:
```
openshift_master_api_port=443
openshift_master_console_port=443
```
-> ansible-playbook -i your_inventory.ini openshift-ansiblee/playbooks/byo/config.yml

2. Change those values to 8443, run the deployment again.

##### Expected Results
The ports being changed and everything working fine

##### Observed Results
Deployment crashed, nothing worked properly anymore

##### Additional Information
Our cluster is running on AtomicOS machines, if that is relevant.

**Comment by philipakash** [comment]
I got the same issue .. Is there a quick way to change the ports?
