### ISSUE TITLE
ec2_security_configs environment variable does nothing

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#481]
Since it's overridden by the default in the deployment type.  Probably should be removed from README.md (or made a default before the base).

**Comment by davidmat** [comment]
The correct environment variable name is `ec2_security_groups` and not ec2_security_configs as stated in the title.

I have submitted pull request #1476 with a fix for this issue.

**Comment by michaelgugino** [comment]
This code path has been removed.

Closing as this bug no longer applies.
