### ISSUE TITLE
Refactor AEP uninstall to be more generic

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#485]
We should refactor #444 so that it's more comprehensive and generic uninstall.

Known deficiencies
- [ ] No handling of docker-storage-setup docker-pool
- [ ] Includes atomic-enterprise specific bits which I believe have never shipped
- [ ] rename to be more generic

**Comment by detiber** [comment]
I don't think we need to worry about the second two items anymore.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
