### ISSUE TITLE
Terminate and launch playbook should refresh inventory cache

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#486]
Today on ec2 if I create a cluster, tear it down with terminate, and then launch the cluster again, I'll get inventory from the previous run (which includes the terminated instances).  Also, due to #482 terminate is not completely successfully.

Jason and I concurred that both terminate and launch playbook should refresh inventory.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
