### ISSUE TITLE
oreg_url not set for system containers

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-ansible#4873]
#### Description

The `oreg_url` seems to imply it would set the container images used by things like masters and nodes (ie. openshift/origin and openshift/node)

However it ends up just using the values hardcoded in `openshift_facts.py`

##### Version

release-1.5

**Comment by giuseppe** [comment]
@sdodson can we drop affects_3.5 since there is no system container support there?

**Comment by sdodson** [comment]
Sure, not sure why I didn't realize that.

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-ansible/issues/4415 is related
