### ISSUE TITLE
sso71-postgresql-persistent template fails as postgres won't start

### ISSUE THREAD

**Issue by tdudgeon** [openshift/openshift-ansible#4889]
#### Description

The [sso71-postgresql-persistent template](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v3.6/xpaas-templates/sso71-postgresql-persistent.json) doesn't currently work as the postgres pod fails to start with this error:

`mkdir: cannot create directory '/var/lib/pgsql/data': Permission denied`

##### Version
Git Checkout: openshift-ansible-3.6.153-1-131-g7a2eab5

OpenShift Origin version:

```
oc v3.6.0-rc.0+98b3d56
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0-rc.0+98b3d56
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
https://github.com/OpenRiskNet/home/blob/master/openshift/create-sso.md

##### Expected Results

SSO and Postgres start

##### Observed Results
Postgres fail to start. The pod logs report:

```
mkdir: cannot create directory '/var/lib/pgsql/data': Permission denied
```

The sso-postgresql-claim pvc seems to be setup OK.

```
oc describe pvc/sso-postgresql-claim
Name:		sso-postgresql-claim
Namespace:	sso-app-demo
StorageClass:
Status:		Bound
Volume:		pv0023
Labels:		application=sso
		template=sso71-postgresql-persistent
		xpaas=1.4.0
Annotations:	pv.kubernetes.io/bind-completed=yes
		pv.kubernetes.io/bound-by-controller=yes
Capacity:	100Gi
Access Modes:	RWO,ROX,RWX
Events:		<none>
```

##### Additional Information

This works fine with the non-persistent version of Postgres

**Comment by sdodson** [comment]
@rcernich Does your team own SSO? can you take a look at this?

**Comment by rcernich** [comment]
It sounds like an issue with the volume being used.  Maybe it wasn't cleaned out or maybe the permissions on the directory are incorrect.

**Comment by tdudgeon** [comment]
OK, seems like that might be the case. I tried again with a new setup and its working fine.
Don't really understand what could have been different, but clearly the template is woking.
