### ISSUE TITLE
[RFE] when running the ansible playbooks report openshift-ansible version

### ISSUE THREAD

**Issue by ingvagabund** [openshift/openshift-ansible#4892]
So we don't have to ask for the openshift-ansible rpm version each time we get ansible logs, the rpm version should be hardcoded. E.g. generate `openshift_ansible_rpm_version.yml` each time an rpm is built (by default the file will have no-op task). Can be then part of `playbooks/common/openshift-cluster/std_include.yml`.

**Comment by sdodson** [comment]
Yes we need this. https://trello.com/c/9PZ6LZRb/441-2-never-have-to-ask-for-more-information-to-debug
