### ISSUE TITLE
3.6 upgrade should set maxInFlight to 9k if cluster above a certain size

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#4903]
Before doing an update to 3.6, we should increase the max in flight to 9k if there are more than X namespaces (x probably 500 namespaces or more).

We then have to restart the api servers *before* the upgrade.

Set `servingInfo.maxRequestsInFlight` to `9000` in the core master config (not asset).

**Comment by smarterclayton** [comment]
@sdodson for 3.6

**Comment by sdodson** [comment]
What's the harm of setting it to 9000 regardless of namespace count?
