### ISSUE TITLE
improper dnsmasq config - pods don't have dns to outside world

### ISSUE THREAD

**Issue by dustymabe** [openshift/openshift-ansible#4935]
When using `ansible-2.3.1.0-1.fc25.noarch` to run openshift-ansible @ a095a16 (with `openshift_release=v1.5.1`) against a set of Fedora 26 Atomic Host's in DigitalOcean I don't get a proper dns set up (running pods within openshift can't get dns). DigitalOcean uses a static networking configuration (not from DHCP) and the network-scripts files that get populated don't have dns information in them, but the `/etc/resolv.conf` on the host does have the proper dns config in it.

```

[root@origin-node-1 ~]# cat /etc/resolv.conf 
; Created by cloud-init on instance boot automatically, do not edit.
;
nameserver 8.8.8.8
nameserver 8.8.4.4
[root@origin-node-1 ~]# ls /etc/dnsmasq.d/
node-dnsmasq.conf  origin-dns.conf
```

I've been told I should have another file in that directory. To work around this I removed the `no-resolv` line from `/etc/dnsmasq.d/origin-dns.conf`.

A possible solution is to try to gather dns information from network files and if it doesn't exist in there then take it from resolv.conf before editing resolv.conf to point back to dnsmasq (will this persist across reboots, though, it depends on if cloud-init populates it every time or not). 

More info is below:

<details>

network-scripts files
```
[root@origin-node-1 ~]# cat /etc/sysconfig/network
NETWORKING=yes
NOZEROCONF=yes
[root@origin-node-1 ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth0 
# Created by cloud-init on instance boot automatically, do not edit.
#
BOOTPROTO=none
DEVICE=eth0
HWADDR=f2:91:9f:e3:4a:41
MTU=1500
ONBOOT=yes
TYPE=Ethernet
USERCTL=no
[root@origin-node-1 ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth0\:
ifcfg-eth0:0  ifcfg-eth0:1  
[root@origin-node-1 ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth0\:0
# Created by cloud-init on instance boot automatically, do not edit.
#
BOOTPROTO=static
DEFROUTE=yes
DEVICE=eth0:0
GATEWAY=174.138.48.1
HWADDR=f2:91:9f:e3:4a:41
IPADDR=174.138.56.164
MTU=1500
NETMASK=255.255.240.0
ONBOOT=yes
TYPE=Ethernet
USERCTL=no
[root@origin-node-1 ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth0\:1
# Created by cloud-init on instance boot automatically, do not edit.
#
BOOTPROTO=static
DEVICE=eth0:1
HWADDR=f2:91:9f:e3:4a:41
IPADDR=10.17.0.6
MTU=1500
NETMASK=255.255.0.0
ONBOOT=yes
TYPE=Ethernet
USERCTL=no

```

**Comment by sdodson** [comment]
My plan is to if /etc/resolv.conf doesn't have our watermark and NM isn't instructing us as to the correct nameservers then we'll just copy the nameservers from /etc/resolv.conf into /etc/dnsmasq.d/origin-upstream-dns.conf and then reset /etc/resolv.conf to point at dnsmasq.

**Comment by dustymabe** [comment]
> My plan is to if /etc/resolv.conf doesn't have our watermark and NM isn't instructing us as to the correct nameservers then we'll just copy the nameservers from /etc/resolv.conf into /etc/dnsmasq.d/origin-upstream-dns.conf and then reset /etc/resolv.conf to point at dnsmasq.

Will that be part of the NM dispatcher that runs when NM starts or will that just happen once when openshift-ansible is executed?

**Comment by sdodson** [comment]
It'd be part of the dispatcher script for now. Longer term I'd like to transition this out of NM dispatcher script and something that's part of the node and owned by the networking team rather than the installer.
