### ISSUE TITLE
Service catalog roles must not use policy objects

### ISSUE THREAD

**Issue by enj** [openshift/openshift-ansible#4956]
@ewolinetz see #4880 for details.

cc @pmorie @sdodson

**Comment by ewolinetz** [comment]
Is there much work to be done with this? We are using the the policy modules but the underlying `policy` objects used have been transitioned to `role`

**Comment by sdodson** [comment]
#4933 may be a better reference for suggested implementation

**Comment by sdodson** [comment]
I think these are the problem lines that we need to figure out. @enj can you reach out and hack this out with @ewolinetz ?

```
roles/openshift_service_catalog/tasks/install.yml:    oc get policybindings/kube-system:default -n kube-system || echo "not found"
roles/openshift_service_catalog/tasks/install.yml:    oc create policybinding kube-system -n kube-system
roles/openshift_service_catalog/tasks/remove.yml:    oc delete policybindings/kube-system:default -n kube-system --ignore-not-found
```

**Comment by ewolinetz** [comment]
@enj What is the 3.7 equivalent for `oc create policybinding kube-system -n kube-system` ?

I'm able to see this issue when testing locally:
```json
fatal: [m01.example.com]: FAILED! => {
    "changed": true, 
    "cmd": [
        "oc", 
        "create", 
        "policybinding", 
        "kube-system", 
        "-n", 
        "kube-system"
    ], 
    "delta": "0:00:00.151888", 
    "end": "2017-09-08 16:02:27.598691", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "oc create policybinding kube-system -n kube-system", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }
    }, 
    "rc": 1, 
    "start": "2017-09-08 16:02:27.446803", 
    "stderr": "error: This command works only with server versions < 3.7.0, found v3.7.0-0.125.0", 
    "stderr_lines": [
        "error: This command works only with server versions < 3.7.0, found v3.7.0-0.125.0"
    ], 
    "stdout": "", 
    "stdout_lines": []
}
```

**Comment by enj** [comment]
@ewolinetz I do not know what you intent was with that command.  I expect you just need to directly create and delete any role bindings as necessary.

**Comment by ewolinetz** [comment]
@deads2k I believe we had talked about something similar on IRC last week... but for this we can resolve this simply by removing the lines in question that Scott had mentioned above?

**Comment by deads2k** [comment]
If these clusters were never supported, then removing the lines in question is fine.

@ewolinetz @sdodson If you like the structure for the TSB, I would suggest that you push on the service catalog team to provide the same structure for you to consume and that should get you out of the business of trying to sort this out.

**Comment by ewolinetz** [comment]
https://github.com/openshift/openshift-ansible/pull/5226 contains this fix

**Comment by pmorie** [comment]
Can we close this?

**Comment by sdodson** [comment]
Yes, this is done.
