### ISSUE TITLE
Submit lib_openshift to ansible upstream or ansible galaxy

### ISSUE THREAD

**Issue by lmello** [openshift/openshift-ansible#4959]
#### Description
lib_openshift makes it possible for anyone to create ansible playbooks to deploy services in an openshift cluster. 

Currently it is used internally in this playbook to deploy logging and metrics on an existing openshift cluster. 

It would be really useful to have it available in ansible upstream or at least available as an ansible galaxy module. 

This would allow anyone to deploy services in openshift using ansible instead of the default kubernetes yml definition files.

**Comment by cmoulliard** [comment]
- What is the status of this issue created long time ago ?
- Is it planned that all the `openshift-ansible` roles are tagged per OpenShift version an published to galaxy ?
