### ISSUE TITLE
Flag to prevent --insecure-registry

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-ansible#497]
I see in the file below that the playbooks will automatically set the --insecure-registry flag in /etc/sysconfig/docker on all nodes. Is there a flag to prevent this behaviour?

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_node/tasks/main.yml#L70

**Comment by JohnTheodore** [comment]
+1

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
