### ISSUE TITLE
Openshift Origin Minor Version Upgarde 1.5.0 -> 1.5.1 failing

### ISSUE THREAD

**Issue by saurabhdevops** [openshift/openshift-ansible#4972]
#### Description

We have openshift origin 1.5.0 cluster. We need to upgrade this to 1.5.1 without losing all the current work that we did in 1.5.0.

##### Version

Ansible Version - ansible 2.3.1.0
Git branch - release-1.5

##### Steps To Reproduce
- Install Openshift Origin 1.5.0 using ansible.
- Try to upgrade it to 1.5.1

##### Expected Results
Cluster Upgraded

##### Observed Results
Cluster not upgraded

##### Additional Information

We tried "playbooks/byo/openshift-cluster/config.yml" "playbooks/byo/openshift-cluster/upgrades/v3_5/upgrade.yml"

**Comment by sdodson** [comment]
Do you get an error? Can you post logs somewhere with -vvv option?
