### ISSUE TITLE
3.7.0 upgrade - remove support for old leader election mode and openshift-master.service

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#4979]
https://github.com/openshift/openshift-ansible/pull/4832 removed support for two old modes of installation:

1. running etcd inside of the openshift master
2. running single process openshift master (instead of split api and controllers for HA)
3. using etcd leader election (instead of using the new config map mutation mode)

The first two only apply to single master setups.

The first item will require a new etcd instance to be stood up, but the data in etcd does not have to change. Likely requires that we install the new etcd, and set an explicit storage dir.  All etcd has to be shut off first.

The second requires the master to be stopped, then the services removed, the sysconfig migrated, and the new services installed and started.

The third requires *all* controllers to be stopped, the config to be updated, then new configs to be created.

**Comment by smarterclayton** [comment]
Second part is implemented in the original PR.  First part scott is doing.  Third part I'll do.

**Comment by wanghaoran1988** [comment]
Do we have an plan to split scheduler process out?

**Comment by sdodson** [comment]
> Do we have an plan to split scheduler process out?

No immediate plans to do that.
