### ISSUE TITLE
etcd ca cert is created with lifetime of only 30 days

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-ansible#499]
When deploying with dedicated etcd servers, the etcd CA cert is erroneously created with a 30 day lifespan.

Although default_days is set to 365 in roles/etcd_ca/templates/openssl_append.j2 , this is not honoured when -x509 is put on the command line in roles/etcd_ca/tasks/main.yml and the default of 30 is used instead.

**Comment by jim-minter** [comment]
I believe adding '-days 365' in roles/etcd_ca/tasks/main.yml is one way to fix this, but am awaiting confirmation.

**Comment by woolsgrs** [comment]
```
> for i in *.crt;do echo $i; openssl x509 -in $i -noout -enddate; done
ca.crt
notAfter=Sep 20 10:14:28 2015 GMT
peer.crt
notAfter=Aug 20 10:14:58 2016 GMT
server.crt
notAfter=Aug 20 10:14:44 2016 GMT
```

After Change above

```
> for i in *.crt;do echo $i; openssl x509 -in $i -noout -enddate; done
ca.crt
notAfter=Aug 20 11:27:03 2016 GMT
peer.crt
notAfter=Aug 20 11:27:32 2016 GMT
server.crt
notAfter=Aug 20 11:27:19 2016 GMT
```

So looks good.

**Comment by detiber** [comment]
@brenton This issue should now be resolved with the merging of https://github.com/openshift/openshift-ansible/issues/500
