### ISSUE TITLE
ensure python-passlib is installed in health checks

### ISSUE THREAD

**Issue by kwoodson** [openshift/openshift-ansible#5008]
#### Description

Check that python-passlib is installed upfront before running the openshift_metrics installer.

```
TASK [openshift_metrics : Check that python-passlib is available on the control host] ******************************************************
fatal: [54.172.119.245]: FAILED! => {
    "assertion": "'not installed' not in passlib_result.stdout", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "msg": "python-passlib rpm must be installed on control host"
}
```

##### Version

latest master

##### Steps To Reproduce
1. Run the metrics installer
2. Verify that it fails without python-passlib

##### Expected Results

I would expect that the upfront health checks would verify that python-passlib is installed on the installer host.

##### Observed Results
Installation fails after 25 minutes.

##### Additional Information

This should be a simple check where we verify the package is installed before byo install.

**Comment by donnydavis** [comment]
This was supposed to be fixed with https://github.com/openshift/openshift-ansible/pull/4285
However I get the same failure using centos 7 and origin 3.7

I just commented that check out, i know passlib is installed...

**Comment by Asgoret** [comment]
Catch error...how fix that?

**Comment by Asgoret** [comment]
@sdodson  Can you help with that?

**Comment by PaulVanStaden** [comment]
In my experience I got the same error. `'not installed' not in passlib_result.stdout` Installing the `python-passlib` in the executing machine made the test pass. Can it be that the test runs against the wrong machine?

**Comment by crmarques** [comment]
Same erro in openshift-ansible-3.9.28-1-2-g8cb69c9a3.

**Comment by blueholes** [comment]
Same erro in openshift-ansible release-3.9
