### ISSUE TITLE
deployment over multiple nics confilict

### ISSUE THREAD

**Issue by mrsiano** [openshift/openshift-ansible#5010]
#### Description
Iv'e tried to deploy my cluster for certain IP address, but it always assign nodes to the default NIC address.

I have two bare-metal hosts with multiple NICs, 2 of them are active and have an ip.
somehow, my deployment always assign nodes to default ip even If i setup otherwise.

those NICs are accessible internal only, but AFIK it is fair enough for ansible deployment.
I've also double check they reach out each other over ssh.

##### Version
ansible 2.3.1.0
openshift-ansible-3.7.1-1-76-g1765ce2

##### Steps To Reproduce
1. have an bare-metal box with multiple nics.
2. active some NIC (in our case solar flare) within random ip (our case 70.70.70.x) 
3. we use 2 hosts 1 master 1 node (master should be managed as node too openshift_schedulable =true).
4. run ansible-playbook for deployment from master (70.70.70.1)

##### Expected Results
my nodes address should be assigned with the IP I specified @inventory. 

##### Observed Results
conflict with ip address that specified in the inventory file 
to 
'oc get nodes -o wide' output

##### Additional Information
this is how I describe my master && nodes at my inventory file:
...
[masters]
70.70.70.1
[nodes]
70.70.70.1 openshift_schedulable=True openshift_node_labels="{'region':'infra','zone':'default'}"
70.70.70.2 openshift_node_labels={'region':'infra','zone':'default'}

**Comment by mrsiano** [comment]
@abutcher

**Comment by aizuddin85** [comment]
@mrsiano have you tried to put those IP in /etc/hosts and assign a name to it?

**Comment by mrsiano** [comment]
yep, and it worked, just forgot to update
