### ISSUE TITLE
Containerised fails because of RPM version

### ISSUE THREAD

**Issue by marekjelen** [openshift/openshift-ansible#5015]
#### Description

Installing Origin v3.6.0 fails because it seems latest RPM release version is v1.5.1.

Based on Google searches this "feature" has been merged because some CI/CD was failing.

##### Version

```
ansible 2.2.0.0
openshift-ansible-3.6.173.0.5-2
```

##### Steps To Reproduce

```
[OSEv3:children]
masters
nodes

[masters]
<IP> openshift_schedulable=true

[nodes]
<IP> openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}"


[OSEv3:vars]
ansible_user=openshift
ansible_become=yes

enable_excluders=false
enable_docker_excluder=false

containerized=True
openshift_use_system_containers=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'

openshift_node_kubelet_args={'pods-per-core': ['10']}


deployment_type=origin
openshift_deployment_type=origin

openshift_release=v3.6.0



osm_use_cockpit=true





openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

openshift_public_hostname=<DNS>
openshift_master_default_subdomain=<DNS>
```

##### Expected Results
Ansible should not be failing, as the v3.6.0 containers are released and when using containerised I do not care what RPMs are released.

##### Observed Results
Describe what is actually happening.

```
TASK [openshift_version : Fail if rpm version and docker image version are different] ***
fatal: [<IP>]: FAILED! => {"changed": false, "failed": true, "msg": "OCP rpm version 1.5.1 is different from OCP image version 3.6.0"}
to retry, use: --limit @<PATH>
PLAY RECAP *********************************************************************
<IP>              : ok=74   changed=2    unreachable=0    failed=1
localhost                  : ok=8    changed=0    unreachable=0    failed=0
Failure summary:
1. Host:     <IP>
Play:     Determine openshift_version to configure on first master
Task:     openshift_version : Fail if rpm version and docker image version are different
Message:  OCP rpm version 1.5.1 is different from OCP image version 3.6.0
```

**Comment by marekjelen** [comment]
Adding

```
openshift_pkg_version=v3.6.0
```

seems to fix this, but should not be required.

**Comment by jkaurredhat** [comment]
It is actually required because the condition checks if openshift_pkg_version or openshift_image_tag is defined, it gives a permission the rpm and docker image versions can differ else it throws the error you are seeing

**Comment by marekjelen** [comment]
If it is really that conditional check, then the message has pretty weird wording.

Anyway, up until switching to `release-3.6`, it was enough to have 

```
openshift_release=v3.6.0
```

which makes sense, as the Ansible script can easily push the into into the correct variable, based on whether containerized is True or False (or other switches) and frees the user from figuring that out.

**Comment by eitamring** [comment]
where do i add openshift_pkg_version=v3.6.0 to?

**Comment by DanyC97** [comment]
in the inventory file @eitamring  see the [example](https://github.com/openshift/openshift-ansible/blob/release-3.6/inventory/byo/hosts.origin.example#L47) 


@marekjelen  are you okay closing this issue ?

**Comment by marekjelen** [comment]
@DanyC97 yeah, sure 👍

**Comment by DanyC97** [comment]
@marekjelen can you please do it as i don't have permission to do so ;)
