### ISSUE TITLE
Master image pull fails

### ISSUE THREAD

**Issue by marekjelen** [openshift/openshift-ansible#5018]
#### Description

When using

```
openshift_use_system_containers=True
```

Ansible fails on `/roles/openshift_master/tasks/system_container.yml` saying that `system_images_registry` is not available in a dict.

Will try to provide more info once I try running with that configuration again.

**Comment by jkaurredhat** [comment]
Try adding as below in inventory file like : 

system_images_registry="docker.io" or system_images_registry="registry.access.redhat.com" depending on your platform.
