### ISSUE TITLE
Run `oadm migrate authorization` pre 3.6 to 3.7 upgrades

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#5021]
Prior to upgrading from 3.6 to 3.7 we must run
`oadm migrate authorization` with no parameters, if the command fails the upgrade should abort. The command may fail in a loaded cluster and should be retried every 15 seconds for up to one minute?

CC: @enj

**Comment by enj** [comment]
@deads2k any comments on this?

**Comment by sdodson** [comment]
@enj when we say prior to we mean while still running 3.6? I remember we discussed this but I should've recorded when it needs to be run.

**Comment by sdodson** [comment]
@mtnbikenc do you mind looking at this one? Not urgent but we need to get it done by the end of the current sprint before we attempt to deploy 3.7 to any environment.

**Comment by mtnbikenc** [comment]
@sdodson this one slipped by me.  I'm working on it now.

**Comment by mtnbikenc** [comment]
@enj I want to make sure I'm capturing correct success and faliure states.  Are there return codes we should look for in execution of this command, such as if we get rc=0 then we are good?  Or should we look for something in the returned CLI text, shuch as `errors=0`?  I just ran this command on a test cluster and received this result:
```bash
[ec2-user@ip-172-18-6-222 ~]$ oc adm migrate authorization
summary (dry run): total=201 errors=0 ignored=0 unchanged=201 migrated=0
[ec2-user@ip-172-18-6-222 ~]$ echo $?
0
```
Here is an Ansible task output:
```
TASK [Execute oc adm migrate authorization] **************************************************************************************************
ok: [ec2-54-152-58-107.compute-1.amazonaws.com] => {
    "attempts": 1, 
    "changed": true, 
    "cmd": [
        "oc", 
        "adm", 
        "migrate", 
        "authorization"
    ], 
    "delta": "0:00:38.420730", 
    "end": "2017-08-24 09:33:14.120826", 
    "rc": 0, 
    "start": "2017-08-24 09:32:35.700096"
}

STDOUT:

summary (dry run): total=201 errors=0 ignored=0 unchanged=201 migrated=0
```

**Comment by enj** [comment]
@mtnbikenc the RC is enough to determine success and failure (if rc == 0 then errors == 0).

If you want to be super specific, the success case is (anything else being a failure):

`summary (dry run): total=AAA errors=0 ignored=0 unchanged=AAA migrated=0` where AAA is some number > 0 AND rc == 0

The output from the error case should be easy for the user to see as they will want to give that information to support for us to help them get things sorted.
