### ISSUE TITLE
Upgrade to 3.6 playbook fails with `etcd_peer` is undefined

### ISSUE THREAD

**Issue by AlbertoPeon** [openshift/openshift-ansible#5052]
#### Description

An error happens halfway whe running the upgrade playbook from 3.5 to 3.6 (ref. /openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.yml) in our multi-master, multi-node cluster. The error seems to be a bug in the  `etcd_upgrade` as `etcd_peer` is empty. See below for the actual error message.

##### Version

```
# ansible --version
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

# git describe
openshift-ansible-3.6.173.0.5-5

```

##### Steps To Reproduce
1. `ansible-playbook --limit='master*,etcd*,localhost' \
~/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.yml`
We don't run the upgrade script in the nodes to avoid downtime. To upgrade nodes, we create new machines, and add them to the cluster using a blue-green update, moving all pods to new nodes.

##### Expected Results
Upgrade script goes through and upgrades the cluster

##### Observed Results
Ansible fails halfway the installation with error:

```
TASK [etcd_upgrade : Verify cluster is healthy pre-upgrade] ********************
fatal: [etcdtest001]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: etcdctl --cert-file {{ etcd_peer_cert_file }} --key-file {{ etcd_peer_key_file }} --ca-file {{ etcd_peer_ca_file }} -C https://{{ etcd_peer }}:{{ etcd_client_port }}: 'etcd_peer' is undefined\n\nThe error appears to have been in '/root/openshift-ansible/roles/etcd_upgrade/tasks/upgrade_rpm.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Verify cluster is healthy pre-upgrade\n  ^ here\n"}
	to retry, use: --limit @/root/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.retry

```
This is under play:
```
PLAY [Upgrade fedora to latest] ************************************************
```
FWIW, we use CentOS 7, not Fedora.

##### Additional Information

The only `etcd` information in our hosts file is:

```
[etcd]
etcdtest001
etcdtest002
etcdtest003
```

**Comment by sdodson** [comment]
@AlbertoPeon Can you please try with ansible-2.2.3.0? We know there are problems with 2.2.0.0.

**Comment by AlbertoPeon** [comment]
@sdodson Right! Re-run the script with ansible-2.3.1 and worked as expected. Thanks for the suggestion!
