### ISSUE TITLE
Need to enable the aggregator by default.

### ISSUE THREAD

**Issue by deads2k** [openshift/openshift-ansible#5056]
In 3.7, the aggregator is on by default. The front proxy keys and certs used to enable it should be on by default in 3.7

**Comment by ewolinetz** [comment]
@deads2k is this simply a flipping the default from `false` to `true` for installing? Or do we also need to split up the installation of the aggregator, api server, and service brokers as part of this (and only set up the aggregator as part of a normal install)?

**Comment by deads2k** [comment]
> @deads2k is this simply a flipping the default from false to true for installing? Or do we also need to split up the installation of the aggregator, api server, and service brokers as part of this (and only set up the aggregator as part of a normal install)?

You should separate the enablement of the aggregator (its certs and keys) and have it unconditionally on for 3.7.
