### ISSUE TITLE
rpm install for origin 3.6.0 missing rpms?

### ISSUE THREAD

**Issue by jraubswitch** [openshift/openshift-ansible#5059]
http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/ does not contain the origin-3.6.0 rpms

**Comment by TimoL** [comment]
+1, stuck at
```
Failure summary:

  1. Host:     master-01
     Play:     Determine openshift_version to configure on first master
     Task:     openshift_version : Fail if rpm version and docker image version are different
     Message:  OCP rpm version 1.5.1 is different from OCP image version 3.6.0
```

**Comment by TimoL** [comment]
This seems to be a duplicate of #5015

**Comment by jraubswitch** [comment]
#5015 has containerized=true I was installing the rpm version. (implicitly not setting containerized or setting containerized=false)

**Comment by TimoL** [comment]
3.6.0 rpms are available now. This issue should be closed.

**Comment by sdodson** [comment]
@TimoL thanks for following up, sorry for the delay it's not something that the openshift-ansible team has direct control over but we're pushing for improving rpm delivery.
