### ISSUE TITLE
openshift_install_examples not respected in upgrades

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-ansible#5061]
#### Description

When `openshift_install_examples=false` the upgrade should also not import all the imagestreams and templates. This is rather annoying as it can end up triggering a lot of builds (or overwriting wrong imagestreams) plus import undesired templates.

**Comment by sdodson** [comment]
https://trello.com/c/zLaSgxig/436-2-customers-need-a-way-to-opt-out-of-openshift-ansible-template-and-imagestream-mangement
