### ISSUE TITLE
Metrics won't start. It is missing --truststore_authorities param

### ISSUE THREAD

**Issue by jaryn** [openshift/openshift-ansible#5062]
#### Description

Start of the metrics pods fails:

[cloud-user@ose3-master ~]$ oc -n openshift-infra log hawkular-metrics-mhg6p
2017-08-11 12:10:12 Starting Hawkular Metrics
The --truststore_authorities value is not specified. Aborting

I am not sure whose problem is it.

##### Version
```
ansible 2.2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

atomic-openshift-utils-3.5.75-1.git.0.f18e0cf.el7.noarch
openshift-ansible-3.5.75-1.git.0.f18e0cf.el7.noarch
```

##### Steps To Reproduce
1. Deploy using openshift-ansible

##### Expected Results
Deployed with hawkular working.

##### Observed Results
Metrics pod cannot start.

**Comment by jkaurredhat** [comment]
Can you please ensure which images are being used. Make sure for version 3.5 you are not using latest as it will pull 3.6 images hence please ensure you are using for 3.5.

**Comment by jsandova** [comment]
@jkaurredhat I am getting the same error using OpenShift origin version 1.5 and 3.6. I don't see a branch listed for version 3.5.

**Comment by jsandova** [comment]
@jkaurredhat I see now that you are referring to the OCP version not the origin version. I am using Ansible, do you know what variable that would be where I set the OCP version? I want to make sure I am setting the correct variable.

**Comment by jkaurredhat** [comment]
Have you set : 
openshift_hosted_metrics_deployer_prefix=docker.io/openshift/origin-
or  
openshift_hosted_metrics_deployer_prefix=registry.example.com:8888/openshift3/

and 
openshift_hosted_metrics_deployer_version=3.5.0

**Comment by vrutkovs** [comment]
No info for more than a year, closing
