### ISSUE TITLE
Please pull the naming fix from bz1248946

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-ansible#507]
The Django PostgreSQL example can't be created because of the error message "The Service "django-postgresql-example" is invalid:metadata.name: invalid value 'django-postgresql-example': must be a DNS 952 label (at most 24 characters, matching regex [a-z]([-a-z0-9]*[a-z0-9])?): e.g. "my-name""

I presume this is fixed at https://bugzilla.redhat.com/show_bug.cgi?id=1248946 and https://github.com/openshift/django-ex/pull/22 , can openshift-ansible be refreshed too?

**Comment by detiber** [comment]
@sdodson was this fixed with your recent update to the examples?

**Comment by sdodson** [comment]
Yup, fixed in #498

**Comment by detiber** [comment]
@brenton @wshearn please close this issue.
