### ISSUE TITLE
Failed to pull image "openshift/origin-efs-provisioner:v1.0.0"

### ISSUE THREAD

**Issue by sudhirpandey** [openshift/openshift-ansible#5070]
#### Description
While trying out external provisioner for efs .
as documented here in aws

the ansible deployment itsef is  sucessfull.. how ever the efs pod cannot come alive. 
I guess its because of the missing image.

Provide a brief description of your issue here. For example:

Followed this document to get external provisioner up .
https://docs.openshift.org/latest/install_config/provisioners.html

The finals efs pod could be deployed as of missing error.
when substiutued by this image in dc
quay.io/external_storage/efs-provisioner

dynamic volume provision worked and pvc was able to bind to the volume form efs storage class.

```
VERSION INFORMATION HERE PLEASE
```

oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Expected Results
Describe what you expected to happen.

The efs pod should have come alive after deployment

```
Example command and output or error messages
```
##### Observed Results
openshi
Failed to pull image "openshift/origin-efs-provisioner:v1.0.0": rpc error: code = 2 desc = unauthorized: authentication required

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by sdodson** [comment]
@wongma7 @childsb do we need to update where we pull the efs provision or will it soon exist at openshift/origin-efs-provisioner?

**Comment by childsb** [comment]
No we didn't plan to move it to an openshift repo.
