### ISSUE TITLE
Need more document about override openshift facts

### ISSUE THREAD

**Issue by samsong8610** [openshift/openshift-ansible#508]
In this page  https://github.com/openshift/openshift-ansible/blob/master/README_origin.md#overriding-detected-ip-addresses-and-hostnames , we explain how to override ip addresses and hostnames, using a variable name with 'openshift_' prefix in the inventory file. 
Actually there are other openshift facts we may need to override, such as portal_net, sdn_cluster_network_cidr. But the variable names to override them are not named by prefixing 'openshift_', instead, named like 'openshift_master_portal_net', 'osm_sdn_cluster_network_cidr' separately.

**Comment by detiber** [comment]
@samsong8610 you are correct in your assessment of the situation.  The openshift_ variables are ones that are meant to be set by the openshift_common role (and override fact variables that are in the openshift.common dict).

We are also in a transition period where we updated our style guide to try to shorten the length of some of the variable names we were using within some of the roles, so you will see some role variables for the openshift_master role prefixed with openshift_master_ and some with osm_, I suspect there is a similar inconsistency right now with the openshift_node role variables as well.

We have an item on our backlog to improve our documentation of the available variables and when you would want to set them.

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit
