### ISSUE TITLE
add-nodes not working properly on AWS cluster

### ISSUE THREAD

**Issue by andjelx** [openshift/openshift-ansible#5083]
#### Description
On aws cluster adding new host not working properly

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

ansible 2.3.1.0
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

If you're operating from a **git clone**:
* The output of `git describe`
openshift-ansible-3.6.173.0.5-5-34-g77be80f

Place the output between the code block below:

```
ansible 2.3.1.0
openshift-ansible-3.6.173.0.5-5-34-g77be80f
```

##### Steps To Reproduce
1. bin/cluster add-nodes -n 1 -i 0 aws cluster-name

##### Expected Results
New node to be added to AWS cluster

```
$ bin/cluster add-nodes -n 1 -i 0 aws cluster-name
```

##### Observed Results
I'm getting a error 

```
ERROR! 'vars_files' is not a valid attribute for a PlaybookInclude

The error appears to have been in '/root/openshift-ansible/playbooks/aws/openshift-cluster/scaleup.yml': line 20, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- include: ../../common/openshift-cluster/scaleup.yml
  ^ here

ACTION [add-nodes] failed: Command 'ansible-playbook  -i inventory/aws/hosts -e 'num_nodes=1 cluster_id=wfi-cluster cluster_env=dev num_infra=0 deployment_type=origin' playbooks/aws/openshift-cluster/add_nodes.yml' returned non-zero exit status 4```


##### Additional Information

Initial cluster installation from this machine have been done successfully.

**Comment by grealish** [comment]
Is this fixed in branch release-3.6-hotfix ?
Also it would be good to pin ansbile versions to your releases, otherwise people burn hours of time trying to figure that stuff out
