### ISSUE TITLE
installing an openID connect identity provider via ansible without manual edit for master-config.yaml

### ISSUE THREAD

**Issue by abdelhegazi** [openshift/openshift-ansible#5094]
#### Description
We are running okta as our main identity provider which uses OpenID Connect running over oAuth. I am able to do this process manually by adding `master-config.yaml` but this is a bit of old school way for us, I need to automate this via ansible installation as well by adding whatever variables to my inventory file, is it possible?

##### Version
This is openshift version
```
# oc version
oc v3.5.5.31
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://879130-stg-openshift-mstr-01:8443
openshift v3.5.5.31
kubernetes v1.5.2+43a9be4
```
And here is ansible
```
$ ansible --version
ansible 2.3.1.0
  config file = /usr/local/etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```
If you're operating from a **git clone**:
I use the main repo
https://github.com/openshift/origin

##### Steps To Reproduce
1. automate adding identity providers via ansible installations, more variables need for sure
2. able to modify my master-config.yaml without needing to edit this file manually

```
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
```

**Comment by abutcher** [comment]
@abdelhegazi It should be possible via `openshift_master_identity_providers`. Check out this example https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.ose.example#L198-L210

**Comment by abdelhegazi** [comment]
Thanks @abutcher 

problem solved, thanks to that link you provided, I don't know who maintains this but as you are working for redhat, there is a little bug and I guess needs some fixing within the template that parse it

basically this was my original inventory value
```
# OpenID auth
openshift_master_identity_providers=[{"name": "NAME", "login": "true", "challenge": "false", "mappingMethod": "claim", "kind": "OpenIDIdentityProvider", "client_id": "IDIDIDIDIDIDID", "client_secret": "SECRETSECRETSECRET", "extraAuthorizeParameters" : {"include_granted_scopes": "true"}, "claims": {"id": ["sub"], "preferredUsername": ["preferred_username"], "name": ["name"], "email": ["email"]}, "urls": {"authorize": "https://XXX.okta-emea.com/oauth2/v1/authorize", "token": "https://XXXXXX.okta-emea.com/oauth2/v1/token", "userInfo": "https://XXXX.okta-emea.com/oauth2/v1/userinfo"} }]
```
and that produced error when restarting master service to pickup the new changes 
```
# systemctl restart atomic-openshift-master-api.service 
Job for atomic-openshift-master-api.service failed because the control process exited with error code. See "systemctl status atomic-openshift-master-api.service" and "journalctl -xe" for details.
```
os I had to dig into it, and the fix was to add ' ' around the true values that openID reads it, as it looks like it doesn't read true/false as boolean rather it reads it as string like this look at `
 {"include_granted_scopes": " 'true' "} `
I guess it's a bug but may be needed for some folks in the future

```
# OpenID auth
openshift_master_identity_providers=[{"name": "NAME", "login": "true", "challenge": "false", "mappingMethod": "claim", "kind": "OpenIDIdentityProvider", "client_id": "IDIDIDIDIDIDID", "client_secret": "SECRETSECRETSECRET", "extraAuthorizeParameters" : {"include_granted_scopes": " 'true' "}, "claims": {"id": ["sub"], "preferredUsername": ["preferred_username"], "name": ["name"], "email": ["email"]}, "urls": {"authorize": "https://XXX.okta-emea.com/oauth2/v1/authorize", "token": "https://XXXXXX.okta-emea.com/oauth2/v1/token", "userInfo": "https://XXXX.okta-emea.com/oauth2/v1/userinfo"} }]
```
