### ISSUE TITLE
Glusterfs: unable install if docker storage driver is overlay2

### ISSUE THREAD

**Issue by SweetOps** [openshift/openshift-ansible#5108]
I know how to fix it manually, but I don't want to use device-mapper, I think no one want :)

OS: 
`Fedora Atomic 26` 

ansible:
```sh
ansible --version
ansible 2.3.1.0
  config file = /usr/share/ansible/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```
inventory:
```sh
[OSEv3:children]
masters
nodes
etcd
glusterfs

[OSEv3:vars]
ansible_ssh_user=fedora
ansible_become=true
ansible_ssh_transfer_method=scp
deployment_type=origin
containerized=true
openshift_master_cluster_method=native
openshift_master_cluster_password=admin
openshift_release=3.6
openshift_image_tag=v3.6.0
openshift_router_selector='region=infra'
openshift_registry_selector='region=infra'

openshift_install_examples=false

glusterfs_wipe=True
openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
openshift_schedulable=true
#monitoring

# Enable cockpit
osm_use_cockpit=true

# Set cockpit plugins
osm_cockpit_plugins=['cockpit-kubernetes']

openshift_hosted_logging_deploy=true
openshift_hosted_metrics_deploy=true
openshift_set_hostname=True

openshift_disable_check=disk_availability, docker_storage, memory_availability

openshift_master_default_subdomain=test2.com
openshift_master_cluster_hostname=test2.com
openshift_master_cluster_public_hostname=test2.com

[etcd]
sir-98p8j2dp
sir-2pq8g33p
sir-6z8gkj5n

[masters]
sir-98p8j2dp
sir-2pq8g33p
sir-6z8gkj5n

[nodes]
sir-98p8j2dp
sir-2pq8g33p
sir-6z8gkj5n

[glusterfs]
sir-98p8j2dp glusterfs_devices='[ "/dev/xvdb" ]'
sir-2pq8g33p glusterfs_devices='[ "/dev/xvdb" ]'
sir-6z8gkj5n glusterfs_devices='[ "/dev/xvdb" ]'
``` 

error what I got:
```sh
TASK [openshift_storage_glusterfs : Load heketi topology] **********************
changed: [sir-w18rjtnn] => {
    "changed": true, 
    "cmd": [
        "/usr/local/bin/oc", 
        "rsh", 
        "--namespace=glusterfs", 
        "deploy-heketi-storage-1-xtfpf", 
        "heketi-cli", 
        "-s", 
        "http://localhost:8080", 
        "--user", 
        "admin", 
        "--secret", 
        "mJKFHcKtImYUhezlenouYwAf8Q48lFgABaTxoX4paJc=", 
        "topology", 
        "load", 
        "--json=/tmp/openshift-glusterfs-ansible-qg81xw/topology.json", 
        "2>&1"
    ], 
    "delta": "0:00:08.833600", 
    "end": "2017-08-16 09:18:33.270592", 
    "failed": false, 
    "failed_when_result": false, 
    "rc": 0, 
    "start": "2017-08-16 09:18:24.436992"
}

STDOUT:

Creating cluster ... ID: 0a294f18b26891e9e83793146bb6e195
  Creating node ip-10-0-1-145.eu-central-1.compute.internal ... ID: 12f2ff53810234e04cdc034f69d39335
    Adding device /dev/xvdb ... OK
  Creating node ip-10-0-1-82.eu-central-1.compute.internal ... ID: 44fdb837f77a49341ce7878fd7391ac9
    Adding device /dev/xvdb ... OK
  Creating node ip-10-0-1-26.eu-central-1.compute.internal ... ID: 8dfe002d322470c3286be6fdbd5d8aee
    Adding device /dev/xvdb ... OK

TASK [openshift_storage_glusterfs : Create heketi DB volume] *******************
fatal: [sir-w18rjtnn]: FAILED! => {
    "changed": true, 
    "cmd": [
        "/usr/local/bin/oc", 
        "rsh", 
        "--namespace=glusterfs", 
        "deploy-heketi-storage-1-xtfpf", 
        "heketi-cli", 
        "-s", 
        "http://localhost:8080", 
        "--user", 
        "admin", 
        "--secret", 
        "mJKFHcKtImYUhezlenouYwAf8Q48lFgABaTxoX4paJc=", 
        "setup-openshift-heketi-storage", 
        "--listfile", 
        "/tmp/heketi-storage.json"
    ], 
    "delta": "0:00:10.515663", 
    "end": "2017-08-16 09:18:44.627313", 
    "failed": true, 
    "rc": 255, 
    "start": "2017-08-16 09:18:34.111650"
}

STDERR:

Error: Unable to execute command on glusterfs-storage-ljvpr:   /usr/sbin/modprobe failed: 1
  thin: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
command terminated with exit code 255
```

**Comment by sdodson** [comment]
> I know how to fix it manually, but I don't want to use device-mapper, I think no one want :)

Lets say you did want it... what's the solution? :-)  I assume install device-mapper packages.

I imagine the glusterfs solution requires it even if you're using overlayfs for container.

**Comment by SweetOps** [comment]
> Lets say you did want it... what's the solution? :-) I assume install device-mapper packages.

but if I didn't write:

>I know how to fix it manually

Next reply would be " install device-mapper packages" or "change docker storage driver to device-mapper" :)

**Comment by jarrpa** [comment]
@SweetOps I don't know enough about this to be able to come up with a proper solution or workaround. Would it be sufficient for now to document this and then put in a check for device-mapper that would output a more useful error message and fail if it isn't found?

**Comment by SweetOps** [comment]
> Would it be sufficient for now to document this and then put in a check for device-mapper that would output a more useful error message and fail if it isn't found?

@jarrpa, yes it will be good

**Comment by dustymabe** [comment]
I'd like to know what libraries are missing? Fedora 26 atomic host has: 

```
$ rpm -qa | grep device
device-mapper-libs-1.02.137-6.fc26.x86_64
device-mapper-event-1.02.137-6.fc26.x86_64
device-mapper-persistent-data-0.6.3-5.fc26.x86_64
device-mapper-1.02.137-6.fc26.x86_64
device-mapper-event-libs-1.02.137-6.fc26.x86_64
```

**Comment by jarrpa** [comment]
@SweetOps Similarly, what would be a good thing to check for? We'd need something that works both on Atomic and non-Atomic hosts, so can't just check packages. Any file or command we can verify?

**Comment by dustymabe** [comment]
> We'd need something that works both on Atomic and non-Atomic hosts, so can't just check packages. 

Why not? rpm commands work on atomic host

**Comment by jarrpa** [comment]
@dustymabe My bad, I just assumed it'd be containerized. I have no experience with Atomic as of yet. :) Sure, if I can check for or install a specific RPM that's easy.

**Comment by dustymabe** [comment]
> @dustymabe My bad, I just assumed it'd be containerized. I have no experience with Atomic as of yet. :) Sure, if I can check for or install a specific RPM that's easy.

no worries. If you ever have a question about atomic host feel free to ask me (dustymabe on freenode). 

once we find out what is missing from atomic host we can see about getting it added. With atomic host you can "check" to see if an rpm is installed with no problem. Installing an rpm is a different story. Typically the atomic host has not allowed installing rpms but there is support for that now, although it may be discouraged vs other methods of delivering software.

**Comment by SweetOps** [comment]
@jarrpa, I've found the workaround for this issue here https://github.com/gluster/gluster-kubernetes/issues/19 , but didn't test it yet.

**Comment by dustymabe** [comment]
so the solution is to run `modprobe dm_thin_pool` ? this makes sense, but is not really something that can be done from inside the container I don't think (maybe I'm wrong). If i'm right then that would explain why you are getting the error. 

You don't see an issue on hosts that are using the devicemapper storage backend because they already have that kernel module loaded because they are already using devicemapper for the container storage on the node. On hosts with overlay2 we don't have that. 

@jarrpa - what is the plan for "fixing" this?

**Comment by jarrpa** [comment]
@dustymabe Well, currently the only thing I can really think of is to force the installation of the necessary devicemapper RPMs, whatever those may be. Otherwise I could probably use http://docs.ansible.com/ansible/latest/modprobe_module.html to load the necessary kernel modules directly.

**Comment by dustymabe** [comment]
> @dustymabe Well, currently the only thing I can really think of is to force the installation of the necessary devicemapper RPMs, whatever those may be. 

The rpms should already be installed. So that is not your problem. 

> Otherwise I could probably use http://docs.ansible.com/ansible/latest/modprobe_module.html to load the necessary kernel modules directly.

This is the real solution I believe.

**Comment by dustymabe** [comment]
> Otherwise I could probably use http://docs.ansible.com/ansible/latest/modprobe_module.html to load the necessary kernel modules directly.
> 
> This is the real solution I believe.

One thing we'd need to be sure of is that this modprobe module would actually make it so that the kernel module also got loaded on every boot. It wouldn't be ideal to have to run the play after every reboot.

**Comment by jarrpa** [comment]
Doesn't look like it does, so we'll need to drop something in modprobe.d

**Comment by sdodson** [comment]
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sec-Persistent_Module_Loading.html says we should craft an /etc/modules-load.d/openshift-cns.conf file that lists the file and systemd-modules-load.service will load it.

**Comment by qiancai** [comment]
If docker is using overlay driver, there is no need to install those device-mapper packages and load dm_thin_pool module. IMO, we should remove this module check in the installer accordingly.

**Comment by sdodson** [comment]
@openshift/sig-storage anyone able to provide additional feedback on how to proceed here? The way I'm reading the issue CNS requires a device mapper module be loaded but now there's suggestion that if overlayfs is used that's not necessary, however I'm not sure if that's related or not.

**Comment by SweetOps** [comment]
That error output from heketi, so I think loading modules are required

**Comment by qiancai** [comment]
If that error came from heketi, it need to fix heketi then. There is no technical reason I can think of need that module for overlay driver.

**Comment by jarrpa** [comment]
@sdodson @SweetOps @qiancai At present, this is a strict requirement from heketi. heketi uses LVM to create/manage the filesystems used as bricks for GlusterFS volume. I believe it uses thin-provisioning which in turn would require the presence of dm_thin_pool.

I have it in my TODO list to update the playbooks with checks for the required kernel modules, I'm just also currently dealing with the downstream release cycle. My apologies for the delay.

**Comment by qiancai** [comment]
OK, it looks like could just load that module in heketi then and not depends on docker to load it for you.

**Comment by jarrpa** [comment]
@qiancai Right, my plan is to check for and load any required kernel modules in the ansible script. :)
