### ISSUE TITLE
`oc cluster up --version=latest --metrics` fails with `lookupip.stdout not in ansible_all_ipv4_addresses`

### ISSUE THREAD

**Issue by jpkrohling** [openshift/openshift-ansible#5130]
The latest version of OpenShift Origin (Docker image: `c42a8b7581bf`) fails to setup Origin Metrics with `oc cluster up --version=latest --metrics`. The following can be seen on the logs for a pod of type `openshift-ansible-metrics-job-xxx` in `Error` state :

```
TASK [Warn user about bad openshift_hostname values] ***************************
Friday 18 August 2017  05:26:22 +0000 (0:00:00.231)       0:00:20.096 ********* 
fatal: [127.0.0.1]: FAILED! => {
    "failed": true
}

MSG:

The conditional check 'lookupip.stdout not in ansible_all_ipv4_addresses' failed. The error was: error while evaluating conditional (lookupip.stdout not in ansible_all_ipv4_addresses): Unable to look up a name or access an attribute in template string ({% if lookupip.stdout not in ansible_all_ipv4_addresses %} True {% else %} False {% endif %}).
Make sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable

The error appears to have been in '/usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/validate_hostnames.yml': line 11, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    failed_when: false
  - name: Warn user about bad openshift_hostname values
    ^ here
```

Full logs: https://paste.fedoraproject.org/paste/1YmLuIhqk1MM6FMDVNtW8g

**Comment by debianmaster** [comment]
same issue in 3.7 alpha.

**Comment by debianmaster** [comment]
I could make playbook run  by removing `openshift_hostname`  check at this location
/usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/std_include.yml

**Comment by faust64** [comment]
just met with that exact error message, applying ocp 3.9 scaleup playbook.

I was able to add a `gather_facts: true` somewhere before calling that validate_hostname playbook, and could pass that task.
Now, I'm stuck while installing `/etc/origin/node/node-config.yaml`, as the DNS IP to set in defaults to `ansible_default_ipv4['address']`, which somehow isn't defined either. Couldn't fix that one so far ...

What's going on? How could we be missing such basic facts?
