### ISSUE TITLE
Openshift-ansible pod creation fails with error:  network: open /etc/origin/calico/calico.etcd-client.crt: no such file or directory

### ISSUE THREAD

**Issue by adsri** [openshift/openshift-ansible#5154]
Installed Openshift-ansible with calico.

Installation succeeds, but all pods are in pending state.

[openshift@openshift-master ~]$ oc get pods
NAME                        READY     STATUS    RESTARTS   AGE
alpine                      0/1       Pending   0          30m
docker-registry-1-deploy    0/1       Pending   0          15h
registry-console-1-deploy   0/1       Pending   0          15h
router-1-deploy             0/1       Pending   0          15h

Tried checking oc get events and observed all nodes are in ScheduleDisable state:
[openshift@openshift-master ~]$ kubectl get events
LASTSEEN   FIRSTSEEN   COUNT     NAME                        KIND      SUBOBJECT   TYPE      REASON             SOURCE              MESSAGE
1m         31m         109       alpine                      Pod                   Warning   FailedScheduling   default-scheduler   no nodes available to schedule pods
1m         15h         3264      docker-registry-1-deploy    Pod                   Warning   FailedScheduling   default-scheduler   no nodes available to schedule pods
1m         15h         3269      registry-console-1-deploy   Pod                   Warning   FailedScheduling   default-scheduler   no nodes available to schedule pods
1m         15h         3300      router-1-deploy             Pod                   Warning   FailedScheduling   default-scheduler   no nodes available to schedule pods

[openshift@openshift-master ~]$ oc get nodes
NAME                         STATUS                     AGE       VERSION
openshift-master.akash.com   Ready,SchedulingDisabled   16h       v1.6.1+5115d708d7
openshift-node1.akash.com    Ready,SchedulingDisabled   16h       v1.6.1+5115d708d7
openshift-node2.akash.com    Ready,SchedulingDisabled   16h       v1.6.1+5115d708d7

Moved nodes state to Ready using command:
[openshift@openshift-master ~]$ oadm manage-node openshift-node2.akash.com --schedulable

[openshift@openshift-master ~]$ oc get nodes
NAME                         STATUS    AGE       VERSION
openshift-master.akash.com   Ready     16h       v1.6.1+5115d708d7
openshift-node1.akash.com    Ready     16h       v1.6.1+5115d708d7
openshift-node2.akash.com    Ready     16h       v1.6.1+5115d708d7

Once nodes Status becomes Ready requests are landing on nodes but /var/log/messages giving error
as below:

Aug 22 02:51:47 openshift-node1 origin-node: W0822 02:51:47.562630    7484 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx_default": Unexpected command output nsenter: cannot open /proc/13357/ns/net: No such file or directory
Aug 22 02:51:47 openshift-node1 origin-node: I0822 02:51:47.565229    7484 kubelet.go:1847] SyncLoop (PLEG): "nginx_default(5af6aadb-8706-11e7-b6ec-525400fbd429)", event: &pleg.PodLifecycleEvent{ID:"5af6aadb-8706-11e7-b6ec-525400fbd429", Type:"ContainerStarted", Data:"5b5c08c5c4bd0b6648470143d9cbc54bb627f2c32aa65039a9e40b9a05a0421a"}
Aug 22 02:51:48 openshift-node1 **origin-node**: E0822 02:51:48.206611    7484 remote_runtime.go:86] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = **NetworkPlugin cni failed to set up pod "nginx_default" network: open /etc/origin/calico/calico.etcd-client.crt: no such file or directory**
Aug 22 02:51:48 openshift-node1 origin-node: E0822 02:51:48.206675    7484 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "nginx_default(5af6aadb-8706-11e7-b6ec-525400fbd429)" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod "nginx_default" network: open /etc/origin/calico/calico.etcd-client.crt: no such file or directory
Aug 22 02:51:48 openshift-node1 origin-node: E0822 02:51:48.206748    7484 kuberuntime_manager.go:619] createPodSandbox for pod "nginx_default(5af6aadb-8706-11e7-b6ec-525400fbd429)" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod "nginx_default" network: open /etc/origin/calico/calico.etcd-client.crt: no such file or directory
Aug 22 02:51:48 openshift-node1 origin-node: E0822 02:51:48.206793    7484 pod_workers.go:182] Error syncing pod 5af6aadb-8706-11e7-b6ec-525400fbd429 ("nginx_default(5af6aadb-8706-11e7-b6ec-525400fbd429)"), skipping: failed to "CreatePodSandbox" for "nginx_default(5af6aadb-8706-11e7-b6ec-525400fbd429)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx_default(5af6aadb-8706-11e7-b6ec-525400fbd429)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"nginx_default\" network: open /etc/origin/calico/calico.etcd-client.crt: no such file or directory"
Aug 22 02:51:48 openshift-node1 origin-node: W0822 02:51:48.575368    7484 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx_default": Unexpected command output nsenter: cannot open : No such file or directory

Output of docker ps on each nodes:
[openshift@openshift-node1 ~]$ sudo docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS               NAMES
a7df979055ac        calico/node:v2.4.1      "start_runit"            11 minutes ago      Up 11 minutes                           calico-node
4b472c25fc5c        openshift/node:v3.6.0   "/usr/local/bin/origi"   11 minutes ago      Up 11 minutes                           origin-node

**Observation:** As you can see in the log provided, its trying to find path **/etc/origin/calico/calico.etcd-client.crt** in **origin-node** container instead of **calico-node**.
Provide a brief description of your issue here. For example:

Setup details:
Openshift with 1 master and 2 nodes.
Openshift-ansible: master

**Invertory File**:

[openshift@openshift-master ~]$ cat /etc/ansible/hosts
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=openshift
ansible_become=true
deployment_type=origin
openshift_use_calico=true
os_sdn_network_plugin_name=cni
openshift_use_openshift_sdn=false
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

containerized=true
openshift_release=v3.6.0
openshift_image_tag=v3.6.0
openshift_public_hostname=openshift-master.akash.com
openshift_master_default_subdomain=apps.openshift-master.akash.com
openshift_docker_options="--log-driver json-file"
enable_excluders=false

[masters]
openshift-master.akash.com

[nodes]
openshift-master.akash.com openshift_node_labels="{'zone': 'default'}"
openshift-node1.akash.com openshift_node_labels="{'zone': 'default'}"
openshift-node2.akash.com openshift_node_labels="{'zone': 'default'}"

[etcd]
openshift-master.akash.com

**ansible version**: 
[openshift@openshift-master ~]$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

**Comment by sdodson** [comment]
@srampal can you take a look please?

**Comment by srampal** [comment]
@sdodson I worked on Contiv support which is a different plugin. In this case the issue is with Calico so that team needs to look. cc @ozdanborne  from the Calico team ... please take a look.

**Comment by sdodson** [comment]
@srampal sorry, thanks for the redirection.

**Comment by adsri** [comment]
@ozdanborne can you please see this issue once.

**Comment by ozdanborne** [comment]
@adsri that is bizarre. Can you dump the output of the following:
```
ls /etc/origin/calico/
stat /etc/origin/calico/
ls /etc/cni/net.d/
cat /etc/cni/net.d/*
ls /opt/cni/bin/
```

Which commit of openshift-ansible is this using?

**Comment by adsri** [comment]
@ozdanborne, Please see the output below:
[root@openshift-master openshift]# ls /etc/origin/calico/
calico.etcd-ca.crt  calico.etcd-client.crt  calico.etcd-client.csr  calico.etcd-client.key
[root@openshift-master openshift]# stat /etc/origin/calico/
  File: ‘/etc/origin/calico/’
  Size: 122       	Blocks: 0          IO Block: 4096   directory
Device: 806h/2054d	Inode: 34083354    Links: 2
Access: (0700/drwx------)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:etc_t:s0
Access: 2017-08-24 03:08:07.717600192 -0400
Modify: 2017-08-21 10:33:27.000000000 -0400
Change: 2017-08-21 10:33:29.926918734 -0400
 Birth: -
[root@openshift-master openshift]# ls /etc/cni/net.d/
10-calico.conf
[root@openshift-master openshift]# cat /etc/cni/net.d/*
{
  "name": "calico",
  "type": "calico",
  "ipam": {
    "type": "calico-ipam"
  },
  "etcd_endpoints": "https://openshift-master.akash.com:2379",
  "etcd_key_file": "/etc/origin/calico/calico.etcd-client.key",
  "etcd_cert_file": "/etc/origin/calico/calico.etcd-client.crt",
  "etcd_ca_cert_file": "/etc/origin/calico/calico.etcd-ca.crt",
  "kubernetes": {
    "kubeconfig": "/etc/origin/node/system:node:openshift-master.akash.com.kubeconfig"
  },
  "hostname": "openshift-master.akash.com",
  "policy": {
    "type": "k8s"
  }
}
[root@openshift-master openshift]# ls /opt/cni/bin/
bridge  calico  calico-ipam  cnitool  dhcp  flannel  host-local  ipvlan  loopback  macvlan  noop  ptp  tuning

**Comment by adsri** [comment]
@ozdanborne Any update on the issue?

**Comment by ozdanborne** [comment]
@adsri sorry for the delay. I'm working on a repro for this, hit a few unrelated snags so taking longer than expected.

My hunch is that Calico doesn't work with `containerized=true` out of the box. I'd like to repro myself before I say that for sure. But it basically comes down to volume mounting all the necessary files (certs, plugins) into the origin container.

Calico could certainly work in that situation with a little tweaking, so if that is indeed the cause, I'd happily work together to merge that functionality upstream.

**Comment by ozdanborne** [comment]
@adsri Can you rerun all the commands from my previous comment, but preceeding them with `docker exec origin-node ...`?

I've mostly repro'd the problem, and my above comment seems to be the problem. Though I'm surprised to see that your nodes entered a Ready state at all. I would have expected that since the CNI plugin was not mounted into the `origin-node` container, the node would never become Ready. Did you add custom volume mounts?
