### ISSUE TITLE
reencrypt certs path is not resolved to env variables 

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-ansible#5155]
If we use environment variables in our inventory files (and from what I seen we do this everywhere where We deploy OCP) our fact engine ignores env variables so if my path looks like
```
openshift_hosted_registry_routecertificates={"certfile": "{{inventory_dir}}/../files/certs/wildcard.registry.company.local.crt", "keyfile": "{{inventory_dir}}/../files/certs/wildcard.registry.companylocal.key", "cafile":"{{inventory_dir}}/../files/certs/CompanyLocalRootCA.crt"} 
openshift_hosted_registry_routehost=containers.registry.comany.local
```
the result is: `/../files/certs/RoSLocalRootCA.crt`

We need to fix our fact set in a long run to read Ansible variables. And it was done in the same way with router certificates already.

**Comment by mangirdaz** [comment]
https://github.com/openshift/openshift-ansible/pull/5156
