### ISSUE TITLE
Setting Kubernetes API args

### ISSUE THREAD

**Issue by gevorg15** [openshift/openshift-ansible#5166]
#### Description

There is an option to pass in kubelet arguments via the "openshift_node_kubelet_args" flag but I don't see any way of passing in args to the kuberenets API server.  Am I missing something or is it not possible at this time?

I'm looking to basically be able to set "--kubelet-preferred-address-types" based on the docs here: https://kubernetes.io/docs/admin/kube-apiserver/

##### Version

Ansible 2.3.2.0

openshift-ansible-3.6.173.0.7-1-4-ga74df94a

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.ose.example#L305-L306 controls kubernetesMasterConfig.apiServerArguments

**Comment by gevorg15** [comment]
Yep. Thank you!
