### ISSUE TITLE
Advanced installer failed with default configuration

### ISSUE THREAD

**Issue by ksemaev** [openshift/openshift-ansible#5169]
Advanced installer failed with default configuration

##### Version
release-1.5

##### Steps To Reproduce
1. create  Single Master and Multiple Nodes Inventory File (https://docs.openshift.org/latest/install_config/install/advanced_install.html#single-master )
2. ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml

##### Current Result
All nodes and masters:
TASK [set_fact] 
fatal: [opsmaster.domain]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'deployment_type' is undefined\n\nThe error appears to have been in '/root/openshift-ansible/playbooks/common/openshift-cluster/initialize_facts.yml': line 18, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      openshift_docker_hosted_registry_network: \"{{ hostvars[groups.oo_first_master.0].openshift.common.portal_net }}\"\n  - set_fact:\n    ^ here\n"}

##### Expected Result
Suscessful installation

##### Additional Information
inventory has a line: openshift_deployment_type=origin

```
 git describe
openshift-ansible-3.5.119-1
```

**Comment by ksemaev** [comment]
TASK [set_fact] *************************************************************************************************************************************
fatal: [secretnet.test]: FAILED! => {
    "failed": true
}

MSG:

the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'deployment_type' is undefined

The error appears to have been in '/root/openshift-ansible/playbooks/common/openshift-cluster/initialize_facts.yml': line 18, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      openshift_docker_hosted_registry_network: "{{ hostvars[groups.oo_first_master.0].openshift.common.portal_net }}"
  - set_fact:
    ^ here

**Comment by ksemaev** [comment]
Running with extra options helps:
`ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml -e deployment_type=origin`

**Comment by abutcher** [comment]
We're unfortunately requiring `deployment_type` to be set as things are written now which doesn't line up with the default inventory in the documentation.

https://github.com/openshift/openshift-ansible/blob/release-1.5/playbooks/common/openshift-cluster/initialize_facts.yml#L19
https://github.com/openshift/openshift-ansible/blob/release-1.5/roles/openshift_facts/tasks/main.yml#L77

**Comment by ksemaev** [comment]
@abutcher Should I create issue for documentation repo, that they should add `-e deployment_type=origin` option to pass to installer?
