### ISSUE TITLE
GlusterFS play failing with undefined variable, r_openshift_storage_glusterfs_firewall_enabled

### ISSUE THREAD

**Issue by dougbtv** [openshift/openshift-ansible#5187]
#### Description

During a run of the BYO inventory method of running the OpenShift-Ansible playbooks, the playbook fails noting that the variable `r_openshift_storage_glusterfs_firewall_enabled` is undefined, and specifically failing with:

```
The conditional check 'r_openshift_storage_glusterfs_firewall_enabled | bool and not r_openshift_storage_glusterfs_use_firewalld | bool' failed. The error was: error while evaluating conditional (r_openshift_storage_glusterfs_firewall_enabled | bool and not r_openshift_storage_glusterfs_use_firewalld | bool): 'r_openshift_storage_glusterfs_firewall_enabled' is undefined
```

[This appears to be the line with an undefined variable](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_storage_glusterfs/tasks/firewall.yml#L2), specifically it's `r_openshift_storage_glusterfs_firewall_enabled`

Apparently there are comments inline notes @ [this commit](https://github.com/openshift/openshift-ansible/commit/6ff354437718584783589c3403cefe9d1b75ee52) by @bacek and @kwoodson (thanks for noticing)

##### Version

Ansible version

```
$ ansible --version
ansible 2.3.1.0
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

Git clone version

```
$ git describe
openshift-ansible-3.7.0-0.104.0-10-g2a4f954
```

##### Steps To Reproduce
1. Run openshift ansible with: `ansible-playbook -i my.inventory ./playbooks/byo/config.yml`

Where your inventory (among other facets) has:

```
[glusterfs]
# hosts here

[glusterfs:vars]
glusterfs_devices=[ "/dev/somedev" ]
```

##### Expected Results

Runs without undefined variable.

##### Observed Results

Playbook fails with:

```
The conditional check 'r_openshift_storage_glusterfs_firewall_enabled | bool and not r_openshift_storage_glusterfs_use_firewalld | bool' failed. The error was: error while evaluating conditional (r_openshift_storage_glusterfs_firewall_enabled | bool and not r_openshift_storage_glusterfs_use_firewalld | bool): 'r_openshift_storage_glusterfs_firewall_enabled' is undefined
```

I can see the variable is used but never set...

```
$ grep -Prin "r_openshift_storage_glusterfs_firewall_enabled" *
roles/openshift_storage_glusterfs/tasks/firewall.yml:2:- when: r_openshift_storage_glusterfs_firewall_enabled | bool and not r_openshift_storage_glusterfs_use_firewalld | bool
roles/openshift_storage_glusterfs/tasks/firewall.yml:22:- when: r_openshift_storage_glusterfs_firewall_enabled | bool and r_openshift_storage_glusterfs_use_firewalld | bool
```

I can work around the issue by specifically setting the variable...

```
$ ansible-playbook -i my.inventory ./playbooks/byo/config.yml -e 'r_openshift_storage_glusterfs_firewall_enabled=false'
```

And [my current entire inventory is here](https://gist.github.com/dougbtv/8118da0f9c73e468faefcb5e83792985) -- including variables I added for a workaround.

namely the `[glusterfs:vars]` section now reads:

```
[glusterfs:vars]
glusterfs_devices=[ "/dev/vdc" ]
r_openshift_storage_glusterfs_use_firewalld=true
r_openshift_storage_glusterfs_firewall_enabled=true
openshift_storage_glusterfs_timeout=600
openshift_storage_glusterfs_wipe=true
```
Note that I had to set both `r_openshift_storage_glusterfs_use_firewalld` and `r_openshift_storage_glusterfs_firewall_enabled`. And I also had the hosts using firewalld, as you might expect, which also includes adding the variables like so:

```
[OSEv3:vars]
# ...more here
os_firewall_use_firewalld=true
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* CentOS 7
* [Inventory](https://gist.github.com/dougbtv/8118da0f9c73e468faefcb5e83792985) including work-around here

**Comment by kwoodson** [comment]
Thanks for reporting this.  This should be fixed with this PR https://github.com/openshift/openshift-ansible/pull/5168.

**Comment by dustymabe** [comment]
seemed to work for me FYI
