### ISSUE TITLE
openshift_image_tag check doesn't allow tags like v3.7.0-0.104.0

### ISSUE THREAD

**Issue by jmencak** [openshift/openshift-ansible#5192]
#### Description

Provide a brief description of your issue here. For example:

openshift_image_tag check doesn't allow tags like v3.7.0-0.104.0

##### Version

$ ansible --version
ansible 2.3.1.0
  config file = /root/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

$ git describe
openshift-ansible-3.7.0-0.105.0-2-g4811a62

##### Steps To Reproduce
1. run the installer with "openshift_image_tag=v3.7.0-0.104.0"

##### Expected Results
No error message and installer continuing with the installation.

##### Observed Results

    TASK [openshift_version : (Enterprise) Verify openshift_image_tag is valid] *******************
    task path: /root/openshift-ansible/roles/openshift_version/tasks/main.yml:63
    fatal: [ip-172-31-8-189.us-west-2.compute.internal]: FAILED! => {
        "assertion": false,
        "changed": false,
        "evaluated_to": false,
        "failed": true
    }
    
    MSG:
    
    openshift_image_tag must be in the format v#.#[.#[.#]]. Examples: v1.2, v3.4.1, v3.5.1.3, v1.2-1, v1.2.3-4
    You specified openshift_image_tag=v3.7.0-0.104.0
            to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry
    
    PLAY RECAP ************************************************************************************
    ip-172-31-8-189.us-west-2.compute.internal : ok=58   changed=1    unreachable=0    failed=1
    localhost                  : ok=11   changed=0    unreachable=0    failed=0
    
    
    Failure summary:
    
      1. Host:     ip-172-31-8-189.us-west-2.compute.internal
         Play:     Determine openshift_version to configure on first master
         Task:     openshift_version : (Enterprise) Verify openshift_image_tag is valid
         Message:  openshift_image_tag must be in the format v#.#[.#[.#]]. Examples: v1.2, v3.4.1, v3.5.1.3, v1.2-1, v1.2.3-4
                   You specified openshift_image_tag=v3.7.0-0.104.0

##### Additional Information
ansible host:
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)

openshift host:
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Atomic Host release 7.4

**Comment by sdodson** [comment]
They've changed the pre-release tagging format so we need to accommodate this.

**Comment by ashcrow** [comment]
@sdodson I can take care of updating the regex
