### ISSUE TITLE
Installer changes docker's log driver 

### ISSUE THREAD

**Issue by ksemaev** [openshift/openshift-ansible#5193]
#### Description

Ansible installer changes docker's log driver, which prevents OS from cretaing log symlinks.

##### Version
ansible 2.3.1.0
openshift-ansible-3.5.119-1
oc v3.6.0

##### Steps To Reproduce
1. set default docker log driver in /etc/sysconfig/docker:
`OPTIONS=' --selinux-enabled  --log-driver=json-file'`
2. run standard installation with master and several nodes
3. check /etc/sysconfig/docker content

##### Expected Results
--log-driver=json-file'

##### Observed Results
--log-driver=journald'

##### Additional Information
The problem with journald is that openshift is not creating simlinks with container names in /var/log/containers/, so you can't get them with filebeat etc. and have to change --log-driver manually and restart docker service on every node for log files to appear.

**Comment by sdodson** [comment]
Yeah, we overwrite whatever is there with the default encoded in the installer, you can override this by setting `openshift_docker_options="--log-driver=json-file"

**Comment by ksemaev** [comment]
@sdodson can please show manual or some link of how you take logs from journald? json-files in /var/log/containers/ are very handy, there must be a reason why you're resetting it to journald, is it more convenient?

**Comment by sdodson** [comment]
I'm not familiar with the reasoning why. @richm and @portante may be able to answer that quesiton.

**Comment by richm** [comment]
The journal logs have much, much more metadata than what is available from the json-file logs.  This is really useful for doing deep inspection of problems, identifying long term trends, advanced correlations, etc.

origin-aggregated-logging uses fluentd with the fluent-plugin-systemd to read logs from the journal.  When docker is configured with `--log-driver=journald`, docker/kubernetes will add several `CONTAINER_*` fields which have the same sort of metadata you would get with the json-file logs in /var/log/containers.

https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/generate_throttle_configs.rb#L130

https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/configs.d/openshift/filter-retag-journal.conf

https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/configs.d/openshift/filter-k8s-meta.conf

https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/README.md

https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/configs.d/openshift/filter-k8s-record-transform.conf
