### ISSUE TITLE
logging es-ops install broken - no cpu limit

### ISSUE THREAD

**Issue by richm** [openshift/openshift-ansible#5206]
@ewolinetz @jcantrill tl;dr logging CI is broken

#### Description

doing a logging install with the ops cluster - get this error when trying to create the es-ops dc:
```
TASK [openshift_logging_elasticsearch : Set ES dc] *****************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_logging_elasticsearch/tasks/main.yaml:287
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "generated_timestamp": "2017-08-24 17:54:39.678096",
    "msg": {
        "cmd": "/bin/oc create -f /tmp/openshift-logging-ansible-q5PRfK/templates/logging-es-dc.yml -n logging",
        "results": {},
        "returncode": 1,
        "stderr": "Error from server (BadRequest): error when creating \"/tmp/openshift-logging-ansible-q5PRfK/templates/logging-es-dc.yml\": DeploymentConfig in version \"v1\" cannot be handled as a DeploymentConfig: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'\n",
        "stdout": ""
    }
}
```
Of course, the error message is almost totally unhelpful 👎 . . .
Fortunately, I was able to tell by visual inspection of `tmp/openshift-logging-ansible-q5PRfK/templates/logging-es-dc.yml`:
```
          resources:
            limits:
              memory: "8Gi"
              cpu: ""
```
This commit broke it: https://github.com/openshift/openshift-ansible/commit/6e498385ab56a1ec3dab84972a160c4bc200919b

The reason is that the default value for `openshift_logging_es_ops_cpu_limit` is `null`: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging/defaults/main.yml#L128

which I guess translates into a string value of `""` in the template.

The non-ops case is broken too, but it works because it uses the default value:

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging/tasks/install_logging.yaml#L88

Since it doesn't specify `openshift_logging_elasticsearch_cpu_limit`, it uses the default value : https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging_elasticsearch/tasks/main.yaml#L281

Which is set here: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging_elasticsearch/defaults/main.yml#L9

Is the setting of `null` for the default value intentional?  Does that mean "omit the cpu limit"?  If so, it would be better to just omit the default, and in the es.j2 template check if the value is defined.  Or does  null mean "use the default value from openshift_logging_elasticsearch_cpu_limit"?

If it is not intentional, then it should be explicitly set to e.g. `1000m` and the value should be always passed in to the openshift_logging_elasticsearch role in openshift_logging/tasks/install_logging.yaml for both the non-ops and the ops case.

Provide a brief description of your issue here. For example:

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by jcantrill** [comment]
A quick search of the code there does not appear to be any specific logic tied to this value other then in the template.  I think the error is just an unfortunate side effect to the changes.  The intention is: "exclude cpu from template gen when value is not provided" but I vaguely recall we had issues with using the default of 'none' and wanting it to be parsed as python None vs the string 'none'.  I'll play with it some to see what I may do to correct it
