### ISSUE TITLE
Setting a default storage class

### ISSUE THREAD

**Issue by gevorg15** [openshift/openshift-ansible#5233]
#### Description

Is there a way to set the default storage class in the ansible playbook? i'm using native glusterfs as my persistent storage.  The problem is that it is the only storage class available and is not defined as the default storage class.  When logging and metrics attempt to start up, they fail because persistent volume are trying to be created with no storage class assigned.  They just sit there with the volumes forever spinning in a "Creating" state.

I can set the storage class to default after the cluster has been built but that means all my logging, metrics and any other service that wants persistent volumes will not function unless i destroy and re-create them after the cluster is up.

**Comment by jstuever** [comment]
I'm curious if this is related to #5236. I'm experiencing a similar issue when using openstack cloud provider integration. This bug was introduced in 3.6; the exact same settings worked fine in 3.5.

**Comment by rabem00** [comment]
Same issue here, I looked but cannot find a setting for using in the inventory. There should be a way to set a default storageclass from within the inventory.

**Comment by malagant** [comment]
This would make perfectly sense.

**Comment by Ananasr** [comment]
Any update on this ?
