### ISSUE TITLE
Service catalog playbook failures on subsequent runs with: spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by dougbtv** [openshift/openshift-ansible#5243]
#### Description

After having successful runs of the openshift-ansible playbook, then running the `./playbooks/byo/openshift-cluster/service-catalog.yml` play -- upon multiple runs of this play it fails on the "Set Service Catalog API Server service" play (found [at this line](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_service_catalog/tasks/install.yml#L175)).

It fails with:

```
TASK [openshift_service_catalog : Set Service Catalog API Server service] *******************************************
Saturday 26 August 2017  23:47:04 +0000 (0:00:00.725)       0:01:28.094 ******* 
fatal: [openshift-master]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

{u'returncode': 1, u'cmd': u'/bin/oc replace -f /tmp/openshift-service-catalog-ansible-CpQsCJ/service_catalog_api_service.yml -n kube-service-catalog', u'results': {}, u'stderr': u'The Service "apiserver" is invalid: spec.clusterIP: Invalid value: "": field is immutable\n', u'stdout': u''}
```

##### Version

Ansible version

```
$ ansible --version
ansible 2.3.1.0
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

Git describe:

```
$ git describe
openshift-ansible-3.7.0-0.117.0-8-gcc45402

```

##### Steps To Reproduce
1. After a successful run of openshift-ansible, then run: `ansible-playbook -i my.inventory ./playbooks/byo/openshift-cluster/service-catalog.yml`

With your inventory containing:

```
openshift_enable_service_catalog=true
openshift_service_catalog_image_prefix=openshift/origin-
openshift_service_catalog_image_version=latest
```

Per [this doc](https://docs.openshift.org/latest/install_config/install/advanced_install.html#enabling-service-catalog).

##### Expected Results

Playbook completes without error.

##### Observed Results

Firstly -- I am having trouble having the playbook complete at all when having `openshift_enable_service_catalog=true` at all. In part because the first time I run the playbook I have the playbook fail with:

E.g. I have this in my inventory:

```
openshift_enable_service_catalog=true
openshift_service_catalog_image_prefix=openshift/origin-
openshift_service_catalog_image_version=latest
```

Then I run the playbook with: `ansible-playbook -i my.inventory ./playbooks/byo/openshift-cluster/service-catalog.yml`

```
TASK [ansible_service_broker : validate Dockerhub registry settings] ************************************************
Saturday 26 August 2017  23:41:11 +0000 (0:00:00.052)       0:04:05.060 ******* 
fatal: [openshift-master]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

To use the dockerhub registry, you must provide the ansible_service_broker_registry_user. ansible_service_broker_registry_password, and ansible_service_broker_registry_organization parameters
```

So, then I modify the inventory to add the registry user, password and organization (although, I'm unsure what I should be putting in there, as [the docs](https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-ansible-service-broker) state that:

> [ ansible_service_broker_registry_user, password, organization are]Only required if ansible_service_broker_registry_url is set to a registry that requires authentication for pulling APBs.

I then I have an inventory that looks like:

```
openshift_enable_service_catalog=true
openshift_service_catalog_image_prefix=openshift/origin-
openshift_service_catalog_image_version=latest
ansible_service_broker_registry_user=michaelangelo
ansible_service_broker_registry_password="1sapartyd00d"
ansible_service_broker_registry_organization=ninjaturtles
```
Include registry authentication that is... well, essentially bogus cause I'm not sure what registry is being used.

So then I run the playbook again, same command, and it fails with:

```
TASK [openshift_service_catalog : Set Service Catalog API Server service] *******************************************
Saturday 26 August 2017  23:47:04 +0000 (0:00:00.725)       0:01:28.094 ******* 
fatal: [openshift-master]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

{u'returncode': 1, u'cmd': u'/bin/oc replace -f /tmp/openshift-service-catalog-ansible-CpQsCJ/service_catalog_api_service.yml -n kube-service-catalog', u'results': {}, u'stderr': u'The Service "apiserver" is invalid: spec.clusterIP: Invalid value: "": field is immutable\n', u'stdout': u''}
```

This will then happen on each subsequent run, so, I'm stumped, and at this point have been tearing down the cluster and re-running an entire openshift-ansible. 

Any eyes / ideas appreciated, and thanks!

##### Additional Information

* CentOS 7
* [full inventory](http://pasteall.org/532835)

**Comment by ewolinetz** [comment]
@fabianvf do you have an idea what is going on with the ASB validation part?

@dougbtv There is a slight issue with how our module handles the creation/updating of service objects. 
I can see if we can make it behave correctly... In the mean time, you can `oc delete` the service and then rerun the playbook to get past that error.

**Comment by dougbtv** [comment]
Much appreciated on that tip regarding the creation/update of service objects -- indeed, if I first find the `apiserver` service that's giving that play some trouble, and then delete it, I can re-run the playbook without it failing at that step, specifically:

```
[centos@openshift-master ~]$ oc delete svc apiserver --namespace=kube-service-catalog
```

**Comment by fabianvf** [comment]
@dougbtv this definitely could be clearer, but upstream the broker will default to using dockerhub as a registry: https://github.com/openshift/openshift-ansible/blob/master/roles/ansible_service_broker/vars/default_images.yml#L10

Because you aren't able to access the dockerhub search API unless you are logged in, we need valid dockerhub login credentials in order to find any serviceclasses that are in dockerhub, in the organization you specify (if you want to try out the services that we build, you can use the organization ansibleplaybookbundle).

**Comment by dougbtv** [comment]
Thanks, @fabianvf appreciate that clarification. Now with [this inventory](http://pasteall.org/533033) in place, I can complete an openshift-ansible run without error.

Relevant lines:

```
openshift_enable_service_catalog=true
openshift_service_catalog_image_prefix=openshift/origin-
openshift_service_catalog_image_version=latest
ansible_service_broker_registry_user=some_valid_dockerhub_user
ansible_service_broker_registry_password="a_valid_password"
ansible_service_broker_registry_organization="an_org"
```

This probably closes out the issue unless @ewolinetz thinks this is relevant for tracking under the linked PR. 

(and likely unrelated) I still see the `asb-xx` pod crashlooping, but [the docs do warn of a similar condition](https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-ansible-service-broker) if you haven't completed the persistent storage part of the configuration, which I haven't completed.

```
[centos@openshift-master ~]$ oc project
Using project "openshift-ansible-service-broker" on server "https://openshift-master.example.local:8443".
[centos@openshift-master ~]$ oc get pods
NAME                    READY     STATUS             RESTARTS   AGE
asb-4275931488-7ck3w    0/1       CrashLoopBackOff   39         3h
etcd-3119139199-rzd6s   0/1       Pending            0          3h
[centos@openshift-master ~]$ oc logs  asb-4275931488-7ck3w
Using config file mounted to /etc/ansible-service-broker/config.yaml
============================================================
==           Starting Ansible Service Broker...           ==
============================================================
ERROR: Failed to read config file
yaml: unmarshal errors:
  line 2: cannot unmarshal !!map into []registries.Config
[centos@openshift-master ~]$ oc exec -it asb-4275931488-7ck3w -- cat /etc/ansible-service-broker/config.yaml
error: unable to upgrade connection: container not found ("asb")
```

**Comment by fabianvf** [comment]
@dougbtv hmm, although the crashloop is expected, I think this is actually crashing for a different reason. It looks like your config is invalid, if I had to guess it's because the broker has changed and is expecting a different config file format. The broker config is actually a mounted configmap, could you do `oc describe configmaps` and paste the result so I can have a look?

**Comment by dougbtv** [comment]
Thanks @fabianvf -- here's the configmap...

```
[centos@openshift-master ~]$ oc describe configmaps
Name:		broker-config
Namespace:	openshift-ansible-service-broker
Labels:		app=ansible-service-broker
Annotations:	<none>

Data
====
broker-config:
----
registry:
  name: "dockerhub"
  url:  ""
  user: "[redacted]"
  pass: "[redacted]"
  org:  "[redacted]"
dao:
  etcd_host: etcd
  etcd_port: 2379
log:
  logfile: /var/log/ansible-service-broker/asb.log
  stdout: true
  level: "info"
  color: true
openshift: {}
broker:
  dev_broker: false
  launch_apb_on_bind: false
  recovery: true
  output_request: false
  bootstrap_on_startup: true
```

**Comment by ewolinetz** [comment]
@dougbtv the installer side of things should now be resolved so you wouldn't need to delete the svc between reruns

**Comment by sdodson** [comment]
This can be closed then?

**Comment by dougbtv** [comment]
Indeed, that does address the issue at hand.

I've discovered a couple other things that might be awry, but, I'll file a more specific issue.

Thanks everyone, much appreciated.
