### ISSUE TITLE
Cannot login using user created by htpasswd on Openshift running HA multi master

### ISSUE THREAD

**Issue by davistran86** [openshift/openshift-ansible#5250]
Hi guys,

I'm using multi master with native load balancing. when I created user using htpasswd on master1, i cannot login with user and password I created. After checking htpasswd file in other master I think that the password is not sync, so when login in if the lb is pointing to master2, there is no user there, so the login failed.

If i copy htpasswd file to master 2, master 3, I can login, but if I create a project on master 1, and next time login the lb point to other master then there is no project :(.

Is this limitation of using htpasswd or did I misconfigured something ? please help, thanks.

I used advanced install method with latest version of openshift origin.

My setup:

> lb
> master1
> master2
> master3
> infra-node
> node1

My ansible hosts file:

```
[OSEv3:children]
masters
nodes
etcd
lb

[OSEv3:vars]

# -- Ansible Configuration -----
ansible_ssh_user=root

# -- OpenShift Version -----
deployment_type=origin

# -- Configures Auth -----
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]


# -- OpenShift Version -----
#openshift_image_tag=v3.6.0
openshift_pkg_version=-3.6.0

#Fix not meet requirement
openshift_disable_check=disk_availability,docker_storage,memory_availability

#Need to check this again:
#containerized=true

# -- Native HA --
openshift_master_cluster_method=native
openshift_master_cluster_hostname=192.168.70.142.nip.io
openshift_master_cluster_public_hostname=192.168.70.142.nip.io	

# -- DNS Configuration -----
openshift_master_default_subdomain=apps.192.168.70.142.nip.io

# -- Metrics Deployment -----
openshift_hosted_metrics_deploy=false

[masters]
192.168.70.141.nip.io
192.168.70.109.nip.io
192.168.87.121.nip.io

[etcd]
192.168.70.141.nip.io
192.168.70.109.nip.io
192.168.87.121.nip.io

[lb]
192.168.70.142.nip.io


[nodes]
192.168.70.141.nip.io
192.168.70.109.nip.io
192.168.87.121.nip.io
192.168.70.69.nip.io openshift_schedulable=True openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
192.168.87.122.nip.io openshift_node_labels="{'region': 'primary', 'zone': 'east'}"

```

**Comment by sdodson** [comment]
In addition to setting the provider you either need to provide a list of usernames and hashes so that openshift-ansible can create the file for you or you need to provide the path to an existing htpasswd file on the host where you're running ansible.

See https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.ose.example#L185-L190
