### ISSUE TITLE
[RFE] accept proxy settings

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-ansible#528]
We should allow for users to provide different proxy settings so that they are propagated accordingly (eg: to /etc/sysconfig/docker, system, etc etc)

**Comment by jdamick** [comment]
+1

**Comment by JohnTheodore** [comment]
+1

**Comment by ReSearchITEng** [comment]
+1

**Comment by nnachefski** [comment]
+1

**Comment by christianh814** [comment]
+1

**Comment by Hellaenergy** [comment]
+1

**Comment by alfredo-quiroga** [comment]
+10

**Comment by sdodson** [comment]
So this is done as #1385 however there's a shortcoming in that we cannot currently push to the registry via dns name https://github.com/openshift/origin/issues/8581 so you'd have to deploy your registry, obtain its service ip, add that to openshift_no_proxy variable and re-run config playbooks.

If anyone wants to submit patches that automate that to improve the situation we'll help review but really we just need to fix the product pushing to registry via dns instead.
