### ISSUE TITLE
Ansible scripts are unable to restart  openshift_node : restart node

### ISSUE THREAD

**Issue by gk529** [openshift/openshift-ansible#5280]
#### Description

Initially i have installed setup (oc  v1.5.1) cluster using ansible and uninstalled same using ansible scripts.
Now on same machines i am trying to freshly install cluster (oc version 3.6), while doing it Handler openshift_node : restart node is failing on all nodes. please check below outputs and help me on whats going wrong

ansible_version: ansible 2.3.1.0
Os: CentOS Linux release 7.3.1611 (Core)

Output of ansible play
============================

RUNNING HANDLER [openshift_node : restart node] **************************************************************************************************************FAILED - RETRYING: restart node (3 retries left).
FAILED - RETRYING: restart node (3 retries left).
FAILED - RETRYING: restart node (3 retries left).
FAILED - RETRYING: restart node (2 retries left).
FAILED - RETRYING: restart node (2 retries left).
FAILED - RETRYING: restart node (2 retries left).
FAILED - RETRYING: restart node (1 retries left).
FAILED - RETRYING: restart node (1 retries left).
FAILED - RETRYING: restart node (1 retries left).
fatal: [node2]: FAILED! => {"attempts": 3, "changed": false, "failed": true, "msg": "Unable to restart service origin-nod
e: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}
fatal: [node1]: FAILED! => {"attempts": 3, "changed": false, "failed": true, "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}
fatal: [infranode]: FAILED! => {"attempts": 3, "changed": false, "failed": true, "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}

RUNNING HANDLER [openshift_node : reload systemd units] ******************************************************************************************************
        to retry, use: --limit @/opt/ansible-scripts/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP ***************************************************************************************************************************************************localhost                  : ok=13   changed=0    unreachable=0    failed=0
infranode : ok=134  changed=35   unreachable=0    failed=1
ocmaster : ok=282  changed=94   unreachable=0    failed=0
node1 : ok=139  changed=38   unreachable=0    failed=1
node2 : ok=134  changed=35   unreachable=0    failed=1
======================================

Output of Node service status in one of node
================================================================
Redirecting to /bin/systemctl status  origin-node.service
● origin-node.service - OpenShift Node
   Loaded: loaded (/etc/systemd/system/origin-node.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/origin-node.service.d
           └─openshift-sdn-ovs.conf
   Active: activating (auto-restart) (Result: exit-code) since Thu 2017-08-31 17:41:24 CEST; 1s ago
     Docs: https://github.com/openshift/origin
  Process: 9395 ExecStopPost=/usr/bin/dbus-send --system --dest=uk.org.thekelleys.dnsmasq /uk/org/thekelleys/dnsmasq uk.org.thekelleys.SetDomainServers array:string: (code=exited, status=0/SUCCESS)
  Process: 9393 ExecStopPost=/usr/bin/rm /etc/dnsmasq.d/node-dnsmasq.conf (code=exited, status=0/SUCCESS)
  Process: 9380 ExecStart=/usr/bin/openshift start node --config=${CONFIG_FILE} $OPTIONS (code=exited, status=255)
  Process: 9377 ExecStartPre=/usr/bin/dbus-send --system --dest=uk.org.thekelleys.dnsmasq /uk/org/thekelleys/dnsmasq uk.org.thekelleys.SetDomainServers array:string:/in-addr.arpa/127.0.0.1,/cluster.local/127.0.0.1 (code=exited, status=0/SUCCESS)
  Process: 9375 ExecStartPre=/usr/bin/cp /etc/origin/node/node-dnsmasq.conf /etc/dnsmasq.d/ (code=exited, status=0/SUCCESS)
 Main PID: 9380 (code=exited, status=255)

Aug 31 17:41:24 node2 systemd[1]: Failed to start OpenShift Node.
Aug 31 17:41:24 node2 systemd[1]: Unit origin-node.service entered failed state.
Aug 31 17:41:24 node2 systemd[1]: origin-node.service failed.
===========================================================

**Comment by ksemaev** [comment]
Please provide  **"journalctl -xe" for details** after the failed restart attempt

**Comment by hbhargav** [comment]
@ksemaev 
"journalctl -xe" reports
could not start DNS, unable to read config file: open /etc/origin/node/resolv.conf: no such file or directory

I think this is related to #5349
