### ISSUE TITLE
Atomic Host Golden Images

### ISSUE THREAD

**Issue by ashcrow** [openshift/openshift-ansible#5290]
#### Description

Great work has been done by @kwoodson to create "golden image" Openshift images to simplify deployment. However, Atomic Host images are not currently covered in the unit of work. Atomic Host is a direct fit for this work based on it's description...

> Use immutable infrastructure to deploy and scale your containerized applications. Project Atomic builds OSes, tools, and containers for cloud native platforms. 

##### Version

master branch

##### Expected Results

Golden images should be available for:

- RHEL Atomic Host
- CentOS Atomic Host
- Fedora Atomic Host

##### Additional Information

- https://github.com/openshift/openshift-ansible/issues/4685
- [card](https://trello.com/c/BA6fitui/461-epic-golden-images)

cc @jtligon @brenton @sdodson @BigN @giuseppe @cgwalters

**Comment by ashcrow** [comment]
Hey guys, just want to make sure this doesn't fall off.

**Comment by ashcrow** [comment]
@kwoodson Tagging in @dustymabe as well. Maybe there is something that Platform Infra can do to help out.

**Comment by cgwalters** [comment]
Broadly speaking anything that applies to a non-Atomic Host could apply equally well to AH.  Presumably this is basically running an Ansible playbook and snapshotting the result?

Are there plans to also do inplace incremental updates?

**Comment by jtligon** [comment]
I don't think there is a plan to do inplace upgrades, but any future work towards it would be greatly helped by running on Atomic Host.

**Comment by sdodson** [comment]
What would we want to bake into the atomic host image? Would that just be the container runtime and node container images pre-pulled and configured for bootstrapping? Could we not just make the node image ready for bootstrapping?

**Comment by ashcrow** [comment]
@sdodson I'd say we'd want to have images already installed in the same way rpms are already installed in the rpm version of RHEL.

**Comment by mrguitar** [comment]
@smarterclayton @kwoodson Atomic is on the roadmap for online. Where are we at for getting support for golden images? This seems like low hanging fruit.

**Comment by cooktheryan** [comment]
:+1: 

@sdodson there are a couple of items based off of things I saw when doing the reference architecture work with atomic.

- Patch based on the installer docker version
- Modify user-data of the scripts @kwoodson created to specify a static user regardless if its Atomic or RHEL. (atomic uses cloud-user by default and rhel uses ec2-user)
- Like @ashcrow mentioned pre-pull images

**Comment by cooktheryan** [comment]
Also, one more item within the AMI code that we currently have we could use the containerized=true variable which would benefit the RHEL AMI as well if it does not already accept it and then Atomic would be able to utilize the same code.

**Comment by ashcrow** [comment]
@cooktheryan 👍 

@smarterclayton / @kwoodson ping 😄

**Comment by ashcrow** [comment]
👋 😄

**Comment by cooktheryan** [comment]
Misfire

**Comment by ashcrow** [comment]
- https://github.com/openshift/openshift-ansible/pull/7057
- https://github.com/openshift/openshift-ansible/pull/7111
