### ISSUE TITLE
Inconsistent fallback hostname on OpenStack

### ISSUE THREAD

**Issue by jsuchenia** [openshift/openshift-ansible#5291]
During investigation of an issue https://github.com/openshift/origin/issues/15910 I found that kubelet code is updating a `nodeName` from an OpenStack metadata service while Ansible scripts are validating it and leaving only IP address. It's creating a problems for Openshift SDN code where it's using original nodeName (not updated from cloud provider)

To avoid this issue I propose to sync behaviour of kubelet and openshift_facts.py by adding in `set_hostname` method behaviour similar to gce:

```
        elif 'cloudprovider' in facts and facts['cloudprovider']['kind'] == 'openstack':
            facts['node']['nodename'] = facts['provider']['metadata']['name']
```
based on code: https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_instances.go#L82

**Comment by jsuchenia** [comment]
I found an issue with my script - internal X.590 certs were generated for full names and IP, not internal short names:

```
[root@oshift-master ~]# oc exec -n openshift-infra hawkular-metrics-wcd3r bash
Error from server: error dialing backend: x509: certificate is valid for oshift-ing1-0.sre.cit-os.tech.ocado.com, 10.118.82.56, not oshift-ing1-0
```

**Comment by pravisankar** [comment]
@jsuchenia  I think you might have figured out the fix.
When we create node config we could provide all hostnames and IPs that will communicate with the 'openshift-infra' node.

```
oc adm create-node-config  --hostnames="oshift-ing1-0.sre.cit-os.tech.ocado.com,10.118.82.56,oshift-ing1-0" ...
```

**Comment by jsuchenia** [comment]
@pravisankar Yes, so there is a workaround - my proposal in this ticket was to fix that in an ansible scripts, to unify behaviour of kubelet code and deployment scripts. If you are using ansible only you can just provide both parameters in an inventory file (https://github.com/openshift/origin/issues/15910#issuecomment-351947767)
