### ISSUE TITLE
htpasswd' is unavailable. Please install httpd-tools on the control node

### ISSUE THREAD

**Issue by magick93** [openshift/openshift-ansible#5293]
#### Description

Playbook fails at:

```
TASK [openshift_metrics : fail] *****************************************************************************************************************************************
fatal: [apps.mydomain.com]: FAILED! => {"changed": false, "failed": true, "msg": "'htpasswd' is unavailable. Please install httpd-tools on the control node"}
```

 On a single master install.

##### Version

Please put the following version information in the code block
indicated below.

**ansible --version**
ansible 2.3.0.0
python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

##### Steps To Reproduce
1. Run `ansible-playbook -i inventory.erb ./openshift-ansible/playbooks/byo/config.yml` where the inventory is:
```

[OSEv3:children]
masters
nodes
nfs

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
containerized=true
openshift_release=v3.6.0
openshift_image_tag=v3.6.0
openshift_public_hostname=apps.domain.com
openshift_master_default_subdomain=apps.domain.com
openshift_hosted_metrics_deploy=true
enable_excluders=false
openshift_disable_check=docker_storage
openshift_hosted_metrics_public_url=apps.domain.com

[etcd]
apps.domain.com

[nfs]
apps.domain.com

[masters]
apps.domain.com openshift_schedulable=true

[nodes]
apps.domain.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true

```

##### Expected Results
Expect installation to complete successfully, including installing metrics.

##### Observed Results
Fails with

```
TASK [openshift_metrics : fail] *****************************************************************************************************************************************
fatal: [apps.mydomain.com]: FAILED! => {"changed": false, "failed": true, "msg": "'htpasswd' is unavailable. Please install httpd-tools on the control node"}
	to retry, use: --limit @/home/john/git/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP **************************************************************************************************************************************************************
apps.mydomain.com        : ok=492  changed=38   unreachable=0    failed=1   
localhost                  : ok=14   changed=0    unreachable=0    failed=0   



Failure summary:


  1. Hosts:    apps.mydomain.com
     Play:     Create Hosted Resources
     Task:     openshift_metrics : fail
     Message:  'htpasswd' is unavailable. Please install httpd-tools on the control node
```

**Comment by ewolinetz** [comment]
Do you have `httpd-tools` installed on the machine you're running your playbook from? That's what the error is saying you need to have configured.

**Comment by tbielawa** [comment]
@ewolinetz @magick93 I'm surprised we don't have that documented in our README

https://github.com/openshift/openshift-ansible#setup

```
Install base dependencies:

Requirements:

Ansible >= 2.2.2.0
Jinja >= 2.7
pyOpenSSL
python-lxml
Fedora:

dnf install -y ansible pyOpenSSL python-cryptography python-lxml
```

**Comment by itewk** [comment]
I just ran into this when trying to upgrade metrics on a cluster that was just upgraded from v3.6 to v3.7

**Comment by ewolinetz** [comment]
@itewk can you confirm whether or not you have `httpd-tools` installed on the system you are running ansible from?

**Comment by itewk** [comment]
@ewolinetz i didn't have that or the java package that turned out to be required, as @tbielawa mentioned this should added to the doc, or better yet, just install it as part of the playbook if it is required, it has to be installed anyways, may as well have the play book do it so I don't have any manual steps.

**Comment by ewolinetz** [comment]
I think it makes the most sense to update the docs. We likely don't want our playbooks modifying the control hosts.

**Comment by itewk** [comment]
But if these are required for the playbook then why not just install them? Like, what is the use case for not installing them?

**Comment by ewolinetz** [comment]
We would be modifying a machine that wouldn't be in the list of hosts (which would be unexpected) and we can't assume that the user has root access on the control node (localhost).

**Comment by itewk** [comment]
Maybe I am just a weird user, I would rather have a playbook that works without me having to do anything then have 10 manual steps I have to follow before I can use the automation :). Maybe its just me, it just seems silly to have manual prerequisite steps before an otherwise automated process. 

At least getting the doc updated would be good. Then maybe providing a playbook, or a flag, that can be run or turned on to install the prereqs?

**Comment by vrutkovs** [comment]
`httpd-tools` is optional and required only when `openshift_master_identity_providers` has `htpasswd_auth`, this is why its not listed in requirements.

Control node packages cannot be verified via a playbook, as control node may not have root access

**Comment by itewk** [comment]
@vrutkovs my `openshift_master_identity_providers` is `idm` and I still hit it saying that `httpd-tools` was required....

**Comment by donnydavis** [comment]
This is a frustrating role, maybe a install_deps playbook could optionally be run to automate the setup of the control node. I don't install openshift from an openshift node or master, i use a bastion host as a utility sever for this cluster.
