### ISSUE TITLE
Upgrading from 1.4 to 1.5 (as a step to 3.6) fails on docker-excluder

### ISSUE THREAD

**Issue by rassie** [openshift/openshift-ansible#5324]
#### Description

When upgrading from 1.4 to 1.5, with either `release-1.5` branch or `master`, Ansible fails with `Available origin-docker-excluder version 3.6.0 is higher than the upgrade target version`, because it only extracts the newest version from the repos, which currently contain 3.6.0 as the newest version.

##### Version

```
ansible 2.3.2.0
openshift-ansible-3.5.124-1-4-gf53e034f9
```

##### Steps To Reproduce
1. Have an existing cluster with OpenShift Origin 1.4
2. Postpone upgrades until 3.6.0 is released
3. Try upgrading to 1.5 first with Ansible playbook

##### Expected Results
Upgrade should succeed

##### Observed Results
Upgrade fails with the error message mentioned above. When setting `openshift_enable_excluders=False`, Ansible fails to find the correct Origin package (`No package matching 'origin-1.5.1' found available, installed or updated`)

##### Additional Information

```
CentOS Linux release 7.3.1611 (Core)
```

**Comment by cameronbraid** [comment]
I'm likely to run into the same issue. 

Do you know of a workaround?

**Comment by rassie** [comment]
Unfortunately no. I've tried hacking around it, mostly by setting intermediate versions directly in playbooks. I've managed to finish the 1.5 upgrade playook successfully, however I ended up with a couple of nodes upgraded to 3.6 software, so I basically ended up upgrading to 3.6 without proper 1.5. Afterwards, I had to remove all nodes so they'd auto-register and that was it.

**Comment by adbaldi** [comment]
I'm having the same issue while trying to add nodes to an existing cluster.  The origin cluster is 1.5.1 running on RHEL 7.4.

yum search --showduplicates origin lists the origin-1.5.1-1.el7.x86_64 package, it just doesn't find it when you search for it.  Possibly an alias issue or something with the CentOS repo?

**Comment by adbaldi** [comment]
I ran into a similar issue while trying to add a node to the cluster.  It looks like each openshift version (1.4, 1.5, 3.6, ...) has been broken out into separate yum repos. The openshift-ansible git repo appears to have been updated for this change a week ago.  

I was using a clone of the repo from when we tested the playbook against our dev cluster a few weeks ago.  A quick fix for me was to change the .repo file to reflect the new location.  Here's a link to the 1.5 version of the yum repo:

https://github.com/openshift/openshift-ansible/blob/release-1.5/roles/openshift_repos/files/origin/repos/openshift-ansible-centos-paas-sig.repo

**Comment by bigl0af** [comment]
+1 this issue - it's preventing me from being able to upgrade from 1.4.1 to 1.5.1 (as part of the move to v3.6).

**Comment by disappear89** [comment]
Hi,
you need to delete all repos first:
`grep -r orig /etc/yum.repos.d/`

Than you have to specify the origin version in your inventory file:
```
grep rele /etc/ansible/hosts 
openshift_release=1.5
```

This should fix your problem =)

**Comment by saurabhdevops** [comment]
We face this too while trying to upgrade from 1.5 to 3.6. The same upgrade worked last week flawless. But with the release of 3.7, the upgrade brakes with the similar error. The workaround by @disappear89 doesn't work for us.

**Comment by ksemaev** [comment]
OK, the problem is like @adbaldi mentioned - they've split repos. So we gave old basic repo /etc/yum.repos.d/CentOS-OpenShift-Origin.repo in our system with new /etc/yum.repos.d/CentOS-OpenShift-Origin36.repo.
All you need is rm -f /etc/yum.repos.d/CentOS-OpenShift-Origin.repo on all nodes and masters, so the won't be able to find this 3.7 excluder
