### ISSUE TITLE
Disconnected install fails check for docker image locations

### ISSUE THREAD

**Issue by rikkuness** [openshift/openshift-ansible#5330]
#### Description
 In disconnected install where `osm_etd_image` is being defined to set the location of the etcd image, checks fail as location is hardcoded https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_health_checker/openshift_checks/docker_image_availability.py#L124-L125

##### Version
Ansible: 2.2.3.0
openshift-ansible: v3.6.173.0.21-2.git.0.44a4038

##### Steps To Reproduce
Install against a registry other than `registry.access.redhat.com`

**Comment by sosiouxme** [comment]
This is a result of there being [a lot of different variables involved in determining where to get the various images](https://github.com/openshift/openshift-ansible/issues/4415).

I guess for the limited set of images we're looking for, we need to track them all down and either include them in this check's logic or stop looking for them at all.

@rikkuness thanks, good to hear from someone who's actually experiencing this on the ground. Were there any other images that were problematic on any other systems or just the etcd one? You can always just disable the check to get through the install of course but I would *like* it to actually be helpful.

**Comment by sosiouxme** [comment]
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1480195

**Comment by rikkuness** [comment]
There was a couple but those were because I postfix a string onto the tag as part of a CI process, in my `oreg_url` I can add the postfix there and there's no problems except for some images where I have to again override with variables such as `osn_image` and there was one for the openvswitch image which seems to be again a different format and location to `oreg_url`, I guess most of these issues are covered under #4415 though.

I did skip the checks in the end to get past this particular issue so this issue isn't a showstopper exactly.

**Comment by sosiouxme** [comment]
I'm moving this to bug https://bugzilla.redhat.com/show_bug.cgi?id=1538806
