### ISSUE TITLE
Installation against CentOS 7 overrwrites /dev/null

### ISSUE THREAD

**Issue by paralin** [openshift/openshift-ansible#5331]
I'm running the Ansible setup against 3 CentOS 7 servers, on master, commit dc0e3d21

The installer breaks with unreachable errors, because for whatever reason it seems like it's overwriting /dev/null with a regular file. This literally breaks SSH access to the server, with the error "Couldn't open /dev/null, permission denied".

The step that causes this is the haproxy setup step. The host affected (only one) is the one marked as `lb`.

```
# stat /dev/null
  File: ‘/dev/null’
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 5h/5d   Inode: 413087      Links: 1
Access: (0666/-rw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Context: unconfined_u:object_r:null_device_t:s0
Access: 2017-09-07 16:10:03.515110000 -0400
Modify: 2017-09-07 16:14:02.146869775 -0400
Change: 2017-09-07 16:14:02.146869775 -0400
 Birth: -
```

cc @smarterclayton

**Comment by paralin** [comment]
To resolve the issue:

```
mknod /dev/null c 1 3
chmod 666 /dev/null
```

Running the installer again broke it again in the same way.

**Comment by sdodson** [comment]
Can you confirm that /dev/null exists prior to install? I can't fathom why it wouldn't but who knows. Do you have logs that indicate at which task it fails and the previous tasks that presumably nuked /dev/null ?

**Comment by paralin** [comment]
Yes it exists, you can't ssh without it, and the openshift load balancer install step for haproxy breaks it. I was lucky to have physical access to the server.

**Comment by abutcher** [comment]
I haven't been able to reproduce this with centos7 + lb in the inventory.
