### ISSUE TITLE
Import Centos Image streams fails

### ISSUE THREAD

**Issue by magick93** [openshift/openshift-ansible#5335]
#### Description

Trying to install OpenShift Origin but fails with

```
TASK [openshift_examples : Import Centos Image streams] *****************************************************************************************************************
fatal: [openshift.domain.com]: FAILED! => {"changed": false, "cmd": ["/usr/local/bin/oc", "create", "--config=/etc/origin/master/admin.kubeconfig", "-n", "openshift", "-f", "/etc/origin/examples/image-streams/image-streams-centos7.json"], "delta": "0:00:01.750698", "end": "2017-09-08 12:17:12.836037", "failed": true, "failed_when_result": true, "rc": 1, "start": "2017-09-08 12:17:11.085339", "stderr": "Unable to connect to the server: dial tcp: lookup openshift.domain.com on 213.133.98.98:53: no such host", "stderr_lines": ["Unable to connect to the server: dial tcp: lookup openshift.domain.com on 213.133.98.98:53: no such host"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/anton/git/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP **************************************************************************************************************************************************************
openshift.domain.com        : ok=523  changed=24   unreachable=0    failed=1   
localhost
```

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

Please put the following version information in the code block
indicated below.

**Versions**
- ansible 2.3.0.0
- Branch release-1.5 

```
git describe
openshift-ansible-3.5.124-1-4-gf53e034f9
```

##### Steps To Reproduce
1. Run the following inventory file:
```
[OSEv3:children]
masters
nodes
nfs

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
containerized=true
openshift_release=v1.5
openshift_image_tag=v1.5
openshift_public_hostname=openshift.domain.com
openshift_master_cluster_hostname=openshift.domain.com
openshift_master_default_subdomain=openshift.domain.com
openshift_master_cluster_public_hostname=openshift.domain.com
openshift_hosted_metrics_deploy=true
enable_excluders=false
openshift_disable_check=docker_storage
openshift_hosted_metrics_public_url=metrics.openshift.domain.com
openshift_certificates_redeploy_ca=true

openshift_hosted_metrics_storage_access_modes=['ReadWriteOnce']
openshift_hosted_metrics_storage_nfs_directory=/exports
openshift_hosted_metrics_storage_nfs_options='*(rw,root_squash)'
openshift_hosted_metrics_storage_volume_name=metrics
openshift_hosted_metrics_storage_volume_size=5Gi

openshift_enable_service_catalog=false
openshift_service_catalog_image_prefix=openshift/origin-
openshift_service_catalog_image_version=lates

[etcd]
openshift.domain.com

[nfs]
openshift.domain.com

[masters]
openshift.domain.com openshift_schedulable=true

[nodes]
openshift.domain.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true

```
Using `ansible-playbook -i inventory.erb ./openshift-ansible/playbooks/byo/config.yml `

##### Expected Results
Expect to see OpenShift installed

```
Example command and output or error messages
```

##### Observed Results
Instead installation fails with

```
TASK [openshift_examples : Import Centos Image streams] *****************************************************************************************************************
fatal: [openshift.domain.com]: FAILED! => {"changed": false, "cmd": ["/usr/local/bin/oc", "create", "--config=/etc/origin/master/admin.kubeconfig", "-n", "openshift", "-f", "/etc/origin/examples/image-streams/image-streams-centos7.json"], "delta": "0:00:01.750698", "end": "2017-09-08 12:17:12.836037", "failed": true, "failed_when_result": true, "rc": 1, "start": "2017-09-08 12:17:11.085339", "stderr": "Unable to connect to the server: dial tcp: lookup openshift.domain.com on 213.133.98.98:53: no such host", "stderr_lines": ["Unable to connect to the server: dial tcp: lookup openshift.domain.com on 213.133.98.98:53: no such host"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/anton/git/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP **************************************************************************************************************************************************************
openshift.domain.com        : ok=523  changed=24   unreachable=0    failed=1   
localhost```

**Comment by sdodson** [comment]
It's attempting to contact openshift.domain.com but that name doesn't resolve, do you expect that it should resolve?

**Comment by magick93** [comment]
Yes it show resolve. But I founds this - https://github.com/openshift/openshift-ansible/issues/2412#issuecomment-245180190 - and while the IPv4 resolves, the IPv6 doesnt.

**Comment by magick93** [comment]
Ok, both IPv4 and IPv6 resolve. But now I am stuck on:

`The hostname "openshift.domain.com" for "openshift.domain.com" doesn't resolve to an ip address owned by this host. Please set openshift_hostname variable to a hostname that when resolved on the host in question resolves to an IP address matching an interface on this host. This host will fail liveness checks for pods utilizing hostPorts, press ENTER to continue or CTRL-C to abort.:`

Which makes absolutely no sense as I can ping - both on the master and remotely - the hostname/domain name and it resolves to the IP address.

**Comment by magick93** [comment]
Both 
`dig +short -s openshift.domain.com`
and
`host openshift.domain.com`
show the correct IP address.

**Comment by sdodson** [comment]
When you say the correct ip address, you mean an ip address that's actually bound to an interface on the host? This is a check that's intended to prevent health checks from utilizing a host's public ip address in scenarios where a host has both a public and private ip like AWS, OpenStack, etc.

If you'd like to bypass this check you can set `openshift_override_hostname_check=true`

**Comment by magick93** [comment]
Ok thanks. Will try that.

**Comment by magick93** [comment]
Now it fails on:

```
FAILED - RETRYING: Verify API Server (1 retries left).
fatal: [openshift.domain.com]: FAILED! => {"attempts": 120, "changed": false, "cmd": ["curl", "--silent", "--tlsv1.2", "--cacert", "/etc/origin/master/ca-bundle.crt", "https://openshift.domain.com:8443/healthz/ready"], "delta": "0:00:00.010448", "end": "2017-09-08 19:58:34.056082", "failed": true, "rc": 7, "start": "2017-09-08 19:58:34.045634", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/anton/git/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP **************************************************************************************************************************************************************
openshift.domain.com        : ok=404  changed=90   unreachable=0    failed=1   
localhost                  : ok=10   changed=0    unreachable=0    failed=0  
```

And when I try that url with curl I get:

`curl: (7) Failed to connect to openshift.domain.com port 8443: Connection refused`

**Comment by magick93** [comment]
Even with `openshift_override_hostname_check=true` I still get the below warning:

```
TASK [Warn user about bad openshift_hostname values] ********************************************************************************************************************
[Warn user about bad openshift_hostname values]
The hostname "openshift.domain.com" for "openshift.domain.com" doesn't resolve to an ip address owned by this host. Please set openshift_hostname variable to a hostname that when resolved on the host in question resolves to an IP address matching an interface on this host. This host will fail liveness checks for pods utilizing hostPorts, press ENTER to continue or CTRL-C to abort.:
```

**Comment by magick93** [comment]
Also, I had to ssh to the master and run `openshift start`. Openshift did not start automatically after completing the playbook.

Also, on the master, when I ran `oc login -u system:admin` I was prompted to login. This is a first.

**Comment by magick93** [comment]
As the previous error said connection refused, I sshed to master, and noticed OpenShift wasnt running, so ran `openshift start`. Then on running the playbook again, it fails at the same place, but with different error details.

```
TASK [openshift_examples : Import Centos Image streams] ***************************
fatal: [openshift.domain.com]: FAILED! => {"changed": false, "cmd": ["/usr/local/bin/oc", "create", "--config=/etc/origin/master/admin.kubeconfig", "-n", "openshift", "-f", "/etc/origin/examples/image-streams/image-streams-centos7.json"], "delta": "0:00:00.223235", "end": "2017-09-09 03:33:18.895136", "failed": true, "failed_when_result": true, "rc": 1, "start": "2017-09-09 03:33:18.671901", "stderr": "Unable to connect to the server: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, openshift, openshift.default, openshift.default.svc, openshift.default.svc.cluster.local, 127.0.0.1, 172.17.0.1, 172.30.0.1, <public ip>, not openshift.domain.com", "stderr_lines": ["Unable to connect to the server: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, openshift, openshift.default, openshift.default.svc, openshift.default.svc.cluster.local, 127.0.0.1, 172.17.0.1, 172.30.0.1, <public ip>, not openshift.domain.com"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/anton/git/openshift-ansible/playbooks/byo/config.retry
```

**Comment by dexterac** [comment]
did this get resolved? 
I have recently tried installing Origin 3.7 and get the same error


TASK [openshift_hosted_templates : Create or update hosted templates] **************************************************************************************************************************************
fatal: [master1.example.com]: FAILED! => {"changed": false, "cmd": ["oc", "create", "-f", "/usr/share/openshift/hosted", "--config=/tmp/openshift-ansible-KqynX1/admin.kubeconfig", "-n", "openshift"], "delta": "0:00:00.376833", "end": "2018-02-08 01:15:24.152095", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2018-02-08 01:15:23.775262", "stderr": "Error from server (Forbidden): error when creating \"/usr/share/openshift/hosted/registry-console.yaml\": User \"system:anonymous\" cannot create templates in the namespace \"openshift\": User \"system:anonymous\" cannot create templates in project \"openshift\" (post templates)", "stderr_lines": ["Error from server (Forbidden): error when creating \"/usr/share/openshift/hosted/registry-console.yaml\": User \"system:anonymous\" cannot create templates in the namespace \"openshift\": User \"system:anonymous\" cannot create temp

**Comment by dexterac** [comment]
openshift seems to be installed however 

> `oc login -u system:admin -n default --config=.kube/config `

will prompt for password and fails

**Comment by jjbeber** [comment]
@dexterac any update about this? I'm facing the same issue.

**Comment by dexterac** [comment]
@jjbeber Not yet. I tried all possible solutions and none seem to work.

**Comment by jjbeber** [comment]
@dexterac are you using the one of the release branchs?
