### ISSUE TITLE
how to integrate jenkins(CI/CD) with existing project in openshift

### ISSUE THREAD

**Issue by naveenkumartangallapally** [openshift/openshift-ansible#5337]
Hi,
I was setup my openshift environment and it is working fine.
Now i want to integrate my existing project which was created earlier in my openshift environment with jenkins(CI/CD).

can any one help me how to integrate to CI/CD.

**Comment by gabemontero** [comment]
hey @naveenkumartangallapally 

The OpenShift portfolio has a series of integration points with Jenkins.  Specifically:

- we provide a set of "openshift jenkins" images out of https://github.com/openshift/jenkins; these images are intended to be run from an OpenShift pod; The openshift/jenkins-2-centos7 image is hosted on dockerhub; the openshift3/jenkins-2-rhel7 is hosted on registry.access.redhat.com; there are also Jenkins slave images geared towards the kubernetes cloud plugin (https://github.com/jenkinsci/kubernetes-plugin)

- we provide example templates for provisioning jenkins in openshift ... see https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v3.6/quickstart-templates/jenkins-ephemeral-template.json and https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v3.6/quickstart-templates/jenkins-persistent-template.json

- we provide a series of plugins for interaction with openshift from jenkins ... see our doc at https://docs.openshift.org/latest/using_images/other_images/jenkins.html for a list of the specific plugins and pointers to detailed documentation of each of them

- all of the above is geared toward running jenkins in openshift on a per namespace/project basis (a lot of wiring occurs for example for communicating to openshift from jenkins when used this way), but you can use our plugins in jenkins running outside of openshift; you just have to manually set up credentials, endpoints, etc. .... the details for this out spelled out in each plugin's github repo

- finally, we have a special OpenShift Build strategy for integration with Jenkins pipelines ... see https://docs.openshift.org/latest/dev_guide/builds/build_strategies.html#pipeline-strategy-options
