### ISSUE TITLE
SDN MTU option for Openshift node config

### ISSUE THREAD

**Issue by pravisankar** [openshift/openshift-ansible#534]
PR: https://github.com/openshift/origin/pull/4101 (will be merged soon) introduces MTU option.

Old node config:
```
....
networkPluginName: ""
....
```

New node config:
```
...
networkConfig:
   mtu: 1450
   networkPluginName: ""
...
```
Please update your templates.

**Comment by sdodson** [comment]
@pravisankar So based on https://github.com/openshift/openshift-docs/pull/928/files

The way for us to make this config file change forward and backwards compatible would be to continue setting networkPluginName and add the new struct. Making sure that both plugin names match of course.

@detiber Any input on this? At some point we'll have to start defining config based on version but I'm not sure if you wanted to go ahead and do that now. If so, how do you think we should do it?

**Comment by detiber** [comment]
@sdodson I think for now, it would be best to set both options, as long as it is truly backward compatible.

I think our best bet for managing backwards compatibility will be when we are managing the configs using a module instead of the templates we are currently using.
