### ISSUE TITLE
Package version conflicts when adding an additional host to cluster

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#5341]
#### Description

Adding an additional node to my inventory and re-running playbooks/byo/openshift-cluster/config.yml results in a failed playbook run with package conflicts.

##### Version

Please put the following version information in the code block
indicated below.

```
> ansible --version
ansible 2.3.1.0
  config file = /home/jdetiber/git/github/ansible_v3_vms/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

> git describe
openshift-ansible-3.7.0-0.125.0-47-g756ab33
```

##### Steps To Reproduce
1. Install a cluster
2. Wait for a newer version of openshift is released
3. Add an additional node to the inventory and re-run playbooks/byo/openshift-cluster/config.yml

##### Expected Results
Playbook completes successfully and the version of OpenShift installed matches the existing cluster hosts.

##### Observed Results
atomic-openshift and atomic-openshift-clients package is installed with the latest version available, then playbook hits an error when trying to install the version of atomic-openshift-node that matches the existing cluster hosts.

```
> ansible-playbook playbooks/byo/openshift-cluster/config.yml
...
PLAY RECAP *************************************************************************************************
infra.test.example.com     : ok=116  changed=32   unreachable=0    failed=1   
localhost                  : ok=12   changed=0    unreachable=0    failed=0   
master.test.example.com    : ok=443  changed=59   unreachable=0    failed=0   
node1.test.example.com     : ok=144  changed=14   unreachable=0    failed=0   
node2.test.example.com     : ok=143  changed=12   unreachable=0    failed=0   



Failure summary:


  1. Hosts:    infra.test.example.com
     Play:     Configure nodes
     Task:     Install Node package
     Message:  Error: Package: atomic-openshift-node-3.6.173.0.5-1.git.0.f30b99e.el7.x86_64 (rhaos)
                          Requires: atomic-openshift = 3.6.173.0.5-1.git.0.f30b99e.el7
                          Installed: atomic-openshift-3.6.173.0.21-1.git.0.f95b0e7.el7.x86_64 (@rhaos)
                              atomic-openshift = 3.6.173.0.21-1.git.0.f95b0e7.el7
                          Available: atomic-openshift-3.6.173.0.5-1.git.0.f30b99e.el7.x86_64 (rhaos)
                              atomic-openshift = 3.6.173.0.5-1.git.0.f30b99e.el7
```

**Comment by detiber** [comment]
@sdodson This also appears to be related to https://github.com/openshift/openshift-ansible/pull/5208

**Comment by michaelgugino** [comment]
@detiber can you post an example inventory and more output?  I don't see why a conflicting (eg newer) package version would already be installed.

**Comment by michaelgugino** [comment]
I think I have this sorted out.

PR Submitted:  https://github.com/openshift/openshift-ansible/pull/5344

Synopsis: atomic-openshift package is installed on all hosts by openshift_version role without first setting the value of openshift_pkg_version.

**Comment by sdodson** [comment]
Makes sense, none of our CI testing will test this. @detiber is this something you can test?

**Comment by detiber** [comment]
@sdodson @michaelgugino I did a run through with #5344 and was able to get a successful run through with the proper versions installed. Thanks!
