### ISSUE TITLE
Enterprise installation fails behind web proxy

### ISSUE THREAD

**Issue by patlachance** [openshift/openshift-ansible#5348]
#### Description
To ensure ingress and egress network flows will be traced by specific network appliances (proxy and reverse proxy), we need  to deploy Openshift behind a secured internet access point.

Since [Proxy Settings](https://github.com/openshift/openshift-ansible/issues/528) were added to the project, I thought that it would be straightforward but it fails.

Installation process triggered by [openshif-ansible-contrib](https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/aws-ansible) on AWS:
- Deployment type: openshift-enterprise
- Deployment: brownfield + byo bastion
- Network appliances are deployed in a distinct VPC

##### Version

```
atomic-openshift-utils-3.6.173.0.21-2.git.0.44a4038.el7.noarch
openshift-ansible-3.6.173.0.21-2.git.0.44a4038.el7.noarch
```

##### Steps To Reproduce
1. create a dedicated vpc to host the various network functions
2. deploy a custom [NAT instance](https://aws.amazon.com/blogs/security/how-to-add-dns-filtering-to-your-nat-instance-with-squid/) allowing web access to openshift nodes
3. trigger openshift-ansible-contrib deployment using my [custom brownfield + byo bastion template](https://github.com/nxtit-pub-lab-oso/openshift-ansible-contrib/blob/nxtit-pub-lab-oso-patch-1/reference-architecture/aws-ansible/playbooks/roles/cloudformation-infra/files/brownfield-byo-bastion.json.j2)
4 (optional). deploy a reverse proxy and redirect requests for apps.{{public_dns_domain}} and openshift-master.{{public_dns_domain}} to the appropriate ELB

Error will happen before step 4.

##### Expected Results
Installation should succeed as [Proxy Settings](https://github.com/openshift/openshift-ansible/issues/528) were added to the project.

##### Observed Results
- the [rhel_subscribe](../tree/master/roles/rhel_subscribe) role fails.
The error can be fixed by adding **proxy_hostname** and **proxy_port** directives in **/etc/rhsm/rhsm.conf** file.
- the [openshift_health_checker](../tree/master/roles/openshift_health_checker) role fails.
The error can be fixed by adding **http_proxy** configuration in **/etc/environment** file of each hosts.
Error message:
```
<truncated>
  8. Host:     ose-master03.{{public_dns_domain}}
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required Docker images are not available:
                   openshift3/node:v3.6.173.0.21,
                   openshift3/openvswitch:v3.6.173.0.21,
                   openshift3/ose-deployer:v3.6.173.0.21,
                   openshift3/ose-docker-registry:v3.6.173.0.21,
                   openshift3/ose-haproxy-router:v3.6.173.0.21,
                   openshift3/ose-pod:v3.6.173.0.21,
                   openshift3/ose:v3.6.173.0.21,
                   registry.access.redhat.com/openshift3/registry-console,
                   registry.access.redhat.com/rhel7/etcd
               Configured registries: registry.access.redhat.com

The execution of "playbooks/openshift-install.yaml"
includes checks designed to fail early if the requirements
of the playbook are not met. One or more of these checks
failed. To disregard these results, you may choose to
disable failing checks by setting an Ansible variable:

   openshift_disable_check=docker_image_availability
<truncated>
```

##### Additional Information
I'm willing to help fix this but wondering what would be the best option.

**Comment by aizuddin85** [comment]
You also need to configure docker to use proxy to reach external registry. My inventory file for proxy:
```

#comment if no proxy needed.
openshift_http_proxy=http://proxy-am.example.com:8080
openshift_https_proxy=http://proxy-am.example.com:8080
openshift_no_proxy='172.30.0.0/16,172.30.70.186,ose-master.linux.examplel.com,docker-registry.default.svc.cluster.local'
openshift_docker_options="--insecure-registry 172.30.0.0/16"
openshift_master_cluster_public_hostname=ose-master.linux.example.com
openshift_public_hostname=ose-master.linux.example.com
openshift_master_default_subdomain=oseapp.linux.example.com
```

**Comment by Numblesix** [comment]
I have the same issue with a plain origin install proxy are also set in the docker daemon

**Comment by patlachance** [comment]
Thanks all for your help.

Closing as the issue is pretty old now and newer openshift release installation process works as long as - the /etc/environment file on each cluster node defines the required environment variables
- openshift_*_proxy attributes are defined accordingly in the ansible inventory hosts file

But some services aren't yet fully operational when :
- openshift_master_cluster_public_hostname resolves to a public internet IP address
- openshift cluster don't have direct internet access, network traffic need to go thru browsing proxy

See https://github.com/openshift/openshift-ansible/issues/11137#issuecomment-470427530 for more information.
