### ISSUE TITLE
Tuned profile setup broken in openshift_node role

### ISSUE THREAD

**Issue by jmencak** [openshift/openshift-ansible#5351]
#### Description
Tuned profile setup broke between commits  f1d98352736169d51a3ea838b8feea4c07d8cccc and 521b65b2a3c911c926974bd70309434d97e6fd0.

openshift_node role no longer includes tasks/tuned.yaml as introduced in PR5089.

##### Version

commit 29f8833107ce2a350fa4cac3c796de359d005565 fails (openshift-ansible-3.7.0-0.112.0)
commit 521b65b2a3c911c926974bd70309434d97e6fd0d fails (openshift-ansible-3.7.0-0.105.0-14-g521b65b2a)
commit f1d98352736169d51a3ea838b8feea4c07d8cccc ok     (openshift-ansible-3.7.0-0.111.0-2-gf1d983527)

**Comment by jmencak** [comment]
Linking RH BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1477518

**Comment by sdodson** [comment]
Looks like your changes to merge the node boostrapping lost the call to tuned.yml but maybe you were refactoring this in some other way?

**Comment by jmencak** [comment]
Fixed by #5370.  Tested both on RHEL Atomic 7.4 and RHEL 7.4.
