### ISSUE TITLE
The install script for the DNS failed to setting the search section

### ISSUE THREAD

**Issue by linzhaoming** [openshift/openshift-ansible#5372]
#### Description

The install script for the DNS failed to setting the search section, and when setting it manually, it will be aoto reseted by the script.

See the Issue of https://github.com/openshift/origin/issues/16097

I have faced the same problem in my environment of V3.6
Installed by openshift_ansible project, the way is rpm.

I found the cause is 99-origin-dns.sh of networkmanager.

I fixed the problem and verifyed it in my environment. The solutions is adding one echo line to 99-origin-dns.sh

> 

      sed -e '/^nameserver.*$/d' /etc/resolv.conf >> ${NEW_RESOLV_CONF}
      echo "search svc.cluster.local cluster.local" >> ${NEW_RESOLV_CONF}
      echo "nameserver "${def_route_ip}"" >> ${NEW_RESOLV_CONF}

I will make a PR in the openshift_ansible project

**Comment by git001** [comment]
I would suggest do use a sed in #5372, just in case that a search is already defined in the resolv.conf.

```
if grep -q 'search .*' /etc/resolv.conf ; then
  sed -e 's/^search \(.*\)/search \1 svc.cluster.local cluster.local/" /etc/resolv.conf >> ${NEW_RESOLV_CONF}
else
echo "search svc.cluster.local cluster.local" >> ${NEW_RESOLV_CONF}
fi
```

**Comment by rjhowe** [comment]
If creating a PR I would instead suggest using the  IP4_DOMAINS in this script as this pulls the search domains from NetworkManager then append the search with the following values {{ openshift.common.dns_domain }}  and svc.{{ openshift.common.dns_domain }}
