### ISSUE TITLE
Installer should not set `pod_presets: true` for web console extension in 3.7

### ISSUE THREAD

**Issue by spadgett** [openshift/openshift-ansible#5403]
See https://github.com/openshift/origin/issues/16313

When enabling service catalog in 3.7, the installer should no longer set `pod_presets = true`.

https://github.com/openshift/openshift-ansible/blob/9c2d56757c87a6de184605f23090a987ada44952/roles/openshift_service_catalog/files/openshift-ansible-catalog-console.js#L2

Pod presets are not supported in 3.7.

cc @ewolinetz @sdodson

**Comment by spadgett** [comment]
@bparees Is template service broker enabled by default now?

If so, we should add....

```js
window.OPENSHIFT_CONSTANTS.ENABLE_TECH_PREVIEW_FEATURE.template_service_broker = true;
```

**Comment by bparees** [comment]
> @bparees Is template service broker enabled by default now?

not exactly, no.  in any case without the service catalog that the console would be broken with that set to true, right?

**Comment by spadgett** [comment]
Yeah, I guess I was asking if the template broker is always enabled when the service catalog is enabled. In which case, we'd want that set to true.

**Comment by bparees** [comment]
> Yeah, I guess I was asking if the template broker is always enabled when the service catalog is enabled. In which case, we'd want that set to true.

ah.  I don't know (@ewolinetz would) but i agree if that's how we've tied the installer behavior together, it makes sense to also set that additional value.

Certainly we tied them all together in oc cluster up.

**Comment by ewolinetz** [comment]
@spadgett @bparees I haven't heard otherwise yet that we are enabling TSB by default through Ansible, but it should be configurable.

@sdodson Have you heard anything on this yet?

However, it does remind me that as part of the TSB role we should make sure we are setting that value to true [1]

[1] https://github.com/openshift/openshift-ansible/pull/5226

**Comment by bparees** [comment]
> @spadgett @bparees I haven't heard otherwise yet that we are enabling TSB by default through Ansible, but it should be configurable.

I think the discussion really need to be, "are we enabling the TSB when we enable the SC"?

and i think the answer should be no, for the ansible installer i'd expect those to be independent choices (but enabling the TSB w/o the SC is silly.  Enabling the SC w/o the TSB is less silly)

**Comment by ewolinetz** [comment]
@bparees I think that makes sense... so if we are setting up the service catalog we can then check if we're setting up the TSB.

Can the TSB and ASB both be deployed side-by-side and play nice? Or should the decision be -- "we're setting up the service catalog, do you want ASB or TSB?"

**Comment by bparees** [comment]
> Can the TSB and ASB both be deployed side-by-side and play nice?

as far as i know that should be fine.  There's some concern about them both offering up similar looking/sounding entries in the service catalog, but there's no actual technical limitation and there are valid reasons to want both.
