### ISSUE TITLE
Can no longer install older versions of OpenShift Origins as RPM have moved

### ISSUE THREAD

**Issue by gamkiller77** [openshift/openshift-ansible#5404]
#### Description

Provide a brief description of your issue here. For example:

While trying to run the ansible-playbook to install v1.5.1 it keeps giving a warning that there are not packagages for `origin-docker-excluder-1.5.1*`.

When I go and look at the repo that was install by ansible I see in the repo only release 3.6 with no other release any more.  Last week they where there.

Looking in the parent directory of the Centos mirror site i see now a openshift-origin15 which now has all the v1.5.1 rpms.  

Looking at the ansible code it is pointing to `http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/` when it should point to `http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin15/`

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
``` 
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)] 
```

If you're operating from a **git clone**:

* The output of `git describe`
`openshift-ansible-3.5.124-1-6-g354d986`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`
Reports not isntalled

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. Setup the install as normal advance install steps from the website but spell out the version you want to use.
```
openshift_version=1.5.1
openshift_release=v1.5
```
2. Run ansible playbook with extra flag as there is a bug too with that.
`ansible-playbook -i /path/to/hosts /path/to/openshift-ansible/playbooks/byo/config.yml --extra-vars="deployment_type=origin" `

##### Expected Results
Describe what you expected to happen.

I expect that v1.5.1 would install not v3.6.0.

##### Observed Results
Describe what is actually happening.

Only RPMs for release v3.6.0 are found as the RPM repo is broken now.

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

RHEL 7.4

**Comment by michaelgugino** [comment]
Thank you for reporting this issue, the information you provided is very helpful.  I will take a look at this and see about implementing a fix.

**Comment by michaelgugino** [comment]
@gamkiller77 We have already merged a fix for each release branch, master branch fix is in progress.
