### ISSUE TITLE
Add new infra-nodes to openshift cluster ?

### ISSUE THREAD

**Issue by davistran86** [openshift/openshift-ansible#5408]
Hi guys,

Can someone help me about adding new infra node to openshift ? 
Currently I have successfully added new infra node to my openshift cluster. Using "oc get node" I can see it:

```
NAME                           STATUS                     AGE       VERSION
openshift-master1.aavn.local   Ready,SchedulingDisabled   7d        v1.6.1+5115d708d7
openshift-master2.aavn.local   Ready,SchedulingDisabled   7d        v1.6.1+5115d708d7
openshift-master3.aavn.local   Ready,SchedulingDisabled   7d        v1.6.1+5115d708d7
openshift-node1.aavn.local     Ready                      7d        v1.6.1+5115d708d7
openshift-router.aavn.local    Ready                      7d        v1.6.1+5115d708d7
openshift-router2.aavn.local   Ready                      57m       v1.6.1+5115d708d7
```
But on new infra node I did not see any docker container running ?
Do I have to do anything to get it work ? any command ?

I'm using Advanced Install to install openshift.
I added new node by modify /etc/ansible/hosts with [new_nodes]

**Comment by sdodson** [comment]
@davistran86 you probably need to scale up your registry deployment config. `oc scale dc/router --replicas=2`

**Comment by davistran86** [comment]
Hi, just one more question, I got error with pushing image on this new infra node:

> Pushing image docker-registry.default.svc:5000/1111/django:latest ...
> error: build error: Failed to push image: Get https://docker-registry.default.svc:5000/v1/_ping: dial tcp: lookup docker-registry.default.svc on 192.168.70.61:53: no such host
> 

Checking docker info I also get this warning: (router1 does not get this warning)

> WARNING: bridge-nf-call-iptables is disabled
> WARNING: bridge-nf-call-ip6tables is disabled
> 
>

**Comment by sdodson** [comment]
Do you have dnsIP set in /etc/origin/node/node-config.yaml ? there was a bug at one time in openshift-ansible that prevented that from being set but has since been fixed. That should be set to the ip address of the host.

**Comment by davistran86** [comment]
Hi @sdodson yes, after I deleted docker-registry pod and service and rollout it again then the problem has been fixed. Thanks :).

**Comment by pschiffe** [comment]
Hi @sdodson , is it possible with ansible installer to automatically scale up router and registry after adding nodes? With some variable or a plabook? Thanks.

**Comment by sdodson** [comment]
No, not today. I'm not sure how valuable adding this to openshift-ansible
would be when it's just one invocation of `oc scale`. What do you think?

**Comment by pschiffe** [comment]
@sdodson well, it depends. In our reference architectures [1] we are using `openshift_hosted_` roles to deploy registry and router automatically during the deployment, so user doesn't have to deal with that. And once we added option to scale up nodes (which is easy as update `config.yaml` file with new number of nodes and run `./ocp-on-gcp.sh --scaleup` (for GCP)) as a user I would expect that the router and registry would be scaled automatically. For now I'm going to mention this in a paper, but I'll probably implement this in the ref. arch. code later. Also, now it's registry and router, but once monitoring and logging are added.. I think that scaling of the infra pods during the scale up infra nodes should be handled by installer if they were deployed by installer (and all req. variables are set).

[1] https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture
