### ISSUE TITLE
Install Helm

### ISSUE THREAD

**Issue by mazzy89** [openshift/openshift-ansible#5409]
There is a proposal to add an Helm role to install the tiller in the cluster?

**Comment by sdodson** [comment]
No, we've not yet had any requests for that. There's some question as to how Helm and templates interact with each other from my understanding.

**Comment by mazzy89** [comment]
Got it. thanks for the answer

**Comment by smarterclayton** [comment]
There will be a blog post on how to install Helm, but it won't be directly supported since it can easily be installed per namespace and doesn't do multi-tenancy yet.

**Comment by mazzy89** [comment]
I succeed to install it in kube-system namespace with cluster-admin role

**Comment by smarterclayton** [comment]
I'd definitely be happy to take a template for installing helm to examples/helm in the openshift origin repository, but it would still be optional.
