### ISSUE TITLE
 Wait for Node Registration failed due to DNS

### ISSUE THREAD

**Issue by xqianwang** [openshift/openshift-ansible#5422]
#### Description

 could not start DNS, unable to read config file: open /etc/origin/node/resolv.conf: no such file or directory
> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

Openshift origin v3.6

* Your ansible version per `ansible --version`
Openshift origin v3.6
If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`
package atomic-openshift-utils is not installed
package openshift-ansible is not installed

**Comment by xqianwang** [comment]
I was using release-1.5 on azure, there was no issue. However when  I switch to release-3.6, this error happened while installation. So I am pretty sure its a bug.

**Comment by kmurthy1** [comment]
I hit the same issue too. atomic-openshift-node.service does not come up without resolv.conf. Once I manually configured /etc/origin/node/resolv.conf and restarted atomic-openshift-node.service, things were fine.

  ```Sep 28 15:34:22 ovs-3 atomic-openshift-node: F0928 15:34:22.625173     882 start_node.go:140] could not start DNS, unable to read config file: open /etc/origin/node/resolv.conf: no such file or directory
Sep 28 15:34:22 ovs-3 systemd: atomic-openshift-node.service: main process exited, code=exited, status=255/n/a
Sep 28 15:34:22 ovs-3 dnsmasq[31685]: setting upstream servers from DBus
Sep 28 15:34:22 ovs-3 systemd: Failed to start OpenShift Node.
```

**Comment by guhuajun** [comment]
@kmurthy1 Thanks a lot! I have manually copy the file during the retry process, it worked. Service restart is not required.

![image](https://user-images.githubusercontent.com/14121694/43180517-175b0864-900b-11e8-8608-8a6c77f7a7ad.png)
