### ISSUE TITLE
Upgrade from 1.5 to 3.6 fails at "Verify containers are available for upgrade"

### ISSUE THREAD

**Issue by arthfl** [openshift/openshift-ansible#5440]
#### Description

When trying to upgrade an openshift cluster from 1.5 to 3.6, i run into following error:
```
TASK [Verify containers are available for upgrade] ********************************************************************
fatal: [--redacted--]: FAILED! => {"changed": false, "cmd": ["docker", "pull", "openshift/origin:v"], "delta": "0:00:06.047824", "end": "2017-09-18 11:58:13.935727", "failed": true, "rc": 1, "start": "2017-09-18 11:58:07.887903", "stderr": "manifest unknown: manifest unknown", "stderr_lines": ["manifest unknown: manifest unknown"], "stdout": "Trying to pull repository registry.access.redhat.com/openshift/origin ... \nTrying to pull repository registry.access.redhat.com/openshift/origin ... \nTrying to pull repository docker.io/openshift/origin ... ", "stdout_lines": ["Trying to pull repository registry.access.redhat.com/openshift/origin ... ", "Trying to pull repository registry.access.redhat.com/openshift/origin ... ", "Trying to pull repository docker.io/openshift/origin ... "]}
```

It seems that ansible tries to pull _openshift/origin:v_, which doesn't exist.
##### Version
```
$ ansible --version
ansible 2.3.2.0
  config file = /home/flart/workspace/openshift/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]

$ git describe
openshift-ansible-3.7.0-0.126.0-80-gb124c678a
```
##### Steps To Reproduce
1. Have openshift 1.5 running
2. apply this workaround: https://github.com/openshift/origin/issues/16346#issuecomment-330185954
Otherwise you don't even get to this stage :D 
3. run the upgrade playbook

##### Expected Results
A working upgrade to 3.6

##### Observed Results
A failed upgrade (at least this happened in the verification stage)

**Comment by krzysiekneo** [comment]
Workaround: modify for appropriate version (in this case 3.6.0) file:
`playbooks/common/openshift-cluster/upgrades/pre/verify_inventory_vars.yml`
is:
`when: openshift_release is defined and openshift_release[0] == 'v'`
replace with:
`when: openshift_release is defined and openshift_release[0] == 'v3.6.0'`
