### ISSUE TITLE
Installer should not set `service_catalog_landing_page: true` for web console extension in 3.7

### ISSUE THREAD

**Issue by spadgett** [openshift/openshift-ansible#5447]
See https://github.com/openshift/origin-web-console/pull/2078

The new experience is now the default, and the old tech preview flag will be ignored if set.

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_service_catalog/files/openshift-ansible-catalog-console.js

cc @ewolinetz @sdodson

**Comment by ewolinetz** [comment]
Low priority but will make part of https://github.com/openshift/openshift-ansible/pull/5226
