### ISSUE TITLE
Need to add first service ip to master cert

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#545]
Per https://github.com/openshift/origin/pull/4423 we need to add the first service ip to the master's cert.

Probably best to do this via openshift_facts so that we can pull in a python library to compute the subnet range based on the portal CIDR and pick the first ip.

Other problems, what do we do when the services subnet changes?

**Comment by detiber** [comment]
@sdodson Maybe similar to the way that we have the all_hostnames fact, we should also add an all_ips fact, then when we generate the cert we can ensure all known IPs are added as part of the SAN.

imo, we can defer the issue of having to deal with the services subnet changing until we start handling certificate re-generation.

**Comment by abutcher** [comment]
@brenton This issue can be closed. Fix added in #609
