### ISSUE TITLE
imageConfig Required value error on cluster upgrade

### ISSUE THREAD

**Issue by feld-ims** [openshift/openshift-ansible#5455]
Moved from https://github.com/openshift/origin/issues/16388

When upgrading origin cluster from 1.5.1 to 3.6.0 using the ansible installer, some of the nodes have missing values in the node-config.yaml for imageConfig.format, so the origin-node service fails to start. Ensuring these values ARE present before running the upgrade, it continues to happen on random nodes without any real pattern. Installing a fresh 3.6.0 cluster on the same hosts worked without issue.

```
oshift-node-01 origin-node[105243]: Invalid NodeConfig /etc/origin/node/node-config.yaml
oshift-node-01 origin-node[105243]: imageConfig.format: Required value
```

Version

1.5.1 -> 3.6.0

Steps To Reproduce

run the ansible upgrade script
Current Result

cluster upgrade fails

Expected Result

cluster upgrade succeeds

**Comment by sdodson** [comment]
If you can replicate this can you run ansible-playbook with the -vvv option and capture the log? That will illustrate why the value is being reset. Also what's your oreg_url value?

**Comment by feld-ims** [comment]
I never explicitly defined oreg_url. Also replicating will be difficult as this cluster is being actively used. I'll see if a can replicate on a test cluster.

**Comment by jfchevrette** [comment]
I just had the same issue. imageConfig.format is set to ''

oreg_url defaults to '' in roles/openshift_node/defaults/main.yml
oreg_url_node is undefined

I captured a log with -vvv but there is private data in there that I can't post publicly. Let me know if there are specitic parts of the log I can extract and anonymize.

**Comment by jfchevrette** [comment]
The only reference to 'oreg' I found in the log is:

```
TASK [Update oreg value] ******************************
task path: /xyz/ansible/playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml:122
skipping: [node01] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}
```

**Comment by tremble** [comment]
@sdodson We hit this too,

I suspect it's been introduced by 
```
commit 57abb2f092264e8adbecf006d3ea0205bfa39489
Author: Michael Gugino <mgugino@redhat.com>
Date:   Thu Aug 17 22:45:05 2017 -0400
```

What I've seen is that the upgrade playbooks check for undefined *NOT* empty string
```
$ grep -r oreg_url_master *
...
playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml:    when: oreg_url is defined or oreg_url_master is defined
...
```

**Comment by michaelgugino** [comment]
@tremble I think you are correct.  I have submitted a patch to fix this issue.  Once it merges in master, we will get the backports for the other branches ASAP.

**Comment by michaelgugino** [comment]
This issue was filed against 3.6.  Reopening until the backport for 3.6 merges.
