### ISSUE TITLE
Checking Master API from outside the master instance

### ISSUE THREAD

**Issue by edsonmarquezani** [openshift/openshift-ansible#5467]
#### Description

On Azure, setup will fail when setting `openshift_master_cluster_hostname` to a Load Balancer's address, because Azure drops requests to a balancer whose the VM is part of its backend pool. (VM is a master node, behind a balancer, checking API via balancer).

So, the installation stucks at API availability check.

##### Version
```
3.7.0-0.126.4
```

This is a particular scenario for Azure, but an option to work around this would be usefull.

**Comment by sdodson** [comment]
Whick specific task is failing? All the places I see that we're verifying the API we should be checking against a specific host.
