### ISSUE TITLE
Multihost advanced installation fails on Fedora 26

### ISSUE THREAD

**Issue by adelton** [openshift/openshift-ansible#5469]
#### Description

On Fedora 26, with two hosts in the cluster, running `python3 /usr/bin/ansible-playbook -e ansible_python_interpreter=/usr/bin/python3` fails.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

```
# python3 /usr/bin/ansible --version
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.6.2 (default, Aug 11 2017, 11:59:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

If you're operating from a **git clone**:

* The output of `git describe`

```
# git describe
openshift-ansible-3.7.0-0.126.0-110-g993436532
```

##### Steps To Reproduce
1. `python3 /usr/bin/ansible-playbook -e ansible_python_interpreter=/usr/bin/python3 -i ansible-inventory openshift-ansible/playbooks/byo/config.yml`

##### Expected Results

Installation passes.

##### Observed Results
Describe what is actually happening.

```
TASK [Ensure openshift-ansible installer package deps are installed] ***********
ok: [node.example.com] => (item=iproute)
ok: [master.example.com] => (item=iproute)
ok: [node.example.com] => (item=python3-dbus)
changed: [node.example.com] => (item=PyYAML)
ok: [master.example.com] => (item=python3-dbus)
ok: [node.example.com] => (item=yum-utils)
ok: [master.example.com] => (item=PyYAML)
ok: [master.example.com] => (item=yum-utils)

[...]

TASK [Gather Cluster facts and set is_containerized if needed] *****************
fatal: [node.example.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to node.example.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible__20buw8m/ansible_module_openshift_facts.py\", line 16, in <module>\r\n    import yaml\r\nModuleNotFoundError: No module named 'yaml'\r\n", "msg": "MODULE FAILURE", "rc": 0}
ok: [master.example.com]

[...]

RUNNING HANDLER [openshift_master : restart master api] ************************
fatal: [master.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service origin-master-api: Job for origin-master-api.service failed because the service did not take the steps required by its unit configuration.\nSee \"systemctl  status origin-master-api.service\" and \"journalctl  -xe\" for details.\n"}
```

##### Additional Information

On the master, installing `ansible-python3` pulled in `python3-PyYAML`. However, on the node, these are not installed. There is only PyYAML-3.12-3.fc26.x86_64 there likely installed via that `changed: [node.example.com] => (item=PyYAML)` but that does not get used with `ansible_python_interpreter=/usr/bin/python3`.

Manually installing the python3 version of `PyYAML` via `dnf install -y python3-PyYAML` on the node makes things pass but it should not be needed.

**Comment by michaelgugino** [comment]
@adelton Thank you for the filing this issue.  I will get a patch submitted shortly.
