### ISSUE TITLE
Cloud Provider Configuration for Any S3 service (Minio, ExoScale, ...) example needed

### ISSUE THREAD

**Issue by ultimatemanu** [openshift/openshift-ansible#5482]
Hello,

I am trying to setup an Openshift-Origin 3.6 cluster with the ansible playbook on ExoScale which provides s3 compatible storage buckets.
In the https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.ose.example there is an example for setting the registry in such a case:
```
# Any S3 service (Minio, ExoScale, ...): Basically the same as above
# but with regionendpoint configured
# S3 bucket must already exist.
#openshift_hosted_registry_storage_kind=object
#openshift_hosted_registry_storage_provider=s3
#openshift_hosted_registry_storage_s3_accesskey=access_key_id
#openshift_hosted_registry_storage_s3_secretkey=secret_access_key
#openshift_hosted_registry_storage_s3_regionendpoint=https://myendpoint.example.com/
#openshift_hosted_registry_storage_s3_bucket=bucket_name
#openshift_hosted_registry_storage_s3_region=bucket_region
#openshift_hosted_registry_storage_s3_chunksize=26214400
#openshift_hosted_registry_storage_s3_rootdirectory=/registry
#openshift_hosted_registry_pullthrough=true
#openshift_hosted_registry_acceptschema2=true
#openshift_hosted_registry_enforcequota=true
```
For the Cloud Provider Configuration I cannot find such an information. There is only the standard aws configuration there:
```
# Cloud Provider Configuration
#
# Note: You may make use of environment variables rather than store
# sensitive configuration within the ansible inventory.
# For example:
#openshift_cloudprovider_aws_access_key="{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
#openshift_cloudprovider_aws_secret_key="{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
#
# AWS
#openshift_cloudprovider_kind=aws
# Note: IAM profiles may be used instead of storing API credentials on disk.
#openshift_cloudprovider_aws_access_key=aws_access_key_id
#openshift_cloudprovider_aws_secret_key=aws_secret_access_key
```
Has OpenShift some advanced properties for setting any S3 services ? 
Thank you very much in advance

Emmanuel

**Comment by ultimatemanu** [comment]
For the moment we have decided to go on with nfs, which works really well. Anyway, if someone has some info about how to set Openshift for working with S3 compatible services please don't hesitate ;)

Emmanuel

**Comment by sdodson** [comment]
Not being familiar with those myself, what happens if you do set `openshift_cloudprovider_aws_access_key` and `openshift_cloudprovider_aws_secret_key` does that not work?

**Comment by ultimatemanu** [comment]
Hi @sdodson 

No unfortunately this does not work. The keys are not recognized. I my case I  deploy OpensShift with the Ansible script on Exoscale. The Ansible script went through fine (without errors) but trying to create persistent volumes using the S3 service and using them by PVC fails. (Invalid keys error).
I can imagine that we would need a kind of endpoint setting there for telling OpenShift "hey don't  go to aws, please use this other S3 Service endpoint".

Thanks in advance if you have any idea for that ;)

**Comment by sdodson** [comment]
If you can find a reference for how to configure this in kubernetes we can help add it to openshift installer.

**Comment by ultimatemanu** [comment]
Hi @sdodson 
I will try to find it out and let you know.

**Comment by ultimatemanu** [comment]
@sdodson I am closing this issue because I did not find anything that can help you on this. We are using nfs for persistent volumes and it is ok now. We will have also a look at glusterfs ... 
Thanks again.
Emmanuel
