### ISSUE TITLE
Add deployed OpenShift Cluster to existing ManageIQ instance

### ISSUE THREAD

**Issue by simon3z** [openshift/openshift-ansible#5484]
#### Description

Now that the ManageIQ Ansible module is available here:

https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/remote_management/manageiq

I think would be easy to provide openshift-ansible inventory options to automatically register the newly deployed cluster to an existing ManageIQ instance.

cc @zgalor @yaacov @sdodson @joelddiaz @ilackarms @bazulay

**Comment by simon3z** [comment]
@tbielawa I suppose this can also be reused at the end of the CFME deployment.

**Comment by pradeepnss** [comment]
It is too early to ask this question, just wanted to know in which release this feature might go in ?

**Comment by tbielawa** [comment]
X-Ref: https://github.com/openshift/openshift-ansible/pull/5336

**Comment by pradeepnss** [comment]
@simon3z @tbielawa I see that #5336 is merged where it looks like we added support of CFME 4.6 deployment during OCP 3.7 cluster creation but it does not perform automatic registration of OCP cluster as container provider to CFME/MIQ. What are the plans on adding deployed cluster to existing MIQ/CFME ?

**Comment by tbielawa** [comment]
@pradeepnss that support is coming in https://github.com/openshift/openshift-ansible/pull/5793

**Comment by pradeepnss** [comment]
@tbielawa Thank you

**Comment by tbielawa** [comment]
Support for this feature has been merged in https://github.com/openshift/openshift-ansible/pull/5793 . Check out the `openshift_management` role README for instructions on adding OCP clusters as container providers.

**Comment by pradeepnss** [comment]
@tbielawa In this readme https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_management i see that this role will be available as of now in manageIQ and it will be available in CFME after release 4.6. Please can you tell in which release of CFME it will be supported and also any idea on tentative release dates of CFME 4.6 and later releases ?
