### ISSUE TITLE
 Images Streams update with ansible inventorie (change "Redhat" registry)

### ISSUE THREAD

**Issue by SpeedBlack** [openshift/openshift-ansible#5505]
Hi,

We have a functional OCP plaform v3.5.
We need to change the "Redhat" registry (registry.access.redhat.com) with a personal external registry.

I tried to use options with ansible inventories :
```
openshift_docker_additional_registries=myregistry.example.com:5000
openshift_docker_insecure_registries=myregistry.example.com:5000
oreg_url=myregistry.example.com:5000/openshift3/ose-${component}:${version}
openshift_examples_modify_imagestreams=true
oreg_auth_user=adminxx
oreg_auth_password='XXXXXX'
```

If i check "/usr/share/openshift/examples/image-streams/image-streams-rhel7.json" or "/usr/share/openshift/examples/xpaas-streams/jboss-image-streams.json" files,  my external registry is correctly informed but
images streams in openshift project always points towards "registry.access.redhat.com".

Does that make sense ? Is there a solution for images streams update ?

For information, some options are not taken into account as "openshift_docker_additional_registries=myregistry.example.com:5000" and "openshift_docker_insecure_registries=myregistry.example.com:5000" (options doesn't exist in /etc/sysconfig/docker). I have to manually add this configuration (after rerun config playbook).
In addition, if I tried, for example, "oc import-image jboss-amq-62 --from=myregistry.example.com:5000/jboss-amq-6/amq62-openshift" command, I have to add the "--insecure" option.

Ansible version :
```
# ansible --version
ansible 2.2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

# rpm -q atomic-openshift-utils openshift-ansible
atomic-openshift-utils-3.5.91-1.git.0.28b3ddb.el7.noarch
openshift-ansible-3.5.91-1.git.0.28b3ddb.el7.noarch
```

System version : 
```
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.3 (Maipo)
```

Thanks,
Best regards

**Comment by aizuddin85** [comment]
@SpeedBlack  try follow this, note that you need to restart docker after made the changes.

http://playbooks-rhtconsulting.rhcloud.com/playbooks/continuous_delivery/external-docker-registry-integration.html

**Comment by SpeedBlack** [comment]
Hello @aizuddin85 ,

Thank you very much for your answer.

I have already been following this documentation.
Docker configuration it's ok (certificate in /etc/docker/certs.d and /etc/sysconfig/docker file).
I added "external-registry" secret in openshift project and on all nodes I run docker login and then copy $HOME/.docker/config.json to /var/lib/origin (https://github.com/openshift/origin/issues/13918).

It's ok for all projects (logging, openshift infra, default, glusterfs,...). All projects use my external registry.
I just have a problem to change images streams. After i added "openshift_examples_modify_imagestreams=true" option, the default images streams in openshift project didn't update :

`# oc get is -n openshift
NAME                                  DOCKER REPO                                                                    TAGS                      UPDATED
dotnet                                172.XX.XX.XXX:5000/openshift/dotnet                                            1.1,1.0
fis-java-openshift                    registry.access.redhat.com/jboss-fuse-6/fis-java-openshift
fis-karaf-openshift                   registry.access.redhat.com/jboss-fuse-6/fis-karaf-openshift
jboss-amq-62                          registry.access.redhat.com/jboss-amq-6/amq62-openshift
jboss-datagrid65-openshift            registry.access.redhat.com/jboss-datagrid-6/datagrid65-openshift
jboss-datavirt63-openshift            registry.access.redhat.com/jboss-datavirt-6/datavirt63-openshift
jboss-decisionserver62-openshift      registry.access.redhat.com/jboss-decisionserver-6/decisionserver62-openshift
jboss-decisionserver63-openshift      registry.access.redhat.com/jboss-decisionserver-6/decisionserver63-openshift
jboss-eap64-openshift                 registry.access.redhat.com/jboss-eap-6/eap64-openshift
jboss-eap70-openshift                 registry.access.redhat.com/jboss-eap-7/eap70-openshift
jboss-processserver63-openshift       registry.access.redhat.com/jboss-processserver-6/processserver63-openshift
jboss-webserver30-tomcat7-openshift   registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat7-openshift
jboss-webserver30-tomcat8-openshift   registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift
jenkins                               172.XX.XX.XXX:5000/openshift/jenkins                                           1,2
mariadb                               172.XX.XX.XXX:5000/openshift/mariadb                                           10.1
mongodb                               172.XX.XX.XXX:5000/openshift/mongodb                                           2.4,3.2,2.6
mysql                                 172.XX.XX.XXX:5000/openshift/mysql                                             5.6,5.5,5.7
nodejs                                172.XX.XX.XXX:5000/openshift/nodejs                                            latest,4,0.10             3 days ago
perl                                  172.XX.XX.XXX:5000/openshift/perl                                              5.24,5.20,5.16
php                                   172.XX.XX.XXX:5000/openshift/php                                               7.0,5.6,5.5
postgresql                            172.XX.XX.XXX:5000/openshift/postgresql                                        9.5,9.4,9.2
python                                172.XX.XX.XXX:5000/openshift/python                                            3.5,3.4,3.3 + 1 more...
redhat-openjdk18-openshift            registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
redhat-sso70-openshift                registry.access.redhat.com/redhat-sso-7/sso70-openshift
redis                                 172.XX.XX.XXX:5000/openshift/redis                                             3.2
ruby                                  172.XX.XX.XXX:5000/openshift/ruby                                              2.2,2.0,2.3`


For example, I tried :
`oc import-image --insecure nodejs --from=myregistry.example.com:5000/rhscl/nodejs-4-rhel7.`

But, if i add new nodejs application from the web interface in OCP platform.  I can't find the component in browse Catalog.

Have you any idea to update default images streams in project openshift ?
Can you explain the best solution ? I need to edit each image stream ? (oc edit is nodejs -o yaml and modify DockerImage option and add option "insecure": true).

Thanks,
Best regards

**Comment by sdodson** [comment]
It looks like it's limited to the xpaas (java) image streams. Can you try re-creating them? `oc replace -n openshift -f /usr/share/openshift/examples/xpaas-streams/jboss-image-streams.json` ?

**Comment by SpeedBlack** [comment]
Hello @sdodson, 

I tried oc replace -n openshift -f /usr/share/openshift/examples/xpaas-streams/jboss-image-streams.json.
It's doesn't work because error certificate :
```
# docker logs registry -f
2017/09/26 14:44:12 http: TLS handshake error from XX.XX.XXX.XX:33124: EOF
2017/09/26 14:44:13 http: TLS handshake error from XX.XX.XXX.XX:33126: EOF
2017/09/26 14:44:13 http: TLS handshake error from XX.XX.XXX.XX:33128: EOF
2017/09/26 14:44:13 http: TLS handshake error from XX.XX.XXX.XX:33130: EOF
2017/09/26 14:44:13 http: TLS handshake error from XX.XX.XXX.XX:33132: EOF
2017/09/26 14:44:13 http: TLS handshake error from XX.XX.XXX.XX:33134: EOF
2017/09/26 14:44:13 http: TLS handshake error from XX.XX.XXX.XX:33136: EOF
2017/09/26 14:44:13 http: TLS handshake error from XX.XX.XXX.XX:33138: EOF
2017/09/26 14:44:13 http: TLS handshake error from XX.XX.XXX.XX:33140: EOF
2017/09/26 14:44:13 http: TLS handshake error from XX.XX.XXX.XX:33142: EOF
2017/09/26 14:44:13 http: TLS handshake error from XX.XX.XXX.XX:33144: EOF
2017/09/26 14:47:02 http: TLS handshake error from XX.XX.XXX.XX:33218: EOF
```

My external registry use self signed (internal PKI).

After, I tried oc replace -n openshift -f /usr/share/openshift/examples/xpaas-streams/jboss-image-streams.json --insecure-skip-tls-verify. It's doesn't work.

I also tried to modify "jboss-image-streams.json" file to add "importPolicy": { "insecure": "true" }. It's doesn't work. 

`        {
            "kind": "ImageStream",
            "apiVersion": "v1",
            "metadata": {
                "name": "jboss-eap70-openshift"
            },
            "spec": {
                "dockerImageRepository": "ocprg01.spb.lan:5002/jboss-eap-7/eap70-openshift",
                "tags": [
                    {
                        "name": "1.4",
                        "annotations": {
                            "description": "JBoss EAP 7.0 S2I images.",
                            "iconClass": "icon-jboss",
                            "tags": "builder,eap,javaee,java,jboss,xpaas",
                            "supports":"eap:7.0,javaee:7,java:8,xpaas:1.4",
                            "sampleRepo": "https://github.com/jboss-developer/jboss-eap-quickstarts.git",
                            "sampleContextDir": "kitchensink",
                            "sampleRef": "7.0.0.GA",
                            "version": "1.4"
                        },
                        "importPolicy": {
                            "insecure": "true"
                        }
                    }
                ]
            }
        },`

I have the following error :
```
# oc replace -n openshift -f /usr/share/openshift/examples/xpaas-streams/jboss-image-streams.json
Error from server (BadRequest): ImageStream in version "v1" cannot be handled as a ImageStream: [pos 917]: json: decode bool: got first char "
```

Have you any idea to have the certificate recognized by the OCP platform ? (as with docker configuration and adding certificate in /etc/docker/certs.d)

Authentication to my registry ist's ok. I added "external-registry" secret in openshift project and execute `oc secrets link default external-registry --for=pull` command.

Thanks,
Best regards,

**Comment by SpeedBlack** [comment]
Hello,

After many failed attempts, I found this issue (https://github.com/openshift/origin/issues/1753).
It seems to be my problem.
@schweikert writes on May 10 :

> After endless trying, I found a workaround to my problem:
> 
> edit /etc/systemd/system/atomic-openshift-master.service, and add to ExecStart:
> 
> `-v /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted` 
> reload systemctl, restart the service
> 
> Now /etc/pki/ca-trust/extracted from the docker host is mapped inside the ose container, and SSL verification works.

Does this solution still work ? Is there risk ?
Otherwise, can you confirm the procedure below ?

On all nodes :
```
# cd /etc/pki/ca-trust/extracted/
# mkdir externalregistry
# cp ca.crt /etc/pki/ca-trust/extracted/externalregistry
```

on masters :
```
#edit /etc/systemd/system/atomic-openshift-master.service, and add to ExecStart:
	-v /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted
# systemctl restart atomic-openshift-master-*
```

Thanks
Best regards

**Comment by sdodson** [comment]
Does the version of the installer you're using not have 2d780c406038a6f0b3cc4c7a2326853c09a3caa0 ? That should've mounted /etc/pki into the master containers.

**Comment by SpeedBlack** [comment]
Hello @sdodson,

I apologise for the delay.

How to know version of the installer ?

Currently, about ansible on my system :
```
# ansible --version
ansible 2.2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

```
# rpm -qa | grep ansible
openshift-ansible-docs-3.5.91-1.git.0.28b3ddb.el7.noarch
openshift-ansible-filter-plugins-3.5.91-1.git.0.28b3ddb.el7.noarch
ansible-2.2.3.0-1.el7.noarch
openshift-ansible-3.5.91-1.git.0.28b3ddb.el7.noarch
openshift-ansible-lookup-plugins-3.5.91-1.git.0.28b3ddb.el7.noarch
openshift-ansible-roles-3.5.91-1.git.0.28b3ddb.el7.noarch
openshift-ansible-callback-plugins-3.5.91-1.git.0.28b3ddb.el7.noarch
openshift-ansible-playbooks-3.5.91-1.git.0.28b3ddb.el7.noarch
```
 
Thanks,
Best regards,

**Comment by sdodson** [comment]
Thanks, you're using 3.5 version of the installer but it should have /etc/pki bind mounted because that change was backported in a9ece184eeea7de99a947f799bb902524250b6ab so I think the only thing that should be necessary is for you to ensure that your registry's CA is added to /etc/pki/ca-trust/extracted/externalregistry on each node.

@abutcher we have a generic way to add arbitrary CAs to the trust store of all nodes, right?

**Comment by SpeedBlack** [comment]
Ok, great ! Thanks !

I will try !

**Comment by SpeedBlack** [comment]
Hello @sdodson,

About CA, it works ! Thank you very much !

I have a last problem during the build. An authentication problem.

If I tried to deploy a new nodejs application (with git repository), I have the following error :

`error: build error: unable to get myregistry.example.com:5000/rhscl/nodejs-4-rhel7@sha256:29b1732f719f4d577827662a8faeea211908657de345ddef4534e3a1eabe1621 `

logs of the registry :
```
time="2017-10-02T07:36:26Z" level=error msg="error authenticating user \"\": authentication failure" go.version=go1.7.6 http.request.host="myregistry.example.com:5000" http.request.id=2bcfd069-ef71-469b-9b6b-399b350643b2 http.request.method=GET http.request.remoteaddr="XX.XX.XXX.XX:xxxxx" http.request.uri="/v2/rhscl/nodejs-4-rhel7/manifests/sha256:29b1732f719f4d577827662a8faeea211908657de345ddef4534e3a1eabe1621" http.request.useragent="docker/1.12.6 go/go1.8.3 kernel/3.10.0-693.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=581890a7-dcdc-4ef5-8540-c7d084b12ce6 vars.name="rhscl/nodejs-4-rhel7" vars.reference="sha256:29b1732f719f4d577827662a8faeea211908657de345ddef4534e3a1eabe1621" version=v2.6.2
time="2017-10-02T07:36:26Z" level=warning msg="error authorizing context: basic authentication challenge for realm \"Registry Realm\": authentication failure" go.version=go1.7.6 http.request.host="myregistry.example.com:5000" http.request.id=2bcfd069-ef71-469b-9b6b-399b350643b2 http.request.method=GET http.request.remoteaddr="XX.XX.XXX.XX:xxxxx" http.request.uri="/v2/rhscl/nodejs-4-rhel7/manifests/sha256:29b1732f719f4d577827662a8faeea211908657de345ddef4534e3a1eabe1621" http.request.useragent="docker/1.12.6 go/go1.8.3 kernel/3.10.0-693.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=581890a7-dcdc-4ef5-8540-c7d084b12ce6 vars.name="rhscl/nodejs-4-rhel7" vars.reference="sha256:29b1732f719f4d577827662a8faeea211908657de345ddef4534e3a1eabe1621" version=v2.6.2
```

The only solution that i found is a create a secret in the project and add this secret for "Pull Secret" option of the project :
```
# oc secrets new-dockercfg external-registry \
>     --docker-server=myregistry.example.com:5000 --docker-username=AAAAA \
>     --docker-password=BBBB --docker-email=CCCC@ee.com

# oc secrets link default external-registry --for=pull
```


Have you any idea to share this "external-registry" secret for all project ? And use this default secret to pull image ?

For information, my registry use "htpasswd" authentication. Is the appropriate solution ?

Thank you very much for your help.
Best regards.

**Comment by sdodson** [comment]
I'm sorry I don't know how to share a secret across all projects. I'd suggest posting to the users list and see if someone there can provide an answer. https://lists.openshift.redhat.com/openshiftmm/listinfo/users

**Comment by SpeedBlack** [comment]
Ok, no problem ! 
Thank you very much for your help !

Best regards,
