### ISSUE TITLE
Allow users to defined uid/gid for 'origin' user which the master will run as

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#551]
The user will be created via rpm install scriptlets if the user doesn't exist already.

See https://github.com/openshift/origin/issues/4487 for that

**Comment by sdodson** [comment]
We'll need to modify a lot of things to run as or chown/chgrp several files/directories.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
