### ISSUE TITLE
Openshift Service Catalog issue

### ISSUE THREAD

**Issue by srirammageswaran8** [openshift/openshift-ansible#5512]
I face the below error message when running deployment.

TASK [openshift_service_catalog : wait for api server to be ready] *******************************************************************
FAILED - RETRYING: wait for api server to be ready (120 retries left).
FAILED - RETRYING: wait for api server to be ready (119 retries left).
FAILED - RETRYING: wait for api server to be ready (118 retries left).
FAILED - RETRYING: wait for api server to be ready (117 retries left).
FAILED - RETRYING: wait for api server to be ready (116 retries left).
FAILED - RETRYING: wait for api server to be ready (115 retries left).
FAILED - RETRYING: wait for api server to be ready (114 retries left).
FAILED - RETRYING: wait for api server to be ready (113 retries left).
FAILED - RETRYING: wait for api server to be ready (112 retries left).
FAILED - RETRYING: wait for api server to be ready (111 retries left).
FAILED - RETRYING: wait for api server to be ready (110 retries left).
FAILED - RETRYING: wait for api server to be ready (109 retries left).
FAILED - RETRYING: wait for api server to be ready (108 retries left).
FAILED - RETRYING: wait for api server to be ready (107 retries left).
FAILED - RETRYING: wait for api server to be ready (106 retries left).
FAILED - RETRYING: wait for api server to be ready (105 retries left).
FAILED - RETRYING: wait for api server to be ready (104 retries left).
FAILED - RETRYING: wait for api server to be ready (103 retries left).
FAILED - RETRYING: wait for api server to be ready (102 retries left).
FAILED - RETRYING: wait for api server to be ready (101 retries left).
FAILED - RETRYING: wait for api server to be ready (100 retries left).
FAILED - RETRYING: wait for api server to be ready (99 retries left).
FAILED - RETRYING: wait for api server to be ready (98 retries left).
FAILED - RETRYING: wait for api server to be ready (97 retries left).
FAILED - RETRYING: wait for api server to be ready (96 retries left).
FAILED - RETRYING: wait for api server to be ready (95 retries left).
FAILED - RETRYING: wait for api server to be ready (94 retries left).
FAILED - RETRYING: wait for api server to be ready (93 retries left).
FAILED - RETRYING: wait for api server to be ready (92 retries left).
FAILED - RETRYING: wait for api server to be ready (91 retries left).
FAILED - RETRYING: wait for api server to be ready (90 retries left).
FAILED - RETRYING: wait for api server to be ready (89 retries left).
FAILED - RETRYING: wait for api server to be ready (88 retries left).
FAILED - RETRYING: wait for api server to be ready (87 retries left).
FAILED - RETRYING: wait for api server to be ready (86 retries left).
FAILED - RETRYING: wait for api server to be ready (85 retries left).
FAILED - RETRYING: wait for api server to be ready (84 retries left).
FAILED - RETRYING: wait for api server to be ready (83 retries left).
FAILED - RETRYING: wait for api server to be ready (82 retries left).
FAILED - RETRYING: wait for api server to be ready (81 retries left).
FAILED - RETRYING: wait for api server to be ready (80 retries left).
FAILED - RETRYING: wait for api server to be ready (79 retries left).
FAILED - RETRYING: wait for api server to be ready (78 retries left).
FAILED - RETRYING: wait for api server to be ready (77 retries left).
FAILED - RETRYING: wait for api server to be ready (76 retries left).
FAILED - RETRYING: wait for api server to be ready (75 retries left).
FAILED - RETRYING: wait for api server to be ready (74 retries left).
FAILED - RETRYING: wait for api server to be ready (73 retries left).
FAILED - RETRYING: wait for api server to be ready (72 retries left).
FAILED - RETRYING: wait for api server to be ready (71 retries left).
FAILED - RETRYING: wait for api server to be ready (70 retries left).
FAILED - RETRYING: wait for api server to be ready (69 retries left).
FAILED - RETRYING: wait for api server to be ready (68 retries left).
FAILED - RETRYING: wait for api server to be ready (67 retries left).
FAILED - RETRYING: wait for api server to be ready (66 retries left).
FAILED - RETRYING: wait for api server to be ready (65 retries left).
FAILED - RETRYING: wait for api server to be ready (64 retries left).
FAILED - RETRYING: wait for api server to be ready (63 retries left).
FAILED - RETRYING: wait for api server to be ready (62 retries left).
FAILED - RETRYING: wait for api server to be ready (61 retries left).
FAILED - RETRYING: wait for api server to be ready (60 retries left).
FAILED - RETRYING: wait for api server to be ready (59 retries left).
FAILED - RETRYING: wait for api server to be ready (58 retries left).
FAILED - RETRYING: wait for api server to be ready (57 retries left).
FAILED - RETRYING: wait for api server to be ready (56 retries left).
FAILED - RETRYING: wait for api server to be ready (55 retries left).
FAILED - RETRYING: wait for api server to be ready (54 retries left).
FAILED - RETRYING: wait for api server to be ready (53 retries left).
FAILED - RETRYING: wait for api server to be ready (52 retries left).
FAILED - RETRYING: wait for api server to be ready (51 retries left).
FAILED - RETRYING: wait for api server to be ready (50 retries left).
FAILED - RETRYING: wait for api server to be ready (49 retries left).
FAILED - RETRYING: wait for api server to be ready (48 retries left).
FAILED - RETRYING: wait for api server to be ready (47 retries left).
FAILED - RETRYING: wait for api server to be ready (46 retries left).
FAILED - RETRYING: wait for api server to be ready (45 retries left).
FAILED - RETRYING: wait for api server to be ready (44 retries left).
FAILED - RETRYING: wait for api server to be ready (43 retries left).
FAILED - RETRYING: wait for api server to be ready (42 retries left).
FAILED - RETRYING: wait for api server to be ready (41 retries left).
FAILED - RETRYING: wait for api server to be ready (40 retries left).
FAILED - RETRYING: wait for api server to be ready (39 retries left).
FAILED - RETRYING: wait for api server to be ready (38 retries left).
FAILED - RETRYING: wait for api server to be ready (37 retries left).
FAILED - RETRYING: wait for api server to be ready (36 retries left).
FAILED - RETRYING: wait for api server to be ready (35 retries left).
FAILED - RETRYING: wait for api server to be ready (34 retries left).
FAILED - RETRYING: wait for api server to be ready (33 retries left).
FAILED - RETRYING: wait for api server to be ready (32 retries left).
FAILED - RETRYING: wait for api server to be ready (31 retries left).
FAILED - RETRYING: wait for api server to be ready (30 retries left).
FAILED - RETRYING: wait for api server to be ready (29 retries left).
FAILED - RETRYING: wait for api server to be ready (28 retries left).
FAILED - RETRYING: wait for api server to be ready (27 retries left).
FAILED - RETRYING: wait for api server to be ready (26 retries left).
FAILED - RETRYING: wait for api server to be ready (25 retries left).
FAILED - RETRYING: wait for api server to be ready (24 retries left).
FAILED - RETRYING: wait for api server to be ready (23 retries left).
FAILED - RETRYING: wait for api server to be ready (22 retries left).
FAILED - RETRYING: wait for api server to be ready (21 retries left).
FAILED - RETRYING: wait for api server to be ready (20 retries left).
FAILED - RETRYING: wait for api server to be ready (19 retries left).
FAILED - RETRYING: wait for api server to be ready (18 retries left).
FAILED - RETRYING: wait for api server to be ready (17 retries left).
FAILED - RETRYING: wait for api server to be ready (16 retries left).
FAILED - RETRYING: wait for api server to be ready (15 retries left).
FAILED - RETRYING: wait for api server to be ready (14 retries left).
FAILED - RETRYING: wait for api server to be ready (13 retries left).
FAILED - RETRYING: wait for api server to be ready (12 retries left).
FAILED - RETRYING: wait for api server to be ready (11 retries left).
FAILED - RETRYING: wait for api server to be ready (10 retries left).
FAILED - RETRYING: wait for api server to be ready (9 retries left).
FAILED - RETRYING: wait for api server to be ready (8 retries left).
FAILED - RETRYING: wait for api server to be ready (7 retries left).
FAILED - RETRYING: wait for api server to be ready (6 retries left).
FAILED - RETRYING: wait for api server to be ready (5 retries left).
FAILED - RETRYING: wait for api server to be ready (4 retries left).
FAILED - RETRYING: wait for api server to be ready (3 retries left).
FAILED - RETRYING: wait for api server to be ready (2 retries left).
FAILED - RETRYING: wait for api server to be ready (1 retries left).
fatal: [hostname.example.com]: FAILED! => {
    "attempts": 120,
    "changed": false,
    "cmd": [
        "curl",
        "-k",
        "https://apiserver.kube-service-catalog.svc/healthz"
    ],
    "delta": "0:00:01.134761",
    "end": "2017-09-22 18:57:56.186472",
    "failed": true,
    "rc": 7,
    "start": "2017-09-22 18:57:55.051711"
}

STDERR:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed connect to apiserver.kube-service-catal                        og.svc:443; Connection refused

The reference code is :

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_service_catalog/tasks/start_api_server.yml#L10-L22

**Comment by ewolinetz** [comment]
@srirammageswaran8 if you log into your cluster and run `oc get pods -n kube-service-catalog` what do you get back?

**Comment by srirammageswaran8** [comment]
Hi @ewolinetz ,

Please Find the output below : 

oc get pods -n kube-service-catalog
NAME                       READY     STATUS              RESTARTS   AGE
apiserver-qhmj6            0/1       MatchNodeSelector   0          0s
controller-manager-74sqb   0/1       MatchNodeSelector   0          0s


Thanks,
Sriram

**Comment by ewolinetz** [comment]
Sorry for the delay on this @srirammageswaran8 . Per chance, are you setting `osm_default_node_selector` at all in your host file?

**Comment by srirammageswaran8** [comment]
Hi @ewolinetz ,

Yes I set that to the below value in the inventory file.

osm_default_node_selector="role=app"

Thanks ,
Sriram Mageswaran.

**Comment by ewolinetz** [comment]
Thanks for that information, this looks to be the same issue as a Bugzilla [1] that has been opened.
I'm going to close this issue so we can just track it there.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1497047

**Comment by srirammageswaran8** [comment]
@ewolinetz 

Thanks.

**Comment by mikk150** [comment]
I havent changed `osm_default_node_seletor` on inventory file but I still have this issue
