### ISSUE TITLE
origin-gce broken: htpasswd is unavailable

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#5514]
Started in the last few days.  I'm not installing openshift_metrics, I wouldn't expect a failure in a metrics task about it.

https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/448/console

```
Failure summary:


  1. Hosts:    ci-primg448-ig-m-942j
     Play:     Create Hosted Resources
     Task:     openshift_metrics : fail
     Message:  'htpasswd' is unavailable. Please install httpd-tools on the control node
Build step 'Execute shell' marked build as failure
```

**Comment by sdodson** [comment]
There was a regression on Friday that led to metrics and logging being
installed by default. That was fixed late Friday, are you current?

**Comment by smarterclayton** [comment]
It was fixed.
