### ISSUE TITLE
Follow this release pattern and you can't go wrong

### ISSUE THREAD

**Issue by magick93** [openshift/openshift-ansible#5516]
#### Description

I'm wanting to take OpenShift v3.7.0-alpha.1 for a spin.

On the openshift-ansible readme it says:

> Follow this release pattern and you can't go wrong:
> 
> | Origin/OCP    | OpenShift-Ansible version | openshift-ansible branch |
> | ------------- | ----------------- |----------------------------------|
> | 1.3 / 3.3          | 3.3               | release-1.3 |
> | 1.4 / 3.4          | 3.4               | release-1.4 |
> | 1.5 / 3.5          | 3.5               | release-1.5 |
> | 3.*X*         | 3.*X*             | **release-3.x** |

But there is no branch called `release-3.x`

Which branch should I use?

Thanks

**Comment by sdodson** [comment]
It means if you're using 3.6 you'd use `release-3.6` branch.
