### ISSUE TITLE
openshift_hosted_logging[ops]_storage_volume_size should have default value

### ISSUE THREAD

**Issue by zgalor** [openshift/openshift-ansible#5525]
#### Description

`openshift_hosted_loggingops_storage_volume_size`
and 
`openshift_hosted_loggingops_storage_volume_size`
are now required params for 'openshift_hosted_logging[ops]_storage_kind=nfs'

##### Version

```
ansible 2.3.2.0
openshift-ansible-3.7.0-0.125.0-258-g509cc3704
```

##### Steps To Reproduce
1. run playbooks/byo/config.yml with inventory file with : 
```
openshift_hosted_logging_deploy=true
openshift_hosted_logging_storage_kind=nfs
```
and/or

```
openshift_hosted_logging_enable_ops_cluster=true
openshift_hosted_loggingops_storage_kind=nfs
```

##### Expected Results
cluster should create a 10Gi internal nfs pv.

##### Observed Results
Describe what is actually happening.

```
'openshift_logging_storage_volume_size' is undefined
```

For long output or logs, consider using a [gist](https://gist.github.com/)

**Comment by zgalor** [comment]
@ewolinetz

**Comment by ewolinetz** [comment]
https://github.com/openshift/openshift-ansible/pull/5546
