### ISSUE TITLE
Unable to install without openshift-sdn

### ISSUE THREAD

**Issue by umairmufti** [openshift/openshift-ansible#554]
We would like to install OSE without openshift-sdn as we use native container routing. Setting `openshift_use_openshift_sdn=false` in the inventory file still causes openshift-sdn to be installed on openshift-nodes. 
 
The issue is that the value for the variable becomes a string when interpreted by Jinja. The default value for `use_openshift_sdn` is then used, which is `True`.

**Comment by ibotty** [comment]
that can be closed, right?

**Comment by abutcher** [comment]
@brenton This one can be closed
