### ISSUE TITLE
RFE: support for etcd upgrades

### ISSUE THREAD

**Issue by dak1n1** [openshift/openshift-ansible#5545]
The OpenShift Ops team ran into an issue that we would like the openshift-ansible team to review. There may be a use case here for an etcd upgrade functionality to be added to the openshift-ansible tooling.

Issue:

On two of our Starter tier clusters, we were performing the RHEL 7.4 upgrade, and it just happened that etcd version 3.2.5 was released that day (or thereabouts) and accidentally installed with that update. When we finished the RHEL 7.4 upgrades, all Starter clusters were on RHEL 7.4, but some were running 
 etcd 3.2.5 while others were still on 3.1.9, just due to the timing of when the etcd package was released.

For consistency's sake, we found it necessary to have an etcd upgrade separate from any other system update or OCP update. That's why it might be useful to have an etcd upgrade functionality inside of openshift-ansible. It would also allow us to upgrade etcd as soon as a new bugfix is available.

I just wanted to document this potential use case so you guys are aware. Thanks,

And here is the script I made for my updates, in case it helps. (Management just wants us to get away from making our own scripts where possible, if there's a potential to get it into the product instead).

https://github.com/openshift/openshift-tools/blob/prod/ansible/playbooks/adhoc/os_update.yml

**Comment by sdodson** [comment]
We do provide an etcd playbook that performs the etcd upgrade in isolation of all other tasks but it does not currently have 3.2 included in the upgrade path so we need to add that. It also doesn't include upgrading to a specific version it will simply upgrade to the latest of whichever 2.1, 2.2, 2.3, 3.0, and 3.1 version is enabled in your repos. That playbook is `playbooks/byo/openshift-cluster/upgrades/upgrade_etcd.yml` You'd just need to add an additional play for 3.2 right now.

The playbook is probably more complex than it needs to be at first glance but we were instructed to ensure that we only upgraded in a stepwise manner, as in you cannot upgrade from 2.1 to 2.3 directly.
