### ISSUE TITLE
Failed to deploy GlusterFS with OCP3.6 due to undefined `openshift` attribute

### ISSUE THREAD

**Issue by miminar** [openshift/openshift-ansible#5548]
## Description
The following error appears when trying to deploy GlusterFS with OCP:

```
Failure summary:

  1. Host:     host0.ocp.example.org
     Play:     Configure GlusterFS
     Task:     openshift_storage_glusterfs : Label GlusterFS nodes
     Message:  the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'openshift'

               The error appears to have been in '/usr/share/ansible/openshift-ansible/roles/openshift_storage_glusterfs/tasks/glusterfs_deploy.yml': line 68, column 3, but may
               be elsewhere in the file depending on the exact syntax problem.

               The offending line appears to be:


               - name: Label GlusterFS nodes
                 ^ here
```

The mentioned task looks like this:

```
- name: Label GlusterFS nodes
  oc_label:
    name: "{{ hostvars[item].openshift.node.nodename }}"
    kind: node
    state: add
    labels: "{{ glusterfs_nodeselector | oo_dict_to_list_of_dict }}"
  with_items: "{{ glusterfs_nodes | default([]) }}"
```

## Version
`openshift-ansible-3.6.173.0.5-3.git.0.522a92a.el7`

## Hosts file

```
[OSEv3:children]
masters
etcd
lb
glusterfs
nodes

[OSEv3:vars]
debug_level=3
openshift_disable_check=disk_availability,docker_image_availability
ansible_ssh_user=lroot
openshift_clock_enabled=true
deployment_type=openshift-enterprise
ansible_become=yes
openshift_http_proxy=http://proxy.ocp.example.org:8080
openshift_https_proxy=http://proxy.ocp.example.org:8080
openshift_no_proxy=example.org
openshift_docker_insecure_registries=172.30.0.0/16
openshift_storage_glusterfs_namespace=glusterfs
openshift_storage_glusterfs_name=storage

os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_router_selector='region=router'

openshift_master_cluster_method=native
# TODO internal api-server address for nodes/containers
openshift_master_cluster_hostname=host14.ocp.example.org
# TODO loadbalancer address
openshift_master_cluster_public_hostname=host14.ocp.example.org
# TODO router/infrastructure "LB" address
openshift_master_default_subdomain=10.96.XXX.NNN.nip.io
openshift_portal_net=172.30.0.0/16

# host group for masters
[masters]
host[170:172].ocp.example.org

# host group for etcd
[etcd]
host[170:172].ocp.example.org

# Specify load balancer host
[lb]
host14.ocp.example.org

[glusterfs]
host5.ocp.example.org glusterfs_ip=10.96.XXX.AAA glusterfs_devices='["/dev/sdb"]'
host6.ocp.example.org glusterfs_ip=10.96.XXX.BBB glusterfs_devices='["/dev/sdb"]'
host7.ocp.example.org glusterfs_ip=10.96.XXX.CCC glusterfs_devices='["/dev/sdb"]'

# host group for nodes, includes region info
[nodes]
host[12:13].ocp.example.org
host14.ocp.example.org openshift_node_labels="{'region': 'router', 'zone': 'default'}"
host[16:17].ocp.example.org openshift_node_labels="{'region': 'infra', 'zone': 'default'}" 
host[0:7].ocp.example.org
host[18:19].ocp.example.org
```

**Comment by jarrpa** [comment]
@miminar Sorry for the delayed response!

....this is very strange. Are you able to edit the openshift-ansible files directly to insert the following right before the failing task and then re-run the playbooks?
```
- debug:
    msg: "{{ hostvars[item] }}"
  with_items: "{{ glusterfs_nodes | default([]) }}"
```

**Comment by miminar** [comment]
Apparently, there was an unreachable gluster node. When replaced with another node, the playbook went through.

**Comment by jarrpa** [comment]
@miminar Ah. Is the problem resolved then? Or is there still a reproducable problem you'd like addressed?

**Comment by miminar** [comment]
The problem is that the error message is super confusing.

**Comment by jarrpa** [comment]
@miminar I'm not sure there's much we can do about that here. It should be something that's done at a higher playbook level, not in the GlusterFS one, but even so I'm not sure how to make sure we allow for any use cases where not having those variables defined is fine. If that's the only problem, please close this Issue and open another one if you feel it should be addressed.

**Comment by miminar** [comment]
@jarrpa can this be re-assigned instead of closing? The playbook level is still contained in this repository if I'm not mistaken.

**Comment by jarrpa** [comment]
@miminar I'm just not sure it makes sense to have the check in the GlusterFS role. If a node which is supposed to be an openshift node is unreachable, this is a higher-level problem not one specific to the role.

**Comment by jarrpa** [comment]
@miminar Specifically, I want you to open a new Issue on this same repo but as a new thread that focuses on the actual core issue you're having rather than the symptom you faced.

**Comment by jarrpa** [comment]
As it's been a week of inactivity, I am closing this issue. As I believe there is nothing that is appropriate for the role specifically, so please continue this discussion in a new issue at a higher level.
