### ISSUE TITLE
Heketi Deployment creates a job with Image that cannot be changed.

### ISSUE THREAD

**Issue by ttindell2** [openshift/openshift-ansible#5550]
#### Description

When attempting to install gluster in an environment where Docker Hub is unavailable, one would set these 4 variables to point gluster containers to a local registry:

openshift_storage_glusterfs_image="<LOCAL REGISTRY>/gluster"
openshift_storage_glusterfs_version="latest"

openshift_storage_glusterfs_heketi_image="<LOCAL REGISTRY>/heketi"
openshift_storage_glusterfs_heketi_version="latest"

The issue is that during the deployment of heketi, specifically the transfer of the DB volume, this command is run:

heketi-cli setup-openshift-heketi-storage --listfile /tmp/heketi-storage.json

This create a template for a job that moves the DB to persistent storage in gluster. The issue is that this generated template uses heketi/heketi:dev for its Image and it cannot be changed. This will cause the job to fail, the DB not to be transferred, and heketi cluster will not be set up properly. 

To remedy the situation, add a task to update the Image name to be:
 {{ openshift_storage_glusterfs_heketi_image }}: {{ openshift_storage_glusterfs_heketi_version }}

Add a task into heketi_deploy_part2.yaml like:

- name: Update Heketi DB Volume Job Image name
  replace:
    path: "{{ mktemp.stdout }}/heketi-storage.json"
    regexp: '\"image\":.*'
    replace: '"image":  "{{ openshift_storage_glusterfs_heketi_image }}:{{ openshift_storage_glusterfs_heketi_version }}"'

**Comment by jarrpa** [comment]
PR #5562 resolves this issue and is merged.
