### ISSUE TITLE
Enable Prometheus by Default

### ISSUE THREAD

**Issue by simon3z** [openshift/openshift-ansible#5572]
#### Description

Can we enable by default the Prometheus metrics service in 3.7 and during upgrades of 3.6 (to 3.7)?

cc @zgalor @sdodson @tbielawa

**Comment by sdodson** [comment]
I'd defer to you and @smarterclayton to determine the default enablement state. I imagine we'd definitely do that if they've enabled CFME but not sure if they haven't.
