### ISSUE TITLE
include is deprecated

### ISSUE THREAD

**Issue by Sandvich** [openshift/openshift-ansible#5586]
#### Description

I'm sure someone has noticed this, but I didn't see it in the issues so...

`[DEPRECATION WARNING]: 'include' for playbook includes. You should use 'import_playbook' instead. This feature will be removed in version 2.8.`

##### Version
ansible version: 2.4.0.0
Running from git clone, on branch release-3.6

**Comment by mtnbikenc** [comment]
Yep, I've been working on this and have a branch updated, including tox tests!

**Comment by mtnbikenc** [comment]
Linking the Trello card: https://trello.com/c/ZTyZu3UM

**Comment by Sandvich** [comment]
Great :)
I assumed someone was aware of this, but figured it was worth mentioning anyway!
