### ISSUE TITLE
Adopt new login template configuration option

### ISSUE THREAD

**Issue by spadgett** [openshift/openshift-ansible#560]
See openshift/origin#4465

Adopt new `oauthConfig.templates.login` master configuration option for customizing the login page.

**Comment by tbielawa** [comment]
I believe this has been included

```jinja
oauthConfig:
{% if 'oauth_always_show_provider_selection' in openshift.master %}
  alwaysShowProviderSelection: {{ openshift.master.oauth_always_show_provider_selection }}
{% endif %}
{% if 'oauth_templates' in openshift.master %}
  templates:{{ openshift.master.oauth_templates | to_padded_yaml(level=2) }}
{% endif %}
```

This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
