### ISSUE TITLE
/var/lib/etcd is owned by root, etcd won't start

### ISSUE THREAD

**Issue by guhcampos** [openshift/openshift-ansible#5602]
#### Description

I have recently deployed a 3 host cluster from scratch with `openshift-ansible` and noticed it was consistently failing because `etcd` could not be started. Looking at `journalctl` reviews `etcd` does not have permissions on `/var/lib/etcd` after deployment. On a fresh install, `/var/lib/etcd` is owned by `root`.

Just running `chown -R etcd /var/lib/etcd` on each host has fixed the problem.

##### Version

Ansible 2.3.2.0
openshift-ansible: bf61775799fc7fb0fccf63ef11102bf48d5a2d7a

**Comment by aizuddin85** [comment]
@guhcampos can you provide the inventory file?

**Comment by guhcampos** [comment]
I won't have it in a couple weeks because I'm currently on vacation time and this was at the office, but I can try to reproduce at home.

Nevertheless, it was a fairly standard inventory I built just for this test, probably something like:

```
[nodes]
host01
host02
host03
```

Where all 3 nodes are also `masters`, `etcd` and `lb`

I don recall the exact changes I did to the inventory config, but a possibly relevant detail is I usually run playbooks with `remote_user = root` rather then resorting to `become`
