### ISSUE TITLE
redeploy-certificates.yml breaks master-config.yaml as well as does not drain nodes during service restarts

### ISSUE THREAD

**Issue by bortek** [openshift/openshift-ansible#5612]
#### Description
Hi guys

I am running /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/redeploy-certificates.yml playbook to update my certificates as they are about to expire soon. 

When playbok is almost complete and it goes on to restart master nodes it fails since restart of the master api service fails. 

````
TASK [Restart master API] *************************************************************************************************************************************
fatal: [HOSTNAME-REMOVED]: FAILED! => {
    "changed": false,
    "failed": true
}

MSG:

Unable to restart service atomic-openshift-master-api: Job for atomic-openshift-master-api.service failed because the control process exited with error code. See "systemctl status atomic-openshift-master-api.service" and "journalctl -xe" for details.


````
Here is the error from /var/log/messages file when it fails to start service

````
Oct  2 13:33:28 HOSTNAME systemd: Starting Atomic OpenShift Master API...
Oct  2 13:33:29 HOSTNAME atomic-openshift-master-api: I1002 13:33:29.161946   86171 start_api.go:104] Using a listen address override "0.0.0.0:8443"
Oct  2 13:33:29 HOSTNAME atomic-openshift-master-api: W1002 13:33:29.164544   86171 start_master.go:297] Warning: assetConfig.servingInfo: Invalid value: "<not displayed>": changes to assetConfig certificate configuration are not used when colocated with master API, master start will continue.
Oct  2 13:33:29 HOSTNAME atomic-openshift-master-api: Invalid MasterConfig /etc/origin/master/master-config.yaml
Oct  2 13:33:29 HOSTNAME atomic-openshift-master-api: servingInfo.namedCertificates[0].names[0]: Required value
Oct  2 13:33:29 HOSTNAME systemd: atomic-openshift-master-api.service: main process exited, code=exited, status=255/n/a
Oct  2 13:33:29 HOSTNAME systemd: Failed to start Atomic OpenShift Master API.
````

This is in turn due to /etc/origin/master/master-config.yaml file is errornous after playbook execution. After comparing master-config file before and after playbook execution  I can see that the playbook adds the following EMPTY line after names: tag

````servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: master.server.crt
  clientCA: ca-bundle.crt
  keyFile: master.server.key
  maxRequestsInFlight: 500
  namedCertificates:
  - certFile: /etc/origin/master/named_certificates/sandbox.mydomain.com.crt
    keyFile: /etc/origin/master/named_certificates/sandbox.mydomain.com.key
    names:
    - ''
    - sandbox.mydomain.com
  requestTimeoutSeconds: 3600
````

If I remove this empty line then it is possible to start master api service. I cannot find any related bug reports on this therefore I think this is something that was missed in the regreation. 

##### Version

I am running Openshift Enterprise on RHEL7 

openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
etcd 3.2.1

<code>ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
</code>

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

<code>
atomic-openshift-utils-3.6.173.0.21-2.git.0.44a4038.el7.noarch
openshift-ansible-3.6.173.0.21-2.git.0.44a4038.el7.noarch
</code>

**Comment by ingvagabund** [comment]
@sdodson what about to run the certificates re-deployment as part of the `ci/openshift-jenkins/install` CI right after the deployment is done but before the conformance tests are run? It will add additional 10 minutes but still will finish before the `ci/openshift-jenkins/upgrade`.

**Comment by bortek** [comment]
Another finding. I manually removed the newline from master-config yaml file to complete the process and it went on but then what happened was that playbook started to restart docker on all nodes, one by one, going from one node to the next one *without draining pods*! So all pods went down and they never had time to start on another node. Luckily this was in the sandbox cluster. Would it have happened in production it would have been catastrophic.

Playbook should really take drain nodes , just like an upgrade playbook does it.

**Comment by sdodson** [comment]
> @sdodson what about to run the certificates re-deployment as part of the ci/openshift-jenkins/install CI right after the deployment is done but before the conformance tests are run? It will add additional 10 minutes but still will finish before the ci/openshift-jenkins/upgrade.

Yeah, Andrew and I discussed that we need to add the cert redeploy to CI. I'm hesitant to keep lumping things into install but I also don't want to fan out to 100 different jobs either. Maybe after conformance tests pass, run cert re-deploy, then run a very targeted test that would ensure that certs were replaced and that a build and deploy works correctly?

**Comment by ingvagabund** [comment]
In reality, we should re-run all the conformance tests again after the re-deployment so it would make sense to run the redeployment right after the installation. However, if we have a certificate tests that we can run and make sure everything works as expected, I am fine with that.

**Comment by bortek** [comment]
Guys I was looking further on this in my environment and I wonder if the playbook is reading contents of the SSL certificate from the Web Gui URL specified in 

openshift_master_cluster_hostname
openshift_master_cluster_public_hostname

variables and using the entries from the cert somehow? Thing is I discovered that the "Subject Alternative Names" in the cert contains two entries one of them like this

DNS Name=sandbox.mydomain.com
DNS Name=

**Comment by bortek** [comment]
This is so old :)
