### ISSUE TITLE
openshift_router_selector and openshift_registry_selector seem to be ignored now

### ISSUE THREAD

**Issue by adelton** [openshift/openshift-ansible#5615]
#### Description

On a all-on-one installation via `ansible-playbook -i ansible-inventory openshift-ansible/playbooks/byo/config.yml` which uses `openshift_router_selector`, `openshift_registry_selector` and `openshift_node_labels` , `dc/router` and `dc/docker-registry` remain stuck in `Pending` state, presumably because their `Node-Selector` is `region=infra` and there is no such node in the setup.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

```
# ansible --version
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

If you're operating from a **git clone**:

```
# git describe
openshift-ansible-3.7.0-0.137.0
```

##### Steps To Reproduce
1. Have `ansible-inventory` file

```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_disable_check=memory_availability,docker_storage,disk_availability,package_version

osm_cluster_network_cidr=10.128.0.0/14
openshift_portal_net=172.30.0.0/16
osm_host_subnet_length=9

openshift_router_selector='node-router=true'
openshift_registry_selector='node-registry=true'

openshift_master_identity_providers=[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]

[masters]
master.example.com

[etcd]
master.example.com

[nodes]
master.example.com openshift_schedulable=true openshift_node_labels="{ 'node-router': 'true', 'node-registry': 'true', 'node-app': 'true' }"
```

2. `ansible-playbook -i ansible-inventory openshift-ansible/playbooks/byo/config.yml`
3. `oc login -u system:admin`
4. `oc project default`
5. `oc status`

##### Expected Results
Describe what you expected to happen.

```
In project default on server https://master.example.com:8443

https://docker-registry-default.router.default.svc.cluster.local (passthrough) (svc/docker-registry)
  dc/docker-registry deploys docker.io/openshift3/ose-docker-registry:v3.6.173.0.21 
    deployment #1 deployed about an hour ago - 1 pod

svc/kubernetes - 172.30.0.1 ports 443->8443, 53->8053, 53->8053

https://registry-console-default.router.default.svc.cluster.local (passthrough) (svc/registry-console)
  dc/registry-console deploys registry.access.redhat.com/openshift3/registry-console:v3.6 
    deployment #1 deployed about an hour ago - 1 pod

svc/router - 172.30.149.229 ports 80, 443, 1936
  dc/router deploys docker.io/openshift3/ose-haproxy-router:v3.6.173.0.21 
    deployment #1 deployed about an hour ago - 1 pod

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
```

##### Observed Results
Describe what is actually happening.

```
In project default on server https://master.example.com:8443

https://docker-registry-default.router.default.svc.cluster.local (passthrough) (svc/docker-registry)
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:v3.6.0 
    deployment #1 pending 3 hours ago

svc/kubernetes - 172.30.0.1 ports 443->8443, 53->8053, 53->8053

https://registry-console-default.router.default.svc.cluster.local (passthrough) (svc/registry-console)
  dc/registry-console deploys docker.io/cockpit/kubernetes:latest 
    deployment #1 deployed 2 hours ago - 1 pod

svc/router - 172.30.170.5 ports 80, 443, 1936
  dc/router deploys docker.io/openshift/origin-haproxy-router:v3.6.0 
    deployment #1 pending 3 hours ago

Errors:
  * route/docker-registry is routing traffic to svc/docker-registry, but either the administrator has not installed a router or the router is not selecting this route.
  * route/registry-console is routing traffic to svc/registry-console, but either the administrator has not installed a router or the router is not selecting this route.

2 errors identified, use 'oc status -v' to see details.
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
Red Hat Enterprise Linux Server release 7.4 (Maipo)
```

**Comment by sdodson** [comment]
Sounds like something @smarterclayton had mentioned to me.
/assign michaelgugino

**Comment by adelton** [comment]
Now that I look at the output, the problem might be that I'm using master of `openshift-ansible` but the deploying images are `v3.6.0` ... is it possible that latest `openshift-ansible` is not compatible with that version.

Thing worked with the same `ansible-inventory` file until 2017-09-26 and started to fail in deterministic fashion on 2017-09-27. Unfortunately, I don't know what image version I was getting on that 2017-09-26.

**Comment by sdodson** [comment]
Master branchs hould work fine for v3.6.0. I'm pretty sure we're just not respecting the selectors due to a code refactor.

**Comment by adelton** [comment]
Thanks, I confirm that I see it fixed in my automation.
