### ISSUE TITLE
ca.txt should be on all masters

### ISSUE THREAD

**Issue by cooktheryan** [openshift/openshift-ansible#5631]
#### Description

Provide a brief description of your issue here. For example:
If a master is selected during an add node and it is not considered the first master the node will not correctly run the add node playbook. Note this is mainly with dynamic inventories and possibly will be an issue depending on where we go with 3.7.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
```
ansible 2.3.2.0
```
If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
atomic-openshift-utils-3.6.173.0.21-2.git.0.44a4038.el7.noarch
```

##### Steps To Reproduce
1. Deploy a cluster and use a dynamic inventory
2. Attempt to add a new node

##### Expected Results
Describe what you expected to happen.

Node adds

##### Observed Results
Describe what is actually happening.
Node dies due to missing file

```
failed: [ose-ocp-cns01-node03.sysdeseng.com -> ose-master03.sysdeseng.com] (item=ose-ocp-cns01-node03.sysdeseng.com) => {
    "changed": true,
    "cmd": [
        "oc",
        "adm",
        "create-api-client-config",
        "--certificate-authority=/etc/origin/master/ca.crt",
        "--client-dir=/etc/origin/generated-configs/node-ip-10-20-6-56.us-west-2.compute.internal",
        "--groups=system:nodes",
        "--master=https://internal-openshift-master.sysdeseng.com",
        "--signer-cert=/etc/origin/master/ca.crt",
        "--signer-key=/etc/origin/master/ca.key",
        "--signer-serial=/etc/origin/master/ca.serial.txt",
        "--user=system:node:ip-10-20-6-56.us-west-2.compute.internal"
    ],
    "delta": "0:00:00.158849",
    "end": "2017-04-17 17:27:29.789575",
    "failed": true,
    "item": "ose-ocp-cns01-node03.sysdeseng.com",
    "rc": 1,
    "start": "2017-04-17 17:27:29.630726",
    "warnings": []
}

STDERR:

error: --signer-serial, "/etc/origin/master/ca.serial.txt" must be a valid file
See 'oc adm create-api-client-config -h' for help and examples.
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by cooktheryan** [comment]
based on our conversation earlier @abutcher 

cc @e-minguez

**Comment by e-minguez** [comment]
In Azure ref. arch. paper we provide a [workaround](https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/azure-ansible/3.6/bastion.sh#L726-L728) in post-installation.
Also, related [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1469358) & [PR](https://github.com/openshift/openshift-ansible/pull/5085)

**Comment by DanyC97** [comment]
this should be fixed by https://github.com/openshift/openshift-ansible/pull/5085 if / when will be merged
