### ISSUE TITLE
journald still rate limits when openshift is upgraded

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-ansible#5642]
#3753 enables setting journald parameters to make log suppression less probable.  However this does not appear to be applied on upgrades.  This means that we can lose relevant messages on test_pull_request_origin_extended_conformance_install_update CI jobs.

@soltysh @smarterclayton @stevekuznetsov @gabemontero

**Comment by bparees** [comment]
@soltysh @sdodson can we get some attention on this? it's killing us on flakes+debugging flakes.

**Comment by soltysh** [comment]
I'm planning to look into it more on Monday.

**Comment by soltysh** [comment]
Actually the linked PR might be fixing this problem, since my original PR was about freshly installed clusters, whereas this PR applies to cluster updates as well. I'll keep an eye and double check that on Monday.
