### ISSUE TITLE
default('') does not work in the var directory of roles

### ISSUE THREAD

**Issue by xiama** [openshift/openshift-ansible#565]
If not define openshift_version in inventory hosts, met the following error:
 Failed to template {{ openshift_version | default('') }}

**Comment by nkhare** [comment]
I also faced similar issue. I get message like following:-
```
 Failed to template {{ openshift_version | default('') }}: recursive loop detected in template string: {{ openshift_version | default('') }}
```

**Comment by xiama** [comment]
@brenton Pls help to fix it. thx

**Comment by brenton** [comment]
This should be fixed by https://github.com/openshift/openshift-ansible/pull/563

**Comment by brenton** [comment]
@xiama, I'm sure you'll let us know if that PR doesn't work for you. :)  Thanks for the help.

**Comment by xiama** [comment]
@brenton work fine. thx
