### ISSUE TITLE
openshift_storage_glusterfs should allow to set as storageclass default

### ISSUE THREAD

**Issue by williamcaban** [openshift/openshift-ansible#5668]
#### Description

When using OpenShift storageclass of AWS or GCE, openshift-ansible automatically designate that storageclass as default. (https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_default_storage_class/defaults/main.yml)

When deploying openshift_storage_glusterfs, the resulting storageclass is not set as the default and there is no option to specify it as the default storageclass (https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_storage_glusterfs/README.md)

##### Version

OpenShift 3.6

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

```
# rpm -q atomic-openshift-utils openshift-ansible
atomic-openshift-utils-3.6.173.0.21-2.git.0.44a4038.el7.noarch
openshift-ansible-3.6.173.0.21-2.git.0.44a4038.el7.noarch
```

##### Steps To Reproduce
1. Install OpenShift w/CNS following reference example https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.byo.glusterfs.native.example
2. Once installed `oc get storageclass` will show glusterfs-storage it defined but it is not the default storageclass.

```
~]# oc describe storageclass
Name:		glusterfs-storage
IsDefaultClass:	No
Annotations:	<none>
Provisioner:	kubernetes.io/glusterfs
Parameters:	resturl=http://heketi-storage-glusterfs.cloudapp.wwtpoc.local,restuser=admin,secretName=heketi-storage-admin-secret,secretNamespace=glusterfs
Events:		<none>
```

This causes other pods requiring persistent storage to fail as there is no default storageclass.

```
# oc get pods --all-namespaces | grep -e Error -e Crash -e Pending
logging                            logging-es-data-master-5bctimqe-1-deploy   0/1       Error              0          22m
openshift-infra                    hawkular-cassandra-1-lkb06                 0/1       Pending            0          23m
```

##### Expected Results

Have the ability to define glusterfs-storage as the default storageclass.

**Comment by jstuever** [comment]
This would be great, I currently have to run the following command post-install to achieve this.
```
oc patch storageclass glusterfs-storage --patch '{"metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"}}}'
```

It would be nice to see the storageclass template contain something like the following
```
metadata:
{% if openshift_storage_glusterfs_is_default_storageclass | bool %}
   annotations:
     storageclass.beta.kubernetes.io/is-default-class: "true"
{% endif %}
```

**Comment by jarrpa** [comment]
Sounds doable! Probably won't make it in for OCP 3.7, but I can put it on the list. :)

**Comment by f1gjam** [comment]
Not trying to hi-jack issue, however, I would like to see something similar for NFS.

**Comment by jarrpa** [comment]
@f1gjam If you really don't wanna hijack, open a new Issue instead. ;)

**Comment by karmab** [comment]
supposedly , you can use the following variable to do the trick
openshift_storage_glusterfs_storageclass=true

**Comment by jstuever** [comment]
openshift_storage_glusterfs_storageclass_default=true

Was handled with #6182 after this issue was created.

**Comment by jarrpa** [comment]
Closing this issue, then. It can be reopened if someone still has a problem. :)
