### ISSUE TITLE
master certificate missing some hostnames

### ISSUE THREAD

**Issue by readonly** [openshift/openshift-ansible#568]
Using recent versions of the Ansible Installer, the master's crt's are not valid for my host name(s), but only for a list of default names like localhost, kubernetes or openshift.devault.svc.

Tracking the problem I found `set_aggregate_facts` in `openshift_facts.py`, which seems to not gather the real host name(s), and also ignores overridden hostnames set in `/etc/ansible/hosts`.  Hardcoding my hostnames into this method helps, but is very ugly.

After the ansible scripts run, I end up with 2 nodes, that can't register with their node because the reject the certificat as it is not valid for the master's hostname.

**Comment by readonly** [comment]
Seems to be related to #538 ...

**Comment by pstinghua** [comment]
It's ok if set openshift_pkg_version to 1.0.4

**Comment by readonly** [comment]
Seems to be fixed since at least v1.0.6's installer. So I'm closing the issue...
