### ISSUE TITLE
templates used for installation of heketi and gluster pods by openshift-ansible-installer must use tags

### ISSUE THREAD

**Issue by raghavendra-talur** [openshift/openshift-ansible#5685]
#### Description

Provide a brief description of your issue here. For example:

The templates that are used by openshift-ansible-installer for glusterfs and heketi don't have any tag.
This leads to a problem that when node hosting gluster pods are restarted or when docker is restarted the latest image is pulled. 

As gluster is a distributed software, we want all the pods to have same version, hence tag the images used.

##### Version
3.6

**Comment by jarrpa** [comment]
I don't think it makes sense to have specific tags upstream. It makes sense for stable, downstream products but we want to always be using the latest available container images when deploying upstream. I do agree with you that we want to make sure the pods are kept in version sync, but hardcoding it into the ansible doesn't feel like the right way forward.

I haven't read or understood it yet, but Admission Controllers might be something we could use for this: https://docs.openshift.org/3.6/architecture/additional_concepts/admission_controllers.html

**Comment by jarrpa** [comment]
@raghavendra-talur We could also, more broadly, look into image policy: https://kubernetes.io/docs/admin/admission-controllers/#imagepolicywebhook

**Comment by jarrpa** [comment]
@raghavendra-talur Here we go: https://docs.openshift.com/container-platform/3.6/admin_guide/image_policy.html

**Comment by raghavendra-talur** [comment]
This issue was solved by forcing the image version to be specified at the time of the installation.
Refer to 
* https://github.com/openshift/openshift-ansible/pull/11136
* https://github.com/openshift/openshift-ansible/pull/11751
