### ISSUE TITLE
Cloud Provider AWS

### ISSUE THREAD

**Issue by srirammageswarank** [openshift/openshift-ansible#5691]
Hi Team,

I was trying to setup OCP in AWS and i run in to the below issue.

If i enables cloud-provider as aws the nodes get registered with the private dns name. In out case the private DNS is not resolvable. Is there any way we can override it.?

Setting openshift_hostname and openshift_public_hostname did not help.

**Comment by DanyC97** [comment]
can we close this one as duplicate of #5962 ?
