### ISSUE TITLE
Metrics playbook fails with multiple errors

### ISSUE THREAD

**Issue by jsanda** [openshift/openshift-ansible#5718]
#### Description

Provide a brief description of your issue here. For example:

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

I am running OpenShift locally via,

```
oc cluster up --host-config-dir=/home/jsanda/.oc/config \
              --host-data-dir=/home/jsanda/.oc/data \
              --use-existing-config
```

I am trying to deploy metrics by running the playbooks/byo/openshift-cluster/openshift-metrics.yml playbook. I am using inventory/byo/hosts.example as my inventory file. I have encountered several, different errors and am unable to get metrics deployed. I am running on Fedora 26.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
$ ansible --version
ansible 2.3.2.0
  config file = /home/jsanda/Development/redhat/openshift/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 31 2017, 17:58:17) [GCC 7.1.1 20170503 (Red Hat 7.1.1-1)]

$ git describe
openshift-ansible-3.7.0-0.147.0

$ oc version
oc v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f

```

##### Steps To Reproduce
1. Run metrics playbook with this command line:

```
sudo ansible-playbook playbooks/byo/openshift-cluster/openshift-metrics.yml \
-e openshift_metrics_hawkular_hostname=hawkular-metrics.example.com \
-vvv -c local -i inventory/byo/hosts.example -e openshift_metrics_install_metrics=false \
-e openshift_master_unsupported_all_in_one=true -e \
openshift_master_unsupported_embedded_etcd=true
```
This fails with:

> ERROR! Attempted to read "inventory/byo/hosts.example" as ini file: inventory/byo/hosts.example:9: Section [OSEv3:children] includes undefined group: nfs`

2. Comment out nfs line (line 9) in inventory/byo/hosts.example and rerun cmd line from step 1. It then fails with a message saying python3 is required for Fedora.

3. Edit inventory/byo/hosts.example to include the python3 property, e.g.,

```
[OSEv3:vars]
ansible_python_interpreter=/usr/bin/python3
```
Rerun cmd line from step 1. It still fails with similar errors which can be viewed in [this gist](https://gist.github.com/jsanda/50de29af3489e3e68f03124619b3653f).

4. Edit playbooks/common/openshift-cluster/initialize_facts.yml to effectively disable python3 validation check and rerun cmd line from step 1. 

I canged line 53 from ```ansible_distribution == 'Fedora'``` to ```ansible_distribution == 'FedoraX'```. It now fails with:

```
TASK [openshift_version : For an RPM install, abort when the release requested does not match the available version.] *******************************
task path: /home/jsanda/Development/redhat/openshift/openshift-ansible/roles/openshift_version/tasks/main.yml:200
Tuesday 10 October 2017  16:09:34 -0400 (0:00:00.025)       0:02:23.737 ******* 
fatal: [ose3-master1-ansible.test.example.com]: FAILED! => {
    "assertion": "openshift_version.startswith(openshift_release) | bool", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "msg": "You requested openshift_release 3.7, which is not matched by\nthe latest OpenShift RPM we detected as origin-3.6.0\non host ose3-master1-ansible.test.example.com.\nWe will only install the latest RPMs, so please ensure you are getting the release\nyou expect. You may need to adjust your Ansible inventory, modify the repositories\navailable on the host, or run the appropriate OpenShift upgrade playbook."
}
```

5. Since I am not too concerned about  running 3.7, I set openshift_release=3.6 in hosts.example and reran cmd line from step 1. Now it fails with:

```
RUNNING HANDLER [openshift_metrics : restart master api] ********************************************************************************************
Tuesday 10 October 2017  16:16:08 -0400 (0:00:00.382)       0:02:33.339 ******* 
fatal: [ose3-master2-ansible.test.example.com]: FAILED! => {
    "failed": true, 
    "msg": "The conditional check '(not (master_api_service_status_changed | default(false) | bool)) and openshift.master.cluster_method == 'native'' failed. The error was: error while evaluating conditional ((not (master_api_service_status_changed | default(false) | bool)) and openshift.master.cluster_method == 'native'): 'dict object' has no attribute 'master'\n\nThe error appears to have been in '/home/jsanda/Development/redhat/openshift/openshift-ansible/roles/openshift_metrics/handlers/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: restart master api\n  ^ here\n"
}
```
At this point I was not sure what to do and decided best to file a ticket.

##### Expected Results
I expect the metrics playbook to run so that metrics components, i.e., hawkular-metrics, heapster, and cassandra get deployed.

```
Please see above
```

##### Observed Results
Please see above

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Fedora 26

```
EXTRA INFORMATION GOES HERE
```

**Comment by michaelgugino** [comment]
@jsanda The example inventories are not meant to be consumed directly.  They serve more as documentation of how inventory variables should be used.

You will need to populate a properly constructed inventory with the appropriate group names to utilize any of the plays in openshift-ansible.

**Comment by jsanda** [comment]
I had been using a different inventory file. Here it is:

```
[oo_first_master]
openshift
 
[oo_first_master:vars]
openshift_deployment_type=origin
openshift_metrics_image_prefix=openshift/origin-
openshift_metrics_image_version=latest
openshift_metrics_cassandra_storage_type=pv

cassandra/lib/jmx_prometheus_javaagent.jar=localhost:7575:/opt/hawkular/prometheus_agent/prometheus.yaml

ansible_python_interpreter=/usr/bin/python3
```
I only recently added the ansible_python_interpreter when I tried to run the playbooks from master. With this inventory file I run into some of the same and additional errors.

**Comment by mwringe** [comment]
@ewolinetz can you also help us out here? We used to be able to get metrics deployed using our simple inventory files (which only contained metrics related parameters) but something has changed and we are no longer able to deploy metrics using the metrics playbook.

Do you have an example of a simple inventory file that we should now be using to deploy metrics in our environments? The last time I tried to look into getting metrics running using the playbook I ran into multiple bugs in the ansible setup.

**Comment by ewolinetz** [comment]
@mwringe I think this is due to the missing groups that openshift-ansible is looking for.
Can you try this inventory file? (assuming this is being run on the actual master)
```yaml
[OSEv3:children]
masters

[OSEv3:vars]
openshift_deployment_type=origin
openshift_metrics_image_prefix=openshift/origin-
openshift_metrics_image_version=latest
openshift_metrics_cassandra_storage_type=pv

cassandra/lib/jmx_prometheus_javaagent.jar=localhost:7575:/opt/hawkular/prometheus_agent/prometheus.yaml

[masters]
localhost ansible_connection=local
```

**Comment by mwringe** [comment]
@ewolinetz awesome, that works :) [well, after getting around the Fedora Python 3 check]

@jsanda is there anything else which is needed here? or can we close this? It just looks like our inventory files were out of date and giving us really bad results.

**Comment by jsanda** [comment]
I got things working with the new inventory file. I still have to hack around the python3 validation check, but I can open a separate ticket for that if necessary. Thanks @ewolinetz!
