### ISSUE TITLE
openshift-etcd/scaleup.yml requires 'deployment_type=x' at run time

### ISSUE THREAD

**Issue by cooktheryan** [openshift/openshift-ansible#5743]
#### Description

Provide a brief description of your issue here. For example:
/usr/share/ansible/openshift-ansible/playbooks/byo/openshift-etcd/scaleup.yml requires that the deployment_type be passed at run time. It does not seem like it gets read from the static inventory file.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
ansible 2.3.2.0
openshift-ansible-3.7.0-0.149.0-2-ge3c8b00
```

##### Steps To Reproduce
1. launch new etcd nodes and register
2. run scaleup.yml playbook as follows
ansible-playbook -i static-inventory /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-etcd/scaleup.yml

##### Expected Results
Describe what you expected to happen.
Installation takes place
```
TASK [openshift_sanitize_inventory : Abort when deployment type is invalid] ***************************************************************************************************************************************
skipping: [ose-master01.rcook-aws.sysdeseng.com]
skipping: [ose-infra-node02.rcook-aws.sysdeseng.com]
skipping: [ose-infra-node03.rcook-aws.sysdeseng.com]
skipping: [ose-app-node01.rcook-aws.sysdeseng.com]
skipping: [ose-master02.rcook-aws.sysdeseng.com]
skipping: [ose-master03.rcook-aws.sysdeseng.com]
skipping: [ose-infra-node01.rcook-aws.sysdeseng.com]
fatal: [ose-etcd01.rcook-aws.sysdeseng.com]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

Please set openshift_deployment_type to one of:
origin, openshift-enterprise

fatal: [ose-etcd02.rcook-aws.sysdeseng.com]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

Please set openshift_deployment_type to one of:
origin, openshift-enterprise

```

##### Observed Results
Describe what is actually happening.
I think because the fact is not on the host or the variable is not being read it causes a failure. The below works.
```
ansible-playbook -i static-inventory /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-etcd/scaleup.yml  -e 'deployment_type=openshift-enterprise'
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by hardbone12** [comment]
```
TASK [openshift_sanitize_inventory : Abort when deployment type is invalid] ********************************************************************************************************************************************************************
skipping: [master.xxxxxx.xxxxxx.com]
skipping: [node1.xxxxxx.xxxxxx.com]
fatal: [node2.xxxxxx.xxxxxx.com]: FAILED! => {"changed": false, "msg": "Please set openshift_deployment_type to one of:\norigin, openshift-enterprise"}
```

It can work around with `-e` flag

ansible 2.4.2.0
openshift-ansible-3.7.16-1

**Comment by ToroNZ** [comment]
Same here... 

OCP 3.9
ansible 2.6.0
openshift-ansible-3.9.37-1-8-g5d6c8da
