### ISSUE TITLE
Installation of metrics fails on v.3.6.0

### ISSUE THREAD

**Issue by ksemaev** [openshift/openshift-ansible#5750]
#### Description
None of supported ways of installation is working for openshift 3.6.0 installed from packages on real hardware (no cloud providers)

##### Version
ansible 2.3.2.0
openshift-ansible-3.6.173.0.49-1-4-g28b1349
```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
Trying to install openshift metrics with inventory:
`openshift_metrics_install_metrics=true
openshift_metrics_image_version=v3.6.0
openshift_hosted_metrics_deployer_version=v3.6.0
openshift_metrics_hawkular_hostname=metrics.elpass
openshift_metrics_cassandra_storage_type=**see_bellow**
openshift_metrics_start_cluster=true
openshift_metrics_duration=5
openshift_metrics_cassandra_pvc_size=5Gi
`
1. when openshift_metrics_cassandra_storage_type=empty the problem is https://github.com/openshift/openshift-ansible/issues/5294

2. when openshift_metrics_cassandra_storage_type=pv the problem is:
hawkular-cassandra-1 pod gives "SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "metrics-cassandra-1", which is unexpected. "

I suppose I have to manually create pv, but there is no info on it's parameters: https://github.com/openshift/openshift-docs/issues/5704

3. when openshift_metrics_cassandra_storage_type=dynamic the problem is:
hawkular-cassandra-1 pod gives "SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "metrics-cassandra-1", which is unexpected"

The only difference between 2 and 3, is that  2 (pv) have this valuse in describe output: "storageClassName":null"

##### Expected Results
Metrics are installed sussesfully

##### Observed Results
Metrics failed to install

for **pv** value:
```
oc describe pvc metrics-cassandra-1
Name:           metrics-cassandra-1
Namespace:      openshift-infra
StorageClass:
Status:         Pending
Volume:
Labels:         metrics-infra=hawkular-cassandra
Annotations:    kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"metrics-infra":"hawkular-cassandra"},"name":"metrics-cassandr...
Capacity:
Access Modes:
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                            -------------   --------        ------          -------
  1m            12s             7       persistentvolume-controller                     Normal          FailedBinding   no persistent volumes available for this claim and no storage class is set


oc edit pvc metrics-cassandra-1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"metrics-infra":"hawkular-cassandra"},"name":"metrics-cassandra-1","namespace":"openshift-infra"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":null}}
  creationTimestamp: 2017-10-13T15:44:01Z
  labels:
    metrics-infra: hawkular-cassandra
  name: metrics-cassandra-1
  namespace: openshift-infra
  resourceVersion: "5222223"
  selfLink: /api/v1/namespaces/openshift-infra/persistentvolumeclaims/metrics-cassandra-1
  uid: 55984eb7-b02d-11e7-bfd1-005056996cbb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status:
  phase: Pending
```

for **dynamic** value:
```
oc describe pvc metrics-cassandra-1
Name:           metrics-cassandra-1
Namespace:      openshift-infra
StorageClass:
Status:         Pending
Volume:
Labels:         metrics-infra=hawkular-cassandra
Annotations:    kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"metrics-infra":"hawkular-cassandra"},"name":"metrics-cassandr...
Capacity:
Access Modes:
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                            -------------   --------        ------          -------
  1m            10s             5       persistentvolume-controller                     Normal          FailedBinding   no persistent volumes available for this claim and no storage class is set

oc edit pvc metrics-cassandra-1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"metrics-infra":"hawkular-cassandra"},"name":"metrics-cassandra-1","namespace":"openshift-infra"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}}}}
  creationTimestamp: 2017-10-13T15:48:57Z
  labels:
    metrics-infra: hawkular-cassandra
  name: metrics-cassandra-1
  namespace: openshift-infra
  resourceVersion: "5222806"
  selfLink: /api/v1/namespaces/openshift-infra/persistentvolumeclaims/metrics-cassandra-1
  uid: 065d146e-b02e-11e7-bfd1-005056996cbb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status:
  phase: Pending
```
~

Any advice is much appreciated

**Comment by Asgoret** [comment]
@ksemaev Hi, i have something same, but with GlusterFS. Check cassandra log for closed ports or check iptables rules.

In my case pvc for docker registry does not created because glusterfs node1 tried to connect to glusterfs node2 by port 24007 wich was closed.

**Comment by ksemaev** [comment]
@Asgoret thank you for advice! But how did you manage to specify which port you want to use for pvc?

**Comment by ksemaev** [comment]
Running from master branch fixes the problem at the moment. We need to find out what to commit to release-3.6 and define strict rules on how the branches should be used

**Comment by Asgoret** [comment]
@ksemaev  I don't manage glusterfs ports at this moment and probably i don't need change something from default values in the future. GlusterFS is managed by heketi service and his ports i can manage in his conf file.

**Comment by ksemaev** [comment]
moved to https://github.com/openshift/openshift-ansible/issues/5842

**Comment by zjagust** [comment]
I'm having the exact same problem. Started with metrics v3.6.0, tried with "latest" also, but same thing happens. Here are my metrics ansible hosts definitions:

# Enable metrics
openshift_master_default_subdomain=openshift.local.lan
openshift_metrics_install_metrics=true
openshift_metrics_hawkular_hostname=hawkular-metrics.openshift.local.lan
openshift_metrics_image_version=v3.6.0
openshift_metrics_cassandra_storage_type=nfs
openshift_metrics_storage_kind=nfs
openshift_metrics_storage_access_modes=['ReadWriteOnce']
openshift_metrics_storage_host=storage.local.lan
openshift_metrics_storage_nfs_directory=/media/metrics
openshift_metrics_storage_volume_name=metrics
openshift_metrics_storage_volume_size=15Gi
openshift_metrics_storage_labels={'storage': 'metrics'}

**Comment by zjagust** [comment]
Ok, I have managed to solve this by creating a PV called metrics-1 with label "storage: metrics" in openshift-infra namespace prior to executing ansible metrics playbook.

This, of course, makes me wonder why the playbook itself does not create a persistent volume before the claim is created. This would only be logical, as if there is no persistent volume present, there is no use for claim also as there is nothing to claim.
