### ISSUE TITLE
docker-registry.default.svc should be on port 443 for https by default

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#5753]
The service for the registry should be on port 443 and 5000 and new clusters should use 443.  No one should hardcode port 5000.  We don't have to upgrade the ports.

In general, the drift between oadm registry and the use cases supported in the ansible role is pretty large.  It's probably no longer productive to continue trying to keep the two in sync as they are.  We should instead consider:

1. defining a core config in origin that is part of the bootstrap yaml we store alongside oc cluster up, and output that into oadm registry rather than building from code
2. drop all flags except a few core ones on oadm registry
3. use the same core yaml in openshift-ansible and figure out a way to keep the delta small

This is a general supportability story - we have a very complex config and code in both openshift/origin and openshift-ansible (we're essentially maintaining 3 separate install paths) and we need to have one.  The core config needs to come from openshift/origin and the customization needs to be done in openshift-ansible.

**Comment by smarterclayton** [comment]
@bparees

**Comment by bparees** [comment]
> output that into oadm registry rather than building from code

not sure i followed this, do you mean oadm registry should take the core registry config yaml (that needs to be created, I guess) and customize it, rather than what it is doing today (programmatically defining a config)?

**Comment by smarterclayton** [comment]
or possibly not customize it, and just only do some small checks.  Basically dump the flags.
