### ISSUE TITLE
Logging project deploymentconfigs should not be using triggers by default

### ISSUE THREAD

**Issue by portante** [openshift/openshift-ansible#5755]
As of the filing of this issue, the `deploymentconfigs` for the `logging` project  use triggers that cause a pod to be re-deployed as soon as a change is made to the configuration.

This can have bad effects if a user is not careful to avoid too many restarts of the Elasticsearch pods with multiple edits.

We recommend changing all `logging` deploymentconfigs to _NOT_ use triggers, and add proper ansible handlers to restart services appropriately (for ES, that means a rolling restart ensuring the cluster comes back to a green state before the next ES pod is restarted).

**Comment by ewolinetz** [comment]
What kind of overhead comes with ensuring ES would not perform unnecessary operations when going through a rolling restart? Would this be something that needs to be captured in the docs as well (an advanced guide perhaps -- updating ES DC configurations)

**Comment by portante** [comment]
If one continually has one or more ES pods start and stop inadvertently because of changes to the DC, you potentially place ES in a state where it has to figure out where it was in a previous restoration on a particular set of indices that had been cleanly updated.  There are sync points [1] in ES that help minimize the length of downtime for a restoration operation.  When you have hundreds of active indices, this can be significant.  I have seen large clusters take a long time to properly recover.

Additionally, because we don't have dedicated clients, writes from fluentd/mux pods will get connection errors, causing premature backoff logic to kick in that is not warranated, and potentially cause some clients to reach their full backoff period if they hop between multiple ES pods restarting.  This in turn can cause fluentd queues to fill, and logs to stop being collected for a period of time.  While these states need to be handled by the logging service as a whole, arbitrarily causing those kinds of outages from ansible scripts seems quite unwarranted.

Keep in mind that Kubernetes does not have a notion of back-pressure on a container, where its rate of logging can be slow if an external collector cannot keep up with log scraping.

Instead, if we are performing a series of ansible operations, the state of the system can be prepared, and the down time of individual components kept to a minimum to maintain maximum uptime and service pauses.  We can properly orchestrate service restarts via ansible itself.

[1] https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-synced-flush.html
