### ISSUE TITLE
v3.6 cluster up openshift-ansible-metrics-job job fails 

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-ansible#5756]
#### Description

I may be filing this in the wrong place, but am not sure where the right place is.

- _registry.access.redhat.com/openshift3/ose-ansible:v3.6.173.0.21 is missing iproute package._

After oc login to a OCP v3.6.173.0.21 cluster, `oc cluster up --metrics` produces a job in the _openshift-infra_ fails to complete and instead runs over and over.

##### Version

Please put the following version information in the code block
indicated below.

* oc version

```
$ oc version
oc v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce

1. oc login https://ocp-3.6.173.0.21-cluster:8443
2. oc cluster up --metrics
3. oc describe jobs -n openshift-infra
4. oc get pods -n openshift-infra
5. Observe multiple `openshift-ansible-metrics-job-*` pods with Status `Error`.

##### Expected Results

Job succeeds and metrics are deployed.

##### Observed Results

`openshift-ansible-metrics-job-54mft` job in `openshift-infra` fails with this error in the logs.

```
TASK [openshift_facts : Ensure various deps are installed] *********************
failed: [127.0.0.1] (item=[u'iproute', u'python-dbus', u'PyYAML', u'yum-utils']) => {
    "changed": false,
    "failed": true,
    "item": [
        "iproute",
        "python-dbus",
        "PyYAML",
        "yum-utils"
    ],
    "rc": 126,
    "results": [
        "No package matching 'iproute' found available, installed or updated"
    ]
}
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

```
docker run --rm -ti registry.access.redhat.com/openshift3/ose-ansible:v3.6.173.0.21 rpm -q ansible iproute python-dbus PyYAML yum-utils
ansible-2.2.3.0-1.el7.noarch
package iproute is not installed
package python-dbus is not installed
PyYAML-3.10-11.el7.x86_64
yum-utils-1.1.31-42.el7.noarch
```

**Comment by siamaksade** [comment]
Is there any update on this? The same happens on Origin 3.7

**Comment by gordillo-ramon-redhat** [comment]
Same happens with minishift and ocp v3.7.9:
     
  | failed: [192.168.99.100] (item=iproute) => {"changed": false, "failed": true, "item": "iproute", "msg": "No package matching 'iproute' found available, installed or updated", "rc": 126, "results": ["**No package matching 'iproute' found available, installed or updated**"]}
  | ok: [192.168.99.100] => (item=dbus-python) => {"changed": false, "item": "dbus-python", "msg": "", "rc": 0, "results": ["dbus-python-1.1.1-9.el7.x86_64 providing dbus-python is already installed"]}
  | ok: [192.168.99.100] => (item=PyYAML) => {"changed": false, "item": "PyYAML", "msg": "", "rc": 0, "results": ["PyYAML-3.10-11.el7.x86_64 providing PyYAML is already installed"]}
  | ok: [192.168.99.100] => (item=yum-utils) => {"changed": false, "item": "yum-utils", "msg": "", "rc": 0, "results": ["yum-utils-1.1.31-42.el7.noarch providing yum-utils is already installed"]}

**Comment by gordillo-ramon-redhat** [comment]
Checked this is the problem. Installing iproute in the container (v3.7.9) the playbook moves forward, but other dependencies (hostname) also needs to be added:


TASK [Gather Cluster facts and set is_containerized if needed]
  | fatal: [192.168.99.100]: FAILED! => {"changed": false, "cmd": "hostname -f", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}

**Comment by gordillo-ramon-redhat** [comment]
And with hostname installed:

  | TASK [openshift_version : Get available atomic-openshift version] 
  | ok: [192.168.99.100] => {"changed": false, "check_mode": false, "results": {"cmd": "/usr/bin/repoquery --plugins --quiet --pkgnarrow=repos --queryformat=%{version}\|%{release}\|%{arch}\|%{repo}\|%{version}-%{release} --config=/tmp/tmplqhoNi atomic-openshift", "package_found": false, "results": "", "returncode": 0}, "state": "list"}
  | TASK [openshift_version : fail] ************************************************
  | fatal: [192.168.99.100]: FAILED! => {"changed": false, "failed": true, "msg": "Package atomic-openshift not found"}
  | PLAY RECAP *********************************************************************

**Comment by ravitri** [comment]
Hi, any update on the issue? Facing it for `docker.io/openshift/origin-ansible:v3.7` image
```
"iproute", "msg": "Failure talking to yum: Cannot find a valid baseurl for repo: base/7/x86_64"}
```

**Comment by jaenswart** [comment]
still getting this issue: Is there any known workarounds

minishift v1.11.0+d7f374a
CDK v3.3.0-1
OSCP v3.7.14

**Comment by rgordill** [comment]
That is my workaround:

from a RHEL VM, create a fixed container with following dockefile:

```
# Use the FROM according with your version
FROM registry.access.redhat.com/openshift3/ose-ansible:v3.7.23
USER root
RUN yum -y install iproute hostname atomic-openshift && \
    yum -y clean all
USER 1001
```
do a docker save on this host, and then a docker load on the minishift VM

Then, you have 2 choices. 

1) Recreate the openshift-ansible-metrics and openshift-ansible-logging job.
2) Use image caching mechanism, do a minishift image export + minishift image config-view add, so this new image is cache. Do a minishift config set image-caching true, so now you at VM creation, the image will be selected from your cache instead of a donwload. Now, with a minishfit delete + minishift start will do it everything automatically.

Hope that helps until we get the fix.

**Comment by froppel** [comment]
Where can I get the package atomic-openshift? Do I need to enable some extra channels or repos on RHEL?

**Comment by gordillo-ramon-redhat** [comment]
From 3.10 on, no metrics and logging are included in oc cluster up. This command is meant for developers, and that features seems not be needed in a dev env (where you have full control on the host).

**Comment by froppel** [comment]
I know and therefore the metrics and logging flags in minishift and cdk are gone, but I am trying to get it running with cdk and ocp-tag flag v3.7.14 or v3.9.30 but the Ansible installer fails. Even I have adjusted the ose-ansible image and installed iproute and hostname, I can not find the package atomic-openshift for installing it in my adjusted image.
