### ISSUE TITLE
etcd ca.crt has expired 1 month after it was created

### ISSUE THREAD

**Issue by roldancer** [openshift/openshift-ansible#578]
HI, For some reason the CA's certificate for the ETCD service has expired 1 month after it was created, we have deployed the OSE in HA, we have a cluster of 3 ETCD nodes.

Any idea why the etcd's CA certificate was created for just one month of ?

**Comment by abutcher** [comment]
Hey @roldancer this was fixed in #500. The lifetime for the CA is now 365 days.

**Comment by roldancer** [comment]
Many thanks !!!

**Comment by abutcher** [comment]
@brenton This issue can be closed - default is now 1 year and I'm not sure we'll want to change that.

**Comment by brenton** [comment]
Closing.  We have other BZs tracking the addition of documentation and tools to make regenerating certificates easier:

https://bugzilla.redhat.com/show_bug.cgi?id=1259150
