### ISSUE TITLE
Can we configure the expiration date for the certificates created during ansible OSE installation

### ISSUE THREAD

**Issue by roldancer** [openshift/openshift-ansible#579]
Hi, By default OSE's ansible installation creates certificates for lot of components, these certification are created for just 365 days, can we change this (365 days) default value ?

Thanks.

**Comment by abutcher** [comment]
@detiber Any objections to making this configurable? I can see the benefit in making this difficult to change...

**Comment by detiber** [comment]
@abutcher I'm not aware of a way to override the default expiration date for the certs created by the openshift CA.

I'm definitely not against overriding the default if possible though.

**Comment by abutcher** [comment]
@detiber Yep doesn't seem to be an option

**Comment by tbielawa** [comment]
@roldancer etcd expiry is configurable, openshift is not (there are no arguments available on the admin binary for controlling expiry).

I urge you to re-open this PR on the https://github.com/openshift/origin repository as a feature request.
