### ISSUE TITLE
Calico is not installed properly when containerized

### ISSUE THREAD

**Issue by fraenkel** [openshift/openshift-ansible#5795]
#### Description
I am attempting to run openshift containerized with Calico. The openshift-node fails to start because multiple mounts are missing.

##### Version
3.7

##### Steps To Reproduce
1. Enable calico
2. Configure nodes to run containerized

##### Expected Results
A running cluster with calico enabled

##### Observed Results
Nodes are errors in the logs accessing cni.

##### Additional Information
I did identify some of the missing volume mounts, e.g., /opt/cni/bin, /etc/cni/net.d, /etc/origin/calico

In the process I noticed that the node is configured and started before calico or any networking is configured. While not wrong, it does seem a bit awkward.

**Comment by kprabhak** [comment]
@fraenkel Please also take a look at this commit (which hasn't been merged upstream yet).  While the commit should allow Calico installation with OpenShift on Atomic, a couple of lines in it should address the issue you're raising.

**Comment by fraenkel** [comment]
@kprabhak which commit?

**Comment by kprabhak** [comment]
Apologies, for got to include a link. This one: https://github.com/kprabhak/openshift-ansible/commit/011a22b48ae1aa4ca9fab5ee83727eeea23c3540

**Comment by kprabhak** [comment]
yeah, agreed - something for the openshift folks to determine.

I think they had also submitted a pr to have kubelet use a configurable set of directories to search for plugins, but not able to find that at the moment.

**Comment by fraenkel** [comment]
If its what I am thinking of, it doesn't work since calico is driven after the node is already set up so there is no way for calico to add directories to the kubelet service which is how I would have liked it to work.
