### ISSUE TITLE
sinatra templates / examples aren't installed

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-ansible#580]

**Comment by sdodson** [comment]
Error message or expectations here, no idea where those should be coming from.

**Comment by thoraxe** [comment]
Currently the installer provides serveral quickstart templates for things like DancerPHP and etc.

There are no Sinatra examples/templates installed, despite us having sample applications and etc upstream.

We might want to review the list of quickstarts/templates we install by default...

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
