### ISSUE TITLE
restart docker fails after ca trust update because docker is not installed yet

### ISSUE THREAD

**Issue by sjenning** [openshift/openshift-ansible#5802]
Running at 5b838f112

```
RUNNING HANDLER [openshift_node_certificates : restart docker after updating ca trust] *********************************************
Wednesday 18 October 2017  13:22:17 -0500 (0:00:00.789)       0:09:16.192 ***** 
FAILED - RETRYING: restart docker after updating ca trust (3 retries left).
FAILED - RETRYING: restart docker after updating ca trust (3 retries left).
changed: [master.lab.variantweb.net]
FAILED - RETRYING: restart docker after updating ca trust (2 retries left).
FAILED - RETRYING: restart docker after updating ca trust (2 retries left).
FAILED - RETRYING: restart docker after updating ca trust (1 retries left).
FAILED - RETRYING: restart docker after updating ca trust (1 retries left).
fatal: [node1.lab.variantweb.net]: FAILED! => {"attempts": 3, "changed": false, "failed": true, "msg": "Could not find the requested service docker: host"}
fatal: [infra.lab.variantweb.net]: FAILED! => {"attempts": 3, "changed": false, "failed": true, "msg": "Could not find the requested service docker: host"}
```
This runs before the docker is installed on any non-master.

@frobware @sdodson

**Comment by sdodson** [comment]
All masters should be nodes for various networking related reasons. As a workaround just ensure your masters are also nodes.

**Comment by sdodson** [comment]
> All masters should be nodes for various networking related reasons. As a workaround just ensure your masters are also nodes. Maybe we should just silently make all masters nodes via the group evaluation process?

Nevermind, I misunderstood the original report.

**Comment by abutcher** [comment]
Scott pointed out that we're probably testing with hosts that have docker installed already so this must have slipped through CI. I'm going to repro and probably check for docker before doing this restart. The handler will need to continue to restart docker for certificate redeployments but we should check first.

**Comment by michaelgugino** [comment]
I thought it was known you couldn't do an RPM-based install on a host without docker being present.  I never can.

**Comment by michaelgugino** [comment]
https://docs.openshift.org/latest/install_config/install/host_preparation.html
