### ISSUE TITLE
ruby sample app template is not installed

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-ansible#581]

**Comment by sdodson** [comment]
Error message or expectations here, no idea where those should be coming from.

**Comment by thoraxe** [comment]
https://github.com/openshift/origin/tree/master/examples/sample-app

We don't provide a template for this app to be deployed as a quickstart. We might want to review what quickstarts/templates we are providing OOTB.

**Comment by vrutkovs** [comment]
Ruby sample app is included in centos/rhel imagestreams
