### ISSUE TITLE
GlusterFS 

### ISSUE THREAD

**Issue by f1gjam** [openshift/openshift-ansible#5827]
#### Description

Tried to create a persistent instance of a db it was hanging, so I then create a separate persistent volume and got the following error

```
Failed to provision volume with StorageClass "glusterfs-storage": glusterfs: create volume err: error creating volume Post http://heketi-storage-glusterfs.app.lab.unixcraft.lcl/volumes: dial tcp 192.168.10.52:80: getsockopt: connection refused.
```

##### Version

Please put the following version information in the code block
indicated below.
ansible 2.3.1.0

If you're operating from a **git clone**:

* The output of `git describe`
openshift-ansible-3.7.0-0.164.0

##### Steps To Reproduce
1. Clean install of Openshift Origin (1 * Master, 1 * Infra, 3 * App nodes) with GlusterFS 
2. Ensure  storage class is set once the install is comeplete

```
oc patch storageclass glusterfs-storage -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
```

##### Expected Results
Create storage or try to deployment anything with persistence and it should work

##### Observed Results
via the gui detailed events is showing the following error
```
Failed to provision volume with StorageClass "glusterfs-storage": glusterfs: create volume err: error creating volume Post http://heketi-storage-glusterfs.app.lab.unixcraft.lcl/volumes: dial tcp 192.168.10.52:80: getsockopt: connection refused.
```

##### Additional Information

Running on Centos 7

**Comment by jarrpa** [comment]
What does your inventory file look like?

**Comment by f1gjam** [comment]
Currently it looks like this -

```
[all:vars]
ansible_ssh_user=ansible
ansible_ssh_private_key_file=/Users/kashif/.ssh/ansible_id_rsa
#ansible_become=true

[OSEv3:children]
masters
nodes
etcd
glusterfs


[OSEv3:vars]
deployment_type=origin
openshift_master_default_subdomain=app.lab.unixcraft.lcl
osm_default_node_selector='region=lab'
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/htpasswd'}]
openshift_disable_check=memory_availability,disk_availability


# enable ntp on masters to ensure proper failover
openshift_clock_enabled=true


##Service Catalog
#openshift_enable_service_catalog=true
#openshift_service_catalog_image_prefix=openshift/origin-
#openshift_service_catalog_image_version=latest

#openshift_hosted_etcd_storage_kind=glusterfs
#openshift_hosted_etcd_storage_volume_size=1G


#GlusterFS Persistent
openshift_storage_glusterfs_namespace=glusterfs
openshift_storage_glusterfs_name=storage
openshift_storage_glusterfs_wipe=True

# Deploy logging
openshift_hosted_logging_deploy=true
openshift_hosted_logging_storage_kind=dynamic

#Deploy Metrics
openshift_hosted_metrics_deploy=true


[masters]
osmaster01.lab.unixcraft.lcl

[etcd]
osmaster01.lab.unixcraft.lcl

[glusterfs]
osond01.lab.unixcraft.lcl glusterfs_ip=192.168.10.62 glusterfs_devices='[ "/dev/sdc" ]'
osond02.lab.unixcraft.lcl glusterfs_ip=192.168.10.63 glusterfs_devices='[ "/dev/sdc" ]'
osond03.lab.unixcraft.lcl glusterfs_ip=192.168.10.64 glusterfs_devices='[ "/dev/sdc" ]'

[nodes]
osmaster01.lab.unixcraft.lcl openshift_schedulable=true
osinfra01.lab.unixcraft.lcl openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true
osond01.lab.unixcraft.lcl openshift_node_labels="{'region': 'lab', 'zone': 'lhr'}" openshift_schedulable=true
osond02.lab.unixcraft.lcl openshift_node_labels="{'region': 'lab', 'zone': 'lhr'}" openshift_schedulable=true
osond03.lab.unixcraft.lcl openshift_node_labels="{'region': 'lab', 'zone': 'lhr'}" openshift_schedulable=true
```

I have been through a few iterations, this is like my 20th install :)

**Comment by jarrpa** [comment]
Can you try the following two things and see if they work?

- `curl -X http://heketi-storage-glusterfs.app.lab.unixcraft.lcl/hello` from each node and master to make sure it's accessible. If this doesn't work, try the IP address of the heketi service with port `8080`
- `oc rsh` into the heketi pod and run `heketi-cli -s http://heketi-storage-glusterfs.app.lab.unixcraft.lcl --user admin --key <ADMIN_KEY> topology info`, where ADMIN_KEY is the generated heketi admin key contained in the `heketi-admin-secret` secret used by the StorageClass.

**Comment by f1gjam** [comment]
I ran this from the master node: curl -X GET http://heketi-storage-glusterfs.app.lab.unixcraft.lcl/hello
This was the output:
curl: (7) Failed connect to heketi-storage-glusterfs.app.lab.unixcraft.lcl:80; Connection refused

The second part, how do I get the admin secret? this was all done by ansible

**Comment by f1gjam** [comment]
ok found out: cat /etc/heketi/heketi.json  

i tried running the command inside the heketi container and it failed. It seems like the master isn't running anything to connect to the cluster?

**Comment by f1gjam** [comment]
@jarrpa - sorry for not following up on this, I was away on holiday. However I rebuilt the entire setup again from scratch with a recent pull of the master (openshift-ansible-3.7.0-0.186.0) - Everything builds fine, however I still cannot get gluster to work.

Still getting the following error:

Failed to provision volume with StorageClass "glusterfs-storage": glusterfs: create volume err: error creating volume Post http://heketi-storage-glusterfs.app.lab.unixcraft.lcl/volumes: dial tcp 192.168.10.52:80: getsockopt: connection refused.

**Comment by jarrpa** [comment]
@f1gjam Sorry for not responding the first time!

Find out the IP address of the heketi service, then re-run the `heketi-cli` command from the heketi pod using `http://<IP_ADDR>:8080` as the server address. Then also try `curl -X http://<IP_ADDR>:8080/hello` from the master node.

**Comment by f1gjam** [comment]
this works from master node:

```
[root@osmaster01 ~]# curl  http://10.130.0.2:8080/hello
Hello from Heketi[root@osmaster01 ~]#
```

**Comment by jarrpa** [comment]
Try using that IP in the StorageClass and see if you can provision. If so, something is wrong with your DNS.

**Comment by f1gjam** [comment]
@jarrpa

How do I update an existing storage class? It was all done via the installation (ansible).

Also in regards to DNS, I have the external DNS pointing to the master node with a *.apps.lab.unixcraft.lcl

All the hosts have their own records but the heketi pod is inside the cluster doesn’t that have its dns resolved internally by openshift?

**Comment by jarrpa** [comment]
@f1gjam I'm not completely certain. I think something like `oc edit storageclass <CLASS>` should do it? Otherwise modifying a YAML file of the StorageClass and then doing `oc apply -f <FILE>` should also work. You can also go the `oc patch` route like you showed at the beginning of this Issue. Note that you'll want to do `<IP>:8080`.

I'm unfortunately not intimately familiar with how DNS works in OpenShift. It seems you have a Router configured and a Service associated with heketi, since OpenShift is resolving `heketi-storage-glusterfs.app.lab.unixcraft.lcl` to `192.168.10.52:80`. However, that IP address looks like something from your host network and not internal to the cluster. I'm not sure how the Route got associated with that IP address, but that seems wrong.

**Comment by f1gjam** [comment]
@jarrpa 

Its all working now. I did NOT update the storage class. You were right about the DNS. the issue I had was I was pointing *.app.lab.unixcraft.lcl to master node (192.168.10.52) - where as I should have changed it to point to the infra node 192.168.10.92.

In my testing of different combination of nodes etc.. I didn't realize that services run on infra node if it exist etc... 

I will close the ticket and create a new one show how I created the setup in vSphere

**Comment by f1gjam** [comment]
I created a README here with the installation instructions:

https://github.com/f1gjam/unixcraft-openshift

**Comment by jarrpa** [comment]
@f1gjam That's great! Glad you go it working. :)

A small note: In your README's last section on Persistent Storage, you could also just do an `oc edit` of the StorageClass, or even more directly do `oc patch storageclass generic -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'`.

Cheers!

**Comment by f1gjam** [comment]
Thanks - I will update the readme.

I need to test out a few other things like logging. Ideally I want to test out the service catalog coming in 3.7

**Comment by f1gjam** [comment]
Actually just looking at the command, the generic class doesn't exist so you have to create it and point it to GFS
