### ISSUE TITLE
Undefined variables in openshift_metrics role

### ISSUE THREAD

**Issue by ksemaev** [openshift/openshift-ansible#5842]
#### Description
Undefined variables in openshift_metrics role in jinja template for pvc.
1) (**critical**) File _openshift-ansible\roles\openshift_metrics\templates\pvc.j2_ consists varaible _storage_class_name_;
which is defined in file _openshift-ansible\roles\openshift_metrics\tasks\install_cassandra.yaml_ for storage type **pv**, but not defined for storage type **dynamic**, which gives an error described in https://github.com/openshift/openshift-ansible/issues/5750 ("no storage class is set")

but even defining it with type=pv gives empty value, beacuse _openshift_metrics_cassanda_pvc_storage_class_name_ variable is not defined anywhere and we have the same https://github.com/openshift/openshift-ansible/issues/5750

So for this time we have to manually set this variable in inventory (or somehow ask for inserting used storage plugins).

2) (not critical)  _File openshift-ansible\roles\openshift_metrics\templates\pvc.j2_ consitsts variable pv_selector;
which defines in _openshift-ansible\roles\openshift_metrics\tasks\install_cassandra.yaml_ as
_pv_selector: "{{ openshift_metrics_cassandra_pv_selector }}"_;
which defines in _openshift-ansible\roles\openshift_metrics\defaults\main.yaml_ as
_openshift_metrics_cassandra_pv_selector: "{{ openshift_hosted_metrics_storage_labels | default('') }}"_;
and this _openshift_hosted_metrics_storage_labels_ is not defined anywhere, so why do we need this variable?

##### Version
```
ansible 2.3.2.0
openshift-ansible-3.6.173.0.58-1
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Additional Information
https://github.com/openshift/openshift-ansible/issues/5750

I could try to create neede changes, but need to contact with developers of role first.

**Comment by ksemaev** [comment]
@sdodson can you please connect me with developers of this openshift_metrics role, so we can discuss how to fix it?

**Comment by jcantrill** [comment]
@mwringe Are you familiar with these variables?

**Comment by zjagust** [comment]
According to Kubernetes documentation, a storageClassName can have an empty value (does not have to be defined), which means that persistent volume claim without defined storage class will request a persistent volume which has no class define also.

Regarding OpenShift, claims have selector defined with matchLabel variable, and that variable needs to be the same as Label variable defined for persistent volume. For instance:

PVC Definition:
selector:
    matchLabels:
      storage: metrics
  volumeName: metrics-1

PV Definition:
labels:
    storage: metrics
  name: metrics-1

I hope this helps. Here is a link to Kubernetes docs which helped me resolve this: [Kubernetes Persistant Volume Claims](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims)

**Comment by alanbchristie** [comment]
There's clearly a problem with metrics, still present in 3.11 (openshift-ansible-3.11.152-1). Whereas (for NFS) the **registry** creates its `export`, `PV` and `PVC` the playbooks for **metrics** only create the `export` and `PVC`, it does not create the `PV`.

This looks like a problem with the metrics playbook.

**Comment by alanbchristie** [comment]
Creating the following NFS-based PV after installing metrics (replacing `storage` and `server` accordingly) should allow the `hawkular-cassandra` Pod to start. You may need to bounce the `hawkular-metrics` and `heapster` Pods, depending on where you are in the installation.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-volume
spec:
  capacity:
    storage: 40Gi
  accessModes:
  - ReadWriteOnce
  volumeName: metrics-volume
  claimRef:
    name: metrics-cassandra-1
    namespace: openshift-infra
  nfs:
    path: /exports/metrics
    server: 1.2.3.4
  persistentVolumeReclaimPolicy: Retain
```
