### ISSUE TITLE
Getting Error: AnsibleUndefinedVariable: 'dict object' has no attribute 'etcd_hostname'

### ISSUE THREAD

**Issue by jerrypeng** [openshift/openshift-ansible#5893]
#### Description

So when I follow the instructions and run the ansible playbook to setup the cluster I get an error:

'AnsibleUndefinedVariable: 'dict object' has no attribute 'etcd_hostname'

I saw this was a bug in the past, but i thought it was resolved.

This is the command I ran:

ansible-playbook -i /usr/share/ansible/openshift-ansible/inventory/inventory.yml /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml -vvv

Can someone please help?

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

ansible 2.3.2.0

* The output of `git describe`

openshift-ansible-3.6.173.0.59-1-4-g31c538b9c

Place the output between the code block below:

Failure summary:

  1. Hosts:    104.154.191.86, 35.184.185.255, 35.193.150.164, 35.193.22.165
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_storage":
               Use of loopback devices with the Docker devicemapper storage driver
               (the default storage configuration) is unsupported in production.
               Please use docker-storage-setup to configure a backing storage volume.
               See http://red.ht/2rNperO for further information.

  2. Hosts:    130.211.221.166
     Play:     Configure etcd
     Task:     Write etcd global config file
     Message:  AnsibleUndefinedVariable: 'dict object' has no attribute 'etcd_hostname'

##### Steps To Reproduce

ansible-playbook -i /usr/share/ansible/openshift-ansible/inventory/inventory.yml /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml -vvv

**Comment by jerrypeng** [comment]
My inventory file:


# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
etcd
#lb
#nfs

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# Enable unsupported configurations, things that will yield a partially
# functioning cluster but would not be supported for production use
#openshift_enable_unsupported_configurations=false

# SSH user, this user should allow ssh based auth without requiring a
# password. If using ssh key based auth, then the key should be managed by an
# ssh agent.
ansible_ssh_user=jerrypeng

# If ansible_ssh_user is not root, ansible_become must be set to true and the
# user must be configured for passwordless sudo
ansible_become=yes

# Debug level for all OpenShift components (Defaults to 2)
debug_level=2

# Specify the deployment type. Valid values are origin and openshift-enterprise.
openshift_deployment_type=origin

# Specify the generic release of OpenShift to install. This is used mainly just during installation, after which we
# rely on the version running on the first master. Works best for containerized installs where we can usually
# use this to lookup the latest exact version of the container images, which is the tag actually used to configure
# the cluster. For RPM installations we just verify the version detected in your configured repos matches this
# release.
openshift_release=v3.6

# htpasswd auth
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# host group for masters
[masters]
130.211.221.166 openshift_public_ip=130.211.221.166 openshift_ip=10.128.0.13
35.184.185.255 openshift_public_ip=35.184.185.255 openshift_ip=10.128.0.15

[etcd]
130.211.221.166 openshift_public_ip=130.211.221.166 openshift_ip=10.128.0.13
35.184.185.255 openshift_public_ip=35.184.185.255 openshift_ip=10.128.0.15
35.193.22.165 openshift_public_ip=35.193.22.165 openshift_ip=10.128.0.12

# NOTE: Containerized load balancer hosts are not yet supported, if using a global
# containerized=true host variable we must set to false.
#[lb]
#ose3-lb-ansible.test.example.com containerized=false

# NOTE: Currently we require that masters be part of the SDN which requires that they also be nodes
# However, in order to ensure that your masters are not burdened with running pods you should
# make them unschedulable by adding openshift_schedulable=False any node that's also a master.
[nodes]
35.184.185.255 openshift_public_ip=35.184.185.255 openshift_ip=10.128.0.15
35.193.22.165 openshift_public_ip=35.193.22.165 openshift_ip=10.128.0.12
35.193.150.164 openshift_public_ip=35.193.150.164 openshift_ip=10.128.0.14
104.154.191.86 openshift_public_ip=104.154.191.86 openshift_ip=10.128.0.16

**Comment by jerrypeng** [comment]
my Inventory file:
    
    # Create an OSEv3 group that contains the masters and nodes groups
    [OSEv3:children]
    masters
    nodes
    etcd
    #lb
    #nfs
    
    # Set variables common for all OSEv3 hosts
    [OSEv3:vars]
    # Enable unsupported configurations, things that will yield a partially
    # functioning cluster but would not be supported for production use
    #openshift_enable_unsupported_configurations=false
    
    # SSH user, this user should allow ssh based auth without requiring a
    # password. If using ssh key based auth, then the key should be managed by an
    # ssh agent.
    ansible_ssh_user=jerrypeng
    
    # If ansible_ssh_user is not root, ansible_become must be set to true and the
    # user must be configured for passwordless sudo
    ansible_become=yes
    
    # Debug level for all OpenShift components (Defaults to 2)
    debug_level=2
    
    # Specify the deployment type. Valid values are origin and openshift-enterprise.
    openshift_deployment_type=origin
    
    # Specify the generic release of OpenShift to install. This is used mainly just during installation, after which we
    # rely on the version running on the first master. Works best for containerized installs where we can usually
    # use this to lookup the latest exact version of the container images, which is the tag actually used to configure
    # the cluster. For RPM installations we just verify the version detected in your configured repos matches this
    # release.
    openshift_release=v3.6
    
    # htpasswd auth
    openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
    
    # host group for masters
    [masters]
    130.211.221.166 openshift_public_ip=130.211.221.166 openshift_ip=10.128.0.13
    35.184.185.255 openshift_public_ip=35.184.185.255 openshift_ip=10.128.0.15
    
    [etcd]
    130.211.221.166 openshift_public_ip=130.211.221.166 openshift_ip=10.128.0.13
    35.184.185.255 openshift_public_ip=35.184.185.255 openshift_ip=10.128.0.15
    35.193.22.165 openshift_public_ip=35.193.22.165 openshift_ip=10.128.0.12
    
    # NOTE: Containerized load balancer hosts are not yet supported, if using a global
    # containerized=true host variable we must set to false.
    #[lb]
    #ose3-lb-ansible.test.example.com containerized=false
    
    # NOTE: Currently we require that masters be part of the SDN which requires that they also be nodes
    # However, in order to ensure that your masters are not burdened with running pods you should
    # make them unschedulable by adding openshift_schedulable=False any node that's also a master.
    [nodes]
    35.184.185.255 openshift_public_ip=35.184.185.255 openshift_ip=10.128.0.15
    35.193.22.165 openshift_public_ip=35.193.22.165 openshift_ip=10.128.0.12
    35.193.150.164 openshift_public_ip=35.193.150.164 openshift_ip=10.128.0.14
    104.154.191.86 openshift_public_ip=104.154.191.86 openshift_ip=10.128.0.16

**Comment by abutcher** [comment]
Looks like the playbooks should be able to continue by setting `openshift_disable_check=docker_storage` in the inventory. The health check role is failing since docker is using loopback storage.

**Comment by jkhelil** [comment]
Hi @abutcher 
What about the error related to etcd, I am getting the same error with openshift ansible relase 3.6
 uncher[9245]: TASK [etcd : Write etcd global config file] ************************************
uncher[9245]: fatal: [xxxxxxx]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict
uncher[9245]: fatal: [xxxx]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict
uncher[9245

**Comment by abutcher** [comment]
The `etcd_hostname` error occurs because we skipped the step that sets `etcd_hostname` due to the original failure.

**Comment by beevelop** [comment]
@abutcher Can you elaborate on which exact step(s) needs to succeed in order to keep this from happening? Are there any side-effects of disabling the Docker storage check via `openshift_disable_check=docker_storage`?
