### ISSUE TITLE
uninstall playbook for CNS(glusterfs) setup  

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [openshift/openshift-ansible#5926]
#### Description

To provide a uninstall playbook for dismantling CNS(glusterfs) setup. 
It should bring down gluster, heketi pods and wipe off the storage devices.

**Comment by DanyC97** [comment]
this can be closed as duplicate https://github.com/openshift/openshift-ansible/issues/6116

**Comment by jarrpa** [comment]
This is not a duplicate issue. One is a code cleanup the other is implementing new functionality.

**Comment by DanyC97** [comment]
well  both can be squash into the same feature/ request etc.
up to you if you want to keep them open / different - i see no difference...

**Comment by jarrpa** [comment]
Definitely a difference in terms of the work covered, especially since one can be done without the other. :)
