### ISSUE TITLE
dnsmasq not bound to public address - service starts too soon

### ISSUE THREAD

**Issue by dustymabe** [openshift/openshift-ansible#5935]
#### Description

On a simple 3 node cluster I end up with a system that doesn't have dns resolution after a reboot. This is because dnsmasq starts early enough where the system doesn't even have an IP on its external facing interfaces yet. In the past openshift-ansible would actually place `listen-address=x.x.x.x` into `/etc/dnsmasq.d/origin-dns.conf` so dnsmasq would fail to even start because it wasn't able to bind to that address. We no longer do that (this was changed recently) and thus dnsmasq starts fine but it's not listening on my public interface. 

##### Version

This leads to a host that can't resolve names and containers that can't resolve names either. I'm working on f26 atomic host as well as f27 atomic host. I'm operating on head at 2d0365b. 

Here is what my inventory file looks like:

<details>

```
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
etcd
glusterfs

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_user=fedora
ansible_become=true
deployment_type=origin
containerized=true
openshift_release=v3.6.1
openshift_router_selector='router=true'
openshift_registry_selector='registry=true'
openshift_master_default_subdomain=54.88.163.229.xip.io
openshift_disable_check=memory_availability,disk_availability
ansible_python_interpreter=/usr/bin/python3


openshift_storage_glusterfs_wipe=True
# tell registry to use our gluster cluster
openshift_hosted_registry_storage_kind=glusterfs

# host group for masters
[masters]
184.73.109.198 openshift_public_hostname=184.73.109.198 openshift_hostname=10.0.245.160

# host group for etcd, should run on a node that is not schedulable
[etcd]
184.73.109.198

# host group for worker nodes, we list master node here so that
# openshift-sdn gets installed. We mark the master node as not
# schedulable.
[nodes]
184.73.109.198 openshift_hostname=10.0.245.160 openshift_schedulable=false
54.88.163.229 openshift_hostname=10.0.101.185 openshift_node_labels="{'router':'true','registry':'true'}"
54.166.242.117 openshift_hostname=10.0.195.5 openshift_node_labels="{'router':'true','registry':'true'}"

[glusterfs]
184.73.109.198 glusterfs_devices='[ "/dev/xvdb" ]'
54.88.163.229 glusterfs_devices='[ "/dev/xvdb" ]'
54.166.242.117 glusterfs_devices='[ "/dev/xvdb" ]'
```

**Comment by sdodson** [comment]
/assign michaelgugino
I think we regressed this in #5891

**Comment by dustymabe** [comment]
yeah. so to be clear I think we still had a problem before #5891 because I was also seeing issues there where dnsmasq wouldn't start cleanly because it was trying to bind to an address that didn't yet exist. The good thing about that is that i could clearly see dnsmasq didn't start clean and restart it once the interface was up. 

we still need to solve the issue of: ***dnsmasq starts too early before interfaces have IP addresses***

**Comment by dustymabe** [comment]
Note there is a related bug on dnsmasq in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1502081

**Comment by michaelgugino** [comment]
This looks like a simple enough fix: https://bugs.launchpad.net/ubuntu/+source/dnsmasq/+bug/1531184

Just need to add the following to the service unit:
```
 After=network-online.target
 Wants=network-online.target
```

**Comment by dustymabe** [comment]
i know @sdodson tried something similar on my machine, didn't seem to work. @michaelgugino it would be good if you could try to recreate the problem and verify it works.

**Comment by michaelgugino** [comment]
@dustymabe I will try do to do that.  Are the interfaces in question being configured via dhcp + NetworkManager?

**Comment by dustymabe** [comment]
> @dustymabe I will try do to do that. Are the interfaces in question being configured via dhcp + NetworkManager?

In AWS, yes. I have a system in digital ocean that uses static networking config with NetworkManager that is also showing the problem so I don't think it is specific to DHCP vs no DHCP.

**Comment by dustymabe** [comment]
please also see dnsmasq maintainers suggestion: https://bugzilla.redhat.com/show_bug.cgi?id=1502081#c3

unfortunately I think 'bind-dynamic' is a relatively new option so you might not be able to use it everywhere.

**Comment by michaelgugino** [comment]
@dustymabe We decided on bind-dynamic, and that code is merged: https://github.com/openshift/openshift-ansible/pull/5953

Please let us know if that solves your issue, I believe it should.  That option appears to be available in both RHEL and CentOS 7 at this time.

**Comment by dustymabe** [comment]
i'll check

**Comment by dustymabe** [comment]
#5953 seems to work for me
