### ISSUE TITLE
logging_ops variables need to be removed

### ISSUE THREAD

**Issue by michaelgugino** [openshift/openshift-ansible#5947]
> When openshift_logging_use_ops is True, there are some additional vars. These work the same as above for their non-ops counterparts, but apply to the OPS cluster instance ...

https://github.com/openshift/openshift-ansible/blame/master/roles/openshift_logging/README.md#L102

There is a lot of duplication of logic, and confusing to trace variables through these roles and tasks.

A better way to approach this is to add a file in the logging role(s) like var/ops.yml, and conditionally include that as a first task in the roles.  The variables in those files should be the same variable names as used elsewhere (ie, no _ops_ in the variable names).

**Comment by ewolinetz** [comment]
How would we be able to specify that an logging operations elasticsearch cluster be set up differently than a non-operations elasticsearch cluster if we do not have 'ops' variables?

**Comment by michaelgugino** [comment]
```
# defaults/main.yml
some_var: 1
im_using_ops_stuff: False
```
```
# vars/ops.yml
some_var: 2
```

```
# tasks/main.yml
include_vars: ops.yml
when: im_using_ops_stuff
```

This is how I would do it.  Creating an entire second set of variables and then passing them around is pretty confusing.

**Comment by ewolinetz** [comment]
I'm not sure I'm correctly expressing my concern with this... how does a user specify different from their inventory file? The variable names are the same in the above example so if you tried to provide a different replica count for ops, it would end up the same for both kinds of ES clusters... right? Or am I missing a way that users can say for ops use this value, for non ops use this value within their inventory?

**Comment by michaelgugino** [comment]
I see what's going on here now.  I didn't realize it was deploying a whole second logging cluster, I thought these were some pre-defined values that ops wanted coded in for some reason or another.
