### ISSUE TITLE
Metrics failing on python-passlib

### ISSUE THREAD

**Issue by f1gjam** [openshift/openshift-ansible#5964]
#### Description

Trying to add Metrics to cluster it fails

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
ansible 2.3.1.0

If you're operating from a **git clone**:

* The output of `git describe`
openshift-ansible-3.7.0-0.186.0

##### Steps To Reproduce
Add parameter to inventory
```openshift_hosted_metrics_deploy=true```

Then run playbook

##### Observed Results
anged: [osmaster01.lab.unixcraft.lcl -> localhost]

TASK [openshift_metrics : Check that python-passlib is available on the control host] ****************************************************
fatal: [osmaster01.lab.unixcraft.lcl]: FAILED! => {
    "assertion": "'not installed' not in passlib_result.stdout",
    "changed": false,
    "evaluated_to": false,
    "failed": true,
    "msg": "python-passlib rpm must be installed on control host"
}
        to retry, use: --limit @/opt/kashif/github/f1gjam/ansible/openshift.retry

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
Centos 7 
```

**Comment by ewolinetz** [comment]
@f1gjam do you have `python-passlib`installed on the machine you are running the ansible playbook from?

**Comment by f1gjam** [comment]
Nope, I’m running from my Mac, I thought it needed to be installed on the machine the playbook was being executed on in this case the master node

I have installed both python-passlib and python2-passlib

**Comment by ewolinetz** [comment]
No, in this case its checking that its installed on the control host which is the machine you are running the playbook from.

**Comment by f1gjam** [comment]
installed:

pip2.7 install passlib
Requirement already satisfied: passlib in /usr/local/lib/python2.7/site-packages



TASK [openshift_metrics : Check that python-passlib is available on the control host] **********************************************************************************************************************************************************************
fatal: [osmaster01.lab.unixcraft.lcl]: FAILED! => {
    "assertion": "'not installed' not in passlib_result.stdout",
    "changed": false,
    "evaluated_to": false,
    "failed": true,
    "msg": "python-passlib rpm must be installed on control host"
}
        to retry, use: --limit @/opt/kashif/github/f1gjam/ansible/openshift.retry



ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/kashif/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible

**Comment by f1gjam** [comment]
ok, ive fixed the issue.

Even when using ansible from homebrew, you need to create a symlink in /usr/local/bin

Since homebrew only creates python2 and python3 links because it doesn't want to mess around with the system python (/usr/bin/python). You cannot create a symlink to /usr/bin/python OSX doesn't let you.

So create a link /usr/local/bin/python2 -> /usr/local/bin/python  

and ensure /usr/local/bin is in your PATH before /usr/bin and you should be good to go.

I think the requirements for the control node should be clarified, unless I missed them in the documentation.
