### ISSUE TITLE
openshift_facts role caches invalid configuration

### ISSUE THREAD

**Issue by dtschan** [openshift/openshift-ansible#599]
Today I hit an interessting issue after I misconfigured `openshift_master_identity_providers={"name":"htpasswd_auth","login":"true", ... }` instead  of `openshift_master_identity_providers=[{"name":"htpasswd_auth","login":"true", ... }]` in the ansible inventory (note the extra brackets). 

This caused the byo ansible playbook running against OSE 3.0.1.0 to fail with:

    TASK: [openshift_master | Install httpd-tools if needed] ********************** 
    fatal: [ose3-master.example.com] => with_items expects a list or a set

So far so good, it was easy enough to find out that the brackets were missing. However after fixing the inventory the ansible playbook kept failing with the obscure message:

    new_keys = set(new.keys()) - set(orig.keys())
    AttributeError: 'list' object has no attribute 'keys'

It took me several ours to find out that the `openshift_facts` role was caching the old configuration in `/etc/ansible/facts.d/openshift.fact`.

IMHO the cache should be invalidated when the inventory changes and/or the configuration should be validated before it is cached.

**Comment by abutcher** [comment]
@dtschan Thanks for reporting this issue!

@brenton I believe this can be closed. Cached facts are overwritten by any fact change but the attribute error above stopped that from happening.
