### ISSUE TITLE
One or more required container images are not available: registry.access.redhat.com/openshift3/registry-console

### ISSUE THREAD

**Issue by mbruzek** [openshift/openshift-ansible#6002]
#### Description

I ran the openshift-ansible/playbooks/byo/config.yml playbook and it failed with the following error:
```
  1. Hosts:    master-1.scale-ci.example.com
     Play:     OpenShift Health Checks
     Task:     Run health checks (install) - EL
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required container images are not available:
                   registry.access.redhat.com/openshift3/registry-console
               Checked with: skopeo inspect [--tls-verify=false] [--creds=<user>:<pass>] docker://<registry>/<image>
               Default registries searched: registry.ops.openshift.com, registry.access.redhat.com
               Failed connecting to: registry.access.redhat.com
```

##### Version

* Your ansible version per `ansible --version`
```
ansible 2.3.2.0
  config file = /home/cloud-user/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Oct 17 2017, 09:08:33) [GCC 4.8.5 20150623 (Red Hat 4.8.5-19)]
```

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`:

Place the output between the code block below:

```
openshift-ansible-3.7.0-0.189.0-4-gb4521f7

atomic-openshift-utils-3.7.0-0.189.0.git.0.d497c5e.el7.noarch
openshift-ansible-3.7.0-0.189.0.git.0.d497c5e.el7.noarch

```

##### Steps To Reproduce
1. Setup OpenStack cluster with the right number and sizes of nodes. 3 Masters+etcd, 3 infra, 2 nodes, 1 Load balancer.
2. Run the `byo/config.yml` playbook with three masters and the master did not get the required container so it failed the docker check.
3. Notice the failure on only one master! 
4. Despair and create an issue.

##### Expected Results
I expected the playbook to complete successfully.

The ansible code pulls the image. Can the code be updated to retry the image pull when it does not work or complete successfully?

##### Observed Results
The check docker images check failed and the playbook failed to install.

```
[openshift@master-1 ~]$ sudo docker images list -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
        "Linux 3.10.0-760.el7.x86_64 x86_64", 
        "NAME=\"Red Hat Enterprise Linux Server\"", 
        "VERSION=\"7.4 (Maipo)\"", 
        "ID=\"rhel\"", 
        "ID_LIKE=\"fedora\"", 
        "VARIANT=\"Server\"", 
        "VARIANT_ID=\"server\"", 
        "VERSION_ID=\"7.4\"", 
        "PRETTY_NAME=\"Red Hat Enterprise Linux Server 7.4 (Maipo)\"", 
        "ANSI_COLOR=\"0;31\"", 
        "CPE_NAME=\"cpe:/o:redhat:enterprise_linux:7.4:GA:server\"", 
        "HOME_URL=\"https://www.redhat.com/\"", 
        "BUG_REPORT_URL=\"https://bugzilla.redhat.com/\"", 
        "", 
        "REDHAT_BUGZILLA_PRODUCT=\"Red Hat Enterprise Linux 7\"", 
        "REDHAT_BUGZILLA_PRODUCT_VERSION=7.4", 
        "REDHAT_SUPPORT_PRODUCT=\"Red Hat Enterprise Linux\"", 
        "REDHAT_SUPPORT_PRODUCT_VERSION=\"7.4\""
```
```
openshift_deployment_type: openshift-enterprise
openshift_master_default_subdomain: "apps.{{ env_id }}.{{ public_dns_domain }}"

openshift_master_cluster_method: native
openshift_master_cluster_public_hostname: "console.{{ env_id }}.{{ public_dns_domain }}"
openshift_master_cluster_hostname: "{{ openshift_master_cluster_public_hostname }}"

osm_default_node_selector: 'region=primary'

openshift_hosted_router_wait: True
openshift_hosted_registry_wait: True

openshift_override_hostname_check: true
ansible_become: true

openshift_install_examples: true
openshift_examples_modify_imagestreams: true

openshift_disable_check: disk_availability,memory_availability,docker_storage

openshift_docker_additional_registries: registry.ops.openshift.com
openshift_docker_insecure_registries: registry.ops.openshift.com
cli_docker_additional_registries: registry.ops.openshift.com
cli_docker_insecure_registries: registry.ops.openshift.com

openshift_clock_enabled: true
use_cluster_metrics: true
```

I ran this install with 3 levels of verbosity and here is the task that failed:
https://gist.github.com/mbruzek/b13f31792709c696e580213dbedf0568

**Comment by mbruzek** [comment]
I ran this a second time and got a very similar error but on different nodes:
```
Failure summary:


  1. Hosts:    app-node-1.scale-ci.example.com
     Play:     OpenShift Health Checks
     Task:     Run health checks (install) - EL
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required container images are not available:
                   openshift3/ose-docker-registry:v3.7.0,
                   openshift3/ose-haproxy-router:v3.7.0,
                   openshift3/ose-pod:v3.7.0
               Checked with: skopeo inspect [--tls-verify=false] [--creds=<user>:<pass>] docker://<registry>/<image>
               Default registries searched: registry.ops.openshift.com, registry.access.redhat.com
               Failed connecting to: registry.access.redhat.com, registry.ops.openshift.com
```
I think the script needs a retry on these image pulls.

**Comment by sosiouxme** [comment]
It does look like you're falling victim to transient outages in reaching the registries. There is some retry logic that merged with https://github.com/openshift/openshift-ansible/pull/5365 so it ought to be in openshift-ansible 3.7 (and [backported to 3.6](https://github.com/openshift/openshift-ansible/pull/5393)). But it does quit trying after it's failed to reach a registry 3 times (otherwise the check would take forever to complete in the scenario where a registry is firewalled off or something).

Perhaps I could improve the JSON object returned for the check as it is not very specific about exactly how it failed to reach a registry; you have to look at the -vvv output for module runs before the result, and output from multiple hosts in parallel is mixed together, so it's hard to make out what happened. I'm not sure what more is to be done though if access to your registries is flaky. If you're confident that access to the images is available, then you can of course disable the check to proceed -- docker and openshift are a great deal more persistent about pulling requested images. Thoughts?

**Comment by sdodson** [comment]
@mbruzek has this happened again, if not do you mind closing it?

**Comment by mbruzek** [comment]
Yes of course! I haven't seen this specific error in quite some time.
