### ISSUE TITLE
gluster: temporary mountpoint gets left behind for registry 

### ISSUE THREAD

**Issue by dustymabe** [openshift/openshift-ansible#6004]
#### Description

After doing an install where I have a registry backed by glusterfs I end up with a failing systemd mount unit on every reboot of my master node: 

```
● sysroot-tmp-openshift\x2dglusterfs\x2dregistry\x2d5ufMjT.mount - /sysroot/tmp/openshift-glusterfs-registry-5ufMjT
   Loaded: loaded (/etc/fstab; generated; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-11-03 13:13:51 UTC; 2h 34min ago
    Where: /sysroot/tmp/openshift-glusterfs-registry-5ufMjT
     What: 45.55.58.69:/glusterfs-registry-volume
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
  Process: 1120 ExecMount=/usr/bin/mount 45.55.58.69:/glusterfs-registry-volume /sysroot/tmp/openshift-glusterfs-registry-5ufMjT -t glusterfs (code=exited, status=1/FAILURE)

Nov 03 13:13:51 origin-master-1.localdomain systemd[1]: Mounting /sysroot/tmp/openshift-glusterfs-registry-5ufMjT...
Nov 03 13:13:51 origin-master-1.localdomain systemd[1]: sysroot-tmp-openshift\x2dglusterfs\x2dregistry\x2d5ufMjT.mount: Mount process exited, code=exited status=1
Nov 03 13:13:51 origin-master-1.localdomain systemd[1]: Failed to mount /sysroot/tmp/openshift-glusterfs-registry-5ufMjT.
Nov 03 13:13:51 origin-master-1.localdomain systemd[1]: sysroot-tmp-openshift\x2dglusterfs\x2dregistry\x2d5ufMjT.mount: Unit entered failed state.
```

Looks like it is coming from https://github.com/openshift/openshift-ansible/blob/c99bfde17bca322e8a89ba3e9dc4e4fdc2776448/roles/openshift_hosted/tasks/storage/glusterfs.yml#L28-L39 

Is this only a temporary mount that is needed during install or is this something that needs to be persistent. Based on the answer to that we should either make sure the systemd mount unit gets cleaned up or set up the mountpoint to be somewhere more persistent than `/tmp/`. 

##### Version

Openshift-ansible @ a7a32bb targeting cluster of 3 fedora 27 atomic hosts. 

Similar inventory setup as what was provided in https://github.com/openshift/openshift-ansible/issues/5935#issue-269704409

**Comment by dustymabe** [comment]
@jarrpa - can you PTAL. Also I haven't seen you in IRC.. Away?

**Comment by jarrpa** [comment]
@dustymabe Sure thing. And no, my IRC redirector has been down since last week, and I forget to reconnect to IRC directly when I rejoin the VPN. :)

**Comment by dustymabe** [comment]
@jarrpa ping me in IRC when you get reconnected. I have some other questions.

**Comment by jarrpa** [comment]
@dustymabe Ah, I see. Yes, this is a temp mount. We just need to mount the GlusterFS volume to set the GID on the root of the volume to something the registry process uses. I'm not sure what the exact solution is, but if you know it shul dbe simple enough to automate.

**Comment by dustymabe** [comment]
Do you just 1. mount, 2. set GID, 3. unmount? Or do we not actually do the unmount? 

It looks like we should run the [mount](http://docs.ansible.com/ansible/latest/mount_module.html) module with `absent`. 

Note I do see the mount in my fstab so that's why it's trying to get mounted:

```
# cat /etc/fstab | tail -n 1
x.x.x.x:/glusterfs-registry-volume /tmp/openshift-glusterfs-registry-5ufMjT glusterfs defaults 0 0
```

**Comment by dustymabe** [comment]
looks like we need to do both `unmounted` and `absent`

**Comment by jarrpa** [comment]
Yeah, we unmount it around line 82 in the `glusterfs.yml` file. Sounds like a trivial fix, at least!

**Comment by dustymabe** [comment]
Nice. I think we just need to convert the following into a `mount` module with state of `absent`. Since that will clean up the directory as well. 

https://github.com/openshift/openshift-ansible/blob/c99bfde17bca322e8a89ba3e9dc4e4fdc2776448/roles/openshift_hosted/tasks/storage/glusterfs.yml#L87-L92

**Comment by jarrpa** [comment]
Not quite, you want this one:

https://github.com/openshift/openshift-ansible/blob/c99bfde17bca322e8a89ba3e9dc4e4fdc2776448/roles/openshift_hosted/tasks/storage/glusterfs.yml#L82-L85

**Comment by jarrpa** [comment]
...that doesn't make sense. If `specifying absent will remove the mount point directory` is true, that means the mount itself has to have been removed first...? Will an `absent` fail if an `unmounted` hasn't been set first?

**Comment by jarrpa** [comment]
Yeah, see here: https://github.com/ansible/ansible/issues/18948

> Running the mount module with state=absent both unmounts the device and removes it from fstab.

**Comment by dustymabe** [comment]
makes sense. docs were wrong 🤷‍♂️ . I think we are both on the same page.
