### ISSUE TITLE
Configure playbook should be broken up into control plane setup and then either node setup or node bootstrapping

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#6012]
In order to do bootstrapping, we should either be able to:

1. provision machines
2. run control plane
3. configure nodes
4. run openshift_hosted / addons

OR

1. provision master nodes as bootstrapping nodes
2. run control plane
3. bootstrap master nodes and add the auto-approver and auto-scaler
4. configure addons and let autoscaling create the nodes under us

I'm currently blocked between this issue and #6011 because I can't bootstrap until after hosted from a higher level.  I may disable service catalog temporarily until we fix both.

**Comment by smarterclayton** [comment]
@kwoodson @sdodson

**Comment by kwoodson** [comment]
@smarterclayton, this was my attempt to do this work for bootstrapping.

https://github.com/openshift/openshift-ansible/pull/5846

**Comment by smarterclayton** [comment]
Great, will comment.  I'm starting to see a pattern - that we'll want to do control plane setup independently of everything else, and we want control plane to be as much of a black box as adding / updating a node group.
