### ISSUE TITLE
rpm_upgrades should use state: latest

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#6013]
During an upgrade we should use state latest to fetch newer microversion rpms for the current  openshift_pkg_version.  This is mostly for clusters that are updated between minor packages.

This broke the api.ci upgrade and will break any prerelease upgrade.  We want to be able to converge alpha clusters to GA continuously.

**Comment by smarterclayton** [comment]
@sdodson

**Comment by sdodson** [comment]
I need to reproduce this, QE filed a similar bug and we fixed this in OCP and that solution should've been general enough to work for origin as well. Can you get me `grep origin /var/log/yum*` from a host so that I can see what versions have been installed in the past?
