### ISSUE TITLE
The label service catalog is using on nodes does not follow our conventions

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#6014]
It's currently defaulting to `openshift-infra: apiserver` which doesn't follow any of the core platform conventions for node labels.

It probably needs to be both namespaced and fit into Kubernetes conventions.

@sdodson this must be fixed prior to shipping 3.7 because once we release it we can't undo it.  @liggitt for opinions on whether we use the `role.node.kubernetes.io/<node>` convention for this.

**Comment by liggitt** [comment]
Also needs to coordinate with our default node selector that keeps user pods off apiservers, right?

**Comment by smarterclayton** [comment]
Yes.  We need to define a convention and stick there.  We'll have to continue to support label customization and the old labels, but new clusters should be using a convention that both the core cluster team and the lifecycle team should agree on.  This is going to be increasingly important because we're going to support a range of configurations:

- 1 master with the master also being an infra node
- 1 master, autoscaling group for infra nodes
- 3 masters, autoscaling group for infra nodes

We need to get this locked down soon.

**Comment by sdodson** [comment]
> Also needs to coordinate with our default node selector that keeps user pods off apiservers, right?

We previously did this by marking the masters unschedulable but we can't do that any longer. I believe @derekwaynecarr and @pmorie were suggesting that we use taints and tolerations instead.
