### ISSUE TITLE
Origin containerized install requires etcd from registry.access.redhat.com

### ISSUE THREAD

**Issue by e-minguez** [openshift/openshift-ansible#6018]
#### Description
Origin containerized install pulls down an image from Red Hat's internal registry (registry.access.redhat.com)

##### Version

```
Latest
```

##### Steps To Reproduce
1. Deploy Origin containerized
2. Check etcd container repo

##### Expected Results
Pull etcd image from https://hub.docker.com/u/openshift/ as others pods instead the registry.access.redhat.com one.

##### Additional Information
* Forcing the etcd container to be pulled from a F26 one seems to work

```
deployment_type=origin
containerized=true
openshift_release=v3.6
openshift_image_tag=v3.6.1

# the following was needed as 3.6.1 rpms weren't yet available
openshift_pkg_version=-3.1.0.0

osm_etcd_image=registry.fedoraproject.org/f26/etcd
```

**Comment by deuther** [comment]
Same happens to me.

**Comment by deuther** [comment]
Looks like this [commit e760ccf93410c94f174a694f3d6bb02f5a5c82e9](https://github.com/openshift/openshift-ansible/pull/6010/commits/e760ccf93410c94f174a694f3d6bb02f5a5c82e9) is suspected. 
But why the `openshift_enterprise.yaml` is used since we both use `deployment_type=origin`

**Comment by sdodson** [comment]
We can use registry.fedoraproject.org/f26/etcd as the default for origin installs but we cannot ensure stepwise upgrades so we need to modify the etcd upgrade playbooks to simply update to the latest version of the image. Otherwise this is just changing the default image in the openshift_facts module.

**Comment by e-minguez** [comment]
Shall we create an etcd container for CentOS and host it in the docker hub as we do with some other pods https://hub.docker.com/u/openshift/?

**Comment by deuther** [comment]
hmm, but I'm configuring option `openshift_use_system_containers=False` so that `etcd_image` should be ignored, right?

**Comment by kbsingh** [comment]
@bamachrn can we ensure that a full stack of origin containers, based on CentOS-PaaS-SIG content is available at registry.centos.org ? 

cc @detiber @sdodson @tdawson

**Comment by dustymabe** [comment]
> We can use registry.fedoraproject.org/f26/etcd as the default for origin installs but we cannot ensure stepwise upgrades so we need to modify the etcd upgrade playbooks to simply update to the latest version of the image. Otherwise this is just changing the default image in the openshift_facts module.

We opened an issue to see if we can do something like `registry.fedoraproject.org/latest/etcd`: https://pagure.io/atomic-wg/issue/376

**Comment by bamachrn** [comment]
> can we ensure that a full stack of origin containers, based on CentOS-PaaS-SIG content is available at registry.centos.org ?

yes we are already working to get all the origin images into registry.centos.org and getting them updated automatically. we need few things to be in place to get them in place  like https://github.com/openshift/origin/pull/17358 to get us through.
