### ISSUE TITLE
logging: allow specifying a pvc storage class name for ES deploy 

### ISSUE THREAD

**Issue by boeboe** [openshift/openshift-ansible#6028]
#As an openshift cluster admin, I would like to be able to specify a specific storage class name when going for a static VPC strategy. This is currently only possible with a non-documented internal ansible variable **openshift_logging_elasticsearch_pvc_storage_class_name**. Exposing it as a new public/documented variable **openshift_logging_es_pvc_storage_class_name** seems like an added value.

**NOTE:** in case dynamic PVC is used and no default storage class is set, the PVC creation will fail due to lack of a storage class. By allowing static PVC strategy to define a storage class, our use case was solved (currently we do this using the internal undocumented variable as mentioned above).

**Comment by boeboe** [comment]
PR created: https://github.com/openshift/openshift-ansible/pull/6029

**Comment by mayorova** [comment]
I guess this can be closed?
