### ISSUE TITLE
In openshift-enterprise, getting docker-registry error while installing openshift

### ISSUE THREAD

**Issue by sudhiragarwal098** [openshift/openshift-ansible#6043]
#### Description

When i am running atomic-openshift-installer script, it is throwing an error saying "docker_image_availability" check failed. Following is the complete error:

Failure summary:
  1. Hosts:    openshift2
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required Docker images are not available:
                   openshift3/ose-deployer:v3.6.173.0.21,
                   openshift3/ose-docker-registry:v3.6.173.0.21,
                   openshift3/ose-haproxy-router:v3.6.173.0.21,
                   openshift3/ose-pod:v3.6.173.0.21,
                   registry.access.redhat.com/openshift3/registry-console
               Configured registries: registry.access.redhat.com (unreachable)
               Checked by: timeout 10 skopeo inspect --tls-verify=false docker://{registry}/{image}

Here, Docker is not able to download those images automatically. I tried disabling the "docker_image_availability" check but this issue won't resolve the problem. It just skips that check so that we won't get that error. 

##### Version
```
atomic-openshift-utils-3.6.173.0.48-1.git.0.1609d30.el7.noarch
```

##### Steps To Reproduce
1. After completing all the required steps and setting prerequisites from the following link:
   https://docs.openshift.com/container-platform/3.6/install_config/install/quick_install.html
2. run the command atomic-openshift-installer install and give the required inputs.

##### Expected Results
Describe what you expected to happen.

```
openshift should be installed completely without any error.
```

##### Observed Results
Describe what is actually happening.

```
I am getting an error at the 9th step as mentioned above
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by sosiouxme** [comment]
You are correct that disabling the check doesn't solve the problem, just ignores it so that it manifests later in the install.

If docker pull doesn't work then this is alerting you to a legitimate problem, and there's really nothing the installer can do about it - it's up to you to have docker pull working.

The reported problem here is `Configured registries: registry.access.redhat.com (unreachable)` - so why might that registry be unreachable? Do you need a proxy configured to reach it? Is there some other network issue preventing resolving and connecting to the registry?

**Comment by sosiouxme** [comment]
I'm closing this as inactive since the error seems to be reporting a legitimate problem, but feel free to re-open this issue and provide further information so I can help.
