### ISSUE TITLE
Unable to install GlusterFS (status: in progress) when install openshift

### ISSUE THREAD

**Issue by davistran86** [openshift/openshift-ansible#6053]
I'm trying to install a fresh Openshift 3.6 origin cluster including Glusterfs, everything went smooth but only Glusterfs install show errors. Please help, thanks.

> TASK [openshift_storage_glusterfs : Label GlusterFS nodes] ********************************************************************
> Wednesday 08 November 2017  13:40:03 +0700 (0:00:00.185)       0:03:42.588 ****
> failed: [openshift-master1.aavn.local] (item=openshift-gfs1.aavn.local) => {"failed": true, "item": "openshift-gfs1.aavn.local", "msg": {"cmd": "/usr/bin/oc label node openshift-gfs1.aavn.local glusterfs=storage-host --overwrite", "results": {}, "returncode": 1, "stderr": "Error from server (NotFound): nodes \"openshift-gfs1.aavn.local\" not found\n", "stdout": ""}}
> failed: [openshift-master1.aavn.local] (item=openshift-gfs2.aavn.local) => {"failed": true, "item": "openshift-gfs2.aavn.local", "msg": {"cmd": "/usr/bin/oc label node openshift-gfs2.aavn.local glusterfs=storage-host --overwrite", "results": {}, "returncode": 1, "stderr": "Error from server (NotFound): nodes \"openshift-gfs2.aavn.local\" not found\n", "stdout": ""}}
> failed: [openshift-master1.aavn.local] (item=openshift-gfs3.aavn.local) => {"failed": true, "item": "openshift-gfs3.aavn.local", "msg": {"cmd": "/usr/bin/oc label node openshift-gfs3.aavn.local glusterfs=storage-host --overwrite", "results": {}, "returncode": 1, "stderr": "Error from server (NotFound): nodes \"openshift-gfs3.aavn.local\" not found\n", "stdout": ""}}

Here is my ansible inventory: 

> [OSEv3:children]
> masters
> nodes
> etcd
> glusterfs
> 
> [OSEv3:vars]
> openshift_clock_enabled=true
> docker_udev_workaround=True
> 
> # -- Ansible Configuration -----
> ansible_ssh_user=root
> 
> # -- OpenShift Version -----
> deployment_type=origin
> 
> # -- Configures Auth -----
> openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
> 
> # -- OpenShift Version -----
> #openshift_release=v3.6
> #openshift_image_tag=v3.6.0
> openshift_pkg_version=-3.6.0
> 
> #Fix not meet requirement
> openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability
> 
> #openshift_docker_insecure_registries=172.30.0.0/16
> 
> 
> # Skip upgrading Docker during an OpenShift upgrade, leaves the current Docker version alone.
> docker_upgrade=False
> 
> #Need to check this again:
> #containerized=true
> 
> # -- Native HA --
> #openshift_master_cluster_method=native
> openshift_master_cluster_hostname=openshift.aavn.local
> openshift_master_cluster_public_hostname=openshift.aavn.local
> 
> # -- DNS Configuration -----
> openshift_master_default_subdomain=apps.openshift.aavn.local
> 
> # -- Metrics Deployment -----
> openshift_hosted_metrics_deploy=false
> 
> [masters]
> openshift-master1.aavn.local
> openshift-master2.aavn.local
> openshift-master3.aavn.local
> 
> [etcd]
> openshift-master1.aavn.local
> openshift-master2.aavn.local
> openshift-master3.aavn.local
> 
> 
> [glusterfs]
> openshift-gfs1.aavn.local glusterfs_devices='["/dev/sdb"]'
> openshift-gfs2.aavn.local glusterfs_devices='["/dev/sdb"]'
> openshift-gfs3.aavn.local glusterfs_devices='["/dev/sdb"]'
> 
> [nodes]
> openshift-master1.aavn.local
> openshift-master2.aavn.local
> openshift-master3.aavn.local
> openshift-router1.aavn.local openshift_schedulable=True openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
> openshift-router2.aavn.local  openshift_schedulable=True openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
> openshift-node1.aavn.local openshift_schedulable=True openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
> openshift-node2.aavn.local openshift_schedulable=True openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
> openshift-gfs1.aavn.local openshift_schedulable=True openshift_node_labels="{'region': 'app'}"
> openshift-gfs2.aavn.local openshift_schedulable=True openshift_node_labels="{'region': 'app'}"
> openshift-gfs3.aavn.local openshift_schedulable=True openshift_node_labels="{'region': 'app'}"
>

**Comment by ghoul008** [comment]
[glusterfs]
gluster-manager.yukun.com     glusterfs_ip=192.168.10.119   glusterfs_devices='[ "/dev/sda3" ]'
gluster-node-1.yukun.com     glusterfs_ip=192.168.10.118   glusterfs_devices='[ "/dev/sda5" ]'
gluster-node-2.yukun.com     glusterfs_ip=192.168.10.117   glusterfs_devices='[ "/dev/sda3" ]'

try it like that

**Comment by sbadakhc** [comment]
Hi,
I'm seeing this also. Adding the ip's didn't help.

**Comment by mglantz** [comment]
I'm also seing this and it's breaking the install of CNS + OpenShift Container Platform 3.9 atleast.


[mglantz@ocpm-0 ~]$ /bin/oc label node ocpi-0.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net glusterfs=storage-host --overwrite
Error from server (NotFound): nodes "ocpi-0.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net" not found
[mglantz@ocpm-0 ~]$ ping ocpi-0.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net
PING ocpi-0.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net (192.168.2.7) 56(84) bytes of data.
64 bytes from ocpi-0.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net (192.168.2.7): icmp_seq=1 ttl=64 time=1.09 ms

But, OpenShift cannot see the nodes on which I run Gluster..

[mglantz@ocpm-0 ~]$ oc get nodes
NAME                                                         STATUS    ROLES     AGE       VERSION
ocpm-0.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net   Ready     master    33m       v1.9.1+a0ce1bc657
ocpm-1.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net   Ready     master    33m       v1.9.1+a0ce1bc657
ocpm-2.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net   Ready     master    33m       v1.9.1+a0ce1bc657
ocpn-0.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net   Ready     compute   33m       v1.9.1+a0ce1bc657

Even though they are defined in /etc/ansible/hosts

[nodes]
ocpm-0.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net openshift_node_labels="{'region': 'master', 'zone': 'default', 'role': 'master' }"
ocpm-1.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net openshift_node_labels="{'region': 'master', 'zone': 'default', 'role': 'master' }"
ocpm-2.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net openshift_node_labels="{'region': 'master', 'zone': 'default', 'role': 'master' }"
ocpi-0.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net openshift_node_labels="{'region': 'infra', 'zone': 'default', runtime: cri-o, role: infra }"
ocpi-1.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net openshift_node_labels="{'region': 'infra', 'zone': 'default', runtime: cri-o, role: infra }"
ocpi-2.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net openshift_node_labels="{'region': 'infra', 'zone': 'default', runtime: cri-o, role: infra }"
ocpn-0.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net openshift_node_labels="{'region': 'nodes', 'zone': 'default', 'runtime': 'cri-o', 'role': 'app' }"
[glusterfs]
ocpi-0.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net glusterfs_ip=192.168.2.7 glusterfs_devices='[ "/dev/sde", "/dev/sdd", "/dev/sdf" ]'
ocpi-1.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net glusterfs_ip=192.168.2.5 glusterfs_devices='[ "/dev/sde", "/dev/sdd", "/dev/sdf" ]'
ocpi-2.qajq1dqotx4efng500mket20ka.fx.internal.cloudapp.net glusterfs_ip=192.168.2.6 glusterfs_devices='[ "/dev/sde", "/dev/sdd", "/dev/sdf" ]'

**Comment by zeedune** [comment]
A somewhat late reply, but posting it here in case someone else has this problem.
I had a similar problem and I did have a missing quotation mark in my inventory file also, but I also think the order in the inventory file can play a role. I tried to move "[glusterfs]" to after the "[nodes]" section. Fixing the typo and moving the section solved the problem for me.
