### ISSUE TITLE
Prometheus default namespace should be `openshift-metrics` not `prometheus`

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#6058]
This must be changed prior to 3.7 ship.

**Comment by smarterclayton** [comment]
@zgalor

**Comment by smarterclayton** [comment]
openshift-metrics is the correct place to put it since it will be part of both monitoring and metrics pipelines.

**Comment by zgalor** [comment]
@smarterclayton @sdodson This can be closed
