### ISSUE TITLE
Gluster Deployment Fails on Initial Install Due To Python Error

### ISSUE THREAD

**Issue by dsutherland1492** [openshift/openshift-ansible#6083]
[hosts.txt](https://github.com/openshift/openshift-ansible/files/1459365/hosts.txt)
#### Description

Provide a brief description of your issue here. For example:

```
Fail to install GlusterFS due to a python error when using the advanced installer for OpenShift 3.6
```

##### Version

Please put the following version information in the code block
indicated below.
* Your ansible version per `ansible --version`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```

ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/openshift-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

atomic-openshift-utils-3.6.173.0.48-1.git.0.1609d30.el7.noarch
openshift-ansible-3.6.173.0.48-1.git.0.1609d30.el7.noarch

```

##### Steps To Reproduce
```
1.  Build your machines (3 masters, 3 infra, 3 nodes)
2.  Setup your hosts file to include glusterfs
3.  Run ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
4.  Wait for failure
```

##### Expected Results
Describe what you expected to happen.
For the command 

```
Expect it to work or error due to a configuration problem
```

##### Observed Results
Describe what is actually happening.
'``
Example command and output or error messages

For long output or logs, consider using a [gist](https://gist.github.com/)

```
TASK [openshift_storage_glusterfs : set_fact] **********************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_storage_glusterfs/tasks/glusterfs_config.yml:2
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 465, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 248, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 376, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 494, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 450, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 672, in do_template
    res = j2_concat(rf)
  File "<template>", line 12, in root
  File "/usr/share/ansible/openshift-ansible/roles/openshift_storage_glusterfs/filter_plugins/openshift_storage_glusterfs.py", line 11, in map_from_pairs
    return dict(item.split(delim) for item in source.split(","))
AttributeError: 'dict' object has no attribute 'split'
fatal: [mycluster-master-0]: FAILED! => {
    "failed": true
}
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
Red Hat Enterprise Linux Server release 7.4 (Maipo)

Hosts file is attached as host.txt

```

**Comment by slaterx** [comment]
Reproducible under centos 7 and openshift 3.7 origin.

**Comment by vrutkovs** [comment]
`openshift_storage_glusterfs_nodeselector` should be set to a `=`-separated string, as default value is `'glusterfs=storage-host'`

**Comment by DanyC97** [comment]
@slaterx @dsutherland1492 any chance you can re-test with the comment made by @vrutkovs ?

**Comment by slaterx** [comment]
@DanyC97 not reproducible on centos 7 and 3.7 origin or red hat 7 and openshift-enterprise 3.7.23.

**Comment by vrutkovs** [comment]
Closing the issue per https://github.com/openshift/openshift-ansible/issues/6083#issuecomment-370741301
