### ISSUE TITLE
Origin Install Fails on Centos7-Azure

### ISSUE THREAD

**Issue by kameshsampath** [openshift/openshift-ansible#6085]
#### Description

unable to perform successful openshift origin install on CentOS , install fails with inability to start the origin-node service

Related: https://github.com/openshift/openshift-ansible/issues/5131

##### Version

```
# ansible --version
ansible 2.4.0.0
  config file = /home/kameshs/.ansible.cfg
  configured module search path = [u'/usr/share/ansible', u'/usr/share/ansible/openshift-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

# rpm -q atomic-openshift-utils openshift-ansible
atomic-openshift-utils-3.6.173.0.60-1.el7.noarch
openshift-ansible-3.6.173.0.60-1.el7.noarch
```

##### Steps To Reproduce
1. build 4 nodes on Azure Cloud 
2. build a openshift single master and multi nodes ansible hosts like given in official docs https://docs.openshift.org/latest/install_config/install/advanced_install.html#single-master
3. run the openshift installation
4. Install fails with the following error

##### Expected Results
Successful Installation, with master, nodes started successfully

##### Observed Results
Describe what is actually happening.

```
RUNNING HANDLER [openshift_node : restart node] ********************************
skipping: [master1]
FAILED - RETRYING: restart node (3 retries left).
FAILED - RETRYING: restart node (3 retries left).
FAILED - RETRYING: restart node (3 retries left).
FAILED - RETRYING: restart node (3 retries left).
FAILED - RETRYING: restart node (2 retries left).
FAILED - RETRYING: restart node (2 retries left).
FAILED - RETRYING: restart node (2 retries left).
FAILED - RETRYING: restart node (2 retries left).
FAILED - RETRYING: restart node (1 retries left).
FAILED - RETRYING: restart node (1 retries left).
FAILED - RETRYING: restart node (1 retries left).
FAILED - RETRYING: restart node (1 retries left).
fatal: [infranode1]: FAILED! => {
    "attempts": 3, 
    "changed": false, 
    "failed": true
}

MSG:

Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.

fatal: [node02]: FAILED! => {
    "attempts": 3, 
    "changed": false, 
    "failed": true
}

MSG:

Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.

fatal: [node03]: FAILED! => {
    "attempts": 3, 
    "changed": false, 
    "failed": true
}

MSG:

Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.

fatal: [node01]: FAILED! => {
    "attempts": 3, 
    "changed": false, 
    "failed": true
}

MSG:

Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, `CentOS Linux release 7.4.1708 (Core)`
* Inventory: https://docs.openshift.org/latest/install_config/install/advanced_install.html#single-master with `dnsmasq=True`

**Comment by xqianwang** [comment]
We are facing exactly same issue.

**Comment by xqianwang** [comment]
@sdodson 
Can you please look into this? After installation, all nodes dns are missing.
example:

db0          Ready                      27m       v1.6.1+5115d708d7
db1          Ready                      27m       v1.6.1+5115d708d7
db2          Ready                      27m       v1.6.1+5115d708d7
master0      Ready,SchedulingDisabled   27m       v1.6.1+5115d708d7
master1      Ready,SchedulingDisabled   27m       v1.6.1+5115d708d7
node000000   Ready                      27m       v1.6.1+5115d708d7
node000001   Ready                      27m       v1.6.1+5115d708d7
router0      Ready                      27m       v1.6.1+5115d708d7
router1      Ready                      27m       v1.6.1+5115d708d7
sftp         Ready                      27m       v1.6.1+5115d708d7

**Comment by aizuddin85** [comment]
Do you mind to share the inventory file? And also the origin-node logging?

**Comment by andrewdobbie** [comment]
> Router0 systemd[1]: origin-node.service: main process exited, code=exited, status=255/n/a
Router0 origin-node[1939]: Invalid NodeConfig /etc/origin/node/node-config.yaml
Router0 origin-node[1939]: masterKubeConfig: Invalid value: "/etc/origin/node/system:node:Router0.kubeconfig": could not read file: stat /etc/origin/node/system:node:Router0.kubeconfig: no such file or directory
Router0 systemd[1]: Failed to start OpenShift Node.


I believe this might be what @kameshsampath is seeing. Seems that the hostname changes from FQDN to the short hostname after creating the kubeconfig. I believe that the playbook is restarting NetworkManager which is rewriting /etc/resolv.conf and removing the search line. NetworkManager 1.0 in CentOS 7.2 does not cause this problem but CentOS 7.3/7.4 use 1.4/1.8 which does not preserve the search line.

Solution seems to be
`nmcli con modify eth0 ipv4.dns-search $DOMAIN`
as Microsoft is doing in this script:
https://github.com/Microsoft/openshift-container-platform/blob/master/scripts/deployOpenShift.sh
where the DOMAIN is captured before enabling NetworkManager.
