### ISSUE TITLE
error: error getting client: couldn't read version from server: Get https://ip:8443/api: x509: cannot validate certificate for ip because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/openshift-ansible#610]
I have installed OpenShift3 with Docker and Kubernetes with the ansible installer. 
After the installation I want to create my docker registration on my master but I get the following error:
commands (from the sample):
``` 
[root@ip-10-0-0-191 centos]# export CURL_CA_BUNDLE=`pwd`/openshift.local.config/master/ca.crt
[root@ip-10-0-0-191 centos]# sudo chmod a+rwX openshift.local.config/master/admin.kubeconfig
[root@ip-10-0-0-191 centos]# sudo chmod +r openshift.local.config/master/openshift-registry.kubeconfig
[root@ip-10-0-0-191 centos]# oadm registry --create --credentials=openshift.local.config/master/openshift-registry.kubeconfig --config=openshift.local.config/master/admin.kubeconfig
 ```
error:
```error: error getting client: couldn't read version from server: Get https://10.0.0.191:8443/api: x509: cannot validate certificate for 10.0.0.191 because it doesn't contain any IP SANs```

```
[root@ip-10-0-0-191 centos]# kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.1.0-alpha.0-1605-g44c91b1", GitCommit:"44c91b1", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.1.0-alpha.0-1605-g44c91b1", GitCommit:"44c91b1", GitTreeState:"not a git tree"}
```
```
[root@ip-10-0-0-191 centos]# oc get services
NAME         CLUSTER_IP   EXTERNAL_IP   PORT(S)   SELECTOR   AGE
kubernetes   172.30.0.1   <none>        443/TCP   <none>     1d
```
```
[root@ip-10-0-0-191 centos]# kubernetes apiserver
F0924 12:15:13.674745   75545 server.go:223] No --service-cluster-ip-range specified
```

**Comment by abutcher** [comment]
@lorenzvth7 Could you try creating your registry per this doc, using the full path to kubeconfig.

https://docs.openshift.com/enterprise/3.0/install_config/install/docker_registry.html#deploy-registry

**Comment by lorenzvth7** [comment]
Already tried that, but same error

Kind Regards,

*Lorenz Vanthillo*Cloud Engineer[image: Inline afbeelding 6]
Veldkant 33a . 2550 Kontich
Tel +32 (0) 496 15 38 98
lorenz.vanthillo@evolane.be <lorenz.vanthillo@evolane.be>
www.contribute-group.be
<https://be.linkedin.com/pub/lorenz-vanthillo/b4/592/b43>
<http://summeroftechnology.eu/>

2015-09-28 17:29 GMT+02:00 Andrew Butcher <notifications@github.com>:

**Comment by lorenzvth7** [comment]
Already tried that, but same error

**Comment by lorenzvth7** [comment]
Already tried, but stillt he same error:
```
[root@ip-10-0-0-191 master]# oadm registry --config=admin.kubeconfig \
> --images='registry.access.redhat.com/openshift3/ose-${component}:${version}'
error: error getting client: couldn't read version from server: Get https://10.0.0.191:8443/api: x509: cannot validate certificate for 10.0.0.191 because it doesn't contain any IP SANs
[root@ip-10-0-0-191 master]# 
```

**Comment by abutcher** [comment]
@lorenzvth7 Please try editing your `/root/.kube/config` and change `10.0.0.191` to the hostname of your master.

If you take a look at your master certificate it should contain your master's full hostname.

```
openssl x509 -in /etc/origin/master/master.server.crt -text | grep DNS
```

**Comment by lorenzvth7** [comment]
I did not really change the hostname so it's just ```ec2-52-18-247-58.eu-west-1.compute.amazonaws.com```

It is that name in my .kube/config. The command gives the following
```[root@ip-10-0-0-191 ~]# openssl x509 -in /etc/origin/master/master.server.crt -text | grep DNS
                DNS:ec2-52-18-247-58.eu-west-1.compute.amazonaws.com, DNS:ip-10-0-0-191.eu-west-1.compute.internal```

**Comment by lorenzvth7** [comment]
Ow you were right. It's fixed: 
```
[root@ip-10-0-0-191 /]# oadm registry --config=/etc/origin/master/admin.kubeconfig \
> --credentials=/etc/origin/master/openshift-registry.kubeconfig
deploymentconfigs/docker-registry
services/docker-registry
```
