### ISSUE TITLE
Tag 3.6.0 not found in repository

### ISSUE THREAD

**Issue by randy280872** [openshift/openshift-ansible#6112]
#### Description

During the installation of openshift origin it tries to pull the openshift/origin:3.6.0 image from docker hub, I am getting "Tag 3.6.0 not found in repository docker.io/openshift/origin".
When I check docker hub it only has the "latest" tagged version of openshift origin.

##### Version

openshift 3.6.0

* Your ansible version per `ansible --version`
ansible 2.4.0.0

If you're operating from a **git clone**:
openshift-ansible

* The output of `git describe`

Playbook command
ansible-playbook -i /etc/ansible/hosts openshift-ansible/playbooks/byo/config.yml --private-key=/home/osadmin/.ssh/id_rsa -v

##### Steps To Reproduce
1. Ran ansible command above until I got to this point.
2. Manually downloaded the docker image for openshift/origin:latest and tagged it to what is expected in the playbook.

##### Expected Results
Describe what you expected to happen.
I expect openshift to be installed using the ansible playbook

Example command and output or error messages
fatal: [openshift.dev.local]: FAILED! => {
    "changed": false,
    "cmd": [
        "docker",
        "pull",
        "openshift/origin:3.6.0"
    ],
    "delta": "0:00:07.204355",
    "end": "2017-11-14 21:11:45.327221",
    "failed": true,
    "invocation": {
        "module_args": {
            "_raw_params": "docker pull openshift/origin:3.6.0",
            "_uses_shell": false,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2017-11-14 21:11:38.122866",
    "stderr": "Tag 3.6.0 not found in repository docker.io/openshift/origin",
    "stderr_lines": [
        "Tag 3.6.0 not found in repository docker.io/openshift/origin"
    ],
    "stdout": "Trying to pull repository docker.io/openshift/origin ... \nPulling repository docker.io/openshift/origin",
    "stdout_lines": [
        "Trying to pull repository docker.io/openshift/origin ... ",
        "Pulling repository docker.io/openshift/origin"
    ]
}

##### Observed Results
The installation works fine until it gets to this point where it tries to pull the 3.6.0 tagged version of the image.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version.
CentOS Linux release 7.2.1511 (Core)

* Your inventory file (especially any non-standard configuration parameters)
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=osadmin
ansible_become=true

deployment_type=origin
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/
etc/origin/master/htpasswd'}]

containerized=true
openshift_release=3.6
openshift_image_tag=3.6.0
openshift_public_hostname=openshift.dev.local
openshift_master_default_subdomain=apps.openshift.dev.local
openshift_http_proxy=http://22.147.24.100:8080/
openshift_https_proxy=https://22.147.24.100:8080/
openshift_pkg_version=-3.6.0
openshift_disable_check=docker_image_availability
enable_excluders=false

[masters]
openshift.dev.local

[nodes]
openshift.dev.local openshift_node_labels="{'zone': 'master'}"
#docker-randall.dev.local openshift_node_labels="{'zone': 'node'}"

[etcd]
openshift.dev.local

**Comment by juanwolf** [comment]
Hi @randy280872,

This issue happened to me before, you need to prefix the versions with a `v`.

Example of what I have in my inventory file: 

```
openshift_deployment_type=origin
openshift_release=v3.6
openshift_image_tag=v3.6.0
```

Hope it helps.

**Comment by randy280872** [comment]
Hi @juanwolf ,

Thank you, that worked for me!
