### ISSUE TITLE
glusterfs role cleanup

### ISSUE THREAD

**Issue by michaelgugino** [openshift/openshift-ansible#6116]
This role could use some cleanup in terms of this repository's 'coding standards'.

Item 1:  Limit use of set_fact, where possible.  Often, it is possible to avoid using set_fact, and that is preferable.

**Comment by DanyC97** [comment]
@michaelgugino  @jarrpa  am i right to believe this work can be done by just stripping all the tasks out with the condition `openshift_storage_glusterfs_wipe` and then as you said improve it such that less `set_facts` are used ?

**Comment by michaelgugino** [comment]
@DanyC97 I'm unsure about the openshift_storage_glusterfs_wipe variable, but if you want to cut a patch that limits the usage of set_fact, I'll gladly take a look.  Just @' me in that PR.

**Comment by jarrpa** [comment]
@michaelgugino @DanyC97 I ask that this not be done until master forks for 3.10 at the very least.

**Comment by DanyC97** [comment]
okay @jarrpa  then will hold off. _i'd love if i could see what big changes are coming in 3.10_  ;)

**Comment by jarrpa** [comment]
@DanyC97 It's not that big changes are coming, it's that I want to keep the branch as stable as possible until 3.9 forks. Don't introduce any changes that aren't strictly required for the release. In addition we need to backport a lot of fixes to 3.7 and 3.6, and a playbook cleanup is not something that is at all crucial to have backported quickly.

**Comment by DanyC97** [comment]
fair point @jarrpa
