### ISSUE TITLE
CNS deploy failing with heketi reporting glusterd failling to start

### ISSUE THREAD

**Issue by sosiouxme** [openshift/openshift-ansible#6126]
#### Description

I tried to install OCP 3.7 with CNS support and couldn't get it started.

##### Version

```
$ ansible --version
ansible 2.4.0.0
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

$ git describe
openshift-ansible-3.7.5-1-48-gc49dd26
```

##### Steps To Reproduce
1. `ansible-playbook playbooks/byo/config.yml` but have it break partway through the glusterfs setup. I think in my case it may have been the yum failure to install `iptables-services` or because the devices I gave gluster weren't clear of LVM partitions, or both.
2. `ansible-playbook playbooks/byo/openshift-glusterfs/config.yml` repeatedly while tweaking the inventory parameters

##### Observed Results
Heketi and three storage pods are being deployed, however heketi is reporting that glusterd didn't start in the pods. 

```
[negroni] Started POST /nodes
[sshexec] INFO 2017/11/14 21:50:22 Check Glusterd service status in node ip-172-18-9-218.ec2.internal
[kubeexec] ERROR 2017/11/14 21:50:22 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:247: Failed to run command [systemctl status glusterd] on glusterfs-storage-8ktnq: Err[command terminated with exit code 3]: Stdout [● glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2017-11-14 21:49:49 UTC; 33s ago
  Process: 110 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, status=1/FAILURE)
Nov 14 21:49:49 ip-172-18-9-218.ec2.internal systemd[1]: Starting GlusterFS, a clustered file-system server...
Nov 14 21:49:49 ip-172-18-9-218.ec2.internal systemd[1]: glusterd.service: control process exited, code=exited status=1
Nov 14 21:49:49 ip-172-18-9-218.ec2.internal systemd[1]: Failed to start GlusterFS, a clustered file-system server.
Nov 14 21:49:49 ip-172-18-9-218.ec2.internal systemd[1]: Unit glusterd.service entered failed state.
Nov 14 21:49:49 ip-172-18-9-218.ec2.internal systemd[1]: glusterd.service failed.
]: Stderr []
[sshexec] ERROR 2017/11/14 21:50:22 /src/github.com/heketi/heketi/executors/sshexec/peer.go:76: Unable to execute command on glusterfs-storage-8ktnq: 
[heketi] ERROR 2017/11/14 21:50:22 /src/github.com/heketi/heketi/apps/glusterfs/app_node.go:99: Unable to execute command on glusterfs-storage-8ktnq: 
[heketi] ERROR 2017/11/14 21:50:22 /src/github.com/heketi/heketi/apps/glusterfs/app_node.go:100: New Node doesn't have glusterd running
[negroni] Completed 400 Bad Request in 117.538247ms
```

However if I manually ssh to those pods `systemctl status glusterd` reports they are running.

```
 glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: ESC[1;32mactive (running)ESC[0m since Tue 2017-11-14 21:57:00 UTC; 40min ago
  Process: 376 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 377 (glusterd)
   CGroup: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podba5f4ab9_c985_11e7_bb5c_0ea8c9b21722.slice/docker-e1b64d267d1526127c2fe496490b7b799083575645ebfd22bf71b7bd1a930f40.scope/system.slice/glusterd.service
           └─377 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO...

Nov 14 21:56:59 ip-172-18-9-218.ec2.internal systemd[1]: ESC[1;39mglusterd.service: ma...ESC[0m
Nov 14 21:56:59 ip-172-18-9-218.ec2.internal systemd[1]: ESC[1;39mUnit glusterd.servic...ESC[0m
Nov 14 21:56:59 ip-172-18-9-218.ec2.internal systemd[1]: ESC[1;39mglusterd.service fai...ESC[0m
Nov 14 21:56:59 ip-172-18-9-218.ec2.internal systemd[1]: Starting GlusterFS, ...
Nov 14 21:57:00 ip-172-18-9-218.ec2.internal systemd[1]: Started GlusterFS, a...
Hint: Some lines were ellipsized, use -l to show in full.

```

See attached tarball of inventory and outputs.
[logs.tar.gz](https://github.com/openshift/openshift-ansible/files/1475842/logs.tar.gz)

**Comment by sosiouxme** [comment]
@jarrpa for your consideration...

**Comment by jarrpa** [comment]
@sosiouxme Where did the file `glusterfs-status` come from? I noticed this line:
```
  * route/heketi-storage is routing traffic to svc/deploy-heketi-storage, but either the administrator has not installed a router or the router is not selecting this route.
```
Is that normal?

Since the playbooks fail at the GlusterFS portion, there should still be a temp directory on the machine running the playbooks with the files it was working with. Can you go to that directory and try manually running the topology load command? Both the directory name and the command should be in the output of the ansible run.

**Comment by sosiouxme** [comment]
>  Where did the file glusterfs-status come from?
>

That comes from running `oc status` in the glusterfs project. Just an
overview of what's there (although it leaves out daemonsets among other
things).


> I noticed this line:
>
>   * route/heketi-storage is routing traffic to svc/deploy-heketi-storage, but either the administrator has not installed a router or the router is not selecting this route.
>
> Is that normal?
>

It's normal if there's no router installed. I'm thinking the glusterfs
portion of the install happens before that.


> Since the playbooks fail at the GlusterFS portion, there should still be a
> temp directory on the machine running the playbooks with the files it was
> working with. Can you go to that directory and try manually running the
> topology load command? Both the directory name and the command should be in
> the output of the ansible run.
>
>
That cluster is blown away now, sorry. I tried another install today and it
failed for several reasons other than glusterfs, will probably try again
tomorrow.

**Comment by sosiouxme** [comment]
I'm not seeing this again; may have been due to the non-idempotent nature of the playbook. Can close unless you want to investigate more.
