### ISSUE TITLE
Openshift origin 3.6.1 install fails on rhel server 7.4 

### ISSUE THREAD

**Issue by djslavens** [openshift/openshift-ansible#6133]
#### Description

> Trying to install openshift origin on two rhel 7.4 VMs booted on libvirt instance using byo
> using one VM as master/node and one VM node as specified in inventory below
> playbook fails on curl command

##### Version

* Your ansible version per `ansible --version`
  ansible 2.3.1.0

* The output of `git describe`
   openshift-ansible-3.7.5-1-36-gc5afbd8

Place the output between the code block below:

```
```

##### Steps To Reproduce
1. Install 2 rhel server 7.4 VMs on host using libvirtd - one as master/node, one as node
2. Use inventory below to install openshift origin 3.6.1

##### Expected Results
Describe what you expected to happen.

Install openshift origin 3.6.1 using this command:

```
ansible-playbook -i /etc/ansible/hosts openshift-ansible/playbooks/byo/config.yml --private-key=vminstall.key -vvv

```

##### Observed Results
Describe what is actually happening.

The playbook fails on the following task. Note the URL passed to the curl command has dashes in the URL value instead of periods:

TASK [openshift_node : Wait for master API to become available before proceeding] 
task path: /home/openshift/openshift-ansible/roles/openshift_node/tasks/config.yml:60

(note the output below has --verbose curl option and 20 iterations - the same behavior occurs
with curl --silent option and 120 iterations)

```
fatal: [node.openshift.vm.com]: FAILED! => {
    "attempts": 20, 
    "changed": false, 
    "cmd": [
        "curl", 
        "--verbose", 
        "--tlsv1.2", 
        "--cacert", 
        "/etc/origin/node/ca.crt", 
        "https://master-openshift-vm-com:8443/healthz/ready"
    ], 
    "delta": "0:00:00.016856", 
    "end": "2017-11-15 18:51:36.136985", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "curl --verbose --tlsv1.2 --cacert /etc/origin/node/ca.crt https://master-openshift-vm-com:8443/healthz/ready", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": false
        }
    }, 
    "rc": 6, 
    "start": "2017-11-15 18:51:36.120129", 
    "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Could not resolve host: master-openshift-vm-com; Name or service not known\n* Closing connection 0\ncurl: (6) Could not resolve host: master-openshift-vm-com; Name or service not known", 
    "stderr_lines": [
        "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", 
        "                                 Dload  Upload   Total   Spent    Left  Speed", 
        "", 
        "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Could not resolve host: master-openshift-vm-com; Name or service not known", 
        "* Closing connection 0", 
        "curl: (6) Could not resolve host: master-openshift-vm-com; Name or service not known"
    ], 
    "stdout": "", 
    "stdout_lines": []
}
	to retry, use: --limit @/home/openshift/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP ***************************************************************************************************************************************************************
localhost                  : ok=13   changed=0    unreachable=0    failed=0   
master.openshift.vm.com    : ok=451  changed=47   unreachable=0    failed=0   
node.openshift.vm.com      : ok=140  changed=9    unreachable=0    failed=1   


INSTALLER STATUS *********************************************************************************************************************************************************
Initialization             : Complete (0:22:48)
Health Check               : Complete (0:00:03)
etcd Install               : Complete (0:35:07)
Master Install             : Complete (1:24:18)
Master Additional Install  : Complete (0:19:19)
Node Install               : In Progress (0:52:24)
	This phase can be restarted by running: playbooks/byo/openshift-node/config.yml



Failure summary:


  1. Hosts:    node.openshift.vm.com
     Play:     Configure nodes
     Task:     Wait for master API to become available before proceeding
     Message:  Failed without returning a message.
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* It was also observed a few yaml config files have URLs with dashes instead of periods in the following files with the file and the URL value listed:

* master vm:

  /etc/origin/master/master-config.yaml
  oauthConfig:
     masterURL: https://master-openshift-vm-com:8443

  /etc/origin/node/node-config.yaml 
  nodeName: master-openshift-vm-com

* node vm:

  /etc/origin/node/node-config.yaml
  nodeName: node-openshift-vm-com

* /etc/redhat-release
  Red Hat Enterprise Linux Server release 7.4 (Maipo)
* Inventory file:

```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=origin
containerized=true
openshift_docker_options="--selinux-enabled --log-driver=journald --insecure-registry 172.30.0.0/16"
openshift_public_hostname=master.openshift.vm.com
openshift_master_default_subdomain=apps.master.openshift.vm.com
openshift_master_identity_providers=[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]
openshift_release=v3.6.1
openshift_image_tag=v3.6.1
openshift_disable_check=disk_availability,memory_availability,package_availability,docker_image_availability,docker_storage,package_version

[masters]
master.openshift.vm.com

[etcd]
master.openshift.vm.com

[nodes]
master.openshift.vm.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}" openshift_schedulable=true
node.openshift.vm.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
```

Thanks for your help!

**Comment by jaypoulz** [comment]
So far in debugging this issue, we're determined that the DNS lookup fails because the node uses `node-openshift-vm-com` for it's curl base url instead of the correct url `node.openshift.vm.com`.

Using the correct URL on the server results in successfully pulling down the health check file, containing the contents `OK`.

Issues with similar behavior that have been logged in the past include #1662, #3800, and #2271. However, while these issues bring up various network manager / dns issues, they do not seem to exhibit the same behavior. For some reason, the node health check lookup is searching at the wrong url, and it is unclear why.

**Comment by cello86** [comment]
I noticed the same issue on RHEL 7.4 and OSE 3.6.0

**Comment by detiber** [comment]
@sdodson ptal

**Comment by sdodson** [comment]
What does master.openshift.vm.com think its hostname is? `hostname --long` on the host.

**Comment by djslavens** [comment]
Here it is:

[root@master-openshift-vm-com ~]# hostname --long
master-openshift-vm-com

**Comment by sdodson** [comment]
From the email thread I see that your hosts believe their hostnames are like `node-openshift-vm-com`. I've not kept up with libvirt but I believe this comes from the vm name but i'd expect it to also configure dnsmasq for that so it should resolve. You could try either stopping the vm and renaming the vm in virt-manager/libvirt or you can override the hostname for each host in your inventory like the following.

```
[masters]
master.openshift.vm.com openshift_hostname=master.openshift.vm.com

[etcd]
master.openshift.vm.com 

[nodes]
master.openshift.vm.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}" openshift_schedulable=true openshift_hostname=master.openshift.vm.com
node.openshift.vm.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}" openshift_hostname=node.openshift.vm.com
```
Finally, setting the hostname within the vm would probably work too

`hostnamectl set-hostname --static master.openshift.vm.com`

**Comment by cello86** [comment]
If you configure the installation if the LB and during this phase you restart the docker engine, the master APIs become available. I noticed this issue only with the version 3.7.0 and not 3.6.1

Marcello

**Comment by ybaumy** [comment]
can somebody tell me what to set if i have 3 masters / a oad balancer and the same problem?

i tried several combinations.

Thats my initial setup...

[masters]
ocp-master-1.vdc1-ext.local 
ocp-master-2.vdc1-ext.local 
ocp-master-3.vdc1-ext.local 

[etcd]
ocp-etcd-1.vdc1-ext.local
ocp-etcd-2.vdc1-ext.local
ocp-etcd-3.vdc1-ext.local

[lb]
ocp-lb-1.vdc1-ext.local

[nodes]
ocp-master-[1:3].vdc1-ext.local
ocp-worker-1.vdc1-ext.local openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
ocp-worker-2.vdc1-ext.local openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
ocp-worker-3.vdc1-ext.local openshift_node_labels="{'region': 'primary', 'zone': 'default'}"

**Comment by ybaumy** [comment]
this is how i got it to work for ppl who have the same problem...

openshift_public_hostname=ocp-lb1-1.vdc1-ext.local
openshift_master_cluster_hostname=ocp-lb-1.vdc1-ext.local
openshift_master_cluster_public_hostname=ocp-lb-1.vdc1-ext.local

[masters]
ocp-master-1.vdc1-ext.local openshift_hostname=ocp-master-1.vdc1-ext.local
ocp-master-2.vdc1-ext.local openshift_hostname=ocp-master-2.vdc1-ext.local
ocp-master-3.vdc1-ext.local openshift_hostname=ocp-master-3.vdc1-ext.local

[etcd]
ocp-etcd-1.vdc1-ext.local
ocp-etcd-2.vdc1-ext.local
ocp-etcd-3.vdc1-ext.local

[lb]
ocp-lb-1.vdc1-ext.local

[nodes]
ocp-master-[1:3].vdc1-ext.local openshift_schedulable=false
ocp-worker-1.vdc1-ext.local openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
ocp-worker-2.vdc1-ext.local openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
ocp-worker-3.vdc1-ext.local openshift_node_labels="{'region': 'primary', 'zone': 'default'}"


and then 

ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/redeploy-certificates.retry
without the last step you will still have the old certs with the wrong names.

hope that helps somebody
