### ISSUE TITLE
tuneable prometheus 

### ISSUE THREAD

**Issue by mrsiano** [openshift/openshift-ansible#6137]
this issue is more about RFE
based on the template
https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_prometheus/templates

we want to have the ability to extend some prometheus args on demand e.g
https://github.com/mbruzek/ansible-openstack-setup/blob/9b7117eb97e868f96f46a10866ff687f5ba72e5f/templates/prometheus-high-performance.yaml#L147

so instead of using custom template, it will be better to use openshift-ansible.
having some byo ini file that specified the relevant args, might be good fit, please advise

**Comment by mrsiano** [comment]
@jeremyeder @mbruzek

**Comment by mrsiano** [comment]
@sdodson

**Comment by sdodson** [comment]
Seems reasoanble to allow specifying a list of arbitrary args to be included by the template.
/assign zgalor

**Comment by zgalor** [comment]
https://github.com/openshift/openshift-ansible/pull/6175 submitted

**Comment by mbruzek** [comment]
> we may consider how we can expose those args outside of byo

@mrsiano I believe the way to do this is use variables we can set before calling the byo playbook. Other contributors to the project have been asked to namespace the variables so they do not collide. So you could preface the variables with "`prometheus_`" or  something like that.

**Comment by mrsiano** [comment]
@mbruzek by this patch #6175 it will be easier, we can play the byo inventory as well.

**Comment by jeremyeder** [comment]
can this issue be closed now that #6175 is merged?

**Comment by sdodson** [comment]
yes i think so, please open a new issue if anyone finds bugs
