### ISSUE TITLE
Create the Broker resource in the catalog Error!

### ISSUE THREAD

**Issue by fanshengado** [openshift/openshift-ansible#6166]
TASK [ansible_service_broker : Create the Broker resource in the catalog] *******************************************************
task path: /root/openshift-ansible-openshift-ansible-3.7.8-1/roles/ansible_service_broker/tasks/install.yml:459
fatal: [master01.openshift.local]: FAILED! => {"changed": false, "failed": true, "msg": {"cmd": "/usr/bin/oc create -f /tmp/brokerout-3D9eja -n default", "results": {}, "returncode": 1, "stderr": "error: unable to recognize \"/tmp/brokerout-3D9eja\": no matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker\n", "stdout": ""}}
        to retry, use: --limit @/root/openshift-ansible-openshift-ansible-3.7.8-1/playbooks/byo/openshift-cluster/service-catalog.retry

PLAY RECAP **********************************************************************************************************************
etcd01.openshift.local     : ok=37   changed=2    unreachable=0    failed=0
localhost                  : ok=11   changed=0    unreachable=0    failed=0
master01.openshift.local   : ok=112  changed=37   unreachable=0    failed=1
node01.openshift.local     : ok=43   changed=2    unreachable=0    failed=0
node02.openshift.local     : ok=43   changed=2    unreachable=0    failed=0
node03.openshift.local     : ok=43   changed=2    unreachable=0    failed=0

INSTALLER STATUS ****************************************************************************************************************
Initialization             : Complete
Service Catalog Install    : In Progress
        This phase can be restarted by running: playbooks/byo/openshift-cluster/service-catalog.yml

[root@master01 ~]# oc get all --all-namespaces   

NAMESPACE                          NAME                  REVISION   DESIRED   CURRENT   TRIGGERED BY
default                            dc/docker-registry    1          1         1         config
default                            dc/registry-console   1          1         1         config
default                            dc/router             1          1         1         config
openshift-ansible-service-broker   dc/asb                1          1         1         config
openshift-ansible-service-broker   dc/asb-etcd           1          1         1         config

NAMESPACE                          NAME                    DESIRED   CURRENT   READY     AGE
default                            rc/docker-registry-1    1         1         1         3h
default                            rc/registry-console-1   1         1         1         3h
default                            rc/router-1             1         1         1         3h
openshift-ansible-service-broker   rc/asb-1                1         1         0         2m
openshift-ansible-service-broker   rc/asb-etcd-1           1         1         0         2m

NAMESPACE                          NAME                      HOST/PORT                                                                   PATH      SERVICES           PORT      TERMINATION   WILDCARD
default                            routes/docker-registry    docker-registry-default.router.default.svc.cluster.local                              docker-registry    <all>     passthrough   None
default                            routes/registry-console   registry-console-default.router.default.svc.cluster.local                             registry-console   <all>     passthrough   None
kube-service-catalog               routes/apiserver          apiserver-kube-service-catalog.router.default.svc.cluster.local                       apiserver          secure    passthrough   None
openshift-ansible-service-broker   routes/asb-1338           asb-1338-openshift-ansible-service-broker.router.default.svc.cluster.local             asb                1338      reencrypt     None

NAMESPACE                          NAME                     CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
default                            svc/docker-registry      172.30.43.33     <none>        5000/TCP                  3h
default                            svc/kubernetes           172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     5h
default                            svc/registry-console     172.30.104.137   <none>        9000/TCP                  3h
default                            svc/router               172.30.244.233   <none>        80/TCP,443/TCP,1936/TCP   3h
kube-service-catalog               svc/apiserver            172.30.21.107    <none>        443/TCP                   4m
kube-service-catalog               svc/controller-manager   172.30.88.50     <none>        6443/TCP                  3m
openshift-ansible-service-broker   svc/asb                  172.30.165.214   <none>        1338/TCP                  2m
openshift-ansible-service-broker   svc/asb-etcd             172.30.176.14    <none>        2379/TCP                  2m

NAMESPACE                          NAME                          READY     STATUS              RESTARTS   AGE
default                            po/docker-registry-1-3tchc    1/1       Running             0          3h
default                            po/registry-console-1-rfm4w   1/1       Running             0          3h
default                            po/router-1-nmr6s             1/1       Running             0          3h
kube-service-catalog               po/apiserver-7mf8h            1/1       Running             0          4m
kube-service-catalog               po/controller-manager-zdqst   0/1       CrashLoopBackOff    4          3m
openshift-ansible-service-broker   po/asb-1-deploy               1/1       Running             0          2m
openshift-ansible-service-broker   po/asb-1-r0tv4                0/1       ContainerCreating   0          2m
openshift-ansible-service-broker   po/asb-etcd-1-789vq           0/1       Pending             0          2m
openshift-ansible-service-broker   po/asb-etcd-1-deploy          1/1       Running             0          2m

ansible/hosts

[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=origin
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIde
ntityProvider', 'filename': '/etc/origin/master/htpasswd'}]

[masters]
master01.openshift.local

[etcd]
etcd01.openshift.local

[nodes]
master01.openshift.local
node03.openshift.local openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
node02.openshift.local openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
node01.openshift.local openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
~

**Comment by MCSH** [comment]
I'm getting the exact same error and can't find a way around it

**Comment by openqt** [comment]
Same issue, as versions:

```
# oc version
oc v3.7.1+284b8b7-18
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://node150:8443
openshift v3.7.1+284b8b7-18
kubernetes v1.7.6+a08f5eeb62
```
