### ISSUE TITLE
How to upgrade installed nodes to latest version?

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/openshift-ansible#617]
I installed a cluster by following 'Advanced installation'  in documentation. Just wondering if a new version of OpenShift is released, how can I upgrade my existing installation to the latest version?

**Comment by nak3** [comment]
You don't need to use ansible installer for the upgrade (at this moment). Following documentations explain the procedure.

(Origin)
https://docs.openshift.org/latest/install_config/upgrades.html

(Enterprise)
https://docs.openshift.com/enterprise/3.0/install_config/upgrades.html

**Comment by xionglingfeng** [comment]
@nak3 I read the documents but in the server, no packages named openshift* installed :-(

**Comment by nak3** [comment]
@xionglingfeng

Sorry I am not so familiar with origin packages. But it looks like the packge names have been changed after 1.0.6.

(1.0.5) https://copr.fedoraproject.org/coprs/maxamillion/origin-next/build/116643/
(1.0.6) https://copr.fedoraproject.org/coprs/maxamillion/origin-next/build/111822/
(Scott's changelog in spec file) http://copr-dist-git.fedorainfracloud.org/cgit/maxamillion/origin-next/origin.git/tree/origin.spec?id=8fcf536d6e44e93b18b2c713795c80f5a4695059#n384

Could you please check `rpm -qa |grep origin`? And if you found origin-{master,node..} and they are v1.0.6, you have installed latest version. (So, you don't need to update at this time.)

**Comment by xionglingfeng** [comment]
@nak3 Ah,  yes, it turns out the package name has changed to `origin-*`. Thanks for your help ^_^
