### ISSUE TITLE
Fixup shared-resource-viewer role failing on upgrade 3.5 to 3.6

### ISSUE THREAD

**Issue by jkhelil** [openshift/openshift-ansible#6177]
#### Description

When upgrading from 3.5 to 3.6, we encounter the following issue
TASK [Fixup shared-resource-viewer role] ***************************************
fatal: [ose3-int-a-master-2.node.xxxxxx]: FAILED! => {"changed": false, "failed": true, "msg": {"cmd": "/bin/oc replace -f /tmp/shared_resource_viewer_role.yaml -n openshift", "results": {}, "returncode": 1, "stderr": "Error from server (Conflict): error when replacing \"/tmp/shared_resource_viewer_role.yaml\": Operation cannot be fulfilled on name.authorization.openshift.io \"shared-resource-viewer\": the object has been modified; please apply your changes to the latest version and try again\n", "stdout": ""}}

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
Launch upgrade playbook from 3.5 to 3.6 using openshift-ansible release-3.6

##### Expected Results
Upgrade working.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by jkhelil** [comment]
we have 3 masters and it is failing on master2. Should we just run this once ?,

**Comment by lcarva** [comment]
I'm also hitting this.

**Comment by cassiussa** [comment]
As are we.  Did either of you manage to get around it?
