### ISSUE TITLE
ansible playbook/byo with non-persistent storage

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/openshift-ansible#618]
I started 3 nodes in OpenStack manually and try to follow the 3-node installation in 'Advanced installation' of the document. The docker registry runs at master and use NFS as storage.

OpenShift can work after installation, then I need to take snapshot of each instances, otherwise, when the instances needs to be rebuild, I will lost the installation.

But which folder of each node (master, etcd, node) needs to be put to a persistent location at NFS/Cinder? I think there are nothing in master node even I run docker register there because I configured it to use NFS. For etcd node, it looks like only `/var/lib/etcd` needs to be put to a persistent volume. What about `node` node?

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
