### ISSUE TITLE
Multiple Network Setup for 3 host (1 master) Cluster

### ISSUE THREAD

**Issue by AdwaitLele** [openshift/openshift-ansible#6190]
#### Description

- I want to create a 3 host cluster - 1 of them will be the master and the other 2 will be the nodes (slaves).
- They are each connected to the internet on a 1GB network but are also connected to each other on a private 10GB network.
- I want the hosts to communicate via the 10GB network when sending data between each other but use the 1GB network to access the internet. Their DNS names are tied to their 1GB IP address.

Am I correct in assuming that if I include the 10GB network IPs for each of the hosts in the ansible inventory file under the "openshift_ip" variable that this should work?

For example something like this:
```
[nodes]
master.domain.com openshift_ip = <master 10GB IP address>
slave1.domain.com openshift_ip = <slave1 10GB IP address>
slave2.domain.com openshift_ip = <slave2 10GB IP address>
```
If not, is there another way to set up my cluster in the way I want to?

##### Version

```
$ ansible --version
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

**Comment by feizeikesi** [comment]
+1
