### ISSUE TITLE
os_firewall-iptables: allow specifying the chain to add the firewall rules to

### ISSUE THREAD

**Issue by ibotty** [openshift/openshift-ansible#621]
Some clusters might not allow unrestricted etcd (only when using ipsec, say), so it makes sense to specify the chain that the rules will be added to. `os_firewall_manage_iptables` already supports that. It just needs to be exposed.

When somebody tells me an option name to use, I will implement it myself. The question is though, what to do for firewalld, which does not really have the same concept (afaict).

**Comment by tbielawa** [comment]
Our firewall configuration has changed a lot in the last year.

This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.

**Comment by ibotty** [comment]
Yeah. It's still not possible to set the firewall rule. 

E.g. for cloud setups it makes sense to only allow communication in, say, an ipsec tunnel.
