### ISSUE TITLE
Installation failed at GlusterFS configuration

### ISSUE THREAD

**Issue by Asgoret** [openshift/openshift-ansible#6218]
#### Description

Provide a brief description of your issue here. For example:

Fails at configuring glusterfs cluster.

##### Version

```
[root@openshift-ansible env]# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]


[root@openshift-ansible openshift-ansible]# git describe
openshift-ansible-3.8.0-0.9.0
```

##### Steps To Reproduce
1. Run ansible install
2. See output log

##### Expected Results
Succesfull installation.

```
TASK [openshift_storage_glusterfs : Copy initial glusterblock provisioner resource file] 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 	
/opt/env/openshift-ansible/playbooks/byo/openshift-cluster/../../common/openshift-cluster/../openshift-glusterfs/v3.6/glusterblock-provisioner.yml
failed: [openshift-master.cluster.local] (item=glusterblock-provisioner.yml) => 
{"changed": false, "failed": true, "item": "glusterblock-provisioner.yml", "msg": "Could not find or access 'v3.6/glusterblock-provisioner.yml'\nSearched in:\n\t/opt/env/openshift-ansible/roles/openshift_storage_glusterfs/files/v3.6/glusterblock-provisioner.yml\n\t/opt/env/openshift-ansible/roles/openshift_storage_glusterfs/v3.6/glusterblock-provisioner.yml\n\t/opt/env/openshift-ansible/roles/openshift_storage_glusterfs/tasks/files/v3.6/glusterblock-provisioner.yml\n\t/opt/env/openshift-ansible/roles/openshift_storage_glusterfs/tasks/v3.6/glusterblock-provisioner.yml\n\t/opt/env/openshift-ansible/playbooks/byo/openshift-cluster/../../common/openshift-cluster/../openshift-glusterfs/files/v3.6/glusterblock-provisioner.yml\n\t/opt/env/openshift-ansible/playbooks/byo/openshift-cluster/../../common/openshift-cluster/../openshift-glusterfs/v3.6/glusterblock-provisioner.yml"}
```

##### Additional Information

```
[root@openshift-ansible openshift-ansible]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```

Inventory file:

```
[OSEv3:children]
masters
etcd
lb
nodes
glusterfs_registry
glusterfs

[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=origin
containerized=False
openshift_storage_glusterfs_wipe=True
openshift_hosted_registry_replicas=3
openshift_hosted_registry_storage_volume_size=20Gi
openshift_storage_glusterfs_heketi_admin_key=''
openshift_storage_glusterfs_is_native=False
openshift_storage_glusterfs_heketi_url=10.5.135.185
openshift_master_cluster_method=native
openshift_master_cluster_hostname=openshift-lb.cluster.local
openshift_master_cluster_public_hostname=openshift-lb.cluster.local
osm_use_cockpit=True
osm_cockpit_plugins=['cockpit-kubernetes']
openshift_master_ingress_ip_network_cidr=10.5.136.0/24

[masters]
openshift-master.cluster.local

[etcd]
openshift-master.cluster.local

[lb]
openshift-lb.cluster.local

[nodes]
openshift-master.cluster.local openshift_schedulable=False
openshift-node1.cluster.local openshift_schedulable=True openshift_node_labels="{'region': 'primary', 'zone': 'firstzone'}"
openshift-node2.cluster.local openshift_schedulable=True openshift_node_labels="{'region': 'primary', 'zone': 'secondzone'}"
openshift-gluster1.cluster.local openshift_schedulable=True openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
openshift-gluster2.cluster.local openshift_schedulable=True openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
openshift-gluster3.cluster.local openshift_schedulable=True openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

[glusterfs_registry]
openshift-gluster1.cluster.local glusterfs_ip='10.5.135.171' glusterfs_devices='["/dev/sdb"]'
openshift-gluster2.cluster.local glusterfs_ip='10.5.135.170' glusterfs_devices='["/dev/sdb"]'
openshift-gluster3.cluster.local glusterfs_ip='10.5.135.169' glusterfs_devices='["/dev/sdb"]'

[glusterfs]
openshift-gluster4.cluster.local glusterfs_ip='10.5.135.168' glusterfs_devices='["/dev/sdb"]'
openshift-gluster5.cluster.local glusterfs_ip='10.5.135.167' glusterfs_devices='["/dev/sdb"]'
openshift-gluster6.cluster.local glusterfs_ip='10.5.135.166' glusterfs_devices='["/dev/sdb"]'
```

EXTRA INFORMATION GOES HERE
If i add 
```
openshift_release=v3.6
```
error is the same.

**Comment by Asgoret** [comment]
Hi, @jarrpa ! Can you look at this issue please?

**Comment by Asgoret** [comment]
@jarrpa 
In version '3.6.173.0.78-1' work`s fine.
Download [https://github.com/openshift/openshift-ansible/archive/openshift-ansible-3.6.173.0.78-1.zip](link)

**Comment by jarrpa** [comment]
Your error message indicates you were trying to install 3.6. The playbook should work if you don't specify `openshift_release=v3.6`.

I'm not sure what the support policy is on these playbooks, e.g. if deploying 3.6 is something we support in 3.8. @sdodson?

**Comment by Asgoret** [comment]
@jarrpa First install i don't specify openshift version, then i try with specify version (3.6 and 3.7 *another error*).

**Comment by jarrpa** [comment]
@Asgoret ....oh wait. Are you using the latest openshift-ansible against the currently available RPMs on CentOS? That would be a 3.6 deployment, yes. Again, I'm not sure what the support policy on this is... but I don't see why we couldn't fix it anyway. :)

I probably won't get to this this week (it's a holiday for me), but the fix is pretty straightforward so I'll get that in.

**Comment by Asgoret** [comment]
@jarrpa so....i will re-run all install again, to install metrics for monitoring) i can use last master repo or i must use work version?

**Comment by jarrpa** [comment]
@Asgoret I believe either latest master or latest release-3.7 should get you what you need. If you're planning on using GlusterFS to provide storage for Metrics, you'll want to deploy OpenShift without Metrics, create a **gluster-block** StorageClass, then run the standalone Metrics installation playbook specifying to use that SC for storage.

**Comment by Asgoret** [comment]
@jarrpa  Well...at this point i don't need to save metrics history. Can you help with commands a little bit?
I will use my inventory old invetory, just add to _[OSEv3:vars]_
```
openshift_metrics_install_metrics=true
openshift_metrics_storage_kind=glusterfs
openshift_metrics_storage_access_modes=['ReadWriteOnce']
openshift_metrics_storage_glusterfs_directory=/exports
openshift_metrics_storage_glusterfs_options='*(rw,root_squash)'
openshift_metrics_storage_volume_name=metrics
openshift_metrics_storage_volume_size=10Gi
openshift_metrics_storage_labels={'storage': 'metrics'}
``` 

Create gluster block (i will find command in previous issues :)

And start process with command:
```
ansible-playbook  -i  /path_to_inventory/inventory /path_to_openshift-ansible/openshift-ansible/playbooks/openshift-metrics/config.yml
```

**Comment by jarrpa** [comment]
@Asgoret Those variables are based on the NFS configs, which does not apply here. You want at least the following:
```
openshift_metrics_cassandra_storage_type=pv
openshift_metrics_cassandra_pvc_storage_class_name=<GLUSTERBLOCK_SC>
```
Then run `ansible-playbook -i <INVENTORY> <OPENSHIFT_ANSIBLE_DIR>/byo/openshift-cluster/openshift-metrics.yml`. I assume you're already there, but look through [the docs](https://access.redhat.com/documentation/en-us/openshift_container_platform/3.7/html-single/installation_and_configuration/#install-config-cluster-metrics) for things ending like `pvc_size`, `replicas`, and `nodeselector`.

You don't need to specify an `install` variable since it defaults to true when you run this playbook. If you later want to remove Metrics you can re-run the same playbook with `-e openshift_metrics_install_metrics=False` to uninstall it. Note that the uninstallation does not remove any PVCs created.

**Comment by Asgoret** [comment]
Problem isn't in storage part.

**Comment by Asgoret** [comment]
@jarrpa  Hi, error isn't in storage part, but maybe you know something about it?
```
TASK [openshift_metrics : generate random password for the hawkular-metrics keystore] 
fatal: [openshift-master.cluster.local]: FAILED! => {"failed": true, "msg": "template error while templating string: no filter named 'oo_random_word'. String: {{ 15 | oo_random_word }}"}
```

Versions:
```
[root@openshift-master ~]# oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift-lb.cluster.local:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7

[root@openshift-ansible openshift-ansible]# git describe
openshift-ansible-3.8.0-0.13.0-82-g5a7b6be


[root@openshift-ansible openshift-ansible]# ansible --version
ansible 2.4.0.0
  config file = /opt/env/openshift-ansible/ansible.cfg
  configured module search path = [u'/opt/env/openshift-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```
Also i try install from release version.

**Comment by jarrpa** [comment]
Unfortunately not. :( Maybe raise another issue about it, it looks like some includes are missing.

**Comment by Asgoret** [comment]
@jarrpa 
Solved porblem. I install openshift cluster from release 3.6, so if you want add something in future (in my case it was metrics) you need to use same version. I clone master branch and install failed, but when clone branch 'release-3.6' install end with succes.
And there was some problem with docker image:
https://github.com/openshift/origin/issues/15851
