### ISSUE TITLE
ERROR : openshift_facts is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by fvillain** [openshift/openshift-ansible#623]
Hello,

I'm following the advanced install guide (1 master, 2 nodes) and when i try to run the install playbook i get the following message:

```
# ansible-playbook -i ansible-hosts --private-key mykey.pem -u centos ./openshift-ansible/playbooks/byo/config.yml
ERROR: openshift_facts is not a legal parameter in an Ansible task or handler
```

Version of ansible : `1.7.2`
`ansible-hosts` points to a valid ansible host file as defined in the advanced installation page (https://docs.openshift.org/latest/install_config/install/advanced_install.html)

Any one know where this is coming from ?

**Comment by sdodson** [comment]
@fvillain Can you try updating ansible we have a minimum version requirement of 1.8.0? I can't replicate this with the latest master code and ansible-1.9.2-1.el7.noarch from EPEL.

**Comment by fvillain** [comment]
Ok this was indeed an Ansible version problem.

The version requirement is not specified in the documentation though (here: https://docs.openshift.org/latest/install_config/install/advanced_install.html#installing-ansible ). Maybe can we add it ? I installed ansible on my computer which runs on Ubuntu 14.04 and the default ansible version is currently 1.7.2
