### ISSUE TITLE
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Running etcd as an embedded service is no longer supported.

### ISSUE THREAD

**Issue by patronluther** [openshift/openshift-ansible#6252]
--I am new to OpenShift and ansible. 

--In my attempt to install the Stand-alone Deployment of OpenShift Container Registry, specifically using all-in-one Stand-alone OpenShift Container Registry Inventory File, I receive a failure for which I cannot workaround yet. Note that I've followed both:
   https://docs.openshift.org/3.6/install_config/install/prerequisites.html
   https://docs.openshift.org/3.6/install_config/install/host_preparation.html
before I proceed and run the ansible playbook.

So, when I use:
ansible-playbook -i /etc/ansible/hosts playbooks/byo/config.yml 

--I get at some point:

TASK [Evaluate groups - Fail if no etcd hosts group is defined] ************************************************************************************************************************************
Saturday 25 November 2017  22:05:02 +0000 (0:00:00.013)       0:00:00.218 ***** 
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Running etcd as an embedded service is no longer supported. If this is a new install please define an 'etcd' group with ei
ther one or three hosts. These hosts may be the same hosts as your masters. If this is an upgrade you may set openshift_master_unsupported_embedded_etcd=true until a migration playbook becomes ava
ilable.\n"}

PLAY RECAP *****************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
registry.oc-master.com     : ok=1    changed=0    unreachable=0    failed=0   

===============

--I do know that is something wrong with the localhost, but I cannot locate where and how to correct it. I am definitely missing something.

--I have one master and one node, in CentOS Linux release 7.4.1708 (Core), one for each of them.

--The ansible --version is:
ansible 2.4.1.0
  config file = /home/test-master/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/test-master/openshift-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

--I cloned:
git clone https://github.com/openshift/openshift-ansible

--git describe
openshift-ansible-3.8.0-0.13.0-5-g1ef463e

--Here is the inventory file:

[OSEv3:children]
masters
nodes

[OSEv3:vars]

ansible_ssh_user=test-master

openshift_master_default_subdomain=apps.oc-master.com

ansible_become=true

openshift_deployment_type=openshift-enterprise
deployment_subtype=registry

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

openshift_use_dnsmasq=true

[masters]
registry.oc-master.com

[nodes]
registry.oc-node.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true

--I use static IPs on the master and node, hence each contain:
/etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.X.X oc-master.com
192.168.X.X oc-node.com

--I also use external DNS server on another linux box, using unbound that has in its /etc/unbound/forward.conf the following:

local-data: "oc-master.com.     IN  A   192.168.X.X"
local-data: "oc-node.com.    IN  A   192.168.X.X"

--I read about:
Microsoft/openshift-origin#30
but I even if I tried to find the 'masterInstanceCount' (if that's the problem here), it doesn't exist in my environment. Note that I run the VMs in vmware.

Thanks!

**Comment by patronluther** [comment]
I read about:
      https://github.com/Microsoft/openshift-origin/issues/30
but I even if I tried to find the 'masterInstanceCount' (if that's the problem here), it doesn't exist in my environment. Note that I run the VMs in vmware.

**Comment by davivcgarcia** [comment]
Looks like you forgot to declare the 'etcd' group in your inventory file. It should be like:

```
[OSEv3:children]
masters
nodes
etcd
```

Also, you need to define who will host etcd. For most part of the deployments, etcd is hosted on master nodes. So, you need to add this piece too:

```
[etcd]
registry.oc-master.com
```

Please take a look on this example of inventory file for single master deployment, which seems your case.

[https://docs.openshift.org/latest/install_config/install/advanced_install.html#single-master](https://docs.openshift.org/latest/install_config/install/advanced_install.html#single-master)

**Comment by patronluther** [comment]
It worked. Thank you very much Davi.

**Comment by ffly827** [comment]
Encountering the same problem here on CentOS 7, tho with a slightly different command (atomic-openshift-installer scaleup). Already modified the hosts file but still not working :(. Any pointers?
