### ISSUE TITLE
Openshift Origin 3.6 FAILED - RETRYING: Wait for master API to become available

### ISSUE THREAD

**Issue by cello86** [openshift/openshift-ansible#6258]
#### Description
During a fresh installation of Openshift Origin 3.6.0 we noticed some failed steps related to the master api availability check:

`FAILED - RETRYING: Wait for master API to become available before proceeding (120 retries left).`

##### Version
```
# ansible --version
ansible 2.4.1.0
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/openshift-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
# git describe
openshift-ansible-3.8.0-0.9.0-52-gd2853ae
```
##### Steps To Reproduce
1.  run the installation from ansible script
2. to fix the issue we restart the docker daemon where the routers are running

##### Expected Results
N/A

##### Observed Results
After the docker daemon restart the installation works correctly

**Comment by aizuddin85** [comment]
you are installing 3.6 and checking out the wrong branch.
```
git clone -b release-3.6 https://github.com/openshift/openshift-ansible
```

**Comment by cello86** [comment]
@aizuddin85 I confirm that with the branch 3.6 it works fine.

Thanks for the tips.

Marcello
