### ISSUE TITLE
installer isn't setting additional registries for CRI-O conf

### ISSUE THREAD

**Issue by runcom** [openshift/openshift-ansible#6270]
installer (master) isn't placing `openshift_docker_additional_registries=` in `/etc/crio/crio.conf` under `registries` key in the config. We need that for openshift-enterprise to install correctly. To reproduce just run the installer with 3.8, you'll see some component like openshift-registry fails to be pulled cause there's no registies (default) configured.

@giuseppe PTAL

**Comment by runcom** [comment]
would be awesome to add some testing around this to prevent any regression again (this used to work afaict)

**Comment by runcom** [comment]
insecure registries are empty as well but I haven't checked if those are broken as well

**Comment by giuseppe** [comment]
https://github.com/openshift/openshift-ansible/pull/6185 was just merged 3 hours ago.  Does it solve the issue reported?

**Comment by runcom** [comment]
I'll test it out, thanks!!
