### ISSUE TITLE
tox: ansible_syntax doesn't seem to behave inside of a container

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/openshift-ansible#6303]
I'm trying to run the `tox` tests in a container. I roughly do this:

 1. clone the repo, checkout correct refs for testing
 2. commit image
 3. run `/usr/bin/tox --notest`
 4. commit image
 5. run `./.tox/py27-ansible_syntax/bin/python setup.py ansible_syntax`

I can't use `tox` to run the tests since it can't be configured to _not_ refresh the `virtualenv` during the test and random UID in Origin Pods screws up `pip`. I see this from the test:

```
# ./.tox/py27-ansible_syntax/bin/python setup.py ansible_syntax
running ansible_syntax
Ansible Deprecation Checks
...PASSED
Ansible Playbook Entry Point Syntax Checks
Entry point playbook count: 68
------------------------------------------------------------
Syntax checking playbook: /data/src/github.com/openshift/openshift-ansible/playbooks/aws/openshift-cluster/build_ami.yml
error: No such file or directory
```

The file does exist, however:

```
# stat /data/src/github.com/openshift/openshift-ansible/playbooks/aws/openshift-cluster/build_ami.yml
  File: '/data/src/github.com/openshift/openshift-ansible/playbooks/aws/openshift-cluster/build_ami.yml'
  Size: 1319      	Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d	Inode: 167876085   Links: 1
Access: (0664/-rw-rw-r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-11-22 18:44:18.000000000 +0000
Modify: 2017-11-22 18:44:18.000000000 +0000
Change: 2017-11-28 19:36:06.943410439 +0000
 Birth: -
```

Unclear what is going on here.

/cc @sdodson @sosiouxme 
Would appreciate help with triage here.

**Comment by stevekuznetsov** [comment]
Mostly looking to debug this with someone who understands what this task is doing and generally how it does it.

**Comment by mtnbikenc** [comment]
The test requires `ansible-playbook` to be in the path, which may be causing the generic `no such file`.

**Comment by mtnbikenc** [comment]
Try running:
```
ansible-playbook -i localhost, --syntax-check /data/src/github.com/openshift/openshift-ansible/playbooks/aws/openshift-cluster/build_ami.yml
```

This is essentially what the test is doing, however with a different host group list and it runs it for every entry point playbook it finds.

**Comment by stevekuznetsov** [comment]
@mtnbikenc good call, missing `ansible-playbook`!

**Comment by stevekuznetsov** [comment]
-100 to that error message :(
