### ISSUE TITLE
Don't rely on /root/.kube/config for oc/oadm tasks in ansible

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#631]
It can't be trusted to be sane. We should use /etc/{{ openshift.common.service_type }}/master/admin.kubeconfig instead.

CC: @thoraxe

**Comment by detiber** [comment]
One caveat here I will recommend...  if for some reason the oc/oadm task is being called from a script that is going to switch the namespace or context, then we should probably copy the admin kubeconfig to a temporary location before running the commands and then removing the temporary copy.

**Comment by liggitt** [comment]
or just specify the namespace with `-n ...` rather than running commands that mutate the kubeconfig

**Comment by detiber** [comment]
@liggitt that is indeed an option, but doesn't prevent the user from doing something like oc login that would muck with ~/.kube/config

I'm still keen on copying the admin kubeconfig to a temporary location and using that to avoid mutating the admin kubeconfig as well as ensuring that we are in a known starting state for each set of operations.

We may also want to make sure that the current context are what we expect even when copying the admin kubeconfig..  though if we explicitly use -n we would only have to worry about the current context.

**Comment by tbielawa** [comment]
we use the admin.kubeconfig whenever possible now.

**Comment by sdodson** [comment]
not everywhere
