### ISSUE TITLE
Missing OpenShift RPMs v.3.7 during installation

### ISSUE THREAD

**Issue by isbalashov** [openshift/openshift-ansible#6322]
#### Description
Current version of openshift-ansible fails to download RPM origin-3.7, so the installation fails

Failure summary:
  1. Hosts:  
     Play:     Determine openshift_version to configure on first master
     Task:     For an RPM install, abort when the release requested does not match the available version.
     Message:  You requested openshift_release 3.7, which is not matched by
               the latest OpenShift RPM we detected as origin-3.6.1
               on host
               We will only install the latest RPMs, so please ensure you are getting the release
               you expect. You may need to adjust your Ansible inventory, modify the repositories
               available on the host, or run the appropriate OpenShift upgrade playbook.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
ansible 2.4.1.

##### Steps To Reproduce
1. git clone https://github.com/openshift/openshift-ansible.git
2. ansible-playbook -i inventory /playbook/byo/config.yml

OS version:
CentOS Linux release 7.4.1708 (Core)

**Comment by DanyC97** [comment]
@isbalashov is this issue still present? 

If so can you please provide the inventory file you used and the openshift-ansible release ?

**Comment by isbalashov** [comment]
Issue resolved.
