### ISSUE TITLE
openshift-logging fails to install properly

### ISSUE THREAD

**Issue by fraenkel** [openshift/openshift-ansible#6332]
I believe I have found at least 2 issues with how openshift logging is installed into my environment.
Deploying Origins 3.7 into a containerized 1 Etcd, 1 Master, 1 Infra and 1 Node.

1. Installing with openshift_install_logging_install: true
Usually one or more of the deploy pods end in an Error state.
The last phase of the install is to update the logging URL on the Master. The Master is then restarted.
Invariably, the master is restarted when the status is being updated which causes the deploy pod to fail and kill the starting pods.

2. Installing with ansible-playbook playbooks/byo/openshift-cluster/openshift-logging.yml
This path has the same problem as above, and additional issues.
The first step is to determine versions. This causes docker to be restarted. This causes a variety of issues.
If the restart occurs on the master, we may hit the above problem.
If the restart occurs on the node, any in flight deploy gets interrupted and can cause the volumes to get wedged. My situation had prometheus deploying and usually causes the emptydir volumes to always fail to mount.
I attempted to use the skip_docker_role but always ran into the situation above if I did.

I realize if I had 2 or more masters, this problem might go away, but I can't guarantee it.
My current solution is to the update of the logging URL first before deploying anything and then forcing the master to restart. This way I know the master will always be there. This doesn't prevent any ongoing deploy from failing.

**Comment by jkaurredhat** [comment]
Can you share the error messages that you see at first.

**Comment by fraenkel** [comment]
https://gist.github.com/fraenkel/21b8ce1b72097017a03ee6b5ee986a6b

**Comment by fraenkel** [comment]
Here is the aftermath on prometheus, this is most likely something that should be reported to origins.
https://gist.github.com/fraenkel/882898500b8308eff33c71685bb08839
