### ISSUE TITLE
openshift_management timeout should be configurable

### ISSUE THREAD

**Issue by elad661** [openshift/openshift-ansible#6333]
In `roles/openshift_management/tasks/main.yml`, there's a task "Wait for the app to come up".
It waits for a maximum of 10 minutes until ManageIQ / CFME is ready before it reports success.

This timeout is too low in some cases, because it's a big docker image and downloading it takes quite a while. It'd be best if this timeout would be configurable in the inventory file instead of being hardcoded.

**Comment by bazulay** [comment]
@sdodson  this issue was opened because when we enable manageiq deployment in the initial inventory file it is almost always fails on timeout (well on 20 retries = 10 min). this happens because of the size of the image.

**Comment by sdodson** [comment]
@elad661 That's fine with me, can you open a PR?
