### ISSUE TITLE
Exception: Tag openshift-ansible-3.8.1-1 already exists

### ISSUE THREAD

**Issue by mfojtik** [openshift/openshift-ansible#6342]
Seems like this error is breaking GCE install and other jobs:

```
+ tito tag --offline --accept-auto-changelog
Creating output directory: /tmp/tito
Tagging new version of openshift-ansible: 3.8.0-0.13.0 -> 3.8.1-1
Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 202, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 666, in main
    return tagger.run(self.options)
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 114, in run
    self._tag_release()
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 136, in _tag_release
    self._check_tag_does_not_exist(self._get_new_tag(new_version))
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 501, in _check_tag_does_not_exist
    raise Exception("Tag %s already exists!" % new_tag)
Exception: Tag openshift-ansible-3.8.1-1 already exists!
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
```

@stevekuznetsov @kargakis

**Comment by kargakis** [comment]
master is yet to be updated with the new tag for tito to work correctly but the tag exists globally and breaks tito.

https://github.com/openshift/openshift-ansible/blob/b62ec2d2e587e55efca930c7919dfe31d3d45edb/.tito/packages/openshift-ansible

**Comment by mfojtik** [comment]
@sdodson PTAL

**Comment by stevekuznetsov** [comment]
/assign @sdodson 
@deads2k did we not make sure to make the tag before cutting the new branch?

**Comment by stevekuznetsov** [comment]
`master` here needs 3.9.0 if `release-3.8` is on `3.8.x`

**Comment by sdodson** [comment]
This is fixed now but should be part of the branching process.

**Comment by jupierce** [comment]
Added bumping this version to our release cut SOP.

**Comment by stevekuznetsov** [comment]
I had talked with @deads2k about this when he asked what the process was for branching -- I think there may have been a poor communication on my end, this should not have been an issue this time around.

**Comment by kargakis** [comment]
Do we have any docs about this branching process?

**Comment by jupierce** [comment]
@kargakis - This is what it looks like for build focus group: https://github.com/openshift/aos-cd-jobs/blob/master/docs/sop/cut-new-release.md . Doc is a placeholder for automation.
