### ISSUE TITLE
Unable to setup custom extensionScripts for console

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#6343]
#### Description

I'm unable to define custom assets for the openshift web console.

My Inventory:

```
# Customs
openshift_master_extension_stylesheets: ['/etc/origin/custom/css/openshift.css']
openshift_master_extension_scripts: ['/etc/origin/custom/js/openshift.js']
```
results into this:

```
assetConfig:
  extensionScripts:
  - /etc/origin/master/openshift-ansible-catalog-console.js
  extensionStylesheets:
  - /etc/origin/custom/css/openshift.css
```

Looks like my value get overwritten here:
https://github.com/openshift/openshift-ansible/blob/012be35217f7415d50afe5e74b7e2e995feea6b5/playbooks/openshift-master/private/tasks/wire_aggregator.yml#L170

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
# ansible --version
ansible 2.4.2.0
# git describe
openshift-ansible-3.7.9-1-47-gafef12fc2
```

##### Steps To Reproduce
1. Setup an inventory with the value above.
2. Verifiy the configuration on /etc/origin/master-config.yaml

##### Expected Results
The custom javascript is loaded on the web console.

```
Example command and output or error messages
```

##### Observed Results
See description: the custom value get overwritten.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
CentOS 7.4
Openshift 3.7 with Service Catalog
```

**Comment by kincl** [comment]
I can confirm I am also seeing this bug.
