### ISSUE TITLE
"Create credentials for registry auth" task running before docker is installed

### ISSUE THREAD

**Issue by sjenning** [openshift/openshift-ansible#6347]
```
TASK [openshift_master : Create credentials for registry auth] *****************
18:52:50
Tuesday 05 December 2017  00:52:50 +0000 (0:00:00.170)       0:02:24.668 ****** 
FAILED - RETRYING: Create credentials for registry auth (3 retries left).
FAILED - RETRYING: Create credentials for registry auth (2 retries left).
FAILED - RETRYING: Create credentials for registry auth (1 retries left).
fatal: [master.lab.variantweb.net]: FAILED! => {"attempts": 3, "changed": false, "cmd": "docker --config=/var/lib/origin/.docker login -u '' -p *redacted* *redacted*", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```

This command is being run on the master before docker is installed.

Running on release-3.8.

**Comment by sdodson** [comment]
Ansible is pretty horrible about "No such file" errors. Can you tell if it's complaining about the absence of `docker` or `/var/lib/origin/.docker` or its parents?
/assign michaelgugino

**Comment by sdodson** [comment]
Nevermind, you'd already diagnosed it's because docker isn't installed.

**Comment by michaelgugino** [comment]
Currently, docker is required to be installed before running openshift-ansible

https://docs.openshift.org/latest/install_config/install/host_preparation.html#installing-docker

**Comment by sjenning** [comment]
This discussion about whether the installer is responsible for installing docker sounds very familiar.  I think we've had it before.  In the past, it did do the installation.  If the installer does not want to support this, I can just adapt my procedure.

**Comment by michaelgugino** [comment]
@sjenning The master branch will now install docker.  We are refactoring that role heavily currently.  3.7 and below need to have docker installed before running openshift-ansible.

**Comment by michaelgugino** [comment]
Fixed in master.  Docker or other container runtime is now installed via prerequisites.yml.
