### ISSUE TITLE
Openshift Origin 3.7 FAILED - RETRYING: wait for api server to be ready (120 retries left).

### ISSUE THREAD

**Issue by cello86** [openshift/openshift-ansible#6354]
#### Description
During the installation of Openshift Origin the playbook fails on this step:

`FAILED - RETRYING: wait for api server to be ready (120 retries left).
`
Provide a brief description of your issue here. For example:

The problem seems to be related with service catalog present on the newer Openshift Origin version.

**Comment by michaelgugino** [comment]
There is not enough information provided to attempt to reproduce the problem.

Please file a new issue and fill out the template provided therein.  Any extra details are helpful.
