### ISSUE TITLE
Fails to Verify API - 3.7

### ISSUE THREAD

**Issue by ghost** [openshift/openshift-ansible#6412]
#### Description

I too am having this problem with the ansible installer. I am installing to VirtualBox VMs on my laptop for a testing environment. No problem on other platforms.

Version: 3.7.0

Grabbed via git

fatal: [master.training.crossvale.io]: FAILED! => {"attempts": 120, "changed": false, "cmd": ["curl", "--silent", "--tlsv1.2", "--cacert", "/etc/origin/master/ca-bundle.crt", "https://master:8443/healthz/ready"], "delta": "0:00:00.012230", "end": "2017-12-08 14:59:08.354583", "failed": true, "msg": "non-zero return code", "rc": 7, "start": "2017-12-08 14:59:08.342353", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP **************************************************************************************************************
localhost                  : ok=12   changed=0    unreachable=0    failed=0
master.training.crossvale.io : ok=251  changed=28   unreachable=0    failed=1
node1.training.crossvale.io : ok=44   changed=2    unreachable=0    failed=0

INSTALLER STATUS ********************************************************************************************************
Initialization             : Complete (0:01:28)
Health Check               : Complete (0:00:00)
etcd Install               : Complete (0:00:27)
NFS Install                : Complete (0:00:07)
Master Install             : In Progress (0:04:00)
	This phase can be restarted by running: playbooks/openshift-master/config.yml

Failure summary:

  1. Hosts:    master.training.crossvale.io
     Play:     Configure masters
     Task:     Verify API Server
     Message:  non-zero return code

journalctl -xe:

-- The start-up result is done.
Dec 08 14:56:37 master.training.crossvale.io ansible-command[22214]: Invoked with warn=False executable=None _uses_shell=False _raw_params=curl --silent --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt
Dec 08 14:56:37 master.training.crossvale.io dockerd-current[2947]: E1208 20:56:37.426143       1 leaderelection.go:229] error retrieving resource lock kube-system/openshift-master-controllers: Get https:
Dec 08 14:56:37 master.training.crossvale.io origin-master-controllers[22079]: E1208 20:56:37.426143       1 leaderelection.go:229] error retrieving resource lock kube-system/openshift-master-controllers:
Dec 08 14:56:37 master.training.crossvale.io dockerd-current[2947]: 2017-12-08 20:56:37.753632 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error:
Dec 08 14:56:37 master.training.crossvale.io origin-master-api[21893]: 2017-12-08 20:56:37.753632 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection erro
Dec 08 14:56:38 master.training.crossvale.io ansible-command[22256]: Invoked with warn=False executable=None _uses_shell=False _raw_params=curl --silent --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt
Dec 08 14:56:39 master.training.crossvale.io ansible-command[22297]: Invoked with warn=False executable=None _uses_shell=False _raw_params=curl --silent --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt
Dec 08 14:56:40 master.training.crossvale.io ansible-command[22338]: Invoked with warn=False executable=None _uses_shell=False _raw_params=curl --silent --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt
Dec 08 14:56:42 master.training.crossvale.io ansible-command[22379]: Invoked with warn=False executable=None _uses_shell=False _raw_params=curl --silent --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt
Dec 08 14:56:43 master.training.crossvale.io origin-master-controllers[22079]: E1208 20:56:43.305662       1 leaderelection.go:229] error retrieving resource lock kube-system/openshift-master-controllers:
Dec 08 14:56:43 master.training.crossvale.io dockerd-current[2947]: E1208 20:56:43.305662       1 leaderelection.go:229] error retrieving resource lock kube-system/openshift-master-controllers: Get https:
Dec 08 14:56:43 master.training.crossvale.io ansible-command[22420]: Invoked with warn=False executable=None _uses_shell=False _raw_params=curl --silent --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt
Dec 08 14:56:44 master.training.crossvale.io origin-master-api[21893]: 2017-12-08 20:56:44.606922 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection erro
Dec 08 14:56:44 master.training.crossvale.io dockerd-current[2947]: 2017-12-08 20:56:44.606922 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error:
Dec 08 14:56:44 master.training.crossvale.io origin-master-api[21893]: 2017-12-08 20:56:44.641833 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection erro
Dec 08 14:56:44 master.training.crossvale.io dockerd-current[2947]: 2017-12-08 20:56:44.641833 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error:
Dec 08 14:56:44 master.training.crossvale.io ansible-command[22461]: Invoked with warn=False executable=None _uses_shell=False _raw_params=curl --silent --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt
Dec 08 14:56:45 master.training.crossvale.io ansible-command[22502]: Invoked with warn=False executable=None _uses_shell=False _raw_params=curl --silent --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt
Dec 08 14:56:47 master.training.crossvale.io ansible-command[22543]: Invoked with warn=False executable=None _uses_shell=False _raw_params=curl --silent --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt
Dec 08 14:56:48 master.training.crossvale.io ansible-command[22584]: Invoked with warn=False executable=None _uses_shell=False _raw_params=curl --silent --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt

**Comment by mtnbikenc** [comment]
Closing old issues.
/close
