### ISSUE TITLE
Metrics setup configures non-existing HOSA image

### ISSUE THREAD

**Issue by ctron** [openshift/openshift-ansible#6424]
#### Description

On an installation enabling the metrics system and deploying the hawkular openshift agent (HOSA) a non-existing HOSA image gets configured, resulting in ImagePullBack errors:

~~~
Dec 11 16:36:00 XXX origin-node[9955]: I1211 16:36:00.376632    9955 kuberuntime_manager.go:458] Container {Name:hawkular-openshift-agent Image:docker.io/openshift/origin-metrics-hawkular-openshift-agent:latest Command:[hawkular-openshift-agent -config /hawkular-openshift-agent-configuration/config.yaml -v 3] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:K8S_POD_NAMESPACE Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {Name:K8S_POD_NAME Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.name,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}}] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:hawkular-openshift-agent-configuration ReadOnly:false MountPath:/hawkular-openshift-agent-configuration SubPath:} {Name:hawkular-openshift-agent-token-5hzfd ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/health,Port:8080,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:30,TimeoutSeconds:1,PeriodSeconds:30,SuccessThreshold:1,FailureThreshold:3,} ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:&Capabilities{Add:[],Drop:[KILL MKNOD SETGID SETUID SYS_CHROOT],},Privileged:*false,SELinuxOptions:&SELinuxOptions{User:,Role:,Type:,Level:s0:c1,c0,},RunAsUser:*1000000000,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Dec 11 16:36:00 XXX origin-node[9955]: E1211 16:36:00.380549    9955 kuberuntime_manager.go:719] container start failed: ImagePullBackOff: Back-off pulling image "docker.io/openshift/origin-metrics-hawkular-openshift-agent:latest"
Dec 11 16:36:00 XXX origin-node[9955]: E1211 16:36:00.380651    9955 pod_workers.go:182] Error syncing pod 0565dc4d-de7a-11e7-bbf1-001a4a60009f ("hawkular-openshift-agent-9tskq_default(0565dc4d-de7a-11e7-bbf1-001a4a60009f)"), skipping: failed to "StartContainer" for "hawkular-openshift-agent" with ImagePullBackOff: "Back-off pulling image \"docker.io/openshift/origin-metrics-hawkular-openshift-agent:latest\""

~~~

Configured image: docker.io/openshift/origin-metrics-hawkular-openshift-agent:latest

~~~
➜  ~ docker pull docker.io/openshift/origin-metrics-hawkular-openshift-agent:latest
Trying to pull repository docker.io/openshift/origin-metrics-hawkular-openshift-agent ... 
Pulling repository docker.io/openshift/origin-metrics-hawkular-openshift-agent
Error: image openshift/origin-metrics-hawkular-openshift-agent:latest not found
~~~

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jreimann/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

➜  openshift-ansible git:(release-3.7) git describe
openshift-ansible-3.7.11-1

```

##### Steps To Reproduce
1. Install OpenShift
2. Check journalctl

##### Expected Results
Describe what you expected to happen.

The correct image to be deployed.

##### Observed Results
Describe what is actually happening.

The wrong image is being deployed.

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
Red Hat Enterprise Linux Workstation release 7.4 (Maipo)
```

<details>
[OSEv3:children]
masters
nodes
nfs
etcd

[OSEv3:vars]
deployment_type=origin
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

openshift_install_examples=false

openshift_enable_service_catalog=false

openshift_master_default_subdomain=XXX

# Registry

openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_nfs_directory=/exports
openshift_hosted_registry_storage_nfs_options='*(rw,root_squash)'
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=80Gi

# Metrics

openshift_metrics_install_metrics=true
openshift_metrics_start_cluster=true
openshift_metrics_install_hawkular_agent=true

openshift_metrics_storage_kind=nfs
openshift_metrics_storage_access_modes=['ReadWriteOnce']
openshift_metrics_storage_nfs_directory=/exports
openshift_metrics_storage_nfs_options='*(rw,root_squash)'
openshift_metrics_storage_volume_name=metrics
openshift_metrics_storage_volume_size=80Gi

[masters]
XXX

[etcd]
XXX

[nodes]
XXX openshift_scheduleable=true openshift_node_labels="{'region': 'infra'}"
N1 openshift_scheduleable=true openshift_node_labels="{'region': 'infra'}"

[nfs]
XXX
</details>

**Comment by ctron** [comment]
In addition to that the start command seems to be wrong as well:

The correct one would be:

~~~yaml
 command:
    - "/opt/hawkular/hawkular-openshift-agent"
~~~

Instead it is:

~~~yaml
command:
    - "hawkular-openshift-agent"
~~~

**Comment by ctron** [comment]
A working image might be:

~~~yaml
image: 'docker.io/hawkular/hawkular-openshift-agent:latest'
~~~

**Comment by kzila** [comment]
Hi, same issue here, Can insall hawkular-agent via openshift-ansible scripts because of this.
