### ISSUE TITLE
Install fails with Command not found error Urgent

### ISSUE THREAD

**Issue by helletheone** [openshift/openshift-ansible#6429]
#### Description
sorry but i create this problem here:
https://github.com/openshift/origin-aggregated-logging/issues/839
And i was asked to create this ticket here again:  soo :) 

Hey, i want to activat the logging on our cluster. But i get this error:

Openshift Origin version 3.6:
OS: Centos 7
Setup: Multi-Master Setup( 1 LB Native & 3 Masters & 3 Worker Nodes) :

TASK [openshift_logging : Run JKS generation script] ***********************************************************************************************************************************************************************
fatal: [master1.example.de -> localhost]: FAILED! => {"changed": true, "failed": true, "msg": "non-zero return code", "rc": 127, "stderr": "+ '[' 2 -lt 1 ']'\n+ dir=/tmp/openshift-logging-ansible-HYILj0\n+ SCRATCH_DIR=/tmp/openshift-logging-ansible-HYILj0\n+ PROJECT=logging\n+ [[ ! -f /tmp/openshift-logging-ansible-HYILj0/system.admin.jks ]]\n+ generate_JKS_client_cert system.admin\n+ NODE_NAME=system.admin\n+ ks_pass=kspass\n+ ts_pass=tspass\n+ dir=/tmp/openshift-logging-ansible-HYILj0\n+ echo Generating keystore and certificate for node system.admin\n+ keytool -genkey -alias system.admin -keystore /tmp/openshift-logging-ansible-HYILj0/system.admin.jks -keyalg RSA -keysize 2048 -validity 712 -keypass kspass -storepass kspass -dname 'CN=system.admin, OU=OpenShift, O=Logging'\n/root/.ansible/tmp/ansible-tmp-1513010720.0-52542015687757/generate-jks.sh: line 89: keytool: command not found\n", "stdout": "Generating keystore and certificate for node system.admin\n", "stdout_lines": ["Generating keystore and certificate for node system.admin"]}
to retry, use: --limit @/root/openshift-ansible/playbooks/byo/openshift-cluster/openshift-logging.retry

What can i do?

Yes we use the RPM-Install-version. But with rpm -qa|grep openshift
comes nothing

only with : openshift-cluster]# rpm -qa | grep origin
i got this:
origin-excluder-3.6.1-1.0.008f2d5.noarch
origin-master-3.6.1-1.0.008f2d5.x86_64
origin-sdn-ovs-3.6.1-1.0.008f2d5.x86_64
origin-docker-excluder-3.6.1-1.0.008f2d5.noarch
origin-3.6.1-1.0.008f2d5.x86_64
origin-clients-3.6.1-1.0.008f2d5.x86_64
origin-node-3.6.1-1.0.008f2d5.x86_64
tuned-profiles-origin-node-3.6.1-1.0.008f2d5.x86_64

The branch is: openshift-ansible-3.6.173.0.78-1-2-g9cd90eb

and no java is not installed

**Comment by sdodson** [comment]
keytool is provided by the jdk, can you try installing java-1.8.0-openjdk-headless on your control host?
/assign ewolinetz

**Comment by helletheone** [comment]
@sdodson big thx you save me day ;-) but i guess this was useful in the Documentation that java is needed ;)

**Comment by crmarques** [comment]
I had the same error. Solved by installing java-1.8.0-openjdk-headless on your control host too. Shouldn't this be in the doc?

**Comment by ewolinetz** [comment]
This is documented in the README of the openshift-logging role and the openshift-ansible repo:
https://github.com/openshift/openshift-ansible/#setup
