### ISSUE TITLE
'dict object' has no attribute 'version'

### ISSUE THREAD

**Issue by jitendra01mishra** [openshift/openshift-ansible#6430]
#### Description

while installing openshift origin i am facing below issues :  'dict object' has no attribute 'version'

Below is the command which i am running:

ansible-playbook -i ansible-inventory/inventory.erb ./openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade.yml -vvvv
 
please find my ansible inventory file : 

```
# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=root
ansible_become=yes
debug_level=2
deployment_type=origin

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

containerized=true
openshift_release=v3.9

openshift_master_cluster_method=native
openshift_public_hostname=master.example.com
openshift_master_default_subdomain=apps.master.example.com
openshift_metrics_install_metrics=false
openshift_hosted_metrics_deploy=false

# apply updated node defaults
openshift_node_kubelet_args={'pods-per-core': ['10'], 'max-pods': ['250'], 'image-gc-high-threshold': ['90'], 'image-gc-low-threshold': ['80']}

# default selectors for router and registry services
openshift_router_selector='region=infra'
openshift_registry_selector='region=infra'

# enable ntp on masters to ensure proper failover
openshift_clock_enabled=true

# host group for masters
[masters]
master.example.com

# host group for etcd
[etcd]
etcd.example.com

# host group for nodes, includes region info
[nodes]
master.example.com openshift_node_labels="{'region': 'primary', 'zone': 'east'}" openshift_schedulable=true
node.example.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}" openshift_schedulable=true
etcd.example.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true
```

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

 ansible --version
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

* The output of `git describe`

[root@master openshift-ansible]# git describe
openshift-ansible-3.9.0-0.2.0-4-gf894bcf

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
[root@master ~]# rpm -q atomic-openshift-utils openshift-ansible
package atomic-openshift-utils is not installed
package openshift-ansible is not installed
```

##### Steps To Reproduce
1. configure 3 VM master, node and etcd
2. install Centos 7 Minimum 
3. setup DNS
4. install the plugins  - 
		yum install -y epel-release docker ansible git wget
		yum install -y pyOpenSSL.x86_64 python-cryptography python-lxml
5. generate rsa key using ssh-keygen -t rsa and copy it over to master, node and etcd vm's using ssh-copy-id. validate ssh to master node and etcd.
6. run the below command to install the using inventory file 

ansible-playbook -i ansible-inventory/inventory.erb ./openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade.yml -vvvv

##### Expected Results
Describe what you expected to happen.

```
OpenShift installation should be successful 
```

##### Observed Results
Describe what is actually happening.

ansible-playbook -i ansible-inventory/inventory.erb ./openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade.yml -vvvv

TASK [set currently installed version] *********************************************************************************************************************************
task path: /root/openshift-ansible/playbooks/common/openshift-cluster/upgrades/init.yml:15
fatal: [etcd.example.com]: FAILED! => {
    "failed": true,
    "msg": "The task includes an option with an undefined variable. The error was: {{ hostvars[groups.oo_first_master.0].openshift.common.version }}: 'dict object' has no attribute 'version'\n\nThe error appears to have been in '/root/openshift-ansible/playbooks/common/openshift-cluster/upgrades/init.yml': line 15, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - name: set currently installed version\n    ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: {{ hostvars[groups.oo_first_master.0].openshift.common.version }}: 'dict object' has no attribute 'version'"
}
fatal: [master.example.com]: FAILED! => {
    "failed": true,
    "msg": "The task includes an option with an undefined variable. The error was: {{ hostvars[groups.oo_first_master.0].openshift.common.version }}: 'dict object' has no attribute 'version'\n\nThe error appears to have been in '/root/openshift-ansible/playbooks/common/openshift-cluster/upgrades/init.yml': line 15, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - name: set currently installed version\n    ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: {{ hostvars[groups.oo_first_master.0].openshift.common.version }}: 'dict object' has no attribute 'version'"
}
fatal: [node.example.com]: FAILED! => {
    "failed": true,
    "msg": "The task includes an option with an undefined variable. The error was: {{ hostvars[groups.oo_first_master.0].openshift.common.version }}: 'dict object' has no attribute 'version'\n\nThe error appears to have been in '/root/openshift-ansible/playbooks/common/openshift-cluster/upgrades/init.yml': line 15, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - name: set currently installed version\n    ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: {{ hostvars[groups.oo_first_master.0].openshift.common.version }}: 'dict object' has no attribute 'version'"
}
        to retry, use: --limit @/root/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade.retry

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by jitendra01mishra** [comment]
Hi Team, Please help on this .. its bit urgent

**Comment by tech-mint** [comment]
What have you done that year to solve the issue?
