### ISSUE TITLE
glusterfs containers can't start on 3.7 with docker 1.13+ 

### ISSUE THREAD

**Issue by dustymabe** [openshift/openshift-ansible#6431]
In Fedora we currently have `docker-1.13.1-42.git4402c09.fc27.x86_64`. There was a change in kube 1.7 to use shared PID namespaces in a pod if docker > 1.13+. It causes issues with our gluster pods (systemd in a container):

```
Couldn't find an alternative telinit implementation to spawn.
```

This specific issue with gluster is documented [upstream](https://github.com/kubernetes/kubernetes/issues/48937) and they actually [reverted the change](https://github.com/kubernetes/kubernetes/pull/51634) (so back to default to no shared PID namespace) in kube 1.8. Kube 1.7 still has the behavior but there is a `--docker-disable-shared-pid` flag that we can give to the kubelet to change the behavior to what we desire (and what is the default in 1.6 & 1.8) and get glusterfs working again.

so... Two options for a fix:

- adding the `--docker-disable-shared-pid` flag to the kubelet using openshift ansible when origin 3.7 && docker 1.13
- backporting the patch from kube 1.8 into origin 1.7 that reverts the change.

Note: If we go the `--docker-disable-shared-pid` they'll probably remove that flag in the future when it is no longer needed so we might have to add logic to "remove" the flag on an upgrade one day. Upstream issue to track that [here](https://github.com/kubernetes/kubernetes/issues/41938).

**Comment by sdodson** [comment]
@dustymabe I assume you have no reasonable way to downgrade to docker-1.12 on this as it's atomic host?
@sjenning assuming ^^ is "no" what should we tell folks who are in the situation where docker-1.13 is the only version of docker available?

**Comment by dustymabe** [comment]
> @dustymabe I assume you have no reasonable way to downgrade to docker-1.12 on this as it's atomic host?

We've had docker 1.13 in Fedora for some time now and going backwards is not desirable. 

> @sjenning assuming ^^ is "no" what should we tell folks who are in the situation where docker-1.13 is the only version of docker available?

hi @sjenning :)

**Comment by sdodson** [comment]
Even if it weren't atomic host Docker 1.12 was never available for Fedora 27.

**Comment by sjenning** [comment]
PR opened to backport the revert from upstream https://github.com/openshift/origin/pull/17722
