### ISSUE TITLE
How to replace corrupted master node with new one ?

### ISSUE THREAD

**Issue by davistran86** [openshift/openshift-ansible#6457]
Hi guys, I would like to know how to replace a master node in existing openshift cluster ? for example if one master down, and I would like to add new one to replace it, so how can I do this using openshift ansible ? thanks alot.

**Comment by michaelgugino** [comment]
@davistran86 You should remove the down node from your inventory.

Next, you can use the steps to add a node to the new_master group here: https://docs.openshift.org/3.6/install_config/adding_hosts_to_existing_cluster.html

Steps may vary depending on your version of openshift, ensure you use the docs for your version.

**Comment by davistran86** [comment]
hi @michaelgugino , thanks for your reply, I'm using version 3.7 but when I removed 1 master from inventory ( etcd, master, node groups) I got error that cannot use embedded etcd, need one or three host in etcd group. So 2 are not possible, is setting openshift_master_unsupported_embedded_etcd=true ok for future use ?


```
TASK [Evaluate groups - Fail if no etcd hosts group is defined] *******************************************************************************************************************************************************************************************************************************
Thursday 14 December 2017  09:43:17 +0700 (0:00:00.034)       0:00:00.427 *****
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Running etcd as an embedded service is no longer supported. If this is a new install please define an 'etcd' group with either one or three hosts. These hosts may be the same hosts as your masters. If this is an upgrade you may set openshift_master_unsupported_embedded_etcd=true until a migration playbook becomes available.\n"}

```

**Comment by michaelgugino** [comment]
@davistran86 try putting the new host in both master/new_master and etcd_newetcd.

You don't want to use the embedded option.

**Comment by davistran86** [comment]
@michaelgugino thanks, I succeed replacing new master as you suggested using playbook scaleup.yaml from openshift-master. But I'm facing a new problem that only new master is ready, the rest are NotReady, checking log I saw that it's something due to certificate problems, . Is there any playbooks I must run after replacing master ?

`http: TLS handshake error from 192.168.70.111:42906: remote error: tls: bad certificate`
```
-- Unit origin-node.service has begun starting up.
Dec 18 15:47:02 origin-router1 dnsmasq[19406]: setting upstream servers from DBus
Dec 18 15:47:02 origin-router1 dnsmasq[19406]: using nameserver 192.168.70.202#53
Dec 18 15:47:02 origin-router1 dnsmasq[19406]: using nameserver 192.168.70.201#53
Dec 18 15:47:02 origin-router1 dnsmasq[19406]: using nameserver 127.0.0.1#53 for domain in-addr.arpa
Dec 18 15:47:02 origin-router1 dnsmasq[19406]: using nameserver 127.0.0.1#53 for domain cluster.local
Dec 18 15:47:02 origin-router1 origin-node[65232]: I1218 15:47:02.489760   65232 start_node.go:251] Reading node configuration from /etc/origin/node/node-config.yaml
Dec 18 15:47:02 origin-router1 origin-node[65232]: F1218 15:47:02.513723   65232 start_node.go:140] cannot fetch "default" cluster network: Get https://openshift.aavn.local:8443/oapi/v1/clusternetworks/default: x509: certificate signed by unknown authority
Dec 18 15:47:02 origin-router1 systemd[1]: origin-node.service: main process exited, code=exited, status=255/n/a
Dec 18 15:47:02 origin-router1 dnsmasq[19406]: setting upstream servers from DBus
Dec 18 15:47:02 origin-router1 dnsmasq[19406]: using nameserver 192.168.70.202#53
Dec 18 15:47:02 origin-router1 systemd[1]: Failed to start OpenShift Node.
-- Subject: Unit origin-node.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit origin-node.service has failed.
--
-- The result is failed.
Dec 18 15:47:02 origin-router1 dnsmasq[19406]: using nameserver 192.168.70.201#53
Dec 18 15:47:02 origin-router1 systemd[1]: Unit origin-node.service entered failed state.
Dec 18 15:47:02 origin-router1 systemd[1]: origin-node.service failed.
Dec 18 15:47:05 origin-router1 dockerd-current[18947]: E1218 08:47:05.003669       1 reflector.go:190] github.com/openshift/origin/pkg/router/controller/factory/factory.go:88: Failed to list *route.Route: Get https://172.30.0.1:443/apis/route.openshift.io/v1/routes: dial tcp 172.30.0.1:
Dec 18 15:47:05 origin-router1 dockerd-current[18947]: E1218 08:47:05.003768       1 reflector.go:190] github.com/openshift/origin/pkg/router/controller/factory/factory.go:95: Failed to list *api.Endpoints: Get https://172.30.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 172.30.0
Dec 18 15:47:05 origin-router1 dockerd-current[18947]: E1218 08:47:05.003847       1 reflector.go:190] git
```

**Comment by davistran86** [comment]
I solved above problems with running redeploy-openshift-ca and redeploy-certificates playbook. But now I'm getting error with running app inside:

```
error: Unable to update build status: the server has asked for the client to provide credentials (get builds python-1)
--
  | error: build error: Failed to push image: unauthorized: authentication required


```

**Comment by DanyC97** [comment]
@michaelgugino shouldn't `redeploy-openshift-ca` & `redeploy-certificates` or am i missing s'thing here?

**Comment by michaelgugino** [comment]
Perhaps just doing the new_master first (not adding the host to etcd or new_etcd), then after scaling masters complete, add that host to the new_etcd group and run scale etcd play.

**Comment by bryantson** [comment]
Following this issue as well. Any definite solution on this?

**Comment by sumanyam** [comment]
Below procedure worked for me.
1. copy /etc/origin/master/ca.serial.txt to all master nodes. It will be only on 1 master initially.
2. Update inventory with new master details in new_masters and new_nodes groups.

[new_masters]
<new_master_name>

[new_nodes]
<new_master_name>

3. Run master-scaleup.

4. Update inventory with new master details in new_etcd and move the information out of new_nodes and new_masters. Update the details in masters and nodes groups.

[new_masters]


[new_nodes]

[masters]
<new_master_name>

[nodes]
<new_master_name>

[new_etcd]
<new_master_name>
5. Run etcd scale up.
6. update inventory and move the new master details from new_etcd group to etcd group.
