### ISSUE TITLE
Journald logs are persistent now. No way to override default values

### ISSUE THREAD

**Issue by jtudelag** [openshift/openshift-ansible#6465]
#### Description
Since 3.7 version, journal logs are persistent by default. But there is no easy way to override its conf variables, because they are defined in the /vars/main.yaml of the role. There might be scenarios where these default values dont fit.

- https://github.com/openshift/openshift-ansible/blob/release-3.7/roles/openshift_master/vars/main.yml#L29

- https://github.com/openshift/openshift-ansible/blob/release-3.7/roles/openshift_master/tasks/journald.yml 

Here it is the Ansible variable precedence doc:

- http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

##### Version

OpenShift v3.7

##### Steps To Reproduce
Install OpenShift 3.7

##### Observed Results

Folder /var/log/journald is created, and these variables are set, with these default values:

- { var: Storage, val: persistent }
- { var: Compress, val: yes }
- { var: SyncIntervalSec, val: 1s }
- { var: RateLimitInterval, val: 1s }
- { var: RateLimitBurst, val: 10000 }
- { var: SystemMaxUse, val: 8G }
- { var: SystemKeepFree, val: 20% }
- { var: SystemMaxFileSize, val: 10M }
- { var: MaxRetentionSec, val: 1month }
- { var: MaxFileSec, val: 1day }
- { var: ForwardToSyslog, val: no }
- { var: ForwardToWall, val: no }

##### Additional Information
Some actions need to be taken:

1. Add a note to openshift-docs stating that jorunald is persistent now by default.
2. Make jorunald parameters easily overridable.
    2.a Moving the variable to defaults/main.yaml would be enough.

**Comment by hamelg** [comment]
+1
SystemMaxUse, val: 8G , why ?
Hard-coded values like that may have negative effect.

**Comment by pgr-mattgartman** [comment]
This is pretty impactful for us as we need to maintain different journald configurations on our servers.  Any chance of this getting addressed?

**Comment by vrutkovs** [comment]
You can replace journald settings using `journald_vars_to_replace`, i.e.
```
journald_vars_to_replace:
- { var: Storage, val: volatile }
- { var: Compress, val: no }
...
```

**Comment by thekad** [comment]
To be more clear: these journald settings are now defined in `roles/openshift_node/defaults/main.yml`, and they can be easily overwritten in playbooks using the `journald_vars_to_replace` variable. Would that be enough to close this issue?

**Comment by vrutkovs** [comment]
Right, lets close it
