### ISSUE TITLE
local variable 'version' referenced before assignment

### ISSUE THREAD

**Issue by thenoid** [openshift/openshift-ansible#647]
Did something get merged recently that would result in the following error?  Steps to reporduce, install ansible, 

    printf " >>>> Cloning ansible from github"
    cd ${DIR}
    git clone https://github.com/openshift/openshift-ansible
    printf " >>>> Running ansible\n"
    ansible-playbook ${DIR}/openshift-ansible/playbooks/byo/config.yml

result

    TASK: [openshift_facts | Gather Cluster facts] ********************************
    failed: [openshift-master.example.icanttellyousorry.com] => {"failed": true, "parsed": false}
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1443751668.56-176431051020792/openshift_facts", line 6013, in <module>
        main()
      File "/root/.ansible/tmp/ansible-tmp-1443751668.56-176431051020792/openshift_facts", line 971, in main
        openshift_facts = OpenShiftFacts(role, fact_file, local_facts)
      File "/root/.ansible/tmp/ansible-tmp-1443751668.56-176431051020792/openshift_facts", line 760, in __init__
        self.facts = self.generate_facts(local_facts)
      File "/root/.ansible/tmp/ansible-tmp-1443751668.56-176431051020792/openshift_facts", line 786, in generate_facts
        facts = set_deployment_facts_if_unset(facts)
      File "/root/.ansible/tmp/ansible-tmp-1443751668.56-176431051020792/openshift_facts", line 477, in set_deployment_facts_if_unset
        facts['common']['version'] = get_openshift_version()
      File "/root/.ansible/tmp/ansible-tmp-1443751668.56-176431051020792/openshift_facts", line 614, in get_openshift_version
        return version
    UnboundLocalError: local variable 'version' referenced before assignment
    OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
    debug1: Reading configuration data /etc/ssh/ssh_config
    debug1: /etc/ssh/ssh_config line 56: Applying options for *
    debug1: auto-mux: Trying existing master
    debug1: mux_client_request_session: master session id: 2
    Shared connection to openshift-master.example.icanttellyousorry.com closed.

    FATAL: all hosts have already failed -- aborting

**Comment by thenoid** [comment]
Dug through the merges and found https://github.com/openshift/openshift-ansible/pull/646/files

Reverting this change fixed the issue, my ansible-fu is weak, @smunilla @wshearn tagging ya'll since you submitted/merged

**Comment by thenoid** [comment]
Looks like the issue is that get_openshift_version returns 'version', but if openshift isn't installed the if conditional doesn't fire and so 'version' is never defined.

adding - version = 'none' before the if statement solves this bug.

    diff --git a/roles/openshift_facts/library/openshift_facts.py b/roles/openshift_facts/library/openshift_facts.py
    index aeab715..d75b9b1 100755
    --- a/roles/openshift_facts/library/openshift_facts.py
    +++ b/roles/openshift_facts/library/openshift_facts.py
    @@ -605,6 +605,7 @@ def get_openshift_version():
             Returns:
                 version: the current openshift version
         """
    +    version = 'none'
         if os.path.isfile('/usr/bin/openshift'):
             _, output, _ = module.run_command(['/usr/bin/openshift', 'version'])
             versions = dict(e.split(' v') for e in output.splitlines())

**Comment by smunilla** [comment]
@thenoid My fault. I just submitted PR #650 to fix this.

**Comment by thenoid** [comment]
awesome, thanks!
