### ISSUE TITLE
Missing config.yml from /openshift-ansible/playbooks/byo/

### ISSUE THREAD

**Issue by rharveyva** [openshift/openshift-ansible#6503]
The openshift install guid states to run 
# ansible-playbook [-i /path/to/inventory] \
    ~/openshift-ansible/playbooks/byo/config.yml
based on
https://docs.openshift.org/latest/install_config/install/advanced_install.html#running-the-advanced-installation-rpm

The config.yml does not exist anymore.

output from ls -l
[server/]$ ls -l /openshift-ansible/playbooks/byo/
total 12
lrwxrwxrwx. 1 root root  20 Dec 13 01:14 filter_plugins -> ../../filter_plugins
lrwxrwxrwx. 1 root root  20 Dec 13 01:14 lookup_plugins -> ../../lookup_plugins
drwxr-xr-x. 3 root root  79 Dec 13 01:14 openshift-cluster
-rwxr-xr-x. 1 root root 204 Dec 13 01:14 openshift_facts.yml
-rwxr-xr-x. 1 root root 583 Dec 13 01:14 README.md
-rwxr-xr-x. 1 root root 442 Dec 13 01:14 rhel_subscribe.yml
lrwxrwxrwx. 1 root root  11 Dec 13 01:14 roles -> ../../roles

Reproduce:
run git clone https://github.com/openshift/openshift-ansible
```

**Comment by GloriaPG** [comment]
Hi @rharveyva  the new way to do this is  using deploy_cluster https://github.com/openshift/openshift-ansible/tree/master/playbooks , https://github.com/openshift/openshift-ansible/blob/master/playbooks/deploy_cluster.yml 

Example : 
 ansible-playbook -i /tmp/openshift-ansible-master/inventory/x /tmp/openshift-ansible-master/playbooks/deploy_cluster.yml

Cheers!

**Comment by kalise** [comment]
good to know but why not update the docs?
