### ISSUE TITLE
Ansible-service-broker: no route to host

### ISSUE THREAD

**Issue by varac** [openshift/openshift-ansible#6506]
#### Description

On a single-node installation (master+node on the same host), the ansible deploy succeeds but I get an event warning that the ansible-service-broker is unreachable:

```
Get https://asb.openshift-ansible-service-broker.svc:1338/ansible-service-broker/v2/catalog: dial tcp 172.30.104.193:1338: getsockopt: no route to host
```

##### Version

```
- ansible 2.4.2.0
- openshift-ansible, tag 3.7.15-1 cloned as subrepo with: 

    git subrepo clone --force --branch=openshift-ansible-3.7.15-1 https://github.com/openshift/openshift-ansible.git roles/openshift-ansible

(I tried the release-3.7 branch as well, same error)

- Openshift release 3.7.0
```

##### Steps To Reproduce

1. Install atomic host 7.1711 as a libvirt VM in bridged networking mode
2. Allow direct ssh access to root
3. Increase root filesystem to 50GB 
3. Clone openshift-ansible, checkout openshift-ansible-3.7.15-1 tag
4. Use following inventory file:

```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=origin
openshift_master_default_subdomain=apps.openshift.our.domain.org
openshift_master_cluster_public_hostname=openshift.our.domain.org
openshift_release="3.7.0"

# host group for masters
[masters]
openshiftmaster.our.domain.org

# host group for etcd
[etcd]
openshiftmaster.our.domain.org

# host group for nodes, including region info
[nodes]
openshiftmaster.our.domain.org openshift_public_hostname=openshiftmaster.autonomia.digital openshift_node_labels="{'region': 'infra','zone': 'west'}" openshift_schedulable=true
```

5. Deploy with:

    ansible-playbook -i development ./roles/openshift-ansible/playbooks/byo/config.yml

##### Expected Results

There should be no event warnings after an successfule ansible deploy, and the deployed ansible-service-broker should be reachable.

##### Observed Results

Ansible deploy succeeds, openshift works fine but the ansible-service-broker seems unreachable.

##### Additional Information

* operating system and version: 
  *  atomic host from CentOS-Atomic-Host-7.1711-GenericCloud.qcow2 image
  * CentOS Linux release 7.4.1708 (Core)

```
--- ~ » oc get events | grep ansible-service-broker
3m         1d          4905      ansible-service-broker        ClusterServiceBroker                                  Warning   ErrorFetchingCatalog    service-catalog-controller-manager     Error getting broker catalog: Get https://asb.openshift-ansible-service-broker.svc:1338/ansible-service-broker/v2/catalog: dial tcp 172.30.104.193:1338: getsockopt: no route to host

--- ~ » oc describe clusterservicebroker ansible-service-broker
Name:		ansible-service-broker
Namespace:	
Labels:		<none>
Annotations:	<none>
API Version:	servicecatalog.k8s.io/v1beta1
Kind:		ClusterServiceBroker
Metadata:
  Creation Timestamp:	2017-12-16T20:44:23Z
  Generation:		1
  Resource Version:	166774
  Self Link:		/apis/servicecatalog.k8s.io/v1beta1/clusterservicebrokers/ansible-service-broker
  UID:			e5f772e9-e2a1-11e7-b6ec-0a580a800007
Spec:
  Auth Info:
    Bearer:
      Secret Ref:
        Name:		asb-client
        Namespace:	openshift-ansible-service-broker
  Ca Bundle:		LS0tLS.......
  Relist Behavior:	Duration
  Relist Duration:	15m0s
  Relist Requests:	0
  URL:			https://asb.openshift-ansible-service-broker.svc:1338/ansible-service-broker
Status:
  Conditions:
    Last Transition Time:	2017-12-16T20:44:26Z
    Message:			Error fetching catalog. Error getting broker catalog: Get https://asb.openshift-ansible-service-broker.svc:1338/ansible-service-broker/v2/catalog: dial tcp 172.30.104.193:1338: getsockopt: no route to host
    Reason:			ErrorFetchingCatalog
    Status:			False
    Type:			Ready
  Operation Start Time:		2017-12-16T20:44:29Z
  Reconciled Generation:	0
Events:
  FirstSeen	LastSeen	Count	From					SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----					-------------	--------	------			-------
  1d		4m		4905	service-catalog-controller-manager			Warning		ErrorFetchingCatalog	Error getting broker catalog: Get https://asb.openshift-ansible-service-broker.svc:1338/ansible-service-broker/v2/catalog: dial tcp 172.30.104.193:1338: getsockopt: no route to host

```

**Comment by fabianvf** [comment]
Is the broker up? If there is no PV for the broker's etcd to consume the broker will not be able to start.

**Comment by varac** [comment]
@fabianvf What do you mean with `PV` ?

**Comment by fabianvf** [comment]
Sorry, persistent volume. Because the broker stores important information about the cluster state, it requires a persistent volume to be configured in order to come up. There are some more details in the [Install Guide](https://docs.openshift.com/container-platform/latest/install_config/install/advanced_install.html#configuring-openshift-ansible-broker) for the broker about how to ensure the broker is able to come up after install. The broker resources are all located in the `openshift-ansible-service-broker` namespace, if you want to double check that that is the source of the problem.

**Comment by varac** [comment]
I just did a complete redeploy from scratch, and I could reproduce the problem:

```
Listing matched pods on node: openshift.xxx

NAME                       READY     STATUS              RESTARTS   AGE                     
docker-registry-1-kh947    1/1       Running             0          6m                      
registry-console-1-tzgwv   1/1       Running             0          5m                      
router-1-bzjpx             1/1       Running             0          7m                      
apiserver-v47fv            1/1       Running             0          4m                      
controller-manager-ms6t5   1/1       Running             0          4m                      
asb-1-deploy               1/1       Running             0          3m                      
asb-1-pkls8                0/1       ErrImagePull        0          3m                      
asb-etcd-1-deploy          1/1       Running             0          3m                      
asb-etcd-1-pqh7s           0/1       ContainerCreating   0          3m                      
apiserver-nwflv            1/1       Running             0          3m   

--- ~ » oc get events --sort-by=lastTimestamp | grep -v ' Normal '
LASTSEEN   FIRSTSEEN   COUNT     NAME                          KIND                    SUBOBJECT                           TYPE      REASON                    SOURCE                                       MESSAGE
13s        4m          25        ansible-service-broker        ClusterServiceBroker                                        Warning   ErrorFetchingCatalog      service-catalog-controller-manager           Error getting broker catalog: Get https://asb.openshift-ansible-service-broker.svc:1338/ansible-service-broker/v2/catalog: dial tcp 172.30.117.31:1338: getsockopt: no route to host
```

Indeed I didn't configure a PV. Will do this soon and report back if the problem is solved by this.

**Comment by fabianvf** [comment]
It looks like you'll also see #6435 , to avoid that you'll want to set `ansible_service_broker_image_prefix` to `ansibleplaybookbundle/origin-`

**Comment by varac** [comment]
@fabianvf thx, I'll try that later.

I configured a PV following ["Configuring the OpenShift Ansible Broker" docs](https://docs.openshift.com/container-platform/latest/install_config/install/advanced_install.html#configuring-openshift-ansible-broker)
``` using the default variables.

I needed to install nfs-utils maually on atomic host with

```
  rpm-ostree install nfs-utils
  systemctl reboot
```
but still ansible fails with:

```
TASK [openshift_storage_nfs : Install nfs-utils] *******************************************
FAILED - RETRYING: Install nfs-utils (2 retries left).                                      
FAILED - RETRYING: Install nfs-utils (1 retries left).                                      
fatal: [openshift.xxx]: FAILED! => {"attempts": 2, "changed": false, "msg": "Could not find a module for unknown."}
```

**Comment by fabianvf** [comment]
Hmm, I've never tried setting up the NFS roles on atomic host. @sdodson do we know a good way to do this?

**Comment by varac** [comment]
I'm fine with picking a different backend as long as it's working mostly out of the box. I picked NFS because it was the documented default. Could you recommend sth else ? I'm learning openshift now and there's tons of new stuff for me so sth easy as PV backend would be appreciated.

**Comment by sdodson** [comment]
I'm afraid that using an atomic host for the nfs storage service may not work. Can you try using a normal RHEL/Centos/Fedora host as your NFS storage host?

**Comment by varac** [comment]
@sdodson That's too bad. Unfortunatly, I don't like to switch the host system for two reasons: I spent a lot of time understanding both atomic host and openshift, and am still a bit overwhelmed by this combination. That's why I don't want to introduce a third factor that I need to take care of. And the second reason is I really like the idea of a stripped down,immutable host.

Why don't nfs backend for PVs work on atomic host ? What about other backend options that I can host myself on that single host installation ?

**Comment by bevinhex** [comment]
Same here, I added PV, so far have
```
pv0002    1Gi        RWO,RWX       Recycle         Bound       openshift-ansible-service-broker/etcd                            19m
```
but still both openshift-ansible-service-broker have "Error" state

**Comment by fabianvf** [comment]
you may need to retry the deployment of asb and asb-etcd if they've been in an error state for too long.

**Comment by bevinhex** [comment]
I did, so far I am stuck here
```
[root@li1666-42 openshift-ansible]# oc logs asb-1-deploy 
--> Scaling asb-1 to 1
error: update acceptor rejected asb-1: watch closed before Until timeout
--> Error listing events for replication controller asb-1: Get https://172.30.0.1:443/api/v1/namespaces/openshift-ansible-service-broker/events?fieldSelector=involvedObject.kind%3DReplicationController%2CinvolvedObject.name%3Dasb-1%2CinvolvedObject.namespace%3Dopenshift-ansible-service-broker%2CinvolvedObject.uid%3D75446fe6-3bd3-11e8-8bd9-f23c91ca87b4: read tcp 10.129.0.83:42182->172.30.0.1:443: read: connection reset by peer
```
I am thinking that there should be a routing, dns issue or certificate issue, which is preventing broker from reaching to kubernetes service (172.30.0.1:443)
```
[root@li1666-42 openshift-ansible]# oc get services --all-namespaces 
NAMESPACE                           NAME                 CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
default                             docker-registry      172.30.230.130   <none>        5000/TCP                  3d
default                             kubernetes           172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     3d
default                             openshift-cockpit    172.30.1.173     <none>        9000/TCP,80/TCP,443/TCP   3d
default                             registry-console     172.30.200.134   <none>        9000/TCP                  3d
default                             router               172.30.226.184   <none>        80/TCP,443/TCP,1936/TCP   3d
kube-service-catalog                apiserver            172.30.119.9     <none>        443/TCP                   3d
kube-service-catalog                controller-manager   172.30.244.63    <none>        6443/TCP                  3d
openshift-ansible-service-broker    asb                  172.30.149.144   <none>        1338/TCP                  1d
openshift-ansible-service-broker    asb-etcd             172.30.114.224   <none>        2379/TCP                  1d
openshift-template-service-broker   apiserver            172.30.106.166   <none>        443/TCP                   1d
```
Both pods in openshift-ansible-service-broker are in Error state
```
[root@li1666-42 openshift-ansible]# oc get pods
NAME                READY     STATUS    RESTARTS   AGE
asb-1-deploy        0/1       Error     0          1d
asb-etcd-1-deploy   0/1       Error     0          1d
```
