### ISSUE TITLE
msg: No Package matching 'origin' found available, installed or updated

### ISSUE THREAD

**Issue by michelvocks** [openshift/openshift-ansible#652]
Hello,

I tried to install openshift origin via openshift-ansible (release 3.0.2-1).
My Master, Slave01 and Slave02 have RHEL 7.1 installed.
My /etc/ansible/hosts:
# Host configuration

# Create an OSEv3 group that contains the masters and nodes groups
[OSv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_sudo must be set to true
#ansible_sudo=true

deployment_type=origin

# host group for masters
[masters]
10.24.208.165

# host group for nodes
[nodes]
10.24.208.168
10.24.208.164

Output of ansible (v.1.9.2):
TASK: [openshift_master_ca | Install the base package for admin tooling] ******
<10.24.208.165> ESTABLISH CONNECTION FOR USER: root
<10.24.208.165> REMOTE_MODULE yum pkg=origin state=present
<10.24.208.165> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 10.24.208.165 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1444052146.36-169705899365807 && echo $HOME/.ansible/tmp/ansible-tmp-1444052146.36-169705899365807'
<10.24.208.165> PUT /tmp/tmp3y2bYv TO /root/.ansible/tmp/ansible-tmp-1444052146.36-169705899365807/yum
<10.24.208.165> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 10.24.208.165 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python -tt /root/.ansible/tmp/ansible-tmp-1444052146.36-169705899365807/yum; rm -rf /root/.ansible/tmp/ansible-tmp-1444052146.36-169705899365807/ >/dev/null 2>&1'
failed: [10.24.208.165] => {"changed": false, "failed": true, "rc": 0, "results": []}
msg: No Package matching 'origin' found available, installed or updated

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/config.retry

10.24.208.165              : ok=21   changed=0    unreachable=0    failed=1
localhost                  : ok=7    changed=0    unreachable=0    failed=0

Output of yum search openshift:
Loaded plugins: langpacks, product-id, subscription-manager
====================================================================================== N/S matched: openshift ======================================================================================
jenkins-plugin-openshift.x86_64 : Provides Basic OpenShift interface to jenkins
openshift-origin-broker.noarch : OpenShift Origin broker components
openshift-origin-broker-util.noarch : Utility scripts for the OpenShift Origin broker
openshift-origin-cartridge-cron.noarch : Embedded cron support for OpenShift
openshift-origin-cartridge-dependencies-optional-all.noarch : All optional user dependency packages for OpenShift Cartridges
openshift-origin-cartridge-dependencies-optional-diy.noarch : Optional user dependencies for DIY OpenShift Cartridges
openshift-origin-cartridge-dependencies-optional-jbossas.noarch : Optional user dependencies for JBossAS OpenShift Cartridges
openshift-origin-cartridge-dependencies-optional-jbosseap.noarch : Optional user dependencies for JBossEAP OpenShift Cartridges
openshift-origin-cartridge-dependencies-optional-jbossews.noarch : Optional user dependencies for JBossEWS OpenShift Cartridges
openshift-origin-cartridge-dependencies-optional-nodejs.noarch : Optional user dependencies for Nodejs OpenShift Cartridges
openshift-origin-cartridge-dependencies-optional-perl.noarch : Optional user dependencies for Perl OpenShift Cartridges
openshift-origin-cartridge-dependencies-optional-php.noarch : Optional user dependencies for PHP OpenShift Cartridges
openshift-origin-cartridge-dependencies-optional-python.noarch : Optional user dependencies for Python OpenShift Cartridges
openshift-origin-cartridge-dependencies-optional-ruby.noarch : Optional user dependencies for Ruby OpenShift Cartridges
openshift-origin-cartridge-dependencies-recommended-all.noarch : All recommended user dependency packages for OpenShift Cartridges
openshift-origin-cartridge-dependencies-recommended-diy.noarch : Recommended user dependencies for DIY OpenShift Cartridges
openshift-origin-cartridge-dependencies-recommended-jbossas.noarch : Recommended user dependencies for JBossAS OpenShift Cartridges
openshift-origin-cartridge-dependencies-recommended-jbosseap.noarch : Recommended user dependencies for JBossEAP OpenShift Cartridges
openshift-origin-cartridge-dependencies-recommended-jbossews.noarch : Recommended user dependencies for JBossEWS OpenShift Cartridges
openshift-origin-cartridge-dependencies-recommended-nodejs.noarch : Recommended user dependencies for Nodejs OpenShift Cartridges
openshift-origin-cartridge-dependencies-recommended-perl.noarch : Recommended user dependencies for Perl OpenShift Cartridges
openshift-origin-cartridge-dependencies-recommended-php.noarch : Recommended user dependencies for PHP OpenShift Cartridges
openshift-origin-cartridge-dependencies-recommended-python.noarch : Recommended user dependencies for Python OpenShift Cartridges
openshift-origin-cartridge-dependencies-recommended-ruby.noarch : Recommended user dependencies for Ruby OpenShift Cartridges
openshift-origin-cartridge-jenkins-client.noarch : Embedded jenkins client support for OpenShift
openshift-origin-cartridge-mongodb.noarch : Embedded mongodb support for OpenShift
openshift-origin-cartridge-phpmyadmin.noarch : phpMyAdmin support for OpenShift
openshift-origin-console.noarch : The OpenShift Management Console
openshift-origin-logshifter.x86_64 : Log transport for OpenShift gear processes.
openshift-origin-msg-common.noarch : Common msg components for OpenShift broker and node
openshift-origin-msg-node-mcollective.noarch : M-Collective agent file for openshift-origin-msg-node-mcollective
openshift-origin-node-proxy.noarch : Routing proxy for OpenShift Origin Node
openshift-origin-node-util.noarch : Utility scripts for the OpenShift Origin node
openshift-origin-port-proxy.noarch : Script to configure HAProxy to do port forwarding for OpenShift
openshift-origin-util.noarch : Utility scripts for the OpenShift Origin broker and node
openshift-origin-util-scl.noarch : Utility scripts for the OpenShift Origin broker and node
pam_openshift.x86_64 : Openshift PAM module
pam_openshift-debuginfo.x86_64 : Debug information for package pam_openshift
rubygem-openshift-origin-admin-console.noarch : OpenShift plugin adding an administrative console to the broker
rubygem-openshift-origin-auth-kerberos.noarch : OpenShift plugin for kerberos auth service
rubygem-openshift-origin-auth-kerberos-doc.noarch : OpenShift plugin for kerberos auth service documentation
rubygem-openshift-origin-auth-mongo.noarch : OpenShift plugin for mongo auth service
rubygem-openshift-origin-auth-mongo-doc.noarch : OpenShift plugin for mongo auth service ri documentation
rubygem-openshift-origin-auth-remote-user.noarch : OpenShift plugin for remote-user authentication
rubygem-openshift-origin-console.noarch : OpenShift Origin Management Console
rubygem-openshift-origin-console-doc.noarch : OpenShift Origin Management Console docs.
rubygem-openshift-origin-container-selinux.noarch : OpenShift plugin for SELinux based containers
rubygem-openshift-origin-dns-avahi.noarch : OpenShift plugin for DNS update service using Avahi
rubygem-openshift-origin-dns-bind.noarch : OpenShift plugin for BIND service
rubygem-openshift-origin-dns-nsupdate.noarch : OpenShift plugin for DNS update service using nsupdate
rubygem-openshift-origin-dns-route53.noarch : OpenShift plugin for AWS Route53 service
rubygem-openshift-origin-frontend-apache-mod-rewrite.noarch : OpenShift Apache mod_rewrite frontend plugin
rubygem-openshift-origin-frontend-apache-vhost.noarch : OpenShift Apache Virtual Hosts frontend plugin
rubygem-openshift-origin-frontend-apachedb.noarch : OpenShift ApacheDB frontend plugin
rubygem-openshift-origin-frontend-haproxy-sni-proxy.noarch : OpenShift HAProxy SNI Proxy frontend plugin
rubygem-openshift-origin-frontend-nodejs-websocket.noarch : OpenShift NodeJS Websocket frontend plugin
rubygem-openshift-origin-msg-broker-mcollective.noarch : OpenShift plugin for mcollective service
rubygem-openshift-origin-routing-activemq.noarch : OpenShift plugin for publishing routing information on ActiveMQ
golang-github-openshift-go-json-rest-devel.noarch : A quick and easy way to setup a RESTFUL JSON API
golang-github-openshift-go-systemd-devel.noarch : Go bindings to systemd D-BUS APIs
jboss-openshift-metrics-module.noarch : Collects and exposes runtime metrics from a running JBoss instance
openshift-origin-cartridge-10gen-mms-agent.noarch : Embedded 10gen MMS agent for performance monitoring of MondoDB
openshift-origin-cartridge-diy.noarch : DIY cartridge
openshift-origin-cartridge-haproxy.noarch : Provides HA Proxy
openshift-origin-cartridge-jbossas.noarch : Provides JBossAS7 support
openshift-origin-cartridge-jbosseap.noarch : Provides JBossEAP6.0 support
openshift-origin-cartridge-jbossews.noarch : Provides JBossEWS2.0 support
openshift-origin-cartridge-jenkins.noarch : Provides jenkins-1.x support
openshift-origin-cartridge-mariadb.noarch : Provides embedded mariadb support
openshift-origin-cartridge-mock.noarch : Mock cartridge for V2 Cartridge SDK
openshift-origin-cartridge-mock-plugin.noarch : Mock plugin cartridge for V2 Cartridge SDK
openshift-origin-cartridge-mysql.noarch : Provides embedded mysql support
openshift-origin-cartridge-nodejs.noarch : Provides Node.js support
openshift-origin-cartridge-perl.noarch : Perl cartridge
openshift-origin-cartridge-php.noarch : Php cartridge
openshift-origin-cartridge-postgresql.noarch : Provides embedded PostgreSQL support
openshift-origin-cartridge-python.noarch : Python cartridge
openshift-origin-cartridge-ruby.noarch : Ruby cartridge
openshift-origin-cartridge-switchyard.noarch : Provides embedded switchyard support
osbs.noarch : Python command line client for OpenShift Build Service
python-osbs.noarch : Python 2 module for OpenShift Build Service
rhc.noarch : OpenShift client management tools
rubygem-openshift-origin-common.noarch : Cloud Development Common
rubygem-openshift-origin-common-doc.noarch : Cloud Development Common Library Documentation
rubygem-openshift-origin-controller.noarch : Cloud Development Controller
rubygem-openshift-origin-controller-doc.noarch : Cloud Development Controller docs
rubygem-openshift-origin-node.noarch : Cloud Development Node
rubygem-rhc.noarch : OpenShift Express Client Tools
switchyard-as7-modules.noarch : JBoss Application Server OpenShift SwitchYard Extension Modules

One hint: My yum repo is configured to look at /etc/yum.repos.mycustomrepo/ instead of /etc/yum.repos.d/ and this cannot be changed.

Thank you in advance

**Comment by abutcher** [comment]
@michelvocks Your yum configuration has `reposdir=/etc/yum.repos.mycustomrepo`?

**Comment by michelvocks** [comment]
@abutcher exactly

**Comment by michelvocks** [comment]
I found a soluten: They openshift-ansible script automatically deployed a yum-configuration file at "/etc/yum.repos.d/maxamillion-origin-next-epel-7.repo". So I just had to copy the "maxamillion-origin-next-epel-7.repo" file to my customized repo "/etc/yum.repos.mycustomrepo".
