### ISSUE TITLE
Prereqs are not applied to masters or etcd when containerized

### ISSUE THREAD

**Issue by fraenkel** [openshift/openshift-ansible#6540]
If you run containerized the new prereqs are only applied to nodes. The install fails pretty quickly when you run containerized.

I also noticed that the container-runtime playbooks refer to openshift_containerized_host_groups which isn't set anywhere and will only configure the l_containerized_host_groups to be nodes only.

**Comment by michaelgugino** [comment]
@fraenkel Yes, this is a bug in our documentation for a few feature.

openshift_containerized_host_groups should be a list (as in, a yaml or json list) of host groups that are containerized.

Masters should be part of the nodes group.

**Comment by fraenkel** [comment]
@michaelgugino For some reason the masters aren't appearing in the oo_nodes_to_config.

**Comment by fraenkel** [comment]
@michaelgugino 
I have tried setting openshift_containerized_host_groups to a variety of things like oo_all_hosts, g_master_hosts, and etcd, but it still only installs docker on the nodes. I think the evaluation of hosts isn't occurring after the variables are defined.

**Comment by michaelgugino** [comment]
@fraenkel openshift_containerized_host_groups should be a list.

Please post your inventory and I'll see if there's any issues and try to replicate.

**Comment by fraenkel** [comment]
@michaelgugino The relevant part taken from our default.yml which is under group_vars/OSEv3/

For testing I did,
openshift_containerized_host_groups: [ 'oo_all_hosts', 'etcd', 'g_master_hosts']

And when I add debug statements to the playbooks/container-runtime/private/conffig.yml
I see that l_containerized_host_groups has oo_nodes_to_config:oo_all_hosts:etcd:g_master_hosts, however I only see the 2 nodes in my setup processed.

**Comment by michaelgugino** [comment]
@fraenkel Thank you for the information.  I was able to figure out what's happening.  I have a patch open to fix the issue of openshift_containerized_host_groups not working as intended.

You can now define openshift_containerized_host_groups in all group_vars or any group that the first master is a part of (such as OSEv3).

Also, all masters should be included in the nodes group, either directly or through a child group.  This is just a standard requirement for openshift.
