### ISSUE TITLE
Installation fails when ansible_become=yes is in all group

### ISSUE THREAD

**Issue by sector2000** [openshift/openshift-ansible#6544]
#### Description

The inventory defines hosts for Openshift (OSEv3 group) but also non-Openshift hosts. For this reason some common variables are defined in the [all:vars] group.
In [all:vars] group are defined the following variables:

ansible_user=ansible
ansible_become=yes
ansible_become_user=root

The Openshift installation fails with:

Failed to fetch the file: [Errno 13] Permission denied

during execution of etcd_server_certificates role.

If the variable ansible_become=yes is moved from [all:vars] group to [OSEv3:vars] group the installation succeeds. If the variable is defined in both groups the installation also fails.

##### Version

Please put the following version information in the code block
indicated below.

```
$ ansible --version

ansible 2.4.1.0

  config file = /home/ansible/git-repos/openpaas-onprem_ext/ocp-installation/ansible.cfg

  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']

  ansible python module location = /usr/lib/python2.7/site-packages/ansible

  executable location = /usr/bin/ansible

  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]


$ rpm -q atomic-openshift-utils openshift-ansible

atomic-openshift-utils-3.6.173.0.48-1.git.0.1609d30.el7.noarch

openshift-ansible-3.6.173.0.48-1.git.0.1609d30.el7.noarch
```

##### Steps To Reproduce
1. Create inventory file defining ansible_user and ansible_become_user in [OSEv3:vars] group
2. Put only ansible_become=yes in [all:vars] group
3. Run Openshift installation with ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml

##### Expected Results
Installation should complete successfully

##### Observed Results
Installation fails with:

Failed to fetch the file: [Errno 13] Permission denied

during execution of etcd_server_certificates role.

```
....... |  TASK [etcd_server_certificates : Retrieve etcd cert tarball] ****************************************************************************************************************************************
2017-11-24 12:26:20,771 p=1863 u=***************** |  fatal: [*****************]: FAILED! => {
    "failed": true
}

MSG:

Failed to fetch the file: [Errno 13] Permission denied: '/tmp/etcd_certificates-c3UDgOu/etcd-*****************.tgz'

2017-11-24 12:26:20,780 p=1863 u=***************** |  fatal: [*****************]: FAILED! => {
    "failed": true
}

MSG:

Failed to fetch the file: [Errno 13] Permission denied: '/tmp/etcd_certificates-dXSJuHq/etcd-*****************.tgz'

2017-11-24 12:26:20,787 p=1863 u=***************** |  fatal: [*****************]: FAILED! => {
    "failed": true
}

MSG:

Failed to fetch the file: [Errno 13] Permission denied: '/tmp/etcd_certificates-nqRs9AD/etcd-*****************.tgz'
```

##### Additional Information

OS: RHEL 7.4

The same error impacts also other roles. The ones that I found are at least:
- etcd_server_certificates
- etcd_client_certificates
- openshift_master_certificates
- openshift_node_certificates
- openshift_logging

but there are most probably more. It seems to occur whenever the role includes a task with

```
local_action: command mktemp ......
become: no
```

**Comment by jpeeler** [comment]
FWIW, I was experiencing this issue as well. Although I suspect there should be some configuration that makes this unnecessary, running as root as indicated here: https://github.com/ansible/ansible/issues/15933#issuecomment-220657744, solved the issue for me.
