### ISSUE TITLE
scheduler.json missing kind/version info

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#656]
The scheduler.json file is supposed to be a serialization with the same kind/apiVersion fields as all other API objects. The default template is missing these fields, which means our config isn't getting run through the conversions/defaulting that keeps us backwards compatible. It happens to work currently, because all the internal field names are the same as the JSON field names, but we shouldn't depend on that.

The scheduler.json should start with:
```
{
"kind" : "Policy",
"apiVersion" : "v1",
...
```

**Comment by liggitt** [comment]
Additionally, we should document (or automate? not sure if that's advisable) adding these to existing scheduler.json files

**Comment by sdodson** [comment]
(Summarizing offline discussions for benefit of future readers of this issue).

We provide an upgrade playbook which re-applies all the current ansible templates defined so if users utilize the upgrade playbook this will be added when they upgrade.

However this is new and we're still documenting json changes so I'll open a docs PR though I'm not sure where to put it as if we list it under 3.0.2/1.0.5 users who have already upgraded to that version may miss it. I guess we should document it for 3.0.2/1.0.5 and 3.1/1.1.

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-docs/pull/1047 and a follow up issue for 3.1 docs as we can't be sure that folks upgrading to 3.0.2 had this applied as we've added it to the docs two weeks after 3.0.2 went out.
https://github.com/openshift/openshift-docs/issues/1048
