### ISSUE TITLE
fail install with latest openshift-ansible

### ISSUE THREAD

**Issue by hetzbh** [openshift/openshift-ansible#6560]
I'm using CentOS 7.4 and @gshipley ansible configuration along with the latest update to use deploy_cluster.yml.

My inventory.erb file is the same as @gshipley just different host & domain name. When I run the command: ansible-playbook -i installcentos/inventory.erb openshift-ansible/playbooks/deploy_cluster.yml it stops after a minute or so with the following message:

`TASK [openshift_version : Get available origin version] ******************************************************************************************
fatal: [openshift.hetzlabs.io]: FAILED! => {"changed": false, "module_stderr": "Shared connection to openshift.hetzlabs.io closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_qhIerf/ansible_module_repoquery.py\", line 641, in <module>\r\n    main()\r\n  File \"/tmp/ansible_qhIerf/ansible_module_repoquery.py\", line 631, in main\r\n    rval = Repoquery.run_ansible(module.params, module.check_mode)\r\n  File \"/tmp/ansible_qhIerf/ansible_module_repoquery.py\", line 587, in run_ansible\r\n    results = repoquery.repoquery()\r\n  File \"/tmp/ansible_qhIerf/ansible_module_repoquery.py\", line 546, in repoquery\r\n    rval = self._repoquery_cmd(repoquery_cmd, True, 'raw')\r\n  File \"/tmp/ansible_qhIerf/ansible_module_repoquery.py\", line 384, in _repoquery_cmd\r\n    returncode, stdout, stderr = _run(cmds)\r\n  File \"/tmp/ansible_qhIerf/ansible_module_repoquery.py\", line 355, in _run\r\n    stderr=subprocess.PIPE)\r\n  File \"/usr/lib64/python2.7/subprocess.py\", line 711, in __init__\r\n    errread, errwrite)\r\n  File \"/usr/lib64/python2.7/subprocess.py\", line 1327, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n", "msg": "MODULE FAILURE", "rc": 0}                                                        
        to retry, use: --limit @/home/hetz/openshift-ansible/playbooks/deploy_cluster.retry`

I thought it was related to firewalld but it's stopped and there are no iptable rules.

Am I missing something?

**Comment by nirdshabo** [comment]
`sudo yum install -y centos-release-openshift-origin`
fixed for me this issue (but not others) on latest cloudimg CentOS7...
from a very brief view its some regression that the playbook is not adding the yum repos anymore. Again, atleast on CentOS7

**Comment by hetzbh** [comment]
[inventory.txt](https://github.com/openshift/openshift-ansible/files/1584476/inventory.txt)
I thought about it too and I added it. Didn't help much. I enabled NFS (since I use it for ETCD) and .. same thing.

Here's my file:

**Comment by subodhp** [comment]
I am facing the same error, I tried to install using -vvv. 

Using module file /root/openshift-ansible/roles/lib_utils/library/repoquery.py
<mymaster.local.com> ESTABLISH SSH CONNECTION FOR USER: root
<mymaster.local.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/7d832251fc mymaster.local.com '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<mymaster.local.com> (0, '/root\n', '')
<mymaster.local.com> ESTABLISH SSH CONNECTION FOR USER: root
<mymaster.local.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/7d832251fc mymaster.local.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1514197910.01-113682525007274 `" && echo ansible-tmp-1514197910.01-113682525007274="` echo /root/.ansible/tmp/ansible-tmp-1514197910.01-113682525007274 `" ) && sleep 0'"'"''
<mymaster.local.com> (0, 'ansible-tmp-1514197910.01-113682525007274=/root/.ansible/tmp/ansible-tmp-1514197910.01-113682525007274\n', '')
<mymaster.local.com> PUT /tmp/tmpLpXr0A TO /root/.ansible/tmp/ansible-tmp-1514197910.01-113682525007274/repoquery.py
<mymaster.local.com> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/7d832251fc '[mymaster.local.com]'
<mymaster.local.com> (0, 'sftp> put /tmp/tmpLpXr0A /root/.ansible/tmp/ansible-tmp-1514197910.01-113682525007274/repoquery.py\n', '')
<mymaster.local.com> ESTABLISH SSH CONNECTION FOR USER: root
<mymaster.local.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/7d832251fc mymaster.local.com '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1514197910.01-113682525007274/ /root/.ansible/tmp/ansible-tmp-1514197910.01-113682525007274/repoquery.py && sleep 0'"'"''
<mymaster.local.com> (0, '', '')
<mymaster.local.com> ESTABLISH SSH CONNECTION FOR USER: root
<mymaster.local.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/7d832251fc -tt mymaster.local.com '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1514197910.01-113682525007274/repoquery.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1514197910.01-113682525007274/" > /dev/null 2>&1 && sleep 0'"'"''
<mymaster.local.com> (0, 'Traceback (most recent call last):\r\n  File "/tmp/ansible_h4Jvxw/ansible_module_repoquery.py", line 641, in <module>\r\n    main()\r\n  File "/tmp/ansible_h4Jvxw/ansible_module_repoquery.py", line 631, in main\r\n    rval = Repoquery.run_ansible(module.params, module.check_mode)\r\n  File "/tmp/ansible_h4Jvxw/ansible_module_repoquery.py", line 587, in run_ansible\r\n    results = repoquery.repoquery()\r\n  File "/tmp/ansible_h4Jvxw/ansible_module_repoquery.py", line 546, in repoquery\r\n    rval = self._repoquery_cmd(repoquery_cmd, True, \'raw\')\r\n  File "/tmp/ansible_h4Jvxw/ansible_module_repoquery.py", line 384, in _repoquery_cmd\r\n    returncode, stdout, stderr = _run(cmds)\r\n  File "/tmp/ansible_h4Jvxw/ansible_module_repoquery.py", line 355, in _run\r\n    stderr=subprocess.PIPE)\r\n  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__\r\n    errread, errwrite)\r\n  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n', 'Shared connection to mymaster.local.com closed.\r\n')
fatal: [mymaster.local.com]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Shared connection to mymaster.local.com closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_h4Jvxw/ansible_module_repoquery.py\", line 641, in <module>\r\n    main()\r\n  File \"/tmp/ansible_h4Jvxw/ansible_module_repoquery.py\", line 631, in main\r\n    rval = Repoquery.run_ansible(module.params, module.check_mode)\r\n  File \"/tmp/ansible_h4Jvxw/ansible_module_repoquery.py\", line 587, in run_ansible\r\n    results = repoquery.repoquery()\r\n  File \"/tmp/ansible_h4Jvxw/ansible_module_repoquery.py\", line 546, in repoquery\r\n    rval = self._repoquery_cmd(repoquery_cmd, True, 'raw')\r\n  File \"/tmp/ansible_h4Jvxw/ansible_module_repoquery.py\", line 384, in _repoquery_cmd\r\n    returncode, stdout, stderr = _run(cmds)\r\n  File \"/tmp/ansible_h4Jvxw/ansible_module_repoquery.py\", line 355, in _run\r\n    stderr=subprocess.PIPE)\r\n  File \"/usr/lib64/python2.7/subprocess.py\", line 711, in __init__\r\n    errread, errwrite)\r\n  File \"/usr/lib64/python2.7/subprocess.py\", line 1327, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n",
    "msg": "MODULE FAILURE",
    "rc": 0
}
        to retry, use: --limit @/root/openshift-ansible/playbooks/deploy_cluster.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0
myinfra.local.com          : ok=14   changed=0    unreachable=0    failed=0
mymaster.local.com         : ok=23   changed=0    unreachable=0    failed=1
mynode.local.com           : ok=14   changed=0    unreachable=0    failed=0

INSTALLER STATUS ****************************************************************************************************************************************************************************************************************************
Initialization             : In Progress (0:00:26)

Failure summary:

  1. Hosts:    mymaster.local.com
     Play:     Determine openshift_version to configure on first master
     Task:     Get available origin version
     Message:  MODULE FAILURE
[root@myadmin ansible]#

Thanks,
Subodh Pachghare

**Comment by nirdshabo** [comment]
i can confirm i pass openstack installation with release `openshift-ansible-3.9.0-0.4.0`
From quick review of the deploy process, on latest openshift ansible its seems to skip major chunk of the requirements/facts installation, hence its also not installing the required repos and libs, but only that, its not putting in many important deployment facts required for the deployment to succeed...

**Comment by hetzbh** [comment]
Ok, looks like I found the issue. the config file mentioned osm_use_cockpit=true while my machine doesn't have cockpit installed. Removed this line and it works.

**Comment by adgud** [comment]
I had the same exact problem, I solved it by running `playbooks/prerequisites.yml` playbook first - this should be mentioned in docs.

**Comment by lukasb95** [comment]
@adgud where to find that playbooks/prerequisites.yml file? 

It's already more than 2 weeks and and my openshift-container platform still fails to install with various problems. 

Last installation error is the same like ts: 
2018-04-02 10:41:16,134 p=12188 u=root |  fatal: [osnodea.172.16.0.15.nip.io]: FAILED! => {"changed": false, "module_stderr": "Shared connection to osnodea.172.16.0.15.nip.io closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_d2lUs_/ansible_module_repoquery.py\", line 642, in <module>\r\n    main()\r\n  File \"/tmp/ansible_d2lUs_/ansible_module_repoquery.py\", line 632, in main\r\n    rval = Repoquery.run_ansible(module.params, module.check_mode)\r\n  File \"/tmp/ansible_d2lUs_/ansible_module_repoquery.py\", line 588, in run_ansible\r\n    results = repoquery.repoquery()\r\n  File \"/tmp/ansible_d2lUs_/ansible_module_repoquery.py\", line 547, in repoquery\r\n    rval = self._repoquery_cmd(repoquery_cmd, True, 'raw')\r\n  File \"/tmp/ansible_d2lUs_/ansible_module_repoquery.py\", line 385, in _repoquery_cmd\r\n    returncode, stdout, stderr = _run(cmds)\r\n  File \"/tmp/ansible_d2lUs_/ansible_module_repoquery.py\", line 356, in _run\r\n    stderr=subprocess.PIPE)\r\n  File \"/usr/lib64/python2.7/subprocess.py\", line 711, in __init__\r\n    errread, errwrite)\r\n  File \"/usr/lib64/python2.7/subprocess.py\", line 1327, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n", "msg": "MODULE FAILURE", "rc": 0}

hopefully someone can help me...

**Comment by adgud** [comment]
@lukasb95 
It's [here](https://github.com/openshift/openshift-ansible/blob/master/playbooks/prerequisites.yml).

**Comment by lukasb95** [comment]
Thanks, 
Currently I'm stuck at installing the web console -- the web console couldn't start...

**Comment by Git-yangrui** [comment]
TASK [Gather Cluster facts and set is_containerized if needed] ****************************************************************************************************************************************************************
Wednesday 10 October 2018  11:58:43 -0400 (0:00:00.182)       0:00:16.777 ***** 
fatal: [node2]: FAILED! => {"changed": false, "module_stderr": "KeyError('ansible_os_family',)\nTraceback (most recent call last):\n  File \"/tmp/ansible_TwhDzs/ansible_module_openshift_facts.py\", line 2501, in <module>\n    main()\n  File \"/tmp/ansible_TwhDzs/ansible_module_openshift_facts.py\", line 2488, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_TwhDzs/ansible_module_openshift_facts.py\", line 1841, in __init__\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_TwhDzs/ansible_module_openshift_facts.py\", line 1878, in generate_facts\n    defaults = self.get_defaults(roles, deployment_type, deployment_subtype)\n  File \"/tmp/ansible_TwhDzs/ansible_module_openshift_facts.py\", line 1969, in get_defaults\n    if self.system_facts['ansible_pkg_mgr'] == 'dnf':\nKeyError: 'ansible_pkg_mgr'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
fatal: [node1]: FAILED! => {"changed": false, "module_stderr": "KeyError('ansible_os_family',)\nTraceback (most recent call last):\n  File \"/tmp/ansible_k7JYnJ/ansible_module_openshift_facts.py\", line 2501, in <module>\n    main()\n  File \"/tmp/ansible_k7JYnJ/ansible_module_openshift_facts.py\", line 2488, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_k7JYnJ/ansible_module_openshift_facts.py\", line 1841, in __init__\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_k7JYnJ/ansible_module_openshift_facts.py\", line 1878, in generate_facts\n    defaults = self.get_defaults(roles, deployment_type, deployment_subtype)\n  File \"/tmp/ansible_k7JYnJ/ansible_module_openshift_facts.py\", line 1969, in get_defaults\n    if self.system_facts['ansible_pkg_mgr'] == 'dnf':\nKeyError: 'ansible_pkg_mgr'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
fatal: [master]: FAILED! => {"changed": false, "module_stderr": "KeyError('ansible_os_family',)\nTraceback (most recent call last):\n  File \"/tmp/ansible_zsiRAu/ansible_module_openshift_facts.py\", line 2501, in <module>\n    main()\n  File \"/tmp/ansible_zsiRAu/ansible_module_openshift_facts.py\", line 2488, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_zsiRAu/ansible_module_openshift_facts.py\", line 1841, in __init__\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_zsiRAu/ansible_module_openshift_facts.py\", line 1878, in generate_facts\n    defaults = self.get_defaults(roles, deployment_type, deployment_subtype)\n  File \"/tmp/ansible_zsiRAu/ansible_module_openshift_facts.py\", line 1969, in get_defaults\n    if self.system_facts['ansible_pkg_mgr'] == 'dnf':\nKeyError: 'ansible_pkg_mgr'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

NO MORE HOSTS LEFT ************************************************************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0   
master                     : ok=21   changed=0    unreachable=0    failed=1   
node1                      : ok=20   changed=0    unreachable=0    failed=1   
node2                      : ok=20   changed=0    unreachable=0    failed=1

**Comment by Git-yangrui** [comment]
I also meet the error when install openshift 3.7 by ansible as above

**Comment by imranrazakhan** [comment]
I have change my network configuration like below and start getting error 
```
      -  nmcli con modify team0 ipv4.method auto
      -  nmcli con modify team0 ipv4.addresses 192.168.x.x/24
      + nmcli con modify team0 ipv4.method manual
      + nmcli con modify team0 ipv4.addresses "192.168.x.x/24, 10.x.x.x.x/28"
```

`FAILED! => {"changed": false, "module_stderr": "Shared connection to my.domain.local closed.\r\n", "module_stdout":`

**Comment by amhazeem** [comment]
> I also meet the error when install openshift 3.7 by ansible as above

Have you found a solution yet?

**Comment by imranrazakhan** [comment]
I have to add default route and now its working.
