### ISSUE TITLE
Error: docker-ce conflicts with docker-1.12

### ISSUE THREAD

**Issue by Tirke** [openshift/openshift-ansible#6566]
#### Description

I'm trying to deploy a one master / two nodes + two infra nodes cluster with every node running docker `17.09.1-ce`.
Install of the master node was successful after setting `openshift_disable_check=docker_storage,package_availability,package_version`.

Node install is failing in `openshift-ansible/roles/openshift_node/tasks/install.yml` with :
`Error: docker-ce conflicts with 2:docker-1.12.6-68.gitec8512b.el7.centos.x86_64\n"`

I'm searching for a way to disable docker version checking or for a way to disable docker installation during the playbook. I know that the documentation points to docker 1.12 but I'm not sure I want to rely on such an old version of docker (unless there is no other way).

Thanks.

##### Version
Ansible 2.4.2.0
Centos 7.4
openshift-ansible-3.9.0-0.10.0-58-g88b74bd

**Comment by davidaah** [comment]
it seems the installer makes hardcoded assumptions that the package will be called `docker` (see docker_sanity.yml) which is being called by package_docker.yml

per https://github.com/openshift/openshift-ansible/issues/4016 does not seem upstream packages are supported (at least by the installer)
