### ISSUE TITLE
AGAIN: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed

### ISSUE THREAD

**Issue by Rocking80** [openshift/openshift-ansible#6575]
#### Description

In my role there is a step using `copy` module, but it reports selinux error as below. 

> fatal: [222.7.7.152]: FAILED! => {"changed": false, "checksum": "c8ee7015b10f48acf4664ec33733e0c1eb025cb7", "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}

I installed libselinux-python on my control server (CentOS 6.5) but it does NOT work.
Also I tried to set selinux status to 'Permissive' on remote server using `setenforce 0` (CentOS 6.5), also cannot fix the issue. As suggested by others, should be work if disable selinux which need a reboot. So I didn't try this solution yet.

Is this a bug in ansible code or is there anyone has a solution which not need to reboot the remote server? Many thanks.

##### Version

I installed ansible via pip.

```
# ansible --version
ansible 2.4.2.0
  config file = /home/peng/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

```
[root@test01 ansible]# rpm -q atomic-openshift-utils openshift-ansible
package atomic-openshift-utils is not installed
package openshift-ansible is not installed
```

##### Steps To Reproduce
1. Run playbook which has copy module

**Comment by Rocking80** [comment]
Sorry, seems wrong place. close it now.

**Comment by zoobab** [comment]
I have the same issue on openshift-ansible-3.9.41-1-27-g764c84f.
