### ISSUE TITLE
termination grace period not set correctly hawkular_cassandra_rc.j2

### ISSUE THREAD

**Issue by jsanda** [openshift/openshift-ansible#6632]
#### Description

```terminationGracePeriodSeconds``` is supposed to be set to 1800 (i.e., 30 minutes); however, the indentation is off resulting in the default of 30 seconds.

##### Version

`ansible --version`
2.3.2.0

`git describe`
openshift-ansible-3.9.0-0.16.0-7-g31d19c5e6

**Comment by mwringe** [comment]
This also needs to be fixed from 3.5 to the present version. Without the proper termination grace period, Cassandra can cause some bad issues due to corrupted files during writes.

**Comment by jsanda** [comment]
I have submitted [PR 6688](https://github.com/openshift/openshift-ansible/pull/6688) for this.

@mwringe will we need PRs for multiple branches? If so, can you please tell me which branches?

**Comment by jsanda** [comment]
@ewolinetz can you review this? Based on previous comment, it looks like I need to back port this as well. Can you tell me what branches? Then I will go ahead and open separate PRs.
