### ISSUE TITLE
ose-web-console container image not available redhat registry

### ISSUE THREAD

**Issue by j00p34** [openshift/openshift-ansible#6645]
#### Description

Openshift enterprise install fails because ose-web-console image is not available:

When doing a fresh install of openshift enterprise on Atomic host the web-console never becomes available

TASK [openshift_web_console : Verify that the web console is running] **********
FAILED - RETRYING: Verify that the web console is running (120 retries left).

It seems the image is not in the redhat registry?

Back-off pulling image "registry.access.redhat.com/openshift3/ose-web-console:v3.9"

##### Version

ansible 2.4.2.0

If you're operating from a **git clone**:

* The output of `git describe`
openshift-ansible-3.9.0-0.16.0-20-g16b18bcd2

##### Steps To Reproduce
Install openshift 3.7 on Atomic

##### Expected Results
Install succeeds

##### Observed Results
FAILED - RETRYING: Verify that the web console is running (1 retries left).

**Comment by tomassedovic** [comment]
I'm seeing the same when trying to deploy Origin on CentOS.

git describe: `openshift-ansible-3.9.0-0.16.0-49-g4ac04c4`

**Comment by tomassedovic** [comment]
A workaround if you don't need the web console is setting:

    openshift_web_console_install: false

**Comment by tomassedovic** [comment]
@j00p34 it looks like maybe your issue is a little different, but this fixed it for me:

https://github.com/openshift/openshift-ansible/pull/6675

**Comment by j00p34** [comment]
Yeah I'm installing Enterprise Openshift and the image is actually not in the registry. Installation works when I just specify the origin one from docker hub :-) 
But thanks anyway

**Comment by spadgett** [comment]
> Install openshift 3.7 on Atomic

@j00p34 You should use the `release-3.7` branch to install 3.7. `master` will attempt to install the web console as a pod, which only works in 3.9. There's no 3.7 image for the console, so the install fails (as you've discovered :)

cc @sdodson 

/close

**Comment by sjenning** [comment]
This is still a legit issue.  I just installed 3.9 and the web-console deployment is set up to pull from `registry.access.redhat.com/openshift3/ose-web-console:v3.9`, not honoring `oreg_url`

**Comment by sjenning** [comment]
I think `oreg_url` needs to be considered here
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_web_console/tasks/install.yml#L11

**Comment by sdodson** [comment]
Yeah, we've done a poor job ensuring that value is parsed and used everywhere that it could be. Logging, metrics, etc all suffer the same fate. openshift_web_console_prefix='registry.example.com/openshift3/' will work around this. We plan to sweep all components and standardize on parsing oreg_url during 3.10 development so that should be the only value you need to set in the future.

**Comment by sdodson** [comment]
Also, #6774 will change this a bit.
