### ISSUE TITLE
LB can't run on masters

### ISSUE THREAD

**Issue by nodefourtytwo** [openshift/openshift-ansible#6680]
#### Description

On a multimaster installation, with native HA, it should be made clear in the documentation or it should be tested in the playbook that you can't use the same machines for the LB and the masters.

Both the master api and the load balancer use the same port (8443 by default), resulting in a conflict.

**Comment by DanyC97** [comment]
@nodefourtytwo what has made you believe that you can deploy 2 roles: master & lb into one node?

**Comment by nodefourtytwo** [comment]
I'm also deploying etcds and masters on the same nodes and it's working fine. It never actually occurred to me that I could not.

**Comment by DanyC97** [comment]
@nodefourtytwo in 3.7 it states clearly that embedded etcd is no longer supported and for prod should be on its own nodes. Before 3.7 yes i was doing the same thing with etcd and masters.

Regarding LB i have never put it on same nodes with the masters, not in prod anyway.
Saying that maybe this issue should be open against the docs to make it more clear that LB should be on separated nodes (same note like is being said about embedded etcd).

**Comment by nodefourtytwo** [comment]
@DanyC97 Thanks for the heads up about etcd in 3.7, I'll look into that before upgrading.

I will open an issue against the docs, thanks again.
