### ISSUE TITLE
bin/cluster create aws fails on OSX

### ISSUE THREAD

**Issue by tdcox** [openshift/openshift-ansible#670]
_Environment:_ OSX 10.10.5, openshift-ansible:latest, ansible:1.9.3
SSH config host wildcard entry for *.compute.amazonaws.com
AWS credentials set in .aws_creds.
ec2_keypair='mykey.pem', ec2_image='ami-e4ff5c93', ec2_region='eu-west-1' set as environment variables.

_Steps to reproduce:_
$ cd openshift-ansible
$ bin/cluster -vvv create aws demo

_Symptoms:_
Script creates the master instance on AWS, then appears to login via ssh. 
At the task [Wait for user setup], the script fails as follows:

TASK: [Wait for user setup] **************************************************\* 
<localhost> REMOTE_MODULE command ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null  echo centos user is setup
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1444229289.14-25072598861871 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1444229289.14-25072598861871 && echo $HOME/.ansible/tmp/ansible-tmp-1444229289.14-25072598861871']
<localhost> PUT /var/folders/f9/4f7r8chn6x7b0kdd8_dct5tr0000gn/T/tmp48pxeO TO /Users/terry/.ansible/tmp/ansible-tmp-1444229289.14-25072598861871/command
<localhost> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/env python2 /Users/terry/.ansible/tmp/ansible-tmp-1444229289.14-25072598861871/command; rm -rf /Users/terry/.ansible/tmp/ansible-tmp-1444229289.14-25072598861871/ >/dev/null 2>&1']
fatal: [localhost] => Traceback (most recent call last):
  File "/Users/terry/Documents/code/ansible/lib/ansible/runner/**init**.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Users/terry/Documents/code/ansible/lib/ansible/runner/__init__.py", line 815, in _executor_internal
    complex_args=complex_args
  File "/Users/terry/Documents/code/ansible/lib/ansible/runner/__init__.py", line 1043, in _executor_internal_inner
    if not utils.check_conditional(cond,  self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
  File "/Users/terry/Documents/code/ansible/lib/ansible/utils/__init__.py", line 281, in check_conditional
    raise errors.AnsibleError("error while evaluating conditional: %s" % original)
  File "/Users/terry/Documents/code/ansible/lib/ansible/errors/**init**.py", line 44, in **init**
  File "/Users/terry/Documents/code/ansible/lib/ansible/parsing/**init**.py", line 36, in <module>
ImportError: cannot import name is_executable

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/Users/terry/launch.retry

localhost                  : ok=33   changed=2    unreachable=1    failed=0   

real    1m36.480s
user    0m4.014s
sys 0m0.684s
ACTION [create] failed with exit status 768

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
