### ISSUE TITLE
openshift-ansible-3.7.23-1 "no action detected in task" in openshift_logging_elsasticsearch

### ISSUE THREAD

**Issue by elad661** [openshift/openshift-ansible#6740]
#### Description
When trying to install a cluster with logging, openshift_ansible exits with an error after 15 minutes.

##### Version

```
openshift-ansible-3.7.23-1

ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### Expected Results
openshift_ansible should finish without an error
##### Observed Results
Describe what is actually happening.

```
TASK [openshift_logging : include_role] ****************************************
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in 'openshift-ansible/roles/openshift_logging_elasticsearch/tasks/determine_version.yaml': line 19, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- include_tasks: get_es_version.yml
  ^ here


The error appears to have been in '/var/lib/jenkins/workspace/ocp-ansible-jenkins-3.7-ext_pvs/138/openshift-ansible/roles/openshift_logging_elasticsearch/tasks/determine_version.yaml': line 19, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- include_tasks: get_es_version.yml
  ^ here
```

**Comment by elad661** [comment]
This error seems to have been introduced in commit a02e68a5a3b4c32e205d6184cfb5579d416adbe7 by @ewolinetz 

This is probably because I'm using Ansible 2.3, and [include_tasks](https://docs.ansible.com/ansible/2.4/include_tasks_module.html) is new in Ansible 2.4

afaik, openshift-ansible is supposed to support Ansible 2.3 in the openshift-ansible 3.7 branch, so this should be changed to `import_tasks`. If you decide that Ansible 2.3 is not supported, openshift-ansible should fail early and tell me to update my ansible version.

**Comment by ewolinetz** [comment]
@elad661 Can you please test with the latest for release-3.7? This should be resolved now

**Comment by elad661** [comment]
@ewolinetz thanks, it works now 👍

**Comment by wenj1104** [comment]
@elad661 Can you please tell me the version that you tested?
