### ISSUE TITLE
Containerized deployment fails on RPM check

### ISSUE THREAD

**Issue by cynepco3hahue** [openshift/openshift-ansible#6756]
#### Description
```
Play:     Ensure the requested version packages are available.
     Task:     Fail if rpm version and docker image version are different
     Message:  The task includes an option with an undefined variable. The error was: 'openshift_rpm_version' is undefined
               
               The error appears to have been in '/root/openshift-ansible/roles/openshift_version/tasks/masters_and_nodes.yml': line 7, column 5, but may
               be elsewhere in the file depending on the exact syntax problem.
```

##### Version

```
openshift-ansible-3.9.0-0.20.0-9-g3a7f199
```

##### Steps To Reproduce
Run `ansible-playbook -v -i inventory openshift-ansible/playbooks/deploy_cluster.yml` with inventory
```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_deployment_type=origin
openshift_clock_enabled=true
openshift_master_identity_providers=[{'name': 'allow_all_auth', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]
openshift_disable_check=memory_availability,disk_availability,docker_storage,package_availability,docker_image_availability
openshift_repos_enable_testing=True
openshift_image_tag=latest
containerized=true
enable_excluders=false

[masters]
<master_ip>

[etcd]
<master_ip>

[nodes]
<master_ip> openshift_node_labels="{'region': 'infra','zone': 'default'}" openshift_schedulable=true
<node_ip> openshift_node_labels="{'region': 'infra','zone': 'default'}" openshift_schedulable=true
```

##### Expected Results
I think in case of `containerized` deployment we need just skip `Fail if rpm version and docker image version are different` check because we do not really use any `rpms`

##### Observed Results
Deployment failed on error

```
Play:     Ensure the requested version packages are available.
     Task:     Fail if rpm version and docker image version are different
     Message:  The task includes an option with an undefined variable. The error was: 'openshift_rpm_version' is undefined
               
               The error appears to have been in '/root/openshift-ansible/roles/openshift_version/tasks/masters_and_nodes.yml': line 7, column 5, but may
               be elsewhere in the file depending on the exact syntax problem.
```

##### Additional Information

* CentOS Linux release 7.4.1708 (Core)
I can overcome this problem by adding

```
when:
    - not openshift_is_atomic | bool
    - not openshift_is_containerized | bool
```
to the task `roles/openshift_version/tasks/masters_and_nodes.yml`
I can create a PR, but first of all, I want to be sure that I did not miss some additional parameter and it is real issue.

**Comment by sosiouxme** [comment]
`  when: not openshift_is_atomic | bool` is already set on the block.
For containerized, although you're not using RPMs for the components, you're still using RPMs for at least docker and its dependencies, and last I checked, had to set up the excluder RPMs to ensure the right docker for the OCP version. I'm not sure where that stands today; just saying there might still be a reason to keep this for containerized.

**Comment by cynepco3hahue** [comment]
@sosiouxme You absolutely right about `docker-excluder` package, it the reason why I added `enable_excluders=false`.
But from my perspective, it can be useful to deploy `latest` openshift build without the need to clone `OpenShift` repository and make `latest` rpms from it.
Maybe skip this check in case of `containerized` deployment does not the good solution, but at least we can skip it when `openshift_disable_check=...,package_availability,...`.
What do you think?

**Comment by michaelgugino** [comment]
openshift_rpm_version has been removed in master.

**Comment by cynepco3hahue** [comment]
@michaelgugino A lot of thanks, now `containerized` deployment works fine.

**Comment by cynepco3hahue** [comment]
@michaelgugino Hi, I again encounter the same problem with `containerized` I believe it because of
https://github.com/openshift/openshift-ansible/pull/7124.

**Comment by michaelgugino** [comment]
@cynepco3hahue Are you setting openshift_release in your inventory?

I believe you will encounter this error if you have openshift_pkg_version set, have multiple openshift repos enabled, and don't specify openshift_release.

**Comment by cynepco3hahue** [comment]
@michaelgugino Thanks for the fast answer, I run deployment with the inventory from https://github.com/openshift/openshift-ansible/issues/6756#issue-289315765
I think the problem that I set container versions to latest `openshift_image_tag=latest` but CentOS repository has only 3.7 packages.
We need OpenShift deployment for testing purposes under our CI environment, but the only way to get latest RPM's it to clone OpenShift repository and make it, so I wanted to use `containerized` deployment that gives you the possibility to get latest images from docker hub, but I fall on RPM check from this file https://github.com/openshift/openshift-ansible/pull/7124/files#diff-43777e49394f32a80ac73f42c351be9b

**Comment by michaelgugino** [comment]
@cynepco3hahue If you don't want to pull down rpms and only want to access the latest containers, you can deploy on atomic host.  This might be a better option for you.

I don't recommend using openshift_image_tag=latest because the 3.9 images that are currently out have not been released and are still in development.  That is unless you want a development version.

**Comment by cynepco3hahue** [comment]
@michaelgugino We run a vagrant machine with the CentOS7 image for k8s and also for OC deployment, I do not sure that we want to use another image with atomic only for OC case.
Some things fixed only under k8s 1.9 so that the reason why we run testing via OC 3.9.
IMHO it looks strange that OC has latest images under docker hub, but you can not install it because of RPM's limitations

**Comment by michaelgugino** [comment]
@cynepco3hahue I agree, the images being available for 3.9 is somewhat misleading.  But those images are currently in-development, they're not intended for general consumption yet (It was a recent change to start doing this, it may have been announced on the dev or user list).

Since the software isn't officially released yet, there aren't any packages being built by the various distros.  You can build the packages yourself, but that would be quite involved and I wouldn't recommend it.

In the mean time, if you want to test out 3.9 and see if it address whatever issues you have, I recommend using atomic.  That's an all-container based deploy that doesn't depend on any openshift-specific rpms.

**Comment by vrutkovs** [comment]
>I do not sure that we want to use another image with atomic only for OC case.

It should be possible to install a containerized Origin in system containers on a plain CentOS image

**Comment by cynepco3hahue** [comment]
@vrutkovs Can you please clarify your proposal? What do you mean by `in system containers`?

**Comment by vrutkovs** [comment]
@cynepco3hahue I haven't tried this for a long time, but it should work:

* Install bare CentOS/Fedora/RHEL
* in openshift-ansible inventory set:
  - `openshift_use_system_containers=True`
* Run installation

This would setup a few additional utils to run [system containers](https://www.projectatomic.io/blog/2016/09/intro-to-system-containers/) and would not require openshift RPM, as it would use docker images to run master and nodes

**Comment by cynepco3hahue** [comment]
@vrutkovs Thanks, will check it and will update the issue with results.

**Comment by cynepco3hahue** [comment]
@vrutkovs I tried to run deployment on `openshift-ansible` master with inventory
```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
ansible_ssh_pass=vagrant
deployment_type=origin
openshift_deployment_type=origin
openshift_clock_enabled=true
openshift_master_identity_providers=[{'name': 'allow_all_auth', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]
openshift_disable_check=memory_availability,disk_availability,docker_storage,package_availability,docker_image_availability
openshift_repos_enable_testing=True
openshift_image_tag=latest
containerized=true
enable_excluders=false
openshift_use_system_containers=true

[masters]
master openshift_ip=$master_ip

[etcd]
master openshift_ip=$master_ip

[nodes]
master openshift_node_labels="{'region': 'infra','zone': 'default'}" openshift_schedulable=true openshift_ip=$master_ip
node0 openshift_node_labels="{'region': 'infra','zone': 'default'}" openshift_ip=$node0
```
but I still have the same issue with RPM's 
```
TASK [openshift_version : Fail if rpm version and docker image version are different] ***
==> master: fatal: [node0]: FAILED! => {"changed": false, "msg": "OCP rpm version 3.7.0 is different from OCP image version latest"}
==> master:     to retry, use: --limit @/root/openshift-ansible/playbooks/deploy_cluster.retry
```

**Comment by vrutkovs** [comment]
Sounds like you need `openshift_version=3.9`

**Comment by cynepco3hahue** [comment]
@vrutkovs Yep it the exact reason why I opened this issue, OpenShift does not have repository with latest RPM's that can be used from different Linux distributives(Fedora, CentOS, RHEL), so in case if you will need to deploy latest openshift for some reason, you can do it without clone OpenShift repository and make RPM's by yourself. I wanted to avoid it with `containerized` deployment, but `containerized` deployment also has some RPM's dependencies. So I just want to have some ansible variable that will skip all RPM's check.

**Comment by vrutkovs** [comment]
Currently RHEL, CentOS and Fedora (see https://bodhi.fedoraproject.org/updates/FEDORA-2018-2bfbd27a0b) have 3.9 packages, 3.10 can be installed without RPMs

@cynepco3hahue, do you mind if I close this one?

**Comment by cynepco3hahue** [comment]
@vrutkovs Really cool, thx it will solve my problems and you can close the issue.

**Comment by cynepco3hahue** [comment]
@vrutkovs I checked CentOs repos and still can not see new 3.9 packages http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/
Do I miss something or I need to use another repo?

**Comment by vrutkovs** [comment]
See https://cbs.centos.org/repos/paas7-openshift-origin39-candidate/x86_64/os/Packages/

**Comment by cynepco3hahue** [comment]
@vrutkovs Thanks again :smile:
