### ISSUE TITLE
[AWS Provisioning] master-internal elb being deployed with scheme: internet-facing

### ISSUE THREAD

**Issue by mazzystr** [openshift/openshift-ansible#6766]
#### Description

master-internal elb being deployed with scheme: internet-facing

##### Version

* Your ansible version per `ansible --version`
```
$ git describe
openshift-ansible-3.9.0-0.20.0-9-g3a7f19924
$ ansible --version
ansible 2.4.2.0
  config file = /home/ccallega/git/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/ccallega/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### Steps To Reproduce
1. ansible-playbook playbooks/aws/openshift-cluster/provision_install.yml -e @playbooks/aws/openshift-cluster/provisioning_vars.yml

##### Expected Results
I expect the \<clusterid\>-master-internal elb to have to be deployed as { "Scheme": "internal" }

##### Observed Results
\<clusterid\>-master-internal elb is deployed as { "Scheme": "internet-facing" }

##### Additional Information

**Comment by kwoodson** [comment]
@mazzystr, thanks for reporting and fixing.
