### ISSUE TITLE
Invalid logging version

### ISSUE THREAD

**Issue by marekjelen** [openshift/openshift-ansible#6781]
When the inventory specifies logging version using

```
openshift_logging_image_version=v3.7.0
```

the playbooks try to deploy `oauth-proxy` 

https://hub.docker.com/r/openshift/oauth-proxy/tags/ 

using the same version, which fails

```
Failed to pull image "docker.io/openshift/oauth-proxy:v3.7.0": rpc error: code = 2 desc = Tag v3.7.0 not found in repository docker.io/openshift/oauth-proxy
```

**Comment by vrutkovs** [comment]
Seems `openshift_logging_elasticsearch_proxy_image_version` should not use `openshift_logging_image_version` and use a separate var for that

**Comment by anpingli** [comment]
@pgeorgiev333 
The playbook will use the default registry registry.access.redhat.com. the origin images aren't in this registry. 


Anping Li 

----- Original Message -----

**Comment by vrutkovs** [comment]
>Will this work:

These are default prefixes openshift uses, so there is no need to override it by setting custom `openshift_logging_elasticsearch_proxy_image_prefix` and `openshift_logging_image_prefix`

**Comment by kahootali** [comment]
I am also facing the same issue, setting openshift_logging_image_version=v3.11 sets the version for oauth_image to 3.11 as well? Did anyone find a way to set oauth_image_version?

**Comment by anpingli** [comment]
openshift_logging_elasticsearch_proxy_image=registry.access.redhat.com/openshift3/oauth-proxy:latest

**Comment by anpingli** [comment]
@vrutkovs  openshift_logging_xxx_image_prefix, openshift_logging_xxx_image_version are deprecated from v3.10
