### ISSUE TITLE
Missing roles, rolebinding, serviceaccount for every new project  after upgrading from 3.6 to 3.7

### ISSUE THREAD

**Issue by davistran86** [openshift/openshift-ansible#6787]
I'm using multi master cluster with origin 3.6
I upgraded to 3.7 using command

```
ansible-playbook -i <path/to/inventory/file> \
    </path/to/upgrade/playbook>
```

After sucess upgrading it to 3.7 I got errors and cannot deploy new project because of missing role binding. Every new project created is missing rolebinding, roles, default serviceaccount

```
oc get rolebinding.rbac -n test-role
**No resources found.**
```

![image](https://user-images.githubusercontent.com/23651625/35204480-f54d8d5e-ff60-11e7-8ad8-0fad97a502e7.png)

I also tried commands below but nothing works:

```
# oadm policy reconcile-cluster-roles \
    --additive-only=true \
    --confirm

# oadm policy reconcile-cluster-role-bindings \
    --exclude-groups=system:authenticated \
    --exclude-groups=system:authenticated:oauth \
    --exclude-groups=system:unauthenticated \
    --exclude-users=system:anonymous \
    --additive-only=true \
    --confirm

```

**Comment by enj** [comment]
/close

Handled in https://github.com/openshift/origin/issues/18206
