### ISSUE TITLE
lack of 3.7.1 rpm's blocks containarized upgrade

### ISSUE THREAD

**Issue by MansM** [openshift/openshift-ansible#6788]
#### Description

Currently the v3.7.1 rpm's are not available on the centos mirros. These are used to verify of the 3.7.1 version. But as I dont used the rpm's but a containerized install this should imo not be a reason to prevent upgrading

##### Version
3.7.0-3.7.1
ansible 2.4.2.0

**Comment by lvlie** [comment]
+1

**Comment by scorputty** [comment]
+1

**Comment by hufon** [comment]
+1

**Comment by oleio** [comment]
+1

how to resolve this problem ?

**Comment by vrutkovs** [comment]
I've updated my containerized install on Fedora Atomic using `master` branch. This should work for CentOS containerized installs - and for `release-3.7` branch.

What's the error message?

**Comment by DanyC97** [comment]
@vrutkovs the OP raised this issue due to 

> Currently the v3.7.1 rpm's are not available on the centos mirros

Looking [here](http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/) i don't see the 3.7.1 rpms, am i missing s'thing ?

**Comment by DanyC97** [comment]
@MansM can this issue be closed now that the rpm is out ?

**Comment by MansM** [comment]
Yeah
