### ISSUE TITLE
Split deploy_cluster.yml up into two pieces, call those from cloud provision

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#6804]
Currently GCP and AWS are having to copy contents out of deploy_cluster.yml because they have to accept nodes before running hosted components.  The easiest short term split is to break deploy_cluster into two pieces:

1. control_plane.yml - everything up to and including openshift-node (master nodes have to be configured)
2. components.yml - everything after openshift-node that relates to configuring a control plane, stuff that eventually will be further decomposed into smaller pieces

@michaelgugino @kwoodson this is now blocking me after the web-console changes went in - I do not want to have to recreate what aws/openshift-cluster/install.yml is doing (copying each sub playbook in).

**Comment by smarterclayton** [comment]
https://github.com/openshift/openshift-ansible/pull/6541/commits/75a4f91a87762a22271dba5021309bae194289cd is one way about it - I'm not that opinionated though as long as we can completely split "below control plane" and "above control plane" (that's going to be a very strongly enforced boundary, and we'll be pulling things out of the lower part to keep it smaller)

**Comment by michaelgugino** [comment]
@smarterclayton we consider the 'control-plane' to be masters and etcd hosts during upgrades.

I don't know what you mean by this statement:
> Currently GCP and AWS are having to copy contents out of deploy_cluster.yml because they have to accept nodes before running hosted components.

**Comment by smarterclayton** [comment]
Resolved, the PR split the two sub parts into includable private snippets
