### ISSUE TITLE
Why aren't prerequisites installed as part of main playbooks?

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#6809]
The addition of prerequisites.yml as a playbook (https://github.com/openshift/openshift-ansible/pull/6530) complicates other flows, like golden images.  If everyone has to run both, we should only need one.  If the core reason for the gap is the openshift_facts module (and its inability to run without pyyaml present) we should fix that in the main code.

@sdodson @michaelgugino this broke the GCP flow and we didn't notice for a few weeks.  I had to work around it by installing pyyaml in the base golden image, which is hacky to the extreme.

**Comment by michaelgugino** [comment]
In 3.7, users had to manually install docker and a handful of other packages before running the installer.  prerequisites.yml now does this.

Additionally, we used to instruct users to setup docker storage on their own.  We do this now in prerequisites.yml if they desire.  We don't want to run this code multiple times.

**Comment by sdodson** [comment]
The PyYAML dep we need to fix. https://github.com/openshift/openshift-ansible/pull/6708 was my hasty attempt at that, @michaelgugino do you mind taking another look at fixing that problem?

If there's a way we can fix the UX to get back to a single playbook execution that'd be my preference but I don't think we're going to sort that out before 3.9.

**Comment by michaelgugino** [comment]
I contend that there was never a 'single' playbook experience due to the fact that users had to manually install and configure items before running the installer.  However, I think with the recent changes to openshift_version and cleaning up some of the items in init/main.yml, I can copy the pattern we have for the scaleup plays in 3.10.

**Comment by DanyC97** [comment]
fair point @michaelgugino , i'll give it a try with branch 3.9 and see if it works ( i know in the past this wasn't the case -ie openshift-ansible branch should have match the origin one)
