### ISSUE TITLE
Documentation needs to reflect refactoring done 

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [openshift/openshift-ansible#6828]
#### Description

Documentation still refers to playbooks/byo/config.yml.
But, it is removed and it seems playbooks/deploy_cluster.yml should be used for setting up cluster.

Please update documentation to reflect this.

git commit a77205f5b49cc06b18c2d881512f9ec25e347a75

**Comment by kwoodson** [comment]
Due to recent refactoring our documentation is still pointing users at `/playbooks/byo/config.yml`.  We need to update this to `/playbooks/deploy_cluster.yml`.

**Comment by kwoodson** [comment]
I believe this is being addressed here: https://github.com/openshift/openshift-docs/pull/7274

**Comment by dburugupalli** [comment]
is this still needs to be addressed. I would like to take up.

**Comment by mtnbikenc** [comment]
Already addressed.
