### ISSUE TITLE
OpenShift ansible should allow more than 251 addresses

### ISSUE THREAD

**Issue by mbruzek** [openshift/openshift-ansible#6829]
#### Description

We are using the OpenStack version of the openshift-ansible installer and found that the cidr range of `\24` is hardcoded in the heat stack configuration. This only allows 251 (254-3) addresses in the range and our scaling goals are larger than 251.

The code that handles this appears to be here:
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_openstack/templates/heat_stack.yaml.j2#L81-L96

##### Version

* Your ansible version per `ansible --version`:
```
            "ansible 2.4.2.0", 
            "  config file = /home/cloud-user/ansible.cfg", 
            "  configured module search path = [u'/home/cloud-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']", 
            "  ansible python module location = /usr/lib/python2.7/site-packages/ansible", 
            "  executable location = /usr/bin/ansible", 
            "  python version = 2.7.5 (default, Dec  8 2017, 16:39:59) [GCC 4.8.5 20150623 (Red Hat 4.8.5-25)]"
```

* The output of `git describe`: openshift-ansible-3.9.0-0.21.0-46-g7ad419c

* The output of `rpm -q atomic-openshift-utils openshift-ansible`:

```
            "atomic-openshift-utils-3.9.0-0.21.0.git.0.296d767.el7.noarch", 
            "openshift-ansible-3.9.0-0.21.0.git.0.296d767.el7.noarch"
```

##### Steps To Reproduce
1. Deploy an OpenShift cluster on OpenStack.
2. Try to scale above 251 virtual machines.
3. Observe you run out of addresses in the subnet.

##### Expected Results

I propose to make the subnet cidr configurable so we can get a larger range of IP addresses.
http://www.subnet-calculator.com/cidr.php
```
openshift_openstack_subnet_cidr: "192.168.7.1/22"
openshift_openstack_subnet_start: "192.168.4.0"
openshift_openstack_subnet_end: "192.168.7.255"
```

The /24 subnet is hardcoded and this limits OpenStack useres to 251 VMs in the OpenShift cluster. This is very limiting and needs to be expanded.

**Comment by tomassedovic** [comment]
Thanks for the bug report!

This is quite reasonable and switching to CIDR would have been my suggestion as well.

**Comment by tzumainn** [comment]
@mbruzek @tomassedovic Would this PR fit your needs?

https://github.com/openshift/openshift-ansible/pull/7002

**Comment by tzumainn** [comment]
@mbruzek Oh, whoops, didn't realize you had your own PR ready! Quick question: can the subnet prefix be different for these added parameters?

**Comment by mbruzek** [comment]
@tzumainn As we discussed in #shiftstack for CIDRs less than 24 the prefix is different and this causes a problem with the current implementation. For example: 192.168.99.0/20 covers a range of 192.168.96.0 - 192.168.111.255 so the prefix method is not valid.
