### ISSUE TITLE
Tag v3.7 not found in repository docker.io/openshift/oauth-proxy

### ISSUE THREAD

**Issue by edsonmarquezani** [openshift/openshift-ansible#6861]
Logging deployment fails in Origin 3.7, because `logging-es-data-master` Pod uses an image/tag which doesn't exist.

![image](https://user-images.githubusercontent.com/11199127/35362695-883023c8-014d-11e8-9b51-ce34b415b066.png)

Playbook version: 3.7.25-1

Ansible inventory:
```
openshift_logging_image_version=v3.7
openshift_logging_install_logging=false
openshift_logging_es_pvc_dynamic=true
openshift_logging_es_pvc_size="64G"
openshift_logging_es_cluster_size=1
openshift_logging_fluentd_nodeselector={"logging":"true"}
openshift_logging_es_nodeselector={"role":"infra"}
openshift_logging_kibana_nodeselector={"role":"infra"}
openshift_logging_curator_nodeselector={"role":"infra"}
openshift_logging_use_ops=false
openshift_logging_purge_logging=false
openshift_logging_kibana_hostname=logs.internal.XXXX.com
openshift_logging_master_url=https://master.XXXX.com:8443
openshift_logging_master_public_url=https://master.XXXX.com:8443
openshift_logging_curator_default_days=60
```

**Comment by fraenkel** [comment]
you need to set the proxy version, openshift_logging_elasticsearch_proxy_image_version
The default values don't quite work as you start setting user defined ones.

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging_elasticsearch/tasks/main.yaml#L29

**Comment by edsonmarquezani** [comment]
@fraenkel Ok. Thanks.

**Comment by kahootali** [comment]
I am also facing the same issue, setting openshift_logging_image_version=v3.11 sets the version for oauth_image to 3.11 as well? Did anyone find a way to set oauth_image_version?
