### ISSUE TITLE
prerequisites.yml can't transition from device mapper to overlay2

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#6864]
If docker is already installed on the base image, the GCP (and AWS, I'm assuming) installers don't properly configure overlay:

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_gce/2286/

If you look at the logs we call "configuring for overlay2" in the node bootstrap setup when we bake the image, but later on the instance is still on device mapper.

Looking at the logs, I see:

```
● docker-storage-setup.service - Docker Storage Setup
   Loaded: loaded (/usr/lib/systemd/system/docker-storage-setup.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2018-01-25 04:11:13 UTC; 3min 56s ago
 Main PID: 2233 (code=exited, status=1/FAILURE)

Jan 25 04:11:13 ci-claytontest2-build-image-instance systemd[1]: Starting Docker Storage Setup...
Jan 25 04:11:13 ci-claytontest2-build-image-instance container-storage-setup[2233]: INFO: Volume group backing root filesystem could not be determined
Jan 25 04:11:13 ci-claytontest2-build-image-instance container-storage-setup[2233]: ERROR: Device /dev/sda is already partitioned and cannot be added to volume group docker_vg
Jan 25 04:11:13 ci-claytontest2-build-image-instance systemd[1]: docker-storage-setup.service: main process exited, code=exited, status=1/FAILURE
Jan 25 04:11:13 ci-claytontest2-build-image-instance systemd[1]: Failed to start Docker Storage Setup.
Jan 25 04:11:13 ci-claytontest2-build-image-instance systemd[1]: Unit docker-storage-setup.service entered failed state.
Jan 25 04:11:13 ci-claytontest2-build-image-instance systemd[1]: docker-storage-setup.service failed.
```

I would expect the presence of the overlay2 configuration value to force us into the mode where this is not broken.

**Comment by smarterclayton** [comment]
@kwoodson who is doing the overlay setup?

**Comment by smarterclayton** [comment]
Basically, what is the correct docker-storage-setup in order to have docker configured on the existing device.

**Comment by smarterclayton** [comment]
Also, if our setup is assuming we're going to configure docker-storage-setup for overlay to have a unique block device, that is not a correct assumption.

**Comment by smarterclayton** [comment]
No, not user error - https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/6626/test_pull_request_openshift_ansible_extended_conformance_gce/61/ failed and this is using the latest checked in code.  So I think this is a mismatch between what the image needs and what is in the prerequisites code.

**Comment by smarterclayton** [comment]
I think the configuration we want for overlay on GCP is "do nothing, but set the correct docker storage driver".

**Comment by kwoodson** [comment]
@smarterclayton,

The history here is that inside of openshift-ansible there was never a path that calls docker-storage-setup.  The expectation was that a user would pre-setup their storage before arriving to the install.  This protected openshift-ansible from wiping docker drives during install or update.

Having said this, we now are in a place where we are providing provisioning and need to provide a path where docker storage driver is setup.  During the AWS image build process this occurs by first setting up the `/etc/sysconfig/docker-storage-setup` file and then proceeding to install docker.  Upon docker's initialization (first start up), the storage driver is correctly configured.  This happens here:
https://github.com/openshift/openshift-ansible/blob/master/playbooks/prerequisites.yml#L22-L24

By specifying the following variables:
```
container_runtime_docker_storage_type: overlay2
container_runtime_docker_storage_setup_device: /dev/xvdb
```

Now that brings us to your issue.  What do we want to do when the user/customer arrives with a pre-configured docker storage?

Few options available:
- User uninstalls docker and arrives without a storage driver
- User passes variable(s) that performs the docker-storage-setup which is known to be **destructive**
- Create a role (@mbarnes has a migrate role) to move to the docker storage driver to overlay
- Other suggestions?

**Comment by smarterclayton** [comment]
container_runtime_docker_storage_setup_device: /dev/xvdb is incorrect for GCP because we aren't going to use a device at all.  

I think there are two undercovered cases:

1. I don't want to do any storage setup, but I do want to "reset" back to overlay (users coming from dev mapper to overlay on upgrades, images that had docker on them)
2. I do want to use docker-storage-setup, but I don't want to provision devices (I just want to reset everything to "no special devices", and then use overlay)

**Comment by smarterclayton** [comment]
Destructive would work for 2 and 1, but it might be a foot shooting thing

**Comment by smarterclayton** [comment]
I removed docker from the base image.  At this point, I need a way to tell prerequisites not to use docker storage setup to configure a device (I just want to use the root filesystem), but to correctly configure overlay2.

Arguably, the following should do that:

```
container_runtime_docker_storage_type: overlay2
container_runtime_docker_storage_setup_device: 
```

which is: "use overlay2, don't configure a device".  If we want to have a different second variable I'm fine, or to make device default to empty by default (probably reasonable for most users), I'm ok with that.

I'm broken until we fix this.

**Comment by kwoodson** [comment]
@smarterclayton,  can you try with this PR? https://github.com/openshift/openshift-ansible/pull/6888

**Comment by smarterclayton** [comment]
Looks resolved.
