### ISSUE TITLE
openshift_management CFME support is commented out (always installs ManageIQ)

### ISSUE THREAD

**Issue by elad661** [openshift/openshift-ansible#6873]
cc @sdodson 

openshift_management only installs ManageIQ at the moment, even if you ask it to install CFME.
This is relevant for the current beta CFME release, and soon for GA.

Relevant lines:
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_management/vars/main.yml#L33-L40

**Comment by elad661** [comment]
This might've been solved by https://github.com/openshift/openshift-ansible/commit/53ed4ededbbac3ca0095051885aecd0674fbf867 but I haven't had the chance to test yet.

**Comment by sdodson** [comment]
Yeah this should've been fixed via #6925
