### ISSUE TITLE
Remove logrotate configs from AWS launch

### ISSUE THREAD

**Issue by twiest** [openshift/openshift-ansible#690]
The [AWS](https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/openshift-cluster/tasks/launch_instances.yml#L163) launch playbook contains logrotate configs.

We need to remove them as this isn't the right place to configure them. They should be configured in a config loop, separate from launch.

**Comment by abutcher** [comment]
Do you see any problem with configuring logrotate by default (and in the same way, everywhere) or keep the configs confined to aws/gce? @twiest @detiber @sdodson

**Comment by detiber** [comment]
I think we should allow for logrotate to be configured everywhere, but toggleable...  For Origin/Enterprise I'm not completely convinced we'd want to configure a user's logrotate config on them.

**Comment by twiest** [comment]
Then maybe we should just change this issue to "remove log rotate as a default configured item" ?

I'm ok with that. For online, we have lot of extra stuff we'll be configuring in addition to what's provided in the basic install, so we'll configure logrotate the same way we configure the rest of the extra things.

So it's really up to you guys if we want this included in the base set of configs or not.

**Comment by sdodson** [comment]
+1 to removing it all together. If we add an openshift specific log either via ansible or in the product itself we can re-introduce some logrotation defaults for that specific log file.

**Comment by abutcher** [comment]
:+1:

**Comment by twiest** [comment]
@sdodson @abutcher @detiber ok, I've updated this issue. I'll also remove the logrotate configs from my GCE PR so that GCE just never has that section.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
