### ISSUE TITLE
openshift_web_console/tasks/install.yml: pointing to static domain

### ISSUE THREAD

**Issue by spookiej** [openshift/openshift-ansible#6914]
#### Description

There is a bug in the master branch to verify if the console is working, it is always going to fail as it is pointing to some other domain, and not your own.

> https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_web_console/tasks/install.yml
> 
This is the task in questions
```
- name: Verify that the web console is running
  command: >
    curl -k https://webconsole.openshift-web-console.svc/healthz
  args:
    # Disables the following warning:
    # Consider using get_url or uri module rather than running curl
    warn: no
  register: console_health
  until: console_health.stdout == 'ok'
  retries: 120
  delay: 1
  changed_when: false

```
I'm not exactly sure what var needs to go in here, but I presume it is your console FQDN and the Port it is listening on. I edited the local file to the below in order to get past this step.
```
- name: Verify that the web console is running
  command: >
    curl -k https://"{{ openshift_master_cluster_hostname }}":8443/healthz
  args:
    # Disables the following warning:
    # Consider using get_url or uri module rather than running curl
    warn: no
  register: console_health
  until: console_health.stdout == 'ok'
  retries: 120
  delay: 1
  changed_when: false
```

**Comment by spookiej** [comment]
Closed issue, after doing some more reading I don't believe it is an issue.

Stemmed from a proxy issue, I believe.

**Comment by missnebun** [comment]
Well this is not a proxy issue ... there is a variable on the openshift_web_console_nodeselector: {"node-role.kubernetes.io/master":"true"} but if you have dedicated masters Scheduling is Disabled so the web-console will never get online.

**Comment by spookiej** [comment]
Ok great, thanks for the help I'll try with openshift_schedulable=true for the master node.
