### ISSUE TITLE
origin-web-console nodeSelector makes it unschedulable by default

### ISSUE THREAD

**Issue by sjenning** [openshift/openshift-ansible#6930]
https://github.com/openshift/openshift-ansible/pull/6882 set the web-console nodeSelector to `node-role.kubernetes.io/master: true`.  The master is cordoned by default.  Thus the web-console fails to schedule unless the default `openshift_web_console_nodeselector` is overridden or the master is manually uncordoned.

https://github.com/openshift/openshift-ansible/pull/6882#commitcomment-27173327
https://github.com/openshift/openshift-ansible/issues/6912#issuecomment-361026002

Is there a reason this pod must run on the master?

@sdodson @spadgett @smarterclayton

**Comment by spadgett** [comment]
I'll defer to @smarterclayton on the why, but the intent is for the master to be schedulable for components like the web console. There was a bug where it wasn't happening for new installs, only upgrades.

See #6932 and #6849
https://bugzilla.redhat.com/show_bug.cgi?id=1535673

/assign @vrutkovs

**Comment by vrutkovs** [comment]
This should be resolved by https://github.com/openshift/openshift-ansible/pull/6932
