### ISSUE TITLE
question - recommended way to upgrade from 3.7.0 to 3.7.1

### ISSUE THREAD

**Issue by cameronbraid** [openshift/openshift-ansible#6931]
What is the recommended way to upgrade from 3.7.0 to 3.7.1 ?

Is it safe to re-run the playbooks/byo/config.yml playbook after changing inventory openshift_release to 3.7.1, or should an upgrade playbook be used ?

**Comment by michaelgugino** [comment]
@cameronbraid I believe we recommend using the upgrade playbook.

**Comment by mshutt** [comment]
Is this still the recommendation?  We're trying to do this now to take a fresh 3.7.0 containerized Origin to 3.7.1 and we're getting hung up with the etcd upgrade as this playbook seems to have only been written to handle the registry.access.redhat.com/rhel7/etcd image with the tagging of like :3.2.7 etc... vs. the f26/etcd image (which does not have any such tags).  Ultimately, we fail with the following:
```
TASK [etcd : Pull new etcd image] **********************************************
Wednesday 21 March 2018  19:39:52 +0000 (0:00:00.136)       0:05:22.015 *******
fatal: [REDACTED]: FAILED! => {"changed": true, "cmd": ["docker", "pull", "registry.fedoraproject.org/f26/etcd:3.2.7"], "delta": "0:00:00.951876", "end": "2018-03-21 19:39:53.178839", "msg": "non-zero return code", "rc": 1, "start": "2018-03-21 19:39:52.226963", "stderr": "Error: image f26/etcd:3.2.7 not found", "stderr_lines": ["Error: image f26/etcd:3.2.7 not found"], "stdout": "Trying to pull repository registry.fedoraproject.org/f26/etcd ... \nPulling repository registry.fedoraproject.org/f26/etcd", "stdout_lines": ["Trying to pull repository registry.fedoraproject.org/f26/etcd ... ", "Pulling repository registry.fedoraproject.org/f26/etcd"]}
```

It seems unavoidable given the looping that is done in:

`playbooks/common/openshift-cluster/upgrades/etcd/upgrade.yml`

**Comment by mshutt** [comment]
@michaelgugino 

`playbooks/common/openshift-cluster/upgrades/etcd/upgrade_image_members.yml` gets iterated with a different `etcd_upgrade_version` over and over until the version is higher than that which is installed.  The rpm version of the `f26/etcd` container from fedoraproject is detected as:

```
TASK [debug] *******************************************************************
Wednesday 21 March 2018  19:39:32 +0000 (0:00:00.130)       0:05:02.779 *******
ok: [etcd1] => {
    "msg": "Etcd containerized version 3.1.9 detected"
}
ok: [etcd2] => {
    "msg": "Etcd containerized version 3.1.9 detected"
}
ok: [etcd3] => {
    "msg": "Etcd containerized version 3.1.9 detected"
}
```

In the task `Determine etcd version` block `Record containerized etcd version (docker)` in the same `playbooks/common/openshift-cluster/upgrades/etcd/upgrade.yml`

**Comment by mshutt** [comment]
Basically, as deployed by the default openshift-ansible release-3.7 (latest), the etcd container image will be defined in `/etc/systemd/system/etcd_container.service` as `registry.fedoraproject.org/f26/etcd` with no tag at all...  The upgrade play requires that a tag be applied here:

```
- name: Get current image
  shell: "grep 'ExecStart=' {{ etcd_service_file }} | awk '{print $NF}'"
  register: current_image

- name: Set new_etcd_image
  set_fact:
    new_etcd_image: "{{ current_image.stdout | regex_replace('/etcd.*$','/etcd:' ~ r_etcd_upgrade_version ) }}"

- name: Pull new etcd image
  command: "docker pull {{ new_etcd_image }}"

- name: Update to latest etcd image
  replace:
    dest: "{{ etcd_service_file }}"
    regexp: "{{ current_image.stdout }}$"
    replace: "{{ new_etcd_image }}"

**Comment by mshutt** [comment]
It looks like this variable might be what we're looking for.  I do not see it in any documentation, but it only occurs the one time in the entire tree for release-3.7

```
- name: Perform etcd upgrade
  include: ./upgrade.yml
  when: openshift_etcd_upgrade | default(true) | bool
```

**Comment by mshutt** [comment]
Indeed, that worked... :/

**Comment by DanyC97** [comment]
@mshutt so is just a docs issue, correct ?

**Comment by mshutt** [comment]
It seems as such!

**Comment by mshutt** [comment]
That is unless the upgrade plays are supposed to upgrade etcd for openshift
origin deployments.

We also noticed that the upgrade plays dont kick off the
openshift_loadbalancer role which can be done either by running the
config.yml playbook from the playbooks/byo/openshift_loadbalancer dir or by
rerunning the full byo/config.yml after the upgrade.
