### ISSUE TITLE
ec2_instance_facts taking long time to get the private_ip_address

### ISSUE THREAD

**Issue by pradeep-gdit** [openshift/openshift-ansible#6950]
I am trying to get the ec2_instance_facts of my ec2 instances immedialy after creating the instances. But always it takes aroung 15 to 30 min to get the factors such private_ip_address. 
I am using below ansible version

Here is the error I am getting

    fatal: [10.247.129.147]: FAILED! => {"msg": "The task includes an option with an undefined 
    variable. The error was: 'dict object' has no attribute 'private_ip_address'\n\nThe error appears to 
    have been in '/ansible/roles/test/tasks/test.yml': line 16, column 3, but may\nbe elsewhere in the file 
    depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- debug:\n  ^ 
    here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has 
    no attribute  'private_ip_address'"}

ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

To re-produce this issue, please create a ec2 instance and execute the ansible script

     ---
     - name: check ec2 factor
          local_action:
          module: ec2_instance_facts
          region: us-east-1
          filters:
               "tag:Name" : "dev-server-01"
           register: ec2_info
     - debug:
          msg: "{{ec2_info.instances[0].private_ip_address}}"
          #   msg: "{{item.private_ip_address}}"
          #  with_items: "{{ec2_info.instances}}"`

is there any way i can use the module immediately after creating the instances.

**Comment by Luk3rson** [comment]
Hey @pradeep-gdit,

I am sure that you solve this issue but after I create an instance I wait for the public IP to come up:
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22 
        state: started 
      with_items: "{{ ec2.instances }}"

I hope it helps!
