### ISSUE TITLE
Changing default docker daemon behaviour regarding log

### ISSUE THREAD

**Issue by ejemba** [openshift/openshift-ansible#696]
From this issue https://github.com/kubernetes/kubernetes/issues/15478, we concluded that a good default log policy should be enforced by modifying docker daemon options regarding --log-opt and --log-driver. 

Since openshift does not use Salt, this means we need to modify openshift-ansible in order to change default options of the docker daemon. And possibly make this configurable.

**Comment by abutcher** [comment]
@brenton This was added in #734 and can be closed
