### ISSUE TITLE
On Fedora 26 and 27, Ensure openshift-ansible installer package deps are installed fail on node

### ISSUE THREAD

**Issue by adelton** [openshift/openshift-ansible#6968]
#### Description

On a setup with one master and one node on Fedora 26 and Fedora 27, the openshift-ansible/playbooks/prerequisites.yml fails.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

```
# python3 /usr/bin/ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.4 (default, Jan 15 2018, 18:44:26) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

If you're operating from a **git clone**:

* The output of `git describe`

```
openshift-ansible-3.9.0-0.34.0-8-g26430dcbb
```

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

```
package atomic-openshift-utils is not installed
package openshift-ansible is not installed
```

##### Steps To Reproduce
1. python3 /usr/bin/ansible-playbook -e ansible_python_interpreter=/usr/bin/python3 -i ansible-inventory /path/openshift-ansible/playbooks/prerequisites.yml < /dev/ptmx

##### Expected Results
Describe what you expected to happen.

No error, the command passes.

##### Observed Results
Describe what is actually happening.

```
PLAY [Install packages necessary for installer] ********************************

TASK [Ensure openshift-ansible installer package deps are installed] ***********
Wednesday 31 January 2018  08:35:04 -0500 (0:00:00.043)       0:00:09.145 ***** 
ok: [master.example.com] => (item=iproute)
ok: [node.example.com] => (item=iproute)
ok: [master.example.com] => (item=python3-dbus)
ok: [master.example.com] => (item=python3-PyYAML)
ok: [node.example.com] => (item=python3-dbus)
FAILED - RETRYING: Ensure openshift-ansible installer package deps are installed (2 retries left).
ok: [node.example.com] => (item=python3-PyYAML)
FAILED - RETRYING: Ensure openshift-ansible installer package deps are installed (2 retries left).
FAILED - RETRYING: Ensure openshift-ansible installer package deps are installed (1 retries left).
FAILED - RETRYING: Ensure openshift-ansible installer package deps are installed (1 retries left).
failed: [master.example.com] (item=__omit_place_holder__2e20659f2a83edb31b3dbd2f8f8c37f0e605bec4) => {"attempts": 2, "changed": false, "item": "__omit_place_holder__2e20659f2a83edb31b3dbd2f8f8c37f0e605bec4", "msg": "one of the following is required: name,list,autoremove"}
ok: [master.example.com] => (item=yum-utils)
failed: [node.example.com] (item=__omit_place_holder__2e20659f2a83edb31b3dbd2f8f8c37f0e605bec4) => {"attempts": 2, "changed": false, "item": "__omit_place_holder__2e20659f2a83edb31b3dbd2f8f8c37f0e605bec4", "msg": "one of the following is required: name,list,autoremove"}
ok: [node.example.com] => (item=yum-utils)

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
node.example.com : ok=12   changed=0    unreachable=0    failed=1   
master.example.com : ok=14   changed=0    unreachable=0    failed=1   
localhost                  : ok=11   changed=0    unreachable=0    failed=0   


INSTALLER STATUS ***************************************************************
Initialization             : In Progress (0:00:36)

Wednesday 31 January 2018  08:35:31 -0500 (0:00:26.511)       0:00:35.657 ***** 
=============================================================================== 
Ensure openshift-ansible installer package deps are installed ---------- 26.51s
openshift_sanitize_inventory : Check for usage of deprecated variables --- 1.76s
Gathering Facts --------------------------------------------------------- 1.50s
Gathering Facts --------------------------------------------------------- 1.29s
openshift_sanitize_inventory : conditional_set_fact --------------------- 0.64s
Detecting Operating System from ostree_booted --------------------------- 0.58s
openshift_sanitize_inventory : conditional_set_fact --------------------- 0.52s
openshift_sanitize_inventory : Assign deprecated variables to correct counterparts --- 0.13s
openshift_sanitize_inventory : set_fact --------------------------------- 0.12s
set openshift_deployment_type if unset ---------------------------------- 0.11s
openshift_sanitize_inventory : include_tasks ---------------------------- 0.11s
initialize_facts set fact openshift_is_atomic and openshift_is_containerized --- 0.11s
openshift_sanitize_inventory : Standardize on latest variable names ----- 0.10s
openshift_sanitize_inventory : include_tasks ---------------------------- 0.08s
openshift_sanitize_inventory : Ensure that dynamic provisioning is set if using dynamic storage --- 0.08s
Evaluate oo_all_hosts --------------------------------------------------- 0.08s
openshift_sanitize_inventory : set_fact --------------------------------- 0.08s
openshift_sanitize_inventory : Abort when openshift_release is invalid --- 0.07s
assert atomic host docker version is 1.12 or later ---------------------- 0.07s
openshift_sanitize_inventory : Ensure clusterid is set along with the cloudprovider --- 0.07s
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)

```
Fedora release 26 (Twenty Six)
```

* Your inventory file (especially any non-standard configuration parameters)

```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_disable_check=memory_availability,docker_storage,disk_availability,package_version
openshift_repos_enable_testing=true

osm_cluster_network_cidr=10.128.0.0/14
openshift_portal_net=172.30.0.0/16
osm_host_subnet_length=9

openshift_router_selector='node-router=true'
openshift_registry_selector='node-registry=true'
template_service_broker_selector={"node-app": "true"}
openshift_web_console_nodeselector={"node-app": "true"}

openshift_master_identity_providers=[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]

[masters]
master.example.com

[etcd]
master.example.com

[nodes]
node.example.com openshift_schedulable=true openshift_node_labels="{ 'node-router': 'true', 'node-registry': 'true', 'node-app': 'true' }"

master.example.com
```

The output above is from Fedora 26, I see the same on Fedora 27.

**Comment by vrutkovs** [comment]
Several notes on the install procedure:
 * Not sure why is `python3 /usr/bin/ansible-playbook` used, is the result the same with `/usr/bin/ansible-playbook-3`? It seems py2 is used to run py2 code for playbook?
 * In 3.9 masters should also be included in nodes and marked schedulable (to run web console pods)
 * `openshift_repos_enable_testing` doesn't do anything on Fedora hosts

Could you put the output log with `ansible-playbook-3 -vvv` in the gist? Its not clear why it fails - and I never have seen that happening on my F27 installs

**Comment by adelton** [comment]
Thank you for your comments.

> Several notes on the install procedure:
> 
>  *   Not sure why is python3 /usr/bin/ansible-playbook used, is the result the same with /usr/bin/ansible-playbook-3? It seems py2 is used to run py2 code for playbook?

```
# ls -la /usr/bin/ansible-playbook
lrwxrwxrwx. 1 root root 29 Nov 30 04:47 /usr/bin/ansible-playbook -> /usr/bin/ansible-playbook-2.7
# ls -la  /usr/bin/ansible-playbook-3
lrwxrwxrwx. 1 root root 29 Nov 30 04:47 /usr/bin/ansible-playbook-3 -> /usr/bin/ansible-playbook-3.6
# diff -u /usr/bin/ansible-playbook-2.7 /usr/bin/ansible-playbook-3.6
--- /usr/bin/ansible-playbook-2.7	2017-11-30 04:05:57.000000000 +0530
+++ /usr/bin/ansible-playbook-3.6	2017-11-30 04:47:41.000000000 +0530
@@ -1,4 +1,4 @@
-#!/usr/bin/python2
+#!/usr/bin/python3
 
 # (c) 2012, Michael DeHaan <michael.dehaan@gmail.com>
 #
```

So my understanding is that it's exactly equivalent.

>  *   In 3.9 masters should also be included in nodes and marked schedulable (to run web console pods)

Can the master not being among nodes be the reason for the `prerequisites.yml` step failure, or would that only matter with `deploy_cluster.yml`, later on?

>  *   openshift_repos_enable_testing doesn't do anything on Fedora hosts

Dtto -- I use the same inventory file on all OSes so if it doesn't do anything, it shouldn't harm either, right?

> Could you put the output log with ansible-playbook-3 -vvv in the gist? Its not clear why it fails - and I never have seen that happening on my F27 installs

Will get back with the output once the test runs. Alternatively I can give you access to the reproducer machines, if you ping me internally.

**Comment by vrutkovs** [comment]
>Can the master not being among nodes be the reason for the prerequisites.yml step failure, or would that only matter with deploy_cluster.yml, later on?

`deploy_cluster.yml` would complain later on, yes

>it shouldn't harm either, right?

Ah, yes, definitely, just a note to cleanup inventory file, its fine to keep it though.

> Will  get back with the output once the test runs. Alternatively I can give  you access to the reproducer machines, if you ping me internally.

Both options are fine, ping me tomorrow when you'll have time

**Comment by adelton** [comment]
Here's the `ansible-playbook-3 -vvv` output: https://gist.github.com/adelton/34acc4827b4e48e1579ff217b0627a73

**Comment by vrutkovs** [comment]
Right, its has failed on `preequisites.yml` again - which failed to complete to the init and so `deploy_cluster.yml` failed later on. Must be something related to `omit` behavior in ansible.
