### ISSUE TITLE
origin-node wont start with openshift_use_openshift_sdn=False

### ISSUE THREAD

**Issue by mfojtik** [openshift/openshift-ansible#701]
While the master and other things works well, the Origin node will fail to register with this:

```
Oct 16 06:12:05 openshift-master.cdk.local origin-node[22499]: F1016 06:12:05.631287   22499 
node.go:141] failed to create kubelet: Network plugin "redhat/openshift-ovs-subnet" not found.
```

I think we should not configure the node to use the ovs subnet plugin but just fallback to docker network management.

**Comment by mfojtik** [comment]
@smarterclayton @sdodson this is breaking the installation on vagrant all-in-one :/

**Comment by sdodson** [comment]
Fix in https://github.com/openshift/openshift-ansible/pull/664 but needs to be rebased

**Comment by sdodson** [comment]
@mfojtik close this?

**Comment by abutcher** [comment]
@brenton this can be closed
