### ISSUE TITLE
Sat6 as Docker registry for offline install

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-ansible#7019]
working on project, who wants to use a Sattelite6 as docker registry for openshift... Sattelite 6 does not have a concept of the namespace when it comes to docker registry. so the only way was to use `oreg_url` to change the ref... `oreg_url=example.com/openshift3/ose-${component}:${version}` but our ansible code has this piece of code 
```

 # template for images that run on top of OpenShift
        image_url = "{}/{}-{}:{}".format(image_info["namespace"], image_info["name"], "${component}", "${version}")
        image_url = self.get_var("oreg_url", default="") or image_url
        image_url = self.template_var(image_url)
        if 'oo_nodes_to_config' in host_groups:
            for suffix in NODE_IMAGE_SUFFIXES:
                required.add(image_url.replace("${component}", suffix).replace("${version}", image_tag))
            if self.get_var("osm_use_cockpit", default=True, convert=bool):
                required.add(self._registry_console_image(image_tag, image_info))
```

which implies we NEED to have `/` in the image format (which is understandable because sat does not follow the naming standard and everybody else does)... 

so the only way how we now can consume images is to flatten the namespaces on Sattelite... but still, this makes super uncomfortable integration. Sat6 view:

```
  

rhel7/etcd:                                    sat6.example.com:5000/myorgurl-test-cv_openshift-rhocpinstreg-rhel7_etcd:latest

rhel7:                                          sat6.example.com:5000/myorgurl-test-cv_openshift-rhocpinstreg-rhel7:latest

openshift3/ose:                               sat6.example.com:5000/myorgurl-test-cv_openshift-rhocpinstreg-openshift3_ose:latest

openshift3/openvswitch:                                                             sat6.example.com:5000/myorgurl-test-cv_openshift-rhocpinstreg-openshift3_openvswitch:latest

openshift3/node:                                            sat6.example.com:5000/myorgurl-test-cv_openshift-rhocpinstreg-openshift3_node:latest 
```
The challenge is with formatting names with namespaces...

**Comment by mjudeikis** [comment]
``` 
oreg_url=sat6.example.com:5000/myorgurl-test-cv_openshift-rhocpinstreg-openshift3_${component}:${version}
osm_etcd_image=sat6.example.com:5000/myorgurl-test-cv_openshift-rhocpinstreg-rhel7_etcd
 ```  
as advised by @IshentRas 
testing...

**Comment by IshentRas** [comment]
openshift_cockpit_deployer_prefix=sat6.example.com:5000/myorgurl-test-cv_openshift-rhocpinstreg-openshift3_
openshift_metrics_image_prefix=sat6.example.com:5000/myorgurl-test-cv_openshift-rhocpinstreg-openshift3_
openshift_logging_image_prefix=sat6.example.com:5000/myorgurl-test-cv_openshift-rhocpinstreg-openshift3_
openshift_service_catalog_image_prefix=sat6.example.com:5000/myorgurl-test-cv_openshift-rhocpinstreg-openshift3_

**Comment by mjudeikis** [comment]
It still fails due other playbooks error. When trying to get openshift version if `openshift_release` is set:
```
(debug) p vars['oreg_url']

sat6.example.com:5000/example-test-cv_openshift-rhocpinstreg-openshift3_${component}:${version}'

(debug)

sat6.example.com:5000/example-test-cv_openshift-rhocpinstreg-openshift3_${component}:${version}'

(debug) p vars['openshift']['common']['cli_image']

u'openshift3/ose'

(debug) p task.args

{u'_raw_params': u'docker run --rm {{ openshift.common.cli_image }}:v{{ openshift_version }} version'}

(debug)
```

this is playbook issue, as this particular step is ignoring `oreg_url` in p `vars['openshift']['common']['cli_image']`

**Comment by brlbil** [comment]
@mjudeikis I am seeing a similar issue. The issue is closed but I do not see any resolution mentioned.
Is there a resolution or a workaround for this.

**Comment by mjudeikis** [comment]
@brlbil let me dig something for you what we did.
