### ISSUE TITLE
3.7, 3.8 imagestreams are not aligned with ose

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-ansible#7027]
our ose repo has 
https://github.com/openshift/ose/blob/enterprise-3.7/examples/image-streams/image-streams-rhel7.json#L849

the ansible repo has:
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v3.7/image-streams/image-streams-rhel7.json#L849

This is also an issue for v3.8.

I guess the sync script doesn't handle the OSE repo?

**Comment by sdodson** [comment]
The release-3.7 branch was sync'd with ose/enterprise-3.7 branch here https://github.com/openshift/openshift-ansible/pull/6703/files#diff-4bf52617deb12314308787d8490d3fceR849 and that's what we ship to customers.
I'll update all the v3.7 content from release-3.7 branch so that master branch is in sync in case anyone is installing 3.7 using a master branch checkout.

After we'd spoke last I wasn't able to come up with a sync script that worked against the ose repo, so if we want to keep openshift-ansible and content we pull from origin in sync it'd be easier if we made those changes in the origin repo.

**Comment by bparees** [comment]
Ah, ok, so at least the 3.7 errata we've shipped should be correct, that's good.

The 3.8 branch is still wrong though:
https://github.com/openshift/openshift-ansible/blob/release-3.8/roles/openshift_examples/files/examples/v3.8/image-streams/image-streams-rhel7.json#L866

(should be v3.8 i guess)

**Comment by bparees** [comment]
(looks like ose 3.8 is actually wrong (points to latest):
https://github.com/openshift/ose/blob/enterprise-3.8/examples/image-streams/image-streams-rhel7.json#L866)

i guess i'll go do a PR for that.

**Comment by bparees** [comment]
updating ose-3.8 here:
https://github.com/openshift/ose/pull/1047

**Comment by bparees** [comment]
@sdodson updating origin/release-3.8 here to try to make your life easier: https://github.com/openshift/origin/pull/18485

**Comment by bparees** [comment]
ok, the jenkins imagestream should be correct in both origin/release-3.8 and ose/enterprise-3.8 now.  (As well as origin/master and ose/master)

**Comment by siamaksade** [comment]
I'm a bit confused where this is supposed to be corrected. This how it looks like now:

release-3.7 /v3.7/: corrected
https://github.com/openshift/openshift-ansible/blob/release-3.7/roles/openshift_examples/files/examples/v3.7/image-streams/image-streams-rhel7.json#L849

master /v3.7/: not corrected
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v3.7/image-streams/image-streams-rhel7.json#L849

master /v3.8/: not corrected
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v3.8/image-streams/image-streams-rhel7.json#L866

release-3.8 /v3.8/: not corrected
https://github.com/openshift/openshift-ansible/blob/release-3.8/roles/openshift_examples/files/examples/v3.8/image-streams/image-streams-rhel7.json#L866

master /v3.9/: correct
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v3.9/image-streams/image-streams-rhel7.json#L1025

**Comment by bparees** [comment]
ideally master /v3.7 and master /v3.8 would be corrected though I believe @sdodson explained to me that that is not strictly necessary because they aren't actually used (since master is effectively v3.9)

release-3.8 /v3.8 needs to be corrected unless we skip updating imagestreams during the 3.8 install/upgrade.

**Comment by siamaksade** [comment]
@sdodson I just installed OCP v3.7.23 and the jenkins imagestream tags are like before. Will it be fixed on OCP 3.7?

**Comment by sdodson** [comment]
> @sdodson I just installed OCP v3.7.23 and the jenkins imagestream tags are like before. Will it be fixed on OCP 3.7?

It's fixed in openshift-ansible-3.7.24-1 and later 3.7 builds, unfortunately they haven't shipped yet but should soon.

**Comment by sdodson** [comment]
Ok v3.9, v3.8, v3.7 content should be fully in sync on master. We have no intention of maintaining the release-3.8 branch going forward, it's dead at this point. While master github branch *should* work to install all the way back to 3.7 the installer we actually ship comes from the release-3.7 branch.
