### ISSUE TITLE
[openshift_storage_glusterfs] heketi setup-openshift-heketi-storage not setting image

### ISSUE THREAD

**Issue by allen13** [openshift/openshift-ansible#7036]
#### Issue Location

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_storage_glusterfs/tasks/heketi_deploy_part2.yml#L3

#### Description

The setup-openshift-heketi-storage command creates a job/pod resource without specifying an image. It then uses the heketi/heketi:dev image that is hardcoded into the binary:

https://github.com/heketi/heketi/blob/master/client/cli/go/cmds/heketi_storage.go#L58

This behavior becomes problematic when working in an isolated enterprise environment and it can't connect to docker hub. Additionally, for users of openshift enterprise this is a security/support issue.

The solution is to add this argument to the command in the playbook.
--image {{ glusterfs_heketi_image }}:{{ glusterfs_heketi_version }}

This is tested and working in an isolated openshift enterprise environment.

##### Version

All versions

**Comment by allen13** [comment]
This issue was fixed in the master branch by reverting a previous commit: https://github.com/openshift/openshift-ansible/commit/f2ea513cde9dad1fb83bd10baa40c69da70a0bfe

Now the same needs to be done for the release-3.7 branch by reverting this commit 
https://github.com/openshift/openshift-ansible/commit/3d3853836d71c37a9c81aea8e606c94052439789

Once this is complete this issue can be resolved. Thanks!

**Comment by DanyC97** [comment]
@jarrpa  are you the right person to do the cherry-pick ? thanks

**Comment by jarrpa** [comment]
I'm a reasonable person to do it, sure. Can't guarantee when I'd get to it, however. It'd probably be part of a larger bundle of backports once QE on 3.9 is done.

**Comment by allen13** [comment]
Looks like the revert has made it's way to the release-3.7 branch. https://github.com/openshift/openshift-ansible/commit/8f7a40c55fba33ab44fb1565bb7d8e46286a6458

Thanks!

**Comment by DanyC97** [comment]
thanks for heads up @allen13 !!
