### ISSUE TITLE
Upgrade from 3.6 -> 3.7 fails at pulling docker images

### ISSUE THREAD

**Issue by jtcressy** [openshift/openshift-ansible#7059]
#### Description

Either the upgrade playbook for 3.7 needs to accept "openshift_release=v3.7.0" or the docker tag for "openshift/origin:v3.7" needs to be created. The upgrade playbook always fails, even if I remove the "openshift_release" variable from my inventory. 

The playbook fails with at least one of my master nodes giving exit code 0 on the docker pull, with the interesting bits being: ``manifest for openshift/origin:v3.7 not found``

And, when I set openshift_release=v3.7.0 the playbook fails with ``openshift_release is 3.7.0 which is not a valid release for 3.7 upgrade``

##### Version

* Ansible 2.4.2.0
* Branch release-3.7.0day

**Comment by jtcressy** [comment]
SOLVED:

I didn't know that "openshift_image_tag" was a variable I could set.
Upgrade completes successfully with ```
openshift_release=v3.7
openshift_image_tag=v3.7.0
```
Ideally this should be the default values when the variables are not set in the user's inventory file, but to anyone coming across this issue, this is the fix.

**Comment by feld-ims** [comment]
is:
`openshift_image_tag=v3.7.0`

the same as:
`openshift_version=3.7.0`

?

**Comment by jtcressy** [comment]
I left openshift_version undefined, but I believe it sets the package version for the rpm's. I think it auto-sets itself to ``openshift_version=-3.7.0`` after the playbook runs.
