### ISSUE TITLE
Was Branch 3.x deleted?

### ISSUE THREAD

**Issue by sborenst** [openshift/openshift-ansible#710]
Hi, 
We are using this branch for our automated deployment, has it been deleted?

**Comment by abutcher** [comment]
@sborenst Hey - looks like it. Could you use the `v3.0.0` tag instead? The `HEAD` of the `3.x` branch lined up with this tag.

**Comment by abutcher** [comment]
@brenton I believe this one can be closed unless we're referring to the 3.x branch in any documentation. openshift-docs points to master branch atm
