### ISSUE TITLE
Router is continuously being restarted due to probe in port 80

### ISSUE THREAD

**Issue by fdmontero** [openshift/openshift-ansible#7118]
I have installed Openshift Origin using ansible and rpm based. I have a router a registry and a registry-console. The router is recreating the pod every 30 seconds. Some kind of health check on port 80 is exiting with no success and the pod is being restarted. 

I0212 19:11:59.673136       1 template.go:254] Starting template router (v3.7.0+7ed6862)
I0212 19:11:59.674646       1 metrics.go:148] Router health and metrics port listening at 0.0.0.0:1936
I0212 19:11:59.734715       1 router.go:441] Router reloaded:
 - Checking http://localhost:80  ...
 - Health check ok : 0 retry attempt(s).
I0212 19:11:59.734776       1 router.go:228] Router is including routes in all namespaces
I0212 19:12:00.090924       1 router.go:441] Router reloaded:
 - Checking http://localhost:80  ...
 - Health check ok : 0 retry attempt(s).
I0212 19:12:05.083024       1 router.go:441] Router reloaded:
 - Checking http://localhost:80  ...
- Health check ok : 0 retry attempt(s).
I0212 19:12:10.097277       1 router.go:441] Router reloaded:
 - Checking http://localhost:80  ...

The router has the following readiness probe:
readinessProbe:
            failureThreshold: 3
            httpGet:
              host: 127.0.0.1
              path: /healthz
              port: 1936
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10

It also has a liveness  probe:
livenessProbe:
            failureThreshold: 3
            httpGet:
              host: 127.0.0.1
              path: /healthz
              port: 1936
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10

I have opened a console in the pod and performed `$ curl http://127.0.0.1:1936/healthz` and it returns ok. Also with authentication `$ curl http://admin:3jGZIPAYMK@localhost:1936/healthz` returns ok.

I am stuck finding out where this probe is defined in order to remove or to fix it. Even I have tried removing liveness and readiness probes with no success.

Any help will be very welcome.
Thanks in advance

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://osc-master.simulacion.local:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. Install openshift with ansible
2. Check the status of the router

##### Additional Information
Output from `oadm diagnostics`
[oadm_diagnostics.txt.gz](https://github.com/openshift/openshift-ansible/files/1717499/oadm_diagnostics.txt.gz)

###############################
Output from `$ oc get all -o json -n default`
[oc_get_all.json.gz](https://github.com/openshift/openshift-ansible/files/1717501/oc_get_all.json.gz)

**Comment by karmab** [comment]
might be an issue with your kernel if using fedora27
