### ISSUE TITLE
GlusterFS - why heketi needs to go over OpenShift Router

### ISSUE THREAD

**Issue by DanyC97** [openshift/openshift-ansible#7156]
Any reason why fro the native deployment `heketi` needs a openshift router (ingress) as a requirement

I see the route is being created [here](https://github.com/openshift/openshift-ansible/blob/release-3.7/roles/openshift_storage_glusterfs/files/v3.7/heketi-template.yml#L28-L38)  but i was hopping this can be done using the internal dns `svc.cluster.local` ?

@jarrpa i'm sure you are the person with the answers, hence would appreciate if you can help me put all the puzzle together. I do apologize in advance, i'm aware github is not the place to raise question, hands up

**Comment by jarrpa** [comment]
Hey, no better recourse means it's the perfect place. :)

The Route is specifically to allow for instances of heketi-cli that are installed outside the OpenShift cluster. There are many users that want that functionality for a variety of reasons.

If you're asking why the Route is used in the generated StorageClass, truth is that design pattern was present before I came along and I just haven't bothered changing it. Any proper OpenShift deployment should have DNS configured such that ingress addresses are resolvable, best I know, so this should only rarely be an issue. That said, if there's any advantage to using the internal service name instead I'd be amenable to changing that.

**Comment by allen13** [comment]
If we could at least have an option to override the route in the StorageClass with an internal service using a group var I would be happy. Using a router introduces another point of failure. In my organization our routers are connected to external load balancers, which means one more additional hop is added further reducing reliability/response times. I don't see the glusterfs storage class ever needing to reach outside of the cluster.

Thanks!

**Comment by jarrpa** [comment]
Okay, I can see that. :) At the moment I don't see any of us getting around to this any time soon, but if you or someone else feels up to it I'll review a PR to make it happen. I'll assign myself to this Issue just to keep tabs on it, at least.

**Comment by DanyC97** [comment]
@jarrpa thx for the quick response

will try to see if it works first w/o the ingress because i came across this [K8 issue](https://github.com/kubernetes/kubernetes/issues/42306)

**Comment by DanyC97** [comment]
closing as is been implemented in master recently
