### ISSUE TITLE
"Verify that TSB is running" fails when it's actually running.

### ISSUE THREAD

**Issue by christianh814** [openshift/openshift-ansible#7158]
#### Description

Provide a brief description of your issue here. For example:

During an install, TSB check returns...

```
FAILED - RETRYING: Verify that TSB is running (XXX retries left).
```
...and eventually fails.

Looking at the playbook...looks it's checking with a simple curl

```
# Check that the TSB is running
- name: Verify that TSB is running
  command: >
    curl -k https://apiserver-kube-service-catalog.apps.mydomain.com/healthz
  args:
    # Disables the following warning:
    # Consider using get_url or uri module rather than running curl
    warn: no
  register: api_health
  until: api_health.stdout == 'ok'
  retries: 120
  delay: 1
  changed_when: false
```
My TSB is up and running

```
[root@ocp-aio share]# curl -k https://apiserver-kube-service-catalog.apps.mydomain.com/healthz
ok
```

Wouldn't it make more sense, since if you're at this point the `oc` binary should be install, to get the route first...

```
oc get routes -n kube-service-catalog -o jsonpath='{.items[*].spec.host}{"\n"}'
```

And use that route instead of relying on the `.svc` to expand to `svc.cluster.local`?

##### Version

Please put the following version information in the code block
indicated below.

```
[root@ocp-aio share]# ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

```
[root@ocp-aio share]# rpm -qi atomic-openshift-utils
Name        : atomic-openshift-utils
Version     : 3.7.23
Release     : 1.git.0.bc406aa.el7
Architecture: noarch
Install Date: Wed 14 Feb 2018 12:08:07 PM PST
Group       : Unspecified
Size        : 160981
License     : ASL 2.0
Signature   : RSA/SHA256, Fri 12 Jan 2018 11:00:59 AM PST, Key ID 199e2f91fd431d51
Source RPM  : openshift-ansible-3.7.23-1.git.0.bc406aa.el7.src.rpm
Build Date  : Thu 11 Jan 2018 12:19:10 PM PST
Build Host  : x86-041.build.eng.bos.redhat.com
Relocations : (not relocatable)
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : https://github.com/openshift/openshift-ansible
Summary     : Atomic OpenShift Utilities
Description :
Atomic OpenShift Utilities includes
 - atomic-openshift-installer
 - other utilities
```

Place the output between the code block below:

```
[root@ocp-aio share]# oc version
oc v3.7.23
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ocp-aio.mydomain.com:8443
openshift v3.7.23
kubernetes v1.7.6+a08f5eeb
```

##### Steps To Reproduce
1. install openshift

##### Expected Results
The validator returns with TSB all "okay"

##### Observed Results
Describe what is actually happening.

```
FAILED - RETRYING: Verify that TSB is running 
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.
```
[root@ocp-aio share]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)
```

**Comment by christianh814** [comment]
First attempt with #7159

**Comment by vrutkovs** [comment]
>Looking at the playbook...looks it's checking with a simple curl

It checking that TSB is running using internal DNS server. If `.svc` URL is not accessible from one of the masters then DNS resolution is broken and other things might go wrong - e.g. pulling/pushing from internal registry

**Comment by christianh814** [comment]
It may be an issue with a disconnected install. The environment works fine. I rerun the playbook with my changes and everything finishes fine and the env works from what I can tell.

Any reason why not use the URI of the svc instead of the shorthand
