### ISSUE TITLE
can't access to http with error ERR_INVALID_HTTP_RESPONSE (  )

### ISSUE THREAD

**Issue by d-malko** [openshift/openshift-ansible#7168]
#### Description

Good day!
I am new in OpenShift and want to try OpenShift tools, but  I've got an error.
Sorry, if I right in wrong repository.
I'll be gratefull for any advice.

##### Version
```
OS: Debian GNU/Linux 8

oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
```

##### Steps To Reproduce
1.downloaded and untar package from repository to PATH dir
2. oc cluster up

```
Starting OpenShift using openshift/origin:v3.7.1 ...
OpenShift server started.

The server is accessible via web console at:
    https://127.0.0.1:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin
```

docker ps
>e38cd98e6397        openshift/origin:v3.7.1   "/usr/bin/openshift …"   6 seconds ago       Up 5 seconds                            epic_galileo

##### Expected Results
Want to access via browser

##### Observed Results
When I try to access via browser I've got an error
> ERR_INVALID_HTTP_RESPONSE

And via curl
```
curl -kv http://127.0.0.1:8443
* Rebuilt URL to: http://127.0.0.1:8443/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 127.0.0.1:8443
> Accept: */*
> 

* Connection #0 to host 127.0.0.1 left intact



```
##### Additional Information
Other functionality working without problems
```
root@openshift:~# oc login -u system:admin
Logged into "https://127.0.0.1:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
  * myproject
    openshift
    openshift-infra
    openshift-node

Using project "myproject".

```

**Comment by vrutkovs** [comment]
The issues against clusters deployed using `oc cluster up` should go to https://github.com/openshift/origin.

The resolution for this is simple though - `8443` is an alternative port for SSL, so `https` should be used in curl.
