### ISSUE TITLE
Can't pull cri-o system container image from authenticated registry

### ISSUE THREAD

**Issue by sjenning** [openshift/openshift-ansible#7177]
https://github.com/openshift/openshift-ansible/blob/master/roles/container_runtime/tasks/systemcontainer_crio.yml#L46

The `atomic pull` command has a flag `--src-creds <username>:<password>` which allows pulls from authenticated registries.

@sdodson anyway we could plumb the existing `oreg_auth_user` and `oreg_auth_password` in there?

@mrunalp @runcom

**Comment by runcom** [comment]
@giuseppe PTAL as well

**Comment by giuseppe** [comment]
the new version of atomic/Skopeo can deal with a registry that requires an authentication.  We are tracking it here:

https://bugzilla.redhat.com/show_bug.cgi?id=1510148

What version of Skopeo are you using?

**Comment by sjenning** [comment]
```
# skopeo -v
skopeo version 0.1.28-dev
```

**Comment by giuseppe** [comment]
that should be good to go.  Could you please also check the version of `atomic`?

`0.1.28-dev` uses the Docker credentials set via `oreg_auth_user` and `oreg_auth_password` when copying to the ostree storage.  Is the registry accessible with `skopeo inspect docker://....` at the moment of the failure?

**Comment by sjenning** [comment]
Huh.  I try it today and it works on a cluster that I already installed with docker, not cri-o.  I wonder if it is just that the ~/.docker/config.json file is not created in the prereqs playbook before the cri-o system container pull is attempted.  Either that or skopeo was updated in the repos between my attempts.

```
# skopeo inspect docker://registry.reg-aws.openshift.com/openshift3/cri-o:v3.9
{
    "Name": "registry.reg-aws.openshift.com/openshift3/cri-o",
...

# atomic pull --storage ostree registry.reg-aws.openshift.com/openshift3/cri-o:v3.9
Getting image source signatures
Copying blob sha256:9a32f102e6778e4b3c677f1f93fa121808006d3c9e002237677248de9acb9589
 71.40 MB / 71.40 MB [======================================================] 6s
...
```

**Comment by giuseppe** [comment]
I've opened a PR to ensure we are logged in before we attempt to pull the image:

https://github.com/openshift/openshift-ansible/pull/7185

**Comment by sjenning** [comment]
Not sure what happened the first time I ran this, but the original issue isn't happening anymore.  I don't think this fix is required.  Sorry for the noise :-/
