### ISSUE TITLE
GlusterFS PVs lost on reboot - mountPath /etc/target missing from glusterfs-template.yml

### ISSUE THREAD

**Issue by datarace** [openshift/openshift-ansible#7194]
#### Description

>mountPath /etc/target missing from glusterfs-template.yml
> As such pv config is not persisted across node reboots
> PVs appear 'lost'

##### Version

3.7.23.1
Issue also looks to be in 3.9

```
atomic-openshift-utils-3.7.23-1.git.0.bc406aa.el7.noarch
openshift-ansible-3.7.23-1.git.0.bc406aa.el7.noarch```
```

##### 
Steps To Reproduce
1. Install openshift & gluster playbooks.
2. Run manual steps identified in Issue #6801
3. Create Glusterblock pv using pvc
4. Reboot all nodes
5. PV is 'lost'

##### Expected Results
PV whould be present after reboot

##### Observed Results
Describe what is actually happening.

```
PV is 'lost'
```

##### Additional Information

```
glusterfs-template.yml is missing mountPath /etc/target when compared to this file in CNS rpm

`[root@ip-10-102-0-5 v3.7]# diff glusterfs-template.yml.fixed glusterfs-template.yml.orig
48,49d47
<           - name: glusterfs-block
<             mountPath: "/etc/target"
99,101d96
<         - name: glusterfs-block
<           hostPath:
<             path: "/etc/target"`

The consequence of this is that when the gluster nodes are stopped/started all config data is lost from /etc/target, meaning that PVs have 'dissapeared'.

I have fixed this in my dev environment and it works for me. 

Fix related to gluster automation https://github.com/openshift/openshift-ansible/issues/6801

Would like to do PR to fix this - any comments please before I go ahead ?
```
Ping @jarrpa @mjudeikis

**Comment by datarace** [comment]
Cause of the issue has been identified in Support Case 02029417 (missing /etc/target mount on underlying node)

**Comment by mjudeikis** [comment]
@jarrpa ping. One more for gluster block. Are you fine with suggested change?

**Comment by jarrpa** [comment]
@mjudeikis I don't see the suggested change so I couldn't tell you. :)

**Comment by mjudeikis** [comment]
@datarace can you raise PR for this as you already have fix in your codebase?

**Comment by datarace** [comment]
Had a support call this morning for Support Case 02029417 with support & CNS Engineer.
CNS Engineer will be arranging conf call with @jarrpa to discuss with the intention of CNS team implementing the PR ASAP.

**Comment by DanyC97** [comment]
@datarace isn't this covered by https://github.com/openshift/openshift-ansible/pull/7198 ?

**Comment by SaravanaStorageNetwork** [comment]
> @datarace isn't this covered by #7198 ?

Yes this is covered by the above PR.

**Comment by DanyC97** [comment]
then can this issue be closed? (i don't have permission to do so)

**Comment by jarrpa** [comment]
Waiting a bit for @datarace to respond. :)

**Comment by datarace** [comment]
Happy to close :) @jarrpa

**Comment by datarace** [comment]
Happy to close :) @jarrpa
