### ISSUE TITLE
openshift_http_proxy not used during pulling router and registry pods

### ISSUE THREAD

**Issue by yrjo** [openshift/openshift-ansible#7215]
#### Description

Seems like "openshift_http_proxy" & co. are not used during pulling the pods right after deployment of basics of openshift cluster.

multimaster environment - deployment from the scratch,
3x master nodes (etcd on it)
3x dedicated infra nodes
3x nodes for app workload

##### Version

cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)

openshift (origin) version
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
etcd 3.2.8

ansible --version
ansible 2.4.3.0

git describe
openshift-ansible-3.9.0-0.42.0-83-gca5e166fe

##### Steps To Reproduce
1. deploy new environment via openshift ansible mentioned above
2. environment is behind web proxy 

##### Expected Results
deployment done successfully, pods are running

##### Observed Results
deployment by ansible shows as completed:

`INSTALLER STATUS **************************************************************************************************************************************************************************************************
Initialization             : Complete (0:00:27)
Health Check               : Complete (0:00:47)
etcd Install               : Complete (0:00:53)
Master Install             : Complete (0:03:46)
Master Additional Install  : Complete (0:00:24)
Node Install               : Complete (0:04:23)
Hosted Install             : Complete (0:03:01)
Metrics Install            : Complete (0:01:18)
Logging Install            : Complete (0:02:57)
Prometheus Install         : Complete (0:00:48)
`

pods are not created,

    oc get pods
    NAME                        READY     STATUS              RESTARTS   AGE
    docker-registry-1-deploy    0/1       ContainerCreating   0          23m
    registry-console-1-deploy   0/1       ContainerCreating   0          21m
    router-1-deploy             0/1       ContainerCreating   0          24m

    oc logs pods/router-1-deploy
    Error from server (BadRequest): container "deployment" in pod "router-1-deploy" is waiting to start: ContainerCreating

    Events:
      FirstSeen	LastSeen	Count	From						SubObjectPath	Type		Reason			Message
      ---------	--------	-----	----						-------------	--------	------			-------
      20m		20m		1	default-scheduler						Normal		Scheduled		Successfully assigned router-1-deploy to NODE03
      19m		19m		1	kubelet, NODE03		Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "deployer-token-gf5hp" 
      18m		1m		11	kubelet, NODE03			Warning		FailedCreatePodSandBox	Failed create pod sandbox.

because they cannot be pulled from docker.io thru the proxy:
```
"openshift/origin-pod:v3.7.0": Network timed out while trying to connect to https://index.docker.io/v1/repositories/openshift/origin-pod/images.

failed: rpc error: code = 2 desc = failed pulling image "openshift/origin-pod:v3.7.0": Network timed out while trying to connect to https://index.docker.io/v1/repositories/openshift/origin-pod/images.

```
even in inventory file there is specified the proxy:

    openshift_http_proxy=http://IP:3128
    openshift_https_proxy=https://IP:3128
    openshift_no_proxy='.DOMAIN.COM'

it is obviously not used during pulling the pods in the beginning.

**Comment by yrjo** [comment]
should be the way to set it automatically with ansible to have in docker environment variables something like:
```
[Service]    
Environment="HTTP_PROXY=http://proxy.example.com:80/" "NO_PROXY=localhost,127.0.0.1,docker-registry.somecorporation.com"
```

bcs right now docker is going without it?

```
systemctl show --property=Environment docker
Environment=GOTRACEBACK=crash DOCKER_HTTP_HOST_COMPAT=1 PATH=/usr/libexec/docker:/usr/bin:/usr/sbin
```
or at least if kube_docker_client.go is using that enviro variables?

`kube_docker_client.go:328] Pulling image "openshift/origin-pod:v3.7.0": ...`

**Comment by DanyC97** [comment]
@yrjo  it certainly does cause i've been using it since origin 1.4 up to 3.7.

**Comment by yrjo** [comment]
fixed by workaround - added lines HTTP_PROXY, HTTPS_PROXY and NO_PROXY with lineinfile ansible module to file /etc/sysconfig/docker for all nodes, restart docker service afterwards.
i am not creating any PR as that is really dirty workaround, i guess that should be done by more system way, or?

**Comment by DanyC97** [comment]
well what i was trying to say @yrjo is that you don't need to do anything since with those parameters it worked w/o any issue - and i've done tons of origin deployments in a locked/ proxy env since 1.4 and it worked every single time

**Comment by yrjo** [comment]
@DanyC97 then there is obviously something bad between my keyboard and chair ;) if there is nobody else having problem like that, i am closing the issue
