### ISSUE TITLE
Should not use the "master" branch for xPaaS templates

### ISSUE THREAD

**Issue by mfojtik** [openshift/openshift-ansible#722]
@sdodson I've learned today from @goldmann that we should not install the "master" branch templates as the images they use are not available in official registry.

This: https://github.com/openshift/openshift-ansible/blob/c443f3fc1b901b72a58e0e28b5a280cec205cbbd/roles/openshift_examples/examples-sync.sh#L18

Should be:

https://github.com/jboss-openshift/application-templates/archive/ose-v1.0.2.zip

**Comment by goldmann** [comment]
Master never should be used, it's a development branch. Please use tags.

**Comment by sdodson** [comment]
@goldmann When can we expect a new tag? I'm pretty sure we've *had* to ship newer code than the latest tag just to fix some pretty major bugs. I can't remember exact details but I asked @knrc to approve those changes.

**Comment by knrc** [comment]
@sdodson We are currently blocked on an EAP clustering issue but will be making a decision on this tomorrow

**Comment by knrc** [comment]
@mfojtik Yes, you should never install master as this is what lead to all the issues with the OSE 3.0 release when the OpenShift team shipped broken templates.

**Comment by knrc** [comment]
@sdodson BTW the change you asked me to approve was simply to fix the template name clash that the JBDS team discovered, something that was already included in our updates for this release.

**Comment by knrc** [comment]
@sdodson and I would definitely not call that a major bug ;)
