### ISSUE TITLE
openshift-ansible fails to play openshift-ansible/roles/openshift_master/tasks/main.yml

### ISSUE THREAD

**Issue by ekuric** [openshift/openshift-ansible#724]
seems openshift-ansible fails to select router per  openshift-ansible/roles/openshift_master/tasks/main.yml. Error below 

TASK: [openshift_router | set_fact _ortr_images="--images='{{ openshift.master.registry_url }}'"] *** 
ok: [hp-dl380g8-01.perf.lab.eng.rdu.redhat.com]

TASK: [openshift_router | set_fact _ortr_selector="--selector='{{ openshift.master.router_selector }}'"] *** 
fatal: [hp-dl380g8-01.perf.lab.eng.rdu.redhat.com] => One or more undefined variables: 'dict object' has no attribute 'router_selector'

FATAL: all hosts have already failed -- aborting

**Comment by detiber** [comment]
@ekuric looks like you are hitting this: https://github.com/openshift/openshift-ansible/pull/721

**Comment by ekuric** [comment]
@detiber yes, I applied changes from #721 and it is solution for this issue too. Closing this issue
