### ISSUE TITLE
GlusterFS - heketi-storage job image is hardcoded to "dev"

### ISSUE THREAD

**Issue by DanyC97** [openshift/openshift-ansible#7284]
@jarrpa i believe you are aware of https://github.com/heketi/heketi/issues/950 ? 

Is a bit shame to see that although we moved to use `latest` tag we still have to get the `dev`  image/ tag

What is your thought?

**Comment by jarrpa** [comment]
I am not aware of that, I don't track heketi too closely. The setup-heketi-openshift-storage command does take a `--image` tag for you to specify any desired heketi image, though. Is that not sufficient?

**Comment by allen13** [comment]
This issue was recently resolved. https://github.com/openshift/openshift-ansible/issues/7036

**Comment by DanyC97** [comment]
@allen13 great !! didn't check master, only my poor 3.7 branch.

should i close this one @jarrpa and trust on your note that the above fix will be backported to 3.7?

**Comment by DanyC97** [comment]
closing as the fix made it to 3.7 branch, thanks for heads up @allen13  !!
