### ISSUE TITLE
GlusterFS - bump heketi image tag to v6

### ISSUE THREAD

**Issue by DanyC97** [openshift/openshift-ansible#7285]
@jarrpa happy to send a PR, you good with it or you still want to wait first for 3.9 QA to finish their round?

**Comment by jarrpa** [comment]
Wait on this one. Also, where would the change be?

**Comment by DanyC97** [comment]
@jarrpa just [here](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_storage_glusterfs/defaults/main.yml#L35) ;)

**Comment by jarrpa** [comment]
...latest doesn't point to 6? If not then that's a problem for the heketi container maintainers and you should raise an Issue against heketi.
