### ISSUE TITLE
Unable to restart service origin-master-api

### ISSUE THREAD

**Issue by randy280872** [openshift/openshift-ansible#7304]
#### Description

During the installation of Openshift Origin I am getting the error below; 

fatal: [dae-openshift-dev.digitaldev.local]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "daemon_reload": false,
            "enabled": null,
            "masked": null,
            "name": "origin-master-api",
            "no_block": false,
            "state": "restarted",
            "user": false
        }
    },
    "msg": "Unable to restart service origin-master-api: Job for origin-master-api.service failed because the control process exited with error code. See \"systemctl status origin-master-api.service\" and \"journalctl -xe\" for details.\n"
}

##### Version

Please put the following version information in the code block
indicated below.
--------------------
ansible 2.4.2.0

-------------------------------------------------
https://github.com/openshift/openshift-ansible.git

 ansible-playbook -i /etc/ansible/hosts /openshift/openshift-ansible/playbooks/openshift-master/config.yml 

```
VERSION INFORMATION HERE PLEASE
```

##### Expected Results
I am expecting OpenShift Origin to be installed.

```
Example command and output or error messages
 ansible-playbook -i /etc/ansible/hosts /openshift/openshift-ansible/playbooks/openshift-master/config.yml 

    "msg": "Unable to restart service origin-master-api: Job for origin-master-api.service failed because the control process exited with error code. See \"systemctl status origin-master-api.service\" and \"journalctl -xe\" for details.\n"
```

##### Observed Results
The ansible playbook execcutes up to the point where it tries to restart the origin-master-api.
When I do a 'docker ps -a' I don't see the container that it's trying to start.

```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.
I tries running the playbook as root and as a non-root user without any success

* OS - 
CentOS Linux release 7.4.1708 (Core)
* Inventory file - 
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_sudo must be set to true
#ansible_sudo=true
ansible_user=root
#ansible_user=osadmin
ansible_become=true
product_type=openshift
deployment_type=origin
enable_excluders=false

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/
etc/origin/openshift-passwd'}]

containerized=true
openshift_release=v3.9
openshift_image_tag=v3.9.0
openshift_public_hostname=dae-openshift-dev.digitaldev.local
openshift_master_default_subdomain=apps.dae-openshift-dev.digitaldev.local
openshift_disable_check=memory_availability,docker_storage,disk_availability,package_version
os_firewall_enabled=false
etcd_version=3.2.7

# host group for masters
[masters]
dae-openshift-dev.digitaldev.local

# host group for nodes, includes region info
[nodes]
dae-openshift-dev.digitaldev.local
[etcd]
dae-openshift-dev.digitaldev.local

**Comment by sbadakhc** [comment]
This could be related: https://github.com/openshift/openshift-ansible/issues/7525

**Comment by DanyC97** [comment]
@randy280872 so what does the output of `systemctl status origin-master-api.service` & `journalctl -xe` show?

**Comment by randy280872** [comment]
@DanyC97 , please see output below;
Mar 18 11:54:34 dae-opsmaster-2.digitaldev.local systemd[1]: Failed to start Atomic OpenShift Master Controllers.
-- Subject: Unit origin-master-controllers.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit origin-master-controllers.service has failed.
--
-- The result is failed.
Mar 18 11:54:34 dae-opsmaster-2.digitaldev.local systemd[1]: Unit origin-master-controllers.service entered failed state.
Mar 18 11:54:34 dae-opsmaster-2.digitaldev.local systemd[1]: origin-master-controllers.service failed.
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local systemd[1]: origin-master-api.service holdoff time over, scheduling restart.
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local systemd[1]: Starting Atomic OpenShift Master API...
-- Subject: Unit origin-master-api.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit origin-master-api.service has begun starting up.
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local atomic-openshift-master-api[62555]: I0318 11:54:39.934245   62555 start_api.go:104] Using a listen address override "0.
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local atomic-openshift-master-api[62555]: I0318 11:54:39.934455   62555 plugins.go:77] Registered admission plugin "Namespace
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local atomic-openshift-master-api[62555]: W0318 11:54:39.935874   62555 start_master.go:290] Warning: assetConfig.loggingPubl
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local atomic-openshift-master-api[62555]: W0318 11:54:39.935906   62555 start_master.go:290] Warning: assetConfig.metricsPubl
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local atomic-openshift-master-api[62555]: W0318 11:54:39.935917   62555 start_master.go:290] Warning: aggregatorConfig.proxyC
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local atomic-openshift-master-api[62555]: Invalid MasterConfig /etc/origin/master/master-config.yaml
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local atomic-openshift-master-api[62555]: etcdClientInfo.ca: Invalid value: "/etc/origin/master/master.etcd-ca.crt": could no
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local systemd[1]: origin-master-controllers.service holdoff time over, scheduling restart.
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local systemd[1]: origin-master-api.service: main process exited, code=exited, status=255/n/a
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local systemd[1]: Failed to start Atomic OpenShift Master API.
-- Subject: Unit origin-master-api.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit origin-master-api.service has failed.
--
-- The result is failed.
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local systemd[1]: Unit origin-master-api.service entered failed state.
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local systemd[1]: origin-master-api.service failed.
Mar 18 11:54:39 dae-opsmaster-2.digitaldev.local systemd[1]: Starting Atomic OpenShift Master Controllers...
-- Subject: Unit origin-master-controllers.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit origin-master-controllers.service has begun starting up.

**Comment by vrutkovs** [comment]
>openshift-master-api[62555]: etcdClientInfo.ca: Invalid value: "/etc/origin/master/master.etcd-ca.crt": could no

Before the master is setup the etcd cluster should be up.

Please run
```
ansible-playbook -i /etc/ansible/hosts /openshift/openshift-ansible/playbooks/prerequisites.yml
ansible-playbook -i /etc/ansible/hosts /openshift/openshift-ansible/playbooks/deploy_cluster.yml
```
instead of per-component playbooks

**Comment by mrmStack** [comment]
I have the same problem, someone can help me?

INSTALLER STATUS **************************************************************************
Initialization             : Complete (0:01:07)
	[DEPRECATION WARNING]: The following are deprecated variables and will be no longer be used in the next minor release. Please update your inventory accordingly.
	openshift_hosted_metrics_deploy
Health Check               : Complete (0:00:23)
etcd Install               : Complete (0:00:57)
Load balancer Install      : Complete (0:00:17)
Master Install             : In Progress (0:05:02)
	This phase can be restarted by running: playbooks/openshift-master/config.yml

Monday 21 May 2018  20:57:49 +0200 (0:00:01.097)       0:07:48.207 ************ 
=============================================================================== 
Run health checks (install) - EL -------------------------------------------------- 22.34s
Gather Cluster facts -------------------------------------------------------------- 16.52s
openshift_master : Set fact of all etcd host IPs ---------------------------------- 15.58s
openshift_master : Re-gather package dependent master facts ----------------------- 15.45s
openshift_buildoverrides : Set buildoverrides config structure -------------------- 15.42s
Initialize openshift.node.sdn_mtu ------------------------------------------------- 15.40s
openshift_facts ------------------------------------------------------------------- 15.25s
openshift_cli : Reload facts to pick up installed OpenShift version --------------- 15.19s
openshift_master_facts : Set master facts ----------------------------------------- 15.19s
openshift_builddefaults : Set builddefaults --------------------------------------- 15.18s
openshift_named_certificates : openshift_facts ------------------------------------ 14.98s
openshift_builddefaults : Set builddefaults config structure ---------------------- 14.87s
openshift_facts ------------------------------------------------------------------- 14.83s
openshift_facts ------------------------------------------------------------------- 14.78s
openshift_master_facts : Set master facts ----------------------------------------- 14.71s
openshift_excluder : Install docker excluder - yum --------------------------------- 7.48s
openshift_version : Get available origin version ----------------------------------- 4.26s
tuned : Ensure files are populated from templates ---------------------------------- 4.03s
tuned : Ensure files are populated from templates ---------------------------------- 4.01s
openshift_master_certificates : Check status of master certificates ---------------- 3.82s

Failure summary:


  1. Hosts:    master-node.opnsft.es
     Play:     Configure masters
     Task:     restart master api
     Message:  Unable to restart service origin-master-api: Job for origin-master-api.service failed because the control process exited with error code. See "systemctl status origin-master-api.service" and "journalctl -xe" for details.

**Comment by mrmStack** [comment]
I have followed the steps of vrutkovs but it doesn't work.

**Comment by vrutkovs** [comment]
We need logs from this service (`journalctl -b -el --unit=origin-master-api`) to find out why API server didn't start

**Comment by mrmStack** [comment]
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.976786 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.977425 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.978735 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.980036 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.980678 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.981302 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: W0521 21:59:52.982536 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.984486 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.985073 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.985726 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.986353 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.986940 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.987554 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.988116 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.989415 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991102 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991160 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991191 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991203 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991279 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991289 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991299 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991309 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991319 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991332 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991342 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991351 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991360 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991370 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991385 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991394 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991404 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991413 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991421 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991430 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991438 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991448 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991456 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991465 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991474 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991483 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991492 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991506 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991516 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991527 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991536 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991546 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: F0521 21:59:52.995268 
May 21 21:59:53 master-node.opnsft.es systemd[1]: Failed to start Atomic OpenShift Master API.

**Comment by mrmStack** [comment]
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.976786 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.977425 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.978735 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.980036 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.980678 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.981302 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: W0521 21:59:52.982536 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.984486 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.985073 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.985726 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.986353 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.986940 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.987554 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.988116 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.989415 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991102 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991160 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991191 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991203 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991279 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991289 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991299 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991309 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991319 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991332 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991342 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991351 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991360 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991370 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991385 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991394 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991404 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991413 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991421 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991430 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991438 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991448 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991456 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991465 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991474 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991483 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991492 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991506 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991516 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991527 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991536 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: I0521 21:59:52.991546 
May 21 21:59:52 master-node.opnsft.es atomic-openshift-master-api[16970]: F0521 21:59:52.995268 
May 21 21:59:53 master-node.opnsft.es systemd[1]: Failed to start Atomic OpenShift Master API.

**Comment by mrmStack** [comment]
it's possible that the problem could be the user?  which is diferent to root;  because I have created a user named origin with root permisions.

thanks @vrutkovs

**Comment by mrmStack** [comment]
Now fail in other situation...it's posible the fail could be bellow " to create listener: failed to listen on 0.0.0.0:8443"? 

may 23 12:35:34 che-master.es systemd[1]: Failed to start Atomic OpenShift Master API.
-- Subject: Unit origin-master-api.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit origin-master-api.service has failed.
-- 
-- The result is failed.
may 23 12:35:34 che-master.es atomic-openshift-master-api[1073]: I0523 12:35:34.174790    1073 plugins.go:83] Registered admission plugin "ResourceQuota"
may 23 12:35:34 che-master.es atomic-openshift-master-api[1073]: I0523 12:35:34.174801    1073 plugins.go:83] Registered admission plugin "PodSecurityPolicy"
may 23 12:35:34 che-master.es atomic-openshift-master-api[1073]: I0523 12:35:34.174810    1073 plugins.go:83] Registered admission plugin "Priority"
may 23 12:35:34 che-master.es atomic-openshift-master-api[1073]: I0523 12:35:34.174824    1073 plugins.go:83] Registered admission plugin "SecurityContextDeny"
may 23 12:35:34 che-master.es atomic-openshift-master-api[1073]: I0523 12:35:34.174835    1073 plugins.go:83] Registered admission plugin "ServiceAccount"
may 23 12:35:34 che-master.es atomic-openshift-master-api[1073]: I0523 12:35:34.174848    1073 plugins.go:83] Registered admission plugin "DefaultStorageClass"
may 23 12:35:34 che-master.es atomic-openshift-master-api[1073]: I0523 12:35:34.174858    1073 plugins.go:83] Registered admission plugin "PersistentVolumeClaimResize"
may 23 12:35:34 che-master.es atomic-openshift-master-api[1073]: I0523 12:35:34.174867    1073 plugins.go:83] Registered admission plugin "PVCProtection"
may 23 12:35:34 che-master.es atomic-openshift-master-api[1073]: F0523 12:35:34.178774    1073 start_api.go:67] failed to create listener: failed to listen on 0.0.0.0:844
may 23 12:35:34 che-master.es origin-master-controllers[35277]: E0523 12:35:34.359790   35277 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/client-go/inform
may 23 12:35:34 che-master.es origin-master-controllers[35277]: E0523 12:35:34.398245   35277 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/client-go/inform

**Comment by ledboot** [comment]
@randy280872  i got a same problem, and i reslove it by redeploying all certificates.  you can try like this:
```
ansible-playbook -i <inventory_file> \
    /usr/share/ansible/openshift-ansible/playbooks/redeploy-certificates.yml
```
after that ,i get a error message like  "can not connect master api", because  api server not start yet, so i retry to run :

```
ansible-playbook -i /etc/ansible/inventory.ini  \
/usr/share/openshift-ansible/playbooks/deploy_cluster.yml
```

it's All Complete!  :)

**Comment by arprasto** [comment]
I am also facing same issue. when i do 'journalctl -xe', i can see below error line in logs:
`leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manag`

I am trying to install openshift3.9
