### ISSUE TITLE
How to disable Openshift Ansible Service Broker?

### ISSUE THREAD

**Issue by dharmit** [openshift/openshift-ansible#7305]
#### Description
By default, OpenShift Ansible Service Broker is enabled for 3.7 installation. [Docs Link](https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-openshift-ansible-broker).

I don't need OpenShift Ansible Service Broker to be enabled by default. It tries to claim the PV that I'm trying to attach to Jenkins (with persistent storage).

##### Version

```bash
$ ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

```bash
$ git describe
openshift-ansible-3.7.31-1-12-g0199c3b
```
##### Steps To Reproduce
This is default behavior. Just installing OpenShift v3.7 should suffice?

##### Expected Results
An option to disable OpenShift Ansible Service Broker in the Ansible hosts file or some other configuration option so that it doesn't try to claim the PV being attached to the cluster.

##### Observed Results
`openshift-ansible-service-broker` has a deployment called `asb-etcd ` which tries to claim the PV attached to it. Since I didn't know about this earlier, because I am not planning on using openshift ansible service broker yet, it took me quite some time to figure the actual issue when a PV I created for the Jenkins deployment didn't succeed in being claimed by a PVC.

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

```bash
$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
```

[Inventory file gist link](https://gist.github.com/dharmit/886d293a00fe32c8b57b344847ffa633)

**Comment by allen13** [comment]
Add this to your group_vars:
    openshift_enable_service_catalog: false

**Comment by dharmit** [comment]
Would that disable only the `openshift-ansible-service-broker` project from being created by default or the entire service catalog (the new UI, if I understand correctly) from coming up?

**Comment by dharmit** [comment]
I tried this and it prevents few things (CI/CD and Databases tabs on "Browse Catalog") from being installed by default. `openshift-ansible-service-broker` being one of those. However, I do need Jenkins (CI/CD tab on the "Browse Catalog" page) available. Anyway, it shouldn't be much of a pain to deploy Jenkins but OOTB integration with jenkins-kubernetes plugin is something I'm kind of interested in.

I'll close this issue. It'd still be nice to just prevent `openshift-ansible-service-broker` from being setup (if that's possible.) Thanks for your help.

**Comment by jlsalmon** [comment]
Could this be reopened? We have several custom service brokers, but we don't want the ansible broker to be installed. It would be great if there was an option analogous to `template_service_broker_install=false` for the ansible broker.

**Comment by jocelynthode** [comment]
@jlsalmon : This is possible although not documented, using `ansible_service_broker_install=false` and `ansible_service_broker_remove=true` if already installed.

https://github.com/openshift/openshift-ansible/blob/master/roles/ansible_service_broker/tasks/main.yml

**Comment by etoews** [comment]
Thanks a lot for the pointer @jocelynthode.  I opened an issue to update the docs at https://github.com/openshift/openshift-docs/issues/9889

**Comment by tech-mint** [comment]
> @jlsalmon : This is possible although not documented, using `ansible_service_broker_install=false` and `ansible_service_broker_remove=true` if already installed.
> 
> https://github.com/openshift/openshift-ansible/blob/master/roles/ansible_service_broker/tasks/main.yml

what playbook can uninstall it after 3.9 is up?
