### ISSUE TITLE
task: "Create the htpasswd file if needed" fails with AnsibleUndefinedVariable: 'list object' has no attribute 'items'

### ISSUE THREAD

**Issue by mbruzek** [openshift/openshift-ansible#7316]
#### Description

Provide a brief description of your issue here. For example:

> On a multi-master cluster the openshift-ansible install fails on an htpasswd task with an Ansible error:
```
Failure summary:


  1. Hosts:    master-0.scale-ci.example.com, master-1.scale-ci.example.com, master-2.scale-ci.example.com
     Play:     Configure masters
     Task:     Create the htpasswd file if needed
     Message:  All items completed
```

Looking in the log it seems to be an ansible object problem:
`AnsibleUndefinedVariable: 'list object' has no attribute 'items'`

##### Version

Please put the following version information in the code block
indicated below.

            "ansible 2.4.2.0", 
            "  config file = /etc/ansible/ansible.cfg", 
            "  configured module search path = [u'/home/cloud-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']", 
            "  ansible python module location = /usr/lib/python2.7/site-packages/ansible", 
            "  executable location = /usr/bin/ansible", 
            "  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]"

If you're operating from a **git clone**:

openshift-ansible-3.9.0-0.53.0-50-gcf0db55

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
        "atomic-openshift-utils-3.9.0-0.53.0.git.0.f8f01ef.el7.noarch", 
        "openshift-ansible-3.9.0-0.53.0.git.0.f8f01ef.el7.noarch"
```

##### Steps To Reproduce
1. Install OpenStack
2. Create the VMs with the provision.yml playbook:  
`source /home/cloud-user/keystonerc; ansible-playbook -vvv --user openshift -i inventory -i openshift-ansible/playbooks/openstack/inventory.py openshift-ansible/playbooks/openstack/openshift-cluster/provision.yml 2>&1 >> /home/cloud-user/openstack_provision.log`

3. Call the install playbook:  
`source /home/cloud-user/keystonerc; ansible-playbook -vvv --user openshift -i inventory -i openshift-ansible/playbooks/openstack/inventory.py openshift-ansible/playbooks/openstack/openshift-cluster/install.yml 2>&1 >> /home/cloud-user/openshift_install.log`

##### Expected Results
I expected the install to complete without an htpasswd error with my configuration that has worked on previous openshift-ansible 3.9 installations.

The htpasswd related part of OSEv3.yml when I ran this install is here:
```
# Allow authentication using an Apache HTTP server authentication file.
openshift_master_identity_providers:
- name: 'htpasswd_auth'
  login: 'true'
  challenge: 'true'
  kind: 'HTPasswdPasswordIdentityProvider'
  filename: '/etc/origin/master/htpasswd'
# Defining htpasswd users
openshift_master_htpasswd_users:
  - admin: 'admin'
  - developer: 'developer'
  - test: 'test'
 
# Configure how often node iptables rules are refreshed.
openshift_node_iptables_sync_period: 30s
```

##### Observed Results
All three masters are failing with an Ansible error in one of the htpasswd tasks. It looks like the object is not a list object but my config has not changed in quite some time and looks like a list object.

Here is the failure from the openshift_install.log

```
TASK [openshift_master : Create the htpasswd file if needed] *******************                
task path: /home/cloud-user/openshift-ansible/roles/openshift_master/tasks/main.yml:85          
Tuesday 27 February 2018  12:24:32 -0500 (0:00:00.231)       0:05:41.086 ******                  
failed: [master-2.scale-ci.example.com] (item={u'name': u'htpasswd_auth', u'challenge': u'true', u'login': u'true', u'kind': u'HTPasswdPasswordIdentityProvider', u'filename': u'/etc/origin/master
/htpasswd'}) => {                                                                                
    "changed": false,                                                                            
    "item": {                                                                                    
        "challenge": "true",                                                                    
        "filename": "/etc/origin/master/htpasswd",                                              
        "kind": "HTPasswdPasswordIdentityProvider",
        "login": "true",                        
        "name": "htpasswd_auth"                
    },                                          
    "msg": "AnsibleUndefinedVariable: 'list object' has no attribute 'items'"                                                                                                                      
}                                                                                                
failed: [master-1.scale-ci.example.com] (item={u'name': u'htpasswd_auth', u'challenge': u'true', u'login': u'true', u'kind': u'HTPasswdPasswordIdentityProvider', u'filename': u'/etc/origin/master
/htpasswd'}) => {                                                                                
    "changed": false,                                                                            
    "item": {
        "challenge": "true",
        "filename": "/etc/origin/master/htpasswd",
        "kind": "HTPasswdPasswordIdentityProvider",
        "login": "true",
        "name": "htpasswd_auth"
    },
    "msg": "AnsibleUndefinedVariable: 'list object' has no attribute 'items'"
}
failed: [master-0.scale-ci.example.com] (item={u'name': u'htpasswd_auth', u'challenge': u'true', u'login': u'true', u'kind': u'HTPasswdPasswordIdentityProvider', u'filename': u'/etc/origin/master
/htpasswd'}) => {
    "changed": false,
    "item": {
        "challenge": "true",
        "filename": "/etc/origin/master/htpasswd",
        "kind": "HTPasswdPasswordIdentityProvider",
        "login": "true",
        "name": "htpasswd_auth"
    },
    "msg": "AnsibleUndefinedVariable: 'list object' has no attribute 'items'"
}
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

I am using OpenShift on OpenStack installer in version 3.9. This has worked as recently as January 26 2018 but when we tried to redeploy the cluster the install failed with this htpasswd error.

Please contact me if you need more information.

**Comment by mbruzek** [comment]
I haven't seen this problem in a several deploys so closing this issue

**Comment by jjo** [comment]
This is happening for me while trying a 3.10 install from scratch:

* `inventory.cfg` relevant line:
```
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
```

* relevant ansible output (note how previous task succeeds):
```
TASK [openshift_control_plane : Install httpd-tools if needed] **********************************************************************************************************************
ok: [ip-x-x-x-x.ec2.internal] => (item={'challenge': 'true', 'login': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'name': 'htpasswd_auth'}) => {"attempts": 1, "changed": false, "item": {"challenge": "true", "kind": "HTPasswdPasswordIdentityProvider", "login": "true", "name": "htpasswd_auth"}, "msg": "", "rc": 0, "results": ["httpd-tools-2.4.6-80.el7_5.1.x86_64 providing httpd-tools is already installed"]}

TASK [openshift_control_plane : Create the htpasswd file if needed] *****************************************************************************************************************
failed: [ip-x-x-x-x.ec2.internal] (item={'challenge': 'true', 'login': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'name': 'htpasswd_auth'}) => {"changed": false, "item": {"challenge": "true", "kind": "HTPasswdPasswordIdentityProvider", "login": "true", "name": "htpasswd_auth"}, "msg": "AnsibleUndefinedVariable: 'list object' has no attribute 'items'"}

```

**Comment by jjo** [comment]
For other pour souls get hit by this: the error comes from the `template` module while parsing 
`openshift_master_htpasswd_users` (which needs to be a `dict`):
* Incorrect: `openshift_master_htpasswd_users=[{'admin': 'XXX'}]`
* Ok: `openshift_master_htpasswd_users={'admin': 'XXX'}`
