### ISSUE TITLE
"Package 'origin-3.7*' not found 

### ISSUE THREAD

**Issue by Raptus1** [openshift/openshift-ansible#7318]
#### Description

On a newly created fedora vbox I ran the pre-req check and it went ok, but the deploy cluster failed on the next step after get available origin version.

##### Version
ansible 2.4.3.0

If you're operating from a **git clone**:
openshift-ansible-3.9.0-0.53.0.59-gced2275b2

##### Steps To Reproduce
1. start fresh fedora 27 install in vbox
2. install the required software as mentioned in the openshift-ansible guide.
3. run pre-req yaml and then deploy-cluster yaml

##### Expected Results
get everything up and running on the latest version 3.7
```
Example command and output or error messages
```
during the task openshift_version:
"fatal: [localhost]: FAILED! => {"changed": false, "msg": "Package origin-3.7*' not found"}"

##### Observed Results
Describe what is actually happening.
The latest version is not being used.

**Comment by sbadakhc** [comment]
Seeing this also. Had to install manually.

**Comment by vrutkovs** [comment]
Please don't use `openshift-ansible-3.9` to install 3.7 - this branch expects `oc` to be at least 3.9. Use `release-3.7` branch instead.

Origin 3.7 is sadly not yet available in Fedora repos, you might have to use CentOS / RHEL as a target. Another option is to use Fedora Atomic - it would install a containerized version of Origin (the base for these containers would be CentOS though)
