### ISSUE TITLE
Install fails with 'already exists' not in oex_import_rhel_streams.stderr and oex_import_rhel_streams.rc != 0

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-ansible#732]
When I run the byo playbook with `deployment_type=enterprise`, I get a fatal error at the very end when trying to sync the examples and quickstarts:

```
TASK: [openshift_examples | Import RHEL streams] ****************************** 
fatal: [master.openshift.example.com] => error while evaluating conditional: 'already exists' not in oex_import_rhel_streams.stderr and oex_import_rhel_streams.rc != 0

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/config.retry

localhost                  : ok=9    changed=0    unreachable=0    failed=0   
master.openshift.example.com : ok=176  changed=55   unreachable=1    failed=0   
```

This seems to be caused by a recent commit, which adds `| bool` at the end of some `register: ` lines in the openshift_examples tasks.

https://github.com/openshift/openshift-ansible/commit/94c2ba099a87c3dc6b87f9bf916c1282a7266e45

If I remove `| bool` from the following line, an enterprise install succeeds again:
- https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/tasks/main.yml#L12
- https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/tasks/main.yml#L35

**Comment by detiber** [comment]
Looks related to https://github.com/openshift/openshift-ansible/pull/728

**Comment by abutcher** [comment]
@brenton this can be closed
