### ISSUE TITLE
Default storageClass hard-coded if cloud provider set

### ISSUE THREAD

**Issue by clcollins** [openshift/openshift-ansible#7345]
#### Description

The default storageClass is automatically set to the cloud provider if the cloud provider is specified in the inventory (see: roles/openshift_default_storage_class/defaults/main.yml)

This is not always desired.  For example, cheaper, more shareable NFS storage or some other storageClass may be desired before attaching dedicated disks so data can be shared between pods, reserving cloud-provider disks for tasks like database backends, etc.

Allow override of default storageClass setting during install, or ability to just not set as default.

##### Version

```
ansible 2.4.3.0

git-clone: yes, release-3.7 & release-3.9 branches

git describe: 
openshift-ansible-3.7.35-1 & openshift-ansible-3.9.1-1

rpm -q atomic-openshift-utils openshift-ansible
package atomic-openshift-utils is not installed
package openshift-ansible is not installed

```

##### Steps To Reproduce
1. Add cloud provider information to inventory.yml
2. Run installer
3. Check storageClass (oc describe storageClass)
4. Verify `IsDefaultClass:	Yes` is set for cloud provider volume

##### Expected Results

This is a feature request.  I'd like to be able to set something like `openshift_cloudprovider_vsphere_default_storageclass=False`

##### Observed Results
storageClass is hard-coded to Default

```
Name:		vsphere
IsDefaultClass:	Yes
Annotations:	storageclass.kubernetes.io/is-default-class=true
Provisioner:	kubernetes.io/vsphere-volume
Parameters:	diskformat=thin
Events:		<none>
```
##### Additional Information

```
Ansible Host: Fedora 27
OpenShift Nodes: RHEL Atomic Host 7.4.4
```

**Comment by dav1x** [comment]
Howdy @clcollins 

You can always use: 
openshift_storageclass_default=False

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_default_storage_class/tasks/main.yml#L6
