### ISSUE TITLE
libcloud package regressed to 2.0.0 in upstream instead of 2.2.0

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#7353]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/6916/test_pull_request_openshift_ansible_extended_conformance_gce/1384/

We are dependent on libcloud 2.2+, but suddenly we're getting 2.0.0

Blocks GCP

**Comment by smarterclayton** [comment]
Was coming from EPEL testing, looks like it got reverted.

**Comment by smarterclayton** [comment]
@sdodson @smunilla we probably need to get python2-libcloud 2.2.0 into some repo we own.  It didn't occur to me that we epel testing wouldn't pull it in.

**Comment by smarterclayton** [comment]
Rawhide has the right version.

**Comment by smarterclayton** [comment]
I'm going to work around this for now

**Comment by sdodson** [comment]
https://bodhi.fedoraproject.org/updates/?search=libcloud interesting that they produced a new build yesterday and that removed the older 2.2 build from epel testing before the new build landed there.
