### ISSUE TITLE
Upgrade to 3.9 doesn't remove NoVolumeNodeConflict from scheduler predicates

### ISSUE THREAD

**Issue by jpeeler** [openshift/openshift-ansible#7355]
#### Description

atomic-openshift-master-controllers.service failed with this error:
Invalid configuration: Predicate type not found for NoVolumeNodeConflict

##### Version

I was using git checkouts of the 3.7 and 3.9 release branches.

#### Necessary fix

I removed the NoVolumeNodeConflict manually from /etc/origin/master/scheduler.json and was able to start the service successfully.

**Comment by jpeeler** [comment]
This might be related to https://github.com/openshift/openshift-ansible/pull/7089/

**Comment by sdodson** [comment]
Tracked here https://bugzilla.redhat.com/show_bug.cgi?id=1549971

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-ansible/pull/7333 fixed this
