### ISSUE TITLE
Add Kuryr option to use public network instead of subnet

### ISSUE THREAD

**Issue by tomassedovic** [openshift/openshift-ansible#7383]
#### Description

The Kuryr SDN requires the `kuryr_openstack_public_subnet_id` to be set. This is the OpenStack subnet that provides floating IP addresses.

In a lot of OpenStack deployments, the external/public subnet is not accessible to the users, only the public network. Kuryr now supports using either:

https://bugs.launchpad.net/kuryr-kubernetes/+bug/1749921

But the option to use networks is missing from the Kuryr module in openshift-ansible.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

    ansible 2.4.2.0

If you're operating from a **git clone**:

* The output of `git describe`

    openshift-ansible-3.10.0-0.1.0-65-gf622e84

cc @celebdor

**Comment by yboaronn** [comment]
Adding this comment to update that this issue assigned to me.
(as I'm not able yet to assign myself to openshift-ansible issues)

**Comment by luis5tb** [comment]
this was added long ago... Closing it
