### ISSUE TITLE
Openshift ansible failed at openshift_node : Wait for master API on centos 7

### ISSUE THREAD

**Issue by maximegy** [openshift/openshift-ansible#7417]
#### Description

Provide a brief description of your issue here. For example:

5 CentOS 7 VM:
- 3 Master
- 5 Nodes
1 DNS resolving thunder.io

Using openshift ansible v3.7.0

this is the inventory:
```
[OSEv3:children]
masters
nodes
etcd
glusterfs

[masters]
172.16.1.31 openshift_ip=172.16.1.31
172.16.1.32 openshift_ip=172.16.1.32
172.16.1.33 openshift_ip=172.16.1.33

[etcd]
172.16.1.31 openshift_ip=172.16.1.31
172.16.1.32 openshift_ip=172.16.1.32
172.16.1.33 openshift_ip=172.16.1.33

[nodes]
172.16.1.31 openshift_ip=172.16.1.31 openshift_schedulable=false
172.16.1.32 openshift_ip=172.16.1.32 openshift_schedulable=false
172.16.1.33 openshift_ip=172.16.1.33 openshift_schedulable=false
172.16.1.34 openshift_ip=172.16.1.34 openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
172.16.1.35 openshift_ip=172.16.1.35 openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

[glusterfs]
172.16.1.31 glusterfs_ip=172.16.1.31 glusterfs_devices='[ "/dev/gfssda", "/dev/gfssdb" ]'
172.16.1.32 glusterfs_ip=172.16.1.32 glusterfs_devices='[ "/dev/gfssda", "/dev/gfssdb" ]'
172.16.1.33 glusterfs_ip=172.16.1.33 glusterfs_devices='[ "/dev/gfssda", "/dev/gfssdb" ]'

[OSEv3:vars]
ansible_ssh_user=root
enable_excluders=False
enable_docker_excluder=False
ansible_service_broker_install=False

containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

openshift_node_kubelet_args={'pods-per-core': ['10']}

deployment_type=origin
openshift_deployment_type=origin

openshift_master_cluster_method=native
openshift_master_cluster_hostname=console.openshift.io
openshift_master_cluster_public_hostname=console.openshift.io

openshift_release=v3.7.0
openshift_pkg_version=v3.7.0
openshift_image_tag=v3.7.0
openshift_service_catalog_image_version=v3.7.0
template_service_broker_image_version=v3.7.0
openshift_metrics_image_version=v3.7.0
#openshift_logging_image_version=v3.7.0

osm_use_cockpit=true
openshift_metrics_install_metrics=True
openshift_logging_install_logging=True

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

openshift_public_hostname=console.openshift.io
openshift_master_default_subdomain=apps.openshift.io
```

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
```
ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### Steps To Reproduce
Minimal install of Centos 7
Launch ansible-playbook -i ./inventory-glusterfs.ini openshift-ansible/playbooks/byo/config.yml
Wait for TASK [openshift_node : Wait for master API to become available before proceeding] ****

2. [step 2]

##### Expected Results

OpS install correctly

##### Observed Results
Describe what is actually happening.

```
FAILED - RETRYING: Wait for master API to become available before proceeding (1 retries left).
fatal: [172.16.1.34]: FAILED! => {"attempts": 120, "changed": false, "cmd": ["curl", "--silent", "--t": "0:00:00.099533", "end": "2018-01-24 17:10:02.637832", "msg": "non-zero return code", "rc": 60, "s
fatal: [172.16.1.35]: FAILED! => {"attempts": 120, "changed": false, "cmd": ["curl", "--silent", "--t": "0:00:00.099456", "end": "2018-01-24 17:10:30.403782", "msg": "non-zero return code", "rc": 60, "s
        to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP ******************************************************************************************
172.16.1.31                : ok=442  changed=37   unreachable=0    failed=0
172.16.1.32                : ok=373  changed=29   unreachable=0    failed=0
172.16.1.33                : ok=373  changed=29   unreachable=0    failed=0
172.16.1.34                : ok=146  changed=5    unreachable=0    failed=1
172.16.1.35                : ok=145  changed=5    unreachable=0    failed=1
localhost                  : ok=14   changed=0    unreachable=0    failed=0

INSTALLER STATUS ************************************************************************************
Initialization             : Complete
Health Check               : Complete
etcd Install               : Complete
Master Install             : Complete
Master Additional Install  : Complete
Node Install               : In Progress
        This phase can be restarted by running: playbooks/byo/openshift-node/config.yml

Failure summary:

  1. Hosts:    172.16.1.34, 172.16.1.35
     Play:     Configure nodes
     Task:     Wait for master API to become available before proceeding
     Message:  non-zero return code

```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
if I run from my failed nodes :
curl --tlsv1.2 --cacert origin/master/ca-bundle.crt https://console.thunder.io:8443/healthz/ready
this error prompt:
curl: (77) Problem with the SSL CA cert (path? access rights?)
```

there is the content of origin/master/ca-bundle.crt of the master (actually 172.16.1.31)
```
ls /etc/origin/master/
admin.crt                          ca.crt                frontproxy-ca.crt         master.etcd-ca.crt         master.proxy-client.key               openshift-master.crt         service-signer.crt
admin.key                          ca.key                front-proxy-ca.key        master.etcd-client.crt     master.server.crt                     openshift-master.key         service-signer.key
admin.kubeconfig                   ca.serial.txt         frontproxy-ca.key         master.etcd-client.csr     master.server.key                     openshift-master.kubeconfig  session-secrets.yaml
aggregator-front-proxy.crt         client-ca-bundle.crt  frontproxy-ca.serial.txt  master.etcd-client.key     named_certificates                    policy.json
aggregator-front-proxy.key         etcd.server.crt       htpasswd                  master.kubelet-client.crt  openshift-aggregator.crt              scheduler.json
aggregator-front-proxy.kubeconfig  etcd.server.key       master-config.yaml        master.kubelet-client.key  openshift-aggregator.key              serviceaccounts.private.key
ca-bundle.crt                      front-proxy-ca.crt    master-config.yaml.orig   master.proxy-client.crt    openshift-ansible-catalog-console.js  serviceaccounts.public.key
```

Can you help me ?
Thx a lot

**Comment by obaroikoh** [comment]
Run `curl --tlsv1.2 --cacert origin/master/ca-bundle.crt https://console.thunder.io:8443/healthz/ready` with sudo and share the output.

**Comment by maximegy** [comment]
sudo curl --tlsv1.2 --cacert origin/master/ca-bundle.crt https://console.thunder.io:8443/healthz/ready
curl: (77) Problem with the SSL CA cert (path? access rights?)

**Comment by obaroikoh** [comment]
HI @maximegy sorry for the late response. The path to crt file is usually /etc/origin/master/ca-bundle.crt . So run `sudo curl  --verbose --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt https://console.thunder.io:8443/healthz/ready`

**Comment by maximegy** [comment]
`sudo curl --verbose --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt https://console.thunder.io:8443/healthz/ready
* About to connect() to console.thunder.io port 8443 (#0)
*   Trying 172.16.1.21...
* Connected to console.thunder.io (172.16.1.21) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* Closing connection 0
curl: (77) Problem with the SSL CA cert (path? access rights?)
`

**Comment by maximegy** [comment]
Maybe is a cert problem between master and node and it can't connect with https ?

**Comment by maximegy** [comment]
I've try to scp the content of master /etc/origin:
`examples  generated-configs  hosted  master  node  openvswitch  sdn`
to node /etc/origin

When I do:
```
sudo curl --tlsv1.2 --cacert /etc/origin/master/ca-bundle.crt https://console.thunder.io:8443/healthz/ready
curl: (60) Peer's certificate issuer has been marked as not trusted by the user.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```
And if I add -k options it works
```
sudo curl --tlsv1.2 --cacert /etc/origin/master/ https://console.thunder.io:8443/healthz/ready -k
ok
```
But if I run the playbook again it don't work

**Comment by obaroikoh** [comment]
run `openssl x509 -in /etc/origin/master/ca-bundle.crt -text -noout` as it seems you are using a named certificate

**Comment by maximegy** [comment]
Where ? on nodes or on master

**Comment by obaroikoh** [comment]
try it on both. In the meantime I am trying to see If I can reproduce the error.

**Comment by maximegy** [comment]
if i don't copy the master folder on nodes they are don't generated so there is the result on the master
```
 openssl x509 -in /etc/origin/master/ca-bundle.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=openshift-signer@1520018145
        Validity
            Not Before: Mar  2 19:15:44 2018 GMT
            Not After : Mar  1 19:15:45 2023 GMT
        Subject: CN=openshift-signer@1520018145
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:94:fe:28:fe:81:3c:ab:9f:2e:d4:84:77:b1:09:
                    a5:57:44:af:3e:3f:c8:be:7c:66:b3:f0:06:02:fc:
                    a9:5b:5e:28:3d:1a:e6:3a:c1:88:66:bf:f1:74:cf:
                    11:56:ed:8e:ad:ef:98:a4:ed:d1:bb:40:7a:ae:44:
                    98:45:1b:e6:25:e9:2c:25:f9:fb:a8:6c:87:27:bc:
                    12:47:be:db:22:04:7c:fd:50:d1:87:bf:d0:3e:f7:
                    06:b9:ba:fc:c0:96:c1:c2:fd:78:f9:80:d3:0e:05:
                    36:16:04:38:42:ce:c1:1f:20:1a:83:f6:e1:62:61:
                    53:9f:59:cf:71:cf:db:de:0d:2e:c5:fe:7e:4d:10:
                    9f:8d:69:59:87:56:72:07:3b:28:7d:fb:47:eb:71:
                    3a:ee:da:e8:3c:02:61:b4:3c:6b:27:57:6e:01:a6:
                    62:a5:92:18:c1:57:7e:be:af:33:e7:b3:e7:c7:ec:
                    7f:ef:5e:89:15:03:8e:26:c9:5f:e0:d4:e2:c8:10:
                    de:c3:24:80:af:6f:8b:5a:16:01:93:5b:46:fd:e6:
                    80:3b:5a:42:b4:70:94:02:6a:45:fb:8f:a1:92:20:
                    00:5e:d5:8d:27:62:38:b5:8b:b6:7e:f6:5e:23:3b:
                    e4:e2:09:d2:39:c4:d4:e0:fb:de:c4:d3:bb:09:58:
                    0e:1d
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Certificate Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
         12:fe:b1:65:96:e8:d4:66:a1:89:b2:8f:37:f9:65:a8:7b:71:
         25:73:85:76:b7:3f:55:51:9e:86:41:ad:36:ba:f2:41:23:35:
         4a:ba:0d:be:f4:51:6c:63:15:5d:6a:3c:f0:d1:6c:60:62:79:
         b1:a5:c9:71:e2:b5:5a:6a:fc:dc:2e:cb:51:e4:8e:34:b4:a6:
         6b:23:c3:0d:45:b9:59:15:50:25:e1:1f:29:4a:c5:0b:2f:a4:
         cc:a4:c2:0d:da:3d:f1:43:a3:fb:74:0e:52:6c:37:41:32:74:
         29:f3:a9:bf:52:97:c8:7a:e0:9a:f8:99:51:2b:a8:0d:9e:01:
         a8:14:1f:ce:4b:56:04:cd:3c:46:30:69:01:e3:ac:39:86:59:
         25:25:cd:29:8d:aa:13:b4:36:77:26:47:64:83:f2:a6:91:14:
         4f:a7:31:b5:75:24:3e:95:08:ef:fe:2c:59:51:d0:c6:fc:46:
         d8:bf:b8:f3:f8:1b:3f:a5:4d:33:4b:5b:5b:c0:ea:97:a7:39:
         b3:09:35:3f:53:24:24:d9:65:09:17:0f:89:62:93:30:72:0a:
         14:ea:84:56:32:f7:9b:68:14:4d:39:6b:84:78:94:f2:d7:8e:
         eb:ad:8c:3c:30:2e:af:b6:b7:e7:f7:81:f9:45:fc:58:f4:0a:
         84:12:c7:30
```

**Comment by maximegy** [comment]
I find the ansible file with the command, so i add -k to see if it works

**Comment by obaroikoh** [comment]
Okay you can find it in /playbooks/common/openshift-master/tasks/wire_aggregator.yml

**Comment by obaroikoh** [comment]
From the output of  `openssl x509 -in /etc/origin/master/ca-bundle.crt -text -noout` you may have to get a certificate for console.thunder.io of you can generate a self-signed certificate, though not recommended. Let me know if it worked for you after adding tag -k tag to the playbook

**Comment by maximegy** [comment]
I Find it on openshift-ansible/roles/openshift_node/tasks/config.yml line 60

**Comment by maximegy** [comment]
behind console.thunder.io it's the master so I must create one for console? How can I do this ?

**Comment by obaroikoh** [comment]
The line I think you are looking for is on line 213. Now to answer your question. If you already have a certificate for console.thunder.io you can pass it a variable in ansible. See [docs](https://docs.openshift.com/container-platform/3.4/install_config/install/advanced_install.html#advanced-install-custom-certificates) for more

**Comment by maximegy** [comment]
it is a future problem "Verify API Server"
the file openshift-ansible/roles/openshift_node/tasks/config.yml at line 60 it's "Wait for master API to become available before proceeding"

**Comment by maximegy** [comment]
Verify API server Works fine, I wait to see if "Wait for master API to become available before proceeding" is working

**Comment by maximegy** [comment]
How can i create a cert for console ?

**Comment by obaroikoh** [comment]
my bad. I was looking at the wrong file.

Here's an easy way to get one `openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /path/to/new.key -out /path/to/new.crt`

**Comment by maximegy** [comment]
it block at openshift_manage_node : Wait for Node Registration

**Comment by maximegy** [comment]
```
TASK [openshift_manage_node : Wait for Node Registration] *******************************************************************************************************************************************************
FAILED - RETRYING: Wait for Node Registration (50 retries left).
ok: [172.16.1.32 -> 172.16.1.31]
ok: [172.16.1.31 -> 172.16.1.31]
ok: [172.16.1.33 -> 172.16.1.31]
FAILED - RETRYING: Wait for Node Registration (50 retries left).
FAILED - RETRYING: Wait for Node Registration (49 retries left).
FAILED - RETRYING: Wait for Node Registration (49 retries left)
```

**Comment by maximegy** [comment]
```
AILED - RETRYING: Wait for Node Registration (1 retries left).
fatal: [172.16.1.34 -> 172.16.1.31]: FAILED! => {"attempts": 50, "changed": false, "results": {"cmd": "/usr/local/bin/oc get node 172.16.1.34 -o json -n default", "results": [{}], "returncode": 0, "stderr": "Error from server (NotFound): nodes \"172.16.1.34\" not found\n", "stdout": ""}, "state": "list"}
fatal: [172.16.1.35 -> 172.16.1.31]: FAILED! => {"attempts": 50, "changed": false, "results": {"cmd": "/usr/local/bin/oc get node 172.16.1.35 -o json -n default", "results": [{}], "returncode": 0, "stderr": "Error from server (NotFound): nodes \"172.16.1.35\" not found\n", "stdout": ""}, "state": "list"}

```

**Comment by obaroikoh** [comment]
Try again but this time with the -vvv tag. We need to know exactly what's wrong

**Comment by maximegy** [comment]
Could it be easier to create the OPC infra with only 3 Master 3Nodes and add the 2 nodes after ?

**Comment by maximegy** [comment]
`ansible-playbook -i ./ThunderInfra/inventory-glusterfs.ini openshift-ansible/playbooks/byo/config.yml -vvv`
?
Do I remove the -k i Add in the ansible file ?

**Comment by obaroikoh** [comment]
No don't remove it

**Comment by obaroikoh** [comment]
> Could it be easier to create the OPC infra with only 3 Master 3Nodes and add the 2 nodes after ?

Honestly, I think the installation should work regardless of the number of nodes you are starting with. Removing nodes doesn't make it any easier. I may be wrong though

**Comment by maximegy** [comment]
I think about it because all the process on the 3 master/node work

**Comment by obaroikoh** [comment]
I just checked your hosts file again and I see that you don't have machines for nodes. Is there a reason for that?

**Comment by maximegy** [comment]
I use 5 VM, 3 Master/Node and 2 Node only

**Comment by maximegy** [comment]
I don't know if my inventory file is correct maybe there are missing options or there are poorly configured options

**Comment by maximegy** [comment]
because kubernetes can't be configured with only 2 master

**Comment by obaroikoh** [comment]
Though I am newbie like you, I think you don't need 3 masters for it to work. Let's try something out.

```
172.16.1.34 openshift_ip=172.16.1.34 openshift_node_labels="{'region': 'node'}"
172.16.1.35 openshift_ip=172.16.1.35 openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
```

Look for the above in your host file and replace what you have with it. Then try again

**Comment by mkgin** [comment]
I ran into something similar... first attempt deploying a test cluster with the scripts and rpm based install.
Will have another look on Monday....

```
 1. Hosts:    os-test-master
     Play:     Configure masters
     Task:     restart master api
     Message:  Unable to restart service origin-master-api: Job for origin-master-api.service failed because the control process exited with error code. See "systemctl status origin-master-api.service" and "journalctl -xe" for details.
```
1 master, 2 nodes
openshift-ansible v3.7.0
ansible 2.3.2.0 
CentOS-7.4

**Comment by maximegy** [comment]
I am testing with only 3VM -> 3Master/node
It works I don't have these problem but I have a new problem when ansible verify that TSB is running
the command prompt this error:
```
curl -k https://apiserver.openshift-template-service-broker.svc/healthz
curl: (7) Failed connect to apiserver.openshift-template-service-broker.svc:443; Connexion refusée
```

**Comment by isaldarriaga** [comment]
Default number of retries for this kind of operation (restart service in openshift node) is 3. 

Depending on your mileage this is not enough to let the services (master-api, etcd, origin, etc) to start in time in between ansible tasks. 

i just raised the number to 30 and the installation worked to me!

you may find the following script handy for making this change at the openshift-ansible project level, also to run the openshift with the desired playbook or the default one (playbooks/deploy_cluster.yaml), and to activate logging.

======================BEGIN=======================
`#!/usr/bin/env bash`
`PLAYBOOK=${1:-"playbooks/deploy_cluster.yml"}`

`CURDIR=$PWD`
`DOMAIN=$(echo $CURDIR | awk -F '/' '{print $4}')`

`cd ~/$DOMAIN/dev-ops/kube-prod/origin`

`echo && echo "Downloading openshift-ansible installer.." && echo`

`mkdir --parents openshift-ansible && git clone https://github.com/openshift/openshift-ansible openshift-ansible && cd openshift-ansible && git checkout release-3.9 && for file in $(find . | grep "\.yml") ; do cat $file | grep "retries: 3$" && sed -i "s@retries: 3@retries: 30@g" $file && echo " ($file) => " && cat $file | grep "retries: 30$" && echo "========================"; done && cd ..`

`echo && echo "Setting up logging.." && echo`

`sudo touch /var/log/ansible.log && sudo chmod 777 /var/log/ansible.log && sudo sed -i "s@#log_path = /var/log/ansible.log@log_path = /var/log/ansible.log@g" /etc/ansible/ansible.cfg`

`echo && echo "Running playbook: ~/$DOMAIN/dev-ops/kube-prod/origin/openshift-ansible/$PLAYBOOK .." && echo`

`ansible-playbook -vvv -i ~/$DOMAIN/dev-ops/kube-prod/origin/assets/inventory.ini openshift-ansible/$PLAYBOOK`

`cd $CURDIR`

======================END=======================

save the content to **`install-openshift.sh`**, and run it as:

**`sh install-openshift.sh`**

or

**`sh install-openshift.sh relative/path/to/playbook/file.yaml`** (useful for submodule retries / relative path to openshift-ansible folder)

the paths in the script assume you have:

1. your project at /home/$USER/<your-project-folder>
2. your working directory is: /home/$USER/<your-project-folder>/dev-ops/kube-prod/origin
3. your ansible config file at: /etc/ansible/ansible.cfg (fedora 28)
4. you want verbose output to /var/log/ansible.log

feel free to change the paths to your needs.
