### ISSUE TITLE
Deploy cluster playbook does not exist in release3.7 branch

### ISSUE THREAD

**Issue by masterkorp** [openshift/openshift-ansible#7418]
Hello,

I was advidsed to use `release-3.7` branch on issue #7416 but the playbook ``deploy_cluster`` [does not exist](https://github.com/openshift/openshift-ansible/tree/release-3.7/playbooks)

How should I deploy a cluster?

Regards,
Alfredo Palhares

**Comment by obaroikoh** [comment]
You won't find the deploy_cluster.yml in that release. To the best of my knowledge, `openshift-ansible/playbooks/byo/config.yml` does the same thing.

**Comment by masterkorp** [comment]
@obaroikoh thank you.

Honestly I just want the more up to date possible and release 3.7 does seems to be a bit outdated

**Comment by obaroikoh** [comment]
@masterkorp You're right. You can try the master branch which I suppose should be the most up to date. However, from the readme it works best with the newest origin release in development. What version of origin are you using?

**Comment by masterkorp** [comment]
@obaroikoh Oh, its my fault. I just noticed that i set up the varible `openshift_release=3.7` (which is the default value on the example file. I did overlook it.

How do I set it to use master?

**Comment by obaroikoh** [comment]
@masterkorp If you cloned openshift-ansible, it will be on the master branch by default. You can 
`git checkout --track origin/release-3.7 ` to make your ansible installer correspond with the origin release you have specified. Unless you want to experiment I wouldn't advice you use the most recent release of origin. 

I hope that answers your question.

**Comment by masterkorp** [comment]
@obaroikoh Actually that did not happen, branch master uses 3.7 by default, check [the hosts file](https://github.com/openshift/openshift-ansible/blob/master/inventory/hosts.localhost#L12)

**Comment by obaroikoh** [comment]
@masterkorp My bad. I thought you were using a custom hosts file. Why not talk me through what you want to do so I can have a better understanding and advise appropriately.

**Comment by masterkorp** [comment]
@obaroikoh Thank you, I will

Honestly for now, I just a simple single master and 3 nodes setup, so i can test deployments and such.

So far I have use the ``hosts.localhost` as base and modifiied it to this state:
```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
# if your target hosts are Fedora uncomment this
#ansible_python_interpreter=/usr/bin/python3
openshift_deployment_type=origin
openshift_release=3.7
osm_cluster_network_cidr=10.128.0.0/14
openshift_portal_net=172.30.0.0/16
osm_host_subnet_length=9
# localhost likely doesn't meet the minimum requirements
openshift_disable_check=disk_availability,memory_availability

[masters]
devops-1 ansible_host=10.0.14.90

[etcd]
devops-1 ansible_host=10.0.14.90

[nodes]
devops-1 ansible_host=10.0.14.90 openshift_schedulable=true
devops-3 ansible_host=10.0.14.92 openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
devops-4 ansible_host=10.0.14.93 openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
```

So since I already used the 3.7 install that was set on that file, I gueess I shall checkout to the ``release-3.7```branch and run it from there? 
I would use what is the "most recomended" version to be honest. I am just not sure what steps should I take now.

**Comment by masterkorp** [comment]
I did a succesful config run, but now the web interface does not seem to be deployed #7420

**Comment by masterkorp** [comment]
@obaroikoh It does not, either I am going to the wrong url.

What is the default url? 

How can I debug?

**Comment by obaroikoh** [comment]
@masterkorp the default url is host_ip:port, in you case,  https://10.0.14.90:8443

Please confirm you didn't omit the 's' in https

**Comment by masterkorp** [comment]
Thank you it works now. I am closing this ticket.
