### ISSUE TITLE
Lost support for docker 1.12.x on 3.7.x branch

### ISSUE THREAD

**Issue by mercer** [openshift/openshift-ansible#7442]
#### Description

Playbook no longer works, with no change on our side, e.g. playbook tag, amazon ami, docker version. It worked fine a few days ago, started failing today.

##### Versions

```
$ ansible --version
ansible 2.3.2.0
  config file = /some/path/ansible.cfg
  configured module search path = [u'../../../common/library']
  python version = 2.7.13 (default, Nov 23 2017, 15:37:09) [GCC 6.3.0 20170406]
```

```
$ git describe
openshift-ansible-3.7.14-1
```

```
$ docker --version
Docker version 1.12.5, build 047e51b/1.12.5
```

##### Steps To Reproduce
1. Create aws hosts for master, slave
2. Install docker 1.12.x yourself
3. Run openshift-ansible-3.7.14-1 (older tag) or openshift-ansible-3.7.37-1 (latest tag today)

##### Expected Results
Running openshift ansible 3.7.x succeeds.

##### Observed Results

Playbook fails when installing openshift with "Failing check names are shown in the failure details above. Some checks may be configurable by variables if your requirements are different from the defaults; consult check documentation.", and "Some required package(s) are available at a version", that is higher than requested", docker-1.13.1", This will prevent installing the version you requested. Please check your enabled repositories or adjust openshift_release."

For a full log, [playbook-fail.log](https://github.com/openshift/openshift-ansible/files/1792813/playbook-fail.log)

##### Workaround

Playbook succeeds when you run it with `--extra-vars "openshift_disable_check=package_version"`.

##### Additional Information

```
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```

```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=user
ansible_become=true
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_pipelining='True'
deployment_type=origin
openshift_cloudprovider_kind=aws
openshift_cloudprovider_aws_access_key=key
openshift_cloudprovider_aws_secret_key=secret
openshift_clusterid=clusterid

openshift_master_identity_providers=[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]

[masters]
10.0.201.21

[nodes]
10.0.201.21
10.0.201.22 openshift_node_labels="{'region': 'infra'}" openshift_docker_options="--log-driver json-file"
10.0.201.23 openshift_node_labels="{'region': 'infra'}" openshift_docker_options="--log-driver json-file"
10.0.201.24 openshift_node_labels="{'region': 'infra'}" openshift_docker_options="--log-driver json-file"

[etcd]
10.0.201.21
```

**Comment by vrutkovs** [comment]
`docker-1.13` has become available in rhel7 extras recently. PR #7347 should fix it
