### ISSUE TITLE
minishift --metrics fails to start for v3.7.1

### ISSUE THREAD

**Issue by paidhi** [openshift/openshift-ansible#7487]
#### Description

The option to enable metrics with `minishift` fails to deploy for OpenShift v3.7.1.

I reported this issue at https://github.com/minishift/minishift/issues/2110 but was asked to report it to OpenShift/origin instead. Since the problem seems to be a missing tag for `openshift/origin-ansible` on DockerHub I am guessing this is the correct place to report this problem.

##### Version

* Minishift version: v1.14.0+1ec5877
* OS: macOS (10.13.3)
* Hypervisor: xhyve

##### Steps To Reproduce
1. `minishift start --metrics --alsologtostderr`

##### Expected Results

Create and deploy pods for Hawkular.

##### Observed Results
The log states a failure in pulling image "openshift/origin-ansible:v3.7.1". Tag v3.7.1 does not exist on DockerHub (https://hub.docker.com/r/openshift/origin-ansible/tags/). I assume the missing tag is the cause of this problem.
The described problem does not occur if minishift is told to run `--openshift-version=v3.7.0` since a tag `v3.7.0` does exist for openshift/origin-ansible on DockerHub.

**Comment by mshahat** [comment]
same here +1

**Comment by paidhi** [comment]
It looks like `--metrics` and `--logging` has been broken for some time and will not be fixed any time soon. The options have been remove from minishift as of v1.16.0.
https://github.com/minishift/minishift/releases/tag/v1.16.0
https://github.com/minishift/minishift/issues/2234
