### ISSUE TITLE
OpenShift Health Checks: Some required package(s) are available at a version that is higher than requested docker-1.13.1

### ISSUE THREAD

**Issue by mfojtik** [openshift/openshift-ansible#7518]
Seen here: https://openshift-gce-devel.appspot.com//build/origin-ci-test/pr-logs/pull/18954/test_pull_request_origin_extended_conformance_install/9058/

```
Failure summary:


  1. Hosts:    localhost
     Play:     OpenShift Health Checks
     Task:     Run health checks (install) - EL
     Message:  One or more checks failed
     Details:  check "package_version":
               Some required package(s) are available at a version
               that is higher than requested
                 docker-1.13.1
               This will prevent installing the version you requested.
               Please check your enabled repositories or adjust openshift_release.
```

**Comment by stevekuznetsov** [comment]
This affects release-3.7 branch.

**Comment by stevekuznetsov** [comment]
Do we want to address this with an excluder?

**Comment by naumannt** [comment]
Have the same problem when trying to install a cluster using [openshift-ansible-contrib](https://github.com/openshift/openshift-ansible-contrib). Is there a way to work around this without disabling the version checks, or would that be safe?

**Comment by stevekuznetsov** [comment]
Don't have a version of `docker` available that's higher than you need -- `yum` will install it instead of whatever you ask for.

**Comment by nrwahl2** [comment]
Found the following:

-  atomic-openshift-docker-excluder allows docker-1.13 on OpenShift 3.7 (https://bugzilla.redhat.com/show_bug.cgi?id=1554174)
- OpenShift 3.7 now has docker-1.13, or are failing to install/update as a result. (https://access.redhat.com/solutions/3376031)

**Comment by dungdm93** [comment]
Same issue.

**Comment by naumannt** [comment]
@stevekuznetsov

> Don't have a version of docker available that's higher than you need -- yum will install it instead of whatever you ask for.

We did not install anything by hand. I even downgraded docker to 1.12 using yum on each node, but the error still persists. Is there no workaround for this?

**Comment by Ananasr** [comment]
Hello,
I face the same problem and a workaround I found is to update the file `roles/openshift_health_checker/openshift_checks/package_version.py` : 
```python
openshift_to_docker_version = {
        (3, 1): "1.8",
        (3, 2): "1.10",
        (3, 3): "1.10",
        (3, 4): "1.12",
        (3, 5): "1.12",
        (3, 6): "1.12",
        (3, 7): ["1.12", "1.13.1"], # <== here add the docker version that you want
        (3, 8): "1.12",
        (3, 9): ["1.12", "1.13"],
}
```

Don't forget to remove any `.pyc` file.

**Comment by sdodson** [comment]
Fixed in https://github.com/openshift/openshift-ansible/pull/7627
