### ISSUE TITLE
openshift_hosted_registry_storage_openstack_volumeID variable is not used by playbooks

### ISSUE THREAD

**Issue by mgrzybek** [openshift/openshift-ansible#7534]
#### Description

According to the official documentation (https://docs.openshift.org/latest/install_config/install/advanced_install.html#advanced-install-registry-storage), the following variables can be set, for example:
```openshift_hosted_registry_storage_kind=openstack
openshift_hosted_registry_storage_access_modes=['ReadWriteOnce']
openshift_hosted_registry_storage_openstack_filesystem=ext4
openshift_hosted_registry_storage_openstack_volumeID=3a650b4f-c8c5-4e0a-8ca5-eaee11f16c57
openshift_hosted_registry_storage_volume_size=10Gi
```
Looking for their usage by the playbooks leads me to the conclusion that some of them are ignored. For example:
```
$ pwd
/home/mgrzybek/ansible/openshift/cluster/openshift-ansible
$ git branch 
* master
$ grep -Rn openshift_hosted_registry_storage_openstack_volumeID 2>/dev/null *
inventory/hosts.example:525:#openshift_hosted_registry_storage_openstack_volumeID=3a650b4f-c8c5-4e0a-8ca5-eaee11f16c57
playbooks/openstack/sample-inventory/group_vars/all.yml:128:## `openshift_hosted_registry_storage_openstack_volumeID`.
playbooks/openstack/sample-inventory/group_vars/OSEv3.yml:35:#openshift_hosted_registry_storage_openstack_volumeID: "{{ lookup('os_cinder', openshift_openstack_cinder_hosted_registry_name).id }}"
playbooks/openstack/sample-inventory/group_vars/OSEv3.yml:39:#openshift_hosted_registry_storage_openstack_volumeID: e0ba2d73-d2f9-4514-a3b2-a0ced507fa05
playbooks/openstack/configuration.md:345:* `openshift_hosted_registry_storage_openstack_volumeID`: e0ba2d73-d2f9-4514-a3b2-a0ced507fa05
```
I can only find `openshift_hosted_registry_storage_openstack_volumeID` in definition and example files.

Same thing with version 3.9:
```
$ git checkout remotes/origin/release-3.9
$ git branch
* (HEAD détachée sur origin/release-3.9)
  master
$ grep -Rn openshift_hosted_registry_storage_openstack_volumeID 2>/dev/null *
inventory/hosts.example:525:#openshift_hosted_registry_storage_openstack_volumeID=3a650b4f-c8c5-4e0a-8ca5-eaee11f16c57
playbooks/openstack/advanced-configuration.md:568:    #openshift_hosted_registry_storage_openstack_volumeID: "{{ lookup('os_cinder', openshift_openstack_cinder_hosted_registry_name).id }}"
playbooks/openstack/advanced-configuration.md:599:    #openshift_hosted_registry_storage_openstack_volumeID: e0ba2d73-d2f9-4514-a3b2-a0ced507fa05
playbooks/openstack/advanced-configuration.md:602:Note the `openshift_hosted_registry_storage_openstack_volumeID` and
playbooks/openstack/sample-inventory/group_vars/all.yml:84:## `openshift_hosted_registry_storage_openstack_volumeID`.
playbooks/openstack/sample-inventory/group_vars/OSEv3.yml:35:#openshift_hosted_registry_storage_openstack_volumeID: "{{ lookup('os_cinder', openshift_openstack_cinder_hosted_registry_name).id }}"
playbooks/openstack/sample-inventory/group_vars/OSEv3.yml:39:#openshift_hosted_registry_storage_openstack_volumeID: e0ba2d73-d2f9-4514-a3b2-a0ced507fa05
```

##### Version

* Your ansible version:
```
ansible 2.4.3.0
  config file = /home/centos/openshift/cluster/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/centos/venv/lib/python2.7/site-packages/ansible
  executable location = /home/centos/venv/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

If you're operating from a **git clone**:

* The output of `git describe`
```
$ git describe
openshift-ansible-3.9.8-1-2-g4deaa4d33
```

##### Steps To Reproduce
1. `git clone https://github.com/openshift/openshift-ansible`
2. `git checkout origin/release-3.9`

##### Expected Results
Find `openshift_hosted_registry_storage_openstack_volumeID` used somewhere in playbooks.

##### Observed Results
`openshift_hosted_registry_storage_openstack_volumeID` is absent from playbooks.

##### Additional Information

Not useful.

**Comment by tomassedovic** [comment]
Hi! The variable is in fact being read and used. Grep only gets you so far.

You can see it here:

https://github.com/openshift/openshift-ansible/blob/0b40b5d5f383f321230b2a357d1cda83ef6d393e/roles/lib_utils/action_plugins/generate_pv_pvcs_list.py#L53

Did you try to use it or were you just curious about the code? Last time I actually used this (about 2 months ago) it was still working. So if it's not working now, let's get more details and fix that.

**Comment by bvkin** [comment]
Hello,
I have been experiencing an issue related to these same variables as well. In my playbooks I am setting all of them properly. When attaching a volume to an internal registry however, one is provisioned dynamically rather than using my already existing volume.This same issue has been happening while provisioning 3.9, 3.10, and 3.11 clusters. Any idea what might be happening?

Thanks.
