### ISSUE TITLE
create safeguards after etcd migration to prevent reverting to v2 data store

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#7544]
I would like to see us do something like this in the migration playbook, after migration, prior to starting the API servers:

1. ensure an etcd backup has been taken

2. remove v2 data after the migration completes and etcd is brought back up, **before any API servers are started** (it is possible this can timeout... not sure if it needs to be retried until successful or given a longer timeout with `--timeout 10m`, etc)

    ```
    ETCDCTL_API=2 etcdctl --timeout <timeout-value> rm --recursive /kubernetes.io
    ```

3. create a key in place of the /kubernetes.io directory. the "migrated" value is arbitrary
    ```
    ETCDCTL_API=2 etcdctl set /kubernetes.io migrated
    ```

That ensures an apiserver cannot start against the etcd data store in v2 mode after a successful migration. If it tries, it will get this error and exit:
```
F0315 23:21:48.730763   99676 controller.go:128] Unable to perform initial IP allocation check: unable to refresh the service IP block: 104: Not a directory (/kubernetes.io) [832]
```

(note that I did not include steps for removing the /openshift.io data... I haven't verified whether any leasers still used the v2 clients under that key in 3.6.x)

**Comment by liggitt** [comment]
@sdodson @blrm

**Comment by blrm** [comment]
@sdodson @liggitt I think this change should be included in the updated playbook we'll be using for the etcd migrations next week. If that can't happen in time, are the steps above all that we need to manually do this after the cluster is migrated and is confirmed to be using etcdv3?

**Comment by liggitt** [comment]
> If that can't happen in time, are the steps above all that we need to manually do this after the cluster is migrated and is confirmed to be using etcdv3?

For safety, those steps should be performed **prior** to any API server starting after a migration. Since the playbook does the migration and the apiserver restart, I think those steps need to be part of the playbook.

**Comment by michaelgugino** [comment]
I like the systemd masking idea @eparis suggested instead of the fix suggested here.  Seems much easier to implement and roll back if needed;  We do allow for etcd migration failure.

**Comment by liggitt** [comment]
Without this, the apiserver is one mis-indented config file away from reverting to v2 mode. Once etcd migration *completes*, we should make it impossible start in v2 mode.
