### ISSUE TITLE
Can I specify the namespace of ImageStream and Template?

### ISSUE THREAD

**Issue by fenggolang** [openshift/openshift-ansible#7564]
Can I specify the namespace of ImageStream and Template, not the default openshift namespace?

**Comment by vrutkovs** [comment]
Which imagestream is that? Is the the one openshift-ansible creates - or is it for your application on top of setup cluster?

**Comment by fenggolang** [comment]
Imagestream is built-in by openshift. It is installed under the openshift project by default. I want to change the installation under other projects.
