### ISSUE TITLE
New Install Openshift Origin 3.7 (No package matching)

### ISSUE THREAD

**Issue by flipkill1985** [openshift/openshift-ansible#7569]
New Installation Centos 7 and i get this Error:

No package matching 'origin-clients-3.10.0' found available, installed or updated

Whats the Reason?

best regards Jan

**Comment by vrutkovs** [comment]
Which repos are installed there?

Which openshift-ansible branch are you using?

What inventory file are you using and what's the log of playbook run with '-vvv'?

**Comment by flipkill1985** [comment]
- Repos dont know
- Branch v3.7

[OSEv3:children]

masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=origin
osm_cluster_network_cidr=10.10.0.0/14
openshift_portal_net=172.100.0.0/16
openshift_master_default_subdomain=apps.x.x.x.x

openshift_release=3.7.0

openshift_disable_check = memory_availability,package_version

[masters]
x.x.x.x

[etcd]
x.x.x.x

[nodes]
x.x.x.x openshift_ip=x.x.x.x openshift_public_ip=x.x.x.x openshift_node_labels="{'region': 'DE', 'zone': 'RZ-Netcup', 'role': 'master'}"

Error:

fatal: [x.x.x.x]: FAILED! => {
    "attempts": 2,
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "conf_file": null,
            "disable_gpg_check": false,
            "disablerepo": null,
            "enablerepo": null,
            "exclude": null,
            "install_repoquery": true,
            "installroot": "/",
            "list": null,
            "name": [
                "origin-clients-3.10.0"
            ],
            "security": false,
            "skip_broken": false,
            "state": "present",
            "update_cache": false,
            "validate_certs": true
        }
    },
    "msg": "No package matching 'origin-clients-3.10.0' found available, installed or updated",
    "rc": 126,
    "results": [
        "No package matching 'origin-clients-3.10.0' found available, installed or updated"
    ]
}

**Comment by phemmer** [comment]
This is very likely related to #7567 & https://bugs.centos.org/view.php?id=14594

**Comment by geoand** [comment]
I am not sure if it's relevant to the package issue discussed here, but I found another oddity that I mention [here](https://github.com/openshift/openshift-ansible/issues/7567#issuecomment-374303479)

**Comment by dungdm93** [comment]
The same issue with me #7577

**Comment by eitamring** [comment]
Had the same issue, 
Go to main.yml 
and switch excluder_enable_excluders =false

**Comment by flipkill1985** [comment]
That helped me:

wget http://cbs.centos.org/kojifiles/packages/origin/3.7.1/2.el7/x86_64/origin-3.7.1-2.el7.x86_64.rpm
wget http://cbs.centos.org/kojifiles/packages/origin/3.7.1/2.el7/x86_64/origin-clients-3.7.1-2.el7.x86_64.rpm
wget http://cbs.centos.org/kojifiles/packages/origin/3.7.1/2.el7/x86_64/origin-master-3.7.1-2.el7.x86_64.rpm
wget http://cbs.centos.org/kojifiles/packages/origin/3.7.1/2.el7/x86_64/origin-node-3.7.1-2.el7.x86_64.rpm
wget http://cbs.centos.org/kojifiles/packages/origin/3.7.1/2.el7/x86_64/tuned-profiles-origin-node-3.7.1-2.el7.x86_64.rpm
wget http://cbs.centos.org/kojifiles/packages/origin/3.7.1/2.el7/x86_64/origin-sdn-ovs-3.7.1-2.el7.x86_64.rpm
wget http://cbs.centos.org/kojifiles/packages/origin/3.7.1/2.el7/x86_64/origin-service-catalog-3.7.1-2.el7.x86_64.rpm
wget http://cbs.centos.org/kojifiles/packages/origin/3.7.1/2.el7/x86_64/origin-template-service-broker-3.7.1-2.el7.x86_64.rpm
wget http://cbs.centos.org/kojifiles/packages/origin/3.7.1/2.el7/x86_64/origin-dockerregistry-3.7.1-2.el7.x86_64.rpm
yum install *.rpm

**Comment by flipkill1985** [comment]
What can i do now?

FATAL: Current Ansible version (2.4.2.0) is not supported. Supported versions: 2.4.3.0 or newer

**Comment by HP-dufeng** [comment]
@flipkill1985 
you can run follow commond , update ansible
```
rpm -Uvh https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ansible-2.4.3.0-1.el7.ans.noarch.rpm
```

**Comment by DanyC97** [comment]
all, as mention in https://bugs.centos.org/view.php?id=14594 by @tdawson the newer 3.7.1 rpm does fix the above issue.

As such i suggest to close this issue as fixed, agree @flipkill1985  ?

**Comment by DanyC97** [comment]
@flipkill1985  gentle reminder please close this issue if the above link fixed your issue (which it should)

@sdodson any chance you can close it if no answer is received in a day or two ? thx

**Comment by sdodson** [comment]
Closing as this is believed to be fixed now.
