### ISSUE TITLE
No config parameter to enable VMware NSX-t based SDN in openshift-ansible 3.9

### ISSUE THREAD

**Issue by kais66** [openshift/openshift-ansible#7583]
#### Description

In openshift-ansible 3.9, there is a sanity check regarding SDN solution used. Since there is no config parameter for VMware NSX-t based SDN solution, if default SDN is disabled, the installation would throw an error.

##### Version

```
Ansible 2.4.3.0, openshift-ansible-3.9.12-1
```

##### Steps To Reproduce
1. set openshift_use_openshift_sdn to false
2. run deploy_cluster playbook

##### Expected Results
It would be great to have a separate config parameter for NSX-t based solution. Or openshift_use_openshift_sdn being false without enabling other SDN explicitly is considered a valid configuration.

##### Observed Results
An error was thrown:

```
Failure summary:

  1. Hosts:    openshift.node.1
     Play:     Verify Requirements
     Task:     Run variable sanity checks
     Message:  last_checked_host: openshift.node.1, last_checked_var: openshift_use_calico;Host Checked: openshift.node.1 Only one of must be true. Found: [('openshift_use_openshift_sdn', False), ('openshift_use_flannel', False), ('openshift_use_nuage', False), ('openshift_use_contiv', False), ('openshift_use_calico', False)]
```

For long output or logs, consider using a [gist](https://gist.github.com/)

cc @rajatchopra @yfauser

**Comment by sdodson** [comment]
/assign michaelgugino
I think the intent of the sanity check previously was to make sure that `openshift_use_openshift_sdn=true` is mutually exclusive with all other sdn plugins. I think we should change https://github.com/openshift/openshift-ansible/blob/master/roles/lib_utils/action_plugins/sanity_checks.py#L136 to be test for > 1. What do you think?

**Comment by michaelgugino** [comment]
@sdodson I wasn't aware that was a supported configuration.  We can easily patch this check if needed.

**Comment by kais66** [comment]
Awesome. That'll work. Thanks @sdodson @michaelgugino
