### ISSUE TITLE
openshift_examples role failing on release-3.9 branch

### ISSUE THREAD

**Issue by chancez** [openshift/openshift-ansible#7585]
#### Description

> fatal: [chancez-chancez-openshift-test8-ig-m-c2lx -> localhost]: FAILED! => {"changed": true, "cmd": ["tar", "-C", "/usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/", "-cvf", "/tmp/openshift-ansible-9F0AD9y/openshift-examples.tar", "."], "delta": "0:00:00.122844", "end": "2018-03-20 21:40:11.185470", "msg": "non-zero return code", "rc": 2, "start": "2018-03-20 21:40:11.062626", "stderr": "tar: /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now", "stderr_lines": ["tar: /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/: Cannot open: No such file or directory", "tar: Error is not recoverable: exiting now"], "stdout": "", "stdout_lines": []}

https://gist.github.com/chancez/fda16e5bedc122122393d7e8bb7ccd6e

It seems on the release-3.9 branch (built the docker image locally) the openshift_examples role is incorrectly trying to use v3.10 examples, which I'm guessing is why it's failing (they don't exist). It seems  

```
ls roles/openshift_examples/files/examples
README.md latest    v1.0      v1.1      v1.2      v1.3      v1.4      v1.5      v3.6      v3.7      v3.8      v3.9
```

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

```
bash-4.2$ ansible --version
ansible 2.4.3.0
  config file = /usr/share/ansible/openshift-ansible/inventory/dynamic/gcp/ansible.cfg
  configured module search path = [u'/opt/app-root/src/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

* The output of `git describe`

```
openshift-ansible-3.9.12-1-4-gfabeed583
```

##### Steps To Reproduce
1. `git checkout release-3.9`
1. `docker build -f images/installer/Dockerfile -t openshift/origin-ansible:v3.9-test`
1. `export OPENSHIFT_ANSIBLE_IMAGE=openshift/origin-ansible:v3.9-test`
1.  Use https://github.com/openshift/release from the `cluster/test-deploy` directory and run `make up WHAT=yourclustername`

**Comment by chancez** [comment]
The only place i even find v3.10 in the branch is in the `role/openshift_facts/library/openshift_facts.py` file, and that got added in https://github.com/openshift/openshift-ansible/pull/7015. I'm guessing that the openshift_facts changes caused it to use v3.10 when otherwise the release isn't specified. Not sure if this should correctly auto-determine v3.9 or if it's incorrect for the user to not have specified `openshift_release: v3.9`. FWIW, I'm using the vars in https://github.com/openshift/release/tree/master/cluster/test-deploy/gcp with small changes for my own GCP project, so I expect this will be breaking CI.

**Comment by smarterclayton** [comment]
could be due to https://github.com/openshift/aos-cd-jobs/commit/4d4c0c861d083c350b567680edeb82d18a985204 - we were running the master ansible against the 3.9 release branch

**Comment by smarterclayton** [comment]
as discussed on slack i think this is `LATEST = (sh curl ...)` taking from the master branch.  Discussion involved how to make this less fragile, including suggestion of having the image default openshift_test_repo to the branch the image was built with.  Currently that happens with centos release, so we might break it.  I think from a user experience perspective either the image needs to default based on branch or we need the makefile to be smarter.
