### ISSUE TITLE
Calico deployment fails with undefined openshift_docker_service_name

### ISSUE THREAD

**Issue by phemmer** [openshift/openshift-ansible#7592]
#### Description

When deploying OpenShift with Calico, the `playbooks/deploy_cluster.yml` playbook fails due to the undefined variable `openshift_docker_service_name`.

##### Version

```
$ ansible --version
ansible 2.4.3.0
  config file = /Users/phemmer/git/openshift-ansible/ansible.cfg
  configured module search path = [u'/Users/phemmer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/phemmer/ansible-2.4/lib/python2.7/site-packages/ansible
  executable location = /Users/phemmer/ansible-2.4/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

$ git describe
openshift-ansible-3.9.12-1

```

##### Steps To Reproduce
1. Follow the directions in https://docs.projectcalico.org/v3.0/getting-started/openshift/installation
* `os_sdn_network_plugin_name=cni`
* `openshift_use_calico=true`
* `openshift_use_openshift_sdn=false`
2. `ansible-playbook -i inventory/hosts.example playbooks/deploy_cluster.yml`

##### Expected Results
Describe what you expected to happen.

Success

##### Observed Results
Describe what is actually happening.

```
TASK [calico : Calico Node | Configure Calico service unit file] *********************************************************************************************************************************************************************************************
Wednesday 21 March 2018  11:27:12 -0400 (0:00:01.196)       0:09:39.342 ******* 
fatal: [openshift-master-dev.c14n.chewy.net]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'openshift_docker_service_name' is undefined"}
fatal: [openshift-node01-dev.c14n.chewy.net]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'openshift_docker_service_name' is undefined"}
fatal: [openshift-node02-dev.c14n.chewy.net]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'openshift_docker_service_name' is undefined"}
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

```
# operating system and version
cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 

# inventory file non-standard configuration parameters
os_sdn_network_plugin_name=cni
openshift_use_calico=true
openshift_use_openshift_sdn=false
openshift_use_crio=True
openshift_crio_enable_docker_gc=True
openshift_crio_docker_gc_node_selector={}
openshift_additional_repos=[{'name': 'OpenShift-Origin', 'id': 'openshift-origin39', 'baseurl': 'https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin39/', 'enabled': 1, 'gpgcheck': 0}]
```

**Comment by phemmer** [comment]
Looking at other examples, such as the `flannel` role, they do the following:

```
# roles/flannel/defaults/main.yaml
openshift_docker_service_name: "{{ 'container-engine' if (openshift_docker_use_system_container | default(False) | bool) else 'docker' }}"
```

Adding this to `roles/calico/defaults/main.yaml` has addressed the issue for me.

**Comment by srirammageswaran8** [comment]
Can this be initialized as part of  to basic_facts.?

https://github.com/openshift/openshift-ansible/blob/release-3.9/playbooks/init/basic_facts.yml

@kprabhak 

Thanks,
Sriram Mageswaran.

**Comment by euprogramador** [comment]
i am receive same error.

**Comment by kprabhak** [comment]
@ozdanborne: fyi

**Comment by ozdanborne** [comment]
I'm seeing this issue even when `use_crio=False`. Seems #6297 added a new `container_runtime` role without adding it as Calico's dependencies.

The workaround is to update `roles/calico/meta/main.yml`, and add `role: container_runtime` as a dependency.

I would recommend instead of implementing that workaround, users try the updated self-hosted installation method for Calico, which is in latest master as well as the `release-3.9` branch.
