### ISSUE TITLE
Vagrant/Virtualbox enterprise deployment username/password install failure

### ISSUE THREAD

**Issue by JaredBurck** [openshift/openshift-ansible#760]
Cloned the openshift-ansible repo locally and attempt to install OpenShift Enterprise using the Vagrant file and Virtualbox as the provider.  I set deployment to "enterprise" and 2 nodes and ran vagrant provision.  Error: must set username and password.  I set the rhel_subscription_user and rhel_subscription_pass environment variables and ran vagrant provision again.  Error: username and password shouldn't exist.

Damned if you do and damned if you don't!  See below for terminal output:

```
$ export OPENSHIFT_DEPLOYMENT_TYPE="enterprise"
$ export OPENSHIFT_NUM_NODES="2"
$ vagrant provision 
/Users/jaredburck/Projects/GitHub/openshift-ansible/Vagrantfile:26:in `block in <top (required)>': rhel_subscription_user and rhel_subscription_pass are required (RuntimeError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:37:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:37:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:103:in `block (2 levels) in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:97:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:97:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:94:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:94:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:28:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `vagrantfile'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:441:in `host'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:207:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:428:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:671:in `unload'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `ensure in <main>'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `<main>'

$ export rhel_subscription_user="jburck@redhat.com"
$ export rhel_subscription_pass="myrhspwd"
$ vagrant provision 
There are errors in the configuration of this machine. Please fix
the following errors and try again:

VagrantPlugins::Registration::Config:
* The following settings shouldn't exist: password, username

$
```

mac osx 10.11.1
vagrant 1.7.4
-vagrant-registration (0.0.8)
virtualbox 5.0.6

**Comment by detiber** [comment]
@JaredBurck It looks like the version of vagrant-registration is older than the version this was originally tested with.

https://github.com/projectatomic/adb-vagrant-registration/tree/12c5c2bf830ec0522c9c528eb032c284ffeb9042 shows that version 0.0.8 expects the variables to be subscriber_username and subscriber_password instead of username and password. From the looks of it, the parameters where changed in version 0.0.11.

That said, vagrant-registration is a bit redundant now, and there is a PR to remove the usage in the Vagrantfile in favor of a more generic registration playbook: https://github.com/openshift/openshift-ansible/pull/739

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.

**Comment by JaredBurck** [comment]
+1 @detiber a long over due thank you for your comment!

@tbielawa thanks for the update! Closing this issue.
