### ISSUE TITLE
openshift_sdn : Ensure the SDN can run privileged Error

### ISSUE THREAD

**Issue by flipkill1985** [openshift/openshift-ansible#7606]
##### Version
Openshift 3.7

Please put the following version information in the code block
indicated below.

# ansible --version
ansible 2.4.3.0
  config file = /tmp/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

If you're running from playbooks installed via RPM or
`playbook`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

```
# rpm -q atomic-openshift-utils openshift-ansible
atomic-openshift-utils-3.7.35-1.git.1.b270aea.el7.noarch
openshift-ansible-3.7.35-1.git.1.b270aea.el7.noarch
```

##### Steps To Reproduce
# ansible-playbook -i /etc/ansible/hosts playbooks/deploy_cluster.yml

##### Expected Results
Describe what you expected to happen.

```
# ansible-playbook -i /etc/ansible/hosts playbooks/deploy_cluster.yml
```

##### Observed Results
Describe what is actually happening.

```
TASK [openshift_sdn : Apply the SDN config] ****************************************************************************************
Wednesday 21 March 2018  23:59:23 +0100 (0:00:00.643)       0:01:46.092 *******
fatal: [master]: FAILED! => {"changed": true, "cmd": "oc apply -f /tmp/console-ansible-P0mAEn", "delta": "0:00:00.300756", "end": "2018-03-21 23:59:23.825519", "msg": "non-zero return code", "rc": 1, "start": "2018-03-21 23:59:23.524763", "stderr": "Error from server (AlreadyExists): error when creating \"/tmp/console-ansible-P0mAEn/sdn-images.yaml\": imagestreamtag.image.openshift.io \"node:v3.9\" already exists\n[unable to recognize \"/tmp/console-ansible-P0mAEn/sdn-ovs.yaml\": no matches for apps/, Kind=DaemonSet, unable to recognize \"/tmp/console-ansible-P0mAEn/sdn.yaml\": no matches for apps/, Kind=DaemonSet]", "stderr_lines": ["Error from server (AlreadyExists): error when creating \"/tmp/console-ansible-P0mAEn/sdn-images.yaml\": imagestreamtag.image.openshift.io \"node:v3.9\" already exists", "[unable to recognize \"/tmp/console-ansible-P0mAEn/sdn-ovs.yaml\": no matches for apps/, Kind=DaemonSet, unable to recognize \"/tmp/console-ansible-P0mAEn/sdn.yaml\": no matches for apps/, Kind=DaemonSet]"], "stdout": "serviceaccount \"sdn\" configured\nclusterrolebinding \"sdn-cluster-reader\" configured\nclusterrolebinding \"sdn-reader\" configured", "stdout_lines": ["serviceaccount \"sdn\" configured", "clusterrolebinding \"sdn-cluster-reader\" configured", "clusterrolebinding \"sdn-reader\" configured"]}
```

Ansilbe Hosts

`[OSEv3:vars]
openshift_master_default_subdomain=apps.ex.xxx.es
ansible_ssh_user=root
ansible_become=yes
openshift_master_cluster_method=native
openshift_master_cluster_hostname=sp-mohs02.ex.xxx.es
openshift_master_cluster_public_hostname=openshift.ex.xxx.es
deployment_type=origin

openshift_release=v3.7
openshift_repos_enable_testing=true

#os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/htpasswd'}]
openshift_docker_options='--selinux-enabled --insecure-registry 172.30.0.0/16'
openshift_router_selector='region=infra'
openshift_registry_selector='region=infra'
openshift_master_api_port=443
openshift_master_console_port=443
openshift_disable_check=memory_availability,disk_availability,package_version

[nodes]
master openshift_schedulable=True ansible_connection=local ansible_become=yes

[masters]
master ansible_connection=local ansible_become=yes

[etcd]
master ansible_connection=local ansible_become=yes
`

**Comment by alexray92** [comment]
I'm actually getting the same error as well
