### ISSUE TITLE
apiserver.kube-service-catalog.svc/healthz

### ISSUE THREAD

**Issue by flipkill1985** [openshift/openshift-ansible#7639]
Cant do Anything openshift 3.7 Failes all the time and 3.9 also fails with other Error. 

fatal: [sp-mohs02.os.mohs.es]: FAILED! => {
    "attempts": 120,
    "changed": false,
    "cmd": [
        "curl",
        "-k",
        "https://apiserver.kube-service-catalog.svc/healthz"
    ],
    "delta": "0:00:00.100573",
    "end": "2018-03-24 12:40:47.309139",
    "invocation": {
        "module_args": {
            "_raw_params": "curl -k https://apiserver.kube-service-catalog.svc/healthz",
            "_uses_shell": false,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": false
        }
    },
    "rc": 0,
    "start": "2018-03-24 12:40:47.208566",
    "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   180  100   180    0     0   1940      0 --:--:-- --:--:-- --:--:--  1956",
    "stderr_lines": [
        "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current",
        "                                 Dload  Upload   Total   Spent    Left  Speed",
        "",
        "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0",
        "100   180  100   180    0     0   1940      0 --:--:-- --:--:-- --:--:--  1956"
    ],
    "stdout": "[+]ping ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/start-service-catalog-apiserver-informers ok\n[-]etcd failed: reason withheld\nhealthz check failed",
    "stdout_lines": [
        "[+]ping ok",
        "[+]poststarthook/generic-apiserver-start-informers ok",
        "[+]poststarthook/start-service-catalog-apiserver-informers ok",
        "[-]etcd failed: reason withheld",
        "healthz check failed"
    ]
}
        to retry, use: --limit @/home/mohs/openshift-ansible/playbooks/byo/config.retry

**Comment by bevinhex** [comment]
Same issue here

**Comment by HP-dufeng** [comment]
Same issue, It often goes wrong in this place

**Comment by HP-dufeng** [comment]
If install on a virtual os，you must ensure avaible memery more then 8Gb,  It is best not to enable dynamic memory.

**Comment by eclipsewebmaster** [comment]
I get this too

fatal: : FAILED! => {"attempts": 60, "changed": false, "content": "", "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "https://apiserver.kube-service-catalog.svc/healthz"}
        to retry, use: --limit @/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry



INSTALLER STATUS ****************************************************************************************************************************************************************************************************************************
Initialization             : Complete
Health Check               : Complete
etcd Install               : Complete
Master Install             : Complete
Master Additional Install  : Complete
Node Install               : Complete
Hosted Install             : Complete
Service Catalog Install    : In Progress
        This phase can be restarted by running: playbooks/byo/openshift-cluster/service-catalog.yml



Failure summary:


  1. Hosts:    master1
     Play:     Service Catalog
     Task:     wait for api server to be ready
     Message:  Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>

**Comment by bevinhex** [comment]
I'm not sure how I solved it, try disabling ansible broker, here is part of my inventory.ini file 
```
openshift_release=v3.7
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/htpasswd'}]
openshift_docker_options='--selinux-enabled --insecure-registry 172.30.0.0/16'
containerized=false
openshift_clock_enabled=true
openshift_use_dnsmasq=true
os_firewall_use_firewalld=true
openshift_public_hostname=ipdirect.solutions
openshift_master_default_subdomain=apps.ipdirect.solutions
openshift_use_openshift_sdn=true
openshift_enable_service_catalog=true

#ansible_service_broker_remove=true
ansible_service_broker_install=false
```
ansible broker can be installed after everything else is working.

**Comment by HP-dufeng** [comment]
Hi, 3.9 is released ,you can try to install this version.
I recently installed successed.

**Comment by JayKayy** [comment]
I had a similar issue see if it is similar to my comment here: https://github.com/openshift/openshift-ansible/issues/8076

**Comment by bluesky255** [comment]
Problem solved by resolve add apps_.domain.com_ in DNS record.
