### ISSUE TITLE
object of type 'builtin_function_or_method' has no len()

### ISSUE THREAD

**Issue by RafnexJr** [openshift/openshift-ansible#7691]
#### Description

I'm trying to install a OpenShift SingleMaster two Node cluster.

##### Version

I'm working with Ansible Verions `2.4.3.0`

Git Version is `openshift-ansible-3.9.14-1-9-g2b99b34`

##### Steps To Reproduce

On the Task `TASK [openshift_master : Ensure that Template Service Broker has nodes to run on]`

A fatal error appears:

`fatal: [master.domain.ch]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{  __schedulable_nodes_matching_selector['results']['results'][0]['items'] | default([]) | length != 0 }}): object of type 'builtin_function_or_method' has no len()"}
`
#### Information

My Inventory File:

```
# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become=true

openshift_deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# host group for masters
[masters]
master.domain.ch

# host group for etcd
[etcd]
master.domain.ch

# host group for nodes, includes region info
[nodes]
master.domain.ch
node01.domain.ch openshift_node_labels="{'region': 'primary', 'zone': 'srv1'}"
node02.domain.ch openshift_node_labels="{'region': 'primary', 'zone': 'srv2'}"
```

**Comment by RafnexJr** [comment]
Issue resolved, was a version mismatch.

**Comment by lfxy** [comment]
Hi, I also get this error. Could you tell me how to resolve this error? What's version mismatch?

**Comment by lfxy** [comment]
@RafnexJr

**Comment by MariuSteinbach** [comment]
Hi, it happened to me, because i checked out the 3.9 version from the git repository and installed the 3.7 version.

I checked out 3.7 and it went through fine.

**Comment by RafnexJr** [comment]
Had the same resolution like mr. steinbach.

**Comment by hendrikhalkow** [comment]
The same issue occurs in the 3.9 release branch. What is the solution if I want to use OpenShift 3.9?

**Comment by michaelgugino** [comment]
@ewolinetz PTAL

**Comment by michaelgugino** [comment]
@abutcher PTAL

**Comment by abutcher** [comment]
Re-opening re: upgrade issue.

**Comment by abutcher** [comment]
@wshearn is also having this problem and is looking into a solution

**Comment by AlbertoPeon** [comment]
I am also hitting this with 3.9 branch. Is there any know fix/workaround?

CC/ @wshearn @abutcher

**Comment by AlbertoPeon** [comment]
I can see that the check for node availability [is gone for v1.10](https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.10.0-0.47.0/roles/template_service_broker/tasks/install.yml). Could you issue a release of 3.9 with this?  

The commit seems to be [this](https://github.com/openshift/openshift-ansible/commit/1832c8e3037443ba9379f8e61513723ff65e90ea). Would it be possible to backport to 3.9? @smarterclayton.

Thanks!

**Comment by vrutkovs** [comment]
>I am also hitting this with 3.9 branch. Is there any know fix/workaround?

Which version of `oc` is installed there?

>I can see that the check for node availability is gone for v1.10

ASB is now running on master, but the check remains for other components (e.g. Prometheus). Which component threw this error?

**Comment by vrutkovs** [comment]
>We use 3.7 server-side but we are testing the upgrade to 3.9.

`origin-clients` should have been updated by the time ASB update hits. Do you have a full update log?

**Comment by AlbertoPeon** [comment]
We are actually running the service-catalog playbook on its own, not the full upgrade playbook (sorry for not clarifying this first). 

Do you think it will make a difference to havethe  `oc` client upgraded to 3.9 first?

**Comment by vrutkovs** [comment]
>Do you think it will make a difference to havethe oc client upgraded to 3.9 first?

Yes, its necessary to make this error go away

**Comment by AlbertoPeon** [comment]
Thanks @vrutkovs ! I will give it a try with the updated clients!
