### ISSUE TITLE
3.9 CRI-O deployment fails due to incompatible version

### ISSUE THREAD

**Issue by phemmer** [openshift/openshift-ansible#7708]
#### Description

The release-3.9 branch fails to deploy when using CRI-O (`openshift_use_crio=True`).
```
RUNNING HANDLER [openshift_node : restart node] ************
fatal: [fll2aosm01dev.dev.chewy.net]: FAILED! => {"attempts": 3, "changed": false, "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}
```
```
# journalctl -u origin-node.service
Mar 29 11:45:53 fll2aosm01dev origin-node[4070]: E0329 11:45:53.656511    4070 remote_runtime.go:69] Version from runtime service failed: rpc error: code = Unimplemented desc = unknown service runtime.RuntimeService
Mar 29 11:45:53 fll2aosm01dev origin-node[4070]: E0329 11:45:53.656631    4070 kuberuntime_manager.go:172] Get runtime version failed: rpc error: code = Unimplemented desc = unknown service runtime.RuntimeService
Mar 29 11:45:53 fll2aosm01dev origin-node[4070]: F0329 11:45:53.656658    4070 server.go:173] failed to run Kubelet: failed to create kubelet: rpc error: code = Unimplemented desc = unknown service runtime.RuntimeService
```

From googling, I stumbled across https://github.com/containerd/cri/issues/619 which seems to be the same issue. The explanation there is that the latest version of CRI-O is not compatible with kubernetes <= 1.9.

The openshift-ansible uses `registry.centos.org/projectatomic/cri-o:latest` as the container image to deploy, thus it pulls in an incompatible version of CRI-O. Additionally when I look at https://registry.centos.org/projectatomic/cri-o, all the tags other than `latest` are just gobblygook, and I have no idea which one corresponds to the last compatible CRI-O version, 1.0.0-beta.1.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
```
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/phemmer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/phemmer/ansible-2.5/lib/python2.7/site-packages/ansible
  executable location = /Users/phemmer/ansible-2.5/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

If you're operating from a **git clone**:

* The output of `git describe`
```
openshift-ansible-3.9.14-1-53-g5c8fcec48
```

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
package atomic-openshift-utils is not installed
package openshift-ansible is not installed
```

##### Steps To Reproduce
1. Set `openshift_use_crio=True`
2. `ansible-playbook -i inventory playbooks/deploy_cluster.yml`

##### Expected Results
Describe what you expected to happen.

```
success
```

##### Observed Results
Describe what is actually happening.

```
RUNNING HANDLER [openshift_node : restart node] ************
fatal: [fll2aosm01dev.dev.chewy.net]: FAILED! => {"attempts": 3, "changed": false, "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}
```
```
# journalctl -u origin-node.service
Mar 29 11:45:53 fll2aosm01dev origin-node[4070]: E0329 11:45:53.656511    4070 remote_runtime.go:69] Version from runtime service failed: rpc error: code = Unimplemented desc = unknown service runtime.RuntimeService
Mar 29 11:45:53 fll2aosm01dev origin-node[4070]: E0329 11:45:53.656631    4070 kuberuntime_manager.go:172] Get runtime version failed: rpc error: code = Unimplemented desc = unknown service runtime.RuntimeService
Mar 29 11:45:53 fll2aosm01dev origin-node[4070]: F0329 11:45:53.656658    4070 server.go:173] failed to run Kubelet: failed to create kubelet: rpc error: code = Unimplemented desc = unknown service runtime.RuntimeService
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
```
# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```
* Your inventory file (especially any non-standard configuration parameters)
```
openshift_use_crio=True
openshift_crio_docker_gc=True
openshift_crio_docker_gc_node_selector={}
```
* Sample code, etc

**Comment by dustymabe** [comment]
just hit this too

**Comment by cynepco3hahue** [comment]
Currently to W/A the problem I use the custom image with CRI-O 1.9.10 from https://hub.docker.com/r/kubevirtci/crio/
`openshift_crio_systemcontainer_image_override=docker.io/kubevirtci/crio:1.9.10`

**Comment by phemmer** [comment]
My workaround was to use the RPM. However this does have more problems of its own: https://github.com/openshift/openshift-ansible/issues/7845 Basically the RPM version of CRI-O pulls in containernetworking-cni which installs CNI plugins to the wrong path. But as documented in that issue, it can be worked around by adding a symlink.

**Comment by sdodson** [comment]
Yes, sorry, but crio as a system container was deemed to be flawed to the point that we're only supporting it via RPM installation and thus until CRI-O is included in Atomic Host it can only be used on RHEL/Centos.
`openshift_crio_use_rpm=True` will ensure you get rpm based install but i think current code actually makes that implicit.
