### ISSUE TITLE
Local USB Device to POD

### ISSUE THREAD

**Issue by flipkill1985** [openshift/openshift-ansible#7718]
Hello,

its a Question, not a bug. Is it possible to map a local USB Device to a POD?
and how is that possible?

best regards Jan

**Comment by vrutkovs** [comment]
Please use support forums for questions and use openshift/origin repo to file issues not related to installation.

Your options are:
* [Local provisioner](https://docs.openshift.com/container-platform/3.7/install_config/configuring_local.html)
* [hostPath](https://docs.openshift.com/container-platform/3.7/dev_guide/volumes.html)

**Comment by flipkill1985** [comment]
How can i configure hostPath?
