### ISSUE TITLE
Error deploying cluster (openshift 3.7) on CentOS 7.4

### ISSUE THREAD

**Issue by alexray92** [openshift/openshift-ansible#7719]
#### Description

Trying to run the setup_cluster playbook against a single host, with a dedicated VG for storage.  I'm using puppet to download the git repo, install/configure docker and ansible, and run the ansible playbooks, if that matters - it's a clean build of CentOS via Foreman.  

Basically, it fails on a step ("Remove the Image Stream tag") that runs "oc delete -n openshift-node istag node:v3.10 --ignore-not-found", however if I then run that command manually it will succeed.  The error it gives is:

"stderr": "error: Missing or incomplete configuration info. Please login or point to an existing, complete config file:\n\n 1. Via the command-line flag --config\n 2. Via the KUBECONFIG environment variable\n 3. In your home directory as ~/.kube/config\n\nTo view or setup config directly use the 'config' command.",

However, ~/.kube/config exists and is populated with quite a bit of data, so I'm not sure what it's referring to.

I tried running that command manually, then ran the ansible playbook from CLI manually, and it then failed at "openshift_node_group : Apply the config", with "error: unable to recognize \"/tmp/ansible-5g1B47/sync.yaml\": no matches for apps/

The web UI is available, but catalog never loads.

##### Version

Please put the following version information in the code block
indicated below.

ansible version = 2.7.5
centos version = 7.4.1708
playbook source = master branch (git describe = openshift-ansible-3.10.0-0.15.0-13-g653eb2b)

Ran using prerequisites.yml and deploy_cluster.yml

##### Steps To Reproduce
1. Run ansible on above scripts
2. Get error

##### Expected Results
Describe what you expected to happen.

```
Install openshift
```

##### Observed Results
It fails toward the end:

```
(ansible playbook) oc delete -n openshift-node istag node:v3.10 --ignore-not-found
-
"stderr": "error: Missing or incomplete configuration info. Please login or point to an existing, complete config file:\n\n 1. Via the command-line flag --config\n 2. Via the KUBECONFIG environment variable\n 3. In your home directory as ~/.kube/config\n\nTo view or setup config directly use the 'config' command.",
...
(manually run) oc delete -n openshift-node istag node:v3.10 --ignore-not-found
-
no error
...
```

**Comment by jfmatth** [comment]
Same error here, have you gotten it work ?

**Comment by vrutkovs** [comment]
Don't use `master` branch to setup 3.7, use `release-3.7`
