### ISSUE TITLE
3.9 deploy_cluster.yml fail to show up in ansible tower

### ISSUE THREAD

**Issue by MansM** [openshift/openshift-ansible#7744]
#### Description

We are using ansible tower to deploy openshift.
As the deploy_cluster.yml doesnt contain the "header" required to show up I have to create a sh*tload of project_templates to get it working

The header I am refering to:
- hosts: all
   tasks: 
     - import yada yada

We prefer to use the openshift-ansible upstream repo untouched, but this is blocking us to go forward with untouched :( 

it is a simple to fix, but I don't know the reason for removal since 3.7.

**Comment by vrutkovs** [comment]
This should be fixed on AWX side - see https://github.com/ansible/awx/pull/1298

**Comment by tusharsanas** [comment]
Hi ,

We are also facing the same issues, we are not able to see deploy_cluster.yml in dropdown list.
Please can anyone suggest what are the action steps to be taken for add deploy_cluster.yml in dropdown list.

**Comment by tusharsanas** [comment]
Hi,

If i require it now, to continue with my openshift3.9 deployment through anisble tower , i need to put the file ansible.pyc file in tower, but may i know in tower in which path should i place this file?
Sorry!!!, being new in Ansible Tower please can you provide me more details
