### ISSUE TITLE
No package matching 'origin-docker-excluder-3.10**' found available, installed or updated

### ISSUE THREAD

**Issue by adelton** [openshift/openshift-ansible#7794]
#### Description

On an all-on-one installation on RHEL 7.4 and RHEL 7.5 nightly, `ansible-playbook openshift-ansible/playbooks/prerequisites.yml` fails with

```
TASK [openshift_excluder : Install docker excluder - yum] **********************
Thursday 05 April 2018  04:36:54 -0400 (0:00:00.056)       0:03:22.822 ******** 
FAILED - RETRYING: Install docker excluder - yum (2 retries left).
FAILED - RETRYING: Install docker excluder - yum (1 retries left).
fatal: [master.example.com]: FAILED! => {"attempts": 2, "changed": false, "msg": "No package matching 'origin-docker-excluder-3.10**' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-docker-excluder-3.10**' found available, installed or updated"]`
```

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
If you're operating from a **git clone**:

* The output of `git describe`

```
openshift-ansible-3.10.0-0.15.0-86-gb27c45d
```

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

```
package atomic-openshift-utils is not installed
package openshift-ansible is not installed
```

Place the output between the code block below:

##### Steps To Reproduce
1. `ansible-playbook -i ansible-inventory openshift-ansible/playbooks/prerequisites.yml`

##### Expected Results
Describe what you expected to happen.

No error.

##### Observed Results
Describe what is actually happening.

```
PLAY [oo_nodes_to_config:oo_hosts_containerized_managed_true] ******************

TASK [container_runtime : Setup the docker-storage for overlay] ****************
Thursday 05 April 2018  04:36:54 -0400 (0:00:10.073)       0:03:22.765 ******** 
skipping: [master.example.com]

PLAY [create oo_hosts_containerized_managed_true host group] *******************
skipping: no hosts matched

PLAY [oo_nodes_to_config:oo_hosts_containerized_managed_true] ******************

TASK [openshift_excluder : Install docker excluder - yum] **********************
Thursday 05 April 2018  04:36:54 -0400 (0:00:00.056)       0:03:22.822 ******** 
FAILED - RETRYING: Install docker excluder - yum (2 retries left).
FAILED - RETRYING: Install docker excluder - yum (1 retries left).
fatal: [master.example.com]: FAILED! => {"attempts": 2, "changed": false, "msg": "No package matching 'origin-docker-excluder-3.10**' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-docker-excluder-3.10**' found available, installed or updated"]}

PLAY RECAP *********************************************************************
master.example.com : ok=53   changed=9    unreachable=0    failed=1   
localhost                  : ok=11   changed=0    unreachable=0    failed=0   


INSTALLER STATUS ***************************************************************
Initialization             : Complete (0:01:24)

Thursday 05 April 2018  04:37:54 -0400 (0:00:59.848)       0:04:22.671 ******** 
=============================================================================== 
Ensure openshift-ansible installer package deps are installed ---------- 76.04s
os_firewall : Install iptables packages -------------------------------- 72.50s
openshift_excluder : Install docker excluder - yum --------------------- 59.85s
openshift_repos : Ensure libselinux-python is installed ---------------- 15.19s
os_firewall : need to pause here, otherwise the iptables service starting can sometimes cause ssh to fail -- 10.07s
os_firewall : Wait 10 seconds after disabling firewalld ---------------- 10.06s
openshift_repos : refresh cache ----------------------------------------- 6.14s
get openshift_current_version ------------------------------------------- 1.53s
Gathering Facts --------------------------------------------------------- 1.29s
Gather Cluster facts ---------------------------------------------------- 1.02s
openshift_repos : Configure origin gpg keys ----------------------------- 0.67s
Initialize openshift.node.sdn_mtu --------------------------------------- 0.49s
os_firewall : Ensure firewalld service is not enabled ------------------- 0.48s
openshift_repos : Configure correct origin release repository ----------- 0.45s
os_firewall : Start and enable iptables service ------------------------- 0.43s
initialize_facts set fact openshift_is_bootstrapped --------------------- 0.37s
Query DNS for IP address of master.example.com ---- 0.36s
openshift_repos : Remove openshift_additional.repo file ----------------- 0.35s
Detecting Operating System from ostree_booted --------------------------- 0.32s
openshift_repos : openshift_repos detect ostree ------------------------- 0.23s
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
```
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```
* Your inventory file (especially any non-standard configuration parameters)
```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_disable_check=memory_availability,docker_storage,disk_availability,package_version
openshift_repos_enable_testing=true

osm_cluster_network_cidr=10.128.0.0/14
openshift_portal_net=172.30.0.0/16
osm_host_subnet_length=9

openshift_router_selector='node-router=true'
openshift_registry_selector='node-registry=true'
template_service_broker_selector={"node-app": "true"}
openshift_web_console_nodeselector={"node-app": "true"}

openshift_master_identity_providers=[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]

[masters]
master.example.com

[etcd]
master.example.com

[nodes]
master.example.com openshift_schedulable=true openshift_node_labels="{ 'node-router': 'true', 'node-registry': 'true', 'node-app': 'true' }"
```

**Comment by adelton** [comment]
I already have `docker-1.13.1-58.git87f2fab.el7` installed before I run the `ansible-playbook` -- why does it mess with some docker excluder in the first place?

**Comment by vrutkovs** [comment]
Docker excluder would prevent `yum update` from updating docker version. This behavior can be disabled by setting `openshift_enable_docker_excluder=False`. There's is also excluder for Openshift version too - `openshift_enable_openshift_excluder`.

**Comment by adelton** [comment]
Is there a way to prevent that `yum update` altogether? I know my machine has the existing packages the way I like them (essentially latest greatest), if `openshift-ansible` wants to install more, it can, but it should not try to upgrade anything anyway ...

**Comment by adelton** [comment]
Another point of course is -- I don't mind `openshift-ansible` installing the excluder if it's the default but it looks like it does not seem to be available ...

**Comment by vrutkovs** [comment]
>Is there a way to prevent that yum update altogether?

Excluders are installed to protect from user running `yum update`.

>it looks like it does not seem to be available

That depends on the repos you're using. For Origin its recommended to use https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo, as CentOS 3.10 candidate repo is way too old

**Comment by adelton** [comment]
> 
> Excluders are installed to protect from user running `yum update`.

Ah, OK.

I confirm that adding `openshift_enable_excluders=false` to `[OSEv3:vars]` makes the `ansible-playbook openshift-ansible/playbooks/prerequisites.yml` pass.

However, the subsequent `ansible-playbook openshift-ansible/playbooks/deploy_cluster.yml` then fails with

```
TASK [openshift_node : Restart journald] ***************************************
Thursday 05 April 2018  10:11:58 -0400 (0:00:07.428)       0:03:14.170 ******** 
changed: [master.example.com]

TASK [openshift_node : Disable swap] *******************************************
Thursday 05 April 2018  10:11:59 -0400 (0:00:00.991)       0:03:15.162 ******** 
changed: [master.example.com]

TASK [openshift_node : Install node, clients, and conntrack packages] **********
Thursday 05 April 2018  10:12:01 -0400 (0:00:01.210)       0:03:16.372 ******** 
FAILED - RETRYING: Install node, clients, and conntrack packages (2 retries left).
FAILED - RETRYING: Install node, clients, and conntrack packages (1 retries left).
failed: [master.example.com] (item={u'name': u'origin-node-3.10*'}) => {"attempts": 2, "changed": false, "item": {"name": "origin-node-3.10*"}, "msg": "No package matching 'origin-node-3.10*' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-node-3.10*' found available, installed or updated"]}
FAILED - RETRYING: Install node, clients, and conntrack packages (2 retries left).
FAILED - RETRYING: Install node, clients, and conntrack packages (1 retries left).
failed: [master.example.com] (item={u'name': u'origin-clients-3.10*'}) => {"attempts": 2, "changed": false, "item": {"name": "origin-clients-3.10*"}, "msg": "No package matching 'origin-clients-3.10*' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-clients-3.10*' found available, installed or updated"]}
```

> That depends on the repos you're using. For Origin its recommended to use https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo, as CentOS 3.10 candidate repo is way too old

I don't configure any specific OpenShift Origin repo, I use whatever `openshift-ansible` decides to configure. I have `openshift_repos_enable_testing=true` in the inventory file, since https://github.com/openshift/openshift-ansible/issues/6086#issuecomment-348453567. What's the recommended repo option to enable the recommented repository?

**Comment by adelton** [comment]
And to confirm what currently gets enabled, it's `/etc/yum.repos.d/CentOS-OpenShift-Origin.repo` pointing to `baseurl=http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/`. Grepping `openshift-ansible` repo, I don't see `storage.googleapis.com` referenced anywhere.

**Comment by adelton** [comment]
The fail `failed: [master.example.com] (item={u'name': u'origin-node-3.10*'}) => {"attempts": 2, "changed": false, "item": {"name": "origin-node-3.10*"}, "msg": "No package matching 'origin-node-3.10*' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-node-3.10*' found available, installed or updated"]}` is internal reproducer J:2410134.

**Comment by adelton** [comment]
When I do

```
cd /etc/yum.repos.d && curl -O https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo
```

before running the playbooks, the task

```
TASK [openshift_node : Install node, clients, and conntrack packages] **********
```

passes but things fail at

```
TASK [openshift_control_plane : Get node logs] *********************************
Thursday 05 April 2018  12:29:31 -0400 (0:00:01.464)       0:43:44.054 ******** 
skipping: [master.example.com]

TASK [openshift_control_plane : debug] *****************************************
Thursday 05 April 2018  12:29:31 -0400 (0:00:00.056)       0:43:44.110 ******** 
skipping: [master.example.com]

TASK [openshift_control_plane : fail] ******************************************
Thursday 05 April 2018  12:29:31 -0400 (0:00:00.055)       0:43:44.166 ******** 
skipping: [master.example.com]

TASK [openshift_control_plane : Verify that the control plane is running] ******
Thursday 05 April 2018  12:29:31 -0400 (0:00:00.054)       0:43:44.220 ******** 
FAILED - RETRYING: Verify that the control plane is running (60 retries left).
FAILED - RETRYING: Verify that the control plane is running (59 retries left).
[...]
FAILED - RETRYING: Verify that the control plane is running (2 retries left).
FAILED - RETRYING: Verify that the control plane is running (1 retries left).
fatal: [master.example.com]: FAILED! => {"attempts": 60, "changed": false, "cmd": ["curl", "-k", "https://master.example.com:8443/healthz/ready"], "delta": "0:00:00.015211", "end": "2018-04-05 12:34:48.025644", "msg": "non-zero return code", "rc": 7, "start": "2018-04-05 12:34:48.010433", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to master.example.com:8443; Connection refused", "stderr_lines": ["  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to master.example.com:8443; Connection refused"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [openshift_control_plane : Check status in the kube-system namespace] *****
Thursday 05 April 2018  12:34:48 -0400 (0:05:16.127)       0:49:00.348 ******** 
fatal: [master.example.com]: FAILED! => {"changed": true, "cmd": ["oc", "status", "--config=/etc/origin/master/admin.kubeconfig", "-n", "kube-system"], "delta": "0:00:00.299006", "end": "2018-04-05 12:34:48.653928", "msg": "non-zero return code", "rc": 1, "start": "2018-04-05 12:34:48.354922", "stderr": "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?\nThe connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}
...ignoring

[...]
```

Internal reproducer J:2410314.

**Comment by infinitydon** [comment]
Same experience here, quite surprised by this kind of error... I have been trying this since yesterday evening

**Comment by vrutkovs** [comment]
CentOS repo has outdated packages, these still have a critical bug - API server won't reply back and would hang there.

Please use https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo for now - this repo should have the latest built image

**Comment by adelton** [comment]
Currently, with that

```
cd /etc/yum.repos.d && curl -O https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo
```

running openshift-ansible from master for all-on-one setup works, internal reproducer J:2429805.

Should we try to make a pull request to use this storage.googleapis.com/origin-ci-test/ repo instead of those CentOS repos? If this repo is kept up-to-date with openshift/origin and openshift-ansible masters, maybe that would provide the best way to test the masters.

Flipping to the appropriate CentOS repos could then be part of creating release branch.

**Comment by vrutkovs** [comment]
>Should we try to make a pull request to use this storage.googleapis.com/origin-ci-test/ repo instead of those CentOS repos?

I'd rather keep the CenOS repos and give them time to re-enable build pipeline. Packages in storage.googleapis are barely tested to be consistent with other CentOS packages.

**Comment by adelton** [comment]
OK. Closing, since we have the workaround.

**Comment by colegatron** [comment]
As far as I understand @adelton you added the CI repo manually on /etc/yum.repos.d and it worked.
I have tried to use the inventory variable to make the process update the package cache without luck:

openshift_additional_repos=[{'id': 'openshift-origin-ci', 'name': 'OpenShift Origin CI repostory (caution: not release)', 'baseurl': 'https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo', 'enabled': 1, 'gpgcheck': 0}]

Not sure if it there is any mistake in the repo specification or the ansible playbook does not refreshes de package list soon enough, although the source code seems to use the variable in a handful of them.

Can you confirm it if works for you? 

Thank you

**Comment by adelton** [comment]
> As far as I understand @adelton you added the CI repo manually on /etc/yum.repos.d and it worked.

Right, I've set it up before running the playbook.

**Comment by colegatron** [comment]
The issue was with the version in the CI repo, v3.10-alpha.
After set openshift_release=v3.7 the prerequisites passed correcty.

**Comment by IRobL** [comment]
Thanks everyone for working on this solution, I'm very excited to soon have a stable/ reproducible test instance of Openshift on a VM.  Adelton's workaround got me past this error great!  

I'm getting the feeling that CentOS is not the first class citizen of this project.  If it's not CentOS, what distro is being targeted?

**Comment by drajen** [comment]
Trying to get v3.10 to pass prereqs on CentOS, no luck. 
```
No package matching 'origin-docker-excluder-3.10**' found available, installed or updated
```

Running `release-3.10` from https://github.com/openshift/openshift-ansible

**Comment by Cajga** [comment]
@drajen So the main issue here is that the CentOS guys are lacking with the testing behind the upstream version. 

The release-3.10 from openshift-ansible is trying to install origin-docker-excluder-3.10* but only origin-docker-excluder-3.9* is available in the [CentOS origin repo](http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/) which is used for CentOS/Red Hat. You can use a workaround to include the repo that @vrutkovs  suggested but as he noted those packages are not really tested by CentOS guys yet.

This should be at least mentioned in the documentation (use 3.9 for CentOS as it is not compatible with 3.10 yet)

**Comment by drajen** [comment]
I appreciate the time you took to explain @Cajga I might just wait for 3.10 to be GA'd next week and I can deploy that to my RHEL hosts. I was under the impression that CentOS would be a good platform to test the latest bits from Origin but I know better now. Thanks!

**Comment by cben** [comment]
@colegatron tried your setting.
1. ```
    Bad id for repo: OpenShift Origin CI repostory (caution: not release), byte =   9
    ```
    => Renaming it to avoid special symbols.

2. `https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`
`.../origin.repo` is where we can fetch a complete .repo file
    ```
    [origin-repo]
    name=Origin RPMs
    baseurl=https://storage.googleapis.com/origin-ci-test/logs/test_branch_origin_extended_conformance_gce/3326/artifacts/rpms
    enabled=1
    gpgcheck=0
    ```

So, this works to add the repo: :tada:
```
openshift_additional_repos: [{'id': 'openshift-origin-ci', 'name': 'OpenShift-Origin-CI-repostory--caution-not-release', 'baseurl': 'https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo', 'enabled': 1, 'gpgcheck': 0}]
```

3. Alas, this CI repo no longer contains 3.10.  It has `origin-docker-excluder.noarch                   3.11.0-0.alpha.0.448.bf684d5` :-(

Gonna re-try 3.11, will update this comment...

**Comment by vrutkovs** [comment]
https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/release-3.10/.latest-rpms contains a link to the latest 3.10 builds in CI

**Comment by onknows** [comment]
3.10 sucks at much as 3.9. Just saying. The project is introducing new issues at a faster rate than fixes. Running forward all the time and getting more and more behind.

**Comment by Bengrunt** [comment]
Hi there,

Any news regarding the general availability of the origin-docker-excluder-3.10 package for CentOS users?

Thanks!

**Comment by adrianovieira** [comment]
I also tried to get v3.10 to pass prereqs on CentOS, but it doesn't work for me.

No package matching 'origin-docker-excluder-3.10**' found available, installed or updated

The repo [`https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo`](https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo) doesn't has v3.10 anymore - instead it only has the v3.11

- `$ sudo yum search --showduplicates origin-docker-excluder`
```bash
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.xpg.com.br
 * epel: mirror.globo.com
 * extras: centos.xpg.com.br
 * updates: centos.xpg.com.br
======================================================================================= N/S matched: origin-docker-excluder =======================================================================================
origin-docker-excluder-3.6.0-1.0.c4dd4cf.noarch : Exclude docker packages from updates
origin-docker-excluder-3.6.1-1.0.008f2d5.noarch : Exclude docker packages from updates
origin-docker-excluder-3.7.0-1.0.7ed6862.noarch : Exclude docker packages from updates
origin-docker-excluder-3.7.1-1.el7.git.0.0a2d6a1.noarch : Exclude docker packages from updates
origin-docker-excluder-3.7.1-2.el7.noarch : Exclude docker packages from updates
origin-docker-excluder-3.8.0-1.el7.git.0.dd1558c.noarch : Exclude docker packages from updates
origin-docker-excluder-3.9.0-1.el7.git.0.ba7faec.noarch : Exclude docker packages from updates
origin-docker-excluder-3.11.0-0.alpha.0.568.10b4e5e.noarch : Exclude docker packages from updates

  Name and summary matches only, use "search all" for everything.
```
- `$ sudo yum info origin-docker-excluder-3.9.0`
```bash
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.xpg.com.br
 * epel: mirror.globo.com
 * extras: centos.xpg.com.br
 * updates: centos.xpg.com.br
Available Packages
Name        : origin-docker-excluder
Arch        : noarch
Version     : 3.9.0
Release     : 1.el7.git.0.ba7faec
Size        : 6.7 k
Repo        : centos-openshift-origin
Summary     : Exclude docker packages from updates
URL         : https://github.com/openshift/origin
License     : ASL 2.0
Description : Certain versions of OpenShift will not work with newer versions
            : of docker.  Exclude those versions of docker.
            : 
            : origin-docker-excluder exclude - No major docker updates
            : origin-docker-excluder unexclude - docker packages can be updated
```
- `$ sudo yum info origin-docker-excluder-3.11.0`
```bash
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.xpg.com.br
 * epel: mirror.globo.com
 * extras: centos.xpg.com.br
 * updates: centos.xpg.com.br
Available Packages
Name        : origin-docker-excluder
Arch        : noarch
Version     : 3.11.0
Release     : 0.alpha.0.568.10b4e5e
Size        : 3.7 k
Repo        : origin-repo
Summary     : Exclude docker packages from updates
URL         : https://github.com/openshift/origin
License     : ASL 2.0
Description : Certain versions of OpenShift will not work with newer versions
            : of docker.  Exclude those versions of docker.
            : 
            : origin-docker-excluder exclude - No major docker updates
            : origin-docker-excluder unexclude - docker packages can be updated

```

**Comment by drajen** [comment]
I'm seeing this on RHEL 7.5 with OCP 3.10 as well as on CentOS.

**Comment by glemsom** [comment]
Seems the mirrors are starting to have 3.10 packages - though the latest symlink is not made yet to 3.10.
I have NO idea what the current state of the 3.10 packages for CentOS is - so, use this with caution !

Append a new repo for 3.10, and ansible should be able to fetch the required versions.

```
# cat /etc/yum.repos.d/CentOS-OpenShift-Origin-310.repo
[centos-openshift-origin310]
name=CentOS OpenShift Origin
baseurl=http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin310/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-PaaS

[centos-openshift-origin-testing310]
name=CentOS OpenShift Origin Testing
baseurl=http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin310/
enabled=0
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/openshift-ansible-CentOS-SIG-PaaS

[centos-openshift-origin-source310]
name=CentOS OpenShift Origin Source
baseurl=http://vault.centos.org/centos/7/paas/Source/openshift-origin310/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/openshift-ansible-CentOS-SIG-PaaS
```

**Comment by DanyC97** [comment]
i was just made aware of this issue by @isaldarriaga , thank you !

so let me try and answer/ clarify few things following some comments made ...

@Cajga  you said

> So the main issue here is that the CentOS guys are lacking with the testing behind the upstream version.

so for everyone benefit, in case you have been following the dev openshift maling list, back in January/ February it was announced that the only 2 active members of the [PaaS SIG](https://wiki.centos.org/SpecialInterestGroup/PaaS) who are in dealing with building the OpenShift rpms for CentOS are stepping down and as such i decided to step in as a volunteer and keep the light on. 

As part of the transition i had to hit the ground running and learn as much as i could in a ver short period of time while we had to release 3.9/3.7 as well as fix the automation etc ....

Fast forward to 3.10 release i think we've done a decent job releasing the rpms very short after the official origin 3.10 release was cut off.

If you would have followed the #8399 you would have noticed my comment and the last minute [issue we hit](https://github.com/openshift/openshift-ansible/issues/8399#issuecomment-410161585) but it was fixed with help of @sdodson 

Now when the rpms were created i sent an email out on dev mailer announcing the process - https://github.com/openshift/openshift-ansible/issues/8399#issuecomment-410189290 and asking for community help in testing it.

I waited 1 week and during this time a user confirmed he was able to install the cluster and no missing packages needs to be solved - https://github.com/openshift/openshift-ansible/issues/8399#issuecomment-411094581

As such i went out and promoted to -testing and then -[release](http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin310/) repo.

After that the **only** person who reported an issue with missing packages and who stay with me helping with the tests was @isaldarriaga !

Looking at the comments in this issue i see there is one issue which i said https://github.com/openshift/openshift-ansible/issues/8399#issuecomment-412304263 i'll fix it - sorry for missing this step (guess is part of missing steps which i'll document in the PaaS SIG wiki)

Now regarding

> I'm getting the feeling that CentOS is not the first class citizen of this project

so here is the true answer ...

* indeed there is more which needs to be done in terms of testing -> today is all manual tests done by the PaaS SIG members
* if anyone wants to help and improving things then i invite you to join the Meeting - see PaaS SIG wiki above - and get involved ( the reality is that when i joined there were other 5 guys who all had big ideas, sadly after 4 months only @rimolive & @sdodson are still hanging around, everyone else ...vanished )

I hope to see some new faces soon .. 

Once i fix the last remaining issue i'll respond here asap.

**Comment by DanyC97** [comment]
@glemsom your solution is only for testing, the [-release repo](http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin310/) should be used for production.

**Comment by DanyC97** [comment]
and by the way @Cajga @glemsom @drajen & whoever is interested in this rpms topic:

Not sure if you are aware but a while ago (before even i joined SIG), the process put in placed assumed that:

> In order for users to easily use the Released Repo's, they need to install the corresponding centos-release-openshift-origin3* rpm. This package is in the main centos-extras repository, so it is easy to install. This package contains the yum configuration files so users can use our Released Repos

If you will get the rpm from [here](http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-openshift-origin310-1-1.el7.centos.noarch.rpm) you will get the right repo in /etc/yum.repos.d/ which will be 

```
cat << EOF >> %{buildroot}%{_sysconfdir}/yum.repos.d/CentOS-OpenShift-Origin%{origin_release_nodot}.repo
[centos-openshift-origin%{origin_release_nodot}]
name=CentOS OpenShift Origin
baseurl=http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin%{origin_release_nodot}/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-PaaS

[centos-openshift-origin%{origin_release_nodot}-testing]
name=CentOS OpenShift Origin Testing
baseurl=http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin%{origin_release_nodot}/
enabled=0
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-PaaS

[centos-openshift-origin%{origin_release_nodot}-debuginfo]
name=CentOS OpenShift Origin DebugInfo
baseurl=http://debuginfo.centos.org/centos/7/paas/x86_64/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-PaaS

[centos-openshift-origin%{origin_release_nodot}-source]
name=CentOS OpenShift Origin Source
baseurl=http://vault.centos.org/centos/7/paas/Source/openshift-origin%{origin_release_nodot}/
enabled=0
gpgcheck=1

```

So that is what i knew hence what i followed ...
Saying that i'll look into updating http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/ although that is the _old_ repo and as said a long time ago it was moved to sub-dirs for each release.

**Comment by DanyC97** [comment]
excellent, thank you for confirmation @danscarf !

Suggest for everyone who has any issue to move the discussion over the [open](https://github.com/openshift/openshift-ansible/issues/8399) issue so i can get any github notifications.
