### ISSUE TITLE
Openshift v1.0.7: Installation failure. Docker 1.8.x dependency issue

### ISSUE THREAD

**Issue by sureddy** [openshift/openshift-ansible#780]
when i tried to install openshift origin v1.0.7 release, it failed with the following message:

<pre>failed: [n01.azure.qtz.io] => {"changed": true, "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\nResolving Dependencies\n--> Running transaction check\n---> Package origin-node.x86_64 0:1.0.7-0.git.6899.032e1ef.el7.centos will be installed\n--> Processing Dependency: origin = 1.0.7-0.git.6899.032e1ef.el7.centos for package: origin-node-1.0.7-0.git.6899.032e1ef.el7.centos.x86_64\n--> Processing Dependency: docker-io >= 1.8.2 for package: origin-node-1.0.7-0.git.6899.032e1ef.el7.centos.x86_64\n--> Processing Dependency: nfs-utils for package: origin-node-1.0.7-0.git.6899.032e1ef.el7.centos.x86_64\n--> Processing Dependency: socat for package: origin-node-1.0.7-0.git.6899.032e1ef.el7.centos.x86_64\n---> Package tuned-profiles-origin-node.x86_64 0:1.0.7-0.git.6899.032e1ef.el7.centos will be installed\n--> Running transaction check\n---> Package nfs-utils.x86_64 1:1.3.0-0.8.el7 will be installed\n--> Processing Dependency: libtirpc >= 0.2.3-1 for package: 1:nfs-utils-1.3.0-0.8.el7.x86_64\n--> Processing Dependency: gssproxy >= 0.3.0-0 for package: 1:nfs-utils-1.3.0-0.8.el7.x86_64\n--> Processing Dependency: rpcbind for package: 1:nfs-utils-1.3.0-0.8.el7.x86_64\n--> Processing Dependency: quota for package: 1:nfs-utils-1.3.0-0.8.el7.x86_64\n--> Processing Dependency: libnfsidmap for package: 1:nfs-utils-1.3.0-0.8.el7.x86_64\n--> Processing Dependency: libevent for package: 1:nfs-utils-1.3.0-0.8.el7.x86_64\n--> Processing Dependency: keyutils for package: 1:nfs-utils-1.3.0-0.8.el7.x86_64\n--> Processing Dependency: libtirpc.so.1()(64bit) for package: 1:nfs-utils-1.3.0-0.8.el7.x86_64\n--> Processing Dependency: libnfsidmap.so.0()(64bit) for package: 1:nfs-utils-1.3.0-0.8.el7.x86_64\n--> Processing Dependency: libevent-2.0.so.5()(64bit) for package: 1:nfs-utils-1.3.0-0.8.el7.x86_64\n---> Package origin.x86_64 0:1.0.7-0.git.6899.032e1ef.el7.centos will be installed\n--> Processing Dependency: origin-clients = 1.0.7-0.git.6899.032e1ef.el7.centos for package: origin-1.0.7-0.git.6899.032e1ef.el7.centos.x86_64\n---> Package origin-node.x86_64 0:1.0.7-0.git.6899.032e1ef.el7.centos will be installed\n--> Processing Dependency: docker-io >= 1.8.2 for package: origin-node-1.0.7-0.git.6899.032e1ef.el7.centos.x86_64\n---> Package socat.x86_64 0:1.7.2.2-5.el7 will be installed\n--> Running transaction check\n---> Package gssproxy.x86_64 0:0.3.0-10.el7 will be installed\n--> Processing Dependency: libverto-tevent for package: gssproxy-0.3.0-10.el7.x86_64\n--> Processing Dependency: libini_config.so.3(INI_CONFIG_1.1.0)(64bit) for package: gssproxy-0.3.0-10.el7.x86_64\n--> Processing Dependency: libref_array.so.1()(64bit) for package: gssproxy-0.3.0-10.el7.x86_64\n--> Processing Dependency: libini_config.so.3()(64bit) for package: gssproxy-0.3.0-10.el7.x86_64\n--> Processing Dependency: libcollection.so.2()(64bit) for package: gssproxy-0.3.0-10.el7.x86_64\n--> Processing Dependency: libbasicobjects.so.0()(64bit) for package: gssproxy-0.3.0-10.el7.x86_64\n---> Package keyutils.x86_64 0:1.5.8-3.el7 will be installed\n---> Package libevent.x86_64 0:2.0.21-4.el7 will be installed\n---> Package libnfsidmap.x86_64 0:0.25-11.el7 will be installed\n---> Package libtirpc.x86_64 0:0.2.4-0.5.el7 will be installed\n---> Package origin-clients.x86_64 0:1.0.7-0.git.6899.032e1ef.el7.centos will be installed\n---> Package origin-node.x86_64 0:1.0.7-0.git.6899.032e1ef.el7.centos will be installed\n--> Processing Dependency: docker-io >= 1.8.2 for package: origin-node-1.0.7-0.git.6899.032e1ef.el7.centos.x86_64\n---> Package quota.x86_64 1:4.01-11.el7 will be installed\n--> Processing Dependency: quota-nls = 1:4.01-11.el7 for package: 1:quota-4.01-11.el7.x86_64\n--> Processing Dependency: tcp_wrappers for package: 1:quota-4.01-11.el7.x86_64\n---> Package rpcbind.x86_64 0:0.2.0-26.el7 will be installed\n--> Running transaction check\n---> Package libbasicobjects.x86_64 0:0.1.1-24.el7 will be installed\n---> Package libcollection.x86_64 0:0.6.2-24.el7 will be installed\n---> Package libini_config.x86_64 0:1.1.0-24.el7 will be installed\n--> Processing Dependency: libpath_utils.so.1(PATH_UTILS_0.2.1)(64bit) for package: libini_config-1.1.0-24.el7.x86_64\n--> Processing Dependency: libpath_utils.so.1()(64bit) for package: libini_config-1.1.0-24.el7.x86_64\n---> Package libref_array.x86_64 0:0.1.4-24.el7 will be installed\n---> Package libverto-tevent.x86_64 0:0.2.5-4.el7 will be installed\n--> Processing Dependency: libtevent.so.0(TEVENT_0.9.9)(64bit) for package: libverto-tevent-0.2.5-4.el7.x86_64\n--> Processing Dependency: libtalloc.so.2(TALLOC_2.0.2)(64bit) for package: libverto-tevent-0.2.5-4.el7.x86_64\n--> Processing Dependency: libtevent.so.0()(64bit) for package: libverto-tevent-0.2.5-4.el7.x86_64\n--> Processing Dependency: libtalloc.so.2()(64bit) for package: libverto-tevent-0.2.5-4.el7.x86_64\n---> Package origin-node.x86_64 0:1.0.7-0.git.6899.032e1ef.el7.centos will be installed\n--> Processing Dependency: docker-io >= 1.8.2 for package: origin-node-1.0.7-0.git.6899.032e1ef.el7.centos.x86_64\n---> Package quota-nls.noarch 1:4.01-11.el7 will be installed\n---> Package tcp_wrappers.x86_64 0:7.6-77.el7 will be installed\n--> Running transaction check\n---> Package libpath_utils.x86_64 0:0.2.1-24.el7 will be installed\n---> Package libtalloc.x86_64 0:2.1.1-1.el7 will be installed\n---> Package libtevent.x86_64 0:0.9.21-3.el7 will be installed\n---> Package origin-node.x86_64 0:1.0.7-0.git.6899.032e1ef.el7.centos will be installed\n--> Processing Dependency: docker-io >= 1.8.2 for package: origin-node-1.0.7-0.git.6899.032e1ef.el7.centos.x86_64\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
msg: Error: Package: origin-node-1.0.7-0.git.6899.032e1ef.el7.centos.x86_64 (maxamillion-origin-next)
           Requires: docker-io >= 1.8.2
           Available: docker-1.3.2-4.el7.centos.x86_64 (extras)
               docker-io = 1.3.2
           Available: docker-1.4.1-37.el7.centos.x86_64 (extras)
               docker-io = 1.4.1-37.el7.centos
           Available: docker-1.5.0-27.el7.centos.x86_64 (extras)
               docker-io = 1.5.0-27
           Available: docker-1.5.0-28.el7.centos.x86_64 (extras)
               docker-io = 1.5.0-28
           Available: docker-1.6.0-11.el7.centos.x86_64 (extras)
               docker-io = 1.6.0-11
           Available: docker-1.6.0-11.0.1.el7.centos.x86_64 (extras)
               docker-io = 1.6.0-11.0.1
           Available: docker-1.6.2-14.el7.centos.x86_64 (extras)
               docker-io = 1.6.2-14
           Available: docker-1.7.1-108.el7.centos.x86_64 (extras)
               docker-io = 1.7.1-108.el7.centos

Then added additional repos to the ansible hosts:
openshift_additional_repos=[{'id': 'techntransit', 'name': 'techntransit', 'baseurl': 'https://yum.dockerproject.org/repo/main/centos/7', 'enabled': 1, 'gpgcheck': 1, 'gpgkey': 'https://yum.dockerproject.org/gpg'}]

still, I get the same error. I also tried creating techntransit.repo in roles/openshift_repos/files/origin/repos/techtransit.repo

But, still problem persists. Error says docker version needed >= 1.8.2 but 
Available: docker-1.7.1-108.el7.centos.x86_64 (extras)
               docker-io = 1.7.1-108.el7.centos

How do i fix it? any thoughts?
</pre>

**Comment by detiber** [comment]
@sureddy Docker 1.8.2 hasn't been released to the CentOS repos yet.  We'll need to add a build to the copr repo that we use for shipping the OpenShift Origin packages.

@sdodson could you add docker-1.8.2 (and the associated SELinux package) to the copr?

**Comment by sdodson** [comment]
@detiber Ahh crap, I didn't realize that would make the v1.0.7 tag. I'd rather just patch the COPR RPM not to require 1.8 just yet it's only needed for logging integration. Is that OK?

**Comment by sdodson** [comment]
@sureddy I've pushed a new build that doesn't require docker-1.8.2. You may need to run `yum clean all` before it shows up.

**Comment by sureddy** [comment]
@detiber @sdodson thanks.  I tried adding docker repo to additional repos but it didn't work either.
openshift_additional_repos=[{'id': 'techntransit', 'name': 'techntransit', 'baseurl': 'https://yum.dockerproject.org/repo/main/centos/7', 'enabled': 1, 'gpgcheck': 1, 'gpgkey': 'https://yum.dockerproject.org/gpg'}]

let me know once you patch the copr rpm. we are currently on 1.0.6 and love to get our hands on 1.0.7.

**Comment by sureddy** [comment]
@sdodson thank you. will give it a try.

**Comment by sureddy** [comment]
@sdodson installation went fine. however, nodes are not starting (esp. Kubelet not starting up.) is this something related to Docker issue? I checked the docker status. Docker is running on the nodes:
<pre>
Last login: Sun Nov  1 22:33:53 2015 from 13.7.193.98
[centos@b ~]$ systemctl status docker.service
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled)
  Drop-In: /usr/lib/systemd/system/docker.service.d
           └─docker-sdn-ovs.conf
   Active: active (running) since Sun 2015-11-01 21:55:20 UTC; 46min ago
     Docs: http://docs.docker.com
 Main PID: 31354 (docker)
   CGroup: /system.slice/docker.service
           └─31354 /usr/bin/docker -d --insecure-registry=172.30.0.0/16 --selinux-enabled -b=lbr0 --mtu=1450
</pre>

Here is the output from <pre> oc describe node </pre> command.
<pre>
[centos@a ~]$ oc describe node b.bdf.io
Name:			b.bdf.io
Labels:			kubernetes.io/hostname=b.bdf.io,region=infra,zone=default
CreationTimestamp:	Sun, 01 Nov 2015 21:55:18 +0000
Phase:
Conditions:
  Type		Status		LastHeartbeatTime			LastTransitionTime			Reason			Message
  ────		──────		─────────────────			──────────────────			──────			───────
  Ready 	Unknown 	Sun, 01 Nov 2015 21:55:18 +0000 	Sun, 01 Nov 2015 21:56:00 +0000 	NodeStatusUnknown 	Kubelet stopped posting node status.
Addresses:	13.7.193.99,13.7.193.99
Capacity:
 memory:	65809600Ki
 pods:		40
 cpu:		16
System Info:
 Machine ID:			19d82c8902374e7caa655973bd7a6e6a
 System UUID:			9BD67DA2-DA30-48D3-A4B2-A869906221B2
 Boot ID:			fec1251b-b25c-426b-aeb6-3c8ece43cf29
 Kernel Version:		3.10.0-229.7.2.el7.x86_64
 OS Image:			CentOS Linux 7 (Core)
 Container Runtime Version:	docker://1.7.1
 Kubelet Version:		v1.2.0-alpha.1-1107-g4c8e6f4
 Kube-Proxy Version:		v1.2.0-alpha.1-1107-g4c8e6f4
ExternalID:			b.bdf.io
Non-terminated Pods:		(0 in total)
  Namespace			Name		CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ─────────			────		────────────	──────────	───────────────	─────────────
Allocated resources:
  (Total limits may be over 100%, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ────────────	──────────	───────────────	─────────────
  0 (0%)	0 (0%)		0 (0%)		0 (0%)
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Reason		Message
  ─────────	────────	─────	────			─────────────	──────		───────
  43m		43m		1	{kubelet b.bdf.io}			Starting	Starting kubelet.
  43m		43m		1	{kubelet b.bdf.io}			NodeReady	Node b.bdf.io status is now: NodeReady
  43m		43m		1	{controllermanager }			RegisteredNode	Node b.bdf.io event: Registered Node b.bdf.io in NodeController
  42m		42m		1	{controllermanager }			NodeNotReady	Node b.bdf.io status is now: NodeNotReady
  25m		25m		1	{controllermanager }			RegisteredNode	Node b.bdf.io event: Registered Node b.bdf.io in NodeController

</pre>

**Comment by sdodson** [comment]
Is there an error in the node logs indicating why it didn't start properly?

journalctl -u origin-node

**Comment by sureddy** [comment]
Here is the last few lines of the log files from the node(s). (similar messages on all nodes)
<pre>
Nov 01 21:55:20 c.bdf.io origin-node[26898]: ovs-vsctl: no port named vovsbr
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + true
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + ovs-vsctl add-port br0 vovsbr -- set Interface vovsbr ofport_request=9
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + ip link set lbr0 down
Nov 01 21:55:20 c.bdf.io origin-node[26898]: Cannot find device "lbr0"
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + true
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + brctl delbr lbr0
Nov 01 21:55:20 c.bdf.io origin-node[26898]: bridge lbr0 doesn't exist; can't delete it
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + true
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + brctl addbr lbr0
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + ip addr add 10.1.3.1/24 dev lbr0
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + ip link set lbr0 up
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + brctl addif lbr0 vlinuxbr
Nov 01 21:55:20 c.bdf.io systemd[1]: origin-node.service: main process exited, code=exited, status=255/n/a
Nov 01 21:55:20 c.bdf.io systemd[1]: Unit origin-node.service entered failed state.
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + ip addr add 10.1.3.1/24 dev tun0
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + ip link set tun0 up
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + ip route add 10.1.0.0/16 dev tun0 proto kernel scope link
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + docker_network_config update
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + '[' -z '' ']'
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + DOCKER_NETWORK_OPTIONS='-b=lbr0 --mtu=1450'
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + local conf=/run/openshift-sdn/docker-network
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + case "$1" in
Nov 01 21:55:20 c.bdf.io origin-node[26898]: ++ dirname /run/openshift-sdn/docker-network
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + mkdir -p /run/openshift-sdn
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + cat
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + systemctl daemon-reload
Nov 01 21:55:20 c.bdf.io origin-node[26898]: + systemctl restart docker.service
Nov 01 21:55:20 c.bdf.io origin-node[26898]: Job for docker.service canceled.
Nov 01 21:55:20 c.bdf.io origin-node[26898]: Error: exit status 1
Nov 01 21:55:20 c.bdf.io origin-node[26898]: F1101 21:55:20.267199   26898 flatsdn.go:42] SDN Node failed: exit status 1
</pre>

**Comment by sdodson** [comment]
And if you try to restart origin-node it continues to fail? It seems like
there's been some recent problems with the sdn initialization.

**Comment by sureddy** [comment]
@sdodson it worked after rebooting nodes. thanks for your help.
[root@a centos]# oc get nodes
<pre>
NAME       LABELS                                                             STATUS                     AGE
a.bdf.io   kubernetes.io/hostname=a.bdf.io,region=infra,zone=default          Ready,SchedulingDisabled   1h
b.bdf.io   kubernetes.io/hostname=b.bdf.io,region=infra,zone=default          Ready                      1h
c.bdf.io   kubernetes.io/hostname=c.bdf.io,region=primary,zone=americas-107   Ready                      1h
d.bdf.io   kubernetes.io/hostname=d.bdf.io,region=primary,zone=americas-107   Ready                      1h
</pre>
[root@a centos]# oc get pods
<pre>
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-deploy   1/1       Running   0          1h
docker-registry-1-uwxxu    1/1       Running   0          18s
router-1-deploy            1/1       Running   0          1h
router-1-s685u             1/1       Running   0          18s
[root@a centos]#
</pre>

**Comment by sureddy** [comment]
@sdodson FYI, all nodes consistently shown the same error message on starting up SDN. Once i rebooted them all came up fine. is this a symptom of something we need to watch for?

**Comment by JohnTheodore** [comment]
fyi, https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/epel-7-x86_64/00132014-origin/ these RPMs these RPMs worked for me. These were built yesterday. I tried some RPMs that were built on Friday, but those gave me this docker-io dependency problem.

**Comment by sdodson** [comment]
> Nov 01 21:55:20 c.bdf.io origin-node[26898]: Job for docker.service canceled.

@sureddy that line is what I'm not sure about, the SDN reconfigures docker networking by placing an environment file in /run/openshift-sdn/docker-network and then restarts docker. If pods between two hosts can reach each other then your SDN is working properly. I just don't understand why it's saying the restart has been canceled.

**Comment by sureddy** [comment]
@sdodson Installation went fine and all services are up and running. Able to create applications. However, none of the routes are working. router not able to route traffic to endpoints. NOTE: This installation in running in Microsoft Azure using CentOS 7. Is this something to do with SDN? Azure Virtual Network is on 172.16.0.0/24 network.

**Comment by nak3** [comment]
I got same issue and filed here https://bugzilla.redhat.com/show_bug.cgi?id=1279925

@sureddy Please let us know. Did you add "openshift_master_portal_net" to your `/etc/ansible/hosts`? I can't reproduce this issue 100%. When I got this issue, I put it. So please let me confirm it.
