### ISSUE TITLE
Question - why a 3.7 hotfix branch?

### ISSUE THREAD

**Issue by DanyC97** [openshift/openshift-ansible#7846]
@vrutkovs @sdodson sorry to keep nudging you on this subject but i just came across the new 3.7 hostfix branch and now i'm very confused after all the chat we had on irc.

Can you please shed some light on the rational of having this hotfix branch ? Should i understand that nothing will be pushed to 3.7 branch as it might be EOL ?

**Comment by sdodson** [comment]
That's correct, we needed to cherry pick a fix atop an older tag.

**Comment by DanyC97** [comment]
thank you for the info @sdodson @vrutkovs , i got the answer, will close it
