### ISSUE TITLE
openshift-infra rebuild

### ISSUE THREAD

**Issue by coolpalani** [openshift/openshift-ansible#7857]
I have deployed OpenShift 3.7 with 6 Nodes (1 master node, 2 infra node, 2 worker node, 1 NFS node)
recently cassandra pods were frequently restarted. Due to this problem hawkular-metrics were broke.

Is there any way to rebuild openshift-infra to bring this metrics services without rebuild whole setup

**Comment by coolpalani** [comment]
Can some one give suggestions to fix this issue

**Comment by vrutkovs** [comment]
There is no separate playbook for metrics in 3.7 (there is in 3.9 though), so you'll have to enable metrics in inventory and re-run `playbooks/byo/config.yml`
