### ISSUE TITLE
syntax error in generate_session_secrets.yml#L26

### ISSUE THREAD

**Issue by mountkin** [openshift/openshift-ansible#7873]
https://github.com/openshift/openshift-ansible/blob/fe7e4702fe8654a3d97d218dd7250f1b938c3a7c/roles/openshift_control_plane/tasks/generate_session_secrets.yml#L26

Should be `- l_osm_session_secrets_slurp is defined `, I guess :smiley_cat:

**Comment by vrutkovs** [comment]
Would be fixed by #7868
