### ISSUE TITLE
RFE a dedicated playbook for (re-)deploying integrated docker-registry

### ISSUE THREAD

**Issue by miminar** [openshift/openshift-ansible#7917]
Recently requested by a customer and really nice to have.

Expected to have something like `playbooks/registry/config.yml` that would deploy/modify just the registry component. This would make it consistent with other components such as [playbooks/openshift-metrics/config.yml](https://github.com/openshift/openshift-ansible/blob/b1fe9ae1031c1084313feec7e82546a9182e1220/playbooks/openshift-metrics/config.yml) [playbooks/openshift-service-catalog/config.yml](https://github.com/openshift/openshift-ansible/blob/b1fe9ae1031c1084313feec7e82546a9182e1220/playbooks/openshift-service-catalog/config.yml) and others.

**Comment by michaelgugino** [comment]
In 3.9 and master we have playbooks/openshift-hosted/deploy_registry.yml that should work for this purpose.

**Comment by miminar** [comment]
Cool, haven't notice that. I'm working on registry re-deployment documentation in https://github.com/openshift/openshift-docs/pull/8666. I'll mention this.

**Comment by miminar** [comment]
Closing.
