### ISSUE TITLE
Premature check for started service

### ISSUE THREAD

**Issue by miminar** [openshift/openshift-ansible#797]
Ansible backs off too early during a check for started master service. Installation failed for me with:

    NOTIFIED: [openshift_master | restart master] ********************************* 
    failed: [atomic-master.miminar.local] => {"failed": true}
    msg: Job for atomic-openshift-master.service failed because the control process exited with error code. See "systemctl status atomic-openshift-master.service" and "journalctl -xe" for details.

    FATAL: all hosts have already failed -- aborting

`ansible-playbook` terminated at **09:11:10**. However, service started three seconds later:

    $ systemctl status atomic-openshift-master
    ● atomic-openshift-master.service - Atomic OpenShift Master
       Loaded: loaded (/usr/lib/systemd/system/atomic-openshift-master.service; enabled; vendor preset: disabled)
       Active: active (running) since Út 2015-11-03 09:11:13 CET; 26s ago
         Docs: https://github.com/openshift/origin
     Main PID: 38192 (openshift)
       CGroup: /system.slice/atomic-openshift-master.service
               └─38192 /usr/bin/openshift start master --config=/etc/origin/master/master-config.yaml --loglevel=2

Used:
atomic-openshift-3.0.2.905-0.git.0.85d6f88.el7aos.x86_64

openshift-ansible revision 9e586db2931863780ce6598bb64b3a134c2fdb27.

**Comment by detiber** [comment]
@miminar are you able to reliably reproduce this?

The failure from that ansible task seems to indicate that systemd reported the startup as failed. In the past we've seen this arise from the daemon taking longer to startup than the DefaultTimeoutStartSec value in the systemd config (defaults to 90s).

If you are seeing repeatable startup times > 90s, then we can update the systemd unit file that we ship in the packaging to set TimeoutStartSec to a value larger than the default.

**Comment by miminar** [comment]
No, not anymore with recent versions (atomic-openshift-3.1.0.4-1.git.2.c5fa845.el7aos.x86_64). Closing.
