### ISSUE TITLE
[3.9] deploying from tower fails on trying to do sudo on tower

### ISSUE THREAD

**Issue by MansM** [openshift/openshift-ansible#7973]
#### Description
```
TASK [openshift_hosted_templates : Create local temp dir for OpenShift hosted templates copy] ***
task path: /var/lib/awx/projects/_11797__openshift_ansible_39/roles/openshift_hosted_templates/tasks/main.yml:2
Monday 16 April 2018  12:46:46 +0200 (0:00:00.148)       0:15:49.433 **********
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-tniyqssyjoftymqffrbzbcpklzovknph; /usr/bin/python'"'"' && sleep 0'
fatal: [xxxxxxxx -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

in https://github.com/openshift/openshift-ansible/pull/6597 become=false has been removed on local actions. Which results in ansible trying to use sudo on Tower. 

Adding
```
[local]
localhost ansible_become=false
``` 
to the inventory did seem to work. But imo this should be needed

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
2.5

If you're operating from a **git clone**:

4b7b6ce08ba5abebd147e961aa5a41e30559826c

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
deploy 3.9 from tower

##### Expected Results
deployed cluster

##### Observed Results
see top

##### Additional Information
Tower 3.2.3

**Comment by liveaverage** [comment]
Encountering the same on Tower 3.2.6 (Ansible 2.6.3) when deploying 3.10. I also had to force remote_user, but working great with workaround. Thank you @MansM 

```
[local]
localhost ansible_become=false ansible_user=awx
```
Thanks for provi

**Comment by karlahag** [comment]
@liveaverage I am experiencing the same issue on a Tower-installation 3.2.6 and Ansible 2.5.2 using zabbix_api-module to run locally on managed host in AWS.
Not sure where the block you mention should be entered though? Is it some setting in Tower or?

**Comment by liveaverage** [comment]
@karlahag you just need to add the following to your inventory file (at least as related to openshift-ansible):

```
[OSEv3:children]
masters
nodes
etcd
nfs

[masters]
r1.gxr.me

[etcd]
r1.gxr.me

[nodes]
r1.gxr.me openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}" 
r2.gxr.me openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}" 
r3.gxr.me openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}" 

[nfs]
r1.gxr.me

[local]
localhost ansible_become=false ansible_user=awx
```
Note that you do *not* need to add [local] to [OSEv3:children]

**Comment by karlahag** [comment]
@liveaverage Hmm...using ec2.py generated inventory from AWS. Not sure if and how I can modify them. And thnx for swift response! :)

**Comment by liveaverage** [comment]
No worries @karlahag -- can't you simply define multiple inventory sources to include `localhost`? It's just convenient for me to include it in an SCM controlled inventory file sourced from a Project [for openshift-ansible deployments]. I use the same `localhost` workaround when interacting with VMware inventory dynamically queried via vmware_inventory.py

**Comment by karlahag** [comment]
@liveaverage Oh yes! Worked with adding a second source along with EC2, just pointing to a source controlled inventory file. Thnx again!

**Comment by liveaverage** [comment]
Great! Glad that was enough :)
