### ISSUE TITLE
cannot deploy grafana playbook

### ISSUE THREAD

**Issue by pgeorgiev333** [openshift/openshift-ansible#7994]
The template is wrong:
https://github.com/openshift/openshift-ansible/blob/release-3.9/roles/openshift_grafana/templates/grafana.yml.j2

```
serviceAccountName: {{ grafana_namespace }}
```

This should be whatever service account you specified, not the namespace

**Comment by duritong** [comment]
This is already fixed on master https://github.com/openshift/openshift-ansible/commit/5d87e35546e1fb4d538559148ed89ae4d8b4ea3f

But it's not backported to the release-3.9 branch

CC @codificat

**Comment by codificat** [comment]
Thanks for the input @duritong.

It was actually already backported to release-3.9 in #8081 just a few days after this issue was open. So, this should be fine now.
