### ISSUE TITLE
Update location of htpasswd

### ISSUE THREAD

**Issue by miminar** [openshift/openshift-ansible#800]
Location of htpasswd file is now set to `/etc/openshift/htpasswd` at [inventory/byo/hosts.example](https://github.com/openshift/openshift-ansible/blob/b2c2e8e2f44faee1f8f7ecd084395b9b9260e0a7/inventory/byo/hosts.example#L39). However, `/etc/openshift/` is no longer used for `atomic-enterprise` or `openshift-enterprise` deployments.

What about defaulting to `openshift.common.config_base + '/htpasswd'` when `filename` unset? And comment it in `hosts.example`?

**Comment by abutcher** [comment]
:+1:

**Comment by tbielawa** [comment]
This has been updated.
