### ISSUE TITLE
Enabling cri-o fails if the OpenShift nodes do not have a /home

### ISSUE THREAD

**Issue by dcritch** [openshift/openshift-ansible#8024]
#### Description

> After setting `openshift_use_crio=true` and without a /home,
> running the deploy_cluster.yml playbook the installation will
> fail due to errors starting the cri-o service.

##### Version

```
ansible 2.5.0
  config file = /srv/git/se-labadmin/ansible.cfg
  configured module search path = [u'/srv/git/se-labadmin/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

git describe
openshift-ansible-3.9.22-1-17-g013747080
```

##### Steps To Reproduce
1. Enable crio in the OSEv3 vars: openshift_use_crio=true
2. Provision nodes with no /home directory
3. Run deploy_cluster.yml

##### Expected Results
Successful cluster installation

##### Observed Results

Playbook run fails with following errors:

```
TASK [container_runtime : Start the CRI-O service] ***********************************************************************************************************
Wednesday 18 April 2018  15:40:25 +0000 (0:00:02.150)       0:12:21.989 *******
fatal: [dc-ocp-m1.example.com]: FAILED! => {"changed": false, "msg": "Unable to start service cri-o: Job for cri-o.service failed because the control process exited with error code. See \"systemctl status cri-o.service\" and \"journalctl -xe\" for details.\n"}
<...>
fatal: [dc-ocp-a1.example.com]: FAILED! => {"changed": false, "msg": "Unable to start service cri-o: Job for cri-o.service failed because the control process exited with error code. See \"systemctl status cri-o.service\" and \"journalctl -xe\" for details.\n"}
```

On the node itself, the following cri-o error pops up:
```
Apr 18 15:40:27 dc-ocp-m0 runc: container_linux.go:348: starting container process caused "process_linux.go:399: container init caused \"rootfs_linux.go:58: mounting \\\"/home\\\" to rootfs \\\"/var/lib/containers/atomic/cri-o.0/rootfs\\\" at \\\"/home\\\" caused \\\"stat /home: no such file or directory\\\"\""
```
##### Additional Information

Creating a /home directory (does not need to be a partition) allows cri-o to start and the installation to succeed.

**Comment by dcritch** [comment]
You are right... the no /home is really weird. It seems to be a RHEL 7.5 thing.

I only turned on cri-o over the last week or so, not long after RHEL 7.5 came out, and was getting this error. I went back and built a server with 7.4 vs. 7.5 with the exact same kickstart but different install trees (e.g. newer installer image) and 7.5 doesn't create a /home, at least if you don't create any users.

**Comment by ashcrow** [comment]
I don't know a specific reason as to why ``/home`` is needed. It likely was pulled in since other containers tend to end up wanting to read configs for a specified user.

@mrunalp  @runcom does cri-o **need** ``/home`` to your knowledge?

**Comment by ashcrow** [comment]
In that case it could be removed from the container mount. @runcom once you verified go ahead and pull it for the next release.

**Comment by giuseppe** [comment]
we mounted `/home` as it could be used as well as part of a mount.

I will prepare a PR to cleanup these paths that are not needed anymore once `--bind-mount-prefix` lands in the system container: https://github.com/kubernetes-incubator/cri-o/pull/1526

**Comment by giuseppe** [comment]
@runcom, I've added the change to the PR that was already open.
