### ISSUE TITLE
openshift_prometheus role is checking for infra node existence

### ISSUE THREAD

**Issue by maxamillion** [openshift/openshift-ansible#8028]
#### Description
Currently the `openshift_prometheus` role is checking for infra node existence by selector and the eventual consistency should be acceptable for the daemonset so I think this is an unnecessary check.

https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.9.24-1/roles/openshift_prometheus/tasks/install_prometheus.yaml#L5

Provide a brief description of your issue here. For example:

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
openshift-ansible-3.9.24-1

ansible 2.4.3.0
```

**Comment by pweil-** [comment]
@ironcladlou

**Comment by zgalor** [comment]
From reading https://github.com/Azure/acs-engine/pull/2718,  I understand why you have an issue but I am not sure removing the validation is the best solution.
This validation was added by @abutcher 
I figured this is a common practice in the installer to validate nodes exist.
@abutcher, can you advise here?

**Comment by maxamillion** [comment]
Can't the cluster's eventual consistency be trusted or is there a specific requirement for the deployment that needs to ensure the nodes exist?

**Comment by kargakis** [comment]
> Can't the cluster's eventual consistency be trusted

We *should* be making use of the guarantees provided by k8s. The extra validation seems redundant when used with node bootstrapping where things are expected to turn up in parallel.
