### ISSUE TITLE
origin-node-3.7.1 installing origin-node-3.9.0

### ISSUE THREAD

**Issue by aelmehra** [openshift/openshift-ansible#8030]
#### Description

When installing origin-node-3.7.1 it will actually install origin-node-3.9.0 and update the following rpms:
origin-clients-3.9.0
origin-3.9.0
origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64

##### Version
```
* ansible 2.4.3.0
* openshift-ansible-3.7.44-1-23-ga7bf5e700
```

##### Steps To Reproduce
1. Add the following openshift repo:
```
[centosopenshift]
name=CentOS-$releasever - OpenShift Origin
baseurl=http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OPENSHIFT-7
```
2. yum install origin-node-3.7.1

##### Expected Results
```
# rpm -qa | grep origin
origin-clients-3.7.1-1.el7.git.0.0a2d6a1.x86_64
origin-node-3.7.1-1.el7.git.0.0a2d6a1.x86_64
origin-3.7.1-1.el7.git.0.0a2d6a1.x86_64
```

##### Observed Results
```
# rpm -qa | grep origin
origin-clients-3.9.0-1.el7.git.0.ba7faec.x86_64
origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64
origin-3.9.0-1.el7.git.0.ba7faec.x86_64
```

##### Additional Information
```
# wget http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/origin-node-3.7.1-1.el7.git.0.0a2d6a1.x86_64.rpm
# yum -y install origin-node-3.7.1-1.el7.git.0.0a2d6a1.x86_64.rpm 
# rpm -qa | grep origin
origin-clients-3.7.1-1.el7.git.0.0a2d6a1.x86_64
origin-3.7.1-1.el7.git.0.0a2d6a1.x86_64
origin-node-3.7.1-1.el7.git.0.0a2d6a1.x86_64
```

```
# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```

**Comment by michaelgugino** [comment]
Make sure you specify openshift_release to the appropriate version.

Also, 3.7 should be using http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin37/ now.

**Comment by DanyC97** [comment]
also i'd suggest in addition to what @michaelgugino said that when you open an issue you provide the inventory file you used.

If what @michaelgugino suggested worked, please don't forget to update and close this issue

**Comment by aelmehra** [comment]
Thanks @michaelgugino switching the mirror to openshift-origin37 fixed it. Also, openshift_release was set to 3.7 in my hosts file.
