### ISSUE TITLE
controllerConfig key does not always exist

### ISSUE THREAD

**Issue by kincl** [openshift/openshift-ansible#8056]
Hi,

On this line we are checking for a few new config options but those options don't always exist in the list of `openshift_cert_check_paths` like node-config.yaml which causes this check to error out the ansible run.

https://github.com/openshift/openshift-ansible/blob/62b6faf8f8278250509c2d6d59ee52d555e0e5ae/roles/lib_utils/library/openshift_cert_expiry.py#L509

**Comment by vrutkovs** [comment]
Fixed by https://github.com/openshift/openshift-ansible/pull/8017
