### ISSUE TITLE
With latest master branch, oc login on node fails due to missing CA setup

### ISSUE THREAD

**Issue by adelton** [openshift/openshift-ansible#8077]
#### Description

On a master + one node setup, up to `release-3.9` it was possible to then do

```
oc login https://$MASTER:8443/ -u developer -p password
```

on the node without additional steps. That now fails with

```
The server uses a certificate signed by an unknown authority.
```

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

If you're operating from a **git clone**:

* The output of `git describe`

```
openshift-ansible-3.10.0-0.26.0
```

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

```
package openshift-ansible is not installed
```

##### Steps To Reproduce
1. on both master and node: `cd /etc/yum.repos.d && curl -O https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo`
2. on master `git clone https://github.com/openshift/openshift-ansible openshift-ansible`
3. on master `ansible-playbook -i ansible-inventory /mnt/tests/OpenShift/Origin/install/dist/openshift-ansible/playbooks/prerequisites.yml`
4. on master `ansible-playbook -i ansible-inventory /mnt/tests/OpenShift/Origin/install/dist/openshift-ansible/playbooks/deploy_cluster.yml`
5. on node, `oc login https://master.example.com:8443/ -u developer -p password`

##### Expected Results
Describe what you expected to happen.

```
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>
```

##### Observed Results
Describe what is actually happening.

```
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): n

error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* This is a regression against `release-3.9`.
* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)

```
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```

* Your inventory file (especially any non-standard configuration parameters)

```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_disable_check=memory_availability,docker_storage,disk_availability,package_version
openshift_repos_enable_testing=true
openshift_enable_excluders=false

osm_cluster_network_cidr=10.128.0.0/14
openshift_portal_net=172.30.0.0/16
osm_host_subnet_length=9

openshift_router_selector='node-router=true'
openshift_registry_selector='node-registry=true'
template_service_broker_selector={"node-app": "true"}
openshift_web_console_nodeselector={"node-app": "true"}

openshift_master_identity_providers=[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]

[masters]
master.example.com

[etcd]
master.example.com

[nodes]
master.example.com
node.example.com openshift_schedulable=true openshift_node_labels="{ 'node-router': 'true', 'node-registry': 'true', 'node-app': 'true' }"
```

**Comment by vrutkovs** [comment]
Sound like openshift CA is not being copied to nodes

**Comment by adelton** [comment]
@vrutkovs, yep, that seems to be the cause. Is that a deliberate change?
