### ISSUE TITLE
enabling Prometheus lifecycle APIs

### ISSUE THREAD

**Issue by lucamaf** [openshift/openshift-ansible#8080]
#### Description
Why don't we enable by default in the prometheus template additional APIs like lifecycle

##### Version

I'm trying with the following version

```
ansible 2.5.0
openshift-ansible-3.9.24-1-7-g62b6faf
```

##### Steps To Reproduce
1. curl -XPOST --header "Authorization: Bearer xxxxxxxxxxx" https://prometheus-openshift-metrics.apps.openshift.es/-/reload

##### Expected Results
What I would expect is a successful reload of the rules files in Prometheus
```
200 code
```

##### Observed Results
This is what happening today

```
Lifecycle APIs are not enabled
```

##### Additional Information

```
Nice to have
By the way this is needed to enable additional cadvisor metrics that have been disabled by default in the current prometheus template. I updated the ConfigMap and don't see another elegant way to let the StatefulSet know about the change.
```

**Comment by AvTiMp** [comment]
Its not safe to turn that on said in prometheus doc,  one can just use `kill -HUP 1` instead
