### ISSUE TITLE
if we dont have enough system Requirements

### ISSUE THREAD

**Issue by behzadnm99** [openshift/openshift-ansible#8088]
#### Description
if we dont have enough system Requirements ...

i want to install openshift origin with Advanced Installation on my local system (laptop) with one node and master ... but i dont have enough System Requirements Which are listed in the link below : https://docs.openshift.org/latest/install_config/install/prerequisites.html#hardware
i have 4gb ram only 

i want to know if we dont have enough System Requirements , the installation will not complete?

##### Version
version:latest

**Comment by HP-dufeng** [comment]
You can add this in ansible invertory file
```
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability,package_version
```
