### ISSUE TITLE
dropping a /etc/profile.d/etcd.sh alias as part of configuration

### ISSUE THREAD

**Issue by timothysc** [openshift/openshift-ansible#814]
using etcdctl in a secure-clustered configuration can be challenging due to the full command line params needed, imho it makes a lot more sense to alias the command as part of installation by default on the etcd nodes. 

e.g. 
# alias etcdctl 'etcdclt -C https://ose3-master1.ansible.test.example.com:2379,https://ose3-master2.ansible.test.example.com:2379,https://ose3-master3.ansible.test.example.com:2379 --ca-file /etc/etcd/ca.crt --cert-file=/etc/openshift/master/master.etcd-client.crt --key-file=/etc/openshift/master/master.etcd-client.key' 

/cc @rrati

**Comment by detiber** [comment]
@timothysc @rrati A few questions:

For which users? I don't really see an issue with setting this for the root user, however I wouldn't want to set this globally on the host. We could potentially set it for the ansible_ssh_user as well, but it would need to be invoked under sudo to prevent a permissions issue.

The other thing I wonder about is how many people do we expect to really be running etcdctl on their etcd systems vs running it from a remote host?

Are we going to be causing potential confusion by users by having the alias in place, vs documenting how to configure an alias for it in the docs?

**Comment by timothysc** [comment]
> For which users?

ansible_ssh_user + root 

> how many people do we expect to really be running etcdctl on their etcd systems vs running it from a remote host?

depends... for certain admins that will be diagnosing their etcd-pets it's highly useful. 

>Are we going to be causing potential confusion by users by having the alias in place, vs documenting how to configure an alias for it in the docs?

doubtful, if anything it will ease their burden of re-creating their own alias.

**Comment by detiber** [comment]
I can live with that.

I would like to wait until after 3.1 is released before we make a change that is not completely necessary.

**Comment by timothysc** [comment]
sgtm, until then we may want to call out in documentation.

**Comment by detiber** [comment]
@adellape ^

**Comment by adellape** [comment]
Call out that it may be helpful to create an alias? So far this is the only spot we mention etcdctl at all (under "Multiple etcd Hosts"):

https://docs.openshift.org/latest/install_config/install/advanced_install.html#verifying-the-installation

Could add a little NOTE box after it w/ the tip.

**Comment by detiber** [comment]
@adellape +1 on adding a note for it...  Do we have anything on backing up and restoring etcd? That would be another place we might need to reference this.

**Comment by jayunit100** [comment]
just want to voice a big vote for this.  spent a few hours trying to get etcdctl to talk correctly to etcd, required both https and couldnt use 127 or 0.0.0.0 + the 3 certs mentioned at the beggining of this thread.

**Comment by detiber** [comment]
I created the following trello card so this doesn't fall off the radar again: https://trello.com/c/z7ryCqMH

**Comment by jayunit100** [comment]
awesome thanks !

**Comment by dlbewley** [comment]
i was planning to install an otherwise unused `etcd` package on my masters (where i expect do do most cli admin) just to make `etcdctl` available, and alias commands like:

```bash
etcdctl -C \
    https://ose-ha-etcd-01.example.com:2379,https://ose-ha-etcd-02.example.com:2379,https://ose-ha-etcd-03.example.com:2379 \
    --ca-file=/etc/origin/master/master.etcd-ca.crt \
    --cert-file=/etc/origin/master/master.etcd-client.crt \
    --key-file=/etc/origin/master/master.etcd-client.key cluster-health
```

i just realized that the following works (updated cert paths) from the dedicated etcd hosts, so maybe i'll rethink the above. it feels a bit messy.

```
etcdctl -C \
    https://ose-ha-etcd-01.example.com:2379,https://ose-ha-etcd-02.example.com:2379,https://ose-ha-etcd-03.example.com:2379 \
    --ca-file=/etc/etcd/ca.crt \
    --cert-file=/etc/etcd/peer.crt \
    --key-file=/etc/etcd/peer.key cluster-health
```

**Comment by timothysc** [comment]
@brenton as we roll towards 3.4 and eventually leverage proto-storage with etcd3, this should get elevated to drop a sane alias. 

/cc @jeremyeder
