### ISSUE TITLE
cadvisor metrics are missing due to wrong kubernetes version.

### ISSUE THREAD

**Issue by mrsiano** [openshift/openshift-ansible#8144]
#### Description
installing prometheus via prometheus playbook currently didn't monitor cadvisor metrics.

those metrics are very useful collection, and we can't missed them.

the following [1] if statement fail due to bad float format.
float by default trailing only one zero (i.e 1.1 instead of 1.10)
this bug causes the scraper to missed cadvisr metrics beacuse he looking for kube version 1.7 or later.

currently we use kube 1.10 but the float format record 1.1 so the metrics patch = metrics instead of metrics/cadvisor

[1]
https://github.com/openshift/openshift-ansible/blob/3de29f6d5a3017b57c553c5e2fb63a50994df840/roles/openshift_prometheus/templates/prometheus.yml.j2#L97

##### Version
ocp 3.10
ansible 2.4.3.0

**Comment by Toper2035** [comment]
I have a same problem for prometheus to scrape container metircs from cadvisor on kubernetes 1.10.
