### ISSUE TITLE
etcd image not found

### ISSUE THREAD

**Issue by beerwine** [openshift/openshift-ansible#8171]
#### Description

The etcd image on the fedora registry is not available.

```
TASK [etcd : Pull etcd container] 
**********************************
fatal: [10.0.0.61]: FAILED! => {"changed": false, "cmd": ["docker", "pull", "registry.fedoraproject.org/latest/etcd"], "delta": "0:03:21.083441", "end": "2018-04-27 09:11:22.410788", "msg": "non-zero return code", "rc": 1, "start": "2018-04-27 09:08:01.327347", "stderr": "Error: image latest/etcd:latest not found", "stderr_lines": ["Error: image latest/etcd:latest not found"], "stdout": "Using default tag: latest\nTrying to pull repository registry.fedoraproject.org/latest/etcd ... \nPulling repository registry.fedoraproject.org/latest/etcd", "stdout_lines": ["Using default tag: latest", "Trying to pull repository registry.fedoraproject.org/latest/etcd ... ", "Pulling repository registry.fedoraproject.org/latest/etcd"]}
```

##### Version

`ansible --version`
```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

`git describe`
```
openshift-ansible-3.9.27-1-4-g1969984
```

##### Steps To Reproduce

I was following the installation guide on https://github.com/gshipley/installcentos

##### Additional Information

CentOS Linux release 7.4.1708 (Core)

**Comment by vrutkovs** [comment]
Works fine here:
```
 sudo docker pull registry.fedoraproject.org/latest/etcd
Using default tag: latest
Trying to pull repository registry.fedoraproject.org/latest/etcd ... 
sha256:66cceb759bae4061c4749cb2a8cd5549eb4b84535f2f22d0bf487a997fe00b39: Pulling from registry.fedoraproject.org/latest/etcd
dd4c676bb40c: Pull complete 
a8e40b0e1bae: Pull complete 
Digest: sha256:66cceb759bae4061c4749cb2a8cd5549eb4b84535f2f22d0bf487a997fe00b39
Status: Downloaded newer image for registry.fedoraproject.org/latest/etcd:latest
```

Could you try again? Might be something wrong with Fedora registry

**Comment by beerwine** [comment]
It doesn't work:
```
[root@localhost ~]# docker pull registry.fedoraproject.org/latest/etcd
Using default tag: latest
Trying to pull repository registry.fedoraproject.org/latest/etcd ...
Pulling repository registry.fedoraproject.org/latest/etcd
Error: image latest/etcd:latest not found
```

It waits for a long time after writing `Trying to pull repository registry.fedoraproject.org/latest/etcd ...`

@vrutkovs Maybe you are inside RedHat network where it works ok?

**Comment by vrutkovs** [comment]
>Maybe you are inside RedHat network where it works ok?

I am, tested that it also works from my DO VM:
```
[root@vrutkovs ~]# docker pull registry.fedoraproject.org/latest/etcd
Using default tag: latest
Trying to pull repository registry.fedoraproject.org/latest/etcd ... 
sha256:66cceb759bae4061c4749cb2a8cd5549eb4b84535f2f22d0bf487a997fe00b39: Pulling from registry.fedoraproject.org/latest/etcd
dd4c676bb40c: Pull complete 
a8e40b0e1bae: Pull complete 
Digest: sha256:66cceb759bae4061c4749cb2a8cd5549eb4b84535f2f22d0bf487a997fe00b39
Status: Downloaded newer image for registry.fedoraproject.org/latest/etcd:latest
[root@vrutkovs ~]# ping registry.fedoraproject.org
PING wildcard.fedoraproject.org (67.219.144.68) 56(84) bytes of data.
64 bytes from 67.219.144.68 (67.219.144.68): icmp_seq=1 ttl=55 time=99.3 ms
64 bytes from 67.219.144.68 (67.219.144.68): icmp_seq=2 ttl=55 time=103 ms
64 bytes from 67.219.144.68 (67.219.144.68): icmp_seq=3 ttl=55 time=98.5 ms
^C
--- wildcard.fedoraproject.org ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2004ms
rtt min/avg/max/mdev = 98.521/100.529/103.684/2.258 ms
```

In any case, that looks like a Fedora registry / your network setup issue. Not much openshift-ansible repo can do here, sorry

**Comment by chrisbili** [comment]
Hi @martinmecera  did  you finally get the answer for this issue? 

[root@master openshift-ansible]#
[root@master openshift-ansible]# docker pull registry.fedoraproject.org/latest/etcd
Using default tag: latest
Trying to pull repository registry.fedoraproject.org/latest/etcd ...
Pulling repository registry.fedoraproject.org/latest/etcd
Error: image latest/etcd:latest not found
[root@master openshift-ansible]#
[root@master openshift-ansible]#
[root@master openshift-ansible]# ping registry.fedoraproject.org/latest/etcd
ping: registry.fedoraproject.org/latest/etcd: Name or service not known
[root@master openshift-ansible]# ping registry.fedoraproject.org
PING wildcard.fedoraproject.org (140.211.169.206) 56(84) bytes of data.
64 bytes from proxy09.fedoraproject.org (140.211.169.206): icmp_seq=1 ttl=50 time=167 ms
64 bytes from proxy09.fedoraproject.org (140.211.169.206): icmp_seq=2 ttl=50 time=171 ms
^C

**Comment by balajignanasundaram** [comment]
Even I'm having the same issue, seems  registry.fedoraproject.org/latest/etcd is broken or unavailable. Please help to fix this error in the ansible script in https://github.com/openshift/openshift-ansible.git
