### ISSUE TITLE
Unknown short_version 3.9

### ISSUE THREAD

**Issue by speedfl** [openshift/openshift-ansible#8190]
##### Version

Please put the following version information in the code block
indicated below.

ansible 2.5.1
openshift-ansible-3.7.44-1-44-g79433e4

##### Steps To Reproduce
1. Clone repo checkout tag mentionned
2. Use this ansible

```
# to be save in /etc/ansible/hosts.
# coming from https://docs.openshift.org/latest/install_config/install/advanced_install.html#single-master

# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become=true

openshift_deployment_type=origin

openshift_master_cluster_hostname=master.my-domain.com

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# host group for masters
[masters]
master.my-domain.com

# host group for etcd
[etcd]
master.my-domain.com

# host group for nodes, includes region info
[nodes]
master.my-domain.com
infra.my-domain.com openshift_node_labels="{'region': 'infra'}"
node1.my-domain.com openshift_node_labels="{'region': 'primary'}"
node2.my-domain.com openshift_node_labels="{'region': 'primary'}"
``` 

3. Run  ansible-playbook playbooks/byo/config.yml

##### Expected Results
Describe what you expected to happen.

##### Observed Results
Describe what is actually happening.

```
  1. Hosts:    master.my-domain.com
     Play:     Create OpenShift certificates for master hosts
     Task:     Set Default scheduler predicates and priorities
     Message:  An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_predicates'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unknown short_version 3.9
[root@master openshift-ansible]# Unknown short_version 3.9fatal: [master.gra1.my-domain.com]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_predicates'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unknown short_version 3.9"}
bash: Unknown: command not found
[root@master openshift-ansible]# ansible-playbook playbooks/adhoc/uninstall.yml
 [WARNING]: Could not match supplied host pattern, ignoring: children
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

N/A

**Comment by speedfl** [comment]
I am sorry. I wanted to install 3.9 and not 3.7.

I thought without specifying the version the latest (non alpha and non beta) is taken.

However should I take the openshift-ansible 3.9?

**Comment by DanyC97** [comment]
if you want 3.9 you can get the 3.9. openshift-ansible branch/ rpm however my suggestion is to keep the parameter in your inventory file.

In that way you can control using same openshift-ansible branch (3.9) which origin release to deploy/ install.

**Comment by speedfl** [comment]
OK I will test this evening and let you know :)

**Comment by speedfl** [comment]
Fixed!! Thanks @DanyC97

**Comment by kooroshkdt** [comment]
can you send us your new inventory file , i have same issue , perhaps i can fix it up to.


tnx

**Comment by speedfl** [comment]
You don't need to update your inventory file if you want to install 3.9. Go to your openshift ansible clone and checkout 3.9 branch

If you want 3.7 you have to change openshift_version in your vars

**Comment by kooroshkdt** [comment]
the problem is I using openshift 3.7 centos-release, it's odd, it's trying to use 3.9
