### ISSUE TITLE
registry-console does not start in a disconnected install

### ISSUE THREAD

**Issue by michaelcourcy** [openshift/openshift-ansible#8208]
#### Description

When I make a disconnected install all the pods start except cokpit, this problem does not happen when connected (ie the nat interface is connected).

In the logs (output below) I can see a timeout error because it's trying to pull the image from docker.io while there's no connection to internet.

My questions are : 
- Why this happen only for the registry-console and not for the rest of pods ?
- Is there a workaround ? 

##### Version

    [vagrant@workstation ~]$ ansible --version
    ansible 2.4.2.0
      config file = /etc/ansible/ansible.cfg
      configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/lib/python2.7/site-packages/ansible
      executable location = /usr/bin/ansible
      python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

    [vagrant@workstation openshift-ansible]$ git describe
    openshift-ansible-3.8.37-1

##### Steps To Reproduce

Launch the install  :  

    ansible-playbook -i $ANSIBLE_DIR/inventory $ANSIBLE_DIR/openshift-ansible/playbooks/deploy_cluster.yml

When install finish check all the pods are running 

    [vagrant@workstation openshift-ansible]$ oc get pods --all-namespaces -o wide

##### Expected Results

All the pods shoud have a running status.

##### Observed Results

All the pods have a running status except registry-console which get stuck in deployment 

    [vagrant@workstation openshift-ansible]$ oc get pods --all-namespaces -o wide
    NAMESPACE                           NAME                         READY     STATUS    RESTARTS   AGE       IP              NODE
    default                             docker-registry-1-svsq7      1/1       Running   1          10h       10.130.0.6      node2.lab.example.com
    default                             registry-console-1-deploy    0/1       Error     0          10h       10.129.0.3      node1.lab.example.com
    default                             router-1-mjrz4               1/1       Running   1          10h       172.25.250.11   node1.lab.example.com
    default                             router-1-mmpv5               1/1       Running   1          10h       172.25.250.12   node2.lab.example.com
    kube-service-catalog                apiserver-d9rjk              1/1       Running   1          10h       10.128.0.5      master.lab.example.com
    kube-service-catalog                controller-manager-dl2mx     1/1       Running   3          10h       10.128.0.4      master.lab.example.com
    openshift-template-service-broker   apiserver-c5sjm              1/1       Running   1          10h       10.129.0.9      node1.lab.example.com
    openshift-template-service-broker   apiserver-cj772              1/1       Running   1          10h       10.130.0.5      node2.lab.example.com
    openshift-web-console               webconsole-119163331-txc9r   1/1       Running   1          10h       10.129.0.10     node1.lab.example.com

The events in the logs and image-stream are self-explanatory : 

    [root@node1 ~]# grep cockpit /var/log/messages
    .....
    May  1 01:09:58 node1 dockerd-current: time="2018-05-01T01:09:58.330556555+02:00" level=error msg="Not continuing with pull after error: 
    Network timed out while trying to connect to https://index.docker.io/v1/repositories/cockpit/kubernetes/images. 
    You may want to check your internet connection or if you are behind a proxy."
    .....
	
	
    [root@workstation vagrant]# oc get is registry-console -o yaml
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        description: Atomic Registry console
        openshift.io/generated-by: OpenShiftNewApp
        openshift.io/image.dockerRepositoryCheck: 2018-04-30T23:09:12Z
      creationTimestamp: 2018-04-30T23:09:02Z
      generation: 2
      labels:
        app: registry-console
        createdBy: registry-console-template
      name: registry-console
      namespace: default
      resourceVersion: "1828"
      selfLink: /oapi/v1/namespaces/default/imagestreams/registry-console
      uid: 78d6d3ec-4ccb-11e8-84c5-08002776f3cf
    spec:
      lookupPolicy:
        local: false
      tags:
      - annotations: null
        from:
          kind: DockerImage
          name: docker.io/cockpit/kubernetes:latest
        generation: 2
        importPolicy: {}
        name: latest
        referencePolicy:
          type: Source
    status:
      dockerImageRepository: docker-registry.default.svc:5000/default/registry-console
      tags:
      - conditions:
        - generation: 2
          lastTransitionTime: 2018-04-30T23:09:12Z
          message: 'Internal error occurred: Get https://registry-1.docker.io/v2/: dial
            tcp: lookup registry-1.docker.io on 10.0.2.15:53: read udp 10.0.2.15:36623->10.0.2.15:53:
            i/o timeout'
          reason: InternalError
          status: "False"
          type: ImportSuccess
        items: null
        tag: latest

##### Additional Information

My inventory file :  

    [OSEv3:children]
    masters
    nodes
    etcd
    
    # Set variables common for all OSEv3 hosts
    [OSEv3:vars]
    # SSH user, this user should allow ssh based auth without requiring a password
    ansible_ssh_user=root
    # If ansible_ssh_user is not root, ansible_become must be set to true
    #ansible_become=true
    
    
    enable_excluders=False
    enable_docker_excluder=False
    ansible_service_broker_install=False
    
    
    deployment_type=origin
    openshift_deployment_type=origin
    
    # Specify the generic release of OpenShift to install. This is used mainly just during installation, after which we
    # rely on the version running on the first master. Works best for containerized installs where we can usually
    # use this to lookup the latest exact version of the container images, which is the tag actually used to configure
    # the cluster. For RPM installations we just verify the version detected in your configured repos matches this
    # release.
    openshift_release=v3.7.1
    
    # set exact RPM version (include - prefix)
    #openshift_pkg_version=-3.6.0
    # you may also specify version and release, ie:
    #openshift_pkg_version=-3.7.0-0.126.0.git.0.9351aae.el7
    openshift_pkg_version=-3.7.1
    
    # Specify an exact container image tag to install or configure.
    # WARNING: This value will be used for all hosts in containerized environments, even those that have another version installed.
    # This could potentially trigger an upgrade and downtime, so be careful with modifying this value after the cluster is set up.
    openshift_image_tag=v3.7.1
    
    
    # Force a specific prefix (IE: registry) to use when pulling the service catalog image
    # NOTE: The registry all the way up to the start of the image name must be provided. Two examples
    # below are provided.
    openshift_service_catalog_image_prefix=docker.io/openshift/origin-
    #openshift_service_catalog_image_prefix=registry.access.redhat.com/openshift3/ose-
    # Force a specific image version to use when pulling the service catalog image
    openshift_service_catalog_image_version=v3.7.1
    
    template_service_broker_image_version=v3.7.1
    template_service_broker_selector={"region":"infra"}
    
    osm_use_cockpit=true
    # OpenShift Registry Console Options
    # Override the console image prefix:
    # origin default is "cockpit/", enterprise default is "openshift3/"
    openshift_cockpit_deployer_prefix=docker.io/cockpit/
    # origin default is "kubernetes", enterprise default is "registry-console"
    #openshift_cockpit_deployer_basename=my-console
    # Override image version, defaults to latest for origin, vX.Y product version for enterprise
    #openshift_cockpit_deployer_version=1.4.1
    
    
    
    #specify where the console should be deployed
    openshift_web_console_nodeselector={'region':'infra'}
    
    
    # uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
    openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
    
    # subdomain wildcard 
    openshift_master_default_subdomain=cloudapps.lab.example.com
    
    openshift_disable_check=memory_availability,disk_availability,package_version
    
    # host group for masters
    [masters]
    master.lab.example.com openshift_ip=172.25.250.10
    
    # host group for etcd
    [etcd]
    master.lab.example.com openshift_ip=172.25.250.10
    
    # host group for nodes, includes region info
    [nodes]
    master.lab.example.com openshift_ip=172.25.250.10
    node1.lab.example.com openshift_node_labels="{'region': 'infra', 'zone': 'east', 'type': 'router'}" openshift_ip=172.25.250.11
    node2.lab.example.com openshift_node_labels="{'region': 'infra', 'zone': 'west'}" openshift_ip=172.25.250.12

**Comment by michaelcourcy** [comment]
I  finally found the reason in comparing the deployment config of docker-registry and registry console 

    [root@workstation ~]# oc get dc docker-registry -o yaml | grep imagePullPolicy
            imagePullPolicy: IfNotPresent
    [root@workstation ~]# oc get dc registry-console -o yaml | grep imagePullPolicy
            imagePullPolicy: Always

In the registry-console template there's no imagePullPolicy defined then this [rules apply](https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/builds_and_image_streams.html#image-pull-policy) thus the default policy was Always because the tag was latest.

**Comment by eslowney** [comment]
As this is the only post in the internet with my exact same problem, can someone spell out the solution for me?  I don't know how to change the imagepullpolicy, or where it is located.  Can this be done on an existing install and re-deployed, and if so, how?  Or do I have to run the uninstall playbook, set up the registries, and somehow edit the file that this setting is contained in, and then re-install?

**Comment by michaelcourcy** [comment]
Don't put latest but a defined version.

**Comment by andridar** [comment]
can you explain about "Don't put latest but a defined version"

**Comment by andridar** [comment]
> can you explain about "Don't put latest but a defined version"

@michaelcourcy

**Comment by andridar** [comment]
> can you explain about "Don't put latest but a defined version"

@michaelcourcy
