### ISSUE TITLE
Hosted registry certificate invalid alternative names

### ISSUE THREAD

**Issue by PiotrKlimczak** [openshift/openshift-ansible#8209]
#### Description

After Openshift 3.9 upgrade we are getting issues with pushing images to docker registry.
We are getting:
Error response from daemon: Get https://docker-registry-default.apps.X/v2/: x509: certificate is valid for docker-registry-default.router.default.svc.cluster.local, docker-registry.default.svc, docker-registry.default.svc.cluster.local, 172.30.166.101, not docker-registry-default.apps.X

As per code analysis this is because mistake in "playbooks/openshift-hosted/private/redeploy-registry-certificates.yml" file, which uses "openshift.master.default_subdomain" instead of "openshift_master_default_subdomain" and as such picking default subdomain: router.default.svc.cluster.local instead of one configured in inventory file.

##### Version

```
ansible 2.5.0
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce
1. Login to OCP
2. Push image to docker registry- docker push...

##### Expected Results
Successful push

##### Observed Results

```
Error response from daemon: Get https://docker-registry-default.apps.X/v2/: x509: certificate is valid for docker-registry-default.router.default.svc.cluster.local, docker-registry.default.svc, docker-registry.default.svc.cluster.local, 172.30.166.101, not docker-registry-default.apps.X
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

As per code analysis this is because mistake in "playbooks/openshift-hosted/private/redeploy-registry-certificates.yml" file, which uses "openshift.master.default_subdomain" instead of "openshift_master_default_subdomain" and as such picking default subdomain: router.default.svc.cluster.local instead of one configured in inventory file.

Once fixed, regenerating registry certificate with 
```
ansible-playbook -i YOUR_INVENTORY_FILE playbooks/openshift-hosted/redeploy-registry-certificates.yml
```
All works.

**Comment by michaelgugino** [comment]
@PiotrKlimczak Thank you for filing this issue.  I will take a look and get a patch out later today.
