### ISSUE TITLE
roles/openshift_hosted/README.md is inaccurate

### ISSUE THREAD

**Issue by maxamillion** [openshift/openshift-ansible#8218]
#### Description

Currently the `roles/openshift_hosted/README.md` file mentions that you can call upon the role directly in a playbook, however that has no effect because it's `main.yml` is empty and instead contains the following comments with no explanation as to what vars need to be defined at the time these tasks are imported.
```
# This role is intended to be used with import_role.
# import_role:
#   name:  openshift_hosted
#   tasks_from: "{{ item }}"
# with_items:
#   - create_projects.yml
#   - router.yml
#   - registry.yml
```

##### Version

master branch at commit 932eaac699bf8bf248e6322b926d0c06f67f46d9

**Comment by hendrikhalkow** [comment]
Even worse, the documentation https://docs.openshift.org/latest/install_config/install/advanced_install.html#running-the-advanced-installation-individual-components makes you think that you can do it, which I just tried. The playbook fails when it tries to discover the GlusterFS IP addresses.
