### ISSUE TITLE
Unable to install containerized Openshift using master branch - Openshift 3.10

### ISSUE THREAD

**Issue by geoand** [openshift/openshift-ansible#8223]
#### Description

Using the same inventory file (except for changing Openshift versions) we are using to successfully install Openshift 3.9 from the `release-3.9` branch, I tried to install Openshift 3.10 from the master `branch`.
The process failed for 3.10

##### Version

Please put the following version information in the code block
indicated below.

* Ansible version: ansible 2.4.3.0

* Git Describe: openshift-ansible-3.10.0-0.32.0-8-gb4be7cd

##### Steps To Reproduce
1. Use the following inventory:

https://gist.github.com/geoand/315b069d5ac60239ad67bdc0a087df9d

2. Execute: `ansible-playbook -i inventory openshift-ansible/playbooks/prerequisites.yml`

3. Execute: `ansible-playbook -i inventory openshift-ansible/playbooks/deploy_cluster.yml`

##### Expected Results
I expected an Openshift 3.10 cluster to be installed (just like was working for `3.9` from the `release-3.9` branch)

##### Observed Results
The `deploy_cluster.yml` playbooks files with the following output:

https://gist.github.com/geoand/905d3abf54a125b0dfacbe2ebfb91954

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Target VM OS: CentOS Linux release 7.4.1708 (Core)
* Inventory: 

```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_user=root

public_ip_address=192.168.99.50
host_key_checking=false

containerized=true
openshift_enable_excluders=false
openshift_release=v3.10

openshift_deployment_type=origin

openshift_hostname=192.168.99.50
openshift_master_cluster_public_hostname=192.168.99.50
openshift_master_default_subdomain=192.168.99.50.nip.io
openshift_master_unsupported_embedded_etcd=true

openshift_disable_check = docker_storage,memory_availability,disk_availability,docker_image_availability,package_version

# Python Interpreter
ansible_python_interpreter=/usr/bin/python

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
openshift_master_htpasswd_users={'admin': '$apr1$DloeoaY3$nqbN9fQBkyXgbj58buqEM.'}

[masters]
192.168.99.50 openshift_public_hostname=192.168.99.50 openshift_hostname=192.168.99.50

[etcd]
192.168.99.50 openshift_ip=192.168.99.50

[nodes]
192.168.99.50 openshift_node_labels="{'region':'infra','zone':'default', 'node-role.kubernetes.io/compute': 'true'}" openshift_public_hostname=192.168.99.50 openshift_hostname=192.168.99.50
```

**Comment by geoand** [comment]
cc @cmoulliard

**Comment by cmoulliard** [comment]
we can avoid the error reported 

```
TASK [openshift_node : Pre-pull node system container image] *********************************************************************************************************************************************************************
fatal: [192.168.99.50]: FAILED! => {"msg": "The conditional check ''Pulling layer' in pull_result.stdout' failed. The error was: error while evaluating conditional ('Pulling layer' in pull_result.stdout): Unable to look up a name or access an attribute in template string ({% if 'Pulling layer' in pull_result.stdout %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable"}
```

if we install within the VM (CentOS7), the atomic package

```
yum install -y atomic
```

**Comment by geoand** [comment]
Is it a bug that we need to install the package manually?

**Comment by vrutkovs** [comment]
Sounds like a bug to me, if that's the only thing which fails with this configuration.

**Comment by geoand** [comment]
Installing the package manually allowed me to complete the installation according to the description of the issue
