### ISSUE TITLE
Crashlooping Openshift-ansible installation

### ISSUE THREAD

**Issue by megastallman** [openshift/openshift-ansible#8229]
#### Description
I'm trying to create a 3-master + 1 node Openshift Origin deployment with ansible playbooks. We use an external Haproxy-based load balancer. When trying to get the console, I see the white page after accepting the certificate. Nothing else works. 

##### Version
Ansible installer container version: docker.io/openshift/origin-ansible:v3.9

My inventory looks like this:
```
[masters]
k8-101.ololo.com
k8-102.ololo.com                                                                                 
k8-103.ololo.com

[nodes]
k8-101.ololo.com
k8-102.ololo.com
k8-103.ololo.com
k8-104.ololo.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

[etcd]
k8-101.ololo.com
k8-102.ololo.com
k8-103.ololo.com

# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]

ansible_user=root
openshift_clock_enabled=true
openshift_deployment_type=origin
openshift_master_cluster_method=native
openshift_master_cluster_hostname=matchbox.ololo.com
openshift_master_cluster_public_hostname=matchbox.ololo.com
```
My haproxy config looks like this:
```
$ cat /etc/haproxy/haproxy.cfg 
# Global settings
#---------------------------------------------------------------------
global
    maxconn     20000
    log         /dev/log local0 info
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
#    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          300s
    timeout server          300s
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 20000

listen stats
    bind :9000
    mode http
    stats enable
    stats uri /

frontend  atomic-openshift-api
    bind *:8443
    default_backend atomic-openshift-api
    mode tcp
    option tcplog

backend atomic-openshift-api
    balance source
    mode tcp
    server      master0 10.10.9.95:8443 check
    server      master1 10.10.9.96:8443 check
    server      master2 10.10.9.97:8443 check
```

##### Steps To Reproduce
docker run -t -u `id -u` -v $PWD/key:/opt/app-root/src/.ssh/id_rsa:Z -v $PWD/4-node.inventory:/tmp/inventory:Z -e INVENTORY_FILE=/tmp/inventory  -e PLAYBOOK_FILE=playbooks/prerequisites.yml -e OPTS="-v" docker.io/openshift/origin-ansible:v3.9
docker run -t -u `id -u` -v $PWD/key:/opt/app-root/src/.ssh/id_rsa:Z -v $PWD/4-node.inventory:/tmp/inventory:Z -e INVENTORY_FILE=/tmp/inventory  -e PLAYBOOK_FILE=playbooks/deploy_cluster.yml -e OPTS="-v" docker.io/openshift/origin-ansible:v3.9

##### Expected Results
I've expected Openshift to get deployed.

##### Observed Results
Describe what is actually happening.

```
[root@k8-101 ~]# oc --config /etc/origin/master/admin.kubeconfig get pods --all-namespaces
NAMESPACE               NAME                          READY     STATUS             RESTARTS   AGE
default                 docker-registry-1-deploy      0/1       Error              0          5d
default                 registry-console-1-deploy     0/1       Error              0          5d
default                 router-10-deploy              0/1       Error              0          1h
default                 router-11-deploy              0/1       Error              0          24m
default                 router-3-deploy               0/1       Error              0          5d
default                 router-4-deploy               0/1       Error              0          4d
default                 router-5-deploy               0/1       Error              0          4d
default                 router-6-deploy               0/1       Error              0          4d
default                 router-7-deploy               0/1       Error              0          4d
default                 router-8-deploy               0/1       Error              0          4d
default                 router-9-deploy               0/1       Error              0          1h
logging                 logging-curator-1-deploy      0/1       Error              0          5d
logging                 logging-fluentd-9nd96         0/1       CrashLoopBackOff   9          5d
logging                 logging-fluentd-b7sgq         0/1       CrashLoopBackOff   9          5d
logging                 logging-fluentd-c9wfh         0/1       CrashLoopBackOff   9          5d
logging                 logging-fluentd-jlmh4         0/1       CrashLoopBackOff   9          5d
logging                 logging-kibana-1-deploy       0/1       Error              0          5d
openshift-web-console   webconsole-84466b9d97-4z764   1/1       Running            0          5d
openshift-web-console   webconsole-84466b9d97-gh9wv   1/1       Running            0          5d
openshift-web-console   webconsole-84466b9d97-rzn5d   1/1       Running            0          5d
```

**Comment by megastallman** [comment]
It breaks after:
```
TASK [openshift_hosted : Poll for OpenShift pod deployment success] *****************************
Wednesday 02 May 2018  14:49:38 +0000 (0:00:00.738)       0:14:33.465 *********
FAILED - RETRYING: Poll for OpenShift pod deployment success (60 retries left).
FAILED - RETRYING: Poll for OpenShift pod deployment success (59 retries left).
```
Unsuccessful retries.

**Comment by vrutkovs** [comment]
Right, router (and other components) were not deployed.

Can you reach the API? 

I'm guessing external LB would require at least `openshift_master_cluster_public_hostname` and `openshift_master_cluster_hostname` set. See config in https://github.com/redhat-cop/openshift-playbooks/blob/master/playbooks/installation/load_balancing.adoc

**Comment by megastallman** [comment]
I've got them set up as:
```
openshift_master_cluster_hostname=matchbox.ololo.com
openshift_master_cluster_public_hostname=matchbox.ololo.com
```

**Comment by vrutkovs** [comment]
Sorry, missed that part.

What's in `oc --config /etc/origin/master/admin.kubeconfig describe router-3-deploy -n default` and `oc --config /etc/origin/master/admin.kubeconfig logs router-3-deploy`?

**Comment by megastallman** [comment]
[root@k8-101 ~]# cat 1
Name:         router-3-deploy
Namespace:    default
Node:         k8-102.ololo.com/10.10.9.96
Start Time:   Fri, 27 Apr 2018 08:35:51 -0700
Labels:       openshift.io/deployer-pod-for.name=router-3
Annotations:  openshift.io/deployment-config.name=router
              openshift.io/deployment.name=router-3
              openshift.io/scc=restricted
Status:       Failed
IP:           10.129.0.6
Containers:
  deployment:
    Container ID:   docker://ba11db3e9bc33073a0023dec5813eb387cabe9b039a25903346d76652b2df909
    Image:          openshift/origin-deployer:v3.9.0
    Image ID:       docker-pullable://docker.io/openshift/origin-deployer@sha256:dd2163374d119a4f5fe3a7f5516b68d9a14712d2074af30f35ad78ab222431ea
    Port:           <none>
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 27 Apr 2018 08:36:09 -0700
      Finished:     Fri, 27 Apr 2018 08:36:10 -0700
    Ready:          False
    Restart Count:  0
    Environment:
      KUBERNETES_MASTER:  https://k8-101.ololo.com:8443
      OPENSHIFT_MASTER:   https://k8-101.ololo.com:8443
      BEARER_TOKEN_FILE:  /var/run/secrets/kubernetes.io/serviceaccount/token
      OPENSHIFT_CA_DATA:  -----BEGIN CERTIFICATE-----
...........................................................
-----END CERTIFICATE-----

      OPENSHIFT_DEPLOYMENT_NAME:       router-3
      OPENSHIFT_DEPLOYMENT_NAMESPACE:  default
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from deployer-token-nq9pf (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  deployer-token-nq9pf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  deployer-token-nq9pf
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  region=infra
Tolerations:     <none>
Events:          <none>

[root@k8-101 ~]# oc --config /etc/origin/master/admin.kubeconfig logs router-3-deploy -n default
Unable to retrieve container logs for docker://ba11db3e9bc33073a0023dec5813eb387cabe9b039a25903346d76652b2df909

**Comment by vrutkovs** [comment]
The pod looks correct.

Not much we can do here without the logs from the container :( 

Anything related to router in `docker` and `origin-node` logs from the infra node?

**Comment by megastallman** [comment]
[root@k8-101 ~]# oc --config /etc/origin/master/admin.kubeconfig -n openshift-web-console logs webconsole-84466b9d97-gh9wv
W0502 14:47:59.635342       1 start.go:93] Warning: config.clusterInfo.metricsPublicURL: Invalid value: "": required to view cluster metrics in the console, web console start will continue.
I0502 14:47:59.958122       1 start.go:201] OpenShift Web Console Version: v3.9.0+b600d46-dirty
I0502 14:47:59.958311       1 serve.go:89] Serving securely on 0.0.0.0:8443
I0502 15:00:22.680337       1 logs.go:41] http: TLS handshake error from 10.128.0.1:59524: remote error: tls: bad certificate

And here: https://hastebin.com/icuxamidin.lua is the k8-104's docker log.

**Comment by megastallman** [comment]
That's how all my resources look like: https://hastebin.com/emogovulay.go

**Comment by megastallman** [comment]
It is an RPM-based installation. Maybe I can also try containerized, if it supports multimaster configurations, of course.

**Comment by megastallman** [comment]
Thanks! @vrutkovs 
The problem is the postinstall playbook breakage. It doesn't finish. So, I'm issuing something like:
```
yum -y erase etcd
rm -rf /etc/etcd
rm -rf /var/lib/etcd
rm -rf /var/lib/cni
rm -rf /etc/cni
```
on all my hosts. So we need to fix the playbook.

**Comment by vrutkovs** [comment]
>It is an RPM-based installation. Maybe I can also try containerized, if it supports multimaster configurations, of course?

I don't think there is any difference. This issue is that an incorrect certs are being issued.

Has there been any luck with getting more details, like inspecting a cert or router container logs?

>At the moment I'm working it around, but I think this ticket could be moved to a feature request, because it is common enough to keep /var/lib/docker separately. What do you think?

This should at least be a separate issue, although I'm not following which option is causing this uninstall playbook to fail

**Comment by megastallman** [comment]
Yes. Looks like it should be a separate issue about external /var/lib/docker. Should I create one? At the moment I'm using some pre-uninstall and post-uninstall playbooks to unmount and clean /var/lib/docker.
