### ISSUE TITLE
ansible playbook modified my /etc/sysconfig/docker file

### ISSUE THREAD

**Issue by Kisen-Chin** [openshift/openshift-ansible#8247]
#### Description

OK. When I install openshift 3.9.0 using openshift-ansible-openshift-ansible-3.9.27-1 
I got error like this:
RUNNING HANDLER [container_runtime : restart container runtime] *************************************************************************************************************
changed: [master2.example.com]
FAILED - RETRYING: restart container runtime (3 retries left).
FAILED - RETRYING: restart container runtime (2 retries left).
FAILED - RETRYING: restart container runtime (1 retries left).
fatal: [master1.example.com]: FAILED! => {"attempts": 3, "changed": false, "msg": "Unable to start service docker: Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"}

I searched on web site and find that I need to edit /etc/sysconfig/docker file to delete "--selinux-enabled " this option. 
After I delete this option and run systemctl start docker, the docker could start successfully.

Then I start to run ansible-playbook to install cluster again. But the installation failed again. 
The error is same as above. 
When I check /etc/sysconfig/docker file, I found that "--selinux-enabled " was added again by the ansible-playbook. 

Does anyone know how to solve this ?

By the way, where should I tell ansible to install the correct version of openshift?
Is it in /etc/ansible/hosts  and these two values?
openshift_deployment_type=origin
openshift_release=3.9.0 

##### Version

[root@master1 ~]# ansible --version

```
[root@master1 ~]# ansible --version
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]



openshift-ansible-openshift-ansible-3.9.27-1 
```

##### Steps To Reproduce
1. ansible-playbook openshift-ansible-openshift-ansible-3.9.27-1/playbooks/prerequisites.yml 

##### Expected Results

```
successfully
```

##### Observed Results

```
RUNNING HANDLER [container_runtime : restart container runtime] *************************************************************************************************************
changed: [master2.example.com]
FAILED - RETRYING: restart container runtime (3 retries left).
FAILED - RETRYING: restart container runtime (2 retries left).
FAILED - RETRYING: restart container runtime (1 retries left).
fatal: [master1.example.com]: FAILED! => {"attempts": 3, "changed": false, "msg": "Unable to start service docker: Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"}


Or the script should not modify my /etc/sysconfig/docker file
```

**Comment by vrutkovs** [comment]
See hosts.example, `openshift_docker_selinux_enabled=False` in the inventory would unset it
