### ISSUE TITLE
remove v1beta3, enable extensions/v1beta1

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#825]
the current template sets this:
```
apiLevels:
{% if openshift.common.deployment_type == "enterprise" %}
- v1beta3
{% endif %}
- v1
...
{% if openshift.master.embedded_kube | bool %}
kubernetesMasterConfig:
  apiLevels:
{% if openshift.common.deployment_type == "enterprise" %}
  - v1beta3
{% endif %}
  - v1
```

in 3.1, v1beta3 needs to be removed from the top-level apiLevels list, and kubernetesMasterConfig.apiLevels should probably be removed completely
```
apiLevels:
{% if openshift.common.deployment_type == "enterprise" %}
- v1beta3
{% endif %}
- v1
...
{% if openshift.master.embedded_kube | bool %}
kubernetesMasterConfig:
{% if openshift.common.deployment_type == "enterprise" %}
  apiLevels:
  - v1beta3
  - v1
{% endif %}
{% if openshift.common.deployment_type == "openshift-enterprise/atomic-enterprise" %}
  disabledAPIGroupVersions: {}
{% endif %}
```

**Comment by liggitt** [comment]
I don't know how to conditionalize the template on API version, and wasn't sure how the default template content interacts with deltas made in `upgrade_master_3_0_to_3_1`

**Comment by liggitt** [comment]
also, I saw these while searching for v1beta3:
```
- name: export physical volumes
  uri: url={{ kubernetes_url }}/api/v1beta3/persistentvolumes
```

nfs.json.j2:
```
{
  "kind": "PersistentVolume",
  "apiVersion": "v1beta3",
...
```

not sure if those are just vestigial, but they won't work on 3.1

**Comment by detiber** [comment]
@liggitt deployment_type == 'enterprise' is only for 3.0, the deployment_type for 3.1 is openshift-enterprise/atomic-enterprise

I'll submit a PR for changing the apiVersion for the nfs role, I don't think anyone is actually using it though as Ops has moved to EBS volumes.

**Comment by liggitt** [comment]
For the extensions/v1beta1 thing, the approach in https://github.com/openshift/openshift-ansible/issues/725 would probably be better

**Comment by detiber** [comment]
https://github.com/openshift/openshift-ansible/pull/829 submitted to remove v1beta3 from the kube_nfs_volumes role

**Comment by detiber** [comment]
@liggitt @deads let me see if I understand this 100%.

For the top level apiLevels, we need to still explicitly whitelist the correct api versions, since disabledAPIGroupVersions isn't available at the top level yet. However, for kubernetesMasterConfig we can omit apiLevels.

And we would have conditional for < 3.1 to keep the config as it was previously.

**Comment by liggitt** [comment]
> For the top level apiLevels, we need to still explicitly whitelist the correct api versions

Correct:
* Prior to 3.1: "v1","v1beta3"
* 3.1: "v1" only

> for kubernetesMasterConfig we can omit apiLevels

Correct. If you feel like giving the user a param to populate `kubernetes.disabledAPIGroupVersions`, you can, but that's up to you. The only real use for that in 3.1 would be to disable the new extensions APIs for HPA and Job

> and we would have conditional for < 3.1 to keep the config as it was previously

Correct.

**Comment by detiber** [comment]
Submitted https://github.com/openshift/openshift-ansible/pull/830 for the previously discussed apiLevels changes.

Will use https://github.com/openshift/openshift-ansible/issues/725 for tracking the addition of disabledAPIGroupVersions at a later time, since it isn't a blocker for 3.1

**Comment by detiber** [comment]
@brenton this issue can now be closed since https://github.com/openshift/openshift-ansible/pull/830 was merged.
