### ISSUE TITLE
[3.10] flake: SDN won't come up on masters

### ISSUE THREAD

**Issue by vrutkovs** [openshift/openshift-ansible#8264]
Tests on Fedora Atomic frequently flake - SDN fails to start up on master

See logs at https://s3.amazonaws.com/aos-ci/ghprb/openshift/openshift-ansible/9a893cfafe6f5403f874cd8cb584a52ab87067d5.0.1525429564778020246/artifacts/index.html

[Master logs](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650):

* [API server is up](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650#file-fah_log-txt-L1)
* [Web Console template is processed](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650#file-fah_log-txt-L86)
* [Waiting for web console to come up](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650#file-fah_log-txt-L114)
* [Something kills API](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650#file-fah_log-txt-L274) - what's causing it?
* [SDN container is declared dead](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650#file-fah_log-txt-L381)
* [SDN container starts again](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650#file-fah_log-txt-L446)

After that the timeout for web console to be up hits.

Any ideas what's going on here? /cc @smarterclayton @openshift/networking 

Log with debug_level=4 - https://gist.github.com/vrutkovs/d9128bdccbf3e48cb9b2a675684775b6

The only suspicious thing I see is:
```
May 04 15:29:09 ocp-master docker-containerd-current[802]: time="2018-05-04T15:29:09.041571714Z" level=error msg="containerd: deleting container" error="exit status 1: \"container a199c08d3a9d2b3938f19915a9b7f228a682c92154b0ceae8c14bfae48ec448a does not exist\\none or more of the container deletions failed\\n\""
```
Could it be docker failing to restart SDN container?

**Comment by smarterclayton** [comment]
SDN is crashlooping.  Check the SDN logs in the json file directory for docker.

**Comment by vrutkovs** [comment]
I think I sorted it out, this only happens on a single master, which is also a node. When SDN is setting up iptables rules, the node is being setup - and it restarts docker. In the end SDN reports it has done it job, but the node is not Ready.

https://github.com/openshift/openshift-ansible/pull/8265/commits/b61d0e7d0f6b90184cc73d7da1c633a8c91e7e93 should fix it

**Comment by vrutkovs** [comment]
SDN failures still occur
```
2018/05/09 10:38:59 socat[10408] E connect(5, AF=1 "/var/run/openshift-sdn/cni-server.sock", 40): No such file or directory
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
warning: Cannot find existing node-config.yaml, waiting 15s ...
```

**Comment by vrutkovs** [comment]
Since sync pod is the first one to pull node image it may take a long time to pull it. So SDN would be crashlooping before sync pod is started. If it didn't start before web console startup comes the installation would fail

https://github.com/openshift/openshift-ansible/pull/8172 should fix that
