### ISSUE TITLE
openshift_examples | Import RHEL streams Fails with Unknown Host Error

### ISSUE THREAD

**Issue by eighilaza** [openshift/openshift-ansible#827]
Hello, 
Im' trying to install openshift entreprise on rhel7 but the installation is failing at:
```
failed: [10.35.60.164] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-rhel7.json"], "delta": "0:00:00.563515", "end": "2015-11-06 04:00:11.671137", "failed": true, "failed_when_result": true, "rc": 1, "start": "2015-11-06 04:00:11.107622", "stdout_lines": [], "warnings": []}
stderr: Unable to connect to the server: Unknown Host
Unable to connect to the server: Unknown Host
Unable to connect to the server: Unknown Host
Unable to connect to the server: Unknown Host
Unable to connect to the server: Unknown Host
Unable to connect to the server: Unknown Host
Unable to connect to the server: Unknown Host
Unable to connect to the server: Unknown Host
Unable to connect to the server: Unknown Host

FATAL: all hosts have already failed -- aborting
```
Although, on the master I am able to resolve the host registry.access.redhat.com that is in /usr/share/openshift/examples/image-streams/image-streams-rhel7.json
Any idea what might be going wrong here please?

**Comment by abutcher** [comment]
This looks like a problem with the client communicating with the master. This command is being ran from the first configured master. Take a look at `/root/.kube/config` and ensure you can communicate with configured server host.

**Comment by eighilaza** [comment]
@abutcher thanks for your reply. Indeed there was an issue in the /root/.kube/config file. The hostname of the master was something like PRIVATE_IP.xip.io and the master could not resolve that hostname for some reason. Anyway I changed that to the actual hostname and it fixed the problem.
I think the error message a bit misleading, as I thought it could not resolve registry.access.redhat.com
