### ISSUE TITLE
OpenShift fails to provision using AWS flow

### ISSUE THREAD

**Issue by oatmealraisin** [openshift/openshift-ansible#8292]
# AWS Playbooks fail to set up working cluster

__Description__

Coming from no AWS infrastructure to the full 8 node cluster provided by the
`playbooks/aws/` flow, there are a series of errors that prevent the cluster
from functioning.

__Versions__

```
# ansible --version
ansible 2.5.2
  config file = /home/ubuntu/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

```
# git describe
openshift-ansible-3.9.27-1-41-ga5c91e7
```

__Steps to Reproduce__

Create an SSH key to use w/ AWS, get a pair of AWS IAM API keys, and insert them as env variables as per [this](https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/README.md) set of instructions.

Using [this](https://gist.github.com/98ef6745555cc26f656239b7a92b0766) inventory file and [this](https://gist.github.com/cd7de525b44481bb544290f73e82f467) provisioning vars file, run [this](https://gist.github.com/86377eb1ec8a180ff286f53908301c76) script.

__Expected Results__

A working cluster with all options implemented

__Actual Results__

It seems like there are only 3 nodes in the cluster, but 8 EC2 instances
running. Three are masters, three are compute nodes, three are infrastructure
nodes. There is no registry, router, monitoring, web console, etc.

```
# oc get nodes
NAME                            STATUS    ROLES     AGE       VERSION
ip-172-31-48-45.ec2.internal    Ready     master    3d        v1.9.1+a0ce1bc657
ip-172-31-54-145.ec2.internal   Ready     master    3d        v1.9.1+a0ce1bc657
ip-172-31-58-20.ec2.internal    Ready     master    3d        v1.9.1+a0ce1bc657
```

The output of `oc get csr` gives a very strange number of objects:

```
# oc get csr
NAME                                                   AGE       REQUESTOR CONDITION
node-csr-5jLbjSl3ZOYmgPdjYG09HHJGlzdTKUSg3xZk-KUqkUM   3d system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
node-csr-ETmtdk1wphiHS_zr1SfZrh9GRnK5kLYZu71Nm_vnmzo   3d system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
node-csr-QDTk7uC_5ugFvPBHt3J-EE0SlPTpMa22EyztMrfJco4   3d system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
node-csr-lu_eFPB_cL-kFymjBdRpd2JsKIf87i42WW_NgqlRfTo   3d system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
node-csr-ulTjYy8DjeGImttyZmoVhH4jVUjKLb0zG6AivoqUF6s   3d system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
```

Upon trying to create a registry, there are no nodes that are available (even
though they say they are).

```
# oc adm registry
--> Creating registry registry ...
  serviceaccount "registry" created
  clusterrolebinding "registry-registry-role" created
  deploymentconfig "docker-registry" created
  service "docker-registry" created
--> Success
# oc get po -w
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-deploy   0/1       Pending   0          24s
# oc describe po/docker-registry-1-deploy
Name:         docker-registry-1-deploy
Namespace:    default
Node:         <none>
Labels:       openshift.io/deployer-pod-for.name=docker-registry-1
Annotations:  openshift.io/deployment-config.name=docker-registry
              openshift.io/deployment.name=docker-registry-1
				  openshift.io/scc=restricted

Status:       Pending
IP:
Containers:
  deployment:
      Image:  openshift/origin-deployer:v3.9.0
		Port:   <none>
		Environment:
			KUBERNETES_MASTER:  https://ip-172-31-48-45.ec2.internal
			OPENSHIFT_MASTER: https://ip-172-31-48-45.ec2.internal
			BEARER_TOKEN_FILE: /var/run/secrets/kubernetes.io/serviceaccount/token
			OPENSHIFT_CA_DATA:  -----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----

		OPENSHIFT_DEPLOYMENT_NAME:       docker-registry-1
		OPENSHIFT_DEPLOYMENT_NAMESPACE:  default
	Mounts:
		/var/run/secrets/kubernetes.io/serviceaccount from deployer-token-v22v9 (ro)
Conditions:
	Type           Status
	PodScheduled   False
Volumes:
	deployer-token-v22v9:
		Type:        Secret (a volume populated by a Secret)
		SecretName:  deployer-token-v22v9
		Optional:    false
QoS Class:       BestEffort
Node-Selectors: node-role.kubernetes.io/compute=true
Tolerations:     <none>
Events:
Type     Reason            Age 	From               Message
----     ------            ----  ----               -------
Warning  FailedScheduling  11s   (x7 over 42s)      default-scheduler  0/3 nodes are available: 3 MatchNodeSelector.

# oc describe rc/docker-registry-1
Name:         docker-registry-1
Namespace:    default
Selector:
deployment=docker-registry-1,deploymentconfig=docker-registry,docker-registry=default
Labels:       docker-registry=default
              openshift.io/deployment-config.name=docker-registry
Annotations:   kubectl.kubernetes.io/desired-replicas=1
               openshift.io/deployer-pod.created-at=2018-05-07 20:56:29 +0000 UTC
					openshift.io/deployer-pod.name=docker-registry-1-deploy
					openshift.io/deployment-config.latest-version=1
					openshift.io/deployment-config.name=docker-registry
					openshift.io/deployment.phase=Pending
					openshift.io/deployment.replicas=0
					openshift.io/deployment.status-reason=config change
Replicas:     0 current / 0 desired
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
...
```

Component statuses:

```
# oc get cs
NAME                 STATUS      MESSAGE ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: getsockopt: connection refused
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: getsockopt: connection refused
etcd-2               Healthy     {"health": "true"}
etcd-0               Healthy     {"health": "true"}
etcd-1               Healthy     {"health": "true"}
```

The logs of each playbooks can be found below

1. [uninstall.yml](https://gist.github.com/0e3933b85c3e008d76526f93e1189bcb)
1. [prerequisites.yml](https://gist.github.com/450790d15e32a9e24146495d98338e88)
1. [build_ami.yml](https://gist.github.com/68c6e918a0df737c7e1f2ba20b3e406c)
1. [provision.yml](https://gist.github.com/b1184995de46e9e43c37012c8e4863b4)
1. [install.yml](https://gist.github.com/927e81085928d9f6272b09461e6f4dd9)
1. [provision_nodes.yml](https://gist.github.com/fffd09b8d41e7ac5add2c36237d4c8fb)
1. [accept.yml](https://gist.github.com/d25c29030d0ddb291ba0df11427fcf4e)

Additionally, here are the logs if you use `provision_install.yml` instead of
the last four playbooks.

* [provision_install.yml](https://gist.github.com/67d9ed9aa380262f70b6d1f52324cef3)

Please note that everything is scrubbed of private information. Let me know if I need to provide any more information!

**Comment by vrutkovs** [comment]
Your inventory has no nodes, tagged with `region=infra`

Add `openshift_node_labels="{'region': 'infra'}"` to the nodes you'd like to dedicate to infra components

**Comment by oatmealraisin** [comment]
@vrutkovs From the `playbooks/aws/README.md`:

>  Step 4
>
> Now it is time to install Openshift using the openshift-ansible installer. This can be achieved by running the following playbook:
>
> `$ ansible-playbook -i inventory.yml install.yml -e @provisioning_vars.yml`
> 
> This playbook accomplishes the following:
>
> 1. Builds a dynamic inventory file by querying AWS.
> 1. Runs the deploy_cluster.yml

Since the directions start from no nodes running, there is no way to label any instance with any labels, unless I'm supposed to add them in between steps. According the directions, the inventory is built dynamically by querying AWS
