### ISSUE TITLE
openshift_examples_modify_imagestreams has no effect on origin install

### ISSUE THREAD

**Issue by michaelcourcy** [openshift/openshift-ansible#8315]
#### Description

Provide a brief description of your issue here. For example:

openshift_examples_modify_imagestreams has no effect on origin install.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version` : 2.5.2

If you're operating from a **git clone**: 

* The output of `git describe` : openshift-ansible-3.9.27-1-43-g81cd65e

##### Steps To Reproduce
1. Set openshift_examples_modify_imagestreams=true in inventory files 
2. Set oreg_url=workstation.lab.example.com/openshift/origin-${component}:${version}
3. launch the install : ansible-playbook -i $ANSIBLE_DIR/inventory $ANSIBLE_DIR/openshift-ansible/playbooks/deploy_cluster.yml

##### Expected Results
All the imageStream in the openshift project should have DockerImage pointing to workstation.lab.example.com 

##### Observed Results
Describe what is actually happening.

Image are still pointing to docker.io : 

```
 oc get is ruby  -o yaml |grep "kind: DockerImage" -A 1

      kind: DockerImage
      name: docker.io/openshift/ruby-20-centos7:latest
--
      kind: DockerImage
      name: docker.io/centos/ruby-22-centos7:latest
--
      kind: DockerImage
      name: docker.io/centos/ruby-23-centos7:latest
--
      kind: DockerImage
      name: docker.io/centos/ruby-24-centos7:latest
```

##### Additional Information

in openshift-ansible/roles/openshift_examples/tasks/main.yml line 52 I can see that we only try to change registry.access.redhat.com but nothing for docker.io which probably explain the situation.

```
- name: Modify registry paths if registry_url is not registry.access.redhat.com
  shell: >
    find {{ examples_base }} -type f | xargs -n 1 sed -i 's|registry.access.redhat.com|{{ registry_host | quote }}|g'
  when: registry_host != '' and openshift_examples_modify_imagestreams | default(False) | bool
```

Is it on purpose ? Do you think 

```
- name: Modify registry paths if registry_url is not registry.access.redhat.com
  shell: >
    find {{ examples_base }} -type f | xargs -n 1 sed -i 's/(registry\.access\.redhat\.com|docker\.io)/{{ registry_host | quote }}/g'
  when: registry_host != '' and openshift_examples_modify_imagestreams | default(False) | bool
```
would do the jobs ?

**Comment by FrederikSuijs** [comment]
I have struggled ages to find this post! Thanks for the proposed solution. After some small changes in my fork, it does the trick partly!
```
- name: Modify registry paths if registry_url is not registry.redhat.io or not docker.io or not registry.centos.org
  shell: "find {{ examples_base }} -type f | xargs -n 1 sed -E -i 's/(registry\\.access\\.redhat\\.com|docker\\.io|registry\\.centos\\.org)/{{ registry_host | quote }}/g'"
  when: registry_host != '' and openshift_examples_modify_imagestreams | default(False) | bool
```

I also had to change each ImageStream to allow an insecure registry.
```
importPolicy:
        insecure: true
```
It seems the openshift_docker_insecure_registries parameter of the inventory file is not properly propagated with a private insecure repo.
