### ISSUE TITLE
Upgrade from 1.5 to 3.6 fails on "Verify docker upgrade targets"

### ISSUE THREAD

**Issue by MarWestermann** [openshift/openshift-ansible#8342]
#### Description

Upgrading from 1.5 to 3.6 using ansible playbook
Branch: release-3.6

##### Version
```
ansible 2.5.2
openshift-ansible-3.6.173.0.119-1
```
##### Steps To Reproduce
1. Have openshift 1.5 installed
2. run ansible-playbook playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.yml

##### Expected Results
Update should succeed

##### Observed Results
The upgrade fails with docker version error

```
Failure summary:


  1. Hosts:    master1.ourdomain.de, node1.ourdomain.de, node2.ourdomain.de, node3.ourdomain.de, node4.ourdomain.de
     Play:     Verify docker upgrade targets
     Task:     fail
     Message:  This playbook requires access to Docker 1.12 or later
```

##### Additional Information
docker --version (on master and nodes)
```
Docker version 1.12.6, build 3a094bd/1.12.6
```
CentOS Linux release 7.3.1611 (Core) on masters and nodes

**Comment by vrutkovs** [comment]
Make sure your nodes didn't get docker 1.13 from RHEL / CentOS 7.5 installed - you may need to downgrade it and set includers

Also note that ansible 2.5.2 may not work with 1.5/3.6 code, so its recommended to use ansible 2.3

**Comment by MarWestermann** [comment]
Hi @vrutkovs 
Thank you for your quick response.
No it did not install 1.13.. it is still on 1.12.6.. But I'm not sure what you mean with setting includers. Can you please point me to the right direction?
I also downgraded ansible to 2.3

**Comment by vrutkovs** [comment]
Sorry, I meant "excluders". These should be enabled by default.

It seems the play can't find docker RPM. Do you have repos setup correctly? What's your inventory and the output of ansible-playbook?

**Comment by MarWestermann** [comment]
This is my inventory: https://github.com/openshift/openshift-ansible/issues/8342
and this the last lines of ansible playbook log: https://pastebin.com/SzM7zhF8

**Comment by vrutkovs** [comment]
The inventory looks good, so I suspect something is wrong with repos on machines

Could you rerun the playbook with `ansible-playbook -vvv`?

**Comment by MarWestermann** [comment]
here is the log of playbook -vvv:
https://gist.github.com/MarWestermann/21fe94de7331a0f71963308ac26f75e6

**Comment by vrutkovs** [comment]
I see the facts list docker 1.12 installed, but the log doesn't have the error part, could you attach last 100 lines of the log with `-vvv`?

**Comment by MarWestermann** [comment]
at the top of the output there is a hint that the output is truncated but when you click on the link provided there you'll see the hole file..

maybe error is that the command:
```
repoquery --plugins --qf %{version} "docker"
```
does not have output.. but it would have for "docker-ce"

**Comment by vrutkovs** [comment]
Oh, that explains it. Docker CE is not supported, so you'll need to enable a repo, which has `docker` package - this would be installed instead

**Comment by MarWestermann** [comment]
ok, but cannot find informations about which repo to add to centos for the correct docker version?!

**Comment by MarWestermann** [comment]
does that mean one needs a docker-ee subscription?

**Comment by vrutkovs** [comment]
`docker` package should be available in (extras)[http://mirror.centos.org/centos/7/extras/x86_64/Packages/]

**Comment by MarWestermann** [comment]
OK, thank you very much for your help!

**Comment by MarWestermann** [comment]
FYI: I found the main reason why the update fails.. In yum.conf there was a line exclude= tuned-profiles-origin-node  origin-tests  origin-sdn-ovs  origin-recycle  origin-pod  origin-node  origin-master  origin-dockerregistry  origin-clients-redistributable  origin-clients  origin  docker*1.20*  docker*1.19*  docker*$

I'm quite sure this comes from installation of origin 1.5

**Comment by MarWestermann** [comment]
I investigated further:
when I remove docker* excludes from yum.conf the problem occurres again cause docker*1.13* is excluded by the playbook itself again.
But then no docker version can be found.. and the extras repository responses with 1.13.1 when not excluded.

**Comment by bilalx20** [comment]
docker 1.12.6 is not available on http://ftp.fau.de/centos/7.5.1804/extras/x86_64/Packages/ anymore :( 

can you suggest something different?
