### ISSUE TITLE
azure image builds broken after `install: verify that at least one master is schedulable`

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-ansible#8353]
```
TASK [openshift_sanitize_inventory : At least one master is schedulable] *******
Friday 11 May 2018  19:35:09 +0000 (0:00:00.030)       0:07:22.819 ************ 
fatal: [40.76.65.11]: FAILED! => {"msg": "The conditional check 'l_master_schedulable | length > 0' failed. The error was: error while evaluating conditional (l_master_schedulable | length > 0): 'dict object' has no attribute u'oo_nodes_to_bootstrap'\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/roles/openshift_sanitize_inventory/tasks/main.yml': line 101, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: At least one master is schedulable\n  ^ here\n"}
```

relevant PRs are:
https://github.com/openshift/openshift-ansible/pull/7911
https://github.com/openshift/openshift-ansible/pull/8341

**Comment by jim-minter** [comment]
Need a fix for release-3.9 and may have a knock-on effect on the master work in progress

@kwoodson please can you work on this?

**Comment by vrutkovs** [comment]
Which groups does Azure use? Given that we test against AWS and GCP there are only two groups: `oo_masters_to_config` and `oo_nodes_to_bootstrap` (for GCP)

**Comment by vrutkovs** [comment]
@kwoodson okay, I see. #8364 has the fix for that and should be merged soon

**Comment by kwoodson** [comment]
@vrutkovs, test against #8364 and it worked on 3.9.  Please also open against master.

**Comment by vrutkovs** [comment]
Fixed by https://github.com/openshift/openshift-ansible/pull/8364
