### ISSUE TITLE
Remove ServiceAntiAffinity priority function from default configuration

### ISSUE THREAD

**Issue by aveshagarwal** [openshift/openshift-ansible#8379]
I'd recommend to remove ServiceAntiAffinity priority function from default configuration. That means removing following: https://github.com/openshift/openshift-ansible/blob/master/roles/lib_utils/lookup_plugins/openshift_master_facts_default_priorities.py#L47-L56

And the reason for removal is that: 

1. By default, SelectorSpreadPriority work on `region` (failure-domain.beta.kubernetes.io/region) and `zone` (failure-domain.beta.kubernetes.io/zone) labels by default. So there is no reason to enable serviceAntiAffinity to work on the same `zone` labels.
2. ServiceAntiAffinity implementation is sort of hack/ or with limited uses perhaps and not same as SelectorSpreadPriority implementation and surely not tested as much as SelectorSpreadPriority.  
3. Enabling ServiceAntiAffinity in its current form could lead to confusions at customer sites and infact can produce undesired result. See https://bugzilla.redhat.com/show_bug.cgi?id=1558122 for reference.

Please note its not about removing ServiceAntiAffinity from code base. Infact I have created a PR upstream to make ServiceAntiAffinity work same as SelectorSpreadPriority on custom labels. Once that PR is available, then customers can enable it as needed for their custom labels.

@sdodson @derekwaynecarr @sjenning

**Comment by sdodson** [comment]
I think that exists to support zones outside of cloudproviders which would provide the labels you're talking about. If `zone` is not defined in the labels for a host where kubernetes provides `failure-domain.beta.kubernetes.io/region` does that create a problem?

**Comment by sdodson** [comment]
Yes, they deliberately label their hosts `region=primary,zone=east` `region=primary,zone=west`, `region=infra,zone=east`, `region=infra,zone=west`. https://docs.openshift.com/container-platform/3.9/install_config/install/advanced_install.html#configuring-node-host-labels

Maybe we should make region and zone mutually exclusive with any configured cloudprovider or a list of known cloud providers?
