### ISSUE TITLE
Adding new node Failure - "/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2, Timer expired"

### ISSUE THREAD

**Issue by BigBlueWhale0** [openshift/openshift-ansible#8385]
#### Description
Hi, everybody. Can you help me?
I have got some cluster which includes 3 master nodes and 6 action nodes  on Openshift origin 3.6.
When I'm trying to add new node to existing cluster through openshift ansible, I get  error: 
```
TASK [Gathering Facts] ***************************************************************************************************************************************************************
ok: [master-02]
ok: [master-03]
ok: [node-07]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired
fatal: [master-01.]: FAILED! => {
    "changed": false, 
    "cmd": "/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2", 
    "failed": true, 
    "rc": 257
}

MSG:

Timer expired
```
I'm executing playbook /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-node/scaleup.yml from master-02 by my private user, who has got permission to ssh-login to every nodes (master and action) and has got root's permissions without sudo (NOPASSWD: ALL).
Before that I've added my new node-07 to ansible's inventory file in group [new_nodes].
I guess there is the problem in master-01, but I'm trying to execute cmd '/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2' by my private user and I did it, I got:
```
/dev/sda                                  
/dev/sda1                                 25f4465b-b18c-4deb-bda6-3b30dba979cb
/dev/sda2                                 d5d84f03-9973-4441-bc55-798b9abf9ce4
/dev/sdb                                  
/dev/sdb1                                 200774a0-d91c-4b41-b703-8deb7530d028
/dev/sdc                                  
/dev/sdc1                                 0fLnWv-LKTb-99Y0-rdpw-5XZ8-xtml-5IvqkV
/dev/mapper/docker--vg-docker--pool_tmeta 
/dev/mapper/docker--vg-docker--pool       
/dev/mapper/docker--vg-docker--pool_tdata 
/dev/mapper/docker--vg-docker--pool       
/dev/sde                                  54832061-6d23-4922-abfc-8a78a963210b
```
Also at the end was error:
```
fatal: [node-07]: FAILED! => {
    "failed": true
}

MSG:

{{ hostvars[groups.oo_first_master.0].openshift.common.portal_net }}: 'dict object' has no attribute 'openshift'
```
What's happed? Why ansible can't execute cmd '/bin/lsblk'?

##### Version
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

openshift-ansible-3.6.173.0.60-1.el7.noarch
openshift-ansible-playbooks-3.6.173.0.60-1.el7.noarch
openshift-ansible-lookup-plugins-3.6.173.0.60-1.el7.noarch
openshift-ansible-docs-3.6.173.0.60-1.el7.noarch
openshift-ansible-callback-plugins-3.6.173.0.60-1.el7.noarch
atomic-openshift-utils-3.6.173.0.60-1.el7.noarch
openshift-ansible-roles-3.6.173.0.60-1.el7.noarch
openshift-ansible-filter-plugins-3.6.173.0.60-1.el7.noarch

origin-excluder-3.6.0-1.0.c4dd4cf.noarch
centos-release-openshift-origin-1-1.el7.centos.noarch
origin-clients-3.6.0-1.0.c4dd4cf.x86_64
origin-docker-excluder-3.6.0-1.0.c4dd4cf.noarch
origin-3.6.0-1.0.c4dd4cf.x86_64
origin-master-3.6.0-1.0.c4dd4cf.x86_64

##### Steps To Reproduce
ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-node/scaleup.yml

##### Expected Results
much much happiness
```
NAME                                STATUS                     AGE       VERSION
node-01           Ready                      224d      v1.6.1+5115d708d7
node-02           Ready                      224d      v1.6.1+5115d708d7
node-03           Ready                      224d      v1.6.1+5115d708d7
node-04           Ready                      224d      v1.6.1+5115d708d7
node-05           Ready                      224d      v1.6.1+5115d708d7
node-06           Ready                      17d       v1.6.1+5115d708d7
node-07         Ready                      17d       v1.6.1+5115d708d7
```

##### Observed Results
TASK [openshift_docker_facts : Set docker facts] *************************************************************************************************************************************
fatal: [node-07]: FAILED! => {
    "failed": true
}

MSG:

{{ hostvars[groups.oo_first_master.0].openshift.common.portal_net }}: 'dict object' has no attribute 'openshift'

 [WARNING]: Could not create retry file '/usr/share/ansible/openshift-ansible/playbooks/byo/openshift-node/scaleup.retry'.         [Errno 13] Permission denied: u'/usr/share/ansible
/openshift-ansible/playbooks/byo/openshift-node/scaleup.retry'

PLAY RECAP ***************************************************************************************************************************************************************************
localhost                  : ok=12   changed=0    unreachable=0    failed=0   
master-01 : ok=0    changed=0    unreachable=0    failed=1   
master-02 : ok=13   changed=0    unreachable=0    failed=0   
master-03 : ok=13   changed=0    unreachable=0    failed=0   
node-07  : ok=112  changed=9    unreachable=0    failed=1   

##### Additional Information
I tried to run ansible playbook by root with ssh-access to master-01, access for root was appeared, but I got the same error - "/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2, Timer expired"

Also I tried to run ansible playbook /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-checks/health.yml and I got the same error on all nodes.

**Comment by vrutkovs** [comment]
Looks like https://github.com/ansible/ansible/issues/10779#issuecomment-228258891 to me - the task times out and facts are corrupted

**Comment by BigBlueWhale0** [comment]
Great. This is right for solution to the my problem. I set 'gather_timeout = 20' in ansible.cfg and ' timeout(seconds=20, error_message="Timer expired"):' in ./lib/ansible/module_utils/facts.py. At the moment it's working, but the all process takes much longer. 
Thank you!
