### ISSUE TITLE
etcd role references non-existent binary in quay.io image

### ISSUE THREAD

**Issue by hansmi** [openshift/openshift-ansible#8388]
#### Description

Commit 5d5d25bf1 changed the default etcd image for containerized Origin installations from `registry.fedoraproject.org/latest/etcd` to `quay.io/coreos/etcd:v3.2.15`. The generated systemd service contains `--entrypoint=/usr/bin/etcd`:

```
# From roles/etcd/templates/etcd.docker.service
ExecStart=/usr/bin/docker run --name {{ etcd_service }} --rm -v {{ etcd_data_dir }}:{{ etcd_data_dir }}:z -v {{ etcd_conf_dir }}:{{ etcd_conf_dir }}:ro --env-file={{ etcd_conf_file }} --net=host --entrypoint=/usr/bin/etcd {{ etcd_image }}
```

That binary doesn't exist, however:

```
$ docker run --rm -it --entrypoint /usr/bin/etcd quay.io/coreos/etcd:v3.2.15
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/usr/bin/etcd\": stat /usr/bin/etcd: no such file or directory": unknown.
```

##### Version

`master` branch as of May 16, 13:20 UTC, `openshift-ansible-3.10.0-0.47.0-4-g5c1207cd2`, commit `5c1207cd2`.

**Comment by vrutkovs** [comment]
This systemd is being removed during install and won't be used anymore. Instead a static pod with etcd image would be setup
