### ISSUE TITLE
azure: integrate image build process with launch

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-ansible#8389]
GCE deployments support running the node build process as part of launch.yml via `openshift_gcp_build_image`. We should do something similar in Azure (at least going to simplify our PR jobs).
```console
[openshift-ansible]$ rg openshift_gcp_build_image
playbooks/gcp/openshift-cluster/launch.yml
4:  when: openshift_gcp_build_image | default(False) | bool
```
@jim-minter @kwoodson @pweil-

**Comment by kwoodson** [comment]
@kargakis,  if you could expound on this I could probably do this work.  We have a `launch.yml` and we just need to call it.  Thanks in advance.

**Comment by kargakis** [comment]
Planning to work on this at some point soon

/assign

**Comment by jim-minter** [comment]
do we definitely want to do this? and should it be a trello card?

**Comment by kargakis** [comment]
@jim-minter the main motivation is to try to reuse the same manifests used for e2e tests when we switch to the ci operator although we will probably need to configure our own additional variables in ansible.

https://github.com/openshift/release/blob/c5042b87283939c927fa35d64f357746016df3bf/cluster/ci/config/prow/jobs/cluster-launch-e2e.yaml#L166

We may also want to just copy-paste the job and reconfigure it for ourselves.

**Comment by jim-minter** [comment]
trello'd
