### ISSUE TITLE
Python dependency problem with OpenSSL crypto

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#840]
http://stackoverflow.com/questions/33555776/openshift-ansible-fails-since-2-days-with-no-module-named-openssl-crypto

Not sure if there is a fix on our side, but wanted it visible here

**Comment by detiber** [comment]
PR to address this is here: https://github.com/openshift/openshift-ansible/pull/826

**Comment by abutcher** [comment]
@brenton Believe this one can be closed. This is now addressed in our docs.
