### ISSUE TITLE
Vagrant up error

### ISSUE THREAD

**Issue by Morriz** [openshift/openshift-ansible#841]
Hi, I have followed the readme and installed the necessary prerequisites, however I get the following output on osx 10.11.1 with vagrant 1.7.4:

```
$ vagrant up --no-provision                           
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- vagrant/command
```

**Comment by dakky** [comment]
Had the same problem. I deleted my ~/.vagrand.d directory and reinstall die hostmanger plugin.
Now it works again

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.
