### ISSUE TITLE
Origin 3.7 installation failed

### ISSUE THREAD

**Issue by victorvoronin** [openshift/openshift-ansible#8410]
#### Description

Simple 1 master and 2 nodes install.

##### Version

ansible --version
ansible 2.5.2

git describe
openshift-ansible-3.7.48-1-4-g1283ae7

##### Steps To Reproduce
1. set inventory values to install 3.7.2 version:
openshift_release=v3.7
openshift_pkg_version=-3.7.2-1.el7.git.0.cd74924
2. run config.yml playbook

##### Expected Results
Openshift origin 3.7.2 cluster installed

##### Observed Results

Describe what is actually happening.
     Message:  Error: Package: origin-sdn-ovs-3.7.2-1.el7.git.0.cd74924.x86_64 (centos-openshift-origin37)
                          Requires: origin-node = 3.7.2-1.el7.git.0.cd74924
                          Installed: origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64 (@centos-openshift-origin)
                              origin-node = 3.9.0-1.el7.git.0.ba7faec
                          Available: origin-node-3.6.0-1.0.c4dd4cf.x86_64 (centos-openshift-origin)
                              origin-node = 3.6.0-1.0.c4dd4cf
                          Available: origin-node-3.6.1-1.0.008f2d5.x86_64 (centos-openshift-origin)
                              origin-node = 3.6.1-1.0.008f2d5
                          Available: origin-node-3.7.0-1.0.7ed6862.x86_64 (centos-openshift-origin)
                              origin-node = 3.7.0-1.0.7ed6862
                          Available: origin-node-3.7.1-1.el7.git.0.0a2d6a1.x86_64 (centos-openshift-origin)
                              origin-node = 3.7.1-1.el7.git.0.0a2d6a1
                          Available: origin-node-3.7.1-2.el7.x86_64 (centos-openshift-origin)
                              origin-node = 3.7.1-2.el7
                          Available: origin-node-3.7.2-1.el7.git.0.cd74924.x86_64 (centos-openshift-origin37)
                              origin-node = 3.7.2-1.el7.git.0.cd74924
                          Available: origin-node-3.8.0-1.el7.git.0.dd1558c.x86_64 (centos-openshift-origin)
                              origin-node = 3.8.0-1.el7.git.0.dd1558c

##### Additional Information

This happened because packages were updated on previous step:
changed: [node1] => {"attempts": 1, "changed": true, "msg": "", "rc": 0, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: centos.slaskdatacenter.com\n * epel: mirror.kinamo.be\n * extras: centos.slaskdatacenter.com\n * updates: ftp.man.poznan.pl\nResolving Dependencies\n--> Running transaction check\n---> Package origin-node.x86_64 0:3.7.2-1.el7.git.0.cd74924 will be installed\n--> Processing Dependency: tuned-profiles-origin-node = 3.7.2-1.el7.git.0.cd74924 for package: origin-node-3.7.2-1.el7.git.0.cd74924.x86_64\n--> Processing Dependency: origin = 3.7.2-1.el7.git.0.cd74924 for package: origin-node-3.7.2-1.el7.git.0.cd74924.x86_64\n--> Running transaction check\n---> Package origin.x86_64 0:3.7.2-1.el7.git.0.cd74924 will be installed\n--> Processing Dependency: origin-clients = 3.7.2-1.el7.git.0.cd74924 for package: origin-3.7.2-1.el7.git.0.cd74924.x86_64\n---> Package origin-node.x86_64 0:3.9.0-1.el7.git.0.ba7faec will be installed\n--> Processing Dependency: origin = 3.9.0-1.el7.git.0.ba7faec for package: origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64\n--> Running transaction check\n---> Package origin.x86_64 0:3.7.2-1.el7.git.0.cd74924 will be installed\n---> Package origin.x86_64 0:3.9.0-1.el7.git.0.ba7faec will be installed\n--> Processing Dependency: origin-clients = 3.9.0-1.el7.git.0.ba7faec for package: origin-3.9.0-1.el7.git.0.ba7faec.x86_64\n---> Package origin-clients.x86_64 0:3.7.2-1.el7.git.0.cd74924 will be installed\n--> Running transaction check\n---> Package origin-clients.x86_64 0:3.9.0-1.el7.git.0.ba7faec will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package        Arch   Version                    Repository               Size\n================================================================================\nInstalling for dependencies:\n origin         x86_64 3.9.0-1.el7.git.0.ba7faec  centos-openshift-origin  69 M\n origin-clients x86_64 3.9.0-1.el7.git.0.ba7faec  centos-openshift-origin  33 M\n origin-node    x86_64 3.9.0-1.el7.git.0.ba7faec  centos-openshift-origin 7.7 k\n\nTransaction Summary\n================================================================================\nInstall             ( 3 Dependent packages)\n\nTotal download size: 102 M\nInstalled size: 809 M\nDownloading packages:\n--------------------------------------------------------------------------------\nTotal                                              745 kB/s | 102 MB  02:19     \nRunning transaction check\nRunning transaction test\nTransaction test succeeded\nRunning transaction\n  Installing : origin-clients-3.9.0-1.el7.git.0.ba7faec.x86_64              1/3 \n  Installing : origin-3.9.0-1.el7.git.0.ba7faec.x86_64                      2/3 \n  Installing : origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64                 3/3 \n  Verifying  : origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64                 1/3 \n  Verifying  : origin-clients-3.9.0-1.el7.git.0.ba7faec.x86_64              2/3 \n  Verifying  : origin-3.9.0-1.el7.git.0.ba7faec.x86_64                      3/3 \n\nDependency Installed:\n  origin.x86_64 0:3.9.0-1.el7.git.0.ba7faec                                     \n  origin-clients.x86_64 0:3.9.0-1.el7.git.0.ba7faec                             \n  origin-node.x86_64 0:3.9.0-1.el7.git.0.ba7faec                                \n\nComplete!\n"]}

**Comment by victorvoronin** [comment]
Sorry, forgot to write
TASK [openshift_node : Install Node package] updates version to 3.9 (that couldn't take place with expected behavior)
Then
TASK [openshift_node : Install sdn-ovs package] have been failed

**Comment by vrutkovs** [comment]
A forced update to 3.9 should be mitigated by excluders - do you have those enabled?

**Comment by victorvoronin** [comment]
No, could you please clarify how to do it?

**Comment by vrutkovs** [comment]
These should be enabled by default - `openshift_enable_excluders` var would make sure your yum would exclude origin packages with other version.

Make sure you have it set to `true` and please include inventory and the output of `ansible-playbook -vvv` output if the issue still occurs

**Comment by aioue** [comment]
Same error, with or without excluders.

Package versions:
```
openshift-ansible-3.7.43-1.git.1.ed51ddd.el7.noarch
ansible 2.4.2.0
```

Partial config from `/etc/ansible/hosts`:
```
[OSEv3:vars]
# Set OpenShift Version
# Make sure this matches up with the ansible-pull which pulls down this inventory and the openshift-ansible repo
openshift_clusterid=prod37
openshift_release=v3.7
#openshift_pkg_version=-3.7.0
```

Verbose output:
```
fatal: [prod37n32.euw1.axonvibelabs.com]: FAILED! => {
    "attempts": 2,
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "conf_file": null,
            "disable_gpg_check": false,
            "disablerepo": null,
            "enablerepo": null,
            "exclude": null,
            "install_repoquery": true,
            "installroot": "/",
            "list": null,
            "name": [
                "origin-sdn-ovs-3.7.0"
            ],
            "security": false,
            "skip_broken": false,
            "state": "present",
            "update_cache": false,
            "validate_certs": true
        }
    },
    "msg": "Error: Package: origin-sdn-ovs-3.7.0-1.0.7ed6862.x86_64 (centos-openshift-origin)\n           Requires: origin-node = 3.7.0-1.0.7ed6862\n           Installed: origin-node-3.7.1-1.el7.git.0.0a2d6a1.x86_64 (@centos-openshift-origin)\n               origin-node = 3.7.1-1.el7.git.0.0a2d6a1\n           Available: origin-node-3.6.0-1.0.c4dd4cf.x86_64 (centos-openshift-origin)\n               origin-node = 3.6.0-1.0.c4dd4cf\n           Available: origin-node-3.6.1-1.0.008f2d5.x86_64 (centos-openshift-origin)\n               origin-node = 3.6.1-1.0.008f2d5\n           Available: origin-node-3.7.0-1.0.7ed6862.x86_64 (centos-openshift-origin)\n               origin-node = 3.7.0-1.0.7ed6862\n           Available: origin-node-3.7.1-2.el7.x86_64 (centos-openshift-origin)\n               origin-node = 3.7.1-2.el7\n           Available: origin-node-3.7.2-1.el7.git.0.cd74924.x86_64 (centos-openshift-origin37)\n               origin-node = 3.7.2-1.el7.git.0.cd74924\n           Available: origin-node-3.8.0-1.el7.git.0.dd1558c.x86_64 (centos-openshift-origin)\n               origin-node = 3.8.0-1.el7.git.0.dd1558c\n           Available: origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64 (centos-openshift-origin)\n               origin-node = 3.9.0-1.el7.git.0.ba7faec\n",
    "rc": 1,
    "results": [
        "Loaded plugins: fastestmirror, s3iam\nLoading mirror speeds from cached hostfile\n * base: ftp.heanet.ie\n * extras: ftp.heanet.ie\n * updates: ftp.heanet.ie\nResolving Dependencies\n--> Running transaction check\n---> Package origin-sdn-ovs.x86_64 0:3.7.0-1.0.7ed6862 will be installed\n--> Processing Dependency: origin-node = 3.7.0-1.0.7ed6862 for package: origin-sdn-ovs-3.7.0-1.0.7ed6862.x86_64\n--> Processing Dependency: openvswitch >= 2.6.1 for package: origin-sdn-ovs-3.7.0-1.0.7ed6862.x86_64\n--> Running transaction check\n---> Package openvswitch.x86_64 1:2.6.1-3.git20161206.el7 will be installed\n--> Processing Dependency: libpcap.so.1()(64bit) for package: 1:openvswitch-2.6.1-3.git20161206.el7.x86_64\n---> Package origin-sdn-ovs.x86_64 0:3.7.0-1.0.7ed6862 will be installed\n--> Processing Dependency: origin-node = 3.7.0-1.0.7ed6862 for package: origin-sdn-ovs-3.7.0-1.0.7ed6862.x86_64\n--> Running transaction check\n---> Package libpcap.x86_64 14:1.5.3-11.el7 will be installed\n---> Package origin-sdn-ovs.x86_64 0:3.7.0-1.0.7ed6862 will be installed\n--> Processing Dependency: origin-node = 3.7.0-1.0.7ed6862 for package: origin-sdn-ovs-3.7.0-1.0.7ed6862.x86_64\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"
    ]
}
```

**Comment by dzianis-shkindzerau** [comment]
Similar error while scaling up origin 3.6 nodes for already worked (1 year) cluster

Partial config:
`
deployment_type: origin
openshift_deployment_type: origin
openshift_release: v3.6
openshift_image_tag: v3.6.1
openshift_pkg_version: -3.6.1
`

Ansible output:
`
TASK [openshift_node : Install Node package] *******************************************************************************************************************************************************************************************
task path: roles/openshift_node/tasks/main.yml:71
fatal: [nodexxx]: FAILED! => {
    "changed": false, 
    "rc": 1, 
    "results": [
        "Loaded plugins: fastestmirror, priorities, protectbase\n
        Loading mirror speeds from cached hostfile\n
        * base: ftp.freepark.org\n
        * epel: mirror.karneval.cz\n
        * extras: ftp.freepark.org\n
        * updates: ftp.freepark.org\n
        0 packages excluded due to repository protections\n
        
        Package tuned-profiles-origin-node is obsoleted by origin-node, trying to install origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64 instead\n
        Resolving Dependencies\n
        --> Running transaction check\n
        ---> Package origin-node.x86_64 0:3.6.1-1.0.008f2d5 will be installed\n
        --> Processing Dependency: socat for package: origin-node-3.6.1-1.0.008f2d5.x86_64\n
        --> Processing Dependency: nfs-utils for package: origin-node-3.6.1-1.0.008f2d5.x86_64\n
        ---> Package origin-node.x86_64 0:3.9.0-1.el7.git.0.ba7faec will be installed\n
        --> Processing Dependency: origin = 3.9.0-1.el7.git.0.ba7faec for package: origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64\n
        --> Processing Dependency: conntrack-tools for package: origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64\n
        --> Processing Dependency: cifs-utils for package: origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64\n
        --> Running transaction check\n
        ---> Package cifs-utils.x86_64 0:6.2-10.el7 will be installed\n
        --> Processing Dependency: keyutils for package: cifs-utils-6.2-10.el7.x86_64\n
        ---> Package conntrack-tools.x86_64 0:1.4.4-3.el7_3 will be installed\n
        --> Processing Dependency: libnetfilter_cttimeout.so.1(LIBNETFILTER_CTTIMEOUT_1.1)(64bit) for package: conntrack-tools-1.4.4-3.el7_3.x86_64\n
        --> Processing Dependency: libnetfilter_cttimeout.so.1(LIBNETFILTER_CTTIMEOUT_1.0)(64bit) for package: conntrack-tools-1.4.4-3.el7_3.x86_64\n
        --> Processing Dependency: libnetfilter_cthelper.so.0(LIBNETFILTER_CTHELPER_1.0)(64bit) for package: conntrack-tools-1.4.4-3.el7_3.x86_64\n
        --> Processing Dependency: libnetfilter_queue.so.1()(64bit) for package: conntrack-tools-1.4.4-3.el7_3.x86_64\n
        --> Processing Dependency: libnetfilter_cttimeout.so.1()(64bit) for package: conntrack-tools-1.4.4-3.el7_3.x86_64\n
        --> Processing Dependency: libnetfilter_cthelper.so.0()(64bit) for package: conntrack-tools-1.4.4-3.el7_3.x86_64\n
        ---> Package nfs-utils.x86_64 1:1.3.0-0.54.el7 will be installed\n
        --> Processing Dependency: libtirpc >= 0.2.4-0.7 for package: 1:nfs-utils-1.3.0-0.54.el7.x86_64\n
        --> Processing Dependency: gssproxy >= 0.7.0-3 for package: 1:nfs-utils-1.3.0-0.54.el7.x86_64\n
        --> Processing Dependency: rpcbind for package: 1:nfs-utils-1.3.0-0.54.el7.x86_64\n
        --> Processing Dependency: quota for package: 1:nfs-utils-1.3.0-0.54.el7.x86_64\n
        --> Processing Dependency: libtirpc.so.1()(64bit) for package: 1:nfs-utils-1.3.0-0.54.el7.x86_64\n
        ---> Package origin.x86_64 0:3.6.1-1.0.008f2d5 will be updated\n
        --> Processing Dependency: origin = 3.6.1-1.0.008f2d5 for package: origin-node-3.6.1-1.0.008f2d5.x86_64\n
        ---> Package origin.x86_64 0:3.9.0-1.el7.git.0.ba7faec will be an update\n
        --> Processing Dependency: origin-clients = 3.9.0-1.el7.git.0.ba7faec for package: origin-3.9.0-1.el7.git.0.ba7faec.x86_64\n
        ---> Package socat.x86_64 0:1.7.3.2-2.el7 will be installed\n
        --> Running transaction check\n
        ---> Package gssproxy.x86_64 0:0.7.0-17.el7 will be installed\n
        --> Processing Dependency: libverto-module-base for package: gssproxy-0.7.0-17.el7.x86_64\n
        ---> Package keyutils.x86_64 0:1.5.8-3.el7 will be installed\n
        ---> Package libnetfilter_cthelper.x86_64 0:1.0.0-9.el7 will be installed\n
        ---> Package libnetfilter_cttimeout.x86_64 0:1.0.0-6.el7 will be installed\n
        ---> Package libnetfilter_queue.x86_64 0:1.0.2-2.el7_2 will be installed\n
        ---> Package libtirpc.x86_64 0:0.2.4-0.10.el7 will be installed\n
        ---> Package origin.x86_64 0:3.6.1-1.0.008f2d5 will be updated\n
        --> Processing Dependency: origin = 3.6.1-1.0.008f2d5 for package: origin-node-3.6.1-1.0.008f2d5.x86_64\n
        ---> Package origin-clients.x86_64 0:3.6.1-1.0.008f2d5 will be updated\n
        ---> Package origin-clients.x86_64 0:3.9.0-1.el7.git.0.ba7faec will be an update\n
        ---> Package quota.x86_64 1:4.01-17.el7 will be installed\n
        --> Processing Dependency: quota-nls = 1:4.01-17.el7 for package: 1:quota-4.01-17.el7.x86_64\n
        --> Processing Dependency: tcp_wrappers for package: 1:quota-4.01-17.el7.x86_64\n
        ---> Package rpcbind.x86_64 0:0.2.0-44.el7 will be installed\n
        --> Running transaction check\n
        ---> Package libverto-tevent.x86_64 0:0.2.5-4.el7 will be installed\n
        ---> Package origin.x86_64 0:3.6.1-1.0.008f2d5 will be updated\n
        --> Processing Dependency: origin = 3.6.1-1.0.008f2d5 for package: origin-node-3.6.1-1.0.008f2d5.x86_64\n
        ---> Package quota-nls.noarch 1:4.01-17.el7 will be installed\n
        ---> Package tcp_wrappers.x86_64 0:7.6-77.el7 will be installed\n
        --> Finished Dependency Resolution\n 
        
        You could try using --skip-broken to work around the problem\n 
        You could try running: rpm -Va --nofiles --nodigest\n"
    ]
}

MSG:

Error: Package: origin-node-3.6.1-1.0.008f2d5.x86_64 (centos-openshift-origin)
           Requires: origin = 3.6.1-1.0.008f2d5
           Removing: origin-3.6.1-1.0.008f2d5.x86_64 (@centos-openshift-origin)
               origin = 3.6.1-1.0.008f2d5
           Updated By: origin-3.9.0-1.el7.git.0.ba7faec.x86_64 (centos-openshift-origin)
               origin = 3.9.0-1.el7.git.0.ba7faec
           Available: origin-3.6.0-1.0.c4dd4cf.x86_64 (centos-openshift-origin)
               origin = 3.6.0-1.0.c4dd4cf
           Available: origin-3.7.0-1.0.7ed6862.x86_64 (centos-openshift-origin)
               origin = 3.7.0-1.0.7ed6862
           Available: origin-3.7.1-1.el7.git.0.0a2d6a1.x86_64 (centos-openshift-origin)
               origin = 3.7.1-1.el7.git.0.0a2d6a1
           Available: origin-3.7.1-2.el7.x86_64 (centos-openshift-origin)
               origin = 3.7.1-2.el7
           Available: origin-3.8.0-1.el7.git.0.dd1558c.x86_64 (centos-openshift-origin)
               origin = 3.8.0-1.el7.git.0.dd1558c
   `

**Comment by stewartshea** [comment]
I was running into the a similar (or the same) issue and this link helped: [](https://github.com/openshift/openshift-ansible/issues/8030
)

In my case, I had originally tested without the `openshift_release` variable, which caused the current release repo to hang around, even after adding the variable after the fact. So, with that, ensure that the only openshift repo enabled is `CentOS-OpenShift-Origin37.repo` and  NOT `CentOS-OpenShift-Origin.repo`. This helped for me at least.

**Comment by dzianis-shkindzerau** [comment]
@stewartshea thanks! This helped me to.

**Comment by DanyC97** [comment]
@victorvoronin if this is no longer an issue, can you please close it? thx

**Comment by DanyC97** [comment]
@vrutkovs candidate for closing it as being resolved, thanks
