### ISSUE TITLE
Installing on GCE, no OVS

### ISSUE THREAD

**Issue by christian-posta** [openshift/openshift-ansible#842]
I've noticed when I do an installation against GCE, OVS doesn't get installed and the minimum requirement for networking for kubernetes (flat network space for pods and nodes) is not satisfied. Am I missing something? Are we supposed to do something manually to make this happen? Why is OVS explicitly turned off for GCE? How do we get this to work on GCE?

**Comment by menren** [comment]
Is OVS an alternative to Openshift SDN ?
On GCE openshift_sdn is enabled for the overlay network

**Comment by detiber** [comment]
We specifically do not enable the sdn by default  on gce installs. In the past there was some kubernetes automagic that allowed it to work, but it appears that is no longer the case.

To enable the sdn, you can use the openshift_use_openshift_sdn variable in your inventory (if using the  byo playbooks):
```
[OSEv3:vars]
...
openshift_use_openshift_sdn=True
...
```

**Comment by christian-posta** [comment]
Thanks @detiber ... i've tried that, and it does install SDN/OVS but doesn't configure it properly. going with AWS at the moment cause I have a hard deadline for this, but will try it again with SDN explicitly set to true and see what else is missing (might be something easy...)

**Comment by detiber** [comment]
@christian-posta make sure that there are no network conflicts with the default values for the sdn network and the host networking.

osm_cluster_network_cidr can be used to change the default (10.1.0.0/16)
osm_host_subnet_length can change the size of the subnet assigned to each host (8 by default)

openshift_master_portal_net can be used if the conflict is with the service network (172.30.0.0/16 by default)

**Comment by christian-posta** [comment]
awesome, thanks @detiber will give that a shot (when i get a sec) and report back

**Comment by eformat** [comment]
i tried this without any luck on GCE. setting 

openshift_use_openshift_sdn=True

and checking the facts generation:

ansible-playbook playbooks/byo/openshift_facts.yml

results in 

       "use_openshift_sdn": false, 

i've ensured the local default network in GCE is not conflicting. how can i further debug this ?

Thx
Mike

**Comment by eformat** [comment]
here's my config for reference (hooked up to OSE3.1 enterprise repos)

```
cat <<EOF > /etc/ansible/hosts
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root
deployment_type=openshift-enterprise

# SDN network
openshift_use_openshift_sdn=True
#osm_cluster_network_cidr=10.1.0.0/16
#openshift_master_portal_net=172.30.0.0/16

# Configure the multi-tenant SDN plugin (default is 'redhat/openshift-ovs-subnet')
#os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
#os_sdn_network_plugin_name='redhat/openshift-ovs-subnet'

# If ansible_ssh_user is not root, ansible_sudo must be set to true
#ansible_sudo=true

# Enable cluster metrics
use_cluster_metrics=true

# enable htpasswd authentication
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/openshift-passwd'}]
osm_default_subdomain=apps.myacc.nz

# default project node selector
#osm_default_node_selector='region=primary'

# default selectors for router and registry services
openshift_router_selector='region=infra'
openshift_registry_selector='region=infra'

# host group for masters
[masters]
ose-master.c.ose-31.internal openshift_public_hostname=ose-master.myacc.nz

# host group for nodes, includes region info
[nodes]
ose-master.c.ose-31.internal openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
ose-node1.c.ose-31.internal openshift_node_labels="{'region': 'primary', 'zone': 'north'}"
ose-node2.c.ose-31.internal openshift_node_labels="{'region': 'primary', 'zone': 'south'}"
EOF

-- test facts
ansible-playbook playbooks/byo/openshift_facts.yml
```

**Comment by eformat** [comment]
commenting out this line allows for sdn to install and interfaces and bridge to be configured in gce using byo playbook

roles/openshift_facts/library/openshift_facts.py

line:191-192

    # Default to no sdn for GCE deployments
    facts['use_openshift_sdn'] = False

will give it a test ..

**Comment by detiber** [comment]
@eformat There must be a bug with the way that we are merging facts. I'll investigate further today.

**Comment by detiber** [comment]
still digging into this, ran into some issues when I attempted to spin up a cluster using the bin/cluster script and didn't get far enough to test the SDN configuration.

**Comment by detiber** [comment]
I've created https://github.com/openshift/openshift-ansible/pull/1007 to address this issue (as well as others that I hit when using bin/cluster to deploy to GCE).

If I can get second hand validation of it, I'll go ahead and cleanup the PR and work on getting it merged.

**Comment by eformat** [comment]
will give it a try over next 48hrs .. just on the road at mo ...

**Comment by lypht** [comment]
We have a GCE requirement, so I've been hoping bin/cluster would become stable and we'd be able to gain idempotence.  I was happy to see the updates in #1007, and cloned the branch to test.  However, despite previously being able to attach GCE_PD through PersistentVolumeClaim (unformatted, unattached, and unbound) I am now no longer able: 
**Could not attach GCE PD "docker-registry". Timeout waiting for mount paths to be created**
I haven't altered any other variables.  I'm going to start with a fresh cluster this AM and see if I can reproduce the issue.  As always, thanks for all of the great work on this project!

**Comment by erinboyd** [comment]
In general you have to have the persistent volume claim as BOUND or else it
won't create the mount paths. Do you have both a pv and pvc created?

**Comment by lypht** [comment]
Sorry, I should have been clearer.  Both the pv and pvc are created and point to a clean (unformatted, unattached, not *previously* bound) disc.  Without which the error becomes **PVC not found**.

I attempted to run *bin/cluster create gce 'project_name'* again this morning using the gceFixes branch previously mentioned, and noted in the GCE developer console that, once created, all VMs were issued  **READ ONLY** permissions to the GCE API for the storage layer.  [Modifying the stack for persistent storage](https://docs.openshift.org/latest/install_config/configuring_gce.html) had no effect.

**Comment by detiber** [comment]
@lypht The persistent disk issue sounds like a separate issue to me.

Can you provide the steps you are using to configure the persistent volume, create the registry and attach the pvc to the registry?

Issues that I can think of off the top of my head:
- If the method used to access the volumes is relying on the kubernetes native cloud support, which we aren't currently configuring with openshift-ansible (We do have a PR that sets the generic scaffolding for this, but are only targeting OpenStack in the PR: https://github.com/openshift/openshift-ansible/pull/883)
- If the method used to access the volumes is relying on the host having service_account_permissions set on the node hosts, which we are not currently setting in bin/cluster(and cannot set until we set a hard requirement on ansible 2.0)

On a side note, for infrastructure pods, we are now recommending to attach the volume directly to pods instead of using the pv/pvc mechanism.

**Comment by lypht** [comment]
Noted.  For BYO pre-flight, I run /usr/share/google/safe_format_and_mount, but had only created the disk through the developer console for my test of bin/cluster.  I am able to mount a persistent docker-registry through that method.

**Comment by eformat** [comment]
@detiber - tested your branch #gceFixes OK (sorry for delay !) sdn is properly configured now. thanks

**Comment by eformat** [comment]
@lypht - i just got PD working in GCE .. there are a few things you need to ensure

- in gce, when creating vm instances - set the checkbox - project access: "Allow API access to all Google Cloud services in the same project". this cannot be set after creation !

- don't leave the separate disk mounted on any host after formatting it. OSE will format it as well (although i didn't try this) if unformatted, i did it manually for starters

- when creating and formatting the volume - need to use "-m" with ext4 (default is xfs in google script for RHEL7), else OSE barfs:
```
/usr/share/google/safe_format_and_mount -m "mkfs.ext4 -E lazy_itable_init=0 -F" /dev/sdb /mnt/foo
```
- i ran a mysql db up, needed to make sure file permissions were OK, e.g (for now !)
``` 
chmod 777 /var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/gce-pd/mounts/mysql-1
```
- make sure set fstype in pv create
```
oc create -f - <<EOF
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv0001"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "mysql-1"
EOF
```

**Comment by lypht** [comment]
Thanks @eformat.  I have been working from an ansible playbook that builds the prereqs for the advanced installation, which includes a stanza that adds /mnt/foo to /etc/fstab to ensure the mount point exists at reboot.  From your instruction, however, I gather that you ran *umount* after *safe_format_and_mount* to unattach the PD from the host instance?  

Unfortunately in my use of ansible, libcloud and gce.py, I have yet to come across the arguments to set GCE API access at instance creation.  If using BYO on GCE, I'm assuming you are manually generating these, rather than instantiating them through a script? I've noted that *bin/cluster create gce foo* doesn't add the API access either (aside from the default storage read-only option).  I'll nuke my current stack and build manually, but given the number of GCE projects in which we plan to run Openshift, I'd love to have a one-size-fits-all preflight playbook that creates a standard image for masters, nodes, and infrastructure.

**Comment by eformat** [comment]
yes, manually formatted the disk for starters.

the gce API is accessible from the vm by default (if you give it access *before* creating the vm) 

i too went hunting for auth access args, but they are not required, or there :)

Cheers
Mike

**Comment by lypht** [comment]
Success story: Openshift is working in GCE using BYO, and our developers are autonomously publishing in multiple projects with working github hooks.  Thanks to everyone for their help.

**Comment by akostadinov** [comment]
What permissions should be granted to the service account that is injected into the machines? I don't find it nice to include a service account with access to the whole project... from security standpoint of view.

Ok, maybe I have to explain more. The feature "Allow API access to all Google Cloud services in the same project" I think injects some default service account. But in fact, using the API I don't see such boolean option. I see only this option:
https://cloud.google.com/compute/docs/reference/latest/instances
And setting `serviceAccounts` property with some service account email and allowed scopes. But scope is too vague of a restriction. I think one is better to create a separate GCE service account with permissions only what is required for OpenShift. Is this possible with GCE?
