### ISSUE TITLE
openshift_service_catalog unknown flag --enable-admission-plugins

### ISSUE THREAD

**Issue by kwoodson** [openshift/openshift-ansible#8422]
#### Description

Provide a brief description of your issue here. For example:
When deploying the openshift_service_catalog in 3.10 the container fails.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
Place the output between the code block below:

```
docker.io/openshift/origin-ansible                   v3.10               7f863c6ddd24        About an hour ago   1.12 GB
```

##### Steps To Reproduce
1. Call the openshift_service_catalog role.
2. Verify the docker logs contain the error message:
```
[root@ocp-master-18458924-0 0]# docker logs b9b61da8e4b5
Error: unknown flag: --enable-admission-plugins

The main API entrypoint and interface to the storage system. The API server is
also the focal point for all authorization decisions.
```

##### Expected Results
Describe what you expected to happen.

```
I expect the container to be running normally.
```

##### Observed Results
Describe what is actually happening.

```
The container is failing to start due to an invalid flag.
Error: unknown flag: --enable-admission-plugins
```

##### Additional Information

```
It appears that this flag is no longer supported and needs to be cleaned up.

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_service_catalog/templates/api_server.j2#L46
```

**Comment by kwoodson** [comment]
@jboyd01, It looks like you added this option recently.  Is this working on latest?

```
docker.io/openshift/origin-template-service-broker   v3.10.0             a7c3fdfdce06        About an hour ago   289 MB
```

**Comment by jboyd01** [comment]
@kwoodson  yes, this is working in master.  My guess is you have an older service-catalog image running with a newer OpenShift.  Can you ensure your service-catalog is current, within the last week or so?

The service-catalog API Server and Controller pods both dump the catalog version at the start of their log files, or you can run the image with the -v flag to get the version.
either of these should work if you locate the proper pod for the first, or image id for the 2nd

`oc exec controller-manager-f2q9t  -- /usr/bin/service-catalog controller-manager --version`

`docker run -i -t 8dbd9e392a96 /usr/bin/service-catalog controller-manager --version`
 
You really want to be running v0.1.17 or 0.1.18.

**Comment by kwoodson** [comment]
@jboyd01,

I have torn down this cluster.  This was at the top of the docker logs:

```
[root@ocp-master-18458924-0 0]# docker logs 11ed637d4691
I0517 19:59:21.646576       1 feature_gate.go:184] feature gates: map[OriginatingIdentity:true]
I0517 19:59:21.646718       1 feature_gate.go:184] feature gates: map[OriginatingIdentity:true AsyncBindingOperations:true]
I0517 19:59:21.646767       1 hyperkube.go:188] Service Catalog version v3.10.0-alpha.0+f39971f-532 (built 2018-04-05T15:24:08Z)
```
I will redeploy and get back to this.  Is it possible our image on docker hub is out of date?

**Comment by jboyd01** [comment]
Yeah, v3.10.0 is old (I'd like to say really old, but its all relative) and definitely not compatible with current OpenShift builds which are starting catalog apiserver with the newish flag `--enable-admission-plugins`.

Sorry for the issues, upstream introduced this breaking change and we didn't realize it until it was too late to make it a non-breaking flag change.

**Comment by kwoodson** [comment]
@jboyd01,

Looks like 3.10.0 was updated 4 hours ago.  Does this reference the correct version? 
https://hub.docker.com/r/openshift/origin-pod/tags/

**Comment by jpeeler** [comment]
For the record, the catalog images are here:
https://hub.docker.com/r/openshift/origin-service-catalog/tags/

For origin, v0.1 is the latest release.
