### ISSUE TITLE
Configure network?

### ISSUE THREAD

**Issue by dakky** [openshift/openshift-ansible#843]
Is it possible to configure the network settings used by the ansible installer? The preconfigured are colliding with my lokal network :(

**Comment by detiber** [comment]
@dakky Which network settings do you mean? 

Assuming you mean the service network (portal_net):
If using inventory/byo/hosts.example as a guide, under [OSEv3:vars]:
```
openshift_master_portal_net: 10.254.0.0/16
```

For the network used by openshfit_sdn:
```
osm_cluster_network_cidr: 10.252.0.0/16 
osm_host_subnet_length: 8
```
In the above, osm_host_subnet_length is the subnet length (in bits) to be assigned to each node that is a member of the cluster.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
