### ISSUE TITLE
Installation openshift 3.9 failed using ansible

### ISSUE THREAD

**Issue by camjoex** [openshift/openshift-ansible#8433]
#### Description
Hello 

I'm trying to install openshift 3.9 with 3 Master / 3 Etcd / 2 Nodes with openshift-ansible release-3.9.
Task playbook seems ok until "Service Catalog Install"

```
Installer status
*************
Initialization             : Complete (0:03:55)
Health Check               : Complete (0:00:54)
etcd Install               : Complete (0:01:19)
Master Install             : Complete (0:03:00)
Master Additional Install  : Complete (0:00:24)
Node Install               : Complete (0:01:43)
Hosted Install             : Complete (0:32:07)
Web Console Install        : Complete (0:00:38)
Service Catalog Install    : FAILED

  1. Hosts:    oc-master1
     Play:     Service Catalog
     Task:     Label com5sctnt601 for APIServer and controller deployment
     Message:  {u'cmd': u'/usr/bin/oc label node com5sctnt601 node-role.kubernetes.io/master=true --overwrite', u'returncode': 1, u'results': {}, u'stderr': u'Error from server (NotFound): nodes "com5sctnt601" not found\n', u'stdout': u''}
```

On master, i have problem when i'm trying to list node
```
Unable to connect to the server: x509: certificate is valid for com5sctnt601, dev.openshift, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, openshift, openshift.default, openshift.default.svc, openshift.default.svc.cluster.local, 1.1.0.21, 172.30.0.1, not oc-master1
```
Hostfile Ansible
```
[masters]
oc-master[1:3]

[etcd]
etcd-node[1:3]

[nodes]
oc-node[1:2]
```
Label com5sctnt601 and oc-master1 are identically ip

Any idea for help ?
Thank you

**Comment by vrutkovs** [comment]
This report contains 2 different report - wrong certs for nodes and service catalog issue.
Also, in 3.9 all masters need to be listed as nodes.

Please open new tickets, including full inventory and the output of `ansible-playbook -vvv`. Don't forget to specify which repos, install type and openshift-ansible branch / commit you are using

**Comment by camjoex** [comment]
Thank you i solve my firt problem certificat by generating another and purge content file .kube/config an regenerate playbook
