### ISSUE TITLE
Where is openshift/origin-node v3.9?

### ISSUE THREAD

**Issue by lomori** [openshift/openshift-ansible#8437]
Trying to install Origin locally but install fails when it can't pull that image.

**Comment by vrutkovs** [comment]
Use `release-3.9` to install 3.9 (it would use `openshift/node`), it won't work with master.

**Comment by lomori** [comment]
/open
 I'm using release-3.9.

**Comment by vrutkovs** [comment]
What's the output of `ansible-playbook -vvv` then? 3.9 branch should use `openshift/node` instead

**Comment by lomori** [comment]
Humm, what is the best way to do it? Tried an attachment but it bounced back. The output has 78K+ lines, 5MB uncompressed.
Regards,Luiz
    On Friday, May 18, 2018, 11:04:32 AM EDT, Vadim Rutkovsky <notifications@github.com> wrote:  
 
 
What's the output of ansible-playbook -vvv then? 3.9 branch should use openshift/node instead

**Comment by vrutkovs** [comment]
gist.github.com should probably work. A tar.gz with logs is okay too

**Comment by lomori** [comment]
...and  I'm on RHEL 7 server with atomic package installed through yum and trying to install containerized=true.

  Humm, what is the best way to do it? Tried an attachment but it bounced back. The output has 78K+ lines, 5MB uncompressed.
The error:
TASK [openshift_node : Pre-pull node image when containerized] ********************************************************************************************************************************************************************************************task path: /home/cats_dev/openshift-ansible/roles/openshift_node/tasks/install.yml:21Friday 18 May 2018  11:26:06 -0400 (0:00:00.156)       0:12:17.413 ************ Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py<vlt-catskube01.dhe.duke.edu> ESTABLISH SSH CONNECTION FOR USER: cats_dev<vlt-catskube01.dhe.duke.edu> SSH: EXEC sshpass -d11 ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o User=cats_dev -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r vlt-catskube01.dhe.duke.edu '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-xueljahmwqnpyjtfscnuzzyztucwmkzm; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''Escalation succeeded<vlt-catskube01.dhe.duke.edu> (1, '\n{"changed": true, "end": "2018-05-18 11:26:07.676038", "stdout": "Trying to pull repository registry.access.redhat.com/openshift/origin-node ... \\nTrying to pull repository docker.io/openshift/origin-node ... ", "cmd": ["docker", "pull", "openshift/origin-node:v3.9.0"], "failed": true, "delta": "0:00:00.929484", "stderr": "manifest for docker.io/openshift/origin-node:v3.9.0 not found", "rc": 1, "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": false, "_raw_params": "docker pull openshift/origin-node:v3.9.0", "removes": null, "creates": null, "chdir": null, "stdin": null}}, "start": "2018-05-18 11:26:06.746554", "msg": "non-zero return code"}\n', '')fatal: [vlt-catskube01.dhe.duke.edu]: FAILED! => {    "changed": false,     "cmd": [        "docker",         "pull",         "openshift/origin-node:v3.9.0"    ],     "delta": "0:00:00.929484",     "end": "2018-05-18 11:26:07.676038",     "invocation": {        "module_args": {            "_raw_params": "docker pull openshift/origin-node:v3.9.0",             "_uses_shell": false,             "chdir": null,             "creates": null,             "executable": null,             "removes": null,             "stdin": null,             "warn": true        }    },     "msg": "non-zero return code",     "rc": 1,     "start": "2018-05-18 11:26:06.746554",     "stderr": "manifest for docker.io/openshift/origin-node:v3.9.0 not found",     "stderr_lines": [        "manifest for docker.io/openshift/origin-node:v3.9.0 not found"    ],     "stdout": "Trying to pull repository registry.access.redhat.com/openshift/origin-node ... \nTrying to pull repository docker.io/openshift/origin-node ... ",     "stdout_lines": [        "Trying to pull repository registry.access.redhat.com/openshift/origin-node ... ",         "Trying to pull repository docker.io/openshift/origin-node ... "    ]}



Regards,Luiz
    On Friday, May 18, 2018, 11:04:32 AM EDT, Vadim Rutkovsky <notifications@github.com> wrote:  
 
 
What's the output of ansible-playbook -vvv then? 3.9 branch should use openshift/node instead

**Comment by lomori** [comment]
Here it is. See attached.
    On Friday, May 18, 2018, 11:39:19 AM EDT, Vadim Rutkovsky <notifications@github.com> wrote:  
 
 
gist.github.com should probably work. A tar.gz with logs is okay too
