### ISSUE TITLE
Openshift after upgrading from 3.7 to 3.9 failed to run my own micro-services due to manifist not found.

### ISSUE THREAD

**Issue by atiato** [openshift/openshift-ansible#8440]
#### Description

when I Upgrade my openshift origin cluster from 3.7 to 3.9 using :

ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade.yml

Everything went successful except that all my pods that i had deployed on 3.7 origin isn't up due to manifist not found , can't find images although images are available on docker.

Docker registry and router pods (v3.9.0) are available (running fine) .

![image](https://user-images.githubusercontent.com/652472/40245688-037d77ee-5acf-11e8-8298-396eeb493f13.png)

my hosts file 

[OSEv3:children]
nodes
nfs
masters
etcd

[OSEv3:vars]
openshift_master_cluster_public_hostname=None
openshift_master_default_subdomain=apps.172.20.10.3.nip.io
ansible_ssh_user=root
openshift_master_cluster_hostname=None
openshift_override_hostname_check=true
deployment_type=origin
openshift_hosted_etcd_storage_kind=nfs
openshift_hosted_etcd_storage_nfs_options="*(rw,root_squash,sync,no_wdelay)"
openshift_hosted_etcd_storage_nfs_directory=/var/nfs-data/pv01
openshift_hosted_etcd_storage_volume_name=etcd-vol2
openshift_hosted_etcd_storage_access_modes=["ReadWriteOnce"]
openshift_hosted_etcd_storage_volume_size=1G
openshift_hosted_etcd_storage_labels={'storage': 'etcd'}
openshift_enable_service_catalog=false
template_service_broker_install=false
#openshift_dns_ip=8.8.8.8
#openshift_use_dnsmasq=true
#enable_docker_excluder=false
#enable_openshift_excluder=false
openshift_node_kubelet_args={'pods-per-core': ['100'], 'max-pods': ['600'], 'image-gc-high-threshold': ['90'], 'image-gc-low-threshold': ['80']}

[nodes:vars]
openshift_disable_check=disk_availability,memory_availability,docker_storage,docker_image_availability,package_availability,package_version

[masters:vars]
openshift_disable_check=disk_availability,memory_availability,docker_storage,docker_image_availability,package_availability,package_version

[nodes]
172.20.10.3  openshift_public_ip=172.20.10.3 openshift_ip=172.20.10.3 openshift_public_hostname=ocp1.172.20.10.3.nip.io openshift_hostname=ocp1.172.20.10.3.nip.io connect_to=172.20.10.3 ansible_connection=local
172.20.10.4  openshift_public_ip=172.20.10.4 openshift_ip=172.20.10.4 openshift_public_hostname=ocp2.172.20.10.4.nip.io openshift_hostname=ocp2.172.20.10.4.nip.io connect_to=172.20.10.4 openshift_node_labels="{'region': 'infra'}" openshift_schedulable=True
172.20.10.5  openshift_public_ip=172.20.10.5 openshift_ip=172.20.10.5 openshift_public_hostname=ocp3.172.20.10.5.nip.io openshift_hostname=ocp3.172.20.10.5.nip.io connect_to=172.20.10.5 openshift_node_labels="{'region': 'infra'}" openshift_schedulable=True

[nfs]
172.20.10.3 connect_to=172.20.10.3 ansible_connection=local

[masters]
172.20.10.3  openshift_public_ip=172.20.10.3 openshift_ip=172.20.10.3 openshift_public_hostname=ocp1.172.20.10.3.nip.io openshift_hostname=ocp1.172.20.10.3.nip.io connect_to=172.20.10.3 ansible_connection=local

[etcd]
172.20.10.3  openshift_public_ip=172.20.10.3 openshift_ip=172.20.10.3 openshift_public_hostname=ocp1.172.20.10.3.nip.io openshift_hostname=ocp1.172.20.10.3.nip.io connect_to=172.20.10.3 ansible_connection=local

**Comment by vrutkovs** [comment]
It seems the registry is not accessible from the pod.

Is `docker-registry` running in `default` namespace? Is `docker-registry.default.svc,cluster.local` resolvable from other pods? Does `/etc/resolv.conf` has `search cluster.local` on all nodes?

**Comment by atiato** [comment]
I'm able to curl docker registry from master and all nodes see snapshot:

![image](https://user-images.githubusercontent.com/652472/40267699-0d8c67a4-5b6a-11e8-8128-39d2e302a107.png)

**Comment by atiato** [comment]
![image](https://user-images.githubusercontent.com/652472/40297392-5dc0293e-5ce8-11e8-8b8a-3423db6e3035.png)

looks like my metadata for micro-services are saved inside ephemeral place so when Docker registry for 3.7 been replaced by docker registry 3.9 , all my images information has been disappeared .

I will simulate the case and let you know , Can you confirm this ?

Thanks,
Omar Atia

**Comment by vrutkovs** [comment]
>when Docker registry for 3.7 been replaced by docker registry 3.9 , all my images information has been disappeared 

Yes, the registry seems to run, but since it was not backed by a persistent storage it was replaced by an empty registry during upgrade

**Comment by atiato** [comment]
I have added persistent storage to docker registry using the following command :  
1- create volume then claim it in default name space : 
![image](https://user-images.githubusercontent.com/652472/40405588-eb33f38a-5e65-11e8-98a2-cdac61ec810c.png)

oc volume dc/docker-registry --add --overwrite -t persistentVolumeClaim --claim-name=nfs-pvc --name=registry-storage

then docker registry has been automatically re-deployed with new storage .
