### ISSUE TITLE
3.9.x installation tries to  pull recycler:v1.9.1

### ISSUE THREAD

**Issue by ctron** [openshift/openshift-ansible#8477]
#### Description

Provide a brief description of your issue here. For example:

OpenShift Origin tries to pull the wrong recycler version:

~~~
May 22 16:53:48 host origin-node[2092]: E0522 16:53:48.671970    2092 remote_image.go:108] PullImage "openshift/origin-recycler:v1.9.1" from image service failed: rpc error: code = Unknown desc = manifest for docker.io/openshift/origin-recycler:v1.9.1 not found
May 22 16:53:48 host origin-node[2092]: E0522 16:53:48.672050    2092 kuberuntime_image.go:50] Pull image "openshift/origin-recycler:v1.9.1" failed: rpc error: code = Unknown desc = manifest for docker.io/openshift/origin-recycler:v1.9.1 not found
~~~

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

Place the output between the code block below:

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jreimann/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]


oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

```

##### Steps To Reproduce
1. Install OpenShift 3.9.x

##### Expected Results
Describe what you expected to happen.

It should pull the correct version.

##### Observed Results
Describe what is actually happening.

It pulls the wrong version. Which does not exist.

**Comment by touchardv** [comment]
I also have the same issue: a fresh installation of 3.9 on CentOS.
Initially I though that was the Docker registry proxy that was wrong, but indeed, a non-existing Docker image is being pulled without success.

**Comment by touchardv** [comment]
This issue is not related to the Ansible scripts. See https://bugzilla.redhat.com/show_bug.cgi?id=1550372

**Comment by nemonik** [comment]
I'm seeing the same problem

Openshift repeatedly tries to pull 

 openshift/origin-recycler:v1.9.1

to recycle my nfs PVs.

**Comment by touchardv** [comment]
Well, for now, I think: don't use the "Recycle" persistent volume reclaim policy. At least until a new version of the RPMs is published with the fix.

**Comment by jfchevrette** [comment]
I have the same issue and I could not find a way to tell openshift to use image tag 'v3.9' instead. I need the Recycle policy because I use NFS volumes.

**Comment by disappear89** [comment]
As workaround you can set on your masters the environment variable: `OPENSHIFT_RECYCLER_IMAGE="openshift/origin-recycler:v3.9"`
Example for centos:
`echo 'OPENSHIFT_RECYCLER_IMAGE="openshift/origin-recycler:v3.9"' >> /etc/sysconfig/origin-master-controllers && systemctl restart origin-master-controllers.service`

**Comment by hhellbusch** [comment]
thanks @disappear89  - workaround worked for me!

**Comment by prrabbhanjon** [comment]
issue: mple.com   Failed to pull image "registry.lab.example.com/openshift3/ose-recycler:v1.9.1": rpc error: code = Unknown desc = Error: image openshift3/ose-recycler:v1.9.1 not found
44m       44m       1         recycler-for-metrics.1630f523eb2d2df8   Pod  


I was trying to redeployed as below troubleshooting:

100% of problem the pv created file.

pv file must be named as.

step 1: (uninstall when you failed the deployment using "-e openshift_metrics_install_metrics=False"
Make sure all deployment configuratons/build files to be deleted as same.

step 2:

apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics (name must be given file) 
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: services.lab.example.com
    path: /OSE_metrics


oc create -f metric-pv.yaml

step 3:
vi inventory

[OSEv3:vars]
oreg_url=registry.lab.example.com/openshift3/ose-${component}:${version}
openshift_examples_modify_imagestreams=true
openshift_docker_additional_registries=registry.lab.example.com
openshift_docker_blocked_registries=registry.access.redhat.com,docker.io
openshift_web_console_prefix=registry.lab.example.com/openshift3/ose-
openshift_cockpit_deployer_prefix='registry.lab.example.com/openshift3/'
openshift_service_catalog_image_prefix=registry.lab.example.com/openshift3/ose-
template_service_broker_prefix=registry.lab.example.com/openshift3/ose-
ansible_service_broker_image_prefix=registry.lab.example.com/openshift3/ose-
ansible_service_broker_etcd_image_prefix=registry.lab.example.com/rhel7/

step 4:
sudo ansible-playbook  -i  inventory usr/share/ansible/openshift-ansible/playbooks/openshift-metrics/config.yml  -e openshift_metrics_image_version=v3.9 -e openshift_metrics_heapster_requests_memory=300M -e openshift_metrics_hawkular_requests_memory=750M -e  openshift_metrics_cassandra_requests_memory=750M -e openshift_metrics_cassandra_storage_type=pv -e openshift_metrics_cassandra_pvc_prefix=cassandra -e openshift_metrics_cassandra_pvc_size=5Gi -e openshift_metrics_install_metrics=True -e openshift_metrics_image_prefix=registry.lab.example.com/openshift3/ose-
issue fixed here the steps: 


[student@workstation ~]$ oc get po
NAME                         READY     STATUS    RESTARTS   AGE
hawkular-cassandra-1-5ff6d   1/1       Running   0          4m
hawkular-metrics-fhsp5       1/1       Running   0          4m
heapster-pjpcs               1/1       Running   0          4m


please make sure given pv's inputs were problem, make sure given filename and name of the pv should be same. if not you will get the error "belet, node1.lab.example.com   Failed to pull image "registry.lab.example.com/openshift3/ose-recycler:v1.9.1": rpc error: code = Unknown desc = Error: image openshift3/ose-recycler:v1.9.1 not found"
