### ISSUE TITLE
Upgrade from 3.6 to 3.7 fails draining node

### ISSUE THREAD

**Issue by AndreaFerraresi** [openshift/openshift-ansible#8478]
#### Description

When running `playbooks/byo/openshift-cluster/upgrades/v3_7/upgrade.yml` process fails with the following error 

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version` 2.5.2

If you're operating from a **git clone**:

* The output of `git describe`:

```
openshift-ansible-3.7.48-1-12-g012dd4b8a
```
##### Steps To Reproduce
1. Ansible-playbook -I inventory.cfg playbooks/byo/openshift-cluster/upgrades/v3_7/upgrade.ym

##### Observed Results
Describe what is actually happening.

```
TASK [Drain Node for Kubelet upgrade] *******************************************************************************************************************************************************************************
Tuesday 22 May 2018  16:52:19 +0200 (0:00:01.586)       0:05:48.641 ***********
FAILED - RETRYING: Drain Node for Kubelet upgrade (1 retries left).
fatal: [masterip]: FAILED! => {"attempts": 1, "changed": true, "cmd": ["oadm", "adm", "drain", "masterip", "--config=/etc/origin/master/admin.kubeconfig", "--force", "--delete-local-data", "--ignore-daemonsets", "--timeout=0s"], "delta": "0:00:00.173678", "end": "2018-05-22 14:52:26.446996", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2018-05-22 14:52:26.273318", "stderr": "Error: unknown command \"adm\" for \"oadm\"\nRun 'oadm --help' for usage.", "stderr_lines": ["Error: unknown command \"adm\" for \"oadm\"", "Run 'oadm --help' for usage."], "stdout": "", "stdout_lines": []}
```

For long output or logs, consider using a [gist](https://gist.github.com/)

*I think it should be oc adm not oadm adm*

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* CentOS Linux release 7.4.1708 (Core)

```
 Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
etcd
new_nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# Setting the clusterID would make 3.7 works smooth
openshift_clusterid="name"

# Specify the deployment type. Valid values are origin and openshift-enterprise
deployment_type=origin

# Specify the generic release of OpenShift to install
openshift_release=v3.7
openshift_image_tag=v3.7.2
openshift_pkg_version="-3.7.2"

# Configure master API and console ports
openshift_master_api_port=443
openshift_master_console_port=443

# AWS
openshift_cloudprovider_kind=aws

# default project node selector
osm_default_node_selector='region=primary'

[masters]
masterip
# host group for etcd
[etcd]
masterip

# host group for nodes, includes region info
[nodes]
masterip openshift_node_labels="{'region': 'master'}"
infranodeip openshift_node_labels="{'region': 'infra'}"
nodeipl openshift_node_labels="{'region': 'primary'}"

[new_nodes]```

**Comment by DanyC97** [comment]
@AndreaFerraresi i've just pushed https://github.com/openshift/openshift-ansible/pull/8428 but there is no 3.7 release being cut recently which includes it

**Comment by DanyC97** [comment]
wait, looking again in your output i see 
```
"cmd": ["oadm", "adm", "drain", "masterip", "--config=/etc/origin/master/admin.kubeconfig", "--force", "--delete-local-data", "--ignore-daemonsets", "--timeout=0s"]
```

but that code only got merged a day ago so no way you can have that in the release `openshift-ansible-3.7.48-1-12-g012dd4b8a` ...very confused

**Comment by AndreaFerraresi** [comment]
@DanyC97 I am very confused as well, seems that the `openshift.common.admin_binary` wasn't set to oc but to oadm on my installation. (I haven't perform the installation, so can't exactly tell what happened) to workaround the problem I modified `playbooks/common/openshift-cluster/upgrade_control_plane.yaml` line 410 to remove `adm` and I was able to go forward. 
Therefore other colleagues did not experienced the problem on other updates, which is even more confusing. 

Thanks, 
Andrea

**Comment by DanyC97** [comment]
can you please do a `git log --oneline -n 5` from within the `openshift-ansible` directory?

**Comment by AndreaFerraresi** [comment]
```
328968935 (HEAD -> release-3.6, tag: openshift-ansible-3.6.173.0.120-1, origin/release-3.6) Automatic commit of package [openshift-ansible] release [3.6.173.0.120-1].
6a8726fa1 Merge pull request #8429 from DanyC97/upgrade-drain-timeout-36
1be2f79b6 Add the ability to specify a timeout for node drain operations
5a90238c3 Merge pull request #8405 from vrutkovs/3.6-force-hardlinks
d9a21a83c Force creating hard- and softlinks
```

**Comment by DanyC97** [comment]
right @AndreaFerraresi , you running 3.6 and not 3.7 ...

**Comment by DanyC97** [comment]
hmm, i'll try to go over an upgrade myself this weekend if times allows

@vrutkovs @michaelgugino  you have any thoughts ? 

looking in 3.7 branch [here](https://github.com/openshift/openshift-ansible/blob/release-3.7/playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml#L37) we have 

`{{ hostvars[groups.oo_first_master.0].openshift.common.admin_binary }} drain {{ openshift.node.nodename | lower }}`

since i changed it ;) 

and compare that with 3.9 i see [here](https://github.com/openshift/openshift-ansible/blob/release-3.9/playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml#L36) we have

`{{ hostvars[groups.oo_first_master.0]['first_master_client_binary'] }} adm drain {{ openshift.node.nodename | lower }}`

how is different `first_master_client_binary` from `openshift.common.admin_binary` ?

**Comment by vrutkovs** [comment]
@DanyC97 good catch, probably the facts are picking a wrong binary for `oadm`

@AndreaFerraresi could you check which `admin_binary` is stored in the facts?
`fgrep "admin_binary" $HOME/ansible/facts/*` would show that

**Comment by DanyC97** [comment]
on my 3.7 i get

```
fgrep "admin_binary" $HOME/ansible/facts/*
/root/ansible/facts/master01:            "admin_binary": "oadm"

```

which one you have @AndreaFerraresi ?

**Comment by AndreaFerraresi** [comment]
@DanyC97 @vrutkovs I don't have that folder actually

**Comment by DanyC97** [comment]
are you going to close this issue then @AndreaFerraresi ? 

(and thanks for raising the issue and being patient with us ;) )
