### ISSUE TITLE
Ubuntu 16.04 compatility

### ISSUE THREAD

**Issue by stecanu** [openshift/openshift-ansible#8500]
Hi guys,

Anyone was able to run openshift-ansible in unbuntu? i walk through .yml file and i noticed that some package name are only available for centos/fedora distribution, in ubuntu they have others name.

thanks

**Comment by vrutkovs** [comment]
Ubuntu / Debian OS are currently not supported, see https://docs.openshift.org/latest/install_config/install/prerequisites.html

**Comment by stecanu** [comment]
HI vrutkovs,

i just seen some seconds before your answer, buy the way i was able to run oc origin in ubuntu with the standard installation from github, so the limit is only for the advanced installation with ansible?

thanks
