### ISSUE TITLE
Openshift upgrade playbook sets different versions for master and nodes

### ISSUE THREAD

**Issue by ksemaev** [openshift/openshift-ansible#8516]
#### Description

Typical automated update from v3.7 to v3.8 installs v3.9 on nodes

##### Version
oc version
oc v3.8.0+dd1558c-1
kubernetes v1.8.5+440f8d36da
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://opsmaster.elpass:8443
openshift v3.8.0+dd1558c-1
kubernetes v1.8.5+440f8d36da

##### Steps To Reproduce
1. My inventory is:

```
cat /etc/ansible/hosts
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
glusterfs
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
openshift_release=v3.8
#ansible_ssh_user=root

openshift_metrics_install_metrics=false
openshift_metrics_image_version=v3.8.0
openshift_hosted_metrics_deployer_version=v3.8.0
openshift_metrics_hawkular_hostname=metrics.elpass
openshift_metrics_cassandra_storage_type=dynamic
openshift_metrics_start_cluster=true
openshift_metrics_duration=1
openshift_metrics_cassandra_pvc_size=6Gi
openshift_metrics_cassandra_pvc_prefix=cassandra
openshift_metrics_project=openshift-infra
openshift_metrics_cassanda_pvc_storage_class_name=glusterfs-storage
openshift_metrics_hawkular_limits_memory=4G

openshift_docker_options="--log-driver json-file"

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become=true
openshift_deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# host group for masters
[masters]
opsmaster.elpass

# host group for etcd
[etcd]
opsmaster.elpass

# host group for nodes, includes region info
[nodes]
opsmaster.elpass
opsnode01.elpass openshift_node_labels="{'region': 'primary', 'dedicate': 'app' }"
opsnode02.elpass openshift_node_labels="{'region': 'primary', 'dedicate': 'app', 'develop': 'dev' }"
opsnode03.elpass openshift_node_labels="{'region': 'infra', 'dedicate': 'app' }"
opsnode04.elpass openshift_node_labels="{'region': 'infra' }"


[glusterfs]
opsnode01.elpass glusterfs_ip=192.168.120.211 glusterfs_devices='[ "/dev/sdc" ]'
opsnode02.elpass glusterfs_ip=192.168.120.212 glusterfs_devices='[ "/dev/sdc" ]'
opsnode03.elpass glusterfs_ip=192.168.120.213 glusterfs_devices='[ "/dev/sdc" ]'
opsnode04.elpass glusterfs_ip=192.168.120.214 glusterfs_devices='[ "/dev/sdc" ]'
```

2. Run typical upgrade:
` ansible-playbook playbooks/byo/openshift-cluster/upgrades/v3_8/upgrade.yml -e openshift_disable_check=disk_availability,memory_availability`

##### Expected Results
 oc get nodes
NAME               STATUS                     ROLES     AGE       VERSION
opsmaster.elpass   Ready,SchedulingDisabled   <none>    293d      v1.8.5+440f8d36da
opsnode01.elpass   Ready                      <none>    266d      v1.8.5+440f8d36da
opsnode02.elpass   Ready                      <none>    266d      v1.8.5+440f8d36da
opsnode03.elpass   Ready                      <none>    266d      v1.8.5+440f8d36da
opsnode04.elpass   Ready                      <none>    104d      v1.8.5+440f8d36da

##### Observed Results
```
 oc get nodes
NAME               STATUS                     ROLES     AGE       VERSION
opsmaster.elpass   Ready,SchedulingDisabled   <none>    293d      v1.8.5+440f8d36da
opsnode01.elpass   Ready                      <none>    266d      v1.9.1+a0ce1bc657
opsnode02.elpass   Ready                      <none>    266d      v1.9.1+a0ce1bc657
opsnode03.elpass   Ready                      <none>    266d      v1.9.1+a0ce1bc657
opsnode04.elpass   Ready                      <none>    104d      v1.9.1+a0ce1bc657
```

##### Additional Information

Is it even OK to have different versions of master and nodes?

**Comment by vrutkovs** [comment]
openshift-ansible follows OSE policy, where 3.8 is a transitional point between 3.7 and 3.9 and used only during install.

So the playbooks for 3.8 upgrade (in `release-3.8` branch) were probably not updated

**Comment by ksemaev** [comment]
@vrutkovs  Please tell - where can I read about this OSE policy regarding Openshift? You are saying that I shouldnot use version 3.8 and update from 3.7 to 3.9 (through transition via 3.8)?

**Comment by DanyC97** [comment]
@vrutkovs why you think the issue is valid ? does this happen when running upgrade from 3.7 to 3.9  or is it just on _green deployment_ which is a user error since it shouldn't happened ?

**Comment by ksemaev** [comment]
@DanyC97 it is not a user error. Since we have playbook that upgrades from 3.7 to 3.8 - it should upgrade to 3.8.
Either upgrade both nodes and masters to same version

**Comment by vrutkovs** [comment]
>does this happen when running upgrade from 3.7 to 3.9

This happens only when 3.7 -> 3.8 is being upgraded. Its not supported in OSE, so playbooks in `release-3.8` branch were neglected. I don't mind approving a PR which fixes that though.

**Comment by ksemaev** [comment]
@vrutkovs my main question is - can I leave cluster in that state where masters and nodes are different versions? 
Upgrade to 3.9 requires ansible 2.4.3.x which is not avaliable in centos official repos, and I do not want to install something in production with pip)

**Comment by vrutkovs** [comment]
>my main question is - can I leave cluster in that state where masters and nodes are different versions?

Its fine to have master version `n` and nodes `n-1` version, but the reverse is not supported and dangerous.

>Upgrade to 3.9 requires ansible 2.4.3.x which is not avaliable in centos official repos

Correct, extras were not yet updated. You might want to enable EPEL to install a newer version (2.5.2 might work, but 2.4.3 is recommended)

**Comment by ksemaev** [comment]
@vrutkovs Thank you for responce! If correction of playbooks is not planned - please close the issue

**Comment by DanyC97** [comment]
@ksemaev sorry but i personally disagree with 

> Since we have playbook that upgrades from 3.7 to 3.8 - it should upgrade to 3.8.

because as @vrutkovs said, it happens 

> only when 3.7 -> 3.8 is being upgraded

which nobody should go to, 3.8 should just be transient stage hence my disagreement.

**Comment by ksemaev** [comment]
@DanyC97 I understand your position. Hers is mine: if something is nobody should do - don't make playbook for it. If you do have playbook for something - make it work properly

Regarding this situation - we need either to remove upgrade_to_v3_8 version directory in repo (with moving all functional to upgrade_to_v3_8 version directory), so nobody would do this upgrade. Or make it upgrade masters and nodes to same version.

Now we have playbook in repo, which works wrong, and that is bad)
