### ISSUE TITLE
Installer does not configure vsphere cloudprovider in master service

### ISSUE THREAD

**Issue by dav1x** [openshift/openshift-ansible#8528]
#### Description
 Installer does not configure vsphere cloudprovider in master service

##### Version
3.10

Please put the following version information in the code block
indicated below.

* The output of `git describe`

```
openshift-ansible-3.10.0-0.50.0-71-ga1c263f3a
```

##### Steps To Reproduce
1. vSphere installation with cloud provider
2. Nodes are configured but master is not (this was previously done in a master role that was removed

##### Expected Results
Describe what you expected to happen.

Dynamic provisioning to work properly.

##### Observed Results
Dynamic provisioning is not working properly.

##### Additional Information

https://bugzilla.redhat.com/show_bug.cgi?id=1572873

**Comment by mtnbikenc** [comment]
Fixed by #8530
