### ISSUE TITLE
Upgrade fails: 'dict object' has no attribute 'master'

### ISSUE THREAD

**Issue by rosseland** [openshift/openshift-ansible#853]
Installed using mutimaster/multietcd hosts similar to the one from https://docs.openshift.org/latest/install_config/install/advanced_install.html#multi-master-multi-etcd-multi-node. 
And the cluster is running fine on 1.0.7
So trying to upgrade to 1.0.8:

ansible-playbook playbooks/adhoc/upgrades/upgrade.yml then fails with 

TASK: [Generate etcd backup] ************************************************** 
fatal: [openshift-etcd-01] => One or more undefined variables: 'dict object' has no attribute 'master'
fatal: [openshift-etcd-02] => One or more undefined variables: 'dict object' has no attribute 'master'
fatal: [openshift-etcd-03] => One or more undefined variables: 'dict object' has no attribute 'master'

**Comment by abutcher** [comment]
Looks like this is related to #850

**Comment by dgoodwin** [comment]
Yes sorry, this is my mistake yesterday, I didn't test a late change in a PR during review properly. Fixed in PR #850.

**Comment by abutcher** [comment]
@dgoodwin Trying this out and with #850 etcd_data_dir is only being set on masters

**Comment by abutcher** [comment]
@brenton Please close - fixed in #893
