### ISSUE TITLE
azure: launch.yml playbook in master should use unstable scripts

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-ansible#8535]
around line https://github.com/openshift/openshift-ansible/blob/master/playbooks/azure/openshift-cluster/launch.yml#L30
yedit should set to use the unstable scripts

a separate PR needed for the release-3.9 branch to hard code the 3.9 scripts

ideally start a document indicating what things need to be fixed up when we branch (I can now think of two things: this, and also the group_vars RPM repo references)

**Comment by jim-minter** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_azure/15 is an example failure because of this

**Comment by kwoodson** [comment]
doc here: https://docs.google.com/document/d/1_LkfO2SxzMI83QY0ivW5cZE2GidYTnKKFwrJv28CnjA/edit

PR here: https://github.com/openshift/openshift-ansible/pull/8536

**Comment by kwoodson** [comment]
release-3.9 here: https://github.com/openshift/openshift-ansible/pull/8537

**Comment by jim-minter** [comment]
sorry, I was unclear, by doc I meant a section in a README under playbooks/azure
