### ISSUE TITLE
"No module named yum" on fedora23

### ISSUE THREAD

**Issue by chmouel** [openshift/openshift-ansible#855]
On fresh Fedora 23 install I am getting : 

<pre>
TASK: [openshift_facts | Ensure python-netaddr and PyYaml are installed] ******
failed: [master.local.openshift.chmouel.com] => (item=python-netaddr,PyYAML) => {"failed": true, "item": "python-netaddr,PyYAML", "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1447167427.32-7785535173678/yum", line 27, in <module>
    import yum
ImportError: No module named yum
OpenSSH_7.1p1, OpenSSL 1.0.2d-fips 9 Jul 2015
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to master.local.openshift.chmouel.com closed.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/config.retry

localhost                  : ok=6    changed=0    unreachable=0    failed=0
master.local.openshift.chmouel.com : ok=5    changed=0    unreachable=0    failed=1

root@master:~/openshift-ansible$
</pre>

**Comment by chmouel** [comment]
workaroundL: ```dnf install yum``` would 'fix' it

**Comment by detiber** [comment]
@chmouel unfortunately, we may just need to add dnf install yum to the prereqs in the README for now unless we can get the community to contribute a proper fix for conditionalizing the package installation steps to use dnf if on fedora and yum on centos7 and rhel7.

@abutcher if you are looking for other tasks, this one may be a candidate.

**Comment by chmouel** [comment]
yep i was guessing so :( There was other things to do as well we need to
prereq python-dnf too and that was to install as well on the nodes (not
sure if that could be done directly from ansible)  after that the install
seemed to install until I hitted bug
https://github.com/openshift/origin/issues/5828

**Comment by abutcher** [comment]
@detiber with ansible 2.0 we could use the package module https://docs.ansible.com/ansible/package_module.html

**Comment by detiber** [comment]
@abutcher without knowing when 2.0 is going to be released or what issues we'll run into for 2.0 compatibility, I wonder how well the package_module would work using 1.9...  we might be able to just ship the package_module in our repo as a workaround until we can fully support 2.0

**Comment by detiber** [comment]
https://github.com/openshift/openshift-ansible/pull/966

**Comment by detiber** [comment]
@brenton this issue can now be closed

**Comment by stevekuznetsov** [comment]
If anyone else is popping into this from Google -- `dnf install yum` is *not* always going to fix this issue. If Ansible is using a non-standard Python interpreter like it would in a `virtualenv`, you need `yum` in your `setup.py` for it to be available.

See: http://stackoverflow.com/a/36138921

**Comment by detiber** [comment]
@stevekuznetsov are you actually hitting this? This should be using dnf for Fedora.

**Comment by stevekuznetsov** [comment]
@detiber I'm hitting this in my Ansible bits, not in the `openshift-ansible` code -- but this is among the highest hits on Google if the error message is searched, so I figured it would be helpful to have some better info here.

**Comment by detiber** [comment]
@stevekuznetsov phew.

As an aside, we will be starting to migrate to using the package module instead of the workaround we are currently using to handle yum/dnf now that we have dropped support for Ansible 1.9 in the master branch.

**Comment by stevekuznetsov** [comment]
@detiber yeah, that will be nice to get the migration and the benefits from not using `command` -- until `package` supports complex use-cases like `--{en,dis}ablerepo`, though, I think I have to use `yum` for my work. Hopefully you guys don't have too many bits like that.
