### ISSUE TITLE
enable multipath - no such file or directory

### ISSUE THREAD

**Issue by kamigerami** [openshift/openshift-ansible#8553]
#### Description

Provide a brief description of your issue here. For example:

While running the playbooks/deploy_cluster.yml the playbook fails on task :

`TASK [openshift_node : Enable multipath] *********************************************************************************************
Monday 28 May 2018  15:03:01 +0200 (0:00:00.826)       0:10:19.796 ************ 
fatal: [myhostname]: FAILED! => {"changed": false, "cmd": "mpathconf --enable", "msg": "[Errno 2] No such file or directory", "rc": 2}
fatal: [myhostname]: FAILED! => {"changed": false, "cmd": "mpathconf --enable", "msg": "[Errno 2] No such file or directory", "rc": 2}
fatal: [myhostname]: FAILED! => {"changed": false, "cmd": "mpathconf --enable", "msg": "[Errno 2] No such file or directory", "rc": 2}
fatal: [myhostname]: FAILED! => {"changed": false, "cmd": "mpathconf --enable", "msg": "[Errno 2] No such file or directory", "rc": 2}
fatal: [myhostname]: FAILED! => {"changed": false, "cmd": "mpathconf --enable", "msg": "[Errno 2] No such file or directory", "rc": 2}
fatal: [myhostname]: FAILED! => {"changed": false, "cmd": "mpathconf --enable", "msg": "[Errno 2] No such file or directory", "rc": 2}

`

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

```
ansible 2.5.3
  config file = /home/svc_ok8sadm/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/svc_ok8sadm/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

openshift-ansible-3.7.0-0.198.0-3139-gf8f497e2b


```

##### Steps To Reproduce
1. ansible-playbook -i hosts -e openshift_enable_service_catalog=false playbooks/deploy_cluster.yml

##### Expected Results
Describe what you expected to happen.

I expect the task to pass without errors.

```
TASK [openshift_node : Enable multipath] *********************************************************************************************
Monday 28 May 2018  15:23:57 +0200 (0:00:00.715)       0:10:42.426 ************ 
changed: [myhostname]
changed: [myhostname]
changed: [myhostname]
changed: [myhostname]
changed: [myhostname]
changed: [myhostname]

```

##### Observed Results
Describe what is actually happening.

```
TASK [openshift_node : Enable multipath] *********************************************************************************************
Monday 28 May 2018  15:03:01 +0200 (0:00:00.826)       0:10:19.796 ************ 
fatal: [myhostname]: FAILED! => {"changed": false, "cmd": "mpathconf --enable", "msg": "[Errno 2] No such file or directory", "rc": 2}
fatal: [myhostname]: FAILED! => {"changed": false, "cmd": "mpathconf --enable", "msg": "[Errno 2] No such file or directory", "rc": 2}
fatal: [myhostname]: FAILED! => {"changed": false, "cmd": "mpathconf --enable", "msg": "[Errno 2] No such file or directory", "rc": 2}
fatal: [myhostname]: FAILED! => {"changed": false, "cmd": "mpathconf --enable", "msg": "[Errno 2] No such file or directory", "rc": 2}
fatal: [myhostname]: FAILED! => {"changed": false, "cmd": "mpathconf --enable", "msg": "[Errno 2] No such file or directory", "rc": 2}
fatal: [myhostname]: FAILED! => {"changed": false, "cmd": "mpathconf --enable", "msg": "[Errno 2] No such file or directory", "rc": 2}
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

We believe that it can't find the binary mpathconf in it's path which is why we get an no such file or directory error.
```
Red Hat Enterprise Linux Server release 7.5 (Maipo)

--- a/roles/openshift_node/tasks/storage_plugins/iscsi.yml
+++ b/roles/openshift_node/tasks/storage_plugins/iscsi.yml
@@ -30,5 +30,5 @@
 
 #enable multipath
 - name: Enable multipath
-  command: "mpathconf --enable"
+  command: "/usr/sbin/mpathconf --enable"
   when: not openshift_is_atomic | bool

```

**Comment by vrutkovs** [comment]
Which OS is that and why would `/usr/sbin` not be in `$PATH` there?

**Comment by kamigerami** [comment]
@vrutkovs Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Comment by vrutkovs** [comment]
Default PATH there already includes this - `/sbin:/bin:/usr/sbin:/usr/bin`. Did you modify the default path?

**Comment by kamigerami** [comment]
no you are correct @vrutkovs the path is there and nothing has been modified. Any ideas as to why this happens?

**Comment by kamigerami** [comment]
The issue was resolved (on the host) by setting the /etc/sudoers  secure_path to /usr/sbin since ansible command module causes commands to be executed with a new, minimal environment (env_reset).

```
/etc/sudoers

Defaults:ansible_user secure_path=/usr/local/bin:/usr/bin:/usr/sbin:/sbin
```

**Comment by kamigerami** [comment]
this issue was resolved outside of openshift-ansible by setting secure_path for the ansible_user in /etc/sudoers to /sbin:/usr/sbin

`Defaults:ansible_user secure_path=/usr/local/bin:/usr/bin:/usr/sbin:/sbin`
