### ISSUE TITLE
node_cpu metrics not available in prometheus UI dropdown, though available from Node Exporter

### ISSUE THREAD

**Issue by skynardo** [openshift/openshift-ansible#8567]
#### Description

Unable to select node_cpu metrics from prometheus UI metrics selection, however node_cpu metrics are available via curl http://localhost:9100/metrics

##### Version

Place the output between the code block below:

```
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
ansible 2.4.4.0
openshift-ansible-3.9.30-1-2-g1ca919a
```

##### Steps To Reproduce
1. On an existing Openshift v3.9.0+ba7faec-1 cluster installed using advanced install
2. Set OSEv3 vars:
#Prometheus
openshift_hosted_prometheus_deploy: true
openshift_prometheus_namespace: openshift-metrics
openshift_prometheus_node_selector: {"region":"infra"}
openshift_prometheus_storage_type: pvc
openshift_prometheus_alertmanager_pvc_name: alertmanager
openshift_prometheus_alertbuffer_pvc_size: 10G
openshift_prometheus_pvc_access_modes: [ReadWriteOnce]
3. Install openshift-prometheus via /usr/share/ansible/openshift-ansible/playbooks/openshift-prometheus/config.yml
4. Add firewall rules on all Nodes for port 9100 prometheus-node-exporter traffic (this reported in separate bug)

##### Expected Results
Describe what you expected to happen.

```
Navigate to https://prometheus-openshift-metrics.apps.shared.openshift.local/graph
Click on insert metric 
Scroll down and find  node_cpu in the list of metrics
```

##### Observed Results
Describe what is actually happening.

```
Navigate to https://prometheus-openshift-metrics.apps.shared.openshift.local/graph
Click on insert metric 
Scroll down to node_
The only node_cpu metric listed is node_cpu_guest_seconds_total

However, if I query one of the Node Exporters on a Node, I see both node_cpu and node_cpu_guest_seconds_total as shown below:

[centos@ip-172-23-20-100 ~]$ curl http://localhost:9100/metrics |grep node_cpu

# HELP node_cpu Seconds the cpus spent in each mode.
# TYPE node_cpu counter
node_cpu{cpu="cpu0",mode="idle"} 33041.98
node_cpu{cpu="cpu0",mode="iowait"} 26.57
node_cpu{cpu="cpu0",mode="irq"} 0
node_cpu{cpu="cpu0",mode="nice"} 16.84
node_cpu{cpu="cpu0",mode="softirq"} 3.23
node_cpu{cpu="cpu0",mode="steal"} 18.06
node_cpu{cpu="cpu0",mode="system"} 86.1
node_cpu{cpu="cpu0",mode="user"} 279.51
node_cpu{cpu="cpu1",mode="idle"} 33047.04
node_cpu{cpu="cpu1",mode="iowait"} 32.41
node_cpu{cpu="cpu1",mode="irq"} 0
node_cpu{cpu="cpu1",mode="nice"} 12.43
node_cpu{cpu="cpu1",mode="softirq"} 2.79
node_cpu{cpu="cpu1",mode="steal"} 21.33
node_cpu{cpu="cpu1",mode="system"} 85.94
node_cpu{cpu="cpu1",mode="user"} 271.42
node_cpu{cpu="cpu2",mode="idle"} 33035.15
node_cpu{cpu="cpu2",mode="iowait"} 57.77
node_cpu{cpu="cpu2",mode="irq"} 0
node_cpu{cpu="cpu2",mode="nice"} 3.67
node_cpu{cpu="cpu2",mode="softirq"} 6.59
node_cpu{cpu="cpu2",mode="steal"} 19.17
node_cpu{cpu="cpu2",mode="system"} 107.8
node_cpu{cpu="cpu2",mode="user"} 311.98
node_cpu{cpu="cpu3",mode="idle"} 33052.59
node_cpu{cpu="cpu3",mode="iowait"} 32.21
node_cpu{cpu="cpu3",mode="irq"} 0
node_cpu{cpu="cpu3",mode="nice"} 12.67
node_cpu{cpu="cpu3",mode="softirq"} 4.85
node_cpu{cpu="cpu3",mode="steal"} 19.19
node_cpu{cpu="cpu3",mode="system"} 105.93
node_cpu{cpu="cpu3",mode="user"} 301.29
# HELP node_cpu_guest_seconds_total Seconds the cpus spent in guests (VMs) for each mode.
# TYPE node_cpu_guest_seconds_total counter
node_cpu_guest_seconds_total{cpu="0",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="0",mode="user"} 0
node_cpu_guest_seconds_total{cpu="1",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="1",mode="user"} 0
node_cpu_guest_seconds_total{cpu="2",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="2",mode="user"} 0
node_cpu_guest_seconds_total{cpu="3",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="3",mode="user"} 0
100  115k  100  115k    0     0  9052k      0 --:--:-- --:--:-- --:--:-- 9608k
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

```
CentOS Linux release 7.4.1708 (Core)
```

**Comment by skynardo** [comment]
I'm thinking I should have opened this under Openshfit / Origin rather than openshift-ansible since I am not sure at this point if this is an installation issue or something else.

**Comment by skynardo** [comment]
I found the following in the prometheus.yml configmap provided by the current ansible installation:
      metric_relabel_configs:
      - source_labels: [__name__]
        action: drop
        regex: 'node_cpu|node_(disk|scrape_collector)_.+'

Why drop node_cpu ? Are there other/better metrics that I should be looking at?

**Comment by vrutkovs** [comment]
@simonpasquier might know why `node_cpu` is being dropped (note that Grafana dashboards are using it IIUC)

**Comment by simonpasquier** [comment]
AFAICT the decision to drop some of the node_exporter metrics comes originally from https://github.com/openshift/origin/pull/18174 which added the scraping of node-exporter to the Prometheus Origin template. At the time, the rationale was to filter out metrics with high cardinality which otherwise it could make Prometheus unusable with large clusters. That being said, a flag is probably needed to enable/disable this filtering.

I also see that the future [Cluster Monitoring Operator](https://github.com/openshift/cluster-monitoring-operator) doesn't filter at all the node_exporter metrics (to be confirmed).

cc @ironcladlou (for the monitoring team) and @mjudeikis (original commiter of node-exporter in openshift-ansible)

**Comment by brancz** [comment]
That's correct, the future stack doesn't filter at all (currently), but also node-exporter since https://github.com/openshift/origin/pull/18174 now ignores a number of filesystems that were producing high cardinality before, so I think we should be good. Scalability tests also haven't shown to have dropping these metrics to be necessary so far (this may change in the future, but seems ok right now).

**Comment by simonpasquier** [comment]
> note that Grafana dashboards are using it IIUC

There is #8279 which points out that filtering of the node_exporter metrics breaks the Grafana dashboard.

Regarding the original reason for dropping `node_cpu` metrics @smarterclayton is probably the most qualified to answer.

**Comment by smarterclayton** [comment]
We filter it out explicitly because we already have it from cadvisor, and
they are incredibly high cardinality.

**Comment by smarterclayton** [comment]
The extra 5GB of memory they use are not worthwhile.
