### ISSUE TITLE
CRI-O RPM missing

### ISSUE THREAD

**Issue by jocelynthode** [openshift/openshift-ansible#8580]
#### Description

When having:
```
openshift_use_crio=true
openshift_crio_use_rpm=true
```
CentOS does not find the crio rpm.

##### Version

Openshift 3.9
openshift-ansible on release-3.9 branch

##### Steps To Reproduce
1. Run the prerequisite playbook

##### Expected Results

cri-o getting installed

##### Observed Results

cri-o unavailable in the repos

##### Additional Information

I'm using http://mirror.switch.ch/ftp/mirror/centos/7/ as my repo.  I might be missing a repo for cri-o rpm. If so which repo should be enabled to be able to install cri-o ?

**Comment by DanyC97** [comment]
@sdodson where is the source code for  cri-o ? i suspect this is a 3rd party to Origin/ ansible repos and as such we can't take care of it ? 

any feedback much appreciated !

**Comment by jocelynthode** [comment]
I saw on the official cri-o website a link to a rc repo but it is for cri-o 1.10 which is not what we would want on openshift 3.9. 

If an other repo is needed the playbook should either install it or have it as a requirement when the variable is enabled.

**Comment by DanyC97** [comment]
@vrutkovs @michaelgugino your thoughts on my comment above ? thx

**Comment by michaelgugino** [comment]
I'm unsure where CentOS users would obtain crio.

**Comment by DanyC97** [comment]
oh i see ... i'll try to keep looking then

**Comment by lsm5** [comment]
So, I just joined the PaaS SIG and built cri-o 1.9.12 for `paas7-openshift-origin39-candidate` tag at 
https://cbs.centos.org/koji/buildinfo?buildID=22911 and doing the same for cri-tools at https://cbs.centos.org/koji/taskinfo?taskID=441657 . Let me know if that unblocks you or anything else needed /cc @runcom

**Comment by runcom** [comment]
isn't CRI-O for 3.9 an RPM? I thought we just used RPMs? @ashcrow @mrunalp

**Comment by lsm5** [comment]
@runcom yup those are rpms, see the URLs for rpm links. Or am I reading your question wrong?

**Comment by lsm5** [comment]
going forward, I'll stop building cri-o for Virt SIG, rather build it for different branches of PaaS SIG

**Comment by runcom** [comment]
I meant, do we support installing cri-o via RPM in 3.9? I though it was something supported from >3.10

**Comment by lsm5** [comment]
@ashcrow ack, so the above CentOS builds are good for 3.9, yes?

**Comment by jocelynthode** [comment]
@ism5: These builds will eventually make it to the paas7-openshift-origin release repo right ?

**Comment by ashcrow** [comment]
@lsm5 :arrow_up:

**Comment by lsm5** [comment]
@jocelynthode do you have rules on when to push something to -release? like get acks from 3 people or wait 2 weeks or whatever? Or is that whenever the maintainer feels like? I don't mind if these get pushed to -release in bulk along with other packages if there's such a thing

**Comment by lsm5** [comment]
@kbsingh @ashcrow could you comment on ^^ please? /cc @runcom

**Comment by lsm5** [comment]
@jocelynthode is the problem you were facing about getting the wrong version of cri-o (1.10 instead of 1.9) ... those should be taken care of by the recent PaaS SIG builds I did. Previously the Virt SIG builds were getting picked up which had all versions mixed up, but PaaS SIG builds are segregated based on openshift versions.

**Comment by DanyC97** [comment]
@jocelynthode when i got the baton from @tdawson the rule for promoting to -release was / is to announce on dev/ users mailing list, wait 1/2 weeks during which we were waiting for folks to confirm the tests worked and then promote it.

Tomorrow in the weekly PaaS meeting i'll bring it up for discussion and an email notification will be sent out.
If you are willing to test it from -candidate repo then we'll move it to -release, how does that sound for you ?

**Comment by jocelynthode** [comment]
@lsm5 My problem was not getting any rpm at all
@DanyC97 I'm not sure I will have time to test these as I'm under certain time constraints unfortunately.

**Comment by DanyC97** [comment]
no prob @jocelynthode .

Fyi the rpms will be available [here](http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin39/) tomorrow after 09:00 UTC

**Comment by DanyC97** [comment]
@vrutkovs suggest we close this as being resolved

**Comment by vrutkovs** [comment]
cri-o and cri-tools are now included in origin-39 and origin-310 CentOS repos

**Comment by debianmaster** [comment]
same issue.

**Comment by ashcrow** [comment]
FWIW the referenced mirror (http://mirror.switch.ch/ftp/mirror/centos/7/) doesn't have `origin-39` or `orgin-310`.
