### ISSUE TITLE
Allow adding additional ports to the loadbalancer firewall

### ISSUE THREAD

**Issue by petergardfjall** [openshift/openshift-ansible#8593]
#### Description

This is really a feature request.

It is great to be able to add additional HAProxy loadbalancer frontends/backends via the `openshift_loadbalancer_additional_frontends` and `openshift_loadbalancer_additional_frontends` ansible variables. 

_However_, this functionality needs to be complemented by an ability to specify additional ports to open in the server's firewall.

At the moment, this appears to be hardcoded to only open ports `8443` (master API servers) and `9000` (stats). Something along the lines of a `openshift_loadbalancer_firewall_allow` which could take on values like `["443/tcp","1234/tcp"]` would be very useful.

##### Version

Please put the following version information in the code block
indicated below.

* openshift-ansible version: 3.9 (commit `1513080b0`)
* Your ansible version: `ansible 2.5.3`
* Operating system: CentOS Linux 7
* Kernel: Linux 3.10.0-862.2.3.el7.x86_64
* Architecture: x86-64

##### Steps To Reproduce
1. Add an additional frontend (port 443) leading traffic to a set of backends (in this case, infrastructure nodes and the hawkular metrics service). For example,
```
openshift_loadbalancer_additional_frontends=[{"name": "https-frontend", "binds": ["0.0.0.0:443"], "default_backend": "https-backends", "mode": "tcp"}]
openshift_loadbalancer_additional_backends=[{"name": "https-backends", "mode": "tcp", "balance": "roundrobin", "options": ["tcp-check"], "servers":[{"name": "infra-0", "address": "10.11.12.20:443", "opts": "check inter 2s fall 2 rise 3 on-marked-down shutdown-sessions"},{"name": "infra-1", "address": "10.11.12.21:443", "opts": "check inter 2s fall 2 rise 3 on-marked-down shutdown-sessions"},{"name": "infra-2", "address": "10.11.12.22:443", "opts": "check inter 2s fall 2 rise 3 on-marked-down shutdown-sessions"}]}]
```

2. From a different hsot, try to connect with a backend through the loadbalancer's frontend port 443:

```
$  curl -kv https://10.11.12.100:443/
* About to connect() to 10.11.12.100 port 443 (#0)
*   Trying 10.11.12.100...
* No route to host
* Failed connect to 10.11.12.100:443; No route to host
```

##### Expected Results
Describe what you expected to happen.

I expected the `curl`to the added frontend (port 443) to succeed
```
$  curl -kv https://10.11.12.100:443/
... a valid response
```

##### Observed Results
Describe what is actually happening.

Since the port (443) is not opened on the haproxy server's firewall, the request will fail on the client machine
```
$  curl -kv https://10.11.12.100:443/
* About to connect() to 10.11.12.100 port 443 (#0)
*   Trying 10.11.12.100...
* No route to host
* Failed connect to 10.11.12.100:443; No route to host

```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* The reason that the request fails is that a port opening for 443 is missing from the firewall (rules are only added for port 8443 and 9000):

```
$ sudo iptables --list-rules 
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N OS_FIREWALL_ALLOW
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j OS_FIREWALL_ALLOW
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 9000 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 8443 -j ACCEPT
```

By manually adding the firewall rule, the request succeeded on the client:

`sudo iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT`

**Comment by nickkeyzer** [comment]
I support this feature request. In the mean time I was able to inject new rules during deployment by specifying the following in the inventory:

```
r_openshift_loadbalancer_os_firewall_allow = [{"service": "haproxy routes","port": "443/tcp"}]
```

This doesn't feel proper but has had the desired effect. We plan to use a real external load balancer when we move to a production environment but this is handy for testing Routes in a lab environment without having to manually add the firewall rules and haproxy configs.
