### ISSUE TITLE
Dynamic volume provisioning of gluster-block is not working on OCP3.9

### ISSUE THREAD

**Issue by rabem00** [openshift/openshift-ansible#8594]
Dynamic volume provisioning of gluster-block is not working on OCP3.9

```
ansible 2.5.2
openshift-ansible-3.9.30-1
openshift origin 3.9.0
atomic 1.22.1
```

##### Steps To Reproduce
Used the following information: [persistant storage glusterfs block install example full](https://docs.openshift.org/3.9/install_config/persistent_storage/persistent_storage_glusterfs.html#install-example-full)

##### Expected Results
When using the storageclass glusterfs-registry-block to create a PVC we expect a volume claim just as the working "normal" gluster volumes using storageclass glusterfs-storage.

```
# oc get pvc
NAME         STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS               AGE
test-block   Pending                                                                        glusterfs-registry-block   2d
test1        Bound     pvc-b1845bb7-632c-11e8-a8d4-005056b05b5d   1Gi        RWO            glusterfs-storage          2d

# oc describe pvc test-block
Name:          test-block
Namespace:     test
StorageClass:  glusterfs-registry-block
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-class=glusterfs-registry-block
               volume.beta.kubernetes.io/storage-provisioner=gluster.org/glusterblock
Finalizers:    []
Capacity:
Access Modes:
Events:
  Type    Reason                Age                  From                         Message
  ----    ------                ----                 ----                         -------
  Normal  ExternalProvisioning  2m (x16670 over 2d)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "gluster.org/glusterblock" or manually created by system administrator
```

The cluster is available for debugging and testing.

**Comment by rabem00** [comment]
`# oc describe storageclass glusterfs-registry
Name:            glusterfs-registry-block
IsDefaultClass:  No
Annotations:     <none>
Provisioner:     gluster.org/glusterblock
Parameters:      chapauthenabled=true,hacount=3,restsecretname=heketi-registry-admin-secret-block,restsecretnamespace=infra-storage,resturl=http://heketi-registry-infra-storage.infracloudapps.ont.example.com,restuser=admin
ReclaimPolicy:   Delete
Events:          <none>

-bash-4.2#`

**Comment by rabem00** [comment]
```
# oc describe storageclass glusterfs-registry
Name:            glusterfs-registry-block
IsDefaultClass:  No
Annotations:     <none>
Provisioner:     gluster.org/glusterblock
Parameters:      chapauthenabled=true,hacount=3,restsecretname=heketi-registry-admin-secret-block,restsecretnamespace=infra-storage,resturl=http://heketi-registry-infra-storage.infracloudapps.ont.belastingdienst.nl,restuser=admin
ReclaimPolicy:   Delete
Events:          <none>

-bash-4.2#
```

**Comment by yuanlinios** [comment]
Exactly the same result. And I don't even see any message related to the pvc from heketi log.

**Comment by mtoddw** [comment]
any updates on this? We're getting the same failure it just hangs

10:28:34 AM | Normal | External Provisioning | waiting for a volume to be created, either by external provisioner "gluster.org/glusterblock" or manually created by system administrator

**Comment by yuanlinios** [comment]
same in OKD 3.10

**Comment by uselessidbr** [comment]
No updates on this?

I've recently deployed openshift and i'm facing the exactly issue.

oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v3.11.0+d545883-301
kubernetes v1.11.0+d4cacc0

**Comment by uselessidbr** [comment]
I managed to workaround this issue temporarily:

https://github.com/openshift/origin/issues/23881
