### ISSUE TITLE
bad certificate issue during startup

### ISSUE THREAD

**Issue by meier-christoph** [openshift/openshift-ansible#861]
I am running into some certificate issues preventing the installation to complete and the master from starting up.

```
nov. 10 19:29:56 master.local.net openshift[975]: http: TLS handshake error from 192.168.3.229:45499: remote error: bad certificate
```

here is the host file we are using:

```yaml
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/openshift/openshift-passwd'}]

[masters]
192.168.3.227

[etcd]
192.168.3.227
192.168.3.228
192.168.3.229

[nodes]
192.168.3.227 openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
192.168.3.228 openshift_node_labels="{'region': 'primary', 'zone': 'lux'}"
192.168.3.229 openshift_node_labels="{'region': 'primary', 'zone': 'lux'}"
```

Note: we had to add the etcd group to the hosts file as otherwise it would not install etcd at all and the installation would fail. When we did some previous tests last week it was installing etcd as exected using just masters and nodes groups though.

The master and nodes are CentOS 7.1 hosts setup according to the prerequisites defined here:
https://docs.openshift.org/latest/install_config/install/prerequisites.html

Regards,
Chris

**Comment by abutcher** [comment]
Hey @meier-christoph, etcd will be embedded with the master when an `[etcd]` group has not been defined and you won't see etcd being installed or a standalone etcd process running. If you encountered issues during the install it's possible that you currently have mis-matched certificates. I'd recommend uninstalling and starting from a blank state to ensure that the certificates are in order.

To uninstall using the uninstall playbook:

```
ansible-playbook ~/openshift-ansible/playbooks/adhoc/uninstall.yml
```

I tested an origin install with both embedded and external etcd to make sure we haven't introduced any regressions in the ansible code and everything seems good.

If your certificate issues persist through your next install please let us know!

**Comment by meier-christoph** [comment]
Uninstalling and reinstalling origin did solve the certificate issue.
Thanks for the quick help,
Chris
