### ISSUE TITLE
This playbook requires access to Docker 1.12 or later

### ISSUE THREAD

**Issue by ewerk-pnahratow** [openshift/openshift-ansible#8620]
#### Description

I'm trying to upgrade OpenShift Origin v3.7.2 to v3.9.0. The playbook stops at 

`TASK [container_runtime : Required docker version not available (non-atomic)]`

with the Message `This playbook requires access to Docker 1.12 or later`

##### Version

ansible: 2.5.0
openshift-ansible: a31b673c4ecab2ed2f0bcd4635f7740d9bb3d8e5

##### Additional Information

OS: CentOS Linux release 7.5.1804 (Core)

#### Analysis

My assumption is that the task fails because the `repoquery` before fails to deliver a result

```
ok: [os-master-3.lab.com] => {
    "attempts": 1, 
    "changed": false, 
    "cmd": [
        "repoquery", 
        "--plugins", 
        "--qf", 
        "%{version}", 
        "docker"
    ], 
    "delta": "0:00:00.309196", 
    "end": "2018-06-04 14:28:53.651509", 
    "failed_when_result": false, 
    "invocation": {
        "module_args": {
            "_raw_params": "repoquery --plugins --qf '%{version}' \"docker\"", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "rc": 0, 
    "start": "2018-06-04 14:28:53.342313", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "", 
    "stdout_lines": []
}
```
When I manually issue `repoquery --plugins --qf '%{version}' "docker"` I get no results. When I remove the `--plugins` I get

```
[root@os-master-1 yum.repos.d]# repoquery --qf '%{version}' "docker"
1.13.1
```

The installed yum plugins are `fastestmirror, versionlock`

The versionlock list gives

```
[root@os-master-1 yum.repos.d]# yum versionlock list
Geladene Plugins: fastestmirror, versionlock
2:docker-common-1.12.6-71.git3e8e77d.el7.centos.1.*
2:docker-1.12.6-71.git3e8e77d.el7.centos.1.*
2:docker-client-1.12.6-71.git3e8e77d.el7.centos.1.*
versionlock list done
```

I think versionlock might be the root of the problem but I'm not sure how to proceed.

**Comment by MarWestermann** [comment]
Hi,
do you have exludes on /etc/yum.conf
I had a similar issue with updating openshift.
Have a look here: https://github.com/openshift/openshift-ansible/issues/8342#issuecomment-388728273

**Comment by ewerk-pnahratow** [comment]
Closing the issue. I versionlocked docker as part of the host preparation some time ago and I just forgot.
