### ISSUE TITLE
provisioning fails when setting up origin with vagrant 

### ISSUE THREAD

**Issue by VolkerKozlowski** [openshift/openshift-ansible#864]
Hello,

Provisioning with vagrant fails  with the output below. It seems that ansible has not been installed.
```
==> node1: Running provisioner: shell...
    node1: Running: inline script
==> node2: Running provisioner: shell...
    node2: Running: inline script
==> node2: Running provisioner: shell...
    node2: Running: inline script
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running provisioner: ansible...
The executable 'ansible-playbook' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.
```

Kind regards, Volker

**Comment by detiber** [comment]
According to the docs here: https://docs.vagrantup.com/v2/provisioning/ansible.html It appears that you just need to install ansible on the machine you are running vagrant.

I've submitted https://github.com/openshift/openshift-ansible/pull/871 to address the fact that the README_vagrant.md file was missing listing ansible as a dependency.
