### ISSUE TITLE
why are roles been called like this?

### ISSUE THREAD

**Issue by jlozadad** [openshift/openshift-ansible#8644]
#### Description

I'm going through the roles/playbook to try to understand what is happening but, I keep seeing this like this https://github.com/openshift/openshift-ansible/blob/master/playbooks/init/roles. Why are they been called like that? it seems to be a waste and not best practices.

**Comment by DanyC97** [comment]
that is just a symlink pointing to roles/ dir.

**Comment by jlozadad** [comment]
but, why ? seems like a terrible idea.

**Comment by DanyC97** [comment]
because in this way you can have playbooks and roles dirs at same level - easier to go to - and with the symlink you don't have to alter the role_path in ansible.cfg

**Comment by DanyC97** [comment]
@jlozadad if you don't have any other comments please close the issue, thank you
