### ISSUE TITLE
can't read /etc/sysconfig/origin-master-api: No such file or directory

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-ansible#8650]
```
TASK [get azure deployment message] ********************************************
Wednesday 06 June 2018  13:21:47 +0000 (0:00:00.158)       0:04:05.336 ******** 
changed: [localhost]

TASK [debug] *******************************************************************
Wednesday 06 June 2018  13:21:49 +0000 (0:00:02.674)       0:04:08.011 ******** 
fatal: [localhost]: FAILED! => {"msg": "the field 'args' has an invalid value ([]), and could not be converted to an dict.The error was: No JSON object could be decoded\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/playbooks/azure/openshift-cluster/launch.yml': line 105, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - debug:\n      ^ here\n"}
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_azure/309/consoleFull#42262949858b6e51eb7608a5981914356

@openshift/sig-azure

**Comment by kargakis** [comment]
```
/etc/sysconfig/origin-master-api\\\\nsed: can't read /etc/sysconfig/origin-master-api: No such file or directory
```

**Comment by kargakis** [comment]
This is on the 3.10 job which seems like a fair failure since we have removed `/etc/sysconfig/origin-master-api` from the node image.

**Comment by kwoodson** [comment]
@kargakis, It appears that this job is running a 3.9 release as the `openshiftmasterscript.sh` that `sed` the value in `/etc/sysconfig/origin-master-api` only exists in 3.9.

https://github.com/Azure/acs-engine/blob/master/parts/openshift/release-3.9/openshiftmasterscript.sh#L45-L47

**Comment by kwoodson** [comment]
The root cause of this is the image query.  It returns an image that is out of date.  We need to be able to return the latest image that matches the version.

**Comment by jim-minter** [comment]
I think @pschiffe's work should resolve this as it will accept a hard-coded input VM rather than use the image query?

**Comment by pschiffe** [comment]
This should be fixed now by https://github.com/openshift/openshift-ansible/pull/8751 and https://github.com/openshift/openshift-ansible/pull/8756

**Comment by pweil-** [comment]
Awesome!  Please verify and close when ready.

**Comment by pschiffe** [comment]
@pweil- yep, it's working, but I don't have perm. to close this.

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_azure/517/
