### ISSUE TITLE
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'oo_first_master'

### ISSUE THREAD

**Issue by arthurlogilab** [openshift/openshift-ansible#8651]
#### Description

Provide a brief description of your issue here. For example:

> The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'oo_first_master'

> When trying to provision on openstack 

##### Version

```
$ ansible --version
ansible 2.5.4
  config file = /home/arthur/local/openshift/ansible.cfg
  configured module search path = [u'/home/arthur/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/arthur/.virtualenvs/ansible/local/lib/python2.7/site-packages/ansible
  executable location = /home/arthur/.virtualenvs/ansible/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]

$ git describe
openshift-ansible-3.10.0-0.60.0

```

##### Steps To Reproduce
> ansible-playbook --user openshift   -i openshift-ansible/playbooks/openstack/inventory.py   -i inventory   openshift-ansible/playbooks/openstack/openshift-cluster/provision_install.yml

##### Observed Results
Describe what is actually happening.

```
     Message:  The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'oo_first_master'
               
               The error appears to have been in '/home/arthur/local/openshift/openshift-ansible/playbooks/init/version.yml': line 26, column 5, but may
               be elsewhere in the file depending on the exact syntax problem.
               
               The offending line appears to be:
               
                 tasks:
                 - set_fact:
                   ^ here
```

**Comment by tomassedovic** [comment]
I've been able to reproduce this error, but only if there are no nodes in the `masters` ansible group. I didn't see anything wrong in the code so more details about the environment you're trying to install would be appreciated.

Could you paste the contents of your inventory/group_vars/all.yml?

Also if you can, what's the output of `openshift-ansible/playbooks/openstack/inventory.py --list` after the ansible failure?

**Comment by tomassedovic** [comment]
Obviously, if you've got any sensitive data  (e.g. the DNS configuration) censor that out.

**Comment by tech-mint** [comment]
any activity?

**Comment by Sebastian-Negoescu** [comment]
`<!DOCTYPE html>
<body>
<p> TASK [mount_backup_folder_jenkins : mount file shared] *************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'backup_jenkinsfileshare_setup' is undefined\n\nThe error appears to have been in '/mnt/workspace/DWP_OPS/backup_jenkins/Ansible/jenkins_backup_restore/roles/mount_backup_folder_jenkins/tasks/main.yml': line 22, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  become: yes\n- name: mount file shared\n  ^ here\n"}
	to retry, use: --limit @/mnt/workspace/DWP_OPS/backup_jenkins/Ansible/jenkins_backup_restore/backup_jenkins.retry </p>
</body>`

**Comment by Sebastian-Negoescu** [comment]
TASK [mount_backup_folder_jenkins : mount file shared] *************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'backup_jenkinsfileshare_setup' is undefined\n\nThe error appears to have been in '/mnt/workspace/DWP_OPS/backup_jenkins/Ansible/jenkins_backup_restore/roles/mount_backup_folder_jenkins/tasks/main.yml': line 22, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  become: yes\n- name: mount file shared\n  ^ here\n"}
	to retry, use: --limit @/mnt/workspace/DWP_OPS/backup_jenkins/Ansible/jenkins_backup_restore/backup_jenkins.retry
