### ISSUE TITLE
"openshift_logging_es_ops_pvc_storage_class_name" not setting the value appropriately during OpenShift Logging Install using Advanced Install Ansible Scripts. 

### ISSUE THREAD

**Issue by jacobjohnanda** [openshift/openshift-ansible#8666]
#### Description
Ansible  Variable "openshift_logging_es_ops_pvc_storage_class_name" not setting the value appropriately during OpenShift  Cluster Logging Install using Advanced Install Ansible Scripts.

I am trying to install  OpenShift  Cluster Logging Install using Advanced Install Ansible Scripts.
I deployed the following command:-

ansible-playbook -i inventory.ini /root/openshift-ansible/playbooks/openshift-logging/config.yml \
   -e openshift_logging_install_logging=True \
   -e openshift_logging_es_pvc_dynamic=TRUE \
   -e openshift_logging_es_pvc_storage_class_name=gold \
   -e openshift_logging_es_pvc_size=7Gi \
   -e openshift_logging_es_pvc_prefix=xlr8-logging123 \
   -e openshift_logging_use_ops=True \
   -e openshift_logging_es_ops_pvc_dynamic=True \
   -e openshift_logging_es_ops_pvc_storage_class_name=gold \
   -e openshift_logging_es_ops_pvc_size=8Gi \
   -e openshift_logging_es_ops_pvc_prefix=xlr8-logging-ops123 \
   -e openshift_logging_image_version=v3.9 

but the PVC for es pod was bound without any issues  but the PVC for es_ops failed with the error "Storage Class not set"
##### Version

Please put the following version information in the code block
indicated below.

* [root@scspa0485357001 ~]# ansible --version
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`
 openshift-ansible-playbooks-3.9.0-0.53.0

```
VERSION INFORMATION HERE PLEASE
```
* [root@scspa0485357001 ~]# oc version
oc v3.9.0+46ff3a0-18
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.9.0+46ff3a0-18
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. Install OpenShift logging  with following options
ansible-playbook -i inventory.ini /root/openshift-ansible/playbooks/openshift-logging/config.yml \
   -e openshift_logging_install_logging=True \
   -e openshift_logging_es_pvc_dynamic=TRUE \
   -e openshift_logging_es_pvc_storage_class_name=gold \
   -e openshift_logging_es_pvc_size=7Gi \
   -e openshift_logging_es_pvc_prefix=xlr8-logging123 \
   -e openshift_logging_use_ops=True \
   -e openshift_logging_es_ops_pvc_dynamic=True \
   -e openshift_logging_es_ops_pvc_storage_class_name=gold \
   -e openshift_logging_es_ops_pvc_size=8Gi \
   -e openshift_logging_es_ops_pvc_prefix=xlr8-logging-ops123 \
   -e openshift_logging_image_version=v3.9 

2. oc get pods -n logging 
   oc get pvc -n logging 

##### Expected Results
1. oc get pods -n logging should see all the pods up and running
2. oc get pvc -n logging should see all the PVCs bound.

```
Example command and output or error messages
```

##### Observed Results
We could  see that the PVC  had bound for es without any issues but the PVC for es_ops was in pending state.
While doing a describe it was found that the PVC failed with  the error "Storage Class not set"

```
[root@scspa0485357001 ~]# oc get pods -n logging
NAME                                           READY     STATUS             RESTARTS   AGE
logging-curator-1-9fl7g                        1/1       Running            4          15m
logging-curator-ops-1-98kt4                    0/1       CrashLoopBackOff   3          14m
logging-es-data-master-ptgnmzgo-1-deploy       0/1       Running            0          12m
logging-es-ops-data-master-kpn4z840-1-deploy   0/1       Error              0          11m
logging-fluentd-4bmkr                          1/1       Running            0          13m
logging-fluentd-cfsf7                          1/1       Running            0          13m
logging-fluentd-h4wl9                          1/1       Running            0          13m
logging-fluentd-mns9s                          1/1       Running            0          13m
logging-fluentd-prqq2                          1/1       Running            0          13m
logging-kibana-1-zmx4p                         2/2       Running            0          17m
logging-kibana-ops-1-w68wg                     2/2       Running            0          16m

[root@scspa0485357001 ~]# oc get pvc  -n logging
NAME                    STATUS    VOLUME                            CAPACITY   ACCESS MODES   STORAGECLASS   AGE

xlr8-logging-ops123-0   Pending                                                                              19m
xlr8-logging123-0       Bound     logging-xlr8-logging123-0-94665   7Gi        RWO            gold           20m
                                                                       3d

[root@scspa0485357001 ~]# oc describe pvc xlr8-logging-ops123-0  -n logging
Name:          xlr8-logging-ops123-0
Namespace:     logging
StorageClass:
Status:        Pending
Volume:
Labels:        logging-infra=support
Annotations:   <none>
Finalizers:    []
Capacity:
Access Modes:
Events:
  Type    Reason         Age                From                         Message
  Normal  FailedBinding  1m (x84 over 21m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

```
1. RHEL 7.4  Server
```

**Comment by Bengrunt** [comment]
Hi, 

Unearthing this issue :)

I think I'm encountering this as well, with Openshift 3.11.  
The only difference is that I've got a default storage class setup so the deployment gets up and running as expected anyway.

However, it's using the wrong storage class since it's using the default one.  
As well as @jacobjohnanda, that leads me to believe that the `openshift_logging_es_ops_pvc_prefix` is ignored by the Ansible playbooks.

I tried to look into the filter that generates the deployment configuration (it's using the same filter for both ops and regular EFK deployments) but I didn't manage to find why it fails.
