### ISSUE TITLE
Openshift Web Console not installed for origin in all in one installation

### ISSUE THREAD

**Issue by akram** [openshift/openshift-ansible#8703]
#### Description

Openshift Web Console not installed for origin
on an all in one installation, the openshift web console (origin web console) does not install

Tried both of these:
#openshift_web_console_nodeselector={'region':'infra'}
openshift_web_console_install=true

The namespace never gets created

**Comment by vrutkovs** [comment]
Could you attach the logs for the install? Which branch and Origin version is being installed?
