### ISSUE TITLE
How to uninstall service catalog

### ISSUE THREAD

**Issue by jerryhan77** [openshift/openshift-ansible#8705]
#### Description

I have a running openshift origin 3.7 cluster with service catalog. The cluster are installed by openshift-ansible. I cannot find the information on how to uninstall the service catalog.

I have try to set 'openshift_enable_service_catalog=false' in inventory file, and run the playbooks/byo/openshift-cluster/service-catalog.yml, but with no luck.

**Comment by ganhuang** [comment]
@jerryhan77 Please try to set `openshift_service_catalog_remove=true`.

 You have to set `openshift_enable_service_catalog=true` at the same time to ensure role `openshift_service_catalog` is called.

**Comment by jerryhan77** [comment]
@ganhuang  Thanks for the tip!

I'm using following setting to remove the service catalog and related service.
```
openshift_service_catalog_remove=true
openshift_enable_service_catalog=true
ansible_service_broker_remove=true
ansible_service_broker_install=false
template_service_broker_remove=true
template_service_broker_install=false
```
