### ISSUE TITLE
How to restart a failed deployment?

### ISSUE THREAD

**Issue by yuanlinios** [openshift/openshift-ansible#8711]
#### Description
Just a generic question regarding to deployment. If the ansible playbook at some stage, how can I restart the deployment? 

Usually, I will get message like  
* "to retry, use: --limit @aaa.retry" under the failed task
* "This phase can be restarted by running: bbb.yml" under installer status 

Shall I retry the failed task, rerun the phase, or rerun the deploy_cluster.yml playbook? I do not think the playbook is idempotent

**Comment by vrutkovs** [comment]
`deploy_cluster.yml` should be started in order to restart the deployment as a whole. Some stages could restarted by running particular playbooks. `--limit` with retry files might not work in most cases and its not recommended
