### ISSUE TITLE
Wait for Node Registration

### ISSUE THREAD

**Issue by MohamedHedi** [openshift/openshift-ansible#8712]
#### Description
try to create origin cluster with ansible in aws (1 master + 2 nodes)

And I have this error on TASK [openshift_manage_node : Wait for Node Registration] :

`fatal: [everysenscloud.com -> everysenscloud.com]: FAILED! => {"attempts": 50, "changed": false, "results": {"cmd": "/bin/oc get node ip-10-0-0-5.eu-west-3.compute.internal -o json -n default", "results": [{}], "returncode": 0, "stderr": "Error from server (NotFound): nodes \"ip-10-0-0-5.eu-west-3.compute.internal\" not found\n", "stdout": ""}, "state": "list"}`

`oc get node
NAME                                                           STATUS     ROLES        AGE     VERSION
ip-10-0-0-12.eu-west-3.compute.internal   NotReady   compute   1h        v1.9.1+a0ce1bc657
ip-10-0-0-5.eu-west-3.compute.internal     NotReady   <none>    53s       v1.9.1+a0ce1bc657
ip-10-0-0-8.eu-west-3.compute.internal     NotReady   compute   1h        v1.9.1+a0ce1bc657`

##### Version
* The output of  `ansible --version` 
ansible 2.5.3

* The output of `git describe`
openshift-ansible-3.9.30-1-27-g7423bb1

* inventory file :
```[OSEv3:children]
masters
etcd
nodes

[OSEv3:vars]
ansible_ssh_user=centos
ansible_sudo=true
ansible_become=true
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
openshift_clusterid=openshiftcluster

openshift_deployment_type=origin
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_install_examples=true
openshift_release="3.9"
openshift_master_default_subdomain=apps.example.com
openshift_master_api_port=8443
openshift_master_console_port=8443
openshift_master_identity_providers=[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]
openshift_docker_options='--selinux-enabled --insecure-registry 172.30.0.0/16'
openshift_disable_check=disk_availability,docker_storage,memory_availability

# AWS
openshift_cloudprovider_kind=aws
# Note: IAM profiles may be used instead of storing API credentials on disk.
openshift_cloudprovider_aws_access_key=xxxxxxxxxxxxxxxxxxxx
openshift_cloudprovider_aws_secret_key=xxxxxxxxxxxxxxxxxxxx

#metric
openshift_metrics_install_metrics=true

[masters]
example.com
[etcd]
example.com

[nodes]
example.com openshift_node_labels="{'region':'infra','zone':'west'}" openshift_schedulable=true
xxxxxx.eu-west-3.compute.amazonaws.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
yyyyyy.eu-west-3.compute.amazonaws.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
```

**Comment by venkatmarella** [comment]
Hi,

Did you resolve this issue? I am getting same error.
