### ISSUE TITLE
Missing bootstrap.kubeconfig

### ISSUE THREAD

**Issue by nwsheppard** [openshift/openshift-ansible#8737]
#### Description

Performing a new deployment to AWS, running the provision_nodes.yml playbook, I am getting a failure to find the /etc/origin/master/bootstrap.kubeconfig.

`TASK [openshift_aws : slurp down the bootstrap.kubeconfig] ***************************************************************************************************************
task path: /home/user/Git/github/openshift-ansible/roles/openshift_aws/tasks/provision_nodes.yml:7
Tuesday 12 June 2018  15:33:07 -0400 (0:00:00.767)       0:00:03.240 ********** 
Using module file /home/user/.local/lib/python2.7/site-packages/ansible/modules/net_tools/basics/slurp.py
<ec2-34-205-75-216.compute-1.amazonaws.com> ESTABLISH SSH CONNECTION FOR USER: centos
<ec2-34-205-75-216.compute-1.amazonaws.com> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/user/.ssh/key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=30 -o ControlPath=/home/user/.ansible/cp/%h-%r ec2-34-205-75-216.compute-1.amazonaws.com '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-udvsxtrmoruhlffkswrdzemezrsvbyes; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<ec2-34-205-75-216.compute-1.amazonaws.com> (1, '\n{"msg": "file not found: /etc/origin/master/bootstrap.kubeconfig", "failed": true, "invocation": {"module_args": {"src": "/etc/origin/master/bootstrap.kubeconfig"}}}\n', '')
fatal: [localhost -> ec2-34-205-75-216.compute-1.amazonaws.com]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "src": "/etc/origin/master/bootstrap.kubeconfig"
        }
    }, 
    "msg": "file not found: /etc/origin/master/bootstrap.kubeconfig"
}
`
##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
`ansible 2.4.3.0`

If you're operating from a **git clone**:

* The output of `git describe`
`openshift-ansible-3.9.32-1`

##### Steps To Reproduce
1. Execute the following playbooks in this order:
prerequisites.yml
build_ami.yml
provision.yml
install.yml
provision_nodes.yml

##### Expected Results
Complete the installation.

##### Observed Results
Fails immediately when searching for bootstrap.kubeconfig on the master nodes.  Can confirm that there are no files by that name on the master servers. 

##### Inventory File
https://gist.github.com/nwsheppard/dee2a8ec8584b5993ac55e52f51d0a95

**Comment by ngiron** [comment]
I have the same issue with that release : openshift-ansible-3.9.35-1
I try to deploy the cluster on AWS with the playbook given with that release.

**Comment by nioe** [comment]
Were you able to solve this? We're getting the exact same error with origin 3.11.
