### ISSUE TITLE
'openshift_hostname' is undefined

### ISSUE THREAD

**Issue by hetzbh** [openshift/openshift-ansible#8738]
#### Description

Provide a brief description of your issue here. 

Testing the prerequisites.yml with a simple hosts file I created (below)

Ansible version - 2.5.3 (CentOS 7, using EPEL repo)

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`
openshift-ansible-3.9.0-0.53.0.git.1.af49d87.el7.noarch

Place the output between the code block below:

##### Steps To Reproduce
1. created the hosts file
2. then run: ansible-playbook -i /root/hosts /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

##### Expected Results
to pass ;)

```
TASK [Validate openshift_hostname when defined] ***************************************************************************************************
skipping: [osmaster.hetzlabs.io]
skipping: [infra.hetzlabs.io]
skipping: [osnode1.hetzlabs.io]
skipping: [osnode2.hetzlabs.io]
fatal: [osnode3.hetzlabs.io]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'openshift_hostname' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/playbooks/init/validate_hostnames.yml': line 13, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Validate openshift_hostname when defined\n    ^ here\n"}

NO MORE HOSTS LEFT ********************************************************************************************************************************
        to retry, use: --limit @/usr/share/ansible/openshift-ansible/playbooks/prerequisites.retry

PLAY RECAP ****************************************************************************************************************************************
infra.hetzlabs.io          : ok=21   changed=0    unreachable=0    failed=0
localhost                  : ok=11   changed=0    unreachable=0    failed=0
osmaster.hetzlabs.io       : ok=28   changed=0    unreachable=0    failed=0
osnode1.hetzlabs.io        : ok=21   changed=0    unreachable=0    failed=0
osnode2.hetzlabs.io        : ok=21   changed=0    unreachable=0    failed=0
osnode3.hetzlabs.io        : ok=21   changed=0    unreachable=0    failed=1
```

My hosts file
```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_release=3.9

containerized=true
openshift_install_examples=true
openshift_metrics_install_metrics=true
openshift_metrics_start_cluster=true

# use htpasswd authentication with demo/demo
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
openshift_master_htpasswd_users={'demo': '$apr1$.MaA77kd$Rlnn6RXq9kCjnEfh5I3w/.'}

# put the router on dedicated infra node
openshift_hosted_router_selector='region=infra'
openshift_master_default_subdomain=apps.hetzlabs.io

# put the image registry on dedicated infra node
openshift_hosted_registry_selector='region=infra'

# project pods should be placed on primary nodes
osm_default_node_selector='region=primary'

[masters]
osmaster.hetzlabs.io openshift_public_hostname="osmaster.hetzlabs.io"

[etcd]
osmaster.hetzlabs.io

[nodes]
# master needs to be included in the node to be configured in the SDN
osmaster.hetzlabs.io
infra.hetzlabs.io openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
osnode[1:3].hetzlabs.io openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
```
OS Info: CentOS 7.5 with latest updates, openshift-ansible from EPEL repo.

**Comment by michaelgugino** [comment]
@hetzbh looks like osnode3.hetzlabs.io is not resolvable on the host.  The error message would indicate that, but looks like we included an undefined variable in the error message we're trying to show users, and since it's undefined you get the undefined error message instead.

```
  - name: Validate openshift_hostname when defined
    fail:
      msg: >
        The hostname {{ openshift.common.hostname }} for {{ ansible_nodename }}
        doesn't resolve to an IP address owned by this host. Please set
        openshift_hostname variable to a hostname that when resolved on the host
        in question resolves to an IP address matching an interface on this host.
        This will ensure proper functionality of OpenShift networking features.
        Inventory setting: openshift_hostname={{ openshift_hostname }}
        This check can be overridden by setting openshift_hostname_check=false in
        the inventory.
        See https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-host-variables
    when:
    - lookupip.stdout != '127.0.0.1'
    - lookupip.stdout not in ansible_all_ipv4_addresses
    - openshift_hostname_check | default(true) | bool
```

**Comment by hetzbh** [comment]
Weird, it's surely resolvable on the master (where I run the ansible playbooks):

```
dig +short  osnode3.hetzlabs.io
192.168.0.43
[root@osmaster playbooks]# ping -c 1 osnode3
PING osnode3.hetzlabs.io (192.168.0.43) 56(84) bytes of data.
64 bytes from osnode3.hetzlabs.io (192.168.0.43): icmp_seq=1 ttl=64 time=0.264 ms

--- osnode3.hetzlabs.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.264/0.264/0.264/0.000 ms
[root@osmaster playbooks]# ping -c 1 osnode3.hetzlabs.io
PING osnode3.hetzlabs.io (192.168.0.43) 56(84) bytes of data.
64 bytes from osnode3.hetzlabs.io (192.168.0.43): icmp_seq=1 ttl=64 time=0.402 ms

--- osnode3.hetzlabs.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.402/0.402/0.402/0.000 ms
```

**Comment by michaelgugino** [comment]
@hetzbh should be resolvable from the node itself, as well.

**Comment by hetzbh** [comment]
You're right. Fixed ;)

**Comment by Kisen-Chin** [comment]
@hetzbh  @michaelgugino  Hi, I met this problem this too.
'''
TASK [Validate openshift_hostname when defined] *****************************************************************************************************************************
fatal: [master.cfetsit.com]: FAILED! => {"changed": false, "msg": "The hostname false for node1 doesn't resolve to an IP address owned by this host. Please set openshift_hostname variable to a hostname that when resolved on the host in question resolves to an IP address matching an interface on this host. This will ensure proper functionality of OpenShift networking features. Inventory setting: openshift_hostname=false This check can be overridden by setting openshift_hostname_check=false in the inventory. See https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-host-variables\n"}
fatal: [node1.cfetsit.com]: FAILED! => {"changed": false, "msg": "The hostname false for master doesn't resolve to an IP address owned by this host. Please set openshift_hostname variable to a hostname that when resolved on the host in question resolves to an IP address matching an interface on this host. This will ensure proper functionality of OpenShift networking features. Inventory setting: openshift_hostname=false This check can be overridden by setting openshift_hostname_check=false in the inventory. See https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-host-variables\n"}
'''
I'm using openshift origin 3.10. And the ansible playbook is downloaded using
'''
yum -y install \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo

yum -y --enablerepo=epel install ansible pyOpenSSL
'''

As I saw above, the node should be resolvable from itself. How can I configure this?
For me, when I type 
'''
dig +short master.cfetsit.com
'''
or 
'''
dig +short node1.cfetsit.com
'''
Nothing output for me.
'''
[support@master ~]$ dig +short master.cfetsit.com
[support@master ~]$ dig +short node1.cfetsit.com
[support@master ~]$ 
'''
Could you two please give me some help about this issue. Thanks!

**Comment by michaelgugino** [comment]
@Kisen-Chin You need to have real dns for your node's hostnames.

**Comment by Kisen-Chin** [comment]
@michaelgugino Hi,
I remember that when I install openshift origin 3.9, I didn't use any so called "real dns", I just set the IP:HOSTNAME in /etc/hosts file. Why in okd 3.10, I need to set up a real dns?
