### ISSUE TITLE
patch module needs to be back ported for OCP < 3.10 for openshift/origin-ansible

### ISSUE THREAD

**Issue by pruan-rht** [openshift/openshift-ansible#8745]
#### Description
According to the requirements for installation, the patch module is needed.  For OCP >= 3.10, it is there in the docker image.  For OCP < 3.10, that module is not there for  openshift/origin-ansible  The openshift3/ose-ansible has that patch, it's the master version that is missing that module.

##### Version

OCP < 3.10

**Comment by vrutkovs** [comment]
This has been backported in https://github.com/openshift/openshift-ansible/pull/8421. There is no new 3.9 release yet though
