### ISSUE TITLE
specify a build server

### ISSUE THREAD

**Issue by eyhanna** [openshift/openshift-ansible#8776]
hello i am trying to specify one server to run build, so as by the documentation i have changed to master config adding  nodeSelector under buildoverride and builddefault. as the following

admissionConfig:
  pluginConfig:
    BuildDefaults:
      configuration:
        apiVersion: v1
        env: []
        kind: BuildDefaultsConfig
        nodeSelector:
          build-node: true
        resources:
          limits: {}
          requests: {}
    BuildOverrides:
      configuration:
        apiVersion: v1
        kind: BuildOverridesConfig
        nodeSelector:
          build-node: true
    PodPreset:

and i have labeled a node with the region=primary and build-node=true
than i have created a project with default node-selector  region=primary
when i create a new application inside the project not pod-build run

is it a bug?

#### Description

Provide a brief description of your issue here. For example:

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by eyhanna** [comment]
hello,

thanks a lot for your answer, actually i am trying to have a specific build server i have 2 nodes both of them region=infra and the default nodeselector  is region=infra


and i have node2 labeled as build-node=true

also i have tainted node2 as the following

 oc adm taint node node.xxxxx.com build-node=true:NoSchedule



and i have edited my master config file to have


admissionConfig:
  pluginConfig:
    BuildDefaults:
      configuration:
        apiVersion: v1
        env: []
        kind: BuildDefaultsConfig
        nodeSelector:
          build-node: "true"
        annotations:
     scheduler.alpha.kubernetes.io/taints: '[{"key": "build-node","value": "true","effect": "NoSchedule"}]'
        resources:
          limits: {}
          requests: {}
    BuildOverrides:
      configuration:
        apiVersion: v1
        kind: BuildOverridesConfig
        nodeSelector:
          build-node: "true"



i expects to all my build runs on node2 and all my pod run on node1 but even my builds are not running. if i remove the annotations and the taints my build run on node2 but also some of my pods run on node2.

thanks again for your help

________________________________

**Comment by eyhanna** [comment]
as i saw that the alpa annotations are not supported anymore and as i am running on version 3.9

i tried the following also with no luck


admissionConfig:
  pluginConfig:
    BuildDefaults:
      configuration:
        apiVersion: v1
        env: []
        kind: BuildDefaultsConfig
        nodeSelector:
          build-node: "true"
        resources:
          limits: {}
          requests: {}
    BuildOverrides:
      configuration:
        apiVersion: v1
        kind: BuildOverridesConfig
        nodeSelector:
          build-node: "true"
        tolerations:
        - key: "build-node"
          value: "true"
          effect: "NoSchedule"
          operator: "Equal"
    PodPreset:
      configuration:
        apiVersion: v1
        disable: false
        kind: DefaultAdmissionConfig
    openshift.io/ImagePolicy:
      configuration:
        apiVersion: v1
        executionRules:
        - matchImageAnnotations:
          - key: images.openshift.io/deny-execution
            value: 'true'
          name: execution-denied




________________________________

**Comment by vrutkovs** [comment]
It seems ansible is generating a correct BuildOverrides section, so I guess its an Origin issue, please file a new bug in `openshift/origin` repository

**Comment by eyhanna** [comment]
thanks for your help vrutkovs.  it works with the playbook
