### ISSUE TITLE
Can't list aws instances

### ISSUE THREAD

**Issue by cw1** [openshift/openshift-ansible#879]
Using following command:
`bin/cluster -v list aws ''`
Output:

```
Traceback (most recent call last):
  File "bin/cluster", line 341, in <module>
    args.func(args)
  File "bin/cluster", line 89, in list
    playbook = "playbooks/{}/openshift-cluster/list.yml".format(args.provider)
ValueError: zero length field name in format
```

Version from git commit 597ba24415d6b7faa7ca02d200c8aed3c08b925a

**Comment by detiber** [comment]
@twiest related to the aws inventory script change?

**Comment by twiest** [comment]
@detiber that change hasn't been merged, it's still an open PR, so I don't think so.

This seems like a creds issue. @cw1 did you either put your creds in your environment, or in the ec2.ini file?

@cw1 try running the ec2 inventory by itself like this:
```
inventory/aws/hosts/ec2.py --list
```

It's an auth issue if it errors with:
```
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
```

**Comment by cw1** [comment]
Performing:
```
inventory/aws/hosts/ec2.py --list
```
Seems to work:
```
{
  "_meta": {
    "hostvars": {}
  }
}
```

**Comment by twiest** [comment]
@cw1 ah, I think it's because we aren't expecting 0 instances.

@cw1 I'm assuming that the output is what you expect (you have 0 instances in that account), right?

@detiber I think this is a real bug. It's probably been in there for awhile.

**Comment by detiber** [comment]
On further review, it looks like the error is that args.provider isn't being set right.

@cw1 what version of python are you running? I'm wondering if different versions of python may parsing the arguments differently.

**Comment by detiber** [comment]
@cw1 bin/cluster with the arguments you passed should be invoking ansible-playbook as follows:
`ansible-playbook -v -i inventory/aws/hosts  playbooks/aws/openshift-cluster/list.yml -e "cluster_id='' deployment_type=origin"`

There shouldn't be any issues related to the inventory being returned being empty (since we are listing localhost in a static inventory file in the inventory/aws/hosts directory).

**Comment by cw1** [comment]
Using python 2.6.6 on centos 6.7
@twiest Yes, there are 0 running instances (only stopped ones)

**Comment by detiber** [comment]
@cw1 ah, I suspect the issue may be with the backported version of argparse and python 2.6.

Any possibility of running under python 2.7?

**Comment by cw1** [comment]
FWIW, trying python 2.7 now
```
[christian@Chris-NB openshift-ansible]$ bin/cluster -v list aws ''
Namespace(action='list', cluster_id='', deployment_type=None, func=<bound method Cluster.list of <__main__.Cluster object at 0x1864e10>>, option=None, product_type=None, profile=False, provider='aws', verbose=1)
Traceback (most recent call last):
  File "bin/cluster", line 342, in <module>
    args.func(args)
  File "bin/cluster", line 90, in list
    playbook = "playbooks/{}/openshift-cluster/list.yml".format(args.provider)
ValueError: zero length field name in format
[christian@Chris-NB openshift-ansible]$ git diff
diff --git a/bin/cluster b/bin/cluster
index 59a6755..56c5c21 100755
--- a/bin/cluster
+++ b/bin/cluster
@@ -86,6 +86,7 @@ class Cluster(object):
         """
         env = {'cluster_id': args.cluster_id,
                'deployment_type': self.get_deployment_type(args)}
+        print(args)
         playbook = "playbooks/{}/openshift-cluster/list.yml".format(args.provider)
         inventory = self.setup_provider(args.provider)
```

**Comment by menren** [comment]
Got the exact same error on AWS with python 2.6.9. AWS creds are given correctly. It was working with an old revision of openshift-ansible

**Comment by detiber** [comment]
@abutcher I believe your python-fu is greater than mine. Any ideas?

**Comment by detiber** [comment]
@jwhonce maybe you can take a look?

**Comment by abutcher** [comment]
@cw1 Can you try with this diff?

```
$ git diff
diff --git a/bin/cluster b/bin/cluster
index 59a6755..c30b96e 100755
--- a/bin/cluster
+++ b/bin/cluster
@@ -57,7 +57,7 @@ class Cluster(object):
         """
         env = {'cluster_id': args.cluster_id,
                'deployment_type': self.get_deployment_type(args)}
-        playbook = "playbooks/{}/openshift-cluster/launch.yml".format(args.provider)
+        playbook = "playbooks/{0}/openshift-cluster/launch.yml".format(args.provider)
         inventory = self.setup_provider(args.provider)
 
         env['num_masters'] = args.masters
```

**Comment by jwhonce** [comment]
@twiest Because of issues with the gce libraries there is a stopped vm on GCE named jhonce-do-not-delete to prevent 0 instance failures.  I never worked on the AWS code so I don't know if the same issue exists in that library.

**Comment by abutcher** [comment]
This is failing before it even does anything. Checking an empty or invalid cluster_id on AWS should result in the following:

```
$ bin/cluster -v list aws 'hurp'
RUN [ansible-playbook -v -i inventory/aws/hosts -e 'cluster_id=hurp deployment_type=origin' playbooks/aws/openshift-cluster/list.yml]
   
PLAY [Generate oo_list_hosts group] ******************************************* 

TASK: [set_fact scratch_group=tag_env_{{ cluster_id }}] *********************** 
ok: [localhost] => {"ansible_facts": {"scratch_group": "tag_env_hurp"}}

TASK: [set_fact scratch_group=all] ******************************************** 
skipping: [localhost]

TASK: [add_host ] ************************************************************* 
skipping: [localhost]

PLAY [List Hosts] ************************************************************* 
skipping: no hosts matched

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

I think this is failing because python 2.6 requires field numbers w/ format. The field names/numbers can be omitted post 2.7.

**Comment by cw1** [comment]
@abutcher I've tried your diff, but still same behavior with python 2.6.6.

**Comment by detiber** [comment]
@cw1 it looks like @abutcher's diff was for the create method and not the list method in bin/cluster.

I created a PR to address this for all of the subcommands: https://github.com/openshift/openshift-ansible/pull/899

**Comment by abutcher** [comment]
Derp nice @detiber

**Comment by cw1** [comment]
@detiber Still not working with python 2.6.6 on Centos 6 but working on python 2.7.10 on Fedora 23.

**Comment by abutcher** [comment]
@cw1 Does it fail on the exact same line? I see more format's used in `bin/cluster` - opened #927 to cover the rest.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
