### ISSUE TITLE
OpenStack playbooks fail with `openshift_node_group_name must be defined for all nodes`

### ISSUE THREAD

**Issue by mbruzek** [openshift/openshift-ansible#8799]
#### Description

Running the `playbooks/opentack/provision_install.yml` playbook fails because `openshift_node_group_name` is not set on the cns nodes.

This check has been introduced in #8639. Addressed in #8683 but needs additional work for cns nodes.

##### Version

* Your ansible version per `ansible --version`:  ansible 2.4.3.0

* The output of `git describe`: openshift-ansible-3.10.0-0.63.0-134-g01ac2f2

Place the output between the code block below:

```
ansible 2.4.3.0

$ git describe
openshift-ansible-3.10.0-0.63.0-134-g01ac2f2
```

##### Steps To Reproduce
1. Install OpenShift on OpenStack following the [readme](https://github.com/openshift/openshift-ansible/tree/master/playbooks/openstack) 

##### Expected Results
I expected the playbook to complete successfully.

##### Observed Results
Describe what is actually happening.

```
TASK [Validate openshift_node_groups and openshift_node_group_name] ************
task path: /home/cloud-user/openshift-ansible/playbooks/init/sanity_checks.yml:18
Friday 15 June 2018  16:23:13 -0400 (0:00:04.305)       0:02:39.834 *********** 
fatal: [master-0.scale-ci.example.com]: FAILED! => {
    "msg": "last_checked_host: cns-1.scale-ci.example.com, last_checked_var: openshift_node_group_name;openshift_node_group_name must be defined for all nodes"
}
```

##### Additional Information

The OpenStack situation is difficult to resolve this error because we are using the dynamic inventory in `openshift-ansible/playbooks/openstack/inventory.py`  and can not easily add values to groups of nodes.

I spoke with @michaelgugino about this and he instructed me to create files in `inventory/group_vars/` directory like this: 
```
inventory/
          dynamic_inventory.py
          group_vars/
                     OSEv3.yml
                     masters.yml
                     app.yml
                     infra_hosts.yml
```
I did this but also created a `glusterfs.yml` file with "openshift_node_group_name: node-config-compute
" but the cns nodes still come back with no group name. 

I suspect this is a bug and we need to change the dynamic inventory to give group names to the cns nodes as well.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```
[dynamic inventory](https://github.com/openshift/openshift-ansible/blob/master/playbooks/openstack/inventory.py)

I wrote a small playbook that shows this problem:
```yaml
---
- name: This playbook prints a group.
  hosts: localhost
  tasks:
    - name: Print group information
      debug:
        msg: "{{ hostvars[item]['openshift_node_group_name'] }}"
      with_items: "{{ groups['glusterfs'] }}"

    - name: Print group information
      debug:
        msg: "{{ hostvars[item]['openshift_node_group_name']}}"
      with_items: "{{ groups['masters'] }}"
```
When this program runs: `ansible-playbook -vv -i inventory/ -i openshift-ansible/playbooks/openstack/inventory.py print_group.yml ` (with multiple inventory options as we run the provision playbook) it shows me that the openshift_node_group_name is empty even when I have a `glusterfs.yml` file in the `group_vars` directory.

**Comment by tomassedovic** [comment]
Right, I can fix this. I didn't realise the CNS nodes are also treated as OpenShift nodes and need a group.

So you'd like to set their group name to `node-config-compute`, right?

**Comment by mbruzek** [comment]
> So you'd like to set their group name to node-config-compute, right?
Correct that is how I set them in the glusterfs.yml group file.
