### ISSUE TITLE
last_checked_host: master.example.com, last_checked_var: openshift_node_group_name;openshift_node_group_name must be defined for all nodes

### ISSUE THREAD

**Issue by ggnanasekaran77** [openshift/openshift-ansible#8819]
#### Trying to Setup One Master One Node and One Infra Node

Provide a brief description of your issue here. For example:

> last_checked_host: master.example.com, last_checked_var: openshift_node_group_name;openshift_node_group_name must be defined for all nodes

##### Version

`[root@master openshift-ansible]# ansible --version
ansible 2.5.3
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
[root@master openshift-ansible]#`

```
[root@master openshift-ansible]# cat inventory/hosts
# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become=true

openshift_deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

# host group for masters
[masters]
master.example.com

# host group for etcd
[etcd]
master.example.com

# host group for nodes, includes region info
[nodes]
master.example.com
node1.example.com openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
infra-node1.example.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
[root@master openshift-ansible]#
```

**Comment by vrutkovs** [comment]
This is required now, see https://github.com/openshift/openshift-ansible/pull/8639
