### ISSUE TITLE
 "msg": "No package matching 'origin-node-3.10*' found available

### ISSUE THREAD

**Issue by debianmaster** [openshift/openshift-ansible#8888]
#### Description

TASK [openshift_node : Install node, clients, and conntrack packages] *********************************************************
Thursday 21 June 2018  08:17:17 +0000 (0:00:00.392)       0:00:52.116 *********
FAILED - RETRYING: Install node, clients, and conntrack packages (3 retries left).
FAILED - RETRYING: Install node, clients, and conntrack packages (2 retries left).
FAILED - RETRYING: Install node, clients, and conntrack packages (1 retries left).
failed: [localhost] (item={u'name': u'origin-node-3.10*'}) => {"attempts": 3, "changed": false, "item": {"name": "origin-node-3.10*"}, "msg": "No package matching 'origin-node-3.10*' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-node-3.10*' found available, installed or updated"]}
FAILED - RETRYING: Install node, clients, and conntrack packages (3 retries left).
FAILED - RETRYING: Install node, clients, and conntrack packages (2 retries left).

##### Version

release-3.10

[root@master1 openshift-ansible]# ansible --version
ansible 2.5.5

[root@master1 openshift-ansible]# git describe
v3.10.0-rc.0

##### Steps To Reproduce
```
    ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml
    ansible-playbook -i inventory/hosts.localhost playbooks/deploy_cluster.yml
```

##### Expected Results
All in one openshift should be installed

```
Example command and output or error messages
```

##### Observed Results

```
No package matching 'origin-node-3.10*' found
```

##### Additional Information

```yaml
[OSEv3:vars]
# if your target hosts are Fedora uncomment this
#ansible_python_interpreter=/usr/bin/python3
openshift_deployment_type=origin
openshift_portal_net=172.30.0.0/16
# localhost likely doesn't meet the minimum requirements
openshift_disable_check=disk_availability,memory_availability
openshift_repos_enable_testing=true
openshift_enable_excluders=false
openshift_additional_repos=[{'id': 'openshift-origin-copr', 'name': 'OpenShift Origin COPR', 'baseurl': 'https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/epel-7-$basearch/', 'enabled': 1, 'gpgcheck': 1, 'gpgkey': 'https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/pubkey.gpg'}]
containerized=true
openshift_node_groups=[{'name': 'node-config-all-in-one', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]


[masters]
localhost ansible_connection=local

[etcd]
localhost ansible_connection=local

[nodes] 
# openshift_node_group_name should refer to a dictionary with matching key of name in list openshift_node_groups.
localhost ansible_connection=local openshift_node_group_name="node-config-all-in-one"
```

**Comment by vrutkovs** [comment]
Does it work with pre-release CentOS builds at https://cbs.centos.org/repos/paas7-openshift-origin310-candidate/x86_64/os/Packages/ ?

**Comment by debianmaster** [comment]
i will give a try

**Comment by debianmaster** [comment]
failed with ` master1 origin-node[29090]: /usr/local/bin/openshift-node: line 17: /usr/bin/openshift-node-config: No such file or directory`

**Comment by leifmadsen** [comment]
I actually have the same issue with Origin 3.9 as well:

```

**Comment by vrutkovs** [comment]
`/usr/bin/openshift-node-config: No such file or directory`
@DanyC97 is there a tracking issue for 'CentOS builds don't include openshift-node-config`? The builds our CI is producing this binary is there - i.e. https://storage.googleapis.com/origin-ci-test/logs/test_branch_origin_extended_conformance_gce_310/3/artifacts/rpms

**Comment by leifmadsen** [comment]
Yea I just noticed that openshift-ansible doesn't install the `centos-release-openshift-origin39` package, which results in the installation progressing...

**Comment by DanyC97** [comment]
yes, i'm working on @vrutkovs , expect to have new rpms announced early next week on openshift dev mailer

**Comment by DanyC97** [comment]
@debianmaster @leifmadsen i'd suggest to close this issue in favour of https://github.com/openshift/openshift-ansible/issues/8550

**Comment by debianmaster** [comment]
closing in favor of #8550
