### ISSUE TITLE
No module named yaml

### ISSUE THREAD

**Issue by onknows** [openshift/openshift-ansible#8951]
#### Description

Provision of cluster fails on message No module named yaml. This is the second GitHub Ansible OpenShift project that I came across that bases provision on module yaml without including the installation of this module. So provision fails fails with message similar to 

```
TASK [Gather Cluster facts] ***************************************************************************************************************************************************************************************
Sunday 24 June 2018  20:36:21 +0000 (0:00:02.169)       0:01:29.101 *********** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named yaml
fatal: [master0]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_pEo4Oa/ansible_module_openshift_facts.py\", line 15, in <module>\n    import yaml\nImportError: No module named yaml\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by onknows** [comment]
I can btw install it on bastion using pip install pyyaml. This doesn't fix the issue obviously.

**Comment by hostingnuggets** [comment]
@srgvg same problem here and it's easy to explain: just install CentOS 7 with the core packages and you will see that the `pyyaml` package is part of the core packages and hence not installed.

**Comment by michaelgugino** [comment]
openshift-ansible/playbooks/init/base_packages.yml ensures PyYAML package is installed on all nodes.  Most likely, you didn't run prerequisites.yml before running deploy_cluster.yml.
