### ISSUE TITLE
Updating atomic-openshift-utils didn't update openshift-ansible* pkgs

### ISSUE THREAD

**Issue by adellape** [openshift/openshift-ansible#896]
Installing `atomic-openshift-utils` from scratch does successfully pull in `ansible` and the `openshift-ansible*` packages automatically:

https://gist.github.com/adellape/d503e23c7362eb14c550

However, on a system that already had it installed, I tried updating `atomic-openshift-utils` because I knew there was a newer version available, and expected it to automatically update the `openshift-ansible*` packages along with it, but it didn't and I had to follow-up with a `yum update openshift-ansible*`:

https://gist.github.com/adellape/d202dea99cd7ffcd6674

Maybe it was just the older package I was on was before those dependencies were put in or something (`atomic-openshift-utils.noarch 0:3.0.12-1.git.0.4c09c5b.el7aos`), but opening this just in case.

**Comment by detiber** [comment]
The spec file doesn't set the version in the requires for the subpackages.

It shouldn't be an issue for the first release, but we'll want to address it for the async release. @brenton

**Comment by sdodson** [comment]
I think this was fixed via #959
