### ISSUE TITLE
Origin v3.7 to v3.9 Upgrade - Web Console Error

### ISSUE THREAD

**Issue by lajchon** [openshift/openshift-ansible#8983]
#### Description

Previous install of OpenShift Origin v3.7. Upgraded control-plane first. Ansible playbooks fail while waiting for webconsole Pods to startup.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Observed Results
Describe what is actually happening.

```
/usr/bin/origin-web-console: error while loading shared libraries: libpthread.so.0: cannot open shared object file: Permission denied
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.5
```
EXTRA INFORMATION GOES HERE
```

**Comment by vrutkovs** [comment]
This is caused by a wrong selinux label for this container.

Make sure you have latest updates installed and run `restorecon -R /var/lib/docker`
