### ISSUE TITLE
Ensure support for identity provider mappingMethod

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#900]
https://github.com/openshift/origin/pull/5060 added a new configuration field named `mappingMethod` to all identity providers (peer to the `login` and `challenge` fields). The default value is `claim`, which means identities from the provider will map to a user with their preferred username unless it is already mapped to a different identity.

* **lookup**
  * Administrator wants to manually configure identity/user mappings. Login process should only look up existing mappings, not create them
* **generate**
  * Provision with generation of unique usernames (e.g. "bob", "bob2")
  * This strategy should not be used in combination with LDAP group sync
* **claim** (default)
  * Provision with deterministic username, fail if username is already mapped to another identity
* **add**
  * Provision with deterministic username, add to existing user if username is already mapped to another identity
  * Needed when multiple identity providers are configured which identity the same set of users and map to the same usernames

Ensure `mappingMethod` can be set as part of an identity provider JSON snippet (I think it can)

In the future, consider setting the `mappingMethod` to `add` for any installations where we set up multiple identity providers that are all addressing the same set of identities.

**Comment by detiber** [comment]
@liggitt is the limitation of only having a single identity provider configured for login=true still the case?

**Comment by liggitt** [comment]
@detiber yes, still true

**Comment by liggitt** [comment]
this is useful now in the following scenarios:
1. they want to use one provider for web login (login: true) and one for CLI auth (challenge: true), but map identities from both providers to the same set of users
2. they want to change identity providers, and map identities from the new provider to users that were originall provisioned under the old one (e.g. anypassword -> htpasswd)

**Comment by detiber** [comment]
@liggitt thanks, taking this time to do some validation on openshift_master_identity_providers as well

**Comment by detiber** [comment]
@brenton this can be closed
