### ISSUE TITLE
No package matching 'atomic-openshift-docker-excluder-3.10**' found available, installed or updated

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-ansible#9010]
Happens in the azure 3.10 jobs

https://ci.openshift.redhat.com/jenkins/job/azure_build_node_image_rhel_310/4/consoleFull#211314771258b6e51eb7608a5981914356
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_azure_310/56/consoleFull#-20592301058b6e51eb7608a5981914356

@openshift/sig-azure 

@sdodson any ideas?

**Comment by jim-minter** [comment]
https://github.com/openshift/openshift-ansible/blob/release-3.10/playbooks/azure/openshift-cluster/group_vars/all/yum_repos.yml#L50 needs to be uncommented and until GA needs to refer to https://mirror.openshift.com/enterprise/enterprise-3.10/latest/x86_64/os

Then need to ensure that the node image is also pointing to the pre-release docker registry

**Comment by jim-minter** [comment]
It's almost tempting not to bother building RHEL 3.10 images until we actually GA...

**Comment by mjudeikis** [comment]
https://github.com/openshift/aos-cd-jobs/pull/1518
https://github.com/openshift/openshift-ansible/pull/9148

**Comment by mjudeikis** [comment]
https://github.com/openshift/openshift-azure/issues/163 we have similar on for origin now. `origin_release.yml` published docker-excluder with 3.11
