### ISSUE TITLE
How do I submit a PR to have a template and imagestream updated for v3.9

### ISSUE THREAD

**Issue by luck3y** [openshift/openshift-ansible#9074]
#### Description

We'd like to update EAP CD to v 13 in the OS 3.9 examples. I have an existing PR for master here: https://github.com/openshift/openshift-ansible/pull/9063

The updated templates and streams are here: https://github.com/jboss-container-images/jboss-eap-7-openshift-image/tree/eap-cd/templates

**Comment by vrutkovs** [comment]
You'd need to file a new PR against `release-3.9` branch.

In case there is no changes to the code (e.g. filenames or contents) are required, we could cherrypick the master PR to any other branch with a bot command

**Comment by luck3y** [comment]
@vrutkovs, can I do the bot cherry-pick, or is that something you'd have to do?

**Comment by vrutkovs** [comment]
@luck3y yep, `/cherrypick release-3.9` would create a new PR.

Not sure if this applies to this PR though, probably paths would need to be altered

**Comment by luck3y** [comment]
Thanks for all the help, as always, @vrutkovs! I'll close this.
