### ISSUE TITLE
Ensure pre-upgrade steps are run using admin kubeconfig

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#908]
The preupgrade scripts need to add --config=/etc/origin/master/admin.kubeconfig in order to ensure they're run with cluster admin rights as the user that ansible uses may have logged in as a different user.

https://github.com/openshift/openshift-ansible/blob/master/playbooks/common/openshift-cluster/upgrades/files/pre-upgrade-check#L64

@adellape found this

**Comment by detiber** [comment]
@sdodson We have to be careful about using the admin kubeconfig...  If we do anything that requires changing the user or project we can still get into trouble.

That said, what we should really be doing is copying the admin kubeconfig to a temporary location (with secure permissions, of course) and then using our copy.

**Comment by dgoodwin** [comment]
So if one were looking for any usages of cli tools without kube config, what would you grep for?

I see openshift.common.admin_binary and client_binary, any others that I might miss?

**Comment by detiber** [comment]
@dgoodwin all uses should be using those variables, but it is possible there may be some hardcoded references to oadm or oc layting around.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
