### ISSUE TITLE
openshift_logging_es_memory_limit is 16Gi in README.md now

### ISSUE THREAD

**Issue by juzhao** [openshift/openshift-ansible#9103]
openshift_logging_es_memory_limit in roles/openshift_logging/README.md is 16Gi now, doc should be updated

**Comment by juzhao** [comment]
default value for openshift_logging_es_ops_memory_limit is also 16Gi now

**Comment by patlachance** [comment]
It was integrated in https://github.com/openshift/openshift-docs/commit/e9bee7e19cbfeb8780e6e76e28d9fe8b346be70e and thus, this issue could be closed!
