### ISSUE TITLE
AWS: export ec2_instance_type='t2.micro' has no effect

### ISSUE THREAD

**Issue by cw1** [openshift/openshift-ansible#915]
Using the enviroment variable ec2_instance_type (='t2.micro') has no effect (ansible still launches m4.large instances). Python version is 2.7.10 (Fedora 23).

Using openshift-ansible from git, commit 426aa0a1613bdfc5547abde43ab1130ba027126e.

**Comment by sils1297** [comment]
@cw1 looking at https://github.com/openshift/openshift-ansible/search?utf8=%E2%9C%93&q=m4.large there seem to be some configuration yml files for those clusters, maybe we need to provide own yml files for that? Maybe we can workaround at least for now by changing those yml files?

**Comment by cw1** [comment]
Changing deployment vars in playbooks/aws/openshift-cluster/vars.yml is working.

**Comment by detiber** [comment]
@cw1 was just getting ready to recommend that.

**Comment by detiber** [comment]
A proper solution would be to check the env var ec2_{master,node,etcd,infra}_instance_type to allow overriding via environment is possible for the different host types.

I'm going to throw together a pr to show what I'm thinking.

**Comment by detiber** [comment]
Only tested for syntax errors so far: https://github.com/openshift/openshift-ansible/pull/918

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
