### ISSUE TITLE
Provisioning on aws using bin/cluster fails with a timeout on starting docker on master host

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#916]
The master instance does not have a separate docker volume like the node instances do and lvm-loop provisioning causes the docker daemon to timeout on first start, which then causes the subsequent configuration of the cluster to fail.

**Comment by detiber** [comment]
Previous discussion of this issue: https://github.com/openshift/openshift-ansible/pull/862#issuecomment-157400973

@menren

**Comment by detiber** [comment]
@menren in addition to the changes you proposed for playbooks/aws/openshift-cluster/tasks/launch_instances.yml

The following changes would also be needed:
- filter_plugins/oo_filters.py - oo_ec2_volume_definition would need to be updated to add the docker volume you specified to conditionally perform the operations on the docker volume for a host_type of master as well.
- https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/openshift-cluster/templates/user_data.j2#L22-L34 needs to be updated to configure the mount and docker-storage-setup config for master hosts.

**Comment by abutcher** [comment]
@brenton Please close - fixed in #933
