### ISSUE TITLE
Support multiple cluster networks

### ISSUE THREAD

**Issue by luxifr** [openshift/openshift-ansible#9173]
According to the docs, multiple cluster networks can be configured in the master-config.yaml. However, the current Ansible playbook/templates only support setting exactly one CIDR address for this configuration item, which limits changes to an existing cluster to extending the original network.

This forces a choice between continue being able to manage the config of an already deployed cluster using ansible and the ability to add additional networks, which might be required if the original network cannot be expanded or when wanting to migrate to another network.

The playbook should allow for a list of CIDRs instead of a single CIDR for clusterNetworks.

**Comment by akram** [comment]
It looks like #10019 proposed to fix this issue but it has not been merged.

**Comment by akram** [comment]
Here is dirty workaround for people facing the issue:

Use a group_vars/OSEv3.yml file
```
---                                                                                                                                                                       │··
osm_cluster_networks: |-                                                                                                                                                  │··
  10.128.0.0/14                                                                                                                                                           │··
      hostSubnetLength: 9                                                                                                                                                 │··
    - cidr: 10.192.0.0/14                                                                                                                                                 │··
      hostSubnetLength: 9                                                                                                                                                 │··
    - cidr: 10.224.0.0/14```
