### ISSUE TITLE
How to deploy cockpit after cluster setup?

### ISSUE THREAD

**Issue by markusdd** [openshift/openshift-ansible#9239]
I just noticed cockpit was not deployed by default in 3.9.
Packages are not there on any node and no one is home at :9090

As far as I understand running deploy_cluster again is a bad idea, so how to deploy it then?
I could not find a playbook for it and just running the role obviously does not work.
I have now added osm_use_cockpit=true to my inventory file.

Any hints on that one?

EDIT:
Could it be that running the additional_config playbook from nodes and master would be correct? But this will not work, as I have deployment type origin. Why is cockpit strictly type_enterprise? I mean the packages are available?! Is there any specific reason why this is the case?

**Comment by markusdd** [comment]
If you read my EDIT from above, I wrote my deployment type is origin. But I see no point why it would only deploy on enterprise.

Ich manually patched the role and it deployed perfectly now, but still I would like to see this check removed. Or is there any specific reason why it would only deploy on enterprise? I couldn't find one...

**Comment by nagonzalez** [comment]
Ahh, sorry about that. Missed your EDIT. I tried searching for a reason to exclude cockpit deployment on origin but couldn't find one.

**Comment by markusdd** [comment]
Ok then, so we're already 2^^
I guess then this turns into a request to remove this check.

**Comment by medined** [comment]
+1 to remove the check. Or provide instructions how to install cockpit a different way, please.

**Comment by fahmifahim** [comment]
I searched on the related article but still not finding clear explanation about the function of "cockpit" on OpenShift Enterprise. 
Is there any reference about "cockpit" and why we should deploy it on Enterprise OpenShift?
