### ISSUE TITLE
3.9 Ansible Install: FAIL API didn't become available

### ISSUE THREAD

**Issue by egkelly** [openshift/openshift-ansible#9269]
#### Description

Installing 3.9 on 2 masters with cohosted etcd, load balancer, 1 infra, 2 nodes. Ansible install fails during "Wait for API to become available." Each host is running Rhel Server 7.4

##### Version
ansible 2.6.0
openshift-ansible 3.9: zip downloaded from github.

##### Steps To Reproduce
1. ansible-playbook ~/openshift/playbooks/prerequisites.yml --ask-pass
2. ansible-playbook ~/openshift/playbooks/deploy-cluster.yml --ask-pass

##### Expected Results
OpenShift installs without issues

Here is my current configuration:

/etc/ansible/hosts

>[OSEv3:children]
>masters
>nodes
>etcd
>lb
>
>[OSEv3:vars]
>ansible_ssh_user=root
>openshift_deployment_type=origin
>
>openshift_master_cluster_method=native
>openshift_master_cluster_hostname=cluster.example.com
>openshift_master_cluster_public_hostname=cluster.example.com
>
>openshift_master_default_subdomain=example.com
>containerized=false
>
>#custom certificates
>openshift_master_named_certificates=[{"certfile": "/etc/ssl/certs/my.cer", "keyfile": "/etc/ssl/private/my.key"}]
>openshift_master_overwrite_named_certficates=true
>
>#enable logging
>openshift_logging_install_logging=true
>
>#private registry
>openshift_docker_additional_registries=myregistry.example.com:8080
>
>#proxy
>openshift_http_proxy=http://proxy.example.com:80
>openshift_https_proxy=http://proxy.example.com:80
>openshift_no_proxy='127.0.0.1,localhost,*.example.com,xxx.xxx.0.0/16,xxx.xxx.0.0/16,.cluster.local,.svc'
>
>#host group for masters
>[masters]
>master1.example.com
>master2.example.com
>
>#host group for etcd
>[etcd]
>master1.example.com
>master2.example.com
>
>#load balancer host
>[lb]
>cluster.example.com
>
>#host group for nodes
>[nodes]
>master1.example.com openshift_node_labels="{'region': 'master', 'zone': 'default'}"
>master2.example.com openshift_node_labels="{'region': 'master', 'zone': 'default'}"
>node1.example.com openshift_node_labels="{'region': 'compute', 'zone': 'default'}"
>node2.example.com openshift_node_labels="{'region': 'compute', 'zone': 'default'}"
>infra.example.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
` 

Here are the issues I'm seeing:

>TASK [openshift_master : Dump verbose curl output when the API didn't become available] >***************************************************************************************************************************
>ok: [master1.example.com] => {
>    "msg": [
>        "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", 
>        "                                 Dload  Upload   Total   Spent    Left  Speed", 
>        "", 
>        "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to proxy proxy-example.com port 80 (#0)", 
>        "*   Trying xxx.xxx.xxx.xxx...", 
>       "* Connected to proxy-example.com (xxx.xxx.xxx.xxx) port 80 (#0)", 
>        "* Establish HTTP proxy tunnel to cluster.example.com:8443", 
>        "> CONNECT cluster.example.com:8443 HTTP/1.1", 
>        "> Host: cluster.example.com:8443", 
>        "> User-Agent: curl/7.29.0", 
>        "> Proxy-Connection: Keep-Alive", 
>        "> ", 
>        "< HTTP/1.1 503 Service Unavailable", 
>        "< Cache-Control: no-cache", 
>        "< Pragma: no-cache", 
>        "< Content-Type: text/html; charset=utf-8", 
>        "< Proxy-Connection: close", 
>        "< Connection: close", 
>        "< Content-Length: 803", 
>        "< ", 
>        "* Received HTTP code 503 from proxy after CONNECT", 
>        "", 
>        "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0", 
>        "* Connection #0 to host proxy-example.com left intact", 
>        "curl: (56) Received HTTP code 503 from proxy after CONNECT"
>    ]
>}
>ok: [master2.example.com] => {
>    "msg": [
>        "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", 
>        "                                 Dload  Upload   Total   Spent    Left  Speed", 
>        "", 
>        "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to proxy proxy-example.com port 80 (#0)", 
>        "*   Trying xxx.xxx.xxx.xxx...", 
>        "* Connected to proxy-example.com (xxx.xxx.xxx.xxx) port 80 (#0)", 
>        "* Establish HTTP proxy tunnel to cluster.example.com:8443", 
>        "> CONNECT cluster.example.com:8443 HTTP/1.1", 
>        "> Host: cluster.example.com:8443", 
>        "> User-Agent: curl/7.29.0", 
>        "> Proxy-Connection: Keep-Alive", 
>        "> ", 
>        "< HTTP/1.1 503 Service Unavailable", 
>        "< Cache-Control: no-cache", 
>        "< Pragma: no-cache", 
>        "< Content-Type: text/html; charset=utf-8", 
>        "< Proxy-Connection: close", 
>        "< Connection: close", 
>        "< Content-Length: 803", 
>        "< ", 
>        "* Received HTTP code 503 from proxy after CONNECT", 
>        "", 
>        "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0", 
>        "* Connection #0 to host proxy-example.com left intact", 
>        "curl: (56) Received HTTP code 503 from proxy after CONNECT"
>    ]
>}

**Comment by andeq4q** [comment]
I'm having the same issue.  Has there been any luck resolving this?

**Comment by egkelly** [comment]
No luck so far. I haven't been able to figure out what's causing it.

**Comment by amelie1979** [comment]
Dont set theses 2 variable on the same name 
openshift_master_cluster_hostname=cluster.example.com
openshift_master_cluster_public_hostname=cluster.example.com

openshift_master_cluster_hostname=vip-internal-cluster.example.com (change the DNS to resolve to master01 during installation)
openshift_master_cluster_public_hostname=vip-external-cluster.example.com (point to LB)

**Comment by egkelly** [comment]
Thank you for the reply! I did some more research and found that I did have to differentiate between the internal and external hostname; however, it still did not fix my problem. My concern is that curl is trying to go through the proxy to verify the API, though I specifically put all hostnames on my domain in no_proxy. I did also realize that openshift doesn't allow the wildcard character in no_proxy, so I also fixed that, but it is still trying to go through the proxy. Any ideas why or how to prevent curl from using the proxy?

**Comment by amelie1979** [comment]
Follow the proxy section from this doc 
https://docs.openshift.com/container-platform/3.9/install_config/install/host_preparation.html
the . in front is like the wildcard

it should look like this.. (Because noproxy does not support CIDR, you can use domain suffixes.)
no_proxy=.internal.example.com,10.0.0.1,10.0.0.2,10.0.0.3,.cluster.local,.svc,localhost,127.0.0.1,172.30.0.1
also did you put also it in the environnement
/etc/environment

I hope that helped.
