### ISSUE TITLE
TASK [openshift_ca : copy] 'item' is undefined

### ISSUE THREAD

**Issue by onknows** [openshift/openshift-ansible#9281]
#### Description

TASK [openshift_ca : copy]  fails consistently with message 'item' is undefined. Without any way of knowing of what is wrong. T

##### Version

 2.7.0.dev0 (devel c43e51e39e) last updated 2018/07/19 05:59:11 (GMT +000)
 openshift-ansible-3.9.32-1-78-gce857fe

##### Steps To Reproduce

Use inventory as https://github.com/onknows/openshift-ansible/blob/release-3.9-zgw-azure/inventory/zgw
ansible playbook prequisites en deploy. 

Ansible will fail consistently on deploy.

##### Expected Results

Ansible to succeed or produce a useful error message indicating what is wrong. 

##### Observed Results

Fail with message

TASK [openshift_ca : copy] *************************************************************************************************************************************
Tuesday 17 July 2018  12:15:36 +0000 (0:00:06.051)       0:29:57.137 ********** 
fatal: [master0]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'item' is undefined\n\nThe error appears to have been in '/home/user/openshift-ansible/roles/openshift_ca/tasks/main.yml': line 117, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    delegate_to: \"{{ openshift_ca_host }}\"\n  - copy:\n    ^ here\n"}

NO MORE HOSTS LEFT *********************************************************************************************************************************************

PLAY RECAP *****************************************************************************************************************************************************
cns0                       : ok=24   changed=1    unreachable=0    failed=0   
cns1                       : ok=24   changed=1    unreachable=0    failed=0   
cns2                       : ok=24   changed=1    unreachable=0    failed=0   
infra0                     : ok=24   changed=1    unreachable=0    failed=0   
infra1                     : ok=24   changed=1    unreachable=0    failed=0   
localhost                  : ok=13   changed=0    unreachable=0    failed=0   
master0                    : ok=140  changed=46   unreachable=0    failed=1   
master1                    : ok=76   changed=27   unreachable=0    failed=0   
master2                    : ok=76   changed=27   unreachable=0    failed=0   
node0                      : ok=24   changed=1    unreachable=0    failed=0   
node1                      : ok=24   changed=1    unreachable=0    failed=0   
node2                      : ok=24   changed=1    unreachable=0    failed=0   

INSTALLER STATUS ***********************************************************************************************************************************************
Initialization             : Complete (0:17:13)
Health Check               : Complete (0:01:01)
etcd Install               : Complete (0:06:34)
NFS Install                : Complete (0:00:28)
Master Install             : In Progress (0:04:32)
	This phase can be restarted by running: playbooks/openshift-master/config.yml

Tuesday 17 July 2018  12:15:36 +0000 (0:00:00.110)       0:29:57.247 ********** 
=============================================================================== 
Run variable sanity checks ---------------------------------------------------------------------------------------------------------------------------- 234.01s
openshift_ca : Install the base package for admin tooling ---------------------------------------------------------------------------------------------- 83.78s
openshift_cli : Install clients ------------------------------------------------------------------------------------------------------------------------ 47.37s
Run health checks (install) - EL ----------------------------------------------------------------------------------------------------------------------- 46.43s
openshift_sanitize_inventory : At least one master is schedulable -------------------------------------------------------------------------------------- 27.66s
openshift_sanitize_inventory : Assign deprecated variables to correct counterparts --------------------------------------------------------------------- 25.19s
openshift_sanitize_inventory : include_tasks ----------------------------------------------------------------------------------------------------------- 24.85s
Gathering Facts ---------------------------------------------------------------------------------------------------------------------------------------- 23.94s
openshift_sanitize_inventory : include_tasks ----------------------------------------------------------------------------------------------------------- 23.62s
openshift_version : Check openshift_version for rpm installation --------------------------------------------------------------------------------------- 22.62s
include_role : openshift_version ----------------------------------------------------------------------------------------------------------------------- 22.25s
openshift_version : Get available RPM version ---------------------------------------------------------------------------------------------------------- 21.41s
set_fact ----------------------------------------------------------------------------------------------------------------------------------------------- 17.35s
openshift_sanitize_inventory : conditional_set_fact ---------------------------------------------------------------------------------------------------- 17.35s
openshift_sanitize_inventory : conditional_set_fact ---------------------------------------------------------------------------------------------------- 16.63s
openshift_sanitize_inventory : Check for usage of deprecated variables --------------------------------------------------------------------------------- 15.70s
openshift_sanitize_inventory : set_fact ---------------------------------------------------------------------------------------------------------------- 15.62s
Gather Cluster facts ----------------------------------------------------------------------------------------------------------------------------------- 15.30s
Initialize openshift.node.sdn_mtu ---------------------------------------------------------------------------------------------------------------------- 15.04s
Detecting Operating System from ostree_booted ---------------------------------------------------------------------------------------------------------- 14.52s

Failure summary:

  1. Hosts:    master0
     Play:     Create OpenShift certificates for master hosts
     Task:     openshift_ca : copy
     Message:  The task includes an option with an undefined variable. The error was: 'item' is undefined
               
               The error appears to have been in '/home/user/openshift-ansible/roles/openshift_ca/tasks/main.yml': line 117, column 5, but may
               be elsewhere in the file depending on the exact syntax problem.
               
               The offending line appears to be:
               
                   delegate_to: "{{ openshift_ca_host }}"
                 - copy:
                   ^ here

##### Additional Information

RHEL 7.4
Inventory https://github.com/onknows/openshift-ansible/blob/release-3.9-zgw-azure/inventory/zgw
```
EXTRA INFORMATION GOES HERE
```

**Comment by inlandsee** [comment]
Same issue.  Fedora 28, release-3.9

Failure summary:
  1. adams.lan
     Create OpenShift certificates for master hosts
     openshift_ca : copy
     The task includes an option with an undefined variable. The error was: 'item' is undefined
               
     The error appears to have been in '/home/user/openshift-ansible/roles/openshift_ca/tasks/main.yml': line 117, column 5, but may
               be elsewhere in the file depending on the exact syntax problem.
               
               The offending line appears to be:
               
                   delegate_to: "{{ openshift_ca_host }}"
                 - copy:
                   ^ here

**Comment by arnold-jr** [comment]
Same issue: CentOS Linux release 7.4.1708 (Core), release 3.10 (1a911c5d0cc48f08e56fed994e7176cd9387a740)
