### ISSUE TITLE
http/https proxies not being configured on new cluster deploy

### ISSUE THREAD

**Issue by felsys** [openshift/openshift-ansible#9291]
#### Description

ansible installer, using the deploy_cluster.yml playbook, is not configuring the http/https proxies when defined in inventory file as:
openshift_http_proxy=<redacted>
openshift_https_proxy=<redacted>
openshift_no_proxy=<redacted>

This, in turn, causes the first docker pull (etcd) to fail, failing the installation.

##### Version

ansible==2.6.1
openshift-ansible-3.9.37-1-4-g700bfa7
OpenShift Origin 3.9.0

##### Steps To Reproduce
1. Define http/https proxies in ansible inventory file
2. Install cluster using deploy_cluster.yml playbook

##### Expected Results
Proxies configured

##### Observed Results
Proxies not configured, docker pull's fail.

##### Additional Information
This has worked previously in the past using the config.yml playbook on previous versions of openshift/ansible.

FWIW I also tried adding these variables as "-e" arguments with the install command, same result.

**Comment by vrutkovs** [comment]
What's the contents of `/etc/sysconfig/docker` on these systems? Do these have `HTTP_PROXY`/`HTTPS_PROXY`/`NO_PROXY`?

**Comment by feld-ims** [comment]
They do not have those proxy configs in there by default

**Comment by vrutkovs** [comment]
Right, these should be set though. Could you put the inventory and output of `ansible-playbook -vvv` in gists and link here?

Also, did you run `prerequsites.yml` playbook? Could you attach its output in a gist too?

**Comment by feld-ims** [comment]
I just ran prerequsites.yml and it seems to have worked and set those configs properly. I've never had to run that playbook for new clusters in the past. At any rate i'll work on getting the other information you requested

**Comment by winkidzz** [comment]
Is this issue fixed? I am seeing the same problem happening today
