### ISSUE TITLE
openshift_loadbalancer_additional_frontends are not opened in firewall by openshift_loadbalancer role

### ISSUE THREAD

**Issue by cwilkers** [openshift/openshift-ansible#9346]
#### Description

On an install with a load balancer, if `openshift_loadbalancer_additional_frontends` is specified, the load balancer host firewall is not configured to open those additional ports.

##### Version

Verified on current master, seen on 3.10 deployment.

##### Steps To Reproduce
1. Set up load balancer with following variables:

```
openshift_loadbalancer_additional_frontends=[{"name":"apps-http","option":"tcplog","binds":["*:80"],"default_backend":"apps-http"},{"name":"apps-https","option":"tcplog","binds":["*:443"],"default_backend":"apps-http"}]
openshift_loadbalancer_additional_backends=[{"name":"apps-http","balance":"source","servers":[{"name":"infra0","address":"{{ groups['infras'].0 }}:80","opts":"check"},{"name":"infra1","address":"{{ groups['infras'].1 }}:80","opts":"check"},{"name":"infra2","address":"{{ groups['infras'].2 }}:80","opts":"check"}]},{"name":"apps-https","balance":"source","servers":[{"name":"infra0","address":"{{ groups['infras'].0 }}:443","opts":"check"},{"name":"infra1","address":"{{ groups['infras'].1 }}:443","opts":"check"},{"name":"infra2","address":"{{ groups['infras'].2 }}:443","opts":"check"}]}]
```
2. Point wildcard DNS at load balancer IP

3. Use deploy_cluster.yml playbook to deploy OCP

4. Create an application, expose its route, and attempt to reach via wildcard address entry. (port 80 or 443)

##### Expected Results
Additional ports directed through haproxy load balancer should be reachable.

##### Observed Results
Firewall configuration on load balancer node prevents access to additional front-ends.

**Comment by bbeaudoin** [comment]
Have you tried specifying the node ports to open for the load balancer group?

```ini
[lb:vars]
openshift_node_open_ports=[{"service":"http", "port":"80/tcp"}, {"service":"https", "port":"443/tcp"}]
```

**Comment by cwilkers** [comment]
I filed this against 3.10 last year. Since then, the repo has been gutted because 4.x does not use openshift-ansible. What version are you trying to answer this issue against?

If we're still talking about 3.11, then the node preparation playbooks in the prerequisites.yaml should have responsibility for opening relevant ports, as they contain routines for handling the firewall.
