### ISSUE TITLE
Install will fail if `dns=none` in `/etc/NetworkManager/NetworkManager.conf`

### ISSUE THREAD

**Issue by itewk** [openshift/openshift-ansible#9351]
#### Description

If `/etc/NetworkManager/NetworkManager.conf` has `dns=none` in it and the openshift installer is expected to install and configure dnsmasq then the install will fail because then the `/etc/NetworkManager/dispatcher.d/99-origin-dns.sh` can not properly pull the nameservers from NetworkManager.

##### Version
```
https://github.com/openshift/openshift-ansible/tree/openshift-ansible-3.9.31-1/playbooks
```

##### Steps To Reproduce
1. configure ifcfg device for DNS1/2
2. have `dns=none` in `/etc/NetworkManager/NetworkManager.conf`
3. run installer
4. be frustrated for 2 days while you try to figure out why the heck dnsmasq can't find the upstream DNS servers

##### Expected Results
It would be great if the ansible playbooks could detect that:

1. dnsmasq has not been preconfigured as per https://docs.openshift.com/container-platform/3.9/install_config/install/prerequisites.html#prereq-dns and therefor the installer should be configuring dnsmasq
2.  `/etc/NetworkManager/NetworkManager.conf` contains `dns=none`

And then if those two things are true, bail EARLY.

Right now the installer runs for about 30 minutes before it gets to the dnsmasq configuration and then attempts to install a package which fails because DNS is busted. It would be great to detect this early and bail early.

##### Observed Results
dnsmasq isn't getting configured correctly because of `dns=none` in `/etc/NetworkManager/NetworkManager.conf` and is causing installs to fail but not clear as to why.

##### Additional Information
From talking to my fellow openshift deployers a bunch of people have been running into this issue and spending massive amounts of time debugging the issue. It would be great to have an automated detection of the issue and report that back to users to avoid hours, in my case, days of troubleshooting.

This comes up because it is common for large slower organizations to still not be using NetworkManager and have it disabled as part of their kickstart of VM cloning process. 

Maybe the detection should happen during the prerequisites playbook?

**Comment by JayKayy** [comment]
I have hit this issue a few times. A fix would be very much welcomed.

**Comment by curt-matthews** [comment]
I've hit this at two customers as well!

**Comment by clodter** [comment]
I've run into this problem at a customer site, too.

**Comment by jnach** [comment]
Joining the party, and can add that a common troubleshooting procedure for some enterprise networking teams for DNS issues is to try and set 'dns=none' (perhaps when you may not be looking), would be great to have an explicit message on this as part of the pre-flight checks.

**Comment by abessifi** [comment]
Just tested with a OpenShift `3.11.104` fresh install and seems to be working correctly.

**Description:**

- configure ifcfg device with `NM_CONTROLLED=yes`
- `/etc/NetworkManager/NetworkManager.conf` contains `dns=none`
- `/etc/resolv.conf` is pre-set manually

**After installation:**

- `dnsmasq` has the correct configuration (which means that the `99-origin-dns.sh` dispatch script was correctly executed by NetworkManager)
- `/etc/resolv.conf` points to dnsmasq as a nameserver
- DNS resolution works fine for public, private and "kubernetes" domains
