### ISSUE TITLE
Azure: would like to store the name of an image as a file on that image

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-ansible#9371]
Makes it bullet-proof to know which image version is actually being used by a VM.

Just a case of dumping "{{ openshift_azure_output_image_name }}" to a marker file maybe if openshift_azure_output_image_ns == images ?

Dump root_image as well? timestamp? ID of subscription where built?

**Comment by jim-minter** [comment]
@kwoodson please can you take a look at this?

**Comment by kwoodson** [comment]
@jim-minter, would you prefer yaml format for this?

**Comment by jim-minter** [comment]
I think a flat file in the same directory we store the oreg_url if set would be fine (is that /var/tmp?)

**Comment by kwoodson** [comment]
This is located in `/etc/origin`:

https://github.com/openshift/openshift-ansible/blob/master/playbooks/azure/openshift-cluster/build_node_image.yml#L85-L89

**Comment by jim-minter** [comment]
Oh, right - there then ;)
