### ISSUE TITLE
Upgrade to 3.10 trouble with master-api pod and master-controller

### ISSUE THREAD

**Issue by IlonkaO** [openshift/openshift-ansible#9397]
After the upgrade to 3.10 I'm not able to login to the web-console and also it isn't possible to login via CLI.
I tried a restart of the master-api pod and get a return code of 2.
If I try to restart the master-controller pod I get the message that it is already stopped.
After looking inside the master-restart command I saw that this command execute "systemctl restart atomic-openshift-master-api.service". But this service doesn't exist.

Are there any suggestions, where I could search???

Version

 `ansible --version: ansible 2.4.4.0`

`rpm -q openshift-ansible: openshift-ansible-3.10.21-1.git.0.6446011.el7.noarch`

```
oc v3.10.14
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server xxx
openshift v3.10.14
kubernetes v1.10.0+b81c8f8

```
##### Steps To Reproduce
1. oc login https://xxxx
2. output:
```
 The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n):
```
3. Using insecure connection -> login with LDAP
`Error from server (InternalError): Internal error occurred: unexpected response: 500`

##### Expected Results
Successful login

Log of the master-api pod:
```
E0802 06:26:31.573552       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
E0802 06:26:35.196337       1 basicauth.go:48] Error authenticating login "<user>" with provider "ldap_xxx": LDAP Result Code 200 "Network Error": x509: certificate signed by unknown authority
E0802 06:26:35.196574       1 errorpage.go:26] AuthenticationError: LDAP Result Code 200 "Network Error": x509: certificate signed by unknown authority

```

##### Additional Information
I also recognise other errors and warnings in the log of the master-api 
```
E0802 06:26:37.548789       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
W0802 06:27:11.641485       1 reflector.go:341] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: watch of *rbac.Role ended with: The resourceVersion for the provided watch is too old.
W0802 06:27:11.641536       1 reflector.go:341] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: watch of *core.PersistentVolumeClaim ended with: The resourceVersion for the provided watch is too old.
W0802 06:27:11.641569       1 reflector.go:341] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: watch of *core.ServiceAccount ended with: The resourceVersion for the provided watch is too old. 
```

Actually the master-api seems not active, because the last try for login wasn't logged. How can I get the status of the master-api? The pods in kube-system are all running...

OS: 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"

Cluster environment:
2 master
2 infrastructure
1 worker

**Comment by calvinmorrow** [comment]
We just ran into this same bug.  Upgrade from 3.9 -> 3.10 and the move from `origin-master-api` -> container means its missing the trusted certificate that was used for ldap authentication.

```E0808 15:27:39.550808       1 errorpage.go:26] AuthenticationError: LDAP Result Code 200 "Network Error": x509: certificate signed by unknown authority```

LDAP logins are broken.  Still trying to find a workaround.

**Comment by vrutkovs** [comment]
There are two changes in 3.10 which have caused this:

* API servers now run in static pods, so they don't share CA store with the host anymore
* Mounts to API server container are limited to /etc/origin/master

So in 3.10 the user can't replace container CA store entirely. `openshift_master_ldap_ca_file` would be copied to the host and mounted in `/etc/origin/master/<basename>`. As a result 'ca:' is required to be set if `openshift_master_ldap_ca_file` is used.
