### ISSUE TITLE
Vagrant Setup : Registry failure with I/O timeout

### ISSUE THREAD

**Issue by urashidmalik** [openshift/openshift-ansible#942]
Steps to Repro:  

System (Vagrant/Virtualbox on Mac OS X)
1. Clone repo
2. Follow https://github.com/openshift/openshift-ansible/blob/master/README_vagrant.md
3. vagrant up --no-provision
4. vagrant provision

Once finished, able to access openshift from MAC chrome https://ose3-master.example.com:8443/
1. SSH into Master
2.  Follow Guide on https://docs.openshift.org/latest/install_config/install/docker_registry.html
3. sudo oadm registry --create --credentials=/etc/origin/master/openshift-registry.kubeconfig
4. Get Logs : oc logs docker-registry-1-deploy
   9: Result: deployer.go:65] couldn't get deployment default/docker-registry-1: Get https://ose3-master.example.com:8443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1: dial tcp: i/o timeout
5. CURL url: curl -k https://ose3-master.example.com:8443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1
6. Result
   {
   "kind": "Status",
   "apiVersion": "v1",
   "metadata": {},
   "status": "Failure",
   "message": "User \"system:anonymous\" cannot get replicationcontrollers in project \"default\"",
   "reason": "Forbidden",
   "details": {
     "name": "docker-registry-1",
     "kind": "replicationcontrollers"
   },
   "code": 403
   }

**Comment by urashidmalik** [comment]
@smarterclayton Tagged

**Comment by urashidmalik** [comment]
Not sure if this helps: https://github.com/openshift/training/blob/master/deprecated/beta4/dnsmasq.conf

**Comment by VolkerKozlowski** [comment]
I am having the same problems as described above on my Mac with Origin 1.0.7. I am using landrush as a plugin for Vagrant to act as a DNS. But this does not help. I am not sitting behind a proxy.

**Comment by dlbewley** [comment]
Looks like dupe of #391 ?

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.
