### ISSUE TITLE
Setting the nodeIP is affecting the node kubernetes.io/hostname label

### ISSUE THREAD

**Issue by simon3z** [openshift/openshift-ansible#943]
In PR #815 it was added:

    +nodeIP: {{ openshift.common.ip }}

to `node.yaml.v1.j2`. This creates nodes that self-register using the IP instead of the hostname. In fact from the OpenShift code:

        if len(options.NodeIP) > 0 {
                server.HostnameOverride = options.NodeIP
        } else {
                server.HostnameOverride = options.NodeName
        }

https://github.com/openshift/origin/blob/v1.0.8/pkg/cmd/server/kubernetes/node_config.go#L114

As a result all nodes have the `kubernetes.io/hostname` and the `externalID` set to the ip address:

    NAME                              LABELS                                STATUS    AGE
    oshift01.eng.lab.tlv.redhat.com   kubernetes.io/hostname=10.35.19.229   Ready     8h
    oshift02.eng.lab.tlv.redhat.com   kubernetes.io/hostname=10.35.19.230   Ready     8h
    oshift03.eng.lab.tlv.redhat.com   kubernetes.io/hostname=10.35.19.231   Ready     8h
    oshift04.eng.lab.tlv.redhat.com   kubernetes.io/hostname=10.35.19.232   Ready     8h

This, among other things affects Heapster and Hawkular as the metrics are now saved using the ip address instead of the node (host)name.

Probably the correct way to address this in the long term would be to fix OpenShift and Heapster but in the short term this single line in the node config is changing/breaking several behaviors.

cc @detiber

**Comment by pravisankar** [comment]
upstream issue: https://github.com/kubernetes/kubernetes/issues/17704

**Comment by sdodson** [comment]
@pravisankar Can you describe the effects on an existing environment if externalID changes from a hostname to IP?

**Comment by detiber** [comment]
submitted https://github.com/openshift/openshift-ansible/pull/970 to address this (as a workaround)

**Comment by pravisankar** [comment]
ExternalID was originally introduced to return the cloud provider ID of the specified instance.
For non cloud provider cases, ExternalID defaults to kubelet hostname. Since we don't run in cloud provider mode, I don't think this field is relevant to us.
Currently, ExternalID is deprecated in favor of ProviderID (can take value of this format: <ProviderName>://<ProviderSpecificNodeID>)

**Comment by simon3z** [comment]
@detiber I think this can be closed, IIUC #17731 is setting `openshift_node_set_node_ip` to `False` right?

**Comment by detiber** [comment]
@simon3z that is correct, by default openshift_node_set_node_ip is False now. Feel free to close this issue.

**Comment by simon3z** [comment]
#970 is fixing this issue. Thanks.
