### ISSUE TITLE
Task [Openshift_master: Disable the legacy maszter service if it exists] fails

### ISSUE THREAD

**Issue by dhanugithub** [openshift/openshift-ansible#9439]
Hello,
I have a CentOS minimal install VM running on Proxmox VE in which I am installing openshift origin (all in one installation).
I am following G. Shipley's youtube video and also instructions given here.
I run into following error:

Task [Openshift_master: Disable the legacy maszter service if it exists]
fatal: [192.168.10.216]: FAILED! => {"changed": false, "msg": "Could not find the requested service origin-master: host"}
Although this error doesn't seem to affect any implementation or later working of openshift but I am curious to know why this appears. Even in my other implementions (1 master VM and 1 node VM) I have same error and several dependency failures.

Also, I have a doubt. According to the Openshift documentation, if we are using "containerized=true", then "docker run" command should be used to implement each service as a separate docker container. But this and many other documents simply follow ansible-playbook command which is suitable for RPM installation.
Any help is appreciated.
Thank you.

**Comment by camabeh** [comment]
Same problem.

I had to revert https://github.com/openshift/openshift-ansible/commit/9854a65d4429bac9bd95f683f6da93a777ae5865.

**Comment by djdevin** [comment]
My guess is that Ansible does not have a step for "Stop service, but only if it exists" so it has to fail.

When you set `containerized=true`, services are still created, but if you look at those service files they contain `docker run` commands. Docker will not restore your services on boot and this is also recommended from the Docker docs: https://docs.docker.com/config/containers/start-containers-automatically/#use-a-process-manager
