### ISSUE TITLE
feature request: be able to customize master-config.yaml

### ISSUE THREAD

**Issue by vnugent** [openshift/openshift-ansible#948]
Is there a way to override values in master-config.yaml?  Specifically I want to be able to set the service subdomain name:

```
# master-config.yaml
...
routingConfig:
  subdomain:  "<my subdomain>"
```

**Comment by detiber** [comment]
@vnugent osm_default_subdomain is the variable you are looking for.

The master-config.yaml file is compiled from the following template: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_master/templates/master.yaml.v1.j2 which uses values set through openshift_facts

Most of the variables that can be overridden in the config are updated through this block: https://github.com/openshift/openshift-ansible/blob/aa0746600ed64b2b2f61eb83f634bccdfa4c5be2/roles/openshift_master/tasks/main.yml#L21-L75

We have an outstanding item to document more of the configurables.

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit

This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
