### ISSUE TITLE
wrong version in inventory file for release-3.10 branch

### ISSUE THREAD

**Issue by dusansusic** [openshift/openshift-ansible#9480]
Branch release-3.10 has wrong version inside inventory file:

https://github.com/openshift/openshift-ansible/blob/d8a8693abfff6c79b11bb8ae972b33f28982c2da/inventory/hosts.example#L54

Should this be v3.10?

**Comment by DanyC97** [comment]
@dusansusic or @vrutkovs can one of you please close this issue now that PR merged.

it should have been closed by github ...oh well

**Comment by vrutkovs** [comment]
Right, weird that Github didn't close it automatically

Fixed in #9529
