### ISSUE TITLE
vxlan not working

### ISSUE THREAD

**Issue by sebasmannem** [openshift/openshift-ansible#9498]
#### Description
Pods on seperate nodes cannot communicate.
`nmcli device` shows `vxlan_sys_4789  vxlan        disconnected  --`

##### Version
```
# ansible --version
ansible 2.5.3
  config file = /home/centos/branch39-new06142018/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

# git describe
openshift-ansible-3.9.40-1-29-g95a7a39
```

##### Steps To Reproduce
1. On AWS create an ansible VM, master VM, Infra VM and 2 workers (All Centos7)
2. On Ansible VM
 * clone repo
 * create correct /etc/ansible/hosts file
 * run ansible-playbook $REPO/playbooks/prerequisites.yml
 * run ansible-playbook $REPO/playbooks/deploy_cluster.yml
3. Schedule deployment with multiple pods

##### Expected Results
* Pods on different nodes can ping eachother
* Pods on same nodes can ping eachother
* `nmcli device` displays vxlan_sys_4789 in connected state
* `oc adm diagnostics NetworkCheck` finishes without errors

```
# nmcli device
DEVICE          TYPE         STATE         CONNECTION
eth0            ethernet     connected     System eth0
docker0         bridge       connected     docker0
vxlan_sys_4789  vxlan        connected     System eth0
```

```
# oc adm diagnostics NetworkCheck
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/root/.kube/config'
Info:  Using context for cluster-admin access: 'default/ip-10-1-88-2-ec2-internal:8443/system:admin'

       [Note] Running diagnostic: NetworkCheck
               Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint
...

Info:  Additional info collected under "/tmp/openshift" for further analysis
[Note] Summary of diagnostics execution (version v3.9.0+ba7faec-1):
[Note] Errors seen: 0
```
##### Observed Results
Describe what is actually happening.

* Pods on different nodes cannot ping each other
* Pods on same nodes can ping each other (which is nice)
* `nmcli device` displays vxlan_sys_4789 in disconnected state
* `oc adm diagnostics NetworkCheck` finishes with errors (see gist: [oc_adm_diagnostics_NetworkCheck.out](https://gist.github.com/sebasmannem/a06407cb6a4e47a96fe7ef049d62ef64)
```
# nmcli device
DEVICE          TYPE         STATE         CONNECTION
eth0            ethernet     connected     System eth0
docker0         bridge       connected     docker0
vxlan_sys_4789  vxlan        disconnected  --
veth621c77e6    ethernet     unmanaged     --
veth65c9cdf6    ethernet     unmanaged     --
veth985ec6d5    ethernet     unmanaged     --
vethb6bfbe15    ethernet     unmanaged     --
lo              loopback     unmanaged     --
br0             openvswitch  unmanaged     --
ovs-system      openvswitch  unmanaged     --
tun0            openvswitch  unmanaged     --
```

##### Additional Information
* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
```
# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
```
* Inventory file does not contain any special config. It can be provided if needed.

Please note that
* I have obfuscated some info in the applied config and log output.
* This environment has been built and used. We where not aware of this issue at that time.
* Huge changes in the config where applied (like switching from containerized=true to containerized=false).
* We want to rebuild, but currently, it is still in use, so we would like to fix the current environment if we can.
* We want to rebuild this environment in a second environment, to try to reproduce the issue.
* If any other info is required, just let me know.
```

**Comment by vrutkovs** [comment]
cc @openshift/networking

**Comment by sebasmannem** [comment]
You can find our inventory here: [/etc/ansible/hosts](https://gist.github.com/sebasmannem/ab51b97eea2a90e516e7b37b8800e4a7)

**Comment by sebasmannem** [comment]
I have found the sdn check of this pull request: #7759.
I wanted to run it, but it couldn't run. Couldn't find the container.
I worked around that by:
```
diff --git a/roles/openshift_health_checker/openshift_checks/sdn.py b/roles/openshift_health_checker/openshift_checks/sdn.py
index 099ce87..6155f94 100644
--- a/roles/openshift_health_checker/openshift_checks/sdn.py
+++ b/roles/openshift_health_checker/openshift_checks/sdn.py
@@ -323,6 +323,9 @@ class SDNCheck(OpenShiftCheck):
             ])
             command = ['/bin/docker', 'exec', container_id]

+        if not container_id:
+            command = []
+
         return command

     def save_service_logs(self, service_name):
```
Now it outputs lines like:
```
  1. Hosts:    worker01.edbdemo-public.net
     Play:     OpenShift Health Checks
     Task:     Run health checks (adhoc)
     Message:  One or more checks failed
     Details:  check "sdn":
               Node ip-{{IP_254}}.ec2.internal cannot ping node ip-{{IP_159}}.ec2.internal.
               Node ip-{{IP_254}}.ec2.internal cannot ping node ip-{{IP_177}}.ec2.internal.
               Node ip-{{IP_254}}.ec2.internal cannot ping node ip-{{IP_88}}.ec2.internal.
```
Which is the problem.
Questions:
1: Should the container openshift-sdn/openvswitch be running (also if containerized=false)?
2: If not, should I make a MR for my changes?
