### ISSUE TITLE
 invalid parameter specified: '_ortr_selector'

### ISSUE THREAD

**Issue by sada-okamura** [openshift/openshift-ansible#955]
### Symptom
When I try to run ansible-playbook command, it fail with the following error.
```bash
# ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml
ERROR! invalid parameter specified: '_ortr_selector'
```

### My environment
```bash
# ansible --version
ansible 2.0.0 (devel 478c6c756a) last updated 2015/11/22 17:29:59 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 1ff0704c0c) last updated 2015/11/22 17:31:23 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 035ad1d140) last updated 2015/11/22 17:31:43 (GMT -700)
  config file =
  configured module search path = Default w/o overrides

# cat ./openshift-ansible/openshift-ansible.spec | grep Version:
Version:        3.0.15
```

### Possible cause
According to Ansible [source code](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/splitter.py), ansible doesn't allow parameters starting with underscore ('_'). 
Wheras openshift-ansible's [task config for routers](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_router/tasks/main.yml) uses "_ortr_images" and "_ortr_selector", both starting from underscore.

**Comment by abutcher** [comment]
Hey @sada-okamura the openshift-ansible playbooks are not compatible with ansible 2.0 yet. We're tracking updating the playbooks for 2.0 in #686.

**Comment by detiber** [comment]
@sada-okamura the variables with leading underscores are the number one known issue with 2.0 compatibility currently.

**Comment by sada-okamura** [comment]
Thanks @abutcher & @detiber!

I close this and will follow #686 and wait for a fix to come.
