### ISSUE TITLE
Openvswitch rpm is missed. Release 3.10

### ISSUE THREAD

**Issue by vital-st1x** [openshift/openshift-ansible#9550]
Hi
Trying to install clean openshift from release 3-10 branch.

RPM openvswitch is missed in default repository
http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin310/

But exists in 

http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin39/

**Comment by vrutkovs** [comment]
This repo should not be used to track CentOS repo issues - please use CentOS bugtracker.

Openvswitch RPM would no longer be checked after #9506 is merged

**Comment by DanyC97** [comment]
@vital-st1x i can tag the rpm into CentOS however as @vrutkovs said we are close for the PR to be merged and so it won't be needed.

**Comment by vital-st1x** [comment]
@DanyC97 let's wait for merge [9506](https://github.com/openshift/openshift-ansible/pull/9506) in this case

Thanks for such fast response!
