### ISSUE TITLE
Creating all-on-one cluster from release-3.9 branch no longer works

### ISSUE THREAD

**Issue by adelton** [openshift/openshift-ansible#9583]
#### Description

On a RHEL 7.5 machine, running

```
ansible-playbook -i ansible-inventory openshift-ansible/playbooks/deploy_cluster.yml
```
started to fail.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

If you're operating from a **git clone**:

* The output of `git describe`

```
openshift-ansible-3.9.40-1-37-g0f6f8b7
```

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

```
package openshift-ansible is not installed
```

##### Steps To Reproduce
1. `git clone -b release-3.9 https://github.com/openshift/openshift-ansible openshift-ansible`
2. Have `ansible-inventory`:

```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_disable_check=memory_availability,docker_storage,disk_availability,package_version
openshift_repos_enable_testing=true
openshift_enable_excluders=false

osm_cluster_network_cidr=10.128.0.0/14
openshift_portal_net=172.30.0.0/16
osm_host_subnet_length=9

openshift_router_selector='node-router=true'
openshift_registry_selector='node-registry=true'
template_service_broker_selector={"node-app": "true"}
openshift_web_console_nodeselector={"node-app": "true"}

openshift_node_groups=[	{ 'name': 'node-all-on-one', 'labels': [ 'node-router=true', 'node-registry=true', 'node-app=true', 'node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true' ] }, { 'name': 'node-router', 'labels': [ 'node-router=true', 'node-role.kubernetes.io/infra=true' ] }, { 'name': 'node-registry', 'labels': [ 'node-registry=true', 'node-role.kubernetes.io/infra=true' ] }, { 'name': 'node-app', 'labels': [ 'node-app=true', 'node-role.kubernetes.io/compute=true' ] }, { 'name': 'node-master', 'labels': [ 'node-role.kubernetes.io/master=true' ] } ]

openshift_master_identity_providers=[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]

[masters]
master.example.com

[etcd]
master.example.com

[nodes]
master.example.com openshift_schedulable=true openshift_node_labels="{ 'node-router': 'true', 'node-registry': 'true', 'node-app': 'true', 'node-master': 'true' }" openshift_node_group_name='node-all-on-one'
```

3. Run `ansible-playbook -i ansible-inventory openshift-ansible/playbooks/prerequisites.yml`
4. Run `ansible-playbook -i ansible-inventory openshift-ansible/playbooks/deploy_cluster.yml`

##### Expected Results
Describe what you expected to happen.

No error.

##### Observed Results
Describe what is actually happening.

```
TASK [openshift_examples : Create local temp dir for OpenShift examples copy] ***
Tuesday 14 August 2018  04:06:41 -0400 (0:00:00.098)       0:21:00.828 ******** 
changed: [master.example.com -> localhost]

TASK [openshift_examples : Chmod local temp dir for OpenShift examples copy] ***
Tuesday 14 August 2018  04:06:41 -0400 (0:00:00.340)       0:21:01.168 ******** 
 [WARNING]: Consider using the file module with mode rather than running chmod.
If you need to use command because file is insufficient you can add warn=False
to this command task or set command_warnings=False in ansible.cfg to get rid of
this message.
changed: [master.example.com -> localhost]

TASK [openshift_examples : Create tar of OpenShift examples] *******************
Tuesday 14 August 2018  04:06:41 -0400 (0:00:00.336)       0:21:01.505 ******** 
fatal: [master.example.com -> localhost]: FAILED! => {"changed": true, "cmd": ["tar", "-C", "/mnt/tests/OpenShift/Origin/install/dist/openshift-ansible/roles/openshift_examples/files/examples/v3.10/", "-cvf", "/tmp/openshift-ansible-YXcxNLI/openshift-examples.tar", "."], "delta": "0:00:00.006552", "end": "2018-08-14 04:06:42.024233", "msg": "non-zero return code", "rc": 2, "start": "2018-08-14 04:06:42.017681", "stderr": "tar: /mnt/tests/OpenShift/Origin/install/dist/openshift-ansible/roles/openshift_examples/files/examples/v3.10/: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now", "stderr_lines": ["tar: /mnt/tests/OpenShift/Origin/install/dist/openshift-ansible/roles/openshift_examples/files/examples/v3.10/: Cannot open: No such file or directory", "tar: Error is not recoverable: exiting now"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0   
master.example.com : ok=265  changed=87   unreachable=0    failed=1   


INSTALLER STATUS ***************************************************************
Initialization             : Complete (0:00:25)
Health Check               : Complete (0:06:26)
etcd Install               : Complete (0:06:48)
Master Install             : Complete (0:07:19)
Master Additional Install  : In Progress (0:00:02)
	This phase can be restarted by running: playbooks/openshift-master/additional_config.yml

Tuesday 14 August 2018  04:06:42 -0400 (0:00:00.286)       0:21:01.792 ******** 
=============================================================================== 
Run health checks (install) - EL -------------------------------------- 386.09s
etcd : Install etcd --------------------------------------------------- 243.49s
openshift_ca : Install the base package for admin tooling -------------- 95.85s
openshift_cli : Install clients ---------------------------------------- 81.91s
openshift_master : Install Master package ------------------------------ 72.78s
etcd : Install openssl ------------------------------------------------- 23.85s
etcd : Install openssl ------------------------------------------------- 23.65s
etcd : Install etcd ---------------------------------------------------- 23.62s
nickhammond.logrotate : nickhammond.logrotate | Install logrotate ------ 23.60s
nickhammond.logrotate : nickhammond.logrotate | Install logrotate ------ 23.56s
openshift_cli : Install bash completion for oc tools ------------------- 23.52s
etcd : Install etcd for etcdctl ---------------------------------------- 23.49s
restart master api ----------------------------------------------------- 19.22s
openshift_master : Start and enable master api ------------------------- 18.99s
openshift_version : Get available RPM version -------------------------- 13.19s
openshift_master : Wait for API to become available --------------------- 4.74s
openshift_ca : Create the master certificates if they do not already exist --- 3.46s
tuned : Ensure files are populated from templates ----------------------- 3.38s
etcd : Enable etcd ------------------------------------------------------ 2.96s
tuned : Restart tuned service ------------------------------------------- 2.43s


Failure summary:


  1. Hosts:    master.example.com
     Play:     Additional master configuration
     Task:     Create tar of OpenShift examples
     Message:  non-zero return code
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
`RHEL 7.5`
* Your inventory file (especially any non-standard configuration parameters)
See above.
* Sample code, etc

**Comment by adelton** [comment]
The same steps passed on 2018-08-08.

**Comment by adelton** [comment]
Internal reproducer J:2693613.

**Comment by EthanBannister** [comment]
I get the same result while trying to deploy a full cluster.  It looks like it is looking for OpenShift examples in 

> openshift-ansible/roles/openshift_examples/files/examples/v3.10/

But it can't find it due to the fact that I am checked out to the 3.9 branch.

**Comment by kellym56** [comment]
Experiencing the same issue. I had successsfully version 3.9 last week. I took the enviroment down and tried to redeploy, but failing at the same step.
When I check the version installed on the master nodes with 'oc version', I get 3.10, whereas on my original deployment I was getting v3.9.

Any ideas?

**Comment by vrutkovs** [comment]
This usually happens on my setups when I try to upgrade a freshly installed 3.9 cluster to 3.10.

Did you try cleaning up facts (in `~/.ansible` on ansible host and `/etc/ansible/facts.d` on target hosts)?

**Comment by kellym56** [comment]
Just wanted to update this with the specific branch I'm using:
`git describe
openshift-ansible-3.9.40-1-45-g8561a68`

However, when I check the oc version on the master nodes I get the below. Expected output is oc v3.9...

`oc version
oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ip-172-16-1-62.eu-west-1.compute.internal:8443
openshift v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8`

**Comment by DanyC97** [comment]
@kellym56 in your inventory for 3.9 i see no trace of `openshift_release` is that intentionally ?

**Comment by adelton** [comment]
> This usually happens on my setups when I try to upgrade a freshly installed 3.9 cluster to 3.10.
> 
> Did you try cleaning up facts (in ~/.ansible on ansible host and /etc/ansible/facts.d on target hosts)?

For me, it's always a brand new installation attempt.

**Comment by adelton** [comment]
> in your inventory for 3.9 i see no trace of openshift_release is that intentionally ?

With this question, do you hint that `openshift_release` is now mandatory way to install from non-master branches?

**Comment by adelton** [comment]
I confirm that adding
```
openshift_release=3.9
```
to `[OSEv3:vars]` makes the setup process pass.

Is it expected that it's necessary to specify that when an openshift-ansible release branch is used?

**Comment by vrutkovs** [comment]
It isn't necessary, it would pickup whatever is latest in the repos. So it seems the generic CentOS repos have been used - and these already include 3.10.

Seems #9549 would fix that - could you try again with `openshift-ansible-3.9.41-1` or latest `release-3.9`?

**Comment by adelton** [comment]
> Seems #9549 would fix that - could you try again with openshift-ansible-3.9.41-1 or latest release-3.9?

It does not, the error is still the same. Internal reproducer from today J:2714850.

**Comment by adelton** [comment]
The `ansible-inventory` file which I pass to `ansible-playbook` via `-i` command-line option. It's shown above, in https://github.com/openshift/openshift-ansible/issues/9583#issue-350430586.

**Comment by kellym56** [comment]
ah! Sorry, I see now, I'll give that a go today. thanks

**Comment by vrutkovs** [comment]
@adelton which repos are in `/etc/yum.repos.d/`? Does it have `...Origin39.repo`?

**Comment by vrutkovs** [comment]
@DanyC97 PTAL, seems a wrong repo on .41 is still being injected. Works fine when `openshift_release` is specified - but that's not necessary, right?

**Comment by DanyC97** [comment]
@adelton sorry for very late response ! 

> Nope, CentOS-OpenShift-Origin.repo with baseurl=http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/.

that is generic repo which contains the latest OKD release. Now today is on v3.10 because of the freeze in CentOS repo as mentioned in the v3.11 [announcement](http://lists.openshift.redhat.com/openshift-archives/users/2018-November/msg00007.html) 

Once the freeze will end i'll push the v3.11.

Now for v3.9 release you should use the [rpm](http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-openshift-origin39-1-1.el7.centos.noarch.rpm) which will give point you to the [specific](http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin39/) repo release 


hope that makes sense
