### ISSUE TITLE
[3.10] Upgrade documentation conflict with containerized GlusterFS 

### ISSUE THREAD

**Issue by rassie** [openshift/openshift-ansible#9601]
#### Description

https://github.com/openshift/openshift-ansible/pull/9407 introduced GlusterFS health checks into upgrade procedure from 3.9 to 3.10. However, the documentation explicitely states to downscale GlusterFS DaemonSet before the upgrade, so that cluster can not be healthy at that point of upgrade.

Is this a documentation or an upgrade playbook problem?

**Comment by lentzi90** [comment]
I think I figured out a way to get past the health check. When it is waiting for the health check to succeed, continue following the documentation by adding the label back to the node. After a while the pod will be healthy and the upgrade continues.

I'm not saying this is a good workaround, but it seems to work.
