### ISSUE TITLE
OKD 3.9 - Grafana Playbook fails to install due to SSL certs

### ISSUE THREAD

**Issue by CelsoSantos** [openshift/openshift-ansible#9642]
#### Description

When running the Grafana install playbook (openshift-grafana/config), the install errors with message `Failed to validate the SSL certificate for grafana-openshift-grafana.<mydomain>....`

##### Version
```
ansible --version:
ansible 2.6.2
  (...)
  python version = 2.7.5

git describe:
openshift-ansible-3.9.40-1-41-g4466348
```

##### Steps To Reproduce
1. ansible-playbook -i /etc/ansible/hosts playbooks/openshift-grafana/config.yaml -vvv

##### Expected Results
The playbook completes successfully

##### Observed Results
The playbook fails with message:
```
Failed to validate the SSL certificate for grafana-openshift-grafana.<mydomain>....
```

##### Additional Information

```
cat /etc/redhat-release:
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```

##### (More) Additional Information
Also ran the playbook upon finding [PR#8114](https://github.com/openshift/openshift-ansible/pull/8114/). This PR has been merged to `master` but seems to not be applied in branch `release-3.9`.
Applies changes manually, only to fail again, this time with the message:
```
forbidden: user \"system:anonymous"\ cannot post path \"/api/datasources\": User \"system:anonymous\" cannot \"post\" in \"/api/datasources\""
```

**Comment by vrutkovs** [comment]
I've hit this as well on self-signed cert setup - the playbook should skip cert validation when a new datasource is being created

**Comment by mrsiano** [comment]
hmm , but we still use validate_certs:false thats strange.
i'm afraid it something related to grafana or proxy..
