### ISSUE TITLE
containerized=true seems to be ignoted for 'Install node, clients, and conntrack packages' task

### ISSUE THREAD

**Issue by MrBones757** [openshift/openshift-ansible#9673]
#### Description

> Containerized install fails on CentOS 7 Core for version 3.11.
> RPM Packages for node and clients are attempted to install even when containerized: true is set

##### Version

Ansible Version
```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

Git Describe
```
openshift-ansible-3.11.0-0.19.0-2-g0e600533e
```

##### Steps To Reproduce
1. Deploy a cluster containing more than one host (this doesn't seem to affect standalone hosts?)
    In my case: 2 master, 2 etcd, 4 nodes (2 infra, 2 compute) and 1 lb
2. use this inventory file [<link>](https://gist.github.com/MrBones757/af774076b3ee30b0de9c9691739dd19c)

##### Expected Results
A containerized openshift cluster should install and use no RPMs for openshift components

##### Observed Results
Openshift-Ansible attempts to pull node and client RPMs and fails due to packages not being available

```
See Gist: <[error.txt](https://gist.github.com/MrBones757/af774076b3ee30b0de9c9691739dd19c)> 
```
##### Additional Information

I believe the error / behaviour is occurring here:
```
Line : 26, 27
https://github.com/openshift/openshift-ansible/blob/release-3.10/roles/openshift_node/tasks/main.yml 

Which Calls:
https://github.com/openshift/openshift-ansible/blob/release-3.10/roles/openshift_node/tasks/install.yml

In this task, it is only checking for an atomic host, and ignores the containerized param (or openshift_is_containerized internally)

I'm not 100% sure what line 14 (item['install'] | default(True) | bool) is supposed to achieve - there is no way for that to become false is there - seems like a redunded check - i could be missing something though.

Perhaps if not on an atomic host we want to only install conntrack if containerized is enabled?

Let me know if you need any additional info
```
OS: Centos 7 Core (Latest Version)
Ansible: Running AWX latest (1.0.7.2)
Inventory File: See Gist: <[config.yml](https://gist.github.com/MrBones757/af774076b3ee30b0de9c9691739dd19c)>
```

**Comment by vrutkovs** [comment]
Containerized mode has been removed -  see https://docs.openshift.com/container-platform/3.10/release_notes/ocp_3_10_release_notes.html#ocp-310-containerized-installation-removed

**Comment by MrBones757** [comment]
Ah - This explains a lot - thanks for that!
As far as testing using more up-to-date (pre-release) builds, what is the recommended way of doing this?
(CentOS Packages for 3.11 aren't available to my knowledge, though i could be expecting them to be in the wrong repo), i have noticed though that 3.11 docker images are build and published regularly.

**Comment by vrutkovs** [comment]
There are package built by CI - https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/.latest-rpms file would contain a link to the repos.

**Comment by MrBones757** [comment]
Excellent - thanks for your assistance - much appreciated
