### ISSUE TITLE
OKD 3.10 : production ready ?

### ISSUE THREAD

**Issue by orpot** [openshift/openshift-ansible#9689]
#### Description

OKD 3.10 seems not finished : 
* v3.10.0 images are not available on https://hub.docker.com/r/openshift/origin-metrics-cassandra/tags/ (it seems it was similar with v3.9.0 : https://github.com/openshift/origin-metrics/issues/423 ). Why not configure automated builds ?
* The `openshift-metrics/config.yml` install metrics in the `openshift-metrics` project, but the doc says it should be on `openshift-infra` : https://docs.okd.io/3.10/install_config/cluster_metrics.html#metrics-namespace.
* The `openshift-ansible` repo has many commits since 3.10 but the `origin-ansible` docker image is from two months ago : https://hub.docker.com/r/openshift/origin-ansible/tags/ : Is it normal ? Why not doing automated builds ?

How do you check your code quality before a release ? Don't you have a full test of a cluster, with at least base components like metrics and logging enabled ?
is 3.10 a stable version ? or just a pretext to rename origin to OKD ?

##### Version

https://hub.docker.com/r/openshift/origin-ansible/tags/ v3.10

**Comment by vrutkovs** [comment]
None of these issues are issues needed to be fixed in this repo

1. and 3. are handled by CD team internally, you can setup your own autobuild workflow to produce images.

2. This might be a documentation issue, please report a new issue if this breaks autoscaler
