### ISSUE TITLE
RFE: Upgrade non default named routers

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#969]
We only upgrade routers if they're named 'router'. Because we only recently started deploying routers automatically and we only do so when zone=infra nodes are provided it's likely that someone's router is named something else. We should consider upgrading all routers in the default name space or potentially all namespaces.

**Comment by detiber** [comment]
I would vote on all routers in the default namespace. I don't think we should be touching any routers in other namespaces (unless we have the user provide namespaces to do so for).

**Comment by detiber** [comment]
Also, we should probably verify that the router we are updating is using the default image and not a custom image as well, otherwise we could break their custom router.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
