### ISSUE TITLE
Upgrade from 3.7 to 3.9 fails if ovs-networkpolicy is used

### ISSUE THREAD

**Issue by hakanisaksson** [openshift/openshift-ansible#9694]
#### Description

Trying to upgrade our openshift 3.7 clusters using the playbook: 
`./openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade_control_plane.yml`

The only difference between a successful upgrade, and a failed upgrade is this single setting in the ansible inventory file:
`os_sdn_network_plugin_name=redhat/openshift-ovs-networkpolicy`
If the cluster is configured to use
`os_sdn_network_plugin_name=redhat/openshift-ovs-multitenant`
instead, the upgrade is successful. 

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
```
ansible 2.5.5
  config file = //ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

If you're operating from a **git clone**:

* The output of `git describe`
```
openshift-ansible-3.9.40-1-29-g95a7a39
```

Current v3.7 version before upgrade:
```
# oc version 
oc v3.7.2+cd74924-1
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ocp.mydomain.my
openshift v3.7.2+cd74924-1
kubernetes v1.7.6+a08f5eeb62
```

##### Steps To Reproduce
1. Install a v3.7 cluster using the latest openshift-ansible-3.7 release
2. Deploy an application that uses one or more NetworkPolicy.
3. Try to upgrade using latest openshift-ansible-3.9 release

##### Expected Results
The cluster should have been successfully upgraded to 3.9.

ansible.log at https://gist.github.com/hakanisaksson/b991c477b425d86ebcba9fb997ea9910

##### Observed Results
The upgrade playbook fails when it's waiting for the origin-node service to start again, after upgrading it to v.3.8.0 on the first master.

Notable error from /var/log/origin/node.log:
```
{ "date":"2018-08-16T09:08:58.364925+02:00", "service":"origin-node", "loglevel":"info", "message":"E0816 09:08:58.363101   96671 networkpolicy.go:130] Unable to query NetworkPolicies (networkpolicies.networking.k8s.io is forbidden: User \"system:node:ocp-master-01.mydomain.my\" cannot list networkpolicies.networking.k8s.io at the cluster scope: User \"system:node:ocp-master-01.mydomain.my\" cannot list all networkpolicies.networking.k8s.io in the cluster) - please ensure your nodes have access to view NetworkPolicy (eg, 'oc adm policy reconcile-cluster-roles')"}
```

For long output or logs, consider using a [gist](https://gist.github.com/)
See Ansible.log and node.log at
https://gist.github.com/hakanisaksson/b991c477b425d86ebcba9fb997ea9910

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version:
`Red Hat Enterprise Linux Server release 7.5 (Maipo)`

* Your inventory file (especially any non-standard configuration parameters)
See inventory.cfg at https://gist.github.com/hakanisaksson/b991c477b425d86ebcba9fb997ea9910

* Sample code, etc
The rpm state after failed upgrade:
```
# rpm -qa | grep origin
tuned-profiles-origin-node-3.8.0-1.el7.git.0.dd1558c.x86_64
origin-sdn-ovs-3.8.0-1.el7.git.0.dd1558c.x86_64
origin-excluder-3.9.0-1.el7.git.0.ba7faec.noarch
origin-clients-3.8.0-1.el7.git.0.dd1558c.x86_64
origin-node-3.8.0-1.el7.git.0.dd1558c.x86_64
origin-master-3.8.0-1.el7.git.0.dd1558c.x86_64
origin-docker-excluder-3.9.0-1.el7.git.0.ba7faec.noarch
origin-3.8.0-1.el7.git.0.dd1558c.x86_64
```

Node status after failed upgrade:
```
 oc get nodes
NAME                                     STATUS                        ROLES     AGE       VERSION
ocp-infra-01.mydomain.my    Ready                         <none>    3d        v1.7.6+a08f5eeb62
ocp-infra-02.mydomain.my    Ready                         <none>    3d        v1.7.6+a08f5eeb62
ocp-master-01.mydomain.my   NotReady,SchedulingDisabled   <none>    3d        v1.8.5+440f8d36da
ocp-master-02.mydomain.my   NotReady,SchedulingDisabled   <none>    3d        v1.8.5+440f8d36da
ocp-master-03.mydomain.my   NotReady,SchedulingDisabled   <none>    3d        v1.8.5+440f8d36da
ocp-worker-01.mydomain.my   Ready                         <none>    3d        v1.7.6+a08f5eeb62
ocp-worker-02.mydomain.my   Ready                         <none>    3d        v1.7.6+a08f5eeb62
```

Note, the suggested command from the node.log
```
oc adm policy reconcile-cluster-roles
```
does not make any difference, the origin-node will still not start properly.

**Comment by vrutkovs** [comment]
That sounds like an Origin issue. @danwinship any ideas if this issue is known?

**Comment by danwinship** [comment]
IIRC there is a problem with upgrading from old versions of 3.7 to 3.9, but if you first update to the latest 3.7 release, it will work

**Comment by hakanisaksson** [comment]
@danwinship Hi, and thank you for the response, but I don't think so, this is from the latest 3.7 release as far as I'm aware. The 3.7 cluster was installed using openshift-ansible-3.7.60-1.tar.gz (released 25days ago on https://github.com/openshift/openshift-ansible/releases) and latest rpms from http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin37/. The oc version is v3.7.2+cd74924-1.

**Comment by danwinship** [comment]
> The oc version is v3.7.2+cd74924-1.

oh... you're using Origin, not OCP. I have no idea then. Origin doesn't get many bugfixes.

**Comment by vrutkovs** [comment]
All that should go to https://github.com/openshift/origin issues anyway
