### ISSUE TITLE
v3.10 upgrade on atomic host fails on "Remove atomic-openshift-master package"

### ISSUE THREAD

**Issue by feld-ims** [openshift/openshift-ansible#9719]
#### Description

Upgrade from 3.9 > 3.10 fails repeatedly on task to remove atomic-openshift-master package

##### Version

```
ansible==2.6.3
openshift-ansible-3.10.34-1
```

##### Steps To Reproduce
1. Run `../playbooks/byo/openshift-cluster/upgrades/v3_10/upgrade.yml` playbook from the release-3.10 branch against Atomic hosts with OpenShift Origin 3.9.0 installed

##### Expected Results
Successful upgrade

##### Observed Results
Describe what is actually happening.

```
fatal: [openshift-master]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "name": "origin-master",
            "state": "absent",
            "values": []
        }
    },
    "msg": "missing required arguments: image, backend"
}
```

**Comment by vrutkovs** [comment]
#9697 should fix that, could you verify it does?

**Comment by feld-ims** [comment]
Confirmed - it does fix

**Comment by DanyC97** [comment]
can you please close the issue then @feld-ims ? thx
