### ISSUE TITLE
support --dry-run and --diff

### ISSUE THREAD

**Issue by ibotty** [openshift/openshift-ansible#972]
It would be great to automatically check whether there is something to be done (get a mail whenever it would change something).

I plan to tackle that myself after #808 lands.

**Comment by detiber** [comment]
@ibotty This one will be quite difficult, given that I don't believe the templates provide meaningful output (other than that the file will be changed, though I could be wrong) and we rely on quite a few command/shell tasks which will not provide meaningful output for --dry-run.

**Comment by ibotty** [comment]
Regarding the shell tasks, afaict there are two classes of shell tasks.
 * oc/oadm create/edit, etc: These might benefit from a module that
   checks whether something changed. I did something like that with some
   etcd keys for flannel, so I am sure that approach will work.
 * diagnostics, tarball copies, etc.: These might be hard indeed. I am
   positive, there is a possibility to do these with --check though.

Of course no many modules support a meaningful `--diff`. But for the
ones I care about, it might work.

**Comment by detiber** [comment]
> Regarding the shell tasks, afaict there are two classes of shell tasks.
> * oc/oadm create/edit, etc: These might benefit from a module that
   checks whether something changed. I did something like that with some
   etcd keys for flannel, so I am sure that approach will work.

I fully agree, long term we want to move a lot of that type of functionality into modules as opposed to command execution.

> * diagnostics, tarball copies, etc.: These might be hard indeed. I am
   positive, there is a possibility to do these with --check though.

Diagnostics shouldn't be too hard to run in check mode, really those should be pushed into a module of some sort as well.

As for tarball copies, the ones for transfering certificates are safe to skip in check case, I'm not sure about other cases though.

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit
