### ISSUE TITLE
support tags

### ISSUE THREAD

**Issue by ibotty** [openshift/openshift-ansible#973]
It would be great to restrict what happens with tags.

This would be great for debugging openshift-ansible itself as well.

**Comment by detiber** [comment]
@ibotty are you thinking of tags on the different playbooks? or further down into the roles as well? 

I love the idea, I just suspect that it'll be quite tricky to get right and to verify that task dependencies are kept along with the tagging.

**Comment by ibotty** [comment]
I used these only in a coarse sense, e.g. I want to run the master-nodes
certificates part, or only configure openshift-sdn.

I concur with your assessment regarding tags within roles. Most of the
time when I used tags on task level I forgot to add some `always_run`
annotations to some tasks.

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit
