### ISSUE TITLE
Validate openshift_hostname when defined reports The hostname false forxxx doesn't resolve to an IP address owned by this host.

### ISSUE THREAD

**Issue by guawazi-glitch** [openshift/openshift-ansible#9742]

**Comment by vrutkovs** [comment]
What's the output of `hostname -f` on `master.cfetsit.com` and `node1.cfetsit.com`? Do you run them on AWS/GCP/OpenStack?

**Comment by Kisen-Chin** [comment]
@vrutkovs Hi, 
the output is:
```
[support@node1 ~]$ hostname -f
node1

[support@master ~]$ hostname -f
master
```

These two servers are my company's. They are pure RHEL servers and nothing special.
