### ISSUE TITLE
High Availability Isn't Working

### ISSUE THREAD

**Issue by chenqifeng28** [openshift/openshift-ansible#9743]
#### Description

I have installed a multi-master OCP cluster, but I forgot to add the parameter to /etc/ansible/hosts, so the high availability of the master node is not working.
The parameters are as follows:

openshift_master_cluster_method=native
openshift_master_cluster_hostname=openshift.demo.com
openshift_master_cluster_public_hostname=openshift.demo.com

My server list is as follows:
lb.demo.com
master01.demo.com
master02.demo.com
master03.demo.com

Now I can only log into the ocp web console through master01. When I try to log into ocp's web console through master02 and master03, the page will automatically go to master01 to log in.

##### Version
[root@master kubernetes]# oc version
oc v3.9.31
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.test.com:8443
openshift v3.9.31
kubernetes v1.9.1+a0ce1bc657

Please put the following version information in the code block
indicated below.

[root@master kubernetes]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-68.gitdded712.el7.x86_64
 Go version:      go1.9.2
 Git commit:      dded712/1.13.1
 Built:           Tue Jun 12 18:30:09 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-68.gitdded712.el7.x86_64
 Go version:      go1.9.2
 Git commit:      dded712/1.13.1
 Built:           Tue Jun 12 18:30:09 2018
 OS/Arch:         linux/amd64
 Experimental:    false

My /etc/ansible/hosts as 

[OSEv3:children]
masters
nodes
etcd
lb

[OSEv3:vars]
ansible_ssh_user=root

#ansible_become=true

openshfit_node_kubelet_args={‘pods-per-core’: [’10’], ‘max-pods’: [‘250’], ‘image-gc-high-threshold’: [’90’], ‘image-gc-low-threshold’: [’80’]}

openshift_router_selector='region=infra'
openshift_registry_selector='region=infra'
openshift_hosted_router_replicas=2

openshift_deployment_type=openshift-enterprise
openshift_image_tag=v3.9.31
openshift_pkg_version=-3.9.31

openshift_clock_enabled=true

openshift_hosted_registry_cert_expire_days=3650
openshift_ca_cert_expire_days=3650
openshift_node_cert_expire_days=3650
openshift_master_cert_expire_days=3650
etcd_ca_default_days=3650

openshift_enable_unsupported_configurations=true
openshift_metrics_install_metrics=true
openshift_metrics_image_prefix=registry.demo.com/openshift3/
openshift_metrics_storage_kind=nfs
openshift_metrics_storage_access_modes=['ReadWriteOnce']
openshift_metrics_storage_host=registry.demo.com
openshift_metrics_storage_nfs_directory=/data/nfs/ocp39/
openshift_metrics_storage_volume_name=metrics
openshift_metrics_storage_volume_size=10Gi

openshift_logging_install_logging=true
openshift_logging_image_prefix=registry.demo.com/openshift3/
openshift_logging_storage_kind=nfs
openshift_logging_storage_access_modes=['ReadWriteOnce']
openshift_logging_storage_host=registry.demo.com
openshift_logging_storage_nfs_directory==/data/nfs/ocp39/
openshift_logging_storage_volume_name=logging
openshift_logging_storage_volume_size=10Gi

openshift_enable_service_catalog=true
openshift_service_catalog_image_prefix=registry.demo.com/openshift3/ose-
ansible_service_broker_image_prefix=registry.demo.com/openshift3/ose-
template_service_broker_prefix=registry.demo.com/openshift3/ose-
ansible_service_broker_etcd_image_prefix=registry.demo.com/rhel7/

openshift_cockpit_deployer_prefix='registry.demo.com/openshift3/'
openshift_cockpit_deployer_version='v3.9.31'

openshift_web_console_install=true
openshift_web_console_prefix=registry.demo.com/openshift3/ose-
openshift_web_console_version=v3.9.31

openshift_master_default_subdomain=apps.demo.com
os_sdn_network_plugin_name=redhat/openshift-ovs-subnet
os_firewall_use_firewalld=true

oreg_url=registry.demo.com/openshift3/ose-${component}:${version}
openshift_examples_modify_imagestreams=true
openshift_docker_additional_registries=registry.demo.com
openshift_docker_blocked_registries=docker.io,registry.access.redhat.com

openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_host=registry.demo.com
openshift_hosted_registry_storage_nfs_directory=/data/nfs/ocp39/
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=10Gi

openshift_disable_check=memory_availability,disk_availability

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

[masters]
master01.demo.com
master02.demo.com
master03.demo.com

[etcd]
master01.demo.com
master02.demo.com
master03.demo.com

[lb]
lb.demo.com

[nodes]
master[01:03].demo.com 
node01.demo.com openshift_node_labels="{'region': 'primary', 'zone': 'default'}" openshift_schedulable=true
node02.demo.com openshift_node_labels="{'region': 'primary', 'zone': 'default'}" openshift_schedulable=true
node03.demo.com openshift_node_labels="{'region': 'primary', 'zone': 'default'}" openshift_schedulable=true
infra01.demo.com openshift_node_labels="{'region': 'infra','router': 'yes', 'zone': 'default'}" openshift_schedulable=true
infra02.demo.com openshift_node_labels="{'region': 'infra','router': 'yes', 'zone': 'default'}" openshift_schedulable=true

##### Expected Results
Describe what you expected to happen.
Who can help me solve this problem? I hope that when I access the web console through open shift.demo.com, I can automatically transfer to one of the three master nodes.
```

**Comment by vrutkovs** [comment]
Does `openshift.demo.com` resolve to `lb.demo.com`? This is the address you should be using instead of particular masters

**Comment by benfairless** [comment]
Additionally, based on your inventory it looks like you are defining `openshift_master_cluster_public_hostname` and `openshift_master_cluster_hostname` with the same value.

In my experience this has caused issues with certificates. If you only need one hostname for both you should omit the `openshift_master_cluster_public_hostname` variable. You can read about this in issue #6971

**Comment by chenqifeng28** [comment]
@vrutkovs yes, the /etc/hosts as follows:
10.1.69.130 master01.demo.com
10.1.69.131 master02.demo.com
10.1.69.132 master03.demo.com
10.1.69.142 lb.demo.com
10.1.69.142 openshift.demo.com

**Comment by chenqifeng28** [comment]
@benfairless  Both parameters are described in this document（[
https://docs.openshift.com/container-platform/3.9/install_config/install/advanced_install.html#multi-masters-using-native-ha-ai]）

# Native high availbility cluster method with optional load balancer.
# If no lb group is defined installer assumes that a load balancer has
# been preconfigured. For installation the value of
# openshift_master_cluster_hostname must resolve to the load balancer
# or to one or all of the masters defined in the inventory if no load
# balancer is present.
openshift_master_cluster_method=native
openshift_master_cluster_hostname=openshift-internal.example.com
openshift_master_cluster_public_hostname=openshift-cluster.example.com

**Comment by chenqifeng28** [comment]
@benfairless Both parameters are described in this document（[
https://docs.openshift.com/container-platform/3.9/install_config/install/advanced_install.html#multi-masters-using-native-ha-ai]）

> 

#### Native high availbility cluster method with optional load balancer.
#### If no lb group is defined installer assumes that a load balancer has
#### been preconfigured. For installation the value of
#### openshift_master_cluster_hostname must resolve to the load balancer
#### or to one or all of the masters defined in the inventory if no load
#### balancer is present.
openshift_master_cluster_method=native
openshift_master_cluster_hostname=openshift-internal.example.com
openshift_master_cluster_public_hostname=openshift-cluster.example.com
