### ISSUE TITLE
Restart path in GlusterFS install error is wrong

### ISSUE THREAD

**Issue by rabem00** [openshift/openshift-ansible#9745]
#### Description
Error message i got:
GlusterFS Install           : In Progress (0:08:47)
        This phase can be restarted by running: playbooks/openshift-glusterfs/new_install.yml

This restart path is not correct it should be playbooks/openshift-glusterfs/**private**/new_install.yml

##### Version
Openshift ansible on 3.10.35-1
ansible 2.5.5

**Comment by vrutkovs** [comment]
You should not run playbooks from `private/`

@jarrpa seems the correct path is `playbooks/openshift-glusterfs/config.yml`, right?

**Comment by rabem00** [comment]
@vrutkovs - I know but the message is: phase can be restarted by running: playbooks/openshift-glusterfs/new_install.yml   . There is no such file in the mentioned path. There is a new_install.yml under private. So the message is wrong or the path wrong, i think its one or the other.

**Comment by jarrpa** [comment]
The correct path is whatever path you used to run it in the first place. I don't know how to change the message to reflect that, however.

**Comment by rabem00** [comment]
@jarrpa I don't think the error message has anything to do with starting path. I tried to install a 3.10 cluster and something went wrong with a heketie pod so the playbook openshift-glusterfs stopped. Everytime an ansible playbook stops it gives a resume (or restart) path that you can run. The message in this case was:

```
GlusterFS Install : In Progress (0:08:47)
This phase can be restarted by running: playbooks/openshift-glusterfs/new_install.yml
```

But if you run like the message is displaying then you get a could not be found error:
```
# ansible-playbook -i infra openshift-ansible-openshift-ansible-3.10.35-1/playbooks/openshift-glusterfs/new_install.yml
ERROR! the playbook: openshift-ansible-openshift-ansible-3.10.35-1/playbooks/openshift-glusterfs/new_install.yml could not be found
```

If you look in playbooks/openshift-glusterfs/private there is new_install.yml file. So my conclusion was that either the resume message is wrong or path mentioned is wrong.

**Comment by jarrpa** [comment]
I'm saying the resume message is wrong, and that the correct response would be to re-run whatever you wan initially. Although, since it failed in the GlusterFS role, you would need to run uninstall first, which presents something of a problem there.

**Comment by rabem00** [comment]
I already did another install, so my problem was already fixed. But i just created this issue so you guys/girls can fix the message in the code (if possible). So for me this one can be closed. Thx

**Comment by jarrpa** [comment]
Works for me! :)
