### ISSUE TITLE
openshift_master_audit_config with a path in /var/log is not working when upgrading to 3.10

### ISSUE THREAD

**Issue by jocelynthode** [openshift/openshift-ansible#9746]
#### Description

When specifiying an audit path residing in /var/log. You cannot upgrade to 3.10

##### Version
```
ansible 2.4.3.0
```

##### Steps To Reproduce
1. have an audit policy in your master-config.yaml with a file path to /var/log
2. Run `openshift-ansible/playbooks/openshift-master/openshift_node_group.yml` playbook

##### Expected Results
The upgrade should happen

##### Observed Results
The upgrade is stopped

```
{"msg": "A string value that appears to be a file path located outside of\n/etc/origin/master/, /var/lib/origin, /etc/origin/cloudprovider, /etc/origin/kubelet-plugins, /usr/libexec/kubernetes/kubelet-plugins has been found in /etc/origin/master/master-config.yaml.\nIn 3.10 and newer, all files needed by the master must reside inside of\nthose directories or a subdirectory or it will not be readable by the\nmaster process. Please migrate all files needed by the master into\none of /etc/origin/master/, /var/lib/origin, /etc/origin/cloudprovider, /etc/origin/kubelet-plugins, /usr/libexec/kubernetes/kubelet-plugins or a subdirectory and update your master configs before\nproceeding. The string found was: /var/log/openshift-audit.log\n***********************\nNOTE: the following items do not need to be migrated, they will be migrated\nfor you: oauthConfig.identityProviders"}

```

##### Additional Information

I would have expected this to continue working as the documentation here: https://docs.openshift.com/container-platform/3.10/install_config/master_node_configuration.html#master-node-config-audit-config  specifies this as an example:
```
auditConfig:
  auditFilePath: "/var/log/audit-ocp.log"
  enabled: true
  maximumFileRetentionDays: 10
  maximumFileSizeMegabytes: 10
  maximumRetainedFiles: 10
```

We should either change the documentation and add a warning for the auditFilePath or allow any path in the playbook.

Is there a workaround for these auditconfig in the meantime ?

**Comment by vrutkovs** [comment]
>The upgrade is stopped

What's the error message?

**Comment by jocelynthode** [comment]
@vrutkovs I have updated the main post with the error message.

as I said it seems to suggest it is not possible to put a path outside of the listed repositories. However the documentation does not seem to imply that.

If for you the documentation is wrong, I'll open a ticket on the documentation repository to fix it.

**Comment by vrutkovs** [comment]
Right, this is a docs bug - it should probably be `/var/lib/origin/log` then. Please file a new bugzilla ticket at https://bugzilla.redhat.com for Red Hat -> Openshift Container Platform, component: docs.

Thanks!
