### ISSUE TITLE
Check for GlusterFS cluster health

### ISSUE THREAD

**Issue by megian** [openshift/openshift-ansible#9763]
#### Description

The upgrade process does stop with the following error. First one or two node the "Check for GlusterFS cluster health" does work, but seams to loose the variable first_master_client_binary somewhere.

TASK [openshift_storage_glusterfs : Check for GlusterFS cluster health] *******************************************************************************************************************************************
Saturday 25 August 2018  09:29:54 +0000 (0:00:02.331)       0:34:47.699 ******* 
fatal: [node3]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'first_master_client_binary' is undefined\n\nThe error appears to have been in '/home/pi/openshift-ansible/roles/openshift_storage_glusterfs/tasks/cluster_health.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# lib_utils/library/glusterfs_check_containerized.py\n- name: Check for GlusterFS cluster health\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'first_master_client_binary' is undefined"}

##### Version

```
ansible 2.4.6.0
openshift-ansible-3.10.35-1-12-g1a87b9ddc
```

##### Steps To Reproduce
1. ansible-playbook playbooks/byo/openshift-cluster/upgrades/v3_10/upgrade.yml

##### Additional Information

```
CentOS Linux release 7.5.1804 (Core)
```

**Comment by masayoshi-louis** [comment]
Same problem

**Comment by megian** [comment]
Looks like something has been changed https://github.com/openshift/openshift-ansible/commit/6721c87447b76bcd509822aa928d58431673c68a

**Comment by michaelgugino** [comment]
@megian yes, this issue is resolved in each release branch that was affected.  It may take some time for the fix to be available via rpms.
