### ISSUE TITLE
OKD 3.10 setting oreg_url is not sufficient pod image still *sometimes* come from docker.io

### ISSUE THREAD

**Issue by dabelenda** [openshift/openshift-ansible#9774]
#### Description

After setting up docker image consolidation in Satellite by setting the ansible "oreg_url" variable.
I saw that *some* "pod" containers are still launched using docker.io/openshift/origin-pod:v.3.10.0 image. I just cannot find how to debug that since most are the infrastructure pods (SDN, OVS, origin-node etc) and some are not (a single daemonset AFAIK). This change in oreg_url is because before that I was only consolidating the RPM packages in satellite, but due to the change in installation mode, I need to consolidate also the images.

Reinstalling every single node is not impossible but really a pain... This is a test cluster, but prod has a lot of servers, all in "byo" mode (due to restrictions outside my control).

Every master and node was configured with the correct imageConfig.format.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
# ansible --version
ansible 2.6.2

# git describe
openshift-ansible-3.10.35-1-10-g6af2c72

```

##### Steps To Reproduce
1. set oreg_url to a consolidated registry
2. re-configure all nodes to use the new registry
3. rolling-reboot the nodes
4. check that every master-config.yaml containes proper imageConfig.format (no problem)
5. check that every node-config ConfigMap contains proper imageConfig.format (no problem)
6. check how each pod container was started using "docker ps | grep pod" (problem)

##### Expected Results
All pod image are the same and all taken from the consolidated source.

##### Observed Results
Some pod containers are started using the docker.io/openshift/origin-pod:v3.10.0 image and other not on the same node.

```
compute3# docker ps | grep pod
021665ce49ee        CONSOLIDATED_REGISTRY/pod:v3.10.0             "/usr/bin/pod"           About an hour ago   Up About an hour                        k8s_POD_router-10-ww2wv_default_06fe9086-a9d2-11e8-a252-005056ba62e9_0
9d6b81b064ed        CONSOLIDATED_REGISTRY/pod:v3.10.0             "/usr/bin/pod"           About an hour ago   Up About an hour                        k8s_POD_logging-fluentd-vsqcm_openshift-logging_f8351fcf-9fa6-11e8-b0d9-005056ba9782_1229
674ae3a53fad        CONSOLIDATED_REGISTRY/pod:v3.10.0             "/usr/bin/pod"           About an hour ago   Up About an hour                        k8s_POD_local-volume-provisioner-8csb6_local-storage_2843d3f8-fd25-11e7-836e-005056ba9782_1247
f558d3c3ddec        docker.io/openshift/origin-pod:v3.10.0        "/usr/bin/pod"           About an hour ago   Up About an hour                        k8s_POD_sync-rl9nv_openshift-node_ed128264-a79f-11e8-87b3-005056ba62e9_4
b913c53c5911        docker.io/openshift/origin-pod:v3.10.0        "/usr/bin/pod"           About an hour ago   Up About an hour                        k8s_POD_core-metrics-prometheus-node-exporter-f95b9_core-metrics_bade4383-21e1-11e8-836e-005056ba9782_24
039b1c74702f        docker.io/openshift/origin-pod:v3.10.0        "/usr/bin/pod"           About an hour ago   Up About an hour                        k8s_POD_sdn-8k52n_openshift-sdn_04f463d3-a78d-11e8-a510-005056ba62e9_4
8e744472298a        docker.io/openshift/origin-pod:v3.10.0        "/usr/bin/pod"           About an hour ago   Up About an hour                        k8s_POD_ovs-gzbw2_openshift-sdn_22342365-a79f-11e8-87b3-005056ba62e9_4
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* RHEL 7.5
* Registry is Satellite 6.3.X

**Comment by aland-zhang** [comment]
I also encountered the same problem.

**Comment by aland-zhang** [comment]
In the version openshift-ansible-openshift-ansible-3.10.41-1 ，The oreg_url parameter is already available

**Comment by dabelenda** [comment]
I am Still getting it with OpenShift 3.11 ...

**Comment by Snoopy696** [comment]
Hello, any updates on this ? It is a blocker on a corporate enviroments with Proxy.. I manage to change every endpoint in ansible to point to external docker registry so far, but no luck with origin-pod. 

During upgrade my etcd pod failes because it tries to ping docker repository(squid proxy blocks pings) and no luck with oreg_url variable. Any help would appreciated..
