### ISSUE TITLE
Installation link in Github description is broken, or at least misleading

### ISSUE THREAD

**Issue by ironfroggy** [openshift/openshift-ansible#9794]
The description at the top of the Github page for openshift/openshift-ansible includes the link https://install.openshift.com/ but the link, while not totally broken (it does not 404) just redirects to the main new domain https://www.okd.io/ with no clear indication where to continue to find any sort of installation instructions the original link would have linked to.

Is there a clear new location this link should be replaced with?

**Comment by aditya-konarde** [comment]
Should maybe point to : https://docs.okd.io/latest/install/running_install.html
