### ISSUE TITLE
Is it possible to upgrade origin 1.0.7 to 1.1 via ansible playbook?

### ISSUE THREAD

**Issue by ubreu** [openshift/openshift-ansible#981]
This document states that it should be possible:
https://docs.openshift.org/latest/install_config/upgrades.html#upgrade-playbook

However, that playbook does not exist on the master branch.

I am currently running:
openshift v1.0.7-2-gd775557-dirty
kubernetes v1.2.0-alpha.1-1107-g4c8e6f4
etcd 2.1.2

**Comment by abutcher** [comment]
Hey @ubreu, sorry it seems we need to update that doc. We recently updated the upgrade playbooks to separate them into minor and major upgrades for the releases so far. The playbook here should work for going from 1.0.7 to 1.1.1.

https://github.com/openshift/openshift-ansible/blob/master/playbooks/byo/openshift-cluster/upgrades/v3_0_to_v3_1/README.md

**Comment by abutcher** [comment]
@ubreu Documentation has been updated in the linked PR which will land in the nightly build. If you have any issues with the upgrade please re-open this issue or submit a new one. Thanks!

@twiest @brenton Please close

**Comment by ubreu** [comment]
@abutcher: Thanks for the pointer. I was able to run that playbook
