### ISSUE TITLE
docker registry log level hardcoded to debug

### ISSUE THREAD

**Issue by e-minguez** [openshift/openshift-ansible#9820]
https://github.com/openshift/openshift-ansible/blob/0835c31e3f52a77daa0fb1ef353401afb29baddb/roles/openshift_hosted/templates/registry_config.j2#L3

[Upstream](https://docs.docker.com/registry/configuration/#log) is configured by default to 'info' but it would be nice to have an ansible variable to be able to configure it (and default it to 'info')

**Comment by legionus** [comment]
@bparees that's why I asked how the stand was created in the BZ. The problem with the morning BZ is that the registry began to write more useful messages and by default it has the error loglevel in the config, but the installers themselves set the loglevel to debug. This is one of those places.

**Comment by legionus** [comment]
Sure! I already put my `lgtm`.
