### ISSUE TITLE
OKD 3.10 webconsole login error

### ISSUE THREAD

**Issue by Scisci75** [openshift/openshift-ansible#9830]
Hi, 
On inventory file I've setuped  htpasswd auth and defined a user "developer".
On terminal no problem to login and use the cluster.
On Web console am unable to login.

Error  
An error has occurred
Return to the console.

How to solve the problem?
Where can I found the errors log ?

Thanks
Mirko

**Comment by Scisci75** [comment]
I've increased the number of CPU and memory on the master nodes ( 4 CPU and 36 GB ) and now it's back to work.

**Comment by flyinghawkren** [comment]
I have the same issue. But my master nodes already has 8vCPU and 16GB memory.
