### ISSUE TITLE
Missing htpasswd file causes 3.10 install to fail because master api/controller cannot start.

### ISSUE THREAD

**Issue by whitingjr** [openshift/openshift-ansible#9833]
#### Description

 The installation fails to complete. This is due to the `master api` image not finding a required file  htpasswd.That causes the service not to start and the installation process fails.
This is for a single master and single compute node install on bare metal RHEL 7.5.

##### Version

Please put the following version information in the code block
indicated below.
```
# ansible --version
ansible 2.4.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

If you're operating from a **git clone**:
```
# git describe
openshift-ansible-3.10.37-1
```

##### Steps To Reproduce
1. Configure Ansible inventory with 1 master and 2 compute nodes
2. Run the prerequisites script
3. Run the install cluster script
```
ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/adhoc/uninstall.yml;ansible-playbook /home/benchuser/jwhiting/openshift-ansible/playbooks/prerequisites.yml ; rm -f nohup.out ; nohup ansible-playbook /home/benchuser/jwhiting/openshift-ansible/playbooks/deploy_cluster.yml -vvv &
```
##### Expected Results
The install to complete successfully.

##### Observed Results
The `master api` service cannot start without the `htpasswd` file. Dumping the log of the `master api` image shows a file is missing.

```
# docker logs -f --tail 10 k8s_api_master-api-server7_kube-system_5946c1f644096161a1242b3de0ee5875_3085
Invalid MasterConfig /etc/origin/master/master-config.yaml
  oauthConfig.identityProvider[0].provider.file: Invalid value: "/etc/origin/openshift-passwd": could not read file: stat /etc/origin/openshift-passwd: no such file or directory
#
```
Inspecting the logs for the `master controller` image shows the same missing file as well.
```
# docker logs -f --tail 10 k8s_controllers_master-controllers-benchserver7_kube-system_8e879171c85e221fb0a023e3f10ca276_3084
Invalid MasterConfig /etc/origin/master/master-config.yaml
  oauthConfig.identityProvider[0].provider.file: Invalid value: "/etc/origin/openshift-passwd": could not read file: stat /etc/origin/openshift-passwd: no such file or directory
#
```
Dropping into the `master api` image to double check the missing file shows the directory the file should be located in is missing
```
# docker run -it --entrypoint /bin/bash  registry.access.redhat.com/openshift3/ose-control-plane
Unable to find image 'registry.access.redhat.com/openshift3/ose-control-plane:latest' locally
Trying to pull repository registry.access.redhat.com/openshift3/ose-control-plane ... 
latest: Pulling from registry.access.redhat.com/openshift3/ose-control-plane
Digest: sha256:fb05ab7dad76f91201660824a5e88d4e17989fb2ef34ce0522eafd7604cf41f0
Status: Downloaded newer image for registry.access.redhat.com/openshift3/ose-control-plane:latest
[root@0f1f30e36bfd origin]# ls /etc/origin
ls: cannot access /etc/origin: No such file or directory
[root@0f1f30e36bfd origin]#
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

os version
```
# uname -a
Linux benchserver7 3.10.0-862.3.2.el7.x86_64 #1 SMP Tue May 15 18:22:15 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
```
inventory file
```
# This is the default ansible 'hosts' file.

[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
containerized=false
openshift_deployment_type=openshift-enterprise
debug_level=0
openshift_node_groups=[{'name': 'node-config-master', 'labels': ['node-role.kubernetes.io/master=true']}, {'name': 'node-config-infra', 'labels': ['node-role.kubernetes.io/infra=true',]}, {'name': 'node-config-compute', 'labels': ['node-role.kubernetes.io/compute=true'], 'edits': [{ 'key': 'kubeletArguments.pods-per-core','value': ['20']}]}]
openshift_master_cluster_hostname=server7
ansible_ssh_user=root
openshift_enable_service_catalog=false
disk_availability=false
openshift_disable_check=memory_availability,disk_availability
openshift_master_htpasswd_users={'admin': 'admin:$apr1$7BqGtoN6$4m5Si/xcm1UjRiO/lA6cL0'}

[masters]
server7.acme.com

[etcd]
server7.acme.com

[nodes]
server7.acme.com openshift_node_group_name='node-config-master'
#server5.acme.com openshift_node_group_name='node-config-infra'
server2.acme.com openshift_node_group_name='node-config-compute'
```

**Comment by vrutkovs** [comment]
>Dropping into the master api image to double check the missing file shows the directory the file should be located in is missing

That's a new container, it certainly doesn't have the config.

You'd need to run `master-exec api api` from root on the target host to enter API container

**Comment by whitingjr** [comment]
Ah yes, good point.
 However the container that was live at the time during the cluster install didn't have it either.
 I'll set up the Use Case for [configuring the cluster to use HTPasswd authentication](https://docs.openshift.com/container-platform/3.10/install_config/master_node_configuration.html#config-htpasswd) and try again.

**Comment by vrutkovs** [comment]
Oh, btw, did you run `prerequisites` playbook? I think its the one which should create the htpasswd file

**Comment by whitingjr** [comment]
Yes. I updated the issue details with the one line command I use to attempt cluster installs. Under steps to reproduce.

**Comment by whitingjr** [comment]
Getting the same missing file error message.
```
# docker logs -f --tail 10 k8s_api_master-api-benchserver7_kube-system_5946c1f644096161a1242b3de0ee5875_3085
Invalid MasterConfig /etc/origin/master/master-config.yaml
  oauthConfig.identityProvider[0].provider.file: Invalid value: "/etc/origin/openshift-passwd": could not read file: stat /etc/origin/openshift-passwd: no such file or directory
```

**Comment by vrutkovs** [comment]
Right, I guess there is no such file on the host (or in the container)?
Does setting `openshift_master_identity_providers` to htpasswd (see `hosts.example` for a sample) fixes that?

**Comment by whitingjr** [comment]
@vrutkovs I think my last comment has console output proving the file is not on the host. Also showing a file is present called `htpasswd`. Definitely not in the container either.
My inventory file has that property set with this value
`openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]`

**Comment by whitingjr** [comment]
@vrutkovs  I tested the combination of using `openshift_master_identity_providers` and `openshift_master_htpasswd_users` does not work. Still not finding `/etc/origin/openshift-passwd`

**Comment by Mikedu1988** [comment]
@whitingjr I think I have a worikaound for you. delete `openshift_master_identity_providers`  `openshift_master_htpasswd_users`  in inventory file, set up an "Allow all" cluster first.
After the cluster is up and runing, fallowing below steps:
[root@openshiftnode5~]# htpasswd -c /etc/origin/htpasswd user1
New password:
Re-type new password:
Adding password for user user1
#You 'll find a ftpasswd file generated under /etc/origin
[root@openshiftnode5 ~]# cat /etc/origin/htpasswd
user1:$apr1$KyAHGnXo$/dw9nhaTB8ubIVCQBjsT..
#then modify the master-config.yaml:
[root@openshift ~]# vim /etc/origin/master/master-config.yaml
identityProviders:
  - challenge: true
    login: true
    mappingMethod: claim
    name: my_provider
    provider:
      apiVersion: v1
      kind: HTPasswdPasswordIdentityProvider
      file: /etc/origin/htpasswd

#save and then restart master node
master-restart api
master-restart controllers
`
hope it helps

**Comment by whitingjr** [comment]
@vrutkovs @Mikedu1988 I solved this problem.
It seems the images from the 3.9 install previously on the machine were still being used. Which is why there was a disconnect between the file in the container image (3.10) and attempt to use the prior location (3.9). The path had changed in the version bump.

 This sequence of steps solved the problem.

1. uninstall
2. `# atomic storage reset`
3. per-requisits
4. cluster install

 Once the storage had been fully cleared the cluster install completed successfully.

**Comment by mtoddw** [comment]
I'm having a similar issue during upgrade to 3.10.  Our cluster has ldap identity provider and it's been in use since 3.3. The ca file in identity provider has had the same path since 3.3.  During 3.10 upgrade the master-api and master-controllers pods go into crashloopback with error that it can't find or stat the ca file, which is in /etc/pki/ca-trust/source/anchors/somefile-ca.crt.

The file is there but it seems the pod can't read it.  This causes the install/upgrade to fail.  If I edit all 3 masters /etc/origin/master-config.yaml file and change the path to /etc/origin/master/somefile-ca.crt  and run master-restart api across the masters, the api pods will start and the upgrade will continue or can be restarted, and will complete successfully.

I've tried changing path in our inventory file, setting openshit_master_ldap_ca_file var to diff path, etc... but they all still fail to update or change master-config.yaml and upgrade fails. only workaround is manually changing before upgrade. 

Any solution or other github issues around this?

**Comment by michaelgugino** [comment]
@mtoddw did you skip sanity_checks?  This should have been caught there.

Master pods cannot read anything outside of /etc/origin/master, so just update your configs and move your certs into that directory.  I think @vrutkovs created a patch to create them in that directory, not sure about existing users/upgrades.

**Comment by mtoddw** [comment]
@michaelgugino  - yes, it has passed sanity checks. I've only run the openshift_node_group_name.yml playbook to create the configmaps and the upgrade.yml playbook.

I seen the patch for 3.11 but don't believe it has been pushed to 3.10 yet.  

I figured out by trial and error, running the playbook, that the pods couldn't' read outside of /etc/origin/master, but wish it was documented in the release notes or upgrade guide.  

The playbooks don't seem to 'update/change' my cert path if i change it in my inventory file. I've tried changing existing line in provider section, removing that ca line and using openshfit_master_ldap_ca_file var but that doesn't modify my master-config either.  Does anyone know correct inventory file setting to update that?  If not i'll just write a pretask to move the certs and update the path.

Thanks

**Comment by michaelgugino** [comment]
@mtoddw looks like identity providers are excluded from that sanity check.  I know we migrate htpasswd auth for you, but I think the ldap certs were missed by oversight.

Upgrades don't make changes to many things, we don't update the master configs during upgrades except to add necessary configuration items for upgrade (eg, someThing was added in 3.11 and is necessary for 3.11 to actually work, we add just someThing).
