### ISSUE TITLE
Release 3.9 prerequisites error message point to a dead URL

### ISSUE THREAD

**Issue by zoobab** [openshift/openshift-ansible#9838]
#### Description

Release 3.9 prerequisites error message point to a dead URL:

```
$ sudo ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml
[...]
TASK [Evaluate groups - Fail if no etcd hosts group is defined] *****************************************************************************************************************************************************************************
Thursday 30 August 2018  13:38:11 +0000 (0:00:00.029)       0:00:00.386 *******
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Running etcd as an embedded service is no longer supported. If this is a new install please define an 'etcd' group with either one, three or five hosts. These hosts may be the same hosts as your masters. If this is an upgrade please see https://docs.openshift.com/container-platform/latest/install_config/upgrading/migrating_embedded_etcd.html for documentation on how to migrate from embedded to external etcd.\n"}
```

The link to the doc "https://docs.openshift.com/containerplatform/latest/install_config/upgrading/migrating_embedded_etcd.html" gives a 404.

##### Version

* The output of `git describe`
```
$ git describe
openshift-ansible-3.9.41-1-13-gc799ce2
```
I run it from the venv made out the requirements.txt

##### Steps To Reproduce
1. create the venv from requirements.txt, and activate it
2. run ```sudo ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml```

##### Expected Results

It might fail with the same error, but with an URL that does not give a 404.

**Comment by vrutkovs** [comment]
Right, that should be https://docs.openshift.com/container-platform/3.7/upgrading/migrating_embedded_etcd.html on 3.7+ versions

**Comment by DanyC97** [comment]
@vrutkovs no idea why this issue hasn't been closed too, you mind closing it manually? thank you !

**Comment by vrutkovs** [comment]
Sure
