### ISSUE TITLE
Origin Centos for release 3.11 binaries are not available

### ISSUE THREAD

**Issue by zoobab** [openshift/openshift-ansible#9875]
#### Description

Origin Centos for release 3.11 binaries are not available.

If I checkout the release-3.11 branch, and run the prerequesites ansible recipe, it fails to find origin-excluder for the 3.11 release.

Only up to 3.10 are available:

http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/

For example, for the origin-excluder package, it stops at 3.10:

```
origin-excluder-3.6.0-1.0.c4dd4cf.noarch.rpm | 2017-08-11 08:52 | 6.5K |  
origin-excluder-3.6.1-1.0.008f2d5.noarch.rpm | 2017-11-08 10:18 | 6.5K |  
origin-excluder-3.7.0-1.0.7ed6862.noarch.rpm | 2017-12-11 09:08 | 6.6K |  
origin-excluder-3.7.1-1.el7.git.0.0a2d6a1.noarch.rpm | 2018-03-19 09:08 | 6.6K |  
origin-excluder-3.7.1-2.el7.noarch.rpm | 2018-03-21 09:10 | 6.5K |  
origin-excluder-3.8.0-1.el7.git.0.dd1558c.noarch.rpm | 2018-04-25 22:55 | 6.6K |  
origin-excluder-3.9.0-1.el7.git.0.ba7faec.noarch.rpm | 2018-04-18 17:27 | 6.6K |  
origin-excluder-3.10.0-1.el7.git.0.0c4577e.noarch.rpm | 2018-08-14 09:02 | 4.3K |  
```

##### Version

```
openshift-ansible-3.11.0-0.25.0-16-g2b771e4
```

##### Steps To Reproduce
1. Checkout to release-3.11 branch
2. Run the prerequesites: ```ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml```

##### Expected Results

It fails to find the package:

```
TASK [openshift_excluder : Install docker excluder - yum] *****************************************************************************************************************************************************************
Monday 03 September 2018  08:29:15 +0000 (0:00:00.055)       0:00:25.348 ******
FAILED - RETRYING: Install docker excluder - yum (3 retries left).
FAILED - RETRYING: Install docker excluder - yum (2 retries left).
FAILED - RETRYING: Install docker excluder - yum (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'origin-docker-excluder-3.11**' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-docker-excluder-3.11**' found available, installed or updated"]}

PLAY RECAP ****************************************************************************************************************************************************************************************************************
localhost                  : ok=56   changed=4    unreachable=0    failed=1

```

##### Additional Information

* Your operating system and version: CentOS Linux release 7.5.1804 (Core)

**Comment by vrutkovs** [comment]
OKD 3.11 is not yet release, so CentOS won't build 3.11 packages just yet.

Latest packages are built by CI, https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/.latest-rpms would contain the base URL to the latest repos

**Comment by matihost** [comment]
OKD 3.11 has been released yesterday and  http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/ rpms not present

**Comment by DanyC97** [comment]
@matihost yes that is correct, it will appear for testing in next week or so at which point i'll send out an email to user/ dev mailing list asking for testers to step forwards and help with - hopefully more people will help this time vs last release.

**Comment by niiku** [comment]
Here's a link to subscribe to the mailing list: https://lists.openshift.redhat.com/openshiftmm/listinfo

**Comment by zhachaoy** [comment]
here same error

**Comment by flipkill1985** [comment]
How long does it take?

**Comment by Caes-Be** [comment]
Hello,
Yes is it possible to have a date? The installation is not possible from now. Or do you have a workaround ? 
Regards,

**Comment by DanyC97** [comment]
@flipkill1985 @Caes-Be as i said over in my previous comment and over the mailer, i'm working on it.

W/o going into too much details  in terms of what is blocking to release it, i'll just say that i am waiting myself for a dependency to be sorted so i can unblock myself.

**Comment by matihost** [comment]
Based on
http://lists.openshift.redhat.com/openshift-archives/users/2018-October/msg00059.html
I added ci repo to additional repos:
```
[OSEv3:vars]
(...)
openshift_additional_repos=[{'id': 'centos-okd-ci', 'name': 'centos-okd-ci', 'baseurl' :'https://rpms.svc.ci.openshift.org/openshift-origin-v3.11', 'gpgcheck' :'0', 'enabled' :'1'}]
```

And the installation is moving forward.

PS.
By official testing do you mean presence of v3.11 rpms in:
http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin/
enabled via `openshift_repos_enable_testing` flag 
(aka https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_repos/templates/CentOS-OpenShift-Origin.repo.j2#L11 )?

**Comment by flipkill1985** [comment]
@matihost Thank you worked for me i am now on 3.11

**Comment by Juancarlosmartin10** [comment]
@matihost this don`t solve my problem, I get the same issue

**Comment by lentzi90** [comment]
I think this issue should be re-opened since 3.11 is now released and the packages are still missing. This would (hopefully) avoid more duplicate issues and confusion.

**Comment by Juancarlosmartin10** [comment]
@matihost This worked for me too today :)
Thank you

**Comment by stratus-ss** [comment]
Goina bump this since its two weeks later and there are still no packages available. using @matihost solution allowed me to proceed in the prereq check but this is sub-optimal

**Comment by vrutkovs** [comment]
CentOS binaries are not an issue for openshift-ansible repo. 

In any case, the repo you should be using is https://cbs.centos.org/repos/paas7-openshift-origin311-testing/x86_64/os/ and collaborate with CentOS to make sure it makes into -released
