### ISSUE TITLE
Is it possible to dynamically get a list of all packages needed to install origin?

### ISSUE THREAD

**Issue by matt-deboer** [openshift/openshift-ansible#990]
This is more of a question than issue--is there any simple way to get a full manifest of the packages required as part of an os-origin install? 
The use case is to pre-package a partial private repository/mirror containing those packages for distribution inside a limited-egress environment.

**Comment by detiber** [comment]
I'm not aware of a way to get the list dynamically, but you can `git grep yum` from within a checkout of openshift-ansible to get a list of all the yum tasks in the playbooks/roles.

From there, naively I would attempt a yum install from a minimal install to gather the full list of packages needed to build up the private mirror.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
