### ISSUE TITLE
Custom labels openshift 3.10

### ISSUE THREAD

**Issue by freakssy** [openshift/openshift-ansible#9918]
Hello,
I tried to create a new nodes group from inventory like this:
`openshift_node_groups=[{'name': 'node-config-master', 'labels': ['node-role.kubernetes.io/master=true', 'zone=control', 'platform=ptf1', 'env=rct']}, {'name': 'node-config-glusterfs-infra', 'labels': ['node-role.kubernetes.io/compute=true', 'glustfers=true', 'zone=infra', 'platform=ptf1']}]`
 
But playbook prerequisites failed:
```
TASK [Validate openshift_node_groups and openshift_node_group_name] ****************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'unicode' object has no attribute 'get'
fatal: [oso-master-59a.admin.edelia.net]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```
ansible version : 2.5.1
python version : Python 2.7.5
redhat version: 7.5

Someone can help me please?

**Comment by gean-xyz** [comment]
Hey freakssy,

have you solved this problem?
had to fix it for myself, but when you see the link[0] below, you have to add the node-configs into the ansible yml file (/usr/share/ansible/openshift-ansible/roles/openshift_facts/defaults/main.yml) like:

`  - name: node-config-my-infra
    labels:
      - 'node-role.kubernetes.io/compute=true'
      - 'node-role.kubernetes.io/infra=true'
      - 'region=infra'
      - 'dc=dcXY'
    edits: []`

link[0]: https://docs.openshift.com/container-platform/3.10/install/configuring_inventory_file.html#configuring-inventory-node-group-definitions 

greets, gean
