### ISSUE TITLE
Install fails with error "Destination /etc/sysconfig/origin-node does not exist !"

### ISSUE THREAD

**Issue by phlogistonjohn** [openshift/openshift-ansible#9932]
#### Description

On a fairly clean CentOS system, running playbooks/deploy_cluster.yml fails with the error:
```
TASK [openshift_node_group : Update the sysconfig to group "node-config-master"] ****
Friday 31 August 2018  20:27:36 +0000 (0:00:00.532)       0:07:41.147 ********* 
fatal: [c1-m0.blr.fdopen.net]: FAILED! => {"changed": false, "msg": "Destination /etc/sysconfig/origin-node does not exist !", "rc": 257}
```

##### Version

```
# ansible --version
ansible 2.6.1
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

# git describe
openshift-ansible-3.10.43-1
```

OS: CentOS 7.5.1804

##### Steps To Reproduce

On fairly minimally installed CentOS VM:
* I clone the openshift-ansible repo
* git checkout  "openshift-ansible-3.10.43-1"
* run: ansible-playbook  -i ../inventory.ini  playbooks/prerequisites.yml
* run `ansible-playbook  -i ../inventory.ini  playbooks/deploy_cluster.yml`

##### Expected Results
This file is ignored if not needed, or created if needed.

##### Observed Results
Ansible playbook fials w/o much indication about how to resolve the problem.

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

This also failed on the same way on an older tag,  3.10.40, I think but I didn't record exactly what version it was before resetting the vm to a clean snapshot. I would have re-tested with master but it does not accept the older version of ansible on the centos install.

Inventory:
```
# cat ../inventory.ini

c1-m0.blr.fdopen.net openshift_node_group_name=node-config-master openshift_ip=192.168.90.218
c1-node0.blr.fdopen.net openshift_node_group_name=node-config-compute openshift_ip=192.168.90.236
c1-node1.blr.fdopen.net openshift_node_group_name=node-config-compute openshift_ip=192.168.90.225
c1-node2.blr.fdopen.net openshift_node_group_name=node-config-compute openshift_ip=192.168.90.137

[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
debug_level=2
containerized=true
openshift_deployment_type=origin
openshift_image_tag="v3.10"
openshift_release="v3.10"
package_version="v3.10"
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
# Needed for non-production deployments(?):
openshift_additional_repos=[{'id': 'openshift-origin-ci', 'name': 'makeitwork', 'baseurl': 'https://storage.googleapis.com/origin-ci-test/logs/test_branch_origin_extended_conformance_gce_310/20/artifacts/rpms', 'enabled': 1, 'gpgcheck': 0}]
openshift_check_min_host_memory_gb=2

[masters]
c1-m0.blr.fdopen.net

[etcd]
c1-m0.blr.fdopen.net

[nodes]
c1-node0.blr.fdopen.net
c1-node1.blr.fdopen.net
c1-node2.blr.fdopen.net

```

**Comment by glemsom** [comment]
Hi

afaik you need to define your masters and etcd servers under [nodes] too.
See here for examples: https://docs.okd.io/3.10/install/example_inventories.html

**Comment by holodragon** [comment]
Got the same error in my environment, and the ansible hosts was ok when I install 3.10.21.

env: OCP
version: 3.10.43

Inventory:
`
[OSEv3:children]
masters
nodes
etcd
nfs
new_nodes

[OSEv3:vars]

openshift_disable_check=disk_availability,docker_storage,package_version
openshift_metrics_install_metrics=true
openshift_enable_unsupported_configurations=True
openshift_metrics_storage_kind=nfs
openshift_metrics_storage_access_modes=['ReadWriteOnce']
openshift_metrics_storage_nfs_directory=/exports
openshift_metrics_storage_nfs_options='*(rw,root_squash)'
openshift_metrics_storage_volume_name=metrics
openshift_metrics_storage_volume_size=10Gi
openshift_cluster_monitoring_operator_install=true
openshift_cluster_monitoring_operator_node_selector={'operator': 'yes'}
openshift_master_default_subdomain=apps.example.com
openshift_logging_install_logging=true
os_sdn_network_plugin_name=redhat/openshift-ovs-networkpolicy
ansible_ssh_user=root
openshift_deployment_type=openshift-enterprise

[masters]
ocp-master.example.com openshift_node_group_name="node-config-master"

[etcd]
ocp-master.example.com openshift_node_group_name="node-config-master"

[nodes]
ocp-master.example.com openshift_node_group_name="node-config-master"
ocp-infra1.example.com openshift_node_group_name="node-config-infra"
ocp-app1.example.com openshift_node_group_name="node-config-compute"
ocp-app2.example.com openshift_node_group_name="node-config-compute"
ocp-app3.example.com openshift_node_group_name="node-config-compute"
`

**Comment by phlogistonjohn** [comment]
@glemsom your suggestion was able to get me past that particular error. Thanks!

However, much like @holodragon I too am pretty sure I didn't always need to do this.

IMO, the playbooks (at least playbooks/prerequisites.yml) ought to discover and protect against common misconfigurations. If its required that all masters also be listed in nodes I think the playbooks should check for that.

**Comment by sc68cal** [comment]
> ought to discover and protect against common misconfigurations. If its required that all masters also be listed in nodes I think the playbooks should check for that. 

Agreed. I ran into this same issue where I had only listed a host in `[masters]` and not nodes, and the `roles/openshift_node_group/tasks/bootstrap.yml` tasks were failing because `/etc/origin/node` directory was not present on the master

**Comment by Th3G4mbl3r** [comment]
i can confirm that this issue exists in 3.11 install as well. If the master node is not listed in the nodes section, the prerequisites check clears successfully but fails during deploy-cluster with error message  "Destination /etc/sysconfig/origin-node does not exist !". This should ideally be detected by prerequisites check or automatically handled to include all nodes declared in the various needed under nodes section as well.

**Comment by ocontant** [comment]
I ran in the same issue. Definitely it should be catched by prerequirements.
