### ISSUE TITLE
Ansible should perform a check if its using the correct project/namespace when perform ing operations against api

### ISSUE THREAD

**Issue by ivanthelad** [openshift/openshift-ansible#994]
Hi, 
it can happen when running the ansible installer a second time that the user's config  (root) on the target master has switch to another project. This results in the ansible install reporting that it cannot find the kubernetes project. 

the installer could 
- Perform a check.
- Switch to project default 
- Execute the command on the default namespace

**Comment by jkroepke** [comment]
This error happens, if I'm not in the default namespace (oc project returns a custom project)

```
GATHERING FACTS ***************************************************************
ok: [master1.example.com]

TASK: [Get master service ip] *************************************************
failed: [ose-master1.example.com] => {"changed": true, "cmd": ["oc", "get", "-o", "template", "svc", "kubernetes", "--template={#.spec.clusterIP#}"], "delta": "0:00:00.273028", "end": "2015-11-26 11:45:44.374584", "rc": 1, "start": "2015-11-26 11:45:44.101556", "warnings": []}
stderr: Error from server: services "kubernetes" not found

FATAL: all hosts have already failed -- aborting
```

**Comment by abutcher** [comment]
Thanks! PR #985 submitted yesterday for this issue.

**Comment by tbielawa** [comment]
we use the admin.kubeconfig whenever possible now.
