### ISSUE TITLE
Question:  how to find nightly build repos  or origin/okd?

### ISSUE THREAD

**Issue by debianmaster** [openshift/openshift-ansible#9944]
#### Description

Where can i get nightly or  releases like (https://github.com/openshift/openshift-ansible/releases/tag/openshift-ansible-3.11.0-0.28.0)    repos ?

i'd like to try installing cluster from these temporary releases.

**Comment by vrutkovs** [comment]
`curl -q https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/.latest-rpms` will return the baseurl for the latest built RPMs
