### ISSUE TITLE
Metrics Installation on v3.10 Fails

### ISSUE THREAD

**Issue by ceagan** [openshift/openshift-ansible#9948]
#### Description

Docker Hub is missing v3.10.0 images for metrics installation and causes the installation of metrics on OpenShift Origin v3.10 to fail. 

##### Version

```
ansible 2.4.6.0
openshift-ansible-3.10.41-1-40-g06b17f7
```

##### Steps To Reproduce
1. Run Metrics install `ansible-playbook ~/openshift-ansible/playbooks/openshift-metrics/config.yml -vvv`

##### Expected Results
A successful install of the Metrics feature.

##### Observed Results
Metrics feature fails to deploy because it is unable to load the referenced image files.

##### Additional Information
I tried to workaround the issue by specifying the image files in the Ansible inventory file explicitly. There are no official v3.10.0 images available on Docker Hub, so I tried the rc.0 images instead. Two of the images below are commented out because projects do not exist for these on Docker Hub.

Unfortunately, this did not work, so I backed out to v3.9 of the Metrics for now.

```
# Version 3.10.0 is missing from Docker Hub
openshift_metrics_cassandra_image=openshift/origin-metrics-cassandra:v3.10.0-rc.0
#openshift_metrics_hawkular_agent_image=openshift/origin-metrics-hawkular-openshift-agent:v3.10.0-rc.0
openshift_metrics_hawkular_metrics_image=openshift/origin-metrics-hawkular-metrics:v3.10.0-rc.0
#openshift_metrics_schema_installer_image=openshift/origin-metrics-schema-installer:v3.10.0-rc.0
openshift_metrics_heapster_image=openshift/origin-metrics-heapster:v3.10.0-rc.0
```

**Comment by creiche** [comment]
Same issue with logging as well.  All images point to 3.10.0 but there is only v3.10 or v3.10.0-rc.0

**Comment by pat2man** [comment]
This is an issue with the metrics project: https://github.com/openshift/origin-metrics/issues/429
