### ISSUE TITLE
openshift_use_crio should be per node_group - not local.

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#9966]
#### Description

Since 3.10 you can only define `openshift_use_crio` per cluster, since all node_groups all evaluates on the 1st master. 

If you install a new node with `openshift_use_crio=true` while the first master has `openshift_use_crio=false` the CRI-O related settings in the node config gets overridden von from master api.

Like labels and edits please add a third parameter for defining the runtime.

Adding the CRI-O params via edits are not future safe in my eyes.

**Comment by michaelgugino** [comment]
@jkroepke thanks for the feedback.  We also realized this issue when trying to deploy a mixed cluster (some nodes with crio, some without).  We have added additional default node groups such as 'node-config-master-crio'  Basically, any existing node group just append '-crio' if you're using the latest of the 3.10 branch.

**Comment by jkroepke** [comment]
@michaelgugino Nice! To do you have commit/PR for me?

Its backported to 3.10 ?

**Comment by michaelgugino** [comment]
@jkroepke oops, looks like I spoke too soon.  This is only fixed in 3.11 and master ATM. https://github.com/openshift/openshift-ansible/pull/9732

We'll try to get the backport out soon, but in the mean time you can reference that PR as a starting point.

**Comment by jkroepke** [comment]
@michaelgugino Since I'm working with production environments unreleased versions are invisible for me ;-)

**Comment by michaelgugino** [comment]
@jkroepke I understand.  I'll update this issue when we get the patch cut.

**Comment by michaelgugino** [comment]
@jkroepke I believe you need to set openshift_use_crio for any groups/hosts you want to use crio, yes.  It does seem a little redundant, but openshift_use_crio will actually drive the installation of crio itself, whereas the openshift_node_group_name reflects the configuration of the kubelet/node.
